"""scripts.platformkit.proof_nba.totals_pace_efficiency — sharper NBA totals via pace x efficiency.

W134 showed the raw EW points model is UNDER-dispersed. Scoring is GENERATED by
pace x efficiency: total = pace/100 * (home_ortg + away_ortg) (exact, verified). Pace is
very STABLE team-to-team (std 5.3) while efficiency is noisier (std 11.9), so modelling the
two SEPARATELY — EW pace + EW offensive/defensive rating, leak-free — should yield a
SHARPER (lower-residual-sigma) total predictor than predicting points directly.

This builds that decomposed model and A/Bs it against the raw points model (reusing
totals_calibration), both with the same leak-free dispersion recalibration, on the same
held-out split. The WINNER is the lower residual sigma at equal-or-better ECE — a strictly
better forecaster (goal: the best predictions).

INVARIANTS: never edit src/ or kernel/; <=300 LOC.
Run: python -m scripts.platformkit.proof_nba.totals_pace_efficiency
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np

_REPO = Path(__file__).resolve().parents[3]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from scripts.platformkit.proof_nba.totals_calibration import (  # noqa: E402
    _LINES, _ece, _load, _phi, _walk_forward,
)

_ALPHA = 0.05
_INIT_PACE = 100.6
_INIT_RTG = 113.4


def _walk_forward_pace_eff(df) -> np.ndarray:
    """Leak-free predicted total = pace/100 * (exp_home_ortg + exp_away_ortg)."""
    off: Dict[str, float] = {}
    deff: Dict[str, float] = {}
    pace: Dict[str, float] = {}
    pred = np.empty(len(df))
    h = df["home_team"].to_numpy(); a = df["away_team"].to_numpy()
    ho = df["home_ortg"].to_numpy(float); ao = df["away_ortg"].to_numpy(float)
    pc = df["pace"].to_numpy(float)
    for i in range(len(df)):
        ht, at = str(h[i]), str(a[i])
        for t in (ht, at):
            off.setdefault(t, _INIT_RTG); deff.setdefault(t, _INIT_RTG); pace.setdefault(t, _INIT_PACE)
        pace_pred = 0.5 * (pace[ht] + pace[at])
        exp_h = 0.5 * (off[ht] + deff[at])          # home offence vs away defence
        exp_a = 0.5 * (off[at] + deff[ht])
        pred[i] = pace_pred / 100.0 * (exp_h + exp_a)
        # update AFTER snapshot (leak-free): this game's realized ortg = pts/poss*100
        off[ht] += _ALPHA * (ho[i] - off[ht]); deff[ht] += _ALPHA * (ao[i] - deff[ht])
        off[at] += _ALPHA * (ao[i] - off[at]); deff[at] += _ALPHA * (ho[i] - deff[at])
        pace[ht] += _ALPHA * (pc[i] - pace[ht]); pace[at] += _ALPHA * (pc[i] - pace[at])
    return pred


def _eval(pred: np.ndarray, total: np.ndarray, mid: int) -> Dict:
    """Dispersion-recalibrate (leak-free, first half) then score held-out ECE/Brier/sigma."""
    b, a = np.polyfit(pred[:mid], total[:mid], 1)
    pred_c = a + b * pred
    sigma = float(np.std(total[:mid] - pred_c[:mid]))
    te = slice(mid, len(total))
    pc, tt = pred_c[te], total[te]
    all_p: List[float] = []; all_y: List[float] = []
    for ln in _LINES:
        p_over = np.array([1.0 - _phi((ln - pt) / sigma) for pt in pc])
        y = (tt > ln).astype(float)
        all_p.extend(p_over.tolist()); all_y.extend(y.tolist())
    ap_, ay_ = np.array(all_p), np.array(all_y)
    return {"sigma": round(sigma, 2), "ece": round(_ece(ap_, ay_), 4),
            "brier": round(float(np.mean((ap_ - ay_) ** 2)), 4),
            "slope_b": round(float(b), 3)}


def run() -> Dict:
    df = _load()
    total = df["total"].to_numpy(float)
    mid = len(df) // 2
    raw = _eval(_walk_forward(df), total, mid)            # W134 points model
    pe = _eval(_walk_forward_pace_eff(df), total, mid)    # pace x efficiency model
    sharper = pe["sigma"] < raw["sigma"] - 0.05
    better_ece = pe["ece"] <= raw["ece"] + 0.002
    return {
        "n_games": len(df), "n_holdout": len(df) - mid,
        "raw_points_model": raw, "pace_efficiency_model": pe,
        "sigma_gain": round(raw["sigma"] - pe["sigma"], 2),
        "verdict": (f"pace x efficiency is SHARPER (sigma {raw['sigma']} -> {pe['sigma']}) "
                    f"at {'equal/better' if better_ece else 'worse'} ECE "
                    f"({raw['ece']} -> {pe['ece']}) — a better totals forecaster"
                    if sharper and better_ece else
                    f"pace x efficiency NOT clearly better (sigma {raw['sigma']} -> {pe['sigma']}, "
                    f"ECE {raw['ece']} -> {pe['ece']}); raw points model retained"),
        "note": "Sharper + well-calibrated = a better predictor. Goal: the best predictions.",
    }


def _main() -> int:
    rep = run()
    print(f"=== NBA Totals: pace x efficiency vs raw points (n={rep['n_games']}, "
          f"holdout={rep['n_holdout']}) ===")
    for name in ("raw_points_model", "pace_efficiency_model"):
        m = rep[name]
        print(f"{name:>22}: sigma={m['sigma']:>6}  ECE={m['ece']:>7}  Brier={m['brier']:>7}  "
              f"recal_b={m['slope_b']}")
    print(f"\nsigma gain (lower=sharper): {rep['sigma_gain']:+}")
    print(f"VERDICT: {rep['verdict']}")
    print(rep["note"])
    return 0


if __name__ == "__main__":
    sys.exit(_main())
