"""Soccer / AdaptabilityVersatility concept-node spec.

Person-free. Descriptive only. Markets are efficient.
"""
from __future__ import annotations

SPORT = "Soccer"
FAMILY = "AdaptabilityVersatility"

CONCEPTS: list[dict] = [
    {
        "slug": "multi_position_player_deployment",
        "title": "Multi-Position Player Deployment",
        "summary": "Players fielded across two or more distinct roles within a season provide tactical optionality without system changes, measured by positional-minutes entropy and per-90 output stability across roles.",
        "stat_signature": "Shannon entropy of positional-minutes >=1.0 bits (each of two roles >=25 % of minutes); per-90 key-metric CV across roles <0.25.",
        "mechanism": "Multi-role players let coaches exploit opponent shape mismatches while preserving collective spacing, introducing individual unpredictability within a stable structural template.",
        "conditions": "Most visible in congested fixture schedules, during positional injuries, or against opponents with a strongly asymmetric defensive block.",
        "magnitude": "Squads with two or more high-entropy deployers average roughly 0.3 to 0.5 additional distinct formation variants per match versus positionally rigid squads.",
        "links": ["inverted_fullback_dual_role", "box_to_box_phase_versatility", "press_role_assignment_fluidity", "positional_interchange_rotations"],
    },
    {
        "slug": "inverted_fullback_dual_role",
        "title": "Inverted-Fullback Dual Role",
        "summary": "Fullbacks who tuck into central midfield in possession and recover to wide defensive positions out of possession create build-up numerical overloads while maintaining flank coverage when defending.",
        "stat_signature": "In-possession central-zone touch share >40 %; out-of-possession wide-zone defensive-action share >50 %; average in-possession x-coordinate within 5 m of the central axis.",
        "mechanism": "Occupying the half-space in build-up pins the opposing winger defensively, freeing the wide attacker to invert and allowing the central midfield to push higher.",
        "conditions": "Most effective against a mid-block that leaves the half-space unguarded and requires a wide attacker willing to hold width or drift inside.",
        "magnitude": "Sides deploying inverted fullbacks typically register 8 to 12 additional progressive carries per 90 through the half-space versus conventional-fullback systems.",
        "links": ["wide_to_central_creative_shift", "three_at_back_to_four_morphing", "auxiliary_winger_fullback_hybrid", "ball_playing_center_back_progression"],
    },
    {
        "slug": "formation_flexibility_within_match",
        "title": "In-Match Formation Flexibility",
        "summary": "Sides that shift base shape phase-by-phase within a match introduce structural unpredictability, quantified by the count of distinct defensive-block shapes per match and the build-up-to-settled reconfiguration rate.",
        "stat_signature": ">=2 distinct defensive-block shapes detected per match via defender-line clustering; build-up median defender count differs from settled-defense median by >=0.8 players.",
        "mechanism": "Shape-switching forces opponents to re-identify threats in real time, disrupting pre-planned pressing triggers and man-marking assignments and opening transitional gaps.",
        "conditions": "Emerges when protecting a lead while retaining possession threat, or when countering a side with a single predictable pressing scheme.",
        "magnitude": "Teams with high within-match shape variance concede roughly 15 to 20 % fewer successful opponent press completions versus shape-rigid sides.",
        "links": ["three_at_back_to_four_morphing", "compact_to_expansive_block_adaptation", "press_role_assignment_fluidity", "dual_pivot_role_rotation"],
    },
    {
        "slug": "false_nine_dropping_role",
        "title": "False-Nine Dropping Role",
        "summary": "Center-forwards who vacate the penalty area to receive between the lines blur the striker-midfield boundary, disrupting center-back tracking decisions and creating space for late-arriving runners.",
        "stat_signature": "Average reception height <28 m from goal (versus a reference-striker baseline of ~18 m); half-space and central-channel touch share >55 %; box touch share <20 %.",
        "mechanism": "Center-backs face a tracking dilemma: follow the dropping forward and vacate depth, or hold and concede free possession in central dangerous zones; either choice creates exploitable gaps.",
        "conditions": "Most disruptive against a high offside trap or a back four whose midfield screen prioritizes ball-side compactness over tracking runs.",
        "magnitude": "False-nine systems typically generate 2 to 4 additional expected-goal-quality chances per 90 in the zone between the opposition midfield and defensive lines.",
        "links": ["positional_interchange_rotations", "wide_to_central_creative_shift", "creator_to_finisher_role_swap", "two_striker_role_specialization"],
    },
    {
        "slug": "box_to_box_phase_versatility",
        "title": "Box-to-Box Phase Versatility",
        "summary": "Central midfielders who contribute in defensive recovery and final-third arrival within the same match provide structural continuity across phases without requiring positional substitutions.",
        "stat_signature": "Defensive actions in own third >=3.0 per 90 and opposition-box touches >=1.5 per 90 simultaneously; combined phase-presence index above the 70th position percentile.",
        "mechanism": "High vertical range forces opponents to commit an extra defensive resource to tracking forward runs, reducing coverage density in wide areas.",
        "conditions": "Most impactful in open, transition-heavy matches where the midfield block is frequently bypassed and vertical space opens behind a disorganized shape.",
        "magnitude": "Teams anchored by a high-range midfielder average approximately 1.2 to 1.8 more late-arrival shots per match versus those relying on positionally static central roles.",
        "links": ["dual_pivot_role_rotation", "midfield_to_attack_late_arrival_versatility", "defensive_to_offensive_transition_role", "multi_position_player_deployment"],
    },
    {
        "slug": "wide_to_central_creative_shift",
        "title": "Wide-to-Central Creative Shift",
        "summary": "Wingers who drift inside to create from central zones while a fullback provides the wide outlet shift chance-creation origin toward higher-probability shooting corridors.",
        "stat_signature": "Half-space reception share >45 %; chance-creation origin-point spatial entropy >1.6 bits; correlation between winger central drift and fullback overlap rate >=0.55.",
        "mechanism": "Central drifts generate direct shooting lanes, stretch the opposition's narrow block laterally, and force the fullback marker to choose between tracking inside or holding the line.",
        "conditions": "Most effective against a flat back four reluctant to follow wide players centrally, leaving the half-space unguarded.",
        "magnitude": "Inward-drifting wingers generate expected assists roughly 0.04 to 0.07 per 90 higher than purely wide counterparts operating from the touchline.",
        "links": ["inverted_fullback_dual_role", "false_nine_dropping_role", "positional_interchange_rotations", "auxiliary_winger_fullback_hybrid"],
    },
    {
        "slug": "dual_pivot_role_rotation",
        "title": "Dual-Pivot Role Rotation",
        "summary": "Double-pivot pairs that alternate the deeper screening and the progressing role possession-by-possession prevent opponents from pre-assigning a press trigger to a single midfielder.",
        "stat_signature": "Within-pair role direction switches in >=40 % of sequential possessions; game-state correlation of role-swap frequency r >=0.30.",
        "mechanism": "Rotating responsibilities make the higher pivot a moving target for the press, continuously relocating the release valve and forcing the opponent to adjust its press shape mid-sequence.",
        "conditions": "Most pronounced against high-press systems that assign one presser per pivot and in matches where the score line incentivizes aggressive pressing.",
        "magnitude": "Rotating-pivot sides complete approximately 8 to 12 % more progressive passes per 90 under high-press conditions versus static-pivot configurations.",
        "links": ["box_to_box_phase_versatility", "formation_flexibility_within_match", "press_role_assignment_fluidity", "ball_playing_center_back_progression"],
    },
    {
        "slug": "three_at_back_to_four_morphing",
        "title": "Three-at-Back to Four Morphing",
        "summary": "Defenses that convert between a back three out of possession and a back four in build-up via a dropping midfielder or splitting wide center-back create numerical instability in the opponent's pressing map.",
        "stat_signature": "Build-up defender-count distribution bimodal at 3 and 4 with each mode covering >=30 % of build-up sequences; morph frequency >=4 per match.",
        "mechanism": "The shape morph reassigns pressing responsibilities mid-build-up, forcing opponent press recalculation and often leaving a free player in central progression lanes.",
        "conditions": "Activated against a front-two or front-three press when the side needs a numerical advantage in the first line of build-up.",
        "magnitude": "Sides with high morphing frequency reduce successful opposition press completions by roughly 12 to 18 % versus shape-static equivalents.",
        "links": ["formation_flexibility_within_match", "inverted_fullback_dual_role", "ball_playing_center_back_progression", "wing_back_dual_phase_workload"],
    },
    {
        "slug": "positional_interchange_rotations",
        "title": "Positional Interchange Rotations",
        "summary": "Front-line units whose attackers rotate positions fluidly disrupt zonal and man-marking schemes by decoupling nominal role from occupied zone.",
        "stat_signature": "Attacker average-position overlap index >0.35; heat-map cross-correlation between nominal role and occupied zone <0.55; rotation events >=6 per 90.",
        "mechanism": "Interchange overloads one zone transiently, drawing defensive resources, before the ball is switched to the vacated area for a late-arriving runner.",
        "conditions": "Most disruptive against rigid zonal blocks and sides that rely on man-marking assignments rather than spatial coverage principles.",
        "magnitude": "High-interchange front lines produce 0.08 to 0.12 additional expected goals per 90 from positional-switch-enabled chances versus positionally static front lines.",
        "links": ["false_nine_dropping_role", "wide_to_central_creative_shift", "two_striker_role_specialization", "creator_to_finisher_role_swap"],
    },
    {
        "slug": "defensive_to_offensive_transition_role",
        "title": "Defensive-to-Offensive Transition Role",
        "summary": "Players assigned a deep defensive task who immediately become forward outlets on regain combine defensive coverage with offensive initiation, exploiting opponent disorganization in the first seconds after a turnover.",
        "stat_signature": "Recovery actions per 90 >=4.0; progressive carries within 5 s of possession change >=1.2 per 90; carrier-to-progressive transition rate after own recovery >=0.30.",
        "mechanism": "Immediate forward carry after a regain catches opponents in transition before the defensive shape is recovered, converting positional advantage into a direct attacking threat.",
        "conditions": "Most valuable against sides that commit many players forward and are slow to reorganize, amplifying the value of winning the ball in midfield zones.",
        "magnitude": "Each additional 0.5 progressive carries per 90 in the transition window is associated with roughly 0.03 to 0.05 more expected goals from counterattack sequences.",
        "links": ["box_to_box_phase_versatility", "press_role_assignment_fluidity", "dual_pivot_role_rotation", "compact_to_expansive_block_adaptation"],
    },
    {
        "slug": "auxiliary_winger_fullback_hybrid",
        "title": "Auxiliary Winger-Fullback Hybrid",
        "summary": "Wide players asked to alternate between an advanced winger line and a defensive fullback line by phase show a bimodal vertical-position distribution, combining offensive width with flank defensive coverage.",
        "stat_signature": "Bimodal vertical-position distribution with attacking-third mode >=35 % and defensive-third mode >=25 % of positional observations; defensive-third recovery share >=2.5 per 90.",
        "mechanism": "Phase-switching binds the opposing wide player to a consistent defensive responsibility while also threatening the flank offensively, preventing the opponent from overloading that side.",
        "conditions": "Emerges in pressing systems that require wide press-participation and in transitional styles that exploit wide regain-to-carry sequences.",
        "magnitude": "Wide hybrids combine roughly 60 to 70 % of the defensive coverage of a fullback with 55 to 65 % of the attacking contribution of a winger within the same role.",
        "links": ["inverted_fullback_dual_role", "wing_back_dual_phase_workload", "wide_to_central_creative_shift", "multi_position_player_deployment"],
    },
    {
        "slug": "ball_playing_center_back_progression",
        "title": "Ball-Playing Center-Back Progression",
        "summary": "Center-backs who step into midfield to progress play temporarily act as an extra pivot, overloading the first defensive line and generating line-breaking pass angles unavailable from deeper positions.",
        "stat_signature": "Line-breaking passes from defensive third >=1.5 per 90; build-up midfield-zone touch share >20 %; average pass-reception depth from step-up carries >=35 m from goal.",
        "mechanism": "A stepping center-back creates a 3-versus-2 or 4-versus-3 numerical advantage against the opponent's press, generating an unguarded receiver further up the pitch.",
        "conditions": "Most impactful against a high press with a front two that leaves the center-back zone uncontested, and in systems that play out rather than bypass the press.",
        "magnitude": "Sides with step-up center-backs gain roughly 4 to 7 m of average build-up progression distance per sequence versus sides that limit center-backs to deep ball-recycling.",
        "links": ["inverted_fullback_dual_role", "three_at_back_to_four_morphing", "dual_pivot_role_rotation", "positional_versus_relational_play_blend"],
    },
    {
        "slug": "two_striker_role_specialization",
        "title": "Two-Striker Role Specialization",
        "summary": "Front-two partnerships split into a drop-and-link role and a run-in-behind role stretch the defensive line vertically while creating possession continuity, with role reversals resetting defensive orientation.",
        "stat_signature": "Reception-height differential between partner roles >=8 m; in-match role-reversal frequency >=2 per 90; link-striker lay-off rate >40 % of touches.",
        "mechanism": "The depth runner pins center-backs to the defensive line while the linking striker exploits the resulting half-space; role reversals disrupt pre-positioned coverage and force defensive re-orientation.",
        "conditions": "Most effective against a high defensive line with narrow center-back spacing and a midfield that does not track depth runs aggressively.",
        "magnitude": "Partnerships with high role-swap rates generate approximately 0.10 to 0.15 more expected goals per 90 than static role-divided pairings facing equivalent defensive shapes.",
        "links": ["false_nine_dropping_role", "positional_interchange_rotations", "creator_to_finisher_role_swap", "midfield_to_attack_late_arrival_versatility"],
    },
    {
        "slug": "wing_back_dual_phase_workload",
        "title": "Wing-Back Dual-Phase Workload",
        "summary": "Wing-backs in a back-three system covering the entire flank in both attack and defense combine the output of a fullback and wide midfielder within a single role, creating full-flank coverage.",
        "stat_signature": "Attacking-third entries per 90 >=4.0 and defensive-third recoveries per 90 >=3.5 simultaneously; flank-coverage sprint distance >1,800 m per 90 at speed above 21 km/h.",
        "mechanism": "Wing-backs substitute the combined output of two positional roles, allowing a back-three system to maintain defensive solidity while generating wide attacking width without an extra specialist.",
        "conditions": "Depends critically on sprint-recovery capacity; workload spikes in congested schedules produce measurable defensive-coverage declines from approximately minute 65 onward.",
        "magnitude": "Wing-back defensive-third recovery rates drop roughly 18 to 25 % relative to the first 45 minutes once fatigue effects become detectable in congested schedules.",
        "links": ["three_at_back_to_four_morphing", "auxiliary_winger_fullback_hybrid", "inverted_fullback_dual_role", "compact_to_expansive_block_adaptation"],
    },
    {
        "slug": "midfield_to_attack_late_arrival_versatility",
        "title": "Midfield-to-Attack Late-Arrival Versatility",
        "summary": "Midfielders who alternate between a deep base role and a late box-arriving role within the same match produce within-game variance in attacking-third arrival timing that makes defensive assignment difficult.",
        "stat_signature": "Within-game variance of average attacking-third arrival timing >4 min^2; box entries per 90 from a nominally deep role >=1.0; shot-from-deep-runner rate >=0.15 per 90.",
        "mechanism": "Unpredictable arrival timing prevents defensive shape-setters from pre-loading cover on the runner, generating uncontested shots from arriving midfielders.",
        "conditions": "Most effective in slow-build possession systems where defensive shape is set early and a late runner can exploit gaps behind organized opposition structure.",
        "magnitude": "Midfielders with high arrival-timing variance generate approximately 0.05 to 0.08 more expected goals per 90 from arriving runs versus those with predictable timing.",
        "links": ["box_to_box_phase_versatility", "two_striker_role_specialization", "dual_pivot_role_rotation", "positional_interchange_rotations"],
    },
    {
        "slug": "press_role_assignment_fluidity",
        "title": "Press-Role Assignment Fluidity",
        "summary": "Sides whose pressing triggers reassign the first-presser identity by zone rather than by fixed position maintain pressing effectiveness without concentrating pressing workload on a single player.",
        "stat_signature": "Dispersion of first-presser identity across pressing sequences >0.60 Shannon entropy bits; per-zone first-presser repetition rate <50 %; PPDA maintained <9.0 despite role rotation.",
        "mechanism": "Zone-keyed pressing assignments ensure the closest available player initiates regardless of nominal position, closing the opponent faster and reducing the ball-carrier's time on the ball.",
        "conditions": "Most effective against sides that rehearse build-up patterns designed to trigger a specific positional presser, and in high-press systems seeking to reduce individual workload.",
        "magnitude": "Fluid first-presser assignment reduces average opponent ball-carrier time before contact by roughly 0.3 to 0.6 s, correlating with a 10 to 15 % increase in press success rate.",
        "links": ["formation_flexibility_within_match", "dual_pivot_role_rotation", "compact_to_expansive_block_adaptation", "defensive_to_offensive_transition_role"],
    },
    {
        "slug": "compact_to_expansive_block_adaptation",
        "title": "Compact-to-Expansive Block Adaptation",
        "summary": "Teams that contract into a low block and expand into a high press by game-state demonstrate defensive shape adaptability, measured by within-match defensive-line-height range and block-compactness variation.",
        "stat_signature": "Defensive line-height range within a match >=15 m; block vertical compactness (inter-line distance) varies >=8 m between game-state bins; PPDA differential between leading and trailing states >=3.0.",
        "mechanism": "Adaptive block depth forces opponents to alternate between patience-requiring build-up against the low block and rapid combination play against the high press, increasing cognitive and physical load.",
        "conditions": "Score-line changes and match time drive the most pronounced activations; sides trailing by one goal shift toward the high block most markedly in the final 20 minutes.",
        "magnitude": "The PPDA differential between low and high block phases typically spans 4 to 8 units, representing a substantive shift in pressing intensity and opponent build-up disruption.",
        "links": ["formation_flexibility_within_match", "three_at_back_to_four_morphing", "press_role_assignment_fluidity", "defensive_to_offensive_transition_role"],
    },
    {
        "slug": "creator_to_finisher_role_swap",
        "title": "Creator-to-Finisher Role Swap",
        "summary": "Attackers who oscillate between providing the final pass and taking the final shot depending on build-up geometry reduce the opponent's ability to assign a single defensive priority to them.",
        "stat_signature": "Within-player balance of expected assists and expected goals per 90 with neither below 0.05; game-to-game role-direction switches in >=40 % of matches across a season.",
        "mechanism": "Defenders must hedge between anticipating a through ball and a shot from the same attacker, degrading the effectiveness of set positioning and pre-planned defensive priorities.",
        "conditions": "Most apparent in fluid attacking systems where the final action emerges from collective movement rather than pre-assigned target and creator roles.",
        "magnitude": "Dual-threat attackers create approximately 0.06 to 0.09 more combined expected-goal-contribution per 90 than role-specialized counterparts in equivalent possession contexts.",
        "links": ["positional_interchange_rotations", "false_nine_dropping_role", "two_striker_role_specialization", "wide_to_central_creative_shift"],
    },
    {
        "slug": "positional_versus_relational_play_blend",
        "title": "Positional-versus-Relational Play Blend",
        "summary": "Teams that blend fixed positional structure with free relational rotations depending on zone demonstrate zonal variance in player-position dispersion across pitch thirds.",
        "stat_signature": "Zonal variance in player-position dispersion: own-third dispersion <8 m average inter-player distance; opposition-third dispersion >13 m; mid-third intermediate.",
        "mechanism": "Fixed structure in deeper zones ensures defensive integrity and build-up predictability; free rotation in higher zones creates combinatorial unpredictability for the opponent's defensive organization.",
        "conditions": "Most coherent in high-possession systems with tactically literate players who can switch between a positional reference frame and relational decision-making cues by zone.",
        "magnitude": "Teams with high zonal-variance blend generate roughly 20 to 30 % more unique passing-network configurations per match in the final third versus rigidly positional or purely relational systems.",
        "links": ["ball_playing_center_back_progression", "dual_pivot_role_rotation", "formation_flexibility_within_match", "positional_interchange_rotations"],
    },
]
