"""scripts.platformkit.specs.anticipationreads_nba — NBA Anticipation Reads concept nodes."""
from __future__ import annotations

SPORT = "NBA"
FAMILY = "AnticipationReads"

CONCEPTS: list[dict] = [
    {
        "slug": "help_rotation_anticipation",
        "title": "Help-Rotation Anticipation Timing",
        "summary": "How early a help defender commits to a driving lane before the ball-handler turns the corner, measured as the lead-time between drive initiation and the helper's first step toward the paint.",
        "stat_signature": "Help-arrival lead-time >=0.3 seconds before corner turn; late-help (<=0.1 s lead) yields rim FG% ~62% against ~48% with pre-committed help; rotation-anticipation gap >0.4 s allows floater-range release at >=42%.",
        "mechanism": "Pre-committed help narrows the driving lane before the ball-handler's decision window closes, making rim attempts harder and floaters less rhythmic. Reactive help arrives after the drive angle is set, allowing the ball-handler to accelerate into open paint without adjusting.",
        "conditions": "Highest leverage against downhill dribble-penetrators with above-average burst; less impactful against step-back creators who rarely attack the rim; compressed in high-hedge pick-and-roll coverages where the big already pre-occupies the driving lane.",
        "magnitude": "Anticipatory help with >=0.3 s lead-time reduces rim frequency by roughly 15-20% and lowers rim FG% by 10-14 percentage points compared with reactive rotations on the same drive type.",
        "links": ["pnr_coverage_pre_read", "drive_gap_pre_seal", "weakside_tag_anticipation", "hedge_recovery_pre_position"],
    },
    {
        "slug": "passing_lane_jump_reads",
        "title": "Passing-Lane Jump Reads",
        "summary": "Pre-emptive gambles into telegraphed kick-out and skip passes, measured by deflection and steal rate on anticipated lanes relative to total passes attempted through those lanes.",
        "stat_signature": "Deflection rate on telegraphed kick-outs >=8 per 100 possessions in high-anticipation units; anticipatory steal rate ~2.5x reaction-steal rate on the same pass type; passing-lane jump rate correlates with turnover creation at r~0.58 across units.",
        "mechanism": "A ball-handler cocked for a kick-out reveals the target through hip and shoulder alignment a half-second before release. A defender reading those cues can break on the ball before it leaves the hand, arriving at the interception point in the natural flight path.",
        "conditions": "Most effective against ball-handlers with pronounced pre-pass body telegraphing and limited pump-fake tendency; backfires when the ball-handler reads the gamble and attacks the vacated area, yielding open drives to the unguarded gap.",
        "magnitude": "Units leveraging passing-lane reads generate ~1.8-2.4 additional steals per 100 possessions on anticipated lanes; each successful deflection produces a fast-break or clock-reset opportunity worth ~0.25 PPP above baseline.",
        "links": ["skip_pass_rotation_read", "ball_pressure_outlet_read", "double_team_trigger_read", "cut_anticipation_denial"],
    },
    {
        "slug": "pnr_coverage_pre_read",
        "title": "Pick-and-Roll Coverage Pre-Read",
        "summary": "How a defense diagnoses screen angle and ball-handler intent before contact, measured by the share of coverages executed before the screener arrives versus reactively after pick contact.",
        "stat_signature": "Pre-contact coverage commitment rate >=60% in disciplined systems; possessions with reactive coverage show pick-and-roll PPP ~1.08 against ~0.88 on pre-read possessions; hedge-timing error (late by >=0.5 s) yields corner-three at >38%.",
        "mechanism": "Screen angle and screener body language reveal the intended roll-or-pop action and the ball-handler's dominant drive direction before contact. Early diagnosis allows the coverage (drop, hedge, switch, blitz) to be set before the screen pressure forces a reactive scramble.",
        "conditions": "Most impactful in half-court late-clock situations where the offense runs a single scripted pick-and-roll; less decisive in continuous ball-movement possessions with multiple screen actions that reset the pre-read clock.",
        "magnitude": "Pre-committed coverage reduces pick-and-roll PPP by approximately 0.18-0.22 relative to reactive coverage on the same action, equivalent to a roughly 4-point defensive rating improvement if applied consistently across all pick-and-roll possessions.",
        "links": ["help_rotation_anticipation", "hedge_recovery_pre_position", "switch_communication_pre_call", "weakside_tag_anticipation"],
    },
    {
        "slug": "closeout_anticipation_distance",
        "title": "Closeout Anticipation Distance",
        "summary": "Pre-rotation positioning that shortens closeout travel on swing passes, measured as average defender-to-shooter distance at the moment of catch on perimeter spot-up attempts.",
        "stat_signature": "Anticipated closeout distance <=5 ft at catch yields contested-three rate >=72%; reaction-closeout distance >=8 ft at catch produces open-three rate ~55%; each additional foot of catch-distance adds ~1.2 percentage points to opponent three-point FG%.",
        "mechanism": "Help rotation opens shooting windows on the weak side; a defender who reads the ball's trajectory and pre-rotates halfway toward the shooter cuts travel distance and time, converting what would be an open catch into a semi-contested one before the shooter can set rhythm.",
        "conditions": "Most valuable in drive-and-kick offenses sequencing two or more swing passes; less effective in quick-hitter offenses where the pass comes before pre-rotation is feasible.",
        "magnitude": "Pre-positioned defenders arriving at the catch within 5 ft suppress corner-three FG% by roughly 5-7 percentage points versus open-look baselines, compounding across the ~30% of possessions that end in a kick-out catch-and-shoot.",
        "links": ["skip_pass_rotation_read", "help_rotation_anticipation", "shooter_release_anticipation", "screen_navigation_pre_read"],
    },
    {
        "slug": "rebound_carom_anticipation",
        "title": "Rebound Carom Anticipation",
        "summary": "Pre-emptive positioning toward predicted miss-trajectory zones by shot location, measured by the share of rebounds secured outside the rebounder's nominal box-out assignment.",
        "stat_signature": "Carom-anticipation rebound rate ~18-24% of total boards in top-quartile rebounders; short-side miss positioning on corner attempts yields offensive rebound rate <8% versus ~22% with static assignment-only positioning; long-miss (above-arc) recovery rate improves ~30% with arc-angle pre-read.",
        "mechanism": "Shot location and arc angle predict miss-trajectory distribution: corner attempts kick long at characteristic angles, rim shots fall short-side, high-arc shots produce a wider short-miss scatter. A rebounder pre-sealing in the statistically dense landing zone secures more contested boards than one reacting post-miss.",
        "conditions": "Most impactful on shot types with predictable carom zones (corner threes, short pull-ups, high-arc floaters); less deterministic on flat-trajectory mid-range shots with wide scatter distributions.",
        "magnitude": "Trajectory-aware positioning improves defensive rebound rate by roughly 3-5 percentage points on predictable-carom shot types, translating to ~0.8-1.2 additional defensive rebounds per 100 possessions in units that apply it systematically.",
        "links": ["drive_gap_pre_seal", "ball_pressure_outlet_read", "transition_matchup_pre_assign"],
    },
    {
        "slug": "drive_gap_pre_seal",
        "title": "Drive-Gap Pre-Seal Reads",
        "summary": "Off-ball defenders pinching a predicted driving gap a beat before the drive, measured as the rate of charges drawn and forced pickups attributable to pre-positioning rather than reaction.",
        "stat_signature": "Pre-seal charge rate ~1.5-2.0 per 100 possessions in high-anticipation systems; forced pickup rate on pre-sealed lanes ~12% of drive attempts versus ~4% on unsealed lanes; turnover-per-drive rate 2.1x higher when the gap is sealed before the ball-handler commits.",
        "mechanism": "Ball-handlers read the driving lane before committing; a defender who establishes legal guarding position in the predicted gap before the drive initiates either deters the drive or draws an offensive foul when the ball-handler cannot redirect. Reactive defenders arrive after the lane has been attacked and must commit reach fouls to contest.",
        "conditions": "Requires reading the offensive alignment for indicators of drive intent — off-ball positioning, screener approach angle, ball-handler's off-dribble stance — at least one beat before the drive launches.",
        "magnitude": "Successfully pre-sealed gaps yield charges or pickups on approximately 1 in 8 drive attempts compared with roughly 1 in 25 on reacted-to drives, representing a substantial possession-quality shift on penetration-heavy possessions.",
        "links": ["help_rotation_anticipation", "pnr_coverage_pre_read", "double_team_trigger_read", "post_entry_dig_anticipation"],
    },
    {
        "slug": "shot_clock_intent_read",
        "title": "Shot-Clock Intent Reading",
        "summary": "Anticipating whether a possession will be a quick-hitter or a late-clock isolation from offensive alignment, measured by defensive load-up timing variance across early versus late shot-clock buckets.",
        "stat_signature": "Early-clock (>=18 s) quick-hitter identification rate >=55% in experienced units; misread possessions (early-clock treated as late) yield open three-pointers on quick-hitter actions at ~42%; late-clock defensive intensity pre-loading reduces shot-clock violation rate forced to ~5% from ~3% with uniform intensity.",
        "mechanism": "Offensive alignment signals possession type: five-out spacing with immediate DHO or jet action indicates a quick-hitter; a single initiator with no early screening action indicates a late-clock probe. Matching defensive intensity and physical load-up to the anticipated possession type preserves energy for the correct window.",
        "conditions": "Most diagnostic in half-court sets with recognizable structural tells; ambiguous in freelance offenses where the ball-handler decides possession type at the point of attack without pre-alignment.",
        "magnitude": "Correct early-versus-late classification allows the defense to commit full intensity at the correct moment, reducing quick-hitter open looks by ~18-22% and improving late-clock possession yields by ~0.10 PPP through better-timed physical presence.",
        "links": ["double_team_trigger_read", "pnr_coverage_pre_read", "post_entry_dig_anticipation"],
    },
    {
        "slug": "weakside_tag_anticipation",
        "title": "Weakside Tag Anticipation",
        "summary": "Low-man stunting to tag a rolling screener before the lob window opens, measured by lob-disruption rate and recovery time back to the corner shooter after the tag.",
        "stat_signature": "Lob-disruption rate on pre-tagged rolls >=65%; lob attempt rate drops ~40% when a tag is established before the roll reaches the dunker spot; corner-three concession on tag-and-recover exits <=34%; tag-recovery time to close-out <=1.0 second in disciplined units.",
        "mechanism": "The lob window opens when the roller clears the screener's hip before any weak-side defender has committed to a stunt; a pre-emptive tag established before that moment makes the lob a high-risk pass, forcing the ball-handler to reset or attack the hedge rather than hunt the lob.",
        "conditions": "Triggered on any pick-and-roll where the roll man descends toward the dunker spot and no on-ball coverage naturally covers the lob lane; most critical under drop coverage, which leaves the roller undiscouraged.",
        "magnitude": "Consistent weak-side tags reduce lob-attempt rate by ~35-40% and suppress roll-man FG% at the rim from ~66% to ~52% by degrading catch quality and forcing off-balance finishes.",
        "links": ["help_rotation_anticipation", "pnr_coverage_pre_read", "hedge_recovery_pre_position", "drive_gap_pre_seal"],
    },
    {
        "slug": "handoff_chase_pre_read",
        "title": "Dribble-Handoff Chase Pre-Read",
        "summary": "Reading a handoff before the exchange to top-lock or chase over, measured by the share of handoffs disrupted at the point of exchange versus after the receiver turns the corner.",
        "stat_signature": "Pre-exchange disruption rate >=40% in top-lock handoff coverages; chase-over success (denying catch-and-shoot) >=55% with pre-read; post-corner disruption rate (reactive) ~18%; open pull-up on pre-read failures ~35% FG% against ~44% without pre-read pressure.",
        "mechanism": "The dribble-handoff giver's body angle and approach speed telegraph whether the receiver will catch-and-shoot immediately or attack the corner. A defender reading the giver's cues a half-step early can arrive at the exchange point in top-lock position rather than trailing by a step.",
        "conditions": "Most effective when the handoff giver displays consistent body language on shoot-versus-drive decisions; less decisive against giver-receiver pairs with high option variability that makes pre-reading unreliable.",
        "magnitude": "Pre-read handoff coverage suppresses catch-and-shoot three-point efficiency by ~6-8 percentage points at the exchange and reduces corner-turn drives by roughly 25% compared with reactive coverage on the same action.",
        "links": ["screen_navigation_pre_read", "pnr_coverage_pre_read", "switch_communication_pre_call"],
    },
    {
        "slug": "transition_matchup_pre_assign",
        "title": "Transition Matchup Pre-Assignment Reads",
        "summary": "Identifying the most dangerous fast-break threat during the rebound or inbound, measured by cross-match assignment latency and points allowed on unmatched leak-outs.",
        "stat_signature": "Pre-assignment latency <=1.5 seconds from rebound to matchup completion in elite transition defenses; leak-out PPP allowed with no pre-assignment ~1.42 against ~0.95 with a designated stopper pre-assigned; cross-match assignment error rate <12% in high-communication units.",
        "mechanism": "The transition advantage belongs to the team that reads the outlet first; a defense that identifies the primary fast-break threat at the moment of rebound can begin assigning coverage before the outlet pass is thrown, closing the burst window before a speed advantage opens.",
        "conditions": "Most critical after live-ball turnovers and missed three-pointers, which produce longer offensive carom distances and faster outlet opportunities; less decisive after made baskets where inbound assignments are structured.",
        "magnitude": "Pre-assignment reduces transition points allowed by approximately 0.45-0.50 PPP per leak-out opportunity — one of the highest per-possession leverage points in the transition-to-halfcourt boundary.",
        "links": ["rebound_carom_anticipation", "ball_pressure_outlet_read", "help_rotation_anticipation"],
    },
    {
        "slug": "cut_anticipation_denial",
        "title": "Backdoor-Cut Anticipation Denial",
        "summary": "Pre-reading off-ball cut intent from a defender's stance and head-position, measured by backdoor steal rate and the fraction of cuts denied before the cutter reaches the dunker spot.",
        "stat_signature": "Backdoor steal rate in anticipatory denial systems ~1.2-1.8 per 100 possessions; cuts denied before dunker arrival ~45% in high-read units against ~20% in pure-reaction coverage; layup-concession rate on unread cuts ~72% FG% from dunker zone.",
        "mechanism": "Backdoor cuts are initiated when the defender's head turns to the ball; the cutter reads that moment and breaks baseline. A defender maintaining peripheral awareness of both the cutter and the ball can feel the overplay trigger and deny the cut before it reaches a high-value catch point.",
        "conditions": "Activated by tight denial on the wing; most dangerous when the on-ball defender is also applying pressure, drawing the wing defender's focus; less effective against offenses that use the backdoor as a primary action rather than as a read.",
        "magnitude": "Consistent backdoor anticipation converts ~1 in 4 cut attempts into steals or denials, reducing high-percentage dunker-zone layup opportunities by roughly 35-45% and forcing the offense into a secondary action.",
        "links": ["passing_lane_jump_reads", "screen_navigation_pre_read", "handoff_chase_pre_read"],
    },
    {
        "slug": "screen_navigation_pre_read",
        "title": "Off-Ball Screen Navigation Pre-Read",
        "summary": "Anticipating pin-down and flare screens to choose top-lock, chase, or switch before screen contact, measured by the share of screens navigated cleanly without a catch-and-shoot release.",
        "stat_signature": "Pre-contact coverage decision rate >=65% in film-prepared units; clean navigation rate (no open release) ~58% with pre-read against ~38% without; back-cut concession on over-applied top-lock ~0.6 per 100; open catch-and-shoot three-point FG% on reactive navigation ~40%.",
        "mechanism": "Screen type and screener approach angle telegraph the action: a pin-down coming from the block suggests a curl-or-flare read; a flare from the corner indicates a pop to the wing. Pre-reading allows the defender to position one step ahead, preserving coverage without contact.",
        "conditions": "Most impactful against offenses running scripted off-ball sequences (staggers, pin-downs, elevator actions); less decisive against freelance motion offenses where screen locations are not pre-determined.",
        "magnitude": "Pre-reading off-ball screens reduces open catch-and-shoot three-point concession by ~5-8 percentage points on those actions and eliminates roughly 20% of the defensive scrambles that produce second-pass open looks.",
        "links": ["handoff_chase_pre_read", "closeout_anticipation_distance", "cut_anticipation_denial", "switch_communication_pre_call"],
    },
    {
        "slug": "post_entry_dig_anticipation",
        "title": "Post-Entry Dig Anticipation",
        "summary": "Pre-positioning a digger on the predicted post-up before the entry pass arrives, measured by post double-team arrival time and forced-kickout rate.",
        "stat_signature": "Pre-entry dig arrival (<=0.4 s after catch) suppresses post FG% to ~44% against ~52% on late digs; forced-kickout rate with pre-positioned dig >=55%; late-dig (>=0.8 s) effectiveness drops to ~28% forced-kickout rate; lob-over-dig concession rate ~8% with pre-arrival against ~22% reactive.",
        "mechanism": "A digger who arrives at catch forces the post scorer to make an immediate decision under pressure before establishing a favorable facing angle. A late digger arrives after the post has already chosen a power move or face-up, making the dig less disruptive and more likely to produce a lob-over or skip-kick penalty.",
        "conditions": "Effective when the primary post-up location is predictable from offensive alignment; requires a digger within ~12-15 feet of the post to arrive in time; high risk of skip-kick open threes if perimeter shell does not account for the dig.",
        "magnitude": "Pre-entry digs reduce post PPP by approximately 0.18-0.24 relative to isolated post coverage, but the skip-kick penalty can offset ~0.06-0.10 PPP if shell rotation is incomplete, making net value execution-dependent.",
        "links": ["drive_gap_pre_seal", "weakside_tag_anticipation", "shot_clock_intent_read"],
    },
    {
        "slug": "hedge_recovery_pre_position",
        "title": "Hedge-Recovery Pre-Positioning",
        "summary": "The big's anticipatory angle of retreat from a hedge to cut off the roll before recovering, measured by roll-man catch suppression and recovery-step efficiency.",
        "stat_signature": "Pre-angled recovery (body facing roll lane on hedge exit) suppresses roll-man catch rate ~35% versus square-out recovery; roll-man FG% at rim ~46% with pre-positioned recovery against ~62% straight-line reactive pursuit; recovery-step count to cut off roll <=3 steps in elite bigs.",
        "mechanism": "A hedging big who retreats straight back gives the roller a free runway to the rim; one who retreats on an angle that intercepts the roll path cuts off both the pass window and the post-catch acceleration lane simultaneously, making the roll a contested catch rather than a layup approach.",
        "conditions": "Requires the big to read the roller's initial step direction during the hedge — curl versus pop versus short-roll — before committing the recovery angle; misjudging the recovery angle on a pop action leaves the shooter uncontested.",
        "magnitude": "Correct recovery angle reduces roll-man PPP from ~1.22 to ~0.94 per possession, a 0.28 PPP gap that is among the largest execution-dependent differentials in pick-and-roll defense.",
        "links": ["pnr_coverage_pre_read", "weakside_tag_anticipation", "help_rotation_anticipation"],
    },
    {
        "slug": "skip_pass_rotation_read",
        "title": "Skip-Pass Rotation Reading",
        "summary": "Anticipating a cross-court skip to begin the long X-out rotation early, measured by closeout arrival time on the far-side shooter after a skip pass.",
        "stat_signature": "Pre-skip rotation start (body weight shifted before release) yields closeout arrival <=0.8 s after catch ~62% of the time against ~28% with reactive rotation; open-three FG% on late arrivals (>=1.0 s) ~42% against ~29% on timely closeouts; skip-pass PPP ~1.18 without rotation read against ~0.94 with.",
        "mechanism": "The ball-handler loading for a skip reveals the target's direction through shoulder alignment and dribble rhythm. A weak-side defender reading these cues begins moving before the ball is released, cutting the 35-40 foot rotation distance into an attainable closeout rather than a dead sprint arriving one beat late.",
        "conditions": "Most impactful in five-out drive-and-kick sets where skip passes are frequent and shooters catch in rhythm; less decisive in handoff-heavy half-court offenses where skips are rare.",
        "magnitude": "Anticipatory skip rotation reduces open-catch-and-shoot three frequency by roughly 30-35% on skip actions and lowers three-point FG% on those attempts by 5-8 percentage points through degraded catch rhythm.",
        "links": ["closeout_anticipation_distance", "passing_lane_jump_reads", "help_rotation_anticipation", "shooter_release_anticipation"],
    },
    {
        "slug": "shooter_release_anticipation",
        "title": "Shooter-Release Anticipation Contest",
        "summary": "Timing a contest to the predicted release point rather than the catch, measured by contest-at-release rate and the fraction of clean looks converted into contested ones.",
        "stat_signature": "Contest-at-release rate >=70% in high-anticipation closeouts; three-point FG% against release-timed contests ~29% against ~38% on clean looks; late contest (arriving post-release by >=0.15 s) lowers FG% only ~2 percentage points; chase-down block rate on anticipated pull-ups ~1.8 per 100 possessions.",
        "mechanism": "Shooters establish their mechanics and release window in a predictable arc from catch to lift to release. A defender who reads the shooter's gather and jump timing can extend at release rather than at catch, maximizing contest proximity at the exact moment the ball leaves the hand rather than collapsing early or arriving after.",
        "conditions": "Requires reading individual shooter release triggers — dip depth, gather width, jump quickness — from game film; uniform early-extend contests produce more foul calls and less shot-quality degradation than release-timed contests.",
        "magnitude": "Release-timed contests lower three-point FG% by approximately 7-9 percentage points compared with open looks, roughly twice the degradation from a late-arriving contest, while reducing shooting foul rate by ~3 percentage points versus early-extend approaches.",
        "links": ["closeout_anticipation_distance", "skip_pass_rotation_read", "screen_navigation_pre_read"],
    },
    {
        "slug": "switch_communication_pre_call",
        "title": "Switch Pre-Call Communication",
        "summary": "Verbal and positional pre-calling of an impending switch before screen contact, measured by switch-miss rate and the share of switches executed without a momentary gap.",
        "stat_signature": "Pre-called switch clean-execution rate >=78% against ~45% for reactive switches; gap-at-switch-point (>=3 ft open) rate ~8% on pre-called versus ~31% on uncalled; first-action PPP after an uncalled switch gap ~1.18 against ~0.91 after a clean switch.",
        "mechanism": "A late switch call arrives after screen contact, leaving both defenders momentarily defending neither the ball-handler nor the screener — the gap window. A pre-call resolves assignments before contact, so each defender knows their man at the moment the screen is set and no gap forms.",
        "conditions": "Most critical on DHO and Spain pick-and-roll actions where both the handoff and the roll create simultaneous threats; less necessary on switch-by-default units where every action is switched uniformly.",
        "magnitude": "Pre-call communication reduces gap-at-switch-point frequency by approximately 23 percentage points, eliminating the highest-leverage single moment in pick-and-roll switching systems — the 0.3 to 0.5 second no-man window that produces the majority of open drive opportunities.",
        "links": ["pnr_coverage_pre_read", "screen_navigation_pre_read", "handoff_chase_pre_read", "help_rotation_anticipation"],
    },
]
