"""Person-free NBA ChainSequences concept nodes — dense, sport-accurate, no player/team names."""
from __future__ import annotations

SPORT = "NBA"
FAMILY = "ChainSequences"

CONCEPTS: list[dict] = [
    {"slug": "advantage_creation_first_action", "title": "First-Action Advantage Creation",
     "summary": "The opening action of a half-court possession — ball-screen, dribble-handoff, cut, or post entry — generates a measurable defensive tilt before any secondary action begins, quantified by the rate at which it forces a rotation, closeout, or two-on-the-ball response.",
     "stat_signature": "First-action rotation-induced rate ranges 28-48% across NBA offenses; possessions with a rotation on the first action yield PPP 0.06-0.14 above those without; closeout-forced first actions generate open catch-and-shoot attempts at 22-32% of cases.",
     "mechanism": "A rotation or closeout triggered on the first action places one defender out of position before the chain continues, creating a structural 4-on-3 or spacing gap that the second-link action can directly exploit without having to create the advantage from scratch.",
     "conditions": "Effect is largest against help-and-recover schemes where the first rotation commitment is mandatory; attenuated against switch-everything coverage that neutralises the first action without committing any single defender to a gap.",
     "magnitude": "First-action rotation rate above 40% corresponds to half-court PPP 0.07-0.12 above average; the gap between top and bottom quartile first-action creation quality spans roughly 0.10-0.18 PPP across a full season.",
     "links": ["advantage_decay_per_pass", "pick_and_roll_into_short_roll_read", "scramble_chain_after_closeout", "chain_terminal_shot_quality"]},

    {"slug": "advantage_decay_per_pass", "title": "Advantage Decay Across the Pass Chain",
     "summary": "A defensive advantage created by the first action erodes or compounds with each subsequent pass, measurable by the half-life of expected-shot-quality gain per additional link in the possession chain.",
     "stat_signature": "Expected-shot-quality (eSQ) gain from the peak-advantage moment decays at roughly 0.015-0.030 eSQ units per additional pass when the defense is recovering; chains of 3+ passes holding the eSQ above 1.05 represent the top 15-20% of half-court possessions.",
     "mechanism": "Each additional pass gives one more defender a recovery step; defensive rotations travel faster than the ball when the offense slows its pace, so the window of exploitable misalignment shrinks unless the chain attacks before coverage reconverges.",
     "conditions": "Decay is steepest against disciplined rotation teams with high help-side communication; slowest against scramble-heavy zone defenses that generate new gaps with every extra rotation they commit to.",
     "magnitude": "Possessions that add a third pass into an already-decayed advantage produce shots 0.04-0.09 eSQ below those that attack at peak advantage; chains that sustain advantage across 3+ passes convert at eFG% 4-8 pp above same-depth chains that allow recovery.",
     "links": ["advantage_creation_first_action", "drive_and_kick_chain_length", "swing_swing_reversal_sequence", "chain_terminal_shot_quality", "advantage_keep_versus_reset"]},

    {"slug": "zero_second_to_paint_touch", "title": "Time-to-First-Paint-Touch Sequencing",
     "summary": "How quickly a possession penetrates the paint after the first live dribble — measured in seconds and passes to the first paint touch — because earlier interior compression front-loads the rotation sequence the rest of the chain exploits.",
     "stat_signature": "Median time-to-first-paint-touch in NBA half-court possessions is 7-9 seconds after inbound; possessions reaching the paint within 4 seconds produce PPP 0.10-0.18 above those reaching it after 12 seconds; early-paint-touch rate above 30% of possessions characterises high-tempo half-court offenses.",
     "mechanism": "An early paint touch forces the defense to commit its help layer before off-ball actions have displaced defenders from optimal position; the compression then radiates outward to create open kick-out angles that later-arriving paint touches cannot match.",
     "conditions": "Effect is strongest against drop-coverage and zone schemes that load the paint; diminished against pack-the-paint schemes that pre-commit defensive bodies to the interior and accept conceding early perimeter catch-and-shoot looks.",
     "magnitude": "Early-paint-touch possessions (under 5 seconds) generate corner-three open-look rates 6-10 pp above late-paint-touch possessions; rim-FGA rates in these chains are 4-8 pp higher than average half-court possessions.",
     "links": ["drive_and_kick_chain_length", "advantage_creation_first_action", "scramble_chain_after_closeout", "post_entry_kickout_recycle"]},

    {"slug": "drive_and_kick_chain_length", "title": "Drive-and-Kick Chain Length",
     "summary": "The count of consecutive drive-collapse-then-kickout links within a single possession and the marginal expected-points contribution of each additional kick before a shot is taken.",
     "stat_signature": "Average NBA drive-and-kick chain terminates at 1.3 kicks; two-kick chains (drive → kick → skip → shoot) occur in 14-22% of drive possessions; marginal PPP added by the second kick averages +0.04 to +0.09 when the defense has not recovered; chains of 3+ kicks produce open corner-three frequency above 38%.",
     "mechanism": "Each kick forces a new closeout to a different defender; the defense must travel laterally across the full court width after each kick, accumulating closeout distance that compounds into progressively more open looks as the chain extends.",
     "conditions": "Chain-length benefits accrue most in lineups with 3+ credible three-point threats occupying multiple zones; diminished when the defense possesses athletes fast enough to close-out twice without trailing distance accumulation.",
     "magnitude": "Two-kick-chain possessions produce eFG% on the terminal shot 5-9 pp above single-kick chains; teams executing 5+ two-kick chains per game score 3-5 additional points per 48 minutes versus teams averaging under 2 per game.",
     "links": ["advantage_decay_per_pass", "zero_second_to_paint_touch", "swing_swing_reversal_sequence", "scramble_chain_after_closeout", "chain_terminal_shot_quality"]},

    {"slug": "swing_swing_reversal_sequence", "title": "Side-to-Side Reversal Sequencing",
     "summary": "Multiple full-court-width ball reversals within one possession force help defenders to close out repeatedly from the opposite side, measurable by the growth in closeout-travel distance across successive reversals.",
     "stat_signature": "Second-reversal closeout distance is 18-26 ft on average versus 10-15 ft on first-reversal closeouts; possessions with 2+ full reversals produce open-three rates above 34% on the final action; double-reversal frequency above 18% of half-court possessions characterises elite ball-movement offenses.",
     "mechanism": "Each reversal assigns a new closeout obligation to the weakside help defender, who must sprint across the arc; the second sprint arrives before the defender has fully recovered from the first, creating an open-catch window that compounds with each additional reversal.",
     "conditions": "Amplified against helpside-loading defenses that chase the ball hard; attenuated against disciplined zone schemes that rotate as a unit without individual help-and-recover assignments.",
     "magnitude": "Third-reversal catch-and-shoot attempts convert at 40-46% versus 36-40% on non-reversed catch-and-shoots; teams that generate 12+ reversal sequences per game average 0.08-0.12 PPP above teams with under 6 per game in half-court sets.",
     "links": ["drive_and_kick_chain_length", "advantage_decay_per_pass", "decoy_action_misdirection_chain", "chain_terminal_shot_quality"]},

    {"slug": "pick_and_roll_into_short_roll_read", "title": "Pick-and-Roll into Short-Roll Read Chain",
     "summary": "The two-link chain where ball-screen coverage forces a pocket pass to a short-roll hub who then executes a 4-on-3 read, quantified by conversion and assist-generation rates conditional on the coverage type faced.",
     "stat_signature": "Short-roll hub possession frequency 8-14 per 100 half-court possessions for screen-heavy offenses; PPP on possessions initiated via short-roll read 1.08-1.22; assist-per-touch rate from the short-roll hub 0.35-0.55; coverage-conditional PPP gap between hedge/switch and drop coverage on short-roll reads 0.06-0.12.",
     "mechanism": "The hedge or blitz on the ball-screen displaces the coverage of both the screener and a help defender; the pocket-pass to the short-roll position exploits this displacement before all five defenders have reassigned, creating a cascading 4-on-3 that is more valuable than the initial ball-screen threat alone.",
     "conditions": "Effect is strongest against aggressive ball-screen coverage schemes (hard hedges, blitzes) that create the largest displacement; neutralised by drop coverage that keeps the big near the rim and denies the pocket-pass angle.",
     "magnitude": "Short-roll-read possessions generate assists on 40-55% of terminal shots; PPP premium of the two-link chain over isolating the ball-screen handler is 0.08-0.14 per possession for elite short-roll reading hubs.",
     "links": ["advantage_creation_first_action", "two_man_game_re_screen_chain", "double_drag_into_flare_sequence", "scramble_chain_after_closeout"]},

    {"slug": "double_drag_into_flare_sequence", "title": "Stacked-Screen into Off-Ball-Flare Sequence",
     "summary": "Chained on-ball screening actions (double or step-up actions) that flow immediately into an off-ball flare or pindown, measured by how often the second screen arrives before the defense has reset from the first.",
     "stat_signature": "Defense-reset lag after a first drag screen averages 1.8-2.5 seconds; flare-screen actions arriving within 1.5 seconds of the first action catch defenders still recovering in 38-52% of cases; open-catch rate on the flare receiver 30-42% when timed correctly versus 20-28% when late.",
     "mechanism": "The on-ball screen forces defenders to communicate coverage before the off-ball flare action initiates; when the second action arrives before communication resolves, a defender must choose between covering the ball-handler or the flare receiver — an unsolvable dual threat.",
     "conditions": "Most productive when on-ball screeners are credible short-roll or face-up threats that demand genuine coverage attention; reduced when the defense can ignore the screener's roll, freeing a body to cover the flare.",
     "magnitude": "Flare receivers catching open off double-drag actions shoot catch-and-shoot threes at 40-46%; possessions using a timed stacked-into-flare sequence yield PPP 0.10-0.18 above single-screen equivalent possessions.",
     "links": ["pick_and_roll_into_short_roll_read", "horns_into_split_sequence", "two_man_game_re_screen_chain", "advantage_creation_first_action"]},

    {"slug": "advantage_keep_versus_reset", "title": "Keep-the-Advantage Against Reset Decision",
     "summary": "The decision point where a ball-handler with a fading advantage either attacks immediately or resets the possession, quantified by the expected-points difference between continuing a partial-advantage chain and restarting.",
     "stat_signature": "Possessions reset after a fading advantage yield PPP 0.92-1.00 on the next action sequence; attacking into a 0.4-to-0.6 advantage state (partial but not full) yields 1.02-1.10 PPP; late-shot-clock resets (under 10 seconds remaining) collapse PPP to 0.80-0.90.",
     "mechanism": "Resetting a partial advantage surrenders the existing displacement and allows the defense to fully reconverge; attacking the partial advantage forces the defense to play a step behind rather than in full position, extracting value from the residual tilt before it vanishes.",
     "conditions": "Decision is most consequential with 12-18 seconds remaining on the shot clock where neither option is forced; with under 8 seconds the attack is typically optimal; with 20+ seconds remaining the reset cost is low.",
     "magnitude": "Teams with high partial-advantage attack rates versus reset rates score 0.06-0.10 PPP more on the affected possessions; the annual value of this decision optimisation across a full season is estimated at 4-8 points per game in aggregate.",
     "links": ["advantage_decay_per_pass", "shot_clock_phase_action_ordering", "isolation_after_advantage_collapse", "chain_terminal_shot_quality"]},

    {"slug": "post_entry_kickout_recycle", "title": "Post-Entry Kickout-and-Recycle Chain",
     "summary": "The sequence of a post touch that draws a double-team, kicks out to the perimeter, and recycles into a second interior or perimeter action against a still-scrambling defense.",
     "stat_signature": "Double-team rate on post-entry touch ranges 35-60% for premier post scorers; post-kickout pass rate when doubled 65-78%; open-shot rate on the first-kickout receiver 38-50%; second-action recycle PPP (shot after a reset from the kick) 0.98-1.14 due to residual defensive scramble.",
     "mechanism": "The double-team commits two defenders to one offensive player, generating a structural 3-on-3 or 4-on-3 on the perimeter; the kickout exploits the committed double; the recycle exploits the late recovery of the double-team defender who must sprint back from post to perimeter.",
     "conditions": "Effective against teams that commit aggressive doubles from the weakside corner or high help; diminished against schemes that send the closest defender only and maintain perimeter coverage.",
     "magnitude": "Post-kickout open-three rate of 38-50% converts at 36-43% eFG, generating PPP 1.05-1.18 on the terminal action; full recycle-to-second-action sequences average PPP 0.04-0.10 above first-look equivalents.",
     "links": ["zero_second_to_paint_touch", "scramble_chain_after_closeout", "second_side_action_conversion", "chain_terminal_shot_quality"]},

    {"slug": "scramble_chain_after_closeout", "title": "Scramble-Chain After Forced Closeout",
     "summary": "The cascading sequence of advantage-extending actions executed while a defense remains in rotation after its first closeout, measured by the count of consecutive advantage-preserving moves before matchups are fully recovered.",
     "stat_signature": "Average defense-in-scramble duration after a forced closeout is 2.8-4.2 seconds; possessions with 2+ actions during the scramble window yield PPP 1.12-1.28; scramble-window attack rate above 55% of closeout possessions characterises high-IQ offenses.",
     "mechanism": "A closeout places one defender sprinting toward a shooter while the help layer is displaced; a quick skip or drive into the scramble reattaches the rotational debt to a new defender before the first one recovers, chaining the scramble state across multiple actions.",
     "conditions": "Amplified against defenses with slow communication where individual defenders react in sequence rather than as a unit; attenuated by defensive schemes that use predetermined zone-rotation principles to prevent cascading scramble.",
     "magnitude": "Scramble-chain possessions of 2+ links convert at eFG% 7-12 pp above settled-defense equivalents; each additional second of maintained scramble correlates with an estimated +0.05 PPP on the terminal shot.",
     "links": ["drive_and_kick_chain_length", "post_entry_kickout_recycle", "second_side_action_conversion", "advantage_creation_first_action", "chain_terminal_shot_quality"]},

    {"slug": "handoff_chain_continuity", "title": "Dribble-Handoff Chain Continuity",
     "summary": "Repeated dribble-handoff actions strung within one possession, where each consecutive handoff increases the probability of a coverage error — measured by defender-trail distance per successive handoff.",
     "stat_signature": "First-handoff defender-trail distance averages 0.8-1.5 ft; second consecutive handoff trail distance 2.5-4.0 ft when defense is overcommitting over the top; coverage-error rate (switch confusion or trail leading to open catch) rises from 18% on first to 34-48% on second handoff.",
     "mechanism": "The first handoff forces an over/under coverage decision; the second handoff arrives before the defender who chose over can redirect, creating a sequential coverage debt that grows faster than the defense can adapt within one possession.",
     "conditions": "Most exploitable against defenses that fight over the top on every handoff; reduced against teams that switch every handoff action and maintain coverage assignments regardless of handoff count.",
     "magnitude": "Second-consecutive-handoff possessions generate shots at eFG% 5-9 pp above first-handoff shots; teams averaging 6+ two-handoff chains per game score 2-4 additional PPP-equivalent points per 48 minutes from this action type.",
     "links": ["two_man_game_re_screen_chain", "double_drag_into_flare_sequence", "advantage_decay_per_pass", "decoy_action_misdirection_chain"]},

    {"slug": "second_side_action_conversion", "title": "Second-Side Action Conversion",
     "summary": "Possessions where the first-side action functions as a deliberate decoy that displaces defensive attention to set up a pre-designed second-side action, measured by the expected-shot-quality lift of the second-side option over the first.",
     "stat_signature": "Second-side action frequency in motion offenses 20-32% of possessions; expected-shot-quality gap between second-side terminal shot and first-side terminal shot averages +0.08-0.16 eSQ for well-designed actions; conversion rate of scripted second-side plays in NBA sets 42-56%.",
     "mechanism": "Defensive attention follows ball movement and the first action, displacing help coverage toward the initial threat; the pre-planned counter on the weak side exploits the precise moment of maximum displacement before the defense reverses.",
     "conditions": "Effectiveness requires the first-side action to credibly threaten scoring so the defense commits; against defenses that ignore weak-side threats, the decoy creates no displacement and the second-side advantage evaporates.",
     "magnitude": "Well-executed second-side counters generate open-look catch-and-shoot threes at 36-44% frequency; scripted second-side plays yield PPP 0.10-0.18 above unscripted possessions with similar ball movement.",
     "links": ["decoy_action_misdirection_chain", "horns_into_split_sequence", "scramble_chain_after_closeout", "chain_terminal_shot_quality"]},

    {"slug": "shot_clock_phase_action_ordering", "title": "Shot-Clock-Phase Action Ordering",
     "summary": "How possessions order their action types across the early (20+ seconds), middle (10-20 seconds), and late (under 10 seconds) shot-clock bands, with distinct frequency and quality profiles in each phase.",
     "stat_signature": "Early-clock PPP 1.05-1.18 (transition bleed + early action advantage); middle-clock PPP 0.97-1.08 (set plays, screen actions); late-clock PPP 0.78-0.92 (contested bailouts, isolation); NBA teams vary up to 0.18 PPP across phases based on action-ordering philosophy.",
     "mechanism": "Early-clock possessions catch defenders still setting up coverage; middle-clock actions exploit schemed advantages; late-clock possessions are contested by fully positioned defenses. Ordering a complex chain that resolves in the early band extracts maximum advantage before the clock-pressure changes the shot context.",
     "conditions": "Most consequential for teams that run scripted 5-second sets in the early clock; less differentiating for teams that rely on free-form improvisation where the ordering is incidental rather than designed.",
     "magnitude": "Teams that resolve 35%+ of possessions in the early-clock phase average 0.06-0.10 PPP above teams resolving fewer than 20% early; each 5 pp shift in early-clock resolution rate corresponds to approximately 0.03-0.05 PPP half-court improvement.",
     "links": ["advantage_keep_versus_reset", "isolation_after_advantage_collapse", "transition_to_early_offense_flow", "chain_terminal_shot_quality"]},

    {"slug": "transition_to_early_offense_flow", "title": "Transition-into-Early-Offense Flow Chain",
     "summary": "When a fast break does not yield an immediate shot, the possession flows into a drag-screen or early-offense action in the 5-to-10-second window before the defense is fully matched up, measured by shot-quality in that window.",
     "stat_signature": "Early-offense PPP in the 5-10 second window after an unsconverted break averages 1.08-1.20 versus 0.96-1.05 for possessions that wait for a full set; drag-screen early-offense actions in this window generate rim or open-three at 38-48% frequency.",
     "mechanism": "An unconverted fast break still carries positional disorganisation in the defense for 5-8 seconds; a drag screen or quick handoff initiated inside that window attacks a coverage that has not yet resolved assignments, preserving a tempo premium that a settled possession cannot replicate.",
     "conditions": "Effective only when the ball-handler accelerates into the early-offense action before the defense communicates; once the trailing defenders call out coverages (~8-10 seconds after inbound), the advantage dissolves into a standard half-court possession.",
     "magnitude": "Drag-screen early-offense possessions yield PPP 0.10-0.18 above equivalent settled ball-screen possessions; teams converting 40%+ of unconverted breaks into productive early-offense chains score an estimated 2-4 more points per 48 minutes.",
     "links": ["shot_clock_phase_action_ordering", "pick_and_roll_into_short_roll_read", "advantage_creation_first_action", "chain_terminal_shot_quality"]},

    {"slug": "isolation_after_advantage_collapse", "title": "Isolation as Terminal Chain Resolver",
     "summary": "Possessions that abandon the motion chain for a late-clock isolation, measured by the expected-points penalty of chain dead-ends into isolation relative to possessions that resolve within the flow.",
     "stat_signature": "Isolation PPP ranges 0.82-1.02 across NBA situations; isolation share above 20% of half-court possessions correlates with PPP 0.04-0.10 below motion-based equivalents; possessions that enter isolation with under 8 seconds remaining post PPP 0.06-0.12 below same-clock-situation motion completions.",
     "mechanism": "Isolation discards the cumulative defensive displacement generated by the earlier chain, presenting the defense with a one-on-one scenario where all five defenders can help from optimal position; the PPP floor rises only when the isolation initiator is among the top percentile of creation talent.",
     "conditions": "Penalty is smallest when the isolation action is triggered by a genuine mismatch created mid-possession rather than by a chain that simply runs out of options; largest when isolation is a default for clock-management rather than exploitation.",
     "magnitude": "Chain-dead-end isolations yield PPP 0.08-0.15 below flow-resolved equivalents; replacing 5 dead-end isolations per game with flow-resolved actions corresponds to 1.5-3.0 additional expected points per 48 minutes.",
     "links": ["advantage_keep_versus_reset", "shot_clock_phase_action_ordering", "chain_terminal_shot_quality", "advantage_decay_per_pass"]},

    {"slug": "chain_terminal_shot_quality", "title": "Chain-Terminal Shot-Quality Profile",
     "summary": "The relationship between the number of advantage-extending links in a possession and the quality of the final shot, measured by the eFG% gradient as a function of chain depth.",
     "stat_signature": "Zero-link possessions (direct first-action shots) average eFG% 48-52%; one-link possessions 51-56%; two-link possessions 54-60%; three-plus-link possessions 56-63% when advantage is maintained; gradient inverts to 46-50% when links accumulate past decay threshold.",
     "mechanism": "Each productive link displaces a defender before the terminal shot, reducing contest probability; the gradient turns negative beyond the optimal depth because additional passes give the defense recovery time that erases the accumulated displacement advantage.",
     "conditions": "Positive gradient extends farthest in scramble-state possessions and against defenses with slow rotation; collapses earliest against disciplined zone and switch-everything schemes where displacement is neutralised by unit rotation rather than individual recovery.",
     "magnitude": "Optimal-depth chains (2-3 links) generate eFG% 6-12 pp above single-action equivalents; over a full season, possession portfolios concentrated in 2-3-link chains produce half-court PPP 0.06-0.12 above single-link heavy offenses at equal talent.",
     "links": ["advantage_decay_per_pass", "drive_and_kick_chain_length", "scramble_chain_after_closeout", "shot_clock_phase_action_ordering", "isolation_after_advantage_collapse"]},
]
