"""MLB ChainSequences — person-free, dense pitch-sequence and inning-chain concepts grounded
in count-path distributions, run-expectancy matrices, and sequence-entropy measures."""
from __future__ import annotations

SPORT = "MLB"
FAMILY = "ChainSequences"

CONCEPTS = [
    {
        "slug": "first_pitch_strike_sequencing_anchor",
        "title": "First-Pitch-Strike Sequencing Anchor",
        "summary": "Winning the first pitch of a plate appearance shifts the subsequent count-path distribution sharply toward the pitcher, collapsing the hitter's accessible pitch sequences and reducing the expected run value of the plate appearance from pitch one.",
        "stat_signature": "RE after 0-1: ~-0.040 runs versus at-bat start; RE after 1-0: ~+0.033 runs. Strikeout rate from 0-1 start: 26-30%; from 1-0 start: 14-18%. Walk rate from 1-0 starts: 12-16%; from 0-1 starts: 4-6%. First-pitch-strike rate for above-average starters: 64-68%.",
        "mechanism": "The first-pitch outcome gates the entire pitch-tree: a strike immediately limits the hitter to a subset of count paths that exclude all walk-access routes and weight heavily toward 0-2 or 1-2 pitcher-ahead nodes. The hitter's zone-management strategy compresses because any subsequent ball merely returns to even rather than conferring advantage.",
        "conditions": "Most consequential against hitters with disciplined zone management who exploit deeper counts. The anchor effect is larger against pull-heavy power hitters relying on a specific count window. Attenuates when the pitcher cannot locate a competitive first pitch and defaults to a predictable get-me-over offering.",
        "magnitude": "First-pitch-strike versus first-pitch-ball produces a ~0.073-run RE swing per plate appearance. Over a nine-inning outing at ~27 PA, a 10 pp improvement in first-pitch-strike rate translates to roughly 0.20 RE units saved — structurally meaningful at the game level.",
        "links": ["ahead_in_count_expansion_chain", "two_strike_putaway_sequence", "swing_decision_chain_within_pa", "pitch_count_attrition_sequence"],
    },
    {
        "slug": "ahead_in_count_expansion_chain",
        "title": "Ahead-in-Count Expansion Chain",
        "summary": "After reaching a pitcher-ahead count, expanding the zone with back-foot breakers and elevated fastballs induces chase attempts on offerings outside the strike zone, producing whiffs and weak contact that chain consecutive out-of-zone pitches into a plate-appearance-ending sequence.",
        "stat_signature": "Chase rate in 0-2 counts: 36-42%; whiff rate on chased pitches: 48-56%. Two consecutive out-of-zone pitches ending the PA rate: 18-24% of 0-2 and 1-2 situations. Expected run value drops ~0.055 per successful chase-induced swing. xwOBA on swing-and-miss sequences: .085-.110.",
        "mechanism": "A hitter defending against a strikeout expands their attack zone to cover plausible borderline offerings, and pitchers exploit that mental zone-widening by serving pitches outside the genuine strike zone at the perimeter of what the hitter must protect. Each consecutive non-contact or swing-through reinforces the hitter's uncertainty about zone boundaries.",
        "conditions": "Most effective against batters with high in-zone contact rates who become over-aggressive when protecting. Attenuates against hitters with elite zone coverage and low chase rates who force the pitcher back into the zone. Requires a secondary pitch (slider, changeup) that tunnels through the attack zone before breaking out.",
        "magnitude": "Whiff rate on expansion pitches in 0-2: 48-56% versus 28-36% in even counts. The combined probability of ending the PA via strikeout within two expansion pitches in a pitcher-ahead count is approximately 30-38%, versus 12-18% on zone pitches. Structurally the highest-efficiency sequencing state for limiting run production.",
        "links": ["first_pitch_strike_sequencing_anchor", "pitch_tunneling_sequence_pairs", "two_strike_putaway_sequence", "swing_decision_chain_within_pa"],
    },
    {
        "slug": "behind_in_count_recovery_path",
        "title": "Behind-in-Count Recovery Path",
        "summary": "Climbing back from a hitter-ahead count requires threading competitive get-me-over strikes that reclaim count parity while avoiding hittable middle-zone pitches, with the expected run value of recovery (even count) versus concession (walk or 3-1) determining how aggressively to push into the zone.",
        "stat_signature": "Get-me-over strike rate from 2-0: 60-68%; RE at 2-0: +0.115 above PA start; RE at 2-1: +0.063; at 3-0: +0.203. xwOBA on pitches thrown for strikes in 2-0 counts: .410-.440 (near-meatball range). Successful recovery to even from 2-0 in two pitches: 38-46% of PA.",
        "mechanism": "In a hitter-ahead count the pitcher must locate a competitive pitch or concede a walk-access count; the hitter knows this and sits fastball middle-out. Pitchers who recover from 2-0 do so with movement-focused pitches on the outer half that generate called strikes or weak pull attempts rather than true middle-zone fastballs.",
        "conditions": "Recovery path is steeper against patient hitters who sit on specific pitches rather than expanding early. Pitchers with elite command on secondary offerings can use a borderline changeup or cut fastball to avoid the meatball; pitchers relying on velocity alone are more likely to issue walks from hitter-ahead counts.",
        "magnitude": "xwOBA differential between a meatball recovery strike (.420) and a movement-based get-me-over (.260) is approximately .160 wOBA points per pitch. Over a season's worth of 2-0 situations, pitchers who can locate movement pitches in hitter-ahead counts suppress expected production by roughly 0.20-0.30 RE units compared to those who cannot.",
        "links": ["first_pitch_strike_sequencing_anchor", "two_strike_putaway_sequence", "pitch_count_attrition_sequence", "swing_decision_chain_within_pa"],
    },
    {
        "slug": "two_strike_putaway_sequence",
        "title": "Two-Strike Put-Away Sequence",
        "summary": "The pitch-type and location pairing used to finish a plate appearance from a two-strike count, where the setup pitch establishes a trajectory expectation that the putaway pitch violates, exploiting the hitter's committed swing decision.",
        "stat_signature": "Put-away rate (strikeout per two-strike count): 38-45% for above-average relievers; 28-35% for average starters. Tunnel-dependent putaway setups (same release, diverging break) lift whiff rate 8-14 pp versus non-tunneled sequences. Two-pitch-strikeout rate from 0-2 and 1-2: 22-28%.",
        "mechanism": "The putaway pitch exploits the hitter's mental model formed from the prior pitch's trajectory. A high fastball followed by a low-and-away slider shares the same early flight path before breaking away from the bat head, forcing a swing decision at a point where the two pitches are indistinguishable and the commitment happens before divergence.",
        "conditions": "Most effective when the setup pitch is borderline enough to require hitter commitment but not so hittable that a swing produces good contact. Attenuates when hitters recognize the tunnel pattern through repeated exposure within a game — the putaway becomes anticipated by the second or third time through the order.",
        "magnitude": "Whiff rate on optimally tunneled putaway pitches: 52-60% versus 34-42% on non-tunneled finishers. Strikeout probability from 0-2 with an elite putaway sequence is approximately 38-44%, versus 28-34% with a predictable or poorly located offering.",
        "links": ["pitch_tunneling_sequence_pairs", "ahead_in_count_expansion_chain", "first_pitch_strike_sequencing_anchor", "times_through_order_sequence_drift"],
    },
    {
        "slug": "pitch_tunneling_sequence_pairs",
        "title": "Sequential Pitch-Tunneling Pairs",
        "summary": "Back-to-back pitches that share release point and early flight path before diverging at the decision point force the hitter to commit based on incomplete trajectory information, degrading contact quality on the second pitch of the pair.",
        "stat_signature": "Tunnel-point distance threshold for maximum deception: under 3.5 inches at 17-foot decision point. Late-break separation (divergence by home plate): 8-14 inches between tunnel pairs. xwOBA on second pitch of optimally tunneled pair: .220-.255 versus .310-.340 on non-tunneled sequences. Barrel rate drops 3-5 pp on tunneled pairs.",
        "mechanism": "The hitter's commit decision occurs roughly 150-175 ms after pitch release, when the ball is approximately 17-20 feet from the plate and trajectory has been partially established but late break has not yet occurred. Two pitches sharing the early trajectory window exploit this timing constraint — the hitter swings or takes based on the shared path, then the late break determines whether the decision was optimal.",
        "conditions": "Requires a pitcher with two or more pitch types that share a genuine release-point cluster (not merely the same slot). Breaks down when the secondary pitch has a markedly different arm slot or earlier visible spin that allows early differentiation. Hitters with elite spin-recognition skills read the tunnel earlier and reduce the timing advantage.",
        "magnitude": "Barrel rate and hard-hit rate on the second pitch of a well-tunneled pair are 3-5 pp below same-pitcher non-tunneled sequences. Over a full sequence structure, pitchers who generate tunnel pairs on 35%+ of back-to-back offerings suppress wOBA by approximately .025-.040 relative to those who throw each pitch in isolation.",
        "links": ["two_strike_putaway_sequence", "ahead_in_count_expansion_chain", "fastball_offspeed_eye_level_ladder", "high_leverage_at_bat_sequencing"],
    },
    {
        "slug": "fastball_offspeed_eye_level_ladder",
        "title": "Eye-Level and Velocity Ladder Sequencing",
        "summary": "Intentional vertical sequencing (elevated hard pitch followed by a low-and-slow offering, or vice versa) exploits the hitter's eye-tracking adjustment time and the velocity-gap-induced timing disruption between adjacent pitches.",
        "stat_signature": "Swing-timing error (early contact) on a changeup following a fastball with velocity gap of 10+ mph: increases by 18-26 ms versus a same-speed sequence. Chase rate on a low changeup after a high fastball: 38-48%. Average launch angle on velocity-gap sequences: 4-8 degrees flatter (pulled-down bat path).",
        "mechanism": "After a high fastball the hitter's eyes and bat path are calibrated to a trajectory arriving at shoulder height with velocity above 92 mph. A subsequent low-and-away changeup at 80-84 mph arrives 55-70 ms later than the calibrated expectation and 18-24 inches lower, producing a swing that is both early in timing and downward in path — both properties degrade contact quality simultaneously.",
        "conditions": "Effective when the two pitches flanking the sequence are far apart in velocity and vertical location. Diminishes when the changeup is in the middle-in zone, where the timing error still produces solid contact due to the favorable contact point. Requires reliable command on both ends of the ladder.",
        "magnitude": "Hard-hit rate (exit velocity above 95 mph) on changeups following 94+ mph fastballs drops approximately 6-9 pp versus changeups thrown after slower fastballs or in isolation. Whiff-or-weak-contact rate on the ladder pair: 54-62% versus 38-46% on non-sequenced changeup delivery.",
        "links": ["pitch_tunneling_sequence_pairs", "two_strike_putaway_sequence", "ahead_in_count_expansion_chain", "swing_decision_chain_within_pa"],
    },
    {
        "slug": "times_through_order_sequence_drift",
        "title": "Times-Through-the-Order Sequencing Drift",
        "summary": "As a starting pitcher faces the lineup repeatedly within a game, hitters accumulate sequencing intelligence that reduces pitch-type entropy and raises expected run value, causing a measurable drift in effectiveness across successive turns through the order.",
        "stat_signature": "wOBA allowed TTO1: .295-.315; TTO2: .315-.335; TTO3: .345-.375 for median starters. Pitch-type entropy (Shannon) declines 0.12-0.18 bits from TTO1 to TTO3 as pitchers telegraph tendencies. Fastball usage frequency rise on 0-0 counts in TTO3: 4-7 pp above TTO1 baseline.",
        "mechanism": "Each plate appearance gives a hitter a richer sample of the pitcher's sequence patterns, velocity band, and count tendencies. By the third time through, hitters have seen the pitcher in every major count context and can pre-load expectations more accurately, reducing the deception value of tunnels and expansion sequences that were effective in earlier encounters.",
        "conditions": "Drift is steepest for pitchers relying on one or two primary sequences (low pitch-type variety) and pitchers with a dominant count-specific tell (e.g., always curveball in 1-2). Pitchers with four or more distinct offerings and randomized count sequences show smaller TTO degradation. The effect is compressed in high-strikeout arm profiles.",
        "magnitude": "Expected run value rises roughly 0.018-0.030 per plate appearance from TTO1 to TTO3, accumulating to 0.45-0.75 expected runs per game over a nine-lineup-slot exposure. Teams managing starter removal around TTO3 avoid the entropy-decline window by replacing the familiar sequence with an opaque relieving arm.",
        "links": ["first_pitch_strike_sequencing_anchor", "two_strike_putaway_sequence", "bullpen_handoff_sequence_break", "pitch_count_attrition_sequence"],
    },
    {
        "slug": "leadoff_on_base_rally_construction",
        "title": "Leadoff-On-Base Rally Construction",
        "summary": "A leadoff baserunner in any inning shifts the run-expectancy baseline sharply upward and restructures the pitcher's sequence logic, as the threat of advancement compounds the decision pressure on each subsequent pitch and plate appearance.",
        "stat_signature": "Run-expectancy with leadoff runner on first: ~0.851 versus ~0.461 with bases empty. Scoring probability from leadoff-on-first: 38-42%. Pitcher fastball rate drops 3-5 pp with a runner on first (more breaking balls to induce grounders). Inning-run total when leadoff reaches: 1.28-1.42 versus 0.46-0.52 when leadoff is retired.",
        "mechanism": "The leadoff runner forces the pitcher to split attention between the runner (delivery time, pickoff rhythm) and the hitter's pitch sequence, which in practice shortens delivery times and restricts secondary-pitch usage. The subsequent batters gain a small but real count and sequencing dividend from the pitcher's constrained arsenal.",
        "conditions": "Rally-construction effect is greatest when the leadoff runner is a threat to advance on contact, amplifying the number of pitches the subsequent hitter sees in even or hitter-favorable counts. Attenuates when the leadoff runner is immobile or the pitcher has an elite pickoff move that neutralizes the secondary distraction.",
        "magnitude": "Scoring probability nearly doubles versus a leadoff out (39% versus 27%). Over a season, converting leadoff walks into outs at the plate-appearance level reduces expected runs per inning by approximately 0.35-0.40 runs — the single highest-leverage outs in any half-inning.",
        "links": ["two_out_rally_extension_chain", "lineup_turnover_sequencing", "rbi_opportunity_conversion_chain", "station_to_station_versus_chain_hitting"],
    },
    {
        "slug": "two_out_rally_extension_chain",
        "title": "Two-Out Rally-Extension Chain",
        "summary": "Chaining consecutive on-base events after two outs are recorded converts a structurally low-probability run-scoring state into a meaningful output through sequential plate-appearance success, with each additional baserunner compounding run-expectancy nonlinearly.",
        "stat_signature": "Scoring probability with two outs and bases empty: 8-10%. With two outs and runner on second: 22-26%. Each additional baserunner with two outs adds 12-18 pp to scoring probability. Two-out RBI rate (runs per PA) for the slot following a two-out baserunner: .085-.110 versus .048-.060 with bases empty and two outs.",
        "mechanism": "With two outs, pitchers can attack the zone more aggressively because an out ends the inning and there is no partial-credit advancement. However, a baserunner shifts the run-scoring distribution: the same plate-appearance outcome (single) now scores a run rather than merely advancing a runner. Chaining two consecutive two-out hits or walks creates an inning-within-an-inning where each subsequent hitter faces a pitcher under compounding pressure.",
        "conditions": "Chain construction is most durable when the batting order cycles through contact-oriented slots after two outs, or when the pitcher is in a late-count degradation state. Breaks down against relievers with above-average two-strike putaway rates, who interrupt chains efficiently.",
        "magnitude": "Two-out runs represent approximately 24-28% of total MLB runs scored despite the structural odds. Teams that sustain two-out on-base rates 15+ pp above the bases-empty two-out baseline generate a measurable per-game run surplus across a 162-game season.",
        "links": ["leadoff_on_base_rally_construction", "rbi_opportunity_conversion_chain", "lineup_turnover_sequencing", "contact_quality_sequence_in_inning"],
    },
    {
        "slug": "station_to_station_versus_chain_hitting",
        "title": "Sequential Run-Scoring Construction Modes",
        "summary": "Scoring innings differ structurally depending on whether runs accumulate through a chain of consecutive on-base events (singles, walks, hit batters) or through isolated extra-base power sequences that collapse the runner-advance chain into one or two swings.",
        "stat_signature": "Innings producing 2+ runs from chained singles and walks: average PA-per-run ~3.8-4.2. Power-mode innings (XBH-driven): average PA-per-run ~2.0-2.6. Share of multi-run innings from consecutive-contact construction: 45-52%. Hard-contact-mode innings have higher run-scoring ceiling but lower frequency at lower run-environment contexts.",
        "mechanism": "Chained construction requires multiple consecutive plate-appearance successes and is thus sensitive to interruption by any out. Power construction concentrates scoring in fewer plate appearances, reducing the cumulative probability required but demanding elite contact outcomes. The two modes interact with pitcher strategy: power lineups induce more fastball-avoidance sequencing while chain-contact lineups see more zone-attack strategies aimed at groundball outs.",
        "conditions": "Chain construction dominates in low-velocity contact environments and ballparks suppressing extra-base hits. Power construction dominates in hitter-friendly contexts with high-exit-velocity lineups. Pitcher strategy adapts to mode: soft-toss and off-speed-heavy sequencing suppresses the chain mode more effectively than velocity.",
        "magnitude": "The structural difference between the two modes is primarily in inning run-variance: power-mode innings produce more zero-run and multi-run outcomes (bimodal), while chain-mode innings produce more single-run outcomes. Run-per-inning expected value is similar at similar talent levels, but inning-run variance differs by approximately 0.35-0.55 runs.",
        "links": ["leadoff_on_base_rally_construction", "rbi_opportunity_conversion_chain", "two_out_rally_extension_chain", "lineup_turnover_sequencing"],
    },
    {
        "slug": "contact_quality_sequence_in_inning",
        "title": "In-Inning Contact-Quality Sequencing",
        "summary": "Exit-velocity and barrel outcomes cluster across consecutive plate appearances within an inning as pitcher fatigue and hitter familiarity accumulate, producing a measurable serial correlation of hard-hit events that is distinct from random sampling of individual talent rates.",
        "stat_signature": "Serial correlation of hard-hit events (exit velocity above 95 mph) across consecutive same-inning PA: r = 0.08-0.14. Barrel rate rises approximately 1.5-2.5 pp per 10 additional pitches thrown within the same inning by the same pitcher. Exit velocity mean rises 0.8-1.4 mph from the first to the fifth PA in the same inning.",
        "mechanism": "As a pitcher accumulates pitches within a single inning, release-point consistency degrades marginally, fastball command narrows, and the velocity band tightens. Simultaneously, each successive hitter adds one more within-game data point on the pitcher's sequence tendencies, compounding familiarity across the lineup. These two effects produce a within-inning rise in contact quality that is small per PA but statistically consistent.",
        "conditions": "The serial correlation effect is largest when a pitcher faces four or more batters in the same inning and when the inning extends beyond 20 pitches. It attenuates sharply when the pitcher escapes the inning quickly with strikeouts and grounders in the early PA sequence. Pitchers with above-average pitch efficiency suppress the familiarity accumulation effect.",
        "magnitude": "Barrel rate rises from approximately 8.5% on the first PA of a long inning to 10.0-11.5% by the fifth PA. The total incremental hard-contact probability over a five-PA inning relative to five isolated PA is approximately 0.08-0.15 percentage points — small per event but meaningful in aggregate over a full season.",
        "links": ["times_through_order_sequence_drift", "pitch_count_attrition_sequence", "bullpen_handoff_sequence_break", "two_out_rally_extension_chain"],
    },
    {
        "slug": "high_leverage_at_bat_sequencing",
        "title": "Late-Inning Leverage Sequence Shift",
        "summary": "As plate-appearance leverage rises in late innings, pitch-location distributions contract toward high-whiff zones and best-pitch frequency increases, reflecting the pitcher's rational shift toward maximizing strikeout probability over any other outcome.",
        "stat_signature": "Best-pitch usage rate (pitcher's primary whiff weapon) in LI above 2.0: 38-46% versus 28-34% in LI under 1.0. Location distribution SD (zone tightness) contracts by 8-12% in high-leverage appearances. Swing-and-miss rate in LI above 2.0: 12-15% versus 10-12% in neutral LI. Walk rate also rises 1.5-2.5 pp (narrower location tolerance).",
        "mechanism": "In leverage states where a single baserunner or run changes win probability materially, the pitcher accepts the higher-walk risk of pitching to corners rather than throwing get-me-over offerings in the zone. The strikeout becomes the primary defensive outcome because its run-prevention certainty exceeds even a weak-contact out in a bases-loaded state.",
        "conditions": "The sequence shift is most pronounced for relievers with clear best-pitch profiles. Starters show a smaller shift due to pitch-count management considerations. Hitters in high-leverage states anticipate the location contraction and shift their attack zones accordingly, partially offsetting the pitcher's advantage.",
        "magnitude": "Strikeout rate in very-high-leverage (LI above 2.5) appearances by elite relievers: 32-40% versus 26-32% in neutral outings. The run-prevention value of the sequencing shift in a bases-loaded one-run game is approximately 0.12-0.18 RE units per PA relative to neutral-leverage sequencing.",
        "links": ["two_strike_putaway_sequence", "pitch_tunneling_sequence_pairs", "first_pitch_strike_sequencing_anchor", "bullpen_handoff_sequence_break"],
    },
    {
        "slug": "pitch_count_attrition_sequence",
        "title": "Pitch-Count Attrition Sequence",
        "summary": "As a starter accumulates pitches within a game, release-point drift, velocity decline, and sequence predictability increase nonlinearly, creating an identifiable inflection point where the expected-run-value per plate appearance rises above the replacement threshold.",
        "stat_signature": "Fastball velocity decline: approximately -0.4 to -0.7 mph per 30 pitches thrown. Release-point vertical spread widens 0.3-0.6 inches from pitch 1-30 versus pitch 76-100. wOBA allowed rises from .295-.310 in pitches 1-60 to .325-.350 in pitches 76-100. Typical inflection for average starter: 85-95 pitches.",
        "mechanism": "Physical fatigue narrows the velocity band and degrades the release-point consistency that enables tunnel-dependent sequences. As the pitcher's command window widens, pitches drift toward the middle of the zone and the separation between tunnel pairs collapses. Simultaneously, hitters have accumulated multiple PA of data on the starter's sequencing tendencies, compressing the remaining deception value.",
        "conditions": "Attrition curve steepens for pitchers with high-effort mechanics and for starts in extreme heat or humidity. Starting pitchers who rely on pure velocity show earlier and steeper declines than those who rely on command and sequence variety. Short-rest starts accelerate the inflection point by 10-15 pitches.",
        "magnitude": "Expected runs allowed per nine from pitches 76-100 is approximately 0.8-1.2 runs higher than from pitches 1-60 for median starters. For the bottom third of the starter distribution the gap widens to 1.5-2.0 runs per nine — the empirical basis for the modern 100-pitch-limit convention.",
        "links": ["times_through_order_sequence_drift", "bullpen_handoff_sequence_break", "contact_quality_sequence_in_inning", "first_pitch_strike_sequencing_anchor"],
    },
    {
        "slug": "bullpen_handoff_sequence_break",
        "title": "Bullpen-Handoff Sequencing Break",
        "summary": "A mid-game pitching change resets the within-game sequencing context: the new arm's pitch repertoire, velocity band, arm angle, and count tendencies are unfamiliar to hitters who have been building a sequence model against the prior pitcher, producing an entropy spike in the plate appearances immediately after the change.",
        "stat_signature": "wOBA allowed in first PA faced by a reliever (without batter prior exposure): .270-.290. wOBA in second and subsequent PA same game: .300-.320. Pitch-type entropy (new arm): resets to near-maximum for all batters. Effective-velocity differential between starter and reliever (velocity bump): average +2.4-3.8 mph for modern high-leverage relievers.",
        "mechanism": "The hitter's sequence model is batter-pitcher specific: it accumulates within-game pitch-type and location tendencies from real PA data. When the relief arm enters, the accumulated model is invalidated. The unfamiliar release angle, velocity, and movement profile force the hitter to re-initialize their decision framework from scratch, typically requiring 1-2 PA to rebuild a working model.",
        "conditions": "The entropy spike is largest when the new arm is a high-velocity short-armer replacing a soft-toss or command-based starter, creating a large velocity and arm-slot differential. The reset effect diminishes when the reliever has faced the lineup multiple times earlier in the season, giving hitters pre-existing sample data.",
        "magnitude": "The first-PA wOBA advantage of a fresh reliever versus the same arm's second and subsequent PA is approximately .020-.035 wOBA points — meaningful per plate appearance and justifying the modern practice of entering relievers before, not during, a lineup slot that has already seen the arm once.",
        "links": ["times_through_order_sequence_drift", "pitch_count_attrition_sequence", "high_leverage_at_bat_sequencing", "contact_quality_sequence_in_inning"],
    },
    {
        "slug": "rbi_opportunity_conversion_chain",
        "title": "Runners-in-Scoring-Position Conversion Chain",
        "summary": "Consecutive plate appearances with a runner in scoring position form a conversion chain where the run-scoring probability is determined by the cumulative success of the sequenced at-bats, with each missed conversion leaving the chain incomplete and resetting the probability structure.",
        "stat_signature": "MLB RISP conversion rate (runs scored per RISP PA): approximately .205-.225. Chain extension rate (next batter also reaches with RISP still occupied after a non-scoring hit): 28-34%. Consecutive two-out RISP PAs that produce a run: 18-22%. Clutch-hit rate in high-LI RISP context: statistically indistinguishable from neutral-LI RISP across multi-season samples.",
        "mechanism": "The conversion chain is structurally a sequential Bernoulli process where each plate appearance with RISP is an independent draw (given pitcher-hitter talent) from a run-scoring probability distribution. The apparent clustering of RISP production is primarily team-level talent effects (lineup quality, on-base ability) rather than a distinct sequencing mechanism beyond the accumulated probability.",
        "conditions": "Conversion chains are most productive when the scoring-position runner is followed by above-average contact hitters who keep the chain alive rather than ending it with a strikeout. Pitcher strategy shifts to out-of-zone expansion to induce chases and break the chain, which interacts directly with the ahead-in-count expansion mechanism.",
        "magnitude": "A team converting at the top quartile RISP rate (.240+) versus the bottom quartile (.185-) generates approximately 35-55 additional runs over a full season — entirely consistent with team quality differences rather than an independent sequencing effect. The conversion rate is descriptive of lineup quality, not a predictive variable beyond talent.",
        "links": ["leadoff_on_base_rally_construction", "two_out_rally_extension_chain", "station_to_station_versus_chain_hitting", "high_leverage_at_bat_sequencing"],
    },
    {
        "slug": "swing_decision_chain_within_pa",
        "title": "Within-PA Swing-Decision Chain",
        "summary": "A hitter's take-or-swing sequence across the pitches of a plate appearance follows a count-conditional decision tree where early pitch outcomes shape the zone-management strategy for subsequent pitches, producing a measurable path-dependency between the first pitch decision and the eventual plate-appearance outcome.",
        "stat_signature": "Swing rate in 0-0 count: 28-32%. Swing rate after a called-strike-one: 38-44%. Swing rate after a ball-one: 22-26%. PA-outcome predictability from 2-PA pitch-path (first two outcomes): r = 0.18-0.24 with final outcome. Zone-in contact rate on 2-0 swing: .340-.360 wOBA; non-swing 2-0: .300-.320 wOBA (next pitch).",
        "mechanism": "Each swing-or-take decision updates the count and the hitter's internal model of the pitcher's sequence. A take on a borderline pitch narrows the subsequent count window if called a strike, forcing a protection stance. A swing and miss commits the hitter to a two-strike defense mode. The chain structure means that early PA decisions have compounding effects on the distribution of outcomes available at each subsequent pitch.",
        "conditions": "Path-dependency is strongest for hitters who adjust zone management based on count (disciplined hitters) versus those who apply a consistent swing trigger regardless of count (low-discipline hitters, who exhibit weaker path-dependence). Against pitchers who vary sequence patterns by count, the within-PA decision chain becomes more complex and the hitter's early decisions are higher-stakes.",
        "magnitude": "The difference in wOBA between hitters who take called-ball-one and subsequently reach favorable counts versus those who swing at 0-0 and miss is approximately .035-.055 wOBA points per plate appearance — the structural value of count discipline measured across a full plate-appearance decision chain.",
        "links": ["first_pitch_strike_sequencing_anchor", "ahead_in_count_expansion_chain", "behind_in_count_recovery_path", "two_strike_putaway_sequence"],
    },
]
