"""ClosingExecution NBA concept nodes — person-free.

Scope: the ACT of CLOSING OUT a contest — converting an established late-game
position into a finished result.  This family is about EXECUTION QUALITY and the
conversion / collapse SIGNATURES of the closing act itself (how a lead is seen
out, how a free-throw close is executed, how a comeback is finished or fumbled),
deliberately distinct from:
  - GamePhases (which DEFINES the clutch / Q4 windows as time bands), and
  - SpecialSituations (which DEFINES the dead-ball / intentional-foul / FT-icing
    STATES and their EV math).
Here every node measures the *finishing behaviour* — closeout conversion rates,
choke gradients, decision-quality of the close — not the state definition.
"""
from __future__ import annotations

SPORT = "NBA"
FAMILY = "ClosingExecution"

CONCEPTS = [
    {
        "slug": "lead_closeout_conversion_rate",
        "title": "Late-Lead Closeout Conversion Rate",
        "summary": "The empirical probability a team finishes a win once it holds a given lead inside a fixed time window, benchmarked against the win-probability model so that under- or over-conversion is a pure finishing-execution residual.",
        "stat_signature": "Conversion of a 5-point lead at 3:00 remaining: ~84-90%; of an 8-point lead: ~94-97%; closeout residual = realised win rate minus model-implied win probability, with stable team-level deviations of +/-2-4 pp across a season.",
        "mechanism": "Holding a lead requires executing a different objective (deny easy looks, secure the ball, draw fouls) than building one; teams whose late offence collapses into isolation and whose late defence over-helps convert established leads below their win-probability entitlement, exposing a finishing-skill gap separate from overall quality.",
        "conditions": "Most diagnostic for leads of 4-9 points where the outcome is genuinely in doubt; uninformative above ~12 points (near-certain) or below 3 (coin-flip); amplified on the road where crowd and whistle pressure raise execution variance.",
        "magnitude": "A persistent -3 pp closeout residual over a season corresponds to roughly two to three converted wins turned into losses from finishing alone, descriptively independent of net rating.",
        "links": ["blown_lead_collapse_signature", "shot_selection_decay_when_ahead", "closing_lineup_net_rating", "milk_the_clock_execution", "free_throw_closeout_reliability"],
    },
    {
        "slug": "blown_lead_collapse_signature",
        "title": "Blown-Lead Collapse Signature",
        "summary": "The characteristic statistical fingerprint of a surrendered late lead: a self-reinforcing run of empty offensive possessions, turnovers, and conceded threes that compresses a comfortable margin to a one-possession game.",
        "stat_signature": "A collapse sequence shows offensive rating dropping 25-40 pts/100 below the team's late-game baseline over a 4-6 possession span, turnover rate spiking to 18-24%, and opponent three-rate rising 8-12 pp as the lead evaporates.",
        "mechanism": "Possession-value loss compounds: a turnover or quick miss while protecting a lead gifts the trailing team transition or extra possessions exactly when the leading team has slowed its own pace, so margin erosion accelerates faster than either team's underlying efficiency implies.",
        "conditions": "Most frequent when a lead is built on unsustainable variance (a hot three-point stretch) rather than rim and free-throw pressure; intensified against high-pace trailing teams that hunt threes and force tempo.",
        "magnitude": "Conditional on a collapse-pattern start, the probability the lead reaches a one-possession game within two minutes is roughly 2-3x the base rate for an equivalent margin, a strong within-game momentum-asymmetry signal.",
        "links": ["lead_closeout_conversion_rate", "shot_selection_decay_when_ahead", "turnover_proneness_under_pressure", "comeback_finishing_execution", "scoring_drought_under_lead_protection"],
    },
    {
        "slug": "shot_selection_decay_when_ahead",
        "title": "Shot-Selection Decay When Protecting a Lead",
        "summary": "The systematic drift toward lower-quality, clock-killing isolation attempts once a team is ahead late, measured as a fall in expected points per shot relative to the same team's flow-of-game shot profile.",
        "stat_signature": "Expected points per shot drops ~0.06-0.12 in lead-protection possessions versus mid-game; rim-and-corner-three share falls 8-14 pp while late-clock contested mid-range share rises 10-18 pp; assisted-field-goal rate declines 12-20 pp.",
        "mechanism": "Lead protection re-prioritises clock consumption over shot quality, funnelling the ball to a primary creator for late-clock isolation; this trades the team's efficient flow offence for a lower-variance but lower-mean shot diet, suppressing realised points exactly when the opponent is mounting pressure.",
        "conditions": "Most pronounced in teams reliant on one ball-dominant creator; muted in motion-heavy systems that retain off-ball actions even while milking clock; sharpened against switch-everything defences that turn isolations into stalled contested jumpers.",
        "magnitude": "The 0.06-0.12 efficiency drop across a handful of closing possessions equals roughly 1-2 expected points sacrificed, materially shrinking the cushion against a trailing team still attacking efficiently.",
        "links": ["blown_lead_collapse_signature", "milk_the_clock_execution", "isolation_reliance_in_closeout", "scoring_drought_under_lead_protection", "lead_closeout_conversion_rate"],
    },
    {
        "slug": "milk_the_clock_execution",
        "title": "Clock-Milking Execution Quality",
        "summary": "How efficiently a leading team converts late shot-clock possessions while deliberately consuming game clock, captured as points per possession on possessions intentionally held to a late shot-clock release.",
        "stat_signature": "Points per possession on lead-protection possessions released in the final 6 shot-clock seconds: ~0.86-0.98 versus ~1.02-1.10 in matched mid-game late-clock possessions; shot-clock-violation rate rises to ~3-5% from a ~1% baseline.",
        "mechanism": "Trading game clock for shot quality is only net-positive when the possession still produces a near-average attempt; teams that bleed clock but generate a panicked heave forfeit both the possession's points and the next defensive stop's value, so execution quality on held possessions decides whether clock-milking helps or hurts.",
        "conditions": "Effective with a creator who can manufacture a quality look from a late-clock action; degraded against ball-pressure defences that force the held possession into a turnover or violation; most relevant with a 4-8 point lead and 3-5 minutes left.",
        "magnitude": "Teams in the top decile of late-clock closeout points per possession preserve roughly 0.1-0.15 more expected points per held possession than bottom-decile teams, compounding across multiple closing trips.",
        "links": ["shot_selection_decay_when_ahead", "lead_closeout_conversion_rate", "possession_value_late_game_execution", "scoring_drought_under_lead_protection", "advance_to_quick_two_decision"],
    },
    {
        "slug": "free_throw_closeout_reliability",
        "title": "Free-Throw Closeout Reliability",
        "summary": "A team's realised free-throw conversion specifically in late-and-close foul-game situations, where a leading team must sink fronts of one-and-ones and bonus pairs to ice the result against deliberate fouling.",
        "stat_signature": "Late-and-close free-throw percentage typically tracks within +/-2-4 pp of the team's season rate but with sharply higher variance; the probability of converting both ends of a bonus trip when leading by 3-4 inside 30 seconds is ~0.62-0.74 for an average free-throw team.",
        "mechanism": "The intentional-foul endgame converts the close into a free-throw shooting contest; a leading team's expected margin is governed less by field-goal offence than by which players are on the floor to be fouled and their conversion under maximal pressure, making line reliability the dominant closing lever.",
        "conditions": "Decisive when the trailing team fouls within the rational deficit-and-time corridor; magnified when the leading team's best free-throw shooters are off the floor for defence or rest; crowd-noise pressure on the road widens the variance band.",
        "magnitude": "The difference between a 60% and an 80% closing free-throw unit converts to roughly a 1-1.5 point swing in expected closing margin per foul-game sequence, frequently the decisive quantity in one-possession finishes.",
        "links": ["lead_closeout_conversion_rate", "deliberate_foul_target_avoidance", "closing_lineup_net_rating", "pressure_free_throw_variance", "icing_resistance_routine"],
    },
    {
        "slug": "deliberate_foul_target_avoidance",
        "title": "Deliberate-Foul Target Avoidance",
        "summary": "The leading team's success at keeping the ball away from its weakest free-throw shooter during the foul game, measured by which player actually absorbs the fouls relative to roster free-throw quality.",
        "stat_signature": "Share of intentional-foul free throws taken by a team's worst rotational free-throw shooter: ~18-30% under poor ball-protection versus ~6-12% under disciplined hand-off-and-shield execution; inbound-completion rate against full-court pressure: ~88-94%.",
        "mechanism": "Once a trailing team commits to hacking, the leading team's job is to route possession through capable free-throw shooters via designed inbounds and quick hand-offs; failure to shield the weak shooter converts a near-certain two points into a sub-1.0-PPP trip, directly reversing the foul-game EV.",
        "conditions": "Relevant whenever a sub-55% free-throw shooter must stay on the floor for defence or rebounding; hardest against pressure that denies the inbound and forces the ball into the targeted hands; eased by anti-hack rules in specific late states.",
        "magnitude": "Disciplined target avoidance can lift the leading team's per-foul expected points by 0.25-0.40 relative to repeatedly conceding the weak shooter, a swing that accumulates across a multi-foul sequence.",
        "links": ["free_throw_closeout_reliability", "inbound_under_full_court_pressure", "lead_closeout_conversion_rate", "closing_lineup_net_rating"],
    },
    {
        "slug": "closing_lineup_net_rating",
        "title": "Closing-Lineup Net Rating",
        "summary": "The net efficiency of the specific five a coach trusts in the final minutes of close games, isolating finishing-unit quality from full-roster quality and from starter net rating.",
        "stat_signature": "Closing-lineup net rating (clutch minutes only) ranges from roughly -15 to +20 pts/100 across teams; its gap from the team's overall net rating is the diagnostic, with elite closers running +8-12 pts/100 above their non-clutch baseline.",
        "mechanism": "Closing demands a particular skill blend — shot creation under pressure, free-throw reliability, switch-defence integrity — that does not coincide with overall lineup value; coaches who can field a unit optimised for that blend convert close games above their season profile, while those forced to close with a flawed unit underconvert.",
        "conditions": "Most informative in the subset of games still within five points inside five minutes; distorted by small-sample variance, so multi-season pooling stabilises the signal; depends heavily on whether a primary creator and a reliable free-throw shooter coexist in the unit.",
        "magnitude": "A closing unit running +10 pts/100 above the team baseline converts a meaningfully higher share of toss-up games than the roster's overall quality predicts, a durable finishing-execution differentiator.",
        "links": ["lead_closeout_conversion_rate", "free_throw_closeout_reliability", "clutch_shot_creation_burden", "defensive_stop_rate_when_protecting", "comeback_finishing_execution"],
    },
    {
        "slug": "clutch_shot_creation_burden",
        "title": "Clutch Shot-Creation Burden",
        "summary": "The concentration of late-and-close scoring load onto a single creator and the efficiency that initiator sustains under that burden, quantifying how reliant a team's close is on one player generating a shot against a set defence.",
        "stat_signature": "Top-creator usage in clutch minutes: ~32-44% versus ~26-32% non-clutch; that creator's clutch true-shooting typically sits 3-6 pp below their season mark as defences load the strong side; assisted share of clutch makes falls to ~28-38%.",
        "mechanism": "Defences in the closing minutes scheme to deny the primary option and force secondary creators to beat them; a team whose close depends on one initiator faces predictable, gap-loaded coverages that depress that player's efficiency, whereas multi-initiator closes preserve unpredictability and shot quality.",
        "conditions": "Most acute against switch-and-load defences that can wall off one star; mitigated by a credible second creator or off-ball gravity; amplified in playoff settings where opponents pre-scout the primary closing action.",
        "magnitude": "The 3-6 pp clutch efficiency drop on a heavily loaded creator translates to a measurable reduction in expected points on the most important possessions, partly offsetting the value of concentrating the ball in the best player's hands.",
        "links": ["isolation_reliance_in_closeout", "closing_lineup_net_rating", "shot_selection_decay_when_ahead", "comeback_finishing_execution", "after_timeout_closeout_set_quality"],
    },
    {
        "slug": "isolation_reliance_in_closeout",
        "title": "Isolation Reliance in the Closeout",
        "summary": "The degree to which a team abandons motion for one-on-one play in the final minutes, and the efficiency penalty that shift carries relative to its flow offence, as a structural property of how that team finishes.",
        "stat_signature": "Isolation play-type frequency rises from a ~8-12% game baseline to ~22-34% in clutch minutes; isolation points per possession (~0.86-0.96) trails the team's overall half-court mark (~0.98-1.06) by ~0.08-0.14.",
        "mechanism": "Late-game offences default to isolation for clock control and to put the ball in the best creator's hands, but isolation is a lower-mean play type that lets a set defence pre-commit; the heavier a team leans on it to close, the more it forfeits the efficiency edge its flow offence holds.",
        "conditions": "Strongest in teams without reliable late-clock secondary actions; reduced in systems that maintain dribble-handoff and screen flow into the final minute; punished hardest by elite point-of-attack defenders who can guard isolation without help.",
        "magnitude": "A team closing with a +20 pp isolation-frequency jump and a 0.10-PPP efficiency drop sacrifices roughly 1-2 expected points across its closing possessions versus maintaining flow, a recurring finishing-style cost.",
        "links": ["clutch_shot_creation_burden", "shot_selection_decay_when_ahead", "after_timeout_closeout_set_quality", "milk_the_clock_execution"],
    },
    {
        "slug": "defensive_stop_rate_when_protecting",
        "title": "Defensive Stop-Rate When Protecting a Lead",
        "summary": "How reliably a leading team gets stops in the final minutes, where the objective shifts to denying easy twos and contesting threes without fouling, distinct from the team's general defensive rating.",
        "stat_signature": "Stop rate on lead-protection defensive possessions: ~52-60% for strong closing defences versus ~44-50% for weak ones; conceded three-rate and shooting-foul rate are the dominant leak channels, the latter rising 4-8 pp above baseline under no-foul discipline.",
        "mechanism": "Protecting a lead requires walking the line between aggressive contests and foul avoidance while denying the trailing team the threes and free throws that compress margins fastest; defences that over-help leak corner threes, and defences that grab leak free throws, so stop-rate under this constraint is a specific finishing competency.",
        "conditions": "Most tested against trailing teams that hunt threes and draw fouls; degraded by foul-trouble among key defenders; sharpened by switchable personnel who can contest without rotating.",
        "magnitude": "An 8-10 pp swing in lead-protection stop rate over a handful of closing possessions is frequently the difference between a comfortable finish and a one-possession scramble, independent of season-long defensive rank.",
        "links": ["closing_lineup_net_rating", "lead_closeout_conversion_rate", "no_foul_contest_discipline", "blown_lead_collapse_signature"],
    },
    {
        "slug": "no_foul_contest_discipline",
        "title": "No-Foul Contest Discipline",
        "summary": "A defence's ability to contest shots in the closing minutes without sending the offence to the line, measured by the ratio of contested attempts to shooting fouls in lead-protection possessions.",
        "stat_signature": "Contest-to-shooting-foul ratio in clutch defence: ~6:1 for disciplined units versus ~3:1 for foul-prone ones; clutch shooting-foul rate per 100 closing possessions varies by 5-9 between the cleanest and most foul-prone closing defences.",
        "mechanism": "A late shooting foul converts a contested low-probability shot into ~1.5 near-certain points and stops the clock for the trailing team; defences that contest with verticality and footwork preserve the clock-and-efficiency advantage of a lead, while reach-and-grab defences hand it back at the worst moment.",
        "conditions": "Hardest against shot-fakers and foul-drawing specialists who hunt contact late; most valuable when the trailing team is in the penalty; eroded by fatigue and foul-trouble that slow defensive feet.",
        "magnitude": "Cutting one or two late shooting fouls per close game saves roughly 1.5-3 expected points and several clock stoppages, a direct contributor to lead-closeout conversion.",
        "links": ["defensive_stop_rate_when_protecting", "free_throw_closeout_reliability", "lead_closeout_conversion_rate", "deliberate_foul_target_avoidance"],
    },
    {
        "slug": "comeback_finishing_execution",
        "title": "Comeback-Finishing Execution",
        "summary": "The trailing team's efficiency in actually completing a comeback once it has cut a deficit to one possession, the mirror image of lead closeout, capturing whether a rally is finished or stalls at the threshold.",
        "stat_signature": "Conditional on cutting a deficit to one possession inside two minutes, the probability of completing the comeback to a tie-or-lead is ~30-42%; finishing teams show a positive late three-point-attempt-quality and a sub-15% turnover rate over the final possessions.",
        "mechanism": "The last stretch of a comeback is the hardest because the leading defence is set and focused while the trailing offence must generate quality without the clock; teams that maintain shot discipline and avoid hero-ball at the threshold convert a higher share of near-comebacks than those that force low-quality threes.",
        "conditions": "Most achievable when the comeback is built on stops rather than fouling (preserving clock); hardest against disciplined no-foul defences; aided by a creator who can generate a clean look against a set defence.",
        "magnitude": "A 10 pp gap in threshold-conversion rate between strong and weak finishing teams represents a meaningful number of completed comebacks across a season, a finishing-skill signal distinct from the comeback's start.",
        "links": ["blown_lead_collapse_signature", "lead_closeout_conversion_rate", "clutch_shot_creation_burden", "intentional_foul_comeback_arithmetic", "three_for_the_tie_versus_two"],
    },
    {
        "slug": "intentional_foul_comeback_arithmetic",
        "title": "Intentional-Foul Comeback Arithmetic Execution",
        "summary": "The trailing team's execution quality within the foul-and-recover sequence — fouling instantly, securing the rebound on a missed front end, and scoring quickly — that determines whether the rational foul game actually narrows the gap.",
        "stat_signature": "Time elapsed per intentional-foul cycle for efficient teams: ~4-7 seconds versus ~9-13 for slow execution; defensive-rebound capture on opponent free-throw misses: ~78-84%; trailing-team points per recovered possession in the foul game: ~1.0-1.1.",
        "mechanism": "The foul game's positive expectation depends entirely on execution speed and rebounding: a foul committed a few seconds late, a missed box-out on a front-end miss, or a slow ensuing possession each forfeit the slim margin the strategy buys, turning a rational comeback tactic into wasted clock.",
        "conditions": "Decisive when trailing by 4-9 with under 90 seconds; degraded against a leading team with reliable free-throw shooters who deny the miss-and-rebound branch; aided by quick-trigger offence after made or missed free throws.",
        "magnitude": "Efficient foul-game execution can recover several extra seconds and one to two possessions over sloppy execution, the difference between a live comeback and a formality.",
        "links": ["comeback_finishing_execution", "free_throw_closeout_reliability", "deliberate_foul_target_avoidance", "three_for_the_tie_versus_two"],
    },
    {
        "slug": "three_for_the_tie_versus_two",
        "title": "Three-for-the-Tie versus Quick-Two Decision",
        "summary": "The trailing team's choice and execution between attempting a game-tying three or taking a quick two to extend via fouling, a closeout decision whose quality depends on time, timeouts, and personnel.",
        "stat_signature": "Down three in the final ~10 seconds, immediate-three attempts convert to overtime at ~14-20%; the quick-two-then-foul branch reaches overtime at ~8-14% but with higher variance; the crossover favouring two-then-foul appears with enough clock and a poor opponent free-throw shooter.",
        "mechanism": "With limited seconds the tie-three is the higher-probability path because the two-then-foul branch requires a make, a foul, an opponent miss, and a final score in sequence; execution quality lies in recognising which branch the clock supports and generating the corresponding shot cleanly rather than a rushed heave.",
        "conditions": "Branch selection depends on remaining seconds, timeout availability for advancing the ball, and the opponent's free-throw reliability; the tie-three dominates inside ~8 seconds, the two-then-foul becomes viable with more clock and a weak free-throw opponent.",
        "magnitude": "Choosing the branch the clock actually supports, and executing it cleanly, can shift the trailing team's overtime-reach probability by several points relative to a default or panicked choice.",
        "links": ["comeback_finishing_execution", "intentional_foul_comeback_arithmetic", "advance_to_quick_two_decision", "after_timeout_closeout_set_quality"],
    },
    {
        "slug": "advance_to_quick_two_decision",
        "title": "Advance-and-Quick-Two Closeout Decision",
        "summary": "The execution of generating an immediate high-percentage two when trailing by three with time to foul afterward, including the rim-pressure read and the speed of converting before the leading defence concedes the easy two.",
        "stat_signature": "When a trailing team elects the quick two, rim-or-layup attempt share rises to ~55-70% as defences willingly concede twos to avoid threes; the quick two converts at ~58-66%, and the elapsed time to attempt for efficient teams is ~3-5 seconds.",
        "mechanism": "A defence guarding a three-point deficit deliberately gives up the two, so the trailing team can take a near-uncontested layup quickly and preserve clock to foul; execution quality is in attacking the conceded rim immediately rather than settling, maximising both make probability and remaining seconds for the ensuing foul.",
        "conditions": "Viable only with enough clock for the subsequent foul-and-recovery sequence; depends on a ball-handler who can attack a soft-dropping defence; undermined by hesitation that burns the clock the strategy needs.",
        "magnitude": "Converting the conceded two in 3-5 seconds rather than 8-10 preserves the extra possession the comeback requires, materially raising the chance the full sequence reaches overtime.",
        "links": ["three_for_the_tie_versus_two", "milk_the_clock_execution", "comeback_finishing_execution", "intentional_foul_comeback_arithmetic"],
    },
    {
        "slug": "after_timeout_closeout_set_quality",
        "title": "After-Timeout Closeout-Set Quality",
        "summary": "The shot quality a team generates on a drawn-up possession in a decisive closing situation, isolating designed-play execution under maximal stakes from the after-timeout premium in ordinary game states.",
        "stat_signature": "Closeout after-timeout possessions in clutch states yield ~1.00-1.12 points per possession with an open-or-lightly-contested first-shot rate of ~48-58%; turnover rate on these high-stakes designed plays is ~10-16%, above the calmer after-timeout baseline.",
        "mechanism": "A late drawn-up set must beat a defence that knows a score is needed and is set to deny the primary option; teams whose closeout sets include credible counters and movement generate a quality look, while predictable single-option sets get walled off, so designed-play execution under stakes is a distinct closing skill.",
        "conditions": "Highest value with seconds on the clock and a need to score; degraded when the opponent also times a timeout to counter-set; depends on having more than one threatening action in the call.",
        "magnitude": "The gap between a well-designed counter-laden closeout set and a predictable one can be 0.1-0.2 points per possession on the single most important trip of the game.",
        "links": ["isolation_reliance_in_closeout", "clutch_shot_creation_burden", "comeback_finishing_execution", "three_for_the_tie_versus_two", "inbound_under_full_court_pressure"],
    },
    {
        "slug": "inbound_under_full_court_pressure",
        "title": "Closeout Inbound Under Full-Court Pressure",
        "summary": "The leading team's reliability completing inbound passes against late-game denial pressure, where a failed entry hands the trailing team a cheap possession or a buzzer chance, distinct from generic inbound geometry.",
        "stat_signature": "Closeout inbound completion against full-court denial: ~88-94%; turnover rate climbs to ~12-18% with under three seconds and a need to beat the five-second count; elapsed time to advance the ball past half-court: ~2-4 seconds under pressure.",
        "mechanism": "When protecting a lead the inbound is the riskiest moment because a steal converts directly into points with the clock stopped; execution quality lies in reliable entry options, a tall release valve, and beating both the five-second count and the trap, all under the highest stakes.",
        "conditions": "Most consequential in the final seconds with a one- or two-possession lead; hardest against aggressive full-court traps; mitigated by designed press-breaks and a dependable inbounder-and-receiver pair.",
        "magnitude": "Cutting the late inbound turnover rate by several points removes a category of self-inflicted late losses where the offence never even runs a possession.",
        "links": ["deliberate_foul_target_avoidance", "after_timeout_closeout_set_quality", "lead_closeout_conversion_rate", "turnover_proneness_under_pressure"],
    },
    {
        "slug": "turnover_proneness_under_pressure",
        "title": "Turnover Proneness Under Closing Pressure",
        "summary": "A team's tendency to give the ball away in the final minutes of close games, the single most damaging closeout error because it surrenders a possession with no shot attempt while the clock and pressure are at maximum.",
        "stat_signature": "Clutch turnover rate: ~10-13% for ball-secure closers versus ~15-19% for turnover-prone teams; live-ball turnovers (steals leading to transition) make up ~55-65% of clutch giveaways, the most damaging subtype.",
        "mechanism": "Closing pressure raises ball-handling difficulty as defences gamble and trap; a live-ball turnover late is doubly costly because it both ends the possession scorelessly and gifts the opponent a fast, high-value transition chance precisely when half-court defence is hardest to set, accelerating margin swings.",
        "conditions": "Worst against trapping and ball-pressure defences that ramp aggression late; amplified with a single overburdened ball-handler; reduced by multiple secure handlers and simple late-game spacing.",
        "magnitude": "Each avoided live-ball clutch turnover is worth roughly a full possession swing plus the transition-value premium, a recurring determinant of one-possession outcomes.",
        "links": ["blown_lead_collapse_signature", "inbound_under_full_court_pressure", "milk_the_clock_execution", "scoring_drought_under_lead_protection"],
    },
    {
        "slug": "scoring_drought_under_lead_protection",
        "title": "Scoring Drought Under Lead Protection",
        "summary": "The length and frequency of empty-possession stretches a leading team endures while protecting late, where extended droughts let a trailing team erase a margin without the leader committing an obvious error.",
        "stat_signature": "Lead-protection droughts of three or more consecutive empty possessions occur in ~25-35% of close games for drought-prone teams; the average margin erased during a clutch drought of ~2 minutes is ~5-8 points against a trailing team attacking efficiently.",
        "mechanism": "Even without turnovers, a leading team that goes cold on a string of contested late-clock isolations hands the trailing team uncontested possessions to chip the lead; the drought is the slow-motion analogue of a collapse and reflects the same shot-quality decay compounded over several trips.",
        "conditions": "Most common when the closeout offence narrows to one creator and one play type; worsened by a defence that denies that action; relieved by maintaining at least one reliable late-clock counter.",
        "magnitude": "A single 2-minute scoring drought can convert a comfortable two-possession lead into a one-possession game, making drought frequency a leading indicator of underconversion.",
        "links": ["shot_selection_decay_when_ahead", "blown_lead_collapse_signature", "milk_the_clock_execution", "isolation_reliance_in_closeout", "lead_closeout_conversion_rate"],
    },
    {
        "slug": "pressure_free_throw_variance",
        "title": "Pressure Free-Throw Variance and Icing Resistance",
        "summary": "The widening of a shooter's free-throw outcome distribution in maximal-leverage closing situations, including the residual effect of a defence calling a timeout to ice the shooter before the attempt.",
        "stat_signature": "Late-and-close free-throw variance exceeds the season-baseline variance even when the mean holds; iced first-attempt conversion runs ~1-4 pp below uniced in matched contexts, with the effect concentrated on the first of a pair and inconsistent in large samples.",
        "mechanism": "Maximal stakes raise arousal and disrupt the automatised free-throw routine, fattening the tails of the conversion distribution; an icing timeout adds a routine-disruption window whose modest, contested effect lands almost entirely on the immediately following first attempt.",
        "conditions": "Most relevant for shooters with rigid timed routines and in road environments with crowd noise; muted for high-volume elite free-throw shooters; the icing component matters only on the first attempt after the stoppage.",
        "magnitude": "The icing effect is a small, contested 1-4 pp first-attempt decrement; the larger story is variance inflation that makes any single closing free-throw trip a higher-variance event than its mean implies.",
        "links": ["free_throw_closeout_reliability", "icing_resistance_routine", "deliberate_foul_target_avoidance", "lead_closeout_conversion_rate"],
    },
    {
        "slug": "icing_resistance_routine",
        "title": "Closeout Free-Throw Routine Stability",
        "summary": "A shooter's ability to preserve a stable pre-shot routine through closing-situation stoppages and crowd pressure, indexed by the consistency of conversion across iced and uniced high-leverage attempts.",
        "stat_signature": "Routine-stable shooters show near-zero gap between iced and uniced first-attempt conversion and minimal late-and-close mean drift; routine-fragile shooters show a 3-5 pp first-attempt drop after icing and a wider late-game spread.",
        "mechanism": "A repeatable, time-invariant pre-shot routine buffers against the cognitive-load spike of a pre-attempt timeout and a hostile crowd; shooters whose routine timing is robust to interruption retain their baseline conversion, while those reliant on uninterrupted rhythm lose a measurable slice of it.",
        "conditions": "Tested specifically when the defence has a timeout to spend and chooses to ice; magnified on the road; a property of the individual's routine more than of team scheme.",
        "magnitude": "The difference between a routine-stable and routine-fragile closer over repeated foul-game trips is a small but persistent edge in expected closing free-throw points.",
        "links": ["pressure_free_throw_variance", "free_throw_closeout_reliability", "deliberate_foul_target_avoidance"],
    },
    {
        "slug": "possession_value_late_game_execution",
        "title": "Late-Game Possession-Value Execution",
        "summary": "How well a team maximises the value of each scarce closing possession given that late-game pace compression makes every trip worth more, blending shot quality, offensive-rebound effort, and avoidance of zero-value outcomes.",
        "stat_signature": "Effective points per closing possession (incorporating offensive rebounds and free throws) for top closers: ~1.05-1.15 versus ~0.92-1.00 for weak closers; zero-value-possession rate (turnover or airball heave) separates the groups by ~5-8 pp.",
        "mechanism": "Because deliberate late-game pace removes possessions from the game, each surviving possession carries amplified leverage; teams that extend possessions with offensive boards, draw fouls, and avoid zero-value outcomes extract more from the scarce closing trips than their per-possession efficiency in open play would predict.",
        "conditions": "Most impactful in low-possession-count finishes where a single wasted trip is irrecoverable; depends on crash-versus-balance rebounding choices and on disciplined shot selection; degraded by fatigue late in regulation and overtime.",
        "magnitude": "A 0.10-0.15 effective-points-per-possession edge across the handful of closing trips compounds into roughly the margin of a one-possession game, a synthesising measure of closing execution.",
        "links": ["milk_the_clock_execution", "scoring_drought_under_lead_protection", "lead_closeout_conversion_rate", "turnover_proneness_under_pressure", "comeback_finishing_execution"],
    },
]
