"""ClosingExecution Tennis concept nodes — person-free.

Scope: the ACT of CLOSING OUT — serving out a set or match, converting a lead into
a finished result, and finishing tiebreaks.  This family measures FINISHING
behaviour: closeout-game conversion, serving-out reliability, the choke/collapse
signatures of failing to close, and tiebreak-finishing execution.  Deliberately
distinct from:
  - SpecialSituations (which DEFINES the break-point / set-point / match-point /
    deciding-point leverage STATES and their probability math), and
  - GamePhases (which owns the serving-for-the-set / final-set time-band windows).
Here the angle is always the EXECUTION and CONVERSION of the closing act, plus its
failure modes — not the definition of the pressure state.
"""
from __future__ import annotations

SPORT = "Tennis"
FAMILY = "ClosingExecution"

CONCEPTS = [
    {
        "slug": "serve_out_set_conversion_rate",
        "title": "Serving-Out-the-Set Conversion Rate",
        "summary": "The realised probability a server holds the specific game in which a hold secures the set, benchmarked against the player's ordinary hold rate so a persistent shortfall isolates closing execution from baseline serve quality.",
        "stat_signature": "Closeout-game hold rate (serving for the set) versus ordinary-game hold rate: confident closers hold within ~1-2 pp of baseline while shaky closers drop ~4-8 pp; the diagnostic is the closeout-minus-baseline hold residual, stable at the player level across a season.",
        "mechanism": "The game that closes a set carries an approach-avoidance load distinct from any other service game; players who maintain first-serve placement and aggression convert at their baseline, while those whose serve grows tentative invite the returner into the rally and concede the break that prolongs the set.",
        "conditions": "Most diagnostic when serving for the set rather than the match (a separable, lower-stakes closeout); amplified after a prior failed closeout in the same set; sharpened against heavy-returning styles that punish a reduced first serve.",
        "magnitude": "A persistent -5 pp serving-out residual over a season converts to several additional set extensions and tiebreaks from closing execution alone, descriptively independent of overall hold rate.",
        "links": ["serve_out_match_conversion_rate", "closeout_game_choke_signature", "first_serve_aggression_when_closing", "return_to_break_back_when_serving_out", "tiebreak_finish_from_minibreak_lead"],
    },
    {
        "slug": "serve_out_match_conversion_rate",
        "title": "Serving-Out-the-Match Conversion Rate",
        "summary": "The realised probability a server holds the game that would end the match, the highest-pressure closeout, benchmarked against ordinary holds so the match-closing residual quantifies finishing under maximal stakes.",
        "stat_signature": "Hold rate when serving for the match versus ordinary holds: elite closers convert ~82-90% while pressure-fragile players drop several points below their serving-for-the-set rate; the match-closeout residual exceeds the set-closeout residual for most players, reflecting the additional stakes.",
        "mechanism": "Closing the match concentrates maximal outcome asymmetry on one service game; the same conservative-serve paradox as break points intensifies, where fear of the double fault flattens the serve and hands the returner attackable balls, so the match-closeout game is the sharpest test of serve reliability under stakes.",
        "conditions": "Most exposed when serving for the match for the first time and after squandered match points; amplified in best-of-three where there is less margin to recover a failed closeout; eased by serve dominance that wins free points regardless of nerves.",
        "magnitude": "The gap between match-closeout conversion and ordinary holds is among the purest finishing signals in the sport, and its variation separates reliable closers from those who repeatedly fail to serve it out.",
        "links": ["serve_out_set_conversion_rate", "match_point_execution_on_serve", "closeout_game_choke_signature", "double_fault_spike_when_closing", "failure_to_serve_out_recovery"],
    },
    {
        "slug": "closeout_game_choke_signature",
        "title": "Closeout-Game Choke Signature",
        "summary": "The characteristic statistical fingerprint of a failed closeout — collapsing first-serve percentage, a double fault at a critical point, and shortened rally aggression — decomposed so the failure mode is identifiable rather than ascribed to variance.",
        "stat_signature": "A choked closeout shows first-serve percentage dropping ~8-15 pp within the game, at least one double fault concentrated at deuce or break point, and a fall in aggressive baseline shot rate as the player becomes tentative; unforced-error rate on closeout rallies rises ~15-25%.",
        "mechanism": "Closing pressure can trigger a self-reinforcing tightening: a tentative first serve raises second-serve exposure, a double fault deepens anxiety, and shortened swings produce errors, so the failed closeout is a cascade rather than a single bad point, with each tentative action feeding the next.",
        "conditions": "Most frequent for players with documented closing fragility and after prior failed closeouts in the same match; amplified against aggressive returners who sense and punish the tentativeness; intensified in front of a hostile crowd.",
        "magnitude": "Conditional on the choke-pattern start (a serve-percentage drop plus an early deuce), the probability of being broken in the closeout game rises well above the player's baseline break-faced rate, a within-game collapse signal.",
        "links": ["serve_out_set_conversion_rate", "serve_out_match_conversion_rate", "double_fault_spike_when_closing", "first_serve_aggression_when_closing", "failure_to_serve_out_recovery"],
    },
    {
        "slug": "first_serve_aggression_when_closing",
        "title": "First-Serve Aggression When Closing",
        "summary": "Whether a server maintains or reduces first-serve speed and placement intent in closeout games, since the conservative-serve paradox — slowing down to avoid faults — is a primary mechanism of failed closeouts.",
        "stat_signature": "First-serve speed and corner-placement rate in closeout games versus the set average: aggression-stable closers hold within ~1-3 km/h and maintain wide-T targeting, while tentative ones slow ~5-9 km/h and centre their placement, raising the returner's read and attack rate.",
        "mechanism": "A first serve struck with full intent earns free or weak-return points that end the game quickly; pulling speed and centring placement to ensure the serve lands trades that free-point advantage for predictable, attackable balls, lengthening rallies into the zone where closing nerves most degrade play.",
        "conditions": "Most consequential against strong returners who punish reduced pace; amplified when the player has already double-faulted in the set; eased for flat, high-pace servers who can hit safe targets without losing speed.",
        "magnitude": "Maintaining first-serve aggression in closeout games measurably raises the free-point and short-rally rate that converts the game quickly, the direct counter to the conservative-serve collapse.",
        "links": ["closeout_game_choke_signature", "serve_out_set_conversion_rate", "double_fault_spike_when_closing", "serve_plus_one_to_finish", "first_serve_percentage_stability_closing"],
    },
    {
        "slug": "double_fault_spike_when_closing",
        "title": "Double-Fault Spike When Closing",
        "summary": "The elevation of double-fault rate specifically in closeout games and on the points that would finish the set or match, the most self-inflicted closing error, isolating second-serve reliability under maximal stakes.",
        "stat_signature": "Double-fault rate in closeout games versus the match average runs ~1.5-2.5x higher for pressure-fragile players; double faults cluster on game point and break point within the closeout game, where the cost of the miss is maximal.",
        "mechanism": "On closing points the cost of a double fault equals losing the game's most important point with no opponent involvement; paradoxically the fear of it flattens and slows the second serve into either a tentative ball the returner attacks or, when overcorrected, an error, so the double-fault spike is the clearest marker of second-serve fragility under closing stakes.",
        "conditions": "Worst for players with mechanically inconsistent second serves and after a prior double fault in the match; amplified against returners who stand in on second serves; muted for players with a heavy, reliable kick second serve.",
        "magnitude": "A doubled double-fault rate in closeout games directly forfeits the highest-leverage points, a measurable and actionable component of failed closeouts.",
        "links": ["closeout_game_choke_signature", "first_serve_aggression_when_closing", "second_serve_reliability_to_finish", "serve_out_match_conversion_rate"],
    },
    {
        "slug": "first_serve_percentage_stability_closing",
        "title": "First-Serve Percentage Stability in the Close",
        "summary": "The consistency of first-serve percentage across closeout games relative to the set baseline, since a closeout-specific drop raises second-serve exposure exactly when the returner is most aggressive.",
        "stat_signature": "First-serve percentage in closeout games versus the set average: stable closers hold within ~2-3 pp while fragile ones drop ~8-15 pp; the resulting second-serve point share rises sharply, and second-serve-points-won fall as returners attack the extra second serves.",
        "mechanism": "A closeout-specific first-serve drop compounds two penalties: more second serves to navigate and a returner emboldened by closing leverage; the combination shifts the game toward the server's weaker delivery at the worst moment, so first-serve stability is a prerequisite for converting the closeout cleanly.",
        "conditions": "Most exposed against heavy returners and on slow surfaces that reward second-serve attack; amplified after squandered closeout opportunities; eased by a robust, repeatable service motion resistant to tension.",
        "magnitude": "Holding first-serve percentage steady in closeout games removes the cascade of extra second serves that drives a meaningful share of closing breaks.",
        "links": ["double_fault_spike_when_closing", "first_serve_aggression_when_closing", "second_serve_reliability_to_finish", "serve_out_set_conversion_rate"],
    },
    {
        "slug": "second_serve_reliability_to_finish",
        "title": "Second-Serve Reliability to Finish",
        "summary": "The quality a server retains on second serves in closeout games — kick, depth, and points-won — since the second serve is the delivery most exposed when closing and the one returners most aggressively attack to extend.",
        "stat_signature": "Second-serve-points-won in closeout games versus the set baseline drops ~3-6 pp for fragile servers; second-serve depth shortens and spin rate falls under closing tension, raising the returner's attackable-ball rate within the game that would finish the set.",
        "mechanism": "When closing, the returner concentrates aggression on second serves knowing a weak one is the path back into the set; a server who keeps the second serve deep and heavy denies that attack, while one whose second serve shortens and slows hands over short balls precisely when each lost point is most costly.",
        "conditions": "Most tested against aggressive second-serve return styles and on surfaces that reward standing in; amplified on closing points where conservatism peaks; mitigated by a reliable high-bouncing kick that resists attack even when slowed.",
        "magnitude": "Sustained second-serve quality in closeout games is a direct lever on whether the closing game is held, separating reliable finishers from those whose second serve betrays them at the close.",
        "links": ["double_fault_spike_when_closing", "first_serve_percentage_stability_closing", "serve_plus_one_to_finish", "serve_out_match_conversion_rate"],
    },
    {
        "slug": "serve_plus_one_to_finish",
        "title": "Serve-Plus-One Execution to Finish",
        "summary": "The server's quality on the first ball after the serve in closeout games — converting a strong serve into a controlling or finishing plus-one shot — since hesitation on the plus-one stalls the point and re-opens the game.",
        "stat_signature": "Plus-one aggression and point-win rate after a strong serve in closeout games versus the set baseline; confident closers maintain forward, offensive plus-one patterns while tentative ones reset to neutral, lowering the short-point win rate that ends closing games quickly.",
        "mechanism": "A strong serve sets up an offensive plus-one ball, and finishing that pattern ends the point before closing nerves accumulate over a long rally; a server who hesitates on the plus-one surrenders the serve-built advantage and drags the point into extended play where tension most degrades execution, lengthening the path to closing the game.",
        "conditions": "Most valuable on faster surfaces where the serve-plus-one pattern dominates; degraded when the first serve is reduced and yields a weaker plus-one ball; sharpened against returners who neutralise the serve and force the plus-one to be decisive.",
        "magnitude": "Maintaining serve-plus-one aggression when closing raises the short-point win rate, shortening closeout games and limiting the rally exposure where collapses occur.",
        "links": ["first_serve_aggression_when_closing", "second_serve_reliability_to_finish", "rally_aggression_when_closing", "serve_out_set_conversion_rate"],
    },
    {
        "slug": "rally_aggression_when_closing",
        "title": "Rally Aggression When Closing",
        "summary": "Whether a player sustains or retreats from offensive baseline patterns in closeout games and on closing points, since defaulting to passive, push-the-ball play is a common closing failure that invites errors and counter-attack.",
        "stat_signature": "Aggressive shot rate, court position, and winner-to-unforced-error ratio in closeout rallies versus the set baseline; finishers hold their aggression and court position while chokers retreat behind the baseline and shorten swings, with unforced errors rising ~15-25% on closing rallies.",
        "mechanism": "Closing leverage tempts players to stop missing rather than to keep winning, but passive play extends rallies, cedes court position, and produces tentative errors; players who maintain their natural aggression end points on their terms, while those who retreat hand initiative to an opponent fighting to extend, converting closeout rallies into lost points.",
        "conditions": "Most consequential for naturally aggressive players whose game depends on dictating; amplified against counterpunchers who feed off passivity; intensified when serving out against a returner with nothing to lose.",
        "magnitude": "Sustaining rally aggression in closeout games measurably preserves the winner-to-error balance that decides tight closing points, a behavioural counterpart to serve aggression.",
        "links": ["serve_plus_one_to_finish", "closeout_game_choke_signature", "unforced_error_inflation_closing", "first_serve_aggression_when_closing"],
    },
    {
        "slug": "unforced_error_inflation_closing",
        "title": "Unforced-Error Inflation When Closing",
        "summary": "The rise in unforced-error rate on the points and games that would finish a set or match, the rally-side analogue of the double-fault spike, capturing how tension degrades shot execution at the close.",
        "stat_signature": "Unforced-error rate on closeout-game rallies and on set- and match-finishing points runs ~15-25% above the match average for pressure-affected players; errors concentrate on the player's normally reliable patterns, signalling tension rather than tactical risk.",
        "mechanism": "Maximal closing stakes raise arousal and disrupt the timing and footwork that produce clean groundstrokes; the result is a fattening of the error distribution precisely on the points that matter most, so unforced-error inflation is a direct, measurable manifestation of closing tension on the rally side.",
        "conditions": "Most pronounced for players with documented closing fragility and on slower surfaces where rallies extend; amplified after squandered closeout chances; muted for players whose patterns are grooved and resistant to tension.",
        "magnitude": "The closeout unforced-error premium forfeits high-leverage points through the player's own mistakes, a recurring contributor to failed closeouts independent of opponent quality.",
        "links": ["rally_aggression_when_closing", "closeout_game_choke_signature", "double_fault_spike_when_closing", "match_point_execution_on_serve"],
    },
    {
        "slug": "return_to_break_back_when_serving_out",
        "title": "Return-to-Break-Back Pressure on the Closeout",
        "summary": "The opponent's heightened return performance specifically against a player serving for the set or match, since a returner with nothing to lose often elevates, and the server's resistance to that surge determines the closeout.",
        "stat_signature": "Returner break-point creation rate against a serving-for-it opponent runs above their ordinary return-game rate; return depth and aggression rise as the returner swings freely, and the server's ability to win the resulting longer, more aggressive return points is the diagnostic.",
        "mechanism": "Facing elimination of the set or match frees the returner to attack returns without fear, raising return depth and aggression exactly as the server tightens; the closeout is therefore contested by a rising returner against a potentially tentative server, so resisting this return surge is a core finishing skill.",
        "conditions": "Strongest when the returner is an aggressive ball-striker and the server is showing closing tension; amplified on return-friendly surfaces; muted when the server's serve dominance denies the returner a foothold regardless of intent.",
        "magnitude": "The returner's elevation against a serving-for-it opponent measurably raises break-back probability, so the server's resistance to it is a decisive component of closeout conversion.",
        "links": ["serve_out_set_conversion_rate", "closeout_game_choke_signature", "first_serve_aggression_when_closing", "failure_to_serve_out_recovery", "consolidate_break_to_serve_out"],
    },
    {
        "slug": "consolidate_break_to_serve_out",
        "title": "Consolidating a Break Toward the Closeout",
        "summary": "Whether a player holds the service game immediately after breaking to move within sight of closing, since an immediate break-back resets the set and a failure to consolidate is a leading momentum-loss signal before the closeout.",
        "stat_signature": "Post-break hold rate when the hold would set up serving for the set versus ordinary holds: strong consolidators hold near baseline while fragile ones suffer immediate re-breaks at ~22-30% rate, with the first two points of the consolidation game showing elevated serve-fault and double-fault rates.",
        "mechanism": "Breaking creates a lead that only matters if consolidated; the player must switch from aggressor to holder while the just-broken opponent is maximally motivated, so a consolidation hold both protects the lead and clears the path to the closeout, whereas an immediate re-break erases the progress and the psychological edge.",
        "conditions": "Most fragile when the break required several attempts (signalling a tight contest) and when the opponent surges immediately; steadier when the break was decisive; amplified on surfaces where breaks are frequently exchanged.",
        "magnitude": "Consolidation reliability determines how often a break actually advances a player toward closing, a momentum-execution dimension that precedes and enables the serve-out game.",
        "links": ["return_to_break_back_when_serving_out", "serve_out_set_conversion_rate", "closeout_game_choke_signature", "two_break_cushion_management"],
    },
    {
        "slug": "two_break_cushion_management",
        "title": "Two-Break Cushion Management",
        "summary": "How a player manages a double-break lead in a set — whether the cushion is preserved to a comfortable close or partially surrendered before serving out — measured by the rate at which a two-break lead is reduced before the set is finished.",
        "stat_signature": "The frequency with which a double-break lead in a set shrinks to a single break before the closeout; secure managers preserve the cushion to the serve-out game while loose ones surrender a break back, converting a comfortable close into a tense single-break serve-out.",
        "mechanism": "A two-break cushion offers margin to absorb one lapse, but complacency or a relaxation of intensity can hand a break back, removing the buffer and raising the stakes of the eventual serve-out; preserving the cushion keeps the closeout low-pressure, so cushion management indirectly governs how difficult the closing game becomes.",
        "conditions": "Most at risk when intensity dips after building the lead; amplified against opponents who raise their level when seemingly out of the set; steadier for players who maintain focus regardless of scoreboard comfort.",
        "magnitude": "Preserving rather than surrendering a two-break cushion keeps the serve-out game at low leverage, materially reducing the closing-execution risk that a single-break serve-out carries.",
        "links": ["consolidate_break_to_serve_out", "serve_out_set_conversion_rate", "failure_to_serve_out_recovery", "front_runner_closing_profile"],
    },
    {
        "slug": "tiebreak_finish_from_minibreak_lead",
        "title": "Tiebreak Finish From a Mini-Break Lead",
        "summary": "How reliably a player converts a mini-break advantage in a tiebreak into the set, the tiebreak analogue of serving out, measured by the rate at which a tiebreak lead is preserved to the finish versus surrendered.",
        "stat_signature": "Conversion of a one-mini-break tiebreak lead (for example leading by two points midway) into the set: confident finishers convert at a high rate while fragile ones surrender the mini-break back; first-serve percentage and aggression on the player's serve points within the lead are the diagnostics.",
        "mechanism": "A mini-break lead in a tiebreak must be protected across the alternating-serve structure, and the player must hold serve points to preserve it; tightening on those serve points or pressing on return points surrenders the mini-break, so finishing a tiebreak from ahead is a distinct execution skill mirroring serving out a set.",
        "conditions": "Most tested in tiebreaks deciding tight sets and against strong tiebreak servers; amplified late in the tiebreak as each point's leverage peaks; eased by serve dominance that protects the player's own serve points within the lead.",
        "magnitude": "Reliable conversion of tiebreak leads is a measurable finishing skill that, like serving out, separates players who close tight sets from those who let won positions slip.",
        "links": ["tiebreak_closeout_serve_pattern", "serve_out_set_conversion_rate", "tiebreak_set_point_finish_execution", "front_runner_closing_profile"],
    },
    {
        "slug": "tiebreak_closeout_serve_pattern",
        "title": "Tiebreak Closeout Serve-Pattern Discipline",
        "summary": "The placement and aggression a server maintains on critical tiebreak serve points near the finish, where pattern discipline and unpredictability sustain the serve advantage that decides tiebreaks.",
        "stat_signature": "First-serve percentage and corner-placement variety on tiebreak serve points at high scores (for example 5-up and beyond): disciplined servers maintain wide-T variation and first-serve reliability while pressure-affected ones centre placement and slow the serve, raising the returner's read at the decisive moments.",
        "mechanism": "Tiebreaks are decided by who protects their serve points, and at the finish a server who keeps placement varied and aggressive denies the returner anticipation, while one who becomes predictable or tentative concedes the mini-break that loses the set; pattern discipline under maximal tiebreak leverage is the finishing competency.",
        "conditions": "Most consequential at the highest tiebreak scores where each serve point is terminal; amplified on faster surfaces where serve dominance is greatest; degraded when closing tension flattens the serve.",
        "magnitude": "Maintaining serve-pattern discipline at the tiebreak finish preserves the serve advantage that, compounded across the alternating structure, decides the closeout.",
        "links": ["tiebreak_finish_from_minibreak_lead", "tiebreak_set_point_finish_execution", "first_serve_aggression_when_closing", "serve_plus_one_to_finish"],
    },
    {
        "slug": "tiebreak_set_point_finish_execution",
        "title": "Tiebreak Set-Point Finish Execution",
        "summary": "The conversion and shot-execution quality on tiebreak set points themselves — the terminal points of the tiebreak — focusing on whether the player executes a clean finishing pattern or tightens into an error at the decisive moment.",
        "stat_signature": "Conversion rate on a player's own tiebreak set points and the unforced-error rate on those points; finishers execute decisive serve or rally patterns and convert at a high rate, while pressure-affected players show elevated errors and tentative play on the points that would end the set.",
        "mechanism": "A tiebreak set point is strictly terminal with no deuce safety net, so the player must execute a finishing pattern under the tiebreak's maximal per-point leverage; clean execution ends the set, while tightening into a tentative serve or shortened groundstroke converts the set point into a missed opportunity and prolongs the tiebreak, mirroring the serve-out choke.",
        "conditions": "Most exposed on the first set point faced and after squandered earlier set points within the tiebreak; amplified against opponents who defend set points aggressively; eased by serve dominance that converts set points on serve.",
        "magnitude": "Finish-execution quality on tiebreak set points is a high-leverage component of closing tight sets, with conversion variation separating reliable from fragile finishers.",
        "links": ["tiebreak_closeout_serve_pattern", "tiebreak_finish_from_minibreak_lead", "match_point_execution_on_serve", "unforced_error_inflation_closing"],
    },
    {
        "slug": "match_point_execution_on_serve",
        "title": "Match-Point Execution on Serve",
        "summary": "The shot-execution quality a server delivers on the actual match points they hold — serve placement, plus-one, and finishing pattern — distinct from the abstract conversion rate, capturing how the closing point is physically executed under maximal stakes.",
        "stat_signature": "On held match points, the server's first-serve percentage, ace-or-weak-return rate, and finishing-pattern success versus the match baseline; clean executors maintain aggressive, decisive patterns while pressure-affected servers slow the serve and reset rallies, lowering the short-point finish rate on the points that would end the match.",
        "mechanism": "A match point on serve is the single highest-stakes execution moment, where the server either commits to a finishing pattern or tightens into safety; committing ends the match cleanly, while pulling pace or hesitating on the plus-one hands the returner a foothold, so the physical execution of the match point — not just its theoretical conversion — decides whether it is converted.",
        "conditions": "Most fragile on the first match point and after prior squandered ones; amplified against returners who elevate facing match point; eased by serve dominance that ends match points before rallies develop.",
        "magnitude": "Execution quality on served match points is the terminal finishing test, and its degradation under stakes is a direct mechanism of squandered match points and extended matches.",
        "links": ["serve_out_match_conversion_rate", "tiebreak_set_point_finish_execution", "double_fault_spike_when_closing", "squandered_match_point_cascade"],
    },
    {
        "slug": "squandered_match_point_cascade",
        "title": "Squandered Match-Point Cascade",
        "summary": "The compounding effect of failing to convert early match points, where each missed opportunity raises tension and lowers conversion on subsequent match points, a within-match psychological cascade distinct from a single failed point.",
        "stat_signature": "Conversion rate on a player's second and later match points versus their first; cascade-prone players show a declining conversion sequence and rising error and double-fault rates across successive match points, while resilient players convert later match points near their first-point rate.",
        "mechanism": "A missed match point can seed doubt that degrades execution on the next, so conversion can fall with each successive opportunity as tension compounds; this cascade is a distinct failure mode from missing one point, because the accumulation of squandered chances can swing momentum to an opponent who survives them.",
        "conditions": "Most pronounced for players with documented closing fragility and when the opponent saves match points with aggressive, momentum-shifting play; amplified in long matches where fatigue compounds tension; muted for players whose execution is robust to prior outcomes.",
        "magnitude": "The decline in conversion across successive match points quantifies how squandered opportunities feed on themselves, a recurring driver of dramatic failures to close.",
        "links": ["match_point_execution_on_serve", "failure_to_serve_out_recovery", "closeout_game_choke_signature", "unforced_error_inflation_closing"],
    },
    {
        "slug": "failure_to_serve_out_recovery",
        "title": "Recovery After Failing to Serve It Out",
        "summary": "How a player responds after being broken while serving for the set or match — whether they break back promptly or spiral — since the ability to recover from a failed closeout governs whether the squandered opportunity proves decisive.",
        "stat_signature": "Break-back rate and subsequent set or match outcome after a failed serve-out; resilient players break back quickly and still close while fragile ones surrender the momentum and lose the set they were serving to win, with elevated error rates in the games immediately following the failed closeout.",
        "mechanism": "A failed closeout hands the opponent momentum and the player a psychological setback; recovery requires immediately re-imposing pressure on return rather than dwelling on the missed chance, so the response to a failed serve-out determines whether it is a brief setback or the turning point of the set.",
        "conditions": "Most tested after a high-stakes failed match-closeout; amplified when the opponent rides the momentum into their own service holds; steadier for players with strong return games who can recreate break chances quickly.",
        "magnitude": "Recovery rate after a failed serve-out determines how often squandered closeouts are reclaimed versus how often they decide the set, a resilience dimension complementing raw conversion.",
        "links": ["squandered_match_point_cascade", "serve_out_set_conversion_rate", "return_to_break_back_when_serving_out", "front_runner_closing_profile"],
    },
    {
        "slug": "front_runner_closing_profile",
        "title": "Front-Runner Closing Profile",
        "summary": "A player's overall tendency to convert leading positions into finished results across sets and matches, synthesising serve-out, consolidation, and tiebreak-finishing reliability into a single closing-from-ahead signature.",
        "stat_signature": "Win rate from a position of leading (a break up in a set, a set up in a match, or ahead in a tiebreak) versus the model-implied conversion; strong front-runners convert leads above expectation while fragile ones repeatedly let leads slip, with the residual stable across a season.",
        "mechanism": "Closing from ahead pools the serve-out, consolidation, cushion-management, and tiebreak-finishing skills into one disposition; a front-runner sustains aggression and composure to convert leads, while a player who tightens when ahead underconverts across all these sub-skills, so the profile is a synthesising measure of finishing temperament.",
        "conditions": "Most diagnostic when pooled across many leading positions to overcome variance; amplified in best-of-five where leads must be protected longer; interacts with serve dominance, which buffers closing nerves regardless of temperament.",
        "magnitude": "A persistent positive or negative lead-conversion residual across a season is the highest-level summary of closing execution, integrating the family's component skills into one signature.",
        "links": ["serve_out_set_conversion_rate", "serve_out_match_conversion_rate", "two_break_cushion_management", "tiebreak_finish_from_minibreak_lead", "failure_to_serve_out_recovery"],
    },
]
