"""scripts.platformkit.specs.deceptiondisguise_tennis — person-free deception and disguise concepts, Tennis."""
from __future__ import annotations

SPORT = "Tennis"
FAMILY = "DeceptionDisguise"

CONCEPTS: list[dict] = [
    {
        "slug": "drop_drive_shared_preparation",
        "title": "Drop-Drive Shared Preparation",
        "summary": "An identical backswing and shoulder turn precedes both a drop shot and a penetrating drive until the last contact frames, forcing the opponent to commit to a recovery depth before the shot type is revealed.",
        "stat_signature": "Pre-contact preparation-overlap duration above 85 % of the swing cycle shared between drop and drive; opponent split-step delay induced above 0.18 s versus baseline; opponent forward-sprint error rate (wrong depth commitment) above 38 % per disguised-drop attempt.",
        "mechanism": "The shared loading phase pins the opponent at mid-court depth because a drive look demands back-court positioning. Delaying racquet-head deceleration until the final 0.05 s of contact withholds the only cue that resolves drop-versus-drive; by the time the deceleration registers, the opponent's split step is already placed and the court opens.",
        "conditions": "Most effective after 3+ groundstrokes that establish a drive rhythm; requires a contact point between knee and hip height for physical drop-shot execution; amplified against deep-standing baseliners whose forward sprint to the net exceeds 2.5 s.",
        "magnitude": "Drop shots preceded by a full drive takeback are reached in time by the opponent only 38–46 % of the time; the forced-short-ball rate from a late arrival exceeds 52 %, compared with 28–34 % when the drop is telegraphed early by wrist softening.",
        "links": ["drop_shot_late_wrist_check", "open_stance_direction_mask", "lob_drive_shared_setup", "drop_volley_touch_disguise"],
    },
    {
        "slug": "serve_toss_location_disguise",
        "title": "Serve-Toss Location Disguise",
        "summary": "A uniform ball-toss placement maintained across wide, body, and T deliveries denies the returner a pre-contact directional read, keeping split-step timing neutral and degrading anticipation accuracy throughout the service game.",
        "stat_signature": "Lateral toss-position variance across serve directions below 8 cm standard deviation; returner pre-contact lean bias toward the correct zone below 55 % (near chance); first-serve-points-won increase of 5–8 percentage points against returners who rely on toss-read anticipation.",
        "mechanism": "Returners at tour level routinely read toss position to begin a directional weight shift before ball contact. A consistent toss neutralizes this cue, forcing the returner to split-step neutrally and react purely to the post-contact ball trajectory — a slower read pathway that adds 0.06–0.10 s of response lag and degrades contact quality on wide deliveries.",
        "conditions": "Most valuable against returners standing inside the baseline who pre-lean heavily; amplified on fast surfaces where post-contact reaction time is already compressed; requires a wrist and shoulder rotation that can replicate full pace across all serve directions from the same toss.",
        "magnitude": "Servers with low toss-variance win 6–9 more first-serve points per set against read-dependent returners; ace and service-winner rates increase by 2–4 percentage points when toss disguise is combined with varied placement patterns.",
        "links": ["kick_slice_flat_toss_mirror", "body_serve_jam_disguise", "second_serve_intent_concealment", "serve_plus_one_pattern_masking"],
    },
    {
        "slug": "kick_slice_flat_toss_mirror",
        "title": "Spin-Type Toss Mirror",
        "summary": "Matching toss height and contact-point setup across flat, slice, and kick deliveries hides spin type until after the racquet strikes the ball, causing the returner to mis-calibrate swing path and contact window for the incoming spin.",
        "stat_signature": "Toss-height variance by spin type below 6 cm standard deviation; mis-read return-contact-quality drop (shallow or popped-up return) above 34 % on disguised kick deliveries; opponent return depth variance rising above 0.55 m SD when spin type is concealed.",
        "mechanism": "Kick and slice serves require the returner to pre-set a different swing path — high-to-low for a kicker, level-through for a flat delivery. A matched toss denies the preparation cue; the returner arrives at contact with a swing path calibrated to the wrong spin, producing off-centre contact, short returns, or errors when adjustment is made too late.",
        "conditions": "Requires sufficient wrist pronation flexibility to replicate the flat-contact look even on kick serves; most disruptive against returners who take the ball early inside the baseline where adjustment time is minimal; less effective against returners who step back to wait for the full bounce and allow the spin to declare itself.",
        "magnitude": "Disguised spin-type serves produce a return landing inside the service box (shallow) at 32–42 % frequency versus 20–26 % when spin is telegraphed by a higher toss; third-ball attack conversion from shallow returns exceeds 58 %.",
        "links": ["serve_toss_location_disguise", "body_serve_jam_disguise", "second_serve_intent_concealment"],
    },
    {
        "slug": "forehand_disguise_inside_out_inside_in",
        "title": "Inside-Out Inside-In Disguise",
        "summary": "A shared open-stance loading phase for a forehand conceals whether the shot travels crosscourt (inside-out) or down the line (inside-in) until hip-rotation direction is committed, causing the opponent to mis-time the recovery split step.",
        "stat_signature": "Hip-rotation timing similarity index between inside-out and inside-in above 0.82 (scale 0–1); opponent recovery-step direction error rate above 32 % on disguised inside-in forehands; wrong-footed-winner and forced-error rate above 40 % when the pattern is deployed in open-stance rally positions.",
        "mechanism": "An open-stance forehand routes power through hip rotation rather than weight transfer, making the rotation direction the sole direction cue. Both inside-out and inside-in share the same grip, backswing plane, and coil phase; hip-rotation delay past 0.10 s before contact prevents reliable opponent read, locking recovery into a probabilistic split rather than a directional lean.",
        "conditions": "Requires a rally position inside the court where the server can execute both directions without reachability constraints; most effective on balls arriving to the centre or inside the body where the open-stance enables full rotation either way; amplified against opponents whose recovery split step is slow or directionally biased.",
        "magnitude": "Inside-in forehands off an open-stance disguise produce an opponent wrong-side recovery at 30–38 % frequency, generating winners or putaway errors on the next ball at 55–65 % of those misreads.",
        "links": ["open_stance_direction_mask", "backhand_dtl_crosscourt_hold", "shot_disguise_late_racquet_face", "inside_in_freeze_recovery"],
    },
    {
        "slug": "backhand_dtl_crosscourt_hold",
        "title": "Backhand Direction Hold",
        "summary": "Delaying wrist and racquet-face disclosure on a backhand groundstroke withholds the down-the-line signal until after the opponent's recovery split step is committed, producing wrong-footed errors when the down-the-line is released.",
        "stat_signature": "Contact-window cue-latency (time from swing initiation to face angle readable) above 0.22 s on disguised down-the-line backhands; wrong-footed-opponent rate above 30 % per disguised execution; resulting forced-error and winner rate from wrong-footed opponents above 52 %.",
        "mechanism": "Crosscourt is the geometric default from the backhand corner; opponents begin recovery toward the forehand side in anticipation. Holding the wrist square and delaying rotation suppresses the face-open cue that signals down-the-line; by the time the cue appears, the opponent's momentum is already crosscourt-directed and the down-the-line corridor is uncontested.",
        "conditions": "Most effective from a loaded, prepared position with 0.4+ s of preparation time; requires a contact point at or behind the baseline where hip clearance allows both directions; amplified against net-rushing opponents who must commit to a volley position before contact.",
        "magnitude": "Hold-and-release down-the-line backhands produce outright winners or forced short balls at 48–58 % frequency against opponents who pre-lean crosscourt, compared with 28–34 % when the direction is telegraphed by early face opening.",
        "links": ["forehand_disguise_inside_out_inside_in", "shot_disguise_late_racquet_face", "two_handed_disguise_slice_release", "inside_in_freeze_recovery"],
    },
    {
        "slug": "disguised_return_block_drive",
        "title": "Disguised Return Block-or-Drive",
        "summary": "An identical return preparation that can convert into either a chip block or a full drive forces the server to position the first-volley or third ball without knowing the returner's intended depth and pace.",
        "stat_signature": "Takeback-amplitude similarity index between block and drive preparations above 0.78; server first-volley positioning error rate (depth or direction) above 28 % on disguised-drive returns; returner first-ball aggression rate (deep drive converted) above 45 % when the serve is returnable.",
        "mechanism": "A chip-block or drive off the return diverge in pace and depth by 30–45 % depending on contact firmness. By replicating the backswing through the loading phase, the returner forces the server to commit to a volley depth before contact determines which ball arrives. A net-approaching server who positions shallow gets a drive past them; a server who holds deep gets a chip angled away.",
        "conditions": "Most effective against serve-and-volley or chip-and-charge servers who must commit to net position before the return is struck; requires a return preparation that can physically generate either shot from the same swing path; amplified on medium-pace courts where the server's approach timing is not fully rushed.",
        "magnitude": "Servers facing disguised return preparations make positioning errors on the first volley at 26–34 % frequency; converted positioning errors produce net-point-lost outcomes for the server at 62–70 % of those misjudgements.",
        "links": ["return_position_bluff", "serve_toss_location_disguise", "shot_disguise_late_racquet_face"],
    },
    {
        "slug": "drop_shot_late_wrist_check",
        "title": "Late-Wrist Drop Check",
        "summary": "Decelerating the racquet head at the final contact instant converts a full drive swing into a drop shot, withholding the deceleration cue until too late for the opponent to reverse a backward defensive stance into a forward sprint.",
        "stat_signature": "Racquet-head speed drop in the final 0.06 s above 55 % of peak swing speed; opponent late-reaction frequency (reaching the drop shot after it has bounced twice) above 22 % per execution; opponent forward-sprint-trigger delay above 0.25 s compared with a telegraphed drop.",
        "mechanism": "The brain recognises deceleration in the swing arc as the primary drop-shot discriminator. A late wrist check that delays deceleration past the opponent's motor planning window — typically 0.15–0.20 s before contact — produces a committed defensive step-back before the drop signal registers; the reversal sprint then begins from behind the baseline, covering 6+ m.",
        "conditions": "Requires a drive-heavy rally context where the deceleration is genuinely unexpected; most effective from mid-court where the drop lands in the service box with maximum distance from the opponent; less effective if deployed repeatedly in close succession, as opponents shift their baseline depth forward in anticipation.",
        "magnitude": "Late-wrist drop shots are reached before the second bounce at 55–64 % frequency; when reached late (off the run near the net), the resulting reply is shallow or angled poorly in 52–60 % of cases, producing a put-away opportunity.",
        "links": ["drop_drive_shared_preparation", "drop_volley_touch_disguise", "open_stance_direction_mask"],
    },
    {
        "slug": "second_serve_intent_concealment",
        "title": "Second-Serve Intent Concealment",
        "summary": "Hiding whether a second delivery will be a conservative kick safety or an aggressive spot serve keeps the returner from pre-positioning at an attacking depth, preserving second-serve points-won closer to first-serve levels.",
        "stat_signature": "Pre-toss routine similarity index across kick and aggressive spot second serves above 0.80; returner depth-positioning misjudgement rate above 30 % per second-serve point; second-serve points-won differential between disguised and non-disguised servers above 5 percentage points against advanced returners.",
        "mechanism": "Returners anticipating a conservative kick second serve step inside the baseline to attack the rise; an aggressive spot delivery into the body then jams them at the wrong depth. Conversely, a telegraphed kick serve allows the returner to back up and load for the high bounce. Uniform routine removes the depth-positioning read that drives this anticipation gap.",
        "conditions": "Most valuable when the server's second serve has genuine pace variation between kick and aggressive deliveries; amplified against returners who exhibit strong positional read (consistently stepping in before second serves); less differentiated when the server lacks a true aggressive second-serve option.",
        "magnitude": "Second-serve points won against read-dependent returners increase by 4–7 percentage points when pre-serve routine concealment is rated high; resulting break-point frequency against the server declines by 0.3–0.5 per service game.",
        "links": ["serve_toss_location_disguise", "kick_slice_flat_toss_mirror", "body_serve_jam_disguise", "return_position_bluff"],
    },
    {
        "slug": "lob_drive_shared_setup",
        "title": "Lob-Drive Shared Setup",
        "summary": "A groundstroke setup positioned and loaded identically for a passing drive and a topspin lob forces a net-approaching opponent to commit to a volley intercept or overhead retreat without knowing which shot is coming.",
        "stat_signature": "Backswing-plane similarity index between lob and drive preparations above 0.81; net-player wrong-commit rate (poaching at volley height when a lob arrives, or retreating when a drive comes) above 29 % per execution; net-point-lost rate for the net player following a wrong commit above 64 %.",
        "mechanism": "A net rusher reads the passing-shot swing plane to determine whether to close for the volley or retreat for the overhead. A shared setup delays that read until racquet-face angle at contact; by then, the net player's weight is shifted in the wrong direction and the recovery is incomplete — either the overhead is uncovered or the volley is abandoned mid-approach.",
        "conditions": "Most effective against serve-and-volley or split-step net rushers who rely on swing-plane reading; amplified on clay where the topspin lob can be loaded with significant dip over the retreating player; requires a contact height around waist that physically accommodates both shot trajectories.",
        "magnitude": "Topspin lobs disguised off a drive-setup force the net player to retreat past the service line in 48–58 % of executions; disguised drives against a retreating net player produce open-court winners at 55–62 % frequency.",
        "links": ["drop_drive_shared_preparation", "net_approach_fake_baseline_hold", "shot_disguise_late_racquet_face"],
    },
    {
        "slug": "open_stance_direction_mask",
        "title": "Open-Stance Direction Mask",
        "summary": "A neutral open stance withholds the footwork and weight-transfer cues that would normally reveal shot direction, keeping the opponent in a symmetric split until racquet-face rotation commits the ball's path.",
        "stat_signature": "Stance-to-contact directional-cue lead time below 0.12 s in open-stance executions versus 0.20–0.28 s in closed or semi-open stances; opponent split-step bias error above 28 % per open-stance shot; direction-read accuracy for opponents below 58 % against consistent open-stance players.",
        "mechanism": "Closed and semi-open stances produce sequential weight shifts — back-hip load followed by front-foot plant — that reveal direction 0.20 s before contact. An open stance routes power through hip rotation without a front-foot cue, delaying directional commitment until the hips fire; hip-rotation direction is readable only 0.08–0.12 s before contact, insufficient for a reliable pre-contact lean.",
        "conditions": "Requires groundstroke proficiency from open stance on both forehand and backhand sides; most effective at mid-court to inside-the-court contact points where open-stance reach accommodates both directions; amplified against opponents whose split step is momentum-biased rather than fully neutral.",
        "magnitude": "Open-stance groundstrokes against read-dependent opponents produce wrong-direction recoveries at 26–34 % frequency; combined with late racquet-face reveals, this generates forced-error or open-court winner outcomes in 48–56 % of those misreads.",
        "links": ["forehand_disguise_inside_out_inside_in", "shot_disguise_late_racquet_face", "drop_drive_shared_preparation", "inside_in_freeze_recovery"],
    },
    {
        "slug": "body_serve_jam_disguise",
        "title": "Body-Serve Jam Disguise",
        "summary": "A jamming body serve disguised within a wide-or-T toss look crowds the returner's swing by arriving at the hip when the returner has pre-positioned for an away delivery, producing cramped contact and a central or short return.",
        "stat_signature": "Toss-cue similarity across wide, T, and body serves above 0.79 composite index; cramped-contact rate (return striking the frame or inside-out) above 26 % on disguised body serves; central-return frequency (landing in the middle third of the court) above 48 % from cramped contacts.",
        "mechanism": "A returner pre-positioning for a wide or T serve loads weight laterally away from the body, opening the swing path. A body delivery that arrives at the hip then cannot be struck cleanly from that pre-loaded stance; the returner must either collapse the swing path or re-step inward under time pressure, both degrading contact quality and removing angle.",
        "conditions": "Most effective against returners who cheat strongly to either the wide or T side; amplified on fast surfaces where pre-lean is most committed; requires a wrist snap that redirects the ball inward from a toss near the wide or T position.",
        "magnitude": "Body serves arriving when the returner has pre-leaned wide produce a central or short return at 44–54 % frequency versus 28–34 % when the returner is correctly positioned; third-ball attack conversion from central returns exceeds 60 %.",
        "links": ["serve_toss_location_disguise", "kick_slice_flat_toss_mirror", "second_serve_intent_concealment"],
    },
    {
        "slug": "shot_disguise_late_racquet_face",
        "title": "Late Racquet-Face Reveal",
        "summary": "Keeping the racquet-face angle neutral across multiple shot options until the final contact frames hides both spin type and direction simultaneously, producing the maximum possible read latency for the opponent.",
        "stat_signature": "Face-angle disclosure lead time below 0.09 s before contact on disguised groundstrokes; opponent directional-read error rate above 32 % per executed disguised shot; winning-percentage differential on groundstrokes with low face-disclosure time versus high disclosure above 8 percentage points.",
        "mechanism": "Spin and direction are jointly encoded in racquet-face angle at contact. Early face opening is the primary read pathway for opponents positioning on the split step. A player who delays face angle through a neutral swing plane maintains ambiguity across cross, down-the-line, slice, and top-spin simultaneously, forcing the opponent to split neutrally and react post-contact — a reaction-time pathway that is 0.05–0.10 s slower.",
        "conditions": "Requires wrist and forearm flexibility that can execute multiple spin types off the same swing path; most effective from prepared, balanced positions where stroke mechanics allow full ambiguity; amplified against net rushers who must make positioning decisions before contact.",
        "magnitude": "Groundstrokes with face-disclosure lead times below 0.10 s win 8–12 percentage points more often than the same player's telegraphed shots; opponents reduce anticipation lean frequency by 20–28 % against validated late-reveal players, defaulting to a fully reactive split that slows coverage.",
        "links": ["open_stance_direction_mask", "backhand_dtl_crosscourt_hold", "forehand_disguise_inside_out_inside_in", "two_handed_disguise_slice_release"],
    },
    {
        "slug": "return_position_bluff",
        "title": "Return-Position Bluff",
        "summary": "Shifting return stance pre-serve to suggest coverage of one zone then repositioning at the toss to cover another zone influences the server's placement decision while reclaiming the originally implied zone.",
        "stat_signature": "Pre-serve position shift magnitude above 0.4 m lateral versus actual contact-coverage position; server location-choice bias toward the bluffed zone above 28 % above baseline; serve placement shift induced per set above 2.1 instances of measurable server direction adjustment.",
        "mechanism": "Servers calibrate delivery placement to the returner's apparent coverage gap. A pre-serve positional bluff inflates the apparent gap in one zone, inviting the server to target it; the returner recovers to that zone at the toss, closing the gap they advertised. The server's planned delivery then arrives to a covered zone, negating the placement advantage.",
        "conditions": "Most effective against servers who read returner position at the service line routine stage; requires the returner to recover the bluffed zone fully by the toss without telegraphing the movement; amplified against predictable servers who commit heavily to one serve based on returner-position reads.",
        "magnitude": "Servers who shift placement toward a bluffed zone produce a first-serve-points-won reduction of 4–7 percentage points on those deliveries versus equivalent serves to unbluffed targets; the bluff amplifies when the returner has a reliable strong-zone forehand or backhand to punish the induced placement.",
        "links": ["disguised_return_block_drive", "second_serve_intent_concealment", "serve_toss_location_disguise"],
    },
    {
        "slug": "inside_in_freeze_recovery",
        "title": "Direction-Freeze Recovery Bait",
        "summary": "A contact look that briefly freezes the opponent's recovery split by holding directional ambiguity past the normal commitment window, then releases the ball in the opposite direction to the opponent's loaded recovery momentum.",
        "stat_signature": "Opponent split-step timing delay above 0.12 s on freeze-baited shots versus normally-readable shots; wrong-side recovery frequency above 30 % per baited execution; resulting open-court winner or forced-error rate from the wrong-side recovery above 54 %.",
        "mechanism": "During a rally, opponents initiate a recovery split step partially responsive to subtle cue reading of ball trajectory before it is struck. Extending directional ambiguity past the 0.15 s pre-contact window causes the opponent to initiate the split without directional lean, then scramble late; delivering the ball to the side opposite the scramble direction exploits residual momentum that the opponent cannot fully arrest.",
        "conditions": "Requires executing during a neutral rally position where both directions are genuinely hittable; amplified against opponents with a slow split-step reset who cannot generate explosive crossover steps from a stuck position; less effective against opponents with equal-speed lateral movement in both directions.",
        "magnitude": "Baited wrong-side recoveries produce open-court coverage gaps of 1.2–1.8 m that convert to winners or forced errors at 50–58 % frequency; the freeze effect is most consistent when combined with late racquet-face reveals that jointly suppress directional and spin reads.",
        "links": ["open_stance_direction_mask", "forehand_disguise_inside_out_inside_in", "backhand_dtl_crosscourt_hold", "shot_disguise_late_racquet_face"],
    },
    {
        "slug": "two_handed_disguise_slice_release",
        "title": "Grip-Shift Release Disguise",
        "summary": "A late grip-shift or second-hand release during the backswing converts a topspin two-handed look into a one-handed slice, delivering a low skidding ball when the opponent has loaded for a high-bouncing topspin reply.",
        "stat_signature": "Takeback-grip-change timing below 0.12 s before contact on disguised-slice releases; opponent contact-quality drop on the following shot above 28 % (short or high float) against disguised slices; opponent loaded-for-topspin positional error above 32 % per executed grip-shift release.",
        "mechanism": "Opponents read topspin preparation by the two-handed backswing and coil phase and pre-load a high-contact response for the expected bouncing ball. A late second-hand release and face-open at contact produces a slice that skids low and stays below knee height after the bounce; the pre-loaded high-contact swing then produces an off-centre, floating return as the opponent adjusts downward under time pressure.",
        "conditions": "Requires a player whose two-handed and one-handed backhand slice are sufficiently similar in takeback to sustain the disguise; most effective on medium-pace hard courts where slice stays low; amplified against players whose high-ball preparation is strong but whose recovery to low balls is slower.",
        "magnitude": "Disguised-slice releases produce a reply ball at net height or below in 44–54 % of opponent contacts, versus 18–24 % when the slice is telegraphed by an early hand release; the resulting short or high-float reply is converted to an offensive shot at 60–68 % frequency.",
        "links": ["backhand_dtl_crosscourt_hold", "shot_disguise_late_racquet_face", "open_stance_direction_mask"],
    },
    {
        "slug": "serve_plus_one_pattern_masking",
        "title": "Serve-Plus-One Pattern Masking",
        "summary": "Varying serve placement so that the subsequent third-ball shot location cannot be reliably predicted from serve direction prevents the returner from pre-loading for the expected follow-up, keeping third-ball aggression high from multiple serve zones.",
        "stat_signature": "Serve-to-next-shot directional correlation below 0.45 (disrupted pattern; high correlation is 0.65+); returner anticipation-collapse rate on third ball above 30 % when pattern masking is deployed; third-ball winner and forced-error rate across all serve zones exceeding 42 % against pattern-reading opponents.",
        "mechanism": "Predictable serve-plus-one patterns allow advanced returners to neutralise the third ball by pre-positioning for the expected location even before the serve contacts the string bed. Decorrelating serve direction from follow-up direction eliminates this anticipation premium; the returner must react to both balls independently, processing each as an isolated event rather than a pre-loaded pattern.",
        "conditions": "Requires genuine shot-making ability from multiple serve positions — the follow-up shot from a wide serve must differ meaningfully from a T serve in a non-predictable manner; most effective against pattern-reading opponents who explicitly adjust return depth and position based on serve zone history.",
        "magnitude": "Pattern-masked serve-plus-one sequences produce opponent split-step errors on the third ball at 28–36 % frequency; total third-ball attack conversion rate is 6–10 percentage points above the server's baseline against the same opponent when patterns are predictable.",
        "links": ["serve_toss_location_disguise", "return_position_bluff", "forehand_disguise_inside_out_inside_in"],
    },
    {
        "slug": "drop_volley_touch_disguise",
        "title": "Drop-Volley Touch Disguise",
        "summary": "An aggressive volley body language and swing initiation that softens into a touch drop volley at contact exploits an opponent sprinting into a defensive passing position who is unprepared to reverse course for a drop that barely clears the net.",
        "stat_signature": "Swing-deceleration at contact above 60 % of peak swing speed on disguised drop volleys; opponent late-sprint-trigger frequency (reaction delayed above 0.20 s) above 35 % per execution; drop-volley outright-winner rate off disguised preparations above 52 % versus 34 % off telegraphed softening.",
        "mechanism": "A passing-shot retriever sprinting wide or backward pre-loads for a deep, pace-absorbing defensive shot once the net player shows an aggressive swing; their recovery toward the net anticipates a put-away deep volley. A touch deceleration at contact produces a ball dying inside the service box; the sprinting opponent cannot reverse course before the ball bounces twice, as their momentum is committed away from the net.",
        "conditions": "Requires a net-play contact point at mid-court height where a touch volley remains unattackable; most effective when the opponent is committed in a deep defensive sprint; less reliable against opponents who read deceleration cues at the net by watching hand firmness rather than swing arc.",
        "magnitude": "Drop volleys disguised behind aggressive swing initiations win the point outright at 50–58 % frequency; undisguised drop volleys from the same net positions win 30–38 % outright, a 18–22 percentage-point disguise premium reflecting the opponent's committed sprint momentum.",
        "links": ["drop_drive_shared_preparation", "drop_shot_late_wrist_check", "lob_drive_shared_setup", "half_volley_drop_disguise"],
    },
    {
        "slug": "half_volley_drop_disguise",
        "title": "Half-Volley Drop Disguise",
        "summary": "A punch-volley setup that converts to a touch drop volley near the feet exploits the opponent's expectation of a deep punched reply, inducing a forward-recovery delay that leaves the short ball uncontested.",
        "stat_signature": "Hand-firmness change at contact above 45 % deceleration on disguised drop half-volleys; opponent forward-recovery delay above 0.22 s versus response to telegraphed drops; short-ball-left-uncontested rate above 30 % when executed from a low contact point at the service line.",
        "mechanism": "A half volley taken at shoe level is a mechanically awkward shot that most opponents expect to be punched back deep; they position for a defensive exchange rather than a touch reply. Converting the punch into a drop by opening the face and absorbing pace at contact produces a ball that lands in the service box before the opponent moves forward, as they have waited for the expected deep ball.",
        "conditions": "Most effective after an approach that forces the opponent deep and a subsequent low volley that compresses their passing-shot angle; requires a deft hand that can generate feel from a low contact point; amplified when the opponent is behind the baseline and must cover 6+ m forward.",
        "magnitude": "Disguised drop half-volleys are contested before the second bounce by the opponent in only 42–50 % of executions; the short-ball replies generated from late-running opponents produce a follow-up putaway at 60–68 % frequency.",
        "links": ["drop_volley_touch_disguise", "drop_shot_late_wrist_check", "drop_drive_shared_preparation"],
    },
]
