"""Soccer / DeceptionDisguise — person-free concept-node spec."""
from __future__ import annotations

SPORT = "Soccer"
FAMILY = "DeceptionDisguise"

CONCEPTS: list[dict] = [
    {
        "slug": "body_feint_weight_commit",
        "title": "Body-Feint Weight Commit",
        "summary": "A shoulder-drop or hip-dip shifts a defender's center of mass one way before the ball-carrier exits the opposite direction, exploiting the 150-250 ms reactive balance correction the defender must complete.",
        "stat_signature": "Dribble success rate rises ~8-12 pp when measurable center-of-mass displacement (>5 cm lateral) precedes the take-on; defenders who over-commit require ≥2 recovery steps before regaining goal-side position.",
        "mechanism": "Defenders prioritize center-of-mass cues over foot-contact cues. A pronounced shoulder-drop triggers an early weight-transfer response; before the defender reverses it, the attacker has exploited the gap in the committed direction.",
        "conditions": "Most effective in 1v1 wide-channel duels at 60-80% sprint speed when the defender is in a narrow stance. Effect diminishes against a passive jockeying shape that withholds weight commitment.",
        "magnitude": "Completed-dribble rate typically 8-14 pp above baseline in wide areas; largest in the final third where defenders must simultaneously track the ball and maintain goal-side positioning.",
        "links": ["step_over_directional_bait", "scissor_double_feint", "drag_back_deceleration_trap", "feint_pass_dribble_branch"],
    },
    {
        "slug": "step_over_directional_bait",
        "title": "Step-Over Directional Bait",
        "summary": "Circling the non-striking foot over the ball manufactures a false touch cue, causing the defender to react to a direction the ball never travels; effectiveness depends on foot-speed and the sell of the hip rotation.",
        "stat_signature": "Defenders commit their first step in the feint direction on ~55-65% of well-executed step-overs; subsequent beat-the-defender rate is roughly 1.4-1.7x the baseline dribble-success rate.",
        "mechanism": "The peripheral visual system is tuned to limb-velocity signals. A fast foot arc over the ball overwhelms the slower contextual read that would reveal the ball has not moved, causing a false-positive defensive step.",
        "conditions": "Most disruptive against defenders in close-pressing range (1.5-2.5 m) on firm surfaces with good traction. Diminished against deep-defending teams that set a passive block.",
        "magnitude": "Beat-the-defender frequency roughly 40-70% above baseline after confirmed defender first-step error; double step-overs add a second displacement layer but carry higher ball-loss risk.",
        "links": ["body_feint_weight_commit", "scissor_double_feint", "feint_pass_dribble_branch"],
    },
    {
        "slug": "disguised_through_ball",
        "title": "Disguised Through-Ball",
        "summary": "Opening the hips or using a no-backlift pass shape hides a penetrating ball until release, giving the defensive line less than one reaction cycle to step up or hold shape.",
        "stat_signature": "Defensive line reaction delay increases by 0.15-0.25 s on disguised versus telegraphed through-balls; line-break completion rate is roughly 15-22 pp higher when passer hip orientation mismatches the delivery direction.",
        "mechanism": "Offside-trap timing relies on reading the passer's body shape before contact. A hip orientation implying a lateral pass holds the back line; delayed recognition of the true direction leaves a gap behind.",
        "conditions": "Requires a runner with pre-run timing and sufficient technique for a no-backlift or open-hip delivery. Most effective against a high-line defense that commits to the trap early.",
        "magnitude": "Line-break creation rate roughly doubles on well-disguised attempts; expected-goal value of resulting chances is typically 1.5-2.5x that of possession in the same zone without a line-break.",
        "links": ["no_look_release_disguise", "dummy_let_run_through", "decoy_run_space_manipulation"],
    },
    {
        "slug": "no_look_release_disguise",
        "title": "No-Look Release Disguise",
        "summary": "Head and eye orientation toward a false target freezes a covering defender long enough for the ball to reach an unmarked receiver, most valuable in congested central zones.",
        "stat_signature": "Marker drift toward the false read averages 0.8-1.5 m lateral displacement on confirmed no-look deliveries; unmarked-receiver reception rate is roughly 20-30 pp above matched-look pass rates.",
        "mechanism": "Defenders use gaze direction as a proxy for imminent pass destination. Sustained head orientation away from the true target delays the covering decision until the ball is already in flight.",
        "conditions": "Requires a passer with strong peripheral vision and a receiver making a timed run. Highly effective when the covering defender is centrally positioned and must choose between two potential receivers.",
        "magnitude": "Open-reception rate lifts by 18-28 pp in high-traffic central zones; in wide areas with fewer coverage decisions the deception advantage narrows to roughly 8-12 pp.",
        "links": ["disguised_through_ball", "dummy_let_run_through", "decoy_run_space_manipulation"],
    },
    {
        "slug": "shot_fake_block_displacement",
        "title": "Shot-Fake Block Displacement",
        "summary": "A wind-up replicating the kinematic signature of a shot collapses a defender or goalkeeper into a block-ready posture before the attacker pulls back or lays the ball off to a free runner.",
        "stat_signature": "Defenders commit to a block stance on ~50-65% of convincing shot fakes within the penalty area; cleared-channel frequency rises to 60-75% when two defenders react simultaneously.",
        "mechanism": "The shot-wind-up cue triggers an instinctive block reflex that locks the defender's center of mass low toward the expected ball trajectory; recovery takes 300-450 ms, sufficient for the attacker to find an unmarked option.",
        "conditions": "Most effective inside the penalty area where the shot threat is credible. Requires a supporting runner in the lay-off zone and a defender who cannot drop into a passive low-block shape.",
        "magnitude": "Open-shot or open-pass window creation roughly doubles compared with unfeinted possession in the same area; resulting chances typically originate from closer range or with fewer defenders between ball and goal.",
        "links": ["fake_shot_lay_off", "body_feint_weight_commit", "goalkeeper_stay_big_feint"],
    },
    {
        "slug": "drag_back_deceleration_trap",
        "title": "Drag-Back Deceleration Trap",
        "summary": "Pulling the ball backward sharply invites a lunging tackle from an over-committed defender, then re-accelerating into the suddenly vacated space exploits the defender's recovery inertia.",
        "stat_signature": "Tackle-commit rate rises to ~60-75% on convincing drag-back setups where the attacker's forward momentum briefly halts; recovered-yardage gain post-drag averages 4-8 m before the next challenge.",
        "mechanism": "Forwards-pressing defenders interpret rapid deceleration as a loss of control and lunge to win the ball. The drag removes the ball from the tackle zone while preserving attacker balance, leaving the defender over-extended.",
        "conditions": "Works best when the defender has committed forward momentum and limited lateral recovery capacity. High-pressing, man-marking schemes produce the most over-committed lunges.",
        "magnitude": "Ball-retention rate on lunge-provoked drag-backs roughly 70-80%; subsequent carry typically advances 4-8 m beyond the original duel position before a new defensive challenge arrives.",
        "links": ["body_feint_weight_commit", "scissor_double_feint", "disguised_first_touch_redirect"],
    },
    {
        "slug": "fake_shot_lay_off",
        "title": "Fake-Shot Lay-Off",
        "summary": "Simulating a shooting motion collapses multiple defenders inward toward the ball-carrier, opening a lay-off to a free runner arriving into the vacated peripheral channel.",
        "stat_signature": "Inward-defender collapse count averages 1.4-1.8 per fake-shot sequence inside the area; open-shot creation rate for the lay-off recipient is roughly 55-70% when the fake draws two or more defenders.",
        "mechanism": "Shot-anticipation posture is a collective defensive reflex; multiple defenders shift toward the projected shot line simultaneously, leaving peripheral support runners unmarked for 300-500 ms after the fake.",
        "conditions": "Requires at least one supporting runner arriving into the lay-off zone and a credible shooting position for the fake. Most effective when the attacker has already beaten the last defender one-on-one.",
        "magnitude": "Expected-goal value of lay-off shots averages roughly 0.12-0.20 xG when the sequence successfully draws two defenders; contrast with ~0.07-0.10 xG for possession in the same zone without a fake.",
        "links": ["shot_fake_block_displacement", "decoy_run_space_manipulation", "goalkeeper_stay_big_feint"],
    },
    {
        "slug": "dummy_let_run_through",
        "title": "Dummy Let-Run",
        "summary": "A player steps over an incoming pass without touching it, allowing the ball to run through to a teammate while wrong-footing the marker who anticipated a control touch.",
        "stat_signature": "Defender step-toward-ball commit occurs on ~55-70% of convincing dummies; through-runner reception rate is roughly 60-75% when the marker commits within 0.5 s of the pass release.",
        "mechanism": "Defenders assign high probability to ball-carrier contact on receiving a pass. The dummy step mimics the kinematic signature of a control touch without contact, drawing the marker to a ball that is no longer there.",
        "conditions": "Requires precise timing coordination between the dummy player and through-runner. Most effective when the dummy player is tightly marked and the through-runner approaches from a blind-side angle.",
        "magnitude": "Through-runner reception in a forward-facing, unpressured position occurs on roughly 60-75% of well-executed dummies; the resulting carrying opportunity typically yields 8-12 m of uncontested space.",
        "links": ["disguised_through_ball", "decoy_run_space_manipulation", "no_look_release_disguise"],
    },
    {
        "slug": "penalty_run_up_stutter",
        "title": "Penalty Run-Up Stutter Deception",
        "summary": "A paused or non-uniform approach to a spot-kick baits the goalkeeper into an early dive, then the kicker places the ball to the opposite side of the committed keeper.",
        "stat_signature": "Goalkeeper pre-contact dive rate averages 35-50% on confirmed stutter approaches; side-correlation between keeper guess and actual placement falls below 0.30 on baited attempts, compared with ~0.52 on conventional run-ups.",
        "mechanism": "Goalkeepers must decide their dive direction within 200-300 ms of contact due to ball flight time constraints. A stutter-step increases time pressure and ambiguity, prompting an early dive decision based on incomplete run-up cues.",
        "conditions": "Requires deliberate pause or speed variation to register as an anomaly to the goalkeeper's pattern-matching system. Most effective against keepers who prefer early-commitment dive strategies.",
        "magnitude": "Conversion rate on baited-dive penalties is roughly 80-88% versus ~74-78% on conventional spot-kicks at the top level; stutter effectiveness decays with repetition as keepers adapt their pre-save strategy.",
        "links": ["fake_set_piece_routine", "goalkeeper_stay_big_feint", "shot_fake_block_displacement"],
    },
    {
        "slug": "feint_pass_dribble_branch",
        "title": "Pass-or-Dribble Branch Feint",
        "summary": "A planted pass shape that can convert to a dribble holds two defenders in place, neither able to fully commit to blocking the pass lane or the dribble channel simultaneously.",
        "stat_signature": "Dual-defender freeze (both nearby defenders delay their press by ≥0.3 s) occurs on ~40-55% of confirmed branch-feint situations; branch-decision success rate is roughly 15-20 pp above single-option possession in similar density.",
        "mechanism": "Two defenders must cover two distinct threat vectors simultaneously. A body shape geometrically valid for both outcomes creates a coverage dilemma; the ball-carrier reads which branch the defenders have left open and commits.",
        "conditions": "Most effective in central midfield or the half-space with a nearby pass option and a dribble lane simultaneously available. Requires composure and quick scanning to identify the open branch before committing.",
        "magnitude": "Successful branch selection roughly doubles the chance-creating outcome rate compared with forced single-option plays in similar high-pressure central situations.",
        "links": ["body_feint_weight_commit", "step_over_directional_bait", "no_look_release_disguise"],
    },
    {
        "slug": "fake_set_piece_routine",
        "title": "Set-Piece Decoy Routine",
        "summary": "A dead-ball delivery is shaped toward one option to shift the wall or markers before the true delivery is made to a different zone; repeated primary routines build the defensive expectation the decoy then exploits.",
        "stat_signature": "Defensive reorientation displacement averages 1.5-3.0 m per confirmed decoy sequence on corners and free-kicks; chance-creation rate is roughly 1.6-2.0x higher on routines with verified defensive reorientation.",
        "mechanism": "Repeating a delivery to the same target builds anticipatory positioning; switching to a decoy routine exploits the learned expectation, catching defenders mid-shift toward the false target.",
        "conditions": "Requires established routine repetition to build the defensive expectation being exploited. Most effective later in matches after the primary routine has drawn consistent defensive alignment.",
        "magnitude": "Shot or header attempts from decoy-generated openings carry roughly 0.05-0.12 xG uplift per delivery; corner-kick goal rates roughly double on confirmed reorientation sequences.",
        "links": ["penalty_run_up_stutter", "decoy_run_space_manipulation", "no_look_release_disguise"],
    },
    {
        "slug": "decoy_run_space_manipulation",
        "title": "Decoy-Run Space Manipulation",
        "summary": "An off-ball runner fakes a penetrating run to drag a marker out of position, opening a lane for a teammate's actual movement or reception when the decoy run forces a genuine tracking commitment.",
        "stat_signature": "Marker displacement caused by confirmed decoy runs averages 3-6 m; vacated-zone exploitation rate (teammate receives in the freed space within two seconds) is roughly 40-55% on coordinated sequences.",
        "mechanism": "Man-marking defenders must track assigned runners. A well-timed decoy run into a dangerous zone forces the marker to follow or concede the space; either outcome creates an opening for the primary ball-receiver.",
        "conditions": "Depends on coordinated timing between decoy runner and ball-receiver. Effective against tight man-marking schemes and in final-third half-space entries where the marker faces a genuine coverage dilemma.",
        "magnitude": "Freed-zone reception rate roughly 40-55% on well-timed decoys; the coordinated chance-quality lift is typically 0.04-0.08 xG per sequence compared with uncoordinated movement into the same zone.",
        "links": ["fake_shot_lay_off", "no_look_release_disguise", "disguised_through_ball", "dummy_let_run_through"],
    },
    {
        "slug": "disguised_first_touch_redirect",
        "title": "Disguised First-Touch Redirect",
        "summary": "A body shape on reception that implies one control direction is converted at contact into a redirect away from the pressing defender, retaining possession under pressure.",
        "stat_signature": "Press-arrival error (defender commits to the implied direction) occurs on roughly 45-60% of well-disguised redirects; retained-possession-under-pressure rate rises roughly 20-30 pp compared with unopposed first touches in the same zone.",
        "mechanism": "Pressing defenders time their approach based on the receiver's pre-contact body orientation. A deliberately misleading hip angle causes the presser to over-commit before the true redirect direction is revealed.",
        "conditions": "Most valuable when receiving under high press in central midfield or the build-up third. Requires sufficient technical quality to redirect cleanly with a non-dominant surface under physical pressure.",
        "magnitude": "Possession-retention rate roughly 20-30 pp above same-zone pressed receptions without disguise; subsequent progressive-pass opportunity rate rises by roughly 15 pp when the press is successfully bypassed.",
        "links": ["drag_back_deceleration_trap", "disguised_through_ball", "dummy_let_run_through"],
    },
    {
        "slug": "goalkeeper_stay_big_feint",
        "title": "Goalkeeper Stay-Big Feint",
        "summary": "A goalkeeper feigns early-dive commitment in a 1v1, baiting the ball-carrier into a premature decision that reduces shot accuracy, then recovers to cover the most likely corner.",
        "stat_signature": "Attacker shot-timing acceleration (shooting earlier than optimal) occurs on ~40-55% of confirmed stay-big feints; save-rate lift on baited attempts is roughly 8-14 pp above baseline 1v1 conversion rates at equivalent distance and angle.",
        "mechanism": "Attackers in 1v1 situations scan for keeper movement to inform placement decisions. A feigned early commitment narrows the attacker's perceived open corner; rushing the shot before the keeper fully recovers degrades placement accuracy.",
        "conditions": "Most effective when the attacker has controlled the ball at speed and has limited time to reassess. Diminished when the attacker has stopped and has full composure to reset the shot decision.",
        "magnitude": "1v1 conversion rates drop by roughly 8-14 pp on baited attempts; the feint is most decisive when the attacker is moving at high speed, compressing the decision window below ~0.4 s.",
        "links": ["shot_fake_block_displacement", "penalty_run_up_stutter", "fake_shot_lay_off"],
    },
    {
        "slug": "scissor_double_feint",
        "title": "Scissor Double-Feint",
        "summary": "Consecutive step-overs in alternating directions double-fake the defender's recovery, accumulating lateral displacement with each false read before the real touch exits.",
        "stat_signature": "Defender direction-reversal count averages 1.8-2.4 per double-feint sequence; cumulative lateral displacement before the real touch is typically 1.2-2.0 m, enough to open a clear dribbling lane in tight wide-channel duels.",
        "mechanism": "Each false step-over resets the defender's momentum in the opposite direction; the second feint exploits the over-correction from the first, producing compounding balance debt the defender cannot clear before the exit touch.",
        "conditions": "Most effective against aggressive close-pressing defenders in 1v1 wide situations with adequate space behind the defender. Requires sufficient close-control to maintain ball proximity during the sequence.",
        "magnitude": "Completed-dribble rate roughly 1.6-2.0x the single-feint baseline in matched wide-channel duels; carry-speed into open space is typically maintained better than after a single high-risk feint.",
        "links": ["step_over_directional_bait", "body_feint_weight_commit", "drag_back_deceleration_trap"],
    },
]
