"""MLB DeceptionDisguise concept nodes — person-free pitch and baserunning deception intelligence."""
from __future__ import annotations

SPORT = "MLB"
FAMILY = "DeceptionDisguise"

CONCEPTS: list[dict] = [
    {
        "slug": "pitch_tunneling_commit_point",
        "title": "Pitch Tunneling Commit Point",
        "summary": "Two distinct pitches sharing a near-identical release-to-commit-point trajectory force the hitter to commit before the paths diverge; the narrower the tunnel distance at the commit point the fewer distinctions a hitter can make in time.",
        "stat_signature": "Tunnel distance at commit point below 3.0 inches between fastball and breaking ball; post-tunnel break separation above 12 inches for elite tunneling pairs; swing-and-miss rate on tunneled secondary pitches above 38 %.",
        "mechanism": "Hitters must decide to swing within roughly 150-170 ms of pitch release; two pitches sharing early trajectory deny the hitter velocity or break cues until after the decision point, converting perceived pitching repertoire depth into genuine cognitive overload.",
        "conditions": "Most effective on breaking-ball and change-up pairs thrown off a consistent fastball; amplified when the pitcher commands all quadrants rather than just one; degrades when release-point variance widens the effective commit-point separation.",
        "magnitude": "Top tunneling-pair pitchers suppress same-sequence swing-and-miss rates 8-12 points above equivalent velocity pitchers without tunneling discipline; whiff rate on a well-tunneled secondary pitch exceeds league average by roughly 10-15 percentage points.",
        "links": ["release_point_consistency_disguise", "breaking_ball_shape_overlap", "eye_level_change_sequencing", "times_through_order_decay"],
    },
    {
        "slug": "release_point_consistency_disguise",
        "title": "Release-Point Consistency Disguise",
        "summary": "Minimizing arm-slot and release-coordinate variance across all pitch types so velocity and movement reads emerge identical until the ball is in flight; hitters cannot pre-sort pitch type by delivery cues.",
        "stat_signature": "Release-point cluster radius below 1.5 inches across the full arsenal; horizontal release spread below 0.8 inches between fastball and change-up; per-pitch-type release-height delta below 0.4 inches.",
        "mechanism": "The arm-slot and release-point are the first cues a hitter reads; a pitcher whose slider and four-seamer originate from an indistinguishable coordinate forces the hitter to wait for ball-flight and flight-path information rather than pre-loading timing on delivery cues.",
        "conditions": "Consistency gains most value against hitters who index heavily on delivery cues; matters most through the second and third time through the order as hitters accumulate cue calibration; attenuated against extreme-velocity differentials that override cue reading.",
        "magnitude": "Pitchers maintaining sub-1.5-inch cluster radius across pitch types generate first-pitch whiff rates roughly 3-5 points above pitchers with 2.5+ inch spread; recognition-time advantage translates to roughly 0.04-0.08 wOBA-against reduction per plate appearance.",
        "links": ["pitch_tunneling_commit_point", "fastball_changeup_arm_speed_mirror", "perceived_velocity_extension", "times_through_order_decay"],
    },
    {
        "slug": "fastball_changeup_arm_speed_mirror",
        "title": "Fastball-Changeup Arm-Speed Mirror",
        "summary": "Matching arm acceleration on an off-speed pitch to its fastball hides the velocity delta until the grip and seam orientation take effect; the hitter reads a fastball cue and receives a slower pitch with late sink.",
        "stat_signature": "Arm-speed differential between four-seam and change-up below 5 mph equivalent; swing-and-miss rate on change-up above 35 %; change-up chase rate out of zone above 42 %; wOBA-against on change-up below .270.",
        "mechanism": "Hitters time arm speed as a velocity proxy; when arm speed mirrors the fastball, the hitter's timing initiates on a fastball track, over-committing before the 10-14 mph velocity reduction and late horizontal or vertical movement can be processed.",
        "conditions": "Requires natural arm deceleration through the grip rather than mechanical throttling; more effective against pull-heavy, fastball-dependent hitters; degrades against disciplined two-strike contact approaches that widen recognition windows.",
        "magnitude": "Pitchers with sub-5-mph arm-speed differential on change-ups generate swing-and-miss rates 6-10 points above average off-speed; the arm-speed mirror effect is worth roughly 0.025-0.040 wOBA reduction per change-up plate appearance versus an unmasked delivery.",
        "links": ["release_point_consistency_disguise", "pitch_tunneling_commit_point", "eye_level_change_sequencing", "two_strike_approach_conversion"],
    },
    {
        "slug": "breaking_ball_shape_overlap",
        "title": "Breaking-Ball Shape Overlap",
        "summary": "Starting a slider and curveball on overlapping early trajectories before late-flight divergence exploits the hitter's inability to distinguish the pitches at commit and forces equal coverage of two break shapes.",
        "stat_signature": "Early-flight overlap angle below 2.5 degrees between slider and curveball pairs; combined called-strike-plus-whiff rate on breaking balls above 52 %; zone-exit chase rate on overlap pairs above 35 %.",
        "mechanism": "Sliders and curveballs originate from the same grip quadrant and share initial trajectory; once they diverge past the commit point the hitter must cover both shapes simultaneously; the cognitive demand suppresses both barrel and solid-contact rates on the pair.",
        "conditions": "Most effective when the slider and curveball have meaningfully different finish shapes (glove-side slide versus downward curve); amplified at higher velocities where the divergence window narrows; reduced value when both pitches miss the same quadrant.",
        "magnitude": "Pitchers with documented shape-overlap breaking-ball pairs generate barrel rates below 4 % on breaking-ball contact; CSW rate premium over single-breaking-ball pitchers is roughly 4-6 percentage points across the arsenal.",
        "links": ["pitch_tunneling_commit_point", "spin_axis_deception", "front_door_back_door_mirror", "two_strike_approach_conversion"],
    },
    {
        "slug": "perceived_velocity_extension",
        "title": "Perceived-Velocity Extension Deception",
        "summary": "Extending release toward home plate reduces ball travel time independent of radar reading, creating a perceived velocity gap that shifts the hitter's timing reference point earlier than the gun indicates.",
        "stat_signature": "Extension above 6.8 feet associated with perceived velocity gains of 1.0-2.5 mph above actual; first-pitch swing rate elevated 3-5 points for high-extension pitchers; whiff rate on fastballs with extension above 7.0 feet roughly 4-6 points above average.",
        "mechanism": "Each additional inch of extension shortens ball-to-plate distance by one inch, reducing flight time proportionally; at 95 mph a 7-foot extension pitcher delivers the ball roughly 6-9 ms faster than a 6-foot extension pitcher at identical radar velocity, equivalent to 1.5-2 mph in hitter timing.",
        "conditions": "Effect largest for tall pitchers with over-the-top mechanics who can physically extend further; partially neutralized by hitters who key on spin direction early rather than timing alone; interacts with downhill plane to compound perceived difficulty.",
        "magnitude": "Moving from 6.0 to 7.0 feet of extension corresponds to roughly 1.2-1.8 mph of perceived velocity gain and a 2-3 percentage-point whiff-rate increase on four-seam fastballs; top-extension pitchers run swinging-strike rates 1.5-2.5 points above extension-adjusted velocity peers.",
        "links": ["release_point_consistency_disguise", "pitch_tunneling_commit_point", "delivery_deception_low_visibility_slot"],
    },
    {
        "slug": "hidden_ball_grip_concealment",
        "title": "Grip-Concealment Tell Suppression",
        "summary": "Hiding ball grip inside the glove until the final milliseconds of delivery denies the hitter or baserunner a visual pitch-type cue, suppressing pre-read advantages that accrue from tipping.",
        "stat_signature": "Pre-release glove-flash frequency below one visible exposure per 15 pitches; opponent pitch-type prediction accuracy correlated with pitcher tipping rate; whiff-rate differential between tipping and non-tipping appearances estimated at 4-7 percentage points.",
        "mechanism": "A visible finger or grip position signals off-speed to an attentive hitter 200-300 ms before release, allowing early timing adjustment; eliminating that visual cue forces the hitter back to ball-flight information only, restoring the full commitment-point uncertainty.",
        "conditions": "Grip-concealment discipline matters most when facing attentive opposing dugouts that relay cue patterns; becomes critical for pitchers with limited velocity separation between pitch types; most exploitable when a catcher signals identically regardless of pitch called.",
        "magnitude": "Catchers who identify opponent tipping document opposing whiff-rate reductions of 5-9 points during tipping sequences; correcting a documented tell restores expected whiff rates within 30-50 plate appearances as adjustment information decays.",
        "links": ["release_point_consistency_disguise", "pitch_tunneling_commit_point", "times_through_order_decay"],
    },
    {
        "slug": "quick_pitch_timing_disruption",
        "title": "Quick-Pitch Timing Disruption",
        "summary": "Accelerating delivery tempo to catch a hitter mid-setup resets pre-pitch routines and forces reactive rather than prepared swings, elevating early-count take rates and disrupting timing on pitches thrown.",
        "stat_signature": "Pitch-clock-to-release time deviation of 3+ seconds below personal average; early-count take-strike rate elevated 4-7 points in quick-delivery sequences; first-pitch swing contact rate depressed 5-8 points on abbreviated tempo pitches.",
        "mechanism": "Hitters rely on pre-pitch setup routines to calibrate timing; a delivery begun before those routines complete forces the hitter to swing from a compromised stance or take a called strike; the disruption effect is strongest for hitters with elongated pre-pitch movements.",
        "conditions": "Most effective after a slow-tempo sequence has set a rhythm expectation; constrained by pitch-clock regulations and umpire judgment; applies most forcefully in early counts where hitters are most selective and setup-dependent.",
        "magnitude": "Quick-delivery appearances generate called-strike rates roughly 3-5 points above sequentially expected rates; the effective disruption window is 2-4 at-bats before hitters recalibrate to the accelerated tempo.",
        "links": ["step_off_balk_threshold_play", "slide_step_tempo_disguise", "pitch_tunneling_commit_point"],
    },
    {
        "slug": "pickoff_move_jump_deception",
        "title": "Pickoff-Move Jump Deception",
        "summary": "A leg-lift or shoulder movement that reads as the beginning of a pitch delivery freezes the leadoff runner's secondary lead, reducing the runner's effective jump distance and stolen-base success probability.",
        "stat_signature": "Runner secondary-lead retreat distance above 3 feet on deceptive holds; pickoff-attempt success rate above 14 % on jump-freeze moves; stolen-base attempt rate depressed 12-18 percentage points against high-deception left-handers.",
        "mechanism": "Runners key on first-move cues from hip rotation and leg lift; a pitcher who mirrors the pitch delivery in a pickoff move exhausts the runner's read before the true direction is revealed; the hesitation costs the runner 0.2-0.3 seconds of jump, translating to approximately 4-5 feet at full sprint.",
        "conditions": "Highest impact against speed-dependent baserunning offenses; left-handed pitchers have structural first-move deception advantages to first base; most effective when paired with variable hold times that further degrade runner timing models.",
        "magnitude": "Elite deceptive pickoff moves suppress stolen-base attempt rates by 15-20 %; when attempts do occur, secondary-lead retreat increases caught-stealing probability by roughly 8-12 percentage points above non-deceptive holds.",
        "links": ["step_off_balk_threshold_play", "slide_step_tempo_disguise", "fake_to_third_throw_first"],
    },
    {
        "slug": "step_off_balk_threshold_play",
        "title": "Step-Off Tempo-Vary Deception",
        "summary": "Varying hold times and step-off sequences to deny a runner a rhythm read on first move, degrading the runner's ability to build a timing model and forcing conservative secondary leads.",
        "stat_signature": "Hold-time standard deviation above 1.2 seconds across a game; runner successful-jump frequency depressed 20-30 % versus low-variation pitchers; step-off frequency above 1 per 3 at-bats with runner on first.",
        "mechanism": "Runners build hold-time probability distributions from within-game observations; high variance in hold times widens that distribution, forcing the runner to initiate from a position that accommodates uncertainty rather than optimizing for a predicted release window.",
        "conditions": "Effective throughout a game but requires enough variation to prevent resampling; less impactful against less aggressive baserunning styles; balk-risk constrains how extreme the deception moves can be.",
        "magnitude": "High hold-time variance pitchers generate stolen-base attempt rates 8-12 points below average; when attempts occur, success rates drop 6-9 points as runners absorb the timing cost of uncertainty rather than committing to an optimized jump.",
        "links": ["pickoff_move_jump_deception", "slide_step_tempo_disguise", "quick_pitch_timing_disruption"],
    },
    {
        "slug": "slide_step_tempo_disguise",
        "title": "Slide-Step Tempo Disguise",
        "summary": "Mixing a slide-step with a full leg-kick delivery prevents runners from reliably timing the release point, creating time-to-plate uncertainty that reduces stolen-base success even when attempt decisions are not deterred.",
        "stat_signature": "Time-to-plate variance between full-kick and slide-step above 0.18 seconds; caught-stealing share attributable to slide-step appearances above 35 %; stolen-base success rate against slide-step-mix pitchers below 68 %.",
        "mechanism": "The slide-step reduces time-to-plate by 0.10-0.15 seconds, shortening the catcher's pop-time requirement; when mixed with full-kick deliveries in unpredictable patterns, the runner cannot time release with enough confidence to gain the full jump advantage that slide-step recognition would otherwise provide.",
        "conditions": "Most valuable when the catcher's pop time is below 1.95 seconds, making the combined time-to-plate window prohibitive; less effective against power runners who clear the stolen-base window even on slide-step appearances.",
        "magnitude": "Pitchers who alternate slide-step and full-kick at rates above 30 % slide-step generate caught-stealing rates 8-12 points above single-tempo pitchers; time-to-plate variance of 0.20+ seconds is the threshold associated with meaningful suppression of attempt success.",
        "links": ["step_off_balk_threshold_play", "pickoff_move_jump_deception", "quick_pitch_timing_disruption"],
    },
    {
        "slug": "two_seam_four_seam_plane_split",
        "title": "Two-Seam Four-Seam Plane Split",
        "summary": "Two fastball variants sharing an early tunnel before late arm-side run or vertical ride divergence force a hitter to cover two distinct quadrants from an identical pre-pitch read, suppressing barrel rate on both.",
        "stat_signature": "Vertical-plus-horizontal movement split between two-seam and four-seam above 8 inches combined; barrel rate across the fastball pair below 7 %; hard-hit rate against both variants below 36 %.",
        "mechanism": "From identical release points and early trajectories, a ride-dominant four-seamer finishes at the top of the zone while a run-and-sink two-seamer finishes arm-side and low; the hitter cannot pre-commit to either quadrant, forcing a reactive contact attempt rather than a barrel-timed swing.",
        "conditions": "Most effective against hitters who segment pitch type by early flight line; requires genuine movement separation of at least 6 inches to force coverage compromise; command of both variants to opposite horizontal edges maximizes the quadrant spread.",
        "magnitude": "Pitchers with documented two-seam and four-seam plane splits suppress hard-hit rate 4-8 points below single-fastball-variant peers at equivalent velocity; the barrel-suppression effect compounds when paired with an above-average change-up that mirrors the two-seam early trajectory.",
        "links": ["pitch_tunneling_commit_point", "spin_axis_deception", "breaking_ball_shape_overlap", "release_point_consistency_disguise"],
    },
    {
        "slug": "spin_axis_deception",
        "title": "Spin-Axis Perception Deception",
        "summary": "Orienting seams and spin axis so a pitch breaks counter to the hitter's expectation based on typical pitch-type patterns; the mismatch between expected and actual break generates take-on-strike outcomes and soft contact.",
        "stat_signature": "Spin-to-movement efficiency gap above 15 inches of deviation from expected break for the axis used; take-on-strike rate on deceptive-axis pitches above 22 %; soft-contact rate on contact above 28 %.",
        "mechanism": "Hitters build pitch-type-to-break models from experience; a slider with an unusual vertical axis that produces more drop than side-break, or a cutter with gyro properties that produces straight carry rather than glove-side cut, forces a late break-classification error that misaligns the swing plane.",
        "conditions": "Most impactful on first or second exposure to an unusual seam orientation; recognition improves over multiple at-bats, so fresh opponents and short-sample encounters amplify the effect; attenuated after the hitter has seen 4+ at-bats against the deceptive pitch.",
        "magnitude": "Pitchers with documented counter-expectation break profiles generate called-strike rates 3-5 points above expected on those pitches; soft-contact rate premium on spin-axis-deceptive pitches is roughly 6-9 points versus conventionally shaped equivalents.",
        "links": ["breaking_ball_shape_overlap", "two_seam_four_seam_plane_split", "front_door_back_door_mirror", "pitch_tunneling_commit_point"],
    },
    {
        "slug": "eye_level_change_sequencing",
        "title": "Eye-Level Change Sequencing",
        "summary": "Sequencing a tunnel-matched high-zone pitch followed by a low-zone pitch disrupts the hitter's vertical tracking plane, elevating chase rate on the low pitch after the high pitch has established a top-of-zone reference.",
        "stat_signature": "Consecutive-pitch vertical-location swing above 18 inches in tunnel-matched pairs; chase rate on low-zone pitch following a high-zone pitch elevated 6-10 points versus isolated low-zone pitches; contact rate on the follow-up pitch depressed 5-8 points.",
        "mechanism": "Hitters anchor vertical tracking to the preceding pitch's arrival height; after a pitch above the belt, the visual system anticipates continuity; a pitch 18-24 inches lower on an identical early trajectory triggers a late downward tracking adjustment that arrives after the swing decision has been made.",
        "conditions": "Requires the two pitches to share an early tunnel to preserve deception; most effective with a high four-seamer followed by a low change-up or sinker; less effective when the preceding pitch was a breaking ball below the belt.",
        "magnitude": "High-low tunnel pairs generate chase rates on the secondary pitch roughly 8-12 points above the pitch's isolated chase rate; whiff rates on low-zone pitches following high-zone tunnel matches average 4-7 percentage points above the same pitch thrown in isolation.",
        "links": ["pitch_tunneling_commit_point", "fastball_changeup_arm_speed_mirror", "front_door_back_door_mirror", "breaking_ball_shape_overlap"],
    },
    {
        "slug": "front_door_back_door_mirror",
        "title": "Front-Door Back-Door Mirror",
        "summary": "A breaking pitch starting off the plate body-side before bending across the strike zone edge shares early trajectory with its mirror counterpart starting off the opposite edge, covering both edges from an identical early path.",
        "stat_signature": "Start-location overlap within 2 inches horizontally between front-door and back-door variants; called-strike rate on edge-bending pitches above 26 %; swing rate on first-strike front-door breaking balls above 18 %.",
        "mechanism": "Front-door pitches begin off the plate glove-side or arm-side, signaling ball to the hitter, before late break carries them across the edge; back-door pitches begin off the opposite edge before breaking back; identical early trajectory for opposite-edge versions forces coverage of the full plate width.",
        "conditions": "Requires genuine late-break magnitude above 5 inches to generate edge reach; most effective after establishing a straight-entry fastball on the same edge so the hitter pre-loads an outside pitch; attenuated when command is insufficient to reliably hit the edge after the break.",
        "magnitude": "Called-strike premium on well-executed front-door and back-door breaking balls is roughly 5-8 points above straight-entry equivalents; coverage of both edges from an overlapping start forces a swing-zone expansion of roughly 4-6 inches in hitter plate coverage.",
        "links": ["spin_axis_deception", "breaking_ball_shape_overlap", "eye_level_change_sequencing", "pitch_tunneling_commit_point"],
    },
    {
        "slug": "fake_to_third_throw_first",
        "title": "Fake-to-Third Pivot Deception",
        "summary": "Faking a throw to third base to freeze that runner before executing a real play at first exploits split-attention between two base threats, generating double-freeze events and suppressing lead distances.",
        "stat_signature": "Induced double-runner freeze frequency above 1 per 8 attempts; trail-runner advance suppression rate above 55 % on successful freezes; pickoff conversion at first following fake-to-third above 12 % of attempts.",
        "mechanism": "With runners on first and third, a convincing third-base throw-fake forces the third-base runner to hesitate and the first-base runner to pause, splitting defensive attention; the pivot to first catches the first-base runner mid-indecision, exploiting the cognitive lag of a simultaneous dual-base read.",
        "conditions": "Most effective in first-and-third situations with aggressive runners; requires convincing upper-body commitment to the third-base direction; attenuated when both runners have pre-committed to conservative leads that absorb the freeze cost.",
        "magnitude": "Successful fake-to-third pivot sequences generate pickoff opportunities at first at roughly 2-3 times the rate of standard pickoff attempts; the freeze effect suppresses advance-to-home on a passed ball by roughly 30-40 % in the subsequent plate appearance.",
        "links": ["pickoff_move_jump_deception", "step_off_balk_threshold_play", "first_to_third_decoy_field"],
    },
    {
        "slug": "first_to_third_decoy_field",
        "title": "Fielder Decoy on Advancing Runner",
        "summary": "A fielder simulating a non-arriving throw or relay alters a runner's read on whether to advance, inducing hesitation that converts into an out or holds a runner at a lower-value base position.",
        "stat_signature": "Induced runner hesitation time above 0.8 seconds on decoy movements; extra-out conversion on baserunning misjudgment above 15 % of decoy executions; third-base hold rate elevated 12-18 points in decoy-executed sequences.",
        "mechanism": "Runners tracking the ball field cues through the corner or relay position; a fielder who mimics catch-and-throw mechanics without possessing the ball forces the runner's decision into uncertainty, extending the hesitation window until the actual ball location resolves — often too late to advance aggressively.",
        "conditions": "Most effective on extra-base hits to shallow right or center where multiple relay options exist; requires coordination between at least two fielders to prevent the decoy fielder's empty hands from being detected; attenuated on deep, unambiguous extra-base hits where the ball is trackable throughout.",
        "magnitude": "Well-executed fielder decoys suppress third-base advance attempts by 10-15 percentage points; when runners commit to advance through a decoy, out-conversion rates of 20-25 % are observed — roughly double the rate on standard relay throws of comparable speed.",
        "links": ["fake_to_third_throw_first", "hidden_ball_trick_tag_setup", "step_off_balk_threshold_play"],
    },
    {
        "slug": "hidden_ball_trick_tag_setup",
        "title": "Hidden-Ball Tag Setup",
        "summary": "An infielder concealing possession of the ball after an apparent return to the pitcher exploits a runner stepping off the base to tag without warning, converting an assumed-safe base into an out.",
        "stat_signature": "Occurrence rate of 0.04-0.08 per game across MLB; lead-off-bag tag conversion when attempted above 60 %; runner-off-base frequency on return-to-play sequences above 25 % at first base.",
        "mechanism": "Runners relax base contact after observing the infielder mime returning the ball; the infielder retains possession and applies a tag during the relaxation window; the rarity of the play means no runner builds an active defensive model for it, preserving surprise value even across a career.",
        "conditions": "Requires pitcher to leave the mound area without the ball and umpire to confirm no balk; most executable at first and second base where runner habits of stepping off are most common; requires coordination without verbal confirmation that might alert the runner.",
        "magnitude": "Successful hidden-ball-trick executions convert a certain no-out state into an out at a 60-70 % rate once the tag attempt is made; the primary value is deterrence — runners who are aware of the pattern reduce secondary leads, shifting run-expectancy at the margin.",
        "links": ["first_to_third_decoy_field", "fake_to_third_throw_first", "step_off_balk_threshold_play"],
    },
    {
        "slug": "delivery_deception_low_visibility_slot",
        "title": "Low-Visibility Slot Deception",
        "summary": "A release angle and body screen that delay the hitter's ball pickup out of the hand; lower and more behind-the-hip release slots extend the occlusion window, reducing effective recognition time.",
        "stat_signature": "Estimated pickup-latency increase of 8-15 ms for sub-slot deliveries; early-count whiff rate elevated 4-7 points for low-three-quarter-to-sidearm pitchers versus over-the-top equivalents at the same velocity; first-pitch take-strike rate 3-5 points above average.",
        "mechanism": "A ball released from behind the hip or thigh travels across a background occluded by the pitcher's body for a longer arc; the hitter must pick up spin direction and trajectory from a later visual angle, compressing the recognition window and generating mis-timed swings or frozen called strikes.",
        "conditions": "Most effective on the first exposure to an unfamiliar arm slot; hitter adjustment occurs over 4-6 at-bats as the background cue model updates; amplified when paired with a high-extension release that further shortens remaining flight time after pickup.",
        "magnitude": "Slot-occlusion pitchers generate called-strike rates on first pitches roughly 4-6 points above over-the-top equivalents at equal velocity; the pickup-latency premium accounts for roughly 2-3 additional whiff opportunities per 100 pitches across the arsenal.",
        "links": ["perceived_velocity_extension", "release_point_consistency_disguise", "pitch_tunneling_commit_point", "quick_pitch_timing_disruption"],
    },
]
