"""Decision-quality intelligence concept nodes for NBA — person-free spec."""
from __future__ import annotations

SPORT: str = "NBA"
FAMILY: str = "DecisionQuality"

CONCEPTS: list[dict] = [
    {
        "slug": "shot_quality_discipline",
        "title": "Shot-Quality Discipline Index",
        "summary": "Captures the share of attempts taken from high-expected-value zones (rim, corner three, open catch-and-shoot) against contested long-twos, expressed as quantified shot-quality per attempt above league baseline.",
        "stat_signature": "Ratio of rim-plus-corner-three attempts to total field-goal attempts; high-discipline profiles sit above 0.55 on this share; eFG% from non-corner twos penalized ~4 pp below league eFG%.",
        "mechanism": "Shot selection drives the largest single-possession expected-value gap in basketball; a contested 18-foot two yields roughly 0.75 PPP versus 1.15–1.20 PPP at the rim or on an open corner three, so zone discipline compounds across a full possession set.",
        "conditions": "Discipline degrades under shot-clock pressure below six seconds and against aggressive hedge coverage that collapses rim paths; elevates when off-ball movement creates open catch-and-shoot opportunities.",
        "magnitude": "Large: moving a rotation from bottom-quartile to top-quartile shot-quality discipline associates with roughly 4–6 pts/100 offensive-rating improvement, the largest single structural lever in halfcourt offense.",
        "links": ["open_three_conversion_choice", "midrange_economy_tradeoff", "shot_clock_pressure_selection", "contested_finish_avoidance"],
    },
    {
        "slug": "open_three_conversion_choice",
        "title": "Open-Three Acceptance Tendency",
        "summary": "Measures willingness to launch when defender closeout distance exceeds the open threshold, quantified as the take-rate on wide-open above-the-break and corner looks relative to availability.",
        "stat_signature": "Wide-open three take-rate (defender 6+ ft away) relative to opportunities; league average is approximately 78–82% acceptance; low-acceptance profiles leave 0.25–0.35 PPP on the table per declined open look.",
        "mechanism": "Declining an open three forces a dribble-into-closeout sequence or a reset, both reducing expected possession value; defenders quickly learn to sag and deny driving lanes when acceptance rates fall below the threat threshold.",
        "conditions": "Acceptance tendency most consequential against zone and drop-coverage schemes that deliberately concede perimeter space; high-take profiles force defenses to close out, opening drive-and-kick chains.",
        "magnitude": "Moderate to large: a consistent high-take profile from range elevates floor spacing value by an estimated 1.5–2.5 pts/100 for the surrounding offense through gravitational kick-out effects.",
        "links": ["shot_quality_discipline", "catch_versus_dribble_decision", "extra_pass_threshold", "skip_pass_recognition"],
    },
    {
        "slug": "midrange_economy_tradeoff",
        "title": "Midrange Selection Economy",
        "summary": "Captures the discipline of declining long two-point pull-ups in favor of a drive or kick, measured as the long-two share of total shot diet and its expected-points cost per possession.",
        "stat_signature": "Long-two share above 18% of total FGA marks a high-cost profile; contested long-two yield averages 0.76–0.82 PPP versus 1.05–1.12 PPP for the average non-long-two alternative; net cost ~0.25 PPP per substituted shot.",
        "mechanism": "The long two occupies the lowest-leverage zone on the court — too far for high-percentage finishing, too close for three-point bonus; choosing it over a rim attempt or three forfeits expected value on nearly every possession.",
        "conditions": "Long-two frequency spikes against drop-coverage that cuts off the paint and against heavy drop-back schemes; disciplined rotations substitute drives, kick-outs, or pull-back threes in those defensive scenarios.",
        "magnitude": "Moderate: rotating from a high long-two diet to a low one correlates with roughly 2–3 pts/100 offensive-rating improvement, controlling for personnel quality.",
        "links": ["shot_quality_discipline", "pull_up_versus_pass_decision", "drive_kick_read_quality", "midrange_economy_tradeoff"],
    },
    {
        "slug": "drive_kick_read_quality",
        "title": "Drive-and-Kick Read Quality",
        "summary": "Quantifies the accuracy of reading help rotation on a paint drive, measured as the pass-out-to-open-shooter rate when two defenders commit versus forced contested finishes.",
        "stat_signature": "Two-man-help trigger rate of kick-out passes; elite read profiles complete the kick at 65–72% of two-help possessions; contested finish forced-shot rate below 25% when double-help triggers; open kick-out converts at ~42% from three.",
        "mechanism": "When help arrives, the math shifts decisively to the open perimeter shooter; the driver who completes the kick generates an expected value ~0.35 PPP above a forced finish; reading the coverage plane before the peak of the dribble maximises decision time.",
        "conditions": "Read quality degrades under fatigue late in games; elevates when the offensive system positions shooters on the weak side before the drive starts; critical against aggressive rotation defenses that hard-crash the paint.",
        "magnitude": "Large: offenses with top-quartile drive-kick read quality generate roughly 5–7 more open threes per 100 possessions, translating to 1.8–2.5 pts/100 offensive-rating advantage.",
        "links": ["pull_up_versus_pass_decision", "extra_pass_threshold", "skip_pass_recognition", "advantage_creation_read"],
    },
    {
        "slug": "pull_up_versus_pass_decision",
        "title": "Pull-Up Against Pass Choice",
        "summary": "Captures the option-read between a pull-up jumper off the dribble and an advantage pass, measured as expected-points delta between the chosen action and the best available teammate look.",
        "stat_signature": "Decision-value delta measured as PPP of chosen action minus PPP of foregone alternative; top-quartile decision-makers show mean positive delta of +0.08–0.12 PPP; bottom-quartile profiles average negative deltas of −0.10 to −0.15 PPP.",
        "mechanism": "The pull-up resolves immediately but closes teammate shot-creation chains; the advantage pass defers resolution but often yields a higher-quality downstream look; the calibration between these depends on the defender's recovery angle and the availability of open shooters.",
        "conditions": "Pull-up value rises in late-clock scenarios below five seconds and against switching defenses that close passing lanes; pass value dominates in early-clock halfcourt against help-and-recover schemes.",
        "magnitude": "Moderate: cumulative decision-value differences across a season approximate 2–4 pts/100 offensive-rating differential between high- and low-quality option-read profiles.",
        "links": ["midrange_economy_tradeoff", "drive_kick_read_quality", "shot_clock_pressure_selection", "pick_and_roll_option_tree"],
    },
    {
        "slug": "transition_decision_horizon",
        "title": "Transition Decision Horizon",
        "summary": "Measures the quality of the early-clock choice to attack in transition, pull back, or hit ahead, quantified as transition expected-points-per-possession against settle-into-halfcourt outcomes.",
        "stat_signature": "Transition PPP averages 1.10–1.18 league-wide; decisions to attack within three seconds of possession gain yield ~1.12 PPP; delayed transitions settled into halfcourt drop to 1.00–1.05 PPP; overpressed attacks (numbers disadvantage) yield ~0.88 PPP.",
        "mechanism": "Defensive transition recovery takes 3–4 seconds after a miss or turnover; the decision horizon is the window in which attacking yields a numbers advantage; extending beyond that window sacrifices the tempo-driven efficiency premium.",
        "conditions": "Horizon value peaks against slower-recovering defenses; collapses when the attacking team operates without a clear numbers advantage; varies by rim protection depth at the retreating end.",
        "magnitude": "Moderate: teams with disciplined horizon recognition generate roughly 2–3 additional uncontested transition looks per game, worth an estimated 1.5 pts/100 across the full game.",
        "links": ["early_offense_versus_set", "advantage_creation_read", "shot_quality_discipline", "pull_up_versus_pass_decision"],
    },
    {
        "slug": "extra_pass_threshold",
        "title": "Extra-Pass Conversion Threshold",
        "summary": "Captures the tendency to swing an above-average look into a great look, measured as the rate of declining a qualifying shot attempt to generate a higher shot-quality opportunity for a teammate.",
        "stat_signature": "Extra-pass rate on above-average shots (eFG threshold ~54%) relative to opportunity; high-threshold profiles swing at 28–35% of qualifying looks; possessions ending in extra-pass-generated shots show ~3.5 pp higher eFG% than baseline.",
        "mechanism": "An above-average look is better than the average possession outcome but may not be the best available option on that possession; the extra pass exploits residual defensive imbalance before recovery closes the window.",
        "conditions": "Extra-pass value is highest when the clock is above 10 seconds remaining and shooters are pre-positioned; degrades under time pressure, in clutch situations where resolution speed matters, and against defenses with fast rotational discipline.",
        "magnitude": "Small to moderate: extra-pass possessions yield roughly 0.05–0.08 PPP above the foregone shot's expected value; over a season this compounds to roughly 1.5–2 pts/100 offensive-rating improvement.",
        "links": ["drive_kick_read_quality", "skip_pass_recognition", "open_three_conversion_choice", "double_team_outlet_read"],
    },
    {
        "slug": "double_team_outlet_read",
        "title": "Double-Team Outlet Read",
        "summary": "Quantifies decision quality when trapped, measured as the rate of completing a pass to the open four-on-three advantage versus turnover or forced contested shot under the trap.",
        "stat_signature": "Trap-escape completion rate; elite post and pick-and-roll handler profiles complete the outlet at 70–78% of trap triggers; turnover-under-trap rate below 12%; four-on-three advantage possessions following clean outlet yield ~1.18–1.25 PPP.",
        "mechanism": "The double-team deliberately overloads one scoring threat to force a decision under contact and time pressure; the correct read instantly creates a numbers advantage on the perimeter; a delayed or poor read collapses the advantage as defenders recover.",
        "conditions": "Traps occur most frequently in the post against elite scorers and in early-clock pick-and-roll coverages; outlet quality degrades against fast-rotating help sides that sprint to passing lanes.",
        "magnitude": "Large in aggregate: a clean trap-escape rate of 75%+ generates roughly 0.30 PPP above a forced-possession alternative; teams that reliably escape traps deter the defensive scheme itself over the course of a series.",
        "links": ["pick_and_roll_option_tree", "post_decision_kickout", "extra_pass_threshold", "drive_kick_read_quality"],
    },
    {
        "slug": "pick_and_roll_option_tree",
        "title": "Pick-and-Roll Option-Tree Quality",
        "summary": "Captures reading the coverage to choose pocket pass, roll feed, skip, or own attack, measured as expected-points across the four primary reads weighted by coverage frequency.",
        "stat_signature": "Coverage-weighted PPP across reads; drop coverage inflates own-attack value to ~1.08 PPP; hard hedge inflates pocket-pass and roll-feed value to ~1.14 PPP; switch coverage elevates skip and isolation reads; top-quartile ball-handlers show coverage-weighted PPP above 1.10.",
        "mechanism": "Pick-and-roll coverages create structural vulnerabilities that vary by scheme; the handler who identifies coverage in the first dribble after the screen maximises the specific advantage the coverage concedes rather than defaulting to a single read.",
        "conditions": "Option-tree quality is most consequential against switching defenses that create mismatches requiring a shift from the primary read; degrades when off-ball spacing is insufficient to punish the skip.",
        "magnitude": "Large: coverage-read accuracy differential between top and bottom quartile handlers approximates 0.12–0.18 PPP per pick-and-roll possession, roughly 3–4 pts/100 offensive-rating over a game's possession volume.",
        "links": ["pull_up_versus_pass_decision", "double_team_outlet_read", "drive_kick_read_quality", "advantage_creation_read"],
    },
    {
        "slug": "post_decision_kickout",
        "title": "Post-Touch Kickout Discipline",
        "summary": "Measures the read on a post catch between sealing for a high-percentage finish and kicking to a relocated shooter when help digs, quantified as kickout-to-three rate against forced post turnaround.",
        "stat_signature": "Kickout-to-three rate when two defenders commit to the post catch; disciplined post players kick at 55–65% of double-team triggers; open-kickout three converts at ~40%; forced post-turnaround yields 0.72–0.80 PPP.",
        "mechanism": "Help rotation to the post creates a 4-on-3 advantage on the perimeter; the kickout exploits this; the seal-and-force play resolves quickly but accepts a lower expected value against set help defense.",
        "conditions": "Kickout discipline is highest value against aggressive digging defenses that send help before the catch; reduces in value against soft-drop schemes that concede the post move without committing a second defender.",
        "magnitude": "Moderate: kickout-versus-force selection accuracy associates with roughly 2–3 pts/100 offensive-rating differential for post-heavy halfcourt systems.",
        "links": ["double_team_outlet_read", "extra_pass_threshold", "skip_pass_recognition", "contested_finish_avoidance"],
    },
    {
        "slug": "shot_clock_pressure_selection",
        "title": "Late-Clock Selection Quality",
        "summary": "Captures shot-difficulty management as the shot clock expires, measured as the quantified shot-quality of attempts in the final four seconds relative to the forced-late baseline.",
        "stat_signature": "eFG% on shots with 0–4 seconds remaining versus 5–14 seconds; league average late-clock eFG% is approximately 38–42%, roughly 10 pp below mid-clock; high-quality decision-makers limit late-clock attempts to 6–8% of total FGA.",
        "mechanism": "Shot clock pressure compresses option processing time, forcing lower-quality looks; teams that consistently avoid clock-desperation shots through early-set running and quick-read offense preserve expected value across possessions.",
        "conditions": "Late-clock selection degrades most against switching defenses that deny early entries; improves for offenses with a reliable quick-hitter set and a designated late-clock handler.",
        "magnitude": "Moderate: reducing late-clock attempt share from 12% to 7% of total FGA associates with roughly 1.5–2 pts/100 offensive-rating improvement, reflecting the eFG% gap on clock-desperation attempts.",
        "links": ["shot_quality_discipline", "pull_up_versus_pass_decision", "transition_decision_horizon", "early_offense_versus_set"],
    },
    {
        "slug": "contested_finish_avoidance",
        "title": "Contested-Finish Avoidance",
        "summary": "Quantifies the discipline of declining heavily contested rim attempts in favor of a reset or a pass when rim protection is set, measured as the rate of attacking into set rim protection versus available outlets.",
        "stat_signature": "Contested layup rate when rim protector is within three feet of the basket; disciplined attackers convert at 38–45% in these situations versus uncontested at 62–68%; avoidance profiles reset or pass on 30–40% of contested-rim opportunities.",
        "mechanism": "A fully set rim protector reduces finishing probability dramatically; absorbing contact and attempting a contested layup accepts a near-50% effective miss rate when an outlet or pull-up reset yields higher expected value on the same possession.",
        "conditions": "Avoidance is highest-value against elite rim protectors positioned in drop coverage; reduces in value when the only alternative is a reset into a worse shot; clutch situations may override avoidance with the contact-drawing calculus.",
        "magnitude": "Small to moderate: consistent avoidance of heavily contested rim finishes saves roughly 0.12–0.18 PPP per avoided possession; over a game's rim-attack volume this approximates 0.8–1.5 pts/100.",
        "links": ["shot_quality_discipline", "rim_versus_floater_read", "drive_kick_read_quality", "post_decision_kickout"],
    },
    {
        "slug": "advantage_creation_read",
        "title": "Advantage-Read Conversion",
        "summary": "Captures whether a created numbers advantage (closeout overrun, rotation gap) is exploited optimally, measured as the share of advantage situations ending in a high-value shot versus a dribbled-out advantage.",
        "stat_signature": "Advantage-exploitation rate: share of identified advantage possessions (closeout from 6+ ft, rotation gap) ending in a shot above the 54% eFG threshold; top-quartile offenses convert 58–65% of identified advantages into qualifying looks versus 40–45% for bottom quartile.",
        "mechanism": "A created advantage has a finite time window before defenders recover; attacking instantly into the correct gap maximises the exploitation window; hesitation or the wrong read allows recovery and neutralises the created advantage.",
        "conditions": "Advantage windows shortest against defenses with disciplined rotation discipline and high closeout speed; longest against tired defenses in the fourth quarter and against slow-rotation zone schemes.",
        "magnitude": "Large: advantage-read conversion differential is one of the primary discriminators between elite and average offenses; top-quartile conversion rates associate with roughly 4–5 pts/100 above average in halfcourt.",
        "links": ["drive_kick_read_quality", "transition_decision_horizon", "pick_and_roll_option_tree", "skip_pass_recognition"],
    },
    {
        "slug": "skip_pass_recognition",
        "title": "Skip-Pass Recognition",
        "summary": "Measures recognition of weak-side overhelp to execute the cross-court skip, quantified as skip-pass-to-open-corner rate when help X-out lag creates the window.",
        "stat_signature": "Skip-pass rate when weak-side help overloads to the strong side; corner three conversion on skip passes averages 39–41% (above league corner average); skip-pass-generated open looks average 44% eFG+ due to higher proportion of non-rushed attempts.",
        "mechanism": "Help defense over-rotation to protect the paint leaves the weak-side corner shooter uncovered for 1–2 seconds; the skip pass bypasses intermediate defenders and arrives ahead of rotation recovery, converting a defensive overcommitment into a high-value shot.",
        "conditions": "Skip recognition most valuable against aggressive paint-protection schemes and hard hedges; loses value against defenses with a designated weak-side X-out responsibility who maintains corner coverage.",
        "magnitude": "Moderate: offenses that consistently execute the skip-pass read generate roughly 2–3 additional open corner looks per game, worth approximately 1.5 pts/100 at corner three conversion rates.",
        "links": ["drive_kick_read_quality", "extra_pass_threshold", "open_three_conversion_choice", "advantage_creation_read"],
    },
    {
        "slug": "turnover_economy_of_decision",
        "title": "Decision-Driven Turnover Economy",
        "summary": "Captures unforced decision errors (telegraphed pass, into-traffic dribble) as distinct from pressure-induced turnovers, measured as live-ball decision-turnover rate per touch versus pressure-induced turnover rate.",
        "stat_signature": "Decision turnover rate (unforced): league average approximately 7–9 per 100 touches; high-economy profiles below 5 per 100; forced turnover rate expected to run 3–5 per 100 regardless of decision quality; the ratio of unforced to forced below 1.0 marks elite economy.",
        "mechanism": "Decision turnovers reflect a mismatch between pass selection and defensive coverage — telegraphing into a zone, driving into set help, or dribbling out of bounds under light pressure; these are avoidable through pre-read coverage recognition before ball movement.",
        "conditions": "Decision turnover rates spike in high-pressure defensive schemes (full-court pressure, ball-denial) and late-clock situations; also elevate in transition when reads must be processed at speed.",
        "magnitude": "Large: reducing decision turnover rate from top-quartile (11+) to bottom-quartile (5 per 100 touches) translates directly to 4–5 additional possessions per game, worth 4–6 pts/100 at league-average offensive rating.",
        "links": ["pull_up_versus_pass_decision", "double_team_outlet_read", "pick_and_roll_option_tree", "interior_pass_timing"],
    },
    {
        "slug": "catch_versus_dribble_decision",
        "title": "Catch-Shoot Against Drive Decision",
        "summary": "Captures the immediate on-catch read between rising for an open shot and putting the ball on the floor, measured as the expected-points of the on-catch decision against the closeout angle and speed.",
        "stat_signature": "Catch-and-shoot eFG% on open catches averages 53–57%; drive-off-catch PPP on partial closeouts averages 1.08–1.14; on full-speed closeouts the shoot decision yields ~0.95 PPP versus drive at ~1.10 PPP; optimal decisions differ by closeout angle above or below 45 degrees.",
        "mechanism": "Closeout angle and speed determine the correct binary: a late or angled closeout leaves the catch-and-shoot open; a full-speed flat closeout removes the shot but opens the drive lane; reading closeout trajectory in the catch moment determines which option dominates.",
        "conditions": "Decision value highest against hard closeout defenses that sprint at the catch; in corner positions, the sideline restricts the drive option, shifting the calculus toward the shoot decision even on aggressive closeouts.",
        "magnitude": "Moderate: correct versus incorrect on-catch reads differ by approximately 0.10–0.18 PPP per possession; over 4–6 catch opportunities per game per shooter this accumulates to roughly 1.5–2.5 pts/100.",
        "links": ["open_three_conversion_choice", "shot_quality_discipline", "drive_kick_read_quality", "advantage_creation_read"],
    },
    {
        "slug": "interior_pass_timing",
        "title": "Interior Feed Timing Quality",
        "summary": "Measures the timing of feeding a sealing big or cutter before the help recovers, quantified as on-time-feed conversion rate versus late-feed turnover rate into recovered help.",
        "stat_signature": "On-time interior feed window approximately 0.8–1.2 seconds after the seal establishes; on-time feed conversion rate 58–65%; late-feed (>1.5 seconds) turnover rate 25–35% due to help recovery; on-time lob conversion at cut averages 68–72%.",
        "mechanism": "Help defense operates on a 1.0–1.5 second rotation clock; passing before that window closes delivers the ball ahead of the help; passing after it closes walks the ball into a reset defense with no positional advantage remaining.",
        "conditions": "Timing quality most critical in dribble-handoff and post-entry sequences where help rotation is predetermined; less critical in delay offenses where the cutter movement is unpredictable.",
        "magnitude": "Moderate: on-time interior feeds convert at 12–18 pp higher rate than late feeds; offenses with disciplined timing generate roughly 2–3 pts/100 offensive-rating advantage in paint-attack sequences.",
        "links": ["drive_kick_read_quality", "turnover_economy_of_decision", "post_decision_kickout", "pick_and_roll_option_tree"],
    },
    {
        "slug": "rim_versus_floater_read",
        "title": "Rim-Against-Floater Touch Read",
        "summary": "Quantifies the in-paint read between attacking the rim through contact and pulling the floater short of the shot-blocker, measured as conversion split by rim-protector proximity.",
        "stat_signature": "Rim-protector-within-two-feet: layup conversion drops to 42–48%, floater yields 40–44%; rim-protector beyond four feet: layup converts 62–68%, floater at 37–40%; optimal threshold proximity approximately three feet determines which option yields higher PPP.",
        "mechanism": "The floater arc clears the shot-blocker's reach but accepts a lower base conversion rate; attacking the rim generates contact and free-throw probability but absorbs the block threat; the proximity threshold determines when the floater's block-avoidance benefit outweighs its accuracy cost.",
        "conditions": "Read value sharpest against elite rim protectors with high block rates; floater correct read more important against centers positioned in drop coverage; collapses against smaller defenders where rim attacks dominate regardless of proximity.",
        "magnitude": "Small to moderate: correct proximity-read selection yields roughly 0.06–0.10 PPP above the alternative on each in-paint touch; over 8–12 in-paint touches per game this approximates 0.6–1.5 pts/100.",
        "links": ["contested_finish_avoidance", "shot_quality_discipline", "drive_kick_read_quality", "catch_versus_dribble_decision"],
    },
]
