"""scripts.platformkit.specs.defensiveschemes_mlb — MLB DefensiveSchemes concept nodes (person-free)."""
from __future__ import annotations

SPORT = "MLB"
FAMILY = "DefensiveSchemes"

CONCEPTS: list[dict] = [
    {"slug": "batted_ball_positioning_system", "title": "Batted-Ball Distribution Positioning System",
     "summary": "The data-driven process of aligning all four infielders and three outfielders to a hitter's spray-and-launch profile within shift-restriction rules, optimising out-probability on each batted-ball type as a coordinated system rather than a single named shift.",
     "stat_signature": "Out-probability-above-average above +4 points for the full defensive alignment; BABIP-allowed below .275 on pulled ground balls; spray-alignment rate above 70 % of plate appearances with distinct positioning from default.",
     "mechanism": "Batted-ball direction and distance are predictable from spray-angle and launch-angle distributions; pre-positioning reduces expected route distance to the mean landing zone, converting balls that a default alignment would misplay into outs without additional range.",
     "conditions": "Greatest value against hitters with spray-angle concentration above 65 % to one field or launch profiles that cluster in a narrow exit-velocity band; effect is modulated by pitch-plan coordination and surface speed.",
     "magnitude": "Alignment-optimised units suppress pull-side BABIP by 8-15 points post-rule relative to neutral alignment; out-probability gain of 3-6 percentage points on shaded balls; system-wide BABIP-against drops roughly 5-10 points for consistent deployers.",
     "links": ["infield_alignment_versus_pitch_plan", "double_play_depth_pivot_positioning", "no_doubles_outfield_alignment", "outfield_arm_run_deterrence_alignment", "corner_infield_depth_bunt_threat"]},

    {"slug": "cutoff_relay_structure", "title": "Cutoff and Relay Structure",
     "summary": "The coordinated chain from outfielder to cutoff to base that converts deep hits into outs or holds runners, covering lead-runner reads, trail-runner deterrence, and cutoff positioning angles.",
     "stat_signature": "Extra-base-advance suppression rate above 68 % on balls reaching the wall; runners-thrown-out on relay attempts above 28 % of relay opportunities; cutoff-catch-to-accurate-release time below 0.9 seconds for efficient relay men.",
     "mechanism": "Relay positioning shortens total throw distance so ball flight time falls inside the baserunner's round-trip time; a well-angled cutoff maintains throw-line momentum and removes seam-grip delay; lead-runner reads from the outfielder before the catch enable earlier cutoff commitment.",
     "conditions": "Most impactful in deep-gap alleys and corners where a single throw from the outfielder would require more than 300 feet; amplified in parks with fast artificial turf or in situations where a runner is already in motion on contact.",
     "magnitude": "Well-drilled relay systems reduce extra-base advancement by 10-18 percentage points on deep hits versus disorganised chains; assist-plus-deterrence rate 6-10 points above league average for units that invest in relay repetition.",
     "links": ["double_cut_long_relay_deep_alley", "outfield_arm_run_deterrence_alignment", "tag_up_sac_fly_outfield_positioning", "rundown_execution_system"]},

    {"slug": "bunt_defense_coverage", "title": "Bunt-Defense Coverage",
     "summary": "The pre-pitch assignment for sacrifice and drag bunts — corners crash, wheel rotation, and bag-coverage responsibilities — designed to take the lead out or concede a clean sacrifice at the right cost.",
     "stat_signature": "Lead-out conversion rate on sacrifice bunt attempts above 35 %; sacrifice-success-allowed rate below 72 % in lead-out situations; fielder-to-bag coverage gap below 90 feet on crash assignments.",
     "mechanism": "Crashing corners reduce fielder-to-ball time below the baserunner's first-step lead; rotation assigns the pitcher or charging corner to the bunt while the remaining corner covers first or third; the wheel play executes a pre-planned coverage swap that removes the lead runner.",
     "conditions": "Highest value with a fast runner on first or second when a sacrifice is conventional; the wheel is triggered by scouted bunt-tendency above 20 % in the situation; attenuated when the batter has below-average bunting execution rate.",
     "magnitude": "Aggressive bunt defense converts the lead out roughly 30-40 % of attempts in optimal wheel situations; sacrifice-success-allowed rate can be suppressed 10-15 points below league average with consistent coverage assignment.",
     "links": ["wheel_and_first_base_coverage", "first_and_third_defense", "corner_infield_depth_bunt_threat", "double_play_depth_pivot_positioning"]},

    {"slug": "first_and_third_defense", "title": "First-and-Third Defensive System",
     "summary": "The set-play menu for runners on the corners — look-back, cut-and-throw, fake-to-third, and concede-the-steal options — that defends the double-steal threat and manages run-scoring risk.",
     "stat_signature": "Run-scored-on-the-play rate below 22 % in first-and-third situations; lead-runner-out conversion rate above 18 % when the cut-and-throw is executed; stolen-base-attempt rate in the situation below 28 % against disciplined-read batteries.",
     "mechanism": "The battery and infield must signal a single response before pitch delivery; the cut-and-throw to the lead catcher checks the front runner while retaining throw options; fake-to-third freezes the lead runner long enough to retire the trail runner at second.",
     "conditions": "Most critical in one-run games with the go-ahead run at third and fewer than two outs; aggressive concede logic applies when the stolen-base attempt adds only a non-scoring runner; battery read speed and middle-infield communication are rate-limiting.",
     "magnitude": "Disciplined first-and-third systems reduce run-scored-on-the-play rate by 5-8 points relative to reactive approaches; lead-runner freeze via fake-to-third succeeds roughly 15-22 % of attempts when the ball-handling misdirection is clean.",
     "links": ["bunt_defense_coverage", "pickoff_hold_running_game_system", "rundown_execution_system", "double_play_depth_pivot_positioning"]},

    {"slug": "double_play_depth_pivot_positioning", "title": "Double-Play Depth and Pivot Positioning",
     "summary": "The middle-infield system of double-play depth, feed angles, and pivot footwork that maximises twin-killing probability with a runner on first and fewer than two outs.",
     "stat_signature": "Double-play conversion rate on grounders above 44 % with a runner on first; pivot-turn time at second base below 0.55 seconds from catch to release; double-play depth employed above 80 % of eligible situations.",
     "mechanism": "Shallower depth shortens the fielder-to-bag throw-line distance so the relay arrives before the sliding runner; pre-pivot footwork aligned to the feed direction reduces transfer time; the pivot fielder anticipates feed angle from the fielding position rather than reacting post-catch.",
     "conditions": "Engaged with a runner on first and zero or one out; modified depth when the batter has extreme groundball tendencies above 55 %; surface hardness and grass length alter turn time by up to 0.05 seconds.",
     "magnitude": "Optimal pivot positioning raises double-play conversion by 6-10 percentage points above reactive positioning; turn-time below 0.55 seconds is the threshold above which umpire safe-call rates drop sharply at second base.",
     "links": ["batted_ball_positioning_system", "infield_alignment_versus_pitch_plan", "bunt_defense_coverage", "first_and_third_defense"]},

    {"slug": "infield_in_corners_in_run_prevention", "title": "Infield-In and Corners-In Run Prevention",
     "summary": "The late-inning alignment pulling the infield in to cut the lead run at the plate, accepting elevated BABIP in exchange for direct run-prevention on batted balls.",
     "stat_signature": "Run-saved-at-plate rate above 28 % when infield is drawn in; BABIP inflation accepted of 35-50 points above normal depth; activation rate above 80 % in tie/one-run games with runner on third and fewer than two outs in the seventh inning or later.",
     "mechanism": "A fielder at normal depth cannot make a play at the plate on most ground balls; drawn-in depth compresses the throw distance so the force or tag is possible on average-speed grounders; the tradeoff accepts single conversion on balls that would have been outs.",
     "conditions": "Deployed exclusively in close late-inning situations where one run is the decisive margin; reversed immediately after the play resolves to limit extended BABIP exposure; modulated by the batter's ground-ball rate and the pitcher's ground-ball tendency.",
     "magnitude": "Run-at-the-plate saved on roughly 25-32 % of drawn-in activations; BABIP inflation of 40-50 points is the accepted cost; net run-prevention value positive only when the deployment context is correctly filtered to high-leverage close games.",
     "links": ["batted_ball_positioning_system", "double_play_depth_pivot_positioning", "defensive_substitution_glove_system", "no_doubles_outfield_alignment"]},

    {"slug": "no_doubles_outfield_alignment", "title": "No-Doubles Outfield Alignment",
     "summary": "The deep-and-guard-the-lines outfield system that concedes singles to prevent extra-base hits late in close games, protecting against the gap-gap damage that extends innings.",
     "stat_signature": "Extra-base-hit suppression rate on fly balls and line drives above 12 points relative to standard depth; single-conversion cost accepted at 6-10 percentage points higher catch rate on shorter flies; deployment above 75 % of late-inning close-game situations.",
     "mechanism": "Deeper outfield alignment intercepts balls in the gaps and along the lines that otherwise land for doubles or triples; the gap between single-distance coverage and line-drive range is accepted as a controlled tradeoff when the extra-base threat exceeds the single-scoring risk.",
     "conditions": "Activated in the seventh inning or later with a one-or-two-run lead and the tying run on base or at the plate; adjusted for park dimensions where gap distance determines break-even depth; less appropriate against pull-heavy hitters who rarely hit true gappers.",
     "magnitude": "Extra-base-hit rate suppressed by 8-14 points on deep fly balls in aligned outfields; single rate increases by 5-8 points as shorter balls fall in; net run-prevention value positive in roughly 60-65 % of contextually appropriate deployments.",
     "links": ["outfield_arm_run_deterrence_alignment", "tag_up_sac_fly_outfield_positioning", "infield_in_corners_in_run_prevention", "defensive_substitution_glove_system", "batted_ball_positioning_system"]},

    {"slug": "pickoff_hold_running_game_system", "title": "Pickoff and Hold Running-Game System",
     "summary": "The battery-plus-infield system of pickoff moves, varied looks, holds, and disengagement budgeting that suppresses baserunner leads and deters stolen-base attempts within pitch-clock and disengagement-limit rules.",
     "stat_signature": "Pickoff rate above 1.2 per nine innings; average lead distance below 12.5 feet against elite hold units; stolen-base attempt deterrence rate above 15 % compared with baseline lineups; disengagement usage averaging 1.6 per plate appearance in running situations.",
     "mechanism": "Varied look-timing and unpredictable first-move timing raise the cognitive cost of timing the pitcher; within the two-disengagement limit, strategic sequencing preserves at least one move for the optimal moment; pickoff throws near the base force the runner to dive, resetting to a shorter secondary lead.",
     "conditions": "Most critical against runners with success rates above 78 % and secondary leads above 13 feet; amplified in hit-and-run counts or when the batter is also a running threat; attenuated when the pitcher's first-move time to the plate exceeds 1.35 seconds.",
     "magnitude": "Shortened lead of 1.0-1.5 feet reduces stolen-base success rate by 5-8 percentage points; elite hold systems reduce attempt rate by 12-18 % versus permissive batteries; the break-even stolen-base success rate rises from 70 % to above 76 % against top hold units.",
     "links": ["first_and_third_defense", "rundown_execution_system", "catcher_blocking_dirt_ball_defense", "passed_ball_third_strike_coverage"]},

    {"slug": "rundown_execution_system", "title": "Rundown Execution System",
     "summary": "The coordinated run-down that finishes a trapped baserunner cleanly — running the runner back, minimising throws, and converging two fielders for the tag — to avoid extra-base advancement on misfires.",
     "stat_signature": "Rundown out-conversion rate above 88 %; average throws per rundown below 2.2; trail-runner advancement-on-rundown rate below 12 % in multi-runner situations.",
     "mechanism": "Running the trapped runner back toward the origin base allows the fielder to chase and compress without committing; the two-fielder convergence limits throws to the minimum required; each additional throw increases the probability of a misfire that advances trail runners.",
     "conditions": "Executed whenever a runner is caught between bases; more complex with multiple runners where trail-runner reads must be taken before the final tag; surface speed and park foul-territory depth affect throw-line options.",
     "magnitude": "Units averaging below 2.0 throws convert rundowns above 91 % and hold trail runners in place above 90 % of attempts; each additional throw above 2.5 per rundown reduces out-conversion by approximately 4-6 percentage points.",
     "links": ["first_and_third_defense", "pickoff_hold_running_game_system", "cutoff_relay_structure", "wheel_and_first_base_coverage"]},

    {"slug": "wheel_and_first_base_coverage", "title": "Wheel Play and Bag Coverage",
     "summary": "The rotation system determining who covers third on a wheel bunt play and who covers first on a 3-1 putout or slow-roller, eliminating bag-coverage gaps under bunt or drawn-in threat.",
     "stat_signature": "Lead-out conversion on wheel plays above 30 %; coverage-error rate on first-base bag exchanges below 4 % on pitcher-fielded bunts; wheel deployment rate above 55 % when a bunt-capable hitter faces a sacrifice situation.",
     "mechanism": "Pre-pitch assignment removes the real-time decision that causes collisions or vacated bags; the third-base coverage assignment (pitcher versus shortstop) is triggered by the first-base fielder's crash read; first-base bag coverage by the second baseman must be timed to arrive before the pitcher's relay.",
     "conditions": "Triggered by scouted bunt-tendency and game-state; modified when the first baseman is the better fielder for a charging read; most critical with a fast runner on first where a missed coverage means a safe lead runner.",
     "magnitude": "Coverage-error reduction of 4-6 points above teams without pre-assigned rotation; lead-out conversion rate on wheel plays 10-15 percentage points above reactive bunt defense; bag-exchange errors on first base reduced by roughly 40 % with pre-assigned coverage.",
     "links": ["bunt_defense_coverage", "corner_infield_depth_bunt_threat", "rundown_execution_system", "passed_ball_third_strike_coverage"]},

    {"slug": "tag_up_sac_fly_outfield_positioning", "title": "Tag-Up and Sacrifice-Fly Outfield Positioning",
     "summary": "Outfield depth and pre-catch footwork positioned to deter or retire tagging runners on fly balls with a runner on third, converting arm strength into run prevention on sac-fly attempts.",
     "stat_signature": "Tag-up run-conversion rate on fly balls below 78 % against aligned outfields; outfield-assist rate at the plate on sac-fly attempts above 6 per 150 games; pre-catch crow-hop initiation rate above 65 % on catchable fly balls with runner on third.",
     "mechanism": "A crow-hop transfer shortens total throw-to-plate time by 0.15-0.20 seconds; pre-positioning with a running start toward the infield at catch removes route distance from the throw calculation; the deterrence effect reduces tagging attempts by runners who track outfielder distance from the base.",
     "conditions": "Most impactful against slow-to-average runners who are vulnerable to throws below 3.8 seconds from catch to plate; amplified in parks with shallow warning tracks; attenuated when the outfielder is deep and the arm strength does not offset distance.",
     "magnitude": "Proper tag-up positioning with crow-hop technique generates an assist or deterrence on roughly 20-25 % of eligible fly balls with runner on third; tag-up run conversion drops 6-10 percentage points below neutral positioning for elite arm-and-position combinations.",
     "links": ["no_doubles_outfield_alignment", "outfield_arm_run_deterrence_alignment", "cutoff_relay_structure", "infield_in_corners_in_run_prevention"]},

    {"slug": "catcher_blocking_dirt_ball_defense", "title": "Catcher Blocking and Dirt-Ball Defense",
     "summary": "The receiving system for keeping pitches in the dirt in front of the plate to prevent wild-pitch and passed-ball runner advancement, complementing breaking-ball-heavy attack plans.",
     "stat_signature": "Block rate on bounced pitches above 89 %; runner-advance-per-bounced-pitch below 0.11; balls-in-dirt advancement-allowed rate below 8 % in situations with runners in scoring position.",
     "mechanism": "Dropping to the blocking stance and angling the body to deflect the ball to the fair-ground zone in front of the plate keeps the ball within range for a recovery throw; a torso seal that prevents the ball from rebounding past the catcher eliminates the advancement path entirely.",
     "conditions": "Most critical with runners on base when the pitch plan calls for a below-zone breaking ball or split-finger pitch; amplified in high-count situations where the pitcher elevates bounced-pitch probability; fast artificial turf increases ball rebound distance and raises the blocking skill threshold.",
     "magnitude": "Elite blockers reduce runner-advance-per-bounced-pitch by 0.04-0.07 below league average; block rate above 92 % is associated with approximately 5-8 fewer bases allowed per 162 games compared with average receivers.",
     "links": ["pickoff_hold_running_game_system", "passed_ball_third_strike_coverage", "first_and_third_defense"]},

    {"slug": "defensive_substitution_glove_system", "title": "Late-Inning Defensive-Substitution System",
     "summary": "The roster framework for swapping in superior gloves and arms late in a lead to upgrade run prevention at the cost of offensive depth, selecting the substitution timing and position to maximise defensive-runs-saved per inning.",
     "stat_signature": "Defensive-runs-saved upgrade of +1.5 to +3.5 per sub per 27 outs remaining; outs-converted-above-average from the substituted alignment above +2 per 100 balls in play; substitution entry inning averaging 7.2 or later in close-lead games.",
     "mechanism": "A late-inning glove upgrade repositions range and arm strength into the game at the moment when each out carries the highest win-probability weight; the offensive cost of replacing a batting slot is acceptable when the team already holds a lead and the defensive improvement is measurable.",
     "conditions": "Deployed in the seventh inning or later with a one-to-three-run lead; priority positions for upgrade are corner outfield and third base, which show the widest gap between offensive and defensive specialist quality; attenuated when the offensive slot in question is the lineup's run-prevention anchor.",
     "magnitude": "Per-substitution run-prevention upgrade of 0.15-0.35 expected runs per game for a high-gap position upgrade; over a full season, systematic defensive substitution is worth 3-7 runs above a static starting alignment, concentrated in close late-game contexts.",
     "links": ["no_doubles_outfield_alignment", "infield_in_corners_in_run_prevention", "outfield_arm_run_deterrence_alignment", "batted_ball_positioning_system"]},

    {"slug": "double_cut_long_relay_deep_alley", "title": "Double-Cut Long-Relay for Deep Alleys",
     "summary": "The two-relay-man system on balls to the deepest gaps and corners that shortens individual throw distance, keeps throw-line angles manageable, and deters trail-runner advancement on a potential triple.",
     "stat_signature": "Triple-suppression rate on balls reaching the warning track above 42 % with double-cut in operation; lead-runner-thrown-out rate on deep-alley relays above 12 %; total relay-to-target time below 4.8 seconds from outfielder catch to receiving base.",
     "mechanism": "A single 300-foot outfield throw decays sharply in accuracy and velocity; splitting the throw into two segments of 150-160 feet preserves throw-line velocity and allows each relay man to adjust for bad hops; the trail relay man also serves as a deterrent on the trailing runner.",
     "conditions": "Deployed on balls to the deepest gaps, the left-centre triangle, or along the line past the outfielder's range; most critical in parks with deep power alleys; activated when the outfielder's arm strength is insufficient for a direct throw to the intended base.",
     "magnitude": "Double-cut systems reduce triple rate on warning-track balls by 8-12 percentage points versus a single-relay structure; total relay time decreases by 0.4-0.6 seconds over a single fielder throw-and-catch sequence; trail-runner advancement held below 30 % on plays that would otherwise allow multi-base gains.",
     "links": ["cutoff_relay_structure", "outfield_arm_run_deterrence_alignment", "no_doubles_outfield_alignment", "rundown_execution_system"]},

    {"slug": "outfield_arm_run_deterrence_alignment", "title": "Outfield-Arm Run-Deterrence Alignment",
     "summary": "Positioning and pre-catch footwork that convert outfield arm strength into baserunner deterrence on advancement attempts, measured through both direct assists and discouraged-advance events.",
     "stat_signature": "Hold-rate on would-be advancers above 72 % for strong-arm alignments; assists-plus-deterred-advances per 100 opportunities above 14; pre-catch running start usage above 60 % on catchable balls with runners in motion.",
     "mechanism": "A runner factoring in the outfielder's arm strength, position, and catch timing stops at the previous base when the run-scoring probability is below the break-even threshold; outfielder positioning shallower than neutral increases perceived arm threat without sacrificing meaningful fly-ball coverage.",
     "conditions": "Most impactful on tag-up and single-to-advance situations involving average-speed runners; amplified when the outfielder's arm is publicly documented and recognised through recent game history; attenuated on balls to deep alleys or with elite-speed runners who push the time threshold.",
     "magnitude": "Arms in the top quartile deter advances on roughly 15-22 % of additional opportunities relative to below-average arms; deterrence value converts to approximately 8-12 runs above average per season at positions with high exposure to advancement decisions.",
     "links": ["tag_up_sac_fly_outfield_positioning", "cutoff_relay_structure", "no_doubles_outfield_alignment", "double_cut_long_relay_deep_alley"]},

    {"slug": "corner_infield_depth_bunt_threat", "title": "Corner-Infield Depth Against Bunt Threat",
     "summary": "The pre-pitch corner-infield depth-versus-bunt-coverage tradeoff against bunt-capable hitters in run-scoring situations, balancing crash readiness against the range cost on swings-away.",
     "stat_signature": "Bunt-attempt deterrence rate above 18 % when corners crash compared with standard depth; range-coverage cost on swings-away measured by additional BABIP of 12-18 points on grounders to the vacated corner; activation rate above 60 % against hitters with bunt-tendency above 15 %.",
     "mechanism": "A crashing corner reduces fielder-to-ball time on a laid-down bunt to below 2.0 seconds; the hitter recognising the crash may swing away into the vacated zone, so the depth decision is a mixed-strategy equilibrium with the batter; scouting tendencies and count sharpen the expected-value read.",
     "conditions": "Engaged primarily in sacrifice-bunt counts with runners on first and second or first only; abandoned in two-strike counts where the bunt risk drops sharply; surface speed and batter's bunt execution rate are the primary calibration inputs.",
     "magnitude": "Crashing corners take the lead out on roughly 30-38 % of successful bunt executions; the swing-away BABIP cost averages 14 points on the vacated zone; net expected-run impact is positive when scouted bunt probability exceeds approximately 22 % in the situation.",
     "links": ["bunt_defense_coverage", "wheel_and_first_base_coverage", "batted_ball_positioning_system", "double_play_depth_pivot_positioning"]},

    {"slug": "infield_alignment_versus_pitch_plan", "title": "Defense-to-Pitch-Plan Coordination",
     "summary": "The synchronisation of fielder positioning with the intended contact profile of the pitch sequence — ground-ball plan, pull-induction plan — so alignment matches expected batted-ball direction before the pitch is thrown.",
     "stat_signature": "Alignment-matched out rate above 52 % when positioning agrees with induced contact type; BABIP reduction of 8-14 points when pitch-plan and defensive alignment are coordinated relative to misaligned plate appearances.",
     "mechanism": "A sinker-heavy at-bat plan induces ground balls at a predictable rate; if the fielders are pre-positioned for a ground-ball profile while the pitcher executes that plan, the expected landing zone matches the coverage zone; misalignment wastes the positioning premium when the actual batted ball diverges from the assumed plane.",
     "conditions": "Requires pre-game or in-game communication between pitching staff and defensive alignment coordinators; most impactful against hitters with strong contact-type tendencies across pitch types; attenuated when the at-bat plan changes mid-sequence based on count development.",
     "magnitude": "Coordinated pitch-and-align systems achieve BABIP-against 8-12 points below systems with independent pitch and defensive planning; out-probability uplift on ground balls of 3-5 percentage points when alignment correctly anticipates sinker-induced contact direction.",
     "links": ["batted_ball_positioning_system", "double_play_depth_pivot_positioning", "corner_infield_depth_bunt_threat", "no_doubles_outfield_alignment"]},

    {"slug": "passed_ball_third_strike_coverage", "title": "Dropped-Third-Strike and Backstop Coverage",
     "summary": "The catcher-plus-first-base coverage system for blocked or dropped third strikes that prevents the batter reaching and runners from advancing on uncaught third-strike chaos.",
     "stat_signature": "Dropped-third-strike out-conversion rate above 85 %; runner-advance rate on uncaught strike-three pitches below 10 %; catcher recovery-and-throw time on dirt balls below 2.0 seconds to first base.",
     "mechanism": "A dropped third strike with first base unoccupied or two outs requires the catcher to recover the ball and throw to first within the runner's sprint time; slow recovery or miscommunication with the first baseman allows the batter to reach safely; runner advancement on the chaos is eliminated when the first baseman remains at the bag and the catcher prioritises recovery.",
     "conditions": "Most critical in two-strike counts with breaking-ball-heavy pitching plans that elevate bounced-pitch probability; amplified with slow-running batters where the out-conversion window is wider; requires clear battery communication pre-pitch on coverage assignments.",
     "magnitude": "Elite dropped-third-strike conversion units prevent 4-8 additional baserunners per 162 games versus below-average recovery; runner-advance rate on missed third strikes reduced by 3-5 points with pre-assigned first-base coverage protocols.",
     "links": ["catcher_blocking_dirt_ball_defense", "pickoff_hold_running_game_system", "wheel_and_first_base_coverage"]},
]
