"""Tennis DisciplineControl spec — unforced errors, double faults, focus lapses,
and point-discipline concepts. Person-free, descriptive only; no edge/ROI/pick claims.
"""
from __future__ import annotations

SPORT = "Tennis"
FAMILY = "DisciplineControl"

CONCEPTS: list[dict] = [
    {
        "slug": "double_fault_pressure_propensity",
        "title": "Double-Fault Propensity Under Pressure",
        "summary": "Elevated double-fault rate on second serve during break-point situations versus baseline second-serve fault rate.",
        "stat_signature": "Baseline second-serve double-fault rate 3-5%; break-point double-fault rate 7-12% in susceptible profiles; ratio above 2.0x flags a structural pressure leak.",
        "mechanism": "High arousal compresses swing amplitude and accelerates the service motion, increasing spin-rate variance on kick or slice; narrowed net margin converts small mechanics deviations into faults.",
        "conditions": "Most pronounced at deuce-game junctures against heavy returners; also elevated after dropping the first set when cumulative tension enters the service routine.",
        "magnitude": "Profiles with break-point double-fault rates above 10% yield roughly 0.4-0.6 extra service breaks per set compared with baseline.",
        "links": ["second_serve_risk_discipline", "tiebreak_error_spike", "deuce_game_error_exposure", "break_point_error_leakage"],
    },
    {
        "slug": "unforced_error_rate_neutral_rally",
        "title": "Unforced-Error Rate on Neutral-Ball Rally",
        "summary": "Groundstroke errors committed when neither player holds a positional advantage, isolating execution lapses from pressure-forced errors.",
        "stat_signature": "Neutral-ball unforced error rate below 15% is controlled; above 22% signals rally discipline problems; errors-per-rally above 0.30 on mid-depth central balls flag structural inconsistency.",
        "mechanism": "Errors on neutral balls reflect targeting over-ambition or footwork timing deficits; they concede points that patient rally construction would have kept open.",
        "conditions": "More visible in slow-surface extended exchanges against grinders offering neutral pace; diminishes against pace-heavy hitters who impose forced-error conditions.",
        "magnitude": "Profiles with neutral-ball error rates above 20% concede 3-5 extra points per set; a 5-percentage-point reduction corresponds to roughly 1.5-2 fewer errors per set.",
        "links": ["rally_length_error_curve", "shot_selection_discipline_on_the_run", "over_aggression_error_tax", "footwork_lapse_error"],
    },
    {
        "slug": "second_serve_risk_discipline",
        "title": "Second-Serve Risk Discipline",
        "summary": "Whether a server maintains consistent spin and target depth on the second serve, avoiding both risk-inflating flat deliveries and defensive pushes that gift easy attacks.",
        "stat_signature": "Second-serve in-percentage below 86% with double-fault rate above 5% indicates insufficient margin; second-serve pace above 155 km/h on flat deliveries correlates with double-fault spikes above 8%.",
        "mechanism": "A second serve must balance net clearance against return-ball quality; flat serves reduce spin-generated margin and spike fault probability under fatigue; ultra-defensive slices open the return window.",
        "conditions": "Risk rises against heavy returners who punish defensive pushes; also elevated late in sets when muscle fatigue degrades spin consistency.",
        "magnitude": "Each percentage-point rise in double-fault rate on the second serve costs roughly 0.7 service points per set; poor second-serve risk discipline drives service-game loss rates 1.3-1.8x above baseline.",
        "links": ["double_fault_pressure_propensity", "energy_management_lapse_late_set", "tiebreak_error_spike", "break_point_error_leakage"],
    },
    {
        "slug": "over_aggression_error_tax",
        "title": "Over-Aggression Error Tax",
        "summary": "Winners-to-unforced-error ratio on high-risk shot attempts, capturing whether attacking intent yields a net positive or a net negative on balance.",
        "stat_signature": "Winners-to-unforced-error ratio below 1.0 on approach shots and down-the-line attempts signals error-tax regime; ratio below 0.7 on cross-court moonball overruns indicates chronic over-aggression.",
        "mechanism": "Targeting lines with insufficient rally control or from off-balance positions increases contact-point variance; the marginal winner gain is offset by a larger error penalty when margin-to-line is too thin.",
        "conditions": "Most visible against defensive baseliners who extend rallies and invite impatient strikes; also emerges on set-point occasions where tactical tightening inflates error rates.",
        "magnitude": "Profiles in the bottom quartile of winners-to-error ratio concede an estimated 4-7 net points per set; shifting the ratio from 0.8 to 1.2 corresponds to roughly 2-3 fewer net-lost points.",
        "links": ["unforced_error_rate_neutral_rally", "shot_selection_discipline_on_the_run", "first_strike_over_commit_error", "momentum_swing_error_cascade"],
    },
    {
        "slug": "net_approach_error_rate",
        "title": "Net-Approach Execution Error Rate",
        "summary": "Unforced errors on the approach shot and first volley during net-transition sequences, distinguishing self-inflicted mis-executions from passing-shot losses.",
        "stat_signature": "Approach-shot unforced error above 12% of net-approach sequences flags poor execution; volley error rate above 8% on first volleys indicates depth or mis-hit frequency.",
        "mechanism": "Approaching on a ball that is too high or mid-court leaves the volleyer exposed; mis-hit volleys from contact below the tape produce poor depth and invite easy passing lanes.",
        "conditions": "Error rate rises against heavy topspin baseliners generating high-bouncing returns; also elevated on faster surfaces where the approach window is compressed and timing is critical.",
        "magnitude": "Profiles above 12% approach-error rate concede roughly 1.5-2 net points per set from this source; successful net transition requires both a quality approach and sound first-volley execution.",
        "links": ["over_aggression_error_tax", "drop_shot_misexecution_risk", "shot_selection_discipline_on_the_run", "footwork_lapse_error"],
    },
    {
        "slug": "break_point_error_leakage",
        "title": "Break-Point Error Leakage",
        "summary": "Disproportionate rise in unforced errors and double faults on break-point occasions, quantifying how discipline erodes under the highest service-game pressure.",
        "stat_signature": "Unforced error rate on break-point rallies elevated 1.5-2.5x above non-break-point baseline signals pressure leakage; double faults on break points above 8% is a persistent susceptible-profile pattern.",
        "mechanism": "Break-point awareness shifts attention from cue-tracking to outcome-awareness, degrading groundstroke automation and serve mechanics simultaneously.",
        "conditions": "Most pronounced in the deciding set when cumulative fatigue interacts with pressure arousal; also elevated against aggressive returners who apply rapid-fire pace to compress decision time.",
        "magnitude": "Profiles with break-point error leakage at 2x baseline convert fewer service games; estimated 0.3-0.5 additional service breaks per set attributed to pure error leakage under pressure.",
        "links": ["double_fault_pressure_propensity", "tiebreak_error_spike", "deuce_game_error_exposure", "momentum_swing_error_cascade"],
    },
    {
        "slug": "tiebreak_error_spike",
        "title": "Tiebreak Unforced-Error Spike",
        "summary": "Increase in unforced errors and double faults during tiebreaks compared with the set baseline, isolating discipline collapse under maximum compact-scoring pressure.",
        "stat_signature": "Tiebreak unforced error rate above 25% of points played indicates a significant spike; mini-break gifted via error above 1.5 per tiebreak is a chronic pattern; double-fault probability above 10% in tiebreak service points is elevated.",
        "mechanism": "Every point in a tiebreak carries equal weight; the inability to tolerate uniform criticality spikes arousal and degrades the motor automation of groundstroke paths and serve targets.",
        "conditions": "Spike is larger when the tiebreak follows a prolonged set with multiple breaks; also amplified against opponents who play aggressively from a mini-lead.",
        "magnitude": "Profiles with tiebreak error spikes above 1.5 per tiebreak concede mini-breaks from self-inflicted errors at twice the rate of disciplined profiles.",
        "links": ["break_point_error_leakage", "double_fault_pressure_propensity", "deuce_game_error_exposure", "second_serve_risk_discipline"],
    },
    {
        "slug": "return_error_giveaway",
        "title": "Return-of-Serve Error Giveaway",
        "summary": "Unforced errors on return — shanks, net returns, wide groundstrokes — that gift free points on the opponent's serve without any serving pressure causing the miss.",
        "stat_signature": "Return error rate above 18% on second-serve returns indicates poor return discipline; return errors per game above 1.8 inflates opponent hold percentage significantly.",
        "mechanism": "Attempting aggressive return angles on deep serves without sufficient contact-point depth produces errors; early or late take-back timing on fast first serves collapses racket-face control.",
        "conditions": "Most frequent against heavy-kick second serves and on wide slice deliveries that push the returner off-balance; also elevated when the returner attempts to dictate rather than neutralize from defensive width.",
        "magnitude": "Each additional return error shifts break-point conversion rate down roughly 3-5%; profiles above 20% second-serve return-error rates win fewer break points despite similar approach aggression.",
        "links": ["footwork_lapse_error", "unforced_error_rate_neutral_rally", "shot_selection_discipline_on_the_run", "over_aggression_error_tax"],
    },
    {
        "slug": "rally_length_error_curve",
        "title": "Rally-Length Unforced-Error Curve",
        "summary": "How a player's unforced-error rate changes as rallies extend, identifying whether the profile deteriorates, improves, or holds steady in extended exchanges.",
        "stat_signature": "A rising error curve — error rate in 9-plus shot rallies above 24% versus 12% in 1-4 shot rallies — flags endurance-based discipline collapse; a falling curve signals grinder-type resilience.",
        "mechanism": "Extended rallies impose cumulative physical demand that degrades footwork quality and contact-point precision; players relying on first-strike aggression see error rates climb as their natural pattern is neutralized.",
        "conditions": "Rising error curves are most exposed against clay-surface defensive baseliners who deliberately neutralize aggression and force 12-plus shot exchanges.",
        "magnitude": "Profiles with a 10-percentage-point error increase from short to long rallies concede roughly 2-3 extra points per set in extended exchange situations.",
        "links": ["unforced_error_rate_neutral_rally", "energy_management_lapse_late_set", "surface_induced_error_discipline", "footwork_lapse_error"],
    },
    {
        "slug": "footwork_lapse_error",
        "title": "Footwork-Lapse Groundstroke Error",
        "summary": "Errors attributable to poor positioning and late split-step recovery, where contact is too close to the body or too wide to allow reliable racket-face control.",
        "stat_signature": "Errors from wide-ball contact above 15% of groundstroke errors indicates a structural footwork deficit; late-split-step error attribution above 20% identifies the movement root cause.",
        "mechanism": "A late split-step forces contact at an off-balance position; the wrist and forearm compensate for the body's absence, reducing contact consistency and elevating miss rate.",
        "conditions": "Most visible against heavy topspin that accelerates sharply off the bounce; also elevated against wide-angled slices that drag the player beyond recovery range.",
        "magnitude": "Footwork-driven errors typically represent 15-25% of total unforced errors; profiles reducing late split-step frequency by half show a 4-6 percentage-point improvement in overall error rate.",
        "links": ["shot_selection_discipline_on_the_run", "return_error_giveaway", "unforced_error_rate_neutral_rally", "rally_length_error_curve"],
    },
    {
        "slug": "shot_selection_discipline_on_the_run",
        "title": "Shot-Selection Discipline on the Run",
        "summary": "Whether players choose conservative high-margin targets when stretched or pulled short, versus attempting low-margin winners from compromised positions.",
        "stat_signature": "Attempted winner rate from outside the singles sideline above 30% of off-balance contact sequences flags poor situational selection; error-per-attempt above 0.50 on those occasions confirms negative expectancy.",
        "mechanism": "Off-balance contact constrains racket-face angle range; body momentum away from the target reduces control over pace and direction, compounding the low-margin target error.",
        "conditions": "Most critical against heavy-angled opponents who deliberately drag the receiver wide; also prominent on fast indoor surfaces where wide balls arrive with compressed reaction time.",
        "magnitude": "Profiles attempting winners above 30% from off-balance positions concede roughly 2-4 extra points per set; adopting a cross-court reset converts those negatives to neutral outcomes.",
        "links": ["footwork_lapse_error", "over_aggression_error_tax", "net_approach_error_rate", "drop_shot_misexecution_risk"],
    },
    {
        "slug": "momentum_swing_error_cascade",
        "title": "Momentum-Swing Error Cascade",
        "summary": "Clustering of unforced errors in 2-4 consecutive points following a momentum trigger such as a double fault, net-cord winner for the opponent, or an unexpected break.",
        "stat_signature": "Error cluster probability (2-plus consecutive unforced errors in 6 points) above 18% after a momentum trigger indicates a cascade pattern; independent-point error rate implies a cluster probability near 5-7%.",
        "mechanism": "Negative emotional events disrupt attentional focus and push arousal beyond the optimal performance band; over-effortful swing paths produce errors that reinforce the cascade rather than resetting it.",
        "conditions": "Most visible in the third set when emotional reserves are depleted; amplified against opponents who accelerate pace to exploit the reactive error window.",
        "magnitude": "Cascade profiles lose an additional 2-4 points per set beyond the initial trigger event; sets containing at least one cascade episode are lost at substantially higher rates.",
        "links": ["break_point_error_leakage", "tiebreak_error_spike", "deuce_game_error_exposure", "unforced_error_rate_neutral_rally"],
    },
    {
        "slug": "deuce_game_error_exposure",
        "title": "Deuce-Game Unforced-Error Exposure",
        "summary": "Error-rate elevation during extended deuce-game situations, measuring how discipline erodes as a service game reaches multiple deuce-advantage cycles without resolution.",
        "stat_signature": "Unforced error rate in the fourth-deuce-cycle-plus above 20% versus a baseline below 14% flags structural exposure; double-fault probability above 7% in late-deuce service situations is elevated.",
        "mechanism": "Extended deuce cycling inflates internal pressure as each point becomes laden with recency value; the resulting arousal spike disrupts established serve and groundstroke routines.",
        "conditions": "Most pronounced in the final set on fast indoor surfaces where service games are expected to be held; opponents who routinely force deuce exploit this exposure across the fourth and fifth deuce cycles.",
        "magnitude": "Service games reaching four-plus deuce cycles are held at roughly 10-15% lower rates for error-susceptible profiles than for disciplined ones.",
        "links": ["break_point_error_leakage", "double_fault_pressure_propensity", "momentum_swing_error_cascade", "tiebreak_error_spike"],
    },
    {
        "slug": "drop_shot_misexecution_risk",
        "title": "Drop-Shot Mis-Execution Risk",
        "summary": "Frequency with which drop-shot attempts land in the net or bounce too deep, turning a tactical weapon into a self-inflicted error when executed from a non-ideal position.",
        "stat_signature": "Drop-shot error rate above 22% of attempts indicates structural execution risk; average bounce depth above 1.1 m from the net on successful placements signals insufficient touch for consistent deployment.",
        "mechanism": "The drop shot requires precise racket-face angle and backswing deceleration; executing under pace pressure or from behind the baseline eliminates the deceleration window and collapses net clearance.",
        "conditions": "Error rate rises when attempted against opponents with elite closing speed who read the disguise early; also elevated on slower surfaces where the opponent has more time to reach the ball.",
        "magnitude": "Drop shots with error rates above 20% become a net-negative tactic beyond 5 attempts per set; shifting the execution threshold to inside the service line typically halves the error rate.",
        "links": ["shot_selection_discipline_on_the_run", "net_approach_error_rate", "over_aggression_error_tax", "footwork_lapse_error"],
    },
    {
        "slug": "energy_management_lapse_late_set",
        "title": "Energy-Management Discipline Late in Sets",
        "summary": "Increase in unforced errors and double faults in the final two games of a set, attributable to physical fatigue compounding on shot-execution precision.",
        "stat_signature": "Unforced error rate in games 9-12 elevated 4-8 percentage points above games 1-4 flags fatigue-based discipline erosion; double-fault rate rising above 6% in the same window confirms the pattern.",
        "mechanism": "Peripheral muscle fatigue reduces split-step reactivity and shortens follow-through, reducing spin rate and net clearance margins; compounding lactic load in extended sets accelerates the effect.",
        "conditions": "Most visible in three-set matches on clay where sustained movement demands are highest; also elevated in humid outdoor conditions that accelerate physiological fatigue onset.",
        "magnitude": "Profiles showing late-set error rise above 6 percentage points convert roughly 12-18% fewer service games in games 9 and beyond.",
        "links": ["rally_length_error_curve", "second_serve_risk_discipline", "surface_induced_error_discipline", "double_fault_pressure_propensity"],
    },
    {
        "slug": "surface_induced_error_discipline",
        "title": "Surface-Induced Error Discipline",
        "summary": "How unforced-error rates shift across court surfaces (clay, hard, grass), capturing whether baseline execution is surface-independent or driven by bounce-speed adaptation gaps.",
        "stat_signature": "Surface delta in unforced error rate above 6 percentage points between best and worst surface indicates meaningful adaptation gaps; double-fault rate cross-surface variance above 3 percentage points confirms service mechanics are surface-sensitive.",
        "mechanism": "Slow clay raises bounce height and rewards topspin patience; fast grass compresses reaction time and amplifies footwork errors; hard courts penalise late adapters to bounce rhythm.",
        "conditions": "Error discipline is most tested on first-tournament appearances on a new surface mid-season; transitions from clay to grass in a two-week window show the largest cross-surface error spikes.",
        "magnitude": "Profiles with a 6-plus percentage-point surface delta concede roughly 2-4 extra unforced errors per set on their weaker surface; across a best-of-five match this represents 10-20 self-inflicted points.",
        "links": ["unforced_error_rate_neutral_rally", "rally_length_error_curve", "footwork_lapse_error", "energy_management_lapse_late_set"],
    },
    {
        "slug": "first_strike_over_commit_error",
        "title": "First-Strike Over-Commitment Error",
        "summary": "Errors from over-ambitious serve-plus-one or return-plus-one attacks attempted at full pace or extreme angle before setup conditions are sufficient.",
        "stat_signature": "Errors on the second shot of the point above 20% when the first shot was neutral or defensive indicates premature attack; winners-to-errors ratio below 0.8 on second-ball attacks after a defensive first ball confirms negative expectancy.",
        "mechanism": "First-strike strategy is profitable only when the initial delivery generates genuine positional advantage; committing to an attack from a neutral position requires line-hitting precision that elevates error probability faster than winner probability.",
        "conditions": "Most prominent against compact defensive returners who absorb pace and invite the over-aggressive attack; also frequent on fast indoor hard courts where first-strike intent is culturally ingrained but margin shrinks.",
        "magnitude": "Profiles with second-ball attack error rates above 20% concede an estimated 3-5 net points per set; shifting the attack trigger to a clearly offensive setup ball saves roughly 1.5-2 errors per set.",
        "links": ["over_aggression_error_tax", "shot_selection_discipline_on_the_run", "net_approach_error_rate", "unforced_error_rate_neutral_rally"],
    },
    {
        "slug": "time_violation_routine_disruption",
        "title": "Time-Violation and Routine-Disruption Risk",
        "summary": "Frequency of time violations and between-point routine overruns indicating disrupted service discipline and vulnerability to umpire intervention in match flow.",
        "stat_signature": "Time violations above 2 per set signal chronic between-point overrun; routine-duration variance above 4 seconds per point indicates inconsistent pre-serve preparation; double-fault rate elevated in the subsequent 3 service points after a violation.",
        "mechanism": "A consistent pre-point routine anchors arousal and motor preparation; disrupted routines from umpire calls or self-imposed overthinking collapse the automaticity that stable service mechanics depend on.",
        "conditions": "Most disruptive in outdoor conditions with wind or crowd noise that naturally extend routines; also elevated in third-set tiebreaks where self-pressure extends pre-serve deliberation beyond the 25-second window.",
        "magnitude": "Service points following a time violation show double-fault rates elevated roughly 3-5 percentage points; profiles receiving 2-plus violations per set show measurably lower first-serve percentages in the same game.",
        "links": ["double_fault_pressure_propensity", "second_serve_risk_discipline", "tiebreak_error_spike", "momentum_swing_error_cascade"],
    },
]
