"""NBA Efficiency Curves — person-free usage-efficiency tradeoff intelligence for the brain."""
from __future__ import annotations

SPORT = "NBA"
FAMILY = "EfficiencyCurves"

CONCEPTS: list[dict] = [
    {
        "slug": "usage_efficiency_tradeoff_curve",
        "title": "Usage-Efficiency Tradeoff Curve",
        "summary": "The downward-sloping relationship between possession-usage rate and true-shooting efficiency, where each 5-point usage increment above 25% costs roughly 1.5-2.5 TS points as shot quality, creation difficulty, and defensive attention all compound.",
        "stat_signature": "TS% decline per +5 usage above 25%: 1.5-2.5 pp across a 500+ attempt sample. Usage above 35% correlates with TS% 3-5 pp below a size-and-role-matched baseline. Year-over-year slope stability r ≈ 0.60 for roles with stable teammate context.",
        "mechanism": "Higher usage forces a player to exhaust first-option looks and extend into lower-quality creation territory; simultaneously, defenses load preparation resources toward the primary option, tightening contest windows and pre-rotating help. Both supply-side (shot quality degradation) and demand-side (defensive attention amplification) forces act in the same direction.",
        "conditions": "Slope steepens for players without a reliable mid-range or self-creation pull-up to supplement rim-attack load; flattens for elite shot creators whose skill range spans multiple zones. Teammate spacing quality mediates slope — compressed floors steepen the curve by reducing drive lanes and catch-and-shoot relief valves.",
        "magnitude": "A player increasing usage from 25% to 35% typically sacrifices 3-5 TS points. Applied over 600 field-goal attempts, the efficiency cost equals roughly 18-30 expected points lost relative to the lower-usage baseline — a material but often offset gain via raw volume.",
        "links": ["diminishing_returns_inflection_point", "defensive_attention_efficiency_drag", "scoring_volume_efficiency_pareto_frontier", "spacing_dependent_efficiency_slope"],
    },
    {
        "slug": "marginal_shot_value_decline",
        "title": "Marginal Shot Value Decline With Volume",
        "summary": "Expected points-per-shot of the next attempt fall as shot volume rises within a possession workload, measured as the slope of expected eFG against ranked shot difficulty within a player's attempt sequence.",
        "stat_signature": "Expected eFG on a player's 1st-ranked shot opportunity in a possession: 57-62%. By the 8th self-created attempt in a quarter, expected eFG drops to 48-52%. The marginal-value decline slope steepens above 6 self-created attempts per quarter.",
        "mechanism": "Players exhaust their highest-quality looks first (open catch-and-shoot, early-clock rim attacks), then progress to lower-quality self-creation as the possession workload rises. Each additional attempt requires more dribble moves, more clock burned, and more defensive recovery time — all degrading the expected shot value of the next attempt in the sequence.",
        "conditions": "Decline is sharpest for shot creators who cannot efficiently exit to a secondary offensive option; ballhandlers in ball-dominant systems with limited off-ball movers show the steepest marginal decline curves. Pace modulates the effect — faster teams recycle possession counts and partially reset attempt quality.",
        "magnitude": "Marginal expected eFG drops approximately 1.5-2.5 pp per added self-created attempt after the 4th in a quarter. Over a full game, the quality gradient between a player's first and last attempt clusters spans 8-12 eFG points.",
        "links": ["usage_efficiency_tradeoff_curve", "shot_difficulty_volume_elasticity", "isolation_volume_efficiency_decay", "shot_clock_volume_quality_tradeoff"],
    },
    {
        "slug": "shot_difficulty_volume_elasticity",
        "title": "Shot-Difficulty Elasticity to Volume",
        "summary": "The elasticity of average defended-shot difficulty with respect to forced volume, quantified as the rise in contested-shot share and reduced-defender-distance share per added self-created attempt above a role-typical baseline.",
        "stat_signature": "Contested-shot share rises approximately 3-5 pp per added self-created attempt per 36 above the positional median. Defender distance on jump shots compresses from 4.5+ feet (open) to under 2 feet (tight) for players who exceed their role-typical creation volume by 4+ attempts per 36.",
        "mechanism": "Forced volume depletes the easiest looks in a player's shot menu, compelling selection of increasingly defender-proximate and clock-pressured attempts. Defenses also adapt within game — as primary-option creation volume rises, help rotations tighten and recovery positions reset closer to the ball-handler's preferred creation zones.",
        "conditions": "Elasticity is highest for one-dimensional scorers with a narrow creation toolkit confined to one zone or action type; ball-handlers with layered creation (pull-up, drive-and-kick, post-up) show lower elasticity because forced volume spills across multiple relatively viable options.",
        "magnitude": "A player forced to create 4 additional self-generated looks per 36 beyond their established baseline typically sees a 10-18 pp increase in tight-contest share on jump shots, equivalent to a 4-7 pp eFG drag on the incremental attempts.",
        "links": ["marginal_shot_value_decline", "usage_efficiency_tradeoff_curve", "defensive_attention_efficiency_drag", "self_creation_efficiency_penalty"],
    },
    {
        "slug": "diminishing_returns_inflection_point",
        "title": "Diminishing-Returns Inflection in the Usage Curve",
        "summary": "The usage threshold near 30-33% where the efficiency-loss slope steepens, captured as the second derivative of the TS%-on-usage curve and the usage level at which marginal efficiency cost per additional usage point begins accelerating.",
        "stat_signature": "Second derivative of TS% on usage turns sharply negative near 30-33% usage for most role archetypes. Below 28% usage, incremental efficiency cost per usage point: 0.5-1.0 TS pp. Above 33%: cost rises to 1.8-3.0 TS pp per usage point — a 2-3x acceleration in the marginal penalty.",
        "mechanism": "Below the inflection, increased usage primarily adds more of the player's established shot types at modest difficulty increases. Above the inflection, the player begins routinely extending into creation actions outside their trained skill set — isolated post-ups for perimeter creators, forced pull-ups for rim finishers — where the efficiency penalty accelerates non-linearly.",
        "conditions": "Inflection sits lower (near 27-30%) for players with a narrow creation toolkit and higher (near 33-36%) for elite ball-handlers with multiple proven creation modes. In lineup contexts with degraded spacing, the inflection point shifts left by roughly 3-5 usage points.",
        "magnitude": "Exceeding the inflection point by 5 usage points typically costs an additional 3-5 TS pp beyond the pre-inflection slope projection — the difference between a player working within their efficiency envelope and one operating in demonstrably diminishing territory.",
        "links": ["usage_efficiency_tradeoff_curve", "scoring_volume_efficiency_pareto_frontier", "defensive_attention_efficiency_drag", "team_usage_concentration_efficiency"],
    },
    {
        "slug": "scoring_volume_efficiency_pareto_frontier",
        "title": "Scoring Volume-Efficiency Pareto Frontier",
        "summary": "The empirical outer boundary of achievable points-per-game against TS% across a population, describing the convex volume-efficiency frontier and each player's interior distance from it as an efficiency gap measure.",
        "stat_signature": "Frontier PPG thresholds at high efficiency: 28+ PPG at TS% ≥ 60% is elite frontier territory occupied by fewer than 5 players per season. The frontier's convex shape means moving from 20 to 28 PPG at frontier efficiency requires a TS% sacrifice of roughly 3-6 pp. Players more than 5 pp inside the frontier in both dimensions are in the sub-optimal interior.",
        "mechanism": "The frontier is convex because usage-efficiency tradeoff forces bound the achievable combination space — a player at maximum reachable TS% for their creation toolkit cannot simultaneously maximize PPG without descending the efficiency curve. The frontier shape encodes the aggregate cost of volume expansion for the best-performing players in the league.",
        "conditions": "Frontier position is most stable for players with 500+ field-goal attempts and 3+ seasons of sustained volume. Short samples inflate apparent frontier position (lucky conversion rates); multi-year frontiers regress to a lower sustainable boundary. Teammate quality mediates frontier access — better spacing shifts the individual frontier outward.",
        "magnitude": "A player 4 pp inside the TS% frontier at their PPG level has an efficiency gap worth approximately 15-25 additional expected points per season if the gap were closed — a concrete benchmark for improvement scope without claiming the gap represents a reachable edge.",
        "links": ["usage_efficiency_tradeoff_curve", "diminishing_returns_inflection_point", "spacing_dependent_efficiency_slope", "lineup_scoring_load_balance_curve"],
    },
    {
        "slug": "self_creation_efficiency_penalty",
        "title": "Self-Creation Efficiency Penalty Slope",
        "summary": "The per-shot efficiency discount of unassisted against assisted looks as self-creation share climbs, measured as eFG points lost per 10-point increase in unassisted-attempt share above a player's role baseline.",
        "stat_signature": "eFG penalty per 10-pp rise in unassisted share above role baseline: 2.0-3.5 eFG pp for perimeter creators; 1.0-2.0 eFG pp for post scorers with trained self-creation. At unassisted share above 65%, eFG is typically 6-10 pp below the same player's assisted-look eFG.",
        "mechanism": "Self-created shots require energy expenditure on the creation action itself, leaving the finisher with less balance, narrower timing windows, and elevated defensive contest proximity. The creation process also advances the shot clock, reducing the option to reset to a higher-quality look if the initial creation sequence fails to generate the desired opening.",
        "conditions": "Slope is steepest for high-usage primary options who carry the playmaking burden alongside the scoring burden; players in systems with dedicated playmakers maintain lower unassisted shares and show flatter penalty slopes. Back-to-backs and late-game fatigue amplify the self-creation penalty.",
        "magnitude": "A player moving from 45% to 65% unassisted share typically sacrifices 4-7 eFG pp on the incremental attempts. Over 400 field-goal attempts at elevated self-creation share, the cumulative conversion cost is roughly 16-28 expected points relative to the assisted-rate counterfactual.",
        "links": ["shot_difficulty_volume_elasticity", "usage_efficiency_tradeoff_curve", "isolation_volume_efficiency_decay", "secondary_creator_efficiency_lift"],
    },
    {
        "slug": "rim_pressure_diminishing_returns",
        "title": "Rim-Pressure Diminishing Returns",
        "summary": "The declining marginal at-rim conversion and foul-draw rate as drive volume rises and defenses load the paint, measured as the at-rim FG% and free-throw-rate slope per added drive per 36.",
        "stat_signature": "At-rim FG% for the 1st-4th drive per 36: 65-68%. For the 9th-12th drive per 36: 59-63%. Free-throw rate (FTA per drive) peaks near 5-7 drives per 36 and declines above 9 drives per 36 as help rotations prevent contact. At-rim attempt share above 55% of total FGA signals an aggressive paint-pressure role.",
        "mechanism": "Initial drives reach the rim before help rotations fully set; as drive volume rises, weakside defenders pre-rotate to paint positions in anticipation, converting open-lane drives into contested or altered layup attempts. The foul-draw rate declines simultaneously because help defenders arriving early can contest cleanly without fouling.",
        "conditions": "Diminishing returns onset is earlier (near 7 drives per 36) in high-help defensive schemes with switchable bigs; onset is later (near 10 drives per 36) against point-of-attack-heavy defenses that commit defenders to ball containment. Off-ball spacing quality mediates the rate — better shooters pull help defenders away, extending the rim-attack value window.",
        "magnitude": "Drive volume rising from 6 to 11 per 36 typically costs 4-6 pp at-rim FG% and reduces free-throw rate by 15-25% of its peak value — a combined possession-efficiency decline equivalent to roughly 0.08-0.12 fewer expected points per drive on the incremental volume.",
        "links": ["usage_efficiency_tradeoff_curve", "defensive_attention_efficiency_drag", "spacing_dependent_efficiency_slope", "marginal_offensive_rebound_value"],
    },
    {
        "slug": "isolation_volume_efficiency_decay",
        "title": "Isolation-Volume Efficiency Decay",
        "summary": "The points-per-possession decline as isolation frequency increases and defenses pre-rotate help, quantified as the PPP slope per 5-point rise in isolation play-type share above a threshold near 10%.",
        "stat_signature": "Isolation PPP at 8-12% play-type share: 0.92-1.02. At 20-25% share: 0.85-0.93. At 30%+ share: 0.78-0.87. The PPP slope steepens above 20% share — each additional 5 pp of isolation share above 20% costs approximately 0.04-0.07 PPP on the marginal possessions.",
        "mechanism": "Early-frequency isolations catch defenses in natural recovery or mismatch states before targeted defensive preparation; as isolation share rises, defenses assign their best on-ball defender, pre-position help on the expected drive or pull-up side, and reduce the set of viable scoring actions through pre-commitment. The isolation creator cannot efficiently exit the ball because the play-type is designed for terminal creation.",
        "conditions": "Decay is sharpest in playoff series where opponent film preparation concentrates between games; regular-season decay is shallower because game-to-game opponent variation resets defensive focus. Players with three-level creation (rim, pull-up mid, pull-up three) show shallower decay because defenders cannot fully commit to a single rotation.",
        "magnitude": "A player running isolations at 30% play-type share rather than 15% operates at approximately 0.10-0.15 PPP below their peak isolation efficiency — equivalent to roughly 15-22 fewer expected points per 150 isolation possessions at high volume.",
        "links": ["usage_efficiency_tradeoff_curve", "marginal_shot_value_decline", "self_creation_efficiency_penalty", "defensive_attention_efficiency_drag"],
    },
    {
        "slug": "defensive_attention_efficiency_drag",
        "title": "Defensive-Attention Efficiency Drag Function",
        "summary": "How rising offensive load attracts incremental help and double-team frequency, measured as the relationship between usage rate and faced double-team rate and the resulting per-shot efficiency drag across the possession.",
        "stat_signature": "Double-team rate at 20-25% usage: 4-8% of half-court possessions. At 30-35% usage: 10-18%. Above 35% usage: 18-30%. Each 10-pp rise in double-team rate typically costs 0.05-0.10 PPP on possessions where a double arrives — partially offset by kick-out value if teammates convert open looks.",
        "mechanism": "As a primary option's offensive load rises, defenses allocate additional preparation capital to disruption tactics (early double-teams, trap actions, ice-and-hedge coverage). The double-team removes a possession from the primary scorer and transfers it to a secondary option who may convert at lower efficiency; the primary scorer's own per-shot efficiency also declines because double-team anticipation forces rushed decisions.",
        "conditions": "Drag is highest when secondary playmaking options are limited — the double-team forces the ball to a poor decision-maker or poor converter. Teams with strong secondary ball-handlers can convert the defensive attention into a net positive; teams without them absorb the drag as a pure efficiency loss.",
        "magnitude": "A primary option facing double-team actions on 20% of half-court possessions, without a secondary option who can punish the tactic, experiences roughly 0.04-0.08 PPP drag across all half-court possessions — approximately 6-12 fewer expected points per 150 possessions compared to a less-targeted role.",
        "links": ["usage_efficiency_tradeoff_curve", "isolation_volume_efficiency_decay", "secondary_creator_efficiency_lift", "team_usage_concentration_efficiency"],
    },
    {
        "slug": "minutes_load_efficiency_curve",
        "title": "Minutes-Load Efficiency Curve",
        "summary": "The within-game and within-season relationship between cumulative minutes load and per-possession scoring efficiency, measured as TS% decline per additional 6 minutes of accumulated in-game load beyond 24 minutes.",
        "stat_signature": "TS% delta per added 6 minutes above 24 in-game minutes: −0.8 to −1.5 pp for high-usage scorers. Players averaging 36+ minutes per game show a Q4 TS% that is 1.5-3.0 pp below their Q1 value on matched shot quality. Across a season, players with 2,800+ regular-season minutes show 2-4% lower per-possession efficiency in the final quarter of the season than the first.",
        "mechanism": "Cumulative fatigue reduces lower-body explosive output that powers both rim attacks and jump-shot arc, degrades reaction-time on shot-fake counters, and elevates error rates in decision-making under defensive pressure. Within-game fatigue compounds with within-season load; players in high-minutes roles with short-rest schedules show the steepest late-game efficiency decline.",
        "conditions": "Curve steepens for players with high body-contact frequency (drive-heavy, foul-drawing roles) and less body-contact for perimeter shooters whose efficiency depends less on explosive lower-body contribution. Rest scheduling — back-to-backs, three-games-in-four nights — amplifies the within-game slope.",
        "magnitude": "A high-usage scorer accumulating 38 minutes per game shows roughly 2-4 TS pp below their optimal-rest baseline by deep fourth quarters, translating to approximately 6-12 fewer expected points per 100 possessions in late-game situations compared to a rested baseline.",
        "links": ["fatigue_efficiency_decay_slope", "usage_efficiency_tradeoff_curve", "rim_pressure_diminishing_returns", "shot_clock_volume_quality_tradeoff"],
    },
    {
        "slug": "pace_possession_efficiency_tradeoff",
        "title": "Pace-Possession Efficiency Tradeoff",
        "summary": "How added possessions from faster pace trade against per-possession efficiency as more attempts come from early-clock and transition-recovery contexts, measured as offensive-rating slope per added possession per 48.",
        "stat_signature": "Offensive rating slope per added possession per 48 above 102 pace: −0.3 to −0.8 rating points. Teams above 108 possessions per 48 sustain offensive ratings 1.5-3.0 points below their half-court efficiency projection. Transition-opportunity rate above 18% of possessions compresses per-possession quality toward 95-100 pace efficiency from quality shot-generation.",
        "mechanism": "Faster pace generates transition opportunities (high efficiency) but also increases possessions where the half-court offense is incomplete — rushed sets, fewer off-ball actions, higher early-clock shot-clock pressure. The marginal possession above a team's sustainable pace tends to come from weaker half-court execution, pulling down per-possession efficiency while adding raw possession count.",
        "conditions": "Tradeoff is sharpest for teams whose primary offensive actions require extended shot-clock time (blocker-mover sets, multiple-action half-court progressions). Transition-attack-dominant teams may show a flatter or even positive slope if their transition efficiency is high enough to offset early-offense quality degradation.",
        "magnitude": "A team running 107 possessions per 48 rather than 100, at a −0.5 rating slope, sacrifices roughly 3.5 offensive-rating points on per-possession quality — typically more than compensated by the raw-possession gain, but the quality degradation is measurable in close-game late-clock situations.",
        "links": ["shot_clock_volume_quality_tradeoff", "usage_efficiency_tradeoff_curve", "lineup_scoring_load_balance_curve", "marginal_shot_value_decline"],
    },
    {
        "slug": "team_usage_concentration_efficiency",
        "title": "Team Usage-Concentration Efficiency Curve",
        "summary": "The relationship between how concentrated a team's usage is on its top option and team offensive efficiency, measured as offensive rating against the Herfindahl index of possession share across the starting five.",
        "stat_signature": "Team offensive rating peaks near a Herfindahl index of 0.22-0.28 (moderate concentration), declining on both the hyper-balanced extreme (< 0.18) and the hyper-concentrated extreme (> 0.35). A top-option usage above 35% without a capable secondary option correlates with 2-4 rating-point team offensive efficiency drag relative to a two-option spread of 27%/22%.",
        "mechanism": "Extreme concentration overloads the primary option's diminishing-returns zone and makes the offense predictable; extreme balance removes the threat of a dominant scorer that opens up the half-court for the rest of the offense. An optimal concentration level allows the primary option to operate within their efficiency envelope while generating enough defensive attention to lift secondary-option opportunity quality.",
        "conditions": "Optimal concentration shifts upward (toward higher primary usage) when the primary option has demonstrated elite self-creation efficiency at 30%+ usage and secondary options are strong converters but not generators. Optimal shifts downward (more balance) for teams with multiple on-ball creation threats and no dominant individual efficiency edge.",
        "magnitude": "Teams at a Herfindahl index above 0.35 average roughly 2-4 offensive rating points below a well-balanced team of comparable personnel quality, approximately equivalent to 3-5 more points per 100 possessions being left on the table through diminishing-returns overuse.",
        "links": ["usage_efficiency_tradeoff_curve", "diminishing_returns_inflection_point", "defensive_attention_efficiency_drag", "lineup_scoring_load_balance_curve"],
    },
    {
        "slug": "shot_clock_volume_quality_tradeoff",
        "title": "Shot-Clock Volume-Quality Tradeoff",
        "summary": "How the urgency to generate a shot before the clock expires trades attempt volume against expected quality, measured as the expected-points-per-shot slope across descending shot-clock buckets from 22+ seconds to under 7 seconds.",
        "stat_signature": "Expected points per shot at 22+ seconds on clock: 1.05-1.12. At 7-14 seconds: 0.98-1.05. Below 7 seconds: 0.87-0.95. Forced-clock attempts below 5 seconds: 0.78-0.86. Shot-clock-under-7 share above 18% of half-court possessions signals systematic late-clock inefficiency in the offensive system.",
        "mechanism": "Shot quality degrades as clock pressure removes off-ball movement options, constrains the shot menu to whatever the ball-handler can create in available time, and compresses the defender's recovery duty into a contested stand. Early-clock possessions benefit from full play-execution including multiple-action progressions; late-clock possession volume reflects failed earlier attempts to generate a shot.",
        "conditions": "Clock-quality tradeoff is sharpest for offenses with slow initiation (post-entry, multiple-action blocker-mover sets); fast-initiation teams (early pick-and-roll) maintain quality further into the shot clock. Tight late-game situations force late-clock attempts from clock-killing strategy rather than offensive failure.",
        "magnitude": "Moving 5% of half-court possessions from the 14-22 second bucket to the under-7 bucket costs approximately 0.08-0.12 expected points per relocated possession — equivalent to roughly 4-6 fewer expected points per 100 half-court possessions with elevated late-clock rates.",
        "links": ["marginal_shot_value_decline", "pace_possession_efficiency_tradeoff", "isolation_volume_efficiency_decay", "minutes_load_efficiency_curve"],
    },
    {
        "slug": "secondary_creator_efficiency_lift",
        "title": "Secondary-Creator Efficiency-Lift Curve",
        "summary": "How adding a second on-ball creator flattens the primary option's usage-efficiency curve by lowering forced volume, measured as the TS% recovery per unit of usage offloaded to a capable secondary creator.",
        "stat_signature": "Primary-option TS% recovery per 3-pp usage offloaded to a secondary creator: 0.8-1.5 TS pp. Lineups that shift primary usage from 32% to 27% via a secondary creator addition show a 2-3 TS pp improvement on the primary option's shots. Full-season TS% for primary options in two-creator lineups runs 1.5-3.0 pp above their single-creator-lineup splits.",
        "mechanism": "A capable secondary creator removes possessions from the primary option's diminishing-returns zone and re-enters them at the secondary option's steeper-gains segment of the efficiency curve. The primary option also benefits from defenses splitting attention, reducing double-team frequency and loosening contest proximity on remaining shots.",
        "conditions": "Lift is largest when the primary option was already operating above their usage inflection point (30%+ usage) and the secondary creator can generate quality half-court shots rather than merely initiating without finishing. Lift diminishes if the secondary creator's efficiency on generated possessions falls below the primary option's diminishing-returns baseline.",
        "magnitude": "A primary option restored from 33% to 27% usage by a secondary creator typically recovers 2-4 TS points on their own shots. If the secondary option converts at a 55%+ TS baseline, the team-level offensive rating gain is roughly 1.5-3.0 rating points relative to single-creator reliance.",
        "links": ["usage_efficiency_tradeoff_curve", "defensive_attention_efficiency_drag", "team_usage_concentration_efficiency", "self_creation_efficiency_penalty"],
    },
    {
        "slug": "playmaking_volume_turnover_tradeoff",
        "title": "Playmaking-Volume Turnover Tradeoff",
        "summary": "The rising turnover rate as assist-creation volume increases against pressure, measured as the turnover-rate slope per added potential-assist pass per 36 and the empirical assist-to-turnover frontier.",
        "stat_signature": "Turnover rate slope per added potential-assist per 36 above 8: 0.4-0.8 pp additional turnover rate. Playmakers above 10 potential assists per 36 show turnover rates 2-4 pp above those at 6-8 per 36. The efficient frontier of assist-to-turnover ratio (ATR above 3.0) is achievable at up to 9 potential assists per 36; above 12, ATR above 2.5 is rare.",
        "mechanism": "Higher playmaking volume forces passes into progressively tighter windows — closeout-prone skip passes, early-entry attempts against recovering defenders, late-clock dribble-hand-off sequences. As pass volume expands beyond a player's trained decision-making envelope, the fraction of risky-window passes rises, elevating live-ball turnover probability per possession.",
        "conditions": "Turnover-volume slope is steepest in half-court settings against zone defenses that make passing lanes intermittently available; transition playmaking generates fewer turnovers per pass because windows are wider. Late-game defensive intensity and trap-heavy coverage inflate the turnovers-per-potential-assist at the margin.",
        "magnitude": "A point-guard operating at 13 potential assists per 36 rather than 9 typically produces 1.5-2.5 additional turnovers per 36 — a net possession cost of roughly 1.5-2.5 points per 36 that partially offsets the assist-volume gain if secondary converters are near-average finishers.",
        "links": ["usage_efficiency_tradeoff_curve", "secondary_creator_efficiency_lift", "pace_possession_efficiency_tradeoff", "shot_clock_volume_quality_tradeoff"],
    },
    {
        "slug": "spacing_dependent_efficiency_slope",
        "title": "Spacing-Dependent Efficiency Slope",
        "summary": "How a scorer's volume-efficiency curve shifts with floor spacing, measured as the change in TS%-on-usage slope between high-spacing and compressed-floor lineup contexts.",
        "stat_signature": "TS%-on-usage slope in high-spacing lineups (3+ floor-spacers): −0.8 to −1.2 pp per 5 usage points. In compressed-floor lineups (0-1 spacers): −1.8 to −2.8 pp per 5 usage points — a 50-130% steepening of the efficiency penalty slope. Ball-handlers in compressed lineups operate 3-6 TS pp below their high-spacing baseline at matched usage.",
        "mechanism": "Floor spacing extends drive lanes and forces help defenders to honor perimeter threats, expanding the set of available rim-attack and pull-up paths. Compressed floors allow help defenders to commit fully to paint protection without conceding shooters, forcing primary options into tougher creation sequences and generating harder looks from each additional usage point.",
        "conditions": "Effect is largest for drive-first creation roles whose primary value comes from rim pressure and kick-out generation; purely off-ball spot-up scorers benefit from spacing but their own curve slope is less sensitive because they rarely force creation. The spacing effect is nonlinear — adding a third spacer yields less marginal lift than adding the second.",
        "magnitude": "A primary ball-handler shifting from a three-spacer lineup to a one-spacer lineup at constant usage typically shows a 3-5 TS pp decline at the 30% usage threshold — nearly equivalent to the efficiency cost of adding 5 usage points in an already-well-spaced system.",
        "links": ["usage_efficiency_tradeoff_curve", "scoring_volume_efficiency_pareto_frontier", "defensive_attention_efficiency_drag", "lineup_scoring_load_balance_curve"],
    },
    {
        "slug": "lineup_scoring_load_balance_curve",
        "title": "Lineup Scoring-Load Balance Curve",
        "summary": "How team efficiency responds to balance against concentration of scoring load across a five-man unit, measured as offensive rating against the standard deviation of on-court usage shares within the lineup.",
        "stat_signature": "Offensive rating peaks near a within-lineup usage standard deviation of 7-9% (moderate balance). Usage SD above 12% correlates with 1.5-3.0 rating points below the within-lineup personnel quality projection. Usage SD below 5% (hyper-balance) correlates with 1.0-2.0 rating points below expectation as the primary option's threat-premium is diluted.",
        "mechanism": "Optimal load balance allows the offense to maintain a credible primary-scorer threat that absorbs defensive attention, while distributing enough possessions across secondary options to prevent over-preparation. Extreme concentration amplifies the primary option's diminishing returns; extreme balance removes the attention-allocation asymmetry that creates open-look opportunities for secondary options.",
        "conditions": "Optimal balance point shifts toward more concentration for lineups where only one player has creation-to-scoring depth; shifts toward more balance when two or more players can generate and finish efficiently. Playoff series preparation shifts the optimal point toward lower concentration as opponents invest more specific preparation per game.",
        "magnitude": "A five-man lineup shifting from a usage SD of 13% to 8% while holding aggregate quality constant typically gains 1.5-3.0 offensive rating points — roughly 1.5-3.0 additional expected points per 100 possessions from more efficient load distribution.",
        "links": ["team_usage_concentration_efficiency", "scoring_volume_efficiency_pareto_frontier", "secondary_creator_efficiency_lift", "spacing_dependent_efficiency_slope"],
    },
    {
        "slug": "fatigue_efficiency_decay_slope",
        "title": "Fatigue Efficiency-Decay Slope",
        "summary": "The per-quarter erosion of matched-quality shot conversion and decision efficiency as in-game fatigue accumulates, measured as the TS%-on-equivalent-shots slope from first to fourth quarter for high-minute roles.",
        "stat_signature": "TS% decay from Q1 to Q4 for 36+ minute scorers on matched shot quality: −1.5 to −3.5 pp. Decision-efficiency proxy (turnover rate) rises 1.5-2.5 pp from Q1 to Q4 for high-usage ball-handlers. Back-to-back second-game efficiency drag: 1.5-4.0 TS pp below full-rest baseline for players with 30+ minutes in the first game.",
        "mechanism": "Accumulated in-game fatigue reduces the explosive lower-body contribution to jump-shot arc and rim-attack verticality, while simultaneously degrading cognitive processing speed for decision-making under defensive pressure. The net effect is an increasing fraction of attempts that miss the technical execution threshold required for the modeled shot quality to be realized.",
        "conditions": "Decay slope steepens for players with high-contact frequency (foul-drawing rim-attackers) and attenuates for perimeter shooters with mechanically consistent forms that depend less on explosive drive-loading. The slope is amplified on the second night of a back-to-back and in the fourth game of a five-game road stretch.",
        "magnitude": "A primary scorer showing a −3 TS pp Q4 decay on 80 Q4 attempts per season sacrifices approximately 2.4 expected points per season from fatigue-related conversion erosion — small in aggregate but material for shot-quality modeling in game-state projections weighting late-game conversion probability.",
        "links": ["minutes_load_efficiency_curve", "usage_efficiency_tradeoff_curve", "shot_clock_volume_quality_tradeoff", "self_creation_efficiency_penalty"],
    },
]
