"""MLB EfficiencyCurves concept nodes — person-free pitcher/hitter efficiency-decay intelligence."""
from __future__ import annotations

SPORT = "MLB"
FAMILY = "EfficiencyCurves"

CONCEPTS: list[dict] = [
    {
        "slug": "times_through_order_penalty_curve",
        "title": "Times-Through-the-Order Penalty Curve",
        "summary": "Opponent wOBA rises each time the batting order cycles against the same starter; the increment per pass averages +0.008 to +0.020 wOBA points, with the sharpest jump from second to third exposure.",
        "stat_signature": "First-time-through wOBA-against baseline; second-time delta +0.008 to +0.012; third-time cumulative delta +0.018 to +0.030 above first-pass; pull-point leverage peaks at batters-faced count 18-21.",
        "mechanism": "Repeated exposure lets hitters calibrate release-point cues, timing, and pitch sequencing; by the third trip they have logged at-bats against every pitch type in the starter's repertoire, reducing reaction uncertainty and enabling more aggressive zone coverage.",
        "conditions": "Steepest for two-pitch starters with flat sequencing entropy; substantially attenuated for four-pitch repertoires with strong tunneling; bullpen depth determines whether the penalty is exploited or allowed to compound.",
        "magnitude": "The third-time-through wOBA gap versus first-time-through spans roughly 25-35 points for average starters, equivalent to upgrading the opposing lineup by one quality tier for a full inning.",
        "links": ["third_time_through_inflection", "pitch_mix_predictability_with_familiarity", "tto_penalty_by_arsenal_depth", "starter_to_reliever_efficiency_crossover"],
    },
    {
        "slug": "pitch_count_effectiveness_decay",
        "title": "Pitch-Count Effectiveness Decay",
        "summary": "Starter stuff and command deteriorate as cumulative pitch count rises; wOBA-against climbs measurably per 15-pitch tranche above roughly pitch 60, with the replacement-line crossing near pitch 85-100 depending on arm profile.",
        "stat_signature": "wOBA-against slope per 15-pitch tranche above pitch 60 averages +0.012 to +0.018; first-pitch-strike rate drops 3-5 percentage points between tranche 1 and tranche 5; chase rate allowed falls 2-4 points as command precision erodes.",
        "mechanism": "Accumulated muscle fatigue degrades arm-slot consistency and velocity; reduced spin and decreased late movement widen the effective strike zone predictably; hitters with deep counts accelerate the pitcher into high-tranche territory faster.",
        "conditions": "Decay sharpest for power profiles reliant on velocity; command-first starters with efficient contact management show slower decay curves; warm-weather and high-humidity conditions attenuate some velocity loss.",
        "magnitude": "Pitchers beyond pitch 90 surrender wOBA approximately 0.035-0.050 above their pitch-1-to-60 baseline; the expected ERA over pitches 90-110 is roughly 0.6-0.9 above the starter's season ERA.",
        "links": ["velocity_decay_per_inning_slope", "stuff_command_decay_under_fatigue", "pitch_efficiency_innings_depth_curve", "starter_to_reliever_efficiency_crossover"],
    },
    {
        "slug": "velocity_decay_per_inning_slope",
        "title": "Velocity-Decay-per-Inning Slope",
        "summary": "Fastball velocity erodes across innings at a measurable rate; the mph-lost-per-25-pitches slope correlates with rising contact quality and falling whiff rate, providing a real-time fatigue signal.",
        "stat_signature": "Average velocity loss of 0.3-0.7 mph per 25 cumulative pitches; pitchers losing more than 1.2 mph by inning 5 show whiff-rate decline of 2-4 percentage points and barrel-rate increase of 1.5-2.5 points.",
        "mechanism": "Fast-twitch fiber fatigue reduces peak arm speed; lower velocity narrows the timing margin for hitters, lifting expected contact quality; the slope steepens when a starter relies heavily on velocity differential to set up secondaries rather than movement-based tunneling.",
        "conditions": "Most pronounced for power profiles with limited pitch-shape diversity; relievers who enter cold after extended warm-up show a transient inverse — initial velocity spikes before fatigue suppresses it; back-to-back-start starters show steeper slopes in the second outing.",
        "magnitude": "A 1-mph intra-start velocity loss corresponds to approximately a 0.8-1.2-point whiff-rate reduction and a 0.5-0.9-point barrel-rate increase; starters whose velocity drops more than 2 mph by inning 6 allow hard-hit rate roughly 4-6 points above their early-inning baseline.",
        "links": ["pitch_count_effectiveness_decay", "stuff_command_decay_under_fatigue", "velocity_decay_per_inning_slope", "pitch_efficiency_innings_depth_curve"],
    },
    {
        "slug": "third_time_through_inflection",
        "title": "Third-Time-Through Inflection Point",
        "summary": "The lineup's third pass introduces a nonlinear acceleration in the order-familiarity penalty; the wOBA curve bends sharply near batters-faced count 18-21, marking the decision-critical inflection for starter removal.",
        "stat_signature": "Marginal wOBA increment from second to third pass exceeds the first-to-second increment by 5-10 wOBA points in aggregate; batters-faced threshold of 18-21 identifies the inflection zone with roughly 65-70% predictive accuracy for above-replacement penalty.",
        "mechanism": "The third at-bat gives hitters their most refined mental model of the starter's tendencies, count-based patterns, and pitch-shape signatures; the information advantage is qualitatively greater than the incremental gain between first and second exposure, creating an asymmetric penalty escalation.",
        "conditions": "Inflection appears soonest against shallow-arsenal starters; diminished but not eliminated for four-pitch starters with high tunneling scores; left-on-base rate begins declining sharply once the inflection is crossed without a pitching change.",
        "magnitude": "Hitter wOBA in the first five batters of the third pass averages 20-28 points above the starter's second-pass wOBA; pulling a starter before crossing the inflection preserves 0.3-0.5 expected runs per game versus letting the lineup cycle through.",
        "links": ["times_through_order_penalty_curve", "tto_penalty_by_arsenal_depth", "starter_to_reliever_efficiency_crossover", "pitch_mix_predictability_with_familiarity"],
    },
    {
        "slug": "stuff_command_decay_under_fatigue",
        "title": "Stuff-and-Command Decay Under Fatigue",
        "summary": "Spin rate, movement amplitude, and zone-edge precision decline jointly as pitch-count workload accumulates; the combined whiff-rate and edge-percentage slope within a start captures the dual decay signature.",
        "stat_signature": "Spin rate decline of 40-80 rpm per 40 pitches for breaking balls; edge-rate drop of 2-4 percentage points between inning 1 and inning 6; whiff rate falling 1.5-3 points per 30-pitch tranche above pitch 60.",
        "mechanism": "Muscular fatigue reduces both peak-force generation (spin rate) and proprioceptive precision (location control); as both decay simultaneously, the pitch's effective tunneling deteriorates and hitters can expand their decision window without penalty, compounding the contact-quality risk.",
        "conditions": "Decay most acute for high-spin profiles where the shape advantage is velocity-spin interactive; command-first starters with lower spin baselines show smaller spin-rate losses but equivalent edge-rate deterioration; hot, humid conditions accelerate grip degradation and amplify location scatter.",
        "magnitude": "A joint whiff-rate decline of 3 points paired with edge-rate decline of 3 points corresponds to an expected wOBA-against increase of roughly 0.020-0.030, equivalent to elevating the opposing lineup by one tier for the affected innings.",
        "links": ["velocity_decay_per_inning_slope", "pitch_count_effectiveness_decay", "fastball_usage_diminishing_whiff", "high_leverage_command_compression"],
    },
    {
        "slug": "pitch_mix_predictability_with_familiarity",
        "title": "Pitch-Mix Predictability With Familiarity",
        "summary": "Repeated exposure within a game narrows the hitter's anticipated pitch set; sequencing entropy falls across successive passes, and the wOBA lift attributable to reduced pitch-type uncertainty is detectable by the third lineup cycle.",
        "stat_signature": "Pitch-type entropy (Shannon H across pitch types in a given count) declines by 0.08-0.15 bits from first to third pass; same-count pitch-type predictability rises 8-15 percentage points; wOBA lift from declining sequencing entropy approximately +0.010 to +0.018 per pass.",
        "mechanism": "Starters tend toward count-specific pitch tendencies they execute well under pressure; hitters recognize these tendencies by the third at-bat and shift their anticipation distribution accordingly, shortening reaction time and improving decision quality on the most likely incoming pitch.",
        "conditions": "Effect largest for starters with low count-to-count pitch-mix variance and high same-count repeatability; partially offset by deliberate sequencing variation, but fatigue-induced tunnel narrowing late in outings tends to restore the predictability signal.",
        "magnitude": "Sequencing entropy below 1.2 bits correlates with wOBA-against roughly 25-35 points above league average; starters who increase entropy across passes maintain the first-pass wOBA advantage more than twice as long as those whose entropy declines.",
        "links": ["times_through_order_penalty_curve", "third_time_through_inflection", "tto_penalty_by_arsenal_depth", "fastball_usage_diminishing_whiff"],
    },
    {
        "slug": "starter_to_reliever_efficiency_crossover",
        "title": "Starter-to-Reliever Efficiency Crossover",
        "summary": "The pitch-count and familiarity-adjusted expected wOBA of a fatigued starter eventually exceeds the fresh bullpen average, marking the theoretical optimal pull point; this crossover is measurable at the start level.",
        "stat_signature": "Starter's pitch-count-tranche wOBA projection exceeds bullpen-average wOBA (typically 0.315-0.330) between pitches 75-100 depending on profile; actual pull decisions occurring after crossover correlate with 0.15-0.25 additional expected runs allowed.",
        "mechanism": "A fresh reliever resets velocity, spin, and hitter familiarity simultaneously; the run-expectancy gain from the reset is the difference between the starter's projected wOBA in the next inning and the expected-wOBA from a fresh arm at the same lineup slot.",
        "conditions": "Crossover arrives earlier for shallow-arsenal starters in their third trip through the order; delayed for high-durability arms with four-pitch mix and strong command retention; bullpen depth constraints can shift the decision point regardless of the theoretical crossover.",
        "magnitude": "Starters pulled at or before crossover allow roughly 0.25-0.45 fewer runs per game than those left to cross into the high-wOBA zone; the efficiency gap between optimal and actual pull timing is estimated at 0.2-0.3 runs per start league-wide.",
        "links": ["times_through_order_penalty_curve", "pitch_count_effectiveness_decay", "reliever_multi_inning_decay", "bullpen_usage_fatigue_carryover"],
    },
    {
        "slug": "reliever_multi_inning_decay",
        "title": "Reliever Multi-Inning Effectiveness Decay",
        "summary": "Relievers extended beyond a single inning show measurable wOBA-against increases as the bullpen-role physiology — calibrated for short, maximum-effort bursts — confronts accumulated pitch counts.",
        "stat_signature": "Second-inning wOBA-against for relievers exceeds first-inning by 0.018-0.030; warm-up-adjusted second-inning velocity decline of 0.5-1.0 mph; strikeout rate falling 2-3 percentage points from first to second batter cycle.",
        "mechanism": "One-inning relievers train and physiologically peak for brief maximum-effort bursts; extended use forces them into a starter-like fatigue zone for which their conditioning and pitch mix are not optimized; hitters also gain a within-outing familiarity advantage similar to the starter TTO dynamic, compressed into two innings.",
        "conditions": "Decay sharpest for elite high-effort relievers whose stuff relies heavily on velocity; multi-inning specialists show attenuated decay because their conditioning and pitch design accommodate longer outings; next-day usage is further penalized when a multi-inning outing precedes it.",
        "magnitude": "Multi-inning relievers face roughly 15-25% higher wOBA in their second inning; season ERA for outings exceeding 1.1 innings is typically 0.35-0.55 above single-inning ERA for the same reliever population.",
        "links": ["starter_to_reliever_efficiency_crossover", "bullpen_usage_fatigue_carryover", "high_leverage_command_compression", "rest_days_starter_efficiency_curve"],
    },
    {
        "slug": "rest_days_starter_efficiency_curve",
        "title": "Rest-Days-to-Efficiency Curve",
        "summary": "Starter effectiveness varies nonlinearly with days of rest between starts; wOBA-against and velocity responses are measurable across short-rest (3 days), standard (4-5 days), and extended-rest (8+ days) intervals.",
        "stat_signature": "Short-rest wOBA-against elevated 0.020-0.035 above standard-rest baseline; velocity on 3-day rest reduced 0.4-0.8 mph; extended-rest (8+ days) wOBA 0.015-0.025 above standard as physical sharpness and rhythm erode.",
        "mechanism": "Standard rest allows full physiological recovery and command rhythm maintenance; short rest compounds residual fatigue from the prior outing, compressing the recovery of fast-twitch capacity; extended rest allows physical recovery but disrupts competitive timing, release-point feel, and pitch-shape calibration.",
        "conditions": "Most pronounced for starters with high-effort deliveries and high pitch counts in the prior outing; less pronounced for command-first starters with efficient pitch economies; post-injury return follows a similar extended-rest profile.",
        "magnitude": "Short-rest starters surrender approximately 0.40-0.55 additional runs per start; extended-rest starters (10+ days) allow 0.25-0.40 additional runs; the optimal rest band of 4-6 days minimizes both residual-fatigue and rhythm-disruption costs.",
        "links": ["pitch_count_effectiveness_decay", "velocity_decay_per_inning_slope", "stuff_command_decay_under_fatigue", "reliever_multi_inning_decay"],
    },
    {
        "slug": "plate_appearance_length_workload_burn",
        "title": "Plate-Appearance-Length Workload Burn Curve",
        "summary": "Deep-count plate appearances accelerate effective pitch-count fatigue; each 0.1-pitch-per-plate-appearance increase in opponent approach compresses the starter's innings of effective depth by a measurable fraction.",
        "stat_signature": "Pitches-per-plate-appearance above 4.2 reduces expected effective depth by roughly 0.3-0.5 innings per start; starters facing deep-count lineups exhaust their pitch budget 12-18 pitches sooner than those facing first-pitch-aggressive approaches.",
        "mechanism": "Foul balls, deep counts, and walks each consume pitches without producing outs; higher pitches-per-plate-appearance compresses available outings within the starter's safe pitch budget, forcing earlier exposure to the times-through-the-order penalty or earlier bullpen entry.",
        "conditions": "Impact largest against patient lineups with above-average pitches-seen per plate appearance; amplified when the lineup's patience concentrates in the top third of the order, burning starter depth before the lineup recycles; attenuated when first-pitch-strike rate is very high.",
        "magnitude": "A 0.3-pitch-per-plate-appearance lineup advantage over the starter translates to approximately 10-15 fewer starter pitches available per start, shortening effective outings by 0.5-0.7 innings and raising bullpen dependency proportionally.",
        "links": ["pitch_count_effectiveness_decay", "pitch_efficiency_innings_depth_curve", "hitter_pitch_count_selectivity_payoff", "times_through_order_penalty_curve"],
    },
    {
        "slug": "hitter_pitch_count_selectivity_payoff",
        "title": "Hitter Pitch-Count Selectivity Payoff Curve",
        "summary": "The wOBA return on taking additional pitches is positive early in counts but diminishes as two-strike risk rises; the payoff curve peaks near 3-ball or 2-ball-1-strike counts and inverts when the called-strike risk overtakes the walk-gain benefit.",
        "stat_signature": "Walk-plus-HBP rate peaks at 4-pitch-plus plate appearances; wOBA slope rises from 1-pitch to 4-pitch depth but declines in 5+ pitch, two-strike-heavy territory; called-strike-looking rate above 12% identifies hitters who over-extend the taking strategy past the payoff peak.",
        "mechanism": "Taking pitches forces the pitcher deeper into counts and raises walk probability; but two-strike territory shifts leverage to the pitcher, who can expand the zone and exploit the hitter's obligation to protect; hitters who correctly identify the peak-taking depth and then shift to contact mode capture the maximum wOBA return.",
        "conditions": "Payoff highest against starters with below-average first-pitch-strike rates and high walk tendencies; diminishes against command-first starters who consistently attack early counts; two-strike discipline — contact rate above 68% in 0-2 and 1-2 — determines whether the selectivity strategy converts to actual wOBA gains.",
        "magnitude": "Hitters who work deep counts without excessive two-strike strikeouts post wOBA approximately 0.025-0.040 above equivalent-contact hitters with more aggressive early-count swings; the penalty for over-extending past the payoff peak reduces wOBA by roughly the same margin in the opposite direction.",
        "links": ["plate_appearance_length_workload_burn", "swing_aggression_contact_tradeoff", "pitch_count_effectiveness_decay", "pitch_mix_predictability_with_familiarity"],
    },
    {
        "slug": "swing_aggression_contact_tradeoff",
        "title": "Swing-Aggression Contact Tradeoff Curve",
        "summary": "The efficient frontier between swing rate and contact quality describes a hitter's optimal zone-coverage boundary; expanding beyond it raises chase and whiff rates while diminishing barrel rate, producing a net-negative wOBA effect.",
        "stat_signature": "Chase rate above 32% correlates with wOBA decline of 0.015-0.025 versus same-contact-quality hitters below 28% chase; barrel rate declines 1.5-2.5 points per 5-percentage-point chase-rate increase beyond the individual hitter's optimum.",
        "mechanism": "Pitches outside the optimal swing zone generate inferior contact angles and velocity due to biomechanical constraints; the further the pitch from the center of the swing path, the more the kinetic chain is compromised at contact, reducing exit velocity and launch angle precision.",
        "conditions": "Tradeoff most pronounced against pitchers with strong velocity-break tunneling that extends the perceived strike zone into chase territory; hitters with wider optimal zones (inside-out swing mechanics) tolerate higher chase rates without the same contact-quality penalty.",
        "magnitude": "The marginal barrel-rate cost per additional percentage point of chase rate is approximately 0.4-0.7 percentage points; aggregate wOBA difference between the top and bottom chase-rate quartiles, controlling for contact quality, is roughly 0.030-0.045.",
        "links": ["hitter_pitch_count_selectivity_payoff", "launch_angle_exit_velocity_frontier", "fastball_usage_diminishing_whiff", "stuff_command_decay_under_fatigue"],
    },
    {
        "slug": "launch_angle_exit_velocity_frontier",
        "title": "Launch-Angle Exit-Velocity Frontier",
        "summary": "Expected wOBA on contact is maximized at a launch-angle band of roughly 10-30 degrees; chasing higher elevation costs average exit velocity as the swing path lengthens and the contact point moves deeper, compressing the efficiency frontier.",
        "stat_signature": "Peak expected-wOBA-on-contact at 10-30 degree launch angle; xwOBAcon declines roughly 0.015-0.025 per 10-degree elevation above 35 degrees; average exit velocity drops 1.5-3 mph for balls contacted above 40 degrees due to uppercut path length.",
        "mechanism": "Extreme uppercut swings contact the lower hemisphere of the ball, generating loft at the cost of solid-center contact; the exit-velocity loss from off-center contact reduces expected distance and production more than the elevation gain contributes, producing diminishing xwOBA returns above the optimal band.",
        "conditions": "Frontier shifts upward in hitter-friendly parks where elevated fly balls carry further; wind direction modulates the carry benefit; power-oriented hitters with higher baseline exit velocity tolerate slightly higher optimal launch angles before the tradeoff turns negative.",
        "magnitude": "Hitters outside the 10-30 degree optimal band (below or above) post xwOBAcon approximately 0.020-0.040 below in-band hitters with equivalent contact rates; the elevation zone above 40 degrees corresponds to pop-up territory with xwOBAcon near the league minimum.",
        "links": ["swing_aggression_contact_tradeoff", "hitter_pitch_count_selectivity_payoff", "tto_penalty_by_arsenal_depth", "pitch_mix_predictability_with_familiarity"],
    },
    {
        "slug": "tto_penalty_by_arsenal_depth",
        "title": "Order-Penalty Sensitivity to Arsenal Depth",
        "summary": "The times-through-order wOBA slope steepens sharply for two-pitch starters relative to four-pitch repertoires; arsenal depth is the primary moderator of how fast hitter familiarity compounds the per-pass penalty.",
        "stat_signature": "Two-pitch starters show TTO wOBA slopes of +0.015 to +0.022 per pass; four-pitch starters average +0.007 to +0.012; third-time-through wOBA gap between shallow and deep arsenals approximately 20-30 points.",
        "mechanism": "A four-pitch repertoire expands the pitch-recognition search space for hitters on each at-bat; starters who can sequence new tunneling pairs on repeat showings prevent hitters from narrowing their anticipation distribution as rapidly, sustaining first-pass uncertainty longer into the outing.",
        "conditions": "Effect is largest when the fourth pitch is meaningfully distinct in shape and velocity from the primary two; a four-pitch arsenal with redundant shapes provides limited additional TTO protection; pitch-mix entropy at the count level — not merely pitch count — determines actual sequencing diversity.",
        "magnitude": "Adding a legitimate third pitch reduces the cumulative TTO wOBA penalty by approximately 8-12 points across the full outing; the difference in expected runs conceded over three passes between a two-pitch and four-pitch starter of otherwise equal quality is roughly 0.35-0.55 runs per start.",
        "links": ["times_through_order_penalty_curve", "pitch_mix_predictability_with_familiarity", "third_time_through_inflection", "fastball_usage_diminishing_whiff"],
    },
    {
        "slug": "bullpen_usage_fatigue_carryover",
        "title": "Bullpen Usage Fatigue-Carryover Curve",
        "summary": "Consecutive-day and high-leverage reliever appearances degrade next-outing effectiveness; wOBA-against slopes against prior-day appearances and back-to-back days are measurable and distinct from single-game fatigue.",
        "stat_signature": "One prior-day appearance: wOBA-against elevated 0.010-0.018; two consecutive prior-day appearances: elevated 0.022-0.035; velocity loss on back-to-back days averaging 0.3-0.6 mph; high-leverage-inning carryover adds 0.008-0.015 wOBA independent of raw appearance count.",
        "mechanism": "Explosive muscle-fiber recovery requires 48-72 hours for high-effort relievers; partial recovery after 24 hours preserves gross velocity but degrades fine motor control and spin precision; consecutive high-leverage outings compound central nervous system fatigue beyond what pitch count alone captures.",
        "conditions": "Most severe for high-effort, high-velocity relievers with limited pitch repertoire; attenuated for command-first relievers who operate below maximum physical effort; warm-weather scheduling and travel fatigue interact additively with the usage carryover.",
        "magnitude": "Relievers used three of four prior days show ERA roughly 1.2-1.8 above their rested baseline; the carryover wOBA penalty decays with each additional rest day at approximately 0.006-0.010 per day, returning to baseline near day 3.",
        "links": ["reliever_multi_inning_decay", "starter_to_reliever_efficiency_crossover", "high_leverage_command_compression", "rest_days_starter_efficiency_curve"],
    },
    {
        "slug": "high_leverage_command_compression",
        "title": "High-Leverage Command-Compression Curve",
        "summary": "Rising leverage and runners-on cognitive load compress command precision; zone-edge percentage and walk rate respond adversely as leverage index climbs, revealing a measurable performance decay beyond what raw pitch-count fatigue explains.",
        "stat_signature": "Edge-rate decline of 1.5-3 percentage points at leverage index above 2.0 versus below 1.0; walk rate elevation of 1-2 percentage points in leverage-above-2 states; two-strike strikeout rate falling 1.5-3 points under maximum-leverage conditions for non-elite closers.",
        "mechanism": "High-leverage situations activate elevated physiological arousal that narrows attentional focus and degrades fine motor precision for pitchers who have not fully automated their mechanics; grip tension increases and arm-action timing shortens, displacing pitches from the edge toward the center of the zone or off the plate entirely.",
        "conditions": "Effect most pronounced for pitchers with fewer than 200 career high-leverage innings who have not fully habituated their arousal-control routines; attenuated for closers with high-leverage experience; interaction with runners-on adds visual-field distraction that amplifies the command compression.",
        "magnitude": "Edge-rate compression of 2-3 percentage points corresponds to roughly a 0.015-0.025 wOBA-against increase per inning under high leverage; walk-rate elevation of 1.5 percentage points adds approximately 0.10-0.15 expected runs per nine innings to the leverage-adjusted ERA.",
        "links": ["stuff_command_decay_under_fatigue", "bullpen_usage_fatigue_carryover", "pitch_count_effectiveness_decay", "reliever_multi_inning_decay"],
    },
    {
        "slug": "pitch_efficiency_innings_depth_curve",
        "title": "Pitch-Efficiency-to-Innings-Depth Curve",
        "summary": "Pitch economy directly converts to start length; the pitches-per-out efficiency tier of a starter predicts expected innings completed within a pitch budget, with first-pitch-strike rate as the primary driver of the slope.",
        "stat_signature": "Pitches-per-out below 3.85 enables 6+ expected innings within an 85-pitch budget; each 0.1-unit improvement in pitches-per-out corresponds to roughly 0.3 additional expected innings; first-pitch-strike rate above 63% reduces pitches-per-plate-appearance by 0.25-0.35.",
        "mechanism": "First-pitch strikes and early-count contact eliminate multi-pitch sequences; when the lineup is retired in three pitches per batter, the starter's 90-pitch budget extends to 30 batters (roughly 7-8 innings) rather than the 22-24 batters implied by 4-pitch-per-plate-appearance inefficiency.",
        "conditions": "Efficiency gains are most durable against aggressive lineups that swing early in counts; erode against disciplined lineups that consistently work deep; the efficiency-to-depth conversion is attenuated late in starts when TTO familiarity degrades first-pitch-strike execution.",
        "magnitude": "Top-quartile pitch-efficiency starters complete starts averaging 6.4 innings on 86 pitches versus bottom-quartile at 5.1 innings on 91 pitches; the 1.3-inning difference displaces approximately 12-15 bullpen appearances per 30-start season.",
        "links": ["plate_appearance_length_workload_burn", "pitch_count_effectiveness_decay", "times_through_order_penalty_curve", "starter_to_reliever_efficiency_crossover"],
    },
    {
        "slug": "fastball_usage_diminishing_whiff",
        "title": "Fastball-Usage Diminishing-Whiff Curve",
        "summary": "Whiff and chase returns on a primary pitch fall as its usage share rises within a game; hitter anticipation concentrates on the heavily-used offering, reducing the pitch's deception value per additional throw.",
        "stat_signature": "Fastball whiff rate declines approximately 0.4-0.8 percentage points per 10-point increase in usage share above 55%; same-pitch whiff rate gap between first-time-through and third-time-through at equal usage share is 2-4 percentage points.",
        "mechanism": "Hitters allocate cognitive preparation resources toward the pitch they are most likely to see; at high usage shares the pitch becomes the default anticipation target, shortening reaction windows and converting borderline-zone offerings from swing-and-miss candidates to contacted pitches.",
        "conditions": "Diminishing returns onset sharpest for pitchers with a primary fastball and limited breaking-ball quality; offset when secondary pitches effectively punish over-anticipation; velocity-at-the-top-of-zone profiles sustain higher usage shares before the diminishing-whiff threshold.",
        "magnitude": "Above 65% fastball usage in a single start, expected whiff rate is roughly 1.5-3 percentage points below the starter's full-season fastball whiff rate; the usage-saturation cost in wOBA-against corresponds to approximately 0.012-0.020 per inning of over-exposure.",
        "links": ["pitch_mix_predictability_with_familiarity", "stuff_command_decay_under_fatigue", "swing_aggression_contact_tradeoff", "tto_penalty_by_arsenal_depth"],
    },
]
