"""MLB Environment concepts — person-free, descriptive intelligence nodes."""
from __future__ import annotations

SPORT = "MLB"
FAMILY = "Environment"

CONCEPTS: list[dict] = [
    {
        "slug": "park_outfield_dimensions",
        "title": "Outfield Fence Distance and Geometry",
        "summary": "Asymmetric fence distances and irregular angles shape extra-base yield by creating spray-direction-dependent carry requirements; a ball landing in a deep power alley requires 20-plus feet more carry than the same exit velocity directed toward a short corner.",
        "stat_signature": "Home-run park factor split by pull-versus-oppo: up to 15–25 point divergence at asymmetric venues. Batted-ball distance-to-wall residuals on flies 380-plus feet: range from -12 feet (homer suppressed) to +18 feet (homer enabled) depending on direction.",
        "mechanism": "Fence geometry determines the minimum batted-ball distance required for a home run in each spray direction; carry surplus over the fence threshold converts to home run, while a deficit converts a well-struck fly into a wall-ball double or out, directly altering run-expectancy on identical contact profiles.",
        "conditions": "Effect strongest for pull-heavy contact profiles facing parks with shallow corners but deep alleys. Spray-neutral hitters distribute across angles and see closer-to-park-average outcomes than pull-dominant types.",
        "magnitude": "HR rate differential between most favorable and least favorable spray-direction pairing at the same park: roughly 18–30 percent; doubles rate inversely adjusts as wall-ball outcomes replace home runs in deep dimensions.",
        "links": ["outfield_wall_height", "fair_territory_gap_alley", "park_handedness_split", "altitude_air_density"],
    },
    {
        "slug": "outfield_wall_height",
        "title": "Outfield Wall Height Profile",
        "summary": "Tall fences convert well-struck fly balls into doubles or wall-caroms while short fences allow the same trajectory to clear for home runs; the doubles-to-homer conversion ratio on balls in the wall-contact distance band is park-specific and stable.",
        "stat_signature": "Doubles-to-homer conversion ratio on balls in the 330-to-380-foot contact band: ranges from roughly 3.5:1 at the tallest-fence parks to roughly 1.2:1 at low-fence venues. HR suppression at the tallest-fence park: roughly 15–22 percent below equivalent-dimension low-fence parks.",
        "mechanism": "A ball's trajectory at the fence line determines clearance; for a given exit velocity and launch angle, a fence ten feet taller requires roughly 8–12 additional feet of carry distance, shifting a meaningful fraction of the doubled-zone contact below the threshold for a home run while still producing in-play doubles.",
        "conditions": "Wall-height effect interacts with launch-angle distribution; high-launch-angle contact is most sensitive to wall height because the ball arrives at the wall near its apex. Ground-ball-heavy profiles see minimal wall-height modulation.",
        "magnitude": "Roughly 15–22 percent HR suppression at maximum-height venues versus minimum-height parks for matched-dimension distances; doubles rate rises correspondingly by roughly 8–14 percent.",
        "links": ["park_outfield_dimensions", "fair_territory_gap_alley", "park_handedness_split"],
    },
    {
        "slug": "altitude_air_density",
        "title": "Altitude and Reduced Air Density",
        "summary": "Thinner air at high-elevation venues reduces aerodynamic drag on batted balls, extending fly-ball carry by a measurable distance per 1000 feet of elevation; breaking pitches simultaneously lose movement because the same thin air provides less resistance for the Magnus force to act upon.",
        "stat_signature": "Batted-ball carry gain at 5000-foot elevation versus sea level: roughly 5–8 percent on fly balls with launch angles above 25 degrees, translating to roughly 15–25 feet of additional distance. Breaking-ball vertical drop reduction at elevation: roughly 3–5 inches on 12-to-6 curveballs.",
        "mechanism": "Drag force is proportional to air density; at reduced density the decelerating force on a batted ball is weaker, extending peak carry distance. For spinning pitches the Magnus lift force that generates movement also scales with density, so both horizontal and vertical break diminish proportionally.",
        "conditions": "Effect is constant across games at the same park but amplifies for power-heavy lineups and high-spin breaking-ball pitchers visiting elevation venues; fastball-dominant arms are less affected because their movement relies less on Magnus differential.",
        "magnitude": "HR park factor at high-elevation venues typically 110–122 versus 95–105 at sea-level parks; breaking-ball whiff-rate decline for visiting pitchers at elevation roughly 1.5–2.5 percentage points.",
        "links": ["altitude_humidor_offset", "altitude_breaking_ball_flattening", "park_outfield_dimensions", "air_temperature_carry"],
    },
    {
        "slug": "air_temperature_carry",
        "title": "Air Temperature and Ball Carry",
        "summary": "Warmer air is less dense, reducing aerodynamic drag on fly balls in a manner analogous to altitude; a 20-degree Fahrenheit increase in game-time temperature corresponds to measurable home-run-per-fly-ball rate improvement at the same park.",
        "stat_signature": "HR-per-fly-ball elasticity to temperature (controlling for launch angle and exit velocity): roughly +0.8–1.2 percent per 10-degree Fahrenheit increase. Games above 85 F: HR rate roughly 8–12 percent above same-park games below 55 F.",
        "mechanism": "Air density decreases approximately 0.35 percent per degree Fahrenheit of temperature increase at constant pressure; the resulting drag reduction extends carry in a manner that compounds with altitude. Ball-elasticity also rises marginally in warmer conditions, contributing a secondary exit-velocity boost.",
        "conditions": "Largest effect in midsummer afternoon games at open-air northern parks where temperature spans the widest seasonal range. Retractable-roof venues with climate control show negligible temperature-driven carry variation.",
        "magnitude": "Full-season temperature range of 30-plus degrees maps to roughly 8–12 percent HR rate divergence at the same park; roughly 0.10–0.18 runs per game in expected scoring tied to temperature-driven carry differences.",
        "links": ["altitude_air_density", "wind_vector_field", "retractable_roof_state", "humidity_ball_drag"],
    },
    {
        "slug": "humidity_ball_drag",
        "title": "Humidity and Aerodynamic Drag",
        "summary": "High ambient humidity reduces dry-air density slightly, and wet-stored baseballs absorb moisture that increases mass and changes seam-drag behavior; both effects influence carry and spin-decay at coastal and humid-climate parks.",
        "stat_signature": "Distance residuals at high-humidity parks (relative humidity above 70 percent) versus arid parks: roughly -2 to -5 feet on matched-launch-angle fly balls when accounting for temperature. Spin-decay differential: breaking-ball spin rate retention roughly 1–2 percent lower in high-humidity conditions.",
        "mechanism": "Contrary to intuition, humid air is marginally less dense than dry air at the same temperature because water vapor is lighter than nitrogen or oxygen; however, a moisture-absorbed baseball is heavier and has altered seam texture, slightly increasing drag and reducing coefficient of restitution, partially offsetting carry gains.",
        "conditions": "Most relevant at coastal and Gulf-region stadiums, especially for evening games when dew point approaches the air temperature. Ball-storage humidors partially decouple on-field humidity from ball characteristics.",
        "magnitude": "Net humidity effect on carry is small — roughly 1–4 feet at typical relative-humidity ranges — but the spin-decay effect on breaking-ball grip is more operationally significant, measurably raising walks and lowering whiff rates in very humid conditions.",
        "links": ["air_temperature_carry", "marine_layer_density", "altitude_humidor_offset", "evening_dew_late_innings"],
    },
    {
        "slug": "wind_vector_field",
        "title": "Stadium Wind Vector Field",
        "summary": "Prevailing and gusting wind direction relative to the stadium's foul lines determines whether fly balls receive an aerodynamic boost or penalty; out-to-center wind adds carry to pull and center flies while cross-wind components differentially affect left- and right-handed batters.",
        "stat_signature": "Wind blowing out at 15-plus mph toward center: HR rate roughly 12–18 percent above calm baseline. Wind blowing in from center at 15-plus mph: HR rate roughly 10–15 percent below baseline. Cross-wind at 15-plus mph: pull-direction HR rate diverges from oppo by roughly 8–12 percent.",
        "mechanism": "Tailwind adds carry to a fly ball's vector by reducing the net drag experienced along the ball's trajectory; headwind does the opposite. Cross-winds deflect trajectories, advantaging batted balls moving with the wind component and suppressing those moving against it, creating spray-direction-dependent park-factor asymmetry within a single game.",
        "conditions": "Open-air parks with exposed upper decks and downtown corridors experience the highest wind speed variability. Stadium orientation determines whether standard prevailing winds from the southwest or ocean breezes align with or against the center-field direction.",
        "magnitude": "HR swing between a strong-out-wind game and a strong-in-wind game at the same open-air park: roughly 25–35 percent; total-run differential of roughly 0.4–0.7 runs per game between extreme-wind conditions.",
        "links": ["air_temperature_carry", "park_outfield_dimensions", "retractable_roof_state", "altitude_air_density"],
    },
    {
        "slug": "foul_territory_size",
        "title": "Foul Territory Area",
        "summary": "Expansive foul ground converts pop-ups and foul flairs into outs that would be fan-intercepted or seat-landing at cramped parks; each additional out-generating foul ball effectively extends the pitcher's leash and suppresses BA.",
        "stat_signature": "Foul-out conversion rate at large-foul-territory parks: roughly 1.8–2.4 per nine innings versus 0.8–1.2 at minimal-foul-territory parks. BA suppression tied to foul territory: roughly 0.005–0.012 across matched contact profiles. Plate-appearance extension rate roughly 4–7 percent lower at large-foul-ground venues.",
        "mechanism": "A pop-up in foul territory is an automatic out at spacious parks; at cramped parks the same batted ball lands in the seats, resetting the at-bat at the prior count. The additional out-generating event shifts the per-at-bat distribution toward fewer pitches and more early-contact outs.",
        "conditions": "Effect most pronounced for high-popup hitters with weak-contact tendencies; negligible for groundball-heavy or pull-dominant lineups whose foul balls travel into the seats regardless of territory dimensions.",
        "magnitude": "Large-foul-territory parks show BA 5–12 points below what identical launch conditions produce at small-territory venues; roughly 0.15–0.25 additional pitcher outs per game from foul catches.",
        "links": ["park_outfield_dimensions", "batters_eye_backdrop", "playing_surface_turf_grass"],
    },
    {
        "slug": "retractable_roof_state",
        "title": "Retractable Roof Open or Closed State",
        "summary": "A closed roof neutralizes wind, temperature, and humidity variation, transforming an outdoor stadium into a controlled dome environment; the within-venue HR and carry differential between roof-open and roof-closed games quantifies the environmental neutralization.",
        "stat_signature": "Within-venue HR rate differential between roof-open and roof-closed games: roughly 8–18 percent, conditional on wind speed at time of opening. Run-scoring standard deviation across games drops roughly 10–15 percent in the roof-closed condition at the same park.",
        "mechanism": "The roof eliminates wind-vector carry effects, temperature-driven density variation, and late-inning dew; the climate-controlled interior maintains a near-constant environment equivalent to a moderate-temperature dry day, collapsing game-to-game carry variance to the ball-storage baseline.",
        "conditions": "Roof state is manager-decided pre-game based on temperature and precipitation; game-time roof changes are rare. Neutral-wind, temperate-day conditions at roof-optional parks produce near-equivalent outcomes for open and closed states.",
        "magnitude": "At venues where roof-open games include high-wind events, the open-minus-closed HR differential can reach 18–22 percent on extreme wind days; under moderate conditions the differential narrows to roughly 3–6 percent.",
        "links": ["wind_vector_field", "air_temperature_carry", "humidity_ball_drag", "marine_layer_density"],
    },
    {
        "slug": "batters_eye_backdrop",
        "title": "Batter's Eye and Hitting Backdrop",
        "summary": "The center-field hitting backdrop contrast — typically a batter's eye — determines how quickly a hitter can identify pitch type and spin at release; poor contrast or sun-exposed backdrops raise swing-and-miss on hard fastballs.",
        "stat_signature": "Swing-and-miss rate residual at poor-backdrop parks versus neutral backdrop controlling for pitcher arsenal: roughly +1.0–1.8 percentage points. Chase-rate increase at direct-sun afternoon start time: roughly 0.8–1.4 percentage points.",
        "mechanism": "Pitch identification begins at the pitcher's release point; a high-contrast matte backdrop allows the batter to isolate the white ball immediately, gaining roughly 15–25 milliseconds of processing time. Poor contrast or sun glare obscures the initial trajectory vector, delaying identification and compressing reaction time toward the plate.",
        "conditions": "Worst conditions occur at afternoon games with direct western sun illuminating the center-field backdrop; open upper-deck stadiums with light-colored seats directly behind the pitcher see the most interference.",
        "magnitude": "Swing-and-miss premium at the most disrupted backdrop conditions: roughly 1.0–2.0 percentage points across all pitch types; effect on curveballs and changeups — whose spin patterns are most backdrop-dependent for identification — may reach 2.5–3.5 percentage points.",
        "links": ["sun_shadow_progression", "foul_territory_size", "park_outfield_dimensions"],
    },
    {
        "slug": "sun_shadow_progression",
        "title": "Sun Angle and Infield Shadow Line",
        "summary": "In afternoon and early-evening games, the shadow line between the lit mound and the darkened home-plate area moves across the plate as the sun angle progresses; pitches traveling from sun to shadow create a disorienting contrast shift that measurably elevates strikeout rates.",
        "stat_signature": "Strikeout rate by inning band when shadow line crosses the plate region (typically innings 3–6 in afternoon games): roughly +1.2–2.0 K/9 above that game's other-inning baseline. Shadow-crossing windows correlate with whiff-rate spikes of 2–3 percentage points on four-seam fastballs.",
        "mechanism": "A ball released from a brightly lit pitching rubber into a shadow-covered plate zone requires the hitter's visual system to adapt from high-luminance to low-luminance mid-trajectory; the adaptation lag reduces contrast sensitivity precisely when the ball approaches the decision zone, compressing swing timing.",
        "conditions": "Effect is tightest in open-air stadiums oriented with the sun behind the pitcher during mid-afternoon starts; retractable-roof venues and fully domed stadiums are unaffected. Strongest in spring and fall when sun angles are lower.",
        "magnitude": "Shadow-zone innings show strikeout rates roughly 12–18 percent above that game's non-shadow baseline; effect dissipates once the entire plate is fully in shadow and hitter eyes adapt to uniform lighting.",
        "links": ["batters_eye_backdrop", "retractable_roof_state", "day_night_split_environment"],
    },
    {
        "slug": "marine_layer_density",
        "title": "Coastal Marine-Layer Heaviness",
        "summary": "Evening coastal marine layer brings dense, cool, moisture-laden air that suppresses fly-ball carry more than standard air-temperature calculations would predict; night games at coastal Pacific parks show systematic HR suppression relative to afternoon games at the same venue.",
        "stat_signature": "Night-game HR suppression residual at marine-layer-affected parks versus same-park afternoon games (controlling for temperature): roughly 8–14 percent. Marine layer index correlates with game-time carry residuals at r roughly 0.35–0.45 across multi-season coastal-park samples.",
        "mechanism": "Marine air is denser than dry air at equivalent temperature due to its higher moisture content and cooler sea-breeze origin; the additional density increases aerodynamic drag on batted balls. Marine layer typically establishes itself between the fourth and seventh inning of evening games, creating a within-game carry transition.",
        "conditions": "Concentrated at Pacific Coast stadiums in a north-south corridor from roughly May through September when onshore flow is strongest; minimally relevant for landlocked or Atlantic-coast parks.",
        "magnitude": "HR rate in late-inning marine-layer-affected states roughly 8–14 percent below same-park early-inning rates; total scoring suppression roughly 0.15–0.30 runs per game under strong marine conditions.",
        "links": ["humidity_ball_drag", "retractable_roof_state", "evening_dew_late_innings", "air_temperature_carry"],
    },
    {
        "slug": "playing_surface_turf_grass",
        "title": "Infield Surface Type: Turf versus Natural Grass",
        "summary": "Artificial turf accelerates ground balls through the infield with more uniform true-hops compared with natural grass, raising infield-hit probability and suppressing slow-roller outs; BABIP on grounders diverges systematically by surface.",
        "stat_signature": "Infield-hit rate on ground balls: turf parks roughly 10–12 percent versus natural grass roughly 8–9 percent. Ground-ball BABIP on turf: roughly 0.240–0.255 versus grass roughly 0.225–0.240. Fielding-error rate on turf: roughly 15–20 percent below grass-equivalent surface.",
        "mechanism": "Artificial turf provides a consistent, low-friction surface with predictable ball-hop geometry; natural grass introduces variability through grass height, soil moisture, and seam irregularities that slow grounders and create irregular hops. The speed advantage on turf is largest on weakly struck slow-rollers and choppers.",
        "conditions": "Speed-to-first advantages are most pronounced for left-handed batters with above-average sprint speed; for pull-heavy grounders the effect is smaller because third baseman positioning absorbs some of the speed advantage.",
        "magnitude": "BABIP differential of roughly 0.015–0.020 on grounders between turf and grass; infield-hit rate roughly 1.5–3.0 percentage points higher on turf, contributing roughly 0.08–0.15 additional runs per game through the ground-ball channel.",
        "links": ["infield_dirt_firmness", "outfield_grass_speed", "foul_territory_size"],
    },
    {
        "slug": "altitude_humidor_offset",
        "title": "Stored-Ball Humidor Conditioning",
        "summary": "Climate-controlled ball storage at precise humidity targets standardizes ball coefficient of restitution by preventing the moisture loss that tightens seams and reduces drag, measurably suppressing exit-velocity-to-distance variance at high-elevation parks.",
        "stat_signature": "Post-humidor HR reduction at the original high-elevation adopting park: roughly 25–30 percent in the first full season after introduction. Distance variance on matched exit-velocity-and-launch-angle fly balls: roughly 10–15 percent lower in humidor conditions.",
        "mechanism": "Dry baseballs at high altitude have lower moisture content, making the core harder and the surface more slippery; the harder core transfers energy more efficiently, boosting effective exit velocity while the reduced seam drag allows more carry. Humidor storage returns moisture to specification, softening the core and restoring standard seam-drag properties.",
        "conditions": "Relevant only at high-elevation venues where balls dry significantly in the low-humidity environment; sea-level parks experience negligible moisture loss in storage and show no measurable humidor offset. Effect is largest in arid-climate cities.",
        "magnitude": "Humidor introduction reduces effective HR park factor from roughly 115–120 to roughly 103–108 at the most prominent high-altitude adopting park; carry variance compression narrows the distribution of distance outcomes, reducing both very long home runs and the random absence of expected ones.",
        "links": ["altitude_air_density", "humidity_ball_drag", "altitude_breaking_ball_flattening"],
    },
    {
        "slug": "park_handedness_split",
        "title": "Park Factor by Batter Handedness",
        "summary": "Asymmetric park dimensions create different pull-versus-opposite-field distances for left-handed and right-handed batters; the resulting park factor split means a park can simultaneously be a HR enhancer for one batting side and neutral or suppressive for the other.",
        "stat_signature": "Left-hand-batter HR park factor at the most asymmetric venues: up to 15–20 points higher than right-hand-batter HR park factor. Venues with short left-field fences show LHB HR factor roughly 115–125 and RHB HR factor roughly 95–105.",
        "mechanism": "Left-handed batters pull to right field and push oppo to left field; a short right-field fence lowers the carry requirement for pull home runs. The same short-right-field geometry presents the deepest part of the park to a right-handed hitter's pull side, suppressing their HR rate while simultaneously boosting left-handed batters' pull power.",
        "conditions": "Effect strongest for pull-dominant batters with launch angles consistently above 25 degrees; spray-neutral hitters who distribute contact across the park see less exaggerated handedness-split park factors.",
        "magnitude": "Park-factor differential between left-handed and right-handed batters at the most asymmetric venues: roughly 15–25 points on a 100-neutral scale; roster-construction decisions around platoon-advantage deployment show measurable exploitation of these splits.",
        "links": ["park_outfield_dimensions", "outfield_wall_height", "fair_territory_gap_alley", "altitude_air_density"],
    },
    {
        "slug": "fair_territory_gap_alley",
        "title": "Power-Alley Gap Depth",
        "summary": "Deep left-center and right-center gap dimensions govern the triples and extra-base-hit rate on well-struck fly balls that carry beyond the infield but fall short of home-run distance; the gap-double rate and triples rate are strongly inversely correlated with park dimensions in these zones.",
        "stat_signature": "Triples rate at deep-gap parks (left-center-to-right-center average above 395 feet): roughly 0.55–0.70 triples per 100 plate appearances versus 0.25–0.40 at shallow-gap parks. Gap-double residuals above a neutral-dimension baseline: roughly +12–18 percent at deep-alley parks.",
        "mechanism": "A batted ball hit to the gap at 390-plus feet of carry that fails to clear the fence must be run down by an outfielder starting from a positioning centered on the fence; greater distance to the wall gives the batter more running time and the outfielder a longer chase path, converting the same contact into a triple rather than a double.",
        "conditions": "Effect largest for fast runners and hitters with power-to-gap contact tendencies (high line-drive and medium-launch-angle fly-ball rates); elevated by slow outfield grass that allows the ball to roll farther before fielder recovery.",
        "magnitude": "Triples-per-game rate at deep-gap parks roughly 50–80 percent above shallow-gap venues; gap-double surplus roughly 0.10–0.18 additional doubles per game relative to a neutral-dimension baseline.",
        "links": ["park_outfield_dimensions", "outfield_grass_speed", "park_handedness_split"],
    },
    {
        "slug": "altitude_breaking_ball_flattening",
        "title": "Thin-Air Breaking-Ball Flattening",
        "summary": "Reduced air density at high-elevation venues cuts both horizontal and vertical break on breaking pitches by reducing the Magnus force acting on the spinning ball; sliders and curveballs lose measurable movement inches and the resulting whiff-rate decline is consistent across pitcher profiles.",
        "stat_signature": "Vertical break reduction on 12-to-6 curveballs at 5000-foot elevation versus sea level: roughly 3–5 inches. Horizontal sweep reduction on sliders: roughly 1.5–3.0 inches. Whiff-rate decline for breaking-ball specialists visiting high-elevation parks: roughly 1.5–2.5 percentage points.",
        "mechanism": "Breaking-ball movement is generated by the Magnus effect: a spinning ball in air experiences a perpendicular lift proportional to air density, spin rate, and velocity. At reduced density, this perpendicular force is weaker in proportion to density change, directly reducing induced movement and flattening trajectories that hitters calibrate against sea-level norms.",
        "conditions": "Strongest for pitchers with break-dependent arsenals — sliders with high sweep, curveballs with high induced-vertical-break — who travel to the highest-elevation parks. Fastball-dominant arms with modest breaking-ball usage show smaller whiff-rate penalties.",
        "magnitude": "Break reduction of 3–5 inches on curveballs corresponds to roughly 1.5–2.5 percentage-point whiff-rate decline; across a full start this can translate to roughly 0.3–0.5 additional strikeout-opportunities lost relative to a sea-level outing.",
        "links": ["altitude_air_density", "altitude_humidor_offset", "wind_vector_field"],
    },
    {
        "slug": "infield_dirt_firmness",
        "title": "Infield Dirt and Grass-Length Conditioning",
        "summary": "Groundskeeping decisions on infield soil firmness, grass height, and mound-area clay composition tune ground-ball speed and bounce behavior; home groundskeeping crews systematically adjust these parameters to advantage the home roster's contact profile.",
        "stat_signature": "Bunt-success rate residual tied to infield firmness tier: roughly 4–7 percentage points between the softest (slow-ball) and firmest (fast-ball) conditioning regimes. Slow-roller-out rate on infield grounders: roughly 15–20 percent higher on firm surfaces versus soft.",
        "mechanism": "A firm, closely mowed infield transfers momentum from the ball to the surface efficiently, accelerating grounders through the infield and reducing the fielder's reaction time for plays at first. Soft or long-grass surfaces absorb energy, slowing ground balls and extending reaction time — advantaging slow batters or bunters on the home team.",
        "conditions": "Effect most pronounced for infield grounders in the shallow zone (speed-of-grass zone from the mound to first); bunt and chop strategies that rely on soft landings are most sensitive to firmness variation.",
        "magnitude": "Home-advantage firmness tuning contributes roughly 0.05–0.12 additional wins per full season through the infield-contact channel; bunt-success rate differential between extreme conditioning regimes roughly 5–8 percentage points.",
        "links": ["playing_surface_turf_grass", "mound_height_firmness", "outfield_grass_speed"],
    },
    {
        "slug": "evening_dew_late_innings",
        "title": "Late-Inning Dew and Ball Slickening",
        "summary": "Settling evening dew in late innings coats the ball and grass surface with moisture, reducing pitcher grip and slickening the outfield; the operational result is a measurable rise in walk rate and bobble-driven infield hits in innings where dew crosses a threshold.",
        "stat_signature": "Walk rate in innings 7-plus at open-air dew-susceptible parks on high-dew-point nights: roughly +0.5–1.0 BB/9 above game-average innings-1-through-6 rate. Infield bobble-driven error rate in late-dew innings: roughly 15–25 percent above early-inning baseline.",
        "mechanism": "Dew depositing on the ball surface reduces the pitcher's fingertip friction against the seams, compressing grip quality and reducing spin-rate control on secondary pitches; slippery grass also slows outfielder deceleration and changes ball-roll dynamics on gappers, contributing to late-inning positioning errors.",
        "conditions": "Strongest on clear, high-dew-point evenings (dew point above 65 F) with minimal wind to dry the surface; worst after the seventh inning in coastal stadiums during late summer when temperatures drop sharply after sunset.",
        "magnitude": "Late-inning dew-driven walk rate premium of roughly 0.5–1.0 per nine innings; bobble and handling errors rise roughly 15–25 percent in affected innings, translating to roughly 0.08–0.15 additional unearned-run-enabling events per dew-affected game.",
        "links": ["marine_layer_density", "humidity_ball_drag", "rain_field_wetness"],
    },
    {
        "slug": "rain_field_wetness",
        "title": "Precipitation and Field Wetness",
        "summary": "Damp turf and a wet ball slow batted-ball roll, reduce pitch grip and spin consistency, and raise fielding-error probability; the interaction of pre-delay conditions and post-delay pitching changes creates a run-environment shift distinct from the precipitation itself.",
        "stat_signature": "Ground-ball-hold rate (out converted on infield grounder) in wet-field conditions: roughly 4–7 percent higher than dry-field equivalent due to slower rolling and more favorable fielder positioning time. Fielding-error rate in wet conditions: roughly 20–30 percent above dry-game baseline. Pitch-spin-rate loss on wet balls: roughly 1.5–3.0 percent.",
        "mechanism": "Wet grass reduces the friction coefficient between ball and ground, slowing grounders and creating skipping-hop irregularities that disrupt standard fielding mechanics. A wet baseball has a moisture film that reduces seam-finger contact area for pitchers, compressing release-point friction and reducing spin-rate consistency on breaking pitches.",
        "conditions": "Most impactful in light rain or post-delay resumptions where the game continues on a damp surface without full groundskeeping restoration; full rain delays with tarp coverage mitigate surface effects upon resumption.",
        "magnitude": "Error rate rise of 20–30 percent in wet conditions; ground-ball BABIP drops slightly (slower rollers create outs) but error-induced base-reaching offsets this, producing net neutral-to-slightly-elevated run environment; pitch spin-rate loss of 1.5–3.0 percent degrades breaking-ball wOBA differential roughly 0.010–0.018.",
        "links": ["evening_dew_late_innings", "playing_surface_turf_grass", "infield_dirt_firmness"],
    },
]
