"""Environment Soccer concept nodes — person-free, calibration-only intelligence."""
from __future__ import annotations

SPORT = "Soccer"
FAMILY = "Environment"

CONCEPTS: list[dict] = [
    {
        "slug": "pitch_dimensions_area",
        "title": "Pitch Length and Width Dimensions",
        "summary": "Legal pitch-size variation (100-130 × 50-100 yards) compresses or expands available space, altering possession-sequence length, pressing-trigger distance, and open-play shot volume in measurable ways.",
        "stat_signature": "A 10-yard increase in pitch length correlates with a 6-9% rise in average-possession-sequence duration; wider pitches (>74 yards) see 15-20% more wide-zone ball-receipts and 8-12% more crosses per match; smaller grounds suppress high-press PPDA uplift by 10-15%.",
        "mechanism": "Greater area stretches defensive compactness, forcing longer recovery distances that degrade press intensity; narrower pitches concentrate play centrally, reducing transition-run space and favouring physical compact-block systems.",
        "conditions": "Most pronounced for pressing sides that calibrate trigger distances to a standard pitch; compact-block sides benefit from narrower grounds because their reduced-space advantage increases; crossing-reliant attacks gain disproportionately on wide pitches.",
        "magnitude": "Crossing attempts rise roughly 15-20% on widest-third pitches; pressing-success rate falls 8-12% on the largest pitches as recovery distances exceed physiological thresholds.",
        "links": ["pitch_size_pressing_fit", "stadium_tightness_touchline", "pitch_surface_uniformity", "pitch_crown_drainage"],
    },
    {
        "slug": "playing_surface_type",
        "title": "Natural, Hybrid, or Artificial Surface",
        "summary": "Surface construction — natural grass, hybrid fibre-reinforced turf, or synthetic third-generation artificial — produces consistent residuals in pass-completion, ground-duel-success, and injury-rate indicators that persist after controlling for squad quality.",
        "stat_signature": "Pass-completion on third-generation artificial is 1.5-2.5 percentage points higher than on natural grass in wet conditions; ground-duel-success falls 4-7% on synthetic due to traction asymmetries; lower-limb non-contact injury incidence is 20-30% elevated on artificial across epidemiological cohorts.",
        "mechanism": "Synthetic fibres provide uniform traction independent of moisture but differ in hardness and ball-rebound angle, producing faster, truer roll; the reduced energy absorption amplifies joint-loading and the risk of traction-related muscle strains.",
        "conditions": "Residuals largest in conditions where natural-grass quality degrades — winter months, heavy rainfall, end-of-season wear; adaption advantage accumulates for home sides playing the majority of matches on the same surface.",
        "magnitude": "Visiting sides on unfamiliar synthetic surfaces show pass-completion residuals of –1 to –2 percentage points and ground-duel-success residuals of –3 to –5 percentage points versus their season average.",
        "links": ["grass_length_watering", "rain_pitch_wetness", "frozen_hard_surface", "pitch_surface_uniformity"],
    },
    {
        "slug": "grass_length_watering",
        "title": "Grass Length and Pre-Match Watering",
        "summary": "Groundskeeping decisions on cut height and pre-match irrigation systematically shift ball-roll speed, bounce height, and first-touch-retention rates, with short-cut watered surfaces favouring direct through-ball styles and longer growth favouring physical press-and-hold.",
        "stat_signature": "Watered short-cut surfaces increase through-ball-completion rates by 8-12%; first-touch-retention under pressure improves 5-8% on faster surfaces; long-grass conditions reduce average ball-travel speed measurably and add 10-15% to duel-contact time.",
        "mechanism": "Water lubrication on short-cut grass lowers rolling resistance, allowing the ball to continue through defensive lines on first-time passes; longer grass absorbs kinetic energy on bounce, slowing the ball to a stop and rewarding a physical hold-up style.",
        "conditions": "Deliberate groundskeeping manipulation most impactful when the home style is heavily possession-oriented and exploits fast roll; heavy pre-match watering on already-moist surfaces can create pooling that degrades both teams equally.",
        "magnitude": "Through-ball attempts rise 10-15% and completion rises 6-10% on maximally watered short-cut surfaces relative to dry long-cut baselines; long-ball attempts increase 12-18% on slow heavy surfaces.",
        "links": ["playing_surface_type", "rain_pitch_wetness", "pitch_crown_drainage", "pitch_dimensions_area"],
    },
    {
        "slug": "altitude_oxygen_pitch",
        "title": "Altitude and Aerobic Demand on the Pitch",
        "summary": "High-elevation venues above 2000 metres reduce atmospheric oxygen partial pressure, suppressing visitor aerobic power output and producing measurable second-half high-intensity-running decay and late-match defensive exposure.",
        "stat_signature": "Unacclimatised visitors above 2500 m show 10-15% second-half high-intensity-distance decline; late-match (75-90 min) expected-goals-against rises 0.10-0.18 versus sea-level baselines; points-per-match for unacclimatised traveling sides falls 0.20-0.35 at altitude venues.",
        "mechanism": "Reduced oxygen availability lowers maximal aerobic power and accelerates lactate accumulation, causing earlier fatigue in repeated-sprint cycles; home sides adapted to altitude maintain output through the second half while visitors experience progressive capacity loss.",
        "conditions": "Deficit largest for sides arriving within 24 hours of kickoff; compounded when altitude exceeds 2500 m, temperatures are elevated, and travel distance was long; acclimatised sides training above 2000 m for 7-10 days recover a substantial fraction of the deficit.",
        "magnitude": "High-intensity running falls 10-15% in the second half for unacclimatised visitors; late-match expected-goals-against swings 0.12-0.22 in favour of the altitude-resident side.",
        "links": ["altitude_aerial_carry", "heat_humidity_load", "travel_distance_timezone", "sea_level_lowland_baseline"],
    },
    {
        "slug": "heat_humidity_load",
        "title": "Heat and Humidity Physiological Load",
        "summary": "High wet-bulb-temperature conditions suppress total-distance output, reduce high-speed-running volume, and force pace contraction across both sides, with cooling-break windows altering the tempo profile in distinctive patterns.",
        "stat_signature": "Total distance per player falls 4-6% above 28°C wet-bulb equivalent; high-speed-running drops 10-15% above 32°C; sprint frequency declines 12-18% in the highest humidity band; cooling-break matches show a 3-5% recovery in high-intensity output in the 10-minute post-break window.",
        "mechanism": "Thermoregulatory demands divert cardiac output to skin cooling, reducing oxygen delivery to working muscles; sweat-driven dehydration accelerates neuromuscular fatigue and degrades sprint replenishment capacity.",
        "conditions": "Most severe in tropical away fixtures for northern-hemisphere sides arriving without heat acclimatisation; midday or early-afternoon kickoffs in summer tournaments amplify thermal load substantially relative to evening matches.",
        "magnitude": "High-speed-running volume falls 10-15% in peak heat; total expected-goals-for per match declines roughly 0.08-0.12 as tempo contraction limits transition and pressing opportunities across both sides.",
        "links": ["altitude_oxygen_pitch", "travel_distance_timezone", "sea_level_lowland_baseline", "fixture_congestion_environment"],
    },
    {
        "slug": "wind_exposure_open_stadium",
        "title": "Wind Exposure in Open Stadiums",
        "summary": "Prevailing wind in open-bowl or partially enclosed grounds perturbs aerial deliveries and long-passing accuracy, producing directional residuals in cross-completion and long-pass accuracy that depend on wind strength and the orientation of play relative to the wind axis.",
        "stat_signature": "Cross-completion drops 8-14% in sustained winds above 30 km/h; long-pass accuracy (passes >30 metres) falls 5-9% across the same threshold; shots into the wind show 10-15% lower on-target rate as trajectory deviation impairs placement precision.",
        "mechanism": "Crosswind displaces aerial deliveries laterally off the intended flight path; headwind reduces ball velocity and shortens carry distance; tailwind extends passes beyond the target, disrupting timing for strikers and pressing runners.",
        "conditions": "Effect largest in exposed coastal or hilltop stadiums with open end-stands; enclosed bowl designs reduce ground-level wind speed by 30-50%, substantially attenuating the effect; becomes decisive in cup matches played at exposed neutral venues.",
        "magnitude": "Cross-completion suppression of 8-14% and long-ball accuracy fall of 5-9% in high-wind conditions; teams that adapt by shortening pass distribution and limiting aerial deliveries maintain efficiency closer to calm-conditions baselines.",
        "links": ["rain_pitch_wetness", "pitch_dimensions_area", "stadium_tightness_touchline", "altitude_aerial_carry"],
    },
    {
        "slug": "rain_pitch_wetness",
        "title": "Rain and Pitch Surface Wetness",
        "summary": "A wet, fast surface accelerates ball roll and reduces player grip, producing measurable increases in misplaced-pass rate, slide-tackle frequency, and goalkeeper-handling errors, with the net effect amplifying match variance above dry-condition baselines.",
        "stat_signature": "Misplaced-pass rate rises 3-6 percentage points on heavily rain-affected pitches; slide-tackle attempts increase 20-30% as standing-tackle traction fails; goalkeeper-handling errors (drops, parries into danger) rise 40-60% in heavy-rain conditions.",
        "mechanism": "Water film on surface fibres reduces rolling friction, making ball travel faster and further than anticipated; reduced traction on plant-foot forces defenders into slide challenges; wet leather absorbs more water, altering flight path on driven passes.",
        "conditions": "Largest impact during active rainfall on already-saturated pitches; synthetic surfaces maintain grip better than natural grass in moderate rain but degrade similarly in standing water; effect diminishes on well-drained modern hybrid pitches.",
        "magnitude": "Match open-play goal-per-shot rate rises approximately 0.01-0.02 per shot on heavily wet pitches due to handling errors and deflections; total expected-goals tends to underestimate actual goals on wettest surfaces by 8-12%.",
        "links": ["playing_surface_type", "grass_length_watering", "pitch_crown_drainage", "wind_exposure_open_stadium"],
    },
    {
        "slug": "frozen_hard_surface",
        "title": "Cold and Hardened Surface",
        "summary": "Freezing temperatures harden natural-grass pitches and increase ball rebound height and unpredictability, raising the rate of uncontrolled-bounce turnovers and suppressing ground-pass tempo while increasing aerial-contest frequency.",
        "stat_signature": "Uncontrolled-bounce control errors rise 15-25% on sub-2°C hardened surfaces; ground-pass tempo slows 8-12% as players compensate with heavier first-touch weight; long-ball usage increases 10-18% relative to comparable matches on normal surfaces.",
        "mechanism": "Frozen soil eliminates the cushioning absorption of a grass root zone, causing the ball to skid and rebound at shallower angles than players expect; boot-stud penetration fails on frozen ground, reducing acceleration and direction-change ability.",
        "conditions": "Primarily relevant in northern-European leagues during January and February; hybrid and synthetic pitches are dramatically more resistant to freezing because undersoil heating is more commonly installed; effect depends on freezing uniformity across the pitch.",
        "magnitude": "First-touch control errors rise 15-25%; aerial-contest frequency increases 10-18% as both sides bypass risky ground play; the aggregate effect raises match variance but effects are broadly symmetric for both sides.",
        "links": ["playing_surface_type", "pitch_surface_uniformity", "pitch_crown_drainage", "snow_visibility_conditions"],
    },
    {
        "slug": "pitch_crown_drainage",
        "title": "Pitch Crown and Drainage Profile",
        "summary": "Surface camber and subsurface drainage quality govern the extent of water pooling after rainfall, producing spatial non-uniformity in ball-roll consistency and localising misplaced passes to low-drainage zones that persist across a match.",
        "stat_signature": "Poorly drained pitches show a 15-25% elevation in misplaced-pass rate in identified waterlogged zones; ball-roll deviation on pooled areas increases 20-35% relative to dry-zone baselines; post-rainfall expected-goals models underestimate goals by 6-10% on worst-draining venues.",
        "mechanism": "Water pooling in low-drainage zones traps the ball suddenly, arresting momentum and causing unintended loss of possession; the spatial concentration of error zones creates repeatable location-specific turnover clusters exploited by pattern-aware sides.",
        "conditions": "Most pronounced at older grounds with compacted clay subsoil and limited modern drainage installation; corners and touchline areas drain slowest; large rainfall events within 48 hours of kickoff produce the strongest effects.",
        "magnitude": "6-10% expected-goals underestimation on worst-draining pitches in rain; misplaced-pass localisation to low-drainage zones produces 15-25% higher turnover rate in those areas.",
        "links": ["rain_pitch_wetness", "grass_length_watering", "pitch_surface_uniformity", "frozen_hard_surface"],
    },
    {
        "slug": "travel_distance_timezone",
        "title": "Away Travel Distance and Time-Zone Shift",
        "summary": "Long continental away trips impose combined physical and circadian costs that suppress high-intensity output in the early match phase and elevate early-match concession rates relative to short-distance or same-timezone travel.",
        "stat_signature": "Journeys over 2000 km correlate with a 5-8% first-half high-intensity-distance drop; crossings of three or more time zones add 0.10-0.15 expected-goals-against in the opening 30 minutes; points-per-match for the traveling side falls 0.20-0.30 relative to trips under 500 km.",
        "mechanism": "Circadian desynchrony degrades reaction time, sprint-replenishment timing, and decision-making in the early phase before physiological adaptation begins; overnight or multi-leg journeys compound muscle stiffness and glycogen depletion.",
        "conditions": "Largest when fixtures are scheduled within 48 hours of arrival, eliminating rest-adaptation time; compounded at altitude or high-heat venues that impose additional aerobic cost on already-fatigued visiting squads.",
        "magnitude": "First-half high-intensity distance for long-haul visitors falls 5-8%; early-match concession rate rises 20-30% above the traveling side's season-average baseline for first-30-minute windows.",
        "links": ["altitude_oxygen_pitch", "heat_humidity_load", "fixture_congestion_environment", "sea_level_lowland_baseline"],
    },
    {
        "slug": "stadium_tightness_touchline",
        "title": "Touchline Run-Off and Stadium Tightness",
        "summary": "Narrow touchline run-off space and close-proximity stands alter throw-in tempo, wing play, and referee foul-call thresholds, producing measurable differences in quick-restart frequency and wide-possession-recycling rates by venue.",
        "stat_signature": "Grounds with less than 2 metres of run-off produce quick-throw-in restarts 25-35% more frequently than open grounds; wide-area ball-recovery following tackles is 10-15% faster in tight stadiums due to ball-wall proximity; side-line fouls are called 8-12% more frequently in narrowest grounds.",
        "mechanism": "Reduced run-off forces the ball out of play more frequently on touchline challenges and constrains wing-player acceleration paths, increasing the density of physical contact in wide corridors and elevating both restart opportunities and foul incidence.",
        "conditions": "Effect largest for crosses-reliant wide-play systems that rely on carrying space; compact-block sides that generate from quick throw-in restarts gain disproportionately in tight stadiums.",
        "magnitude": "Quick-throw-in restart advantage adds approximately 3-5 additional restart possessions per match; wide-area foul rate elevation of 8-12% translates to 0.5-1.5 additional dangerous free-kick opportunities per match.",
        "links": ["pitch_dimensions_area", "enclosed_atmosphere_acoustics", "wind_exposure_open_stadium", "pitch_crown_drainage"],
    },
    {
        "slug": "enclosed_atmosphere_acoustics",
        "title": "Enclosed Bowl Acoustic Pressure",
        "summary": "Steep, fully enclosed stand designs concentrate crowd noise and create measurable referee-decision biases and home-intimidation effects, with foul-call differentials and added-time allocations that deviate systematically from open-ground baselines.",
        "stat_signature": "Home sides in fully enclosed grounds receive 12-18% fewer fouls called per contact than in open grounds; added time averages 0.4-0.8 minutes longer in enclosed venues in favour of the home side in lead situations; away-yellow-card-to-foul ratios are 15-20% higher in tightest enclosed bowls.",
        "mechanism": "Elevated ambient decibel levels raise crowd-signal noise around referee decisions, introducing a social-pressure bias that shifts marginal foul and card decisions toward the crowd's preference; enclosed sound reflection amplifies intensity uniformly around the pitch.",
        "conditions": "Bias strongest in high-attendance capacity utilisation above 90%; effect diminished in behind-closed-doors or low-attendance matches at the same venues, confirming crowd rather than architecture as the primary driver.",
        "magnitude": "12-18% home-foul-call advantage translates to approximately 0.04-0.08 additional expected-goals-for per match via favourable dead-ball positions; added-time manipulation in enclosed grounds represents roughly 0.5 minutes of suppressed opponent opportunity.",
        "links": ["stadium_tightness_touchline", "pitch_dimensions_area", "wind_exposure_open_stadium", "sunlight_glare_kickoff"],
    },
    {
        "slug": "sea_level_lowland_baseline",
        "title": "Lowland Sea-Level Reference Environment",
        "summary": "Matches played near sea level on temperate-climate pitches define the neutral aerobic and aerodynamic reference distribution against which altitude, climate, and surface deviations are scaled for cross-environment comparison.",
        "stat_signature": "Sea-level high-intensity running averages 900-1100 metres per outfield player per 90 minutes in top leagues; pass velocity on dry natural grass averages 18-22 m/s on driven passes; expected-goals-per-shot baselines of 0.095-0.115 are established at this reference tier.",
        "mechanism": "Full atmospheric oxygen pressure enables maximal aerobic power throughout the match without altitude penalty; temperate temperatures eliminate thermoregulatory diversion of cardiac output; consistent ball aerodynamics produce predictable shot-curve and pass-carry baselines.",
        "conditions": "Relevant as the calibration anchor when quantifying altitude, heat, or surface deviations; side comparisons across environments require normalisation to this baseline to avoid confounding environment with squad-quality differences.",
        "magnitude": "Serves as the reference distribution; deviations of 10-20% in high-intensity output and 0.10-0.25 in expected-goals-against per match represent the upper bounds of observed environment-driven effects.",
        "links": ["altitude_oxygen_pitch", "heat_humidity_load", "altitude_aerial_carry", "travel_distance_timezone"],
    },
    {
        "slug": "pitch_size_pressing_fit",
        "title": "Pitch Size and Pressing-Space Fit",
        "summary": "The interaction between available pitch area and a side's pressing-trigger distance determines how efficiently the press functions; larger pitches disadvantage shorter-trigger press systems and advantage compact-block sides with transition outlets.",
        "stat_signature": "Pressing-trigger distance increases by approximately 2-4 metres per 10-yard pitch-length increment; PPDA for high-press sides deteriorates 8-15% on the largest pitches; recovery-zone compactness scores fall 10-18% when available width exceeds 72 yards for compact-block systems.",
        "mechanism": "Additional space widens the area each pressing player must cover on a trigger run, breaking the coordinated overload that makes the press effective; compact sides gain because the larger transition-run distance for opponents extends counter-attack time.",
        "conditions": "Most impactful for extreme high-press systems with very short trigger distances; mid-block sides are relatively insensitive to pitch-size variation as they do not calibrate trigger distances to the press threshold.",
        "magnitude": "PPDA residual of 8-15% for high-press sides on largest pitches; expected-goals-per-press-recovery falls 0.02-0.04 on largest grounds as recovered possession is further from the opponent goal.",
        "links": ["pitch_dimensions_area", "stadium_tightness_touchline", "altitude_oxygen_pitch", "pitch_surface_uniformity"],
    },
    {
        "slug": "altitude_aerial_carry",
        "title": "Thin-Air Ball Flight and Set-Piece Carry",
        "summary": "Reduced air density at altitude extends ball carry distance on long passes and driven free-kicks, alters dipping-shot trajectory, and produces measurable shot and set-piece residuals relative to sea-level aerodynamic baselines.",
        "stat_signature": "Long pass carry increases 4-8% at 2500 m relative to sea level; dipping-shot inflection points shift 2-4 metres further from goal, altering goalkeeper positioning; corner-delivery carry is 5-10% longer, pushing set-piece delivery zones deeper.",
        "mechanism": "Reduced air resistance allows the ball to sustain velocity further along its trajectory; the Magnus effect generating dip and swerve on struck balls is weakened by lower air density, flattening shot and free-kick curves relative to expected trajectories.",
        "conditions": "Effect scales with altitude; most noticeable above 2000 m and dramatic above 3000 m; relevant for qualifying and continental fixtures at equatorial highland venues; negligible at venues below 1000 m.",
        "magnitude": "Ball carry extension of 4-8% at 2500 m alters calibrated set-piece delivery zones by 2-4 metres; shot-curve deviation reduces goalkeeper save probability by an estimated 2-4% on dipping long-range attempts.",
        "links": ["altitude_oxygen_pitch", "sea_level_lowland_baseline", "wind_exposure_open_stadium", "travel_distance_timezone"],
    },
    {
        "slug": "pitch_surface_uniformity",
        "title": "Surface Uniformity and Bobble Risk",
        "summary": "Patchy, worn, or unevenly maintained turf raises the rate of uncontrolled bounces and second-ball-loss events, with turnover concentration localised to documented worn zones that persist across the match.",
        "stat_signature": "Worn-zone control errors occur at 20-35% higher frequency than on undamaged surface areas; second-ball-loss rate in identified centre-circle and penalty-area wear zones rises 15-25%; matches on lowest-rated pitch-quality grounds show 0.05-0.10 additional expected-goals from opponent recoveries following control errors.",
        "mechanism": "Inconsistent turf density produces irregular ball-rise angles that diverge from trained first-touch responses; players calibrated to one bounce expectation on uniform surfaces cannot adapt in real time to a patchwork of degraded zones across the pitch.",
        "conditions": "Most severe in winter and spring on well-used community or shared-use grounds; highest-quality grounds with specialised maintenance maintain acceptable uniformity through the season; cup draws to lower-tier grounds introduce unfamiliar surface risk for elite sides.",
        "magnitude": "Control-error rate elevation of 20-35% in worn zones; overall match turnover rate rises approximately 4-8% on lowest-rated surfaces, adding roughly 0.05-0.10 expected-goals-against for the visiting technically-oriented side.",
        "links": ["playing_surface_type", "frozen_hard_surface", "pitch_crown_drainage", "pitch_dimensions_area"],
    },
    {
        "slug": "fixture_congestion_environment",
        "title": "Fixture Congestion Recovery Environment",
        "summary": "Short inter-match rest windows of under 72 hours create an accumulated-load environment that suppresses high-intensity running and elevates late-match defensive fragility across congested scheduling blocks.",
        "stat_signature": "High-intensity distance falls 8-12% on under-72-hour rest relative to the same side on full-week rest; late-match (75-90 min) expected-goals-against rises approximately 0.10-0.15 per match across two-game weeks; points-per-match declines 0.15-0.25 for sides accumulating three matches in eight days.",
        "mechanism": "Incomplete glycogen and soft-tissue recovery narrows the safe pressing window; cumulative muscle micro-damage reduces sprint-replenishment speed and elevates injury risk, forcing conservative positioning that widens defensive territory in the final quarter.",
        "conditions": "Largest in midfield-heavy pressing systems requiring high collective output across central runners; amplified when multiple key positions saw 90-minute exposure within 72 hours; rotation depth determines how effectively congestion is managed.",
        "magnitude": "Late-match expected-goals-against rises 0.10-0.15; high-intensity distance falls 8-12%; both sides sharing a congested fixture absorb symmetric cost, reducing the directional effect unless rest asymmetry exists.",
        "links": ["heat_humidity_load", "travel_distance_timezone", "playing_surface_type", "sea_level_lowland_baseline"],
    },
]
