"""NBA Environment spec — venue, travel, schedule, and physical-plant factors."""
from __future__ import annotations

SPORT = "NBA"
FAMILY = "Environment"

CONCEPTS = [
    {
        "slug": "venue_altitude_oxygen",
        "title": "Venue Altitude and Oxygen Availability",
        "summary": "Arenas above ~1,500 m reduce aerobic oxygen delivery, compressing visiting-team late-game output as anaerobic capacity is already taxed by playing time.",
        "stat_signature": "Visitors at high-elevation venues show Q4 net-rating decay of 4–7 points per 100 possessions versus their season-baseline Q4; live-ball turnover rate rises 1.2–1.8 pp in minutes 36–48.",
        "mechanism": "Reduced oxygen partial pressure elevates lactate accumulation per sprint, shortening effective high-intensity burst duration; repeat-sprint recovery slows and communication lapses under fatigue compound defensive miscoverage.",
        "conditions": "Largest in first 1–2 visits before partial acclimatization; amplified on back-to-back road legs and when visitors log heavy minutes in Q3; suppressed when visitors arrive 48+ hours early.",
        "magnitude": "4–7 net-rating points of Q4 visiting-side depression; roughly 1–2 extra live-ball turnovers per 48 visitor minutes in the closing stretch.",
        "links": ["elevation_three_carry", "altitude_recovery_back_to_back", "elevation_conditioning_adaptation", "schedule_compression_environment", "travel_distance_density"],
    },
    {
        "slug": "circadian_timezone_shift",
        "title": "Circadian Body-Clock Offset",
        "summary": "A mismatch between a team's home time zone and local tip-off time desynchronizes circadian rhythms governing peak reaction speed, producing wider shooting variance and first-quarter pace deviation.",
        "stat_signature": "Westbound travel (later body-clock tip) associates with a 2–4 pp drop in Q1 three-point percentage for visitors versus their road baseline; eastbound early-tip games show 1–2 possession pace compression per 48 minutes.",
        "mechanism": "Core body temperature and alertness peak in the home time zone's late afternoon; a 2–3 hour body-clock lag pushes tip-off into a sub-optimal physiological window, slowing fine motor accuracy before acclimation.",
        "conditions": "Strongest in the first road game of a cross-country trip; moderated by overnight flights allowing sleep at destination time; amplified for westbound teams on pre-19:00 local-time tip-offs.",
        "magnitude": "2–4 pp shooting variance increase and ~1–2 possession pace shift in Q1; effect decays to near zero by Q3.",
        "links": ["travel_distance_density", "schedule_compression_environment", "return_from_road_swing", "altitude_recovery_back_to_back"],
    },
    {
        "slug": "travel_distance_density",
        "title": "Travel Distance and Trip Density",
        "summary": "Cumulative air miles and time-zone crossings within a rolling seven-day road swing degrade defensive closeout speed, visible in help-side recovery rates and transition denial frequency.",
        "stat_signature": "Trips averaging above 800 air miles per game over 7 days correlate with a 3–5 point decline in opponent corner-three contest rate and a 1.5–2.5 pp rise in uncontested mid-range attempts allowed.",
        "mechanism": "Cabin pressure, disrupted sleep, and sedentary seated hours reduce lower-body vascular recovery; cumulative fatigue shortens first-step quickness and elevates perceived exertion at equivalent sprint speeds.",
        "conditions": "Effect is additive across trip legs — a three-city five-day swing produces larger degradation than a single long flight; moderated by rosters with established travel-adaptation protocols.",
        "magnitude": "3–5 defensive net-rating points per 100 possessions on high-density legs; ~2 extra uncontested perimeter looks allowed per 48 minutes.",
        "links": ["circadian_timezone_shift", "schedule_compression_environment", "return_from_road_swing", "venue_altitude_oxygen", "altitude_recovery_back_to_back"],
    },
    {
        "slug": "shooting_background_sightlines",
        "title": "Backdrop Sightlines and Depth Perception",
        "summary": "Seating backdrop contrast and depth-cue geometry behind each basket alter perimeter shooters' distance calibration, producing venue-specific three-point make-rate residuals after controlling for shot difficulty.",
        "stat_signature": "Light-colored upper-deck seat banks show a 1.5–2.5 pp three-point make-rate residual versus dark-backdrop arenas on catch-and-shoot corner attempts; basket-end splits within the same building diverge up to 1.8 pp on pull-up threes.",
        "mechanism": "A bright, low-contrast backdrop behind the rim reduces apparent rim distance, systematically biasing release arc and perceived depth on long-range attempts via the loss of visual anchor contrast.",
        "conditions": "More pronounced on first 1–2 visits before sightline adaptation; amplified under high-glare overhead lighting and in buildings with low upper-deck fill during early-season games.",
        "magnitude": "1.5–2.5 pp three-point rate residual at affected basket ends; roughly one additional missed perimeter attempt per 10 catch-and-shoot touches.",
        "links": ["lighting_glare_profile", "hvac_air_currents", "neutral_site_environment", "rim_backboard_stiffness"],
    },
    {
        "slug": "arena_humidity_ball_grip",
        "title": "Court Humidity and Ball Grip",
        "summary": "Building HVAC humidity levels change ball tackiness and floor surface moisture, affecting grip security on high-speed dribble moves and free-throw release consistency.",
        "stat_signature": "High-humidity buildings (RH above 55%) show live-ball turnover rates 0.8–1.5 pp above humidity-adjusted expectation; free-throw percentage variance inflates by ~1.2 standard deviations in the same venues.",
        "mechanism": "Elevated humidity increases surface moisture on the ball and palm, altering friction coefficient mid-grip; floors absorb moisture unevenly, creating micro-slip zones that amplify turnover risk on aggressive crossover sequences.",
        "conditions": "Concentrated in buildings with older HVAC systems or humid climates where outdoor air is entrained; most pronounced in early-season games before full climate conditioning cycles reach setpoint.",
        "magnitude": "0.8–1.5 pp live-ball turnover elevation; ~1.2 SD free-throw variance inflation in the highest-humidity venues.",
        "links": ["floor_traction_surface", "ambient_temperature_load", "rim_backboard_stiffness"],
    },
    {
        "slug": "floor_traction_surface",
        "title": "Hardwood Traction and Surface Friction",
        "summary": "Plank friction coefficient and dead-spot distribution vary across installed arena floors, producing non-contact slip events and crossover-related turnover residuals that track to venue configuration rather than player skill.",
        "stat_signature": "Venues with documented low-traction patches show non-contact turnover rates 0.6–1.2 pp above league average on dribble-penetration sequences; slip events cluster in identifiable dead-zone quadrants.",
        "mechanism": "Hardwood finish degrades unevenly under arena-event foot traffic; buffer compound depth, plank curvature, and subfloor rigidity interact to produce localized friction anomalies that disrupt planned cut angles.",
        "conditions": "Most pronounced on shared-event floors used for concerts or ice events within 48 hours of a game; also elevated in newer arenas where finish cure is incomplete.",
        "magnitude": "0.6–1.2 pp non-contact turnover elevation at affected venues; diffuse across all game phases.",
        "links": ["arena_humidity_ball_grip", "court_dimension_baseline_gap", "ambient_temperature_load"],
    },
    {
        "slug": "court_dimension_baseline_gap",
        "title": "Sideline and Baseline Run-Off Space",
        "summary": "Variation in out-of-bounds run-off distances shapes corner-three frequency and loose-ball save conversion, as tighter baseline gaps compress effective shooting windows and limit save-attempt angles.",
        "stat_signature": "Arenas with less than 3 feet of baseline run-off show corner-three frequency reductions of 0.4–0.9 attempts per 100 possessions for visiting offenses; loose-ball save-to-possession conversion drops 1.0–1.8 pp in tight-baseline venues.",
        "mechanism": "Shooter awareness of nearby padding narrows foot-placement confidence on baseline drift; save geometry shrinks when scorer's-table proximity limits lateral recovery angles on deflections.",
        "conditions": "Corner-three suppression is larger for visiting offenses unfamiliar with the run-off geometry; persists through repeated visits but never fully equalizes to home-team familiarity within a single season.",
        "magnitude": "0.4–0.9 corner-three attempt reduction per 100 possessions; 1.0–1.8 pp loose-ball save rate differential in constrained-baseline buildings.",
        "links": ["floor_traction_surface", "bench_distance_substitution_geometry", "neutral_site_environment"],
    },
    {
        "slug": "schedule_compression_environment",
        "title": "Schedule Compression Environment",
        "summary": "Back-to-back and four-in-five clusters act as environmental stressors producing second-half pace decay and defensive-rotation breakdown rates that track to schedule density independently of opponent quality.",
        "stat_signature": "Second-night back-to-back teams show second-half net-rating drops of 3–6 points per 100 possessions versus single-rest baselines; transition defense frequency falls 0.8–1.4 pp and closeout contests drop proportionally.",
        "mechanism": "Accumulated neuromuscular fatigue depresses fast-twitch recruitment; sleep debt from late arrivals compounds cognitive processing speed for defensive reads and rotation communication.",
        "conditions": "Largest effect when the second leg is a road game; moderated by shortened-rotation coaches who load stars on the first leg; amplified in the second half of the season when cumulative fatigue debt is highest.",
        "magnitude": "3–6 net-rating points of second-half depression; ~1–1.5 extra uncontested perimeter looks allowed per 48 minutes on compressed-schedule legs.",
        "links": ["travel_distance_density", "altitude_recovery_back_to_back", "return_from_road_swing", "venue_altitude_oxygen"],
    },
    {
        "slug": "elevation_three_carry",
        "title": "Thin-Air Shot Carry",
        "summary": "Reduced air density at high-elevation arenas lowers aerodynamic drag on the ball, extending shot carry distance on deep perimeter attempts and altering make-rate distribution for twenty-five-foot-plus shots.",
        "stat_signature": "Make rates on 25-foot-plus attempts at high-elevation venues run 1.5–3.0 pp above shot-quality-adjusted expectation for first-visit shooters; trajectory depth on offline makes skews 2–4 inches deeper off the back rim.",
        "mechanism": "Air resistance is proportional to air density; at 1,600 m elevation drag is roughly 15–18% lower than at sea level, meaning a calibrated sea-level release carries marginally farther before apex, altering bank angle and rim interaction geometry.",
        "conditions": "Applies equally to both teams within a game but differentially favors the home team across a full season via accumulated venue familiarity; most detectible on intentionally deep off-balance shots.",
        "magnitude": "1.5–3.0 pp residual make-rate increase on deep threes; 2–4 inch trajectory depth offset measurable at the back-rim contact zone.",
        "links": ["venue_altitude_oxygen", "elevation_conditioning_adaptation", "altitude_recovery_back_to_back", "hvac_air_currents"],
    },
    {
        "slug": "hvac_air_currents",
        "title": "Indoor Air Currents and Drafts",
        "summary": "Arena airflow near the rim from HVAC discharge vents can perturb long-arc free throws and deep corner threes, producing variance inflation in long-attempt accuracy at buildings with recirculation patterns near the basket.",
        "stat_signature": "Free-throw variance (SD of make rate across games) inflates 0.8–1.4 pp in buildings with ceiling discharge vents within 12 meters of the basket; similar inflation appears on corner-three attempts from the air-current side.",
        "mechanism": "A horizontal crosswind of 0.5–1.0 m/s at apex height is sufficient to deflect a high-arc shot laterally 1–3 cm; HVAC cycles create intermittent rather than steady drafts, producing inconsistent rather than directionally biased misses.",
        "conditions": "Strongest in high-ceiling arenas with centralized plenum discharge; amplified when loading docks are open, entraining outdoor air; less relevant in modern low-velocity diffusion HVAC systems.",
        "magnitude": "0.8–1.4 pp free-throw standard-deviation inflation; roughly one additional variance-driven miss per 30 attempts in high-draft buildings.",
        "links": ["shooting_background_sightlines", "elevation_three_carry", "arena_humidity_ball_grip"],
    },
    {
        "slug": "ambient_temperature_load",
        "title": "Ambient Court Temperature and Thermal Load",
        "summary": "Playing-surface temperature and arena thermal load shift thermoregulation demand, elevating cramping risk and late-game sprint-count decay in warmer buildings detectable through substitution cadence patterns.",
        "stat_signature": "Buildings running above 23°C at court level show late-game sprint-count decay of 8–12% in minutes 38–48; substitution cadence rises 0.4–0.7 extra dead-ball subs per Q4 in the warmest venues.",
        "mechanism": "Elevated ambient temperature raises skin blood-flow demand for heat dissipation, competing with working muscle perfusion; electrolyte loss accelerates cramping risk, forcing precautionary substitutions that compress effective rotation depth.",
        "conditions": "Most pronounced in arenas with shared cooling systems or prior-night events that raise residual thermal mass; amplified in humid climates where evaporative cooling efficiency is reduced.",
        "magnitude": "8–12% late-game sprint-count reduction; 0.4–0.7 extra precautionary dead-ball substitutions per Q4 in the warmest-quartile venues.",
        "links": ["arena_humidity_ball_grip", "floor_traction_surface", "schedule_compression_environment"],
    },
    {
        "slug": "lighting_glare_profile",
        "title": "Court Lighting and Glare Profile",
        "summary": "Overhead lighting intensity and glare angle affect visual tracking of fast passes and high-arc shots, producing passing-lane turnover residuals and catch-and-shoot accuracy differentials that are venue-specific.",
        "stat_signature": "Arenas with luminaire glare angles below 55 degrees show passing-lane turnover rates 0.5–1.0 pp above adjusted expectation; catch-and-shoot accuracy on above-the-break threes dips 1.0–1.8 pp in high-glare conditions.",
        "mechanism": "Transient glare from high-output fixtures at shallow angles creates pupil adaptation lag when tracking a ball through the lit zone; reaction time to intercept passing lanes or acquire a pass release point elongates 15–30 ms under peak glare.",
        "conditions": "Largest for shorter players whose upward sightline intersects the fixture zone more directly; amplified in older arenas with high-intensity discharge lamps rather than modern LED arrays.",
        "magnitude": "0.5–1.0 pp passing-lane turnover elevation; 1.0–1.8 pp catch-and-shoot accuracy reduction in glare-heavy venues.",
        "links": ["shooting_background_sightlines", "hvac_air_currents", "crowd_density_acoustic"],
    },
    {
        "slug": "altitude_recovery_back_to_back",
        "title": "Altitude Recovery Penalty on Consecutive Games",
        "summary": "Playing the second leg of a back-to-back at elevation compounds aerobic deficit from the first game with reduced oxygen availability, producing larger output decay than either stressor in isolation.",
        "stat_signature": "Visitor plus-minus on the second leg of a high-elevation back-to-back runs 6–10 points per 100 possessions below their season-average road figure; the same team's sea-level back-to-back second leg shows only 3–5 point decay.",
        "mechanism": "A single high-intensity game depletes muscle glycogen and elevates inflammatory markers; when recovery also restricts aerobic replenishment via reduced oxygen partial pressure, net energy availability for the second contest falls below what either stressor alone would predict.",
        "conditions": "Requires the first leg to be a full-effort high-minute game; suppressed when the visiting team rests rotation players on leg one; amplified when elevation gap between legs exceeds 1,200 m.",
        "magnitude": "6–10 net-rating points of visiting depression on high-elevation back-to-back second legs, roughly 2–4 points deeper than a comparable sea-level back-to-back.",
        "links": ["venue_altitude_oxygen", "elevation_conditioning_adaptation", "schedule_compression_environment", "travel_distance_density"],
    },
    {
        "slug": "crowd_density_acoustic",
        "title": "Acoustic Environment and Crowd Noise Floor",
        "summary": "Physical sound-pressure levels in loud arenas impair on-court verbal communication, producing defensive-rotation breakdown rates and substitution-timing differentials that reflect acoustic environment rather than team quality alone.",
        "stat_signature": "Sold-out arenas averaging above 90 dB during dead balls show defensive breakdown rates 0.7–1.3 pp above adjusted expectation in the final 4 minutes of close games; late substitution errors run 0.3–0.6 events per game higher than quiet venues.",
        "mechanism": "Speech intelligibility degrades sharply above 85 dB ambient; defensive call-outs for switch assignments become unreliable, increasing coverage-gap frequency; bench-to-floor substitution signals are harder to relay under sustained high noise floors.",
        "conditions": "Largest on visiting teams unfamiliar with crowd timing and noise patterns; amplified in arenas with curved bowl acoustics that focus crowd noise toward the floor; reduced in partial-attendance settings.",
        "magnitude": "0.7–1.3 pp defensive breakdown elevation in closing minutes; 0.3–0.6 extra administrative error events per game in the loudest-quartile venues.",
        "links": ["lighting_glare_profile", "bench_distance_substitution_geometry", "neutral_site_environment"],
    },
    {
        "slug": "neutral_site_environment",
        "title": "Neutral-Site Physical Familiarity Gap",
        "summary": "Games at non-home, non-standard venues expose both teams to unfamiliar rim tension, sightline depth, and floor traction simultaneously, producing combined shooting-variance inflation versus each team's typical road accuracy profile.",
        "stat_signature": "Neutral-site shooting averages run 1.5–3.0 pp below the weighted average of each participant's road profile; game-to-game three-point standard deviation inflates 1.5–2.2 pp versus standard away games.",
        "mechanism": "Road adaptation to any given arena takes multiple visits to stabilize spatial calibration for shooting and rim angles; at a neutral site neither team has accumulated that familiarity, compounding the accuracy-uncertainty floor for both simultaneously.",
        "conditions": "Largest in purpose-built neutral sites without an embedded fan majority; reduced when one team played the venue recently; amplified in single-elimination formats with no game-to-game adaptation.",
        "magnitude": "1.5–3.0 pp combined three-point rate reduction; 1.5–2.2 pp variance inflation per game across the shooting sample.",
        "links": ["shooting_background_sightlines", "rim_backboard_stiffness", "court_dimension_baseline_gap", "crowd_density_acoustic"],
    },
    {
        "slug": "return_from_road_swing",
        "title": "Post-Road-Swing Re-Acclimation",
        "summary": "Teams returning home after multi-city road trips show first-game shooting and pace residuals relative to rested home baselines, reflecting a brief re-acclimation window before familiar venue cues restore spatial calibration.",
        "stat_signature": "First home game after a 4+ game road swing shows three-point percentage 0.8–1.5 pp below the team's rested home-game baseline; transition offense pace recovers to full home-court level within 1–2 additional home contests.",
        "mechanism": "Extended exposure to foreign sightlines, rim tensions, and floor geometries partially recalibrates spatial memory; on return, the home-court spatial model requires a brief reset period before familiar cues re-anchor calibration.",
        "conditions": "Requires a swing of at least 4 away games; suppressed when the team returns to a rested rotation; amplified when the road swing included multiple different floor types.",
        "magnitude": "0.8–1.5 pp three-point rate shortfall in the first home game; full recovery to home baseline within 1–2 home contests.",
        "links": ["travel_distance_density", "circadian_timezone_shift", "schedule_compression_environment", "neutral_site_environment"],
    },
    {
        "slug": "bench_distance_substitution_geometry",
        "title": "Bench Geometry and Substitution Logistics",
        "summary": "Scorer's-table position and bench layout affect substitution speed and dead-ball management, producing too-many-men and late-sub frequency residuals that are venue-configuration signals rather than coaching-quality signals.",
        "stat_signature": "Venues with unconventional scorer's-table orientation or short bench-to-table distances show too-many-men violation rates 0.2–0.5 events per 100 dead balls above league average; substitution-delay technical fouls cluster in such buildings.",
        "mechanism": "Physical distance and sightline geometry between bench, scorer's table, and the officiating crew determine the available time window for a player check-in; tight geometries reduce the margin for error on simultaneous multi-player changes.",
        "conditions": "Effect is largest in multipurpose arena configurations where the bench sideline is compressed by event staging; amplified in playoff settings where substitution timing is strategically critical.",
        "magnitude": "0.2–0.5 extra administrative violation events per 100 dead balls in affected venues; diffuse but persistent across the season.",
        "links": ["court_dimension_baseline_gap", "crowd_density_acoustic"],
    },
    {
        "slug": "elevation_conditioning_adaptation",
        "title": "Home-Elevation Conditioning Adaptation",
        "summary": "Home teams at high-elevation arenas develop physiological adaptation across a full season of practices and home games, sustaining Q4 pace and transition frequency at levels visiting teams at the same venue cannot match.",
        "stat_signature": "Home teams at high-elevation venues sustain Q4 transition frequency within 0.5 pp of their full-game average; visiting teams at the same venues show Q4 transition drops of 2–4 pp versus their own full-game rate.",
        "mechanism": "Chronic altitude exposure increases red blood cell mass and mitochondrial density via erythropoietin upregulation; home teams train repeatedly at elevation, accumulating adaptations that buffer aerobic fatigue unavailable to teams visiting only 1–3 times per season.",
        "conditions": "Adaptation benefit accumulates over a full season of home-altitude training; most pronounced in back-to-back home games where the adaptation advantage compounds against a fatigued visitor.",
        "magnitude": "2–4 pp Q4 transition-frequency advantage over visiting teams at the same elevation; ~3–5 net-rating points of Q4 home differential attributable to conditioning adaptation alone.",
        "links": ["venue_altitude_oxygen", "altitude_recovery_back_to_back", "elevation_three_carry", "schedule_compression_environment"],
    },
    {
        "slug": "rim_backboard_stiffness",
        "title": "Rim and Backboard Tension Profile",
        "summary": "Venue-specific rim elasticity and backboard rebound behavior leave measurable residuals in offensive-rebound rate and short-bounce make rate after controlling for shot location and shooter quality.",
        "stat_signature": "Stiff-rim venues show offensive-rebound rates 0.6–1.2 pp above expectation on mid-range short-bounce attempts; soft-rim venues show a 0.5–1.0 pp reduction in strong-bounce offensive put-back frequency.",
        "mechanism": "Ring tension determines energy transfer on rim contact: a stiffer ring deflects with less energy absorption, producing shorter higher-velocity bounces favoring quick-reaction offensive rebounders; softer rings yield lower-arc closer-to-basket deflections.",
        "conditions": "Stiffness effect is largest on medium-quality field goal attempts where rim contact is expected; negligible on clean swishes; amplified at venues that share rims across multiple event configurations and recalibrate inconsistently.",
        "magnitude": "0.5–1.2 pp offensive-rebound rate residual depending on rim tension class; accumulates over large shot-volume samples.",
        "links": ["shooting_background_sightlines", "neutral_site_environment", "arena_humidity_ball_grip"],
    },
]
