"""Tennis Environment concept-node spec — person-free, market-honest."""
from __future__ import annotations

SPORT = "Tennis"
FAMILY = "Environment"

CONCEPTS = [
    {
        "slug": "surface_type_category",
        "title": "Court Surface Category",
        "summary": "Surface family — clay, grass, hard, indoor — is the dominant structural variable governing bounce height, skid angle, and grip, shaping every tactical trade-off in a match.",
        "stat_signature": "Rally-length median differs 2–5 shots across families; serve-hold spans 60–72 pct clay-to-grass; return-points-won residual shifts ±6–9 pct after surface-family dummies.",
        "mechanism": "Clay particles shear on impact, decelerating and elevating the ball; grass minimises skid angle, accelerating it; hard acrylic gives mid-range predictable rebound. Grip and pace determine structural server-versus-baseliner advantage.",
        "conditions": "Effect is largest early in a tournament before within-event wear obscures the clean surface signature; cross-surface comparisons require controlling elevation, temperature, and ball model.",
        "magnitude": "Surface family explains roughly 25–35 pct of explainable variance in hold rate and rally length tour-wide, making it the single dominant environmental factor.",
        "links": ["clay_bounce_height", "grass_low_skid", "hard_court_true_bounce", "court_pace_index", "surface_transition_swing"],
    },
    {
        "slug": "court_pace_index",
        "title": "Surface Court Pace Index",
        "summary": "Within a surface family, individual courts vary on a continuous pace scale driven by acrylic hardness, clay density, or grass thickness, producing serve-dominance gradients between venues of nominally the same type.",
        "stat_signature": "Serve-plus-one winner rate rises ~1.5–3.0 pct per 10-point pace-index increase; return-points-won falls ~1–2 pct; average rally shortens 0.4–0.8 shots per 10-point increment.",
        "mechanism": "A faster court rewards flat, penetrating ball-striking by compressing the time window for the receiver between bounce and contact. Coefficient of restitution and skid angle jointly determine whether the returner can neutralise incoming pace.",
        "conditions": "Pace-index effects amplify in hot, dry conditions that harden acrylic and are attenuated by cold, damp conditions. Ball model and altitude interact with pace index.",
        "magnitude": "Moving from a slow hard court (pace index ~40) to a fast one (~70) shifts hold rate 5–8 pct, comparable in size to the clay-to-hard surface shift.",
        "links": ["surface_type_category", "altitude_thin_air_speed", "ball_type_pressure", "day_night_session_conditions"],
    },
    {
        "slug": "clay_bounce_height",
        "title": "Clay High-Bounce and Friction",
        "summary": "Clay's granular surface decelerates the ball on impact and redirects energy upward, producing a high, slow bounce that lengthens rallies and rewards heavy topspin clearance well above the contact zone.",
        "stat_signature": "Points exceeding 8 shots: 35–50 pct on clay versus 18–28 pct on hard; topspin-ball clearance height 0.5–1.0 m higher on clay; break-point opportunity rate 8–14 pct above hard-court baseline.",
        "mechanism": "Clay particles shear and spread under ball impact, absorbing kinetic energy and converting horizontal momentum to vertical displacement. The resulting high ball sits up longer, reducing the first-strike time premium and rewarding consistent high-looping groundstrokes.",
        "conditions": "Effect is strongest on freshly-groomed, well-watered clay. Dry, compacted clay late in a tournament approaches hard-court characteristics. Red clay produces a more pronounced high bounce than green clay due to finer particle size.",
        "magnitude": "Hold rate on clay is typically 4–9 pct below equivalent hard-court events; point duration averages 20–35 pct longer, placing clay at the top of the physiological-load spectrum.",
        "links": ["surface_type_category", "court_surface_freshness", "humidity_spin_grip", "heat_humidity_player_load"],
    },
    {
        "slug": "grass_low_skid",
        "title": "Grass Low-Skid and Slick Bounce",
        "summary": "Natural grass keeps the ball close to the turf on impact by minimising surface friction and skid angle, producing a fast, skidding ball that compresses rallies and challenges return timing.",
        "stat_signature": "Serve-unreturned rate 30–42 pct on grass versus 20–28 pct on hard; points ending within four shots 55–65 pct; net-approach success exceeds 72 pct on grass compared with 60–65 pct on hard.",
        "mechanism": "Grass blades yield under ball contact, limiting vertical rebound force and letting the ball slide forward rather than rising. The low trajectory forces the returner to contact the ball below the ideal strike window.",
        "conditions": "Effect is most pronounced early in the tournament when grass is lush. Worn, scuffed baseline zones in later rounds produce unpredictable bounces rather than uniformly low skid. Damp grass is slower and higher-bouncing than dry grass.",
        "magnitude": "Hold rate on grass is typically 5–10 pct above clay and 3–6 pct above medium hard courts; break frequency reaches its seasonal low, making service dominance the defining statistical feature.",
        "links": ["surface_type_category", "court_surface_freshness", "court_orientation_layout", "indoor_controlled_conditions"],
    },
    {
        "slug": "hard_court_true_bounce",
        "title": "Hard-Court True-Bounce Consistency",
        "summary": "Acrylic hard courts deliver a medium-height, predictable bounce with low variance in skid angle, creating a consistent contact environment that rewards timing precision and baseline depth control.",
        "stat_signature": "Unforced-error rate standard deviation 15–25 pct lower on hard courts than grass; return-depth consistency residuals are tightest of any surface; serve hold rate near tour median at 64–68 pct.",
        "mechanism": "Rigid acrylic reflects ball energy with high fidelity, producing a bounce angle proportional to incoming pace and spin. Predictability reduces forced adaptation in footwork and contact-point, evening the tactical playing field relative to clay or grass extremes.",
        "conditions": "True-bounce advantage is strongest for precise ball-strikers. In extreme heat the surface becomes livelier, shifting toward a faster pace profile; cold or damp conditions deaden and slow it.",
        "magnitude": "Hard courts produce the most balanced hold-break ratio on tour, with the narrowest spread in match outcome statistics across comparable events.",
        "links": ["surface_type_category", "court_pace_index", "heat_ball_liveliness", "cold_dense_air_drag"],
    },
    {
        "slug": "altitude_thin_air_speed",
        "title": "Altitude Thin-Air Ball Speed",
        "summary": "High-elevation venues reduce air density, lowering aerodynamic drag in flight and flattening spin-induced deviation, producing measurably faster effective ball speed and higher ace rates.",
        "stat_signature": "Effective serve speed at 2,000 m is roughly 4–7 pct higher than at sea level for the same racket head speed; ace rate residuals +3–6 pct controlling for surface; topspin-induced drop reduced 15–20 pct.",
        "mechanism": "Aerodynamic drag scales with air density. At 2,500 m, density is ~25 pct below sea level, reducing deceleration over the flight path. Magnus-effect spin deviation diminishes proportionally, flattening heavy topspin and making flat-hit serves more penetrating.",
        "conditions": "Effects compound with high temperature. Most visible on serves and flat groundstrokes; heavy looping shots are relatively more disrupted because their tactical value depends on spin deviation that thin air suppresses.",
        "magnitude": "High-elevation hard courts often play one pace-index category faster than their acrylic rating would suggest at sea level; ace rates are statistically elevated and rally lengths compressed.",
        "links": ["altitude_spin_reduction", "court_pace_index", "ball_type_pressure", "heat_ball_liveliness"],
    },
    {
        "slug": "ball_type_pressure",
        "title": "Ball Model and Internal Pressure",
        "summary": "The specific ball approved for each tournament — defined by felt density, core compound, and internal pressurisation — shifts speed and bounce independently of surface, creating measurable performance differences between otherwise comparable venues.",
        "stat_signature": "Rally-length median shifts 0.5–1.5 shots between high-altitude-spec and standard balls on the same surface; ace-rate residuals differ 2–4 pct between ball specifications at matched elevation and temperature.",
        "mechanism": "Higher internal pressure raises the coefficient of restitution, making the ball spring off the surface more sharply. Denser felt adds drag and exaggerates spin; thinner felt reduces it. Organizers select ball models partly to counteract altitude or surface-speed extremes.",
        "conditions": "Ball-type effects are largest at altitude, where pressureless balls are often specified to compensate for thin-air acceleration. The interaction with surface pace index is non-linear.",
        "magnitude": "Switching from standard to high-altitude-spec at sea level would produce effects comparable to a 5–10 point pace-index increase, illustrating the ball's own contribution independent of the court.",
        "links": ["altitude_thin_air_speed", "ball_fluffing_wear", "court_pace_index", "altitude_spin_reduction"],
    },
    {
        "slug": "ball_fluffing_wear",
        "title": "Ball Felt Fluffing and In-Play Wear",
        "summary": "As a match ball is used, felt fibres fluff outward, increasing drag and bounce height gradually from the first game after a change to the last, creating a systematic intra-ball-cycle drift in pace.",
        "stat_signature": "Serve speed drops ~1.5–3.0 km/h from a fresh ball to the final game of a standard 7-to-9-game cycle; rally length increases 0.3–0.7 shots across the same window on fast surfaces.",
        "mechanism": "Fresh felt is tightly napped and aerodynamically smooth. With each shot, felt fibres stand erect, increasing effective surface area and drag coefficient. The expanding felt shell also cushions impact, raising bounce height and reducing the coefficient of restitution incrementally.",
        "conditions": "Effect is fastest on abrasive hard courts, slowest on clay. Wet or humid conditions accelerate matting. The transition from new to fluffed is sharpest in the first two games of a cycle, then plateaus.",
        "magnitude": "The mid-cycle ball produces detectably longer rallies and lower ace rates than the same exchange with a fresh ball — visible in aggregate serve-speed tracking across tours.",
        "links": ["ball_type_pressure", "humidity_spin_grip", "court_pace_index", "surface_type_category"],
    },
    {
        "slug": "indoor_controlled_conditions",
        "title": "Indoor Controlled-Air Environment",
        "summary": "Enclosed indoor arenas eliminate wind and normalise air temperature and humidity, producing a stable, repeatable ball-flight environment that standardises physical conditions across every point in a session.",
        "stat_signature": "Serve-hold rate 3–6 pct higher indoors than equivalent outdoor hard courts in the same temperature range; point-to-point unforced-error variance 10–20 pct lower indoors; double-fault rate near its tour minimum.",
        "mechanism": "Wind absence removes perturbation of the ball toss and high-ball tracking. Stable humidity keeps ball felt from rapid weight change and maintains consistent string tension, rewarding precision over adaptability.",
        "conditions": "Indoor hold-rate advantage is most pronounced on fast carpet or fast acrylic. On slower indoor hard courts the effect narrows because serve dominance is already suppressed by surface pace.",
        "magnitude": "Indoor events are among the most serve-dominant on the calendar, with break-of-serve frequency at its seasonal low, reflecting the compound benefit of surface speed and environmental stability.",
        "links": ["wind_outdoor_disruption", "retractable_roof_transition", "day_night_session_conditions", "court_pace_index"],
    },
    {
        "slug": "wind_outdoor_disruption",
        "title": "Outdoor Wind Disruption",
        "summary": "Gusting and sustained wind at outdoor venues perturbs the ball toss, disrupts depth and direction control on groundstrokes, and measurably elevates double-fault and unforced-error rates above calm-day baselines.",
        "stat_signature": "Double-fault rate increases 0.8–2.0 pct per 10 km/h mean wind speed; unforced-error rate rises 1.5–3.5 pct in gusting versus calm conditions; toss-related double faults are asymmetrically elevated on the upwind serving end.",
        "mechanism": "Horizontal wind force displaces the released ball toss from its intended contact point, forcing real-time compensation that reduces pace or accuracy. Gusty conditions are more disruptive than steady wind because players cannot pre-adapt the toss for an arriving gust.",
        "conditions": "Wind disruption is most severe on clay and grass where the serve bonus is already moderate. Court orientation determines which end faces into the prevailing wind, creating asymmetric performance by serving end.",
        "magnitude": "High-wind sessions produce hold rates 3–7 pct below calm conditions at the same venue; total match errors increase enough to extend average duration 10–20 minutes.",
        "links": ["indoor_controlled_conditions", "sun_glare_serve_window", "court_orientation_layout", "day_night_session_conditions"],
    },
    {
        "slug": "heat_humidity_player_load",
        "title": "Heat and Humidity Physiological Load",
        "summary": "High wet-bulb temperature impairs thermoregulation, accelerating fatigue and extending recovery between points, with measurable effects on third-set error rates and point duration.",
        "stat_signature": "Third-set point duration 8–15 pct longer than first-set average above 32 C wet-bulb; time between points increases 3–7 seconds; late-match unforced-error rate rises 2–5 pct in extreme heat.",
        "mechanism": "Core temperature elevation and sweat-driven fluid loss reduce central nervous system signal fidelity and muscle contractile speed. The longer a set extends under heat stress, the larger the performance decrement compounds. Humidity impairs sweat evaporation, making the same dry-bulb temperature more physiologically demanding.",
        "conditions": "Effect is largest in best-of-five formats and tournaments that do not invoke heat-rule rest periods. It compounds with prior-round fatigue and back-to-back scheduling. Afternoon sessions are most exposed; night sessions largely sidestep extreme heat load.",
        "magnitude": "In conditions exceeding heat-rule thresholds, match duration stretches 15–30 pct relative to temperate-day baselines, and third-set competitive balance shifts noticeably toward whichever side entered with lower accumulated fatigue.",
        "links": ["heat_ball_liveliness", "day_night_session_conditions", "clay_bounce_height", "cold_dense_air_drag"],
    },
    {
        "slug": "heat_ball_liveliness",
        "title": "Heat-Driven Ball Liveliness",
        "summary": "High air temperature raises internal ball pressure and reduces air density slightly, producing a livelier, faster-bouncing ball independently of the physiological effects on the athletes.",
        "stat_signature": "Serve speed increases ~1–2 km/h per 10 C temperature rise at the same elevation; bounce height residuals on hard courts 2–4 pct higher in afternoon heat versus morning sessions; ace rate lifts 1–2 pct on extreme-heat days.",
        "mechanism": "Internal ball pressure follows the ideal gas law: at 40 C a ball inflated to standard pressure at 20 C carries roughly 7 pct higher internal pressure, increasing the coefficient of restitution. Warmer, less dense air also reduces drag in flight.",
        "conditions": "Ball-liveness gain is additive with altitude effects and most visible on fast hard courts. On clay the high bounce is already present, so additional liveness narrows the rally-length gap with hard courts but does not reverse it.",
        "magnitude": "On a 38 C afternoon hard court, the ball behaves comparably to a 5–8 point faster pace index, pushing serve statistics toward those seen at moderately faster venues under temperate conditions.",
        "links": ["heat_humidity_player_load", "altitude_thin_air_speed", "ball_type_pressure", "day_night_session_conditions"],
    },
    {
        "slug": "retractable_roof_transition",
        "title": "Roof Closure Condition Shift",
        "summary": "Closing a retractable roof mid-event converts the playing environment from outdoor to indoor, eliminating wind and altering temperature and humidity in ways that measurably shift serve-hold and rally-length statistics within the same session.",
        "stat_signature": "Serve-hold rate rises 3–5 pct in roof-closed segments compared with immediately preceding roof-open play; rally length drops 0.4–0.8 shots per point post-closure; double-fault rate falls 1–2 pct.",
        "mechanism": "Roof closure halts wind disruption of the toss and removes gusts that skew trajectory. Air conditioning quickly stabilises humidity and temperature, removing both the ball-liveness boost of afternoon heat and the unpredictability of changing outdoor conditions.",
        "conditions": "Transition effects are sharpest when closure happens mid-match after sustained wind or rain, forcing tactical adaptation within the match. Pre-match closure produces a clean indoor baseline without the transition artifact.",
        "magnitude": "The roof-closure shift is statistically detectable within a single match segment; historically documented with within-session serve-hold differentials of 4–6 pct at major venues.",
        "links": ["indoor_controlled_conditions", "wind_outdoor_disruption", "day_night_session_conditions", "court_pace_index"],
    },
    {
        "slug": "day_night_session_conditions",
        "title": "Day versus Night Session Conditions",
        "summary": "Night sessions at outdoor and retractable-roof venues are cooler, denser, and often calmer than day sessions, producing a slower, less lively ball and measurably different hold rates within the same tournament.",
        "stat_signature": "Serve speed 2–4 km/h lower in night sessions versus afternoon sessions at the same venue; average rally length 0.5–1.2 shots longer at night; hold rate shifts 2–4 pct between session types at matched-surface venues.",
        "mechanism": "As ambient temperature drops 8–15 C from afternoon peak to night, air density rises and ball internal pressure falls, reducing both liveness and flight pace. Wind typically subsides after sunset, adding the calm that further normalises conditions.",
        "conditions": "Day-night splits are largest at venues with high diurnal temperature swings such as desert hard courts. At moderate-climate clay events the split is smaller because afternoon temperatures rarely reach the threshold where ball liveness diverges substantially.",
        "magnitude": "Day-night session difference is equivalent to a 3–6 point pace-index shift on the same court, producing a meaningful statistical signal when session type is consistently recorded.",
        "links": ["heat_ball_liveliness", "indoor_controlled_conditions", "cold_dense_air_drag", "court_pace_index"],
    },
    {
        "slug": "court_surface_freshness",
        "title": "Surface Freshness Through the Draw",
        "summary": "Clay and grass courts degrade progressively through a tournament as footwork churns the surface, producing patchy wear in the baseline zone that increases bounce variance and error rates in later rounds.",
        "stat_signature": "Bad-bounce unforced-error rate rises 1.5–3.5 pct from round one to quarterfinal on grass; baseline wear-zone error residuals increase ~2 pct per tournament day on clay; return errors from unpredictable skids spike in week two of major clay events.",
        "mechanism": "Heavy foot traffic concentrates wear in the T-zone and baseline corners, stripping grass and compacting or rutting clay. On grass this creates bare patches that produce inconsistent skid; on clay it creates hard furrows that alter bounce angle unpredictably.",
        "conditions": "Most pronounced on grass, which cannot be replaced during a tournament. Clay can be raked and watered between matches, slowing degradation. Hard courts are essentially immune to within-tournament wear. Late-round matches on deteriorated surfaces reward adaptability over precision.",
        "magnitude": "On worn major grass courts in week two, bad-bounce contributions to errors are visible enough to inflate match totals compared with the same matchups on a fresh court at the same venue.",
        "links": ["grass_low_skid", "clay_bounce_height", "surface_type_category", "humidity_spin_grip"],
    },
    {
        "slug": "humidity_spin_grip",
        "title": "Humidity and Spin Grip",
        "summary": "High atmospheric humidity adds weight to ball felt and increases air drag interaction with spin, slowing flat drives more than looped topspin and extending rallies within any surface family.",
        "stat_signature": "Topspin-ball clearance residuals 3–6 pct higher above 75 pct relative humidity versus below 50 pct; rally length 0.4–0.9 shots longer in high-humidity matched pairs; ace rate falls 1–2 pct in humid versus dry sessions at fixed temperature.",
        "mechanism": "Damp felt absorbs moisture and gains weight, increasing drag and the felt-ball spin interaction. The net effect slows flat shots more than spin shots, because drag is velocity-squared whereas spin deviation also depends on it — heavy topspin retains more relative effectiveness.",
        "conditions": "Effect is most visible on clay, where rally lengths are already extended and the humidity contribution is additive. On grass, humidity also slows the surface and adds ball weight, partially counteracting the grass speed advantage.",
        "magnitude": "In tropical or near-coast high-humidity outdoor events, clay rally length approaches levels seen at slow indoor clay, illustrating the humidity contribution independently of nominal surface category.",
        "links": ["clay_bounce_height", "ball_fluffing_wear", "heat_humidity_player_load", "altitude_spin_reduction"],
    },
    {
        "slug": "altitude_spin_reduction",
        "title": "Thin-Air Spin Reduction",
        "summary": "Reduced air density at altitude diminishes the Magnus-effect force that converts ball spin into trajectory curvature, flattening topspin kick and slice skid and favouring pace-based ball-strikers over heavy spinners.",
        "stat_signature": "Topspin-induced bounce height 15–20 pct lower at 2,500 m than at sea level for matched spin rates; flat-hitter winner rate increases 3–6 pct at altitude after controlling for surface; kick-serve bounce height residuals fall 0.2–0.4 m.",
        "mechanism": "Magnus force is proportional to air density times the cross product of angular velocity and translational velocity. At 2,500 m, density is ~25 pct lower, so the same topspin rpm produces ~25 pct less trajectory curvature, landing heavy looping groundstrokes shorter and lower than intended.",
        "conditions": "Most strategically significant for players whose game model depends on high-kick serves or high-bouncing topspin to push opponents behind the baseline — at altitude those shots arrive in a neutral rather than extreme high-ball position.",
        "magnitude": "Kick-serve effectiveness at altitude is estimated 15–25 pct below its sea-level margin, a tactically significant reduction visible in second-serve hold-rate comparisons across matched altitude and sea-level events.",
        "links": ["altitude_thin_air_speed", "ball_type_pressure", "humidity_spin_grip", "hard_court_true_bounce"],
    },
    {
        "slug": "cold_dense_air_drag",
        "title": "Cold Dense-Air Drag",
        "summary": "Cold outdoor sessions increase air density, raising aerodynamic drag throughout the ball's flight and deadening both the serve and the groundstroke, effectively slowing the court below temperate-baseline norms.",
        "stat_signature": "Serve speed drops ~1.5–3.0 km/h per 10 C decrease below 15 C; ace rate falls 1.5–3.0 pct at fast hard courts in cold conditions; average rally length extends 0.3–0.7 shots in sub-10 C outdoor sessions.",
        "mechanism": "Air density increases as temperature falls (ideal gas law), raising drag force. Simultaneously, ball internal pressure drops in cold, reducing the coefficient of restitution and flattening the bounce. Both effects compound: the ball decelerates more in flight and bounces lower and slower off the surface.",
        "conditions": "Most relevant at early-season or late-season outdoor events in temperate climates, or at evening sessions that extend into cold night air. A cold, dense atmosphere at moderate elevation can neutralise most of the altitude pace gain.",
        "magnitude": "A 10 C cold outdoor hard-court session produces serve statistics comparable to a medium-pace court under standard conditions — a shift large enough to reclassify effective court pace for that session.",
        "links": ["heat_ball_liveliness", "day_night_session_conditions", "hard_court_true_bounce", "altitude_thin_air_speed"],
    },
]
