"""Tennis / ErrorCascades — person-free concept-node spec."""
from __future__ import annotations

SPORT = "Tennis"
FAMILY = "ErrorCascades"

CONCEPTS: list[dict] = [
    {
        "slug": "unforced_error_streak_within_game",
        "title": "Unforced-Error Streak Within a Game",
        "summary": "Consecutive unforced errors within a game compound: the conditional UE probability after a first UE is 1.3-1.6x baseline, and games with 3+ UEs are lost at ~75-85% frequency versus ~40% for 0-1-UE games.",
        "stat_signature": "Conditional UE rate after a prior UE in the same game ~1.3-1.6x the unconditional per-point rate; 3+-UE games lost ~75-85% of the time.",
        "mechanism": "A UE triggers mild arousal and self-monitoring that degrades fluid stroke production; abbreviated preparation and over-corrective shot selection sustain the elevated error rate within the same game.",
        "conditions": "Most pronounced in high-leverage games, on surfaces demanding precise placement (clay, slow hard), and during extended rallies where cognitive load amplifies the effect.",
        "magnitude": "Games with a 3+-UE streak are won roughly 20-30 percentage points less often than comparable games without such a streak.",
        "links": ["double_fault_cluster_cascade", "post_error_rushed_selection_cascade", "deuce_game_pressure_compounding"],
    },
    {
        "slug": "double_fault_cluster_cascade",
        "title": "Double-Fault Cluster Cascade",
        "summary": "A double fault raises tension that compounds into clustered repeat double faults within the same service game; the conditional double-fault rate after a prior double fault is 1.5-2.2x the baseline, multiplying break risk.",
        "stat_signature": "Conditional DF rate after a prior DF in the same game: 1.5-2.2x baseline; games with 2+ DFs broken at 2-3x the frequency of single-DF games.",
        "mechanism": "The DF anchors the server toward a defensive second serve, reducing pace and spin consistency; the returner gains confidence pressing the second ball — both effects multiply break risk.",
        "conditions": "Amplified at high-leverage moments (break point already conceded), on fast surfaces, and in late-set situations with elevated stakes.",
        "magnitude": "Service games with 2+ DFs broken at ~55-65%; those with 0-1 DF broken at ~20-25%.",
        "links": ["one_bad_service_game_to_break_spiral", "first_serve_collapse_pressure_cascade", "unforced_error_streak_within_game"],
    },
    {
        "slug": "one_bad_service_game_to_break_spiral",
        "title": "Single-Loose-Game-to-Break Spiral",
        "summary": "One shaky service game — first-serve percentage below ~50% — substantially raises break probability in that game and, if broken, cascades into a set-score deficit that is rarely recovered.",
        "stat_signature": "Break probability when first-serve percentage <50%: ~55-65% versus baseline ~20-25%; a single early break converts to set loss at ~65-75% frequency absent a re-break.",
        "mechanism": "Low first-serve percentage exposes the weaker second serve to aggressive returns; the returner's confidence rises with each second-serve attack while the server's routine becomes tentative.",
        "conditions": "Most decisive on faster surfaces where second-serve pace drops are punished, against heavy returners, and early in a set when the structural damage of a break is largest.",
        "magnitude": "A single break secured after a first-serve collapse is converted to a set win at ~70% frequency when the set score is otherwise level.",
        "links": ["break_conceded_to_set_loss_cascade", "double_fault_cluster_cascade", "first_serve_collapse_pressure_cascade"],
    },
    {
        "slug": "break_conceded_to_set_loss_cascade",
        "title": "Break-Conceded-to-Set-Loss Cascade",
        "summary": "Conceding one break cascades into set loss without recovery at ~70-78% conditional rate because the breaker can play conservatively while the deficit holder must take escalating risks.",
        "stat_signature": "Conditional set-loss probability after falling one break down: ~0.70-0.78; re-break rate interrupting the cascade: ~22-30%, concentrated in the immediately following game.",
        "mechanism": "The one-break lead allows conservative high-percentage play; the trailer must force shots under pressure, elevating UEs while the leader's hold rate rises above baseline.",
        "conditions": "Strongest on clay and slow hard courts where holds are inherently reliable; attenuated on grass where serve dominance elevates re-break frequency.",
        "magnitude": "The ~70-78% set-loss rate after a single break is roughly 2.5-3x the set-loss rate when games are level.",
        "links": ["one_bad_service_game_to_break_spiral", "tiebreak_mini_break_runaway_cascade", "set_loss_carryover_intensity_drop"],
    },
    {
        "slug": "momentum_loss_after_squandered_break_point",
        "title": "Squandered-Break-Point Momentum Cascade",
        "summary": "Failing to convert 2+ break points in a single game deflates the attacker and raises the probability of losing the very next service game; the escaped server's hold rate rises comparably.",
        "stat_signature": "After a multi-break-point non-conversion, the attacker's subsequent hold rate drops ~8-15 percentage points; escaped-server hold rate rises comparably in the following game.",
        "mechanism": "Maximal effort without reward generates a contrast effect: attacker confidence erodes, escaped server gets a relief-driven arousal boost enhancing serve placement and aggression.",
        "conditions": "Strongest after 4+ break points squandered, at set-deciding moments, and in best-of-five formats where swings have time to materialise.",
        "magnitude": "A two-game swing following a multi-break-point escape occurs roughly 25-35% more often than the baseline two-game-swing rate.",
        "links": ["break_conceded_to_set_loss_cascade", "tightening_under_lead_choke_cascade", "momentum_run_of_games_compounding"],
    },
    {
        "slug": "tightening_under_lead_choke_cascade",
        "title": "Closing-Lead Tightening Cascade",
        "summary": "Serving for a set or match elevates break risk through conservative shot selection, reduced first-serve aggression, and compounding mental load — a self-reinforcing tightening cascade.",
        "stat_signature": "Break rate on serving-for-the-set games: 1.5-2x the match-average; first-serve speed drops 3-6 km/h; first-serve percentage falls 4-8 points below match baseline in these games.",
        "mechanism": "Closing awareness shifts attention from process cues (ball toss, rotation) to outcome cues, disrupting automated stroke production; conservative toss shortening reduces serve quality exactly when the returner is most motivated.",
        "conditions": "Most pronounced in decisive sets, against heavy returners, on slower courts, and for players with documented closing difficulty in their statistical profile.",
        "magnitude": "Players failing to close on the first serving-for-the-set opportunity lose that set in a tiebreak at ~55-65% frequency.",
        "links": ["double_fault_cluster_cascade", "first_serve_collapse_pressure_cascade", "tiebreak_mini_break_runaway_cascade"],
    },
    {
        "slug": "first_serve_collapse_pressure_cascade",
        "title": "First-Serve-Collapse Pressure Cascade",
        "summary": "A drop in first-serve percentage below ~55% compounds by exposing the weaker second serve to attack, elevating break-point-faced frequency through a two-stage cascade: fewer free points, then returner aggression.",
        "stat_signature": "Points won on serve drop from ~68-72% at 65%+ first-serve percentage to ~52-58% below 55%; break-point-faced frequency roughly doubles when first-serve percentage falls below 50%.",
        "mechanism": "Lower first-serve-in rate forces reliance on the second serve traveling 20-30 km/h slower; the returner steps in for early-ball attacks that pin the server defensively and extend rally length.",
        "conditions": "Amplified on fast surfaces, during windy conditions elevating double-fault risk, and against aggressive returners who step inside the baseline on second balls.",
        "magnitude": "A service game with first-serve percentage below 50% carries ~55-65% break probability versus a ~18-22% baseline at 65%+ first-serve percentage.",
        "links": ["double_fault_cluster_cascade", "return_pressure_snowball_on_second_serve", "serve_plus_one_breakdown_cascade"],
    },
    {
        "slug": "return_pressure_snowball_on_second_serve",
        "title": "Second-Serve Return-Pressure Snowball",
        "summary": "An aggressive returner punishing weak second serves compounds into repeated break-point exposure across consecutive service games as each successful second-serve attack raises returner aggression and deepens the server's defensive posture.",
        "stat_signature": "Servers yielding 55%+ second-serve points face break points in ~65-70% of service games versus ~35% when winning 55%+ of second-serve points.",
        "mechanism": "Each successful early-ball attack reinforces the returner's positioning; the server adapts by reducing second-serve pace further (safer margin), deepening vulnerability in a feedback loop.",
        "conditions": "Strongest against players standing inside the baseline on return, on slow-bouncing clay, and for servers with limited kick and slice variety on the second ball.",
        "magnitude": "A set in which the server loses 60%+ of second-serve points is lost at ~70-80% frequency, roughly 1.8-2.2x the baseline set-loss rate.",
        "links": ["first_serve_collapse_pressure_cascade", "deuce_game_pressure_compounding", "serve_plus_one_breakdown_cascade"],
    },
    {
        "slug": "set_loss_carryover_intensity_drop",
        "title": "Set-Loss Carryover Intensity-Drop Cascade",
        "summary": "Losing a tight set, especially via tiebreak, cascades into a deflated start to the following set: the early-break-conceded rate rises ~30-45% for the set loser, compounding the structural deficit.",
        "stat_signature": "First-to-break frequency in the game immediately following a set loss: ~30-40% for the loser versus ~22% baseline; tiebreak-set losers concede an early break in the next set ~35-45% of the time.",
        "mechanism": "A close set loss activates ruminative processing that competes with execution focus; the winner's momentum carries forward through heightened serve and return confidence.",
        "conditions": "Strongest after tiebreak losses (maximum emotional investment), in best-of-three formats where each set carries full structural weight.",
        "magnitude": "A 10-18 percentage-point increase in probability of going down an early break in the subsequent set following a tiebreak loss.",
        "links": ["break_conceded_to_set_loss_cascade", "tiebreak_mini_break_runaway_cascade", "momentum_run_of_games_compounding"],
    },
    {
        "slug": "rally_length_error_accumulation_cascade",
        "title": "Extended-Rally Error-Accumulation Cascade",
        "summary": "Repeated long rallies compound physical and cognitive load into rising error rates: unforced-error probability rises sharply beyond ~9 shots per rally, accumulating into meaningful set-level degradation.",
        "stat_signature": "UE rate on rallies of 9+ shots is 1.8-2.5x the rate on 1-4 shot rallies; in sets with average rally length exceeding 5 shots, UE total rises ~25-40% above baseline.",
        "mechanism": "Extended rallies deplete working memory (court positioning, shot sequencing) and slow motor unit recruitment; subsequent shot selection becomes reactive rather than proactive, increasing error risk on directional changes.",
        "conditions": "Strongest on clay and slow hard courts, in warm humid conditions accelerating fatigue, and against opponents whose style deliberately extends rallies.",
        "magnitude": "The unforced-error rate differential between short-rally and 9+-shot-rally performance represents a ~15-25 percentage-point gap in points-won probability.",
        "links": ["physical_fatigue_decline_third_set_cascade", "wing_targeted_breakdown_cascade", "post_error_rushed_selection_cascade"],
    },
    {
        "slug": "tiebreak_mini_break_runaway_cascade",
        "title": "Tiebreak Mini-Break Runaway Cascade",
        "summary": "An early mini-break in a tiebreak compounds through serve-rotation advantage and pressure asymmetry: the leader holds while the deficit player must break back on return, with win probability rising sharply at each mini-break gained.",
        "stat_signature": "Conditional tiebreak-win probability after the first mini-break: ~0.68-0.74; after a 3-0 lead: ~0.85+; runaway scores (7-2, 7-1) occur more often than the uniform model predicts.",
        "mechanism": "The mini-break shifts serve rotation favourably; each successful hold extends the gap while the deficit player faces break-back requirements on every return game — asymmetric pressure that compounds.",
        "conditions": "Strongest on fast indoor surfaces where holds are near-automatic, at 6-6 in decisive sets, and against opponents with limited tiebreak clutch-serve records.",
        "magnitude": "A 3-1 mini-break lead translates to tiebreak win ~80-85% of the time — one of the sharpest leverage inflections in tennis.",
        "links": ["break_conceded_to_set_loss_cascade", "set_loss_carryover_intensity_drop", "tightening_under_lead_choke_cascade"],
    },
    {
        "slug": "deuce_game_pressure_compounding",
        "title": "Deuce-Game Pressure-Compounding Dynamic",
        "summary": "A service game stretching to multiple deuces compounds break probability with each additional deuce as the server's first-serve percentage declines and the returner's pattern recognition improves through repeated exposure.",
        "stat_signature": "Hold probability: ~80% at first deuce, ~67% at second deuce, ~57% at third deuce; each additional deuce beyond the first reduces hold probability by ~5-8 percentage points.",
        "mechanism": "Each additional deuce represents a new break-point survived at cost: serve urgency lifts, first-serve percentage falls further, and the returner recognises serve tendencies from repeated within-game exposure.",
        "conditions": "Most consequential in set-decisive games (5-5, 6-5), against accurate returners maintaining high contact quality under pressure.",
        "magnitude": "A game reaching three-plus deuces is broken at ~3-4x the frequency of a clean hold game.",
        "links": ["unforced_error_streak_within_game", "double_fault_cluster_cascade", "return_pressure_snowball_on_second_serve"],
    },
    {
        "slug": "serve_plus_one_breakdown_cascade",
        "title": "Serve-Plus-One Breakdown Cascade",
        "summary": "Degradation of the first-strike serve-plus-one pattern cascades into longer defensive rallies the server is structurally ill-suited to win, as the first-ball advantage disappears and the returner dictates court position.",
        "stat_signature": "First-three-shot points won drops from 70-80% at 65%+ first-serve percentage to 55-65% below 55%; average rally length on service points rises 1.5-2.5 shots, pushing the player into defensive-rally territory.",
        "mechanism": "The serve-plus-one depends on a reliable first serve creating an exploitable second-ball response; when the first serve rate drops, the second ball arrives from a less dominant position, negating the planned attack.",
        "conditions": "Most pronounced for aggressive baseliners and serve-volleyers, against returners who redirect pace deep, and in conditions (wind, slow surface) reducing serve-pace advantage.",
        "magnitude": "A set where the server fails to win 60%+ of first-three-shot rallies is lost at ~65-70% frequency.",
        "links": ["first_serve_collapse_pressure_cascade", "return_pressure_snowball_on_second_serve", "rally_length_error_accumulation_cascade"],
    },
    {
        "slug": "momentum_run_of_games_compounding",
        "title": "Run-of-Games Compounding Dynamic",
        "summary": "Consecutive games won self-reinforce through rising confidence and opponent deflation: runs of three-plus games extend to five-plus at rates above the independent-game model, shaping set outcomes disproportionately.",
        "stat_signature": "Conditional probability a run of three consecutive games extends to five-plus: ~0.55-0.65 versus ~0.42-0.48 under independence; games-streak distributions are over-dispersed relative to geometric.",
        "mechanism": "Multi-game runs elevate serve aggression while simultaneously depressing the losing player's first-serve percentage and return intent; the compounding is bidirectional across both players.",
        "conditions": "Strongest on clay where points are longer and momentum accumulates, after a lost set triggers carryover deflation, and in third-set scenarios with cumulative energy deficits.",
        "magnitude": "Runs of five consecutive games occur roughly 25-35% more often than the independent-game model predicts, indicating meaningful cascade amplification.",
        "links": ["set_loss_carryover_intensity_drop", "tiebreak_mini_break_runaway_cascade", "momentum_loss_after_squandered_break_point"],
    },
    {
        "slug": "post_error_rushed_selection_cascade",
        "title": "Post-Error Rushed-Selection Cascade",
        "summary": "An unforced error prompts an over-corrective shot choice — too defensive or too aggressive — that compounds into a further error on the immediately following point through a brief attentional disruption cycle.",
        "stat_signature": "Error rate on the point immediately following an UE: ~1.25-1.5x the unconditional per-point rate; double-error sequences occur ~1.3-1.7x more often than the independent per-point product predicts.",
        "mechanism": "Post-error self-monitoring redirects attentional resources from ball tracking and footwork to error analysis; over-correction in either direction (extreme caution or aggression) reflects pressure-induced decision simplification.",
        "conditions": "Most pronounced after errors on critical points (break point, set point), under time pressure, and for players with high self-criticism tendencies visible in in-match reactions.",
        "magnitude": "Three consecutive point pairs with elevated error risk represent a 2-3 game vulnerability window within a service or return game.",
        "links": ["unforced_error_streak_within_game", "rally_length_error_accumulation_cascade", "wing_targeted_breakdown_cascade"],
    },
    {
        "slug": "wing_targeted_breakdown_cascade",
        "title": "Targeted-Wing Breakdown Cascade",
        "summary": "Relentless opponent pressure on a weaker wing compounds errors off that side as it fatigues structurally and cognitively, with rising UE rate and a growing share of lost points ending on the targeted wing.",
        "stat_signature": "UE rate on the targeted wing rises ~1.4-1.9x from the first two games to the final two of an extended set; lost-point share ending on the weaker wing often crosses 60-70% under systematic targeting.",
        "mechanism": "Repeated high-load shots to one wing produce selective muscle fatigue and shortened preparation time; reduced racket-head speed and earlier contact degradation create a self-reinforcing cycle inviting further targeting.",
        "conditions": "Strongest on clay against heavy topspin opponents, for players with single-handed backhands under high balls, and in third sets with cumulative wing fatigue.",
        "magnitude": "Sets with sustained wing targeting see the targeted player's hold rate drop ~8-15 percentage points from the first-set baseline.",
        "links": ["rally_length_error_accumulation_cascade", "physical_fatigue_decline_third_set_cascade", "post_error_rushed_selection_cascade"],
    },
    {
        "slug": "physical_fatigue_decline_third_set_cascade",
        "title": "Late-Set Physical-Fatigue Decline Cascade",
        "summary": "Accumulated physical load from extended prior-set duration compounds into decisive-set service and movement decline, measured as drops in first-serve speed, court coverage, and points-won on serve in the final set.",
        "stat_signature": "First-serve speed declines 3-8 km/h from set 1 to the decisive set in matches exceeding 2.5 hours; points-won on serve in the decisive set drop ~5-10 percentage points; sprints per rally decline 15-25% in sets 3+.",
        "mechanism": "Sustained effort depletes phosphocreatine and glycogen stores, slowing neuromuscular firing rates; serve toss accuracy degrades with shoulder fatigue, reducing placement variety; lateral slowdown opens the court for opponent attacks.",
        "conditions": "Strongest in best-of-five formats, on clay with prolonged baseline exchanges, at high-altitude venues, and for physically lighter players against heavy-groundstroke opponents.",
        "magnitude": "Decisive-set performance degradation represents roughly a 5-12 percentage-point reduction in points-won on serve and a 10-18% increase in UE rate versus the first-set baseline.",
        "links": ["rally_length_error_accumulation_cascade", "wing_targeted_breakdown_cascade", "serve_plus_one_breakdown_cascade"],
    },
]
