"""Soccer ErrorCascades concept spec — person-free, dense, calibration-only intelligence."""
from __future__ import annotations

SPORT = "Soccer"
FAMILY = "ErrorCascades"

CONCEPTS = [
    {
        "slug": "turnover_to_counterattack_cascade",
        "title": "Possession-Loss to Counterattack Cascade",
        "summary": "A giveaway in the attacking third with players committed forward cascades into a high-value transition chance against; xG-against per attacking-third turnover runs 2-4x the settled-possession baseline.",
        "stat_signature": "xG-against per attacking-third turnover ~0.08-0.14 versus ~0.03 per settled defensive action; shots conceded within 10 s of loss ~1 per 6-8 such turnovers; bottom-third possession-security teams concede ~0.4 additional xG-against per 90.",
        "mechanism": "Committing fullbacks and a high defensive line shortens recovery distance to goal while ball-winners advance; a single dispossession inverts numerical balance instantly, leaving the defensive third exposed before shape is restored.",
        "conditions": "Most pronounced against deep-lying fast forwards and teams that train structured counter-press breaks; amplified in open games with high possession-share and when the trailing team chases the game late.",
        "magnitude": "Teams conceding 4+ attacking-third turnovers per 90 face roughly 0.35-0.55 additional xG-against per match attributable to transition exposure alone.",
        "links": ["high_press_break_line_overload_cascade", "fullback_caught_upfield_exposure_cascade", "chasing_game_press_overcommit_concession", "transition_outnumbered_recovery_failure"],
    },
    {
        "slug": "conceding_then_chasing_shape_disintegration",
        "title": "Concede-Then-Chase Shape Disintegration",
        "summary": "Conceding a goal prompts a more committed attacking posture that opens structural gaps, measurably raising xG-against per 90 and the conditional probability of a second concession within 15 minutes.",
        "stat_signature": "Conditional P(second goal within 15 min | first conceded) ~0.22-0.28 versus unconditional rate ~0.10; xG-against per 90 rises ~25-40% in the 20 minutes following concession; defensive-line height increases ~3-6 m.",
        "mechanism": "Trailing teams push higher and flood midfield, compressing recovery space; the midfield filter thins, isolating center-backs against runners, while the opponent gains more ground per carry.",
        "conditions": "Effect strongest when the goal is conceded before the 60th minute; amplified against tactically flexible opponents who can shift between possession and counter modes rapidly.",
        "magnitude": "Teams conceding first show a match-level xG-against uplift of ~0.3-0.5 attributable to shape disintegration beyond the baseline defensive exposure.",
        "links": ["early_concession_gameplan_abandonment_cascade", "chasing_game_press_overcommit_concession", "fatigue_late_block_breakdown_cascade"],
    },
    {
        "slug": "high_press_break_line_overload_cascade",
        "title": "Press-Bypass Line-Overload Cascade",
        "summary": "A single press-resistant pass breaking the first line cascades into a numerical overload behind the press, with the receiving unit carrying or playing into space before midfield can recover.",
        "stat_signature": "~35-50% of high-press engagements bypassed in one pass result in a chance within 8 s; xT gain per bypassing pass ~0.06-0.12 versus ~0.01 for a non-bypass press escape; progressive-carry distance after bypass averages 18-25 m.",
        "mechanism": "A pressing line sacrifices positional compactness for collective forward pressure; one accurate vertical ball invalidates the entire press unit's position, and the compact shape that enabled pressing now creates the exploitable space.",
        "conditions": "Most pronounced against high-defensive-line pressers when facing a keeper or center-back with distribution quality; amplified on large pitches and when the press triggers without a proper press-trap cue.",
        "magnitude": "Teams with below-median press-trap success (under ~55%) concede roughly 0.25-0.40 additional xG-against per 90 from bypass sequences.",
        "links": ["turnover_to_counterattack_cascade", "goalkeeper_distribution_error_cascade", "midfield_bypass_isolation_cascade"],
    },
    {
        "slug": "individual_error_to_goal_chain",
        "title": "Individual-Error-to-Goal Chain",
        "summary": "A control or pass error in the defensive half chains directly into a shot or goal against, with error-induced chances converting at roughly 2.5-4x the rate of open-play chances due to proximity and positioning advantage.",
        "stat_signature": "Goal conversion rate of error-induced chances ~0.25-0.40 versus open-play conversion ~0.08-0.12; average xG of an error-induced shot ~0.22 versus open-play average ~0.09; ~6-8% of all top-flight goals trace directly to a coded defensive error.",
        "mechanism": "An error in the defensive third eliminates recovery time and removes the defensive structure's ability to reduce shot angle; the attacker arrives with pace and clear sight of goal from close range.",
        "conditions": "Frequency rises under high-press opposition, late in matches when cognitive load increases, and on difficult playing surfaces; keepers and center-backs account for the largest share of error-linked goals.",
        "magnitude": "A top-quartile-error defensive unit concedes roughly 3-5 additional error-linked goals per season relative to a median unit.",
        "links": ["goalkeeper_distribution_error_cascade", "marking_handover_breakdown_cascade", "offside_trap_break_cascade"],
    },
    {
        "slug": "set_piece_second_phase_scramble_cascade",
        "title": "Set-Piece Second-Phase Scramble Cascade",
        "summary": "A cleared-but-not-controlled set piece cascades into compounding second-phase chances, with cumulative xG across recycled phases substantially exceeding the first-contact clearance outcome.",
        "stat_signature": "Cumulative xG across second and third phases when the first clearance is recovered by the attacking team ~0.06-0.10; ~40-55% of corner-phase xG comes from second or later shots; second-phase recovery rate for attackers ~45-60% on partial clearances.",
        "mechanism": "A partial clearance lands in space where the attacking team has pre-loaded runners; the defending unit transitions from set-piece shape to open-play shape, leaving pockets of space at the edge of the penalty area.",
        "conditions": "Most acute when the defending team relies on clearance-only rather than controlled distribution; amplified when attackers have designated second-phase runners at the 18-yard line.",
        "magnitude": "Teams conceding the highest second-phase xG allow ~0.10-0.15 additional xG per defensive set piece relative to the cleanest-clearance units.",
        "links": ["rebound_recycle_sustained_siege_cascade", "second_ball_loss_compounding_pressure", "marking_handover_breakdown_cascade"],
    },
    {
        "slug": "fullback_caught_upfield_exposure_cascade",
        "title": "Fullback-Caught-Upfield Exposure Cascade",
        "summary": "An attacking fullback dispossessed high cascades into a wide overload behind the defensive line, with the vacated flank generating elevated xT and conditional cross or cutback chances at high rates.",
        "stat_signature": "xT conceded down a vacated flank per fullback-dispossession event ~0.05-0.09; conditional cross or cutback attempt rate when fullback fails to recover within 6 s ~60-75%; resulting chance xG from crosses into vacated flank ~0.10-0.16 versus ~0.07 baseline.",
        "mechanism": "Advanced fullback roles create a structural gap behind; losing the ball before recovery position forces the center-back to step wide, opening the central channel simultaneously with the flank.",
        "conditions": "Strongest against fast wide forwards who can receive and accelerate in behind; more frequent in teams with aggressive overlapping instructions and when the central midfielder fails to cover the vacated zone.",
        "magnitude": "A team with top-quartile fullback-dispossession events concedes roughly 0.20-0.35 additional xG-against per 90 from wide-exposure chains.",
        "links": ["turnover_to_counterattack_cascade", "wide_overload_switch_exploitation_cascade", "transition_outnumbered_recovery_failure"],
    },
    {
        "slug": "goalkeeper_distribution_error_cascade",
        "title": "Goalkeeper-Distribution-Error Cascade",
        "summary": "A misplaced build-up pass from the keeper or back line cascades into a high-quality chance in the defensive third, with resulting shot proximity and xG far above the open-play average.",
        "stat_signature": "xG-against per build-up turnover inside the defensive third ~0.18-0.30; average shot distance on resulting chances ~10-14 m versus ~18 m open-play; ~1 in 5 defensive-third turnovers leads to a shot attempt within 5 s.",
        "mechanism": "A short-pass build-up system concentrates ball-playing in the area with the smallest error margin; a miscontrolled or intercepted ball leaves the keeper out of position and attackers between defenders and goal.",
        "conditions": "Highest under aggressive high-press opposition; amplified when the defensive structure has no long-ball safety valve and when the keeper's distribution metrics fall below squad median.",
        "magnitude": "Bottom-fifth possession-security teams concede ~0.3-0.5 additional xG-against per 90 from back-line turnover chains.",
        "links": ["high_press_break_line_overload_cascade", "individual_error_to_goal_chain", "turnover_to_counterattack_cascade"],
    },
    {
        "slug": "transition_outnumbered_recovery_failure",
        "title": "Outnumbered-Transition Recovery-Failure Cascade",
        "summary": "Failure to delay an even or outnumbered break cascades into a clear-cut chance, with undelayed breaks converting at roughly double the rate of delayed ones.",
        "stat_signature": "Conversion rate of undelayed 2-on-1 breaks ~0.32-0.45 versus delayed equivalents ~0.15-0.22; xG of undelayed 1-on-1 situations ~0.38-0.50; a recovery delay of 4+ s reduces conversion probability by ~30-40%.",
        "mechanism": "A recovering defender's primary role is to compress time and angle rather than win the ball; absence of delay leaves the attacker free to choose timing and shot type, maximising decision-quality advantage.",
        "conditions": "Most apparent against fast counter-attacking units and in the final 20 minutes when pressing intensity has dropped; amplified when center-backs are caught high from a set piece or attacking phase.",
        "magnitude": "Transitional sequences with zero recovery delay yield ~0.20-0.30 more xG per event than those with at least one delaying action completed.",
        "links": ["turnover_to_counterattack_cascade", "fullback_caught_upfield_exposure_cascade", "midfield_bypass_isolation_cascade"],
    },
    {
        "slug": "second_ball_loss_compounding_pressure",
        "title": "Second-Ball-Loss Compounding-Pressure Cascade",
        "summary": "Repeatedly losing second balls after clearances sustains and compounds opponent siege pressure, measured by second-ball recovery rate and the resulting consecutive box-entry and shot frequency.",
        "stat_signature": "Teams with second-ball recovery rate below 40% in the defensive third allow ~1.8-2.4 additional box entries per clearance sequence versus teams above 55%; sustained-pressure spells produce xG at ~0.04-0.07 per spell; shot frequency rises ~60% during siege.",
        "mechanism": "Clearance without control returns possession to the attacker in open space outside the penalty area; repeated resets deny the defending team the positional reset needed to restore shape, deepening the compressive cycle.",
        "conditions": "Most damaging late in tight matches when defensive energy reserves are depleted; amplified when the attacking team has designated second-ball players stationed at the edge of the area.",
        "magnitude": "A bottom-quartile second-ball unit faces roughly 0.15-0.25 additional xG-against per 90 attributable to compounded siege sequences.",
        "links": ["set_piece_second_phase_scramble_cascade", "rebound_recycle_sustained_siege_cascade", "fatigue_late_block_breakdown_cascade"],
    },
    {
        "slug": "offside_trap_break_cascade",
        "title": "Offside-Trap-Break Cascade",
        "summary": "A mistimed offside line cascades into a runner played clean through, generating one-on-one chances with very high xG due to proximity and positional advantage.",
        "stat_signature": "xG of through-balls that beat a broken offside line ~0.35-0.55; conditional 1-on-1 chance rate when trap fails to step in unison ~70-85%; teams using high-line traps that fail once per 90 concede ~0.35-0.50 additional xG per failure event.",
        "mechanism": "A high defensive line executing an offside trap requires perfect synchrony; one defender stepping late leaves an attacker onside and behind the line, eliminating every structural defensive advantage simultaneously.",
        "conditions": "Highest risk against units with fast strikers who time runs off the ball; amplified when communication between center-backs degrades under pressure or when a substitute occupies one side of the line.",
        "magnitude": "A single successful trap-break yields xG comparable to a penalty (~0.40-0.55), making each failure disproportionately costly relative to the average concession.",
        "links": ["transition_outnumbered_recovery_failure", "individual_error_to_goal_chain", "midfield_bypass_isolation_cascade"],
    },
    {
        "slug": "fatigue_late_block_breakdown_cascade",
        "title": "Fatigue-Driven Late Block-Breakdown Cascade",
        "summary": "Accumulated high-intensity running late in a match compounds into structural defensive gaps, raising inter-line spacing and xG-against per box entry in the final 15 minutes for high-running teams.",
        "stat_signature": "Inter-line spacing increases ~2-4 m in minutes 75-90 versus 30-45 for high-intensity-distance teams; xG-against per box entry rises ~20-35% in the final 15 minutes; top-quartile sprint-distance teams show ~0.15-0.25 additional xG-against in the last 20 minutes.",
        "mechanism": "Neuromuscular fatigue degrades positional discipline needed to maintain compact block shape; gaps open between defensive and midfield lines, exploited by late-match rotations and delivery into the channels.",
        "conditions": "Most pronounced after 120+ minutes or in a second match within three days; amplified when the substitution window is exhausted and no fresh legs can be introduced into the defensive shape.",
        "magnitude": "High-load teams concede roughly 0.20-0.40 additional xG-against in the final 15 minutes relative to the per-minute rate across the first 60 minutes.",
        "links": ["compressed_block_late_game_concession_spiral", "second_ball_loss_compounding_pressure", "transition_outnumbered_recovery_failure"],
    },
    {
        "slug": "rebound_recycle_sustained_siege_cascade",
        "title": "Rebound-Recycle Sustained-Siege Cascade",
        "summary": "A blocked or saved shot recycled by the attacker compounds into repeated shots within one possession, with cumulative xG of the full sequence well above the single-shot baseline.",
        "stat_signature": "Cumulative xG across all shots in a recycled possession ~0.12-0.22 versus a one-shot-and-clear outcome at ~0.06; ~30-40% of rebounds inside the six-yard box result in a second shot; rebound-shot xG averages ~0.18-0.30 due to proximity and scrambled keeper positioning.",
        "mechanism": "A shot deflected by the keeper or post leaves the ball in a contested zone where attackers have momentum and defenders are repositioning from their shot-blocking stance; the keeper's position is compromised.",
        "conditions": "Most frequent in sustained set-piece phases and when attackers pre-position second-phase runners; amplified when the keeper's dive commits them beyond recovery range for a second-post rebound.",
        "magnitude": "Sustained recycled possessions yield roughly 2-3x the xG of single-shot cleared sequences, making second-phase recovery a material defensive priority.",
        "links": ["set_piece_second_phase_scramble_cascade", "second_ball_loss_compounding_pressure", "marking_handover_breakdown_cascade"],
    },
    {
        "slug": "midfield_bypass_isolation_cascade",
        "title": "Midfield-Bypass Defender-Isolation Cascade",
        "summary": "A pass that takes out the midfield line cascades into a center-back isolated against a runner, with the resulting 1-on-1 or 2-on-2 generating high-xG chances from open-field carries.",
        "stat_signature": "Frequency of midfield-bypass passes leading to an isolated center-back ~8-14% of all progressive long passes; resulting chance xG ~0.12-0.22; chance creation rate from such isolations ~1 per 3-4 bypass events against a high-line defense.",
        "mechanism": "Midfielders serving as a positional shield are taken out of the play in a single action, removing the structural layer between the press and the back four; center-backs must defend with pace they are not calibrated for.",
        "conditions": "Most damaging against teams with a flat or narrow midfield four; amplified when the attacker has a pace differential over the covering center-back and when fullbacks are committed in wide positions.",
        "magnitude": "A successful midfield-bypass sequence yields approximately 0.10-0.20 xG above the mean possession value of a normal build-up progression.",
        "links": ["high_press_break_line_overload_cascade", "offside_trap_break_cascade", "transition_outnumbered_recovery_failure"],
    },
    {
        "slug": "chasing_game_press_overcommit_concession",
        "title": "Chasing-Game Press-Overcommit Concession Cascade",
        "summary": "An aggressive equalizing press while trailing cascades into space conceded on the break, with xG-against per high-press engagement when trailing notably higher than when level or ahead.",
        "stat_signature": "xG-against per high-press engagement when trailing by 1+ goals ~0.055-0.085 versus ~0.025-0.040 when level; conditional fast-break concession rate against a settled defense ~18-28%; press PPDA drops ~20-35% when trailing, indicating higher but less controlled intensity.",
        "mechanism": "Urgency to equalize drives higher-risk pressing triggers; structural compactness is sacrificed for press coverage, and a press escape is more damaging because recovery distances are longer with the team pushed forward.",
        "conditions": "Sharpest in the final 25 minutes when a trailing team intensifies the press against opponents who prefer to absorb and counter; amplified when the opponent has fresh legs through late substitution.",
        "magnitude": "A trailing team pressing aggressively concedes roughly 0.15-0.30 additional xG-against per 90 compared to its baseline settled-defensive exposure.",
        "links": ["conceding_then_chasing_shape_disintegration", "turnover_to_counterattack_cascade", "early_concession_gameplan_abandonment_cascade"],
    },
    {
        "slug": "marking_handover_breakdown_cascade",
        "title": "Marking-Handover Breakdown Cascade",
        "summary": "A failed pass-off between zonal and man markers cascades into a free attacker in the box, with the resulting unmarked-shot xG substantially above a properly tracked equivalent.",
        "stat_signature": "Share of conceded box chances preceded by a marking-handover error ~12-18%; unmarked-shot xG from handover breakdown ~0.18-0.28 versus ~0.10 for marked equivalents; set-piece handover errors account for ~35-45% of all marking-breakdown chances.",
        "mechanism": "Hybrid zonal and man-marking systems require a clear trigger for responsibility transfer; ambiguous triggers or communication failures leave a runner owned by neither defender at the moment of delivery.",
        "conditions": "Most frequent on near-post and second-phase delivery where defenders must simultaneously track a mover and defend a delivery zone; amplified by late-game fatigue and complex attacking movement schemes.",
        "magnitude": "An above-average-error marking unit concedes roughly 2-4 additional goals per season from free-attacker situations relative to a low-error unit.",
        "links": ["set_piece_second_phase_scramble_cascade", "individual_error_to_goal_chain", "rebound_recycle_sustained_siege_cascade"],
    },
    {
        "slug": "early_concession_gameplan_abandonment_cascade",
        "title": "Early-Concession Game-Plan-Abandonment Cascade",
        "summary": "Conceding early forces premature abandonment of the intended structure, cascading into an open end-to-end pattern with elevated total-match xG for both sides.",
        "stat_signature": "Matches with a goal in the first 20 minutes show total-match xG ~15-25% higher than scoreless matches to the same point; transitions per 90 rise ~30-50% after an early opener; both-teams-score rate rises ~12-18 percentage points when the match is opened before the 20th minute.",
        "mechanism": "An early deficit collapses the intended tactical identity; a possession-dominant team must open up, while a counter-attacking team faces opponents willing to trade blows, fundamentally changing the game's structural character.",
        "conditions": "Most pronounced when the early goal arrives against the intended style — a possession side conceding on the break, or a defensive side conceding before setting their block.",
        "magnitude": "An early concession adds roughly 0.25-0.45 xG to the total-match expected tally for both sides combined, reflecting genuine structural opening of the game.",
        "links": ["conceding_then_chasing_shape_disintegration", "chasing_game_press_overcommit_concession", "compressed_block_late_game_concession_spiral"],
    },
    {
        "slug": "compressed_block_late_game_concession_spiral",
        "title": "Deep-Block Late-Game Concession Spiral",
        "summary": "Sustained deep defending while protecting a lead compounds pressure into late concessions, as xG-against per 10 minutes and box entries allowed rise across the final 20 minutes for compact low-block teams.",
        "stat_signature": "xG-against per box entry rises ~15-30% in the 70th-90th minutes versus 50th-70th minutes for teams holding a low block; box entries per 10 minutes increase ~20-40% as the game narrows; final-15-minute xG-against for compacted blocks ~0.12-0.20.",
        "mechanism": "A compact defensive block gradually narrows the attacking angles available to the opponent, but sustained pressure degrades the block's compactness through fatigue and accumulated positional drift, exposing gaps at the edge of the area.",
        "conditions": "Most apparent when protecting a single-goal lead in the final 20 minutes against high-possession attackers; amplified when substitution options are exhausted and the pressing unit lacks fresh intensity.",
        "magnitude": "Teams holding a deep block in the final 20 minutes show roughly 0.15-0.25 additional xG-against per 10 minutes relative to the first-half defensive baseline.",
        "links": ["fatigue_late_block_breakdown_cascade", "second_ball_loss_compounding_pressure", "early_concession_gameplan_abandonment_cascade"],
    },
    {
        "slug": "wide_overload_switch_exploitation_cascade",
        "title": "Switch-of-Play Overload-Exploitation Cascade",
        "summary": "Ball-side over-commitment cascades into a quick switch that finds a free attacker on the weak side, with the resulting xT gain and unmarked cross or shot opportunity rate well above the settled-attack baseline.",
        "stat_signature": "xT gain of switches into a vacated flank ~0.07-0.13 versus ~0.02 for recycled ball-side possession; unmarked-attacker rate on weak-side switches ~55-70%; resulting cross or shot attempts from wide switches are ~30-50% more likely to produce a chance than non-switch deliveries.",
        "mechanism": "A defensive structure drawn to the ball side compresses recovery distances on that flank but simultaneously vacates the opposite channel; a single accurate diagonal switches the numerical balance, leaving the far winger or overlapping run unmarked.",
        "conditions": "Most effective against narrow defensive blocks or teams that aggressively shift their entire shape to the ball; amplified in wide-pitch environments and when the switching pass finds a player with delivery quality.",
        "magnitude": "A team conceding 3+ successful wide switches per 90 faces roughly 0.15-0.30 additional xG-against attributable to overload exploitation sequences.",
        "links": ["fullback_caught_upfield_exposure_cascade", "turnover_to_counterattack_cascade", "midfield_bypass_isolation_cascade"],
    },
]
