"""ExperienceComposure Soccer — person-free concept nodes.

Angle: psychological and decision-quality layer of high-stakes execution —
composure under elimination pressure, hostile-environment retention, post-shock
recovery, and the concentration disciplines that separate composed units from
fragile ones.  Distinct from ClosingExecution (lead mechanics), DisciplineControl
(general foul profile), and SpecialSituations (delivery mechanics).
"""
from __future__ import annotations

SPORT = "Soccer"
FAMILY = "ExperienceComposure"

CONCEPTS = [
    {
        "slug": "penalty_kick_composure",
        "title": "Penalty-Kick Composure",
        "summary": "Conversion stability in high-leverage spot kicks, isolating the pressure component by comparing knockout-fixture conversion against the same squad's overall penalty baseline.",
        "stat_signature": "Overall penalty conversion ~75-80%; in knockout/title-deciding fixtures it drops to ~65-72% for pressure-fragile units and holds ~76-80% for composed ones; placement-zone dispersion and keeper-correct-dive rate widen under elevated stakes.",
        "mechanism": "A penalty is a constrained skill whose execution is almost purely psychological under stakes; committing to placement before the run-up and executing an automatic routine suppresses conscious over-control, so composure is the degree to which conversion rate is invariant to contextual pressure.",
        "conditions": "Most diagnostic in knockout rounds and must-win league matches; aggregate squad trends across multiple seasons are more informative than single-match samples given small per-match penalty counts.",
        "magnitude": "A ~8-12 pp conversion drop under high-stakes versus routine conditions is a meaningful composure signal; systematic across a squad it quantifies a pressure vulnerability.",
        "links": ["shootout_nerve_steadiness", "big_match_decision_calm", "high_leverage_finishing_steadiness", "set_piece_concentration_late"],
    },
    {
        "slug": "shootout_nerve_steadiness",
        "title": "Shootout Nerve Steadiness",
        "summary": "Retention of placement quality across the escalating pressure sequence of a penalty shootout, with per-kick conversion and shot-placement variance tracked from the first kick through sudden-death rounds.",
        "stat_signature": "Overall shootout conversion ~70-75%; kicks 4-5 and sudden-death kicks convert ~5-12 pp less for fragile squads; placement-zone variance rises as takers abandon committed routines for safer, more stoppable corners.",
        "mechanism": "Each kick is an independent task made harder by mounting elimination stakes; takers who maintain pre-loaded automatic placement routines resist the conscious deliberation that degrades accuracy, so nerve steadiness is the capacity to suppress score-contingent anxiety across sequential kicks.",
        "conditions": "Relevant only in knockout competitions with tied scores; most diagnostic across a full roster of trained takers rather than from individual-kick samples; preparation depth (all outfield players trained and ordered) is a measurable advantage.",
        "magnitude": "A ~5 pp shootout-conversion edge converts roughly one additional kick in a five-kick sequence — a decisive distributional advantage that is entirely within training and selection control.",
        "links": ["penalty_kick_composure", "big_match_decision_calm", "post_red_card_adaptation_composure", "two_legged_tie_aggregate_savvy"],
    },
    {
        "slug": "big_match_decision_calm",
        "title": "Big-Match Decision Calm",
        "summary": "Retention of progressive-pass accuracy and turnover discipline in knockout or title-deciding matches, measuring whether decision quality degrades when amplified stakes make every error visible.",
        "stat_signature": "Composed units hold progressive-pass completion within ~2-3 pp of their league baseline in high-stakes fixtures; pressure-fragile ones drop ~5-9 pp; in-possession turnover rate rises ~1.5-3 pp under elevated pressure, representing several additional costly losses per match.",
        "mechanism": "Elevated stakes increase cognitive load and the tendency to rush or select overly safe options; a unit maintaining its normal decision tempo and pass-selection preserves its structural threat, while one that hurries creates turnovers and reverts to low-value direct play.",
        "conditions": "Most measurable in knockout rounds, finals, and top-of-table clashes; amplified in hostile away environments; more informative at squad-level across several high-stakes fixtures than in single-match samples.",
        "magnitude": "A ~6 pp progressive-pass-accuracy drop in big matches is comparable to losing a key creative midfielder — it reduces xG output in proportion to the reduction in progressions reaching the final third.",
        "links": ["hostile_atmosphere_execution", "penalty_kick_composure", "high_leverage_finishing_steadiness", "trailing_urgency_balance", "comeback_composure_after_concession"],
    },
    {
        "slug": "hostile_atmosphere_execution",
        "title": "Hostile-Atmosphere Execution",
        "summary": "Retention of passing rhythm and disciplinary control in intimidating away environments, measured by the away-minus-home differential in pass-completion and caution rate beyond what standard home advantage accounts for.",
        "stat_signature": "Standard home advantage suppresses away pass-completion ~2-4 pp; atmosphere-fragile units show an additional ~3-6 pp suppression in high-decibel hostile grounds; caution rate rises ~20-30% in hostile atmospheres for reactive sides versus ~5-10% for disciplined ones.",
        "mechanism": "Crowd noise disrupts communication, raises arousal, and creates reactive fouling as players respond to perceived referee partiality; a composed unit isolates execution from these stimuli, maintaining normal communication and pre-match foul-avoidance discipline.",
        "conditions": "Most pronounced in full high-intensity away grounds during elimination fixtures; amplified for sides with historically reactive discipline or playing their first visit to a specific hostile venue.",
        "magnitude": "An additional ~4 pp pass-accuracy penalty beyond baseline home disadvantage, combined with elevated caution risk, is a measurable structural vulnerability across a knockout campaign.",
        "links": ["big_match_decision_calm", "card_avoidance_discipline_pressure", "two_legged_tie_aggregate_savvy"],
    },
    {
        "slug": "trailing_urgency_balance",
        "title": "Trailing-Urgency Balance",
        "summary": "Whether attacking risk when chasing a late goal stays disciplined and quality-focused rather than devolving into chaotic volume, measured by shot quality (xG per attempt) and counter-attack concession rate when behind in the final twenty minutes.",
        "stat_signature": "Composed chasers maintain xG-per-shot above ~0.10 while volume rises; fragile ones flood attempts at xG-per-shot below ~0.07 and concede counters at ~0.12-0.18 per loss of possession versus ~0.05-0.08 for disciplined units.",
        "mechanism": "Desperation biases toward volume over quality and over-commits players forward, leaving defence stretched; disciplined chasing selects only high-quality attempts, maintains a rest-defence skeleton, and converts at higher rates than volume strategies do.",
        "conditions": "Most apparent when chasing by one goal after the seventieth minute; amplified against sides with fast transition threats; varies with the attacking depth available off the bench.",
        "magnitude": "The gap between controlled and chaotic chasing can mean several extra counter-attack chances per match phase — enough to turn a one-goal deficit into a two-goal loss rather than an equaliser.",
        "links": ["comeback_composure_after_concession", "big_match_decision_calm", "high_leverage_finishing_steadiness", "two_legged_tie_aggregate_savvy"],
    },
    {
        "slug": "comeback_composure_after_concession",
        "title": "Composure After Conceding",
        "summary": "Whether defensive structure and possession retention hold in the ten minutes immediately after conceding rather than fragmenting under shock, measured by post-concession xG-against and possession share in that window.",
        "stat_signature": "The ten minutes after conceding show an xG-against spike of ~0.03-0.07 above match average for fragile units; composed sides return to near-baseline xG-against within five minutes and regain possession share to ~48-52%; a second goal arrives in this window ~18-25% of the time for fragile units.",
        "mechanism": "Conceding disrupts emotional regulation and can prompt reactive over-commitment forward or collapse of shape; absorbing the shock, resetting structure before kickoff, and avoiding the panic chase prevents the compounding second goal that frequently follows in this window.",
        "conditions": "Most consequential when a second goal in the opening or closing phase would decisively change the match state; amplified in away legs where the home crowd feeds on the momentum.",
        "magnitude": "Reducing the post-concession xG-against spike from ~0.06 to ~0.02 halves the probability of a quick second goal — a composure dividend that is entirely behavioural rather than quality-driven.",
        "links": ["trailing_urgency_balance", "big_match_decision_calm", "post_red_card_adaptation_composure", "hostile_atmosphere_execution"],
    },
    {
        "slug": "two_legged_tie_aggregate_savvy",
        "title": "Two-Legged-Tie Aggregate Savvy",
        "summary": "Intelligent modulation of attacking and defensive risk across both legs of a knockout tie based on the live aggregate state, measured by goal-concession rate and shot-volume modulation tied to aggregate context.",
        "stat_signature": "In the second leg of a tie, sides with a one-goal first-leg deficit increase shot volume ~20-35% and concede counter-attacks at ~1.4 times their baseline rate; composed sides show lower xG-against per unit of xG-generated while chasing the aggregate.",
        "mechanism": "Aggregate mathematics creates context-specific risk-reward functions — a goal conceded early in the second leg may require two in reply — so awareness of the exact aggregate state continuously recalibrates the optimal risk level; sides that over- or under-commit to the required state waste the structural advantage that correct reading confers.",
        "conditions": "Specific to two-legged knockout formats; most complex when an away goal creates asymmetric risk in the second leg; shaped by whether a side hosts or travels for the second fixture.",
        "magnitude": "Correctly timing the shift from defensive solidarity to committed attacking based on aggregate state is a discrete tactical-intelligence dimension readable across a side's multi-season knockout record.",
        "links": ["shootout_nerve_steadiness", "trailing_urgency_balance", "hostile_atmosphere_execution", "big_match_decision_calm"],
    },
    {
        "slug": "set_piece_concentration_late",
        "title": "Late Set-Piece Concentration",
        "summary": "Defensive marking discipline on set pieces delivered in the closing twenty minutes, when fatigue and time pressure erode shape, measured by set-piece goals-conceded rate after the seventy-fifth minute relative to earlier match phases.",
        "stat_signature": "Set-piece goals as a share of total late concessions: ~45-55%; fragile units show a ~0.04 goals-per-set-piece excess after the 75th versus their first-half rate; post-75 aerial-duel win rate on opposing set pieces drops ~4-8 pp for pressure-fatigued units.",
        "mechanism": "Fatigue degrades the sustained vigilance marking assignments require — runners are tracked late, zonal blocks drift, jump timing suffers — opening precisely the deliveries trailing sides target late; concentration maintenance is a specific fatigue-and-pressure discipline distinct from general set-piece defending.",
        "conditions": "Most acute in the 75-90+ band on congested schedules; amplified against sides whose late strategy is explicitly set-piece driven; partially mitigated by substituting a fresh aerial defender before the closing phase.",
        "magnitude": "A ~0.05 goals-per-set-piece excess in the late phase versus early match translates to several dropped points across a season from one concentration-specific vulnerability.",
        "links": ["penalty_kick_composure", "card_avoidance_discipline_pressure", "injury_time_concentration", "comeback_composure_after_concession"],
    },
    {
        "slug": "card_avoidance_discipline_pressure",
        "title": "Pressure Card-Avoidance Discipline",
        "summary": "Avoidance of rash challenges in high-tension phases, particularly in the final third of high-stakes matches when frustration provokes reactive fouls, measured by caution-rate relative to the side's own lower-stakes baseline.",
        "stat_signature": "In high-stakes fixtures caution rate rises ~15-30% for reactive sides versus ~5-10% for disciplined ones relative to their season baseline; second-yellow risk concentrates in the 60-80 minute band; defensive-third foul rate rises ~20% for pressure-fragile units in closing minutes.",
        "mechanism": "Elevated stakes and momentum shifts trigger frustration and reactive challenges; a yellow card in the closing stage raises second-caution risk and limits tactical-foul options, while a red can collapse closing structure; composure is the ability to absorb momentum swings without translating frustration into rash challenges.",
        "conditions": "Most consequential in the 60-90 minute band of tight matches; amplified in hostile atmospheres; interacts with the existing caution tally — a player on a yellow at the 70th minute is a structural fragility.",
        "magnitude": "One additional late caution per high-stakes match carries meaningfully elevated red-card risk across a knockout campaign, a structural composure tax that shows up in closing-phase concession rates.",
        "links": ["hostile_atmosphere_execution", "set_piece_concentration_late", "post_red_card_adaptation_composure", "injury_time_concentration"],
    },
    {
        "slug": "post_red_card_adaptation_composure",
        "title": "Post-Red-Card Adaptation Composure",
        "summary": "Retention of defensive structure immediately after a dismissal, measured by xG-against per minute and block compactness in the phase following the numerical reduction.",
        "stat_signature": "In the five minutes after a dismissal, xG-against per minute spikes ~2-4 times the match baseline for disorganised units; composed sides reorganise within two to three minutes and return to ~1.4 times baseline; successful reorganisation is detectable via opponent box-entry density.",
        "mechanism": "A dismissal creates an immediate structural gap and psychological disruption that an opponent exploits through rapid tempo increases; the side's response — quickly filling the gap, communicating new assignments, dropping a forward without argument — determines whether disruption lasts two minutes or ten, with proportional concession-probability differences.",
        "conditions": "Amplified when the dismissal is early and a long defensive period follows; most consequential when protecting a lead; the speed and clarity of tactical reorganisation is a measurable squad-intelligence dimension.",
        "magnitude": "The difference between a two-minute and a ten-minute reorganisation gap under a sustained opponent tempo surge represents several tenths of expected goals — often decisive for whether a side survives a dismissal.",
        "links": ["card_avoidance_discipline_pressure", "comeback_composure_after_concession", "big_match_decision_calm", "trailing_urgency_balance"],
    },
    {
        "slug": "goalkeeper_distribution_under_press",
        "title": "Goalkeeper Distribution Under Press",
        "summary": "Composed buildup from the goalkeeper against a high press in tight matches, measured by under-pressure pass-completion rate and turnover-in-own-third rate when a side elects to play out.",
        "stat_signature": "Under active high-press conditions, keeper distribution pass-completion drops to ~72-80% for fragile distributors versus ~87-93% for composed ones; own-third turnover rate under press is ~2-4 times the baseline; xG-against per own-third loss under press is the consequential output metric.",
        "mechanism": "A high press collapses distribution windows and forces rapid decisions under physical pressure; a keeper who reads outlets quickly, executes accurately, and chooses when to go direct rather than force a dangerous short pass removes the press's primary yield — the own-third turnover — from the opponent's toolkit.",
        "conditions": "Most diagnostic against active high-press sides in tight matches where possession value is high; amplified when outfield rest-defence options are limited; separable by comparing high-stakes versus routine-match distribution metrics.",
        "magnitude": "Each own-third turnover under press carries an xG-against value several times the baseline; reducing press-yield from ~0.20 to ~0.08 per press sequence is a direct defensive-efficiency contribution from goalkeeper composure.",
        "links": ["big_match_decision_calm", "hostile_atmosphere_execution", "comeback_composure_after_concession"],
    },
    {
        "slug": "injury_time_concentration",
        "title": "Stoppage-Time Concentration",
        "summary": "Defensive and decision concentration during added time, measured by goals conceded and errors leading to shots relative to the expected per-minute rate from the ninety-minute match.",
        "stat_signature": "League-wide, stoppage-time goals are ~20-30% more frequent per minute than the ninety-minute baseline; fragile units show ~40-60% per-minute excess; composed sides hold near ~1.1-1.2 times baseline; error-leading-to-shot rate is the clearest concentration diagnostic.",
        "mechanism": "Stoppage time brings maximal fatigue, signaled added minutes raising the trailing side's commitment, and a referee environment more permissive of physical play; concentration required to maintain marking and clearance quality under exhaustion erodes faster in less composed units, translating directly into late errors.",
        "conditions": "Most acute when five or more added minutes are signaled with a one-goal lead; amplified on congested schedules; partially mitigated by substituting fresh defensive legs before added time begins.",
        "magnitude": "A ~35% per-minute excess in stoppage-time concession across a season represents multiple dropped points from concentration failure in the final minutes alone.",
        "links": ["set_piece_concentration_late", "card_avoidance_discipline_pressure", "comeback_composure_after_concession", "big_match_decision_calm"],
    },
    {
        "slug": "high_leverage_finishing_steadiness",
        "title": "High-Leverage Finishing Steadiness",
        "summary": "Whether finishing quality holds in decisive moments, measured by the goals-minus-xG differential in high-stakes matches compared with the same side's routine-fixture baseline.",
        "stat_signature": "In routine fixtures goals-minus-xG oscillates within ~+/-0.05 per match; in high-stakes fixtures pressure-fragile units show a consistent ~-0.08 to -0.15 per-match negative differential — shot quality is held but conversion falls; composed finishers hold within ~+/-0.03.",
        "mechanism": "High-stakes pressure amplifies conscious over-control in the finishing action — tightened muscles, altered timing, last-moment placement change — causing technically clean shots to miss targets they would have hit in lower-stakes contexts; composure-stable mechanics immunise conversion against stakes.",
        "conditions": "Most informative across multiple high-stakes fixtures to separate genuine composure from sample variance; amplified after a key miss within the same match; interacts with shot-volume context (desperate late volume skews xG-per-shot).",
        "magnitude": "A consistent ~0.10 goals-per-match composure gap in high-stakes fixtures is equivalent to removing one quality finish per knockout match — descriptively decisive at the margins of tournament advancement.",
        "links": ["penalty_kick_composure", "big_match_decision_calm", "trailing_urgency_balance", "hostile_atmosphere_execution"],
    },
    {
        "slug": "deep_block_patience_holding_result",
        "title": "Deep-Block Patience Holding a Result",
        "summary": "Disciplined retention of defensive shape rather than being drawn forward when protecting a result, measured by block compactness and line-break concessions during the closing phase under sustained pressure.",
        "stat_signature": "Patient sides maintain ~35-40 metre defensive lines under pressure; impatient ones are dragged to ~42-48 metres with gaps, allowing ~2-4 additional between-the-lines receptions per closing phase; line-break concession rate separates the groups by ~0.03-0.05 xG per pressure sequence.",
        "mechanism": "An opponent applies decoy runs and short combinations to tempt the line forward; disciplined patience — trusting shape, ignoring decoys, holding depth — neutralises these triggers; the composure element is resisting the instinct to step out and engage rather than holding structural capability.",
        "conditions": "Most tested in the 70-90 minute band when a desperate opponent runs shape-disruption patterns; amplified when the leading side lacks ball-retention options and must defend passively; degraded by poor communication and fatigue-driven positional discipline loss.",
        "magnitude": "Maintaining compactness reduces between-the-lines receptions and line-break xG by a measurable margin per pressure sequence, directly lowering concession probability for the same volume of opponent territory.",
        "links": ["set_piece_concentration_late", "injury_time_concentration", "post_red_card_adaptation_composure", "comeback_composure_after_concession"],
    },
    {
        "slug": "close_match_conversion_steadiness",
        "title": "Close-Match Conversion Steadiness",
        "summary": "The rate of converting tight match states into favorable results, measured by actual points won relative to expected-points from the distribution of one-goal-margin match states across a season.",
        "stat_signature": "Steady sides convert within ~+/-0.05 points per match of their model entitlement in one-goal-margin contexts; fragile ones under-convert by ~0.10-0.18 points per match in tight games versus multi-goal-margin matches, representing multiple dropped points across a season.",
        "mechanism": "One-goal-margin matches maximally amplify stakes and error cost; a side whose structural and decision quality is invariant to match tightness converts its model-implied share, while one whose execution degrades under marginal-result pressure systematically under-converts in the tightest contests.",
        "conditions": "Most informative across a full-season sample of one-goal-margin matches; partially confounded by opponent quality in those matches; the gap between one-goal-margin and multi-goal-margin conversion is the composure-specific signal.",
        "magnitude": "A persistent ~0.12 points-per-match under-conversion in one-goal contexts across thirty or more such matches is a several-point seasonal composure tax descriptively separable from overall quality.",
        "links": ["big_match_decision_calm", "high_leverage_finishing_steadiness", "trailing_urgency_balance", "injury_time_concentration", "deep_block_patience_holding_result"],
    },
]
