"""Tennis / FormDynamics — person-free concept-node spec. Dense, market-agnostic."""
from __future__ import annotations

SPORT = "Tennis"
FAMILY = "FormDynamics"

CONCEPTS = [
    {
        "slug": "elo_recent_form_update",
        "title": "Elo Recency Update Sensitivity",
        "summary": "K-factor magnitude governs how sharply a rating shifts per result and compresses the match-count half-life of prior information, making high-K ratings closer proxies for recent form than long-run ability.",
        "stat_signature": "K-factor 10-32 across tour tiers; half-displacement match count ≈ 14-28 matches; rating round-trip stddev over rolling 20 matches rises with K and stabilises once 40+ graded results exist on the surface.",
        "mechanism": "Each result updates by K*(outcome - expected); consecutive wins against above-rated opponents compound upward displacement faster than mixed results because the expected-outcome term remains high while the outcome term stays at 1.",
        "conditions": "Most informative for players in their first 60 surface-specific matches (provisional K) and for short-format events where results cluster in time; stabilises for veterans with 80+ surface matches where fixed low K is appropriate.",
        "magnitude": "A 4-match single-surface win streak against opponents averaging +50 rating points above shifts the rating 30-60 points — roughly 1.5 percentage points of single-match win probability against a median opponent at K=32.",
        "links": ["early_career_rating_volatility", "ranking_momentum_trajectory", "form_to_rating_shrinkage", "win_streak_confidence_signal"],
    },
    {
        "slug": "surface_specific_form_decay",
        "title": "Surface-Specific Form Decay",
        "summary": "Trailing hold and serve-points-won rates from a prior surface swing lose predictive accuracy as elapsed time and intervening cross-surface matches increase; each surface's form trajectory is largely independent.",
        "stat_signature": "Correlation between prior-surface trailing hold rate and current-surface realised hold rate decays from ~0.72 within two weeks to ~0.48 after eight weeks; clay-to-grass transition shows the largest hold-rate gap at 4-8 percentage points for baseline specialists.",
        "mechanism": "Bounce height, slide mechanics, and rally length differ systematically by surface; skill distributions — ace rates, approach-shot frequencies, net-game volume — all redistribute when switching surfaces, so prior-surface form is a biased predictor.",
        "conditions": "Most pronounced at swing transitions for players with a surface-Elo gap exceeding 40 points; less relevant for all-surface baseliners whose cross-surface hold rate varies under 3 percentage points.",
        "magnitude": "Naively applying prior-surface form inflates hold-rate predictions by 3-7 percentage points for surface specialists; shrinking toward the surface-Elo implied rate reduces prediction MAE by roughly 0.04 percentage points of hold rate per match.",
        "links": ["surface_transition_adjustment", "indoor_outdoor_form_split", "rolling_serve_hold_form", "form_to_rating_shrinkage"],
    },
    {
        "slug": "rolling_serve_hold_form",
        "title": "Rolling Service-Hold Form",
        "summary": "Trailing hold percentage and serve-points-won over the most recent 8-12 same-surface matches capture short-term service rhythm and mechanical confidence beyond what the season-level rating encodes.",
        "stat_signature": "8-match rolling hold rate; 8-match 1st-serve-points-won and 2nd-serve-points-won; deviation from 40-match surface baseline in standard deviations; within-surface autocorrelation of rolling hold rate across adjacent 8-match windows is ~0.62.",
        "mechanism": "Service rhythm — ball-toss height consistency, shoulder-rotation timing — compounds positively over a hot stretch and degrades with fatigue or technical disruption; the trailing window captures this transient state independently of opponent quality.",
        "conditions": "Most predictive at event start when pre-tournament practice data are unavailable; signal strengthens when trailing matches share the same surface and indoor/outdoor context as the upcoming event.",
        "magnitude": "A rolling hold rate 5 percentage points above baseline predicts a 2-3 percentage-point lift in event hold rate through the first two rounds; the signal attenuates to near zero by rounds 4-5 as fresh in-event data dominate.",
        "links": ["first_serve_percentage_form", "break_point_clutch_form_regression", "surface_specific_form_decay", "rolling_return_form", "form_to_rating_shrinkage"],
    },
    {
        "slug": "rolling_return_form",
        "title": "Rolling Return-Game Form",
        "summary": "Trailing return-points-won and break-point conversion rate over recent matches capture aggressiveness and timing on return that fluctuates around the surface baseline with momentum and fatigue.",
        "stat_signature": "8-match rolling return-points-won percentage; 8-match rolling break-point conversion rate; deviation from 40-match surface baseline; within-surface correlation with next-match realised return-points-won is ~0.55, dropping to ~0.38 cross-surface.",
        "mechanism": "Return quality depends on split-step calibration and read-timing that builds across a hot stretch; high trailing return-points-won reflects a player tuned to pace and spin, carrying short-term predictive power independently of opponent serve strength.",
        "conditions": "Most informative against heavy servers where small positioning deviations compound; less separating against slower second-serve opponents where return quality converges toward a near-universal floor.",
        "magnitude": "Rolling return-points-won 3 percentage points above baseline associates with roughly 1.8 percentage points higher break probability per service game in the near term; cross-surface transfer captures roughly 60% of the within-surface effect.",
        "links": ["rolling_serve_hold_form", "break_point_clutch_form_regression", "best_of_format_endurance", "form_to_rating_shrinkage"],
    },
    {
        "slug": "win_streak_confidence_signal",
        "title": "Win-Streak Confidence Decomposition",
        "summary": "A current match-win streak carries residual predictive information beyond as-of surface Elo; this residual is small but meaningful for streaks of 5 or more same-surface matches and decays rapidly once the streak ends.",
        "stat_signature": "Residual win-probability lift (observed win rate minus Elo-predicted) regressed on streak length: +0.5 to +1.2 percentage points per additional match for streaks of 3-10, flattening above 10; streak-break match shows a residual of -2 to -4 pp against the same Elo spread.",
        "mechanism": "Consecutive wins build tactical confidence and serve rhythm; momentum also reflects opponent quality compounding — beating above-rated opponents elevates Elo, so the residual captures latent form not yet absorbed by the rating update lag.",
        "conditions": "Most relevant for streaks built on a single surface within a 6-week window; multi-surface streaks dilute the signal because the underlying skill distribution shifts across surfaces.",
        "magnitude": "A 7-match single-surface streak adds approximately 1.5-2.5 percentage points to win probability after Elo conditioning; the residual half-life after the streak ends is roughly 3 matches.",
        "links": ["elo_recent_form_update", "ranking_momentum_trajectory", "layoff_rust_effect", "form_to_rating_shrinkage"],
    },
    {
        "slug": "first_serve_percentage_form",
        "title": "First-Serve-In Percentage Form Trend",
        "summary": "Short-run movement in a player's first-serve-in rate signals rhythm and fatigue independently of the power or placement dimension; a declining trend predicts elevated double-fault risk and compressed service-game dominance.",
        "stat_signature": "8-match rolling first-serve-in percentage; linear trend slope (pp per match) over the window; double-fault rate correlates with 1st-serve-in rate at r ≈ -0.58 within-surface; a 4-point drop in 1st-serve-in associates with roughly +0.15 double faults per service game.",
        "mechanism": "First-serve consistency is governed by ball-toss repeatability and shoulder-rotation timing; fatigue disrupts motor sequencing — producing higher arc variance and reduced arm-speed consistency — before it appears in ace rate or placement quality.",
        "conditions": "Most diagnostic when trailing matches include at least two 3-set contests within the prior 10 days or after significant travel; also informative at the start of a surface swing where mechanical recalibration is ongoing.",
        "magnitude": "Rolling first-serve-in rate 5 percentage points below baseline predicts roughly 0.3-0.5 additional double faults per set and a 3-5 percentage-point reduction in hold probability.",
        "links": ["rolling_serve_hold_form", "match_minutes_fatigue_carryover", "consecutive_match_load", "surface_transition_adjustment"],
    },
    {
        "slug": "match_minutes_fatigue_carryover",
        "title": "On-Court-Minutes Fatigue Carryover",
        "summary": "Long or multi-set matches accumulate neuromuscular fatigue that persists into the next round; serve hold rate and rally-length tolerance decline measurably when trailing 48-hour on-court minutes exceed a surface-specific threshold.",
        "stat_signature": "Trailing 48-hour on-court minutes; hold-rate change per additional 30 minutes above 120-minute threshold: approximately -1.8 pp on clay and -1.2 pp on hard; second-serve win rate drops ~2 pp per 30 excess minutes; effect detectable up to 72 hours post-match.",
        "mechanism": "Extended play depletes glycogen stores and induces microtrauma in rotator cuff and lower-limb stabilisers; serve velocity drops 2-4 km/h and lateral sprint initiation slows, reducing approach-shot quality and increasing unforced error rates on passing shots.",
        "conditions": "Most pronounced in early rounds of 5-day events with back-to-back 3-set matches; surface effect is larger on clay due to longer average rally lengths amplifying total muscular work.",
        "magnitude": "Carrying 180+ on-court minutes into the next match corresponds to roughly a 3-5 percentage-point hold-rate reduction and a 2-point first-serve-percentage decline; the effect attenuates to near zero after 72 hours rest.",
        "links": ["consecutive_match_load", "days_rest_between_events", "first_serve_percentage_form", "best_of_format_endurance"],
    },
    {
        "slug": "consecutive_match_load",
        "title": "Consecutive-Match Tournament Load",
        "summary": "Accumulated wear from deep runs within a single event produces a round-by-round decline in serve accuracy and break-point save rate separable from opponent quality once match count and cumulative court time are conditioned on.",
        "stat_signature": "Round number within event (1-7); cumulative on-court minutes; round-by-round slope of first-serve-in percentage: approximately -0.8 pp per round on hard, -1.2 pp per round on clay from round 3 onward; break-point save rate declines ~1.5 pp per additional match beyond round 3.",
        "mechanism": "Each match adds to cumulative neuromuscular debt; rest days partially restore baseline motor precision but residual fatigue compounds across rounds; tactical decision-making also deteriorates under accumulated cognitive load in extended events.",
        "conditions": "Signal is meaningful only for players reaching round 4 or beyond; less informative for efficient 3-set-in-under-90-minute winners with low cumulative minutes relative to round depth.",
        "magnitude": "A finalist carrying 400+ cumulative minutes shows approximately 4-7 percentage-point lower hold rate than their baseline; a rested finalist with three short matches shows a 1-2 pp decline.",
        "links": ["match_minutes_fatigue_carryover", "days_rest_between_events", "best_of_format_endurance", "first_serve_percentage_form"],
    },
    {
        "slug": "days_rest_between_events",
        "title": "Days-Rest Between Tournaments",
        "summary": "Recovery time between the last match of one event and the first match of the next predicts early-round serve and movement quality; insufficient rest suppresses first-serve accuracy while excess rest reduces match sharpness.",
        "stat_signature": "Days between events; hold rate is maximised at 7-10 rest days (~+1.5 pp above baseline); under 3 days shows -2 to -4 pp; over 21 days shows -1 to -2 pp (rust); the effect is halved when the prior event exit was in round 1-2 (low cumulative load).",
        "mechanism": "Physical recovery follows known half-life curves for glycogen replenishment and muscle repair; 5-7 days restores acute fatigue but match rhythm requires live-ball practice or competition to recalibrate, explaining the mild decrement after long layoffs.",
        "conditions": "Most relevant for players exiting deep runs (QF or beyond); less important for first-round losers where prior cumulative load is near zero regardless of rest days.",
        "magnitude": "Optimal rest adds approximately 1-2 percentage points to first-round win probability against a 2-day turnaround; the over-rested penalty (21+ days) is smaller at ~0.5-1 pp, controlling for opponent and surface Elo.",
        "links": ["match_minutes_fatigue_carryover", "consecutive_match_load", "layoff_rust_effect", "travel_timezone_adjustment"],
    },
    {
        "slug": "travel_timezone_adjustment",
        "title": "Travel and Time-Zone Adjustment",
        "summary": "Intercontinental travel and large time-zone shifts between events produce a residual early-round performance decrement even after controlling for rest days, opponent rating, and surface, primarily through disrupted sleep architecture affecting motor sequencing.",
        "stat_signature": "Time-zone delta (hours); residual win probability after Elo conditioning declines approximately 1.5-2.5 pp per 3-hour eastward shift and 0.8-1.5 pp per 3-hour westward shift; first-serve win rate is the most sensitive metric, dropping ~1 pp per 3 hours eastward in match 1.",
        "mechanism": "Eastward circadian phase advance disrupts REM sleep more severely; cortisol timing misaligns with match schedules, impairing reaction time and fine motor control; the effect is strongest in match 1 and decays over 3-5 days of local acclimation.",
        "conditions": "Most measurable for intercontinental swings (Europe to Americas, Asia to Europe); negligible within the same continent where timezone deltas are under 3 hours; compounded by red-eye travel with under 6 hours sleep.",
        "magnitude": "A large-timezone jump (9+ hours eastward) reduces first-round serve-hold probability by roughly 2-3 percentage points; adjustment fully resolves by match 3 in most cases.",
        "links": ["days_rest_between_events", "layoff_rust_effect", "surface_transition_adjustment", "as_of_form_freshness_gap"],
    },
    {
        "slug": "surface_transition_adjustment",
        "title": "Surface-Transition Adjustment Period",
        "summary": "The first 2-4 matches on a new surface after a swing change show elevated prediction error because cross-surface trailing stats are imperfect proxies for current surface performance; tactical and mechanical recalibration takes measurable match-count to complete.",
        "stat_signature": "Cross-surface hold-rate MAE is ~4-6 pp in match 1 on the new surface, declines to ~2 pp by match 3, and converges to within-surface error (~1 pp) by match 5-6; error is largest at clay-to-grass and grass-to-clay transitions (bounce height differential).",
        "mechanism": "Each surface imposes distinct ball-speed decay and bounce-angle profiles; players must re-learn positioning depth and contact-point timing, producing higher unforced error and lower approach-shot success until the new baseline is internalised.",
        "conditions": "Most pronounced for surface specialists (surface-Elo gap > 50 points); all-surface players with surface-Elo gap under 20 points show minimal adjustment period.",
        "magnitude": "Surface specialists show a 3-5 pp hold-rate shortfall in match 1 on the new surface relative to their surface-specific baseline; transition matches also show 20-30% higher double-fault rate than the destination-surface norm.",
        "links": ["surface_specific_form_decay", "indoor_outdoor_form_split", "rolling_serve_hold_form", "layoff_rust_effect"],
    },
    {
        "slug": "layoff_rust_effect",
        "title": "Layoff and Comeback Rust Effect",
        "summary": "Extended competitive absence disrupts serve rhythm, return timing, and match-intensity tolerance; the first 3-5 matches back show elevated prediction error and serve-percentage shortfall relative to the pre-layoff as-of baseline.",
        "stat_signature": "Layoff duration (weeks); first-serve-in percentage in match 1 back is approximately 3-5 pp below pre-layoff trailing rate for 4-12 week absences; shortfall halves with each subsequent match; hold-rate prediction error is elevated by 4-8 pp in match 1 versus within-form error of ~1-2 pp.",
        "mechanism": "Match-play intensity involves explosive efforts unreplicable in practice; serve timing calibration depends on live opponent feedback; absence removes both physical conditioning load and perceptual calibration, producing a compounded initial decrement.",
        "conditions": "Most severe for injury-induced absences (physical deconditioning added to rhythm loss) versus voluntary scheduling breaks; also more pronounced when the return event surface differs from the one played before the layoff.",
        "magnitude": "A 6-week absence predicts roughly a 4 pp hold-rate reduction in match 1; effect resolves to under 1 pp by match 5 in most cases; injury-return absences extend the resolution window to 8-12 matches.",
        "links": ["days_rest_between_events", "travel_timezone_adjustment", "surface_transition_adjustment", "elo_recent_form_update", "as_of_form_freshness_gap"],
    },
    {
        "slug": "break_point_clutch_form_regression",
        "title": "Break-Point Conversion Form Regression",
        "summary": "Unusually high or low recent break-point save and conversion rates revert toward the serve-and-return-implied expectation; the residual between trailing break-point rate and underlying serve/return metrics decays predictably across subsequent matches.",
        "stat_signature": "8-match trailing break-point save rate minus serve-implied save rate (derived from 1st- and 2nd-serve-points-won); residual correlation with next-match break-point rate is approximately 0.18 (much lower than the 0.55 correlation of underlying serve metrics); regression coefficient toward implied rate ~0.6 per 10 matches.",
        "mechanism": "Break-point outcomes have high variance at the individual rally level; over short windows a player can diverge from serve-implied expectation due to random clustering; underlying serve mechanics govern expected break-point performance and reassert themselves across larger samples.",
        "conditions": "Most detectable when 3+ matches show break-point save rate diverging from serve-implied expectation by more than 10 percentage points; less useful for big-serving specialists where variance in break-point count per match is already low.",
        "magnitude": "A trailing break-point save rate 15 pp above the serve-implied expectation reverts approximately two-thirds of that gap over the next 6 matches; the residual contributes roughly 1-2 pp to hold-rate prediction error if uncorrected.",
        "links": ["rolling_serve_hold_form", "tiebreak_overperformance_decay", "rolling_return_form", "form_to_rating_shrinkage"],
    },
    {
        "slug": "tiebreak_overperformance_decay",
        "title": "Tiebreak Overperformance Decay",
        "summary": "An inflated recent tiebreak win rate reverts toward the serve-strength-implied expectation; the gap between trailing tiebreak win percentage and the expectation derived from first-serve dominance decays faster than the underlying serve metrics change.",
        "stat_signature": "8-match tiebreak win rate; serve-implied tiebreak expectation based on 1st-serve-points-won (correlation with tiebreak win rate is ~0.65 over full seasons); residual autocorrelation across the next 5 tiebreaks is only ~0.15; reversion coefficient ~0.55 per 8 tiebreaks.",
        "mechanism": "Tiebreak outcomes compress serve dominance into a 12-point mini-set with high variance per point; clutch execution in a small sample can diverge sharply from expectation; over a longer horizon the serve metrics reassert their structural role and the luck component dissipates.",
        "conditions": "Only meaningful when the trailing window includes at least 4-5 tiebreaks; on clay where tiebreaks are rare the sample is insufficient; most useful on fast indoor hard courts where tiebreak frequency is highest.",
        "magnitude": "A trailing tiebreak win rate 20 pp above implied expectation reverts roughly 10-12 points over the next 5 tiebreak encounters; over-relying on recent tiebreak rate without adjustment inflates single-match win-probability estimates by 1-3 pp.",
        "links": ["break_point_clutch_form_regression", "rolling_serve_hold_form", "win_streak_confidence_signal", "form_to_rating_shrinkage"],
    },
    {
        "slug": "as_of_form_freshness_gap",
        "title": "As-Of Form Freshness Gap",
        "summary": "A frozen pre-match form snapshot loses predictive accuracy as the number of matches played since the snapshot was computed increases; the decay in correlation quantifies how quickly stale form data should be down-weighted.",
        "stat_signature": "Correlation between frozen 8-match rolling hold rate and realised hold rate decays from ~0.68 at 0 elapsed matches to ~0.50 at 3 elapsed matches and ~0.38 at 6 elapsed matches; decay is faster for players with high K-factor and slower for veterans with stable surface baselines.",
        "mechanism": "Each intervening match shifts the true trailing window but is not captured in the frozen snapshot; a player who has played 4 new matches is operating on a different trailing window, making the snapshot an increasingly biased estimate of current form.",
        "conditions": "Most important for systems that compute form features at a fixed pre-season or pre-event date; highly relevant for tournaments where players enter at different round depths with different freshness gaps relative to a common snapshot date.",
        "magnitude": "Using a 6-match-stale snapshot instead of a fresh one inflates hold-rate prediction MAE by approximately 1.5-2.5 pp and reduces the signal-to-noise ratio of form-based features by roughly 30%.",
        "links": ["layoff_rust_effect", "elo_recent_form_update", "form_to_rating_shrinkage", "rolling_serve_hold_form"],
    },
    {
        "slug": "form_to_rating_shrinkage",
        "title": "Form-to-Rating Shrinkage",
        "summary": "The optimal pre-match performance estimate blends the short trailing window with the established surface-Elo prior; the shrinkage weight varies with sample size, surface consistency, and freshness gap, and is estimable from historical forward-error minimisation.",
        "stat_signature": "Shrinkage weight on 8-match rolling hold rate versus surface-rating-implied hold rate minimising next-match MAE: empirically ~0.35 for players with 20-40 surface matches, declining to ~0.20 for 80+ surface matches, rising to ~0.50 at freshness gap of 0 matches.",
        "mechanism": "Rolling form captures transient state (rhythm, fatigue, recalibration) while surface Elo captures durable skill level; neither alone is optimal — short windows are noisy and long-run ratings are slow to update; Bayesian shrinkage toward the prior dampens noise while preserving meaningful recent signal.",
        "conditions": "Shrinkage weight should increase when rolling form is based on fewer than 5 same-surface matches (high noise) and decrease when based on 8+ recent same-surface matches with freshness gap of 0-1 matches; cross-surface form requires additional shrinkage toward the destination-surface prior.",
        "magnitude": "Optimal shrinkage reduces hold-rate prediction MAE by roughly 0.8-1.5 pp versus rolling form alone, and by 0.3-0.6 pp versus surface-Elo implied rate alone; improvement is largest for players in the 20-50 surface-match range where both sources are informative.",
        "links": ["elo_recent_form_update", "rolling_serve_hold_form", "as_of_form_freshness_gap", "surface_specific_form_decay", "break_point_clutch_form_regression"],
    },
]
