"""FormDynamics Soccer concept nodes — person-free, calibration-only intelligence."""
from __future__ import annotations

SPORT = "Soccer"
FAMILY = "FormDynamics"

CONCEPTS: list[dict] = [
    {
        "slug": "rolling_xg_form",
        "title": "Rolling Expected-Goals Form",
        "summary": "A club's trailing expected-goals-for and expected-goals-against per match over the last N fixtures, and the direction and magnitude of drift from its season mean, captures process-level momentum independently of finishing variance.",
        "stat_signature": "Rolling five-match expected-goals-for and expected-goals-against; drift from the season mean exceeding ±0.20 per match is flagged; split-half reliability of the five-match window reaches ~0.55 correlation with the next five.",
        "mechanism": "Expected goals integrate shot volume, shot location, and assist quality into a single process measure that is more stable than goals, allowing form identification before results stabilise.",
        "conditions": "Most informative when the rolling window diverges from the season mean by more than one rolling standard deviation; reliability degrades below four recent matches and in post-international-break windows.",
        "magnitude": "A rolling expected-goals-for drift of +0.25 per match above the season mean associates with roughly 0.12-0.18 additional expected goals in the next fixture after regression to baseline.",
        "links": ["finishing_residual_regression", "shots_on_target_form_trend", "defensive_solidity_form", "form_to_rating_shrinkage"],
    },
    {
        "slug": "finishing_residual_regression",
        "title": "Finishing-Residual Mean-Reversion",
        "summary": "Goals exceed expected goals when finishing conversion runs hot; the exponentially-weighted residual (goals minus approximately 0.32 times shots on target) decays back toward zero at a rate predictable from its recent magnitude.",
        "stat_signature": "Exponentially-weighted residual with alpha ~0.15; residuals exceeding ±0.30 goals per match over a ten-match window show ~65% reversion toward zero within the next six fixtures; split-half stability of the residual is below 0.20.",
        "mechanism": "Finishing conversion above long-run rates reflects a mix of skill and random shot sequencing; the random component decays while the durable skill component sets the asymptote, producing predictable partial reversion.",
        "conditions": "Reversion speed is fastest when the residual is driven by low-probability shot conversion rather than structural chance-quality improvement; delayed when a squad undergoes a genuine tactical shift raising shot quality.",
        "magnitude": "A ten-match overperformance of +0.35 goals per match above expected reverts approximately 55-70% within the next eight fixtures; net realistic forward adjustment is roughly -0.15 to -0.25 goals per match.",
        "links": ["rolling_xg_form", "set_piece_overperformance_decay", "early_season_form_instability", "form_to_rating_shrinkage"],
    },
    {
        "slug": "shots_on_target_form_trend",
        "title": "Shots-on-Target Volume Form",
        "summary": "The rolling shots-on-target rate for and against per match captures attacking-threat volume and defensive-pressure level independently of finishing, providing an early signal of expected-goals trajectory shifts.",
        "stat_signature": "Rolling five-match shots-on-target-for and shots-on-target-against per match; a slope exceeding ±0.8 per match across the trailing five identifies a meaningful volume trend; the volume metric shows split-half stability of ~0.50.",
        "mechanism": "Shots on target reflect sustained attacking intent and defensive organisation more reliably than goals, since they strip out the goalkeeper-save and post-contact randomness layers that inflate goals variance.",
        "conditions": "Volume trends carry the most forward information when shot-quality (expected-goals-per-shot) is stable; if quality shifts alongside volume, the combined expected-goals reading supersedes the volume signal alone.",
        "magnitude": "A rolling gain of +1.5 shots on target per match above the season mean associates with approximately +0.10-0.15 expected goals per match in the forward window after partial regression.",
        "links": ["rolling_xg_form", "defensive_solidity_form", "finishing_residual_regression", "scoreline_variance_band"],
    },
    {
        "slug": "defensive_solidity_form",
        "title": "Defensive-Solidity Recent Form",
        "summary": "A club's trailing chance-suppression quality, measured as rolling expected-goals-against and big-chances-conceded per match relative to the season baseline, identifies defensive form shifts before goals-against totals fully reflect them.",
        "stat_signature": "Rolling five-match expected-goals-against per match; big-chances-conceded (individual expected-goals above 0.35) per match; a rolling expected-goals-against below 0.80 for five-plus fixtures signals a consolidating defensive structure.",
        "mechanism": "Defensive solidity reflects the interaction of pressing shape, compactness, and individual marking quality; sustained suppression across multiple fixtures signals structural rather than chance-driven improvement.",
        "conditions": "Most predictive when the defensive improvement coincides with tactical cohesion indicators (PPDA improvement, fewer deep-run completions allowed); unreliable when driven by opponent-quality variance in the fixture window.",
        "magnitude": "A five-match rolling expected-goals-against below 0.85 versus a 1.20 season mean corresponds to roughly 0.15-0.25 forward defensive improvement before full mean-reversion over ten matches.",
        "links": ["rolling_xg_form", "shots_on_target_form_trend", "home_away_form_split_drift", "form_to_rating_shrinkage"],
    },
    {
        "slug": "points_per_game_momentum",
        "title": "Rolling Points-Per-Match Momentum",
        "summary": "Short-run results trajectory measured as rolling points per match over the last five fixtures and its gap from the expected-goal-difference-implied points rate separates genuine momentum from finishing-luck contamination.",
        "stat_signature": "Rolling five-match points-per-match; expected-goal-difference-implied points rate estimated from a Poisson model; momentum signal defined as the residual gap exceeding ±0.40 points per match after controlling for expected-goal rate.",
        "mechanism": "Results carry a component of correlated team execution — set-piece delivery timing, concentration under pressure, and substitute impact — that is partially distinct from expected-goals flow and shows mild serial correlation.",
        "conditions": "The serial correlation in points is strongest within a single phase of a season (a two- to four-week window) and dissipates rapidly; opponent-quality scheduling effects must be removed for the signal to be clean.",
        "magnitude": "Rolling five-match points-per-match above 2.20 associates with approximately 0.08-0.12 forward points-per-match uplift after regression, representing modest but non-negligible momentum persistence.",
        "links": ["rolling_xg_form", "unbeaten_streak_decomposition", "fixture_congestion_fatigue", "as_of_form_freshness_decay"],
    },
    {
        "slug": "unbeaten_streak_decomposition",
        "title": "Unbeaten or Winless Streak Decomposition",
        "summary": "Whether a current unbeaten or winless run carries predictive information beyond underlying expected-goal ratings is measured by the residual points-per-match lift of streak length after conditioning on as-of expected-goal difference.",
        "stat_signature": "Regression of points-per-match on streak length controlling for rolling expected-goal difference; residual coefficient on streak length greater than five matches typically falls below 0.04 additional points per match per game.",
        "mechanism": "Long streaks are predominantly a consequence of stable underlying ratings rather than an independent momentum effect; once expected-goal difference is controlled, the incremental information in the streak label is small.",
        "conditions": "Streak information is most redundant with underlying ratings when the expected-goal difference is consistently in the same direction as the results; it carries more residual signal when streaks occur despite adverse expected-goal readings.",
        "magnitude": "After conditioning on expected-goal difference, each additional unbeaten match adds approximately 0.02-0.05 points-per-match forward expectation; the streak label without that conditioning overstates the effect by three to five times.",
        "links": ["points_per_game_momentum", "rolling_xg_form", "form_to_rating_shrinkage", "early_season_form_instability"],
    },
    {
        "slug": "fixture_congestion_fatigue",
        "title": "Fixture-Congestion Fatigue",
        "summary": "Cumulative wear from compressed match calendars is measured as the dose-response of matches-in-fourteen-days and short-turnaround exposure (under four days) on second-half expected goals and late-match goal concession.",
        "stat_signature": "Matches-in-14-days above four raises late-match expected-goals-against by 0.08-0.12 per extra fixture; turnarounds under four days reduce second-half high-intensity distance 8-12%; points-per-match falls 0.12-0.18 in the congested window.",
        "mechanism": "Incomplete glycogen and connective-tissue recovery reduces effective pressing duration, widening territorial exposure in the final third of each half when muscular output is depleted relative to a rested baseline.",
        "conditions": "Fatigue impact is largest in midfield-pressing-intensive systems relying on collective compactness; amplified when multiple starters logged 90 minutes within 72 hours and squad depth is thin in high-output positions.",
        "magnitude": "Approximately 0.10-0.18 additional expected-goals-against in the final 20 minutes per congested three-match week; squad-depth multiplier can shift the magnitude 50% in either direction.",
        "links": ["midweek_turnaround_load", "rest_day_advantage", "rolling_xg_form", "ew_goal_rate_decay"],
    },
    {
        "slug": "midweek_turnaround_load",
        "title": "Midweek-to-Weekend Turnaround Load",
        "summary": "Performance change after a short rest following midweek continental or cup fixtures is measured as the residual expected-goal-difference effect against a normal seven-day rest baseline, isolating the fatigue penalty from opponent-quality confounders.",
        "stat_signature": "Short-turnaround residual (expected-goal-difference minus rating-implied baseline): typically -0.15 to -0.25 per match on under-four-day rest; PPDA deteriorates 12-18% first half; three-plus rotations correlate with 0.08-0.14 additional expected-goals-against.",
        "mechanism": "Compressed preparation limits both tactical drilling and neuromuscular restoration; a rotated lineup reduces collective automaticity in transition defence and pressing trigger coordination.",
        "conditions": "Largest for squads with shallow cover across central midfield; compounded when midweek travel exceeds 1500 km; moderated for sides with strong squad depth and flexible tactical systems.",
        "magnitude": "Expected-goal-differential narrows 0.15-0.25 per match in favour of the rested side; short-turnaround point-per-match cost averages 0.12-0.20 versus the same fixture on normal rest.",
        "links": ["fixture_congestion_fatigue", "rest_day_advantage", "travel_distance_form_load", "rolling_xg_form"],
    },
    {
        "slug": "rest_day_advantage",
        "title": "Rest-Day Differential Advantage",
        "summary": "The effect of having more recovery days than the opponent is measured as the per-extra-rest-day change in expected-goal difference after controlling for venue and team strength.",
        "stat_signature": "Per-extra-rest-day expected-goal-difference advantage of approximately +0.04-0.08; the threshold effect is steepest between three and five days rest; advantage diminishes above seven days where recovery is complete for both sides.",
        "mechanism": "Each additional recovery day restores a measurable fraction of neuromuscular readiness, sprint-replenishment capacity, and tactical preparation depth; the relative advantage scales with the size of the rest differential.",
        "conditions": "Most pronounced when one side is on two-day rest and the opponent is on five-plus days; reversed when the rested side loses rhythm during a prolonged gap and the shorter-rest side is mid-tournament momentum.",
        "magnitude": "A two-day rest differential translates to roughly +0.08-0.15 expected-goal-difference advantage; beyond four days the marginal return per additional rest day falls below 0.03.",
        "links": ["midweek_turnaround_load", "fixture_congestion_fatigue", "travel_distance_form_load", "defensive_solidity_form"],
    },
    {
        "slug": "travel_distance_form_load",
        "title": "Travel-Distance and Away-Trip Load",
        "summary": "Form degradation associated with long away journeys is measured as the residual effect of trip distance on away-match expected-goal difference after controlling for opponent strength and venue.",
        "stat_signature": "Journeys exceeding 2000 km associate with -0.12 to -0.20 expected-goal-difference residual; first-half high-intensity distance drops 5-9%; points-per-match on 2000-km-plus trips falls 0.18-0.28 versus sub-500-km away fixtures.",
        "mechanism": "Long-haul travel produces circadian disruption, metabolic dehydration, and elevated cortisol that suppress neuromuscular readiness, particularly in the opening phase before progressive warm-up counteracts stiffness.",
        "conditions": "Largest when the journey involves time-zone crossings exceeding two hours or overnight travel arriving within 24 hours of kickoff; altitude adds a compounding aerobic deficit above 2000 metres.",
        "magnitude": "Approximately 0.12-0.20 expected-goal-difference penalty per qualifying away trip; first-half attacking output falls 15-25% relative to home or short-trip baselines.",
        "links": ["midweek_turnaround_load", "rest_day_advantage", "fixture_congestion_fatigue", "rolling_xg_form"],
    },
    {
        "slug": "set_piece_overperformance_decay",
        "title": "Set-Piece Conversion Overperformance Decay",
        "summary": "An inflated set-piece goal share above the long-run conversion rate reverts toward the shots-on-target-implied baseline, measured as the trailing set-piece-goals-minus-expected residual and its decay speed.",
        "stat_signature": "Set-piece goals-minus-expected residual: above +0.15 per match over eight fixtures reverts ~60% within the next ten fixtures; long-run set-piece conversion rate is stable at 22-28% per big-chance from dead balls.",
        "mechanism": "Set-piece over-conversion reflects delivery and movement scheme repetition that defences eventually adjust to, combined with stochastic goalkeeper positioning variance that averages out across a larger sample.",
        "conditions": "Reversion is faster after opponents have multiple preparation weeks to study dead-ball schemes; slower when the overperformance is driven by a structural aerial overload that defences cannot neutralise tactically.",
        "magnitude": "A ten-match set-piece overperformance of +0.20 goals per match above expected reverts approximately 55-65% within eight to twelve forward fixtures; the residual permanent component is roughly 0.05-0.08 goals per match.",
        "links": ["finishing_residual_regression", "rolling_xg_form", "early_season_form_instability", "scoreline_variance_band"],
    },
    {
        "slug": "home_away_form_split_drift",
        "title": "Home and Away Form-Split Drift",
        "summary": "Divergence in a club's trailing form by venue, measured as the rolling home-minus-away expected-goal-difference gap, identifies sides whose aggregate form reading masks a systematic venue-dependent performance split.",
        "stat_signature": "Home-minus-away rolling expected-goal-difference gap; a sustained divergence exceeding 0.50 per match over six home and six away fixtures flags a meaningful structural split; typical league-wide gap is 0.30-0.40.",
        "mechanism": "Home advantage compounds with tactical identity: pressing-intensive systems perform better at familiar venues where crowd noise aids communication, while direct or counter-attacking systems travel more neutrally.",
        "conditions": "Split is most diagnostic when the home and away fixture samples are balanced in quality; misleading when away fixtures are systematically harder or the venue sample is too small to stabilise.",
        "magnitude": "A home-away expected-goal-difference split of 0.60 per match versus a 0.30 league baseline implies the aggregate form estimate overstates away threat and understates home dominance by approximately 0.15 per fixture.",
        "links": ["rolling_xg_form", "defensive_solidity_form", "form_to_rating_shrinkage", "as_of_form_freshness_decay"],
    },
    {
        "slug": "manager_change_form_discontinuity",
        "title": "Tactical-Regime-Change Form Discontinuity",
        "summary": "The break in form continuity after a coaching or system change is measured as the jump in prediction error when pre-change trailing rates are applied to post-change fixtures, quantifying the stale-prior cost.",
        "stat_signature": "Prediction error (expected-goal-difference residual) rises 0.25-0.45 per match in the first six fixtures after a managerial change relative to pre-change rolling form; the prior window correlation with post-change outcomes falls to 0.10-0.20.",
        "mechanism": "A new tactical system alters pressing triggers, defensive shape, and chance-creation routes; pre-change rolling rates reflect the prior regime's structure and carry little forward information until the new system stabilises.",
        "conditions": "Discontinuity is most severe for stylistically distinct appointment types (from low-block to high-press); smaller when the incoming manager continues the predecessor's system with minor personnel adjustments.",
        "magnitude": "Rolling form from the preceding eight matches explains only 10-20% of post-change outcomes in the first six fixtures; the break effectively resets the informative sample window to zero.",
        "links": ["early_season_form_instability", "promotion_relegation_level_reset", "rolling_xg_form", "form_to_rating_shrinkage"],
    },
    {
        "slug": "early_season_form_instability",
        "title": "Early-Season Form Instability",
        "summary": "Rolling rates in the opening fixtures are unreliable as squads settle new personnel and systems, measured as the match count at which split-half correlation of rolling expected goals exceeds a reliability threshold of 0.50.",
        "stat_signature": "Split-half correlation of rolling expected-goals-for crosses 0.50 reliability at approximately eight to ten completed fixtures; below six matches the rolling rate is dominated by noise; opponent-schedule variance further depresses reliability in the opening six weeks.",
        "mechanism": "New signings require time to achieve tactical automaticity; pre-season conditioning varies by squad; early-fixture scheduling asymmetries in opponent quality inflate or suppress early form readings independently of true ability.",
        "conditions": "Instability is most severe for promoted sides, heavily rebuilt squads, or clubs with new managers; least severe for stable squads entering a season with high personnel continuity.",
        "magnitude": "Pre-match predictions using fewer than six-match rolling windows show RMSE approximately 15-25% higher than mid-season equivalents; the reliability cost shrinks roughly 3% per additional fixture beyond six.",
        "links": ["manager_change_form_discontinuity", "promotion_relegation_level_reset", "rolling_xg_form", "form_to_rating_shrinkage"],
    },
    {
        "slug": "form_to_rating_shrinkage",
        "title": "Form-to-Rating Shrinkage",
        "summary": "The optimal blend of a short trailing window with the established rating prior minimises forward prediction error; the shrinkage weight on rolling expected goals against the season rating is a function of window length and within-team variance.",
        "stat_signature": "Optimal shrinkage weight on the rolling five-match expected-goals rate versus the season mean is approximately 0.30-0.45 for five-match windows and rises to 0.55-0.65 for twelve-match windows; blended predictor reduces RMSE 4-8% against the season mean alone.",
        "mechanism": "Short windows are noisy but capture regime shifts; season ratings are stable but lag real changes; Bayesian shrinkage toward the prior by a weight proportional to inverse window variance produces the minimum-error compromise.",
        "conditions": "Optimal shrinkage toward the season prior is higher early in the season and after stable multi-week form runs; weight shifts toward the rolling window when a discontinuity event (manager change, key return from injury) has occurred.",
        "magnitude": "Blending five-match rolling expected goals with the season mean at a 35:65 ratio reduces forward expected-goal-difference RMSE by approximately 4-8% over using either alone.",
        "links": ["rolling_xg_form", "early_season_form_instability", "manager_change_form_discontinuity", "as_of_form_freshness_decay"],
    },
    {
        "slug": "as_of_form_freshness_decay",
        "title": "As-Of Form Freshness Decay",
        "summary": "A frozen pre-match form snapshot loses predictive value as fixtures elapse without update, measured as the decay in correlation between the frozen as-of value and realised outcomes as the gap between snapshot and prediction date widens.",
        "stat_signature": "Correlation between a frozen five-match rolling expected-goal rate and realised next-match expected goals decays from ~0.48 at zero-day lag to ~0.28 at a ten-day lag and ~0.15 at a twenty-one-day lag; a two-match gap erodes approximately 35% of predictive correlation.",
        "mechanism": "Each intervening fixture updates the rolling window, injuries and returns shift squad composition, and tactical adjustments between matches alter the rate; the frozen snapshot becomes progressively more stale relative to the true current state.",
        "conditions": "Decay is fastest in dense fixture periods where two or more matches intervene within ten days; slowest for stable squads with no personnel changes and consistent tactical identity.",
        "magnitude": "A ten-day-old form snapshot loses approximately 35-40% of its forward predictive correlation; refreshing the snapshot at a seven-day maximum lag retains 70-80% of the available predictive signal.",
        "links": ["rolling_xg_form", "form_to_rating_shrinkage", "points_per_game_momentum", "home_away_form_split_drift"],
    },
    {
        "slug": "scoreline_variance_band",
        "title": "Goal-Output Volatility Band",
        "summary": "The rolling standard deviation of match goals and goal-difference captures within-team output consistency, identifying volatile sides whose aggregate expected-goal rate understates or overstates the probability of extreme outcomes.",
        "stat_signature": "Rolling eight-match standard deviation of total goals; coefficient of variation (standard deviation divided by mean) above 1.10 identifies a high-variance output profile; the inter-quartile range of rolling goal-difference is a secondary stability metric.",
        "mechanism": "High output variance reflects tactical versatility (shifts between defensive and attacking postures by context) or structural inconsistency in pressing triggers; both produce wider prediction intervals than mean-based expected-goal models imply.",
        "conditions": "Volatility bands are most informative for total-goals markets and over-under modelling, where the variance structure directly determines probability mass in the tails; less actionable for match-result win-probability, where mean differences dominate.",
        "magnitude": "A side with coefficient of variation above 1.10 has approximately 15-25% more probability mass in zero-goal and four-plus-goal outcomes than Poisson-mean models predict; interval widths should be inflated by one standard deviation unit.",
        "links": ["rolling_xg_form", "shots_on_target_form_trend", "finishing_residual_regression", "set_piece_overperformance_decay"],
    },
]
