"""scripts.platformkit.specs.gamephases_tennis — GamePhases concepts for Tennis.
Person-free, dense phase-structure intelligence.  No player/team/match names.
"""
from __future__ import annotations

SPORT = "Tennis"
FAMILY = "GamePhases"

CONCEPTS = [
    {
        "slug": "opening_set_settling_phase",
        "title": "Opening-Set Settling Phase",
        "summary": "The first set while serve rhythm and return-timing calibration are forming; unforced errors and double-faults peak relative to match average before decaying exponentially across early games.",
        "stat_signature": "Unforced-error rate in set-1 games 1-4 is 5-8% above the match mean; double-fault frequency in the opening two service games runs 30-50% above mid-match baseline; hold percentage is 2-4 points below the match hold rate.",
        "mechanism": "Neuromuscular warm-up lag and limited return-read sample on spin profile and serve placement delay timing calibration; racket-face control and footwork anticipation require repetitions to converge, so error rates fall sharply over the first four games.",
        "conditions": "Most pronounced on indoor hard courts after minimal warm-up and on fast surfaces where bounce gives less reaction time; exacerbated by sharp changes in temperature, humidity, or altitude between rounds.",
        "magnitude": "Set-1 break rates run 3-6% higher than set-2 rates on ATP hard courts; the effect compresses but persists on clay.",
        "links": ["early_set_break_window", "opening_games_break_propensity", "momentum_after_set_won"],
    },
    {
        "slug": "early_set_break_window",
        "title": "Early-Set Break-Window Phase",
        "summary": "The opening games of a set where a single break shifts set-win probability most sharply, because the trailing player must break back while the leader holds — an asymmetric recovery burden.",
        "stat_signature": "A break in games 1-2 raises set-win probability roughly 55-65 percentage points from baseline; break-point conversion in games 1-3 averages 42-48% on hard courts, near the match mean despite unsettled serve rhythm.",
        "mechanism": "Set-probability mathematics create asymmetric payoff: an early break forces the opponent to hold every service game and break back, while the leader only needs to hold; this scoreboard leverage amplifies each break-point's marginal value.",
        "conditions": "Effect is strongest in sets 2 and 3 when match context adds psychological weight; smaller on clay where breaks are recovered more frequently; reduced in final-set advantage formats where game count extends.",
        "magnitude": "Converting the first break-point of a set closes roughly 60% of remaining set-win probability in a three-set match.",
        "links": ["opening_set_settling_phase", "serving_for_the_set_phase", "serving_first_in_set_advantage", "break_back_response_phase"],
    },
    {
        "slug": "serving_for_the_set_phase",
        "title": "Serving-for-the-Set Phase",
        "summary": "The service game in which a leading player can close a set, characterised by reduced first-serve percentage as the server tightens placement and by elevated opponent risk-taking that raises break-back frequency.",
        "stat_signature": "Hold rate while serving for the set averages 78-84% versus a match-wide 82-87%; break-back rate in this game is 4-8 points above mid-set average; first-serve percentage drops an estimated 3-5 points.",
        "mechanism": "Compressing decision trees for both players: the server must balance aggression with margin control while the returner shifts to higher-risk lines with nothing to lose, exploiting reduced serve-placement precision.",
        "conditions": "Pressure is highest closing a first or second set in a tight match; lower when the leader already has one set in hand and is closing a second.",
        "magnitude": "Breaks occur roughly 20% more often in serve-for-set games than in mid-set service games.",
        "links": ["serving_to_stay_in_set_phase", "early_set_break_window", "tiebreak_phase_dynamics", "late_set_tightening_phase"],
    },
    {
        "slug": "serving_to_stay_in_set_phase",
        "title": "Serving-to-Stay-in-Set Phase",
        "summary": "The do-or-die service game for a trailing player facing set-loss on the opponent's next hold; survival is followed by elevated break-point creation as the momentum burden shifts.",
        "stat_signature": "Hold rate when facing set-loss in the following game is 74-80%, roughly 4-7 points below general hold rate; among players who survive, break-point creation in the next return game rises 15-20% above baseline.",
        "mechanism": "Trailing players adopt an aggressive, nothing-to-lose serve pattern; survival unlocks a momentum-reversal dynamic where the opponent who failed to close bears the new psychological burden.",
        "conditions": "Strongest when the deficit is exactly one break with the opponent serving for the set next; less pronounced trailing by two breaks, where the set is statistically near-closed.",
        "magnitude": "Surviving this game recovers set-win probability roughly 15-25 points toward tiebreak distance.",
        "links": ["serving_for_the_set_phase", "break_back_response_phase", "tiebreak_phase_dynamics"],
    },
    {
        "slug": "tiebreak_phase_dynamics",
        "title": "Tiebreak Phase Dynamics",
        "summary": "The seven-point mini-game resolving a tied set where each mini-break carries disproportionate weight and first-serve dependence peaks relative to normal service games.",
        "stat_signature": "Tiebreak win rate correlates at r ~ 0.72 with service-point win rate in the preceding set; server wins 52-54% of service points inside a tiebreak versus 58-62% in regular games; ace rate rises 20-30% in breakers.",
        "mechanism": "Tiebreak scoring compresses variance: a single mini-break at 4-4 shifts win probability by roughly 30 points, incentivising maximum first-serve aggression and reducing average rally length.",
        "conditions": "Most decisive on fast surfaces (indoor hard, grass) where serve quality dominates; smaller edge for big servers on clay where returns penetrate more deeply.",
        "magnitude": "A mini-break at 4-4 closes tiebreak win probability by approximately 65%.",
        "links": ["tiebreak_serve_dependence", "deciding_set_tiebreak_format", "serving_for_the_set_phase", "late_set_tightening_phase"],
    },
    {
        "slug": "deciding_set_phase",
        "title": "Deciding-Set Phase",
        "summary": "The final set under maximal accumulated fatigue and stakes, where serve speed, rally tolerance, and error rates diverge from earlier sets in measurable and consistent directions.",
        "stat_signature": "First-serve speed averages 2-5 km/h below set-1 baseline in three-set matches; unforced errors per game rise 8-15% versus the match mean; average rally length shortens 0.3-0.6 shots as depleted players abbreviate exchanges.",
        "mechanism": "Cumulative glycogen depletion and lactate accumulation impair neuromuscular coordination; cognitive fatigue narrows tactical range, compressing shot selection toward high-frequency patterns and increasing decision errors.",
        "conditions": "Strongest after extended rallies on clay; partially offset by the inter-set rest interval; more pronounced when preceding sets were contested rather than one-sided.",
        "magnitude": "Deciding-set break rates exceed set-1 rates by 4-9% on hard courts.",
        "links": ["third_set_fatigue_phase", "set_by_set_efficiency_drift", "deciding_set_tiebreak_format", "pressure_game_density_by_set"],
    },
    {
        "slug": "deciding_set_tiebreak_format",
        "title": "Deciding-Set Tiebreak-Format Phase",
        "summary": "The variance-compressing resolution of the final set via a seven- or ten-point tiebreak, reducing expected games played and flattening quality differentials relative to an advantage set.",
        "stat_signature": "A ten-point match tiebreak compresses expected point count to roughly 16-22 points from an uncapped advantage-set tail; upset frequency rises approximately 12-18% under the super-tiebreak format relative to equivalent-quality advantage sets.",
        "mechanism": "Small-sample variance dominates a ten-point breaker: a single mini-break at 5-5 shifts win probability by ~45 points, amplifying luck and momentary serve peaks over sustained quality accumulated in a long match.",
        "conditions": "Applies under tournament-specific rules; most ATP and WTA events use the ten-point match tiebreak; the seven-point format is used at some Grand Slams after 6-6 in the final set.",
        "magnitude": "Variance of match outcome roughly doubles under a ten-point super-tiebreak compared with an uncapped advantage set.",
        "links": ["tiebreak_phase_dynamics", "deciding_set_phase", "tiebreak_serve_dependence"],
    },
    {
        "slug": "changeover_reset_effect",
        "title": "Changeover Reset Effect",
        "summary": "The 90-second odd-game interruption that disrupts momentum and allows tactical recalibration, measurably moving the next game's scoring rate back toward baseline expectation.",
        "stat_signature": "Point-win rate in the game immediately after a changeover is 1.5-3 percentage points closer to baseline than in the preceding game; double-fault rate drops 10-15% in the post-changeover service game.",
        "mechanism": "Partial physiological recovery reduces serve-speed deficit; tactical reset via self-analysis allows pattern adjustment; momentum decays fastest at structural breaks, and the changeover is the primary mid-set break.",
        "conditions": "Effect is most measurable when one player won the preceding game at love or 15, indicating a momentum run that the changeover interrupts; smaller after closely contested games.",
        "magnitude": "Post-changeover games revert roughly 40-60% of a scoring-rate deviation built in the preceding momentum run.",
        "links": ["momentum_after_set_won", "break_back_response_phase", "new_balls_phase"],
    },
    {
        "slug": "new_balls_phase",
        "title": "New-Balls Phase",
        "summary": "The recurring switch to fresh balls (every 7 then every 9 games) that increases bounce height, reduces felt depth, and temporarily elevates first-serve effectiveness and ace frequency.",
        "stat_signature": "Ace rate rises 15-25% in the two games after a ball change; first-serve points won increases roughly 2-4 percentage points; double-fault rate is unchanged, confirming the benefit is aerodynamic rather than control-related.",
        "mechanism": "Fresh balls are lighter with fuller felt, producing higher bounce and more skid on hard courts; returns have marginally less time after the bounce, compressing the returner's reaction window.",
        "conditions": "Effect is amplified on fast hard courts and grass; minimal on clay where high bounce and heavy top-spin flatten the aerodynamic advantage of fresh felt.",
        "magnitude": "Roughly 1-2 additional aces per set attributable to ball-change games on fast hard courts.",
        "links": ["return_game_rhythm_phase", "tiebreak_serve_dependence", "opening_set_settling_phase"],
    },
    {
        "slug": "return_game_rhythm_phase",
        "title": "Return-Game Rhythm Phase",
        "summary": "The alternating non-serving games where break pressure is applied and return efficiency accumulates across the match as the returner reads the opponent's serve pattern across increasing sample size.",
        "stat_signature": "Return-points-won typically starts 1-3 points below match mean in set 1 and drifts upward 2-4 points in sets 2-3; break-points created per return game rises 10-20% from set 1 to set 3.",
        "mechanism": "Serve-read is a sample-accumulation process: each return game adds data on wide/body/T frequency and spin depth, enabling increasingly efficient footwork positioning and early-ball targeting.",
        "conditions": "Most observable in long matches on hard courts with consistent bounce; less clear on grass where bounce variation limits pattern stability.",
        "magnitude": "Return-game break probability increases roughly 3-6% from set 1 to set 3 absent fatigue confounds.",
        "links": ["opening_games_break_propensity", "new_balls_phase", "set_by_set_efficiency_drift"],
    },
    {
        "slug": "late_set_tightening_phase",
        "title": "Late-Set Tightening Phase",
        "summary": "The pressure compression as a set nears conclusion past 5 games each, marked by rising deuce-game frequency, falling first-serve percentage, and risk-averse shot selection.",
        "stat_signature": "Deuce-game frequency rises roughly 15-25% in games 9-12 of a set compared with games 3-8; first-serve percentage drops an estimated 3-5 points; net-approach frequency decreases as players protect the score.",
        "mechanism": "Both players shorten shot selection toward high-percentage patterns under scoreboard pressure, paradoxically increasing deuce frequency because errors-on-approach fall while forcing opportunities also decline.",
        "conditions": "Most visible in tight sets trending toward a tiebreak; absent in blowout sets where one player breaks decisively early.",
        "magnitude": "Average game length rises roughly 0.5-1.0 points per game in late-set games relative to mid-set.",
        "links": ["tiebreak_phase_dynamics", "serving_for_the_set_phase", "pressure_game_density_by_set"],
    },
    {
        "slug": "momentum_after_set_won",
        "title": "Momentum-After-Set-Won Phase",
        "summary": "The measurable carryover swing into the opening games of the next set after a set is decided, captured as conditional first-game break rate and early-point-win shift for the set winner.",
        "stat_signature": "Set winner breaks first in the subsequent set at a rate roughly 8-14% above the unconditional break rate; point-win rate in the first two games of the next set is approximately 2-4 points higher than the winner's match mean.",
        "mechanism": "Set conclusion creates competing forces: the loser is motivated to reset but the winner benefits from confidence and opponent discouragement; net direction is a modest winner-favoring effect decaying within 3-4 games of the new set.",
        "conditions": "Strongest when the preceding set was decided by a decisive break rather than a close tiebreak; tiebreak losers can attribute the outcome to variance, dampening the psychological carry.",
        "magnitude": "Conditional break lift of roughly 5-10 percentage points in the opening two games of the following set.",
        "links": ["opening_set_settling_phase", "early_set_break_window", "changeover_reset_effect", "break_back_response_phase"],
    },
    {
        "slug": "third_set_fatigue_phase",
        "title": "Third-Set Fatigue Phase",
        "summary": "Physical decline in extended matches reaching a third set, measured as serve-speed drop, rally-length shortening, and unforced-error rise relative to the opening set.",
        "stat_signature": "First-serve speed falls 2-5 km/h in set 3 relative to set 1 in contested hard-court matches; unforced errors per game rise 10-18% versus the match mean; average rally length shortens 0.4-0.8 shots per point.",
        "mechanism": "Sustained aerobic and anaerobic exertion depletes phosphocreatine and glycogen, impairing fast-twitch power and lateral sprint speed; the resulting serve-speed drop and reduced coverage amplify break probability.",
        "conditions": "Most pronounced on clay after rallies averaging 5+ shots per point; partially offset by the 10-minute inter-set rest; surface-mediated by whether match pace was physical or serve-dominated.",
        "magnitude": "Third-set break rate rises 5-10% above set-1 baseline on hard courts.",
        "links": ["deciding_set_phase", "set_by_set_efficiency_drift", "pressure_game_density_by_set"],
    },
    {
        "slug": "set_by_set_efficiency_drift",
        "title": "Set-by-Set Efficiency Drift",
        "summary": "The trend in serving and return efficiency across successive sets, measured as the slope of first-serve points won and return points won across sets 1-3, reflecting simultaneous serve-read accumulation and serve-power depletion.",
        "stat_signature": "First-serve points won declines on average ~1.5 points per set in contested three-set hard-court matches; return-points-won rises ~1.5 points per set symmetrically, as read improves and serve power depletes.",
        "mechanism": "Two compounding processes: the returner accumulates serve-read data each game, improving positioning; simultaneously the server's explosive power budget depletes, reducing speed and spin margin — together they drive break-rate convergence across sets.",
        "conditions": "Most reliable when neither player dominates serve enough to win games at love consistently; masked in lopsided matches where serve quality holds throughout.",
        "magnitude": "Expected break-rate differential between set 1 and set 3 is roughly 4-8 points, all else equal.",
        "links": ["return_game_rhythm_phase", "third_set_fatigue_phase", "deciding_set_phase", "opening_set_settling_phase"],
    },
    {
        "slug": "break_back_response_phase",
        "title": "Break-Back Response Phase",
        "summary": "The service game immediately following a loss of serve where the just-broken player creates break-back chances at elevated frequency, driven by aggressive return positioning and occasional relaxation by the player who just broke.",
        "stat_signature": "Conditional break rate in the game directly following a break against is roughly 28-36% — 6-12 points above the unconditional break rate; this is the single highest-break-probability game type within a set.",
        "mechanism": "Psychological rebound compels the just-broken player toward aggressive return positioning and early-ball targets; the opponent who just broke may relax ('banking the break'), briefly widening the window for an immediate counter-break.",
        "conditions": "Strongest when the break was achieved quickly at 15 or 30; less pronounced when the break required five deuces and both players are fatigued from the extended game.",
        "magnitude": "Unconditional hold rate drops roughly 8-12 percentage points for the player who just broke, in the game immediately after their break.",
        "links": ["serving_to_stay_in_set_phase", "early_set_break_window", "momentum_after_set_won", "changeover_reset_effect"],
    },
    {
        "slug": "opening_games_break_propensity",
        "title": "Opening-Games Break Propensity",
        "summary": "The elevated likelihood of a break in the first two service games of each set before serve rhythm fully re-establishes, most visible in the opening games of sets 2 and 3 when fatigue adds to the calibration lag.",
        "stat_signature": "Break rate in the first two service games of a set is roughly 3-6% above the mid-set (games 3-8) break rate; double-fault frequency is 20-35% above mid-set average in these opening games.",
        "mechanism": "Inter-set transitions interrupt the serve-rhythm groove: muscles cool slightly, footwork timing resets, and tactical patterns resume from scratch; the first two games represent the re-convergence window before full rhythm restores.",
        "conditions": "Strongest at the start of sets 2 and 3 in long matches; less pronounced in set 1 where both players begin from equivalent warm-up states.",
        "magnitude": "Break probability roughly 3-6 points higher in games 1-2 of a set than in games 4-8 on hard courts.",
        "links": ["opening_set_settling_phase", "early_set_break_window", "serving_first_in_set_advantage"],
    },
    {
        "slug": "serving_first_in_set_advantage",
        "title": "Serving-First-in-Set Advantage",
        "summary": "The scoreboard-pressure asymmetry from which player serves first within a set, giving the first server a measurable set-win lift because the trailer must break while the leader only needs to hold.",
        "stat_signature": "The player serving first wins that set roughly 52-54% of the time on hard courts versus 46-48% for the server-second — a 4-6 point split; the advantage is ~2-3 points on clay and ~6-8 points on grass.",
        "mechanism": "Leading the service rotation means the set-trailer must break while the leader absorbs pressure by holding; each hold by the leader forces the trailer to hold just to stay even, creating asymmetric emotional loading over the set's duration.",
        "conditions": "Effect amplifies when hold rates are high (fast surfaces), because a break by the trailer requires a larger deviation from baseline; diminishes on clay where breaks are more frequent.",
        "magnitude": "Serving first provides a 4-6 percentage point set-win lift over random expectation across ATP hard-court events.",
        "links": ["early_set_break_window", "tiebreak_phase_dynamics", "opening_games_break_propensity", "serving_for_the_set_phase"],
    },
    {
        "slug": "pressure_game_density_by_set",
        "title": "Pressure-Game Density by Set",
        "summary": "The increasing concentration of deuce and break-point games in later sets, reflecting fatigue-driven shot-margin compression and heightened stakes as the match approaches conclusion.",
        "stat_signature": "Deuce-game share rises from roughly 28-32% of games in set 1 to 34-40% in set 3; break-points-faced per service game increases from ~0.55 in set 1 to ~0.70 in set 3; average games per set increases ~0.8-1.5 in set 3.",
        "mechanism": "Physical depletion narrows shot margin, preventing games from closing quickly at 40-0 or 40-15; break-point density amplifies the impact of conversion efficiency in the deciding set beyond what baseline break rates would suggest.",
        "conditions": "Strongest in physically taxing clay-court matches with long rallies; partially suppressed on grass or indoor hard where serve dominance persists across sets.",
        "magnitude": "Break-point density is roughly 15-25% higher in set 3 than set 1 on hard courts; 20-35% on clay.",
        "links": ["third_set_fatigue_phase", "deciding_set_phase", "late_set_tightening_phase", "set_by_set_efficiency_drift"],
    },
]
