"""MLB GamePhases concepts — person-free, descriptive intelligence nodes for
temporal and structural phases of a baseball game."""
from __future__ import annotations

SPORT = "MLB"
FAMILY = "GamePhases"

CONCEPTS: list[dict] = [
    {
        "slug": "first_inning_vulnerability",
        "title": "First-Inning Vulnerability Phase",
        "summary": "Starters face the top of the order cold, without in-game feel for spin rate, grip, or mound surface, producing a reliably elevated first-inning ERA relative to the same pitcher's overall innings distribution.",
        "stat_signature": "First-inning ERA roughly 0.30–0.55 runs above the same starter's second-through-fifth-inning ERA. First-inning OPS against roughly 0.730–0.760 versus ~0.700–0.720 in innings two through four. Walk rate rises ~0.4–0.8 BB/9 in the first inning versus all-inning average.",
        "mechanism": "Pitchers calibrate release point, arm speed, and secondary-pitch feel through the first several batters; until that calibration settles, command sits at its loosest point of the outing. Hitters in the top of the order are also fresh and most likely to work counts.",
        "conditions": "Strongest for pitchers with a below-average first-pitch-strike rate or a repertoire dependent on feel-based breaking balls. Cold-weather games and mounds with unfamiliar firmness amplify the calibration lag. Effect attenuates for high-walk-rate pitchers who warm up extensively in the bullpen.",
        "magnitude": "First-inning run rate roughly 20–35 percent above the pitcher's per-inning seasonal average; roughly one additional run per 10 first-inning appearances at the extreme of the vulnerability distribution.",
        "links": ["first_time_through_order", "first_pitch_of_game_tone", "pitch_count_threshold_phase", "times_through_order_penalty"],
    },
    {
        "slug": "first_time_through_order",
        "title": "First-Time-Through-the-Order Phase",
        "summary": "The first nine plate appearances represent peak starter advantage — tunneling novelty is intact, hitters have no within-game pitch-sequence data, and repertoire depth is undisclosed.",
        "stat_signature": "wOBA against in the first pass roughly 0.290–0.315. Swing-and-miss rate highest in the first pass: roughly 11–13 percent versus 10–11.5 percent in subsequent passes. BA against roughly .230–.250.",
        "mechanism": "Pitchers exploit the information asymmetry of an undisclosed arsenal; hitters must make reactive decisions without count-conditional pitch tendencies. Deception through tunneling — pitches sharing an early flight path — is most effective before hitters have catalogued delivery patterns.",
        "conditions": "Advantage is largest for starters with three or more effective pitch types and above-average tunnel efficiency. Against patient lineups that run deep counts, the tunnel advantage erodes faster as pitch-type exposure accumulates.",
        "magnitude": "wOBA gap between first and third time through order roughly 0.045–0.065; strikeout rate in the first pass is roughly 5–10 percent above the starter's season average.",
        "links": ["times_through_order_penalty", "first_inning_vulnerability", "middle_innings_grind_phase", "opener_bulk_structure"],
    },
    {
        "slug": "times_through_order_penalty",
        "title": "Times-Through-the-Order Penalty",
        "summary": "Each successive pass through the lineup erodes starter effectiveness as hitters accumulate in-game pitch data, forcing pitchers into narrower arsenals with deteriorating command and reduced deception.",
        "stat_signature": "wOBA against rises roughly 0.020–0.030 from first to second pass and a further 0.025–0.040 from second to third. Third-time-through OPS against roughly 0.760–0.810 versus 0.680–0.710 in the first pass. ERA increases roughly 0.3–0.5 runs per additional lineup turn.",
        "mechanism": "Repeated exposure allows hitters to build within-game priors on pitch sequencing, release-point cues, and count-conditional tendencies. Pitchers simultaneously accumulate pitch-count fatigue that flattens trajectory differentiation and reduces late-movement amplitude.",
        "conditions": "Effect is strongest for two-pitch starters and those relying on horizontal movement pitches whose release-point cue is more exposed over multiple passes. High-strikeout, high-spin pitchers partially resist the third-pass penalty through pure stuff.",
        "magnitude": "Roughly 0.3–0.5 additional expected runs per nine innings on each successive pass; third-time-through OPS disadvantage of 0.080–0.130 above first-pass OPS against.",
        "links": ["first_time_through_order", "middle_innings_grind_phase", "bullpen_handoff_phase", "pitch_count_threshold_phase"],
    },
    {
        "slug": "middle_innings_grind_phase",
        "title": "Middle-Innings Grind Phase",
        "summary": "Innings four through six represent the contested zone where starters carry accumulating pitch counts, bullpens remain unused, and the balance between per-inning run suppression and efficient depth consumption is most strained.",
        "stat_signature": "Strikeout rate decays roughly 0.4–0.8 K/9 between innings one through three and innings four through six for starters. Run-expectancy per inning is roughly 0.05–0.12 runs higher in innings four through six than innings two through three. Pitch count rises roughly 15–20 per inning through this band.",
        "mechanism": "Cumulative pitch load suppresses velocity by 0.3–0.7 mph and narrows breaking-ball sweep by the fourth and fifth innings; hitters accumulating pitch-sequence data from prior at-bats exploit the reduced deception. Bullpen conservation logic keeps relief arms idle until leverage or count thresholds are reached.",
        "conditions": "Pronounced for pitchers without a dominant four-pitch arsenal; starters with elite stamina metrics (low walks, high contact-quality suppression) extend competitiveness deeper into this phase. Run environment and lineup depth modulate how fast the pitch-count penalty materializes.",
        "magnitude": "Strikeout rate decay of 0.4–0.8 K/9; ERA in innings four through six roughly 0.20–0.40 runs above innings two through three for typical starter samples.",
        "links": ["times_through_order_penalty", "pitch_count_threshold_phase", "bullpen_handoff_phase", "opener_bulk_structure"],
    },
    {
        "slug": "high_leverage_late_innings",
        "title": "High-Leverage Late-Innings Phase",
        "summary": "The seventh-through-ninth window concentrates the highest average leverage index of any inning band; each base-out state within it swings win probability most sharply and draws the most precisely matched relief deployment.",
        "stat_signature": "Average leverage index in innings seven through nine: roughly 1.3–1.7 versus ~0.8–1.0 in innings one through three. Reliever ERA in this window for top-tier bullpens roughly 3.00–3.50, suppressing scoring ~15–20 percent below league average. wOBA against in LI-above-2.0 states roughly 0.260–0.285.",
        "mechanism": "Managers allocate highest-quality relievers to the highest-LI states; the selection effect compounds individual reliever quality. Win-probability sensitivity per baserunner is greatest in close late-inning frames, aligning maximum roster investment with maximum scoring consequence.",
        "conditions": "Effect is most pronounced when both clubs have deep bullpens and a one-run margin persists into the seventh inning. Thin-bullpen teams blunt the concentration effect by necessity; parks with short porches amplify the high-LI scoring risk even with elite relief.",
        "magnitude": "Scoring-rate suppression of roughly 15–22 percent relative to league average in high-leverage late-inning states; the LI differential between innings seven through nine and innings one through three is roughly 0.5–0.8 LI units.",
        "links": ["save_situation_ninth", "bullpen_handoff_phase", "closer_warmup_readiness_phase", "late_game_platoon_matching"],
    },
    {
        "slug": "save_situation_ninth",
        "title": "Save-Situation Ninth-Inning Phase",
        "summary": "The three-run-or-less closing frame handled by a designated finisher concentrates the highest-quality single-inning relief in the game, producing systematically distinct run-prevention rates relative to non-save ninth innings.",
        "stat_signature": "Closer OPS against in save situations roughly 0.620–0.660 versus ~0.720–0.750 in non-save ninth innings. Walk rate in save-state ninth: roughly 2.0–2.8 BB/9. Blown-save frequency roughly 14–18 percent across the league closer tier.",
        "mechanism": "Save situations trigger a highly specific selection effect — teams deploy their single highest-leverage arm in a narrow context; the finisher benefits from a specific warm-up rhythm tuned to entering in the ninth, optimizing velocity and command relative to multi-inning relief appearances.",
        "conditions": "Run-prevention advantage most stable for finishers with proven high-LI experience; blown-save rate rises materially for pitchers in the finisher role with below-average strikeout rates who rely on contact suppression. Road save situations show slightly elevated blown-save frequency.",
        "magnitude": "OPS-against differential between save and non-save ninth innings roughly 0.060–0.090; save conversion rate at the top closer tier roughly 82–86 percent season-wide.",
        "links": ["high_leverage_late_innings", "closer_warmup_readiness_phase", "late_game_platoon_matching", "bullpen_handoff_phase"],
    },
    {
        "slug": "opener_bulk_structure",
        "title": "Opener-and-Bulk Phase Structure",
        "summary": "A two-pitcher staffing pattern where a short-stint reliever pitches the first one or two innings ahead of a bulk arm disrupts hitter-sequencing expectations and resets the times-through-order count for the bulk pitcher.",
        "stat_signature": "Opener stint length: typically one inning, allowing roughly 15–22 pitches. Bulk arm enters at inning two or three; first-time-through advantage resets. Teams using this structure show opener ERA roughly 3.80–4.50 in the opener inning, with the bulk arm inheriting first-time-through advantage from inning two onward.",
        "mechanism": "The bulk pitcher faces hitters in their first true exposure to his arsenal from inning two, despite the game already being underway; the opener's inning eliminates the line-up's first-pass bonus against the bulk arm's actual pitch mix, shifting the times-through-order curve by one full pass.",
        "conditions": "Most effective against lineups with a potent top three that would otherwise see a starter's best arsenal fresh; requires a reliable opener arm that can avoid big innings in a short high-leverage burst. Platoon-based opener selection amplifies effectiveness by exploiting handedness asymmetry against the top of the order.",
        "magnitude": "Bulk-arm first-time-through wOBA advantage of roughly 0.020–0.040 relative to traditional starter deployment from inning one; opener usage has risen from under 1 percent of starts to roughly 7–12 percent in recent seasons.",
        "links": ["first_time_through_order", "bullpen_handoff_phase", "late_game_platoon_matching", "middle_innings_grind_phase"],
    },
    {
        "slug": "bullpen_handoff_phase",
        "title": "Bullpen-Handoff Phase",
        "summary": "The transition from starter to relief corps creates a matchup leverage point where platoon alignment, pitch-mix novelty, and warm-up readiness all converge to determine whether the handoff suppresses or inflates run scoring.",
        "stat_signature": "First batter faced by a relief entrant: wOBA against roughly 0.310–0.340, roughly 15–20 percent above the same reliever's full-appearance average. Walk rate in first batter faced: roughly 0.5–0.8 BB/9 above season norm. Platoon-advantaged handoffs reduce wOBA against first batter by roughly 0.020–0.040.",
        "mechanism": "The first batter of a relief appearance carries maximum cold-start command risk before the pitcher has integrated mound surface, grip feel, and in-game trajectory. Hitters facing a new arm lack previous-at-bat experience, partially offsetting the command disadvantage with their own elevated swing uncertainty.",
        "conditions": "The command penalty is largest in the first batter faced after a long bullpen wait (20-plus minutes); it is attenuated when the reliever warmed up in a high-energy extended session simulating game tempo. Managers who execute the handoff with a platoon advantage convert the match-up edge into measurable OPS suppression.",
        "magnitude": "First-batter wOBA above reliever average roughly 0.025–0.040; over the course of a season, suboptimal handoff timing (wrong platoon, cold entrant) costs roughly 0.10–0.18 runs per handoff event.",
        "links": ["high_leverage_late_innings", "opener_bulk_structure", "closer_warmup_readiness_phase", "late_game_platoon_matching"],
    },
    {
        "slug": "leadoff_of_inning_dynamics",
        "title": "Leadoff-of-Inning Dynamics",
        "summary": "The base-empty plate appearance opening each frame sets run expectancy for the entire inning; a leadoff on-base event roughly doubles scoring probability and reshapes both dugouts' within-inning strategic posture.",
        "stat_signature": "Leadoff on-base rate (OBP): league average roughly .330–.345. Conditional run-scoring probability when leadoff reaches: roughly 40–45 percent versus 15–18 percent with leadoff out. Run-expectancy difference between leadoff-on and leadoff-out: roughly 0.55–0.65 runs.",
        "mechanism": "With no outs and a runner on base, the batting team gains both run-expectancy value and strategic optionality (stolen base, sacrifice, hit-and-run) that compress the pitcher's zone-management choices; pitchers with poor leadoff OBP-against effectively multiply the number of high-leverage plate appearances faced per inning.",
        "conditions": "Effect is largest in innings four through seven where bullpen preservation incentives suppress early relief entry and a leadoff reach extends starter exposure deep into high-risk territory. Against fly-ball-heavy pitchers in run-enhancer parks, a leadoff double carries especially high run-expectancy uplift.",
        "magnitude": "A one-percentage-point improvement in leadoff OBP corresponds to roughly 0.08–0.12 additional runs per game in expectation; the gap between top and bottom quartile leadoff OBP-against is roughly 0.040–0.060, translating to roughly 0.3–0.5 runs per game.",
        "links": ["two_out_inning_phase", "scoring_burst_clustering", "run_expectancy_decay_by_inning", "middle_innings_grind_phase"],
    },
    {
        "slug": "two_out_inning_phase",
        "title": "Two-Out Inning Phase",
        "summary": "The within-inning state after two outs collapses run expectancy to its lowest level, reshaping offensive approach toward all-or-nothing contact and measuring a pitching staff's ability to strand baserunners efficiently.",
        "stat_signature": "Run expectancy with two outs and bases empty: roughly 0.10 runs. Two-out RBI rate: roughly 25–30 percent of all runs scored. Two-out OPS roughly 0.700–0.730 versus 0.760–0.780 with no outs. Share of innings where runs score after two outs: roughly 8–12 percent of all innings.",
        "mechanism": "With two outs any ball in play must reach base to continue the inning; pitchers shift toward chase-inducing pitch types at zone edges, knowing a single strikeout or groundball ends the threat. Hitters with high two-strike OPS disproportionately contribute in this phase versus hitters who collapse markedly with two strikes.",
        "conditions": "Two-out run-scoring is most frequent against pitchers with below-average chase rates who cannot reliably force zone expansion; in high run-environment parks the two-out hit-for-extra-bases probability is meaningfully elevated. Clutch two-out performance is highly variable and regresses toward league average over full seasons.",
        "magnitude": "Two-out run-expectancy roughly 55–65 percent below zero-out run-expectancy at the same base state; yet two-out plate appearances account for roughly 35–38 percent of all game plate appearances, making this phase voluminous despite low scoring rate per PA.",
        "links": ["leadoff_of_inning_dynamics", "scoring_burst_clustering", "full_count_at_bat_phase", "run_expectancy_decay_by_inning"],
    },
    {
        "slug": "full_count_at_bat_phase",
        "title": "Full-Count At-Bat Phase",
        "summary": "The three-and-two count is the most decisive within-plate-appearance state, forcing the pitcher to throw a hittable strike while hitters must be ready to swing, producing the highest walk and strikeout rates of any count.",
        "stat_signature": "Full-count walk rate: roughly 28–35 percent. Full-count strikeout rate: roughly 32–40 percent. Full-count contact-quality: hard-hit rate roughly 1–3 percent above overall at-bat average. BA on full-count contact: roughly 0.280–0.310 versus 0.260–0.280 on two-strike contact overall.",
        "mechanism": "The three-two count removes the pitcher's ability to throw a ball without consequence; this forces the most hittable pitch in the sequence, raising contact quality when hitters make contact. Simultaneously, high-velocity pitchers gain a strikeout premium because hitters in protection mode swing at borderline pitches.",
        "conditions": "Full-count frequency is highest against patient lineups and high-walk-rate pitchers; it is lowest against aggressive zone-attacking pitchers who induce early contact. The full-count walk rate rises significantly for pitchers whose fastball command is below average, creating disproportionate run-expectancy impact.",
        "magnitude": "Full-count at-bats resolve in a walk or strikeout roughly 60–75 percent of the time; hard-hit-rate premium on full-count contact is roughly 1.5–3.0 percentage points above the batter's season average.",
        "links": ["two_out_inning_phase", "leadoff_of_inning_dynamics", "times_through_order_penalty", "pitch_count_threshold_phase"],
    },
    {
        "slug": "late_inning_pinch_phase",
        "title": "Late-Inning Pinch-Hit Phase",
        "summary": "The seventh-inning-and-beyond substitution window allows managers to insert a right-handed or left-handed bat for a platoon advantage, concentrating bench production into the highest-leverage matchups of the game.",
        "stat_signature": "Pinch-hit appearances in innings seven-plus: roughly 0.8–1.4 per game. Platoon-advantaged pinch appearances show wOBA improvement of roughly 0.030–0.055 above the replaced hitter's projected at-bat value. League-wide pinch-hit BA roughly .225–.245, reflecting cold-at-bat penalty.",
        "mechanism": "The bench hitter enters without in-game rhythm, facing a pitcher seen at most once before in the game; the platoon-advantage wOBA gain partially offsets the cold-at-bat BA penalty. Manager decisions concentrate pinch appearances in the highest-LI states, making the selection effect central to interpreting pinch-hit aggregate statistics.",
        "conditions": "Effectiveness is highest when the platoon gap is above the league median (0.040-plus OPS split) and the relief arm is a true specialist. The cold-at-bat penalty is minimized for hitters who maintain regular off-day plate appearances through extended-batting-practice routines.",
        "magnitude": "Net pinch-hit wOBA uplift after controlling for cold-at-bat penalty: roughly 0.010–0.025 above expectation of the removed hitter; the full platoon advantage without the cold penalty would be roughly 0.035–0.055.",
        "links": ["late_game_platoon_matching", "high_leverage_late_innings", "bullpen_handoff_phase", "save_situation_ninth"],
    },
    {
        "slug": "first_pitch_of_game_tone",
        "title": "First-Pitch-of-Game Tone Phase",
        "summary": "The very first delivery calibrates command readiness, bullpen urgency, and hitter aggression; first-pitch-strike rate in the opening plate appearance predicts the starter's command profile for the first two innings.",
        "stat_signature": "First-pitch strike rate in opening PA: league average roughly 59–63 percent. Starters who throw a first-pitch ball in the game-opening PA: BB/9 roughly 0.3–0.5 above their season norm for the first inning. Early-count swing rate by leadoff hitter roughly 25–35 percent on first pitches.",
        "mechanism": "The first pitch serves as a live calibration signal; a ball reveals grip or release-point instability that propagates into subsequent hitters as pitchers compensate by shortening arm action, reducing velocity, or altering sequencing. Hitters and their dugout process this information in real time to calibrate early-inning aggressiveness.",
        "conditions": "Signal is largest for command-dependent pitchers (below-average walk rate reliant on location). Cold-weather conditions amplify calibration lag, making the first-pitch-ball rate a stronger early-warning signal than in warm-weather games.",
        "magnitude": "First-pitch-ball starters show first-inning ERA roughly 0.15–0.25 runs above first-pitch-strike starters in matched game samples; a single first-inning walk is predictive of at least one additional walk in the same inning roughly 35–40 percent of the time.",
        "links": ["first_inning_vulnerability", "pitch_count_threshold_phase", "leadoff_of_inning_dynamics", "first_time_through_order"],
    },
    {
        "slug": "pitch_count_threshold_phase",
        "title": "Pitch-Count Threshold Phase",
        "summary": "Beyond roughly 75–100 pitches a starter's command, velocity, and spin rate measurably erode, inflecting the times-through-order penalty with a compounding fatigue signal that predicts run-allowance acceleration.",
        "stat_signature": "Pitch 76–90: velocity drop roughly 0.3–0.5 mph; walk rate rise roughly 0.5–0.8 BB/9 above outing average. Pitch 91–105: velocity drop roughly 0.6–0.9 mph; hard-hit rate rises roughly 1.5–3.0 percentage points. ERA in high-pitch-count plate appearances roughly 0.40–0.70 runs above same-pitcher low-pitch-count PA.",
        "mechanism": "Progressive recruitment of compensatory muscle groups alters release-point consistency and reduces the precision of secondary-pitch placement; as command precision falls, pitchers must throw pitches more centrally to avoid walks, increasing the probability of contact in the barrel-path zone.",
        "conditions": "Threshold is lower for pitchers with high-effort deliveries (extension-heavy mechanics) and is modulated by prior-day bullpen workload. Hot-weather games accelerate dehydration-driven performance degradation. Young starters with fewer than 100 career starts show earlier degradation than veteran arms.",
        "magnitude": "Roughly 0.40–0.70 ERA-equivalent decline beyond the 90-pitch mark relative to same-pitcher below-75-pitch performance; the hard-hit-rate inflection is the most stable predictive signal, persisting across pitch-count bands even when ERA surface-level results are noisy.",
        "links": ["times_through_order_penalty", "middle_innings_grind_phase", "bullpen_handoff_phase", "first_inning_vulnerability"],
    },
    {
        "slug": "closer_warmup_readiness_phase",
        "title": "Closer Warm-Up Readiness Phase",
        "summary": "The eighth-inning window determines whether a finisher enters the ninth fresh, over-warmed, or without preparation; warm-up protocol mismatches between leverage timing and actual entry timing degrade run prevention in the closing frame.",
        "stat_signature": "Finishers who warm up but do not enter in the eighth show ninth-inning ERA roughly 0.25–0.40 runs above their season average in the subsequent outing. Finishers used on back-to-back days: blown-save rate rises roughly 3–5 percentage points above single-day baseline. Readiness-optimal entry (one warm-up session, entering as planned): walk rate closest to season baseline.",
        "mechanism": "The closing inning requires peak neuromuscular precision; excess warm-up pitches accumulate fatigue without the adrenaline of game action, while insufficient warm-up leaves the release-point uncalibrated. Prior-day usage depletes the elastic energy in the forearm flexors that drive late-movement amplitude.",
        "conditions": "Disrupted warm-up timing is most common in high-leverage eighth-inning threats that occupy the bullpen catcher but resolve without an entry; games with ninth-inning lead changes expose the finisher to double-warm-up protocols that accelerate fatigue.",
        "magnitude": "ERA impact of warm-up disruption roughly 0.25–0.50 runs above baseline; back-to-back usage blown-save premium roughly 3–5 percentage points, representing a meaningful conversion-probability shift in a leverage-critical context.",
        "links": ["save_situation_ninth", "high_leverage_late_innings", "bullpen_handoff_phase", "late_game_platoon_matching"],
    },
    {
        "slug": "run_expectancy_decay_by_inning",
        "title": "Run-Expectancy Decay by Inning",
        "summary": "Expected runs per half-inning follows a measurable curve across nine frames: elevated early against a tiring starter, depressed in mid-innings as starters are most efficient, then rising through the sixth before collapsing in the late innings as elite relief enters.",
        "stat_signature": "Average runs per half-inning: inning one roughly 0.48–0.52 (starter cold); innings two through four roughly 0.43–0.47 (peak starter efficiency); innings five through six roughly 0.48–0.52 (fatigue inflection); innings seven through nine roughly 0.38–0.44 (elite relief selection effect). Inflection between innings six and seven is the sharpest step-down.",
        "mechanism": "The curve reflects the compounding of starter fatigue against hitter information accumulation in mid-to-late innings, punctuated by the strategic substitution of elite relief that resets run-suppression to a new lower level. Each successive inning narrows the roster available for the remaining frames, creating a concave depth-depletion effect.",
        "conditions": "The inning-six-to-seven step-down is largest in games where a closer-quality arm is available and the lead margin is within three runs. In blowout states, the quality of pitching deployed in late innings regresses toward league-average, flattening the decay curve.",
        "magnitude": "Inning-six-to-seven run-expectancy step-down roughly 0.06–0.12 runs per half-inning; across a full game, the decay curve implies roughly 0.40–0.60 fewer runs in innings seven through nine than a flat-rate projection would suggest.",
        "links": ["high_leverage_late_innings", "bullpen_handoff_phase", "leadoff_of_inning_dynamics", "scoring_burst_clustering"],
    },
    {
        "slug": "late_game_platoon_matching",
        "title": "Late-Game Platoon-Matching Phase",
        "summary": "The endgame sequencing of relief and pinch moves to align handedness represents the highest-precision version of platoon advantage deployment, producing the most controllable wOBA shift of any tactical lever available to the dugout.",
        "stat_signature": "Late-game platoon-advantaged plate appearances (innings seven-plus): wOBA against roughly 0.020–0.045 below same-reliever mixed-platoon average. Share of seventh-inning-plus PA with platoon advantage: roughly 55–65 percent for well-resourced bullpens versus 48–52 percent for shallow ones. Late-inning pitching changes per game: roughly 1.8–2.5.",
        "mechanism": "Opposite-handedness batters see breaking balls moving into their swing plane from a more visible angle; pitchers with pronounced platoon splits gain a material contact-quality suppression bonus when matched correctly. Roster depth determines how consistently a team can execute the match without exhausting high-leverage arms.",
        "conditions": "Advantage is most actionable for pitchers with platoon splits above 0.040 OPS gap; it is largely neutral for true platoon-neutral pitchers (sub-0.020 gap). Extra-inning ghost-runner states suppress strategic switching due to the loaded-base risk of the walk allowed to force the match.",
        "magnitude": "Per-appearance wOBA improvement from platoon matching of roughly 0.020–0.045; across a season, a team that maximizes late-game platoon-matching frequency suppresses roughly 0.08–0.15 additional runs per game in the seventh through ninth innings.",
        "links": ["high_leverage_late_innings", "late_inning_pinch_phase", "bullpen_handoff_phase", "save_situation_ninth"],
    },
    {
        "slug": "scoring_burst_clustering",
        "title": "Inning Scoring-Burst Clustering",
        "summary": "Runs in a game concentrate within a small number of high-output innings rather than distributing evenly across nine frames; the single biggest inning accounts for a disproportionate share of total scoring and shapes over-under distribution.",
        "stat_signature": "Share of game runs from the single highest-scoring inning: roughly 30–40 percent league-wide. Multi-run-inning frequency: roughly 2.5–3.5 per game. Probability that a game contains a four-plus-run inning: roughly 35–45 percent. Median total runs in the top-scoring inning: roughly 2.3–2.8.",
        "mechanism": "Scoring begets scoring within an inning through base-state compounding — each successive base-runner inflates run-expectancy multiplicatively rather than additively. Pitching changes rarely occur mid-inning until significant damage has occurred, allowing rare high-leverage inning states to cascade before intervention.",
        "conditions": "Clustering is amplified in high-park-factor environments where extra-base hits compound faster, and against pitchers with above-average walk rates who produce leadoff free passes at the top of a big inning. Games started by struggling starters showing early-inning velocity loss show above-average big-inning probability.",
        "magnitude": "Top-scoring inning accounts for roughly 30–40 percent of total game runs; in a 9-run game, the peak inning averages roughly 3.2–3.8 runs. Over-under total distributions shift roughly 0.15–0.25 runs upward per unit increase in big-inning-probability above the league median.",
        "links": ["leadoff_of_inning_dynamics", "run_expectancy_decay_by_inning", "two_out_inning_phase", "first_inning_vulnerability"],
    },
]
