"""NBA InGameAdaptation concepts — mid-game tactical adjustments, person-free."""
from __future__ import annotations

SPORT = "NBA"
FAMILY = "InGameAdaptation"

CONCEPTS: list[dict] = [
    {
        "slug": "coverage_switch_after_pick_and_roll_burn",
        "title": "Ball-Screen Coverage Switch After Repeated Concession",
        "summary": "Defenses rotate coverage scheme when the initial ball-screen assignment yields repeated successful reads; the lag between the third or fourth concession and the coverage flip quantifies organizational rigidity versus in-game responsiveness.",
        "stat_signature": "PPP on ball-screen possessions rises above 1.10 across 3-4 consecutive reads before coverage flips; post-flip PPP typically drops 0.15-0.25 in the ensuing 8-12 possessions as offense recalibrates.",
        "mechanism": "Each successful read conditions the ball-handler to attack the same coverage; the defense faces a choice between yielding more reps or disrupting its own defensive rhythm by switching scheme mid-game. The lag reflects communication cost and scheme familiarity of the backup coverage.",
        "conditions": "Appears most sharply when the offense possesses a dominant pick-and-roll ball-handler with demonstrated drop-coverage or hedge-and-recover reads; coverage flips are most frequent in first-half quarters 1-2 when scouting overrides remain malleable.",
        "magnitude": "Coverage-type frequency shift of 30-50 percentage points within a quarter; PPP swing of 0.15-0.30 across the transition window before the offense adapts to the new look.",
        "links": ["trap_escalation_against_single_creator", "deescalation_back_to_single_coverage", "counter_to_the_defensive_switch", "zone_change_of_pace_injection"],
    },
    {
        "slug": "matchup_reassignment_on_primary_defender",
        "title": "Primary-Defender Reassignment Onto a Hot Creator",
        "summary": "When the primary offensive creator crosses a scoring threshold, the defense redirects a longer or higher-effort on-ball defender onto that assignment, immediately altering the creator's per-possession output and shot-selection mix.",
        "stat_signature": "Creator PPP drops from above 1.15 in the pre-reassignment window to below 0.90 in the 6-10 possessions post-reassignment; pull-up attempt share shrinks 8-15 percentage points as the creator avoids the upgraded coverage.",
        "mechanism": "A defender with superior length or lateral quickness alters the creator's preferred release windows; the threat of a block or recovery on the pull-up forces longer possessions and higher-difficulty creation, raising the offense's break-even threshold.",
        "conditions": "Requires a reserve of defensively capable, fresh wing or guard on the bench; most effective when the creator relies on a signature mid-range or step-back action that is length-sensitive rather than speed-sensitive.",
        "magnitude": "Creator usage rate decline of 5-12 percentage points; open-look conversion rate for that creator down 10-20 percentage points in the adjusted window.",
        "links": ["foul_trouble_assignment_rebalance", "shooter_run_off_the_line", "attacking_the_newly_inserted_defender", "coverage_switch_after_pick_and_roll_burn"],
    },
    {
        "slug": "timeout_to_arrest_opponent_run",
        "title": "Stoppage Called to Arrest an Opponent Scoring Run",
        "summary": "A deliberate dead-ball break interrupts a sustained unanswered burst, resetting offensive rhythm and defensive communication; the run length at the trigger point and the opponent's PPP on the first three to five possessions after resumption measure the adjustment's immediacy.",
        "stat_signature": "Typical trigger at 6-10 unanswered points; post-timeout PPP for the running team drops to 0.85-1.00 in the first five possessions, compared with 1.30-1.60 during the run itself.",
        "mechanism": "The stoppage breaks the transition rhythm and eliminates inertia-driven defensive lapses; the called-up set allows the trailing team to reset rotations, restate defensive assignments, and draw a specific action to attack the fatigued defense.",
        "conditions": "Most effective when the run is transition-driven (fatigue-amplified defensive lapses) rather than half-court execution; diminishing returns after the third timeout used for run-arrest in a half as offense anticipates the pattern.",
        "magnitude": "Opponent scoring rate suppressed by 25-40% in the immediate five possessions; net-rating swing of 6-12 points per 100 during the recovery window.",
        "links": ["after_timeout_counter_set_sequence", "halftime_scheme_overhaul_delta", "intentional_pace_manipulation_shift", "tempo_freeze_protecting_a_lead"],
    },
    {
        "slug": "halftime_scheme_overhaul_delta",
        "title": "Halftime Schematic Overhaul Magnitude",
        "summary": "The second-half coverage or set-package change relative to first-half baseline, measured by the third-quarter net-rating swing and the shift in coverage-type frequency mix from first half to the opening minutes of the third quarter.",
        "stat_signature": "Coverage-type frequency shifts of greater than 25 percentage points between halves; third-quarter net-rating deltas of plus-or-minus 8-14 points per 100 are common when an overhaul is substantive, versus 2-4 points when adjustments are marginal.",
        "mechanism": "Full intermission gives coaching staff the entire first-half dataset to identify sustainable mismatches and failing coverages; the 15-minute window allows a complete schematic re-brief, set installation, and personnel-shift coordination that mid-game timeouts cannot replicate.",
        "conditions": "Magnitude correlates with the size of the first-half coverage failure (larger PPP concession → larger overhaul); teams with deep enough rotations to support alternative personnel groups execute larger adjustments with less per-player fatigue cost.",
        "magnitude": "Net-rating swing of 8-18 points per 100 in Q3 opening minutes for substantial overhauls; coverage-frequency reversion to first-half levels by Q4 in roughly 60% of cases as the offense adapts.",
        "links": ["coverage_switch_after_pick_and_roll_burn", "second_half_minutes_concentration", "shot_diet_rebalance_within_game", "zone_change_of_pace_injection"],
    },
    {
        "slug": "zone_change_of_pace_injection",
        "title": "Change-of-Pace Zone Injection",
        "summary": "A brief burst of half-court zone for a handful of possessions breaks offensive rhythm after consecutive man-coverage concessions; the share of possessions converted to zone in that window and the opponent's PPP delta during the injection quantify the disruption.",
        "stat_signature": "Zone deployed for 4-8 consecutive possessions; opponent ball-movement slows by 1.5-3.0 extra passes per possession in the zone window; PPP during zone burst averages 0.82-0.95 against teams without a practiced zone-attack package.",
        "mechanism": "The zone presents a different spatial problem and eliminates the individual matchup reads the offense has been exploiting; teams lacking a practiced skip-and-cut or dribble-entry zone attack suffer immediately from unfamiliar positioning constraints.",
        "conditions": "Most effective against man-heavy offensive systems early in games before a zone-attack is prepared; effectiveness degrades after two distinct zone stints as the offense locates the preferred entry point.",
        "magnitude": "PPP suppression of 0.10-0.25 during the burst; zone stints rarely exceed 8-12 possessions before the defense resets to man to avoid corner-skip exposure.",
        "links": ["coverage_switch_after_pick_and_roll_burn", "halftime_scheme_overhaul_delta", "trap_escalation_against_single_creator", "deescalation_back_to_single_coverage"],
    },
    {
        "slug": "trap_escalation_against_single_creator",
        "title": "Escalation to Trapping a Single Creator",
        "summary": "After single ball-screen coverage fails, the defense begins blitzing the ball-screen ball-handler; trap frequency on that handler rises across the game while forced-pass and turnover rates shift as the offense locates the rotation seams.",
        "stat_signature": "Trap frequency on target handler rises from below 15% to above 40% of screen possessions; turnover rate on those possessions rises 6-10 percentage points but secondary-action PPP from the freed roller or corner can rise 0.12-0.18.",
        "mechanism": "The blitz eliminates the primary read but creates second-side vacancies; whether the net effect favors the defense depends on the handler's ability to throw skip passes under pressure and the offense's spacing discipline on the weak side.",
        "conditions": "Most punishing against handlers with lower off-the-bounce creation under duress (high usage but moderate assist-to-turnover ratios); least effective against offenses with a trained skip-passer who exploits the corner vacancy.",
        "magnitude": "Handler PPP drops 0.15-0.30 on trap possessions; overall team PPP impact is muted or slightly negative for the defense if the offense has a capable second-side threat.",
        "links": ["coverage_switch_after_pick_and_roll_burn", "deescalation_back_to_single_coverage", "help_rotation_tightening_after_kickout_damage", "counter_to_the_defensive_switch"],
    },
    {
        "slug": "deescalation_back_to_single_coverage",
        "title": "De-escalation Back to Single Coverage",
        "summary": "When trapping or aggressive hedging generates a secondary-action three-rate spike as the offense exploits rotation seams, the defense reverses toward conservative coverage; the secondary-action three-rate spike that precedes de-escalation and the subsequent coverage-mix reversion quantify the trigger.",
        "stat_signature": "Secondary-action corner-three attempt rate rises above 35% of offensive-rebound or kick-out possessions during the trap phase; de-escalation follows within 4-8 possessions; post-reversion PPP drops 0.10-0.18 as trap-exploit possessions disappear.",
        "mechanism": "A defense willing to cede corner looks to protect the paint faces the inverse of the trap's original goal if shooters convert at above-average clip; once the expected-value ledger flips, the coaching staff signals a dial-back to preserve terminal possessions.",
        "conditions": "Requires a spacing offense capable of rapid ball movement from trap receiver to corner; more common when the trapped handler possesses a practiced one-touch kick to shooters who convert above league average.",
        "magnitude": "Corner-three attempt share drops 15-25 percentage points post-reversion; defensive rebound rate improves 4-7 percentage points once help-and-recover rotations are no longer overextended.",
        "links": ["trap_escalation_against_single_creator", "coverage_switch_after_pick_and_roll_burn", "help_rotation_tightening_after_kickout_damage", "zone_change_of_pace_injection"],
    },
    {
        "slug": "counter_to_the_defensive_switch",
        "title": "Offensive Counter to a Switching Adjustment",
        "summary": "The offense responds to a switching defense by deliberately inducing mismatches through repeated re-screens and then targeting the switched defender with post-ups or isolations; the rise in post-up or isolation frequency on those possessions and the PPP on targeted possessions measure the counter's execution.",
        "stat_signature": "Target-defender isolation or post-up frequency rises from below 8% to above 22% of half-court possessions; PPP on induced-mismatch possessions reaches 1.10-1.30 when the mismatch differential is significant.",
        "mechanism": "Switching removes the coverage-coordination advantage for the defense but introduces size or speed mismatches on specific assignments; a disciplined offense exploits these by screening to locate the desired mismatch rather than accepting whatever matchup the switch produces.",
        "conditions": "Most productive when the switching defense includes a center defending a guard or a small guard defending a power forward; requires an offensive system with the patience to hunt the mismatch through multiple screen actions.",
        "magnitude": "PPP on targeted mismatch possessions exceeds the team's half-court average by 0.15-0.25; mismatch-hunting accounts for 15-30% of half-court possessions in the exploitation phase.",
        "links": ["coverage_switch_after_pick_and_roll_burn", "attacking_the_newly_inserted_defender", "shot_diet_rebalance_within_game", "matchup_reassignment_on_primary_defender"],
    },
    {
        "slug": "attacking_the_newly_inserted_defender",
        "title": "Targeting a Newly Substituted Defender",
        "summary": "The offense concentrates screen actions or isolations on a defender just brought off the bench or recently re-entered before that defender's rhythm and rotational communication are re-established, measured by PPP on those targeted possessions in the first several minutes after substitution.",
        "stat_signature": "Targeted possessions concentrated in the first 2-4 minutes after the substitute's insertion; PPP on those possessions runs 0.10-0.20 above the team's season half-court average during the cold-entry window.",
        "mechanism": "A defender returning from rest or bench observation requires 1-3 possessions to re-calibrate spacing instincts, rotation cues, and ball-screen assignment; the offense exploits this re-acclimation lag before the rhythm normalizes.",
        "conditions": "Offensive exploitation is most pronounced when the substituted defender is entering a zone of responsibility (the pick-and-roll coverage assignment or a switchable role) rather than a simple matched assignment; less impactful in a straight man-to-man system.",
        "magnitude": "PPP advantage decays within 3-5 possessions as the defender settles; the initial-entry window yields roughly 0.10-0.20 PPP above steady-state on directly targeted possessions.",
        "links": ["foul_trouble_assignment_rebalance", "matchup_reassignment_on_primary_defender", "lineup_size_change_response", "second_half_minutes_concentration"],
    },
    {
        "slug": "lineup_size_change_response",
        "title": "Counter-Adjustment to an Opponent Lineup-Size Change",
        "summary": "When the opponent shifts to a small or large lineup, the reactive swap either preserves switchability or upgrades rebounding capacity; the substitution latency relative to the opponent's change and the subsequent rebounding-rate and pace shift measure the response quality.",
        "stat_signature": "Responsive substitution latency under 2 possessions in high-stakes fourth-quarter situations; rebounding-rate differential shifts 4-9 percentage points when a mismatched lineup persists for more than 6 possessions against a properly countered lineup.",
        "mechanism": "Small lineups create pace and switchability but surrender offensive-rebound and post-up leverage; the counter-adjustment trades the opponent's intended advantage while preserving the responding team's preferred pace. Latency in responding allows the opponent to exploit the size mismatch.",
        "conditions": "Most consequential in the fourth quarter when bench depth is contracted; small-ball advantages amplify in high-pace games and diminish in slow, half-court possessions where the size deficit is more exploitable.",
        "magnitude": "Rebounding rate swings of 6-10 percentage points when the counter is delayed more than 4 possessions; pace differential of 3-6 seconds per possession between matched and mismatched lineup pairings.",
        "links": ["second_half_minutes_concentration", "attacking_the_newly_inserted_defender", "offensive_rebound_crash_dial", "foul_trouble_assignment_rebalance"],
    },
    {
        "slug": "after_timeout_counter_set_sequence",
        "title": "After-Timeout Counter-Set and the Defensive Reply",
        "summary": "One side runs a drawn-up set out of a stoppage while the defense replies on the next dead ball; PPP on the first scripted possession versus the subsequent live possessions as the information advantage decays measures the two-step tactical exchange.",
        "stat_signature": "First-possession-after-timeout PPP averages 1.05-1.20 when a prepared set is executed cleanly; PPP for the following 3-4 possessions reverts toward the team's half-court baseline as the defense loads the set into rotation memory.",
        "mechanism": "A freshly drawn set carries positional surprise that the defense cannot have pre-loaded; the defense's counter on the next dead ball eliminates the surprise premium, creating a diminishing information advantage across the first several possessions of the subsequent run.",
        "conditions": "Advantage is largest in early-game timeouts where the defensive staff has seen fewer possessions; late-game set recognition by high-IQ defensive schemes nearly eliminates the PPP premium.",
        "magnitude": "Scripted-possession PPP premium of 0.10-0.20 above team's live half-court average; premium decays to near zero within 3-5 possessions as defensive recognition catches up.",
        "links": ["timeout_to_arrest_opponent_run", "halftime_scheme_overhaul_delta", "shot_diet_rebalance_within_game", "intentional_pace_manipulation_shift"],
    },
    {
        "slug": "intentional_pace_manipulation_shift",
        "title": "Deliberate In-Game Pace Manipulation",
        "summary": "A mid-game decision to speed up when trailing or to slow the clock when leading changes possession count and the opponent's tactical preparation time; the change in seconds-per-possession and possessions-per-quarter from the first half to the adjusted phase measures the magnitude of the shift.",
        "stat_signature": "Pace acceleration produces a drop of 5-9 seconds per possession; trailing teams increasing pace generate 3-6 additional possessions per quarter, compressing the scoring deficit opportunity cost. Slowing teams reduce possessions by 2-5 per quarter.",
        "mechanism": "Pace increase shortens the game's effective length per possession, increasing variance and the trailing team's comeback probability through volume; pace decrease depletes opponent's remaining possession budget when protecting a lead.",
        "conditions": "Acceleration is most effective when the trailing team has quick-release shooters who can generate efficient shots within abbreviated possessions; deceleration requires the leading team to avoid forced turnovers that negate the possession-scarcity advantage.",
        "magnitude": "Possession-count differential of 3-6 possessions per quarter between accelerated and decelerated paces; comeback probability shifts non-linearly with each additional possession recovered.",
        "links": ["tempo_freeze_protecting_a_lead", "timeout_to_arrest_opponent_run", "inbounds_pressure_escalation_late", "after_timeout_counter_set_sequence"],
    },
    {
        "slug": "help_rotation_tightening_after_kickout_damage",
        "title": "Help-Rotation Tightening After Kick-Out Damage",
        "summary": "Defenders shrink or stretch their help positioning after a run of open kick-out threes or paint touches; the change in help depth and the open-three concession rate before and after the adjustment within the game quantify the rotation recalibration.",
        "stat_signature": "Open corner-three concession rate above 35% in a 6-8 possession window triggers visible help-depth retrenchment; post-adjustment open-three rate drops 12-20 percentage points while paint-touch concessions typically rise 0.08-0.14 PPP as the compensating tradeoff.",
        "mechanism": "A help structure optimized for paint protection leaves kick-out lanes open; when those lanes are repeatedly converted, the defense must trade rim-area pressure for perimeter coverage, accepting the inverse vulnerability as the cost of suppressing the three-point concession.",
        "conditions": "Most common against spread-pick-and-roll offenses where the roller threatens the rim and shooters occupy corners; occurs mid-first-half once a readable pattern of kick-out conversions registers in the defensive scheme.",
        "magnitude": "Open-three concession rate drops 12-20 percentage points; rim-protection PPP concession rises 0.08-0.15 as the compensating tradeoff manifests.",
        "links": ["deescalation_back_to_single_coverage", "trap_escalation_against_single_creator", "shot_diet_rebalance_within_game", "zone_change_of_pace_injection"],
    },
    {
        "slug": "foul_trouble_assignment_rebalance",
        "title": "Assignment Rebalancing Around Foul Trouble",
        "summary": "When a rotation defender accumulates early fouls, coverage assignments shift toward conservatism on that player while other defenders absorb the displaced coverage load; the net-rating change of the reshuffled assignments during the protected stretch measures the organizational cost.",
        "stat_signature": "Foul-troubled defender's on-ball coverage frequency drops from above 30% to below 10% of possessions; the displaced matchup load moves to the next available defender, whose coverage-efficiency declines 0.06-0.14 PPP above their season average during the absorbing window.",
        "mechanism": "The defensively weaker substitute or the coverage-conservative use of the foul-troubled player creates exploitable vacancies; the offense can probe for the protected zone through pick-and-roll routing toward the compromised assignment.",
        "conditions": "Most impactful when the foul-troubled player is the primary rim protector or the primary pick-and-roll drop-coverage anchor; cosmetic fouls on perimeter-only defenders produce smaller assignment ripples.",
        "magnitude": "Net-rating differential of 5-10 points per 100 between the regular assignment and the foul-protection shuffle configuration over a sustained 10-15 minute stretch.",
        "links": ["matchup_reassignment_on_primary_defender", "attacking_the_newly_inserted_defender", "lineup_size_change_response", "second_half_minutes_concentration"],
    },
    {
        "slug": "shooter_run_off_the_line",
        "title": "Running a Hot Shooter Off the Three-Point Line",
        "summary": "After a cluster of made threes, the defense applies targeted closeouts and top-lock denial to a perimeter player; the drop in catch-and-shoot attempt rate and the rise in drives forced inside the arc measure the adjustment's mechanical effect.",
        "stat_signature": "Cluster threshold of 3 made threes within 6-8 possessions triggers top-lock or denial; catch-and-shoot attempt rate drops 40-60% for the denied player in the subsequent 8-12 possessions; drive-frequency from forced-off-line cuts rises 8-15 percentage points.",
        "mechanism": "Top-lock removes the threat of stationary-catch looks by denying the ball above the arc; the player is forced to use curls, back-cuts, or handoff attacks to create, which are generally lower-efficiency actions for catch-and-shoot specialists.",
        "conditions": "Effective when the shooter is a limited creator without a reliable off-the-dribble attack; counterproductive if the shooter is also a capable cutter or ball-mover, where denying their spot opens spacing for other offensive actions.",
        "magnitude": "Catch-and-shoot three-point attempt rate decline of 40-60%; overall offensive PPP impact is approximately neutral as the freed spacing often benefits other offensive players.",
        "links": ["matchup_reassignment_on_primary_defender", "help_rotation_tightening_after_kickout_damage", "counter_to_the_defensive_switch", "shot_diet_rebalance_within_game"],
    },
    {
        "slug": "inbounds_pressure_escalation_late",
        "title": "Late-Game Inbounds and Backcourt Pressure Escalation",
        "summary": "A shift to full-court denial and ball pressure on inbounds when protecting or chasing a late lead raises the opponent's time-to-frontcourt and live-ball turnover rate; the rise in pressure frequency and resulting turnover-rate change during the escalated window measure the effect.",
        "stat_signature": "Full-court pressure increases ball-handler time-to-frontcourt by 2-4 seconds on average; live-ball turnover rate on pressured possessions rises 8-14 percentage points above the half-court baseline; teams without a designated pressure-break ball-handler are most vulnerable.",
        "mechanism": "Full-court denial eliminates the easy advance pass and forces the ball-handler to dribble against set pressure, increasing the distance over which turnovers can occur and the physical cost of each possession; the compounding effect on a fatigued ball-handler late in the game amplifies the pressure's value.",
        "conditions": "Most effective when the opponent relies on a single primary ball-handler who cannot be hidden in a pressure-break scheme; diminished effectiveness against teams with multiple competent passers who can reset the advance quickly.",
        "magnitude": "Live-ball turnover rate elevation of 8-14 percentage points during sustained pressure windows; possession advantage of roughly 1 additional turnover per 10 possessions under extended pressure.",
        "links": ["intentional_pace_manipulation_shift", "tempo_freeze_protecting_a_lead", "timeout_to_arrest_opponent_run", "after_timeout_counter_set_sequence"],
    },
    {
        "slug": "tempo_freeze_protecting_a_lead",
        "title": "Clock-Freeze Tempo Shift to Protect a Lead",
        "summary": "A late-game deliberate elongation of possessions drains the clock once a sufficient lead is established; the increase in average possession length and the reduction in total possessions relative to the team's game-average pace measure the lead-protection intent.",
        "stat_signature": "Possession length increases from a game average of 14-16 seconds to 20-26 seconds per possession in clock-freeze mode; possessions-per-quarter reduction of 3-6 relative to game average, compressing the opponent's remaining attempts-to-overcome budget.",
        "mechanism": "By elongating each possession through deliberate ball movement and attack-only when a high-value look develops, the leading team converts its lead into a possession-budget advantage; each additional second consumed reduces the trailing team's expected remaining possessions.",
        "conditions": "Clock-freeze is sustainable only when the leading team can maintain offensive structure without forcing; teams with high-usage isolation-heavy offenses often fragment under clock-management pressure, producing inefficient forced shots.",
        "magnitude": "Expected-lead preservation improves non-linearly with possession-length extension; a 3-second average increase per possession extends the effective game length by approximately 4-6 possessions fewer for the trailing team.",
        "links": ["intentional_pace_manipulation_shift", "inbounds_pressure_escalation_late", "second_half_minutes_concentration", "timeout_to_arrest_opponent_run"],
    },
    {
        "slug": "shot_diet_rebalance_within_game",
        "title": "Within-Game Shot-Diet Rebalance Toward an Exploit",
        "summary": "The offense tilts its shot-zone distribution toward an identified soft spot, such as more rim attacks against a passive drop or more corner looks against an over-helping defense; the shift in attempt-zone share from the first half to the adjusted phase quantifies the exploit concentration.",
        "stat_signature": "Zone-share shift of 12-22 percentage points toward the exploited zone in the second-half adjusted phase; PPP in the targeted zone typically runs 0.12-0.20 above the team's first-half PPP in that same zone as the offensive volume increases before the defense re-adjusts.",
        "mechanism": "First-half data reveals which coverage posture the opponent maintains under pressure; a coherent scheme concentrates volume at the revealed weakness until the defense closes the gap, at which point the offense must locate the secondary soft spot created by the defensive overreaction.",
        "conditions": "Requires an offensive system with positional flexibility to shift zone concentration (e.g., a stretch-four who can post or spot-up depending on coverage); rigid offensive systems with fixed sets cannot dynamically rebalance without sacrificing execution quality.",
        "magnitude": "PPP lift of 0.12-0.20 in the exploited zone during the adjustment phase; advantage decays within 8-15 possessions as the defense recalibrates and attempts to close the coverage gap.",
        "links": ["halftime_scheme_overhaul_delta", "counter_to_the_defensive_switch", "help_rotation_tightening_after_kickout_damage", "after_timeout_counter_set_sequence"],
    },
]
