"""MLB InGameAdaptation concepts — person-free, descriptive intelligence nodes."""
from __future__ import annotations

SPORT = "MLB"
FAMILY = "InGameAdaptation"

CONCEPTS: list[dict] = [
    {
        "slug": "times_through_order_sequence_overhaul",
        "title": "Pitch-Sequence Overhaul Across Lineup Turns",
        "summary": "A pitcher deliberately reorders and reweights pitch usage on the second and third trips through the order to defeat hitter familiarity; the divergence between first-pass and later-pass pitch-mix distributions is the measurable footprint of this adjustment.",
        "stat_signature": "Pitch-mix Jensen-Shannon divergence above 0.08 between the first and second trip indicates intentional reordering. First-pitch fastball share shifts by more than 8 percentage points; breaking-ball tunnel lead rate rises 5-10 points in the second pass against the same batters.",
        "mechanism": "Hitters build an internal pitch-sequence model within the first look; reordering primary and secondary offerings on the second pass invalidates the hitter's timing priors, yielding whiff-rate recovery of 2-4 percentage points relative to the monotonic-sequence baseline on the same pitcher-day.",
        "conditions": "Effect is largest for two-plus-pitch pitchers whose first-pass mix is heavily fastball-dominant (above 55 percent). Against hitters who have a large first-pass swing-rate, the reorder gains another 1-2 whiff points. Dampened when fatigue narrows the effective arsenal to one pitch type.",
        "magnitude": "Second-pass wOBA against the same batters falls roughly 0.020-0.035 below first-pass when a deliberate sequence overhaul is executed; without overhaul the standard times-through-order penalty adds 0.025-0.040 to wOBA.",
        "links": ["in_game_pitch_usage_pivot", "two_strike_putaway_shift", "batter_approach_adjustment_after_first_look", "catcher_target_migration_with_umpire_zone"],
    },
    {
        "slug": "in_game_pitch_usage_pivot",
        "title": "Mid-Outing Pivot to a Working Secondary",
        "summary": "A pitcher abandons a flat or punished primary pitch mid-outing and shifts usage share toward whichever secondary is generating whiffs or weak contact in that specific start; the within-game usage-share trajectory is the measurable adaptation signal.",
        "stat_signature": "Primary-pitch usage share falls more than 10 percentage points after a cluster of three-plus consecutive hard-hit events (exit velocity above 95 mph or barrel). Working secondary usage share rises 8-15 points in the subsequent 15-20 pitches.",
        "mechanism": "Hitters' timing adjusts to a repeatedly seen pitch; switching to a secondary that is sharper that day resets the timing baseline. The pivot is most potent when the secondary shows a 15-plus-percent whiff uplift in early-outing samples, signaling that day-specific grip or spin conditions favor the offering.",
        "conditions": "Requires at least two usable secondaries in the arsenal. Effective when the catcher actively signals the shift rather than waiting for the pitcher's own trigger. Weakens late in the outing when velocity on the secondary also trails off with cumulative pitch load.",
        "magnitude": "Post-pivot hard-contact rate drops roughly 4-8 percentage points in the immediately following 10-15 plate appearances; without the pivot, the hard-hit cluster tends to persist for 3-5 additional plate appearances before natural regression.",
        "links": ["times_through_order_sequence_overhaul", "catcher_target_migration_with_umpire_zone", "location_adjustment_after_barrel_cluster", "two_strike_putaway_shift"],
    },
    {
        "slug": "batter_approach_adjustment_after_first_look",
        "title": "Hitter Approach Adjustment After the First Look",
        "summary": "A batter modifies swing decision or timing on later plate appearances in the same game after processing the pitcher's arsenal, contact quality, and sequence tendencies from the first encounter; chase rate, first-pitch-swing rate, and contact quality shift measurably.",
        "stat_signature": "Chase rate on second-plus plate appearances falls 2-4 percentage points versus the first PA against the same starter. First-pitch-swing rate rises 3-6 points when the hitter identifies a fastball-dominant pattern. Barrel rate on contact rises 1.5-3 percentage points from the first to the second plate appearance.",
        "mechanism": "Visual pattern recognition from the first plate appearance calibrates swing timing and pitch-location expectations; hitters who have seen a pitch at least once reduce their reaction latency, allowing better plate-coverage decisions on edge pitches and improving contact quality on pitches in the zone.",
        "conditions": "Largest for disciplined high-contact hitters with swing-decision OAA above median. Diminished against pitchers who execute a deliberate sequence overhaul on the second pass. High-strikeout hitters show smaller chase-rate adjustment but larger barrel-rate gains when they do make contact.",
        "magnitude": "Second-PA barrel rate improvement of 1.5-3 percentage points; cumulative xwOBA lift from first to second PA roughly 0.018-0.032 across the league-average hitter cohort.",
        "links": ["times_through_order_sequence_overhaul", "lineup_aggression_recalibration_against_a_starter", "two_strike_putaway_shift", "zone_expansion_after_getting_ahead"],
    },
    {
        "slug": "location_adjustment_after_barrel_cluster",
        "title": "Location Adjustment After a Barrel Cluster",
        "summary": "A pitcher and catcher migrate off a hot zone after surrendering multiple barreled balls, climbing the ladder, expanding to the back foot, or tunneling from a new quadrant; the shift in average pitch location and subsequent hard-contact rate measure the adaptation.",
        "stat_signature": "Average pitch height shifts more than 1.5 inches vertically or average horizontal location shifts more than 2 inches following a run of three-plus barrels within 15 pitches. Hard-contact rate in the 10 pitches post-adjustment falls 5-10 percentage points from the cluster rate.",
        "mechanism": "A barrel cluster reveals the hitter's timed-up zone; relocating off that quadrant resets the hitter's spatial model. Climbing the ladder against a hitter sitting middle-down moves the contact point forward of the barrel's sweet spot, generating soft pop-ups instead of barreled line drives.",
        "conditions": "Most effective when the barrel cluster reflects true contact quality (exit velocity consistently above 95 mph) rather than bloops or flares. Least effective when the pitcher lacks command to consistently hit the relocated target zone under fatigue.",
        "magnitude": "Barrel rate in the 10 pitches after a deliberate location shift drops roughly 5-10 percentage points; without adjustment, barrel clusters continue for 2-4 additional hitter encounters before fatigue or sequencing naturally provides relief.",
        "links": ["in_game_pitch_usage_pivot", "catcher_target_migration_with_umpire_zone", "zone_expansion_after_getting_ahead", "mound_visit_to_reset_a_struggling_arm"],
    },
    {
        "slug": "reliever_matchup_chain_to_neutralize_handedness",
        "title": "In-Game Reliever Chaining to Flip Handedness Splits",
        "summary": "A manager sequences relievers to manufacture platoon advantages against an emerging dangerous segment of the lineup, measured by the platoon-advantage share of late-inning plate appearances created and the inning timing of each transition.",
        "stat_signature": "Platoon-advantage PA share in innings 7-plus rises to 68-78 percent through deliberate chaining versus roughly 50-55 percent in neutral deployment. Each handedness flip gains roughly 0.030-0.050 wOBA against the confronted hitter.",
        "mechanism": "Opposite-hand breaking balls move away from the hitter's eye-line, elevating chase rate on the outside edge; same-hand fastballs run to the back hip rather than into the barrel's path. Chaining two or three relievers preserves the platoon advantage across the lineup's left-right sequence.",
        "conditions": "Requires sufficient bullpen depth to absorb single-batter or partial-inning outings without exhausting high-leverage arms. Amplified in late-season expanded rosters and against lineups with large platoon-split differentials (above 0.050 OPS gap).",
        "magnitude": "Platoon wOBA differential of 0.030-0.070 per confrontation; across four-to-six late-inning PA optimized by chaining, the cumulative run-expectancy benefit is roughly 0.20-0.45 runs relative to neutral deployment.",
        "links": ["pinch_hitter_to_break_platoon_disadvantage", "early_hook_after_command_signals", "intentional_walk_to_reset_matchup", "defensive_substitution_to_protect_a_lead"],
    },
    {
        "slug": "early_hook_after_command_signals",
        "title": "Accelerated Starter Hook on Command-Decay Signals",
        "summary": "A starter is pulled ahead of the planned pitch count once velocity drop or location scatter appears; the gap between the actual pull point and the typical pull point and the within-at-bat location variance that triggered it are the measurable signals.",
        "stat_signature": "Velocity drop of 1.5-plus mph relative to first-inning peak sustained over 10 consecutive pitches triggers early-hook consideration. Late-count location variance (standard deviation of pitch coordinates) rising above 30 percent of the starter's game-wide baseline signals impending command breakdown. Actual pull point moves 12-22 pitches earlier than the rotation's median pull-point.",
        "mechanism": "Command decay precedes performance collapse by roughly 10-15 pitches; acting on the leading indicator prevents the barrel cluster and big inning that follow full mechanical breakdown. Early pulls preserve bullpen match-up quality because the highest-leverage arms remain available for the crisis state rather than the aftermath.",
        "conditions": "Activated in close games (within two runs) and against the heart of the lineup. Less applicable in blowout states where absorbing starter-innings at reduced quality has lower cost. Requires a bullpen not already fatigued from consecutive high-leverage usage.",
        "magnitude": "Early hook prevents an expected 0.6-1.2 additional runs in the endangered innings; at-full-collapse pull points cost roughly 1.0-1.8 runs above the early-signal trigger point.",
        "links": ["mound_visit_to_reset_a_struggling_arm", "reliever_matchup_chain_to_neutralize_handedness", "opener_to_bulk_handoff_timing", "times_through_order_sequence_overhaul"],
    },
    {
        "slug": "intentional_walk_to_reset_matchup",
        "title": "Intentional Pass to Reset the Matchup State",
        "summary": "The in-game choice to bypass a dangerous hitter creates a force play or a more favorable next matchup; the run-expectancy cost of the free base against the platoon or double-play gain on the following hitter quantifies the decision quality.",
        "stat_signature": "Run-expectancy cost ranges from +0.10 runs (two outs, runners on second-and-third) to +0.35 runs (bases empty, no outs). Double-play probability on the following hitter must exceed 18-22 percent to justify the walk in average base-out states. Intentional-walk frequency rises to 0.25-0.50 per nine innings in late-close situations.",
        "mechanism": "Loading a base increases force-out probability and may enable a favored platoon matchup on the next hitter; the net expected-run change must be negative to justify the cost. The strategy is rational only when the hitter-quality differential between the bypassed and upcoming hitters is large enough to overcome the conceded base-runner.",
        "conditions": "Deployed most in late-inning, close-game states with the tying or go-ahead run in scoring position. Extra-inning automatic-runner regimes suppress usage because loading bases raises walk-off exposure. Weakened against lineups with deep quality through the seven-and-eight holes.",
        "magnitude": "Net run-expectancy benefit when justified: roughly -0.05 to -0.15 runs versus the alternative confrontation. When unjustified (roughly 40-50 percent of historical deployments), cost is +0.10 to +0.30 runs above the neutral-matchup expectation.",
        "links": ["reliever_matchup_chain_to_neutralize_handedness", "pinch_hitter_to_break_platoon_disadvantage", "bunt_or_steal_dial_by_run_environment", "infield_in_decision_threshold"],
    },
    {
        "slug": "catcher_target_migration_with_umpire_zone",
        "title": "Catcher Target Migration to the Live Strike Zone",
        "summary": "The battery relocates pitch targets during a game as the umpire's called zone reveals itself; the within-game drift of edge-target placement toward the calls being granted and the called-strike-rate change on borderline pitches are the measurable footprint.",
        "stat_signature": "Catchers shift target placement by 1-3 inches horizontally or vertically within the first 30 pitches when the umpire's zone deviates more than 1.5 inches from the published zone. Called-strike rate on borderline pitches rises 4-8 percentage points after zone calibration versus the pre-calibration baseline.",
        "mechanism": "Umpires have idiosyncratic consistent zone tendencies within a game; pitch framers who identify the live zone early can exploit additional called strikes on edges that the canonical zone misclassifies. Zone migration converts borderline pitches to strikes rather than balls, reducing pitch counts by 5-10 pitches per game.",
        "conditions": "Amplified with high-framing catchers whose presentation skill magnifies the shift. Low-friction for pitchers with command to reliably hit 2-inch-diameter target zones. Minimal benefit when the umpire's zone closely matches the algorithmic strike zone (deviation below 1 inch).",
        "magnitude": "Called-strike-rate gain of 4-8 percentage points on borderline pitches; across 15-20 borderline pitches per game this translates to roughly 0.6-1.6 additional called strikes, reducing pitcher pitch-count and extending starter depth.",
        "links": ["location_adjustment_after_barrel_cluster", "in_game_pitch_usage_pivot", "two_strike_putaway_shift", "mound_visit_to_reset_a_struggling_arm"],
    },
    {
        "slug": "tempo_and_disengagement_adjustment",
        "title": "Tempo and Disengagement Adjustment Against the Run",
        "summary": "A pitcher varies delivery tempo and spends disengagements to disrupt a runner threatening to steal; the change in stolen-base attempt rate and the runner's primary-lead distance after the tempo and pickoff adjustments begin measure the adaptation's effectiveness.",
        "stat_signature": "Switching from a full windup or consistent tempo to a slide-step cuts delivery home time from 1.3-1.5 to 1.1-1.2 seconds. After 2-plus disengagements, runner primary-lead distance shrinks 8-14 inches. Stolen-base attempt rate drops 35-55 percent in the two-plate-appearance window following a pickoff nearly complete.",
        "mechanism": "Stolen-base success depends on the combined home-delivery time and catcher pop time; compressing delivery time below 1.2 seconds raises the caught-stealing probability above break-even (~40 percent depending on park and runner speed). Disengagements force the runner to reset the lead, reducing the jump advantage.",
        "conditions": "Most effective against runners with below-average sprint speed (28.5 mph or below) who depend on lead distance for timing. Limited value against elite speedsters who achieve break-even jump speed regardless of delivery variation. Must be balanced against the pitch-location disruption a slide-step causes against the hitter.",
        "magnitude": "Slide-step adoption reduces catcher pop-time requirement by roughly 0.10-0.15 seconds; at typical thresholds this shifts caught-stealing probability from roughly 32 percent to 44 percent, near the 40-percent break-even threshold.",
        "links": ["bunt_or_steal_dial_by_run_environment", "pitch_tempo_break_to_disrupt_timing", "opener_to_bulk_handoff_timing", "intentional_walk_to_reset_matchup"],
    },
    {
        "slug": "pinch_hitter_to_break_platoon_disadvantage",
        "title": "Pinch-Hit Substitution to Break a Platoon Disadvantage",
        "summary": "The manager substitutes a hitter to flip the handedness matchup against a reliever just brought in; the projected platoon-split swing of the substitution and the leverage index at the moment of deployment quantify the decision's expected run value.",
        "stat_signature": "Pinch-hit substitution flips wOBA expectation by 0.030-0.060 when the platoon split is large. Leverage index at deployment averages 1.4-2.1 in recorded late-inning cases. Frequency rises to roughly 1.2-1.8 per game in close games from the sixth inning onward in September rosters.",
        "mechanism": "The substituted hitter carries a favorable handedness against the entering reliever; the platoon OPS split of 0.040-0.070 translates to roughly 8-15 percent better on-base probability per plate appearance. At leverage indices above 1.5 this converts to roughly 0.04-0.12 win-probability units per deployment.",
        "conditions": "Requires roster depth in the bench with the correct handedness; reduces available pinch-hitting depth for subsequent leverage opportunities in the same game. Most frequently deployed in the seventh-or-later innings against teams relying on same-handed specialists.",
        "magnitude": "Platoon-flip wOBA gain of 0.030-0.060 per substitution; across two-to-three late-game plate appearances at leverage above 1.5, cumulative win-probability benefit averages roughly 0.04-0.10 units.",
        "links": ["reliever_matchup_chain_to_neutralize_handedness", "intentional_walk_to_reset_matchup", "defensive_substitution_to_protect_a_lead", "infield_in_decision_threshold"],
    },
    {
        "slug": "two_strike_putaway_shift",
        "title": "Two-Strike Putaway Shift Within the Game",
        "summary": "A pitcher escalates to the highest-whiff offering and chase locations once batters have shown they protect the plate; the within-game change in two-strike pitch mix and the putaway-rate trend across successive two-strike counts are the measurable signals.",
        "stat_signature": "Two-strike putaway-pitch usage share rises 8-15 percentage points relative to the first-pass baseline when the pitcher identifies that hitters are extending contact attempts. Chase rate on two-strike pitches outside the zone improves 4-7 percentage points from first-pass to second-pass encounters in the same game.",
        "mechanism": "Hitters who expand to protect the zone against two-strike breaking balls reveal an exploitable chase tendency; concentrating the highest-spin-rate secondary at the bottom of the zone or off the back edge generates whiffs at a higher rate than varying pitch types. The pitcher's two-strike sequencing becomes a within-game learned exploit.",
        "conditions": "Most effective against contact hitters who rarely walk (BB rate below 7 percent) and must protect the zone. Diminished against disciplined hitters who accept two-strike walks rather than chasing. Requires a high-spin secondary (above 2,500 rpm) that maintains sharp break under fatigue.",
        "magnitude": "Two-strike putaway rate improvement of 3-6 percentage points when the shift is executed deliberately; strikeout rate rises roughly 1.5-2.5 K/9 in the second-and-third pass relative to the first pass for pitchers who successfully execute the two-strike pattern shift.",
        "links": ["times_through_order_sequence_overhaul", "batter_approach_adjustment_after_first_look", "zone_expansion_after_getting_ahead", "in_game_pitch_usage_pivot"],
    },
    {
        "slug": "lineup_aggression_recalibration_against_a_starter",
        "title": "Lineup-Wide Aggression Recalibration Against a Starter",
        "summary": "A batting order collectively shifts toward patience or first-pitch aggression once a starter's tendencies are read through early innings; team-level changes in pitches-per-plate-appearance and first-pitch-swing rate from early to middle innings are the measurable signals.",
        "stat_signature": "Pitches per plate appearance rises 0.20-0.45 from innings 1-2 to innings 4-6 for teams executing a patience strategy against a command-challenged starter. First-pitch swing rate rises 5-10 percentage points in innings 4-6 against a fastball-dominant starter who falls behind frequently in counts.",
        "mechanism": "The first time through the lineup reveals whether a starter works ahead or behind in counts and whether first-pitch offerings are predictable fastballs; a team signal — explicit or emergent through the lineup — to work counts forces pitch-count inflation and moves the starter toward the times-through-order penalty zone earlier.",
        "conditions": "Patience strategy is most effective against starters with walk rates above 3.5 BB/9 who cannot consistently recover from behind-in-count states. Aggression strategy is most effective against first-pitch-strike starters who rely on early-count dominance and fatigue late.",
        "magnitude": "A successful patience shift forces 4-8 additional pitches per inning, advancing the starter's exit by roughly 0.5-1.0 innings and elevating bullpen exposure; a successful aggression shift raises early-inning HR rate roughly 15-25 percent above the neutral baseline.",
        "links": ["batter_approach_adjustment_after_first_look", "times_through_order_sequence_overhaul", "opener_to_bulk_handoff_timing", "early_hook_after_command_signals"],
    },
    {
        "slug": "bunt_or_steal_dial_by_run_environment",
        "title": "Small-Ball Dial Keyed to the In-Game Run Environment",
        "summary": "The in-game decision to deploy or shelve sacrifice and steal attempts adapts to the scoring state and reliever quality on the mound; the change in attempt frequency relative to the base-out run-expectancy break-even is the measurable adaptation.",
        "stat_signature": "Break-even steal success rate rises from roughly 72 percent (standard) to 78-82 percent against high-groundball relievers who hold runners well. Sacrifice-bunt deployment frequency triples above the game-average rate when trailing by one in the sixth inning or later with a weak contact hitter up and a dominant reliever expected next.",
        "mechanism": "Run-expectancy tables define the break-even threshold for each attempt type; the in-game dial adapts when the current run environment (reliever ERA, inning, score) shifts the expected-runs calculation far from the season-average baseline. An elite shutdown reliever expected in the next inning raises the urgency of scoring the current runner above the expected-value calculation alone.",
        "conditions": "Small-ball deployment highest in pitcher-friendly parks during low-scoring games (combined total below 7.5). Shelved in high-run environments where a single run conceded is less decisive and multi-run rallies are more probable. Stolen-base dial also adjusted for catcher arm and battery delivery time measured live.",
        "magnitude": "Sacrifice attempt in the optimal state (one-run deficit, sixth-or-later, weak contact hitter, dominant reliever next) reduces run-expectancy cost to roughly 0.08-0.12 runs versus the 0.18-0.22 cost in a neutral game state; the break-even narrows to roughly 5-8 percentage-point improvement in scoring probability.",
        "links": ["tempo_and_disengagement_adjustment", "intentional_walk_to_reset_matchup", "infield_in_decision_threshold", "batter_approach_adjustment_after_first_look"],
    },
    {
        "slug": "infield_in_decision_threshold",
        "title": "Infield-In Decision Threshold Late and Close",
        "summary": "Pulling the infield in to cut down a run at the plate in a tight late inning trades lower hit-through probability for higher run-prevention on balls in play; the inning-and-score trigger state and the batting-average-on-balls-in-play concession quantify the tradeoff.",
        "stat_signature": "BABIP against the infield-in alignment rises roughly 0.070-0.120 above the standard-depth baseline. Run-scoring probability with a runner on third and fewer than two outs in the seventh-or-later inning falls from roughly 80-85 percent (standard depth) to 60-68 percent (infield in) on grounders to the infield.",
        "mechanism": "Infield depth reduction cuts the fielder-to-home throw path; sharply hit grounders that would normally be out-at-first are now play-at-plate opportunities. The tradeoff is that softly or lofted grounders find gaps, elevating BABIP. The break-even depends on the run-leverage value of preventing the specific scoring event.",
        "conditions": "Justified only when one run is decisive (one-run game in the seventh inning or later, or tie game) and the offensive threat to the next batter is manageable. Counter-indicated against high-launch-angle batters who elevate contact, neutralizing the infield-depth advantage.",
        "magnitude": "Run-prevention improvement on ground balls of roughly 12-22 percentage points; BABIP cost of roughly 0.070-0.120 above standard depth; net win-probability effect positive when the preventing run is worth more than 6-8 percentage points of win probability.",
        "links": ["defensive_repositioning_within_at_bat_count", "defensive_substitution_to_protect_a_lead", "intentional_walk_to_reset_matchup", "bunt_or_steal_dial_by_run_environment"],
    },
    {
        "slug": "opener_to_bulk_handoff_timing",
        "title": "Opener-to-Bulk Handoff Timing Adjustment",
        "summary": "Shifting the planned transition from a short-stint opener to the bulk arm adapts to how the top of the order is being handled; the batter count at handoff relative to plan and the times-through-order exposure avoided thereby are the measurable adaptation.",
        "stat_signature": "Standard opener handles 1-2 innings (roughly 15-25 batters). Handoff moves 3-8 batters earlier when the opener struggles against the top of the lineup (OPS above 0.850 against opener). Handoff moves 5-10 batters later when the opener is generating whiffs and the bulk arm would face the lineup's third pass sooner.",
        "mechanism": "The opener's primary function is to neutralize the first-time-through OPS boost that the lineup's top hitters enjoy against a fresh starter; flexible handoff timing maximizes that benefit. An early handoff avoids exposing the opener to the second time through while a delayed handoff exploits a hot opener before the bulk arm absorbs the easier middle-of-order lineup segment.",
        "conditions": "Applicable only in the opener-bulk deployment regime. Most effective when the bulk arm is a multi-inning pitcher with a significant times-through-order penalty of his own, making early transition counterproductive. Requires a bullpen deep enough to handle the 4-6 innings remaining after the handoff.",
        "magnitude": "Optimally timed handoff reduces expected runs across the shared outing by roughly 0.25-0.50 runs relative to a rigid inning-based handoff rule; avoided third-pass exposure for the opener saves roughly 0.20-0.35 runs per lineup turn avoided.",
        "links": ["early_hook_after_command_signals", "times_through_order_sequence_overhaul", "lineup_aggression_recalibration_against_a_starter", "reliever_matchup_chain_to_neutralize_handedness"],
    },
    {
        "slug": "pitch_tempo_break_to_disrupt_timing",
        "title": "Deliberate Pace Break to Disrupt Hitter Timing",
        "summary": "A pitcher steps off, holds the ball, or quick-pitches within constraints to reset a hitter who is timing the delivery; within-plate-appearance tempo variance and the contact-quality change on pitches following the break are the measurable signals.",
        "stat_signature": "Delivery time variance exceeding 0.35 seconds standard deviation within a plate appearance reduces hitter expected exit velocity by roughly 1.5-2.5 mph on the pitch following the tempo break. Swing-and-miss rate on the pitch immediately after a step-off rises roughly 3-5 percentage points above the same pitcher's baseline.",
        "mechanism": "Hitters synchronize internal timing rhythms with the pitcher's delivery cadence; an unexpected hold or quick-pitch forces a timing reset that disrupts the forward weight transfer and rotation timing, producing swing misses or weak contact even on pitches in the hitting zone.",
        "conditions": "Most effective against noticeably rhythm-dependent hitters with large timing-load swings (contact quality drops measurably against variable-tempo pitchers). Limited benefit against hitters who trigger independently of pitcher cadence. Must comply with rules limiting disengagements to two per batter.",
        "magnitude": "Post-tempo-break swing-and-miss uplift of 3-5 percentage points; exit velocity suppression of 1.5-2.5 mph; across a full plate appearance with two tempo breaks, expected xwOBA declines roughly 0.015-0.025 versus a constant-tempo baseline.",
        "links": ["tempo_and_disengagement_adjustment", "two_strike_putaway_shift", "mound_visit_to_reset_a_struggling_arm", "catcher_target_migration_with_umpire_zone"],
    },
    {
        "slug": "defensive_substitution_to_protect_a_lead",
        "title": "Late Defensive Substitution to Protect a Lead",
        "summary": "Swapping in glove-first fielders for bat-first ones once a lead is established optimizes outs-above-average in the field at the expense of offensive depth; the inning of the change, the projected defensive-runs improvement, and the offensive value forfeited in remaining plate appearances quantify the tradeoff.",
        "stat_signature": "Defensive substitution occurs most frequently entering the seventh inning or later with a two-to-three run lead. Fielder OAA improvement per substitution averages +3 to +7 runs per 150 defensive chances at premium positions (center field, shortstop, third base). Offensive forfeiture averages 0.15-0.25 runs in the remaining 1-2 plate appearances for the substituted hitter.",
        "mechanism": "Late-game run prevention is asymmetric: a ball in play that is not caught converts directly into a baserunner in a high-leverage state. Superior range and first-step reads at premium defensive positions convert 2-5 percent more balls in play into outs, suppressing scoring probability by more than the offensive downgrade costs in low-plate-appearance remainder situations.",
        "conditions": "Break-even favors the substitution when the lead exceeds two runs and fewer than 1.5 expected plate appearances remain for the removed hitter. Counter-indicated in one-run games where an additional at-bat from the offensive player could represent the tying or go-ahead run.",
        "magnitude": "Defensive-runs improvement of 0.10-0.25 runs for the remaining half-innings; net win-probability improvement of 2-5 percentage points when the lead is two-to-three runs in the seventh inning or later.",
        "links": ["pinch_hitter_to_break_platoon_disadvantage", "infield_in_decision_threshold", "defensive_repositioning_within_at_bat_count", "reliever_matchup_chain_to_neutralize_handedness"],
    },
    {
        "slug": "mound_visit_to_reset_a_struggling_arm",
        "title": "Mound Visit to Reset a Faltering Pitcher",
        "summary": "The conference used to slow the game and recalibrate a pitcher mid-inning after a sudden command lapse; the base-out leverage at the visit and the strike-rate and contact-quality change in the batters immediately following it measure the adaptation's effectiveness.",
        "stat_signature": "Strike rate in the 10 pitches immediately after a mound visit rises 4-7 percentage points versus the preceding 10-pitch block that triggered the visit. Hard-contact rate in the three batters following the visit falls 5-9 percentage points from the cluster rate preceding it. Visit is most common with leverage index above 1.5 and runners on base.",
        "mechanism": "The conference interrupts a pitcher's mechanical spiral by introducing a pause, physical contact, and verbal cues that disrupt the feedback loop of missed-location-anxiety-more-misses. The resetting interval allows grip adjustment, breathing regulation, and pitch-selection simplification that collectively recover release-point consistency.",
        "conditions": "Most effective for mechanical rather than fatigue-induced command loss; a pitcher experiencing velocity-driven fatigue will not sustainably recover from a visit alone. The visit consumes one of the permitted mound visits per inning, constraining subsequent use of the reset tool in the same inning.",
        "magnitude": "Command-recovery strike-rate lift of 4-7 percentage points; xwOBA suppression in the 3 batters post-visit of roughly 0.020-0.040 versus the pre-visit struggling baseline; effect decays toward pre-visit levels by the 8th-12th pitch if underlying fatigue is the root cause.",
        "links": ["early_hook_after_command_signals", "location_adjustment_after_barrel_cluster", "catcher_target_migration_with_umpire_zone", "pitch_tempo_break_to_disrupt_timing"],
    },
    {
        "slug": "zone_expansion_after_getting_ahead",
        "title": "Zone Expansion After Getting Ahead in Counts",
        "summary": "A pitcher widens the effective attack zone once consistently ahead in counts during a game; the within-game rise in out-of-zone rate when ahead and the chase rate the expanded approach generates against the lineup measure the adaptation.",
        "stat_signature": "Out-of-zone pitch rate when ahead in the count (0-2, 1-2) rises 6-12 percentage points from early innings to middle innings as the pitcher confirms hitters are chasing. Chase rate on 0-2 pitches outside the zone reaches 32-40 percent for lineups that do not adjust, versus a 25-28 percent baseline for disciplined lineups.",
        "mechanism": "Hitters in two-strike counts extend their defensive swing arc to cover the zone; pitchers who confirm this tendency through early-inning observation can place breaking balls at the lower periphery or spinning away from the barrel, generating chases without sacrificing called-ball frequency. The expansion is calibrated within-game rather than applied uniformly.",
        "conditions": "Effective when the lineup's two-strike chase rate ranks in the bottom third of the league (above 32 percent). Least effective against lineups that shorten the swing and accept walks rather than expanding coverage. Requires a breaking ball with sufficient depth or sweep to fall out of the expanded chase arc at the plate.",
        "magnitude": "Chase-rate improvement of 4-8 percentage points in the pitcher-ahead count; K/9 rises roughly 1.0-2.0 above the pitcher's first-inning baseline when the expansion is successfully calibrated to the lineup's two-strike tendencies.",
        "links": ["two_strike_putaway_shift", "batter_approach_adjustment_after_first_look", "location_adjustment_after_barrel_cluster", "catcher_target_migration_with_umpire_zone"],
    },
]
