"""InGameAdaptation Soccer concept nodes — person-free, calibration-only intelligence."""
from __future__ import annotations

SPORT = "Soccer"
FAMILY = "InGameAdaptation"

CONCEPTS: list[dict] = [
    {
        "slug": "halftime_shape_change_delta",
        "title": "Halftime Formation-Shape Change Magnitude",
        "summary": "The size of the structural adjustment made at the interval — such as a shift between a back four and back three — is measurable through the swing in average defensive-line height, passes-per-defensive-action, and territorial control between the first half and the opening of the second.",
        "stat_signature": "Defensive-line height change exceeding 4 metres between halves flags a shape adjustment; PPDA delta of more than 2.0 between halves indicates a pressing-trigger recalibration; territorial-control share shift of 5-plus percentage points in the opening 10 minutes of the second half distinguishes structural changes from tactical noise.",
        "mechanism": "A back-line reconfiguration alters the width and depth of the defensive block instantly, changing which pressing triggers are viable; shifting to a back three releases a wing-back to create numerical overloads in wide build-up zones while narrowing the central defensive channel.",
        "conditions": "Shape changes are most frequent after half-time when conceding or failing to create in the first half; they are rarer when a side leads by two or more, where continuity carries lower risk than disruption.",
        "magnitude": "A half-time shape change correlates with a 12-20% swing in expected-goals rate in the opening 15 minutes of the second half relative to the last 15 of the first; larger structural shifts (four to three back) carry roughly double the expected-goals-rate swing of minor adjustments.",
        "links": ["press_trigger_recalibration", "block_height_drop_to_protect_lead", "fullback_role_inversion_adjustment", "tempo_control_through_possession_phases"],
    },
    {
        "slug": "press_trigger_recalibration",
        "title": "In-Game Press-Trigger Recalibration",
        "summary": "After early build-up is beaten consistently, a side adjusts the height and cue conditions for engaging the press, observable as a shift in where defensive recoveries occur and a change in passes-per-defensive-action across match phases.",
        "stat_signature": "PPDA rising from below 8 to above 11 between the first and second half signals a mid-block retreat; a fall in the proportion of defensive actions in the attacking third from above 30% to below 18% marks a press-trigger pull-back; high-turnover location centroid shifts more than 15 metres backward between phases.",
        "mechanism": "When ball-playing sides exploit pressing triggers through third-man combinations, the pressing side's expected-goals-against from transitions rises; rational recalibration lowers the engagement threshold and forces the opponent to progress through deeper positional defence rather than explosive transitions.",
        "conditions": "Recalibration is triggered by two or more transition-conceded shots in a 20-minute window; more likely against sides with high-quality central midfield ball-carriers who can break the first press line consistently.",
        "magnitude": "A press recalibration reduces transitions-against by 20-35% in the subsequent phase while typically raising opponent possession time by 8-12%; net expected-goals-against usually falls slightly despite the possession concession.",
        "links": ["halftime_shape_change_delta", "pressing_trap_redirection_to_a_new_side", "rest_defense_balance_dial", "line_engagement_change_against_long_ball"],
    },
    {
        "slug": "block_height_drop_to_protect_lead",
        "title": "Defensive-Block Drop to Protect a Lead",
        "summary": "Once ahead, a side deliberately lowers its defensive block, conceding possession in exchange for compactness; measurable by the fall in average line height, rise in opponent outside-the-area shots, and drop in own possession share.",
        "stat_signature": "Average defensive-line height drops 5-9 metres versus the same side's first-half position when protecting a lead; opponent shots from outside the area rise from 30-40% to 50-65% of total attempts; the protecting side's possession share falls 10-15 percentage points from its first-half level.",
        "mechanism": "Compressing space between the defensive and midfield lines eliminates high-probability through-ball routes and forces opponents into low-expected-goals deliveries from distance; the protection increases counter-attack exposure value by channelling space in behind a high opponent line.",
        "conditions": "Deployed most systematically at away fixtures where a draw remains a positive outcome; triggered earlier (before minute 65) when the lead-holder is the lower-ranked side by expected-goals ratio.",
        "magnitude": "Opponent expected-goals-per-shot typically falls from 0.11-0.13 to 0.08-0.10; shot volume conceded may rise 20-35% but at lower quality, resulting in a net expected-goals-against reduction of 0.05-0.12 per match phase.",
        "links": ["game_management_time_use_late", "chase_state_shape_push", "low_block_closing_phase", "rest_defense_balance_dial"],
    },
    {
        "slug": "chase_state_shape_push",
        "title": "Chase-State Shape Push When Trailing",
        "summary": "When behind, a side shifts structurally toward attack — adding a forward, pushing fullbacks high — creating measurable increases in final-third entries and box occupancy at the cost of defensive depth.",
        "stat_signature": "Final-third entries per minute rise 25-40% after the trailing-state shape push versus the same side's pre-deficit rate; box touches per sequence increase 15-25%; opponent low-block frequency rises to above 65% of defensive phases as they absorb the pressure.",
        "mechanism": "Adding an attacking player forces the midfield to widen, creating numerical disadvantage in the defensive third on transitions; the fullback push creates wide-overload opportunities for crosses at the expense of transition exposure.",
        "conditions": "Push intensity scales with time remaining and goal deficit; a one-goal deficit after minute 70 produces the most structured push, while a two-goal deficit after minute 80 typically triggers near-total attacking commitment with minimal defensive cover.",
        "magnitude": "Expected-goals-for per minute rises 0.015-0.030 in the post-push phase; simultaneously expected-goals-against on transitions rises 0.010-0.020, reflecting the dual consequence of the risk shift.",
        "links": ["block_height_drop_to_protect_lead", "attacking_substitution_xg_shift", "target_man_route_introduction", "counter_to_opponent_block_change"],
    },
    {
        "slug": "attacking_substitution_xg_shift",
        "title": "Attacking Substitution Expected-Goal Shift",
        "summary": "Introducing an attacker to raise chance creation produces a measurable shift in expected-goals-per-shot and shot volume in the window after the substitution, relative to the same match period before it.",
        "stat_signature": "Shot volume rises 18-30% in the 15 minutes after an attacking substitution versus the preceding 15-minute window; expected-goals-per-shot rises 0.010-0.020 on average from improved service quality and positional depth; the substituting side's PPDA worsens 10-18% reflecting the conceded defensive compactness.",
        "mechanism": "The entering attacker's fresh legs and positional novelty disrupt the defensive structure's man-assignment before opponents re-calibrate; the tactical shift to accommodate the new player briefly opens combination channels that the defence has not planned for.",
        "conditions": "The shift is largest when the entering attacker plays a different positional role to the withdrawn player, forcing the defence to adapt rather than merely replace; smallest when the substitute mirrors the replaced player's role.",
        "magnitude": "Expected-goals-for uplift of approximately 0.04-0.10 in the 15-minute window post-substitution; the benefit declines toward 0 as opponents adapt and the substitute's own fatigue accumulates.",
        "links": ["chase_state_shape_push", "fresh_legs_pressing_reinforcement", "defensive_substitution_to_close_a_game", "wide_overload_to_central_overload_shift"],
    },
    {
        "slug": "defensive_substitution_to_close_a_game",
        "title": "Defensive Substitution to Close Out a Match",
        "summary": "Bringing on a holding or defensive player to consolidate a lead reduces transitions allowed and opponent expected goals, measurable by post-substitution changes in opponent expected goals conceded and defensive actions in the own third.",
        "stat_signature": "Opponent expected goals conceded per 15 minutes drops 15-25% after a defensive substitution in a lead-protecting side; defensive actions in the own third rise 20-30% as the additional holding player screens the backline; transitions allowed per 15 minutes fall 25-35% as the substitution compresses the midfield block.",
        "mechanism": "A holding midfielder's introduction reduces the gap between midfield and defensive lines, removing the half-space channels through which opponents build transition momentum; the numerical reinforcement of the compact block forces opponents to circulate rather than penetrate.",
        "conditions": "Applied most systematically in the 70-80-minute window when protecting a one-goal advantage; deployed earlier at away fixtures where the lead-holding side is the underdog by expected-goals.",
        "magnitude": "Net expected-goals-against reduction of 0.06-0.15 in the phase following a defensive substitution; the tradeoff is a decline in own attacking transitions from 1.8-2.4 to 0.8-1.2 per 15 minutes.",
        "links": ["block_height_drop_to_protect_lead", "game_management_time_use_late", "rest_defense_balance_dial", "fresh_legs_pressing_reinforcement"],
    },
    {
        "slug": "fresh_legs_pressing_reinforcement",
        "title": "Fresh-Legs Pressing Reinforcement",
        "summary": "Substitutions made specifically to restore press intensity after fatigue erodes it produce a recovery in passes-per-defensive-action and high-recovery count in the minutes after the change versus the pre-substitution decline.",
        "stat_signature": "PPDA recovers from its pre-substitution high of 12-16 toward 8-10 within 10 minutes of a pressing-reinforcement substitution; high-press recoveries per 15 minutes increase 25-35% versus the preceding fatigued phase; sprint-distance-per-minute recovers 15-20% for the entering pressing sub versus the replaced player's late-match output.",
        "mechanism": "Fresh legs restore the press-trigger speed that fatiguing muscles cannot sustain; the replacement carries the full positional knowledge of the press scheme without the accumulated physical cost, restoring the compactness and trigger timing that make the press effective.",
        "conditions": "Most effective when deployed before minute 75 so the entering presser has sufficient time to influence the match; if the opponent has already adjusted to the fatigued press, the reset creates a secondary adaptation challenge for their build-up.",
        "magnitude": "PPDA recovery of 3-6 units in the 10 minutes post-substitution; high-turnover rate in the pressing zone rises 15-25% versus the pre-substitution fatigued press phase.",
        "links": ["press_trigger_recalibration", "attacking_substitution_xg_shift", "defensive_substitution_to_close_a_game", "rest_defense_balance_dial"],
    },
    {
        "slug": "tactical_foul_to_break_transition",
        "title": "Tactical Foul to Break a Developing Transition",
        "summary": "The deliberate foul to stop a counter before it reaches dangerous territory is measurable by the rate of fouls committed in the middle third on opponent transitions and the prevented expected-goal value of the broken attacks.",
        "stat_signature": "Teams ranking in the top quartile for tactical-foul rate commit 1.8-2.5 middle-third fouls per match on transition; each prevented transition avoids an estimated 0.08-0.15 expected goals based on counter-attack expected-goals rates; bookable offence rate from tactical fouls averages 0.3-0.5 yellow cards per match for high-frequency practitioners.",
        "mechanism": "Stopping the transition before it reaches the final third eliminates the positional and numerical advantage the counter-attacking side has accumulated; the conceded free kick, typically 25-35 metres from goal, carries a far lower expected-goals value than the live counter.",
        "conditions": "Most frequently executed by compact mid-block sides that lack the press capacity to force the opponent back through pressing; also deployed by leading sides protecting a narrow advantage when a defensive backline is temporarily exposed.",
        "magnitude": "Expected-goals-against reduction from broken transitions of 0.06-0.12 per match versus allowing counters to complete; the yellow-card accumulation cost materialises as a reduced-man risk if the practitioner reaches two cautions.",
        "links": ["rest_defense_balance_dial", "press_trigger_recalibration", "block_height_drop_to_protect_lead", "game_management_time_use_late"],
    },
    {
        "slug": "man_to_zonal_marking_switch",
        "title": "In-Game Switch Between Man and Zonal Marking",
        "summary": "Changing the marking scheme on set pieces or in open play after conceding or being threatened alters opponent contact-on-set-piece rate and dead-ball expected goals in the following phase.",
        "stat_signature": "Contact rate on opponent set-piece deliveries changes 15-25% when the marking scheme is switched; expected goals from dead-ball situations for the opponent fall 0.02-0.05 per set piece following a mid-game marking switch; conceded corners that result in shots drop from 20-28% to 12-18% when a side moves from zonal to man-marking after a concession.",
        "mechanism": "Man-marking prevents free runs to the delivery zone but creates vulnerability to blocking runners and decoy movements; zonal marking holds shape against runners but leaves aerial second-ball contests under-pressured; switching after a concession removes the pattern the opponent has already rehearsed.",
        "conditions": "Switch is most commonly applied after conceding a goal from a corner or free kick; the adjustment is more impactful against sides with high set-piece expected-goals shares (above 30% of total expected goals).",
        "magnitude": "Dead-ball expected-goals conceded per match drops 0.03-0.08 following a marking-scheme change, reflecting opponent loss of the rehearsed approach; benefit diminishes over subsequent set pieces as the opponent adapts delivery targets.",
        "links": ["set_piece_routine_variation_after_scouting", "halftime_shape_change_delta", "block_height_drop_to_protect_lead", "double_team_redirect_on_a_threat"],
    },
    {
        "slug": "wide_overload_to_central_overload_shift",
        "title": "Shift Between Wide and Central Attacking Overload",
        "summary": "Relocating attacking emphasis from the flanks to the half-spaces or center when one channel is sealed is measurable by change in side-of-pitch touch share and the resulting box-entry method mix during the match.",
        "stat_signature": "Wide-zone touch share drops from 35-45% to 22-30% when a side pivots to central overload; box entries via central combinations rise 20-35% while cross-based entries fall 25-40%; expected-goals-per-shot from central entries averages 0.130-0.160 versus 0.095-0.110 from crosses, making the shift quality-positive.",
        "mechanism": "When wide channels are congested by defensive width adjustments, recycling the attack through central half-spaces accesses higher-probability shot positions; the opponent's wide compactness simultaneously creates space for diagonal ball delivery into the half-space channels.",
        "conditions": "Shift is triggered when the attacking side has generated three or more low-return wide attacks without a box entry in a 20-minute window; facilitated by the presence of a half-space runner or central midfielder with progressive carry ability.",
        "magnitude": "Expected-goals-per-shot improvement of 0.025-0.040 when moving from wide-dominant to central-overload attack; net expected-goals-for rise of 0.05-0.12 per match phase in which the shift is executed effectively.",
        "links": ["chase_state_shape_push", "attacking_substitution_xg_shift", "fullback_role_inversion_adjustment", "counter_to_opponent_block_change"],
    },
    {
        "slug": "line_engagement_change_against_long_ball",
        "title": "Defensive-Line Engagement Change Against Direct Play",
        "summary": "Dropping or holding the offside line in response to repeated balls played in behind alters line height, offside-trap success rate, and the share of opponent attacks routed over the top after the adjustment.",
        "stat_signature": "Defensive-line height drops 6-10 metres within two phases of repeated over-the-top exposures; offside-trap success rate improves from below 55% (pre-adjustment) to above 70% (post-adjustment) as the line retreats to reliable depth; opponent attacks routed via long ball fall from 35-45% to 20-28% as the spatial reward diminishes.",
        "mechanism": "A high line relies on precise collective timing; repeated penetration via long balls signals that timing discipline is being disrupted, so retreating reduces the space exposed behind the line while conceding more contested territory in midfield.",
        "conditions": "Adjustment is most necessary against direct-play sides that target a fast centre-forward with the vertical ball; less relevant against possession-dominant sides whose attacking threat derives from short combination play.",
        "magnitude": "Expected-goals-against from over-the-top situations falls 0.05-0.12 per match phase post-adjustment; possession conceded in the middle third rises 8-14% as the price of the defensive depth gained.",
        "links": ["press_trigger_recalibration", "halftime_shape_change_delta", "block_height_drop_to_protect_lead", "target_man_route_introduction"],
    },
    {
        "slug": "tempo_control_through_possession_phases",
        "title": "Tempo Control Through Possession-Phase Modulation",
        "summary": "Slowing or accelerating the game by changing pass tempo and directness based on scoreline is measurable through change in passes-per-sequence, sequence duration, and direct-speed metrics between controlling and chasing phases.",
        "stat_signature": "Passes per sequence rises from 3.8-5.2 to 7.0-9.5 when a leading side shifts into tempo-kill possession; sequence duration extends from 8-12 seconds to 18-28 seconds; direct-speed metric (proportion of sequences covering more than 30 metres in under 6 seconds) falls from 22-30% to 8-14% in the slow-tempo phase.",
        "mechanism": "Extending possession sequences forces the pressing side to commit effort to recovery runs that accumulate fatigue without generating goal-scoring opportunities; controlled recycling around the opponent's defensive block simultaneously preserves the lead and depletes the opponent's capacity to press effectively.",
        "conditions": "Tempo kill is viable only for sides with high technical ball-retention quality; it is most effectively deployed when leading by one goal from minute 65 onward with a high-press opponent whose energy budget is depleting.",
        "magnitude": "Ball-in-play time controlled by the leading side rises 10-18 percentage points in the slow-possession phase; opponent high-intensity-distance output falls 12-20% across the tempo-kill period as recovery runs without the ball accumulate fatigue.",
        "links": ["game_management_time_use_late", "block_height_drop_to_protect_lead", "halftime_shape_change_delta", "rest_defense_balance_dial"],
    },
    {
        "slug": "double_team_redirect_on_a_threat",
        "title": "In-Game Double-Up Redirect Onto a Threat",
        "summary": "Committing a second defender to a dangerous ball carrier after that player has begun to influence the match reduces progressive-carry and chance-creation output in the subsequent phase.",
        "stat_signature": "Progressive-carry completions for the doubled threat fall 30-45% in the phase following the adjustment; chance-creation actions attributed to the doubled player drop 25-40%; however, the vacated space from the second defender creates a 15-20% lift in danger from the player's nearest teammate who exploits the gap.",
        "mechanism": "Doubling denies the threat time and space to drive forward or play, but necessarily creates a 1v1 elsewhere on the pitch; the net effect depends on whether the threat's isolated teammate can exploit the overcommitment.",
        "conditions": "Applied mid-match when a ball carrier exceeds a threshold influence — typically three or more progressive carries or key passes in a 20-minute window; requires a positional read from the nearest midfielder to release from their own role.",
        "magnitude": "Direct output from the doubled threat falls 30-45%; secondary expected-goals creation from the exploited vacancy rises 0.03-0.08 per 15-minute phase, partially offsetting the suppression.",
        "links": ["man_to_zonal_marking_switch", "press_trigger_recalibration", "fullback_role_inversion_adjustment", "block_height_drop_to_protect_lead"],
    },
    {
        "slug": "set_piece_routine_variation_after_scouting",
        "title": "Set-Piece Routine Variation Within the Match",
        "summary": "Changing dead-ball delivery zone and runner patterns after early routines were defended produces variation in first-contact win rate measurable across successive set pieces within a match.",
        "stat_signature": "First-contact win rate on corners and free kicks in the first three of a match averages 38-46%; after two or more defended deliveries, sides shifting delivery zone or runner assignment see first-contact win rate rise to 52-60% on subsequent attempts; expected-goals-per-set-piece improves 0.010-0.025 following an in-match routine variation.",
        "mechanism": "Defenders set up their marking assignments based on observed opener routines; altering the delivery target zone or introducing a blocking-run disrupts the pre-positioned scheme before the defence can re-rehearse the counter.",
        "conditions": "Variation is most impactful against zonal-marking sides where zone assignments are predetermined; less impactful against man-marking sides where runners are individually tracked regardless of delivery zone.",
        "magnitude": "Expected-goals-per-set-piece lift of 0.010-0.025 per routine variation event; first-contact win rate improvement of 10-18 percentage points in the phase following the routine change.",
        "links": ["man_to_zonal_marking_switch", "halftime_shape_change_delta", "wide_overload_to_central_overload_shift", "double_team_redirect_on_a_threat"],
    },
    {
        "slug": "fullback_role_inversion_adjustment",
        "title": "In-Game Fullback Role Inversion or Release",
        "summary": "Shifting fullbacks mid-match between inverted central support and high-wide overlap solves build-up or width problems, measurable by change in fullback average touch position and the team's progression-route distribution.",
        "stat_signature": "Fullback average touch position shifts inward by 8-14 metres (laterally) when inverting; proportion of build-up progression routed through the fullback's new interior channel rises from 12-18% to 28-38%; wide crossing volume drops 20-30% when both fullbacks invert, redirecting width responsibility to the wide attacker.",
        "mechanism": "Inverting a wide fullback creates a numerical overload in the central progression corridor, allowing the team to by-pass a pressed wide channel; releasing a fullback to overlap creates an uncovered width threat if the opponent tracks the inversion and narrows defensively.",
        "conditions": "Inversion is triggered when the wide channel is being dominated by the opponent's winger pressing the fullback into backward passing; the switch requires a central midfielder to cover the vacated wide defensive zone against transitions.",
        "magnitude": "Progression-route efficiency from the fullback zone improves 15-25% after an inversion adjustment; wide-zone threat creation rises 20-30% when a released fullback overlaps against a side that over-narrowed to block the central route.",
        "links": ["halftime_shape_change_delta", "wide_overload_to_central_overload_shift", "chase_state_shape_push", "pressing_trap_redirection_to_a_new_side"],
    },
    {
        "slug": "pressing_trap_redirection_to_a_new_side",
        "title": "Pressing-Trap Redirection to a New Side",
        "summary": "Moving the engineered pressing trap from one flank or player to another after the opponent escapes the first is measurable by the change in where high turnovers are forced and recovery-to-shot conversion in the relocated trap zone.",
        "stat_signature": "High-turnover location centroid shifts 15-25 metres laterally when a trap is redirected; recovery-to-shot conversion in the new trap zone rises to 18-25% in the first four activations before the opponent identifies and escapes the updated trigger; PPDA in the new target zone improves 20-35% versus the abandoned trap zone's late-phase rate.",
        "mechanism": "Opponents learn to trigger and escape a repetitive pressing trap within 2-3 activations; redirecting the trap's target zone and the cue condition resets the learning advantage and briefly restores the high-turnover value that motivated the press.",
        "conditions": "Redirection is feasible when the pressing side has sufficient structural flexibility to shift the trigger side without exposing a new vulnerability; it requires that the trap-escape route the opponent has learned routes them into the new target zone.",
        "magnitude": "Trap-escape rate for the opponent rises from 15-25% initially to 40-55% after repeated exposure; redirection resets the escape rate to below 25% for the next 3-5 activations before knowledge accumulates again.",
        "links": ["press_trigger_recalibration", "fullback_role_inversion_adjustment", "fresh_legs_pressing_reinforcement", "halftime_shape_change_delta"],
    },
    {
        "slug": "rest_defense_balance_dial",
        "title": "Rest-Defense Balance Dial During Sustained Pressure",
        "summary": "Adjusting how many players stay back in attacking phases to guard against transitions — in response to leaked counters — is measurable by the change in players-behind-the-ball count and opponent counter-attack frequency.",
        "stat_signature": "Average players behind the ball in the attacking phase changes from 3-4 to 5-6 after two or more counter-attack concessions in a 30-minute window; opponent counter-attack frequency falls 30-45% in the subsequent phase; own final-third entries per minute drop 12-18% as a consequence of the retained defensive shape.",
        "mechanism": "Retaining an additional midfielder or wide player in a defensive reference position eliminates the numerical advantage that transition-capable opponents gain in the space vacated by committed attackers; the cost is reduced attacking overload density in the final third.",
        "conditions": "Dial adjustment is most common after conceding two or more counter-attack opportunities from an advanced possession phase; required when facing opponents whose central forwards or wide players are specifically dangerous in the transition phase.",
        "magnitude": "Counter-attack frequency reduction of 30-45% in the adjusted phase; own expected-goals-for per phase falls 0.04-0.09 from the retained defensive shape — a trade-off that rational management accepts when protecting a lead or reducing transition risk.",
        "links": ["block_height_drop_to_protect_lead", "tactical_foul_to_break_transition", "defensive_substitution_to_close_a_game", "press_trigger_recalibration"],
    },
    {
        "slug": "target_man_route_introduction",
        "title": "Introduction of a Direct Target Outlet",
        "summary": "Shifting build-up toward a physical aerial outlet when short progression is being pressed off the pitch raises long-pass share toward the central forward and aerial-duel and second-ball recovery rate after the change.",
        "stat_signature": "Long-ball percentage rises from 18-24% to 32-42% after introducing a target outlet; central-forward aerial-duel win rate in the subsequent phase averages 50-62%; second-ball recovery rate within 5 metres of the first aerial contact improves from 38-45% to 52-60% when supporting runners are repositioned to anticipate the contest.",
        "mechanism": "When short passing lanes are systematically pressed, the long-ball route bypasses the press entirely, relocating the contest to an aerial duel where a physical target forward can compete even against organised defence; second-ball players positioned ahead of the midfield line create immediate second-phase danger.",
        "conditions": "Effective when the side possesses a strong aerial forward and the opponent's centre-backs are below average at aerial duels or are physically mismatched against the target; ineffective if the opponent recruits aerial superiority at the back and wins second balls consistently.",
        "magnitude": "Aerial-duel win rate of 50-62% generates a second-phase possession sequence on over half of long-ball plays, converting a previously unproductive possession phase into a 0.06-0.12 expected-goals-per-10-long-balls rate.",
        "links": ["line_engagement_change_against_long_ball", "chase_state_shape_push", "wide_overload_to_central_overload_shift", "counter_to_opponent_block_change"],
    },
    {
        "slug": "game_management_time_use_late",
        "title": "Late-Game Time-Use and Tempo-Kill Management",
        "summary": "Controlled slowing of restarts and possession retention to manage out a result is measurable by dead-ball-to-restart interval lengthening, rise in defensive-third possession share, and fall in ball-in-play time late.",
        "stat_signature": "Goal-kick and throw-in restart intervals extend from 8-12 seconds to 18-28 seconds in the 80-90-minute window for managing sides; defensive-third possession share rises 12-20 percentage points in the final 15 minutes versus the mid-match baseline; ball-in-play percentage falls from a match average of 55-60% to 42-50% in the managed phase.",
        "mechanism": "Extended restarts reduce the total number of opponent possession sequences available in the remaining time; positional security in the defensive third minimises transition exposure; the combined effect shortens the opponent's window to produce high-expected-goals chances mechanically.",
        "conditions": "Applied when leading by one goal after minute 78 at away fixtures or against superior opposition; less viable when the referee awards time-added that effectively cancels the time saved, as frequently occurs under modern officiating directives.",
        "magnitude": "Ball-in-play reduction of 10-15 percentage points in the managed phase reduces opponent sequence count by 4-8 per 15 minutes; the cumulative expected-goals reduction is approximately 0.04-0.10 per match through fewer opponent possessions.",
        "links": ["block_height_drop_to_protect_lead", "tempo_control_through_possession_phases", "defensive_substitution_to_close_a_game", "tactical_foul_to_break_transition"],
    },
    {
        "slug": "counter_to_opponent_block_change",
        "title": "Attacking Counter to an Opponent Block Change",
        "summary": "When an opponent drops into a low block, the attacking side responds by recycling for crosses or shooting from distance; the adaptation is measurable by change in cross volume and outside-the-box shot share after the opponent's block lowers within the match.",
        "stat_signature": "Cross volume per 15 minutes rises 30-45% when the opponent shifts to a low block; outside-the-box shot share increases from 28-35% to 45-55% as central routes become congested; expected-goals-per-shot from outside-the-box attempts against a low block averages 0.055-0.075, below the match baseline of 0.100-0.120.",
        "mechanism": "A low block that surrenders the middle third forces the attacking side into wide deliveries or speculative distance shots as the only viable routes; cross-based attacks against a compact block generate second-ball and set-piece opportunities that partially recover lost expected-goals quality.",
        "conditions": "Adaptation depends on the available wide attackers' crossing quality and the central target forwards' aerial ability; against blocks that defend aerial delivery well, the attacking response may shift toward patient combination probing in half-space channels.",
        "magnitude": "Net expected-goals-for per phase falls 0.05-0.12 against a well-organised low block versus an open-game baseline; cross-and-set-piece recovery partially offsets this to a net reduction of 0.03-0.08, reflecting the structural defensive advantage of the low block.",
        "links": ["chase_state_shape_push", "wide_overload_to_central_overload_shift", "target_man_route_introduction", "block_height_drop_to_protect_lead"],
    },
]
