"""MLB InitiationProfiles concepts — person-free, descriptive intelligence nodes."""
from __future__ import annotations

SPORT = "MLB"
FAMILY = "InitiationProfiles"

CONCEPTS: list[dict] = [
    {
        "slug": "leadoff_plate_appearance_origin",
        "title": "Leadoff Plate-Appearance Origination",
        "summary": "Innings that begin with the top-of-lineup hitter set the baserunner context before the first out; leadoff on-base rate is the primary driver of the share of innings that begin with a runner already in play.",
        "stat_signature": "Elite leadoff on-base rate: .370–.400 OBP; league average: .320–.330. Innings with a leadoff baserunner score at roughly 40–44 percent versus 15–18 percent for innings starting with zero baserunners. Leadoff strikeouts convert to scoreless innings at roughly 78 percent.",
        "mechanism": "A leadoff on-base event shifts run-expectancy from ~0.48 to ~0.85–1.10 depending on the base reached, compressing the rest of the lineup's sequence toward run-scoring configurations and activating stolen-base and hit-and-run options that do not exist from an all-out origin.",
        "conditions": "Effect largest in high-run-environment parks where the downstream sluggers convert baserunner opportunities at above-average rates. Suppressed when the pitcher is elite at stranding runners, nullifying the origin advantage.",
        "magnitude": "Innings begun with a leadoff single produce runs at roughly 2.5 times the rate of innings begun with a leadoff out; this origination gap persists across park and era adjustments.",
        "links": ["leadoff_walk_rally_origin", "leadoff_double_extra_base_origin", "table_setter_on_base_initiation", "first_inning_script_origin"],
    },
    {
        "slug": "first_pitch_strike_setup",
        "title": "First-Pitch Strike Setup",
        "summary": "The opening pitch of each plate appearance determines count leverage for the entire at-bat; a first-pitch strike shifts run value sharply toward the pitcher while a ball shifts it toward the hitter.",
        "stat_signature": "First-pitch strike rate for elite starters: 63–68 percent; league average: 57–61 percent. At-bats beginning 0-1: hitter OPS roughly .640–.660. At-bats beginning 1-0: hitter OPS roughly .760–.800. First-pitch strike correlates with K/9 at r ≈ 0.55 across starter samples.",
        "mechanism": "An early strike allows the pitcher to expand the zone with secondary pitches on subsequent offerings, forcing hitters to protect on pitches at the periphery they would take from a ball-ahead count; hitters in 0-1 counts swing at pitches 4–7 percent outside the zone more frequently than in 1-0 counts.",
        "conditions": "Advantage largest for pitchers with a plus secondary that is most dangerous when thrown in pitcher-ahead counts, and against free-swinging lineups with high first-pitch swing rates that cede zone judgment early.",
        "magnitude": "First-pitch-strike leaders suppress wOBA-against roughly 0.025–0.040 below their overall season mark; at-bats with a first-pitch strike end in strikeouts at roughly 1.8–2.2 times the rate of at-bats beginning ball-one.",
        "links": ["count_origination_get_me_over", "ambush_first_pitch_swing", "first_pitch_breaking_ball_origin", "two_strike_origination_battle"],
    },
    {
        "slug": "leadoff_walk_rally_origin",
        "title": "Leadoff-Walk Rally Origination",
        "summary": "A free pass to the leadoff hitter injects a non-contact baserunner at the inning origin, shifting run-expectancy identically to a single while signaling elevated walk-rate risk that may carry through subsequent batters.",
        "stat_signature": "Leadoff walk innings score at roughly 40–43 percent, nearly matching leadoff-single scoring rate (~42–46 percent). Innings with a leadoff walk produce roughly 0.90–1.05 expected runs. Pitchers with leadoff-walk rates above 12 percent of innings faced allow 15–25 percent more runs per game.",
        "mechanism": "A walk creates a baserunner with zero batter-fatigue cost and no defensive positioning advantage, preserving the full sequence of quality hitters in the lineup; the walk itself signals poor command state that correlates with elevated zone-expansion on subsequent hitters.",
        "conditions": "Run amplification strongest when the subsequent lineup slot is a power hitter who benefits from runners on base; weakened when the walked hitter is a slow base runner limiting stolen-base or scoring-from-first options.",
        "magnitude": "Innings with a leadoff walk produce runs at roughly 2.5–2.8 times the rate of innings with a leadoff out; a pitcher allowing leadoff walks in more than 10 percent of innings faces roughly 0.25–0.40 additional ERA above expected from season walk rate alone.",
        "links": ["leadoff_plate_appearance_origin", "table_setter_on_base_initiation", "leadoff_hit_by_pitch_origin", "first_pitch_strike_setup"],
    },
    {
        "slug": "table_setter_on_base_initiation",
        "title": "Table-Setter On-Base Initiation",
        "summary": "Top-of-order slots one and two function as the on-base origin for the run-producing heart of the lineup; their combined on-base frequency determines how often the three-through-five slots receive baserunner context.",
        "stat_signature": "Combined slots one-to-two OBP above .360 delivers a baserunner to slot three in roughly 55–62 percent of innings. League-average combined table-setter OBP (.315–.330) delivers a runner in roughly 43–48 percent of innings. RBI opportunity rate for the middle of the order rises ~15–20 percent with elite table-setters.",
        "mechanism": "The lineup sequences so that table-setters bat earliest in each inning; their on-base frequency directly determines the expected run-value the heart of the order encounters. Each table-setter on-base event shifts the expected-runs-remaining curve upward by roughly 0.30–0.50 runs depending on the base occupied.",
        "conditions": "Effect largest when middle-of-order sluggers have high batting-average-on-balls-in-play and home-run rates that convert baserunner contexts efficiently; partially neutralized when the pitcher excels at stranding runners regardless of origin.",
        "magnitude": "Teams with top-five combined table-setter OBP score roughly 0.4–0.7 additional runs per game versus teams in the bottom quintile; RBI counts for middle-of-order hitters are roughly 12–18 percent higher with elite table-setters.",
        "links": ["leadoff_plate_appearance_origin", "leadoff_walk_rally_origin", "lineup_anchor_protection_origin", "bottom_of_order_turnover_origin"],
    },
    {
        "slug": "first_inning_script_origin",
        "title": "First-Inning Script Origination",
        "summary": "The opening inning is pitched before a starter's command and sequencing rhythms are fully settled; first-inning baserunner rates and pitch-count consumption differ systematically from innings two through five for most starters.",
        "stat_signature": "Starter first-inning ERA runs roughly 0.15–0.35 above innings two-through-four composite ERA. First-inning pitch count averages 16–20 pitches league-wide versus 13–16 in mid-game innings. First-inning walk rate is roughly 0.4–0.8 BB/9 above the starter's full-game average.",
        "mechanism": "Starters require facing live batters to calibrate release-point feel, spin-rate feedback, and breaking-ball break under game-condition adrenaline; the first inning is a calibration sample that exhibits higher command variance and less effective pitch tunneling than later innings once physical rhythm is established.",
        "conditions": "Effect amplified for pitchers who use grip-sensitive breaking balls as primary sequences; diminished for sinker-heavy pitchers whose ground-ball profile requires less command precision. Cold weather and outdoor early-season games widen the first-inning gap.",
        "magnitude": "First-inning run-scoring rate roughly 0.15–0.35 ERA units above subsequent innings for the median starter; approximately 15–22 percent of first-inning plate appearances produce baserunners at a higher rate than the same pitcher's mid-game average.",
        "links": ["leadoff_plate_appearance_origin", "first_pitch_strike_setup", "first_batter_faced_origin", "count_origination_get_me_over"],
    },
    {
        "slug": "count_origination_get_me_over",
        "title": "Get-Me-Over First-Pitch Origination",
        "summary": "A deliberate zone-center first offering designed to guarantee a strike sacrifices pitch tunneling in exchange for count leverage, producing early-count contact at an elevated rate and setting a zone-predictability expectation for hitters.",
        "stat_signature": "Zone-first-pitch rate above 70 percent correlates with contact rate on first pitches of roughly 18–24 percent. Early-count weak-contact (exit velocity below 90 mph) frequency roughly 5–8 percentage points above pitchers with sub-55 percent zone-first-pitch rate.",
        "mechanism": "A predictable first-offering zone target allows quality hitters to time and square up a less deceptive pitch; while count leverage is gained, hitters who correctly anticipate a fastball down the middle achieve above-average contact quality, partially offsetting the command benefit.",
        "conditions": "Most common for pitchers with below-average stuff who rely on command sequencing rather than raw velocity; used situationally by power pitchers behind in counts who cannot afford a two-strike approach without first establishing a strike.",
        "magnitude": "Zone-first-pitch-heavy pitchers allow first-pitch in-play slugging roughly 0.040–0.065 above pitchers who mix off-speed first offerings; the weak-contact trade-off is modest when followed by quality secondary pitches.",
        "links": ["first_pitch_strike_setup", "first_pitch_breaking_ball_origin", "ambush_first_pitch_swing", "first_inning_script_origin"],
    },
    {
        "slug": "ambush_first_pitch_swing",
        "title": "Ambush First-Pitch Swing Origination",
        "summary": "Hitters who swing at the first pitch initiate offensive action before any count pressure exists, trading zone selectivity for contact-on-anticipated-pitch quality; lineup tendencies toward first-pitch aggression reshape pitcher strategic options from the first offering.",
        "stat_signature": "League-wide first-pitch swing rate: roughly 27–31 percent. Elite first-pitch swingers: 36–44 percent. First-pitch swing contact rate: roughly 82–87 percent. BA on first-pitch balls in play: roughly .330–.360, materially above overall BA.",
        "mechanism": "Pitchers attempting a first-pitch strike against aggressive lineups face a forced choice: throw a quality zone pitch with high contact probability or work off the zone and concede a ball, starting each at-bat from count disadvantage; first-pitch aggression eliminates the 'free strike' benefit that anchors most opening-pitch strategy.",
        "conditions": "Effective against pitchers who rely on first-pitch-strike rate as the engine of their sequencing; ineffective against pitchers who deliberately start with balls to set up zone ambiguity or against high-first-pitch-breaking-ball frequency pitchers.",
        "magnitude": "First-pitch in-play events produce BABIP roughly 0.030–0.050 above league average; lineups in the top-decile of first-pitch swing rate score roughly 0.20–0.35 more runs per game from origination-phase plate efficiency.",
        "links": ["first_pitch_strike_setup", "count_origination_get_me_over", "first_pitch_breaking_ball_origin", "two_strike_origination_battle"],
    },
    {
        "slug": "leadoff_double_extra_base_origin",
        "title": "Leadoff Extra-Base Origination",
        "summary": "A leadoff double or triple places a runner in immediate scoring position with zero outs, generating the highest run-expectancy inning origin short of a home run and eliminating the need for a subsequent hit-then-advance sequence.",
        "stat_signature": "Leadoff double: run-expectancy ~1.17 runs, innings score at roughly 60–65 percent. Leadoff triple: run-expectancy ~1.43 runs, innings score at roughly 75–82 percent. Leadoff extra-base rate for top table-setters: roughly 8–12 percent of plate appearances.",
        "mechanism": "Positioning a runner on second or third with zero outs activates sacrifice, squeeze, wild-pitch, and passed-ball scoring paths that are unavailable from first base; the pitcher must also guard the runner's scoring position while managing the at-bat, dividing cognitive load.",
        "conditions": "Amplified in parks with large outfield dimensions where gap-to-gap contact converts to doubles at above-average rates; strongest when the follow-up hitter is a contact-over-power type capable of a run-scoring productive out.",
        "magnitude": "Leadoff extra-base origination produces runs at roughly 3.5–4.0 times the rate of leadoff-out origination; teams ranking in the top quartile of leadoff extra-base rate score roughly 0.35–0.55 additional runs per game from inning origination alone.",
        "links": ["leadoff_plate_appearance_origin", "table_setter_on_base_initiation", "leadoff_walk_rally_origin", "bottom_of_order_turnover_origin"],
    },
    {
        "slug": "bottom_of_order_turnover_origin",
        "title": "Bottom-of-Order Turnover Origination",
        "summary": "Innings begun by slots seven through nine require the weakest hitters to generate a baserunner before turning the lineup back to the top; the on-base rate of the bottom third determines how frequently the high-quality top-of-order originates a second-at-bat inning.",
        "stat_signature": "Bottom-third OBP league average: roughly .290–.310. Innings begun by slot seven-through-nine that produce a leadoff baserunner before the first out: roughly 29–33 percent. Each 10-point bottom-third OBP gain correlates with roughly 0.08–0.12 additional runs per game.",
        "mechanism": "When the bottom of the order reaches base, the lineup turns over into the high-leverage origination slots during the same inning, compounding origination quality; conversely, bottom-third strikeouts terminate the inning without providing any sequential lineup continuation.",
        "conditions": "Effect largest in lineups with a dramatic talent gap between the heart of the order and bottom-third; partially offset in lineups designed with contact-first slots eight and nine that suppress strikeouts and maximize turnover frequency.",
        "magnitude": "Teams with bottom-third OBP above .330 produce roughly 0.3–0.5 more runs per game than teams with bottom-third OBP below .290; the difference compounds across a 162-game season to roughly 50–80 additional runs.",
        "links": ["table_setter_on_base_initiation", "leadoff_plate_appearance_origin", "lineup_anchor_protection_origin", "bunt_to_initiate_rally"],
    },
    {
        "slug": "first_batter_faced_origin",
        "title": "First-Batter-Faced Origination",
        "summary": "The pitcher's inning initiation against its opening hitter determines the clean-start or trouble-inherited state for the entire half-inning; first-batter-retired rate is among the strongest per-inning run-prevention predictors.",
        "stat_signature": "Elite starters retire the first batter in roughly 68–73 percent of innings; league average: 63–67 percent. Innings where the first batter reaches base: run-expectancy jumps from ~0.48 to ~0.85–1.10. ERA in first-batter-reached innings is roughly 1.8–2.4 times the ERA in first-batter-retired innings.",
        "mechanism": "Retiring the first batter resets leverage to a low state, allowing the pitcher to work with reduced run-expectancy pressure; allowing the first batter to reach immediately activates situational defense positioning, sacrifice-bunt options, and secondary-hitter strategies the defense must manage simultaneously.",
        "conditions": "Effect strongest for pitchers whose command variance is high inning-to-inning; dampened for groundball-heavy pitchers who generate double-play opportunities even after first-batter reach events.",
        "magnitude": "First-batter-retire rate difference of 5 percentage points corresponds to roughly 0.18–0.28 ERA reduction across a full season; relief pitchers who inherit mid-inning situations show first-batter retire rates 3–6 points lower than starters facing fresh innings.",
        "links": ["first_inning_script_origin", "leadoff_plate_appearance_origin", "first_pitch_strike_setup", "inning_origin_clean_slate_rate"],
    },
    {
        "slug": "steal_origin_first_to_second",
        "title": "Stolen-Base Origination",
        "summary": "A successful steal of second immediately after the leadoff baserunner event converts a first-base origin into a scoring-position origin without consuming an out, shifting the inning's run-expectancy by roughly 0.30–0.50 runs.",
        "stat_signature": "Steal-attempt success rate threshold for positive run-expectancy: roughly 72–74 percent. League-average success rate: roughly 77–80 percent. Run-expectancy shift from first to second with zero outs: ~0.48 to ~1.10, a gain of ~0.62 runs. Caught-stealing run-expectancy cost: roughly -0.45 runs.",
        "mechanism": "A successfully stolen base eliminates the need for a subsequent hit to advance the runner into scoring position; it also shifts the defensive positioning toward infield-in configurations and raises intentional-walk frequency for the subsequent hitter, altering the pitcher's sequencing strategy.",
        "conditions": "Positive run-expectancy only above the break-even success rate; against elite-caught-stealing catchers, the break-even threshold rises to 78–82 percent, reducing net-positive steal opportunities. High-strikeout pitchers reduce the value of being in scoring position by raising the probability of a strikeout ending the sequence.",
        "magnitude": "Net run-expectancy gain of ~0.15–0.25 runs per successful attempt at league-average success rates; teams in the top-quartile of team stolen-base efficiency score roughly 0.15–0.25 more runs per game from this origination-advancement mechanism.",
        "links": ["leadoff_plate_appearance_origin", "leadoff_walk_rally_origin", "hit_and_run_initiation", "table_setter_on_base_initiation"],
    },
    {
        "slug": "lineup_anchor_protection_origin",
        "title": "Lineup-Anchor Protection Origination",
        "summary": "Run-production origination flows into the middle-of-order anchor when preceding on-base events are frequent; the anchor's run-expectancy context — runners-on frequency — determines whether the lineup's best hitter maximizes RBI and extra-base productivity.",
        "stat_signature": "Heart-of-order hitters with preceding table-setters posting combined OBP above .360 encounter runners-on in roughly 55–62 percent of at-bats; those with bottom-half table-setters (.300–.315 OBP) encounter runners-on in roughly 38–44 percent of at-bats. RBI rate per at-bat: roughly 0.18–0.24 with runners-on versus 0.04–0.06 with bases empty.",
        "mechanism": "The anchor batter's RBI and scoring-event frequency is structurally dependent on origination events from preceding slots; lineup construction that isolates the anchor behind weak on-base performers neutralizes slugging power by removing the baserunner context that converts extra-base hits into multi-run events.",
        "conditions": "Strongest when the anchor batter has a high line-drive-plus-fly-ball rate that converts runner-on contexts into multi-base RBI events. Partially offset when the pitcher elevates intentional walks to bypass the anchor when first base is open.",
        "magnitude": "An anchor batter receiving runners-on contexts 15 percentage points more frequently accumulates roughly 12–20 additional RBI over a full season; this represents a systematic 8–13 percent RBI rate improvement from lineup-origination optimization alone.",
        "links": ["table_setter_on_base_initiation", "bottom_of_order_turnover_origin", "leadoff_double_extra_base_origin", "leadoff_plate_appearance_origin"],
    },
    {
        "slug": "first_pitch_breaking_ball_origin",
        "title": "First-Pitch Breaking-Ball Origination",
        "summary": "Initiating a plate appearance with a non-fastball first offering disrupts the hitter's timing assumption anchored to velocity, generating early weak-contact or called-strike outcomes at rates above the first-pitch fastball baseline.",
        "stat_signature": "First-pitch breaking-ball rate among curveball-heavy starters: roughly 18–26 percent of first pitches. First-pitch curveball called-strike rate: roughly 52–58 percent. Swinging-strike rate on first-pitch breaking balls: roughly 12–16 percent versus 7–10 percent on first-pitch fastballs.",
        "mechanism": "Hitters time their pre-pitch preparation to an expected fastball arrival window; a breaking ball arriving 8–15 mph slower with movement disrupts the swing-trigger timing, producing early swings over the ball, checked-swing calls, and off-center contact that results in above-average ground-ball rates.",
        "conditions": "Effective against lineups with high first-pitch swing rates who commit early to fastball timing; weakened against patient hitters who take the first pitch at above-average rates regardless of pitch type.",
        "magnitude": "First-pitch breaking-ball ground-ball rate roughly 55–65 percent versus 42–50 percent for first-pitch fastballs; pitchers using breaking balls as 20-percent-plus first offerings suppress early-count slugging by roughly 0.040–0.060 OPS.",
        "links": ["first_pitch_strike_setup", "count_origination_get_me_over", "ambush_first_pitch_swing", "two_strike_origination_battle"],
    },
    {
        "slug": "leadoff_hit_by_pitch_origin",
        "title": "Leadoff Hit-by-Pitch Origination",
        "summary": "A leadoff plunk injects a non-contact baserunner with identical run-expectancy to a leadoff walk, while also signaling acute command disruption that elevates the probability of subsequent walk or hit-by-pitch events in the same inning.",
        "stat_signature": "Leadoff HBP innings score at roughly 40–43 percent, matching leadoff-walk scoring rate. Pitcher HBP rate above 1.2 per nine innings correlates with same-inning walk rate roughly 15–20 percent above baseline. Leadoff-HBP innings produce approximately 0.88–1.05 expected runs.",
        "mechanism": "A hit-by-pitch reflects acute command failure: the pitch missed its intended target by a substantial margin. This command-failure signal often indicates a grip-disruption or mechanical inconsistency that persists across subsequent batters in the same inning, raising the probability of further base-on-balls events.",
        "conditions": "Signal strength largest in cold-weather games where reduced grip quality amplifies pitch-location variance; dampened for pitchers with chronically high-HBP rates due to deliberate inside fastball usage, where the HBP reflects strategy rather than command failure.",
        "magnitude": "Same-inning escalation: pitchers who issue a leadoff HBP allow additional baserunners in that inning at roughly 1.3–1.5 times their baseline per-inning rate; scoring frequency matches leadoff-walk innings at roughly 40–43 percent.",
        "links": ["leadoff_walk_rally_origin", "leadoff_plate_appearance_origin", "first_pitch_strike_setup", "inning_origin_clean_slate_rate"],
    },
    {
        "slug": "inning_origin_clean_slate_rate",
        "title": "Clean-Slate Inning Origination Rate",
        "summary": "The share of half-innings that begin with bases empty and no inherited runners quantifies how frequently each side operates from a zero-context start rather than a carried-pressure or inherited-runner context.",
        "stat_signature": "Clean-slate inning rate for starters in innings one through five: roughly 85–92 percent (low carry-in frequency). Relief-pitcher clean-slate rate: roughly 55–68 percent due to inherited-runner appearances. Expected runs from a true clean slate origin: ~0.48 runs versus ~1.10 from a runner-on-second inherited origin.",
        "mechanism": "A clean-slate origin minimizes baseline run-expectancy and eliminates inherited-runner scoring probability that inflates ERA for relievers; pitchers who routinely create clean-slate origins by retiring the previous inning's final batters maintain the structural advantage of starting each half-inning at minimum run-expectancy.",
        "conditions": "Most relevant for middle relievers who frequently enter mid-inning, where inherited-runner scoring directly impacts ERA; for starters, the clean-slate rate is nearly constant across innings and serves as a baseline reference for comparing across contexts.",
        "magnitude": "Relievers entering with inherited runners allow those runners to score at roughly 28–34 percent rates; the ERA inflation from non-clean-slate appearances can add 0.40–0.80 ERA units to a reliever's season mark relative to their true run-prevention ability.",
        "links": ["first_batter_faced_origin", "leadoff_plate_appearance_origin", "leadoff_hit_by_pitch_origin", "leadoff_walk_rally_origin"],
    },
    {
        "slug": "two_strike_origination_battle",
        "title": "Two-Strike Origination Battle",
        "summary": "Plate appearances that reach a two-strike count reset the effective at-bat origin to a deep-count survival battle, where the hitter's zone-expansion and foul-extension ability determine whether the origination results in a strikeout or a continued sequence.",
        "stat_signature": "Two-strike contact rate: roughly 72–78 percent; strikeout probability from two-strike count: roughly 32–38 percent. Foul-ball extension frequency at two strikes: roughly 1.8–2.4 fouls per two-strike at-bat. BA on two-strike balls in play: roughly .220–.250, roughly 80 points below overall BA.",
        "mechanism": "Two-strike counts force hitters to expand their zone acceptance to protect against borderline called third strikes; zone-expansion raises contact on pitches at the zone's lower edge and outer periphery where exit velocity and launch angle are degraded, producing a systematic shift toward weak-contact outcomes on the balls that are put into play.",
        "conditions": "Strongest against hitters with high strikeout rates who lack two-strike adjustment approaches; weakened against contact-first hitters with low called-strikeout rates who make consistent two-strike foul contact and extend at-bats until receiving a hittable offering.",
        "magnitude": "Two-strike wOBA of roughly .220–.250 represents a roughly 0.090–0.130 reduction from the same lineup's overall wOBA; pitchers who reach two strikes in 48-plus percent of at-bats suppress opponent wOBA by roughly 0.030–0.045 above league average.",
        "links": ["first_pitch_strike_setup", "ambush_first_pitch_swing", "first_pitch_breaking_ball_origin", "count_origination_get_me_over"],
    },
    {
        "slug": "platoon_matchup_at_bat_origin",
        "title": "Platoon-Matchup At-Bat Origination",
        "summary": "Handedness alignment at the origination of each plate appearance shapes early-count pitch-tunnel effectiveness, early swing-and-miss probability, and the probability that the at-bat converts to a quality contact event.",
        "stat_signature": "Platoon OPS advantage (opposite-hand versus same-hand confrontation): roughly .040–.070. First-pitch whiff rate in platoon-disadvantaged matchups: roughly 2.5–4.0 percentage points above neutral. Same-hand breaking-ball called-strike rate: roughly 55–62 percent versus 47–53 percent in opposite-hand matchups.",
        "mechanism": "Opposite-hand pitchers deliver breaking balls that move into the hitter's sightline from an angle that tracks longer as a strike before breaking off the barrel; same-hand breaking balls depart away from the hitter's dominant eye, reducing tunnel effectiveness from the first pitch and widening the contact-quality gap across the full at-bat.",
        "conditions": "Magnified in deep counts where the handedness advantage controls which secondary pitch dominates the two-strike arsenal; diminished for hitters with neutral platoon splits (gap below 0.020 OPS) who adjust release-point perception without a handedness cue.",
        "magnitude": "Platoon-matched lineups originate at-bats in the platoon-advantage state for roughly 65–70 percent of at-bats when managed actively; wOBA improvement of roughly 0.025–0.045 per at-bat in the platoon-favorable origination context.",
        "links": ["first_pitch_breaking_ball_origin", "first_pitch_strike_setup", "two_strike_origination_battle", "first_batter_faced_origin"],
    },
]
