"""InitiationProfiles — Tennis: person-free, dense point-origination concept nodes."""
from __future__ import annotations

SPORT = "Tennis"
FAMILY = "InitiationProfiles"

CONCEPTS: list[dict] = [
    {
        "slug": "first_serve_placement_origin",
        "title": "First-Serve Placement Origination",
        "summary": "Where serves are directed on the first delivery — wide, body, or T — expressed as zone-share per court side and placement entropy, forming the spatial blueprint from which every service point departs.",
        "stat_signature": "Dominant-zone share above 58% per side flags a readable pattern. Placement entropy below 1.0 bits signals pattern-lock; above 1.4 bits signals maximal variety. First-serve-in rate above 65% is the gate for pattern value to materialise.",
        "mechanism": "Consistent placement in one zone forces the returner to pre-read and narrow stance width, gaining reaction advantage; however, learned patterns are exploited as match data accumulates. High entropy raises the returner's positional uncertainty and widens error bands on the return.",
        "conditions": "Entropy advantage is largest early in a match before the returner has calibrated. Wide-court servers on the ad side exploit right-handed opponents' backhand; body serves suppress swing paths on both sides. Pattern value decays after three consecutive serves to the same zone inside a set.",
        "magnitude": "Shifting dominant-zone share from 65% to 45% per side is associated with a ~3-5pp reduction in first-serve return points won as the returner must cover more court.",
        "links": ["second_serve_initiation_pattern", "deuce_court_serve_origin", "ad_court_serve_origin", "first_strike_pattern_origin"],
    },
    {
        "slug": "second_serve_initiation_pattern",
        "title": "Second-Serve Initiation Pattern",
        "summary": "How the server originates points on the second delivery — measured by spin type (kick, slice, flat), placement spread, and the frequency with which the server begins the ensuing rally on the defensive back foot.",
        "stat_signature": "Kick-serve usage rate above 55% on second serves marks a spin-dominant pattern. Body-jam rate above 18% on the ad-court second serve is a suppression signal. Double-fault rate below 2.0% per service game is the baseline reliability floor.",
        "mechanism": "A high-bouncing kick to the backhand corner pushes the returner above the strike-zone sweet-spot and narrows attack angles; a body jam collapses the swing arc. Spin variety prevents groove-loading on repeated second serves and keeps the returner's strike-zone assessment uncertain.",
        "conditions": "Kick benefit is amplified on clay where bounce height is greatest, and against one-handed backhand returners unable to absorb high-contact pace. On grass the skid neutralises kick; body jams remain effective on all surfaces.",
        "magnitude": "A body-jam second-serve rate above 25% on the ad court suppresses aggressive return intent by ~3-5pp relative to a purely wide or T second serve.",
        "links": ["first_serve_placement_origin", "kick_serve_origination", "slice_serve_origination", "second_serve_attack_origin"],
    },
    {
        "slug": "serve_plus_one_origin",
        "title": "Serve-Plus-One Origination",
        "summary": "The server's scripted first groundstroke after the delivery — measured by plus-one forehand-share, direction into the opened court, and the rate of dictating rally shape on the first strike after a successful serve.",
        "stat_signature": "First-strike specialists place the plus-one into the opened court above 60% of opportunities. Forehand-after-serve rate above 55% marks deliberate pattern construction. Inside-out forehand plus-one rate above 35% identifies a serve-and-forehand combo specialist.",
        "mechanism": "A wide serve opens the diagonal court; a scripted forehand into the vacated space converts geometric advantage into immediate point pressure without requiring a longer rally construction phase. Pattern co-design of serve placement and plus-one direction multiplies the combined effect.",
        "conditions": "Pattern is most usable when the first serve lands in — second-serve plus-one sequences carry higher execution risk. Against early-contact returners who redirect cross-court, the opened space closes before the third ball arrives.",
        "magnitude": "A coherent serve-plus-one scheme raises third-ball winner or forced-error rate by ~8-12pp versus an unstructured first-strike approach on the same first-serve in-rate.",
        "links": ["first_serve_placement_origin", "serve_location_to_open_court", "first_strike_pattern_origin", "serve_and_volley_origin"],
    },
    {
        "slug": "deuce_court_serve_origin",
        "title": "Deuce-Court Serve Origination",
        "summary": "Point initiation from the deuce side — measured as wide, body, and T placement distribution on deuce-court deliveries and the directional pull it exerts on the returner's first contact position.",
        "stat_signature": "Wide-serve share on the deuce side above 50% is structurally common; T-serve share above 35% marks a backhand-attack strategy. Body-serve deuce rate above 15% signals a jam-variety pattern. Deuce-side first-serve-in rate typically 2-4pp higher than ad-side.",
        "mechanism": "A wide serve on the deuce side pulls a right-handed returner off the court and opens the cross-court forehand plus-one lane; a T serve directly attacks the backhand, forcing the weaker wing into the initiating exchange. Placement choice predetermines the geometric starting conditions for the rally.",
        "conditions": "Wide deuce serves are most effective against returners without a reliable inside-out running forehand. T serves to the deuce side are most exploitable against two-handed backhand players with limited reach extension.",
        "magnitude": "A deuce-side wide-serve rate above 55% correlated with a coherent cross-court plus-one pattern generates ~4-6pp higher deuce-side service-point win rate versus a random placement baseline.",
        "links": ["first_serve_placement_origin", "ad_court_serve_origin", "serve_location_to_open_court", "tiebreak_serve_origination"],
    },
    {
        "slug": "ad_court_serve_origin",
        "title": "Ad-Court Serve Origination",
        "summary": "Point initiation from the advantage side — captured as the wide-to-T placement split on ad-court deliveries and the open-court geometry it sets up for the server's first strike after a landing serve.",
        "stat_signature": "Wide ad-court serve rate above 45% marks a left-side open-court strategy. T serve rate above 30% signals direct backhand targeting. Ad-side ace rate typically 1-2pp higher than deuce side on right-handed servers due to the wide-to-backhand angle.",
        "mechanism": "A wide serve on the ad side pulls the returner off the court to the left, opening the cross-court forehand opportunity for the server; a T serve attacks the returner's backhand at a deep straight angle. The ad-court geometry is particularly punishing on the wide ball because the angle of departure is sharpest.",
        "conditions": "Wide ad-side serves are most effective on break points where the returner is under psychological pressure. T serves are most effective on fast surfaces where the skid eliminates the returner's adjustment step.",
        "magnitude": "An ad-side wide-serve rate above 50% combined with consistent forehand plus-one execution is associated with ~4-7pp higher break-point save rate versus a non-directional placement approach.",
        "links": ["first_serve_placement_origin", "deuce_court_serve_origin", "kick_serve_origination", "game_opening_point_origin"],
    },
    {
        "slug": "return_depth_origination",
        "title": "Return-Depth Origination",
        "summary": "How the returner originates the rally by the depth of the first ball back — measured as the deep (back-third), mid-court, and short return distribution and the neutralisation rate each depth band yields.",
        "stat_signature": "Elite neutralising return: above 55% of returns landing in the back third within 1 m of the baseline. Short-ball return rate below 20% marks a disciplined depth floor. Return-depth stability r ~0.58 across matches on the same surface.",
        "mechanism": "A deep return pushes the server behind the baseline, compressing available angles and forcing a defensive first groundstroke; a short return gifts an attackable mid-court ball and transfers rally initiative back to the server. Depth discipline at the origination point determines which player enters the rally phase in control.",
        "conditions": "Deep-return discipline is most critical on second serves where the returner has time to load. Against a wide-jam serve, contact quality drops and depth naturally falls; the informative signal is deep-return rate conditioned on clean contact.",
        "magnitude": "Improving deep-return rate from 45% to 58% on second serves corresponds to roughly 3-4pp additional second-serve return points won across a match.",
        "links": ["return_position_origin", "return_target_seam_origin", "chip_return_initiation", "aggressive_block_return_origin"],
    },
    {
        "slug": "return_position_origin",
        "title": "Return-Position Origination",
        "summary": "The returner's court depth at contact as a point-origination lever — measured by the frequencies of standing back, on-baseline, and inside-baseline return stances, and the time-pressure each imposes on the server's first strike.",
        "stat_signature": "Aggressive inside-baseline stance: above 35% of second-serve returns contacted inside the line. On-the-rise contact share above 25% on first serves marks exceptional reaction capability. Stance depth stability r ~0.62 within a surface.",
        "mechanism": "Contacting the return inside the baseline compresses the server's recovery window by 0.15-0.25 s, effectively shortening the time between the serve landing and the server needing to strike. It requires early preparation and a disciplined split step; errors rise when rushed.",
        "conditions": "Inside-baseline stance most effective on medium-to-slow hard courts and clay where server recovery after the delivery is inherently slower. On grass the added pace makes inside-baseline contact on first serves high-risk.",
        "magnitude": "An inside-baseline contact share above 35% on second serves raises second-serve return points won by ~3-5pp versus a behind-baseline default return stance.",
        "links": ["return_depth_origination", "aggressive_block_return_origin", "second_serve_attack_origin", "return_target_seam_origin"],
    },
    {
        "slug": "chip_return_initiation",
        "title": "Chip-Return Initiation",
        "summary": "Points the returner originates with a low sliced block — quantified by chip-return frequency and the share that forces a low rising-ball first volley or a cramped mid-court reply from the server.",
        "stat_signature": "Chip-return rate above 25% on first serves marks a primary neutralisation strategy. Low-ball-to-server rate above 60% from chip returns measures effective execution. Chip-to-approach sequence rate above 15% identifies a serve-and-volley counter pattern.",
        "mechanism": "A low sliced chip skids through fast surfaces and stays below net height, forcing the server to scoop the ball from below knee level on their first strike and reducing their available angles. On slower courts it serves as a rhythm disruptor that breaks the server's groundstroke groove.",
        "conditions": "Most effective on grass where the chip skids and stays low, making the server's first groundstroke mechanically awkward. Against serve-and-volley specialists it creates an attacking low-first-volley problem. Least effective on clay where the ball sits up after the chip.",
        "magnitude": "A chip-return rate above 30% on grass surfaces suppresses server first-strike aggression by ~4-6pp compared to returners who default to a full groundstroke return.",
        "links": ["return_depth_origination", "aggressive_block_return_origin", "return_position_origin", "first_strike_pattern_origin"],
    },
    {
        "slug": "aggressive_block_return_origin",
        "title": "Aggressive Block-Return Origination",
        "summary": "Rally starts where the returner punches the ball back early on a fast first serve to steal time — measured by block-return frequency and the depth-on-fast-serve retention rate it achieves at the origination point.",
        "stat_signature": "Block-return rate above 30% on first serves above 185 km/h marks a time-efficient return strategy. Depth retention (landing in back third) from block returns above 45% is an elite execution floor. Block-return errors below 18% on first serves define a reliable pattern.",
        "mechanism": "A compact block return on a fast serve converts the server's pace into the return's pace without a full swing, cutting rally initiation time; the trade-off is reduced directional control. Reliable depth retention on the block denies the server a comfortable first-strike opportunity.",
        "conditions": "Most viable on fast hard courts and grass where first-serve pace is highest. Requires late preparation tolerance and a short backswing; players with wide take-back mechanics struggle to execute reliably.",
        "magnitude": "A block-return depth-retention rate above 48% on first serves above 190 km/h neutralises approximately 3-4pp of the server's pace advantage relative to a full-swing return.",
        "links": ["return_position_origin", "chip_return_initiation", "return_depth_origination", "second_serve_attack_origin"],
    },
    {
        "slug": "kick_serve_origination",
        "title": "Kick-Serve Origination",
        "summary": "Points the server begins with a high-bouncing topspin delivery — quantified by kick-serve usage rate, the elevated-contact return height it forces, and the positional disadvantage it creates at the rally origin.",
        "stat_signature": "Kick-serve rate above 55% on second serves marks a spin-dominant initiator. Kick serves that produce a return contact above shoulder height at a rate above 40% are generating the intended effect. Bounce-height correlation with clay: kick bounces average 1.2-1.6 m on clay versus 0.8-1.1 m on hard courts.",
        "mechanism": "A kick serve's upward trajectory forces the returner into an above-shoulder strike zone where both power and direction are mechanically constrained; the high contact window shrinks angle options and increases frame-strike and floated-return rates. On the ad side, a kick to the backhand combines spin pressure with wing targeting.",
        "conditions": "Kick effectiveness is amplified on clay where bounce height peaks and on ad-side targets against one-handed backhand players. On grass the lower skid bounce reduces the kick's height advantage significantly.",
        "magnitude": "A kick-serve rate above 55% generating above-shoulder returns at a 40%+ rate is associated with ~4-6pp lower second-serve return points won relative to a flat/slice-dominant second-serve pattern.",
        "links": ["second_serve_initiation_pattern", "slice_serve_origination", "ad_court_serve_origin", "body_serve_origination"],
    },
    {
        "slug": "flat_serve_origination",
        "title": "Flat-Serve Origination",
        "summary": "Points started with a high-pace minimal-spin delivery — quantified by flat-serve usage rate, its unreturned-serve frequency, and the free-point yield it generates at the rally origin before a rally begins.",
        "stat_signature": "Flat-serve usage above 55% on first serves marks a pace-first initiator. Ace-plus-service-winner rate above 22% per service game is the elite flat-serve threshold. First serve above 205 km/h on flat trajectory compresses return window to below 0.40 s.",
        "mechanism": "A flat serve maximises speed at minimal arc cost; the compressed reaction window below 0.40 s limits the returner to a reactive block rather than a constructive swing, producing a high rate of returned errors and weak short balls that enable easy third-ball attacks.",
        "conditions": "Flat serves maximise efficiency on fast hard courts and grass where the low bounce extends pace through impact. On clay the bounce absorbs pace and the flat trajectory's thin margin for net clearance increases double-fault risk.",
        "magnitude": "A flat-serve rate above 55% on first deliveries above 200 km/h generates approximately 3-4 extra free points per service game relative to a spin-dominant first-serve approach.",
        "links": ["first_serve_placement_origin", "slice_serve_origination", "kick_serve_origination", "first_strike_pattern_origin"],
    },
    {
        "slug": "slice_serve_origination",
        "title": "Slice-Serve Origination",
        "summary": "Point initiation with a low-skidding sidespin delivery — measured by slice-serve frequency and the lateral pull it exerts on the returner, dragging them off the court at the point of origination.",
        "stat_signature": "Slice-serve rate above 40% on first serves marks a lateral-displacement strategy. Wide ad-side slice ace rate typically 1.5-2.5pp higher than flat serves at the same speed due to geometric angle. Lateral displacement above 1.5 m off the court is the mechanical threshold for open-court plus-one creation.",
        "mechanism": "A slice serve's sidespin produces lateral movement after the bounce, pulling the returner off the court and creating an open lane for the server's first groundstroke. On grass the low skid amplifies the lateral pull; on clay the bite is reduced but the angle remains effective.",
        "conditions": "Slice serves are most laterally effective on grass and fast hard courts where bounce height is low and the skid extends lateral run. Against left-handed servers on the ad side, the angle to the right-hander's backhand is structurally exaggerated.",
        "magnitude": "A slice serve that displaces the returner above 1.5 m off the court creates an opened space that translates to a ~6-8pp higher winner rate on the subsequent plus-one shot.",
        "links": ["flat_serve_origination", "kick_serve_origination", "deuce_court_serve_origin", "serve_location_to_open_court"],
    },
    {
        "slug": "serve_and_volley_origin",
        "title": "Serve-and-Volley Origination",
        "summary": "Points the server originates by following the delivery forward to net — measured by serve-and-volley frequency, first-volley contact height, and the conversion rate from that approach origin.",
        "stat_signature": "Serve-and-volley rate above 15% per service game marks a committed net-attack initiator. First-volley conversion rate above 68% is the structural viability threshold. Serve-and-volley frequency above 25% on second serves identifies an aggressive risk-distribution strategy.",
        "mechanism": "Following the serve to net eliminates the rally construction phase and forces the returner to pass immediately under time pressure; the first volley's depth and angle determine whether the approach converts or exposes the server to a passing winner.",
        "conditions": "Most effective on grass and fast hard courts where the low bounce limits the returner's dip passing opportunity. Least effective on clay where the high bounce creates angled low-dipping passes that make first volleys mechanically awkward.",
        "magnitude": "A serve-and-volley conversion rate above 70% over 15+ approaches per set generates approximately 2-3 structurally earned points beyond a baseline-only service strategy.",
        "links": ["first_serve_placement_origin", "flat_serve_origination", "first_strike_pattern_origin", "serve_plus_one_origin"],
    },
    {
        "slug": "second_serve_attack_origin",
        "title": "Second-Serve-Attack Origination",
        "summary": "Rally starts where the returner steps in to originate aggression against a slower second delivery — measured by step-in attack frequency, return-depth from the attack stance, and the immediate court-position gain it yields.",
        "stat_signature": "Second-serve attack return rate above 40% marks an aggressive intent pattern. Inside-baseline contact on second-serve attacks above 45% confirms stance aggression. Second-serve return points won above 55% is the structural threshold separating attacking returners from passive ones.",
        "mechanism": "Stepping inside the baseline on a second serve shortens the ball's travel time between return and server by 0.2-0.3 s, turning a slower delivery into a time-pressure exchange. Consistent execution forces servers to increase second-serve pace or placement risk, raising double-fault probability.",
        "conditions": "Step-in attack most effective against kick serves below 150 km/h. On grass the lower kick bounce makes step-in contact more reliable. Against very high-bouncing clay kicks the step-in contact zone rises above the comfortable strike zone and reduces attacking precision.",
        "magnitude": "A second-serve attack stance above 40% rate combined with 55%+ return points won on second serves corresponds to approximately 4-5 additional points per service game imposed through return-origination dominance.",
        "links": ["return_position_origin", "return_depth_origination", "kick_serve_origination", "return_target_seam_origin"],
    },
    {
        "slug": "serve_location_to_open_court",
        "title": "Serve-Location-to-Open-Court Origination",
        "summary": "The systematic link between serve placement direction and the open-court angle it creates — quantified by the correlation between wide serves and the subsequent cross-court plus-one finishing geometry it enables.",
        "stat_signature": "Wide-serve open-court exploitation rate (serve wide, plus-one cross-court winner or forced error) above 35% marks a scheme-coherent initiator. Correlation between wide-serve rate and cross-court plus-one rate above r = 0.55 confirms co-designed pattern execution.",
        "mechanism": "A wide serve displaces the returner laterally; a scripted cross-court plus-one to the vacated space converts the geometric opening into point termination without requiring a rally. The serve and the plus-one function as a single geometric unit rather than independent decisions.",
        "conditions": "Exploitation rate is highest when the first serve lands in — second-serve wide placements carry reduced lateral displacement and narrower open-court angles. Against returners who redirect down-the-line on the run, the opened cross-court space closes.",
        "magnitude": "A wide-serve open-court exploitation rate above 38% contributes approximately 3-4 additional service-game points per set through serve-plus-one geometric design versus an unstructured placement approach.",
        "links": ["first_serve_placement_origin", "serve_plus_one_origin", "deuce_court_serve_origin", "ad_court_serve_origin"],
    },
    {
        "slug": "tiebreak_serve_origination",
        "title": "Tiebreak Serve Origination",
        "summary": "Point-origination tendencies under the alternating-serve tiebreak format — measured by first-serve-in rate change in the tiebreak, placement-conservatism shift, and pace-versus-placement trade-off adjustment relative to set-play baselines.",
        "stat_signature": "First-serve-in rate above 70% in tiebreaks versus a set-play baseline of 62-65% marks conservatism adoption. Ace rate in tiebreaks typically 1.5-2.5pp lower than in service games due to placement caution. Wide-serve rate in tiebreaks increases on average by ~4-6pp as servers target the safer lateral option.",
        "mechanism": "Tiebreak stakes raise the cost of double faults; servers typically shift toward a higher-margin placement pattern, accepting reduced pace for increased reliability. The alternating-serve structure creates asymmetric mini-break pressure that reinforces conservative initiation behaviour.",
        "conditions": "Conservatism shift is most pronounced from 5-5 onward in a tiebreak. Players with historically higher double-fault rates under pressure show larger first-serve-in adjustments. On fast surfaces the conservatism shift is partially offset by the inherent service advantage.",
        "magnitude": "A tiebreak first-serve-in rate above 70% combined with wide-serve conservatism reduces double-fault exposure by ~40% relative to set-play patterns, protecting the origination advantage on high-pressure points.",
        "links": ["first_serve_placement_origin", "game_opening_point_origin", "deuce_court_serve_origin", "ad_court_serve_origin"],
    },
    {
        "slug": "body_serve_origination",
        "title": "Body-Serve Origination",
        "summary": "Points initiated by jamming the serve at the returner's frame — quantified by body-serve frequency and the cramped weak-return rate it produces at the point of origination, suppressing the returner's angle repertoire.",
        "stat_signature": "Body-serve rate above 20% on first serves marks a jam-variety integrator. Cramped-return rate from body serves (return landing inside the service box or floating short) above 50% confirms effective execution. Body-serve jam rate above 25% on ad-court second serves is a second-delivery suppression signal.",
        "mechanism": "A serve directed at the body eliminates the returner's swing radius by forcing the racket back toward the torso; the resulting contact is a defensive redirect with reduced pace and direction control, creating a short or floating return that gifts the server an attackable third ball.",
        "conditions": "Most effective against returners with a wide take-back who cannot compact the swing arc quickly. On the deuce side a right-handed body serve jams the two-handed backhand; on the ad side it jams the forehand. Less effective against players with a compact contact-point style who absorb body serves with a short punch.",
        "magnitude": "A body-serve rate above 22% generating cramped returns at a 50%+ rate produces approximately 2-3 additional short-ball attack opportunities per service game.",
        "links": ["second_serve_initiation_pattern", "kick_serve_origination", "flat_serve_origination", "first_serve_placement_origin"],
    },
    {
        "slug": "return_target_seam_origin",
        "title": "Return-Target-Seam Origination",
        "summary": "The returner's directional intent at the point of origination — measured by the cross-court, down-the-line, and through-the-middle return distribution and the neutral-rally-entry rate each direction achieves.",
        "stat_signature": "Cross-court return dominance: above 65% of returns directed cross-court marks a safety-first entry pattern. Down-the-line return rate above 20% identifies a proactive seam-targeting originator. Through-middle return share above 15% indicates a neutralisation-first default strategy.",
        "mechanism": "Returning cross-court uses the longest court dimension and lowest net clearance, maximising margin; returning down-the-line requires greater precision but changes the rally's directional baseline and can catch the server out of position. Seam selection at the origination point determines which player enters the rally controlling the directional exchange.",
        "conditions": "Down-the-line return targeting is most effective early in a match before the server adapts their post-serve positioning. Against a T serve the down-the-line angle is geometrically shorter and higher-risk; the cross-court seam widens.",
        "magnitude": "A down-the-line return seam rate above 22% with an execution success rate above 65% corresponds to approximately 2-3 additional forced errors per set induced through directional variety at the origination point.",
        "links": ["return_depth_origination", "return_position_origin", "second_serve_attack_origin", "aggressive_block_return_origin"],
    },
]
