"""Person-free concept-node spec: Soccer / InitiationProfiles."""
from __future__ import annotations

SPORT = "Soccer"
FAMILY = "InitiationProfiles"

CONCEPTS: list[dict] = [
    {
        "slug": "goal_kick_build_up_origin",
        "title": "Goal-Kick Build-Up Origination",
        "summary": "Possessions originating from a goal kick split between short build-out and long launch; the short-versus-long ratio and the share that progress intact past the first defensive third define a side's distribution profile.",
        "stat_signature": "Short goal-kick share above 55 percent correlates with middle-third entry rate of 60-75 percent; long-kick sides post aerial-duel-win rates of 45-55 percent and second-ball recoveries determining possession continuity.",
        "mechanism": "The short build-out draws the opposition press upfield, creating space behind the press line if the sequence survives; the long launch bypasses the press but surrenders first-touch control, making the aerial contest and second-ball priority decisive.",
        "conditions": "Short-kick superiority materialises against passive or mid-block defences; against high-press teams, short sequences face turnover rates 20-30 percent higher unless the goalkeeper's distribution is accurate under pressure.",
        "magnitude": "Teams with first-defensive-third exit rates above 70 percent from short goal kicks generate 15-25 percent more controlled middle-third entries per 90 minutes than those relying on long launches.",
        "links": ["goalkeeper_distribution_initiation", "playing_out_under_press_origin", "deep_build_up_third_origin", "goalkeeper_long_launch_origin"],
    },
    {
        "slug": "goalkeeper_distribution_initiation",
        "title": "Goalkeeper Distribution Initiation",
        "summary": "The keeper's choice of distribution type — feet-based short pass, throw, or long kick — and the retention rate at the first receiving line characterise how build-up originates from restarts and open play.",
        "stat_signature": "Distribution-to-feet rate above 60 percent correlates with first-reception retention of 70-80 percent; throw retention is typically 75-85 percent over shorter distances; long-distribution retention at first contact averages 50-60 percent.",
        "mechanism": "Feet and throw distributions allow controlled tempo and positional structure; long distributions remove an outfield line from the sequence but buy time and territory when the back line is pressed high.",
        "conditions": "Feet-based distribution is feasible under organised defensive shapes; under intense pressing that reduces short-pass lanes, distribution accuracy falls 10-15 percent and keepers shift toward longer options.",
        "magnitude": "A 10-percentage-point increase in goalkeeper feet-distribution rate associates with roughly 8-12 additional controlled possessions per 90 entering the middle third without pressure.",
        "links": ["goal_kick_build_up_origin", "goalkeeper_long_launch_origin", "playing_out_under_press_origin", "center_back_first_pass_origin"],
    },
    {
        "slug": "center_back_first_pass_origin",
        "title": "Center-Back First-Pass Origination",
        "summary": "Possessions begun with the first progressive pass from a central defender quantify how often the initial ball-mover breaks the first line of opposition pressure from depth, measured by forward-pass share and line-break frequency.",
        "stat_signature": "Center-back first-pass forward share above 40 percent identifies progressive build-up systems; line-break frequency — passes bypassing at least one defensive line — of 15-25 percent per possession marks high-ambition origination.",
        "mechanism": "A center-back capable of carrying the ball into space or playing a diagonal over a pressing mid-line removes an opposition press unit from the sequence, creating immediate numerical advantage in the next zone.",
        "conditions": "Effective in possession-based systems where center-backs advance past the midfield engagement line; suppressed in low-block defensive setups where deep distribution to a forward is the primary out-ball.",
        "magnitude": "Teams with above-median center-back line-break frequency generate 10-18 percent more middle-third entries per 90 than those relying on lateral recycling before the first advance.",
        "links": ["deep_build_up_third_origin", "first_pass_progression_direction", "pivot_drop_receive_origin", "goalkeeper_distribution_initiation"],
    },
    {
        "slug": "deep_build_up_third_origin",
        "title": "Deep Build-Up Origination",
        "summary": "Sequences initiated from within the defensive third under active opposition pressure measure a side's willingness to play out from the back, captured by deep-build frequency and the success rate of progressing into the middle third.",
        "stat_signature": "Deep-build frequency above 35 possessions per 90 denotes a committed back-build style; progression success rate from the defensive third typically ranges from 55 to 75 percent depending on press intensity faced.",
        "mechanism": "Deep build-up tolerates early-phase risk to impose structure and tempo on subsequent phases; a retained deep sequence shifts opposition compactness upfield and creates exploitation pockets behind the press.",
        "conditions": "Profitable in technical systems with a high-skill distribution unit and clear press-escape triggers; dangerous for sides with below-average center-back passing accuracy, where turnover-in-own-third rates exceed 15-20 percent.",
        "magnitude": "Each percentage-point improvement in deep-build progression success translates to roughly 0.4-0.6 additional middle-third entries per 90, compounding over a full match.",
        "links": ["center_back_first_pass_origin", "playing_out_under_press_origin", "goal_kick_build_up_origin", "first_pass_progression_direction"],
    },
    {
        "slug": "first_pass_progression_direction",
        "title": "First-Pass Progression Direction",
        "summary": "The directional intent of the opening pass of a possession — forward, lateral, or backward — reveals a side's structural ambition and tempo at the moment of regaining the ball.",
        "stat_signature": "Forward first-pass share above 45 percent characterises direct-progression systems; possession-dominant systems average 30-40 percent forward with 35-45 percent lateral; backward first-pass rates above 20 percent signal high press-avoidance caution.",
        "mechanism": "The first-pass direction sets the structural frame for the entire possession; early vertical intent compresses defence before it sets, while early lateral recycling sacrifices tempo in exchange for positional stability.",
        "conditions": "Forward-first systems expose the first receiving line to immediate pressure; lateral-first systems require high positional discipline to prevent ceding space through over-recycling.",
        "magnitude": "A 10-percentage-point shift toward forward first-pass intent associates with 12-18 percent more possessions reaching the attacking third within four passes.",
        "links": ["center_back_first_pass_origin", "vertical_first_ball_into_forward", "regain_to_attack_transition_origin", "deep_build_up_third_origin"],
    },
    {
        "slug": "regain_to_attack_transition_origin",
        "title": "Regain-to-Attack Transition Origination",
        "summary": "Possessions originating the instant the ball is won back — particularly in high or central zones — measure a side's capacity to exploit defensive disorganisation before the opposition resets.",
        "stat_signature": "Time-to-first-forward-pass below five seconds after a regain in the opposition or central half identifies high-tempo transition sides; share of regains entering the final third within five seconds ranges from 8-18 percent across competitive leagues.",
        "mechanism": "A rapid first forward pass after a turnover catches defending lines mid-recovery, with larger spaces between defensive units; the structural advantage dissolves progressively as the defender count behind the ball resets over five to ten seconds.",
        "conditions": "Most effective when the regain occurs in the central or attacking half; deep-defensive-third regains against an organised low block reduce the time-advantage to near zero.",
        "magnitude": "Possessions converted to a forward pass within three seconds of a high regain produce shots at approximately twice the rate of possessions recycled for eight or more seconds before advancing.",
        "links": ["first_pass_progression_direction", "vertical_first_ball_into_forward", "third_man_release_initiation", "switch_of_play_origination"],
    },
    {
        "slug": "goalkeeper_long_launch_origin",
        "title": "Goalkeeper Long-Launch Origination",
        "summary": "Build-up bypassed by a long keeper launch to a target line characterises the direct-play initiation profile, measured by launch frequency and the aerial-duel-win rate at the first-contact zone.",
        "stat_signature": "Long-launch frequency above 25 per 90 identifies direct-play systems; aerial-duel-win rate at first contact of 50-58 percent determines whether second-ball zones are contested effectively.",
        "mechanism": "The long launch skips the build-up phase entirely, relocating the contest zone 40-60 yards upfield; the outcome depends almost entirely on the aerial duel and the second-ball organisation immediately after.",
        "conditions": "Effective against high-press teams whose back-line steps up, creating space behind for target-forward flick-ons; weakest against deep-block oppositions who absorb the aerial contest with numerical superiority.",
        "magnitude": "Teams winning above 52 percent of first-contact aerials from long launches recover second balls at a rate 20-30 percent higher than those below 48 percent, directly determining possession continuity.",
        "links": ["goal_kick_build_up_origin", "goalkeeper_distribution_initiation", "vertical_first_ball_into_forward", "penalty_box_clearance_to_origin"],
    },
    {
        "slug": "pivot_drop_receive_origin",
        "title": "Pivot Drop-and-Receive Origination",
        "summary": "Build-up initiated by a defensive midfielder dropping between the center-backs to receive the first ball out of defence creates numerical overloads against the first pressing line and shapes the whole origination structure.",
        "stat_signature": "Drop-receive frequency above 18 actions per 90 identifies pivot-anchored build-up; turn-and-advance rate — pivots receiving and playing forward within two touches — above 55 percent characterises high efficiency.",
        "mechanism": "The dropping pivot creates a three-on-two against a two-forward press, allowing the goalkeeper and center-backs to recycle safely; if the pivot can turn and advance, a direct vertical lane opens before the midfield press re-engages.",
        "conditions": "Effective when the pivot has sufficient spatial awareness to pre-scan and turn under pressure; negated by aggressive press triggers that mark the drop receiver tightly and limit turn-angles.",
        "magnitude": "Possession sequences with a successful pivot drop-receive progress to the middle third at 65-75 percent versus 45-55 percent for sequences that bypass the pivot structure entirely.",
        "links": ["center_back_first_pass_origin", "deep_build_up_third_origin", "playing_out_under_press_origin", "third_man_release_initiation"],
    },
    {
        "slug": "throw_in_restart_initiation",
        "title": "Throw-In Restart Initiation",
        "summary": "Possessions originated from a throw-in vary systematically by pitch third, with throw-in retention rate and the frequency of building immediate forward momentum defining the restart quality profile.",
        "stat_signature": "Throw-in retention above 70 percent across all thirds is achievable; attacking-third throws generate shots within three passes at roughly 8-12 percent; defensive-third throw-in turnovers above 20 percent signal high structural risk.",
        "mechanism": "Throw-ins allow deliberate positioning and movement before the restart; sides with structured throw-in routines create pre-planned receiving combinations that break the immediate press before it organises.",
        "conditions": "Routine-based throw-in advantage peaks against press-heavy opponents who commit numbers to the ball; against passive defensive structures, unpatterned throws still achieve moderate retention.",
        "magnitude": "Sides with structured throw-in routines retain possession on 10-15 percent more attacking-third throws and convert those possessions into dangerous actions at approximately 1.5 times the rate of unstructured restarts.",
        "links": ["free_kick_restart_origin", "set_piece_short_routine_origin", "press_resistance_first_touch_origin", "first_pass_progression_direction"],
    },
    {
        "slug": "playing_out_under_press_origin",
        "title": "Playing-Out-Under-Press Origination",
        "summary": "Build-up originating against an active high press quantifies a side's ability to escape organised pressure from the back, measured by press-escape-pass success rate and turnover frequency inside the defensive third.",
        "stat_signature": "Press-escape rate above 60 percent identifies reliable build-out sides; turnover-inside-defensive-third rates above 18 per 90 indicate structural vulnerability to high-press systems.",
        "mechanism": "Escaping a high press requires pre-planned rotations, rapid ball-circulation, and at least one spare player in a lane not covered by the press — structural conditions that must be drilled and conditioned rather than improvised.",
        "conditions": "Most decisive in fixtures against high-press opponents pressing above 40 percent of opposition possessions; negligible in mid-block or low-block match-up contexts where the press trigger is rare.",
        "magnitude": "A 10-percentage-point improvement in press-escape rate associates with approximately 6-10 fewer defensive-third turnovers per 90, directly reducing dangerous concession-chance exposure.",
        "links": ["deep_build_up_third_origin", "goal_kick_build_up_origin", "press_resistance_first_touch_origin", "pivot_drop_receive_origin"],
    },
    {
        "slug": "third_man_release_initiation",
        "title": "Third-Man Release Initiation",
        "summary": "Possessions advanced at origin via a bounce to a pre-running third player create a line-break in the opening sequence before the defence has time to organise, capturing the efficiency of combination build-up.",
        "stat_signature": "Third-man combination frequency above 12 per 90 marks systematic exploitation; line-break rate through the combination of 30-45 percent indicates the tactic creates meaningful positional advancement.",
        "mechanism": "The first player draws a press trigger, the second acts as a relay to shift the ball quickly, and the third — already in motion — receives beyond the press line; the success depends on the pre-run timing preceding the first touch.",
        "conditions": "Works best against press systems that commit the first presser aggressively; against organised man-marking or zonal mid-blocks, the third runner is tracked and the combination is neutralised.",
        "magnitude": "Possessions featuring a successful third-man release reach the final third within five passes at 35-50 percent versus 15-22 percent for sequences without this combination structure.",
        "links": ["regain_to_attack_transition_origin", "pivot_drop_receive_origin", "wide_full_back_initiation", "first_pass_progression_direction"],
    },
    {
        "slug": "wide_full_back_initiation",
        "title": "Wide Full-Back Initiation",
        "summary": "Possessions initiated by releasing the first progressive ball into advancing wide defenders establish early width and stretch the opposition shape before the ball reaches more advanced receivers.",
        "stat_signature": "Full-back first-reception frequency above 20 percent of all possessions signals a wide-initiation structure; width created at first reception — measured as horizontal field coverage at the reception moment — averages 60-70 percent of pitch width in these systems.",
        "mechanism": "A wide-full-back receiving high and early forces the opposition winger to track back, taking one press unit out of the central block and opening interior passing lanes for subsequent combination play.",
        "conditions": "Effective against oppositions with narrow midfield presses that leave wide zones open; neutralised by low-block defences that concede wide ball while condensing central spaces.",
        "magnitude": "Possessions entering through a wide full-back at depth shift subsequent chances into crossing and cutback positions, increasing the shot-generation rate per possession by 15-25 percent relative to centrally-initiated possessions.",
        "links": ["switch_of_play_origination", "regain_to_attack_transition_origin", "third_man_release_initiation", "first_pass_progression_direction"],
    },
    {
        "slug": "vertical_first_ball_into_forward",
        "title": "Vertical First-Ball Into Forward",
        "summary": "Origination that skips intermediate build-up by playing directly into a forward's feet or chest quantifies the direct-entry profile, with lay-off retention rate determining whether the possession survives the first contact.",
        "stat_signature": "Direct-entry frequency above 18 per 90 characterises direct-play systems; lay-off first-touch retention above 60 percent is required for the tactic to generate continuing possession rather than loose-ball contests.",
        "mechanism": "Playing over the midfield line early exploits a momentary gap before the opposition defensive line drops; if the forward retains and lays off, the receiving midfielder arrives at the ball facing forward with space to advance.",
        "conditions": "Most effective against high defensive lines that leave long gaps between midfield and the back four; weakest against compact mid-blocks with no separation between lines for the vertical first ball to exploit.",
        "magnitude": "Vertical first balls that succeed in retention generate an attacking-third entry within three passes at 40-55 percent, roughly 1.8 times the rate of equivalent possessions recycled through lateral build-up.",
        "links": ["regain_to_attack_transition_origin", "goalkeeper_long_launch_origin", "first_pass_progression_direction", "third_man_release_initiation"],
    },
    {
        "slug": "switch_of_play_origination",
        "title": "Switch-of-Play Origination",
        "summary": "Possessions that begin their progression with an early cross-field switch stretch the opposition shape at the earliest phase, measured by first-phase switch frequency and the one-against-one width created on the far side.",
        "stat_signature": "First-phase switch frequency above 8 per 90 identifies systematic width-shifting; the proportion of switches creating a one-against-one situation on the far touchline ranges from 30-50 percent depending on opposition compactness.",
        "mechanism": "An early switch of play forces the defence to slide its entire shape laterally before settling; the time lag between the ball arriving and full defensive realignment creates an exploitable window on the far side.",
        "conditions": "Most effective against compact narrow presses or defences biased toward one flank; less effective against well-structured flat-back-four units with disciplined slide speed.",
        "magnitude": "Possessions including an early switch create wide one-against-one situations at 35-50 percent frequency; those one-against-ones convert to crosses or cut-inside attempts at roughly double the rate of non-switch wide entries.",
        "links": ["wide_full_back_initiation", "first_pass_progression_direction", "third_man_release_initiation", "regain_to_attack_transition_origin"],
    },
    {
        "slug": "set_piece_short_routine_origin",
        "title": "Set-Piece Short-Routine Origination",
        "summary": "Possessions originated from a short, worked set-piece routine rather than a direct delivery quantify a side's use of dead-ball restarts to create positional advantages through movement and combination.",
        "stat_signature": "Short-routine frequency above 30 percent of non-shooting set pieces identifies a pattern-oriented restart approach; progression-into-final-third rate from short routines ranges from 35-55 percent versus 15-25 percent from cleared direct deliveries.",
        "mechanism": "A short routine disrupts the numerical organisation of a set-piece defensive block, drawing defenders toward the ball-near zone while creating runs into vacated space; the extra pass resets the defensive shape as an open-play sequence.",
        "conditions": "Effective when the defensive set-piece structure is high-line and man-oriented; less effective against deep zonal blocks that absorb the routine and recover compactness before the ball advances.",
        "magnitude": "Short-routine sequences reaching the final third yield a shot every 3-5 possessions compared with one shot every 8-12 from cleared direct deliveries of equivalent set-piece type.",
        "links": ["throw_in_restart_initiation", "free_kick_restart_origin", "corner_won_second_phase_origin", "press_resistance_first_touch_origin"],
    },
    {
        "slug": "press_resistance_first_touch_origin",
        "title": "Press-Resistance First-Touch Origination",
        "summary": "How the first receiving touch under immediate pressure shapes origination quality, measured by the receive-and-retain rate and turnover-at-origin frequency across all possession types.",
        "stat_signature": "First-touch retention rate under pressure above 75 percent identifies technically robust origination; turnover-at-origin rates above 12 per 90 across all possession starts indicate a structural first-touch vulnerability to press triggers.",
        "mechanism": "A clean first touch — shielded, screened, or played off quickly — neutralises the immediate press trigger and allows the originating player to set the direction of the next pass before pressure arrives at the second line.",
        "conditions": "Critical in high-press match-ups where the opposition applies the first challenge within one to two seconds of the ball reaching the receiver; largely invisible against passive mid-blocks where the first touch is uncontested.",
        "magnitude": "A 5-percentage-point improvement in first-touch retention under pressure correlates with 4-7 fewer turnovers per 90 in the defensive and middle thirds, reducing high-danger counterattack exposure proportionally.",
        "links": ["playing_out_under_press_origin", "throw_in_restart_initiation", "set_piece_short_routine_origin", "deep_build_up_third_origin"],
    },
    {
        "slug": "penalty_box_clearance_to_origin",
        "title": "Clearance-Recovery Origination",
        "summary": "Possessions that originate by recovering a defensive clearance in the middle third represent a second-ball contest for possession; the second-ball-win rate and immediate forward-progression frequency define this origination class.",
        "stat_signature": "Second-ball-win rate above 52 percent from defensive-clearance duels generates a possession advantage; immediate forward progression within two seconds of winning the second ball occurs at 35-50 percent frequency for high-tempo sides.",
        "mechanism": "Defensive clearances create contested aerial or rolling balls with both teams in mid-reorganisation; the side that wins the second ball can exploit the brief period before either defensive structure resets.",
        "conditions": "Second-ball value peaks against sides that defend with high-line out-of-possession pressure, leaving larger spaces behind the defensive line after a clearance; absorbed by deeper blocks that retreat and reorganise before the second ball lands.",
        "magnitude": "Teams winning above 50 percent of second balls from opposition clearances initiate attacking sequences from these situations at 1.3 to 1.6 times the rate of sides below 48 percent, compounding across a high-clearance match.",
        "links": ["goalkeeper_long_launch_origin", "corner_won_second_phase_origin", "regain_to_attack_transition_origin", "first_pass_progression_direction"],
    },
    {
        "slug": "corner_won_second_phase_origin",
        "title": "Corner Second-Phase Origination",
        "summary": "Open-play possessions that originate from the second phase after a corner is cleared measure the capacity to recycle a set-piece situation into a renewed attack, captured by recycle-retention rate and re-entry frequency into the box.",
        "stat_signature": "Second-phase retention from cleared corners above 55 percent generates a renewed attack sequence; re-entry into the penalty box on the recycled possession occurs at 18-30 percent frequency for organised second-phase systems.",
        "mechanism": "As defenders clear a corner delivery, their positioning transitions from organised set-piece marking to reactive recovery; a team structured with second-phase runners at the edge of the box arrives at the ball in a forward-facing position before the defence fully resets.",
        "conditions": "Most effective against tall defensive set-piece teams that commit headers high and leave the penalty-box periphery momentarily sparse; less effective against low-block sides that absorb and retain compact shape after clearing.",
        "magnitude": "Organised second-phase recycling generates a shot within two further passes at 20-30 percent, compared with 8-12 percent for unstructured corner second-ball recovery.",
        "links": ["set_piece_short_routine_origin", "penalty_box_clearance_to_origin", "free_kick_restart_origin", "press_resistance_first_touch_origin"],
    },
]
