"""Tennis / LeadManagement — person-free concept-node spec."""
from __future__ import annotations

SPORT = "Tennis"
FAMILY = "LeadManagement"

CONCEPTS: list[dict] = [
    {
        "slug": "break_consolidation_hold",
        "title": "Break-Consolidation Hold",
        "summary": "Hold-rate in the service game immediately after a break versus baseline hold-rate, measuring how reliably a gained break converts to a two-game cushion.",
        "stat_signature": "Post-break hold rate minus overall hold rate; typical spread 3–9 pp; segmented by set-score state and surface.",
        "mechanism": "Emotional reset and tactical refocus after break-point exertion; players who re-anchor pre-serve routine show consolidation rates near baseline; those who relax drop measurably.",
        "conditions": "Amplified on slow surfaces where server advantage is lower and returner retains momentum; strongest at 1-0 and 2-1 leads.",
        "magnitude": "Top-quartile consolidators hold 5–10 pp above baseline; bottom-quartile players dip 4–7 pp, meaningfully shifting expected set-win probability.",
        "links": ["post_break_letdown_vulnerability", "consolidation_first_point_priority", "front_running_momentum_retention", "set_closing_clutch_point_conversion"],
    },
    {
        "slug": "post_break_letdown_vulnerability",
        "title": "Post-Break Letdown Vulnerability",
        "summary": "Conditional rebreak probability in the game following a break gain, quantifying the immediate reversal risk before a cushion is secured.",
        "stat_signature": "Rebreak rate in game N+1 after break versus unconditional service-loss rate; conditional rebreak range 18–30 % tour-wide.",
        "mechanism": "Overconfidence lowers first-serve aggression; the energized returner elevates depth and break-point conversion, creating a narrow but recurring reversal window.",
        "conditions": "Stronger on fast surfaces; more frequent in set 2 after a first-set win; sharpest when the break was earned via a long sequence rather than a short error run.",
        "magnitude": "High-letdown players rebreak at 1.4–1.8x the unconditional rate; effect dissipates once the consolidation game is secured.",
        "links": ["break_consolidation_hold", "break_back_recovery_after_loss", "consolidation_first_point_priority", "lead_state_error_discipline"],
    },
    {
        "slug": "serving_for_set_pressure_profile",
        "title": "Serving-for-the-Set Pressure Profile",
        "summary": "Hold rate and first-serve quality specifically when serving to close a set, isolating execution under a discrete high-stakes service game.",
        "stat_signature": "Hold rate and first-serve-in rate in serving-for-set games versus all other service games; double-fault and ace rates; first-opportunity set-point conversion.",
        "mechanism": "Finite-stakes pressure concentrates decision noise; players who compress serve pattern toward body serves and wider seconds raise first-serve percentage and cut double faults.",
        "conditions": "Amplified in deciding sets and best-of-five; more variable on slow surfaces where the returner's upside is higher.",
        "magnitude": "Top closers hold 3–7 pp above baseline in these games; vulnerable players drop 5–12 pp with double-fault rates spiking 30–50 %.",
        "links": ["set_closing_clutch_point_conversion", "lead_protection_first_serve_reliance", "lead_state_serve_placement_conservatism"],
    },
    {
        "slug": "double_break_cushion_management",
        "title": "Double-Break Cushion Management",
        "summary": "Statistical behavior once a two-break cushion is established, distinguishing sustained controlled pressure from passive error accumulation.",
        "stat_signature": "Points-per-game, unforced-error rate, and first-serve percentage when leading by two-plus breaks versus single-break baseline; break-points-faced frequency shift.",
        "mechanism": "Commanding cushion removes immediate break-point survival imperative; players who maintain tactical pressure lock in higher set-win rates than those who coast.",
        "conditions": "Occurs in early-set phases; more consequential in best-of-three; individual temperament and tactical discipline dominate surface effects.",
        "magnitude": "Players holding first-serve within 3 pp of baseline while up two breaks allow 15–25 % fewer break-point opportunities than those whose error rates climb 10 %+.",
        "links": ["lead_state_error_discipline", "service_game_speed_protection", "two_sets_to_love_cushion_behavior", "scoreboard_pressure_transfer"],
    },
    {
        "slug": "lead_protection_first_serve_reliance",
        "title": "Lead-Protection First-Serve Reliance",
        "summary": "Degree to which a player raises first-serve percentage while ahead, reducing second-serve exposure by targeting high-percentage zones under scoreboard pressure.",
        "stat_signature": "First-serve-in rate while leading one-plus breaks versus level; second-serve frequency and points-won rate; typical first-serve uplift 3–8 pp in lead states.",
        "mechanism": "Risk asymmetry shifts ahead: the cost of a double fault or vulnerable second serve exceeds the gain from a high-risk first serve winner, so selection compresses toward body serves.",
        "conditions": "Most measurable at 30–40 and deuce; stronger on fast surfaces where the second-serve disadvantage is largest.",
        "magnitude": "A 5+ pp first-serve-in uplift while ahead correlates with a 3–5 pp hold-rate improvement over predicted hold probability.",
        "links": ["lead_state_serve_placement_conservatism", "lead_state_second_serve_protection", "set_lead_serve_assertiveness", "serving_for_set_pressure_profile"],
    },
    {
        "slug": "set_lead_serve_assertiveness",
        "title": "Set-Lead Serve Assertiveness",
        "summary": "Captures serve-aggression changes while protecting a set lead, measuring first-serve percentage, ace rate, and serve-plus-one win rate by set-score state.",
        "stat_signature": "Ace rate and serve-plus-one win rate by set-score state (up 2-1, 3-1, 4-2); first-serve speed percentile shift from level versus lead states.",
        "mechanism": "Some players raise aggression to close out sets quickly, reducing opponent rhythm; others conserve risk, producing measurable serve-speed or placement-entropy divergence from their neutral baseline.",
        "conditions": "Most diagnostic when leading by one break with a slow-surface opponent who thrives in longer rallies; best-of-five amplifies the pattern across multiple lead states.",
        "magnitude": "Assertive servers gain 1–2 pp on first-serve win rate in lead states; conservative servers trade that for a 4–6 pp reduction in double-fault frequency.",
        "links": ["lead_protection_first_serve_reliance", "serving_for_set_pressure_profile", "lead_state_serve_placement_conservatism"],
    },
    {
        "slug": "margin_state_return_aggression",
        "title": "Margin-State Return Aggression",
        "summary": "Return-game risk appetite when already holding a scoreboard advantage, distinguishing break-pressing strategies from error-minimizing returns.",
        "stat_signature": "Return depth score, first-return-in-play rate, and return-points-won rate by break and set margin state; winner-to-unforced-error ratio on return side by lead magnitude.",
        "mechanism": "When ahead, the net expected value of a high-risk return falls because a held serve still preserves the lead; conservative returners prioritize rally entry and harvest opponent errors.",
        "conditions": "Clearest on slow surfaces where return depth has a larger rally effect; strongest at one-break and two-break margins; resets at level scores.",
        "magnitude": "Return aggression index drops 8–15 % in one-break-lead states for margin-conservative players, correlating with 4–6 pp fewer unforced return errors per game.",
        "links": ["lead_state_rally_tempo_control", "scoreboard_pressure_transfer", "front_running_momentum_retention", "lead_state_error_discipline"],
    },
    {
        "slug": "front_running_momentum_retention",
        "title": "Front-Running Momentum Retention",
        "summary": "Persistence of game-winning and point-winning streaks once a lead is established, measuring how reliably early scoreboard advantages compound into extended runs.",
        "stat_signature": "Average consecutive-games-won streak while ahead; time to opponent's first game win after a break is taken; point-streak duration during service holds in lead states.",
        "mechanism": "A scoreboard lead concentrates opponent errors through psychological pressure while allowing the leader to operate within a tested tactical framework without deviation.",
        "conditions": "Strongest on slow surfaces; evident in players with stable first-serve percentages who do not deviate from their game plan under lead conditions.",
        "magnitude": "Top-quartile front-runners extend consecutive-game streaks by 1.5–2.5 games before the opponent's next hold; set-win probability per break held rises 8–15 pp.",
        "links": ["break_consolidation_hold", "double_break_cushion_management", "scoreboard_pressure_transfer", "set_closing_clutch_point_conversion"],
    },
    {
        "slug": "lead_state_error_discipline",
        "title": "Lead-State Error Discipline",
        "summary": "Unforced-error control and rally-length tolerance while protecting an advantage, measuring the cost of tactical relaxation after securing a break.",
        "stat_signature": "Unforced-error rate per game by lead magnitude; average rally length in lead states versus level-score baseline; error rate on high-percentage shots by set score.",
        "mechanism": "Reduced neurological arousal once a lead registers as safe lowers fine-motor precision; players who override this with deliberate process cues maintain rally quality through lead states.",
        "conditions": "Most measurable in games 2–3 after consolidation and again approaching set-closing; surface-independent but amplified on courts rewarding first-strike tactics.",
        "magnitude": "Poor lead-state discipline produces 20–35 % more unforced errors per game while leading; elite-discipline players show less than 5 % uplift over baseline.",
        "links": ["double_break_cushion_management", "post_break_letdown_vulnerability", "lead_state_rally_tempo_control", "margin_state_return_aggression"],
    },
    {
        "slug": "set_closing_clutch_point_conversion",
        "title": "Set-Closing Clutch-Point Conversion",
        "summary": "Set-point conversion rate on first opportunity and the ability to save opponent set points while leading, isolating execution quality at the highest-leverage moments of a set.",
        "stat_signature": "First-opportunity set-point conversion rate; opponent set-point save rate while ahead; break-point save rate in serving-for-set games; first-serve percentage at set point.",
        "mechanism": "Set points spike cognitive load; players relying on pattern repetition and pre-serve routine show higher first-opportunity conversion than those who deviate tactically under pressure.",
        "conditions": "More pronounced in best-of-five; faster surfaces amplify set-point importance because a hold converts more directly to a set win.",
        "magnitude": "First-opportunity conversion varies 58–72 % tour-wide; players converting 68 %+ win sets 10–15 pp more often than those consistently requiring multiple set points.",
        "links": ["serving_for_set_pressure_profile", "break_consolidation_hold", "front_running_momentum_retention", "lead_state_serve_placement_conservatism"],
    },
    {
        "slug": "break_back_recovery_after_loss",
        "title": "Break-Back Recovery After Loss",
        "summary": "Speed and reliability with which a player re-establishes a break advantage after being broken back to level, measuring resilience after a lead is surrendered.",
        "stat_signature": "Re-break rate in the two service games following a lost break lead versus baseline break-point conversion rate; hold stability in the games immediately after the rebreak.",
        "mechanism": "A rebreak is a high-volatility emotional event; players with strong recovery profiles reset tactical patience quickly, while fragile responders show cascading errors and reduced first-serve percentage.",
        "conditions": "Most diagnostic in deciding sets; amplified on slow surfaces where break opportunities are frequent; strongest when the rebreak came via an opponent run rather than a single error.",
        "magnitude": "Strong recovery profiles re-break within two service games at 25–35 % above baseline; weak profiles experience a 2–4 game drought of break opportunities.",
        "links": ["post_break_letdown_vulnerability", "break_consolidation_hold", "lead_state_error_discipline", "front_running_momentum_retention"],
    },
    {
        "slug": "service_game_speed_protection",
        "title": "Service-Game Speed Protection",
        "summary": "Efficient, low-variance service holds used to protect a lead, measured by points-per-game and time-per-game while leading, limiting the opponent's rhythm-building windows.",
        "stat_signature": "Average points per service game and time per service game by lead state; rate of holds in four points or fewer; ace plus unreturnable-serve rate by lead magnitude.",
        "mechanism": "Short games deny opponent rhythm time and conserve leader resources; high first-serve percentage with targeted placement produces more four-point holds than deuce-heavy sequences.",
        "conditions": "Most impactful on fast surfaces; relevant in long matches for physical conservation; effects strengthen against return-heavy opponents who benefit from extended rallies.",
        "magnitude": "Four-point holds occur at 45–60 % for dominant servers while leading versus 30–45 % at level; each four-point hold reduces game time by roughly 30–45 seconds.",
        "links": ["lead_protection_first_serve_reliance", "lead_state_rally_tempo_control", "double_break_cushion_management", "running_down_set_clock_pace"],
    },
    {
        "slug": "two_sets_to_love_cushion_behavior",
        "title": "Two-Sets Cushion Behavior",
        "summary": "Statistical shifts once a commanding multi-set lead is established, distinguishing players who sustain intensity from those who regress toward passive error accumulation.",
        "stat_signature": "Per-set hold rate and unforced-error rate in set 3 of best-of-three or sets 3–5 of best-of-five when leading 2–0; double-fault rate change versus sets 1–2 baseline.",
        "mechanism": "A two-set lead reduces perceived cost of losing a game; cognitive comfort reduces first-serve urgency and rally focus, which disciplined opponents exploit to build momentum.",
        "conditions": "Exclusively relevant in multi-set formats; amplified in best-of-five where physical fatigue compounds; more frequent when the two-set lead was built against strong resistance.",
        "magnitude": "Marked cushion-behavior drops produce 15–25 % unforced-error rate increases in set 3; hold rate can fall 6–10 pp, enabling opponents to steal sets above their season-average frequency.",
        "links": ["double_break_cushion_management", "lead_state_error_discipline", "scoreboard_pressure_transfer", "break_back_recovery_after_loss"],
    },
    {
        "slug": "scoreboard_pressure_transfer",
        "title": "Scoreboard-Pressure Transfer",
        "summary": "Degree to which holding a lead increases the trailing opponent's error rate and break-point-faced frequency without any increase in the leader's active aggression.",
        "stat_signature": "Opponent unforced-error rate by margin state; opponent break-points-faced frequency when trailing by one or two breaks; opponent first-serve percentage decline by set deficit.",
        "mechanism": "Deficit triggers threat-response cognition in the trailer, compressing shot selection toward low-percentage risks and raising double-fault and net-error rates structurally.",
        "conditions": "Strongest against pressure-sensitive opponents; amplified on slow surfaces where the path back from a deficit requires sustained return aggression.",
        "magnitude": "Opponents trailing one break show 10–20 % unforced-error increases; trailing two breaks pushes to 20–35 %; this accounts for 30–50 % of observed break-rate asymmetry by margin.",
        "links": ["front_running_momentum_retention", "two_sets_to_love_cushion_behavior", "double_break_cushion_management", "margin_state_return_aggression"],
    },
    {
        "slug": "consolidation_first_point_priority",
        "title": "Consolidation First-Point Priority",
        "summary": "Disproportionate importance of winning the first point of the consolidation service game, anchoring early control of a hold that secures the break advantage.",
        "stat_signature": "Consolidation hold rate conditional on first-point outcome; first-serve-in rate on point 1 of consolidation games; comparison with first-point outcome effects in neutral service games.",
        "mechanism": "The first point anchors framing for both players; a won first point reinforces the server's authority while the energy-depleted returner faces an uphill 0–15 deficit immediately.",
        "conditions": "Amplified on fast surfaces where first-point serve quality most directly determines game outcome; strongest early in sets before both players establish a rallying rhythm.",
        "magnitude": "Conditional on first point won, consolidation hold rates run 8–14 pp above the unconditional rate; on first point lost, the hold rate can revert near the neutral hold baseline.",
        "links": ["break_consolidation_hold", "post_break_letdown_vulnerability", "lead_protection_first_serve_reliance", "service_game_speed_protection"],
    },
    {
        "slug": "lead_state_serve_placement_conservatism",
        "title": "Lead-State Serve-Placement Conservatism",
        "summary": "Shift toward higher-percentage serve targets while protecting a lead, measured by serve-location entropy and body-serve utilization rate in lead states.",
        "stat_signature": "Serve-location entropy across T, body, and wide zones by lead state; body-serve rate delta from level to lead; serve speed differential between lead and neutral states.",
        "mechanism": "Variance reduction dominates expected-value maximization when ahead: body serves and mid-range wide serves reduce returner angle options at a small cost to ace probability.",
        "conditions": "Strongest on fast surfaces where placement is the primary point-ending mechanism; tighter placement clusters appear at one-break and two-break leads.",
        "magnitude": "Body-serve rate increases 8–15 pp in lead states for conservative servers; entropy drops 0.10–0.18 bits; first-serve-in rate rises 3–6 pp, yielding a 2–4 pp hold-rate uplift.",
        "links": ["lead_protection_first_serve_reliance", "serving_for_set_pressure_profile", "lead_state_second_serve_protection"],
    },
    {
        "slug": "lead_state_second_serve_protection",
        "title": "Lead-State Second-Serve Protection",
        "summary": "Protection of the vulnerable second serve while holding an advantage, measuring double-fault rate and second-serve points-won rate by lead state.",
        "stat_signature": "Double-fault rate and second-serve points-won rate in lead states versus level-score baseline; second-serve speed and placement entropy by lead magnitude; double-fault share of break points conceded while ahead.",
        "mechanism": "While ahead, a double fault carries disproportionate psychological weight; players who tighten second-serve placement and reduce speed variance avoid the double-fault spikes that trail poorer lead managers.",
        "conditions": "Amplified on fast surfaces where double faults cost points directly; most consequential at deuce and 30–40 in consolidation games.",
        "magnitude": "Strong lead-state second-serve protectors hold double-fault rate within 1 pp of baseline; fragile servers double-fault at 1.4–1.8x baseline, contributing 15–25 % of break points conceded while leading.",
        "links": ["lead_protection_first_serve_reliance", "lead_state_serve_placement_conservatism", "break_consolidation_hold"],
    },
]
