"""NBA LeadManagement spec — dense, person-free. See specs/__init__.py for contract."""
from __future__ import annotations

SPORT = "NBA"
FAMILY = "LeadManagement"

CONCEPTS: list[dict] = [
    {"slug": "lead_protection_tempo_modulation", "title": "Lead-Protection Tempo Modulation",
     "summary": "Teams deliberately extend seconds-per-possession and increase late-shot-clock usage once a cushion forms, shrinking the opponent's possession count per minute.",
     "stat_signature": "Seconds-per-possession rises 1.8–2.6 s above open-game baseline beyond +8 margin; shot-clock-under-8 shot frequency climbs from ~18 % (neutral) to ~30–36 % in protection mode.",
     "mechanism": "Each extra second consumed reduces the number of scoring opportunities available to the trailing side; the compounding effect is independent of per-possession efficiency.",
     "conditions": "Most pronounced in Q4 with margin 8–15 points; weaker against press defenses forcing live-clock resets; amplified for teams in the bottom quartile of transition rate.",
     "magnitude": "Full modulation yields roughly 2–3 fewer opponent possessions per quarter versus neutral pace, worth ~4–6 expected points of margin durability.",
     "links": ["spacing_discipline_lead_offense", "transition_restraint_lead_safety", "margin_elastic_pace_control", "two_for_one_margin_banking"]},

    {"slug": "letdown_after_run_collapse", "title": "Post-Run Letdown Collapse",
     "summary": "Following an 8-or-larger self-built scoring run, many teams enter a predictable drought as collective focus softens, raising turnover rate and shot-selection entropy.",
     "stat_signature": "Next-5-possessions PPP drops 0.12–0.20 below team mean after an 8-0 or larger run; live-ball turnover rate spikes 1.4–2.0× baseline; opponent transition opportunity rises ~25 %.",
     "mechanism": "Post-burst arousal lowers attentional bandwidth; players accept marginal shot quality; defensive positioning loosens before reset occurs.",
     "conditions": "Most pronounced in teams with weak half-court structure; reduced when the coaching staff calls a timeout immediately after the run to anchor execution.",
     "magnitude": "Opponent counter-scores ~4–7 points on average in the post-run window, capable of converting a double-digit lead into a contested single-digit margin.",
     "links": ["run_extension_press_continuation", "timeout_bleed_stop_response", "lead_volatility_band", "double_digit_lead_retention_rate"]},

    {"slug": "lead_volatility_band", "title": "Lead Volatility Band",
     "summary": "The standard deviation of point margin across rolling 2-minute windows while ahead captures how tightly a team controls the margin versus allowing large intra-game swings.",
     "stat_signature": "Low-volatility holders show rolling-margin SD below 3.5 pts per 2-min window; high-volatility teams exceed 5.5; league median splits at ~4.2.",
     "mechanism": "Consistent defensive stops and high-quality offensive possessions keep opponent run lengths short, anchoring the margin and preventing structural resets.",
     "conditions": "Volatility elevates when bench units lack defensive versatility; lowers against opponents with weak shot creation and poor three-point percentages.",
     "magnitude": "Bottom-tercile lead-volatility teams lose double-digit leads ~40 % of the time versus ~18 % for top-tercile holders — roughly a 22-percentage-point descriptive gap.",
     "links": ["double_digit_lead_retention_rate", "momentum_arrest_anti_run_index", "defensive_intensity_decay_ahead", "cushion_threshold_behavior_shift"]},

    {"slug": "cushion_threshold_behavior_shift", "title": "Cushion-Threshold Behavior Shift",
     "summary": "Teams show a measurable discontinuity in shot selection and defensive aggression when margin crosses the 8–12-point band, shifting from attack mode to protection mode.",
     "stat_signature": "Three-point attempt rate drops 3–5 pp above the +10 threshold; help-rotation frequency on ball-screens declines ~10–15 %; paint-touch rate on offense rises.",
     "mechanism": "The 8–12-point band equates to roughly two possessions of safety; play-callers rationally shift to variance-minimizing profiles, trading closeout aggression for transition safety.",
     "conditions": "Threshold is sharpest in Q4; flatter in Q1–Q3; more visible for teams with explicit protection schemes signaled by substitution pattern changes.",
     "magnitude": "Behavior shift is observable in ~65 % of team-games with a sustained +10 or larger margin; three-point rate divergence averages ~4 pp versus neutral-margin baseline.",
     "links": ["shot_quality_conservatism_ahead", "defensive_intensity_decay_ahead", "lead_protection_tempo_modulation", "lead_dependent_rotation_staggering"]},

    {"slug": "double_digit_lead_retention_rate", "title": "Double-Digit Lead Retention Rate",
     "summary": "The fraction of 10-plus-point mid-game margins still 6 or more points eight game-minutes later is a stable team-level signature of lead-holding execution quality.",
     "stat_signature": "League range spans ~52–82 % retention; elite holders sustain at a 78–82 % rate; bottom decile falls below 55 %; season-level SD is ~7–9 pp.",
     "mechanism": "Retention integrates tempo control, turnover suppression, foul avoidance, and stop-chain quality into one outcome metric.",
     "conditions": "Degrades against elite late-game three-point creation; improves when the leading team holds a free-throw-rate advantage activatable in closing minutes.",
     "magnitude": "The ~27-pp gap between top and bottom decile corresponds descriptively to roughly 3–5 wins per season attributable to lead-holding execution alone.",
     "links": ["lead_volatility_band", "turnover_suppression_while_ahead", "free_throw_lead_insulation", "momentum_arrest_anti_run_index"]},

    {"slug": "stop_get_score_chaining_ahead", "title": "Stop-and-Score Chaining While Ahead",
     "summary": "The conditional probability of scoring on the possession immediately after a defensive stop while leading measures a team's ability to compound a margin rather than merely maintain it.",
     "stat_signature": "High-chain teams convert stop-to-score at ~58–64 %; league median is ~51 %; each 5-pp improvement adds ~0.4 expected net-margin points per game.",
     "mechanism": "Back-to-back efficiency events compound the scoring deficit the trailing team must close and deplete opponent bench depth by forcing earlier substitutions.",
     "conditions": "Rate is highest when transition opportunities follow the stop; declines on late-shot-clock resets; opponent fatigue in Q4 elevates chaining opportunity.",
     "magnitude": "Top-quartile chain teams extend leads by an extra ~3–5 points per game on average once they hold a 6-plus margin entering Q4.",
     "links": ["run_extension_press_continuation", "lead_extension_efficiency_window", "transition_restraint_lead_safety", "momentum_arrest_anti_run_index"]},

    {"slug": "timeout_bleed_stop_response", "title": "Timeout Bleed-Stop Response",
     "summary": "A defensive timeout called while leading to arrest opponent momentum is measured by opponent PPP in the four possessions before versus after the stoppage.",
     "stat_signature": "Effective responses yield a 0.15–0.22 PPP drop over the following four possessions; ~55–60 % of lead-protection timeouts produce a measurable bleed-stop.",
     "mechanism": "The stoppage disrupts opponent shot rhythm and allows the leading defense to reset rotations and communicate coverage adjustments; most effective against momentum-driven runs.",
     "conditions": "Effect is largest in Q3–Q4; diminishes when the leading team has exhausted timeouts and must substitute as a proxy stoppage; weaker against disciplined half-court offenses.",
     "magnitude": "The 0.15–0.22 PPP reduction across four possessions represents ~0.6–0.9 expected points of momentum arrest per timeout usage.",
     "links": ["letdown_after_run_collapse", "momentum_arrest_anti_run_index", "lead_volatility_band", "free_throw_lead_insulation"]},

    {"slug": "free_throw_lead_insulation", "title": "Free-Throw Lead Insulation",
     "summary": "Drawing fouls and converting free throws stabilizes a margin under pressure by generating uncontested points the opponent's defense cannot directly prevent.",
     "stat_signature": "Free-throw rate (FTA/FGA) rises 15–25 % in margin-protection stretches for foul-drawing offenses; FT% in high-leverage margin moments averages 77–80 % leaguewide.",
     "mechanism": "Free throws stop the clock in most situations and accumulate foul trouble on opposing defenders, degrading their defensive cohesion over the closing stretch.",
     "conditions": "Most impactful when opposing best defenders are near foul limits; less effective when officiating is consistent and does not reward marginal contact.",
     "magnitude": "Each additional FTA per possession in protection mode adds ~0.2 expected points (at 80 % FT conversion), compounding clock and point advantages simultaneously.",
     "links": ["double_digit_lead_retention_rate", "lead_holding_foul_avoidance", "turnover_suppression_while_ahead", "timeout_bleed_stop_response"]},

    {"slug": "turnover_suppression_while_ahead", "title": "Turnover Suppression While Ahead",
     "summary": "Protecting possession when leading prevents opponent transition opportunities that can rapidly collapse a margin; live-ball turnover rate is the key differentiator.",
     "stat_signature": "Live-ball TO rate in positive-margin possessions averages ~9.5 % leaguewide; top-quartile suppressors fall below 7.5 %; each 1-pp reduction saves ~0.12 transition PPP per possession.",
     "mechanism": "Live-ball turnovers uniquely provide fast-break opportunities bypassing half-court defensive setup, amplifying expected opponent scoring value beyond a missed shot.",
     "conditions": "Suppression deteriorates under high-pressure defenses and with fatigued ball-handlers in Q4; teams with deliberate half-court flow exhibit the lowest rates.",
     "magnitude": "The ~2-pp gap between top and bottom quartile corresponds to a ~0.24 PPP differential against transition-proficient opponents — meaningful over 30-plus possessions.",
     "links": ["double_digit_lead_retention_rate", "spacing_discipline_lead_offense", "transition_restraint_lead_safety", "lead_protection_tempo_modulation"]},

    {"slug": "defensive_intensity_decay_ahead", "title": "Defensive Intensity Decay While Ahead",
     "summary": "On-ball pressure and closeout speed measurably soften as a lead grows, yielding more open threes and rim approaches — a structural byproduct of conservative defensive positioning.",
     "stat_signature": "Opponent open-three rate (defender > 4 ft) rises 4–7 pp when margin exceeds +12 versus neutral possessions for the same team; rim frequency also rises 3–5 pp in that margin band.",
     "mechanism": "Coaches shade defenders off shooters to maintain help positioning, trading contested-three prevention for transition safety — a rational expected-value decision at large margins.",
     "conditions": "Decay is largest against three-point-heavy offenses; minimized by teams with deep athletic wings capable of closing out while maintaining transition recovery lanes.",
     "magnitude": "The 4–7-pp open-three concession during decay windows adds ~0.06–0.10 expected opponent PPP — modest per possession but meaningful cumulated across a quarter.",
     "links": ["cushion_threshold_behavior_shift", "shot_quality_conservatism_ahead", "lead_holding_foul_avoidance", "lead_volatility_band"]},

    {"slug": "momentum_arrest_anti_run_index", "title": "Momentum-Arrest Anti-Run Index",
     "summary": "A team's ability to cap opponent counter-runs at 5 or fewer points before forcing a stop measures the structural robustness of its lead-holding system.",
     "stat_signature": "Maximum opponent partial-run per held-lead stretch averages ~7.2 pts leaguewide; top-tercile anti-run teams hold to ~5.1 before a stop; recovery PPP after an allowed run averages ~1.02.",
     "mechanism": "Timely stops interrupt rhythm and prevent the cascade of psychological momentum that accelerates run length; both stop quality and quick offense after stops contribute.",
     "conditions": "Index degrades when the primary rim-deterrent is on the bench; improves when coaching staff deploys a timeout in the first two possessions of an opponent run.",
     "magnitude": "Top-quartile anti-run teams sustain 10-plus leads ~12 pp more reliably than bottom-quartile teams — a large descriptive separation.",
     "links": ["lead_volatility_band", "timeout_bleed_stop_response", "run_extension_press_continuation", "double_digit_lead_retention_rate"]},

    {"slug": "shot_quality_conservatism_ahead", "title": "Shot-Quality Conservatism While Ahead",
     "summary": "When leading, teams shift toward higher-percentage, lower-variance shots — more paint and mid-range, fewer contested threes — to minimize scoring droughts that invite opponent runs.",
     "stat_signature": "Contested-three rate drops 3–5 pp above the +8 threshold; paint-touch frequency rises 4–6 pp; expected PPP shifts modestly 0.03–0.05 downward as teams accept lower ceilings for reduced variance.",
     "mechanism": "Variance reduction in scoring output lowers the likelihood of consecutive empty possessions; each empty possession is a one-sided gift to the trailing team.",
     "conditions": "Most rational when opponent three-point defense is strong; partially counterproductive against half-court iso coverages that benefit from a slowed opponent pace.",
     "magnitude": "Conservatism narrows lead-offense PPP by ~0.03–0.06 versus neutral-game baseline while reducing empty-possession streaks by roughly 20–25 %.",
     "links": ["cushion_threshold_behavior_shift", "defensive_intensity_decay_ahead", "spacing_discipline_lead_offense", "lead_protection_tempo_modulation"]},

    {"slug": "transition_restraint_lead_safety", "title": "Transition Restraint for Lead Safety",
     "summary": "Teams ahead strategically reduce offensive leak-out rates and crash frequency to prioritize transition defense, trading fast-break upside for margin stability.",
     "stat_signature": "Offensive leak-out rate drops 30–40 % below neutral-game baseline at +8 or larger margins; opponent transition PPP falls 0.10–0.18 versus their season mean in those stretches.",
     "mechanism": "Each prevented opponent transition possession is worth ~0.15 more PPP than a half-court possession; the trade favors restraint when the margin is large enough to absorb the fast-break upside cost.",
     "conditions": "Most rational above +10; below +5 the fast-break upside trade-off reverses. Teams with elite transition defense can maintain some leak-out activity regardless of margin.",
     "magnitude": "Full restraint reduces opponent transition PPP by 0.12–0.18, compounding across 20–30 protected possessions in a lead-management-heavy game.",
     "links": ["lead_protection_tempo_modulation", "turnover_suppression_while_ahead", "stop_get_score_chaining_ahead", "lead_holding_foul_avoidance"]},

    {"slug": "lead_holding_foul_avoidance", "title": "Lead-Holding Foul Avoidance",
     "summary": "Restraint from unnecessary reaching fouls while leading prevents opponents from accumulating bonus free-throw opportunities that provide clock-neutral scoring at the worst time.",
     "stat_signature": "Fouls-per-possession while leading averages ~0.18 leaguewide; elite avoiders fall below 0.14; bonus-entry timing averages 4.2 possessions remaining per quarter for top-quartile teams versus 2.8 for the bottom quartile.",
     "mechanism": "Reaching fouls in bonus situations surrender points without stopping the clock, converting defensive miscues directly into margin erosion; delayed bonus entry preserves defensive depth for critical possessions.",
     "conditions": "Avoidance is hardest against physical pick-and-roll offenses manufacturing foul-drawing angles; most achievable against low-free-throw-draw jump-shooting teams.",
     "magnitude": "Each 0.02-unit reduction in fouls-per-possession while leading corresponds to ~0.016 fewer opponent free throws per possession — small individually, meaningful across 30-plus protected possessions.",
     "links": ["free_throw_lead_insulation", "defensive_intensity_decay_ahead", "turnover_suppression_while_ahead", "transition_restraint_lead_safety"]},

    {"slug": "two_for_one_margin_banking", "title": "Two-for-One Margin Banking",
     "summary": "End-of-period possession-count optimization secures an extra offensive possession before the buzzer, compounding a lead without ceding clock control.",
     "stat_signature": "Properly executed two-for-one sequences occur on ~38–48 % of eligible windows leaguewide; net points gained in confirmed sequences averages ~+1.1 versus opponent's next-possession expectation.",
     "mechanism": "Gaining two possessions for one opponent possession in the final 35–45 seconds shifts the marginal point balance; over a half the compounded execution adds 1.5–2.5 expected margin points.",
     "conditions": "Requires ball-handlers with high read-the-clock IQ; most relevant with margin 6–15 points where extending the lead has peak protective value.",
     "magnitude": "Top-tercile two-for-one teams gain ~1.8 net points per game in end-of-period sequences — a modest but consistent descriptive signature.",
     "links": ["lead_protection_tempo_modulation", "spacing_discipline_lead_offense", "cushion_threshold_behavior_shift", "lead_extension_efficiency_window"]},

    {"slug": "spacing_discipline_lead_offense", "title": "Spacing Discipline in Lead Offense",
     "summary": "Maintaining floor balance and deliberate pass sequencing in protection mode prevents live-ball turnovers while burning clock, trading peak offensive efficiency for ball-security reliability.",
     "stat_signature": "Average shot-clock used per possession rises to 17–19 s in protection mode versus 14–15 s at neutral; pass-count per half-court possession rises 0.6–1.1; live-ball TO rate falls below 7 % for disciplined systems.",
     "mechanism": "Each additional second consumed reduces available opponent possessions; ball-reversal sequences maintain defender attention and reduce help-side availability, lowering turnover probability.",
     "conditions": "Requires high-IQ, low-turnover half-court units; deteriorates with bench lineups lacking clear initiators; opponent pressure defense can disrupt spacing and force early clock resets.",
     "magnitude": "Structured lead offense at ~19 s per possession versus ~14 s yields roughly 2–3 fewer opponent possessions per quarter, worth ~4–5 expected points of margin preservation.",
     "links": ["lead_protection_tempo_modulation", "turnover_suppression_while_ahead", "two_for_one_margin_banking", "shot_quality_conservatism_ahead"]},
]
