"""Person-free NBA MatchupConcepts nodes — dense, sport-accurate, no player/team names."""
from __future__ import annotations

SPORT = "NBA"
FAMILY = "MatchupConcepts"

CONCEPTS: list[dict] = [
    {"slug": "switch_heavy_defense_against_high_pick_and_roll",
     "title": "Switch-Heavy Defense Against High Pick-and-Roll Volume",
     "summary": "A fully-switching scheme neutralises a pick-and-roll-reliant offense by denying clean separation on every screen, trading mismatch exposure for continuity coverage and reduction of blow-by layups.",
     "stat_signature": "Screen-assist rate drops 4-7 pp versus switch rate ≥75%; late-clock isolation frequency conceded rises 3-5 per 100 half-court possessions; ballhandler direct-read PPP suppressed to 0.82-0.90.",
     "mechanism": "Switching removes the gap between ball-screen coverage decisions that pick-and-roll systems are designed to exploit. When every screen is traded, the split-second separation window disappears, forcing the offense into improvised isolation rather than designed reads.",
     "conditions": "Sustainable when the defending roster is length-neutral across positions. Stressed against pick-the-picker or horns actions that engineer sequential mismatches and against bigs with enough shooting gravity to punish the switch.",
     "magnitude": "Clean separation from ball screens drops 20-30%; mismatch-exploitation possessions rise 3-5 per 100 half-court possessions, yielding 0.05-0.12 PPP surplus on hunted switches.",
     "links": ["drop_coverage_against_pull_up_shooting_initiator", "playmaking_big_against_switch_everything_coverage", "high_usage_creator_against_dedicated_chaser_blitz", "post_up_offense_against_undersized_switch_defender", "two_big_frontcourt_against_five_out_spacing"]},

    {"slug": "drop_coverage_against_pull_up_shooting_initiator",
     "title": "Drop Coverage Against a Pull-Up Shooting Initiator",
     "summary": "A sagging big conceding elbow and mid-range space to a creator with a credible pull-up game creates a structural concession that compounds across possessions as the initiator settles into uncontested rhythm jumpers.",
     "stat_signature": "Mid-range frequency lift 4-8 attempts per 100 ball-screen possessions; effective FG% on uncontested elbow pull-ups 46-52%; rim-attempt rate suppressed 6-10 pp below league average on same possessions.",
     "mechanism": "Drop coverage trades rim protection for perimeter concessions. When the ballhandler converts mid-range shots above the break-even threshold, the defensive logic inverts and the scheme becomes a net negative regardless of its rim-protection value.",
     "conditions": "Exploitable when the initiator posts pull-up mid-range FG% above 40%. Remains viable when the screener is a lob threat and the ballhandler is rim-oriented with limited pull-up range.",
     "magnitude": "Mid-range pull-up PPP against a drop averages 0.88-0.96 for capable initiators — comparable to league-average rim PPP — eliminating the scheme's primary efficiency rationale when the initiator is accurate.",
     "links": ["switch_heavy_defense_against_high_pick_and_roll", "movement_shooting_against_static_drop_scheme", "stretch_big_against_traditional_drop_anchor", "zone_defense_against_non_shooting_personnel"]},

    {"slug": "small_ball_lineup_against_dual_big_frontcourt",
     "title": "Small-Ball Spacing Against a Dual-Big Frontcourt",
     "summary": "A five-out or four-guard lineup exploits the perimeter-coverage liability of two traditional bigs while accepting an offensive rebounding deficit and rim-protection exposure at the other end.",
     "stat_signature": "Offensive-rebound rate conceded rises 5-9 pp when small-ball lineup faces dual bigs; perimeter closeout failures by opposing bigs 6-10 per 100 possessions; three-point attempt share in small-ball lineups ≥42%.",
     "mechanism": "Pulling both bigs away from the rim creates driving lanes and open corner threes, but the defense surrenders second-chance points at an elevated rate. The trade resolves in the small team's favour only when three-point conversion rates compensate for the rebound deficit.",
     "conditions": "Most advantageous when one or both opposing bigs post perimeter-closeout grades below average. Net-negative when the big frontcourt is mobile enough to defend the arc and still dominate the glass.",
     "magnitude": "Second-chance points conceded rises 3-5 per 100 possessions in sustained small-ball; offensive-rebound rate drops 6-10 pp for the small-ball team, representing a structural 1-2 extra possession swing per game for the bigger frontcourt.",
     "links": ["two_big_frontcourt_against_five_out_spacing", "elite_rim_protection_against_drive_heavy_attack", "offensive_rebounding_team_against_one_big_back_scheme", "deep_three_volume_against_paint_packing_defense"]},

    {"slug": "elite_rim_protection_against_drive_heavy_attack",
     "title": "Elite Rim Protection Against a Drive-Heavy Attack",
     "summary": "A paint-anchoring shot-alterer suppresses restricted-area attempts and forces a downhill slashing offense into a lower-value shot diet of floaters, pull-ups, and kick-out threes.",
     "stat_signature": "Restricted-area attempt rate drops 8-14 pp against elite rim protection; floater/short mid-range attempt share rises 4-7 pp; FG% at the rim drops 8-12 pp versus league average against elite anchor presence.",
     "mechanism": "Consistent rim deterrence shifts drive-completion probability before contact occurs — slashers initiate floaters or early kick-outs rather than challenging a shot-alterer. The kick-out three becomes the primary outlet, transferring shot-creation pressure to perimeter shooters.",
     "conditions": "Most impactful against drive-first offenses with limited pull-up shooting range. Reduced when the slashing offense employs a high-low spacing system that draws the anchor out or when kick-out shooters convert at above-average rates.",
     "magnitude": "Rim deterrence alone reduces drive-possession PPP by 0.08-0.14; total defensive PPP improvement attributable to elite rim protection estimated at 2-4 points per 100 possessions in anchored defensive systems.",
     "links": ["small_ball_lineup_against_dual_big_frontcourt", "perimeter_pressure_against_high_turnover_ball_handling", "zone_defense_against_non_shooting_personnel", "transition_attack_against_slow_defensive_transition"]},

    {"slug": "perimeter_pressure_against_high_turnover_ball_handling",
     "title": "Perimeter Ball Pressure Against High-Turnover Ball-Handling",
     "summary": "Sustained on-ball pressure against a loose-handle offense compounds live-ball turnover generation, converting defensive activity into a fast-break points pipeline at the other end.",
     "stat_signature": "Live-ball turnover rate forced rises to 15-22% on pressed possessions; transition PPP off takeaways 1.12-1.28; targeted ball-handler turnover rate ≥5 per 100 half-court possessions above league average.",
     "mechanism": "Aggressive pressure accelerates decision speed beyond the handler's comfort threshold, increasing fumble and travel frequency. Takeaways generate unset fast breaks where numerical mismatches persist before the defense re-sets.",
     "conditions": "Effective against offenses where the primary initiator posts a live-ball turnover rate above 15% and where secondary handlers lack the composure to absorb the ball under pressure. Physically taxing, limiting its usage to burst sequences.",
     "magnitude": "Turnover rate roughly doubles on pressed possessions versus unpressed half-court; each extra live-ball turnover yields approximately 1.15 PPP in fast-break conversion, creating a compounding impact across a game.",
     "links": ["pressing_full_court_against_methodical_initiation", "transition_attack_against_slow_defensive_transition", "high_usage_creator_against_dedicated_chaser_blitz", "foul_drawing_attack_against_aggressive_contest_scheme"]},

    {"slug": "zone_defense_against_non_shooting_personnel",
     "title": "Zone Defense Against Non-Shooting Personnel",
     "summary": "A 2-3 or matchup zone collapses the paint and disrupts offensive timing when the offensive roster lacks credible arc shooters, turning the zone's gap concessions into negligible threats.",
     "stat_signature": "Above-the-break three-point attempt rate rises 5-9 per 100 zone possessions; three-point conversion rate from zone concession positions drops to 29-33%; rim-attempt rate from half-court falls 10-16 pp versus zone baseline.",
     "mechanism": "Zone area responsibilities clog the paint with pre-positioned bodies, denying the drive-and-kick sequences that rely on floor spacers. Without credible shooters occupying zone gaps, defenders can double the ball without conceding open conversion looks.",
     "conditions": "Most effective when two or more offensive players post three-point attempt rates below 15% or conversion rates below 30%. Exploitable via high-post flash entries and skip-pass sequences that shift the zone before it can rotate.",
     "magnitude": "PPP in zone typically 0.03-0.08 below man-coverage PPP for zone-attack-incompetent offenses; offensive-rebound gap of 4-7 pp is the structural cost that partially offsets the shot-quality gain.",
     "links": ["drop_coverage_against_pull_up_shooting_initiator", "movement_shooting_against_static_drop_scheme", "small_ball_lineup_against_dual_big_frontcourt", "deep_three_volume_against_paint_packing_defense"]},

    {"slug": "transition_attack_against_slow_defensive_transition",
     "title": "Transition Attack Against Slow Defensive Transition",
     "summary": "A high-pace offense exploits an opponent that crashes the offensive glass or jogs back, manufacturing numerical mismatches in the first eight seconds before coverage sets.",
     "stat_signature": "Points-off-misses in first 8 seconds: 1.18-1.28 PPP; cross-matchup mismatch frequency before set: 18-28% of transition possessions; early-clock rim attempt rate ≥42% versus late-transition 28-34%.",
     "mechanism": "Slow-transitioning teams concede the floor before defensive assignments are established. A one-step advantage in transition translates directly into rim access or open corner threes that settled half-court coverage would prevent.",
     "conditions": "Amplified when the slow-transitioning team values offensive rebounding and sends multiple players to the glass. Diminished when the opponent outlets deliberately and applies disciplined defensive-first rotations.",
     "magnitude": "Transition PPP advantage over half-court averages 0.12-0.22; top-quartile transition-frequency teams generate 4-8 additional high-value attempts per game against slow-transition opponents.",
     "links": ["perimeter_pressure_against_high_turnover_ball_handling", "offensive_rebounding_team_against_one_big_back_scheme", "rebounding_advantage_against_pace_pushing_opponent", "slow_grind_halfcourt_against_chaos_pace_identity"]},

    {"slug": "post_up_offense_against_undersized_switch_defender",
     "title": "Post-Up Offense Against an Undersized Switch Defender",
     "summary": "A switching scheme that deposits a guard on an interior scorer creates a seal-and-punish dynamic, elevating post-touch frequency, deep-seal position rate, and free-throw attempts drawn.",
     "stat_signature": "Post-touch frequency against switch mismatch ≥12 per 100 half-court possessions; free-throw rate drawn on post touches 30-40%; points-per-post-touch against size mismatch 1.08-1.22.",
     "mechanism": "An undersized switch defender lacks the leverage to contest deep seals or alter finish attempts. The interior scorer dictates contact on every touch, drawing fouls at elevated rates while also finishing over inferior size at higher conversion.",
     "conditions": "Requires deliberate mismatch-hunting: the offense must run its switching scheme to isolate the guard on the post scorer consistently. Reduced when the defense sends a quick double-down that strips the ball or contests the entry pass.",
     "magnitude": "Free-throw rate on mismatch post-ups exceeds league-average post-up free-throw rate by 8-14 pp; PPP advantage of 0.12-0.20 over matched-size post coverage makes mismatch hunting a repeatable offensive lever.",
     "links": ["switch_heavy_defense_against_high_pick_and_roll", "two_big_frontcourt_against_five_out_spacing", "iso_isolation_offense_against_help_heavy_defense", "foul_drawing_attack_against_aggressive_contest_scheme"]},

    {"slug": "movement_shooting_against_static_drop_scheme",
     "title": "Off-Ball Movement Shooting Against a Static Drop Scheme",
     "summary": "A motion-shooting offense exploits conservative, non-rotating drop coverage by relocation and screen-the-screener actions that generate wide-open catch-and-shoot threes before closeout defenders can arrive.",
     "stat_signature": "Wide-open catch-and-shoot three rate: 8-14 per 100 half-court possessions versus drop; closeout distance on skip passes ≥4 feet in 35-45% of catch events; catch-and-shoot three conversion 39-44% in open-look classification.",
     "mechanism": "Drop-coverage defenders prioritise paint protection over perimeter rotation. Off-ball screens exploit the resulting closeout deficit: by the time the help-side defender relocates, the shooter has already secured a standing set position.",
     "conditions": "Most productive when the screener has enough shooting gravity to prevent the defender from camping in the gap. Stressed against switching schemes that trade the closeout deficit for seamless coverage continuity.",
     "magnitude": "Open catch-and-shoot threes off off-ball screens convert 3-6 pp above contested equivalents; motion-heavy offenses against non-rotating drop schemes generate 4-7 additional wide-open threes per game.",
     "links": ["drop_coverage_against_pull_up_shooting_initiator", "zone_defense_against_non_shooting_personnel", "iso_isolation_offense_against_help_heavy_defense", "stretch_big_against_traditional_drop_anchor"]},

    {"slug": "iso_isolation_offense_against_help_heavy_defense",
     "title": "Isolation-Heavy Offense Against a Help-and-Recover Defense",
     "summary": "One-on-one scoring that draws nail help triggers a kick-out cascade to corner threes, creating a drive-and-kick efficiency loop when perimeter shooters convert at above-threshold rates.",
     "stat_signature": "Drive-and-kick pass rate ≥40% on possessions drawing two defenders; corner-three frequency generated 6-10 per 100 iso possessions; help-defender stunt-recovery deficit resulting in open catch >1.5 s: 30-45% of rotation events.",
     "mechanism": "A help-heavy scheme predicts that an isolated scorer cannot punish the kick-out. The efficiency trade inverts when perimeter shooters convert corner threes above 36%, making the help defense structurally suboptimal regardless of iso containment quality.",
     "conditions": "Most effective when four legitimate perimeter threats surround the isolating scorer. Stressed when the defense can stunt-and-recover quickly enough to contest kick-outs without conceding open looks.",
     "magnitude": "Corner three generation from iso kick-outs yields PPP of 1.08-1.18 when conversion is ≥36%; the drive-and-kick loop generates 2-4 additional open corner attempts per game against help-heavy schemes.",
     "links": ["post_up_offense_against_undersized_switch_defender", "movement_shooting_against_static_drop_scheme", "high_usage_creator_against_dedicated_chaser_blitz", "deep_three_volume_against_paint_packing_defense"]},

    {"slug": "offensive_rebounding_team_against_one_big_back_scheme",
     "title": "Crash-the-Glass Offense Against a One-Big-Back Scheme",
     "summary": "A heavy-crashing offense exploits a defense that sends only one rebounder back, generating second-chance points while symmetrically exposing itself to fast-break transition attempts in the opposite direction.",
     "stat_signature": "Offensive-rebound rate: 28-35% against one-big-back versus 23-26% against two-back; second-chance PPP 1.10-1.22; transition exposure created by crashing forwards: 15-22% of opponent transition possessions.",
     "mechanism": "A single rim-protecting rebounder cannot box out multiple crashing perimeter players simultaneously. The offensive rebound surge creates extra possessions, but each crash forward sent late also concedes an open lane for the defensive team's transition.",
     "conditions": "Net-positive when the crashing team converts second-chance opportunities at above-average rates and can match back defensively. Net-negative when the opponent has a high-pace primary ball-handler who pushes immediately after the rebound.",
     "magnitude": "Each additional offensive rebound generates approximately 1.15 points in expectation; crashing teams that exceed 30% OREB rate against one-back defenses gain 2-4 extra possessions per game.",
     "links": ["small_ball_lineup_against_dual_big_frontcourt", "transition_attack_against_slow_defensive_transition", "rebounding_advantage_against_pace_pushing_opponent", "slow_grind_halfcourt_against_chaos_pace_identity"]},

    {"slug": "deep_three_volume_against_paint_packing_defense",
     "title": "High-Volume Three Shooting Against a Paint-Packing Defense",
     "summary": "A perimeter-heavy offense accepts the arc concessions of a paint-packing scheme to generate high volumes of three-point attempts, trading efficient-paint access for elevated game-to-game scoring variance.",
     "stat_signature": "Three-point attempt share lifts to ≥42% against paint-packing; game-to-game scoring standard deviation 8-13% above baseline; paint-touch rate suppressed 12-18 pp; three-point conversion variance across game samples expands by 15-25%.",
     "mechanism": "A defense that walls off the rim concedes the arc explicitly, relying on three-point variance to suppress the offense's expected-value ceiling. High-volume three-point offenses accept this variance, banking on law-of-large-numbers convergence across a season.",
     "conditions": "Positively resolved for the offense when shooters convert at league-average or above. Structurally negative for the offense in short samples or playoff series where variance is not averaged out.",
     "magnitude": "Three-point-heavy offenses against paint-packing defenses see PPP of 1.04-1.12 in large samples but game-level scoring variance 10-15% above equivalent mid-range-heavy offenses.",
     "links": ["zone_defense_against_non_shooting_personnel", "small_ball_lineup_against_dual_big_frontcourt", "iso_isolation_offense_against_help_heavy_defense", "movement_shooting_against_static_drop_scheme"]},

    {"slug": "high_usage_creator_against_dedicated_chaser_blitz",
     "title": "High-Usage Creator Against a Dedicated Chaser and Blitz",
     "summary": "A top-lock-plus-trap design removes primary scoring volume from a high-usage creator, transferring playmaking burden to secondary handlers who must make decisions against a recovering defense.",
     "stat_signature": "Creator usage rate suppressed 6-10 pp under chaser-blitz scheme; assist-rate transfer to secondary playmakers +4-7 pp; turnover rate on trapped possessions 18-24%; secondary-handler PPP on blitz escape 0.94-1.08.",
     "mechanism": "The blitz forces a quick decision out of the creator's hands. Secondary handlers — often less decision-proficient under pressure — inherit a 4-on-3 advantage they must convert cleanly or the advantage evaporates before a shot is generated.",
     "conditions": "Effective when the creator's supporting cast lacks either the passing skill or shooting range to punish the rotational gaps. Costly when the offense has multiple competent playmakers who can advance the ball and find the open man.",
     "magnitude": "Creator scoring volume drops 4-8 points per game equivalent under sustained chaser-blitz; secondary-handler errors (turnovers or rushed looks) offset roughly 30-50% of the blitz's disruption value.",
     "links": ["switch_heavy_defense_against_high_pick_and_roll", "perimeter_pressure_against_high_turnover_ball_handling", "iso_isolation_offense_against_help_heavy_defense", "playmaking_big_against_switch_everything_coverage"]},

    {"slug": "playmaking_big_against_switch_everything_coverage",
     "title": "Playmaking Big Against Switch-Everything Coverage",
     "summary": "A passing big exploits the coverage gaps created behind ball screens by attacking switched matchups in the short roll, generating 4-on-3 advantages that smaller switch defenders cannot help on without conceding open threes.",
     "stat_signature": "Short-roll touch frequency: 8-14 per 100 switch possessions; 4-on-3 advantage pass rate from short roll ≥35%; catch-and-shoot three rate generated from short-roll kick 5-9 per 100 possessions.",
     "mechanism": "Switch coverage sends a guard to cover the roll. The big — now guarded by a smaller defender in the mid-post or short-roll area — passes before the defense can rotate, creating an open shooter or cutter that the thinned coverage cannot contain.",
     "conditions": "Amplified when the big has genuine passing vision and the offense has three or more perimeter shooters surrounding the screen action. Neutralised when the defense sends immediate double coverage on the short-roll catch.",
     "magnitude": "Short-roll catch-and-pass sequences generate open threes at 5-9 per 100 possessions; the 4-on-3 frame yields PPP of 1.10-1.22, making this one of the highest-value exploit patterns against switch-heavy schemes.",
     "links": ["switch_heavy_defense_against_high_pick_and_roll", "high_usage_creator_against_dedicated_chaser_blitz", "movement_shooting_against_static_drop_scheme", "two_big_frontcourt_against_five_out_spacing"]},

    {"slug": "two_big_frontcourt_against_five_out_spacing",
     "title": "Two-Big Frontcourt Against Five-Out Spacing",
     "summary": "Conventional interior size defending a fully-spaced five-out floor faces repeated perimeter closeout duties that pull bigs away from their rim-protection value and expose them to open driving lanes.",
     "stat_signature": "Perimeter closeout frequency for bigs: 8-14 per 100 possessions against five-out; rim-protection possessions forfeited while closing: 20-30% of big's defensive actions; open-drive rate when big closes out ≥35%.",
     "mechanism": "Asking a traditional big to close out on the arc simultaneously empties the rim-protection role he was deployed for. The drive behind the closeout is uncontested, and the big's recovery speed from arc to rim is structurally insufficient.",
     "conditions": "Structurally challenging when both bigs lack credible arc-closeout speed. Mitigated when one big is mobile enough to close out without abandoning the rim and when the offense has limited drivers who can punish the closeout.",
     "magnitude": "Rim-protection possessions forfeited to closeout duties represent a 0.06-0.12 PPP swing per relevant possession; over a game, dual-big lineups against five-out offenses concede an estimated 3-6 additional high-quality shot opportunities.",
     "links": ["small_ball_lineup_against_dual_big_frontcourt", "playmaking_big_against_switch_everything_coverage", "stretch_big_against_traditional_drop_anchor", "zone_defense_against_non_shooting_personnel"]},

    {"slug": "foul_drawing_attack_against_aggressive_contest_scheme",
     "title": "Foul-Drawing Attack Against an Aggressive Contesting Scheme",
     "summary": "A contact-seeking offense targets hand-up vertical-contest defenders to generate free throws at elevated rates, accumulating bonus situations and foul-trouble minutes that degrade defensive quality late in games.",
     "stat_signature": "Free-throw rate (FTA/FGA): 0.42-0.58 against aggressive-contest scheme; opponent team bonus reaching frequency: 14-18 minutes per game; foul-trouble impact: top defensive player 4+ fouls in ≥25% of high-pressure matchups.",
     "mechanism": "Aggressive-contest defenders are structurally disposed to illegal contact on shot fakes and gather moves. A foul-seeking offense internalises this tendency to manufacture high-percentage foul situations rather than field-goal attempts.",
     "conditions": "Most impactful in the fourth quarter when opponents are already in foul trouble and the bonus compounds. Diminished against patient, vertical-only defenders who refuse contact but accept the slight shot-quality concession.",
     "magnitude": "Each free-throw rate unit above league average (~0.28) generates approximately 0.04 extra points per possession; foul-trouble-induced defensive degradation in bonus situations adds 0.05-0.10 PPP to offense for the affected defensive minutes.",
     "links": ["perimeter_pressure_against_high_turnover_ball_handling", "post_up_offense_against_undersized_switch_defender", "iso_isolation_offense_against_help_heavy_defense", "high_usage_creator_against_dedicated_chaser_blitz"]},

    {"slug": "stretch_big_against_traditional_drop_anchor",
     "title": "Stretch Big Against a Traditional Drop Anchor",
     "summary": "A shooting big drags a rim-protecting anchor out to the three-point line, forcing a choice between defending the pop-out three or maintaining paint presence — a dilemma that most traditional drop anchors cannot resolve.",
     "stat_signature": "Anchor distance-from-basket on pop-out possessions: forced to ≥18 ft in 30-45% of screen possessions; pick-and-pop three rate conceded: 5-9 per 100 pick-and-roll possessions; rim-protection possessions forfeited while closing: 25-35%.",
     "mechanism": "Drop coverage logic depends on the screener being a non-threat at the arc so the anchor can remain near the rim. A stretch big inverts this assumption: every step the anchor takes toward the arc vacates his rim-protection role and enables the ballhandler's drive.",
     "conditions": "Maximally disruptive when the screening big converts above-the-break threes at ≥36%. Neutralised when the defense switches — accepting the guard-on-big mismatch at the arc rather than asking the anchor to close out.",
     "magnitude": "Pick-and-pop three rate conceded against stretch-big screen actions is 2-4× the rate versus non-shooting screeners; anchors forced to close out concede rim-protection on 25-35% of their defensive possessions in those lineups.",
     "links": ["drop_coverage_against_pull_up_shooting_initiator", "two_big_frontcourt_against_five_out_spacing", "small_ball_lineup_against_dual_big_frontcourt", "movement_shooting_against_static_drop_scheme"]},
]
