"""Person-free Soccer MatchupConcepts spec — contract in __init__.py."""
from __future__ import annotations

SPORT = "Soccer"
FAMILY = "MatchupConcepts"

CONCEPTS: list[dict] = [
    {
        "slug": "high_press_against_short_build_up_possession",
        "title": "High Press Against Short Build-Up Possession",
        "summary": "An aggressive high press applied against a play-out-from-the-back side forces the build-up into the goalkeeper as the last safe outlet, compressing passing lanes and generating turnovers in dangerous defensive territory.",
        "stat_signature": "Pressing side PPDA < 8 in opponent defensive third; high-turnover recoveries > 4 per 90; bypassing side long-ball share rises above 30 pct when pressed versus 18 pct baseline.",
        "mechanism": "Short build-up requires time and space; a coordinated press collapses both by flooding near-ball lanes before the receiving player can turn. The goalkeeper becomes a decision bottleneck: distribute short into pressure or clear long and concede territory. Either disrupts possession rhythm and shifts second-ball contests to unfavorable zones.",
        "conditions": "Most acute when the pressing side sustains shape in a 4-3-3 or 4-2-3-1 high block and the build-up side circulates through a central double pivot. Diminishes when the build-up side carries a strong aerial target who can win long clearances and hold play.",
        "magnitude": "Sides pressed at PPDA < 8 show a 15-25 pct reduction in successful build-up progressions past their own half; high-turnover zones near goal translate to a meaningful increase in close-range attempt volume for the pressing team.",
        "links": ["pressing_trap_against_slow_central_circulation", "direct_long_ball_against_high_aggressive_press", "build_up_goalkeeper_against_forward_pressing_trigger", "midfield_press_resistance_against_aggressive_pressing"],
    },
    {
        "slug": "low_block_against_possession_dominant_attack",
        "title": "Low Block Against a Possession-Dominant Attack",
        "summary": "A deep compact defensive block absorbs sustained possession pressure by collapsing space inside the penalty area, conceding the ball in wide or deep zones and forcing the attacking side into low-probability long-range attempts.",
        "stat_signature": "Defensive block line below own penalty area; opponent outside-box attempt share > 40 pct; xG conceded per shot < 0.09; box entries per 90 suppressed below 12 despite opponent possession above 60 pct.",
        "mechanism": "Narrow spacing between defensive lines eliminates through-ball channels and forces wide recycling. The attacking side accumulates possession statistics but cannot penetrate; the resulting shot diet is dominated by speculative long-range efforts with low conversion rates. Low-block sides accept territorial inferiority in exchange for shape integrity and transition opportunities on the counter.",
        "conditions": "Most effective when the attacking side lacks wide overloads or set-piece delivery quality. Breaks down against overlapping fullback combinations that stretch the block laterally, or against teams that combine width with cutback delivery to unmarked runners at the penalty-area edge.",
        "magnitude": "Possession-dominant attackers facing a disciplined low block average 0.7-1.0 xG lower per match than against mid-block opponents, with a 20-30 pct shift in attempts toward outside-the-box zones that carry roughly half the conversion rate of central close-range shots.",
        "links": ["compact_mid_block_against_patient_buildup", "wing_overload_against_narrow_compact_block", "counter_attack_against_high_defensive_line", "possession_control_against_low_pressing_intensity"],
    },
    {
        "slug": "counter_attack_against_high_defensive_line",
        "title": "Counter-Attack Against a High Defensive Line",
        "summary": "A transition-focused side exploits space behind an advanced back line by releasing runners immediately after a turnover, generating high-value fast-break chances before the opposing structure can recover.",
        "stat_signature": "Fast-break attacks reaching the box within 10 seconds of turnover > 5 per 90; through-balls completed into the channel > 3 per 90; counter-attack shot xG > 0.15 per attempt; opposition defensive-line depth above 35 meters from own goal.",
        "mechanism": "A high line compresses space in front of the ball but leaves a large vacant corridor behind the center-backs. One accurate ball over the line unlocks a one-on-one or two-on-one before defenders recover. The transition window is typically three to five seconds, so execution must be high-speed with minimal touches.",
        "conditions": "Strongest when the transitioning side has pace in forward positions and the high-line team lacks a sweeper or hybrid libero to cover behind. Effectiveness diminishes if the defending side deploys aggressive offside trapping in unison to neutralize the channel runs.",
        "magnitude": "Counter-attack attempts against a high line generate xG per shot roughly 40-60 pct higher than the match average for the attacking side, reflecting the open-goal and minimal-defender scenarios that fast breaks create.",
        "links": ["fast_transition_against_slow_recovery_defense", "high_line_against_pacey_runners_in_behind", "low_block_against_possession_dominant_attack", "direct_long_ball_against_high_aggressive_press"],
    },
    {
        "slug": "wing_overload_against_narrow_compact_block",
        "title": "Wing Overload Against a Narrow Compact Block",
        "summary": "Concentrating attacking players on one flank forces a centrally compact defense to choose between holding its narrow shape or shifting to cover the overload, creating either wide crossing opportunities or half-space cutback angles as the block slides.",
        "stat_signature": "Crosses attempted from dominant flank > 18 per 90; half-space entries (channels between penalty area and wide zones) > 6 per 90; cutback chance rate from wide areas above 15 pct of total chances; lateral defensive-block shift > 8 meters from center.",
        "mechanism": "A narrow block is optimized for central channel closure. A winger, overlapping fullback, and underlapping midfielder create 3-versus-2 situations in wide areas. As the block shifts to compensate, either the near-post lane opens for a driven cross or the far side vacates for late runners. Neither defensive response fully neutralizes both threats simultaneously.",
        "conditions": "Most effective against a 4-4-2 flat or 5-4-1 that maintains rigid horizontal compactness. Reduces in impact against a 4-3-3 where a wide midfielder can track the overload without displacing the central trio.",
        "magnitude": "Flank-dominant sides facing a narrow block average 2-4 additional cutback chances per match versus balanced opponents; half-space entries generated carry xG 30-40 pct above the team's baseline attempt quality.",
        "links": ["low_block_against_possession_dominant_attack", "overlapping_fullbacks_against_man_marking_wingers", "inverted_winger_against_low_overlapping_fullback", "cross_heavy_attack_against_tall_aerial_defense"],
    },
    {
        "slug": "pressing_trap_against_slow_central_circulation",
        "title": "Coordinated Pressing Trap Against Slow Central Circulation",
        "summary": "A trigger-based press that springs on a specific passing action sidelines central midfielders who circulate slowly, winning the ball in the middle third and converting possession turnover directly into transition opportunities.",
        "stat_signature": "Ball recoveries in the middle third > 8 per 90 for the pressing side; opponent backward and sideways pass share > 55 pct under pressure; forced turnovers leading to shots within 15 seconds > 2 per 90.",
        "mechanism": "Slow circulation allows pressing lines to close before the receiving player turns. A coordinated trap — one player triggers high, one covers the back pass, one shadows the outlet — collapses options simultaneously. The result is a forced backward pass or a loose touch recovered by the pressing team in a dangerous central zone.",
        "conditions": "Requires compact lines and high energy for repeated trap cycles. Effect diminishes after 70 minutes as pressing intensity falls, or if the ball-playing side switches to a direct style that bypasses the central trap zone entirely.",
        "magnitude": "Effective trap pressing against slow central circulation generates mid-third turnovers at roughly twice the rate of passive defending; resulting transition shots carry xG 20-30 pct above open-play average due to proximity to goal and disorganized defensive shape.",
        "links": ["high_press_against_short_build_up_possession", "midfield_press_resistance_against_aggressive_pressing", "physical_midfield_against_technical_short_passing", "compact_mid_block_against_patient_buildup"],
    },
    {
        "slug": "midfield_press_resistance_against_aggressive_pressing",
        "title": "Press-Resistant Midfield Against Aggressive Pressing",
        "summary": "Ball-retentive central midfielders who receive under pressure and complete progressive passes defeat an aggressive press by escaping the trap zone and advancing their team into the attacking half with numerical structure intact.",
        "stat_signature": "Progressive passes completed under direct pressure > 4 per 90; press-break frequency into attacking half against PPDA < 10 opponent > 6 per 90; touch-and-release time under pressure < 1.2 seconds per action.",
        "mechanism": "Press-resistant midfielders pre-scan before receiving, identify the escape angle, and release the ball in a single fluid motion, denying the pressing trigger its closing window. Each successful press-break advances the entire team structure forward, converting defensive pressure into a numerical advantage in the subsequent phase.",
        "conditions": "Most valuable when paired with positional triangular support around the ball carrier. Breaks down under extreme man-press with high foul tolerance, where physicality disrupts the touch-and-release rhythm regardless of technical quality.",
        "magnitude": "Teams with high press-break frequency advance into the attacking half on roughly 40-55 pct of sequences even against PPDA < 8 opponents, versus 20-30 pct for sides lacking press-resistant profiles; each break increases the probability of a controlled final-third entry by roughly 25 pct relative to direct clearance sequences.",
        "links": ["high_press_against_short_build_up_possession", "pressing_trap_against_slow_central_circulation", "physical_midfield_against_technical_short_passing", "possession_control_against_low_pressing_intensity"],
    },
    {
        "slug": "set_piece_threat_against_zonal_marking_defense",
        "title": "Set-Piece Threat Against a Zonal-Marking Defense",
        "summary": "A side with strong set-piece delivery and aerial runners attacks a zone-marking scheme by targeting seams between assigned zones, generating near-post flick-ons and back-post arrival chances that zonal assignments leave momentarily uncontested.",
        "stat_signature": "Near-post and far-post first-contact wins > 50 pct on attacking set pieces; headed-shot xG from corners and wide free kicks > 0.12 per delivery; zone-seam chances between two defenders' zones > 2 per 90 from dead balls.",
        "mechanism": "Zonal systems assign ground to defend rather than players to mark. Blockers and late-arriving runners disrupt the moment of defensive jump, introducing a half-second gap at the seam between zone boundaries. Curved deliveries timed to arrive at the seam before defenders can shuffle deny the positional advantage zonal marking is designed to provide.",
        "conditions": "Most effective when delivery quality curves consistently into zone-seam areas. Less effective against a hybrid scheme that assigns man-marks on the most dangerous aerial threats while zone-covering the back post.",
        "magnitude": "Set-piece threatening sides against pure zone schemes generate 0.10-0.18 xG per corner, roughly 30-50 pct above leaguewide average per delivery, with the surplus concentrated in first-contact headed chances from the seam arrival route.",
        "links": ["cross_heavy_attack_against_tall_aerial_defense", "two_striker_front_against_back_three_defense", "low_block_against_possession_dominant_attack"],
    },
    {
        "slug": "direct_long_ball_against_high_aggressive_press",
        "title": "Direct Long-Ball Style Against a High Aggressive Press",
        "summary": "A vertical direct playing style bypasses the high press entirely by launching the ball over the pressing line to a target forward, winning second-ball contests around that forward and establishing territory without building through midfield.",
        "stat_signature": "Long-pass share > 30 pct of total passes; second-ball recovery rate near target forward > 45 pct; territory gained per sequence above 25 meters when press is detected; opposition pressing intensity PPDA < 10 in the trigger zone.",
        "mechanism": "The high press concentrates players near the ball in deep zones, leaving space behind and around the pressing lines. A well-weighted ball over the top eliminates multiple press players with a single action. The direct side cedes possession statistics but gains field position and physical contest advantages around a strong aerial target forward.",
        "conditions": "Requires a forward capable of holding aerial contests and bringing teammates into play under physical pressure. Most effective on large pitches where the long ball provides a genuine distance advantage. Diminishes against a high defensive line playing an aggressive offside trap that neutralizes the channel before the ball arrives.",
        "magnitude": "Direct sides facing a high press bypass the midfield line on 20-35 pct of sequences, advancing the ball 25-40 meters in a single action. Second-ball recovery rate near the target determines whether this translates to sustained pressure or a recycled possession reset.",
        "links": ["high_press_against_short_build_up_possession", "counter_attack_against_high_defensive_line", "build_up_goalkeeper_against_forward_pressing_trigger", "two_striker_front_against_back_three_defense"],
    },
    {
        "slug": "overlapping_fullbacks_against_man_marking_wingers",
        "title": "Overlapping Fullbacks Against Man-Marking Wide Defenders",
        "summary": "Attacking fullbacks who join wide overloads exploit man-oriented wide marking schemes by arriving late into the overlap after the marking defender has committed to the winger, generating two-on-one situations and final-third delivery opportunities.",
        "stat_signature": "Fullback touches in the final third > 12 per 90; two-on-one wide situations created > 5 per 90; chances created from fullback overlap crossing or cutback > 2 per 90; opponent wide defender recovery distance per event > 8 meters.",
        "mechanism": "Man-marking winger assignments fix one defender to one attacker. When the fullback overlaps late, the assigned defender must choose: follow the original mark and concede the overlap, or switch to cover the fullback and allow the winger to cut inside. Either decision creates a gap that a driven cutback or low cross can exploit.",
        "conditions": "Strongest when the attacking fullback is athletic enough to recover defensively after the overlap, limiting transition exposure. Breaks down if the defending side rotates centrally and releases a wide midfielder to pick up the overlapping run.",
        "magnitude": "Fullback overlap systems against man-oriented wide schemes generate 25-35 pct more wide entry chances per match than narrow-fullback systems, with the additional crosses concentrated in the low-cross zone that produces higher xG than traditional high-ball delivery.",
        "links": ["wing_overload_against_narrow_compact_block", "inverted_winger_against_low_overlapping_fullback", "high_press_against_short_build_up_possession"],
    },
    {
        "slug": "physical_midfield_against_technical_short_passing",
        "title": "Physical Midfield Against Technical Short-Passing",
        "summary": "An aggressive ball-winning midfield that presses with physicality and tactical fouling disrupts a technically superior short-passing core by breaking rhythm, accumulating yellow-card pressure, and shifting the contest to second-ball duels rather than combination play.",
        "stat_signature": "Tackles and interceptions in the central zone > 14 per 90; fouls committed in midfield > 8 per 90; opponent pass-completion in central zones drops below 78 pct from above 87 pct when unpressed; circulation tempo slows by 15-25 pct under physical engagement.",
        "mechanism": "Technical short-passing depends on quick touch-and-move combinations requiring a fraction of a second between receipt and release. Physical pressure extends that window by disrupting balance, demanding an additional touch to retain possession. Accumulated disruption forces backward passes and resets rather than progressive play.",
        "conditions": "Most effective when referees allow a physical contest and when the technical side's passing structure relies on central pivots rather than wide recycling to escape pressure. Becomes self-limiting as yellow-card accumulation forces restraint in the second half.",
        "magnitude": "Technical sides against a high-foul high-duel midfield complete roughly 10-15 fewer progressive central passes per 90 than against a passive opponent, with disruption most acute in the opening 30 minutes before tactical adjustments.",
        "links": ["pressing_trap_against_slow_central_circulation", "midfield_press_resistance_against_aggressive_pressing", "possession_control_against_low_pressing_intensity"],
    },
    {
        "slug": "inverted_winger_against_low_overlapping_fullback",
        "title": "Inverted Winger Against a Low Overlapping Fullback",
        "summary": "A wide forward cutting inside onto a dominant foot exploits a wide defender who pushes high in the overlap, conceding the half-space behind the run and allowing the inverted winger to arrive centrally with space to shoot or combine.",
        "stat_signature": "Half-space shots from the inverted route > 3 per 90; dribbles completed inside from wide starting positions > 2 per 90; defensive recovery distance for the overlapping fullback left behind > 10 meters; inverted-path xG above 0.12 per attempt.",
        "mechanism": "The overlapping fullback vacates the half-space to join the wide overload, leaving a seam between the shifted wide defender and the near center-back. The inverted winger attacks this seam rather than the touchline, cutting onto a preferred foot for a driven shot or a layoff to an underlapping midfielder arriving in the gap.",
        "conditions": "Clearest when the defending fullback is assigned to the winger in a man-oriented scheme and commits to the touchline rather than dropping to cover the inside lane. Reduces in effectiveness when an interior midfielder tracks the cut-inside run rather than the fullback.",
        "magnitude": "Inverted wingers cutting inside against the overlapping fullback's vacated half-space average 0.15-0.20 xG per cutting sequence — roughly double the conversion probability of a wide crossing attempt from the same starting position.",
        "links": ["wing_overload_against_narrow_compact_block", "overlapping_fullbacks_against_man_marking_wingers", "compact_mid_block_against_patient_buildup"],
    },
    {
        "slug": "compact_mid_block_against_patient_buildup",
        "title": "Compact Mid-Block Against Patient Build-Up",
        "summary": "A defensive mid-block holding a medium-height shape invites build-up circulation in front of it, waiting for a pressing trigger — a heavy touch, a slow pivot, a backward pass — before springing to win the ball in the middle third.",
        "stat_signature": "Block engagement line at 35-45 meters from own goal; pressing triggers activated > 6 per 90; ball recoveries in middle third > 7 per 90; forced lateral-pass share above 50 pct when opponent circulates inside the engagement zone.",
        "mechanism": "The mid-block conserves energy by passively shaping the opponent's build-up into predictable patterns — wide circulation, backward resets, limited central entry. The pressing trigger converts one of these predictable moments into an active press without sustaining full high-press intensity for a full match.",
        "conditions": "Most effective when trigger recognition is coordinated across at least two pressing players simultaneously. Breaks down when the build-up side has a press-resistant midfielder who can receive inside the zone, turn quickly, and advance before the trap closes.",
        "magnitude": "A well-organized mid-block trigger strategy wins possession in the middle third at 1.5-2 times the rate of purely passive defending, generating transition opportunities 25-35 percent shorter distance to goal than recoveries from a deep block.",
        "links": ["pressing_trap_against_slow_central_circulation", "low_block_against_possession_dominant_attack", "possession_control_against_low_pressing_intensity", "inverted_winger_against_low_overlapping_fullback"],
    },
    {
        "slug": "possession_control_against_low_pressing_intensity",
        "title": "Possession Control Against Low Pressing Intensity",
        "summary": "A possession-dominant side facing a passive drop-off opponent accumulates territorial and statistical control but risks a sterile-dominance pattern where high possession shares do not convert to proportional expected-goal generation.",
        "stat_signature": "Possession share > 60 pct with opponent PPDA > 18; final-third entries > 20 per 90; possession-to-xG conversion ratio below 0.015 xG per pct possession; box entries from open play below 10 per 90 despite dominant ball share.",
        "mechanism": "Low pressing invites circulation freely but denies entry channels by packing the defensive block. The dominant side retains the ball safely in lateral zones but cannot penetrate through central lanes. The mismatch between possession share and xG output reflects the block's success funneling attempts to low-value zones.",
        "conditions": "Sterile dominance is most pronounced when the possession side lacks wide overloads or individual dribble capacity to bypass the passive block. The dynamic reverses when the possession team combines patient circulation with a sudden wide switch or a dribble to attract and break the block structure.",
        "magnitude": "Possession-dominant sides in sterile-dominance conditions generate 0.8-1.2 xG per 90 despite 65-70 pct possession, compared with 1.5-2.0 xG when circulation links to genuine penetration — the gap reflects the efficiency cost of uncontested but non-penetrating ball retention.",
        "links": ["low_block_against_possession_dominant_attack", "compact_mid_block_against_patient_buildup", "midfield_press_resistance_against_aggressive_pressing", "draw_prone_grinder_against_high_scoring_attack"],
    },
    {
        "slug": "high_line_against_pacey_runners_in_behind",
        "title": "High Defensive Line Against Pacey Runners in Behind",
        "summary": "An advanced back line playing a coordinated offside trap creates a tension between the territorial advantage of the high line and the catastrophic-chance cost when the trap is beaten by pace-intensive attackers.",
        "stat_signature": "Offside traps correctly sprung > 4 per 90; through-balls beating the line into the box > 2 per 90 against the high-line side; big-chance xG conceded from behind-the-line runs > 0.20 per event; defensive line depth above 38 meters from own goal.",
        "mechanism": "A high line compresses the playing field, shortening distances and limiting opponent receiving time in midfield. The tradeoff is a large open corridor behind the center-backs. When timing is imperfect — one defender steps late or ball timing outruns the line — the result is an uncovered channel leading directly to the goalkeeper.",
        "conditions": "Risk is highest when the attacking side deploys multiple runners splitting defensive lines in unison, stretching the offside check across simultaneous runs. A single covering center-back with pace can partially mitigate but cannot fully negate the corridor when two runners release simultaneously.",
        "magnitude": "High-line defenses neutralize the majority of runs through offside, but the minority of beaten traps generates big chances at xG roughly 0.30-0.45 per event — among the highest-value chance types in open play — creating a distributional skew toward small numbers of very high-value conceded opportunities.",
        "links": ["counter_attack_against_high_defensive_line", "fast_transition_against_slow_recovery_defense", "direct_long_ball_against_high_aggressive_press"],
    },
    {
        "slug": "fast_transition_against_slow_recovery_defense",
        "title": "Fast Transition Against a Slow Recovery Defense",
        "summary": "A quick-break attacking side exploits a defense slow to regain compact shape after losing possession, reaching the penalty area with numerical parity or advantage before the defending block resets.",
        "stat_signature": "Attacks reaching the box before defensive reset (within 6 seconds of turnover) > 4 per 90; open-play chance value in transition above 0.14 xG per attempt; opponent recovery block success rate < 55 pct on transition sequences.",
        "mechanism": "A slow-recovery defense is typically one committed high in attack or reliant on a flat back line that retreats en masse rather than individually recovering. The transitioning side's forward runners reach the box before the defensive structure reforms, leaving large spaces centrally or wide for cutback or through-ball exploitation.",
        "conditions": "Amplified when the transitioning side has two or more runners who accelerate immediately on turnover and when the opposition defensive line at the moment of loss is above the halfway line. Reduces against sides with a dedicated defensive midfielder who drops on ball loss to screen the transition corridor.",
        "magnitude": "Transition chance value against a slow-recovery unit runs 35-50 pct higher per attempt than the attacking side's open-play baseline, reflecting the reduced time defenders have to position between the ball and the goal.",
        "links": ["counter_attack_against_high_defensive_line", "compact_mid_block_against_patient_buildup", "low_block_against_possession_dominant_attack"],
    },
    {
        "slug": "build_up_goalkeeper_against_forward_pressing_trigger",
        "title": "Ball-Playing Goalkeeper Against a Forward Pressing Trigger",
        "summary": "A goalkeeper who participates in the first line of build-up by distributing short to center-backs faces a direct high press on their own distribution, forcing a choice between accepting pressure short or launching a long clearance that abandons the positional structure.",
        "stat_signature": "Goalkeeper pass-completion under pressure > 70 pct; long-clearance fallback rate when pressing trigger closes within 5 meters > 30 pct; opponent forward trigger activation targeting the goalkeeper > 5 per 90; successful goalkeeper-to-outfield progressive passes > 4 per 90.",
        "mechanism": "A ball-playing goalkeeper extends the numerical structure of the back line into distribution range, providing an extra passing option opponents must account for. A forward pressing trigger that closes the goalkeeper's short-pass lanes forces a confrontation: accept a pass under pressure or concede the build-up structure with a long clearance.",
        "conditions": "The clash is sharpest in sides that build in a 4-2-3-1 or 3-2-5 shape where the goalkeeper is designated as the extra outfield player. Less relevant for traditional sides that use a long goal-kick distribution pattern without goalkeeper positional involvement.",
        "magnitude": "Goalkeeper distribution under pressure accounts for 10-15 pct of possession sequences in high-pressing matches; when forced to clearance the side concedes 30-40 meters of territory per sequence and resets the entire build-up structure from scratch.",
        "links": ["high_press_against_short_build_up_possession", "direct_long_ball_against_high_aggressive_press", "midfield_press_resistance_against_aggressive_pressing"],
    },
    {
        "slug": "draw_prone_grinder_against_high_scoring_attack",
        "title": "Low-Scoring Grinder Against a High-Scoring Attack",
        "summary": "A defensively cautious low-tempo side meeting a free-scoring opponent creates a combined-goals distribution pulled toward the under, as the grinder suppresses shot volume while the attacker's finishing rate cannot fully overcome the defensive structure.",
        "stat_signature": "Grinder's shots conceded per 90 suppressed below 10 against high-scoring opponent's baseline of 16+; combined match xG pulled below 2.0 per game despite the attacker's seasonal average above 2.5; shot-volume suppression rate above 35 pct relative to the attacker's typical opponents.",
        "mechanism": "A defensively compact low-block structure reduces the high-scoring attack's attempt volume and shot quality simultaneously. The attacker retains the ball but cannot generate the frequency or location mix needed to express its full scoring rate. Total match xG contracts toward a narrow band that favors low-total outcomes.",
        "conditions": "Effect is strongest when the grinder side is willing to accept full territorial inferiority and the high-scoring attack lacks wide route diversity to bypass the block. Weakens when the attacker has elite set-piece delivery that bypasses the open-play suppression.",
        "magnitude": "Matchups pairing a low-block grinder against a top-quartile scoring attack produce combined xG roughly 0.6-1.0 below expected from averaging the two sides' seasonal totals, indicating the structural suppression is not additive — the grinder's effect dominates the combined output.",
        "links": ["low_block_against_possession_dominant_attack", "possession_control_against_low_pressing_intensity", "set_piece_threat_against_zonal_marking_defense"],
    },
    {
        "slug": "two_striker_front_against_back_three_defense",
        "title": "Two-Striker Front Against a Back-Three Defense",
        "summary": "A two-striker system pins a three-center-back defense by occupying two of the three central defenders, reducing the spare-defender cover that a three-back structure is designed to provide and opening wide channels for late-arriving midfield runners.",
        "stat_signature": "Spare-defender involvement frequency drops below 25 pct of defensive actions from a baseline of 40 pct; central duel load per center-back > 6 per 90; wide channel entries by opposing midfielders > 5 per 90 as wing-backs are forced inward to track the striker pair.",
        "mechanism": "A three-back system's advantage is one unchallenged center-back who sweeps centrally. Two strikers occupying the two markers deny the spare role, forcing the sweeper into active coverage. Simultaneously, wing-backs must choose whether to track striker flank movement or hold width, creating a permanent structural tension that forward-arriving midfielders exploit.",
        "conditions": "Most effective when the two-striker system has physical center-forward profiles that demand active man-marking. Reduces in effectiveness if the three-back side rotates into a deeper five-back block when defending, nullifying the spare-defender removal.",
        "magnitude": "Two-striker fronts against a three-back unit generate wide-channel entries at roughly 30-40 pct above average for the attacking side, as wing-backs are pulled inward to cope with the central pair, leaving wide channels momentarily uncontested for midfield runners.",
        "links": ["set_piece_threat_against_zonal_marking_defense", "direct_long_ball_against_high_aggressive_press", "wing_overload_against_narrow_compact_block"],
    },
]
