"""Person-free NBA Mechanisms concept nodes — dense, sport-accurate, no player/team names."""
from __future__ import annotations

SPORT = "NBA"
FAMILY = "Mechanisms"

CONCEPTS: list[dict] = [
    {"slug": "spacing_gravity_conversion", "title": "Spacing-Gravity Conversion",
     "summary": "An off-ball shooter's threat displaces the nearest help defender, expanding driving lanes and generating rim-attempt and corner-three lift for teammates relative to no-gravity lineups.",
     "stat_signature": "Defender-to-shooter distance on catch >= 4 ft qualifies as open; gravity-lineup rim-FGA% 8-12 pp above no-gravity baseline; corner-three rate lift 3-5 per 100 half-court possessions per unit of gravity.",
     "mechanism": "A credible catch-and-shoot threat forces the help defender to pin to the shooter's hip rather than shrink toward the paint, removing the automatic low-man tag and widening the driving corridor by 4-6 horizontal feet.",
     "conditions": "Effect peaks when the spacer converts threes at above 37%; diminishes when the defense accepts conceding the corner-three at below break-even rates and loads help regardless.",
     "magnitude": "Rim-FGA rate lift of 6-10 pp in full-gravity lineups; open catch-and-shoot threes generated for teammates rise 4-7 per 100 possessions, converting at 38-43%.",
     "links": ["five_out_motion_offense", "rim_pressure_and_collapse", "halfcourt_shot_quality_generation", "lineup_synergy_amplification"]},

    {"slug": "pace_control_possession_inflation", "title": "Pace Control and Possession Inflation",
     "summary": "Controlling tempo expands or compresses the shared possession count per game, amplifying or dampening absolute scoring variance without changing per-possession quality.",
     "stat_signature": "Possessions-per-48 range 93-104 across NBA teams; each +1 possession adds roughly 1.0-1.1 expected points per team; pace deviation from 98 baseline correlates with total-game-points SD at r ~ 0.45-0.60.",
     "mechanism": "Faster transitions deny defensive set-up time and increase the fraction of early-clock possessions; slower deliberate offenses burn shot-clock seconds and cap the total number of possessions available to both teams.",
     "conditions": "Pace differential is most consequential when opponent teams deviate more than 4 possessions from baseline; in near-even-pace matchups the effect is absorbed into per-possession efficiency.",
     "magnitude": "A 6-possession pace gap shifts expected total points by 6-7 points; top-quartile pace teams produce game-total SDs 3-5 points wider than bottom-quartile pace teams across a season.",
     "links": ["transition_conversion_engine", "halfcourt_shot_quality_generation", "three_point_variance_amplification", "rest_advantage_conversion"]},

    {"slug": "halfcourt_shot_quality_generation", "title": "Half-Court Shot-Quality Generation",
     "summary": "Creation of high-expected-value looks against a set defense, anchored by rim-or-corner attempts and suppression of mid-range volume in the half-court clock.",
     "stat_signature": "Half-court PPP range 0.90-1.12; rim-or-corner share above 55% of half-court attempts marks elite shot-quality discipline; contested mid-range share below 15% is the strongest single-possession quality proxy.",
     "mechanism": "Forcing the defense to guard both the rim and the three-point arc simultaneously creates a binary dilemma; shot selection that consistently resolves into high-value zones converts shot-clock and offensive talent into sustainable PPP.",
     "conditions": "Most impactful in late-clock situations where the defense can crowd the paint; attenuated in transition possessions where coverage is unset and shot-clock pressure is absent.",
     "magnitude": "Elite rim-or-corner discipline produces half-court PPP 0.06-0.12 above average; each 5 pp shift in mid-range share corresponds to roughly 0.03-0.05 PPP change.",
     "links": ["spacing_gravity_conversion", "rim_pressure_and_collapse", "transition_conversion_engine", "three_point_variance_amplification", "clutch_leverage_execution"]},

    {"slug": "transition_conversion_engine", "title": "Transition Conversion Engine",
     "summary": "Converting defensive stops and live-ball turnovers into early-clock scoring by attacking before the defense reaches set positions, generating a persistent PPP premium over half-court possessions.",
     "stat_signature": "Transition frequency >= 18% of offensive possessions; transition PPP 1.10-1.25 against 0.98-1.05 half-court; early-clock rim attempt share > 40% in first 4 seconds; transition FGA frequency correlated with opponent live-ball turnover rate at r ~ 0.55.",
     "mechanism": "Numerical and positional mismatches before coverage assignments are set create lay-up or open-three opportunities that no half-court scheme replicates; a single live-ball turnover generates a 1.15+ PPP possession on average.",
     "conditions": "Amplified when the opponent posts high live-ball turnover rate (>15%) or slow defensive rebounding outlet pace; diminished when the defense sprints back and refuses to engage early-clock screens.",
     "magnitude": "Transition-to-half-court PPP gap of 0.10-0.20 is among the most durable shot-quality differentials; top-transition-frequency teams generate 5-9 additional high-value attempts per 48 minutes.",
     "links": ["pace_control_possession_inflation", "second_chance_generation", "defensive_stop_chaining", "transition_defense_prevention"]},

    {"slug": "second_chance_generation", "title": "Second-Chance Generation",
     "summary": "Manufacturing extra possessions via offensive rebounding, converting missed shots into live-ball possession continuations at higher value than possession-start averages.",
     "stat_signature": "OREB% above 28% marks top-quartile; second-chance PPP 1.05-1.20 due to proximity at catch; put-back-attempt FG% 58-66% versus reset-and-reset average of 48-54%; second-chance points per game range 10-17.",
     "mechanism": "Crashing the offensive glass extends the possession without a new shot-clock reset and positions the offense within 4-8 feet of the rim, removing the half-court set-up cost and generating high-quality attempts.",
     "conditions": "Amplified against small or non-boxing defensive lineups; attenuated when the defense assigns a dedicated back-to-the-basket rebounder and commits full box-out resources on every shot.",
     "magnitude": "Each additional 3 pp in OREB% corresponds to roughly 1.5-2.0 second-chance points per game; top-OREB teams generate 2-4 extra scoring possessions per 48 minutes relative to average.",
     "links": ["transition_conversion_engine", "halfcourt_shot_quality_generation", "paint_protection_deterrence", "lineup_synergy_amplification"]},

    {"slug": "turnover_economy_suppression", "title": "Turnover-Economy Suppression",
     "summary": "Protecting possessions by minimising live-ball giveaways, preserving scoring opportunities and denying opponent transition PPP generated off forced errors.",
     "stat_signature": "Turnover rate below 12% of possessions marks elite possession care; live-ball turnover share above 60% of all turnovers is the dangerous subtype; opponent points-off-turnovers conceded varies 13-20 per 100 possessions.",
     "mechanism": "Live-ball turnovers bypass half-court defense and trigger the highest-PPP possession type; suppressing them removes the highest-cost possession outcome and stabilises the per-game scoring floor.",
     "conditions": "Most consequential in pace-heavy contexts where turnovers directly seed transition; less differentiating in deliberate half-court offenses where most turnovers are dead-ball and recovery is possible.",
     "magnitude": "A 3 pp improvement in turnover rate saves approximately 2-3 scoring possessions per 48 minutes; teams in the bottom quartile of turnovers concede 4-6 more transition attempts per game than top-quartile teams.",
     "links": ["transition_conversion_engine", "defensive_stop_chaining", "clutch_leverage_execution", "ball_movement_advantage_creation"]},

    {"slug": "rim_pressure_and_collapse", "title": "Rim Pressure and Defensive Collapse",
     "summary": "Forcing interior defensive commitment by attacking the rim directly, then punishing the resulting rotations with kick-out threes and free-throw-attempt generation.",
     "stat_signature": "Drive frequency >= 16 per 100 half-court possessions; rim-FGA rate > 28% of all attempts; kick-out catch-and-shoot three rate 3-5 per 100 drives; FTA-per-drive rate 0.18-0.30 on contact finishes.",
     "mechanism": "A credible rim threat forces the help defender to commit before the drive resolves, creating a collapse-and-kick binary. The free-throw bonus arrives independently of shooting quality, making rim-pressure a two-revenue-stream mechanism.",
     "conditions": "Most productive against drop-coverage and zone schemes that allow free driving lanes; attenuated by switch-everything schemes or shot-blocking deterrence that deflects attempts before the kick-out read develops.",
     "magnitude": "Elite-drive teams generate 6-10 additional free-throw attempts per game versus average; kick-out threes off drives convert at 38-43% with established gravity.",
     "links": ["spacing_gravity_conversion", "halfcourt_shot_quality_generation", "free_throw_leverage_conversion", "mismatch_exploitation_routing"]},

    {"slug": "three_point_variance_amplification", "title": "Three-Point Variance Amplification",
     "summary": "High three-point attempt volume widens the per-game scoring distribution, creating larger positive and negative tails relative to mid-range-heavy offenses at equivalent average PPP.",
     "stat_signature": "3PA rate above 40% of total field goals marks high-variance profile; game-to-game 3P% SD 4-8 pp; simulated scoring SD rises ~0.3 points per 1 pp increase in 3PA rate; margin-variance attribution to three-point makes 35-50% in high-volume offenses.",
     "mechanism": "Each three-pointer converts a binary make/miss outcome at 3 points rather than 2, amplifying the scoring swing per attempt; high volume compounds this into measurable game-level SD inflation that is independent of average shooting quality.",
     "conditions": "Variance effect dominates in small-sample game subsets; over a full season average outcomes converge. Effect is most decision-relevant for in-game projections in the first and fourth quarters.",
     "magnitude": "Top-10 three-point-volume teams show per-game scoring SDs 3-5 points wider than bottom-10 teams; 40-attempt three-point games move expected-score variance by 15-25% above baseline.",
     "links": ["halfcourt_shot_quality_generation", "pace_control_possession_inflation", "clutch_leverage_execution", "spacing_gravity_conversion"]},

    {"slug": "free_throw_leverage_conversion", "title": "Free-Throw Leverage Conversion",
     "summary": "Converting contact and foul-drawing into uncontested scoring, accumulating a bonus-possession equivalent that compounds its value in close games and late-clock situations.",
     "stat_signature": "FTA-per-FGA rate above 0.30 marks top-quartile foul-drawing; free-throw-derived points share 18-26% for foul-heavy offenses; FT-driven margin lift in games decided by 5 or fewer points averages 2-4 points for elite converters.",
     "mechanism": "Free throws arrive without shot-clock cost or defensive contest, generating scoring at 70-80% conversion efficiency from a standing line position; accumulating fouls also stresses opponents into foul-trouble rotations.",
     "conditions": "Magnified in physical half-court settings and late-game bonus situations; attenuated when opponents field disciplined non-fouling defenders or when the foul-drawer converts below 70% at the line.",
     "magnitude": "A 0.10 increase in FTA/FGA rate corresponds to 2-3 additional free-throw points per game; bonus-situation exploitation in the fourth quarter generates 1.5-2.5 extra points per close game.",
     "links": ["rim_pressure_and_collapse", "clutch_leverage_execution", "foul_environment_management", "mismatch_exploitation_routing"]},

    {"slug": "defensive_stop_chaining", "title": "Defensive Stop Chaining",
     "summary": "Consecutive defensive stops compound into scoring runs by denying opponent PPP while seeding transition and offensive rhythm, widening score margins in short bursts.",
     "stat_signature": "Stop-streak sequences of 3+ consecutive stops occur 4-8 times per game; average run differential during 3+ stop streaks 6-10 points; opponent PPP during multi-stop sequences drops 15-25% below their season average.",
     "mechanism": "Consecutive stops deny the opponent the score-equalising possession and hand the scoring team consecutive opportunities to widen the margin, exploiting the psychological and tactical weight of momentum accumulation.",
     "conditions": "Amplified when the defending team also holds high transition-frequency and fast-outlet tendencies; attenuated by opponent timeout usage which resets defensive coverage and breaks stop chains.",
     "magnitude": "Three-stop runs produce average margin swings of 6-9 points; teams in the top quartile of stop-chain frequency outscore opponents by 4-7 additional points during their best defensive stretches per game.",
     "links": ["transition_conversion_engine", "turnover_economy_suppression", "run_prevention_stabilization", "paint_protection_deterrence"]},

    {"slug": "paint_protection_deterrence", "title": "Paint-Protection Deterrence",
     "summary": "Suppressing opponent rim scoring through contested presence and shot-altering that pushes attempts to lower-value zones, reducing opponent half-court PPP at the primary source.",
     "stat_signature": "Opponent rim-FGA rate allowed below 24% marks elite deterrence; opponent rim-FG% allowed 57-63% with shot-alteration versus 66-72% uncontested; mid-range share of opponent attempts elevated 4-8 pp versus non-deterrent baselines.",
     "mechanism": "A credible rim protector raises the expected cost of drives before they initiate, reducing drive frequency and lowering rim conversion once shots arrive; the deterrence effect compounds at the point of attack before contact.",
     "conditions": "Most impactful against drive-heavy offenses with limited perimeter shooting gravity; attenuated when opponents use spacing to pull the rim protector out of the paint.",
     "magnitude": "Elite rim deterrence suppresses opponent half-court PPP by 0.04-0.10; mid-range shot deflection adds another 0.02-0.04 PPP disadvantage relative to would-be rim attempts.",
     "links": ["defensive_stop_chaining", "perimeter_containment", "rim_pressure_and_collapse", "lineup_synergy_amplification"]},

    {"slug": "perimeter_containment", "title": "Perimeter Containment",
     "summary": "Preventing dribble penetration at the point of attack and limiting open-three generation, forcing the offense into lower-value or contested shot alternatives.",
     "stat_signature": "Opponent drive rate allowed below 14 per 100 half-court possessions marks top-quartile containment; opponent open-three rate conceded below 28% of opponent three attempts; closeout-distance distribution on conceded threes skewed above 4 ft.",
     "mechanism": "On-ball containment at the perimeter forces the offense to reset or pull up rather than access the rim; effective closeouts reduce open-three conversion by 5-8 pp relative to uncontested equivalents.",
     "conditions": "Effective against isolation-centric and penetration-first offenses; stressed when the offensive team uses off-ball screens at speed to free shooters ahead of closeout arrivals.",
     "magnitude": "Top-quartile containment teams allow 2-4 fewer drive-generated rim attempts per game; open-three rate suppression of 4-6 pp translates to 0.04-0.08 PPP reduction on opponent half-court possessions.",
     "links": ["paint_protection_deterrence", "transition_defense_prevention", "foul_environment_management", "run_prevention_stabilization"]},

    {"slug": "transition_defense_prevention", "title": "Transition-Defense Prevention",
     "summary": "Denying the opponent early-clock scoring advantage by getting back and matching up before the first shot, converting opponent transition possessions into settled half-court actions.",
     "stat_signature": "Opponent transition frequency allowed below 15% marks elite prevention; opponent transition PPP conceded below 1.05 (league baseline 1.10-1.18); points-saved gap versus league transition baseline 3-6 per 48 minutes for top-quartile prevention units.",
     "mechanism": "Contested rebounders who outlet slowly and guards who retreat rather than crash deny the opponent numerical advantages; forcing a reset to half-court negates the 0.10-0.20 PPP premium of transition possessions.",
     "conditions": "Amplified when the defending team makes deliberate outlet choices rather than crashing offensively; attenuated when the opponent triggers live-ball turnovers that bypass rebounding-based prevention entirely.",
     "magnitude": "Suppressing opponent transition frequency from 20% to 15% of possessions prevents approximately 1.5-2.5 PPP-equivalent possession quality per 48 minutes; preventing all transition layups saves roughly 3-5 points per game.",
     "links": ["defensive_stop_chaining", "perimeter_containment", "transition_conversion_engine", "turnover_economy_suppression"]},

    {"slug": "foul_environment_management", "title": "Foul-Environment Management",
     "summary": "Controlling the rate at which defensive fouls donate bonus free-throw possessions to the opponent, limiting uncontested scoring and preserving key defenders from foul-trouble disqualification.",
     "stat_signature": "Fouls per 100 possessions committed range 18-26; opponent bonus-time share per quarter above 35% marks a foul-heavy environment; free throws conceded per drive defended 0.12-0.25 by defensive aggression profile.",
     "mechanism": "High foul rates transfer scoring possessions at near-70-80% efficiency to the opponent at zero defensive contest cost; foul trouble also forces rotation of key defenders, degrading coverage quality beyond the foul tally itself.",
     "conditions": "Most consequential in physical half-court settings and late-clock bonus situations; attenuated when the foul-drawing team converts below 72% at the line or when the defense effectively contests without fouling.",
     "magnitude": "Each 3 pp increase in opponent bonus-time share corresponds to 1.5-2.5 additional uncontested free-throw points per game; foul-trouble rotations degrade defensive PPP by an estimated 0.04-0.08 per absent starter.",
     "links": ["free_throw_leverage_conversion", "rim_pressure_and_collapse", "perimeter_containment", "clutch_leverage_execution"]},

    {"slug": "clutch_leverage_execution", "title": "Clutch Leverage Execution",
     "summary": "Generating disproportionate possession value in high-leverage late-game minutes when each possession carries amplified win-probability weight.",
     "stat_signature": "Clutch window defined as final 5 minutes with score within 5; clutch PPP varies 0.88-1.15 across teams season-over-season; shot-quality on clutch possessions averages 0.02-0.05 eFG% below non-clutch due to defensive attention; WPA per clutch possession peaks 2-4x non-clutch baseline.",
     "mechanism": "Win probability becomes highly non-linear in clutch windows; a single high-quality possession can swing WP by 8-15 percentage points, making possession-by-possession shot-quality more valuable than any per-game volume metric.",
     "conditions": "Effective against defenses that collapse to zone or force step-backs in high-leverage moments; attenuated when opponent clutch defense forces the offense into contested mid-range or off-the-dribble threes.",
     "magnitude": "Top-quartile clutch-PPP teams outperform by 0.08-0.15 PPP in clutch windows; clutch WPA gap between top and bottom quartile teams corresponds to an estimated 3-5 wins per season in close games.",
     "links": ["free_throw_leverage_conversion", "halfcourt_shot_quality_generation", "three_point_variance_amplification", "run_prevention_stabilization", "mismatch_exploitation_routing"]},

    {"slug": "run_prevention_stabilization", "title": "Run Prevention and Stabilization",
     "summary": "Limiting opponent scoring bursts and arresting momentum swings through timely timeouts and defensive adjustments, keeping deficit sizes within recoverable ranges.",
     "stat_signature": "Opponent 8-or-more-point run frequency averages 1.5-2.5 per game; points conceded in the 2 minutes following a timeout 4-7 per possession sequence; run-differential ceiling during worst defensive stretches 10-15 points per 3-minute window.",
     "mechanism": "Recognising and interrupting momentum runs via timeout or substitution resets defensive coverage, allows recovery of mismatched assignments, and breaks opponent rhythm — each mechanism contributing independently.",
     "conditions": "Most decisive in games with 3-possession or fewer margins in the third and fourth quarters; attenuated when the opponent maintains discipline after the stoppage and the underlying defensive coverage scheme remains unchanged.",
     "magnitude": "Effective run prevention reduces opponent scoring burst frequency by 20-35%; post-timeout defensive improvement averages 0.05-0.12 PPP reduction on the first 3 possessions after the stoppage.",
     "links": ["defensive_stop_chaining", "clutch_leverage_execution", "perimeter_containment", "paint_protection_deterrence"]},

    {"slug": "lineup_synergy_amplification", "title": "Lineup-Synergy Amplification",
     "summary": "Non-additive net-rating lift produced by complementary on-court skill combinations, where the observed five-man unit exceeds the sum of individual on-off contributions.",
     "stat_signature": "Five-man net-rating synergy gap (observed minus additive estimate) ranges from -4 to +8 per 100 possessions; lineups with complementary spacing-gravity and rim-threat profiles show synergy premiums of +3 to +6; sample-size floor for stable estimates is 100 possessions.",
     "mechanism": "Skill complementarity creates simultaneous threats that no single defender can neutralise, forcing the defense into coverage dilemmas it cannot solve positionally; each individual component benefits from the whole exceeding its parts.",
     "conditions": "Synergy premiums stabilise only in lineups exceeding 150-200 possessions together; short-sample spurious synergy is common and reverts; effect is largest when the combination uniquely stresses a specific defensive archetype.",
     "magnitude": "Genuine synergy lineups produce +3 to +8 net-rating surplus above additive expectation; top-5 lineup synergy gaps across a roster correspond to 2-4 estimated wins over 82 games.",
     "links": ["spacing_gravity_conversion", "mismatch_exploitation_routing", "ball_movement_advantage_creation", "rest_advantage_conversion"]},

    {"slug": "mismatch_exploitation_routing", "title": "Mismatch Exploitation Routing",
     "summary": "Systematically routing possessions to a created size or speed advantage after a screen or switch, maximising PPP by attacking the weakest available defender.",
     "stat_signature": "Post-switch target frequency >= 6 per 100 possessions for mismatch-seeking offenses; points-per-possession on switch-targeted actions 1.05-1.22 versus 0.95-1.05 non-targeted baseline; target-defender FG% allowed 8-14 pp above their non-targeted average.",
     "mechanism": "Engineering a mismatch concentrates the most difficult defensive assignment on the least equipped defender; sequencing actions to isolate the mismatch before the defense rotates converts the structural advantage into shot-quality.",
     "conditions": "Sustainable when the offense can repeatedly manufacture the mismatch through off-ball screens or sequential ball-screens; attenuated when the defense pre-switches or hides the targeted defender away from the primary action.",
     "magnitude": "Targeted-mismatch PPP premium of 0.08-0.18 over non-targeted possessions; routing 6-8 possessions per game into mismatches adds an estimated 1.0-1.5 points per game above random-assignment PPP.",
     "links": ["rim_pressure_and_collapse", "spacing_gravity_conversion", "clutch_leverage_execution", "lineup_synergy_amplification", "free_throw_leverage_conversion"]},
]
