"""MLB Mechanisms concept nodes — person-free causal-mechanism intelligence."""
from __future__ import annotations

SPORT = "MLB"
FAMILY = "Mechanisms"

CONCEPTS: list[dict] = [
    {
        "slug": "run_prevention_via_contact_suppression",
        "title": "Run Prevention via Contact Suppression",
        "summary": "Limiting run scoring by reducing contact quality; the gap between xERA from contact metrics and actual ERA measures how much suppression is real versus strand-rate noise.",
        "stat_signature": "Opponent hard-hit rate below 34 %; barrel rate allowed below 6 %; xERA-to-ERA gap above 0.20 for sustained suppression; sweet-spot rate against below 30 %.",
        "mechanism": "Avoiding barrels forces hitters into top-of-bat or bottom-of-bat contact, producing weak grounders or pop-ups with low exit velocity; each avoided barrel removes roughly 1.4 expected runs per nine innings from the contact-quality baseline.",
        "conditions": "Most durable for pitchers with elite vertical-break separation; decays as velocity drops or secondary shape degrades; high-altitude parks amplify suppressed fly-ball exit velocity effects.",
        "magnitude": "Top barrel-suppression quartile pitchers run xERA roughly 0.35-0.55 below league average; each 1-point reduction in barrel rate corresponds to approximately 0.08-0.12 ERA reduction over a full season.",
        "links": ["batted_ball_regression_to_expected", "strikeout_run_value_conversion", "ground_ball_double_play_suppression", "defensive_efficiency_conversion"],
    },
    {
        "slug": "strikeout_run_value_conversion",
        "title": "Strikeout Run-Value Conversion",
        "summary": "Converting whiffs into run-expectancy reduction; a strikeout is worth more than a ball-in-play out because it eliminates BABIP variance and runner-advancement risk simultaneously.",
        "stat_signature": "Strikeout rate above 26 %; whiff rate above 28 %; run-expectancy reduction per strikeout approximately 0.28 runs versus 0.24 for a ball-in-play out; swinging-strike rate above 12 %.",
        "mechanism": "Any ball in play carries a non-zero hit probability; strikeouts remove it entirely and advance no runners; the margin widens in high-base-out-leverage states where contact risks multi-base outcomes.",
        "conditions": "Run value is highest in bases-loaded and runner-on-third states; diminished in low-leverage early innings; strikeout accumulation raises pitch counts, creating a durability cost for starters.",
        "magnitude": "Pitchers above 28 % strikeout rate allow roughly 0.40-0.55 fewer runs per nine than contact-manager equivalents with identical walk rates; the per-event premium over a ball-in-play out is about 0.04 runs in neutral states.",
        "links": ["run_prevention_via_contact_suppression", "two_strike_approach_conversion", "times_through_order_decay", "high_leverage_strand_prevention"],
    },
    {
        "slug": "walk_economy_baserunner_inflation",
        "title": "Walk-Economy Baserunner Inflation",
        "summary": "Free passes inflate run-scoring opportunity independent of hits; each walk shifts the run-expectancy matrix upward without requiring the hitter to reveal batted-ball tendencies.",
        "stat_signature": "Walk rate above 10 % signals command vulnerability; run-expectancy lift per walk ranges from 0.17 runs with bases empty to 0.48 with runners on second and third.",
        "mechanism": "Walks consume a plate appearance while advancing the base-out state; high-walk pitchers face compounding risk because each walk raises the stakes for the next contact event with no ability to force a weak contact type.",
        "conditions": "Impact amplified when paired with a lineup that converts baserunners at high rates; compounds most severely when the lineup's top hitters follow immediately after the walk.",
        "magnitude": "Each 1-percentage-point increase in walk rate adds roughly 0.09-0.12 runs per nine innings; pitchers above 10 % walk rate surrender 0.6-0.8 more runs per game than those below 7 %, controlling for strikeout rate.",
        "links": ["big_inning_generation", "high_leverage_strand_prevention", "bullpen_leverage_chaining", "leverage_index_conversion"],
    },
    {
        "slug": "big_inning_generation",
        "title": "Big-Inning Generation",
        "summary": "Sequenced baserunners cluster to produce multi-run innings; roughly 60-65 % of all runs in a typical game score in innings yielding three or more runs, so inning-level variance dominates game totals.",
        "stat_signature": "Frequency of 3-or-more-run innings above 8 % per inning; runners-in-scoring-position conversion above 30 %; lead-off on-base rate above 35 % as a big-inning precursor.",
        "mechanism": "Run expectancy is non-linear in base-out state; a leadoff single raises same-inning scoring probability from 28 % to 43 %; each subsequent baserunner compounds expected runs, making the first baserunner the critical gating event.",
        "conditions": "Highest rate against pitchers with elevated walk rates or who allow hard-hit leadoff contact; park run environments amplify clustering when power hitters follow contact hitters.",
        "magnitude": "A leadoff walk or single raises same-inning expected runs by 0.45-0.60 runs; inning clustering accounts for roughly 30 % of game-level run-total variance above what independent-plate-appearance models predict.",
        "links": ["walk_economy_baserunner_inflation", "sequencing_and_cluster_luck", "power_isolation_run_compression", "leverage_index_conversion"],
    },
    {
        "slug": "sequencing_and_cluster_luck",
        "title": "Sequencing and Cluster Luck",
        "summary": "The timing-of-hits effect decouples runs from raw offensive output; observed run totals exceed context-neutral expectation in short samples but regress toward the mean as sequence randomness averages out.",
        "stat_signature": "Actual runs minus context-neutral expected runs diverging by more than 15 over a half-season; strand rate deviating from the 70-73 % baseline by more than 4 percentage points.",
        "mechanism": "Random sequencing of a fixed set of hits and walks produces a distribution of run totals centered on the context-neutral expectation; deviations reflect variance, not sustained skill, because no team clusters hits durably.",
        "conditions": "Largest apparent deviations occur in samples under 40 games; contact-heavy lineups show tighter clustering windows; extra-base-hit frequency moderates but does not eliminate regression.",
        "magnitude": "Over a full season, team run totals regress to within 8-12 runs of the context-neutral expectation; early-season deviations of 20-30 runs resolve to roughly half by game 81.",
        "links": ["big_inning_generation", "batted_ball_regression_to_expected", "power_isolation_run_compression", "defensive_efficiency_conversion"],
    },
    {
        "slug": "batted_ball_regression_to_expected",
        "title": "Batted-Ball Regression to Expected",
        "summary": "Outcome statistics revert toward contact-quality expectation over accumulating sample; BABIP and actual run output converge toward xBABIP and xwOBA as the contact signal overwhelms sequencing and defense noise.",
        "stat_signature": "BABIP deviation from expected BABIP above 20 points in small samples; xwOBA minus actual wOBA gap exceeding 25 points; half-life of BABIP regression approximately 200-300 plate appearances.",
        "mechanism": "Short-term BABIP is driven partly by defense, sequencing, and park; but the dominant long-run predictor is contact quality; pitchers with low barrel rates revert to below-average BABIP regardless of early outcomes.",
        "conditions": "Regression sharpest in samples under 250 plate appearances; interacts with defensive quality; high-altitude parks slow downward regression by sustaining fly-ball outcomes.",
        "magnitude": "Over 400+ plate appearances, xwOBA explains roughly 65-70 % of variance in actual wOBA; a starter with xERA of 3.80 but actual ERA of 5.10 in the first 8 starts is more likely to post a 3.90 than a 5.10 ERA over the next 8.",
        "links": ["run_prevention_via_contact_suppression", "sequencing_and_cluster_luck", "defensive_efficiency_conversion", "park_factor_run_modulation"],
    },
    {
        "slug": "leverage_index_conversion",
        "title": "Leverage-Index Conversion",
        "summary": "Generating disproportionate win-probability swing in high-leverage plate appearances; performance quality at leverage index above 2.0 determines game outcomes far more than equivalent performance in low-leverage contexts.",
        "stat_signature": "Win-probability-added per high-leverage plate appearance exceeding +0.05; wOBA split between leverage index above and below 1.5 exceeding 40 points; clutch score deviating from pLI-adjusted expectation by more than 0.5 over a season.",
        "mechanism": "Win probability changes non-linearly with game state; a single run in the eighth inning of a tie game moves win probability 15-20 points while the same run in the first inning moves it 3-4 points; the leverage multiplier amplifies both good and bad outcomes.",
        "conditions": "High-leverage states cluster in late close games with runners in scoring position; split performance across leverage tiers shows partial year-to-year stability, suggesting a mix of repeatable skill and variance.",
        "magnitude": "Season-level WPA ranges of 5-8 wins separate elite high-leverage performers from average ones; a 30-wOBA-point improvement at leverage index above 2.0 translates to roughly 2-3 additional win shares per season.",
        "links": ["bullpen_leverage_chaining", "high_leverage_strand_prevention", "big_inning_generation", "strikeout_run_value_conversion"],
    },
    {
        "slug": "bullpen_leverage_chaining",
        "title": "Bullpen Leverage Chaining",
        "summary": "Preserving leads by routing high-strikeout relief arms into the highest-leverage game states rather than predetermined innings, maximizing inherited and created strand rates.",
        "stat_signature": "Late-inning strand rate above 78 %; inherited-runner-scored rate below 24 %; top-reliever entry leverage index averaging above 1.8; fireman usage (mid-inning with runners) above 25 % of elite-arm appearances.",
        "mechanism": "Win-probability swing per half-inning peaks with runners on and a one-to-two-run lead; routing the best run-suppression arm to that moment maximizes expected-win preservation and resets lineup familiarity as a side benefit.",
        "conditions": "Most valuable in one-run games entering the seventh inning or later; requires at least two high-leverage-capable arms; attenuated in blowouts where leverage is uniformly low.",
        "magnitude": "Leverage-optimal deployment is worth an estimated 2-4 additional wins per 162 games at the roster level; inherited-runner strand rate gap of 10-15 points between optimal-chain and role-fixed deployment at the same reliever quality.",
        "links": ["leverage_index_conversion", "high_leverage_strand_prevention", "strikeout_run_value_conversion", "times_through_order_decay"],
    },
    {
        "slug": "power_isolation_run_compression",
        "title": "Power and Isolated-Power Run Compression",
        "summary": "Extra-base power shortens the sequence required to score; home runs produce runs without sequenced baserunners, compressing variance and reducing reliance on strand-rate luck.",
        "stat_signature": "Isolated power (SLG minus BA) above .200; HR-per-fly-ball rate above 18 %; share of runs scoring via home run above 35 %.",
        "mechanism": "A home run scores all baserunners plus the batter in one plate appearance, eliminating the sequencing randomness governing multi-hit innings and compressing the run-scoring distribution toward a consistent floor.",
        "conditions": "Most impactful in neutral-to-hitter park environments; high-strikeout lineups accept higher variance in exchange for compressed sequencing risk; altitude and wind modulate HR-per-fly-ball rate.",
        "magnitude": "Lineups above 35 % HR-contribution to runs show strand-rate variance 8-10 points tighter than contact-first lineups; each 1-point increase in ISO corresponds to roughly 0.12-0.18 additional runs per game at the lineup level.",
        "links": ["big_inning_generation", "sequencing_and_cluster_luck", "park_factor_run_modulation", "speed_and_baserunning_advancement"],
    },
    {
        "slug": "speed_and_baserunning_advancement",
        "title": "Speed and Baserunning Advancement",
        "summary": "Manufacturing run-expectancy gains via extra-base advancement and stolen bases; advancing an extra base shifts the runner to a materially higher run-expectancy state without consuming an out.",
        "stat_signature": "Extra-base-taken rate above 45 % on opportunities; stolen-base success rate above 75 % (the break-even threshold); run-expectancy added per first-to-third advancement on a single approximately 0.18 runs.",
        "mechanism": "First-to-third on a single converts an 0.85-run expected-value state to a 1.19-run state; stolen bases shift run expectancy similarly when success probability exceeds approximately 73 %; slow catchers or pitchers with poor pickoff control raise the marginal value.",
        "conditions": "Baserunning gains largest against infield alignments that pull outfielders shallow; stolen-base value rises with two outs as the runner position matters more for the next single; diminishes with two outs when advancement run-expectancy gains are smaller.",
        "magnitude": "Elite baserunning clubs add 8-14 runs per season above average on advancement alone; a 10-percentage-point gain in extra-base-taken rate contributes roughly 4-6 additional runs per 162 games at the team level.",
        "links": ["power_isolation_run_compression", "big_inning_generation", "leverage_index_conversion"],
    },
    {
        "slug": "defensive_efficiency_conversion",
        "title": "Defensive-Efficiency Conversion",
        "summary": "Turning balls in play into outs at rates above expectation, suppressing opponent BABIP below the contact-quality floor and preventing runs that pitching alone cannot avoid.",
        "stat_signature": "Defensive efficiency ratio above 0.710; outs-above-average above +10 for elite defenders; team BABIP-against below expected BABIP by 8+ points.",
        "mechanism": "Even low-exit-velocity balls in play carry non-zero BABIP; range, positioning, and arm accuracy convert borderline balls to outs; each avoided hit removes roughly 0.45 expected runs from the inning.",
        "conditions": "Largest gains on medium-depth fly balls and infield gap grounders; artificial surfaces raise grounder BABIP, compressing the conversion opportunity; shift-rule changes reallocate some value to lateral range.",
        "magnitude": "Top defensive units suppress team BABIP by 8-12 points below contact-quality expectation, translating to roughly 20-30 fewer hits per season and approximately 18-25 runs saved — about 1.8-2.5 wins above a league-average defense.",
        "links": ["batted_ball_regression_to_expected", "run_prevention_via_contact_suppression", "ground_ball_double_play_suppression", "sequencing_and_cluster_luck"],
    },
    {
        "slug": "ground_ball_double_play_suppression",
        "title": "Ground-Ball and Double-Play Suppression",
        "summary": "Erasing baserunners via ground-ball inducement; double plays are the highest-leverage out event because they remove a base-out combination and reset run expectancy in a single pitch.",
        "stat_signature": "Ground-ball rate above 50 %; double-plays turned per opportunity above 14 %; run-expectancy reset per double play approximately 0.80-0.95 runs in bases-occupied, zero-out state.",
        "mechanism": "A ground ball with runner on first and zero or one out carries a 40-55 % double-play probability for ground-ball specialists; the double play removes two outs and one baserunner in a single event, producing a run-expectancy shift second only to a strikeout per pitch.",
        "conditions": "Most valuable with fast infields on slower grass; sinker specialists who keep the ball low generate the most opportunities; attenuated with two outs when no double play is possible.",
        "magnitude": "Pitchers above 50 % ground-ball rate generate roughly 0.3-0.5 more double plays per nine innings than fly-ball pitchers; each additional double play saves approximately 0.75-0.85 expected runs versus a single-out resolution of the same state.",
        "links": ["run_prevention_via_contact_suppression", "defensive_efficiency_conversion", "high_leverage_strand_prevention", "pitch_count_efficiency_durability"],
    },
    {
        "slug": "park_factor_run_modulation",
        "title": "Park-Factor Run Modulation",
        "summary": "The ballpark environment scales run and home-run totals systematically; expected game totals and pitching lines require park adjustment before cross-venue comparisons are meaningful.",
        "stat_signature": "Park run factor above 1.08 for hitter-friendly environments; HR park factor above 1.15 in power-amplifying parks; expected game total shift of 0.5-1.2 runs in extreme parks relative to neutral baseline.",
        "mechanism": "Altitude reduces air density, extending fly-ball carry 3-8 % per thousand feet; short foul territories reduce foul-out opportunities; temperature shifts ball-flight distance 1-3 % per 10-degree Fahrenheit change; asymmetric dimensions create gap-dependent extra-base rates.",
        "conditions": "Park effects most consistent for HR rate; BABIP modulation is noisier and confounds with defense quality; 3-year rolling park factors more reliable than single-season estimates.",
        "magnitude": "Extreme hitter-friendly parks add 0.8-1.2 runs per game relative to neutral; HR park factors above 1.20 increase expected long-ball rate by 18-22 %; park-adjusted ERA differences of 0.30-0.45 between the most and least run-friendly environments.",
        "links": ["power_isolation_run_compression", "batted_ball_regression_to_expected", "run_prevention_via_contact_suppression"],
    },
    {
        "slug": "times_through_order_decay",
        "title": "Times-Through-the-Order Decay",
        "summary": "Hitters gain familiarity each successive time facing the same starter; wOBA-against rises measurably from the first to the third trip through the lineup, with the steepest declines for shallow repertoires.",
        "stat_signature": "Second-time-through wOBA-against elevated 15-20 points above first-time-through; third-time-through elevated a further 10-15 points; total first-to-third penalty of 25-35 wOBA points for average starters.",
        "mechanism": "Hitters calibrate timing, release-point cues, and pitch recognition across at-bats; by the third trip they have seen every pitch in the starter's mix; pitchers without tunneling variation and velocity hold face compounding calibration disadvantage.",
        "conditions": "Decay sharpest for two-pitch starters with predictable sequencing; mitigated by four-pitch repertoires and strong tunneling variety; bullpen availability determines whether the penalty is acted upon.",
        "magnitude": "Expected run-prevention gain of 0.3-0.5 runs per game from removing a starter before the third trip; wOBA-against the third time through is the single strongest predictor of optimal starter pull-point leverage.",
        "links": ["pitch_count_efficiency_durability", "bullpen_leverage_chaining", "strikeout_run_value_conversion", "two_strike_approach_conversion"],
    },
    {
        "slug": "high_leverage_strand_prevention",
        "title": "High-Leverage Strand Prevention",
        "summary": "Stranding inherited and self-created runners in scoring situations is the terminal run-prevention skill; strand rate at leverage index above 1.5 captures true late-inning pitching value.",
        "stat_signature": "Left-on-base rate above 75 %; runners-in-scoring-position wOBA allowed below .310; inherited-runner-scored rate below 24 %; two-strike RISP wOBA below .260 for elite late-inning relievers.",
        "mechanism": "With runners in scoring position, high-strikeout arms strand runners at higher rates by eliminating both advancement and contact risk simultaneously; weak contact with runners on is more costly than a walk because runners advance on grounders.",
        "conditions": "Most stable for high-strikeout, low-walk relievers; partially influenced by defensive alignment on contact with runners on; highest-leverage state is bases loaded with one out, where expected run output ranges from 1.6 to 2.2 runs.",
        "magnitude": "Top strand-rate relievers prevent roughly 0.30-0.45 additional runs per nine innings above average; inherited-runner strand rate gap of 15-20 points between elite and replacement-level arms in high-leverage use.",
        "links": ["bullpen_leverage_chaining", "leverage_index_conversion", "strikeout_run_value_conversion", "walk_economy_baserunner_inflation", "ground_ball_double_play_suppression"],
    },
    {
        "slug": "pitch_count_efficiency_durability",
        "title": "Pitch-Count Efficiency and Starter Durability",
        "summary": "Extending starters deeper limits bullpen exposure; middle-relief ERA runs roughly 0.4-0.6 runs above the starter ERA pool, so each starter inning saved from the bullpen carries direct run-prevention value.",
        "stat_signature": "Pitches per inning below 15.5; pitches per plate appearance below 3.7; innings per start above 6.0; quality-start rate above 55 %; bullpen innings per game below 3.0 for starter-dependent systems.",
        "mechanism": "Efficient pitch counts arise from first-pitch-strike rate and low walk rate; each additional starter inning displaces a middle-reliever inning worth 0.45-0.60 more expected runs; the times-through-the-order penalty ultimately caps how deep even efficient starters can go.",
        "conditions": "Durability gains largest when available middle relief is below average quality; less impactful with a deep, high-quality bullpen; times-through-the-order familiarity constrains the ceiling regardless of pitch-count efficiency.",
        "magnitude": "Teams whose starters average 6.5 innings per start save roughly 30-40 bullpen appearances per season over a 5.5-inning average, worth approximately 12-20 run-prevention runs per season.",
        "links": ["times_through_order_decay", "ground_ball_double_play_suppression", "walk_economy_baserunner_inflation", "bullpen_leverage_chaining"],
    },
    {
        "slug": "two_strike_approach_conversion",
        "title": "Two-Strike Approach Conversion",
        "summary": "Two-strike counts shift both hitter and pitcher behavior materially; the run-value gap between those who adapt (pitchers who shift mix, hitters who maintain discipline) versus those who do not is substantial.",
        "stat_signature": "Two-strike batting average below even-count BA by 60+ points; two-strike chase rate above 35 %; two-strike strikeout rate above 55 % of two-strike plate appearances; contact rate below 70 % in two-strike counts.",
        "mechanism": "Hitters expand zone coverage with two strikes to avoid called third strikes; pitchers exploit this by locating off the black; contact-first hitters who shorten the swing and foul off putaway pitches reduce the pitcher's leverage by resisting expansion pitches.",
        "conditions": "Leverage highest against high-strikeout hitters with wide two-strike zone expansion rates; attenuated against two-strike contact specialists who consistently foul off putaway pitches and work deeper counts.",
        "magnitude": "Two-strike OPS is roughly 0.200-0.250 points below neutral-count OPS league-wide; pitchers who deliberately shift pitch mix with two strikes post strikeout rates 3-5 percentage points above their even-count rate.",
        "links": ["strikeout_run_value_conversion", "times_through_order_decay", "high_leverage_strand_prevention", "run_prevention_via_contact_suppression"],
    },
]
