"""Person-free concept spec: Tennis — MomentumSwings family."""
from __future__ import annotations

SPORT = "Tennis"
FAMILY = "MomentumSwings"

CONCEPTS: list[dict] = [
    {
        "slug": "consecutive_games_run_distribution",
        "title": "Consecutive-Games Run Distribution",
        "summary": "Full distribution of unbroken game-winning streaks within a set; runs of 4+ occur in ~18-22% of sets with a heavier right tail than independent-game models predict.",
        "stat_signature": "Median run 1-2 games; 4+ game runs in ~18-22% of sets; 5+ runs in ~8-10% on fast surfaces where hold rates exceed 75%.",
        "mechanism": "Each game won raises next-game win probability ~3-6 pp above baseline hold rate via compounding confidence and opponent serve-pressure exposure after a break.",
        "conditions": "Most pronounced on fast surfaces (hold rate >75%) where a single break cascades; amplified in deciding sets under fatigue.",
        "magnitude": "A four-game run shifts set-win probability 35-50 pp from the pre-run baseline; each extension game adds roughly 8-12 pp.",
        "links": ["break_back_immediate_response", "double_break_swing_magnitude", "deciding_set_swing_amplitude", "score_from_behind_in_set"],
    },
    {
        "slug": "break_to_break_swing_chain",
        "title": "Break-to-Break Swing Chain",
        "summary": "Conditional probability that a break is immediately countered by a break in the very next game, producing a see-saw exchange that prevents consolidation of a lead.",
        "stat_signature": "Counter-break probability immediately after a break: ~28-35% on clay, ~20-26% on hard, ~18-22% on grass versus set-average break rates of 30%, 24%, and 20% respectively.",
        "mechanism": "The freshly broken server channels heightened arousal into return aggression; the new leader may briefly reduce intensity during the consolidation transition, opening a narrow defensive gap.",
        "conditions": "Amplified when the preceding break required escaping multiple break points, leaving the breaker emotionally depleted. More frequent in early sets before patterns stabilise.",
        "magnitude": "Counter-break game carries a break probability 6-12 pp above set-average; the majority of breaks (65-72%) are held without immediate reply.",
        "links": ["consolidation_hold_after_break", "break_back_immediate_response", "saved_break_point_momentum", "consecutive_games_run_distribution"],
    },
    {
        "slug": "consolidation_hold_after_break",
        "title": "Consolidation-Hold Momentum",
        "summary": "Probability of holding serve in the game immediately after breaking — the critical step converting a single break into a durable scoreboard advantage.",
        "stat_signature": "Tour-average consolidation hold rate: ~68-74% on hard, ~62-68% on clay. Conditional on consolidating, set-win probability jumps to ~78-84% from a pre-break ~50%.",
        "mechanism": "Holding to consolidate locks in structural asymmetry and terminates the counter-break window; failure to hold resets parity and nullifies the break swing entirely.",
        "conditions": "Consolidation rate is higher when the break was achieved cleanly (first break point converted) and on surfaces with baseline hold rates above 70%.",
        "magnitude": "The gap between consolidating and being broken back represents a ~20-25 pp set-win swing; each pp in consolidation rate shifts set-win probability ~0.6-0.9 pp.",
        "links": ["break_to_break_swing_chain", "double_break_swing_magnitude", "break_back_immediate_response", "converted_break_point_carryover"],
    },
    {
        "slug": "double_break_swing_magnitude",
        "title": "Double-Break Swing Magnitude",
        "summary": "Set-win-probability swing when a second break is secured, a near-dominant event requiring the opponent to win two consecutive break games to recover.",
        "stat_signature": "Double break raises set-win probability to ~92-96%. Swing from one break to two: ~14-18 pp; from level to double break: ~38-46 pp above 50%.",
        "mechanism": "A two-game structural deficit cannot be erased without back-to-back breaks — an unlikely compound event — while every hold by the leader advances set completion without requiring further breaks.",
        "conditions": "Most consequential when the double break is achieved early (3-0 or 4-0 score). On clay, double breaks occur more frequently per set due to lower service dominance.",
        "magnitude": "Sets with a double break are won by the breaker at 92-96% frequency; double-break-back recoveries represent the rarest momentum reversals in the sport.",
        "links": ["consolidation_hold_after_break", "consecutive_games_run_distribution", "score_from_behind_in_set", "momentum_after_squandered_lead"],
    },
    {
        "slug": "saved_break_point_momentum",
        "title": "Saved-Break-Point Momentum Surge",
        "summary": "Elevated break-creation rate for a server who escapes a game containing three or more break points, where surviving sustained danger triggers an offensive momentum shift.",
        "stat_signature": "Servers saving 3+ break points then holding show a next-game break-creation rate ~4-8 pp above set-average; effect decays to baseline within two games.",
        "mechanism": "Escaping sustained pressure builds confidence while forcing the opponent to process a missed conversion opportunity; the asymmetric psychological residue briefly shifts initiative to the surviving server.",
        "conditions": "Most pronounced when the escape occurs late in the set (4-4 or 5-5) and when the server escaped via winner rather than opponent error.",
        "magnitude": "The 4-8 pp next-game break-rate elevation is a within-set micro-momentum marker; primary value is directional signal, not a structural match-level predictor.",
        "links": ["break_to_break_swing_chain", "converted_break_point_carryover", "love_hold_momentum_signal", "run_of_points_within_game"],
    },
    {
        "slug": "converted_break_point_carryover",
        "title": "Converted-Break-Point Carryover",
        "summary": "Whether securing a break after a hard-fought multi-deuce game carries elevated consolidation-hold rate into the following service game, distinguishing momentum-building breaks from energy-draining ones.",
        "stat_signature": "Breaks on first break point yield ~52-58% clean break-then-hold rate versus ~46-52% for breaks requiring 3+ deuce cycles, a 4-6 pp consolidation gap.",
        "mechanism": "A cleanly converted break preserves physical and mental resources for the consolidation game; extended breaks deplete both players but leave the newly broken server with the momentum-recover incentive.",
        "conditions": "Carryover differential is largest on fast surfaces where energy-per-point expenditure is high and extended games are atypical. Narrows on clay where long games are routine.",
        "magnitude": "The 4-6 pp consolidation gap is small relative to the baseline ~68-74% consolidation rate; hold quality matters at the margin, not as a dominant effect.",
        "links": ["consolidation_hold_after_break", "saved_break_point_momentum", "deuce_game_swing_leverage", "love_hold_momentum_signal"],
    },
    {
        "slug": "tiebreak_mini_break_swing",
        "title": "Tiebreak Mini-Break Swing",
        "summary": "Compressed win-probability swing from a single mini-break in a tiebreak — the highest leverage momentum event on a per-point basis given the short path to set resolution.",
        "stat_signature": "First mini-break raises tiebreak win probability from 50% to ~57-61%. Leading 2-1 in mini-breaks (e.g., 4-2): ~72-78%. Each mini-break worth ~10-14 pp versus ~3-5 pp per held service game.",
        "mechanism": "A tiebreak removes re-serve opportunity and compresses seven equally weighted points toward the outcome threshold; each mini-break removes a margin-for-error unit from the loser faster than any within-set mechanism.",
        "conditions": "Mini-break leverage peaks at 3-all or 4-all with one mini-break outstanding; the first scoring event from level is the highest individual-point swing in the match outside of match point.",
        "magnitude": "A double mini-break lead (e.g., 5-3) raises tiebreak win probability to ~85-90%; the per-point swing is 2-4× the equivalent game-win swing in the set.",
        "links": ["consecutive_games_run_distribution", "deciding_set_swing_amplitude", "run_of_points_within_game", "serve_for_set_collapse_swing"],
    },
    {
        "slug": "love_hold_momentum_signal",
        "title": "Love-Hold Momentum Signal",
        "summary": "How holding serve to love versus surviving multiple deuces changes the next-game scoring trajectory, isolating the quality-of-hold momentum signal across successive service games.",
        "stat_signature": "After a love-hold, next-game break-creation rate is ~3-5 pp above set baseline. Love-holds occur in ~18-25% of service games on fast surfaces and ~10-15% on clay.",
        "mechanism": "A love-hold signals rally-initiation control and conserves energy for the return game; the opponent's return game rhythm is disrupted by the lack of any pressure resistance in the preceding game.",
        "conditions": "Signal strongest when the love-hold follows a comfortable opponent hold (no deuce), amplifying dominance contrast. Weakest at 3-3 or later in close sets where stakes neutralise rhythm effects.",
        "magnitude": "The 3-5 pp next-game break-rate elevation is a directional micro-signal whose value accumulates across multiple consecutive dominant holds rather than as a single-game predictor.",
        "links": ["saved_break_point_momentum", "converted_break_point_carryover", "deuce_game_swing_leverage", "run_of_points_within_game"],
    },
    {
        "slug": "deuce_game_swing_leverage",
        "title": "Extended-Deuce Game Swing Leverage",
        "summary": "Outsized momentum effect of winning a game requiring four or more deuce cycles, where accumulated psychological investment amplifies the next-game scoring shift beyond the game's face value.",
        "stat_signature": "Games reaching 4+ deuces (~3-5% of all games) are followed by elevated next-game break probability of 6-10 pp above set baseline for the winner.",
        "mechanism": "Extended cycles generate compounding energy expenditure and emotional investment; the loser absorbs simultaneous physical depletion and psychological deflation while the winner gains disproportionate confidence currency.",
        "conditions": "Effect is larger in high-stakes moments (5-5 in a deciding set) and when the marathon game resolved on a break rather than a hold, adding structural damage to the psychological impact.",
        "magnitude": "The post-marathon break-rate elevation of 6-10 pp decays within two games; it is a transient amplifier rather than a persistent structural shift.",
        "links": ["love_hold_momentum_signal", "converted_break_point_carryover", "saved_break_point_momentum", "run_of_points_within_game"],
    },
    {
        "slug": "serve_for_set_collapse_swing",
        "title": "Serving-for-Set Collapse Swing",
        "summary": "Momentum reversal when a player is broken while serving for a set, flipping a near-certain set conversion into a high-leverage swing toward the opponent and frequently extending the set to a tiebreak.",
        "stat_signature": "Break-while-serving-for-the-set in ~14-18% of set-clinching opportunities. Following such a break, the set reaches a tiebreak in ~55-60% of cases; opponent wins the next game at ~62-68%.",
        "mechanism": "The psychological cost of failure peaks at set point; the returner's aggression spikes and the server's first-serve percentage drops, producing a structural opening. A successful break erases the full structural advantage and resets to 6-6.",
        "conditions": "Collapse rate is slightly elevated when the leader already failed to serve out at 5-4 and is attempting again at 6-5. Also higher in best-of-three where each set carries greater match-probability weight.",
        "magnitude": "Set-win probability drops from ~88-92% (serving for set at 5-4) to ~50-55% after being broken — a 35-40 pp single-game swing among the largest in the sport.",
        "links": ["tiebreak_mini_break_swing", "momentum_after_squandered_lead", "break_back_immediate_response", "double_break_swing_magnitude"],
    },
    {
        "slug": "break_back_immediate_response",
        "title": "Immediate Break-Back Response Window",
        "summary": "Elevated conditional break probability in the single game directly after being broken — the highest break-likelihood game type and the primary mechanism for parity restoration.",
        "stat_signature": "Break-back probability immediately after being broken: ~28-36% tour-wide versus set-average break rate of ~22-26%. Elevated window lasts one game; reverts to baseline within 1-2 pp two games later.",
        "mechanism": "The freshly broken server channels heightened arousal into return aggression on the very next return game; the opponent transitioning to the consolidation hold may briefly reduce intensity.",
        "conditions": "Break-back probability is higher when the preceding break was unexpected (server had held comfortably for several games) and on clay where return-game leverage is structurally higher.",
        "magnitude": "The 6-12 pp elevation above set-average is the largest single-game break-probability spike outside of tiebreak mini-breaks, defining the counter-momentum window that makes break chains common.",
        "links": ["break_to_break_swing_chain", "consolidation_hold_after_break", "momentum_drought_consecutive_breaks", "saved_break_point_momentum"],
    },
    {
        "slug": "run_of_points_within_game",
        "title": "Within-Game Point-Run Streaks",
        "summary": "Distribution of consecutive points won within a single game and the conditional run-extension probability — the point-level micro-momentum layer beneath game-level swings.",
        "stat_signature": "Runs of 3+ consecutive points occur in ~60-68% of games. Winning the first two points of a game raises game-win probability to ~80-84% from baseline ~62-68% on serve.",
        "mechanism": "A server leading 30-0 or 40-0 can serve more aggressively with lower risk, amplifying the conditional probability cascade; early point runs reveal rhythm control and raise error cost for the returner.",
        "conditions": "Run-extension effects are largest when the server leads by two points (30-0, 40-15) versus trailing (0-30, 15-40), where game-win probability diverges most steeply from 50%.",
        "magnitude": "The game-win probability gap between 30-0 and 0-30 is roughly 60-65 pp; within-game point runs are the highest-resolution momentum layer but decay within the game without persistent cross-game signal.",
        "links": ["love_hold_momentum_signal", "deuce_game_swing_leverage", "tiebreak_mini_break_swing", "saved_break_point_momentum"],
    },
    {
        "slug": "score_from_behind_in_set",
        "title": "Score-from-Behind Set Recovery",
        "summary": "Conditional set-win probability after falling behind by a specified game margin, defining the deficit thresholds beyond which a momentum reversal becomes statistically improbable.",
        "stat_signature": "Trailing 0-3: set-win probability ~8-12%. Trailing 0-4: ~3-6%. Recoveries from 0-5 deficits occur in ~1-2% of sets on hard courts.",
        "mechanism": "Each lost game compounds the structural deficit; recovery requires winning two consecutive break games without conceding any, a multi-step conditional whose probability declines exponentially with deficit size.",
        "conditions": "Recovery probability is marginally higher on clay where service dominance is lower. Also slightly higher when the deficit arose from a single run rather than distributed breaks.",
        "magnitude": "The 0-3 to set-win path requires winning 6 of 9 remaining games with above-average break rate — a compound probability of ~8-12% reflecting genuine but limited reversal potential.",
        "links": ["consecutive_games_run_distribution", "double_break_swing_magnitude", "momentum_after_squandered_lead", "deciding_set_swing_amplitude"],
    },
    {
        "slug": "momentum_carry_across_sets",
        "title": "Cross-Set Momentum Carry",
        "summary": "Conditional first-game and early-break-rate shift carried by the set winner into the next set, measuring how strongly a decided set's momentum persists past the inter-set reset.",
        "stat_signature": "Set winners win the first game of the next set at ~52-56% versus a baseline hold rate of ~65-72% on serve. Early-break rate in the new set is 3-6 pp above average for the set winner.",
        "mechanism": "The 90-second inter-set reset is too brief for full recalibration; the winner holds elevated confidence while the loser's recalibration takes 2-4 games, creating a transient initiative advantage.",
        "conditions": "Cross-set carry is larger after decisive set wins (6-1, 6-2) than after tiebreak wins where both players were equally invested. Stronger in best-of-five formats.",
        "magnitude": "The 3-6 pp first-game advantage decays to noise by game four; cross-set carry shapes early-set dynamics without determining set outcome.",
        "links": ["set_flip_momentum_after_loss", "first_set_swing_match_anchor", "deciding_set_swing_amplitude", "changeover_momentum_interruption"],
    },
    {
        "slug": "deciding_set_swing_amplitude",
        "title": "Deciding-Set Swing Amplitude",
        "summary": "Elevated game-run and break-swing volatility in a final deciding set under maximal stakes and fatigue, where individual momentum exchanges carry the largest match-win-probability impact.",
        "stat_signature": "First break in a deciding set raises match-win probability to ~72-78% (versus ~68-74% for an equivalent first break in set one). Deciding-set break rate is ~4-8 pp above match-average.",
        "mechanism": "Fatigue and compounded psychological investment from preceding sets amplify each momentum event; service reliability typically declines 3-6 pp from set-one baselines, structurally increasing break rate.",
        "conditions": "Swing amplitude is highest after physically demanding matches (extended sets, multiple tiebreaks). Also elevated in no-advantage final-set tiebreak formats where variance compresses into a single high-leverage game.",
        "magnitude": "Each game in a deciding set carries 2-4 pp more match-win probability than the equivalent game in earlier sets — the highest per-game leverage in the match.",
        "links": ["consecutive_games_run_distribution", "tiebreak_mini_break_swing", "score_from_behind_in_set", "momentum_carry_across_sets"],
    },
    {
        "slug": "momentum_drought_consecutive_breaks",
        "title": "Consecutive-Breaks-Against Drought",
        "summary": "Persistence of a streak of dropped service games and the conditional probability that the run extends — the inverse-momentum counterpart to a holding run and a marker of collapsed serve reliability.",
        "stat_signature": "After dropping two consecutive service games, probability of dropping a third is ~32-38% (versus set-average ~22-26%). Streaks of 3+ consecutive service losses occur in ~5-8% of sets and correlate with eventual set loss at 85-92%.",
        "mechanism": "Repeated service losses compound mechanical disruption (first-serve percentage drops ~5-8 pp across a losing streak) and psychological pressure in a feedback loop; the returner simultaneously builds rhythm and reduces error rate.",
        "conditions": "More frequent on clay where breaks are structurally common, in later sets under fatigue, and after squandered leads where the psychological shock accelerates mechanical deterioration.",
        "magnitude": "Two consecutive service losses raise the third-break probability 6-12 pp above baseline; correlation with set-loss at 85-92% makes it a strong within-set momentum indicator of impending set completion.",
        "links": ["break_back_immediate_response", "score_from_behind_in_set", "consecutive_games_run_distribution", "momentum_after_squandered_lead"],
    },
    {
        "slug": "momentum_after_squandered_lead",
        "title": "Squandered-Set-Lead Reversal",
        "summary": "Dynamics when a player who held a break advantage is pegged back to level, measuring heightened reversal risk and the swing toward the recovering opponent.",
        "stat_signature": "A player broken back to level after holding a break lead loses the set at a rate of ~48-54% (near-coin-flip) versus the ~78-84% win rate they held while ahead by a break.",
        "mechanism": "Being pegged back combines structural reset (returning to parity) with psychological deflation from squandering a position of strength; the recovering opponent gains momentum from the successful break-back and enters the next game with elevated confidence.",
        "conditions": "Reversal swing is largest when the lead was held for multiple games (not immediately broken back) and when the recovery occurred late in the set under high pressure.",
        "magnitude": "The swing from one-break-up to level represents a ~24-34 pp set-win probability collapse; the momentum-shift from squandered lead regularly produces a subsequent run for the recovering player.",
        "links": ["double_break_swing_magnitude", "serve_for_set_collapse_swing", "score_from_behind_in_set", "break_to_break_swing_chain"],
    },
]

# Stubs referenced in links but not expanded as full concepts (cross-family references)
_STUB_REFS = [
    "set_flip_momentum_after_loss",   # referenced in links from momentum_carry_across_sets
    "first_set_swing_match_anchor",   # referenced in links from momentum_carry_across_sets
    "changeover_momentum_interruption",  # referenced in links from momentum_carry_across_sets
]
