"""Soccer — OfficialAdaptation concept spec.

Dense, person-free nodes on how teams calibrate style to a referee's tendencies.
Descriptive only; markets are efficient.
"""
from __future__ import annotations

SPORT = "Soccer"
FAMILY = "OfficialAdaptation"

CONCEPTS: list[dict] = [
    {
        "slug": "card_threshold_calibration",
        "title": "Referee Card-Threshold Calibration",
        "summary": "Tackling aggression is dialed to a referee's fouls-per-card ratio; strict officials compress the tactical-foul budget and push teams toward shepherding rather than challenging.",
        "stat_signature": "Fouls-per-yellow ratio spans 3–5 (strict) to 8–12 (lenient) across referees; committed-foul rate shifts ±15–25 % from season norm when the assigned official sits in the extreme quartiles.",
        "mechanism": "An early caution removes 65+ min of foul-budget; teams preemptively reduce mid-block challenges under strict officials, accepting more carried-ball progress to preserve numerical advantage.",
        "conditions": "Concentrates in defensive thirds for teams in the bottom half of clean-sheet rate; amplified when a 10-man scenario carries a high expected-goal swing (≥1.2 xG delta).",
        "magnitude": "Fouls per 90 shifts ~10–18 % between strict and lenient referee assignments, with the largest delta in the 20–60 min window before most bookings accumulate.",
        "links": ["tactical_foul_budgeting", "first_booking_restraint", "foul_cluster_management", "physical_duel_standard_read"],
    },
    {
        "slug": "advantage_play_anticipation",
        "title": "Advantage-Tendency Anticipation",
        "summary": "Attacking units sustain transitions through contact based on a referee's historical play-on rate rather than automatically breaking off attacks.",
        "stat_signature": "Play-on rate after fouls spans 35–55 % across referee cohorts; attacking transitions sustained through contact rise 8–14 % under high-advantage officials versus a 5–7 % drop under low-advantage ones.",
        "mechanism": "When advantage is reliably signalled, forwards drive through contact to preserve open-space momentum; defenders learn that transition contact is less penalised, adjusting recovery-sprint commitment.",
        "conditions": "Strongest for fast-transition systems where continued possession in space exceeds a 30 m set-piece; diminishes for possession-heavy styles that prefer set-piece placement over continuation.",
        "magnitude": "Counter-attack completion rate (fouled-on possession to shot) varies ~12 percentage points between the highest and lowest advantage-playing referee quartiles.",
        "links": ["advantage_recall_exploitation", "whistle_quickness_adaptation", "restart_speed_exploitation"],
    },
    {
        "slug": "first_booking_restraint",
        "title": "Post-First-Booking Restraint",
        "summary": "Once a teammate is cautioned, other defensive players modulate tackle selection to shield the booked player from second-yellow exposure.",
        "stat_signature": "Tackle attempts for the cautioned player drop ~30–45 % in the 30 min post-booking; team-wide second-yellow rate is 4–7 % under strict officials versus 1–2 % under lenient ones.",
        "mechanism": "A cautioned player becomes a liability in 50-50 duels; teammates redistribute pressing triggers so the booked player intercepts via positioning rather than contact, widening channels slightly.",
        "conditions": "Strongest when the booking occurs before the 60th minute and the cautioned player is a central midfielder or fullback whose role requires repeated dueling.",
        "magnitude": "Defensive duel count for cautioned players falls to roughly half the team-average rate; unbooked partners absorb ~20 % more duels in the subsequent 20 min window.",
        "links": ["card_threshold_calibration", "tactical_foul_budgeting", "foul_cluster_management"],
    },
    {
        "slug": "tactical_foul_budgeting",
        "title": "Tactical-Foul Budgeting",
        "summary": "Cynical stoppages are metered to a referee's cumulative-foul patience, concentrated in low-danger midfield zones and spaced temporally to avoid triggering a caution cascade.",
        "stat_signature": "Fouls-before-caution count spans 3–11 across officials; midfield-foul proportion rises to 65–75 % under patient officials versus 50–60 % under stricter ones.",
        "mechanism": "A predictable fouls-per-card quota lets a defensive shape exploit the allowance early (15–30 min), preserving the budget for critical late-phase counter-break suppression.",
        "conditions": "Deployed mainly by teams defending narrow leads from the 60–85 min window; pattern weakens when a referee deviates from historical booking pace or match tempo is unusually high.",
        "magnitude": "Teams with a tactical-foul identity commit 18–28 % more midfield stoppages than their season norm when assigned a lenient referee, compressing opponent attack-to-shot conversion.",
        "links": ["card_threshold_calibration", "foul_cluster_management", "stoppage_foul_positioning"],
    },
    {
        "slug": "var_intervention_awareness",
        "title": "VAR-Intervention Awareness",
        "summary": "Box contact and protest behavior adapt to a referee's VAR-utilisation tendency; defenders reduce arm-out positioning and attackers delay celebrations during reviewable phases.",
        "stat_signature": "Penalty-area body-check frequency drops ~20 % in high-VAR-use match contexts; goal-celebration duration increases 15–25 s when the official historically triggers VAR above the peer median.",
        "mechanism": "VAR converts previously deniable box contact into high-probability penalty awards; defenders who understand the official's trigger threshold shift from arms-out to jockeying, shrinking reviewable infringement surface.",
        "conditions": "Most pronounced in tight-line defensive systems and with referees who publicly acknowledge VAR consultation frequency; attenuates when the xG differential is large.",
        "magnitude": "Penalty concession rate inside the box is ~25–35 % lower for teams that adapt arm-positioning under high-VAR officials compared with teams maintaining static technique.",
        "links": ["penalty_contact_caution", "handball_interpretation_read", "set_piece_holding_caution"],
    },
    {
        "slug": "penalty_contact_caution",
        "title": "Penalty-Area Contact Caution",
        "summary": "Defensive challenge selection inside the box is calibrated to a referee's penalty-award rate, favouring jockeying and delay over committed challenges on ball-carriers.",
        "stat_signature": "Box-tackle attempt rate drops 15–30 % under referees whose penalty-per-box-challenge rate exceeds 12 %; arms-down defending posture rises correspondingly in the same matches.",
        "mechanism": "A high penalty-award rate sharply raises the expected-goal cost of a mistimed challenge; risk-averse defenders shepherd attackers toward the byline rather than attempting interceptions that may generate contact.",
        "conditions": "Strongest on wide-channel crosses where the defender chooses between a sliding block and covering the cutback; diminishes for back-to-goal challenges where shoulder contact is traditionally refereed more leniently.",
        "magnitude": "Penalties conceded per 90 correlates at r ≈ 0.35 with the assigned referee's career penalty-per-match rate, controlling for team defensive quality and match xG.",
        "links": ["var_intervention_awareness", "handball_interpretation_read", "set_piece_holding_caution", "physical_duel_standard_read"],
    },
    {
        "slug": "handball_interpretation_read",
        "title": "Handball-Interpretation Read",
        "summary": "Arm positioning in blocking and aerial duels is adjusted to a referee's handball strictness, reducing arm extension in defensive walls and aerial posture.",
        "stat_signature": "Handball concession rate spans 0.04–0.18 per 90 across referee cohorts; arm-tucked block rate in walls rises ~10 % when the assigned official's career handball rate exceeds 0.10 per match.",
        "mechanism": "Handball interpretation is the most subjectively variable infringement; defenders who track official-level application learn whether 'natural arm position' is interpreted strictly (shoulder-width) or leniently, adjusting wall geometry accordingly.",
        "conditions": "Largest effect in dead-ball defensive walls, headed clearance contexts, and wide-channel crossing situations; aerial-duel version amplified in leagues where VAR applies the 'unnatural position' standard strictly.",
        "magnitude": "Teams adapting arm geometry under strict-handball officials concede indirect box free kicks from handball roughly 30–40 % less frequently than their own-team norm.",
        "links": ["var_intervention_awareness", "penalty_contact_caution", "set_piece_holding_caution"],
    },
    {
        "slug": "simulation_penalty_sensitivity",
        "title": "Simulation-Penalty Sensitivity",
        "summary": "Forward contact-selling is suppressed once a referee demonstrates willingness to card simulation, shifting contact response toward shielding or continuation rather than going to ground.",
        "stat_signature": "Go-down-under-contact rate drops ~20–35 % in matches where the official has issued at least one simulation caution in the prior five matches; simulation-caution rate spans 0.05–0.20 per match by official.",
        "mechanism": "Simulation cards carry a double cost (yellow plus play restarted against); referees with a published history of booking play-acting raise the risk of contact-selling above the potential penalty reward, making shielding the dominant strategy.",
        "conditions": "Largest for forwards with above-average dribble attempts inside the box per 90; diminishes when match pace or contact rate is very high, making individual events harder to isolate.",
        "magnitude": "Expected penalty-award rate from box contact falls ~15 % under anti-simulation referees for teams with high go-to-ground tendencies; staying-upright specialists see minimal difference.",
        "links": ["penalty_contact_caution", "var_intervention_awareness", "advantage_play_anticipation"],
    },
    {
        "slug": "added_time_management_read",
        "title": "Added-Time Pattern Adaptation",
        "summary": "Substitution timing and deliberate time-wasting onset are shaped by a referee's historical added-time generosity, adjusting attacking urgency and closing-phase tempo accordingly.",
        "stat_signature": "Referee-level added time spans a 3–7 min range; time-wasting onset (keeper holding, corner-flag dallying) begins 4–6 min earlier under low-added-time officials; throw-in speed drops ~15 % for leading teams under generous officials.",
        "mechanism": "A trailing team knowing the official adds generously can sustain a patient high-press in the 85th minute rather than resorting to speculative long balls, improving shot quality during true remaining time.",
        "conditions": "Matters most in one-goal-margin matches in the 80–90 min window; trailing teams benefit from generous officials, leading teams from low-added-time ones; near-neutral at two-goal margins.",
        "magnitude": "xG accumulation in the 85–90 min window is 10–18 % higher per minute when trailing teams are assigned a referee in the top quartile of added-time generosity.",
        "links": ["restart_speed_exploitation", "stoppage_foul_positioning", "whistle_quickness_adaptation"],
    },
    {
        "slug": "set_piece_holding_caution",
        "title": "Set-Piece Holding Caution",
        "summary": "Shirt-pulling and grappling in the box on corners and free kicks are moderated to a referee's dead-ball contact enforcement, forcing defenders toward positional blocking.",
        "stat_signature": "Shirt-pull frequency in the box on corners drops ~25 % under referees whose dead-ball penalty rate exceeds 0.08 per match; cautions for holding on set pieces span 0.0–0.25 per match by official.",
        "mechanism": "Set-piece defending relies partly on early contact to disrupt runs; when a referee polices this, defenders must use boxing-out and positional technique rather than grappling, raising the aerial-duel premium for timing over strength.",
        "conditions": "Amplified for teams whose defensive set-piece scheme is heavily zonal-hybrid where marking contact is designed, and for opposition attackers with top-five aerial-duel-win rates.",
        "magnitude": "Penalty concession rate from corner situations is ~30–45 % higher under strict set-piece officials for teams in the bottom quartile of aerial-duel win rate that rely most on contact to compensate.",
        "links": ["var_intervention_awareness", "penalty_contact_caution", "handball_interpretation_read", "foul_cluster_management"],
    },
    {
        "slug": "advantage_recall_exploitation",
        "title": "Advantage-Recall Exploitation",
        "summary": "Continuation decisions in attack are adjusted to whether a referee reliably recalls play to award a free kick when a played advantage breaks down.",
        "stat_signature": "Referee-level advantage-recall rate (foul played on, advantage fails, free kick awarded) spans 20–60 % across officials; teams with identified high-recall referees attempt ball-retention after contact 10–15 % more often.",
        "mechanism": "When recall is reliable, players can attempt to retain possession after a foul without fully committing, knowing the set-piece fall-back exists; under low-recall officials the binary choice forces full commitment or an immediate fall.",
        "conditions": "Most relevant for midfield turnovers 25–35 m from goal with a partially open passing lane; recall exploitation diminishes inside the final third where continuation to shot is always dominant.",
        "magnitude": "Attempted-continuation rate after midfield contact correlates at r ≈ 0.28 with the assigned referee's recall rate, yielding roughly 1.5 additional continuation sequences per 90 in the intermediate third.",
        "links": ["advantage_play_anticipation", "whistle_quickness_adaptation", "restart_speed_exploitation"],
    },
    {
        "slug": "foul_cluster_management",
        "title": "Foul-Cluster Management",
        "summary": "Fouls are distributed across squad members to avoid concentrating cautions when a referee tracks individual repeat offenders.",
        "stat_signature": "Per-player foul standard deviation within a match rises ~18 % when the referee has a career repeat-offender caution rate above 0.15 per match; moderately fouling players are substituted ~5 min earlier under such officials.",
        "mechanism": "Referees with repeat-offender sensitivity issue a second yellow more predictably after three fouls from one player; distributing the foul load across eight outfield players removes the trigger condition.",
        "conditions": "Observable in matches where the team defends a lead with high-pressing intensity; less relevant for possession-dominant teams generating fewer stoppages.",
        "magnitude": "Second-yellow rate falls ~40 % for teams that demonstrably redistribute fouls under repeat-offender-sensitive referees relative to the same teams under non-tracking officials.",
        "links": ["card_threshold_calibration", "first_booking_restraint", "tactical_foul_budgeting"],
    },
    {
        "slug": "whistle_quickness_adaptation",
        "title": "Whistle-Quickness Adaptation",
        "summary": "Play-through-contact behavior is calibrated to how quickly a referee stops play, with attackers pressing on and defenders risking continuation challenges under slow-whistle officials.",
        "stat_signature": "Whistle-delay time (contact to stoppage) averages 0.4–1.8 s across referee cohorts; continued-action rate after contact rises ~12 % per additional 0.5 s of average whistle delay.",
        "mechanism": "A slow whistle creates a brief play-on window; attackers recognising this exploit the gap to shoot or play a final pass before the infringement is penalised, while defenders may attempt a second challenge.",
        "conditions": "Concentrates in the final third and within 20 m of goal where the post-contact window has highest xG value; in midfield the delay benefit is absorbed into possession rather than shots.",
        "magnitude": "Shot-from-contact-situation rate is ~8–14 % higher under slow-whistle officials relative to quick-whistle officials, controlling for match pace.",
        "links": ["advantage_play_anticipation", "advantage_recall_exploitation", "restart_speed_exploitation"],
    },
    {
        "slug": "restart_speed_exploitation",
        "title": "Quick-Restart Permissiveness Exploitation",
        "summary": "Free-kick and throw-in tempo is pushed toward the legal maximum when a referee consistently tolerates quick restarts without enforcing opponent-distance rules strictly.",
        "stat_signature": "Quick-restart attempt rate (within 5 s of signal) rises 20–35 % under referees in the top quartile of restart-distance-waiver frequency; opponents encroach 1.5–2.5 m closer than the mandated 9.15 m under such officials.",
        "mechanism": "A referee tolerating short distances converts set pieces into transitional situations with reduced defensive organisation; quick restarts yield higher first-pass quality and lower opponent compactness than static dead-ball setups.",
        "conditions": "Most exploitable for technically fluid sides that execute accurate short free kicks at pace; teams relying on long-ball set-piece delivery gain less from restart-distance tolerance.",
        "magnitude": "xG output from free-kick restarts is ~25 % higher per quick restart for ball-playing teams under high-permissiveness officials than under strict-distance ones.",
        "links": ["advantage_play_anticipation", "whistle_quickness_adaptation", "added_time_management_read"],
    },
    {
        "slug": "stoppage_foul_positioning",
        "title": "Stoppage-Foul Positioning",
        "summary": "The zone where fouls are committed to halt dangerous attacks is shaped by a referee's whistle-spot strictness, concentrating stoppages where the resulting free-kick xG is minimised.",
        "stat_signature": "Foul-zone distribution (proportion outside the central channel 25–35 m zone) varies ~12 percentage points between officials who award free kicks at the exact contact point versus those who spot the ball at the nearest advantageous position.",
        "mechanism": "A strict spot-placement referee removes the incentive to foul in wide channels to shift restart angle; teams concentrate tactical fouls wherever the resulting dead-ball xG is lowest — typically wide, deep zones.",
        "conditions": "Largest for compact-block defending teams relying on mid-block fouls to reset shape; possession-oriented high-line teams show less zone-specific clustering.",
        "magnitude": "Direct-free-kick xG conceded per match is ~10–15 % lower for teams assigned spot-placement-lenient officials relative to strict ones, controlling for total fouls committed.",
        "links": ["tactical_foul_budgeting", "card_threshold_calibration", "foul_cluster_management"],
    },
]
