"""Soccer OfficiatingDynamics — person-free concept-node spec.

Rule-interpretation, video-review, and disciplinary regimes that shape
match flow and outcome distributions in top-flight soccer. Descriptive
and person-free; no edge or market-efficiency claims are made.
"""
from __future__ import annotations

SPORT = "Soccer"
FAMILY = "OfficiatingDynamics"

CONCEPTS: list[dict] = [
    {
        "slug": "var_intervention_threshold",
        "title": "VAR Clear-and-Obvious Intervention Threshold",
        "summary": "Video review overturns an on-field decision only when the error is clear and obvious, leaving most borderline subjective calls intact. Overturn rate per match and the share of checked incidents upheld jointly define the operative threshold.",
        "stat_signature": "~0.3-0.5 overturns per match in top leagues; ~60-70% of incidents checked yield no change; penalty-related reviews account for ~40% of all overturns.",
        "mechanism": "The protocol requires an unambiguous error before triggering a correction; subjective contact rarely meets the bar, concentrating overturns on factual questions such as offside geometry and boundary events.",
        "conditions": "Threshold effect is largest in conservative review cultures; it narrows in knockout rounds where review teams apply heavier scrutiny to decisive incidents.",
        "magnitude": "Roughly one in three checks results in an overturn; penalty overturns shift goal-scoring rates by approximately 0.1-0.2 goals per match when isolated.",
        "links": ["var_check_review_duration", "var_factual_subjective_split", "penalty_award_consistency", "handball_deliberate_standard"],
    },
    {
        "slug": "var_check_review_duration",
        "title": "VAR Check and On-Field-Review Duration",
        "summary": "Video checks and pitch-side monitor reviews consume measurable dead time, with on-field reviews adding longer delays than silent corrections. Competition norms shape how liberally reviews are initiated.",
        "stat_signature": "Mean check duration ~60-90 seconds; on-field reviews ~0.15-0.25 per match; each pitch-side episode adds ~2-4 minutes of stoppage credited to added time.",
        "mechanism": "Referee communication with the review room, angle selection, and replay-speed calibration extend check duration; pitch-side reviews suspend all play and feed directly into the added-time computation.",
        "conditions": "Duration peaks for handball and simulation reviews requiring multiple angles; offside checks using semi-automated lines resolve faster once the calibration frame is identified.",
        "magnitude": "High-review matches can accumulate 6-10 extra stoppage minutes attributable to review episodes, materially inflating effective added time relative to pre-VAR baselines.",
        "links": ["var_intervention_threshold", "added_time_computation", "semi_automated_offside_latency"],
    },
    {
        "slug": "semi_automated_offside_latency",
        "title": "Semi-Automated Offside Detection Latency",
        "summary": "Limb-tracking automated systems reduce mean offside decision time and improve marginal-call accuracy by replacing manual line drawing with skeletal joint projection at the calibration frame.",
        "stat_signature": "Semi-automated lines cut mean offside review time from ~90 seconds to ~30-45 seconds; marginal-call overturn rate shifts because sub-10-cm decisions that manual lines left ambiguous are resolved.",
        "mechanism": "High-frame-rate optical tracking tags skeletal joints and projects the outermost legal body part in three dimensions, removing subjectivity from line placement while retaining dependence on the calibration frame.",
        "conditions": "Benefits are largest for fast counter-attacks and high-line defenses where attacker and defender converge within centimeters; gains are smaller for clear non-marginal calls.",
        "magnitude": "Adoption reduces total VAR-related dead time for offside by roughly 30-50% per match in competitions using full limb tracking.",
        "links": ["var_check_review_duration", "var_intervention_threshold", "goal_line_technology_resolution"],
    },
    {
        "slug": "added_time_computation",
        "title": "Stoppage-Time Computation Regime",
        "summary": "Added time accumulates from substitutions, injury assessments, goal celebrations, and review episodes, with competition-level directives controlling how strictly each category is credited. Mean added minutes per half have risen substantially under stricter mandates.",
        "stat_signature": "Mean second-half added time rose from ~4-5 minutes pre-2023 to 6-9 minutes under stricter mandates; first-half additions similarly increased from ~2-3 to ~4-6 minutes.",
        "mechanism": "Fourth official credits stoppage in real time against a prescribed schedule; stricter directives require longer credits for goal celebrations (~1 min each) and review episodes, extending effective playing time and widening late-match comeback windows.",
        "conditions": "Largest inflation occurs in matches with multiple goals, video reviews, or medical stoppages; knockout rounds without score pressure show smaller inflation.",
        "magnitude": "Strict accumulation adds roughly 8-14 minutes of effective playing time per match compared with legacy conventions, materially altering late-match goal probability distributions.",
        "links": ["var_check_review_duration", "concussion_substitution_stoppage", "extra_time_added_load"],
    },
    {
        "slug": "handball_deliberate_standard",
        "title": "Handball Natural-Silhouette Standard",
        "summary": "Handball penalties are awarded when an arm makes the body unnaturally bigger, with the deliberate-versus-natural-silhouette criterion distinguishing punishable from incidental contact. Handball-penalty rate per box entry and the share attributed to unnatural-silhouette contact track enforcement.",
        "stat_signature": "Handball penalties at ~0.10-0.18 per match in top leagues; VAR adoption roughly doubled the apparent rate; ~30-40% of box-contact reviews are upheld as unnatural-silhouette handballs.",
        "mechanism": "VAR slow-motion review makes accidental-looking contacts appear more deliberate, inflating the apparent incidence relative to real-time calls; competition interpretive guidance shapes how conservatively 'natural' is defined.",
        "conditions": "Applies most consequentially inside the penalty area; deflections from close range are hardest to adjudicate because reaction time is insufficient for deliberate action.",
        "magnitude": "Variation in handball interpretation across competitions can shift penalty rates by 30-60%, noticeably affecting goal-scoring distributions.",
        "links": ["var_intervention_threshold", "penalty_award_consistency", "var_factual_subjective_split"],
    },
    {
        "slug": "penalty_award_consistency",
        "title": "Penalty-Award Contact Threshold",
        "summary": "The contact bar for awarding a penalty inside the area varies by competition culture and VAR review practice. Penalties per box touch and the rate shift after video review isolate how much on-field judgment diverges from post-hoc standards.",
        "stat_signature": "Elite leagues average ~0.25-0.40 penalties per match; VAR modifies ~15-20% of on-field penalty decisions; box-touch rates exceed 30 per half in high-press systems.",
        "mechanism": "High-press systems generate more penalty-area contests and therefore more penalty opportunities; referee calibration drifts over a season and is partially corrected by review, but the clear-and-obvious threshold resists correction of borderline fouls.",
        "conditions": "Penalty rate rises in matches where one side dominates territory; late-match defensive desperation increases foul frequency and penalty exposure.",
        "magnitude": "Each additional penalty adds ~0.75 expected goals to the conversion-weighted distribution, representing a substantial swing in match goal probability.",
        "links": ["handball_deliberate_standard", "var_intervention_threshold", "penalty_retake_encroachment", "denial_goal_scoring_opportunity"],
    },
    {
        "slug": "denial_goal_scoring_opportunity",
        "title": "Denial-of-Goalscoring-Opportunity Sanction",
        "summary": "Red cards for denying an obvious goalscoring opportunity are subject to a double-jeopardy relaxation inside the penalty area: if a penalty is awarded, the offending player is typically cautioned rather than dismissed. Red-card rate per last-defender foul and the yellow-downgrade share characterize this regime.",
        "stat_signature": "Last-defender foul rate ~0.05-0.10 per match; inside-area DOGSO downgrades to yellow in ~70-80% of cases post-rule-change; outside-area DOGSO retains red at ~60%.",
        "mechanism": "The double-jeopardy principle treats a penalty as itself a severe sanction, making a red card disproportionate when there is a genuine attempt to play the ball; the inside-versus-outside spatial discontinuity must be correctly located by the referee.",
        "conditions": "Applies when an attacker breaks behind the defensive line; less relevant in set-piece scenarios where the goalkeeper is typically the last line.",
        "magnitude": "The downgrade regime reduces match-disqualifying reds by roughly 0.04-0.06 per match, measurably reducing numerical-imbalance game states.",
        "links": ["penalty_award_consistency", "second_yellow_threshold", "card_accumulation_tendency"],
    },
    {
        "slug": "card_accumulation_tendency",
        "title": "Disciplinary-Card Issuance Tendency",
        "summary": "Referee-level card issuance clusters into lenient and strict style regimes measurable as yellow and red cards per match and per foul committed. Between-referee variance in cards per foul defines the behavioral distribution independently of team foul rates.",
        "stat_signature": "Top-league averages range from ~3.5 to 5.5 yellow cards per match; per-foul booking rates span 0.10 to 0.22; between-referee standard deviation in cards per match exceeds 1.2 within the same league.",
        "mechanism": "Card issuance reflects game-management philosophy: strict regimes book early to deter escalation while lenient regimes prioritize flow; accumulated cautioning history within a match feeds back into subsequent thresholds.",
        "conditions": "Strictness increases in high-intensity fixture contexts and knockout matches; leniency is more common in flowing, open-game contexts.",
        "magnitude": "A strict-regime match accumulates ~1.5-2.0 additional yellows compared with a lenient-regime match for similar foul volumes, materially raising dismissal probability.",
        "links": ["foul_tolerance_threshold", "persistent_infringement_management", "second_yellow_threshold", "dissent_simulation_sanction"],
    },
    {
        "slug": "foul_tolerance_threshold",
        "title": "Foul-Tolerance Whistle Threshold",
        "summary": "How much physical contact a referee permits before stopping play is measurable as fouls called per match and the ratio of contested duels to fouls awarded. A lenient threshold produces high-contact, low-whistle matches; a strict threshold fragments play into frequent stoppages.",
        "stat_signature": "Top-league fouls per match range from ~20 to 32; duels-per-foul ratios span 3.5 to 6.5; between-referee variance in fouls per match is approximately 4-7 within the same competition.",
        "mechanism": "Referees calibrate threshold to game tempo and tactical context: fast transitions receive wider latitude than static midfield duels; a low threshold raises set-piece frequency and benefits direct-play styles.",
        "conditions": "Tolerance shifts toward leniency in attacking-third contact and toward strictness in midfield cycling zones; late-match lead changes shift the threshold dynamically.",
        "magnitude": "A 10-foul-per-match difference corresponds to roughly 8-12 additional set-piece restarts, materially affecting possession and transition distributions.",
        "links": ["card_accumulation_tendency", "persistent_infringement_management", "advantage_play_on_application"],
    },
    {
        "slug": "advantage_play_on_application",
        "title": "Advantage and Play-On Application",
        "summary": "Referees defer a whistle when the fouled side retains attacking promise, measured as advantage-played rate per foul and the conversion rate of advantage situations into a shot within a defined window. Lenient foul thresholds increase advantage-play frequency.",
        "stat_signature": "Advantage is applied in ~8-15% of observed foul situations in high-press matches; roughly 25-35% of advantages result in a shot or entry into the final third within 5 seconds.",
        "mechanism": "Advantage allows the attacking team to retain momentum from a promising position that a whistle would neutralize; if the advantage does not materialize within a few seconds, the referee can return the whistle for the original foul.",
        "conditions": "Advantage application peaks when the fouled player retains possession in the attacking half; it is rarely applied in the defensive third or in situations where the ball is contested.",
        "magnitude": "Competitions with higher advantage-application rates see proportionally fewer direct free-kicks and more open-play continuations from foul situations, affecting set-piece frequency and flow.",
        "links": ["foul_tolerance_threshold", "added_time_computation", "wall_management_free_kick"],
    },
    {
        "slug": "persistent_infringement_management",
        "title": "Persistent-Infringement and Tactical-Foul Management",
        "summary": "Cumulative booking for repeated or cynical fouling is triggered by team-foul accumulation and referee warnings. The team-foul count preceding a first caution and the booking rate on counter-stopping tactical fouls characterize this category.",
        "stat_signature": "First persistent-infringement caution typically arrives after 4-7 team fouls in a half; tactical counter-stopping fouls are booked at ~25-45% of occurrences in high-intensity matches.",
        "mechanism": "Persistent-infringement cautions deter tactical-foul budgets: teams approaching the threshold receive a formal warning, compressing their counter-press disruption capacity and forcing territory concessions.",
        "conditions": "Most consequential when one side is structurally inferior and relies on tactical disruption to neutralize transitions; counter-press-heavy opponents generate high tactical-foul exposure for the side being pressed.",
        "magnitude": "A team receiving an early persistent-infringement warning commits roughly 15-20% fewer fouls in the subsequent 30 minutes on average, indicating a measurable behavioral deterrent.",
        "links": ["card_accumulation_tendency", "foul_tolerance_threshold", "second_yellow_threshold"],
    },
    {
        "slug": "second_yellow_threshold",
        "title": "Second-Caution Sending-Off Threshold",
        "summary": "An already-booked player operates under a compressed threshold because any further caution results in dismissal. Second-yellow rate per already-booked player and the observed foul-rate shift for cautioned players characterize how this dynamic affects match behavior.",
        "stat_signature": "Already-booked players commit fouls at ~10-20% lower per-minute rate than uncautioned teammates; second-yellow dismissals occur at ~0.04-0.08 per match; dismissal rate rises sharply after the 60th minute.",
        "mechanism": "The dismissal threat creates a dual-side threshold compression: cautioned players reduce foul frequency while referees may apply tighter scrutiny, jointly shrinking the effective foul budget.",
        "conditions": "Effect is largest when the booked player is a central defensive midfielder whose role requires physical engagement; weakened tactical-foul budgets affect press-oriented systems disproportionately.",
        "magnitude": "Each dismissal shifts the numerical balance for ~25-40 minutes on average, materially altering scoring probability curves during that window.",
        "links": ["card_accumulation_tendency", "denial_goal_scoring_opportunity", "persistent_infringement_management"],
    },
    {
        "slug": "goal_line_technology_resolution",
        "title": "Goal-Line-Technology Resolution",
        "summary": "Automated whole-ball-over-line detection delivers binary goal or no-goal decisions to the referee's watch within roughly one second, eliminating ambiguity in near-line scenarios that historically required linesman judgment.",
        "stat_signature": "Top competitions see ~2-5 goal-line technology decisions per season that are non-obvious to the naked eye; signal delivery within ~1.0-1.2 seconds; historical pre-technology ambiguous cases resolved incorrectly ran at ~0.2-0.5 per season.",
        "mechanism": "A network of high-speed cameras tracks ball position in three dimensions relative to the goal-line plane, generating a certified decision free from line-of-sight occlusion that caused historic controversies.",
        "conditions": "Relevant only at the goal-line boundary; maximum relevance for shots cleared off the line or goal-mouth scrambles with multiple bodies blocking sightlines.",
        "magnitude": "Technology effectively eliminates the prior ~0.3-per-season incorrect goal-line decision rate in equipped competitions, a small but high-consequence effect.",
        "links": ["semi_automated_offside_latency", "var_intervention_threshold", "penalty_retake_encroachment"],
    },
    {
        "slug": "penalty_retake_encroachment",
        "title": "Penalty-Kick Encroachment and Retake Enforcement",
        "summary": "Goalkeeper line-position rules and field-player encroachment during a penalty kick are reviewable by VAR, triggering retakes when the infringing side benefits from the original outcome. Retake rate per penalty and goalkeeper-off-line review frequency quantify enforcement intensity.",
        "stat_signature": "Retakes awarded in ~5-10% of penalties in actively enforced competitions; goalkeeper encroachment is the most common trigger; field-player encroachment retakes occur at ~1-3% of penalties.",
        "mechanism": "VAR reviews the goalkeeper's foot position frame-by-frame and recommends a retake if the keeper was off the line on a missed or saved penalty, providing a material second-chance mechanism for the kicking side.",
        "conditions": "Enforcement is asymmetric: retakes are called only when the infringing side benefits; saved penalties in high-stakes matches receive the most scrutiny.",
        "magnitude": "In competitions with active encroachment review, saved penalties lead to retakes at a rate that raises effective conversion probability by roughly 2-4 percentage points.",
        "links": ["penalty_award_consistency", "var_intervention_threshold", "goal_line_technology_resolution"],
    },
    {
        "slug": "var_factual_subjective_split",
        "title": "Factual-Versus-Subjective Review Split",
        "summary": "VAR distinguishes objectively measurable incidents (offside geometry, goal-line position, player identity) from judgment calls (foul severity, handball deliberateness). Overturn rates are substantially higher for factual categories, defining a two-tier review effectiveness landscape.",
        "stat_signature": "Factual offside overturns at ~80-90% of checked incidents; goal-boundary overturns approach 100% with technology; subjective foul and handball reviews overturn at only ~25-40% of checked on-field calls.",
        "mechanism": "Factual questions have verifiable ground truth from camera geometry; subjective questions must meet the clear-and-obvious standard against an inherently imprecise original judgment, systematically preserving referee discretion for contact decisions.",
        "conditions": "The factual-subjective gap narrows in aggressive review cultures with lower intervention thresholds; it widens in conservative cultures strictly applying clear-and-obvious. Competition guidance on which categories merit active checks shapes how many subjective incidents are even reviewed.",
        "magnitude": "The split explains why VAR has near-eliminated incorrect offside decisions while leaving handball and foul-contact controversies largely unchanged across competitions.",
        "links": ["var_intervention_threshold", "handball_deliberate_standard", "penalty_award_consistency"],
    },
    {
        "slug": "wall_management_free_kick",
        "title": "Defensive-Wall Distance Enforcement",
        "summary": "Enforcement of the required wall distance and the attacker-encroachment rule shapes how much space a direct free-kick executor has. Wall-distance cautions per direct free-kick and the retake rate for encroachment quantify the regime.",
        "stat_signature": "Wall-distance cautions issued in ~3-6% of direct free-kick situations; spray-mark adoption reduced encroachment violations by ~30-40%; retakes for encroachment occur at ~1-2% of direct free-kicks.",
        "mechanism": "A wall set too close reduces the shooting angle available to the kicker; referee authority in enforcing the distance, aided by vanishing spray, determines how much the defensive team exploits the encroachment window before the kick is taken.",
        "conditions": "Most consequential for dangerous direct free-kick positions within 25 meters; less relevant for wide angles where wall distance affects trajectory minimally.",
        "magnitude": "A wall set 1-2 meters short of the required distance reduces the effective shooting window by approximately 15-25%, measurably altering direct-free-kick conversion probability.",
        "links": ["advantage_play_on_application", "foul_tolerance_threshold", "added_time_computation"],
    },
    {
        "slug": "extra_time_added_load",
        "title": "Knockout Extra-Time Officiating Load",
        "summary": "Two fifteen-minute extra-time periods generate officiating patterns distinct from regulation: fatigue-driven foul frequency rises, card thresholds may shift, and added time within extra time compounds stoppages. Fouls and cards per extra-time half relative to per-minute regulation baselines capture the regime.",
        "stat_signature": "Fouls per minute in extra time run ~15-25% above regulation average; yellow cards per extra-time period ~0.8-1.2; added time within extra time averages 2-4 minutes per period under current stoppage-credit rules.",
        "mechanism": "Physical fatigue increases uncontrolled contact independently of tactical intent; referees managing already-cautioned players face compounded second-yellow risk, creating asymmetric officiating burdens that influence game-management decisions.",
        "conditions": "Largest deviation from regulation baselines appears in the second extra-time period (minutes 106-120) where fatigue peaks; matches with both sides carrying cautioned players show highest variance in cards-per-foul ratios.",
        "magnitude": "The compound effect of higher foul frequency, second-yellow risk, and credited stoppage means a 30-minute extra-time window generates officiating load comparable to ~35-38 regulation minutes.",
        "links": ["added_time_computation", "second_yellow_threshold", "concussion_substitution_stoppage"],
    },
    {
        "slug": "concussion_substitution_stoppage",
        "title": "Injury and Concussion-Substitution Stoppage",
        "summary": "Head-injury assessments under concussion protocols halt play for a standardized period, and competitions permitting additional concussion substitutions alter effective squad depth. Injury stoppages per match and added time credited per assessment characterize the regime.",
        "stat_signature": "Head-injury assessments add ~2-5 minutes per incident; competitions with concussion substitution permits see ~0.15-0.30 such substitutions per match; credited stoppage per assessment averages 2-3 minutes under strict-credit rules.",
        "mechanism": "Protocol mandates a minimum assessment window regardless of match urgency, creating fixed dead time in the added-time calculation; additional substitution permits remove the tactical penalty for substituting a symptomatic player.",
        "conditions": "Relevant primarily in physically intense knockout matches with high aerial duel frequency; concussion incidents concentrate around heading duels and high-speed collisions.",
        "magnitude": "A match with two head-injury assessments accumulates 4-10 additional credited stoppage minutes, materially feeding into second-half added-time totals.",
        "links": ["added_time_computation", "extra_time_added_load", "var_check_review_duration"],
    },
]
