"""Soccer OpponentScouting concept-node spec for the brain builder."""
SPORT = "Soccer"
FAMILY = "OpponentScouting"

CONCEPTS = [
    {
        "slug": "opponent_analysis_report_depth",
        "title": "Opponent-Analysis Report Depth",
        "summary": "Pre-match analysis converts prior-match film into actionable structural patterns across build-up, press, and transition; report depth is measured by coverage breadth and calibration against subsequent realized behavior.",
        "stat_signature": "Coverage rate of observed structural dimensions >=80%; behavioral-forecast calibration (predicted patterns realized) >=65%; single-dimension reports achieve <=45% calibration.",
        "mechanism": "Each additional structural dimension reduces in-game unscripted defensive scenarios, lowering cognitive load on defenders responding without a prepared read on the opponent's next action.",
        "conditions": "Depth advantage is largest against tactically varied opponents; against single-system opponents the marginal return on report breadth diminishes after the core structure is documented.",
        "magnitude": "Reports covering all three structural dimensions (build-up, press, transition) achieve 65-72% behavioral calibration; single-dimension reports achieve 38-48% — roughly a 25-point calibration gap.",
        "links": ["pressing_plan_tailoring", "build_up_pattern_priors", "marking_scheme_priors", "analysis_freshness_decay"],
    },
    {
        "slug": "set_piece_routine_cataloguing",
        "title": "Set-Piece Routine Cataloguing",
        "summary": "Cataloguing an opponent's attacking set-piece routines — corner deliveries, near-post flick-ons, blocking runs, late arrivals — enables pre-assigned rather than reactive marking, measured by the fraction of routines defended with correct pre-match assignments.",
        "stat_signature": "Pre-assigned marking coverage >=75% of catalogued routines; set-piece shots conceded <=0.18 per delivery for catalogued opponents versus 0.28 uncatalogued; free-runner rate <=10% when >=4 distinct routines are covered.",
        "mechanism": "Attacking set-piece routines are rehearsed and repeated; pre-assigning responsibility before the routine activates converts the attacker's rehearsal advantage into a preparation advantage, removing the reactive matching problem that generates free runners.",
        "conditions": "Catalogue value is highest against opponents relying on a small high-frequency routine set; degrades when the opponent's routine library exceeds scoutable coverage within a short preparation window.",
        "magnitude": "Correct pre-assigned marking on >=75% of routines suppresses set-piece xGA by 30-40%; free-runner shots from set pieces drop from 0.10-0.14 to 0.03-0.06 per 90.",
        "links": ["marking_scheme_priors", "penalty_and_dead_ball_priors", "throw_in_routine_scouting", "opponent_analysis_report_depth"],
    },
    {
        "slug": "pressing_plan_tailoring",
        "title": "Pressing-Plan Tailoring",
        "summary": "A pressing scheme shaped to an opponent's specific build-up structure — targeting a particular positional role on a rehearsed trigger, or consistently overloading one flank — generates higher turnover rates than a generic press applied without opponent-specific cue calibration.",
        "stat_signature": "Forced-turnover rate in the targeted zone >=18 per 90 versus 11-13 per 90 for generic presses; long-ball concession per press engagement <=0.40; opponent carry-out-of-press rate <=25%.",
        "mechanism": "Generic pressing fires on universal cues that opponents train to defeat; a tailored plan exploits a specific build-up habit — a goalkeeper who habitually plays short into a crowded channel — converting that structural repetition into a predictable turnover location.",
        "conditions": "Most impactful against short-build opponents with habitual first- and second-pass patterns; less impactful when opponents use long distribution as a primary press escape.",
        "magnitude": "Tailored presses achieve 45-55% ball-recovery rates in targeted zones; generic presses achieve 28-35% under equivalent press intensity — a 15-20 percentage point recovery gain from opponent-specific calibration.",
        "links": ["pressing_trigger_anticipation", "build_up_pattern_priors", "goalkeeper_distribution_priors", "opponent_analysis_report_depth"],
    },
    {
        "slug": "build_up_pattern_priors",
        "title": "Build-Up Pattern Priors",
        "summary": "Scouted preferred progression routes out of the back — favored wide channel, third-man sequence through the pivot, or direct carry — are encoded as calibrated priors; quality is measured by how closely forecast pass-network density matches the realized network in equivalent phases.",
        "stat_signature": "Top-2 scouted routes accounting for >=60% of realized progressive passes on >=70% of matches; build-up interception rate in pre-targeted channels >=12 per 90 versus 6-8 per 90 for uncalibrated baselines.",
        "mechanism": "Well-drilled build-up systems execute the same pass sequences repeatedly; priors from that repetition enable defenders to pre-position in the landing zone rather than reacting in flight, converting a reactive interception into a prepared one.",
        "conditions": "Prior calibration is strongest against opponents who have played together over an extended run; degrades when mid-season personnel or tactical changes alter the progression network.",
        "magnitude": "Calibrated priors identifying >=2 of 3 top build-up channels raise mid-block interception rates by 40-55% in those zones; miscalibrated priors concede 20-30% more progressive receptions in channels the defense vacated.",
        "links": ["pressing_plan_tailoring", "pressing_trigger_anticipation", "opponent_analysis_report_depth", "analysis_freshness_decay"],
    },
    {
        "slug": "defensive_block_exploitation_plan",
        "title": "Defensive-Block Exploitation Plan",
        "summary": "Pre-match planning identifies the structural weakness in a scouted opponent block — wide-channel gap in a narrow low block, space behind a high mid-block, or second-ball zone in a deep compact block — and directs attacking patterns toward that channel, measured by chance-creation rate through the targeted zone.",
        "stat_signature": "Chance-creation rate through the pre-targeted channel >=0.22 xG per 90; share of attacking sequences routed to the scouted weak zone >=40%; xG per shot from targeted-channel chances >=0.12.",
        "mechanism": "Blocks are structurally biased by shape: narrow blocks concede wide delivery, high blocks concede through-balls, deep compact blocks concede second balls; an exploitation plan pre-selects the mismatch and rehearses the sequence that accesses it.",
        "conditions": "Most impactful against consistent single-block opponents who do not adjust shape dynamically; against fluid hybrid-block sides, pre-targeted channels may be closed before the attack arrives.",
        "magnitude": "Matches with a correctly targeted exploitation plan average 0.20-0.26 xG per 90 through the targeted channel; unplanned attacks against the same block average 0.10-0.14 xG — roughly a 2× channel-xG efficiency ratio.",
        "links": ["high_line_exploitation_plan", "build_up_pattern_priors", "transition_route_scouting", "individual_duel_avoidance_plan"],
    },
    {
        "slug": "transition_route_scouting",
        "title": "Transition-Route Scouting",
        "summary": "Scouting the preferred counter-attack lanes an opponent uses after possession recovery allows pre-positioning of defensive cover on those routes, measured by transition shots conceded per scouted lane versus the team's baseline transition concession rate.",
        "stat_signature": "Transition shots conceded via the scouted dominant route <=0.10 per 90 when pre-positioned versus 0.22-0.30 per 90 baseline; forced-backward-pass rate on counter attempts >=35%; transition xGA reduction in the scouted lane >=40%.",
        "mechanism": "Counter-attacking systems are drilled; the first-choice route is executed quickly and repeatedly because it is pre-rehearsed; scouting that route removes its surprise advantage by placing a defender in the gap before possession is even recovered.",
        "conditions": "Scouting value is highest against single-dominant-route transition teams; against multi-route transition sides, covering one lane displaces the threat rather than suppressing it.",
        "magnitude": "Pre-positioned defensive coverage on the scouted dominant lane reduces transition shots in that zone by 45-60%; total match transition xGA drops by 0.08-0.14 when the primary counter route is effectively neutralized.",
        "links": ["rest_defence_scouting", "opponent_analysis_report_depth", "defensive_block_exploitation_plan", "tempo_and_game_state_priors"],
    },
    {
        "slug": "pressing_trigger_anticipation",
        "title": "Pressing-Trigger Anticipation",
        "summary": "Pre-match knowledge of the cues that activate an opponent's press — back-pass to the goalkeeper, touchline reception, or a square central pass under load — allows the in-possession team to disguise or pre-empt those cues, measured by play-out success rate on sequences that mimic the scouted trigger.",
        "stat_signature": "Play-out success rate when correctly pre-empting the scouted trigger >=68% versus 42-48% baseline; third-man escape rate through the triggering zone >=30%; press-escape-by-disguise rate >=25% of scouted-trigger sequences.",
        "mechanism": "A pressing team invests collective forward momentum in the trigger response; pre-empting the trigger by delivering the ball away from the cue zone before the press fires exploits that committed momentum, creating space behind the pressing wave.",
        "conditions": "Anticipation is most effective when the opponent uses a small set of high-frequency triggers; less effective against opponents with fluid trigger criteria or those who combine multiple simultaneous cue types.",
        "magnitude": "Correct pre-emption raises play-out success in triggering zones from 44% to 65-70%; each avoided press generates approximately 8-12 m of additional forward progression before defensive recovery.",
        "links": ["pressing_plan_tailoring", "build_up_pattern_priors", "counter_scouting_pattern_disguise", "goalkeeper_distribution_priors"],
    },
    {
        "slug": "marking_scheme_priors",
        "title": "Marking-Scheme Priors",
        "summary": "Scouting whether an opponent uses man-marking, zonal, or hybrid schemes at dead balls allows the attacking team to design overloads, blocking runs, or late arrivals that exploit the seams of the forecast scheme, measured by calibration of forecast marker assignment against realized behavior.",
        "stat_signature": "Forecast marking-assignment calibration >=70% for man-marking opponents and >=60% for zonal opponents; set-piece xG when scheme-exploiting routine is deployed >=0.14 per delivery; free-runner creation via scheme-targeted blocking run >=20% of deployed routines.",
        "mechanism": "Man markers commit to a runner; a blocking run occupying their assigned attacker frees the late arrival. Zonal defenders hold positions, so overloading one zone defeats it without physical displacement of the marker.",
        "conditions": "Scheme exploitation is most reliable against opponents who apply the same scheme regardless of set-piece type or delivery zone; adaptive opponents who switch scheme by context may render calibrated priors mismatched.",
        "magnitude": "Set-piece routines built on correctly calibrated marking-scheme priors generate 0.13-0.18 xG per delivery; generic routines against the same opponents generate 0.07-0.10 xG — a roughly 60-80% xG increase from scheme-aware design.",
        "links": ["set_piece_routine_cataloguing", "penalty_and_dead_ball_priors", "opponent_analysis_report_depth", "throw_in_routine_scouting"],
    },
    {
        "slug": "goalkeeper_distribution_priors",
        "title": "Goalkeeper-Distribution Priors",
        "summary": "Scouting the opposing goalkeeper's distribution habits — short-pass preference, dominant-side bias, long-clearance landing zone, and trigger conditions for each — enables the pressing team to pre-position for press traps or second-ball recovery.",
        "stat_signature": "Press-trap initiation success rate when distribution matches the scouted pattern >=45%; second-ball recovery in forecast landing zones >=55%; forced-long-ball rate under press >=35% for opponents scouted as short-builders.",
        "mechanism": "A goalkeeper under pressure defaults to their dominant distribution habit; pre-positioning to overload the expected short-pass target forces either a turnover at the target or a long clearance into the pre-populated second-ball zone.",
        "conditions": "Distribution priors are most reliable in high-press systems that consistently apply pressure before the goalkeeper's decision window; in low-block systems where the goalkeeper distributes unpressured, the prior adds less structured value.",
        "magnitude": "Correctly pre-positioned press traps achieve 40-50% press-success rates on scouted distribution patterns versus 20-28% without scouting — roughly a 2× press-success differential.",
        "links": ["pressing_plan_tailoring", "pressing_trigger_anticipation", "build_up_pattern_priors", "analysis_freshness_decay"],
    },
    {
        "slug": "high_line_exploitation_plan",
        "title": "High-Line Exploitation Plan",
        "summary": "Pre-match preparation to attack a scouted high defensive line through calibrated runs in behind, through-ball timing, and offside-trap beating patterns; measured by through-ball attempt rate and trap-beating shots generated against the catalogued line height.",
        "stat_signature": "Through-ball attempts against high-line opponents >=4.5 per 90 when plan is deployed; trap-beating runs generating shots >=1.2 per 90; offside calls conceded while generating trap-beating xG <=0.8 per 90.",
        "mechanism": "A high defensive line creates vulnerability to precisely timed diagonal and vertical runs that breach the line before the offside trap resets; scouting the line height calibrates the release-run timing to the specific threshold rather than generic through-ball depth.",
        "conditions": "Exploitation value is highest against rigid high lines that do not adjust height on forward-run cues; adaptive lines that drop quickly on through-ball signals narrow the timing window considerably.",
        "magnitude": "Matches with a calibrated high-line plan generate 1.0-1.4 trap-beating shots per 90; unplanned deep-run attempts against the same opponent generate 0.4-0.6 shots per 90 and incur approximately 2× the offside calls.",
        "links": ["defensive_block_exploitation_plan", "transition_route_scouting", "build_up_pattern_priors", "tempo_and_game_state_priors"],
    },
    {
        "slug": "rest_defence_scouting",
        "title": "Rest-Defence Scouting",
        "summary": "Mapping which players an opponent leaves behind the ball during their own attacks — and their positional depth, spacing, and recovery speed — enables counter-attack designs targeting the structural gap, measured by counter-attack shots generated through scouted rest-defence corridors.",
        "stat_signature": "Counter-attack shots through the scouted corridor >=1.2 per 90 versus 0.5-0.7 per 90 baseline; xG per counter-attack shot through the corridor >=0.14; ball-recovery-to-shot conversion >=30%.",
        "mechanism": "Rest-defence assignments are habitual and system-driven; scouting the number and positioning of players left behind converts the coverage gap into a pre-designed counter route rather than an improvised one.",
        "conditions": "Largest dividend against opponents who commit heavily to attacks and leave a predictable structural gap; against opponents with disciplined rest-defence depth, the counter corridor is narrow and scouted routes converge with the coverage.",
        "magnitude": "Counters routed through the pre-scouted corridor generate 0.12-0.18 xG per counter; improvised counters against the same opponents generate 0.05-0.08 xG — a 2-3× xG-per-counter efficiency gap.",
        "links": ["transition_route_scouting", "opponent_analysis_report_depth", "tempo_and_game_state_priors", "individual_duel_avoidance_plan"],
    },
    {
        "slug": "individual_duel_avoidance_plan",
        "title": "Duel-Targeting and Avoidance Plan",
        "summary": "Pre-match routing of attacking sequences toward a scouted weak defensive one-versus-one matchup — or away from a dominant one — increases the share of high-probability carry successes, measured by the fraction of one-versus-one engagements directed into the pre-targeted zone.",
        "stat_signature": "Share of one-versus-one engagements in the pre-targeted zone >=35% versus ~20% baseline; dribble-success rate in the targeted weak matchup >=55%; engagements steered away from the scouted strong matchup reduced by >=25%.",
        "mechanism": "Defensive one-versus-one quality is asymmetric across positions; repeatedly targeting the structural weak point overloads a defender who cannot rotate out of the duel, while avoiding the dominant defender removes the suppression effect on the attacking system.",
        "conditions": "Targeting plans are most executable when attacking patterns can be directed laterally to a specific zone without telegraphing intent; against opponents who shift coverage to protect the targeted zone, the plan requires a wrinkle to draw the strong defender first.",
        "magnitude": "Consistently directing attacks into the weak matchup raises carry-and-cross success from 40% to 55-65%; avoiding the strong matchup contributes 0.06-0.10 additional xG per 90 through improved dribble conversion.",
        "links": ["defensive_block_exploitation_plan", "rest_defence_scouting", "high_line_exploitation_plan", "counter_scouting_pattern_disguise"],
    },
    {
        "slug": "tempo_and_game_state_priors",
        "title": "Tempo-by-Game-State Priors",
        "summary": "Scouting how an opponent's tempo and shape change by scoreline — pressing higher when trailing, dropping into a deeper block when leading, widening the shape when level late — enables game-state-contingent tactical responses calibrated to forecast behavior.",
        "stat_signature": "Forecast-versus-realized behavioral calibration across three states (leading / level / trailing) >=65%; tactical response success rate when game-state shift matches the forecast >=55%; incorrect game-state reads producing additional conceded transitions <=0.8 per 90.",
        "mechanism": "Teams operate different structural sub-systems by scoreline; the trailing system commits more attackers and reduces rest-defence depth, creating a counter-attack window that only opens at a predictable scoreline threshold, enabling preparation before the state arrives.",
        "conditions": "Game-state priors are most actionable against opponents with pronounced and consistent behavioral shifts; against system-stable opponents who maintain shape regardless of score, prior calibration adds marginal structural value.",
        "magnitude": "Correctly calibrated game-state priors enable sub-responses generating 0.08-0.15 additional xG per 90 in the predicted game-state window; miscalibrated priors misreading the opponent's trailing shape produce 0.10-0.18 additional transition-xGA per 90.",
        "links": ["opponent_analysis_report_depth", "transition_route_scouting", "rest_defence_scouting", "analysis_freshness_decay"],
    },
    {
        "slug": "counter_scouting_pattern_disguise",
        "title": "Counter-Scouting Pattern Disguise",
        "summary": "In repeat fixtures against familiar opponents who have scouted one's own patterns, deploying pre-prepared set-piece variations and build-up wrinkles degrades the opponent's scouting calibration, measured by variation deployment rate and the corresponding drop in opponent defensive pre-positioning accuracy.",
        "stat_signature": "Variation deployment rate in repeat fixtures >=30% of set-piece deliveries and >=20% of build-up sequences; opponent defensive pre-positioning accuracy drop >=15 percentage points versus first-meeting fixtures; variation xG per set-piece delivery >=0.12.",
        "mechanism": "A prepared opponent's defensive advantage is largest at the start of a familiar routine and collapses when an unrehearsed variation arrives; deploying variations selectively preserves the deceptive value of the standard routine while opening alternative scoring paths.",
        "conditions": "Disguise value is greatest in second-leg and playoff encounters with maximum opponent preparation time; in congested fixtures with limited opponent scouting depth, variation rate can remain modest without structural risk.",
        "magnitude": "Repeat fixtures with >=30% variation deployment concede 25-35% fewer correctly pre-positioned markers per set-piece delivery; matches with no variation against a well-prepared opponent show 0.05-0.10 lower xG per set piece versus the season average.",
        "links": ["pressing_trigger_anticipation", "individual_duel_avoidance_plan", "marking_scheme_priors", "analysis_freshness_decay"],
    },
    {
        "slug": "analysis_freshness_decay",
        "title": "Analysis Freshness Decay",
        "summary": "Opponent pattern reports degrade as formations and personnel roles evolve across a season; the decay rate determines how many matches old the last observed sample can be before scouting calibration falls below the threshold where preparation adds value over a generic opponent model.",
        "stat_signature": "Reports based on the last 3 matches achieve 65-72% calibration; reports from matches 8-12 weeks prior achieve 45-52%; reports older than 15 matches fall below 40% calibration for opponents with mid-season tactical changes.",
        "mechanism": "Opponent systems evolve with form, personnel availability, and tactical learning; a report built on a 10-match-old sample maps the historical system, not the present one; calibration erosion is faster for opponents with high rotation or a recent structural shape change.",
        "conditions": "Decay is slowest against system-stable sides who maintain identical shapes across the season; fastest against sides in mid-season tactical transition, where even a 3-match-old report may misrepresent the current structure.",
        "magnitude": "Each additional 4-match gap between the most recent scouted sample and the target fixture reduces behavioral calibration by an estimated 4-7 percentage points; at a 12-match gap, calibration is typically 18-25 points lower than a report built on the last 3 matches.",
        "links": ["opponent_analysis_report_depth", "build_up_pattern_priors", "goalkeeper_distribution_priors", "tempo_and_game_state_priors"],
    },
]
