"""NBA OpponentScouting concepts — person-free spec for brain_concept_nodes."""
from __future__ import annotations

SPORT = "NBA"
FAMILY = "OpponentScouting"

CONCEPTS: list[dict] = [
    {
        "slug": "film_study_tendency_extraction",
        "title": "Film-Study Tendency Extraction Depth",
        "summary": "Measures how thoroughly pre-game scouting converts opponent film into actionable tendency tables, covering play-type frequency, personnel groupings, and after-timeout sets relative to the opponent's actual subsequent distribution.",
        "stat_signature": "Calibration of pre-game play-type frequency forecast against realized half-court action distribution; well-prepared units forecast the top-3 action types within 5 percentage points; shallow scouting drifts 12-plus points.",
        "mechanism": "Deep film extraction reduces in-game decision latency by pre-loading the defense's recognition tree; when a covered tendency appears, the defender reacts to a known pattern rather than processing a novel stimulus.",
        "conditions": "Most diagnostic against schematically complex offenses with high action variety; value diminishes against one-dimensional isolation-heavy systems where shallow scouting captures 80 percent of actions.",
        "magnitude": "High-extraction units concede roughly 3-6 fewer points per 100 half-court possessions across the first half before the opponent adapts; advantage narrows after halftime as live adjustment compensates.",
        "links": ["set_play_recognition_library", "first_action_predictability_scouting", "scouting_report_decay", "coverage_disguise_anticipation"],
    },
    {
        "slug": "prior_meeting_familiarity_curve",
        "title": "Prior-Meeting Familiarity Curve",
        "summary": "Captures how shot-quality conceded and turnover-forcing efficiency improve as cumulative head-to-head minutes accumulate within a season, measuring defensive efficiency delta per additional prior meeting against the same offensive system.",
        "stat_signature": "Defensive effective field-goal percentage delta from first to third meeting within a season; units showing familiarity gains improve eFG% allowed by 2-4 percentage points by the third encounter; top-quartile units reach 5-plus.",
        "mechanism": "Repeated exposure reduces scouting uncertainty and lets defenders allocate attention with greater precision; the mechanism is learning compression — each meeting sharpens the tendency estimate and reduces coverage hesitation.",
        "conditions": "Strongest within a single season where the opponent's system is stable; attenuates across seasons when offensive personnel or coordinator changes reset the familiarity baseline.",
        "magnitude": "Third-meeting defensive ratings are roughly 2-5 points per 100 possessions better than first-meeting ratings on average; effect is larger against teams with deep scripted set libraries.",
        "links": ["film_study_tendency_extraction", "scouting_report_decay", "set_play_recognition_library", "first_action_predictability_scouting"],
    },
    {
        "slug": "first_action_predictability_scouting",
        "title": "First-Action Predictability Scouting",
        "summary": "Captures how scoutable an offense's opening action out of timeouts and dead balls is, measured by the entropy of the first half-court action call and the defense's pre-rotation accuracy against it.",
        "stat_signature": "Shannon entropy of the first-action call distribution out of timeouts; low-entropy offenses (under 1.5 bits) concede pre-rotation accuracy above 70 percent; high-entropy offenses (above 2.2 bits) keep pre-rotation accuracy below 45 percent.",
        "mechanism": "Dead-ball first actions are the only scripted possession in a game; predictable openers allow defenses to pre-set rotations, eliminating the read-and-react window that gives the offense its advantage.",
        "conditions": "Most impactful in late-game timeout situations where the offense has limited play variety; less relevant in early-game settings where offensive sequencing is more exploratory.",
        "magnitude": "Defenses with correct pre-rotation on the first post-timeout action hold opponents to roughly 0.82 points per possession on that action compared to 1.05 when caught in reactive mode.",
        "links": ["film_study_tendency_extraction", "set_play_recognition_library", "inbound_and_blob_sideline_prep", "coverage_disguise_anticipation"],
    },
    {
        "slug": "scouted_weakness_exploitation_rate",
        "title": "Scouted-Weakness Exploitation Rate",
        "summary": "Captures how often a pre-identified opponent vulnerability is actually attacked, measured as the share of half-court possessions routed at the scouted weak point versus baseline distribution.",
        "stat_signature": "Share of half-court possessions explicitly targeting the scouted vulnerability; disciplined offenses reach 30-45 percent routing at the identified weak point; undisciplined offenses fall below 15 percent.",
        "mechanism": "Pre-game vulnerability identification is only valuable when converted to possession-level routing decisions; the conversion gap between scouting quality and on-floor execution separates preparation depth from tactical commitment.",
        "conditions": "Highest exploitation rates appear when the vulnerability is a specific poor-closeout defender isolated in ball-screen situations; lower when the weakness is rotational and requires coordinated multi-player setups.",
        "magnitude": "Offenses reaching 35-plus percent routing at a scouted weakness generate roughly 4-8 additional points per game from the targeted advantage compared to un-routed baselines.",
        "links": ["personnel_matchup_targeting_plan", "coverage_disguise_anticipation", "matchup_hunting_avoidance_plan", "shot_contest_priority_mapping"],
    },
    {
        "slug": "personnel_matchup_targeting_plan",
        "title": "Personnel Matchup-Targeting Plan",
        "summary": "Captures the pre-match plan to hunt a specific defensive role in switches, measured as the rate of intentional screening actions aimed at drawing the targeted defender onto the ball-handler.",
        "stat_signature": "Proportion of ball-screen possessions designed to force the target onto the ball; deliberate targeting plans reach 40-60 percent of ball-screen actions funneled toward the identified mismatch; reactive offenses stay under 20 percent.",
        "mechanism": "Screening geometry is the primary tool for creating switch mismatches; pre-identified targets allow offensive coordinators to pre-script screening angles and personnel arrangements rather than discovering mismatches reactively.",
        "conditions": "Most executable when the targeted defender is in a five-out or switchable lineup; less productive when the defense uses hard-hedge or non-switch coverage that prevents the targeted switch from occurring.",
        "magnitude": "Forced-mismatch possessions on a below-average defender generate roughly 0.12-0.20 surplus points per possession above league-average ball-screen outcomes; across a game 3-6 surplus points are achievable.",
        "links": ["scouted_weakness_exploitation_rate", "matchup_hunting_avoidance_plan", "coverage_disguise_anticipation", "shot_contest_priority_mapping"],
    },
    {
        "slug": "coverage_disguise_anticipation",
        "title": "Coverage-Disguise Anticipation",
        "summary": "Captures pre-game preparation for an opponent's pick-and-roll coverage tendencies, measured by counter-action readiness and points-per-chance when the scouted coverage is correctly anticipated by the ball-handler.",
        "stat_signature": "Points per ball-screen possession where coverage was correctly anticipated versus unanticipated; anticipating drop coverage yields 0.04-0.08 surplus points via pull-up mid-range; anticipating hedge yields 0.06-0.10 surplus via slip.",
        "mechanism": "Coverage anticipation converts ambiguous reads into pre-committed decisions; when the ball-handler already knows the hedge is coming, the slip or early-release decision is executed with full momentum rather than as a reactive recognition.",
        "conditions": "Sharpest when the opponent uses a single high-frequency coverage tag (above 65 percent of possessions) making the forecast reliable; degrades against defenses that rotate coverage tags by quarter or personnel group.",
        "magnitude": "Offenses with high anticipation accuracy generate roughly 2-4 additional points per game from ball-screen possessions compared to offenses processing coverage reactively.",
        "links": ["film_study_tendency_extraction", "first_action_predictability_scouting", "scouted_weakness_exploitation_rate", "set_play_recognition_library"],
    },
    {
        "slug": "set_play_recognition_library",
        "title": "Set-Play Recognition Library",
        "summary": "Captures the breadth of an opponent's catalogued set plays a defense can recognize on the call, measured by the fraction of scripted sets that trigger a correct defensive pre-rotation before the first cut.",
        "stat_signature": "Fraction of catalogued opponent sets where defense achieves correct pre-rotation before the primary action; elite recognition libraries cover 70-plus percent of set plays; shallow libraries cover under 40 percent.",
        "mechanism": "Set plays derive value from deception and timing; recognition eliminates the deception premium by allowing the defense to pre-configure before the action initiates, reducing the play to a contested execution rather than a surprise.",
        "conditions": "Most impactful against play-calling offenses with a large scripted repertoire; less relevant against positionless systems that generate action from continuous read-and-react flow rather than called sets.",
        "magnitude": "Correctly pre-rotated set play possessions yield opponents roughly 0.80-0.88 points per possession versus 0.98-1.10 on unrecognized sets; library depth contributes an estimated 1.5-4.0 points per game.",
        "links": ["film_study_tendency_extraction", "first_action_predictability_scouting", "inbound_and_blob_sideline_prep", "prior_meeting_familiarity_curve"],
    },
    {
        "slug": "free_throw_and_shot_diet_priors",
        "title": "Shot-Diet and Free-Throw Priors",
        "summary": "Captures the pre-match expected shot-location and foul-drawing distribution for an opponent, measured by the calibration of forecast rim-rate, midrange-rate, and three-point-rate against realized shot diet.",
        "stat_signature": "Pre-game forecast calibration for rim-rate within plus-or-minus 4 percentage points, midrange-rate within 3 percentage points, and three-point-rate within 5 percentage points; well-calibrated scouting achieves all three bounds simultaneously above 65 percent of games.",
        "mechanism": "Shot-diet priors determine where defensive resources are pre-positioned; a miscalibrated prior over-guards the three-point line while an opponent attacks the rim, systematically conceding the wrong shot type.",
        "conditions": "Highest-value calibration in first-time-meeting games where live adjustment is the only correction mechanism; less critical in rematches where the defense can adjust from observed first-half data.",
        "magnitude": "Defenses with well-calibrated shot-diet priors concede roughly 2-4 fewer points per 48 minutes by pre-positioning correctly rather than reacting to the shot diet after it emerges.",
        "links": ["film_study_tendency_extraction", "shot_contest_priority_mapping", "scouting_report_decay", "hot_hand_and_role_priors"],
    },
    {
        "slug": "transition_trigger_scouting",
        "title": "Transition-Trigger Scouting",
        "summary": "Captures preparation against the specific live-ball events that ignite an opponent's fast break, measured by transition possessions conceded per scouted trigger event versus league baseline.",
        "stat_signature": "Transition possessions conceded per live-ball turnover and long-rebound event for scouted opponents; prepared defenses reduce transition rate to 55-65 percent of turnovers converted to breaks versus 75-85 percent unprepared baseline.",
        "mechanism": "Fast breaks require conversion of a trigger event into a numbers advantage before the defense resets; scouting the preferred triggers (specific player-initiated pushes, immediate secondary breaks) allows the defense to flood back with pre-assigned sprint assignments.",
        "conditions": "Most impactful against high-transition-frequency offenses generating above 18 fast-break possessions per game; less material against slow-paced half-court offenses where transition volume is inherently low.",
        "magnitude": "Prepared transition defense reduces fast-break points allowed by roughly 4-8 points per game against transition-oriented offenses; the suppression is largest against teams exploiting the long-rebound trigger.",
        "links": ["film_study_tendency_extraction", "scouting_report_decay", "first_action_predictability_scouting"],
    },
    {
        "slug": "inbound_and_blob_sideline_prep",
        "title": "Sideline and Baseline Inbound Prep",
        "summary": "Captures preparation against scouted out-of-bounds set actions near the basket, measured by points-per-inbound conceded and the defense's correct-assignment rate on the primary scouted screener.",
        "stat_signature": "Points per baseline and sideline inbound possession for scouted opponents; prepared defenses hold inbound plays to under 0.90 points per possession; unprepared defenses concede 1.05-1.20 on set-play inbounds.",
        "mechanism": "Inbound sets are scripted by design and executed at maximum predictability; defensive correct-assignment depends entirely on pre-game study because there is no read-and-react opportunity once the action unfolds at speed.",
        "conditions": "Most consequential in late-game situations where inbound plays are called with deliberate set-play design; less relevant when inbounds are routine continuation of possessions rather than designed scoring actions.",
        "magnitude": "Defenses with correct-assignment rates above 75 percent on primary screener inbounds concede roughly 0.15-0.25 fewer points per inbound possession than assignment-deficient defenses.",
        "links": ["set_play_recognition_library", "first_action_predictability_scouting", "film_study_tendency_extraction"],
    },
    {
        "slug": "hot_hand_and_role_priors",
        "title": "Role-and-Volume Scouting Priors",
        "summary": "Captures the pre-match expected usage and role distribution across an opposing lineup, measured by calibration of forecast possession-share and shot-volume against realized role usage by lineup grouping.",
        "stat_signature": "Mean absolute error of pre-game usage-rate forecast per rotation group; well-calibrated priors achieve MAE under 3 percentage points per player group; poorly calibrated priors exceed 7 percentage points.",
        "mechanism": "Defensive attention allocation scales with expected usage; miscalibrated role priors cause defenders to over-guard low-volume options while neglecting genuine usage concentrations that emerge in the game.",
        "conditions": "Highest-value calibration against deep rotations where usage can shift substantially based on defensive matchup; lower value against lineups with one dominant usage anchor whose share is stable above 30 percent.",
        "magnitude": "Defenses with calibrated role priors generate 1.5-3.5 fewer points per game from defensive-attention misallocation relative to defenses operating on stale or averaged role assumptions.",
        "links": ["free_throw_and_shot_diet_priors", "shot_contest_priority_mapping", "scouting_report_decay", "film_study_tendency_extraction"],
    },
    {
        "slug": "off_ball_movement_mapping",
        "title": "Off-Ball Movement Mapping",
        "summary": "Captures scouting of an opponent's preferred off-ball cuts, pindowns, and relocation patterns, measured by the defense's chase-and-deny accuracy on the catalogued off-ball routes.",
        "stat_signature": "Catch-rate on scouted off-ball routes versus unscouted routes; well-mapped defenses reduce catch rate on catalogued cuts and relocations by 15-25 percentage points versus naive baseline; unscouted routes maintain full catch rates.",
        "mechanism": "Off-ball threats derive value from misdirection and pre-planned timing; mapping the preferred routes allows defenders to cheat positioning before the action is telegraphed, removing the timing advantage.",
        "conditions": "Highest value against offenses with dedicated off-ball movers operating in scripted pindown-and-relocate sequences; less relevant against positionless systems where off-ball movement is opportunistic rather than designed.",
        "magnitude": "Defenses with comprehensive off-ball route mapping reduce corner-three and cut-finish opportunities from these routes by roughly 20-30 percent, translating to 1.5-3.0 fewer expected points per game from this action type.",
        "links": ["film_study_tendency_extraction", "set_play_recognition_library", "coverage_disguise_anticipation"],
    },
    {
        "slug": "weak_side_help_tendency_read",
        "title": "Weak-Side Help-Tendency Read",
        "summary": "Captures pre-game knowledge of how aggressively an opponent's help defense rotates from the weak side, measured by skip-pass and corner-three generation rate when the scouted help behavior is exploited.",
        "stat_signature": "Corner-three attempt rate when weak-side help tendency is correctly identified and attacked; offenses exploiting an aggressive-helper concede achieve 8-12 corner-threes per 100 possessions above league average in that action type.",
        "mechanism": "Weak-side help overcommitment leaves corner shooters open for skip-pass opportunities; pre-scouted knowledge allows the ball-handler to enter the drive with the skip already planned rather than reading the help post-contact.",
        "conditions": "Most exploitable when the opponent's help defender has a high-frequency rotation tendency above 80 percent of drive attempts; less reliable when help rotation is situational or reads from multiple triggers.",
        "magnitude": "Offenses with accurate weak-side help reads generate roughly 3-6 additional corner-three attempts per game from this pathway, worth an estimated 1.0-2.0 surplus expected points depending on personnel shooting quality.",
        "links": ["coverage_disguise_anticipation", "scouted_weakness_exploitation_rate", "off_ball_movement_mapping"],
    },
    {
        "slug": "late_clock_tendency_scouting",
        "title": "Late-Clock Tendency Scouting",
        "summary": "Captures preparation against an opponent's predictable shot-clock-under-7 action, measured by contest rate and forced-difficult-shot rate on the scouted late-clock option.",
        "stat_signature": "Effective field-goal percentage conceded on shot-clock-under-7 possessions against scouted opponents; prepared defenses hold late-clock eFG% at or below the scouted player's season baseline; unprepared defenses concede 4-8 percentage points above baseline.",
        "mechanism": "Late-clock situations force offenses into their most rehearsed improvisation sequence; pre-identifying the preferred step-back or isolation spot allows defenders to pre-position the contest rather than reacting to the creation move.",
        "conditions": "Most impactful when a single designated late-clock option handles above 60 percent of shot-clock-under-7 possessions; less predictive when late-clock usage is distributed across multiple creators.",
        "magnitude": "Defenses with accurate late-clock scouting force difficult-shot rates 15-25 percentage points higher on those possessions, reducing expected late-clock scoring by roughly 0.08-0.15 points per possession.",
        "links": ["film_study_tendency_extraction", "first_action_predictability_scouting", "shot_contest_priority_mapping"],
    },
    {
        "slug": "scouting_report_decay",
        "title": "Scouting-Report Decay",
        "summary": "Captures how quickly catalogued opponent tendencies become stale as schemes evolve over a season, measured by the decline in tendency-forecast calibration as days since the last observed sample increase.",
        "stat_signature": "Calibration error of tendency forecasts as a function of days since most recent scouted sample; calibration error increases roughly 0.8-1.5 percentage points per additional week of gap; high-variance offenses show 2-plus points per week.",
        "mechanism": "Offensive coordinators make micro-adjustments across a season in response to defensive schemes; tendency catalogs built on 30-plus day old samples fail to capture current play-calling priorities and personnel-role shifts.",
        "conditions": "Decay is fastest for offenses with high mid-season scheme volatility or frequent rotational changes; more stable for systems with a fixed identity and consistent personnel throughout the season.",
        "magnitude": "Scouting reports more than 14 days old show roughly 15-25 percent higher tendency-forecast error than reports within 7 days; the accuracy gap translates to 1.5-3.5 additional points conceded from stale-report-driven miscoverage.",
        "links": ["film_study_tendency_extraction", "prior_meeting_familiarity_curve", "free_throw_and_shot_diet_priors", "hot_hand_and_role_priors"],
    },
    {
        "slug": "matchup_hunting_avoidance_plan",
        "title": "Matchup-Hunting Avoidance Plan",
        "summary": "Captures the defensive pre-plan to hide a targeted weak defender from being hunted, measured by the success rate of pre-switches and scram actions that remove the scouted mismatch before the catch.",
        "stat_signature": "Rate at which pre-planned scram switches and pre-switches successfully remove the targeted defender before ball-screen completion; effective avoidance plans achieve 70-plus percent removal rate; reactive plans fall below 45 percent.",
        "mechanism": "Pre-empting the hunt requires the defensive unit to recognize screening action intent before the mismatch materializes; pre-committed scram assignments shift the cognitive burden to offense, which must re-identify the new defensive configuration mid-action.",
        "conditions": "Most executable in structured ball-screen situations where the screening angle reveals intent early; less applicable in off-ball screen-the-screener actions where the mismatch creation is more covert.",
        "magnitude": "Successful mismatch avoidance on targeted possessions reduces offensive production by roughly 0.10-0.18 points per possession from what a completed mismatch would yield; across a game 2-5 surplus points are preserved.",
        "links": ["personnel_matchup_targeting_plan", "scouted_weakness_exploitation_rate", "coverage_disguise_anticipation", "shot_contest_priority_mapping"],
    },
    {
        "slug": "shot_contest_priority_mapping",
        "title": "Shot-Contest Priority Mapping",
        "summary": "Captures the scouted decision on which opponents to run off the line versus sag against, measured by alignment between assigned contest aggression and each opponent's catalogued shot profile.",
        "stat_signature": "Alignment rate between pre-game contest-assignment and realized shot-profile demand; well-mapped defenses align on 80-plus percent of primary offensive players; misaligned defenses over-contest non-shooters above 30 percent of the time.",
        "mechanism": "Contest aggression is a scarce resource; defenders who sprint at non-shooters are out of position for drives, while sagging against high-volume three-point threats concedes open looks. Pre-scouted shot-profile assignment eliminates on-the-fly misallocation.",
        "conditions": "Highest value in lineups with wide shot-profile heterogeneity, where one player is a prolific three-point threat and an adjacent player is a non-shooter; less discriminating in uniform-shooting lineups where a single contest rule applies to all.",
        "magnitude": "Defenses with correct contest priority mapping concede roughly 2-4 fewer open corner-threes and 1.5-3.0 fewer rim attempts per game than defenses applying uniform closeout rules regardless of shooter profile.",
        "links": ["free_throw_and_shot_diet_priors", "scouted_weakness_exploitation_rate", "matchup_hunting_avoidance_plan", "film_study_tendency_extraction"],
    },
]
