"""MLB PossessionControl concept nodes — person-free possession-resource intelligence."""
from __future__ import annotations

SPORT = "MLB"
FAMILY = "PossessionControl"

CONCEPTS: list[dict] = [
    {
        "slug": "outs_management_economy",
        "title": "Outs-Management Economy per 27 Outs",
        "summary": "Baseball offense operates against a fixed budget of 27 outs rather than a clock; the foundational efficiency metric is runs produced per out consumed, which determines whether a lineup extracts maximal value from its finite possession resource.",
        "stat_signature": "Runs per 27 outs (runs per game) league average 4.3-4.6; top-quartile lineups exceed 5.0; efficiency ratio of runs to unproductive outs (popups, K looking, non-advancing grounders) separates lineup constructions; innings ending with zero runs despite multiple baserunners signal possession waste.",
        "mechanism": "Unlike clock-bounded sports, each out is irreplaceable and non-renewable within an inning; a wasted out that neither advances a runner nor threatens the battery forces the lineup to produce runs from a depleted budget; lineup construction that minimizes unproductive out-consuming events raises expected runs per inning by preserving base-state progression paths.",
        "conditions": "Economy matters most in low-scoring environments where park factors suppress extra-base hits and lineups cannot rely on power to override poor out usage; amplified in late-inning situations where partial out budgets remain and each out consumed is irrecoverable.",
        "magnitude": "A difference of 0.4 runs per game between efficient and inefficient lineups accumulates to roughly 65 runs over a season, equivalent to approximately six to seven wins in standard run-to-win conversion.",
        "links": ["productive_out_rate", "double_play_avoidance_rate", "two_out_rally_extension", "base_state_run_expectancy_control"],
    },
    {
        "slug": "double_play_avoidance_rate",
        "title": "Double-Play Avoidance Rate",
        "summary": "A grounded-into-double-play event consumes two outs from a single plate appearance, the steepest per-event possession drain in baseball; avoiding it in double-play situations (runner on first, fewer than two outs) is a foundational offensive efficiency discipline.",
        "stat_signature": "GIDP per double-play opportunity: league band 10-12 %; left-side ground-ball hitters near 13-15 %; pull-oriented elevated-launch hitters near 6-8 %; hard-contact ground-ball rate into the pull side above 18 % of contact flags high GIDP exposure.",
        "mechanism": "A GIDP event removes the baserunner, records the batter out, and resets run expectancy from a populated state to a bases-empty two-out state, erasing the value created by the preceding baserunner's presence; the two-out debit compounds because the next hitter faces the worst base-out state (0 on, 2 out) in the 24-cell run-expectancy matrix.",
        "conditions": "Exposure peaks when a slow-footed pull-heavy ground-ball hitter bats with a runner on first and fewer than two outs against a ground-ball-inducing sinker/two-seam pitcher; suppressed against fly-ball pitchers who generate pop-ups and lofted contact instead of hard grounders.",
        "magnitude": "Each GIDP costs approximately 0.85-1.05 runs in run-expectancy delta relative to a non-DP groundout; lineups averaging 120 GIDP per season surrender roughly 30-40 additional runs above lineups at 90 GIDP.",
        "links": ["ground_ball_double_play_exposure", "outs_management_economy", "double_play_turn_defense", "base_state_run_expectancy_control"],
    },
    {
        "slug": "ground_ball_double_play_exposure",
        "title": "Ground-Ball Double-Play Exposure",
        "summary": "A hitter's ground-ball rate and pull-ground-ball tendency establish the batted-ball-profile component of double-play risk, independent of how frequently a runner occupies first base; this batted-ball signature predicts GIDP vulnerability across lineup contexts.",
        "stat_signature": "Ground-ball rate above 50 % combined with pull rate above 45 % identifies peak DP exposure profiles; pull-ground-ball percentage (PGB%) above 22 % correlates with GIDP rate exceeding 12 %; hard-hit ground-ball rate on sinkers above 25 % raises the per-opportunity conversion rate the defense achieves.",
        "mechanism": "Pulled hard grounders to the third-base and shortstop side hit slower infield grass at an angle that maximizes 5-4-3 and 6-4-3 double-play opportunity; the ball reaches the shortstop or third baseman with sufficient time and favorable angle for a pivot throw, whereas opposite-field grounders typically travel to first-side infielders at angles that make the relay throw to second more difficult.",
        "conditions": "Exposure is compounded against sinker-heavy ground-ball pitchers who attack the lower half of the zone; stadium infield surfaces with less grass friction (faster artificial or hard dirt) speed the ball to infielders, raising conversion probability; cold ambient temperatures also harden infield clay and accelerate the hop.",
        "magnitude": "A 10-percentage-point increase in pull-ground-ball rate corresponds to approximately 1.5-2.0 additional GIDP per 150 double-play opportunities, a roughly 1.0-1.5 run-expectancy cost over a typical season.",
        "links": ["double_play_avoidance_rate", "double_play_turn_defense", "force_out_versus_advance_routing", "outs_management_economy"],
    },
    {
        "slug": "baserunning_extra_base_rate",
        "title": "Extra-Base Advancement Rate on Batted Balls",
        "summary": "How often a baserunner converts a single into a first-to-third advance, or a double into a scoring play from first, directly measures base-state enrichment per batted ball, translating contact quality into run-expectancy gains without requiring an additional hit.",
        "stat_signature": "Extra-base taken percentage (XBT%) league average 40-45 %; top-quartile baserunning lineups above 50 %; first-to-third on a single: taken in roughly 27-32 % of opportunities; scoring from first on a double: roughly 55-62 % depending on outfield arm strength and baserunner speed.",
        "mechanism": "Base advancement converts a static base occupancy (runner on first) into a higher run-expectancy state (runner on second or third) at zero out cost; the gain is purely additive to expected runs because no out is spent; the decision requires accurate read of ball trajectory, outfield jump, and arm strength, with each correct aggressive read adding approximately 0.15-0.30 expected runs.",
        "conditions": "Highest return against outfielders with below-average arm strength or slow first steps; most valuable with two outs when the only scoring path requires base advancement before the final out; suppressed against center fielders with above-average range who cut off balls in the gap.",
        "magnitude": "A team with XBT% of 50 % generates approximately 10-15 additional bases per 162 games versus a 40 % team, translating to roughly 8-12 extra expected runs from baserunning alone.",
        "links": ["first_to_third_aggression_efficiency", "stolen_base_success_threshold", "baserunning_outs_on_bases", "base_state_run_expectancy_control"],
    },
    {
        "slug": "stolen_base_success_threshold",
        "title": "Stolen-Base Success Above the Break-Even Threshold",
        "summary": "A stolen base attempt is a run-expectancy wager: the gain from the stolen base must exceed the expected-run cost of a caught stealing at the relevant base-out state; the break-even success rate for stealing second with nobody out is approximately 70-74 %.",
        "stat_signature": "Break-even success rate: stealing second with 0 out near 72 %; with 1 out near 74 %; with 2 out near 76 % because the out cost is smaller relative to run expectancy; success rate above 75 % is net-positive across all base-out states; league average success rate historically 68-72 %, recently elevated to 78-80 % under rule changes.",
        "mechanism": "A successful steal advances the runner to a higher run-expectancy state at zero out cost; a caught stealing simultaneously removes a baserunner and adds an out, inflicting a double penalty: the run-expectancy loss from losing the runner plus the out-consumption cost that moves the defense toward the inning-ending state.",
        "conditions": "Attempts are highest-value against batteries with slow combined times (pitcher delivery plus catcher pop time) exceeding 2.05 s; attempts are negative-expectancy against elite pop-time catchers below 1.85 s or combined times below 1.95 s even at high individual success rates.",
        "magnitude": "A team improving success rate from 68 % to 78 % on 150 annual attempts converts approximately 15 caught-stealings into stolen bases, gaining roughly 0.30 expected runs per conversion for a total of 4-5 additional expected runs per season from the steal game alone.",
        "links": ["caught_stealing_possession_cost", "caught_stealing_throwing_control", "baserunning_outs_on_bases", "base_state_run_expectancy_control"],
    },
    {
        "slug": "caught_stealing_possession_cost",
        "title": "Caught-Stealing Possession and Run-Expectancy Cost",
        "summary": "A caught stealing inflicts the steepest single-play run-expectancy penalty in the baserunning domain by simultaneously erasing a baserunner and consuming an out, contracting the offense from a base-occupied state to a higher-out-count state with no baserunner.",
        "stat_signature": "Run-expectancy delta for caught stealing second with 0 out: approximately negative 0.46 runs; with 1 out: negative 0.41 runs; with 2 out: negative 0.26 runs; cumulative season cost for a team with 45 caught stealings at average base-out distribution: roughly 18-22 runs.",
        "mechanism": "The double penalty of losing the runner and the out distinguishes a caught stealing from a routine groundout, which at least preserves the batter's consumption of a single out without removing a baserunner; the compound contraction of the base-state immediately lowers scoring probability for the remainder of the inning, and the out-count advancement brings the inning closer to termination.",
        "conditions": "The cost is highest with the lead runner on first with zero outs because the lost run-expectancy delta is maximized when the remaining base-state was most productive; lowest with two outs because the inning is near-termination regardless and the marginal out cost is smallest.",
        "magnitude": "A team reducing caught stealings by 10 per season (from 45 to 35 attempts failing) recovers approximately 4-5 expected runs, equivalent to roughly half a win in standard conversion.",
        "links": ["stolen_base_success_threshold", "baserunning_outs_on_bases", "outs_management_economy", "base_state_run_expectancy_control"],
    },
    {
        "slug": "baserunning_outs_on_bases",
        "title": "Outs-on-the-Bases Rate from Aggressive Advancement",
        "summary": "Runners thrown out attempting to advance on batted balls — rounding third on a single, tagging and scoring on a deep fly, or taking an extra base on a double — are self-inflicted outs distinct from stolen-base caught stealings, measurable as baserunning outs per advancement opportunity.",
        "stat_signature": "Outs-on-bases per 162 games: conservative teams below 8; aggressive teams above 18; outs-per-opportunity on balls in play near 2-4 % for disciplined baserunning lineups; each additional baserunning out costs approximately 0.50-0.70 expected runs depending on the base-out state at the moment of the attempt.",
        "mechanism": "An out recorded on the bases while a ball is in play drains the out budget while also eliminating a runner who was already in a scoring position; unlike strikeouts, these outs are discretionary decision-based events that reflect read-and-react judgment quality from the runner and third-base coach rather than pitcher-induced outcomes.",
        "conditions": "Frequency rises against outfielders with above-average arm strength who encourage third-base coach caution yet draw runners who misread arm strength; amplified in must-score late-inning situations where aggressive choices are rational but execution errors cost disproportionately.",
        "magnitude": "A team generating 18 baserunning outs per season loses approximately 10-13 expected runs compared with a team generating 8; the difference in winning percentage corresponds to roughly 1.0-1.3 wins per season.",
        "links": ["caught_stealing_possession_cost", "baserunning_extra_base_rate", "first_to_third_aggression_efficiency", "tagging_up_sacrifice_advancement"],
    },
    {
        "slug": "productive_out_rate",
        "title": "Productive-Out Rate in Advancement Situations",
        "summary": "A productive out advances a baserunner without generating a run, purchasing base-state progress at the unavoidable cost of one out; tracking the share of outs that are productive versus wasted captures whether a lineup extracts positional value even from its inevitable out consumption.",
        "stat_signature": "Productive out rate: advancement situations defined as runner on second with fewer than two outs or runner on third with fewer than two outs; productive out conversion near 35-42 % league average in those situations; a fly-out advancing a runner from second to third counts; a strikeout looking in the same situation is a zero-return out.",
        "mechanism": "An out that advances a runner converts the out-consumption into a base-state improvement: a runner moving from second to third raises run-expectancy by approximately 0.22 runs at one out, partially offsetting the out cost; a wasted out delivers neither runner advancement nor run, extracting no positive value from the possession budget expenditure.",
        "conditions": "Most relevant with a runner on second and fewer than two outs and a contact hitter at the plate; right-side grounders advancing a runner from second to third are the primary productive-out type; deep fly balls to the warning track perform similarly when the runner can tag; suppressed against extreme strikeout pitchers who prevent contact-based productive outs.",
        "magnitude": "A team with a 42 % productive-out conversion rate in advancement situations generates approximately 12-18 additional expected-run contributions per season versus a 30 % team, reflecting the cumulative base-state improvement across hundreds of advancement opportunities.",
        "links": ["outs_management_economy", "tagging_up_sacrifice_advancement", "sacrifice_bunt_out_tradeoff", "base_state_run_expectancy_control"],
    },
    {
        "slug": "first_to_third_aggression_efficiency",
        "title": "First-to-Third Aggression Efficiency",
        "summary": "The decision to advance from first to third on a single is the highest-stakes routine base-advancement choice, requiring a read of ball exit velocity, outfield positioning, and arm strength before committing to an attempt that cannot be reversed mid-route.",
        "stat_signature": "First-to-third attempt rate among opportunities: league average 28-33 %; success rate among attempts: league average 82-87 %; attempts rate above 40 % with success below 78 % signals over-aggression; attempts rate below 20 % with success above 90 % signals excessive conservatism that wastes safe advancement opportunities.",
        "mechanism": "Reaching third from first on a single converts a two-base-advancement into a scoring-position gain with a subsequent sacrifice fly or groundout path to a run; the run-expectancy premium of being on third with one out (0.97 runs) versus second with one out (0.66 runs) is 0.31 runs, the value gained by successful aggression; an out at third costs approximately 0.45-0.65 expected runs.",
        "conditions": "Efficiency is highest against left fielders fielding in the right-center gap where the throw angle to third is longest; suppressed against right fielders in the right-center gap who have shorter throws to third base with momentum; also suppressed when the third baseman is stationed near the base, shortening the effective throw distance.",
        "magnitude": "A team converting 35 % of first-to-third opportunities at 85 % success generates approximately 5-8 additional expected runs per season above a team converting 25 % at the same success rate, purely from the base-advancement premium.",
        "links": ["baserunning_extra_base_rate", "baserunning_outs_on_bases", "caught_stealing_throwing_control", "base_state_run_expectancy_control"],
    },
    {
        "slug": "tagging_up_sacrifice_advancement",
        "title": "Tag-Up and Sacrifice Advancement Yield",
        "summary": "Tagging on fly outs and executing bunt sacrifices are the primary methods of purchasing base advancement at the cost of a premeditated or induced out; the yield — bases advanced per qualifying opportunity — measures whether the out expenditure translates into positional gain.",
        "stat_signature": "Tag-up success rate from third on fly outs to the outfield: 93-97 % when the attempt is made; tag-up rate from second on medium-depth outfield flies: 45-55 % of qualifying fly outs; sacrifice bunt success rate (runner advances, batter out): 88-93 % of attempts; failed sacrifice (runner not advanced, batter out) rate 4-8 %.",
        "mechanism": "Tagging on a fly out converts a routine out into a scoring-position advance or even a run without spending any additional out; the advancement is cost-free if the tag succeeds because the out was already registered by the fly ball; sacrifice bunts voluntarily trade an out for a runner advance, with the run-expectancy tradeoff depending on the base-out state and the lineup slot following the sacrifice.",
        "conditions": "Tag-up yield highest with fast runners on second who can reach third on medium-depth left-center flies; sacrifice bunt value highest when the pitcher bats or a weak lineup slot precedes stronger hitters, concentrating run-production load on better contact options; the three-batter minimum for pitchers has eliminated the sacrifice as a tool in the highest-leverage bullpen situations.",
        "magnitude": "A successful tag-up from third to home adds approximately 0.50-0.60 expected runs versus the strikeout or pop-up alternative; a productive tag from second to third adds 0.22 expected runs at one out, compounding across 60-80 qualifying opportunities per season for an aggressive baserunning team.",
        "links": ["productive_out_rate", "sacrifice_bunt_out_tradeoff", "baserunning_extra_base_rate", "baserunning_outs_on_bases"],
    },
    {
        "slug": "double_play_turn_defense",
        "title": "Defensive Double-Play Conversion Rate",
        "summary": "A defense's ability to turn the available double play converts one batted ball into two outs, seizing the maximum possession leverage from a single defensive play and resetting the offense's run-expectancy to a near-inning-termination state.",
        "stat_signature": "Double-play conversion rate per opportunity: league average 42-47 %; elite infield units above 52 %; shortstop pivot time (ball received to release on relay throw) of 0.55-0.70 s separates elite from average turners; hard-hit ground-ball double-play conversion drops to 28-35 % because reduced time to first base shortens the relay window.",
        "mechanism": "A successful double play instantly voids the run-expectancy accumulated by the preceding baserunner and records two outs in a single defensive action; the compounding effect resets the inning to a state where a subsequent hit cannot score the erased runner, compressing the offensive threat more severely than any other single defensive play.",
        "conditions": "Conversion rate highest on slow-to-medium ground balls to the left side where the pivot has the most time; drops against left-handed pull hitters who direct grounders away from the shortstop pivot; artificial turf surfaces raise conversion rates by accelerating ball travel to infielders and providing consistent hops.",
        "magnitude": "Each converted double play versus a single out outcome saves approximately 0.50-0.80 expected runs depending on base-out state; an infield that converts 52 % of double-play opportunities versus 42 % records roughly 15-20 additional double plays per season, saving an estimated 10-16 runs.",
        "links": ["double_play_avoidance_rate", "ground_ball_double_play_exposure", "force_out_versus_advance_routing", "defensive_extra_out_creation"],
    },
    {
        "slug": "caught_stealing_throwing_control",
        "title": "Caught-Stealing and Running-Game Suppression",
        "summary": "The battery's combined pop time, pitch tempo, and pickoff frequency controls how often opponents attempt stolen bases and how many attempts are neutralized, suppressing the opponent's base-advancement resource without requiring a batted ball.",
        "stat_signature": "Catcher pop time (glove to second base): elite below 1.85 s; average 1.90-2.00 s; fringe above 2.05 s; combined battery time (pitcher delivery plus pop time) below 1.95 s suppresses attempts to 0.8-1.0 per nine innings; caught-stealing rate by battery: league average 22-27 %; elite battery above 35 %.",
        "mechanism": "A short combined delivery-to-throw time compresses the window in which a runner can safely advance; catchers with sub-1.85-s pop times require runners to attempt only the cleanest leads, suppressing attempt rates because the break-even success threshold rises; pitchers who vary delivery times from the stretch disrupt runner timing-read without using disengagement budget.",
        "conditions": "Suppression most effective against average-speed baserunners who depend on timing reads rather than pure acceleration; fast runners remain viable stealers even against elite batteries if their first-step quickness generates sufficient head-start; the rule-capped disengagement limit reduces the battery's ability to reset runner timing through repeated pickoffs.",
        "magnitude": "Batteries suppressing attempts to fewer than 1.0 per nine innings effectively neutralize the running game; each prevented stolen base is worth approximately 0.20 expected runs saved; over a season a dominant throwing battery might prevent 20-30 additional attempts versus a fringe battery, saving 4-6 expected runs.",
        "links": ["stolen_base_success_threshold", "caught_stealing_possession_cost", "pickoff_and_lead_management", "first_to_third_aggression_efficiency"],
    },
    {
        "slug": "leadoff_baserunner_conversion",
        "title": "Leadoff-Baserunner Conversion to Runs",
        "summary": "When the first batter of an inning reaches base, the lineup enters a high-leverage state with a full out budget and a runner aboard; how reliably that leadoff baserunner is converted into a run is the clearest inning-efficiency measure.",
        "stat_signature": "League-average leadoff-runner-to-run conversion: approximately 40-44 %; top-quartile lineups above 48 %; innings with a leadoff walk score at roughly 39-42 %, leadoff singles at 40-44 %, leadoff home runs at 100 %; the gap between a team's leadoff conversion rate and 40 % represents pure lineup execution efficiency.",
        "mechanism": "A leadoff baserunner activates the full inning run-expectancy (approximately 0.53 runs versus 0.28 for a leadoff out) and shifts the defensive burden to managing the runner and the risk of a multi-run inning; converting the leadoff runner requires a chain of subsequent decisions (advancing via contact, stealing, or staying put) to avoid out-consuming events that leave the runner stranded.",
        "conditions": "Conversion rate rises when the lineup bats its three-four-five core with the baserunner on and when the next batter avoids a double play; conversion falls when the lineup's middle of the order is low in the lineup slot cycle and weaker hitters must drive in the leadoff runner; park factors suppressing extra-base hits reduce conversion by limiting the run-scoring paths.",
        "magnitude": "A team converting leadoff baserunners at 48 % versus 40 % over 1,458 innings (162 games) scores approximately 12-15 additional runs per season, assuming roughly 1.5 leadoff baserunners per nine innings.",
        "links": ["outs_management_economy", "two_out_rally_extension", "base_state_run_expectancy_control", "productive_out_rate"],
    },
    {
        "slug": "wild_pitch_passed_ball_advancement",
        "title": "Wild-Pitch and Passed-Ball Free Advancement",
        "summary": "Base advancement via battery miscues adds runners to scoring position without consuming an out or requiring a batted ball, generating expected-run value at zero possession cost to the offense and creating pressure that compounds with subsequent plate appearances.",
        "stat_signature": "Wild pitches per nine innings: league average 0.55-0.70; passed balls per nine innings: league average 0.10-0.15; combined miscue rate above 0.90 per nine innings identifies high-opportunity batteries; runner advancement per miscue: single-base advancement in 75-85 % of cases where a runner is aboard and the opportunity exists.",
        "mechanism": "A battery miscue that advances a runner changes the base-out state without an out transaction: a runner on first advancing to second on a wild pitch raises run expectancy by approximately 0.14-0.22 runs at various out counts at no cost; the advance increases the probability that a subsequent single or sacrifice fly scores the runner, amplifying the value of downstream plate appearances.",
        "conditions": "Wild-pitch advancement opportunities highest against battery pairs featuring a breaking-ball heavy repertoire in the dirt and a catcher with below-average framing and blocking skills; amplified in cold weather when fingers are cold and grip insecurity increases; the designated universal DH also reduces the battery's motivation to waste pitches in low-leverage situations.",
        "magnitude": "A lineup that benefits from 90 combined wild-pitch and passed-ball advancements per season (versus a league-average 75) gains approximately 10-15 expected-run opportunities from the extra base-state improvements, translating to 2-4 additional runs scored.",
        "links": ["base_state_run_expectancy_control", "leadoff_baserunner_conversion", "productive_out_rate", "tagging_up_sacrifice_advancement"],
    },
    {
        "slug": "base_state_run_expectancy_control",
        "title": "Base-Out State Run-Expectancy Management",
        "summary": "Every offensive and defensive decision can be evaluated as a transition between the 24 base-out states on the run-expectancy matrix; tracking how aggressively each side trades out-risk for base-advancement gain is the unifying lens over all possession-resource choices.",
        "stat_signature": "Run-expectancy range: 0.11 runs (bases empty, 2 out) to 2.25 runs (bases loaded, 0 out); run-expectancy delta per play distinguishes value-generating from value-destroying decisions; a lineup's average base-out state run-expectancy at plate-appearance start measures structural base-creation quality.",
        "mechanism": "The 24-cell matrix makes explicit the run-expectancy premium of each additional base and the out-consumption cost of each transition; teams that systematically move runners into higher-expectancy states at acceptable out-risk accumulate more expected runs per inning than teams that allow states to contract toward bases-empty through outs and failed baserunning; the matrix also makes the sacrifice bunt cost explicit — most states show negative run-expectancy delta from a voluntary out.",
        "conditions": "The framework is most powerful in low-leverage mid-inning states where optimal base-state management determines whether a half-inning produces zero or one run; in high-run-expectancy states (bases loaded) the incremental gain from further advancement is capped, while the out-cost risk remains constant.",
        "magnitude": "Teams averaging 0.10 higher run-expectancy at PA start due to superior base-state management score approximately 2-4 additional runs per 162 games from structural advantages alone, independent of plate-discipline or batted-ball quality improvements.",
        "links": ["outs_management_economy", "productive_out_rate", "leadoff_baserunner_conversion", "sacrifice_bunt_out_tradeoff"],
    },
    {
        "slug": "sacrifice_bunt_out_tradeoff",
        "title": "Sacrifice-Bunt Out-for-Base Tradeoff",
        "summary": "The sacrifice bunt deliberately trades an out for a runner advance, a tradeoff that is negative in run expectancy in most base-out states for non-pitcher hitters, but may be positive when the lineup slot batting is the weakest hitter preceding a strong run of hitters.",
        "stat_signature": "Run-expectancy delta: runner on first, 0 out (0.85 runs) sacrificed to runner on second, 1 out (0.66 runs) = negative 0.19 runs net; runner on second, 0 out (1.10 runs) sacrificed to runner on third, 1 out (0.97 runs) = negative 0.13 runs net; sacrifice bunt frequency above 0.8 per game signals frequent use despite negative-expectancy profiles.",
        "mechanism": "Voluntarily consuming an out that advances a runner sacrifices inning continuation for positional improvement; the tradeoff is negative in standard run-expectancy accounting because the out wasted is more costly than the base gained in most states; the exception arises when the out removes a weak hitter from a two-strike threat state and places the runner where a subsequent productive out or fly ball can score without requiring a hit.",
        "conditions": "Positive run-expectancy sacrifice scenarios: pitcher hitting (a genuine weak hitter replacing an out with a runner-advance cost offset by the hitter replacement effect), very tight late-game one-run situations where a single run wins, or top-of-the-lineup positioning where the sacrifice puts the best run-producers at bat in scoring-position states.",
        "magnitude": "A team executing 120 sacrifice bunts per season at an average negative run-expectancy delta of 0.15 runs surrenders approximately 18 expected runs relative to a lineup that attempts the hit or draw; modern analytical lineups average 20-40 sacrifice attempts, recovering roughly 12-15 expected runs over high-bunting teams.",
        "links": ["productive_out_rate", "base_state_run_expectancy_control", "tagging_up_sacrifice_advancement", "outs_management_economy"],
    },
    {
        "slug": "defensive_extra_out_creation",
        "title": "Defensive Extra-Out Creation Beyond the Routine",
        "summary": "Outs generated above those guaranteed by batted-ball probability — through exceptional range, accurate relay throws, and runner-cutting plays at the bases — represent the defense claiming possession units the offense's contact quality did not necessarily surrender.",
        "stat_signature": "Outs above average (OAA) and defensive runs saved (DRS) metrics quantify range-based out creation; relay-throw accuracy on runner-at-third cut-off plays: elite infields convert 55-65 % of scoring-range throws into outs; outfield arm-out rate (runners thrown out attempting to advance) above 8-10 per season for strong outfield arms.",
        "mechanism": "A batted ball converted into an out by exceptional range prevents the out from escaping as a hit that populates a base-state; a relay play at third or home that records an advancing runner eliminates a baserunner and an out simultaneously, matching the double-play's run-expectancy impact; each extra defensive out shrinks the offensive possession budget before the run-scoring chain can complete.",
        "conditions": "Extra outs are most impactful in the seventh through ninth innings where opponent lineups are depleted to weaker hitters and preventing baserunners compounds by cutting off scoring opportunities; a deep outfield that suppresses extra-base hits also suppresses base-state escalation even when contact is not converted into outs.",
        "magnitude": "A defense generating 20 outs above average per season saves approximately 12-18 runs relative to a league-average defense, reflecting both the prevented hits and the runner eliminations on the bases.",
        "links": ["double_play_turn_defense", "caught_stealing_throwing_control", "force_out_versus_advance_routing", "double_play_avoidance_rate"],
    },
    {
        "slug": "two_out_rally_extension",
        "title": "Two-Out Rally-Extension and Out-Preservation",
        "summary": "Reaching base with two outs preserves the inning against imminent termination; the two-out on-base rate and runs-scored-after-two-outs metric capture a lineup's ability to extend possession beyond the brink of the half-inning's end.",
        "stat_signature": "Two-out OBP: league average 0.290-0.305; elite lineups above 0.320; runs scored per inning with two-out rallies: approximately 0.18-0.25 runs per inning, accounting for roughly 20-25 % of total runs scored; two-out RBI rate above 28 % indicates high late-count clutch production.",
        "mechanism": "A baserunner reached with two outs converts an imminent inning-end into a continued scoring opportunity: the single remaining possession unit (the plate appearance with two outs) is extended into a populated base state where subsequent hitters can drive runs; each two-out hit also resets the count for the batter-runner and the inning continues, compounding further multi-hit rally probability.",
        "conditions": "Two-out production peaks against fatigued starters late in starts and when the batting order cycles through its best hitters at the two-out moment; suppressed against dominant relief specialists brought in with two outs who have the platoon advantage against the due hitter.",
        "magnitude": "A team with a two-out OBP of 0.320 versus 0.290 over 4,500 two-out plate appearances per season generates approximately 135 additional baserunners, corresponding to roughly 20-25 additional expected runs over the season from two-out rally extension.",
        "links": ["outs_management_economy", "leadoff_baserunner_conversion", "base_state_run_expectancy_control", "double_play_avoidance_rate"],
    },
]
