"""Soccer PredictabilityTendencies spec — how telegraphed a team's build-up,
set-pieces, and attacking patterns are; decision entropy in possession.

Person-free, descriptive intelligence; no edge/ROI/pick claims.
"""
from __future__ import annotations

SPORT = "Soccer"
FAMILY = "PredictabilityTendencies"

CONCEPTS: list[dict] = [
    {
        "slug": "buildup_side_bias_predictability",
        "title": "Build-Up Side-Bias Predictability",
        "summary": "How consistently a side channels early possession through one flank, measured as directional imbalance in progressive passes and carries across pitch width.",
        "stat_signature": "Side bias above 58% of progressive actions on one flank is noteworthy; build-up pass-direction entropy below 1.4 bits signals a patterned approach.",
        "mechanism": "A persistent channel preference lets opponents overload the preferred side in mid-block, compressing the lane and forcing later tempo-killing switches.",
        "conditions": "Most legible against mid- and low-block defences that have time to shape their press around scouted tendencies; diluted against high-press systems.",
        "magnitude": "Sides above the 75th percentile in side bias see roughly 8-12% lower progressive-carry completion on the preferred flank when opponents concentrate coverage there.",
        "links": ["attacking_channel_preference_telegraphing", "wing_overload_tendency_telegraphing", "tempo_script_predictability", "deception_disguise_capacity"],
    },
    {
        "slug": "goal_kick_distribution_predictability",
        "title": "Goal-Kick Distribution Tendency",
        "summary": "How reliably a side signals its restart target — short to centre-backs, lateral to fullbacks, or long to forwards — letting opponents pre-position their press.",
        "stat_signature": "Long-ball share above 65% or short-circulation share above 70% of goal kicks; distribution entropy below 1.2 bits across three channels flags a scoutable pattern.",
        "mechanism": "A predictable channel lets the pressing side pre-load aerial duellers and press-triggers before the ball is struck rather than reacting to the delivery.",
        "conditions": "Against high-press systems the long-ball default becomes a contested aerial duel; against passive shapes the short routine is learnable but rarely punished.",
        "magnitude": "Predictable distribution allows opponents to win the first aerial 10-15% more often; second-ball recovery drops by a similar margin when the channel is anticipated.",
        "links": ["first_phase_pressing_trigger_predictability", "low_block_exit_route_predictability", "tempo_script_predictability", "buildup_side_bias_predictability"],
    },
    {
        "slug": "corner_routine_repetition",
        "title": "Corner-Routine Repetition Rate",
        "summary": "The degree to which a side reuses the same delivery zone, runner path, and blocking arrangement across successive corners, eroding surprise value.",
        "stat_signature": "Fewer than three distinct corner routines in a 15-plus corner sample flags high repetition; delivery-zone entropy below 1.1 bits indicates near-deterministic targeting.",
        "mechanism": "Repeated routines let the defending unit pre-assign responsibilities based on runner paths, converting a set-piece advantage into a neutral contest.",
        "conditions": "Most punishing against disciplined set-piece defences that share footage in advance; less harmful against man-mark schemes focused on individual coverage.",
        "magnitude": "Scouted corners yield header-on-target rates roughly 15-20% lower than unscouted equivalents; expected-goal value per corner falls from ~0.045 toward ~0.027.",
        "links": ["free_kick_delivery_tendency", "set_piece_marking_scheme_tells", "penalty_taking_direction_tendency", "throw_in_pattern_predictability"],
    },
    {
        "slug": "free_kick_delivery_tendency",
        "title": "Free-Kick Delivery Tendency",
        "summary": "Whether a side defaults to in-swinging, out-swinging, or driven deliveries from wide and central free-kick positions, replicated consistently enough to be scouted.",
        "stat_signature": "A single delivery type exceeding 65% of wide free kicks is a predictable tendency; delivery-curve correlation above 0.80 across attempts quantifies repeatability.",
        "mechanism": "When the delivery curve is known, goalkeeper and wall positioning neutralises expected quality before the ball is struck.",
        "conditions": "Most readable in central positions where the direct-or-indirect choice is binary; delivery-foot preference remains scoutable from wider angles too.",
        "magnitude": "Expected-goal value of a predictable direct free kick drops roughly 0.01-0.02 when the wall is optimally positioned for the known curve.",
        "links": ["corner_routine_repetition", "set_piece_marking_scheme_tells", "crossing_versus_cutback_tendency", "penalty_taking_direction_tendency"],
    },
    {
        "slug": "throw_in_pattern_predictability",
        "title": "Throw-In Pattern Predictability",
        "summary": "The consistency of receiver role and direction on throw-ins — backward safety, square to a midfielder, or long diagonal — making the restart pre-anticipatable.",
        "stat_signature": "Backward throw-in share above 60% flags safety-first tendencies; directional entropy below 1.2 bits; long-throw frequency above 15% in the final third is a distinct tell.",
        "mechanism": "A predictable throw-in target lets the pressing side pre-trigger rather than react, compressing the restart window and raising dispossession risk.",
        "conditions": "Matters most in the middle third where a pressed throw-in creates danger; less consequential in deep defensive thirds where safety is structurally appropriate.",
        "magnitude": "Dispossession rate on throw-ins rises roughly 8-14% when the target and direction are pre-anticipated by the press.",
        "links": ["buildup_side_bias_predictability", "first_phase_pressing_trigger_predictability", "low_block_exit_route_predictability", "tempo_script_predictability"],
    },
    {
        "slug": "first_phase_pressing_trigger_predictability",
        "title": "First-Phase Press-Trigger Predictability",
        "summary": "How consistently a pressing side signals its activation cue — a back-pass to the goalkeeper, a square ball to the centre-back — enabling opponents to rehearse escapes.",
        "stat_signature": "Press-trigger cue entropy below 1.3 bits across sequences indicates a learnable signal; ball-win rate drops 10-18% when opponents pre-read the trigger.",
        "mechanism": "A single trigger allows the possession team to time a rehearsed escape — a third-man run or wide switch — converting the press from reactive hunt to known set piece.",
        "conditions": "Most consequential against technically proficient possession sides that execute pre-planned press-break patterns; less exploited against direct sides.",
        "magnitude": "When opponents correctly anticipate the trigger, ball-win rate in the pressed third typically falls from ~35-40% toward ~25-28%.",
        "links": ["counter_press_trigger_predictability", "buildup_side_bias_predictability", "goal_kick_distribution_predictability", "tempo_script_predictability"],
    },
    {
        "slug": "attacking_channel_preference_telegraphing",
        "title": "Attacking-Channel Preference Telegraphing",
        "summary": "The degree to which a side's final-third entries concentrate on a single channel — left halfspace, right halfspace, or central corridor — making the attack origin scoutable.",
        "stat_signature": "Channel concentration above 45% of final-third entries through a single zone; halfspace entry entropy below 1.5 bits signals meaningful concentration.",
        "mechanism": "A concentrated entry zone lets the defensive shape overload that channel numerically, reducing chance quality per entry without conceding width elsewhere.",
        "conditions": "Against compact low blocks the channel preference is most legible; against higher defensive lines with more movement, channel identity is disrupted.",
        "magnitude": "Expected-goal per final-third entry drops approximately 15-25% when defenders concentrate coverage on a known channel.",
        "links": ["buildup_side_bias_predictability", "wing_overload_tendency_telegraphing", "crossing_versus_cutback_tendency", "final_third_entry_pattern_entropy"],
    },
    {
        "slug": "penalty_taking_direction_tendency",
        "title": "Penalty-Taking Direction Tendency",
        "summary": "Whether a side's penalty takers show a consistent directional preference — low-left, low-right, central — across a sample large enough to inform goalkeeper anticipation.",
        "stat_signature": "A dominant direction exceeding 60% of penalties taken is scoutable; keeper dive success rises 10-15% with known tendency relative to a random-dive baseline.",
        "mechanism": "A strong directional habit removes the information advantage over the goalkeeper, allowing anticipatory rather than pure-reaction diving and raising save probability.",
        "conditions": "Most impactful in shootouts where prior footage is available per taker; in regular-time penalties a disguised run-up can override the tendency.",
        "magnitude": "Known direction tendency raises expected keeper save rate from the baseline ~12% to approximately 18-22%, worth roughly 0.3-0.5 extra saves in a five-kick shootout.",
        "links": ["corner_routine_repetition", "set_piece_marking_scheme_tells", "free_kick_delivery_tendency"],
    },
    {
        "slug": "transition_outlet_predictability",
        "title": "Transition-Outlet Predictability",
        "summary": "How consistently a side uses the same primary forward target — wide striker, advancing fullback, or central runner — when launching from ball-win into attack.",
        "stat_signature": "A single outlet receiving above 50% of transition-launch passes is highly concentrated; transition pass entropy below 1.2 bits; transition xG per sequence falls 10-20% when the outlet is shadowed.",
        "mechanism": "A habitual outlet allows the defending team to shadow the target before ball-win, forcing a secondary outlet, adding a touch and erasing the pace advantage.",
        "conditions": "Most consequential against teams that track transition outlets rather than ball-pressing; less effective against sides that commit numbers forward.",
        "magnitude": "Compressed transition sequences take 1-2 additional touches before reaching the final third, reducing open-space advantage from roughly 4.5 to 3.5 defenders behind the ball.",
        "links": ["counter_press_trigger_predictability", "attacking_channel_preference_telegraphing", "first_phase_pressing_trigger_predictability", "final_third_entry_pattern_entropy"],
    },
    {
        "slug": "set_piece_marking_scheme_tells",
        "title": "Set-Piece Marking-Scheme Tells",
        "summary": "Identifiable cues in a side's defensive set-piece organisation — zonal block positions, man-mark assignments, post-keeper roles — that attacking coordinators can design routines against.",
        "stat_signature": "Zonal-block sides concede headed goals 10-15% more often against in-swinging deliveries; set-piece concession rate per corner above 3.5% signals scheme exposure.",
        "mechanism": "A rigid marking scheme creates a spatial map of uncovered zones or exploitable movement gaps that a purpose-built routine can target repeatedly.",
        "conditions": "Most exploitable by sides that dedicate set-piece analysis; less exploitable when the defending side blends zonal and man coverage to obscure its scheme.",
        "magnitude": "Expected-goal per corner against a known single-scheme defence rises roughly 0.010-0.015 compared with a mixed scheme, a meaningful uplift given typical corner volumes.",
        "links": ["corner_routine_repetition", "free_kick_delivery_tendency", "penalty_taking_direction_tendency", "throw_in_pattern_predictability"],
    },
    {
        "slug": "wing_overload_tendency_telegraphing",
        "title": "Wing-Overload Tendency Telegraphing",
        "summary": "How recognisably a side commits numerical overloads to one or both wide zones in the attacking phase, making the resulting cross foreseeable for the defensive block.",
        "stat_signature": "Wide-zone touch share above 42% of final-third actions on the dominant side; three-plus attackers in the wide zone above 25% of sequences; crossing rate per final-third possession above 0.30.",
        "mechanism": "A systematic wide overload invites the block to compact wide, eliminating the positional advantage the overload was designed to create.",
        "conditions": "Against narrow low blocks a wide overload retains value even when expected; against sides with mobile wide defenders the overload is more readily absorbed.",
        "magnitude": "Recognised wing overloads see crossing success rates (touches in the six-yard box) drop roughly 8-15% as defenders pre-adjust their width.",
        "links": ["attacking_channel_preference_telegraphing", "crossing_versus_cutback_tendency", "buildup_side_bias_predictability", "final_third_entry_pattern_entropy"],
    },
    {
        "slug": "tempo_script_predictability",
        "title": "Tempo-Script Predictability",
        "summary": "How consistently a side follows a learnable tempo sequence — slow build, triggered acceleration, cooling-off after a chance — making its attacking rhythm anticipatable.",
        "stat_signature": "Pass-tempo variance below 8 passes-per-minute standard deviation across sequences; high-tempo burst frequency at predictable match-minute intervals quantifies rhythm regularity.",
        "mechanism": "A learnable tempo script lets the defending team cycle press intensity in sync, saving energy for scripted bursts and recovering safely during scripted slow phases.",
        "conditions": "Most exploitable by tactically disciplined sides that can cycle press intensity economically; less relevant against chaotic or transition-dependent opponents.",
        "magnitude": "Defending sides that correctly anticipate the tempo burst can raise their PPDA from ~10 toward ~7 during bursts while dropping to ~14 in known slow phases, saving ~15-20% of total pressing energy.",
        "links": ["buildup_side_bias_predictability", "first_phase_pressing_trigger_predictability", "counter_press_trigger_predictability", "final_third_entry_pattern_entropy"],
    },
    {
        "slug": "substitution_pattern_predictability",
        "title": "Substitution-Pattern Predictability",
        "summary": "Whether a side's substitution timing, positional profiles introduced, and tactical purpose follow a learnable sequence that opponents can plan against in the closing phase.",
        "stat_signature": "First substitution before the 60th minute in more than 60% of matches signals a scripted pattern; position-type concentration above 70% in one role category; timing entropy below 1.1 bits.",
        "mechanism": "A predictable substitution moment lets the opposition schedule its own adjustment or pressing phase to land before fresh legs arrive, neutralising the intended boost.",
        "conditions": "More consequential in close matches where a single substitution shifts tactical shape; in blowouts the predictability carries lower strategic weight.",
        "magnitude": "Anticipated defensive substitutions see the opponent's attack intensity spike 10-18% in the preceding window as they rush to exploit the pre-change shape.",
        "links": ["tempo_script_predictability", "counter_press_trigger_predictability", "first_phase_pressing_trigger_predictability"],
    },
    {
        "slug": "final_third_entry_pattern_entropy",
        "title": "Final-Third Entry-Pattern Entropy",
        "summary": "The diversity of routes a side uses to penetrate the final third — runs in behind, halfspace layoffs, wide overlaps, long passes — quantified as Shannon entropy across route types.",
        "stat_signature": "Entry entropy above 2.0 bits across five route types signals high unpredictability; below 1.4 bits indicates concentration on two or fewer routes.",
        "mechanism": "Low entry entropy allows the defensive mid-block to pre-position for the dominant route, reducing its yield; high entropy forces later reactive defensive commitments.",
        "conditions": "Entropy matters most against organised mid-blocks with time to shape; against chaotic defences route mix is less important than execution on any given attempt.",
        "magnitude": "A one-bit reduction in entry entropy is associated with roughly 10-18% higher per-attempt blocking rate by the defensive shape.",
        "links": ["attacking_channel_preference_telegraphing", "wing_overload_tendency_telegraphing", "crossing_versus_cutback_tendency", "buildup_side_bias_predictability"],
    },
    {
        "slug": "counter_press_trigger_predictability",
        "title": "Counter-Press Trigger Predictability",
        "summary": "The identifiability of the cue that launches a side's counter-press after ball-loss — a zone threshold, a specific loss type, or a height signal — making the press-onset avoidable.",
        "stat_signature": "Counter-press activation above 70% in the attacking third but below 20% in the defensive third reveals a zone-triggered pattern; trigger consistency above 0.75 across matches signals predictability.",
        "mechanism": "A recognisable trigger allows the receiving side to pre-plan a long switch or direct pass beyond the pressing block, converting the counter-press's surprise into a rehearsed set piece.",
        "conditions": "Most exploitable by technically adept sides with quick decision-makers who execute rehearsed escapes before the press closes; less harmful against lower-quality opposition.",
        "magnitude": "When the escape is pre-planned against a known trigger, counter-press ball-win rate drops from ~28-35% toward ~18-22%, yielding roughly 8-12 extra completed escapes per match.",
        "links": ["first_phase_pressing_trigger_predictability", "transition_outlet_predictability", "tempo_script_predictability", "low_block_exit_route_predictability"],
    },
    {
        "slug": "crossing_versus_cutback_tendency",
        "title": "Crossing and Cutback Delivery Tendency",
        "summary": "The balance between early crosses into the box and square cutbacks to arriving runners, and how predictably a wide attacker selects one over the other based on defender positioning.",
        "stat_signature": "Cutback share of wide final-third actions above 35% is a meaningful tendency; early-cross share above 55% signals a dominant delivery preference; expected-goal per wide action decomposes the over-reliance.",
        "mechanism": "A wide attacker who always selects the same delivery type lets the near-post defender commit correctly to either cross-block or cutback cover rather than holding a split position.",
        "conditions": "Most readable in one-on-one wide situations observed across many repetitions; less predictable when a second runner provides a genuine two-option choice.",
        "magnitude": "Defenders who correctly anticipate the delivery type block or intercept at roughly 15-25% higher rates than in ambiguous situations.",
        "links": ["wing_overload_tendency_telegraphing", "attacking_channel_preference_telegraphing", "final_third_entry_pattern_entropy", "buildup_side_bias_predictability"],
    },
    {
        "slug": "low_block_exit_route_predictability",
        "title": "Low-Block Exit-Route Predictability",
        "summary": "How consistently a defensively compact side uses the same route out of its own low block — goalkeeper punt, wide flick, or central layoff — making the counter-attack launch scoutable.",
        "stat_signature": "A single exit route above 55% of transitions out of the low block; exit-route entropy below 1.2 bits; press engagement by opponents rises 12-18% when the primary exit route is known.",
        "mechanism": "A learnable exit route lets the pressing side station a hunter at the exit target, converting the block's defensive solidity into a press-trap and neutralising counter-attack pace.",
        "conditions": "Most consequential against high-energy pressing sides that can station hunters without over-exposing themselves; less impactful against cautious possession sides.",
        "magnitude": "When the primary exit route is contested, ball-retention on first touch drops from ~75% to ~58-62%, forcing a backward pass that resets the counter opportunity.",
        "links": ["goal_kick_distribution_predictability", "transition_outlet_predictability", "counter_press_trigger_predictability", "throw_in_pattern_predictability"],
    },
    {
        "slug": "deception_disguise_capacity",
        "title": "Deception and Disguise Capacity in Build-Up",
        "summary": "How effectively a side introduces deliberate variation — body-feint passing, switch-of-play disguise, dummy-run decoys — to suppress the opponent's pattern-recognition and maintain decision entropy.",
        "stat_signature": "Pass-direction entropy above 2.2 bits per sequence phase signals high disguise capacity; dummy-run frequency above 3.0 per final-third entry indicates active deception investment.",
        "mechanism": "Maintained entropy forces defenders into reactive rather than anticipatory decisions, delaying the press trigger by 0.2-0.5 seconds and preserving the passing option's space.",
        "conditions": "Most effective against aggressive press systems that rely on early trigger reading; less impactful against passive mid-block defences that react to ball movement.",
        "magnitude": "Sides in the top quartile for pass-direction entropy allow opponents 8-14% lower ball-win rates on pressing sequences, consistent with the disguise preserving the passer's option window.",
        "links": ["buildup_side_bias_predictability", "final_third_entry_pattern_entropy", "tempo_script_predictability", "first_phase_pressing_trigger_predictability"],
    },
]
