"""PressureResponse NBA concept nodes — person-free.

Scope: how units and systems respond to elevated situational stakes —
the late-and-close clutch window, elimination contexts, hostile crowds,
icing, and composure after setbacks.  Distinct from ClosingExecution
(which covers MECHANICS of finishing a result) and GamePhases (which
DEFINES the clutch time band); every node here measures a RESPONSE
PATTERN — efficiency deltas, behavioural shifts, variance inflation —
that arises specifically because stakes are high.
"""
from __future__ import annotations

SPORT = "NBA"
FAMILY = "PressureResponse"

CONCEPTS = [
    {
        "slug": "clutch_scoring_efficiency_delta",
        "title": "Clutch Scoring-Efficiency Delta",
        "summary": "The signed difference between a unit's true-shooting percentage and points-per-possession inside the last five minutes of one-possession games versus its own non-clutch baseline, measuring pressure-induced efficiency change rather than raw clutch level.",
        "stat_signature": "Clutch true-shooting delta ranges from roughly -8 pp to +5 pp across teams in a season; the median unit drops ~2-4 pp, reflecting tighter defences and harder shot creation; clutch points-per-possession falls ~0.05-0.10 from non-clutch for the typical offense.",
        "mechanism": "Defences tighten coverages and switch more aggressively in the clutch, shrinking the space for high-percentage attempts; simultaneously offences funnel possessions to a primary creator against pre-loaded schemes, compressing shot diversity and raising attempt difficulty, together depressing scoring efficiency below the open-play mean.",
        "conditions": "Most pronounced against switch-everything defences that neutralise actions designed around mismatches; moderated when a unit retains multiple credible shot-creators who force coverage choices; amplified on the road where crowd noise raises arousal.",
        "magnitude": "A -6 pp clutch true-shooting delta versus a -2 pp delta across four clutch possessions represents roughly 0.6-0.8 expected points foregone, frequently the decisive quantity in one-possession finishes.",
        "links": ["clutch_skill_noise_dominance", "self_creation_under_pressure_premium", "shot_selection_conservatism_shift", "high_usage_pressure_concentration", "pressure_composure_persistence"],
    },
    {
        "slug": "clutch_skill_noise_dominance",
        "title": "Clutch-Skill Sampling-Noise Dominance",
        "summary": "The empirical finding that year-over-year correlation of a unit's clutch-minus-baseline efficiency is low, meaning cross-sectional clutch rankings within a season are dominated by small-sample variance rather than durable execution differences.",
        "stat_signature": "Year-over-year correlation of team-level clutch net rating is roughly 0.25-0.40; 95% confidence intervals on a typical season's clutch sample (~80-120 possessions) span ±12-18 pts/100, encompassing the full observed spread; split-half reliability within a season is similarly modest at ~0.30-0.45.",
        "mechanism": "The clutch window is defined narrowly enough that any team accumulates only a thin possession sample, making realised outcomes strongly dependent on the outcomes of a handful of three-point attempts or free throws whose variance overwhelms the underlying skill signal at single-season horizons.",
        "conditions": "Noise dominance is universal at the team level; partially reduced over multi-season aggregations (n > 300 clutch possessions) and for individual play-type clutch metrics with cleaner denominators; worst for single-game or short-series assessments.",
        "magnitude": "At single-season sample sizes, more than half of the observed clutch ranking is sampling noise; a unit ranked first in clutch net rating has a genuine probability of below-average underlying clutch skill, so descriptive clutch splits require explicit uncertainty acknowledgment.",
        "links": ["clutch_scoring_efficiency_delta", "perimeter_make_variance_inflation", "composure_after_failed_clutch_possession", "pressure_composure_persistence", "garbage_time_pressure_absence"],
    },
    {
        "slug": "free_throw_pressure_decay",
        "title": "High-Leverage Free-Throw Conversion Decay",
        "summary": "The change in free-throw make-rate in the final two minutes of one-possession games relative to a shooter's non-pressure baseline, isolating self-paced closed-skill execution from defensive interference as the cleanest measurable pressure-response signature.",
        "stat_signature": "Late-and-close free-throw percentage runs roughly 1-4 pp below season baseline for average shooters; high-volume elite shooters show near-zero decay; the first attempt of a pair shows larger drops (~2-5 pp) than the second, which benefits from outcome feedback; road clutch shooting fouls add ~1-2 pp of additional suppression.",
        "mechanism": "Free throws remove the confounding of defensive intensity, so any conversion decline reflects arousal-driven disruption to the automatised shooting routine; elevated cortisol tightens peripheral musculature and alters rhythm of elbow extension, shifting outcome distribution toward misses without changing conscious intent.",
        "conditions": "Decay is largest for shooters whose pre-shot routine is time-anchored and disrupted by crowd noise; smallest for shooters with deliberate low-tempo routines less susceptible to time pressure; amplified in road arenas and after a prior momentum shift toward the opponent.",
        "magnitude": "A 3-4 pp late free-throw decay on two attempts per trip costs roughly 0.06-0.08 expected points per possession — small per instance but accumulating across a team's foul-game exposures across a season.",
        "links": ["icing_routine_disruption_response", "arousal_performance_inverted_u", "road_crowd_pressure_execution_drag", "lead_protection_nerves", "clutch_scoring_efficiency_delta"],
    },
    {
        "slug": "arousal_performance_inverted_u",
        "title": "Arousal-Performance Inverted-U Response",
        "summary": "The non-monotonic relationship between stakes-driven physiological arousal and fine-motor shooting execution, where performance peaks at moderate arousal and declines at both low-leverage and extreme-pressure extremes.",
        "stat_signature": "Three-point make-rate by leverage index (win-probability impact) shows a mild inverted-U shape: slightly elevated at moderate leverage (~0.8-1.0 pts/100 win probability at stake) relative to zero-leverage garbage time, then declining as leverage exceeds ~1.5 pts/100; the peak is shallow and the descent at extreme pressure is ~1-3 pp.",
        "mechanism": "Moderate arousal optimises attentional focus and motor activation for a ballistic skill like shooting; extreme arousal over-activates the sympathetic nervous system, producing muscular tension in the shooting arm and wrist that degrades the smoothness of the release and alters release-point consistency.",
        "conditions": "Most visible in long-range shooting, which requires precise wrist extension and rotation; attenuated in short-range attempts dominated by power rather than precision; present only when the arousal source is genuine (real stakes), not absent during practice or low-leverage regular-season possessions.",
        "magnitude": "The extreme-pressure descent of 1-3 pp in three-point rate represents a real but modest effect, implying that execution decline at peak pressure is real but small relative to the total observed clutch variance, most of which is sampling noise.",
        "links": ["free_throw_pressure_decay", "road_crowd_pressure_execution_drag", "icing_routine_disruption_response", "perimeter_make_variance_inflation", "clutch_scoring_efficiency_delta"],
    },
    {
        "slug": "self_creation_under_pressure_premium",
        "title": "Self-Creation-Under-Pressure Premium",
        "summary": "Units carrying multiple independent shot-creators retain clutch efficiency better than single-creator units, quantified as a smaller clutch-minus-baseline efficiency drop as a function of on-court creation redundancy.",
        "stat_signature": "Units where the top-two creators each carry at least 18% usage in clutch minutes show a clutch efficiency drop roughly 2-4 pp smaller than units where one creator exceeds 38% usage; clutch assisted-make share stays ~5-8 pp higher in multi-creator units, reflecting sustained ball movement.",
        "mechanism": "Defences facing a single primary clutch creator can pre-commit their most disruptive coverage to that action, predictably degrading its efficiency; a second credible initiator forces coverage choices that protect neither option fully, preserving at least one viable high-quality action per possession.",
        "conditions": "Premium is largest against elite-switching defences that can neutralise one creator without help-rotation cost; reduced when both creators rely on the same play type (e.g., both isolation) that a strong point-of-attack defender can guard sequentially; amplified in playoff series where scout-based coverage pre-loads the primary option.",
        "magnitude": "Multi-creator units sustaining a 2-4 pp smaller clutch drop across the most important possessions translate to roughly 0.3-0.5 additional expected points per late-and-close possession, compounding over a playoff run.",
        "links": ["clutch_scoring_efficiency_delta", "high_usage_pressure_concentration", "shot_selection_conservatism_shift", "self_creation_under_pressure_premium", "after_timeout_composure_reset"],
    },
    {
        "slug": "shot_selection_conservatism_shift",
        "title": "Pressure Shot-Selection Conservatism Shift",
        "summary": "The tightening of shot-quality distribution under leverage as offences trade variance for higher-floor looks, measured as the rise in rim-and-foul-seeking share and fall in contested-pullup-three frequency in clutch versus non-clutch possessions.",
        "stat_signature": "Rim-and-foul-seeking share rises roughly 5-10 pp in clutch versus non-clutch; contested mid-range and pull-up-three frequency falls 6-12 pp; expected points per attempt on the clutch diet is roughly flat or slightly lower than non-clutch because the floor-seeking shift is partially offset by defensive pressure at the rim.",
        "mechanism": "Decision-makers under pressure weight the downside of a turnover or an uncontested low-percentage heave more heavily than the upside of a variance-adding three, shifting the probability distribution of shot selection toward safer, lower-variance attempts; this is a rational risk-aversion response that trades expected value for variance reduction.",
        "conditions": "Shift is most pronounced when the score differential permits a conservative approach (ahead or tied); attenuated when trailing units must generate three-point variance to alter the outcome; magnified by shot-clock pressure that limits play development.",
        "magnitude": "The conservatism shift produces a meaningful change in shot-type composition but modest net efficiency change because the safer attempts face tighter rim defence; its primary observable consequence is lower three-point attempt frequency and higher free-throw-rate in clutch minutes.",
        "links": ["clutch_scoring_efficiency_delta", "turnover_inflation_under_pressure", "lead_protection_nerves", "high_usage_pressure_concentration", "after_timeout_composure_reset"],
    },
    {
        "slug": "turnover_inflation_under_pressure",
        "title": "Pressure Turnover-Rate Inflation",
        "summary": "The rise in live-ball turnover frequency under defensive intensification and clock-scarcity in clutch minutes, measured as the clutch-minus-baseline turnover-per-possession gap and its split by ball-handling concentration.",
        "stat_signature": "Clutch live-ball turnover rate averages ~12-16% versus a ~9-12% non-clutch baseline; units with a single handler absorbing over 35% of clutch possessions show clutch turnover rates 2-4 pp above the team average; steal rate by defences in clutch minutes rises ~1.5-2.5 pp as defences gamble more.",
        "mechanism": "Defences increase ball-pressure and trap frequency in the clutch to force turnovers at the moment each possession is most valuable; simultaneously, clock scarcity reduces the time available for safe pass options, compressing the decision window and elevating risk of forced entries and reach-ins on the offensive side.",
        "conditions": "Inflation is worst for teams relying on a single ball-handler under full-court pressure; reduced by multiple ball-handling options that give the primary handler a safety valve; amplified against defences that selectively foul or trap on the inbound, forcing possession under duress.",
        "magnitude": "Each additional clutch live-ball turnover concedes roughly 1.1-1.3 expected opponent points (transition-adjusted), making a 3-4 pp clutch turnover-rate increase worth approximately 0.03-0.05 expected points against the unit per possession — a meaningful recurring cost in close games.",
        "links": ["shot_selection_conservatism_shift", "lead_protection_nerves", "clutch_scoring_efficiency_delta", "self_creation_under_pressure_premium", "composure_after_failed_clutch_possession"],
    },
    {
        "slug": "perimeter_make_variance_inflation",
        "title": "Clutch Perimeter Make-Variance Inflation",
        "summary": "The widening of three-point outcome variance under pressure even when attempt quality is held constant, measured as the increase in the standard deviation of clutch three-point make-rate relative to binomial expectation at matched volume.",
        "stat_signature": "Observed clutch three-point make-rate standard deviation across possessions exceeds the binomial baseline by roughly 15-30% in leverage-filtered samples; the excess variance is most visible in series-level data where the same shooters hit or miss in clusters beyond independent-trial expectation.",
        "mechanism": "Arousal-induced variability in release mechanics fattens the tails of the outcome distribution at the shot level; because clutch three-point volume is thin per unit, this increased shot-level variance compounds into extreme make-rate outcomes at the game and series level, producing observed streakiness that exceeds what skill-level alone predicts.",
        "conditions": "Most salient in road environments where crowd arousal is highest; attenuated for shooters with very high clutch volume who approach the law-of-large-numbers even in a single playoff run; visible mainly in small samples where excess variance is not diluted.",
        "magnitude": "A 20% variance inflation above binomial on a modest clutch three-point sample produces game-level make-rate swings of several percentage points beyond underlying skill, directly explaining why single-game clutch shooting outcomes are difficult to predict even with perfect shooter-quality data.",
        "links": ["clutch_skill_noise_dominance", "arousal_performance_inverted_u", "road_crowd_pressure_execution_drag", "clutch_scoring_efficiency_delta", "composure_after_failed_clutch_possession"],
    },
    {
        "slug": "lead_protection_nerves",
        "title": "Lead-Protection Execution Tightening",
        "summary": "The points-per-possession dip a leading unit incurs from risk-averse, clock-conscious play in the closing window, distinct from the opponent's improved effort and measuring the self-inflicted portion of efficiency loss attributable to playing not-to-lose.",
        "stat_signature": "Leading-team offensive rating inside the clutch window drops roughly 5-10 pts/100 below its non-clutch baseline; assisted shot rate falls ~8-14 pp; shot clock on release extends 1-2 seconds as clock-milking displaces flow; the drop is largest for units with a single creator who bears full clock-burn responsibility.",
        "mechanism": "A leading unit prioritises clock consumption over shot quality, channelling possessions into a primary initiator for late-clock isolation; the resulting plays are lower-mean, and the psychological cost of protecting a lead adds decision hesitation, slowing execution and increasing the probability of a shot-clock violation or a contested desperation shot.",
        "conditions": "Most acute in four-to-nine-point leads inside three minutes; mitigated in motion systems that retain off-ball actions while milking clock; magnified by road crowd noise that raises protective arousal and by foul trouble that limits the available closing options.",
        "magnitude": "A 7 pt/100 lead-protection rating drop across a handful of possessions costs roughly 0.3-0.5 expected points against an opponent maintaining its non-clutch pace, a material self-inflicted handicap of choosing lead-protection over continuation of the efficient attack.",
        "links": ["shot_selection_conservatism_shift", "turnover_inflation_under_pressure", "comeback_freedom_release", "clutch_scoring_efficiency_delta", "after_timeout_composure_reset"],
    },
    {
        "slug": "comeback_freedom_release",
        "title": "Trailing-Team Psychological-Freedom Release",
        "summary": "The partial execution lift a trailing unit shows from reduced loss-aversion once a deficit removes the cost of variance, measured as the smaller-than-expected efficiency penalty on high-difficulty clutch attempts relative to lead-protection states.",
        "stat_signature": "Trailing-team clutch three-point attempt frequency rises 8-15 pp above their non-clutch baseline; their clutch offensive rating shows a roughly 2-4 pt/100 smaller decline than that of leading teams in matched leverage states, consistent with freed-up shot-selection and attack mentality.",
        "mechanism": "When trailing, loss-aversion shrinks because the downside of variance has already partially materialised; the unit rationally accepts higher-difficulty attempts that widen the outcome distribution, and the psychological release from this deliberate variance-seeking modestly restores shot-creation freedom and off-ball movement that risk-aversion suppressed.",
        "conditions": "Freedom-release is real but partial — defences still intensify regardless of score, so not all variance-seeking attempts are high quality; the effect is most visible in units with legitimate shot-creation depth that can deploy freely once variance-aversion lifts; attenuated in units with a single variance creator who is already fully loaded.",
        "magnitude": "The 2-4 pt/100 smaller clutch rating decline for trailing units versus leading units describes a modest but observable execution difference tied to psychological state, not defensive advantage; it partially offsets the deficit in a way that makes close games noisier than win-probability models calibrated on mid-game data would suggest.",
        "links": ["lead_protection_nerves", "shot_selection_conservatism_shift", "favorite_burden_expectation_weight", "clutch_scoring_efficiency_delta", "elimination_game_composure_signature"],
    },
    {
        "slug": "favorite_burden_expectation_weight",
        "title": "Favorite-Burden Expectation Weight",
        "summary": "The descriptive tendency for heavily favored units to underperform their pregame implied margin in tight finishes versus blowouts, measured as the conditional margin-versus-expectation residual in close late-game states stratified by pregame favorite status.",
        "stat_signature": "Teams favored by seven or more points underperform their closing-line spread in one-possession game states at a rate roughly 3-5 pp above their full-game cover rate; the effect is concentrated in the last five minutes where tight-game dynamics replace the open play that built the lead.",
        "mechanism": "A large pregame favourite carries the dual burden of execution expectation and opponent desperation-play escalation; favourites often reach the clutch window via comfortable leads that then compress, entering the closing window with a protection mindset against an opponent playing with house money and heightened attack aggression — the asymmetric arousal states narrow the expected gap.",
        "conditions": "Visible mainly when comparing blowout outcomes to tight-finish outcomes within the same favourite cohort; confounded by selection bias (tight finishes occur when the underdog outperforms, which itself requires the favourite to be somewhat vulnerable); clearest in large samples across multiple seasons.",
        "magnitude": "The 3-5 pp underperformance in tight-finish states is a descriptive regularity, not a durable edge signal, because the market prices tight-game finishing variance into the spread; it surfaces as a calibration note for distribution-of-outcomes models rather than a systematic predictor.",
        "links": ["comeback_freedom_release", "lead_protection_nerves", "clutch_skill_noise_dominance", "elimination_game_composure_signature", "clutch_scoring_efficiency_delta"],
    },
    {
        "slug": "composure_after_failed_clutch_possession",
        "title": "Composure After a Failed Clutch Possession",
        "summary": "Whether a missed or turned-over high-leverage possession degrades the immediately following possession's execution, measured as the near-zero autocorrelation of possession-level clutch outcomes that distinguishes genuine rattling from independent trials.",
        "stat_signature": "Serial autocorrelation of successive clutch possession outcomes (score/no-score) is near zero (r ≈ -0.02 to +0.04), indicating that a failed possession does not systematically predict the next; units described as rattled in subjective observation do not show detectable next-possession efficiency drops in aggregate.",
        "mechanism": "Basketball possessions are separated by a defensive rebound, a change-of-possession dead ball, or a timeout — all natural reset points that interrupt any arousal spike from a prior failure; the game's structure limits carryover of emotional state across possessions, making true rattling a rare acute event rather than a persistent possession-chain phenomenon.",
        "conditions": "Near-zero autocorrelation holds in aggregate; extreme acute events (a goaltending controversy, a flagrant foul) may produce a short-lived disruption visible only at the individual level in very small samples; the finding does not preclude a unit-level reputation for composure that manifests as a lower variance floor rather than next-possession correlation.",
        "magnitude": "The near-zero autocorrelation implies that composure-after-failure is not a measurable game-state predictor; it is a calibration-important null result that cautions against over-weighting observed post-failure clutch runs as evidence of unit-level rattling versus independent-trial variance.",
        "links": ["clutch_skill_noise_dominance", "perimeter_make_variance_inflation", "after_timeout_composure_reset", "turnover_inflation_under_pressure", "pressure_composure_persistence"],
    },
    {
        "slug": "icing_routine_disruption_response",
        "title": "Pre-Shot Icing Routine-Disruption Response",
        "summary": "The small, heterogeneous drop in first-attempt free-throw conversion when a timeout interrupts a shooter's pre-shot routine, measured as the iced-minus-uniced first-attempt make-rate gap and its dependence on routine rigidity.",
        "stat_signature": "Meta-analytic estimates of the icing effect on first-attempt conversion range from -0.5 pp to -2.5 pp with wide confidence intervals; the second attempt shows no reliable effect; routine-rigid shooters (highly consistent step-count and timing) show larger iced-versus-uniced gaps (~2-4 pp) than routine-flexible shooters (~0-1 pp).",
        "mechanism": "A timeout before the first attempt interrupts the rhythmic pre-shot sequence a shooter has internalised, briefly shifting attention from automatic execution to conscious monitoring of the routine; this reinstatement of conscious control degrades automaticity, narrowing the swing to the first release where the interruption is freshest.",
        "conditions": "Most consequential for shooters with rigid timed routines; marginal for high-volume elite shooters who have adapted their routines to survive interruption; moot on the second attempt of a pair once rhythm is re-established; magnified in road arenas where crowd noise amplifies the arousal dimension of the timeout.",
        "magnitude": "The icing effect is real but modest — roughly 1-3 pp on the first attempt for susceptible shooters — and the small magnitude means its practical impact on game outcomes is limited to situations where a single make-or-miss is decisive, such as a front-end one-and-one with seconds left.",
        "links": ["free_throw_pressure_decay", "arousal_performance_inverted_u", "road_crowd_pressure_execution_drag", "after_timeout_composure_reset", "lead_protection_nerves"],
    },
    {
        "slug": "after_timeout_composure_reset",
        "title": "After-Timeout Composure Reset",
        "summary": "The steadying effect of a dead-ball stoppage on a unit that was unravelling, measured as the reversion of post-timeout possession execution toward baseline following a negative run rather than the set-play scoring premium itself.",
        "stat_signature": "Units that call a timeout following three or more consecutive empty possessions show a post-timeout offensive rating reversion of roughly 8-15 pts/100 toward their season baseline on the first two possessions; the reversion is larger than a baseline after-timeout scoring bump (~2-4 pts/100) in matched non-crisis contexts, isolating the composure-reset component.",
        "mechanism": "A timeout interrupts the negative-feedback loop of a run by removing the team from live play, providing a structured reset of communication, coverage assignments, and emotional state; the composure reset is distinct from drawing up a set play because the primary value is stopping the psychological momentum of an unravelling sequence rather than designing a specific shot.",
        "conditions": "Reset value is highest following runs of three or more empty possessions or two consecutive turnovers; smaller following a single missed shot, which has less psychological weight; most impactful when the timeout also allows personnel substitution to change the on-court energy.",
        "magnitude": "An 8-15 pt/100 reversion toward baseline on post-timeout possessions after a crisis run is the largest composure-management lever available to a unit mid-game, larger in absolute terms than the marginal value of a late-game set play in a non-crisis context.",
        "links": ["composure_after_failed_clutch_possession", "icing_routine_disruption_response", "lead_protection_nerves", "comeback_freedom_release", "turnover_inflation_under_pressure"],
    },
    {
        "slug": "road_crowd_pressure_execution_drag",
        "title": "Road-Crowd Pressure Execution Drag",
        "summary": "The incremental late-game execution penalty a visiting unit absorbs from hostile crowd arousal specifically in one-possession states, measured as the clutch road-minus-home execution gap net of the general home-court advantage.",
        "stat_signature": "Visiting teams' clutch offensive rating runs roughly 3-6 pts/100 below their home clutch rating after removing the ~2-3 pt/100 season-long home-court differential; visiting clutch free-throw percentage lags home by ~1.5-3 pp; visiting three-point make-rate in clutch lags by ~1-2 pp, narrower than the free-throw gap consistent with the arousal-precision mechanism.",
        "mechanism": "Hostile crowd noise elevates arousal and degrades communication between ball-handlers, raising possession-execution error rate; self-paced fine-motor skills (free throws) absorb more arousal impact than reactive field-goal attempts, producing a disproportionate visiting clutch free-throw decline that separates crowd-pressure drag from defensive intensity effects.",
        "conditions": "Most pronounced in arenas with high decibel variance between regular-game and clutch-state crowd engagement; attenuated for visiting units that have deep familiarity with high-noise environments from their own home schedule; amplified in playoff settings where home crowds are more consistently at maximum intensity.",
        "magnitude": "The net 3-6 pt/100 visiting clutch drag beyond baseline home-court advantage is a descriptive regularity that narrows the road unit's expected clutch efficiency and contributes to the well-documented home-court closing-game advantage without implying a predictable edge beyond what win-probability models already capture.",
        "links": ["free_throw_pressure_decay", "arousal_performance_inverted_u", "perimeter_make_variance_inflation", "clutch_scoring_efficiency_delta", "favorite_burden_expectation_weight"],
    },
    {
        "slug": "high_usage_pressure_concentration",
        "title": "High-Usage Pressure Concentration Effect",
        "summary": "How clutch possessions funnel toward a single primary initiator and the efficiency cost of that concentration against loaded defences, measured as the rise in top-option usage share and the associated points-per-possession on those concentrated touches.",
        "stat_signature": "Primary-option clutch usage share climbs from roughly 26-30% in non-clutch to 34-44% in the last-five-within-five window; that option's clutch points-per-possession on isolated touches runs ~0.85-0.95 versus their non-clutch isolation mark of ~0.90-1.00, a 0.05-0.08 PPP drop driven by pre-loaded defensive positioning.",
        "mechanism": "Coaches and shot-creators rationally concentrate the ball in the best initiator as game stakes peak, but defences pre-scout this decision and load accordingly; the pre-loaded scheme raises the average defender quality on each touch and eliminates help rotation cost, compressing the creator's efficiency without a symmetrical benefit to secondary options who become passive.",
        "conditions": "Effect is most acute in single-creator units facing switch-everything defences in playoff series where advanced pre-game preparation amplifies the pre-loading; mitigated in motion systems where the concentration is less predictable by possession and the primary creator functions within movement rather than pure isolation.",
        "magnitude": "A 0.06 PPP drop on an elevated clutch usage of 40% corresponds to roughly 0.024 expected points lost per full possession versus maintaining non-clutch efficiency — a persistent but moderate tax on the natural concentration tendency.",
        "links": ["clutch_scoring_efficiency_delta", "self_creation_under_pressure_premium", "shot_selection_conservatism_shift", "turnover_inflation_under_pressure", "defensive_intensity_response_to_pressure"],
    },
    {
        "slug": "defensive_intensity_response_to_pressure",
        "title": "Defensive Intensity Response to Pressure",
        "summary": "The lift in contest-rate, deflection-rate, and shot-difficulty forced by the defending unit in clutch minutes, framing pressure response as two-sided and measuring the tightening of defensive coverage that drives the observed offensive efficiency decline.",
        "stat_signature": "Clutch contest rate (nearest defender within four feet) rises roughly 5-9 pp above non-clutch; opponent shot difficulty index (accounting for defender proximity and release time) rises ~0.06-0.10 units; deflection rate per 100 possessions climbs ~2-4; opponent shot clock on release shortens by ~1-2 seconds as defences trap and deny longer.",
        "mechanism": "Coaches deploy their best defenders on highest-leverage matchups in the clutch, reduce help rotations to guard the perimeter against threes, and increase ball-pressure to shrink the shot clock; the combined effect degrades shot quality independent of any offensive execution change, meaning observed clutch offensive decline is partly attributable to a genuine defensive intensity lift rather than solely to offensive pressure response.",
        "conditions": "Intensity lift is most pronounced from defences with switch-capable rosters that can increase individual coverage without rotation gaps; smaller from defences reliant on help and rotation who must choose between protecting the three and protecting the rim; amplified in playoff series where defensive scheme is tailored to the specific offensive system.",
        "magnitude": "A 7 pp contest-rate lift in the clutch reduces expected offensive efficiency by roughly 4-6 pts/100 through shot-quality suppression alone, accounting for a substantial portion of the observed clutch offensive efficiency decline and correctly attributing it to defensive intensity rather than solely to offensive pressure-response.",
        "links": ["clutch_scoring_efficiency_delta", "high_usage_pressure_concentration", "shot_selection_conservatism_shift", "self_creation_under_pressure_premium", "pressure_composure_persistence"],
    },
    {
        "slug": "pressure_composure_persistence",
        "title": "Cross-Game Pressure-Composure Persistence",
        "summary": "The limited but non-zero stability of a unit's clutch-execution tendency across seasons, measured as the split-half and year-over-year correlation of clutch-minus-baseline efficiency to separate durable composure from transient variance.",
        "stat_signature": "Year-over-year correlation of team clutch net-rating delta: roughly 0.25-0.40; split-half reliability within a season: ~0.30-0.45; multi-year aggregated clutch minus baseline shows a wider talent signal than single-season, with the top quartile of teams running +3 to +6 pts/100 clutch premium sustained across multiple seasons.",
        "mechanism": "Composure is partly a function of personnel stability (experienced units that have shared prior clutch repetitions develop shared mental models of closing actions), coaching consistency (scheme reduces decision uncertainty under pressure), and roster construction (multi-creator lineups with reliable free-throw shooters retain clutch efficiency more consistently than single-creator units).",
        "conditions": "Persistence is stronger when the core of the closing unit is stable across seasons; degrades after significant roster turnover even if overall team quality is preserved; most detectable at the unit level when the closing lineup is identifiable and consistent, rather than at the full-team level where substitution patterns add noise.",
        "magnitude": "A durable multi-season clutch premium of +4 pts/100 above baseline across a roster that retains its closing core represents a genuine but modest composure signal, meaningful for distribution-of-outcomes modelling but insufficient to claim as a reliable game-by-game predictor given the overlying sampling noise.",
        "links": ["clutch_skill_noise_dominance", "clutch_scoring_efficiency_delta", "self_creation_under_pressure_premium", "defensive_intensity_response_to_pressure", "elimination_game_composure_signature"],
    },
    {
        "slug": "elimination_game_composure_signature",
        "title": "Elimination-Stakes Composure Signature",
        "summary": "Whether closeout-stakes contexts produce a unit-level execution shift beyond ordinary clutch leverage, described as the elimination-versus-non-elimination late-game efficiency residual with explicit acknowledgment of small playoff sample sizes.",
        "stat_signature": "Elimination game clutch efficiency deltas are statistically noisy due to thin samples (~15-30 elimination clutch possessions per team per season); descriptively, units show a ~1-3 pt/100 additional drag in elimination versus non-elimination playoff clutch states, but confidence intervals span zero for any individual team.",
        "mechanism": "Elimination stakes amplify loss-aversion maximally because the entire season's investment rides on the outcome; this psychological asymmetry may induce over-tight decision-making and over-reliance on primary options beyond ordinary clutch concentration, further depressing efficiency through the same high-usage concentration mechanism that operates in regular-season clutch windows.",
        "conditions": "Most credible in aggregate across many units and seasons rather than as a game-specific predictor; attenuated for units with deep playoff experience whose closing familiarity partially offsets the stakes increment; mixed with opponent quality escalation since both teams are in elimination simultaneously.",
        "magnitude": "The elimination-specific component beyond ordinary playoff clutch pressure is small (0-3 pts/100 descriptively) and statistically uncertain; it is best treated as a distribution-widening factor rather than a mean-shifting predictor, consistent with the broader finding that extreme stakes inflate variance more than they shift the mean.",
        "links": ["pressure_composure_persistence", "favorite_burden_expectation_weight", "comeback_freedom_release", "clutch_skill_noise_dominance", "clutch_scoring_efficiency_delta"],
    },
]
