"""Soccer PressureResponse spec — person-free concept-node content for the brain."""
from __future__ import annotations

SPORT = "Soccer"
FAMILY = "PressureResponse"

CONCEPTS: list[dict] = [
    {
        "slug": "penalty_conversion_pressure_decay",
        "title": "Penalty Conversion Pressure Decay",
        "summary": "Spot-kick conversion falls 4-8 pp under maximum-stakes conditions beyond what goalkeeper quality explains, capturing a composure signature of the taking side.",
        "stat_signature": "League-wide conversion ~77% at low stakes; drops to ~70-73% when equalising or match-winning after minute 75, net of post-shot xG saved. Single-taker variance across stake buckets exceeds 12 pp below 15 high-pressure attempts.",
        "mechanism": "Elevated stakes shift orientation from gain-pursuit to loss-prevention, narrowing attentional focus and causing micro-deviations toward the goalkeeper's strong side with reduced ball-velocity at contact.",
        "conditions": "Largest in knockouts and table-decisive rounds; amplified for visiting takers in crowds above 40,000. Sample stabilises only above 12 high-pressure kicks.",
        "magnitude": "Roughly 4-8 pp conversion drop from low-stakes to maximum-pressure conditions; approximately one additional miss per 15 attempts net of goalkeeper quality.",
        "links": ["shootout_order_pressure_gradient", "goalkeeper_one_on_one_composure", "hostile_crowd_visitor_composure", "penalty_taker_load_rotation_response"],
    },
    {
        "slug": "shootout_order_pressure_gradient",
        "title": "Shootout Order Pressure Gradient",
        "summary": "Conversion probability declines monotonically across the shootout sequence as elimination proximity increases; must-score kicks miss at rates 10-13 pp above kick-1.",
        "stat_signature": "Kicks 1-3 convert ~78%; kicks 4-5 ~72%; sudden-death kicks ~65-68%. First-kicking side wins ~60% of shootouts across order-randomised samples.",
        "mechanism": "Sequential elimination framing shifts each subsequent taker progressively from gain-pursuit toward loss-prevention; cascading pressure compounds as survivor count shrinks.",
        "conditions": "Gradient steepest in knockout eliminators with immediate consequence. Effect diminishes for kicking positions 1-2 where elimination is psychologically distant.",
        "magnitude": "Approximately 10-13 pp conversion gap between kick-1 and a must-score sudden-death attempt; first-kicking structural advantage of ~60% shootout win-rate.",
        "links": ["penalty_conversion_pressure_decay", "goalkeeper_one_on_one_composure", "high_stakes_discipline_breakdown"],
    },
    {
        "slug": "late_goal_concession_fragility",
        "title": "Late-Goal Concession Fragility",
        "summary": "Fragile defensive units concede 0.10-0.18 goals-against above expected in the 75-90 window, reflecting fatigue-driven shape degradation beyond what xGA models assign to late attempts.",
        "stat_signature": "Fragile units: actual-minus-expected late goals +0.10 to +0.18 per 90. Signal stabilises over ~25-30 matches; year-over-year persistence correlation ~0.30-0.35 in stable squads.",
        "mechanism": "Accumulated match load degrades postural and anticipatory capacities; positional discipline erodes under sustained pressure without adequate rotation depth, creating shape gaps the xG model under-credits.",
        "conditions": "Pronounced against sides that sustain high-tempo pressure through minute 70; attenuated when the conceding side holds a two-goal cushion that reduces opponent urgency. Squads with shallow rotation show systematically larger residuals.",
        "magnitude": "Approximately one additional conceded goal per 6-9 late windows compared with expectation for fragile units; robust units show near-zero or negative late residuals.",
        "links": ["post_concession_response_window", "lead_holding_psychological_compression", "chasing_team_clarity_release", "pressure_response_persistence"],
    },
    {
        "slug": "lead_holding_psychological_compression",
        "title": "Lead-Holding Psychological Compression",
        "summary": "Narrowly leading sides drop forward-pass rate 8-14 pp and possession retention 4-7 pp in the closing phase relative to their level-game baseline, inviting pressure that widens PPDA by 3-5 units.",
        "stat_signature": "One-goal leaders after minute 70 show forward-pass rate -8 to -14 pp and retained possession -4 to -7 pp versus matched level-game closing baseline. PPDA widens 3-5 units as pressing responsibility is ceded.",
        "mechanism": "Loss-aversion behaviour at the team level drives collective shift toward defensive consolidation, surrendering territory and creating structural xG access the score-state alone would not predict.",
        "conditions": "Strongest in tight defensive sides with low-scoring profiles; attenuated in high-press sides whose identity resists the low-block posture. Larger in knockouts where a draw carries elimination risk.",
        "magnitude": "Associated with ~0.08-0.12 additional opposition xG above a naive lead-protection baseline; roughly 8-14 pp forward-pass reduction per defensive half-hour.",
        "links": ["chasing_team_clarity_release", "late_goal_concession_fragility", "two_legged_aggregate_pressure_posture", "stoppage_time_decision_quality"],
    },
    {
        "slug": "chasing_team_clarity_release",
        "title": "Chasing-Team Psychological-Clarity Release",
        "summary": "A trailing side generates 25-35% more xGF and 20-30% more xGA after minute 70 as role-clarity removes tactical hedging and commits resources forward despite territorial exposure.",
        "stat_signature": "One-goal trailing sides post-70 show xGF rates 25-35% above level-game closing baseline and xGA 20-30% above baseline. Shot urgency (within 8s of possession entry) roughly doubles.",
        "mechanism": "Eliminating the tactical hedging of a neutral game state enables collective commitment to a single objective; territory concession becomes acceptable because the cost of a second conceded goal is secondary to scoring.",
        "conditions": "Most pronounced with exactly one-goal deficits; two-goal deficits after minute 80 trigger a more compressed release with larger counter-exposure. High attacking rotation depth amplifies the benefit.",
        "magnitude": "Approximately 25-35% xGF lift with 20-30% xGA increase; net xG differential remains negative for most sides despite the urgency-driven volume surge.",
        "links": ["lead_holding_psychological_compression", "must_score_finishing_tightening", "post_concession_response_window", "early_goal_composure_response"],
    },
    {
        "slug": "high_stakes_discipline_breakdown",
        "title": "High-Stakes Discipline Breakdown",
        "summary": "Table-decisive or knockout fixtures raise fouls-per-defensive-action 12-18% and yellow-card rate 20-28% above matched mid-season baselines, driven by threat-response impulse overriding disciplined positioning.",
        "stat_signature": "Fouls-per-defensive-action +12-18%; yellow-card rate +20-28% in knockout versus low-stakes matched fixtures. Rash challenge rate (challenge within 0.5s of ball receipt under pressure) +15-22% in the closing 20 minutes.",
        "mechanism": "Heightened stakes activate threat-response that prioritises immediate interruption over positional discipline; impulsive challenge decisions increase as arousal outpaces prefrontal regulation and tactical foul calculus takes over.",
        "conditions": "Largest in relegation play-offs, title-deciding final rounds, knockout eliminators. Amplified for trailing sides in the closing phase; attenuated for sides with strong mid-season form reducing existential stakes framing.",
        "magnitude": "One additional caution per roughly 4-5 high-stakes matches per side; fouls-per-defensive-action premium of 12-18 pp versus comparable low-stakes fixtures.",
        "links": ["penalty_conversion_pressure_decay", "numerical_disadvantage_composure", "stoppage_time_decision_quality", "two_legged_aggregate_pressure_posture"],
    },
    {
        "slug": "goalkeeper_one_on_one_composure",
        "title": "Goalkeeper One-on-One Composure",
        "summary": "A goalkeeper's save outcomes in one-on-one and penalty events diverge from post-shot xG benchmarks by up to 18 pp, capturing a composure signal partially separable from overall shot-stopping skill.",
        "stat_signature": "Post-shot xG for one-on-one chances ~0.45-0.55; composure-elite goalkeepers achieve -0.08 to -0.12 goals-above-expected per chance. Penalty xG ~0.76; top penalty-stoppers show -0.10 to -0.18 goals-above-expected across 30+ attempts.",
        "mechanism": "Composure suppresses premature commitment; goalkeepers maintain neutral stance longer, exploiting the striker's micro-hesitation and shoulder-drop cues more reliably than pure reflex speed predicts.",
        "conditions": "Signal most meaningful in knockout or title-relevant contexts with maximum event-level pressure. Stabilises slowly — noisy below 15 career high-leverage appearances.",
        "magnitude": "Top composure decile saves 10-18 pp above post-shot xG expectation on combined one-on-one and penalty attempts relative to median goalkeepers.",
        "links": ["penalty_conversion_pressure_decay", "shootout_order_pressure_gradient", "must_score_finishing_tightening"],
    },
    {
        "slug": "must_score_finishing_tightening",
        "title": "Must-Score Finishing Tightening",
        "summary": "Finishing quality degrades when a goal is urgently required: actual goals run 0.05-0.10 below expected in the closing phase as urgency drives speculative volume over quality.",
        "stat_signature": "Chasing sides in the final 15 minutes: actual-minus-expected finishing residual -0.05 to -0.10 per match. xG-per-shot falls 12-20% below the side's full-match baseline as urgency substitutes volume for placement.",
        "mechanism": "Urgency compresses deliberation and encourages speculative long-range efforts; muscle-memory precision falters under maximal arousal, adding residual finishing error beyond what shot-location models capture.",
        "conditions": "Strongest with one-goal deficits after minute 80; weaker for two-goal deficits where urgency is diluted. Sides with high-quality deep rotation suffer less as fresh finishers preserve composure.",
        "magnitude": "Approximately -0.05 to -0.10 goals below expected finishing under must-score urgency; xG-per-shot 12-20% below open-play baseline.",
        "links": ["chasing_team_clarity_release", "missed_chance_psychological_carryover", "stoppage_time_decision_quality"],
    },
    {
        "slug": "early_goal_composure_response",
        "title": "Early-Goal Composure Response",
        "summary": "Conceding before minute 15 creates a 30-45% xGA elevation in the subsequent 15-minute window as tactical reorganisation lags, with resilient sides showing galvanising xGF uplift and fragile sides fragmenting.",
        "stat_signature": "Post-concession minutes 0-15: xGA +30-45% above baseline; xGF +20-30% above baseline as urgency activates. PPDA improves sharply for galvanising units and widens for fragile ones — this bimodal split is the diagnostic.",
        "mechanism": "An early goal scrambles tactical structure before defensive automaticity has fully embedded; the first 15 minutes post-concession carry the highest reorganisation cost as marking assignments and pressing triggers reset.",
        "conditions": "Vulnerability window largest before minute 10 when tactical shape is least embedded. Attenuated when the early goal derives from a set piece and open-play shape remains intact.",
        "magnitude": "Approximately 30-45% xGA elevation in the 15-minute post-concession window; bimodal PPDA response (galvanising versus fragmenting) is the most diagnostic resilience split.",
        "links": ["post_concession_response_window", "chasing_team_clarity_release", "late_goal_concession_fragility", "two_legged_aggregate_pressure_posture"],
    },
    {
        "slug": "two_legged_aggregate_pressure_posture",
        "title": "Aggregate-Pressure Risk Posture",
        "summary": "The aggregate state entering a knockout second leg directly reshapes both sides' risk posture: trailing sides generate 20-30% more xGF and 25-35% more xGA; leading sides suppress both by 10-18% and 8-12% respectively.",
        "stat_signature": "Second-leg aggregate-trailing sides: xGF +20-30%, xGA +25-35% versus single-match baseline. Aggregate-leading sides: xGF -10-18%, xGA -8-12%. Line-height proxies (PPDA, defensive action territory) shift within the first 15 minutes consistent with aggregate margin.",
        "mechanism": "Aggregate framing converts a two-match series into a single extended decision problem; the first-leg result is a binding risk parameter that forces trailing sides to open shape and leading sides to consolidate at the cost of attacking presence.",
        "conditions": "Largest when aggregate deficit exceeds one goal. Mixed-incentive posture under narrow one-goal leads. Attenuated when qualification is already mathematically secure regardless of second-leg result.",
        "magnitude": "Trailing-side xGF/xGA inflation of 20-30%/25-35%; leading-side suppression of 10-18%/8-12% relative to single-match baselines captures the aggregate-framing reshaping effect.",
        "links": ["lead_holding_psychological_compression", "chasing_team_clarity_release", "early_goal_composure_response", "high_stakes_discipline_breakdown"],
    },
    {
        "slug": "post_concession_response_window",
        "title": "Post-Concession Response Window",
        "summary": "In the 10 minutes after conceding, resilient sides show near-zero xGA above baseline plus a +0.09-0.12 xGF surplus; fragile sides show +0.15-0.20 xGA above baseline with suppressed xGF.",
        "stat_signature": "Cross-match average post-concession 10-minute window: xGA +0.12 per-minute above baseline, xGF +0.09 above baseline. Fragile units: xGA +0.15-0.20; resilient units: xGA near zero, xGF +0.09-0.12. Year-over-year split stability correlation ~0.28-0.35.",
        "mechanism": "Conceding triggers an immediate tactical reorganisation demand that temporarily disrupts positional discipline. Resilient units regroup via leadership and defensive automaticity; fragile units remain positionally loose and concede the exploitable xGA window.",
        "conditions": "Window effect largest following unexpected low-xG concessions. Late-match concessions amplify the xGF galvanising component as urgency adds to motivational response.",
        "magnitude": "Average +0.12 xGA premium in the 10-minute post-concession window; fragile sides reach +0.15-0.20; resilient sides hold near zero while generating +0.09-0.12 xGF surplus.",
        "links": ["early_goal_composure_response", "late_goal_concession_fragility", "missed_chance_psychological_carryover", "pressure_response_persistence"],
    },
    {
        "slug": "missed_chance_psychological_carryover",
        "title": "Missed Big-Chance Psychological Carryover",
        "summary": "Correlation between a missed big chance (xG >= 0.40) and follow-on xGF in the next 10 minutes is near zero (+0.02 to +0.05), distinguishing genuine deflation from statistically independent sequential events.",
        "stat_signature": "Cross-match correlation of prior big-chance miss with subsequent 10-minute xGF: +0.02 to +0.05, indistinguishable from zero. Shot volume in the 10-minute window is similarly uncorrelated with a prior missed big chance.",
        "mechanism": "Possession-transition structure decouples successive events; the next chance arises from an independent phase with its own positional and defensive configurations. Perceived momentum sequences are narrative artefacts, not mechanistic carryover.",
        "conditions": "Near-zero carryover applies to aggregate cross-match data. Individual local momentum may persist within a sustained pressing phase but regresses to independence within 10 minutes. Null result most reliable outside the final 10 minutes.",
        "magnitude": "Carryover correlation of +0.02 to +0.05 is negligible; xGF production after a missed big chance is statistically indistinguishable from a matched window without a prior miss.",
        "links": ["must_score_finishing_tightening", "post_concession_response_window", "chasing_team_clarity_release"],
    },
    {
        "slug": "stoppage_time_decision_quality",
        "title": "Stoppage-Time Decision-Quality Shift",
        "summary": "Passing accuracy drops 4-8 pp and xG-per-shot falls 10-18% in added time under compounding fatigue and urgency, reducing effective scoring probability per attack by roughly 12-20%.",
        "stat_signature": "Chasing side stoppage-time passing accuracy: -4 to -8 pp below 70-90 minute baseline. xG-per-shot: -10-18% as speculative long-range efforts displace composed finishes. Holding sides: passing accuracy -3-6 pp as clearance urgency replaces progressive passing.",
        "mechanism": "Fatigue degrades cognitive processing speed and fine motor precision simultaneously; emotional stakes arousal maximises at match end, compressing deliberation time for chasing sides and short-circuiting possession-quality heuristics.",
        "conditions": "Pronounced in matches with unresolved competitive outcome at stoppage time. Larger for sides that have pressed intensively through minute 80. Substitution freshness dampens but does not eliminate the degradation.",
        "magnitude": "4-8 pp passing accuracy drop; xG-per-shot -10-18% below in-regulation baseline; combined effect reduces effective scoring probability per attack ~12-20% in stoppage time.",
        "links": ["must_score_finishing_tightening", "lead_holding_psychological_compression", "high_stakes_discipline_breakdown", "late_goal_concession_fragility"],
    },
    {
        "slug": "numerical_disadvantage_composure",
        "title": "Numerical-Disadvantage Composure",
        "summary": "After a dismissal, composure-resilient ten-player sides concede only +0.08-0.12 xGA per 90 above baseline — roughly half the naive ten-against-eleven exposure model — through disciplined deep-block reorganisation.",
        "stat_signature": "Naive ten-against-eleven xGA penalty: +0.15 to +0.22 per 90. High-composure sides: +0.08 to +0.12. Post-dismissal defensive-action share inside own third rises 35-50%; shot-concession rate +18-25% but shot-quality-against falls 10-15% as block depth degrades chance quality.",
        "mechanism": "Collective recalibration toward a deep compact block accepts territory concession in exchange for degrading the quality of chances allowed. Composure-resilient sides execute disciplined low-block shape that limits high-xG access beyond the volume increase.",
        "conditions": "Composure effect largest for dismissals between minutes 30-70, giving adequate reorganisation time before fatigue compounds the deficit. Very late dismissals reduce reorganisation opportunity; very early ones impose greater cumulative fatigue load.",
        "magnitude": "40-55% reduction in post-dismissal xGA exposure through disciplined shape; composure-resilient sides hold to +0.08-0.12 versus the +0.15-0.22 naive expectation.",
        "links": ["high_stakes_discipline_breakdown", "lead_holding_psychological_compression", "pressure_response_persistence"],
    },
    {
        "slug": "pressure_response_persistence",
        "title": "Cross-Season Pressure-Response Persistence",
        "summary": "Late-window defence composure shows modest year-over-year correlation (~0.28-0.38); offensive clutch-finishing is lower (~0.18-0.28), requiring at least 25 matched high-pressure events per season to separate durable signal from variance.",
        "stat_signature": "Year-over-year correlation of late-window goals-versus-expected: defensive composure 0.28-0.38; offensive clutch-finishing 0.18-0.28. Durable unit effects explain roughly 25-40% of observed late-window composure variance; remainder is seasonal noise.",
        "mechanism": "Composure signals mix genuine organisational culture carryover with high-variance random sequences; modest persistence reflects tactical culture attenuated by personnel churn, managerial change, and small-sample fluctuation.",
        "conditions": "Persistence highest for sides with identical coaching and settled defensive core across seasons. Weakest following managerial change or departure of the primary defensive organiser. Requires 30+ high-pressure events per season for reliability.",
        "magnitude": "Year-over-year composure correlations of 0.18-0.38 depending on metric; durable effects account for roughly 25-40% of observed late-window variance.",
        "links": ["late_goal_concession_fragility", "post_concession_response_window", "dead_rubber_pressure_absence", "numerical_disadvantage_composure"],
    },
    {
        "slug": "dead_rubber_pressure_absence",
        "title": "Dead-Rubber Pressure-Absence Distortion",
        "summary": "Stakes-free fixtures carry no genuine pressure signal; including them in composure metrics overstates late-window conversion by 6-10 pp and understates fouls by 15-20 pp, adding noise that stakes-weighting reduces by 15-25%.",
        "stat_signature": "Dead-rubber closing-phase conversion for already-decided sides exceeds high-stakes matched windows by ~6-10 pp. Fouls-per-defensive-action -15-20% in dead rubbers. Stakes-weighting by motivation index reduces composure-metric noise ~15-25% measured by cross-season prediction correlation.",
        "mechanism": "Absence of stakes eliminates arousal and avoidance-motivation drivers that produce composure costs; dead-rubber execution reflects technical quality at low arousal, systematically overstating composure when averaged into pressure-response metrics.",
        "conditions": "Applies to group-stage finales with already-decided outcomes, late-season rounds with no title/European/relegation stakes, and second legs with insurmountable aggregate margins. Contamination proportional to share of dead-rubber events in the analytic window.",
        "magnitude": "Un-weighted dead-rubber contamination overstates late-window conversion by 6-10 pp and understates fouls by 15-20 pp; stakes-weighting recovers 15-25% noise reduction in composure metrics.",
        "links": ["pressure_response_persistence", "high_stakes_discipline_breakdown", "chasing_team_clarity_release"],
    },
]
