"""ProgressionDynamics intelligence concept nodes for NBA — person-free spec."""
from __future__ import annotations

SPORT: str = "NBA"
FAMILY: str = "ProgressionDynamics"

CONCEPTS: list[dict] = [
    {
        "slug": "age_curve_peak_window",
        "title": "Aging Curve and Prime Window",
        "summary": "Box-composite value (BPM, VORP, EPM) rises into a peak band near ages 25–28 and declines thereafter; mean year-over-year value-per-minute delta by age bucket traces a concave arc across the population.",
        "stat_signature": "Population mean BPM peaks near age 26–27 at roughly +1.5 to +2.0; average annual delta is +0.4–0.6 in ages 22–25, near zero at 26–27, and −0.3 to −0.6 per year from 28 onward; VORP follows a similar arc with peak around 26–27.",
        "mechanism": "Physical maturity (strength, conditioning) reaches its ceiling in the mid-twenties while tactical understanding continues accumulating; the combination maximises both athletic output and decision quality simultaneously in that window before physical decline begins outpacing knowledge gains.",
        "conditions": "Peak window is widened for skill-primary archetypes (passers, floor spacers) and compressed for burst-dependent archetypes (above-the-break rim attackers); the arc is estimated on a mixed-effects population base and carries individual residual uncertainty of ±1–2 seasons.",
        "magnitude": "Population-level arc spans roughly 3–4 BPM units from the youngest-entry mean to peak; post-peak decline averages 0.4 BPM per year, accelerating past 32 to approximately 0.7–1.0 per year.",
        "links": ["skill_specific_aging_divergence", "cliff_decline_late_career", "physical_profile_aging_modifier", "minutes_durability_aging_interaction"],
    },
    {
        "slug": "skill_specific_aging_divergence",
        "title": "Skill-Specific Aging Divergence",
        "summary": "Distinct skills age on different schedules within one global trajectory: three-point accuracy and free-throw touch persist into the mid-thirties, while first-step burst, rim-finishing rate, and on-ball defensive impact decay meaningfully before the global BPM peak.",
        "stat_signature": "Three-point percentage age slope past peak: approximately −0.1 to −0.2 pp per year (slow decay); rim-finishing rate past 28: −1 to −1.5 pp per year; steals and blocks per 36 minutes past 29: −0.1 to −0.15 per year each; free-throw rate (FTA/FGA) declines ~0.02 per year past 29.",
        "mechanism": "Range shooting is rehearsed-motor skill less dependent on reactive athleticism; rim approaches and on-ball defense require burst speed and lateral agility whose physiological substrate erodes earlier with musculoskeletal wear.",
        "conditions": "Divergence is most pronounced when measured cross-sectionally holding minutes constant; body-load careers (high-usage guards) show steeper burst decay relative to the mean; spot-up specialists show near-flat accuracy curves into the mid-thirties.",
        "magnitude": "Clinically large for projection: a 30-year-old guard may retain 95% of peak shooting skill while carrying only 80% of peak rim-attack rate, making composite BPM inadequate without per-skill decomposition.",
        "links": ["age_curve_peak_window", "athletic_decline_versus_skill_retention", "free_throw_rate_aging_drift", "defensive_aging_trajectory"],
    },
    {
        "slug": "athletic_decline_versus_skill_retention",
        "title": "Athleticism Decline Against Skill Retention",
        "summary": "Physically driven outputs (dunk rate, transition frequency, blocks, steals) fall steeply with age past 30, while craft-driven outputs (passing reads, off-ball gravity, mid-range creation) hold or shift only slowly; the ratio of athletic-stat slope to skill-stat slope captures the adaptation arc.",
        "stat_signature": "Dunk-attempt rate past 30: roughly −0.3 to −0.5 per 100 possessions per year; transition-play frequency past 30: −0.4 pp per year; secondary-assist and hockey-assist rates show near-zero age slopes past 30; assist-to-turnover ratio often improves slightly as decision speed compensates for burst loss.",
        "mechanism": "Reactive muscle fibre composition and tendon elasticity decline with age and cumulative load; tactical reading, rhythm, and motor-program efficiency accumulate with repetitions and are less tied to fast-twitch capacity.",
        "conditions": "Observable when comparing high-age-season windows against the same player's peak-age seasons; confounded by minutes management that selectively protects older players in competitive minutes.",
        "magnitude": "Large for athletic stats: a two-standard-deviation drop in burst metrics from age 27 to 34 is typical; skill-based outputs drop less than one standard deviation over the same interval for non-burst-reliant archetypes.",
        "links": ["skill_specific_aging_divergence", "age_curve_peak_window", "defensive_aging_trajectory", "post_injury_performance_reintegration"],
    },
    {
        "slug": "rookie_to_year_three_development_slope",
        "title": "Rookie-to-Year-Three Development Slope",
        "summary": "Most players achieve their largest per-season value increments in seasons one through three as they adapt to NBA pace, physicality, and scheme complexity; the average per-82-game change in efficiency and usage compresses substantially in years four and five.",
        "stat_signature": "Average BPM delta for non-washout players: +0.8 to +1.2 per year in years 1–3; shrinks to +0.3–0.5 in years 4–5; true-shooting percentage improves roughly 1.5–2 pp per year in years 1–3 before stabilising; usage rate ramps ~1–1.5 pp per year as role expands.",
        "mechanism": "Strength and conditioning gains from the first NBA off-season, expanding offensive read-library, and defensive positioning adjustment compound into a steep early-career curve; by year four, the lowest-hanging adaptation gains are exhausted.",
        "conditions": "Slope is steeper for younger entrants and for players entering with underdeveloped off-ball skills; players with polished college shooting curves show flatter early improvement in efficiency but sharper usage ramps.",
        "magnitude": "Substantial: cumulative BPM gain in years 1–3 for eventual above-replacement players averages +2.5 to +4 points; the spread across this window is the widest of any three-year career interval.",
        "links": ["draft_age_development_runway", "breakout_versus_fluke_separation", "usage_role_progression_arc", "sample_size_prior_blending"],
    },
    {
        "slug": "draft_age_development_runway",
        "title": "Draft-Age Development Runway",
        "summary": "A player's age at league entry shifts the expected remaining-improvement runway: younger entrants carry steeper subsequent growth curves and wider upside intervals, while older draftees reach their ceilings sooner with less variance in outcome.",
        "stat_signature": "Correlation of entry age with cumulative value gained through age 25: approximately −0.25 to −0.35 (younger entry → more gain); 19-year-old entrants average roughly 30–40% more cumulative VORP by age 25 than 22-year-old entrants of the same draft slot.",
        "mechanism": "Younger entrants compress more developmental seasons before hitting the population-wide peak window; the same human-capital accumulation occurs over a longer runway, amplifying compounding improvement before physiological peak.",
        "conditions": "Effect is largest in the top quartile of draft position where talent ceiling is sufficient to realise the runway; weak-physical 19-year-olds whose entry is skill-incomplete may not show the full benefit until year three or later.",
        "magnitude": "Moderate to large in projection spread: a two-year age difference at entry widens the 90th-percentile upside estimate by roughly 1.5–2 BPM points at age 25, while compressing the median by only ~0.3 points.",
        "links": ["rookie_to_year_three_development_slope", "age_curve_peak_window", "breakout_versus_fluke_separation", "physical_profile_aging_modifier"],
    },
    {
        "slug": "usage_role_progression_arc",
        "title": "Usage and Role Progression Arc",
        "summary": "Multi-season migration of usage rate and on-ball responsibility captures how a player's offensive ecosystem role expands or contracts across a career; the trajectory is non-monotone for many players as team contexts change.",
        "stat_signature": "Median usage rate growth for eventual primary options: +2 to +3 pp per year in years 1–4, then flattening near 28–32% by year 5; time-of-possession per-game correlates with usage at r ≈ 0.82; secondary-option players often show usage fluctuation of ±4–6 pp when traded or injured teammates change the ecosystem.",
        "mechanism": "Coaching trust, demonstrated efficiency, and teammate scarcity interact to allocate on-ball responsibilities; early-career efficiency under low usage is the primary credential that earns expanded role in subsequent seasons.",
        "conditions": "Arc is interrupted by team trade activity, coaching changes, or injury to teammates altering the offensive hierarchy; projected role must condition on the expected roster environment, not historical personal usage.",
        "magnitude": "Large for counting-stat projection: a 5 pp usage-rate change shifts expected points-per-36 by roughly 2–3 points and assist rate by ~1 unit; usage-role transitions are among the strongest within-career projection drivers.",
        "links": ["rookie_to_year_three_development_slope", "true_shooting_skill_stabilization", "second_contract_workload_re_rating", "breakout_versus_fluke_separation"],
    },
    {
        "slug": "three_point_volume_expansion_curve",
        "title": "Three-Point Volume Expansion Curve",
        "summary": "Within-career, attempt-rate growth in three-point shots as a share of total field-goal attempts traces a multi-season ramp distinct from a single hot stretch, capturing genuine shot-diet restructuring.",
        "stat_signature": "Players who add range: multi-season slope of 3PA-share of FGA approximately +2 to +3 pp per year over a three-year expansion window; stabilisation occurs when 3PA-share settles within ±1 pp across two consecutive seasons; the expansion window correlates at r ≈ 0.60 with subsequent year-over-year retention of the higher share.",
        "mechanism": "Range expansion requires off-season repetition investment (muscle memory and shot-release modification) plus coaching validation via meaningful game attempts; once the skill reaches a repeatable release threshold, the efficiency plateau enables sustained volume without efficiency penalty.",
        "conditions": "Expansion is most durable when the player's catch-and-shoot accuracy on the new attempts exceeds 35% within the first expansion season; forced-volume expansions under high usage without efficiency support often regress or plateau.",
        "magnitude": "Meaningful for role projection: a successful 8 pp 3PA-share expansion adds roughly 1.5–2 expected points per 100 possessions to offensive output at constant efficiency, reshaping spacing gravity and defensive attention.",
        "links": ["shot_diet_quality_shift_persistence", "skill_specific_aging_divergence", "true_shooting_skill_stabilization", "usage_role_progression_arc"],
    },
    {
        "slug": "true_shooting_skill_stabilization",
        "title": "True-Shooting Skill Stabilization Horizon",
        "summary": "Efficiency rates require a minimum attempt sample before split-half reliability separates signal from noise and the reading can be treated as a stable personal trait; this horizon differs substantially across shot types.",
        "stat_signature": "Split-half reliability of true-shooting percentage crosses r = 0.70 at approximately 500–700 field-goal attempts for aggregate TS%; three-point percentage stabilises at r = 0.70 near 300–400 attempts; free-throw percentage at roughly 200 attempts; season-long samples below these thresholds warrant heavier regression to league average.",
        "mechanism": "Bernoulli trials with per-player latent probability require sufficient count before the central-limit variance shrinks enough to distinguish the personal rate from the population distribution; higher-variance shots (low-probability events) need more trials.",
        "conditions": "Stabilisation floors are lower for high-usage players reaching the attempt count faster; relevant for interpreting single-season efficiency changes as skill signal versus noise, especially for players under 400 FGA.",
        "magnitude": "Substantial for inference: a player on 200 FGA with 57% TS% has a 95% posterior interval of roughly ±4 pp around a league-mean prior; at 700 FGA the interval narrows to ±2 pp — the sample-size driven difference in certainty is prediction-critical.",
        "links": ["career_high_regression_after_outlier", "shot_diet_quality_shift_persistence", "sample_size_prior_blending", "breakout_versus_fluke_separation"],
    },
    {
        "slug": "career_high_regression_after_outlier",
        "title": "Career-Year Regression After an Outlier Season",
        "summary": "In the season following an outlier-high season unsupported by underlying indicators, systematic mean-reversion back toward the established baseline is reliably observed; the regression is proportional to the magnitude of the outlier above the prior trend.",
        "stat_signature": "Players in the top decile of single-season overperformance against their prior-three-year trend (excess of +3 BPM or more): average next-season decline of 1.8–2.5 BPM; regression fraction approximately 55–65% of the original excess; TS% outliers above +4 pp show similar reversion.",
        "mechanism": "Extreme seasons embed both genuine signal and unsustainable luck components (hot streaks, low-foul-rate variance, unusually high assisted-shot share); regression disaggregates these and re-weights toward the stable personal baseline.",
        "conditions": "Regression is attenuated when the outlier is accompanied by a documented shot-diet shift or role change; purely rate-driven outliers without structural underlying changes show the strongest and fastest reversion.",
        "magnitude": "Large in the first follow-on season: roughly 60% of the excess above the prior trend disappears, translating to 1.5–2.5 BPM or 3–4 pp TS% for the most extreme outlier cohort.",
        "links": ["down_year_rebound_after_underperformance", "breakout_versus_fluke_separation", "true_shooting_skill_stabilization", "sample_size_prior_blending"],
    },
    {
        "slug": "down_year_rebound_after_underperformance",
        "title": "Down-Year Rebound After Underperformance",
        "summary": "Partial mean-reversion upward in the season following a depressed season caused by injury or shooting variance, not aging; recovery fraction is conditioned on underlying shot-quality and burst indicators that distinguish variance-dip from structural decline.",
        "stat_signature": "Players whose down-year BPM dip exceeded the age-curve-predicted trajectory by more than 1.5 BPM with injury or variance cause identified: next-season recovery of approximately 50–70% of the excess dip on average; TS% recovers faster (~75%) than usage-dependent counting stats (~45%).",
        "mechanism": "Injury-suppressed or variance-driven seasons carry below-latent-skill observations; once the structural cause resolves, the player's rate stabilises closer to the pre-dip trajectory; the partial (not full) recovery reflects residual aging and genuine health degradation even in partially-injury-driven dips.",
        "conditions": "Recovery fraction is larger when the dip was caused by a single discrete injury event with full resolution confirmation; recovery is smaller for cumulative-load injuries where residual physical limitation persists into the following season.",
        "magnitude": "Moderate: expected recovery of ~1–1.5 BPM for dips in the 1.5–2.5 BPM range; clinically important for multi-year projection because ignoring this reversion biases forward estimates downward for injury-recovering players.",
        "links": ["career_high_regression_after_outlier", "post_injury_performance_reintegration", "sample_size_prior_blending", "minutes_durability_aging_interaction"],
    },
    {
        "slug": "post_injury_performance_reintegration",
        "title": "Post-Injury Performance Reintegration Curve",
        "summary": "After a major lower-body injury, explosiveness and efficiency recover along a ramp profile over multiple game-to-season intervals; recovery is often incomplete in the return season and may plateau short of the pre-injury baseline.",
        "stat_signature": "Rim-finishing rate (paint FG%) in the first 20 games post-return: approximately 3–5 pp below pre-injury baseline; burst metrics (drive frequency, transition play-share) recover to 80–90% of pre-injury level by game 30–40; full composite BPM recovery to within 0.5 of pre-injury baseline occurs in roughly 40–50% of major lower-body injury cases.",
        "mechanism": "Tendon and cartilage healing follows a staged remodelling timeline; return-to-play clearance precedes full reactive athleticism by 4–8 months; psychological hesitation compounds physical limitation in the first return block before motor patterns are fully trusted.",
        "conditions": "Recovery ramp is steeper for younger players and for injuries with surgical precision outcomes; older players and cumulative-load injuries show shallower ramps and lower plateaus; second occurrences of the same injury truncate the reintegration significantly.",
        "magnitude": "Large in the injury-return window: pre-to-post efficiency gap of 3–6% in burst-dependent stats across the first 30 games; gap narrows to 1–2% by season's end in successful reintegrations, with residual deficit persisting in the highest-intensity situations.",
        "links": ["down_year_rebound_after_underperformance", "athletic_decline_versus_skill_retention", "minutes_durability_aging_interaction", "physical_profile_aging_modifier"],
    },
    {
        "slug": "minutes_durability_aging_interaction",
        "title": "Minutes-Durability and Aging Interaction",
        "summary": "Games-played availability and sustainable per-game minutes load both decline with age, compounding raw per-minute skill decline into larger total-value loss; availability curves diverge by archetype and load history.",
        "stat_signature": "Games-played rate (fraction of 82): population mean declines approximately 1–2 games per year past age 30; per-game minutes ceiling for high-usage players drops roughly 1–1.5 minutes per year past 32; combined value loss from availability plus per-minute decline exceeds per-minute decline alone by 30–40% past age 33.",
        "mechanism": "Cumulative load history reduces recovery capacity and raises soft-tissue injury risk; teams managing ageing players shift toward rest protocols that hold per-minute rates stable while compressing games-played, masking the true decline in gross value.",
        "conditions": "Availability decline is steeper for guards with high historical drive and burst workload; bigs with low sprint-count roles retain games-played rates longer; compressed schedules accelerate the availability decline for older rosters.",
        "magnitude": "Large in projection: combining per-minute skill decline with games-played decline often doubles the projected value loss relative to a per-minute-only projection model for players past age 33.",
        "links": ["age_curve_peak_window", "physical_profile_aging_modifier", "cliff_decline_late_career", "post_injury_performance_reintegration"],
    },
    {
        "slug": "physical_profile_aging_modifier",
        "title": "Body-and-Position Aging Modifier",
        "summary": "Positional archetype and physical build shift the age-curve schedule; high-mileage guards with burst-reliant games peak earlier and decline faster, while perimeter-shooting bigs and mobile stretch-fours carry longer productive windows.",
        "stat_signature": "Age-slope differences in BPM across position-build clusters past peak: burst guards −0.8 to −1.0 BPM per year; perimeter bigs −0.4 to −0.6; rim-anchored bigs −0.5 to −0.7; shooting-oriented wings −0.3 to −0.5; age-peak centroid is roughly 1.5–2 years earlier for high-burst guards than stretch bigs.",
        "mechanism": "Reactive burst capacity, which guard play most depends on, erodes faster with cumulative musculoskeletal load than range shooting or post footwork; heavier body mass accelerates joint wear for bigs in non-shooting roles.",
        "conditions": "Modifier is applied on top of the global age curve; the cluster assignment is based on career shot-type and drive-frequency data, not nominal position label; positional role shifts mid-career (e.g., guard transitioning to off-ball wing) reset the relevant cluster.",
        "magnitude": "Moderate in forward projection spread: 1.5-year peak shift across clusters translates to roughly 1.2–1.8 BPM difference in projected value at age 32 for players of equivalent skill level at 27.",
        "links": ["age_curve_peak_window", "skill_specific_aging_divergence", "cliff_decline_late_career", "minutes_durability_aging_interaction"],
    },
    {
        "slug": "sample_size_prior_blending",
        "title": "Sample-Driven Prior-to-Observed Blending",
        "summary": "A player's projection should weight an aging-curve prior against accumulating in-career observations; optimal shrinkage weight on the prior decreases as career games grow, shifting from near-full-prior at entry to a balanced blend by year four.",
        "stat_signature": "Optimal prior weight on aging-curve expectation (minimising forward BPM error): approximately 0.75–0.85 after 50 career games; 0.50–0.60 after 150 games; 0.25–0.35 after 300 games; below 0.15 after 500+ games; split-half correlation of observed BPM rises from ~0.35 at 50 games to ~0.65 at 300.",
        "mechanism": "Empirical-Bayes shrinkage reduces expected squared error when the personal sample is small and noisy; as games accumulate, the personal sample carries enough information to outweigh the population prior in the bias-variance tradeoff.",
        "conditions": "Prior should be age-conditional (conditioning on the same age bucket in the population distribution); role-change events reset the effective sample size for role-specific outputs because prior career data was generated in a different statistical regime.",
        "magnitude": "Substantial in the early career window: prior-blended projections outperform naïve personal-sample estimates by approximately 0.8–1.2 BPM RMSE in years 1–2; the advantage compresses to 0.2–0.4 RMSE by year five.",
        "links": ["true_shooting_skill_stabilization", "breakout_versus_fluke_separation", "career_high_regression_after_outlier", "draft_age_development_runway"],
    },
    {
        "slug": "breakout_versus_fluke_separation",
        "title": "Breakout Against Statistical-Fluke Separation",
        "summary": "A durable quality leap supported by shot-diet changes, role expansion, and improved underlying rates differs from a non-repeating spike driven by make-rate variance; the distinguishing criteria are measurable within the breakout season.",
        "stat_signature": "Single-season jumps that persist into the following season: approximately 35–45% of jumps above +2 BPM; persistence rate rises to 60–70% when the jump is accompanied by documented shot-diet diversification (≥3 pp 3PA-share increase) or usage-rate increase of ≥4 pp; pure rate-driven jumps without structural support persist only 20–25% of the time.",
        "mechanism": "Durable leaps reflect a genuine shift in skill or role accessibility; variance-driven spikes reflect short-run luck in make rates and low-count defensive matchup draws; the shot-diet and usage evidence serves as a structural anchor separating the two.",
        "conditions": "Separation is clearest when the underlying-efficiency shift (xeFG%, free-throw-rate change) confirms or denies the observed TS% move; without underlying-indicator support, large efficiency jumps are treated as predominantly noise for forward projection.",
        "magnitude": "Critical for projection calibration: treating all jumps as real would overstate forward value by roughly 1.2–1.8 BPM for the fluke cohort; treating all as noise would understate by a similar margin for the genuine-breakout cohort.",
        "links": ["career_high_regression_after_outlier", "shot_diet_quality_shift_persistence", "rookie_to_year_three_development_slope", "sample_size_prior_blending"],
    },
    {
        "slug": "shot_diet_quality_shift_persistence",
        "title": "Shot-Diet Quality Shift Persistence",
        "summary": "Efficiency changes anchored by a durable shift in shot selection (location, assisted share, and shot-clock depth) persist more reliably than changes driven by a transient make-rate run on the same shot diet.",
        "stat_signature": "Persistence of next-season TS% change: shot-location-driven xeFG+ improvements retain ~70% of the change; make-rate residual above xeFG+ retains only ~25%; a 3 pp TS% gain attributed to location shift carries forward at ~2.1 pp; the same gain as pure make-rate luck carries forward at ~0.75 pp.",
        "mechanism": "Shot-location shifts reflect repeatable off-season skill investment or system exploitation; make-rate variance is high-entropy and reverts toward the player's per-location expected rate; separating the two requires expected-FG calibration on the same shot types.",
        "conditions": "Measurement requires at least 300 attempts in both the base and comparison season to separate xeFG from realised; robust when assisted-FG share and average-shot-distance data are available to account for play-type composition.",
        "magnitude": "Moderate: a 3 pp TS% difference between location-driven and luck-driven gains translates to roughly 0.6–0.9 points per 100 possessions of durable value difference in projection — meaningful at the margin for role and contract assessment.",
        "links": ["breakout_versus_fluke_separation", "three_point_volume_expansion_curve", "true_shooting_skill_stabilization", "career_high_regression_after_outlier"],
    },
    {
        "slug": "defensive_aging_trajectory",
        "title": "Defensive Impact Aging Trajectory",
        "summary": "On-ball defensive impact and rim protection decline earlier and more steeply relative to offensive skill as burst and lateral agility erode; defensive estimated plus-minus often peaks 1–2 years before offensive metrics.",
        "stat_signature": "Defensive EPM or DRPM age peak: approximately age 24–26 for on-ball defenders; rim-protection (opponent FG% at the rim) starts deteriorating near 28–29, roughly one year ahead of offensive BPM peak; defensive-rating contribution (DRTG per 100) declines by approximately 0.5–0.7 pts/100 per year past 30.",
        "mechanism": "Lateral quickness and help-rotation speed are the primary inputs to on-ball defense; both are fast-twitch-dependent and erode with age; shot-blocking requires reactive timing and explosion off the floor, similarly burst-reliant.",
        "conditions": "Defensive trajectory is steeper for guards who rely on lateral speed and for mobile bigs whose block rate depends on vertical burst; defensive scheme-adaptation (reading and positioning) partially offsets but does not fully compensate for the athletic loss.",
        "magnitude": "Large for multi-position comparison: a wing who contributes +1.5 defensive BPM at 26 may contribute +0.5 at 31 with consistent offensive production — the gap represents roughly 2.5 win shares over a season.",
        "links": ["skill_specific_aging_divergence", "athletic_decline_versus_skill_retention", "physical_profile_aging_modifier", "age_curve_peak_window"],
    },
    {
        "slug": "cliff_decline_late_career",
        "title": "Late-Career Cliff Decline",
        "summary": "In the final career phase past the mid-thirties, decline accelerates non-linearly beyond the smooth global arc; the second derivative of the value-by-age curve turns sharply negative as compounding physical, availability, and usage-ceiling constraints interact.",
        "stat_signature": "Second-derivative acceleration in BPM past age 35: approximately −0.4 to −0.6 additional BPM per year beyond the age-30-to-35 linear slope; games-played availability falls by roughly 5–8 games per year; combined, value loss past 35 runs roughly 40–50% faster than the age-30-to-35 rate.",
        "mechanism": "Multiple declining systems reach simultaneous threshold crossings — injury-risk ceiling, anaerobic recovery capacity, and cognitive processing speed all degrade in concert rather than independently; the interaction among these constraints creates non-linearity beyond simple summation.",
        "conditions": "Cliff steepness varies with prior body-load history and positional demand; players who managed load carefully or played a low-burst style may extend the linear phase by one to two seasons; cliff onset is earlier for high-cumulative-load guards.",
        "magnitude": "Large in terminal-phase projection: late-career players in this zone lose value at roughly 1.5–2× the rate predicted by a globally fitted polynomial; ignoring the second-derivative term materially overstates projected performance in the final 2–3 career seasons.",
        "links": ["age_curve_peak_window", "minutes_durability_aging_interaction", "physical_profile_aging_modifier", "athletic_decline_versus_skill_retention"],
    },
]
