"""Person-free concept-node spec: MLB / PsychologicalWarfare."""
from __future__ import annotations

SPORT = "MLB"
FAMILY = "PsychologicalWarfare"

CONCEPTS: list[dict] = [
    {
        "slug": "brushback_pitch_intimidation",
        "title": "Inside Brushback To Reclaim The Plate",
        "summary": "Purposeful tight-inside pitching backs a hitter off the plate, contracting their coverage zone for subsequent offerings and shifting spatial ownership without requiring a strike.",
        "stat_signature": "Post-brushback inside-pitch swing rate drops 8-14 pp; outer-third coverage expands ~0.7 inches via Statcast; pull-side contact rate decreases ~12 pp in the same at-bat.",
        "mechanism": "A near-miss inside pitch triggers a reflexive backward step, repositioning the hitter further from the plate. Subsequent load and stride adjust outward, opening outer-third vulnerability for the next sequence.",
        "conditions": "Most effective against free-swingers who dive toward the outer edge; deployed in 0-0 or 0-1 counts where a ball is tolerable; reinforced after a hitter barreled an inner-third pitch in a prior plate appearance.",
        "magnitude": "10-15 pp decline in xwOBA on inside pitches for the remainder of the plate appearance; effect dissipates after two plate appearances without reinforcement.",
        "links": ["pitch_to_count_dominance_messaging", "high_velocity_challenge_messaging", "called_pitch_predictability_baiting", "catcher_framing_gamesmanship"],
    },
    {
        "slug": "pace_disruption_quick_pitch",
        "title": "Tempo Disruption Via Quick-Pitch Rhythm",
        "summary": "Varying delivery tempo and intermittent quick-pitching denies hitters consistent timing cues, widening contact-quality dispersion and increasing early-count weak-contact rates.",
        "stat_signature": "Between-pitch interval CV above 0.35 correlates with 6-10 pp increase in early-count swing-and-miss; barrel rate drops ~2 pp against top-quartile tempo-variance pitchers.",
        "mechanism": "Hitters calibrate their pre-pitch routine to an expected inter-pitch window. Tempo variance forces continuous recalibration; early deliveries catch the hitter mid-routine, producing late or early contact.",
        "conditions": "Most disruptive against pull hitters who commit early in their load; effective in high-leverage situations where stepping out feels costly; reinforced by varying arm-action pause.",
        "magnitude": "~0.04 mph lower average exit velocity in 0-0 and 1-0 counts for top-variance pitchers versus metronomic peers; hard-contact-over-expected drops ~5 pp.",
        "links": ["step_off_to_break_hitter_timing", "mound_presence_projection", "batter_box_routine_to_impose_tempo", "tempo_acceleration_to_keep_defense_tired"],
    },
    {
        "slug": "mound_presence_projection",
        "title": "Mound Presence And Composure Projection",
        "summary": "A pitcher's deliberate, unhurried body language with runners on base signals emotional control, denying the opposition a sense that pressure is accumulating and correlating with expanded opponent chase rates.",
        "stat_signature": "Pitchers maintaining inter-pitch routine timing within 1.5 s of their bases-empty baseline with runners in scoring position show a 4-7 pp higher chase rate and a walk rate near their season baseline.",
        "mechanism": "Visible composure reduces hitter confidence that the pitcher is rattled. When hitters perceive no seam of vulnerability, they expand their zone in search of a mistake pitch rather than taking disciplined walks.",
        "conditions": "Manifest in multi-runner scenarios and after the opposing lineup has scored in the inning; amplified when the pitcher has a high career strikeout rate establishing prior dominance.",
        "magnitude": "Composure-stable pitchers suppress inherited-runner scoring at 28-32 percent versus 38-44 percent for pitchers showing visible tempo disruption; gap widest in innings six and later.",
        "links": ["pace_disruption_quick_pitch", "mound_visit_to_cool_a_hot_streak", "staredown_after_strikeout", "pickoff_pressure_to_rattle_runner"],
    },
    {
        "slug": "step_off_to_break_hitter_timing",
        "title": "Step-Off To Break Hitter Timing",
        "summary": "Stepping off the rubber resets the plate encounter and disrupts a comfortable hitter's load timing, particularly in deep counts where the hitter is maximally dialed in.",
        "stat_signature": "Step-offs in 2-2 and 3-2 counts correlate with a 9-13 pp increase in first-pitch-after-reset take rate and a 7 pp increase in weak-contact rate on the subsequent delivery.",
        "mechanism": "Deep-count hitters enter a heightened anticipatory state requiring a continuous delivery cue. A step-off collapses that state; many hitters default to passive zone-reading on the reset pitch, surrendering count leverage.",
        "conditions": "Deployed when the hitter is visibly locked in; most useful against anticipation-reliant hitters; less effective against patient hitters who routinely use box exits themselves.",
        "magnitude": "xSLG on the post-step-off pitch drops ~30-40 points; strikeout probability in the at-bat increases ~5 pp for a single step-off in a two-strike count.",
        "links": ["pace_disruption_quick_pitch", "batter_box_routine_to_impose_tempo", "called_pitch_predictability_baiting", "pitch_to_count_dominance_messaging"],
    },
    {
        "slug": "pickoff_pressure_to_rattle_runner",
        "title": "Repeated Pickoff Pressure On A Runner",
        "summary": "Serial pickoff attempts and varied hold durations shrink a runner's secondary lead, erode aggressiveness, and suppress steal attempts even for catalogued fast runners.",
        "stat_signature": "After three or more pickoff throws in one inning, lead distance contracts 0.4-0.8 feet; stolen-base attempt rate in subsequent innings drops 18-25 pp versus games without intensive pickoff pressure.",
        "mechanism": "Repeated throws shorten the comfortable secondary lead through operant conditioning. Varied hold durations prevent the runner from timing the delivery, making the jump window uncertain and steal expected-value negative.",
        "conditions": "Applied to high-frequency stealers with below-average first-step reaction time; intensified in one-run games where a stolen base significantly shifts run-expectancy; requires a low-profile leg kick or slide-step.",
        "magnitude": "Intensive pickoff sequences reduce in-game stolen-base success rate by ~10-15 pp; extra-base advancement on singles drops ~12 pp in games with heavy pickoff volume.",
        "links": ["leadoff_disruption_to_unsettle_starter", "mound_presence_projection", "tempo_acceleration_to_keep_defense_tired", "pace_disruption_quick_pitch"],
    },
    {
        "slug": "pitch_to_count_dominance_messaging",
        "title": "Establishing Inside Command As Messaging",
        "summary": "Consistently commanding the inner third early signals that the hitter cannot camp on the outer edge, forcing a neutral stance and opening the outer third for strikeout sequences.",
        "stat_signature": "Pitchers with inner-edge strike rate above 14 percent on first pitches generate outer-third whiff rate 4-6 pp higher; xwOBA on subsequent outer pitches drops ~25 points.",
        "mechanism": "Early inner-edge strikes force full-zone mental coverage. A hitter guarding the inner third cannot commit to an outer-edge barrel path; breaking balls away become unplayable when width-defending.",
        "conditions": "Most effective against hitters with an extreme outer-edge crouch or high opposite-field hard-contact rate; requires precise command since inner misses become extra-base threats.",
        "magnitude": "Hitters facing high inner-edge-strike pitchers show ~15-20 pp lower pull-rate and a 0.030-0.040 xwOBA decrease across all counts versus their baseline against inner-third-avoidant pitchers.",
        "links": ["brushback_pitch_intimidation", "high_velocity_challenge_messaging", "called_pitch_predictability_baiting", "catcher_framing_gamesmanship"],
    },
    {
        "slug": "mound_visit_to_cool_a_hot_streak",
        "title": "Mound Visit To Cool A Hot Streak",
        "summary": "A pitching-coach or catcher stoppage interrupts a surging lineup's momentum by resetting tempo and delivering adjusted sequencing instructions, forcing the dugout to recalibrate rather than ride a current read.",
        "stat_signature": "Post-visit wRC-plus in the immediately following at-bat drops ~18-25 points versus the three-at-bat pre-visit rolling average; rally-continuation rate falls ~9 pp in the inning of the visit.",
        "mechanism": "A hot lineup operates on predictive sequence reads. A mound visit signals a sequencing reset, invalidating those reads and forcing the next hitter to a neutral prior. The mandatory pause also cools the arousal characterizing offensive streaks.",
        "conditions": "Deployed after two or more consecutive baserunners without an out; most impactful in innings four through seven before bullpen deployment; reinforced by a concrete new pitch-mix instruction.",
        "magnitude": "Teams with high mound-visit efficiency suppress multi-run innings at a 6-9 pp higher rate than league average; single-run inning rate increases ~8 pp after a well-timed visit.",
        "links": ["mound_presence_projection", "pace_disruption_quick_pitch", "intentional_walk_as_disrespect_signal", "staredown_after_strikeout"],
    },
    {
        "slug": "intentional_walk_as_disrespect_signal",
        "title": "Bypassing A Hitter As A Pressure Signal",
        "summary": "An intentional walk explicitly transfers pressure to the on-deck hitter, who inherits high-leverage runners and a defined expectation to deliver, measurably degrading their performance.",
        "stat_signature": "On-deck hitters inheriting runners from an intentional walk post ~12-17 pp lower xwOBA than their season average at the same leverage tier; strikeout rate increases ~4 pp; walk rate drops ~3 pp.",
        "mechanism": "The intentional walk publicly assigns responsibility to the next hitter. This elevates arousal beyond optimal performance levels in hitters without high-pressure experience, producing zone expansion and timing disruption.",
        "conditions": "Highest impact against the fifth-or-lower-ranked on-deck hitter by wRC-plus; most effective late in close games; less effective when the on-deck hitter has above-average leverage-split statistics.",
        "magnitude": "Expected run-value of the on-deck at-bat decreases ~0.04-0.06 RE24 units compared with facing the same count without inherited-runner pressure; effect roughly doubles in the seventh inning or later.",
        "links": ["mound_visit_to_cool_a_hot_streak", "fielder_positioning_psych_pressure", "staredown_after_strikeout"],
    },
    {
        "slug": "catcher_framing_gamesmanship",
        "title": "Framing And Subtle Plate Gamesmanship",
        "summary": "A catcher's quiet receiving and presentation angle nudges borderline calls toward strikes and erodes a hitter's confidence in their own zone read, widening the zone they feel compelled to protect.",
        "stat_signature": "Top-quartile framing catchers generate 0.8-1.4 extra called strikes per game on pitches 1-3 inches outside the zone; opponent walk rate drops ~0.6 per nine; hitter protective-swing rate on borderlines rises 5-8 pp.",
        "mechanism": "Subtle glove presentation exploits umpire perceptual anchoring. When borderline pitches are called strikes repeatedly, the hitter expands their mental strike zone outward, widening the pitcher's effective zone without any pitch-location change.",
        "conditions": "Most impactful on borderline pitches in two-strike counts; amplified with wide-zone umpires; requires a pitcher with command sufficient to target the framing window consistently.",
        "magnitude": "A surplus of one called strike above expected per PA translates to ~0.025 reduction in opponent wOBA; 90th-percentile framing catchers generate ~12-18 runs above average per season via this pathway.",
        "links": ["pitch_to_count_dominance_messaging", "brushback_pitch_intimidation", "batter_box_routine_to_impose_tempo", "called_pitch_predictability_baiting"],
    },
    {
        "slug": "batter_box_routine_to_impose_tempo",
        "title": "Hitter Box-Exit To Impose Counter-Tempo",
        "summary": "A hitter repeatedly stepping out between pitches disrupts a quick-working pitcher's rhythm, reasserts pace control, and correlates with elevated pitcher walk rates and non-competitive pitch frequency.",
        "stat_signature": "Hitters averaging more than 1.5 box exits per PA induce walk rate ~1.2 pp higher and wild-pitch rate ~0.8 pp higher against fast-working pitchers versus those same pitchers facing low-exit-frequency hitters.",
        "mechanism": "Quick-working pitchers derive rhythm from continuous delivery momentum. Mandatory pauses force a mental routine restart, increasing the likelihood of rushing the wind-up or over-thinking location under repeated reset pressure.",
        "conditions": "Most effective against metronomic pitchers in the bottom third of between-pitch variance; deployed in high-leverage at-bats in middle innings when pitcher fatigue amplifies disruption.",
        "magnitude": "Pitchers facing high-exit-frequency hitters show ~0.15 higher walk rate per nine innings and a 3-4 pp increase in middle-third fastball usage as sequencing complexity is abandoned.",
        "links": ["pace_disruption_quick_pitch", "step_off_to_break_hitter_timing", "tempo_acceleration_to_keep_defense_tired"],
    },
    {
        "slug": "high_velocity_challenge_messaging",
        "title": "Velocity Challenge As Intimidation",
        "summary": "Daring a hitter with elevated fastball velocity in the strike zone asserts physical superiority and dares them to prove they can match the speed, producing late-swing whiff and foul-back as measurable signatures.",
        "stat_signature": "Fastballs at 97-plus mph in the upper third on even counts generate whiff rate 8-12 pp above the pitcher's overall swinging-strike rate; foul-back rate increases ~5 pp, indicating a consistent late-swing pattern.",
        "mechanism": "Top-velocity pitches in a hittable location force a binary decision: swing early with a poor contact path, or time correctly and accept an extremely narrow margin. Repeated exposure narrows timing-window confidence.",
        "conditions": "Most effective in 1-1 and 2-2 counts where accepting a ball is tolerable; amplified against low-spin-rate hitters who cannot read upper-zone ride; less reliable in humid conditions affecting grip.",
        "magnitude": "xwOBA on elevated 97-plus fastballs is ~0.240-0.270 versus ~0.310-0.330 on the same location at 91-93 mph; intimidation extends to the following off-speed pitch, generating a 3-5 pp higher chase rate.",
        "links": ["brushback_pitch_intimidation", "pitch_to_count_dominance_messaging", "staredown_after_strikeout", "called_pitch_predictability_baiting"],
    },
    {
        "slug": "staredown_after_strikeout",
        "title": "Post-Strikeout Dominance Display",
        "summary": "A demonstrative physical reaction after a high-leverage strikeout projects confidence and signals full-power operation to the remaining lineup, correlating with expanded chase rates from subsequent hitters.",
        "stat_signature": "The at-bat immediately following a display-strikeout in leverage index above 1.5 shows chase rate 5-8 pp above the pitcher's season baseline; zone-expansion first-pitch swing rate increases ~4 pp.",
        "mechanism": "Dominance displays exploit social-comparison mechanisms: seeing a teammate punched out emphatically raises the next hitter's threat appraisal and lowers their confidence in taking close pitches, producing aggressive early swinging on borderline offerings.",
        "conditions": "Strongest when the strikeout ends a threat (runner on base, two outs) and the display is brief but visible; diminishes against lineups that have normalized the behavior through multiple prior exposures.",
        "magnitude": "Next-hitter xwOBA decreases ~0.015-0.025 following a demonstrative strikeout in leverage index above 1.5; effect attenuates to near-zero by the third plate appearance following the display.",
        "links": ["mound_presence_projection", "high_velocity_challenge_messaging", "intentional_walk_as_disrespect_signal", "mound_visit_to_cool_a_hot_streak"],
    },
    {
        "slug": "fielder_positioning_psych_pressure",
        "title": "Demonstrative Shift Positioning As Pressure",
        "summary": "Conspicuous defensive alignment that telegraphs awareness of a hitter's spray tendencies crowds their comfort zone and invites a deviation attempt that typically degrades contact quality.",
        "stat_signature": "Hitters facing an extreme shift who attempt to go opposite-field show batting average ~25-35 points below their opposite-field season average; ground-ball rate increases ~6 pp as hitters attempt to beat the shift low.",
        "mechanism": "A conspicuously visible shift forces a real-time mental calculation: accept the shift or alter swing mechanics. Either path degrades expected contact quality, and the cognitive load of the decision itself fragments timing.",
        "conditions": "Most impactful against extreme pull-hitters with sub-25-percent opposite-field ground-ball rate; less effective late in games when the hitter has adapted; amplified against free-swingers who struggle to take walks as an alternative.",
        "magnitude": "Pull-hitters against an extreme shift show ~15-20 pp higher ground-ball rate and 0.030-0.050 lower xwOBA on pulled balls versus standard alignment; the deviation attempt costs ~0.015 xwOBA on opposite-field contact.",
        "links": ["intentional_walk_as_disrespect_signal", "pitch_to_count_dominance_messaging", "catcher_framing_gamesmanship"],
    },
    {
        "slug": "tempo_acceleration_to_keep_defense_tired",
        "title": "Pace Acceleration To Pressure A Tiring Defense",
        "summary": "A quick-working pitcher's accelerated tempo keeps the defense alert while denying hitters reset time, compressing game duration and reducing cognitive bandwidth available to the opposing lineup in late innings.",
        "stat_signature": "Games pitched above 20 pitches per minute show a 3-5 pp increase in opposing two-strike approach contraction in innings five through seven; late-inning walk rate drops ~0.4 per nine for fast-pace pitchers versus slow-pace peers.",
        "mechanism": "Short inter-pitch intervals deny hitters full breathing cycles and prevent dugout-to-plate sequencing communication. A defense kept continuously engaged maintains focus better than one idle between long at-bats.",
        "conditions": "Effective in warm-weather games where slower recovery amplifies fatigue; most pronounced in the sixth inning and later; complements contact-oriented pitching profiles that generate quick outs.",
        "magnitude": "Fast-pace pitchers allow ~0.08-0.12 fewer runs per nine innings attributable to pace alone (controlling for stuff); defensive range factor improves ~0.05 per game behind fast-pace starters.",
        "links": ["pace_disruption_quick_pitch", "batter_box_routine_to_impose_tempo", "mound_presence_projection", "leadoff_disruption_to_unsettle_starter"],
    },
    {
        "slug": "called_pitch_predictability_baiting",
        "title": "Baiting With A Telegraphed Pattern",
        "summary": "Deliberately showing a repeated pitch pattern early establishes a false expectation that a sequence-breaking surprise then exploits, producing an expanded chase on the pattern-break pitch as the measurable outcome.",
        "stat_signature": "Pattern-break pitches in put-away counts show a 10-14 pp higher whiff rate than the same pitch type thrown without prior pattern establishment; chase rate on the surprise pitch increases ~8 pp.",
        "mechanism": "Hitters build intra-at-bat sequencing priors from the first two to three pitches seen. A repeated type trains an anticipatory read; the pattern break fires against that read, arriving at a speed or location the hitter's motor program is unprepared for.",
        "conditions": "Most effective against analytically oriented hitters who lean on sequencing tendencies; requires command of at least two pitch types in the same tunnel; most potent in two-strike counts at peak anticipatory arousal.",
        "magnitude": "Strikeout probability in the at-bat increases ~8-12 pp when the pattern-break follows three same-type pitches; effect is strongest on the third appearance against the same hitter in a game, where the pattern has had maximum time to calcify.",
        "links": ["pitch_to_count_dominance_messaging", "step_off_to_break_hitter_timing", "catcher_framing_gamesmanship", "high_velocity_challenge_messaging"],
    },
    {
        "slug": "leadoff_disruption_to_unsettle_starter",
        "title": "Aggressive Baserunning To Unsettle A Starter",
        "summary": "Big secondary leads, fakes, and delayed steals divide a pitcher's attention between the hitter and the runner, measurably elevating stretch walk rates and wild-pitch frequency.",
        "stat_signature": "Pitchers facing runners who extend secondary lead beyond 15 feet show stretch walk rate ~0.8 per nine higher and wild-pitch rate ~0.4 per nine higher than their bases-empty baseline.",
        "mechanism": "Split attention degrades the pitcher's ability to fully execute their delivery mechanics. Repeated fakes and delayed-steal threats force the pitcher to hold, disrupt their tempo, and increase mechanical variance in their release-point consistency.",
        "conditions": "Most impactful in innings one through four when the starter is still establishing rhythm; amplified against pitchers with below-average pickoff move rating; effective when paired with an aggressive third-base coach expanding take-extra-base decisions.",
        "magnitude": "Starter ERA in games with two or more stolen-base attempts in the first four innings is ~0.25-0.40 higher than in games without; first-pitch strike rate drops ~4 pp when a runner extends their lead conspicuously.",
        "links": ["pickoff_pressure_to_rattle_runner", "tempo_acceleration_to_keep_defense_tired", "pace_disruption_quick_pitch"],
    },
]
