"""Tennis / ResourceAllocation — dense person-free concept specs."""
from __future__ import annotations

SPORT = "Tennis"
FAMILY = "ResourceAllocation"

CONCEPTS = [
    {
        "slug": "challenge_review_inventory",
        "title": "Challenge Review Inventory",
        "summary": "Finite incorrect-challenge pool per set; conserving reviews to enter tiebreaks with at least one intact materially shapes late-set decision latitude.",
        "stat_signature": "Challenges spent per set (allotted 3, median ~1.4 used); overturn success rate ~30–35 pct; tiebreak entry with at least one challenge remaining ~55–65 pct.",
        "mechanism": "Each wasted incorrect challenge removes a future review option; retaining one for a tiebreak preserves the ability to contest a close call on a match-deciding point where the asymmetry of errors is highest.",
        "conditions": "Most pronounced on hard courts with high ball-tracking accuracy, sets progressing to 6-6, and when baseline line calls cluster under heavy serving.",
        "magnitude": "Players entering tiebreaks with at least one challenge win tiebreak first points at a ~3–5 pct higher rate versus those already exhausted — a small but consistent asymmetry.",
        "links": ["challenge_leverage_point_selection", "tiebreak_resource_reservation", "between_point_clock_management"],
    },
    {
        "slug": "challenge_leverage_point_selection",
        "title": "Challenge Leverage Point Selection",
        "summary": "Selectivity in deploying a finite challenge budget on break and set points rather than low-stakes exchanges maximises the scoreline value of each overturn.",
        "stat_signature": "Challenges on break/set points ~15–22 pct of total (versus their ~8–12 pct share of all points); overturn rate on leverage challenges ~38 pct versus routine ~28 pct.",
        "mechanism": "An overturned call on a break point shifts the scoreline directly; the same overturn on 40-0 produces no scoreline change, so identical overturn probability yields higher expected value at high leverage.",
        "conditions": "Emerges on fast surfaces with high challenge accuracy, in closely contested sets where break opportunities are rare, and inside tiebreaks.",
        "magnitude": "Selective challengers convert their budget into score-line reversals on ~1 in 8 challenges versus ~1 in 14 for indiscriminate challengers — roughly a 40–50 pct efficiency gap.",
        "links": ["challenge_review_inventory", "tiebreak_resource_reservation", "momentum_break_timeout_lever"],
    },
    {
        "slug": "medical_timeout_strategic_timing",
        "title": "Medical-Timeout Strategic Timing",
        "summary": "Placement of a permitted medical timeout relative to score state and an opponent's run affects both the physical recovery benefit and the rhythm disruption delivered.",
        "stat_signature": "Proportion called during opponent 3-plus-game runs versus neutral stretches; post-timeout points-won swing for the recipient in the subsequent service game ~+4 to +7 pct.",
        "mechanism": "A stoppage cools elevated opponent arousal, resets breathing rhythm, and enables tactical recalibration; the disruption effect on the opponent is the larger observable driver beyond physiological recovery.",
        "conditions": "Most impactful in third or fifth sets when both players are fatigued, after a sequence of short points that kept heart rate elevated, and after the recipient's serve was broken.",
        "magnitude": "Recipients hold their next service game at roughly 3–6 pct above the situational baseline — a small but statistically observable interruption benefit.",
        "links": ["momentum_break_timeout_lever", "bathroom_break_reset_economy", "changeover_recovery_economy"],
    },
    {
        "slug": "bathroom_break_reset_economy",
        "title": "Off-Court Break Reset Economy",
        "summary": "Permitted off-court breaks between sets disrupt opponent rhythm and enable physiological and tactical reset; frequency relative to set outcome is the primary observable.",
        "stat_signature": "Breaks taken after losing a set ~2.3x more frequent than after winning; games-won differential in the two resumption games ~+0.15 games per game for the break-taker.",
        "mechanism": "An off-court break removes the opponent's rhythm cues built during the prior set, allows the departing player to rehearse a tactical adjustment, and provides temperature and hydration recovery.",
        "conditions": "Appears in long matches, extreme heat, and when a player has just been broken to end a set and needs both tactical and physiological reset.",
        "magnitude": "Break-takers win the first service game after returning at ~5–8 pct above expected from form — a consistently observed first-game resumption advantage.",
        "links": ["medical_timeout_strategic_timing", "heat_rule_recovery_allotment", "energy_budget_across_sets"],
    },
    {
        "slug": "energy_budget_across_sets",
        "title": "Cross-Set Energy Budgeting",
        "summary": "Physical reserves rationed across a multi-set match produce measurable decay in rally length, movement intensity, and point-construction complexity from early to late sets.",
        "stat_signature": "Shots per point falling 8–14 pct from set 1 to set 5 in five-setters; estimated movement-distance decline ~6–10 pct by the final set; late-match shift toward first-strike endings.",
        "mechanism": "Aerobic capacity and neuromuscular precision degrade under sustained intensity; over-investment in early sets narrows the physical margin in the deciding set, forcing abbreviated point construction before tactical preferences call for it.",
        "conditions": "Most pronounced in five-set formats, in extreme heat, and when early sets contain above-average long rallies or extended tiebreaks.",
        "magnitude": "Players losing a physically demanding first set by 7-5 or tiebreak show ~4–7 pct lower first-serve percentage in the third set relative to tournament baseline — a detectable depletion signal.",
        "links": ["first_serve_effort_allocation", "rally_length_energy_pricing", "decisive_set_reserve_deployment"],
    },
    {
        "slug": "first_serve_effort_allocation",
        "title": "First-Serve Effort Allocation",
        "summary": "Deliberate variation of serve exertion by point importance concentrates peak speed on break and set points while reducing effort on routine 40-0 situations to conserve shoulder and core reserves.",
        "stat_signature": "Serve-speed coefficient of variation by point importance tier; top-20 pct fastest serves occurring on break/set points at ~1.8–2.4x base rate; speed uplift of 4–8 km/h on break points versus 40-0.",
        "mechanism": "Maximal serve effort demands significantly more rotator-cuff and leg drive than controlled placement; concentrating peak exertion on the fraction of points with highest free-point value extends the window before speed-fatigue becomes visible.",
        "conditions": "Observed in best-of-five matches after the second set, high-heat conditions, and when a player holds serve routinely and can afford to bank effort on low-leverage games.",
        "magnitude": "Players maintaining an 8 km/h speed differential between break-point and 40-0 first serves show ~3–5 pct less serve-speed decay in the final set compared to uniform-effort servers.",
        "links": ["second_serve_risk_budgeting", "energy_budget_across_sets", "service_game_speed_modulation"],
    },
    {
        "slug": "free_point_chase_versus_rally_cost",
        "title": "Free-Point Chase Against Rally-Cost Tradeoff",
        "summary": "The tension between chasing aces through high-risk serving to save rally energy and accepting rallies at controlled serve speed integrates benefit and cost in the ace-plus-double-fault rate.",
        "stat_signature": "Ace-plus-double-fault rate (service game variance proxy, typically 15–30 pct combined) cross-referenced against average rally length per service game and hold percentage.",
        "mechanism": "High-risk serving converts some games to near-zero-effort free points but inflates double-fault exposure; a service game lost on a double fault costs more energy in the ensuing return game than the rally energy saved, making the breakeven non-trivial.",
        "conditions": "Sharpens on fast surfaces where aces are achievable, in late-match sets where double faults are most costly, and against heavy returners who punish second-serve uplift.",
        "magnitude": "Players with ace rates above 8 pct and double-fault rates below 3 pct sustain ~0.4 fewer rallies per service game — roughly 15–20 fewer extended points across a five-setter.",
        "links": ["first_serve_effort_allocation", "second_serve_risk_budgeting", "return_aggression_energy_rationing"],
    },
    {
        "slug": "return_aggression_energy_rationing",
        "title": "Return-Aggression Energy Rationing",
        "summary": "Selective deployment of full-effort step-in returns concentrated on genuine break opportunities conserves energy on the majority of service games that will hold regardless.",
        "stat_signature": "Step-in frequency on break-point opportunities ~35–50 pct versus routine 30-0 return points ~15–22 pct; break-point conversion rate 35–45 pct in return games.",
        "mechanism": "Defending serve is the lower-expectation role; exhausting lateral effort on every return point yields diminishing returns because most service games hold; concentrating explosive attempts on the 8–12 pct of points that are break opportunities maximises return on physical investment.",
        "conditions": "Most pronounced against big servers on fast surfaces, in matches extending to four or five sets, and when the player must preserve energy for a deciding set.",
        "magnitude": "Selective step-in returners maintain return-winner rate on break points ~4–6 pct above their average return rate; non-selective returners show ~2 pct lower break-point conversion over five sets.",
        "links": ["energy_budget_across_sets", "decisive_set_reserve_deployment", "free_point_chase_versus_rally_cost"],
    },
    {
        "slug": "tiebreak_resource_reservation",
        "title": "Tiebreak Resource Reservation",
        "summary": "Deliberate conservation of physical and mental peak output for tiebreak decision points produces a measurable uplift in first-serve percentage and movement intensity at 6-6.",
        "stat_signature": "First-serve percentage in tiebreak versus prior-set average (uplift ~3–6 pct); movement-intensity proxy in tiebreak mini-games versus the preceding service game; tiebreak win rate correlation with late-set hold economy.",
        "mechanism": "A tiebreak compresses a full set's strategic value into 12–15 points; a player arriving with marginally more neuromuscular precision and a retained challenge can alter the set outcome, making pre-tiebreak conservation positive expected value.",
        "conditions": "Relevant only in sets reaching 6-6; amplified in best-of-five formats and on fast surfaces where tiebreaks are disproportionately common.",
        "magnitude": "Players who modestly reduce service exertion at 5-4 and 5-5 show first-serve percentages 4–7 pct higher in the tiebreak, translating to roughly a 2–3 pct tiebreak-win-rate uplift over a tournament sample.",
        "links": ["challenge_review_inventory", "energy_budget_across_sets", "decisive_set_reserve_deployment"],
    },
    {
        "slug": "between_point_clock_management",
        "title": "Between-Point Clock Management",
        "summary": "The permitted 25-second window functions as a finite per-point recovery resource; pressure compresses it involuntarily, reducing serve quality on high-importance points.",
        "stat_signature": "Average between-point time rises from ~18 s after rallies under 5 shots to ~22–23 s after rallies over 15 shots; time-violation warning rate on the most important points ~0.8 per 100 points.",
        "mechanism": "Breath recovery after a 15-shot rally requires ~20–22 seconds; pressure-induced compression of this window reduces first-serve percentage and elevates double-fault risk on the subsequent high-leverage point.",
        "conditions": "Manifests under shot-clock enforcement, in hot conditions, after three or more consecutive long rallies, and in the final two service games of a fifth set.",
        "magnitude": "Players spending under 18 seconds after rallies of 12-plus shots show first-serve percentage 5–8 pct below their match average on the following point — a clear compression penalty.",
        "links": ["serve_clock_pressure_absorption", "changeover_recovery_economy", "energy_budget_across_sets"],
    },
    {
        "slug": "changeover_recovery_economy",
        "title": "Changeover Recovery Economy",
        "summary": "The 90-second changeover is a structured recovery and re-strategizing window; how effectively a player uses it predicts the first-point-won rate immediately after resumption.",
        "stat_signature": "First-point-won rate post-changeover versus mid-game service points (uplift ~4–6 pct); behavioral signals of seated versus standing rest stratified by preceding game intensity.",
        "mechanism": "Seated 90-second rest permits partial lactate clearance and cognitive processing of tactical patterns; players who compress this window (standing, pacing) show diminished cardiovascular recovery and higher first-serve fault rates.",
        "conditions": "Most measurable after high-intensity games with three or more deuces, in the second half of long matches, and when a break has just occurred and tactical re-evaluation is most valuable.",
        "magnitude": "The first service game after a 4-plus-deuce game is held at ~3–5 pct below tournament baseline; disciplined changeover routines narrow that deficit by approximately half.",
        "links": ["between_point_clock_management", "medical_timeout_strategic_timing", "energy_budget_across_sets"],
    },
    {
        "slug": "service_game_speed_modulation",
        "title": "Service-Game Hold Economy",
        "summary": "Rationing effort to achieve love and 15-holds closes service games cheaply, minimising points played and banking energy for return games where break opportunities are rare.",
        "stat_signature": "Love-hold rate ~12–18 pct for top servers; combined love/15-hold rate ~25–38 pct; points-per-service-game rising from 3.8 at high hold economy to 4.6 at low.",
        "mechanism": "A service game closing 40-0 consumes three points of reserve; a deuce game five or more; the cumulative difference across five sets creates a meaningful energy margin entering decisive moments.",
        "conditions": "Most pronounced on fast surfaces where first-serve percentage is highest; degrades late in matches when fatigue reduces first-serve percentage.",
        "magnitude": "A player with 30 pct combined love/15-hold rate averages ~3.8 points per service game versus ~4.6 for 15 pct combined — roughly 16–20 extra points across a typical five-setter.",
        "links": ["first_serve_effort_allocation", "energy_budget_across_sets", "second_serve_risk_budgeting"],
    },
    {
        "slug": "second_serve_risk_budgeting",
        "title": "Second-Serve Risk Budgeting",
        "summary": "Allocation of risk on second serves balances double-fault exposure against ceding returner control; speed and spin variance by point importance captures the risk distribution.",
        "stat_signature": "Double-fault rate on break points ~2.8 pct versus 40-15 ~1.4 pct; second-serve speed variance stratified by importance tier; returner-winner rate against flat versus kick second serves.",
        "mechanism": "A kick or slice second serve sacrifices speed for margin, reducing double-fault risk while giving the returner more time to attack; increasing second-serve speed on break points trades elevated double-fault exposure against a higher free-point probability.",
        "conditions": "Most consequential against aggressive step-in returners who punish weak second serves, on hard courts where spin bounces predictably, and in the final set of a five-setter.",
        "magnitude": "Players maintaining second-serve speed within 5 pct of match average on break points double-fault at ~2.1x baseline versus those who spin up (~1.4x baseline) — a meaningful volatility difference at critical junctures.",
        "links": ["first_serve_effort_allocation", "service_game_speed_modulation", "tiebreak_resource_reservation"],
    },
    {
        "slug": "decisive_set_reserve_deployment",
        "title": "Decisive-Set Reserve Deployment",
        "summary": "Release of held-back physical and tactical reserves in a final deciding set produces an uplift in court-position aggression and net-approach rate relative to earlier sets.",
        "stat_signature": "Net-approach rate in set 5 relative to sets 1–4 (uplift ~5–10 pct); court-position depth shifting forward; winner-to-unforced-error ratio increase in the decisive set versus the preceding one.",
        "mechanism": "A player who rationed effort holds a physiological reserve accessible in the final set; the tactical expression is more aggressive shot selection and net approaches that shorten points — deliberate depletion of banked energy in the highest-value set.",
        "conditions": "Relevant in best-of-five formats or three-setters reaching a decider; amplified when the player won the prior set and enters the decider with psychological momentum.",
        "magnitude": "Players showing the largest net-approach uplift in the fifth set win the set ~4–6 pct more often than expected from set-level ratings — a modest but observable aggressive reserve signature.",
        "links": ["energy_budget_across_sets", "tiebreak_resource_reservation", "rally_length_energy_pricing"],
    },
    {
        "slug": "rally_length_energy_pricing",
        "title": "Rally-Length Energy Pricing",
        "summary": "Willingness to extend or abbreviate rallies based on remaining stamina produces a late-match shift toward aggressive first-strike endings as the energy cost of each additional shot rises.",
        "stat_signature": "Shots-per-point declining 8–14 pct from set 1 to set 5; winner-to-unforced-error ratio on 6-plus-shot rallies declining with match progression; net-approach rate rising 5–10 pct in the fifth set.",
        "mechanism": "Each additional shot in a rally exponentially increases energy cost; a player pricing long rallies as expensive terminates them through approach shots or flat drives, accepting marginally lower groundstroke quality on the attacking shot.",
        "conditions": "Emerges most clearly in clay-court matches past 90 minutes, five-set encounters, and when a player carries a physical injury into the late set.",
        "magnitude": "Late-match first-strike proportion rises ~6–9 pct from set 1 to set 5, with the shift correlating ~0.45 with total shots played in prior sets.",
        "links": ["energy_budget_across_sets", "decisive_set_reserve_deployment", "return_aggression_energy_rationing"],
    },
    {
        "slug": "momentum_break_timeout_lever",
        "title": "Momentum-Break Stoppage Lever",
        "summary": "Deployment of any permitted stoppage to arrest an opponent's consecutive-game run, with the trigger threshold and post-stoppage run-arrest rate as the key observables.",
        "stat_signature": "Proportion of stoppages initiated after opponent 3-plus-game runs (~30–40 pct of all stoppages); post-stoppage opponent games-won in the subsequent 4 games versus matched non-stoppage periods (~−0.4 games).",
        "mechanism": "An opponent on a run has elevated confidence and settled serving rhythm; any permitted stoppage resets that rhythm, forces a restart of warm-up routines, and creates a window for tactical recalibration — interrupting the momentum loop at its highest-cost point.",
        "conditions": "Most impactful in middle sets of a five-setter, after three or more consecutive games lost, and when the opponent has been serving with high first-serve percentage.",
        "magnitude": "Following a stoppage triggered during a 3-plus-game run, the trailing player holds their next service game ~5–8 pct above their trailing-momentum baseline — a demonstrable momentum-arrest pattern.",
        "links": ["medical_timeout_strategic_timing", "bathroom_break_reset_economy", "challenge_leverage_point_selection"],
    },
    {
        "slug": "serve_clock_pressure_absorption",
        "title": "Serve-Clock Pressure Absorption",
        "summary": "Capacity to sustain full recovery routines within the clock window on the most important points without incurring time violations, measured as the gap between average recovery time and the 25-second limit.",
        "stat_signature": "Average between-point time on break/set points versus match average (gap ~1.5–3.5 s); time-violation warning rate on break points ~2.1x baseline; first-serve percentage immediately after a warning ~−5 to −8 pct.",
        "mechanism": "High-leverage points trigger stress responses extending natural recovery time; a player unable to absorb that extension within the clock incurs a violation, itself elevating arousal and compressing serve mechanics on the ensuing point.",
        "conditions": "Most pronounced at 5-6 second serves in a third set, during tiebreaks, and in any match where fatigue has already pushed between-point recovery near the 25-second threshold.",
        "magnitude": "Players receiving a clock warning on a break-point serve double-fault at ~1.8x their match baseline on that point — a clear stress-amplification effect within the finite time budget.",
        "links": ["between_point_clock_management", "tiebreak_resource_reservation", "second_serve_risk_budgeting"],
    },
    {
        "slug": "heat_rule_recovery_allotment",
        "title": "Heat-Rule Recovery Allotment",
        "summary": "Permitted extended breaks under extreme heat conditions function as a targeted recovery resource; break-activation patterns and the post-break decay arrest in movement intensity are the key signals.",
        "stat_signature": "Break-activation rate by temperature threshold (most rules trigger above 35 °C wet-bulb index); post-break movement-intensity decay arrest relative to non-heat matches at equivalent set depth (~−3 to −5 pct less decay).",
        "mechanism": "Extreme heat accelerates core-temperature rise and sweat-rate dehydration; an extended break interrupts the thermal spiral by enabling towel cooling, ice vest use, and controlled rehydration — partially resetting the physiological ceiling for the subsequent set.",
        "conditions": "Applies exclusively in tournaments permitting heat rules (typically set-break only), in afternoon sessions on hard courts, and most consequentially in five-set matches where the thermal load accumulates across sets.",
        "magnitude": "In matches where heat rules are invoked, point-construction quality in the post-break set is approximately 4–6 pct less degraded than in comparable-temperature matches without the break — a measurable thermal rescue effect.",
        "links": ["energy_budget_across_sets", "bathroom_break_reset_economy", "changeover_recovery_economy"],
    },
]
