"""ResourceAllocation NBA concept nodes — person-free."""
from __future__ import annotations

SPORT: str = "NBA"
FAMILY: str = "ResourceAllocation"

CONCEPTS: list[dict] = [
    {
        "slug": "timeout_inventory_burn_rate",
        "title": "Timeout Inventory Burn Rate",
        "summary": "The pace at which a team consumes its allotted timeouts across quarters determines late-game tactical flexibility; early-burn teams frequently enter the final 90 seconds with zero timeouts.",
        "stat_signature": "Median timeouts per quarter: ~1.1 (Q1), ~1.2 (Q2), ~0.9 (Q3), ~1.6 (Q4); share of games entering the final 3 minutes with zero timeouts: ~8–12%; disciplined teams hold ≥2 timeouts entering Q4 in ~65% of games versus ~38% for high-burn teams.",
        "mechanism": "Each timeout is a scarce resource with no carry-forward except one full timeout per half; deploying inventory in low-leverage early segments depletes the stock needed to stop momentum runs or draw up end-game possessions.",
        "conditions": "Burn-rate pressure is highest for teams that surrender large mid-game runs and rely on drawn-up ATO possessions to score; self-sufficient half-court offenses tolerate lower Q1–Q3 reserves.",
        "magnitude": "Moderate: losing a timeout in the final 90 seconds reduces the probability of executing a designed last possession by an estimated 20–30 pp relative to timeout-holding peers.",
        "links": ["stop_the_bleed_timeout_threshold", "timeout_hoarding_endgame_risk", "advance_timeout_baseline_optionality"],
    },
    {
        "slug": "advance_timeout_baseline_optionality",
        "title": "Advance-Timeout Baseline Optionality",
        "summary": "Holding a live-ball timeout in the final two minutes preserves the right to advance the inbound to the front-court sideline, converting potential full-court scrambles into designed half-court scoring sets.",
        "stat_signature": "Teams with an available timeout in the final 30 seconds generate front-court inbounds on ~78% of possessions versus ~42% without; half-court designed-set PPP ~1.05–1.15 versus full-court scramble ~0.68–0.78; advance-right utilization among eligible possessions: ~55–65%.",
        "mechanism": "Rule permits calling a timeout before the ball is inbounded to relocate the spot to the front-court sideline; this removes 45–55 feet of required advance distance, converting a reaction play into a scripted set and substantially raising shot quality.",
        "conditions": "Optionality is only valuable when the timeout is actually available; most consequential for trailing teams in the final 5–20 seconds; defensive anticipation of the advance spot partially reduces the PPP premium.",
        "magnitude": "High in-situation: the ~0.30–0.40 PPP gap between a front-court set and a full-court scramble is among the largest execution differentials in late-game offense.",
        "links": ["timeout_inventory_burn_rate", "challenge_save_for_late_game", "clock_kill_versus_conserve_tradeoff"],
    },
    {
        "slug": "stop_the_bleed_timeout_threshold",
        "title": "Stop-the-Run Timeout Threshold",
        "summary": "Coaches deploy discretionary timeouts to interrupt opponent scoring runs; the run-size trigger follows a distributional pattern with a modal break-point around 7–9 unanswered points, with substantial variance across coaching styles.",
        "stat_signature": "Median run before timeout call: 7 unanswered points; 80th-percentile trigger: 10 points; share of 8-0 runs met with a timeout within the next possession: ~58–65%; post-timeout opponent PPP over the next three possessions drops ~0.06–0.10 relative to the run pace.",
        "mechanism": "A mid-game run generates momentum through faster pace, transition breakdowns, and offensive rhythm; a timeout resets defensive assignments, allows substitutions, and eliminates the tempo advantage accumulated by the running team.",
        "conditions": "Threshold is lower in Q4 and overtime where each possession carries higher win-probability weight; coaches with deep rotations use substitutions instead of timeouts for smaller runs, conserving inventory.",
        "magnitude": "Moderate: the ~0.06–0.10 PPP disruption over three possessions following a timeout is equivalent to approximately half a possession of swing in the trailing team's favor.",
        "links": ["timeout_inventory_burn_rate", "timeout_hoarding_endgame_risk", "fatigue_aware_substitution_budgeting"],
    },
    {
        "slug": "coach_challenge_trigger_selectivity",
        "title": "Coach Challenge Trigger Selectivity",
        "summary": "The single coach's challenge is deployed with varying selectivity; overturn success rate is strongly correlated with restraint — coaches challenging only high-confidence miscalls convert at nearly twice the rate of reactive challengers.",
        "stat_signature": "League-wide challenge overturn rate: ~32–38%; top-selectivity coaches (fewest challenges, highest leverage): ~48–55% overturn; bottom quartile: ~18–24%; median challenges per 100 games: ~42; high-leverage challenges (final 5 min, within 6 pts): ~38% of all challenges.",
        "mechanism": "The challenge grants one reviewable reversal attempt per game; spending it on a marginal or correct call wastes the resource with no recovery; replay confirms calls at a high base rate, so only clear geometry errors (out-of-bounds, goaltending) reliably exceed the overturn threshold.",
        "conditions": "Selectivity matters most in tight Q4 situations where a wasted challenge eliminates the only recourse against a clear late-game error; lower stakes in blowouts where challenge value is negligible.",
        "magnitude": "Moderate: a systematic improvement from 30% to 48% overturn rate yields approximately one additional successful reversal per 14 games, non-trivial across a full season.",
        "links": ["challenge_leverage_timing_curve", "challenge_save_for_late_game", "instant_replay_review_burden"],
    },
    {
        "slug": "challenge_leverage_timing_curve",
        "title": "Challenge Leverage Timing Curve",
        "summary": "The win-probability swing of the contested call determines the optimal moment to spend the challenge; early-half challenges typically carry 1–3% WP swings while fourth-quarter equivalents can reach 4–9%.",
        "stat_signature": "Median WP impact by period: Q1 ~1.2%, Q2 ~1.8%, Q3 ~2.4%, Q4 ~5.1%; share of challenges deployed in Q4: ~46%; share in Q1–Q2: ~31%; mean clock remaining at challenge deployment in Q4: 6.4 minutes.",
        "mechanism": "Win-probability sensitivity to a single-possession swing accelerates as clock and margin compress; temporal patience in challenge deployment is a leverage multiplier even when early calls appear equally unfair in isolation.",
        "conditions": "The curve steepens in playoff games with tighter score margins; teams with strong early-game run prevention face less pressure to challenge early, naturally preserving the resource for peak-leverage windows.",
        "magnitude": "Large in the optimal window: a Q4 reversal in a one-possession game carries ~5–9 pp WP swing versus ~1–2 pp in Q1.",
        "links": ["coach_challenge_trigger_selectivity", "challenge_save_for_late_game", "timeout_inventory_burn_rate"],
    },
    {
        "slug": "foul_to_give_management",
        "title": "Foul-to-Give Management",
        "summary": "Deploying non-penalty fouls before the bonus to stop the shot clock or break offensive rhythm converts expendable foul inventory into defensive resets without conceding free throws.",
        "stat_signature": "Pre-bonus deliberate fouls per quarter for high-utilization teams: ~0.8–1.3; shot-clock seconds harvested per use: ~14–18; opponent PPP on the reset possession: ~0.94–1.00 versus ~1.04–1.10 on the interrupted possession; frequency peaks in Q4 with margins of 1–4 points.",
        "mechanism": "A foul before the penalty threshold awards no free throws; the defense surrenders a half-court possession reset but eliminates a high-leverage end-of-clock look, resets the shot clock, and interrupts offensive rhythm at the cost of one unused foul slot.",
        "conditions": "Rational when the prevented look is a primary creator in isolation or off a screen for a live-dribble three; irrational when the foul inventory is needed for later endgame stop-the-clock scenarios.",
        "magnitude": "Moderate per use: the ~0.10–0.15 PPP disruption on the targeted possession is meaningful; systematic over-use depletes the non-penalty buffer needed for late-game foul-to-give opportunities.",
        "links": ["team_foul_penalty_pacing", "free_throw_bonus_avoidance", "intentional_foul_clock_arbitrage"],
    },
    {
        "slug": "team_foul_penalty_pacing",
        "title": "Team Foul Penalty Pacing",
        "summary": "How rapidly a defense accumulates the four-foul threshold within a quarter determines how long it can play aggressively; early-penalty teams concede a higher share of opponent points from bonus free throws.",
        "stat_signature": "Average minutes elapsed before fourth foul: ~7.2 min (top-discipline quartile) versus ~4.8 min (bottom); share of quarter points from bonus FT trips when penalty entered before 4:00 remaining: ~22–28%; early-penalty teams allow ~3.5 additional expected points per quarter from free-throw exposure alone.",
        "mechanism": "Once in the penalty, every defensive contact awards free throws regardless of shot attempt, converting high-variance half-court offense into ~1.50 expected points per trip; defenders must retreat to passive positioning, conceding perimeter shots on top of the FT exposure.",
        "conditions": "Penalty pacing pressure is highest against drive-heavy offenses that manufacture contact; zone and drop-coverage schemes reduce individual foul frequency by routing challenges away from the body.",
        "magnitude": "Large in early-penalty quarters: ~3–5 expected points conceded above a discipline-neutral baseline when the penalty is entered 3+ minutes before end of the quarter.",
        "links": ["foul_to_give_management", "free_throw_bonus_avoidance", "intentional_foul_clock_arbitrage"],
    },
    {
        "slug": "star_minutes_budgeting",
        "title": "Star Minutes Budgeting",
        "summary": "Distributing a high-usage creator's finite minutes to preserve Q4 availability against opponent lineup downgrades is a core rotation decision; Q4-heavy skew correlates with stronger closing lineups but higher mid-game vulnerability.",
        "stat_signature": "Net-rating delta when the primary creator is on versus off: ~+6 to +10 pts/100; Q4 minutes share for top-usage players with load management: ~13 min Q4 versus ~9–10 min average in Q1–Q3; teams staggering less than 9 min in Q1–Q3 protect ~14 min of Q4/OT availability.",
        "mechanism": "A high-usage creator's per-minute impact degrades with cumulative fatigue; front-loading minutes in lopsided segments burns the budget before the highest-leverage closing window; staggered deployment preserves fresh-legs impact for possessions where the on-off gap is widest.",
        "conditions": "Most critical in playoff environments where opponents precisely match high-usage minutes; regular-season blow-out risk allows more liberal early use; back-to-back scheduling compresses total availability.",
        "magnitude": "Large over the final six minutes: the ~6–10 pts/100 on-off gap for a fully fresh creator in a close Q4 translates to roughly 0.8–1.5 expected net points in the critical window.",
        "links": ["rotation_stagger_resource_overlap", "fatigue_aware_substitution_budgeting", "garbage_time_resource_preservation"],
    },
    {
        "slug": "rotation_stagger_resource_overlap",
        "title": "Rotation Stagger Resource Overlap",
        "summary": "Deliberately offsetting the rest windows of primary creators ensures at least one is on the floor at all times; the share of game minutes with zero creators on court is a direct measure of stagger discipline.",
        "stat_signature": "Share of game minutes with zero on-court creators (both top-two usage players resting): disciplined teams ~6–9% versus undisciplined ~15–20%; net-rating deficit in zero-creator minutes: ~-8 to -14 pts/100; typical creator overlap windows: ~14–18 min per game.",
        "mechanism": "Removing both primary creators simultaneously collapses half-court offense to bench-level creation; staggering rest windows maintains a creation floor in every segment while avoiding excessive fatigue on highest-load players.",
        "conditions": "Stagger discipline is easiest against predictable opponent rotations; in playoff series, opponents scout rest windows and deploy optimal defensive lineups against bench-only units.",
        "magnitude": "Moderate: reducing zero-creator exposure from 18% to 8% of game minutes saves approximately 4–5 net points per game from exploitation of creation vacuums.",
        "links": ["star_minutes_budgeting", "fatigue_aware_substitution_budgeting", "garbage_time_resource_preservation"],
    },
    {
        "slug": "intentional_foul_clock_arbitrage",
        "title": "Intentional Foul Clock Arbitrage",
        "summary": "A trailing team's deliberate fouling trades two opponent free throws for a retained possession plus clock stoppage, a rational exchange when the deficit-per-remaining-possession ratio exceeds the expected-point cost.",
        "stat_signature": "Expected opponent points per deliberate-foul trip (league-average FT): ~1.50–1.54; expected points from the recovered possession: ~0.98–1.02 PPP; net swing per foul cycle: ~-0.50 to -0.56 pts; strategy is EV-positive when trailing by more than ~0.5 pts per remaining possession.",
        "mechanism": "Clock stoppage converts an opponent ball-control possession — which would drain the clock without yielding a comeback chance — into a bilateral exchange; the leading team scores below its PPP expectation while the trailing team gains a possession, gradually reducing the possession deficit.",
        "conditions": "Becomes irrational against high-FT-percentage opponents where the two-shot value approaches 1.70+; away-from-the-ball violations can convert to enhanced penalties.",
        "magnitude": "Situation-dependent: within the rational corridor, sustained fouling reduces the expected final deficit by 2–4 points over a four-possession sequence, enabling comebacks that pure clock-management forecloses.",
        "links": ["hack_target_selection", "team_foul_penalty_pacing", "deliberate_foul_versus_three"],
    },
    {
        "slug": "hack_target_selection",
        "title": "Off-Ball Foul Target Selection",
        "summary": "Choosing to foul the weakest free-throw shooter in the opponent rotation suppresses expected points per trip; the strategy yields positive expected value only when the target's FT percentage falls below the ~52% crossover threshold.",
        "stat_signature": "Strategy EV-positive when target FT% <~52–54%; a 40% shooter yields ~0.80 expected points per two-shot trip versus ~1.00 PPP from a live possession; league share of rotation players below the crossover: ~4–7%; deliberate foul rate against sub-50% FT targets: ~2.3 per targeted game.",
        "mechanism": "Free throws are a controlled, defense-independent event; substituting a high-expected half-court possession with two shots from a poor FT shooter lowers expected opponent points; the gap widens with worse FT percentage and is eliminated as target quality approaches league average.",
        "conditions": "Requires a clearly sub-threshold shooter who cannot be substituted off before the foul; anti-hack rules in certain game-clock windows convert the foul into a two-shot plus possession penalty, reversing EV.",
        "magnitude": "Moderate per trip when target FT% <45%: ~0.15–0.25 expected points saved per deliberately fouled possession; cumulative over 8–12 targeted trips can approach 1.5–2.5 net expected points.",
        "links": ["intentional_foul_clock_arbitrage", "team_foul_penalty_pacing", "free_throw_bonus_avoidance"],
    },
    {
        "slug": "free_throw_bonus_avoidance",
        "title": "Bonus-Avoidance Foul Discipline",
        "summary": "Once near the penalty threshold, disciplined defenders suppress reaching fouls to avoid converting the opponent's marginal offense into the higher expected-point pipeline of free-throw trips.",
        "stat_signature": "Foul rate per 100 defensive possessions after reaching the third foul drops ~18–22% relative to the prior three-possession window; disciplined teams reduce bonus-FT-trip concessions by ~1.8–2.4 per quarter; teams with the largest foul-rate drop see ~0.8–1.2 PPP reduction per quarter from avoided free-throw trips.",
        "mechanism": "Each foul after the threshold converts a variable half-court possession into a near-certain ~1.50 expected-point sequence; the defense accepts contested mid-range shots rather than challenging drives, trading lower shot quality for not deepening the penalty exposure.",
        "conditions": "Avoidance is rational when the defense is already near the threshold with several minutes remaining; less relevant in the final 90 seconds where foul-to-give logic applies regardless.",
        "magnitude": "Moderate: avoiding one bonus foul per quarter saves ~0.50–0.55 expected points; over four quarters this accumulates to roughly 2 expected points of structural advantage.",
        "links": ["foul_to_give_management", "team_foul_penalty_pacing", "hack_target_selection"],
    },
    {
        "slug": "clock_kill_versus_conserve_tradeoff",
        "title": "Clock-Kill Against Conserve Tradeoff",
        "summary": "A leading team must choose between maximizing possession length to shorten the game and conserving clock to leave a response window after a potential opponent score; the optimal possession length shifts with score margin and remaining time.",
        "stat_signature": "Average possession length when leading by 6+ with under 3 minutes: ~20–23 seconds versus ~14–16 seconds at game flow; share of possessions using 22+ seconds when leading by 3–5 in the final 2 minutes: ~34–42%; teams maximizing clock show ~4–6% lower trailing-opponent scoring-run rate in the final two minutes.",
        "mechanism": "Every drained second reduces opponent possession count; a maximal-clock possession eliminates a counter-attack without surrendering a possession; however, forced late-clock shots raise turnover and offensive-rebound risk, potentially gifting a quick opponent basket.",
        "conditions": "Clock-kill is rational at 2+ possession leads inside two minutes; with a one-possession lead the offense must seek a good shot rather than trading the possession for clock only to surrender the lead on the opponent's next trip.",
        "magnitude": "Moderate: disciplined clock-kill with a 3–6 point lead inside two minutes reduces opponent expected-possession count by ~0.6–0.9, worth ~0.6–0.9 expected points in prevented offense.",
        "links": ["timeout_inventory_burn_rate", "advance_timeout_baseline_optionality", "star_minutes_budgeting"],
    },
    {
        "slug": "deliberate_foul_versus_three",
        "title": "Foul-Up-Three Possession Trade",
        "summary": "Intentionally fouling an opponent who has secured the ball beyond the arc while leading by three in the final possession converts a potential tying three-point attempt into a two-shot free-throw sequence, reducing tying probability.",
        "stat_signature": "Tying probability from an open corner three: ~35–40%; tying probability via a two-shot plus offensive-rebound-and-tip chain: ~12–16%; foul-up-three deployment rate in correct corridor: ~28–38% of eligible possessions; execution failure (contact while shooter rises) converts to a three-shot foul, restoring tying probability to ~65–70%.",
        "mechanism": "A two-shot FT trip yields ~1.50 expected points, leaving the opponent one point short of tying; the only path to three points requires making both free throws and recovering an offensive rebound on a deliberate miss — a low-probability chain compared with an open three.",
        "conditions": "Strategy requires fouling cleanly before the shooter enters the act of shooting; in-rhythm drives or early jump releases before contact raise the three-shot-foul risk; rational only in the absolute final possession.",
        "magnitude": "High in-situation: the 20–25 pp reduction in tying probability is among the largest single-decision leverage events available in late game.",
        "links": ["intentional_foul_clock_arbitrage", "hack_target_selection", "team_foul_penalty_pacing"],
    },
    {
        "slug": "challenge_save_for_late_game",
        "title": "Challenge Reserve Discipline",
        "summary": "Withholding the challenge through marginal first-half calls preserves the resource for high-leverage late-game whistles; the share of challenges deployed in Q4 is a proxy for reserve discipline.",
        "stat_signature": "Share of challenges in Q4 among top-reserve-discipline teams: ~58–65%; bottom quartile: ~30–36%; challenge success rate when deployed in Q4 only: ~44–51% versus ~26–32% for free-spending teams; WP swing per successful Q4 reversal: ~4.5–8.0 pp.",
        "mechanism": "The single challenge is non-replenishable; spending it on a Q1 call worth ~1.2 pp WP versus reserving it for a Q4 reversal worth ~6 pp is a 5x leverage sacrifice; reserve discipline increases expected value even before accounting for the higher overturn rate in careful late-game selection.",
        "conditions": "Reserve strategy requires accepting perceived injustice early; in high-stakes playoff games, early-game miscalls on key momentum-defining sequences can justify breaking the reserve policy if the call is both clear and momentum-altering.",
        "magnitude": "Moderate to large: the combined effect of higher leverage and higher overturn probability in reserved late challenges produces roughly 2.5–3x the expected WP gain of a freely spent early challenge.",
        "links": ["coach_challenge_trigger_selectivity", "challenge_leverage_timing_curve", "instant_replay_review_burden"],
    },
    {
        "slug": "fatigue_aware_substitution_budgeting",
        "title": "Fatigue-Aware Substitution Budgeting",
        "summary": "Linking substitution timing to accumulated on-court load — minutes in the current stint, distance covered, high-intensity burst count — identifies the physiological inflection point where a player's per-minute impact begins to decay.",
        "stat_signature": "Per-minute on/off impact decay after 10 consecutive minutes for high-usage players: ~-1.2 to -2.5 pts/100 per additional minute; correlation between stint length above 10 minutes and turnover-rate increase: r ~0.31–0.38; load-threshold substitutions yield ~0.7–1.1 higher net rating over the five minutes following a rest window.",
        "mechanism": "Sustained high-intensity effort depletes physical and cognitive capacity within a single stint; decision speed and defensive positioning accuracy decline measurably after ~8–12 consecutive minutes for high-volume players; a 3–5 minute rest window restores near-peak capacity, compounding over a full game.",
        "conditions": "Impact of substitution timing is largest for players logging 36+ minutes per game and on short rest; playoff games compress windows as coaches guard against lineup mismatches in opponent defensive sets.",
        "magnitude": "Small to moderate per possession, cumulative over 48 minutes: load-aware rotations are estimated to preserve approximately 1.5–2.5 net points per game by sustaining per-minute impact at higher levels.",
        "links": ["star_minutes_budgeting", "rotation_stagger_resource_overlap", "garbage_time_resource_preservation"],
    },
    {
        "slug": "garbage_time_resource_preservation",
        "title": "Garbage-Time Resource Preservation",
        "summary": "Once win probability surpasses a near-certain threshold, withdrawing starters and withholding unused timeouts eliminates injury exposure and preserves health for subsequent games without competitive cost.",
        "stat_signature": "Starter bench-transition threshold in blowouts: win probability ~94–97% or margin ≥16 with under 6 minutes; average game minute at full bench deployment: ~41.5; season injury rate per 1,000 competitive versus garbage-time minutes: competitive ~1.8–2.2x higher in muscular soft-tissue categories.",
        "mechanism": "Starter fatigue accumulates across a season; unnecessary high-intensity minutes in decided games accelerate wear without benefit; withheld timeouts also represent spared rest-period obligations for key players and remove the incentive to burn the clock through tactical stoppages.",
        "conditions": "Preservation rationale strengthens on back-to-backs and in playoff series where the next game follows within 48 hours; teams in play-in contention may still value garbage-time load data for rotation decisions.",
        "magnitude": "Small per game, cumulative across a season: consistent garbage-time protection accumulates an estimated 3–6 fewer high-intensity player-game loads per starter over 82 games, descriptively associated with reduced late-season soft-tissue injury incidence.",
        "links": ["star_minutes_budgeting", "rotation_stagger_resource_overlap", "timeout_hoarding_endgame_risk"],
    },
    {
        "slug": "timeout_hoarding_endgame_risk",
        "title": "Timeout Hoarding Endgame Risk",
        "summary": "Carrying excess timeouts into garbage minutes signals missed mid-game momentum-interruption opportunities; unused timeouts at the final buzzer are a proxy for under-deployment rather than disciplined preservation.",
        "stat_signature": "Share of games with 2+ timeouts unused at the buzzer: ~14–18% league-wide; correlation between unused-timeout count at buzzer and largest mid-game opponent run allowed: r ~0.27–0.34; high unused-timeout teams concede opponent runs of 10+ points ~23% more frequently than league-median teams.",
        "mechanism": "A timeout not spent on a momentum-disruption or ATO possession delivered zero tactical value; preserving it past the relevant window reflects systematic over-valuation of the resource at the expense of using it when expected value was highest.",
        "conditions": "Hoarding risk is most damaging against fast-tempo opponents capable of 8–12 point burst runs; less damaging against half-court-dominant opponents where an uninterrupted run develops more slowly.",
        "magnitude": "Moderate when it occurs: the opportunity cost of an 8-point run that a timeout could have broken is roughly 8 points of expected swing — larger than the marginal end-game value of the unused timeout.",
        "links": ["timeout_inventory_burn_rate", "stop_the_bleed_timeout_threshold", "garbage_time_resource_preservation"],
    },
    {
        "slug": "instant_replay_review_burden",
        "title": "Replay-Triggered Stoppage Resource",
        "summary": "Official-initiated replay reviews create unplanned stoppages of 2.8–3.5 minutes; the coaching staff better prepared to draw up plays and substitute during the interval extracts a free tactical-reset without depleting timeout inventory.",
        "stat_signature": "Average official-initiated replay duration: ~2.8–3.5 minutes; per-game frequency in Q4: ~0.6–0.9; post-review possession efficiency shift: the team holding possession at stoppage shows ~+0.04–0.08 PPP on the subsequent three possessions versus their game average, consistent with a rest-and-draw-up benefit.",
        "mechanism": "Replay reviews pause the game for several minutes without depleting either team's timeout inventory; coaching staffs that prepare during the review by diagramming plays or making substitutions convert the interval into a no-cost timeout, gaining the ATO possession premium for free.",
        "conditions": "Benefit accrues disproportionately to the team that held possession when the review was called; teams with strong draw-up capacity and flexible substitution patterns extract more value from the unplanned break.",
        "magnitude": "Small per event, occasionally decisive: a ~0.04–0.08 PPP lift over three possessions amounts to roughly 0.1–0.2 expected points per review, potentially meaningful when reviews cluster near end-of-game critical moments.",
        "links": ["coach_challenge_trigger_selectivity", "challenge_save_for_late_game", "stop_the_bleed_timeout_threshold"],
    },
]
