"""Spec: Soccer / ResourceAllocation — person-free concept nodes for the brain."""
from __future__ import annotations

SPORT = "Soccer"
FAMILY = "ResourceAllocation"

CONCEPTS = [
    {
        "slug": "substitution_window_budgeting",
        "title": "Substitution Window Budgeting",
        "summary": "Elite soccer permits five substitutions across three permitted stoppage windows plus half-time, making the distribution of changes across windows a finite-resource allocation problem. Bunching multiple changes into one window preserves flexibility in later windows; spreading singles across all three wastes the option value of later information.",
        "stat_signature": "Subs used per window distribution (1-2-2, 2-2-1, etc.); share of matches where fewer than three windows are used (efficiency rate). Teams wasting a window slot with a single isolated early sub lose tactical optionality 35-45 % of the time when a late state change occurs.",
        "mechanism": "Each permitted stoppage window is a non-transferable option. A change made in window one commits the slot regardless of whether the match state justifies it; unused windows expire. Managers who bunch changes maximise the number of options available when game state is most informative.",
        "conditions": "Window-spreading cost is highest in close matches where late state changes (goal conceded or scored after minute 70) are frequent; least costly when the match is resolved by the 60th minute and the remainder is load-management.",
        "magnitude": "Squads with a median 2-2-1 distribution across congested fixtures retain at least one tactical sub option in 80-85 % of late-game state changes, versus 55-60 % for squads defaulting to 1-1-1-1-1 single-change patterns.",
        "links": ["fresh_legs_timing_curve", "tactical_versus_injury_sub_allocation", "early_substitution_information_cost", "chasing_game_attacker_overload"],
    },
    {
        "slug": "fresh_legs_timing_curve",
        "title": "Fresh-Legs Timing Curve",
        "summary": "The clock-minute at which attacking substitutions are introduced determines how much fatigue-differential advantage the replacement can exploit against tiring defenders. A replacement entering at minute 60-65 can operate against defenders already 10-15 % below peak sprint output for 25-30 minutes; one entering at minute 80 retains only a narrow window.",
        "stat_signature": "Median attacking-sub minute; post-substitution sprint-count of replacement in first 20 minutes on pitch relative to starter exit-minute sprint rate; expected-goals created per replacement minute in the 60-80 window versus the 75-90 window.",
        "mechanism": "Defenders accumulate deceleration and glycogen depletion loads that reduce peak sprint speed and lateral change-of-direction capacity from around minute 60 onward. A fresh attacker entering at this point exploits a growing differential in explosive capacity that an attacker who has also been on the pitch for 60 minutes cannot.",
        "conditions": "Differential is largest when the defending team is playing its fourth match in a 10-day congested block, or when high-press, high-line defensive systems have burned sprint reserves early. Less pronounced against low-block defensive shapes where individual sprint counts are already moderated.",
        "magnitude": "Attacking subs introduced in minutes 60-70 average 15-20 % more sprints in their first 20 minutes than the starter they replace was producing in minutes 60-70, generating a measurable xG uplift of 0.05-0.12 per 30-minute appearance.",
        "links": ["substitution_window_budgeting", "set_piece_specialist_deployment", "chasing_game_attacker_overload", "energy_pressing_intensity_budget"],
    },
    {
        "slug": "defensive_lockdown_substitution",
        "title": "Lead-Protection Substitution",
        "summary": "Replacing an attacker with a defensive midfielder or centre-back when holding a narrow lead converts offensive resources into defensive insurance, reducing the conceded expected-goals rate while accepting a reduced attacking threat. The formation typically shifts from a three-to-two or four-to-three midfield structure.",
        "stat_signature": "Post-substitution change in conceded xG per 90 minutes; shift in midfield-defensive-player count; team defensive-line depth change (meters retreated); and ratio of defensive actions per opposition possession in the 15 minutes before versus after the change.",
        "mechanism": "An additional outfield defensive body increases the number of passing lanes blocked, reduces space between midfield and defensive lines, and adds a press-resistant screening body in front of the centre-backs. The compactness gained reduces the opponent's high-probability shot count.",
        "conditions": "Most effective when protecting a one-goal lead in the final 20-25 minutes against opponents who build through central channels and possess strong late-match xG numbers. Less impactful against teams reliant on wide overloads or set-piece aerial delivery.",
        "magnitude": "A defensive substitution in the 70th minute or later is associated with a 0.08-0.14 reduction in conceded xG per 90 minutes in the subsequent period, at the cost of an 0.05-0.10 reduction in own-attack xG creation.",
        "links": ["substitution_window_budgeting", "tactical_versus_injury_sub_allocation", "time_wasting_clock_management", "yellow_card_aggression_budget"],
    },
    {
        "slug": "tactical_versus_injury_sub_allocation",
        "title": "Tactical Against Forced-Substitution Allocation",
        "summary": "Injuries or medical enforcements that consume a substitution slot before the intended tactical window erode the budget for planned changes, leaving the manager with fewer options to shape the match. Each involuntary change reduces the effective tactical-option count by one from the remaining budget.",
        "stat_signature": "Share of substitutions classified as involuntary (injury or protocol); correlation of forced-sub count with post-65-minute tactical sub rate; residual tactical sub availability (budget minus forced) at the point of the first tactical need.",
        "mechanism": "A finite five-sub budget is shared across injury-response and tactical purposes. Forced changes are unscheduled and often early, consuming a unit of budget before the match state has resolved enough to make optimal tactical use of the slot. The expected value of the remaining budget falls with each unplanned use.",
        "conditions": "Risk is highest in physically demanding matches — congested fixtures, high-sprint-volume encounters, or matches at altitude — where soft-tissue and contact injury rates are elevated. Also elevated after international windows when players return with residual fitness deficits.",
        "magnitude": "Teams averaging more than 1.5 involuntary substitutions per match complete their intended tactical plan (three or more tactical changes to shape game state) in only 55-65 % of matches, versus 80-90 % for teams with fewer than 0.5 forced changes per match.",
        "links": ["substitution_window_budgeting", "early_substitution_information_cost", "extra_time_stamina_reserve", "concussion_substitution_contingency"],
    },
    {
        "slug": "energy_pressing_intensity_budget",
        "title": "Pressing-Intensity Energy Budget",
        "summary": "A squad carries a finite collective stamina reserve for high-intensity pressing. Deploying a full-throttle press from kickoff burns this reserve at a rate that produces a measurable second-half PPDA deterioration. Teams that modulate press intensity across the match preserve collective stamina for decisive late-match pressing exchanges.",
        "stat_signature": "PPDA (passes allowed per defensive action) split by 15-minute segments; pressures per defensive action first-half versus second-half; change in pressing success rate (ball recovery within 5 seconds) from minutes 0-30 to 60-90.",
        "mechanism": "Each sprint and deceleration required for a press action depletes type-II muscle-fibre glycogen. When collective pressing is sustained maximally for 90 minutes, the squad enters the final quarter with enough residual depletion that the coordinated press shape cannot be maintained, raising effective PPDA and exposing deeper blocks.",
        "conditions": "Manifests most clearly in teams with a tactically prescribed high-press identity playing in summer heat or at altitude, and in the second match of a back-to-back where pre-match fatigue advances the onset of press degradation.",
        "magnitude": "PPDA in minutes 75-90 is typically 20-30 % worse than in minutes 0-15 for sustained-press teams; the differential narrows to 10-15 % for teams that modulate press triggers and allow selective lower-intensity phases in the middle third of the match.",
        "links": ["tempo_energy_conservation", "pressing_trigger_selectivity", "second_half_kitchen_sink_timing", "fresh_legs_timing_curve"],
    },
    {
        "slug": "tempo_energy_conservation",
        "title": "Tempo-Energy Conservation",
        "summary": "Deliberately slowing build-up pace when ahead conserves collective energy by reducing the high-intensity running requirement for both attackers and supporting midfielders. Shorter, lateral possession sequences replace direct-play bursts, lowering sprint frequency without sacrificing possession.",
        "stat_signature": "Possession sequence speed (passes per second of possession) when leading versus when level; direct-play rate (passes forward as share of all passes) split by score state; average sprint count per ball-carrier in possession segments when leading by one goal after minute 60.",
        "mechanism": "A slower tempo reduces the number of supporting runs and recovery sprints triggered per possession cycle. Lateral and backward passes require less coordinated forward movement, reducing distance covered at high intensity per possession and extending the depletion timeline toward a more manageable end-of-match energy state.",
        "conditions": "Most effective when the opposing team has not yet committed to chasing the game with high pressing intensity. If the opposition commits bodies forward and disrupts the controlled tempo, the energy-conservation benefit can be offset by the defensive sprint load imposed.",
        "magnitude": "Teams leading by one goal in the final 30 minutes that shift to a lateral possession tempo average 18-25 % fewer sprints per possession sequence than their baseline, extending the effective high-intensity reserve into added time without a statistically significant increase in defensive xG conceded.",
        "links": ["energy_pressing_intensity_budget", "time_wasting_clock_management", "goalkeeper_distribution_tempo_lever", "defensive_lockdown_substitution"],
    },
    {
        "slug": "time_wasting_clock_management",
        "title": "Clock-Management Time Wasting",
        "summary": "Converting a lead into drained minutes through slow goal-kick restarts, delayed throw-ins, and drawn-out substitution procedures reduces effective playing time and limits the opponent's opportunities to equalise. The tactical legitimacy of deliberate time-wasting makes it a resource-allocation instrument within the laws of the game.",
        "stat_signature": "Average ball-out-of-play duration when leading in the final 15 minutes (seconds per stoppage); effective playing time when leading versus when level or trailing; ratio of time-wasting cautions to total cautions as a proxy for intent.",
        "mechanism": "Each second of dead-ball time when leading permanently removes an opportunity for the opponent to possess the ball and create chances. The total effective-playing-time reduction compounds across multiple restarts, converting a narrow lead into a structurally safer state without conceding defensive shape.",
        "conditions": "Most deployed and most effective when leading by one goal after minute 75, and when the opposing team requires multiple possession sequences to generate meaningful xG. Less impactful against set-piece-dominant opponents who exploit dead-ball situations regardless of playing time.",
        "magnitude": "Disciplined time-wasting reduces effective playing time in the final 15 minutes by 2-4 minutes on average, equivalent to removing 1-2 expected opposition possession sequences of sufficient quality to threaten goal.",
        "links": ["tempo_energy_conservation", "stoppage_time_resource_exposure", "goalkeeper_distribution_tempo_lever", "var_review_stoppage_rest"],
    },
    {
        "slug": "var_review_stoppage_rest",
        "title": "VAR-Review Stoppage Rest Harvest",
        "summary": "Video assistant referee reviews create unscheduled stoppages averaging 60-120 seconds of passive rest for outfield players. Teams with higher collective fatigue at the moment of a review gain disproportionate recovery benefit relative to a fresher opponent, and pressing intensity in the minutes immediately following a review is measurably elevated.",
        "stat_signature": "Average VAR review duration per match (seconds); pressing actions per defensive possession in the five-minute window post-review versus the five-minute window pre-review; sprint count delta per player in the first two minutes after restart.",
        "mechanism": "A two-minute enforced rest partially replenishes phosphocreatine stores and allows some neuromuscular recovery without full glycogen resynthesis. For a team entering the review with depleted sprinting reserves, the recovery benefit raises the immediate post-restart peak sprint speed measurably.",
        "conditions": "Recovery benefit is largest when the review occurs after the 65th minute of a congested-schedule match where cumulative fatigue is highest. Benefit is negligible in the first half or in matches following a 96+ hour rest period when players are near full readiness.",
        "magnitude": "Pressing intensity in the two minutes following a VAR review typically exceeds the five-minute pre-review average by 8-15 % in matches played in the third game of a congested block, compared to a neutral effect in rested fixtures.",
        "links": ["time_wasting_clock_management", "energy_pressing_intensity_budget", "stoppage_time_resource_exposure", "tempo_energy_conservation"],
    },
    {
        "slug": "stoppage_time_resource_exposure",
        "title": "Stoppage-Time Resource Exposure",
        "summary": "Extended referee-added time commits fully-depleted outfield energy and bodies to a prolonged final phase, elevating exposure to counter-attacking goals when pressing teams push men forward. Each additional minute added concentrates risk in the final passage, as the team chasing the match overcommits bodies beyond the halfway line.",
        "stat_signature": "Conceded xG per minute of added time for teams trailing; count of players committed beyond the halfway line in the final five minutes; counter-attack xG rate in added time versus regulation final-15-minutes rate.",
        "mechanism": "Teams trailing in added time deploy attackers and support players forward to maximise goal probability, reducing defensive cover behind the ball. Fatigue-impaired recovery runs after transitions create wide open counter-attack corridors exploited by teams defending with two central defenders and pace in behind.",
        "conditions": "Exposure is highest in matches with 5+ minutes of added time, when the trailing team has exhausted its substitution budget, and when the defending team has an attacker of pace available as a counter-attack outlet. Elevated after VAR interventions that extend dead-ball time and inflate the added-time allocation.",
        "magnitude": "Counter-attack xG per minute of added time is 2-3x the open-play xG-per-minute rate during regulation for teams playing more than three men forward; the risk compounds when defenders are at >85th-percentile cumulative fatigue load.",
        "links": ["time_wasting_clock_management", "chasing_game_attacker_overload", "var_review_stoppage_rest", "stoppage_time_resource_exposure"],
    },
    {
        "slug": "set_piece_specialist_deployment",
        "title": "Set-Piece Specialist Deployment",
        "summary": "Introducing a dead-ball delivery or aerial-target specialist as a finite substitution asset is timed relative to set-piece frequency to maximise the return on the budget spent. A specialist introduced when the match has 20+ minutes remaining across a set-piece-rich encounter generates more expected-goals return per change than one introduced in the 87th minute.",
        "stat_signature": "Substitution minute of specialist relative to subsequent set-piece count; post-introduction set-piece xG per delivery; difference in headed-chance creation rate in the 15 minutes before versus after introduction.",
        "mechanism": "A specialist delivery or target player changes the opponent's defensive set-piece scheme, forcing repositioning of blocking runners or aerial-duel match-ups, and directly increases the probability of high-xG headed attempts from near-post and back-post zones where the specialist's delivery or aerial quality is concentrated.",
        "conditions": "Return is highest in matches where the score is level or the trailing team has trailing set-piece frequency (corners plus fouls in dangerous areas) above 0.6 per minute. Diminishes sharply after the 85th minute when fewer set pieces remain in expectation.",
        "magnitude": "An aerial specialist introduced at minute 70 in a match with 8+ set pieces remaining generates an incremental 0.08-0.15 xG over the final 20 minutes relative to the starter replaced, a uplift visible even after adjusting for defensive repositioning.",
        "links": ["substitution_window_budgeting", "fresh_legs_timing_curve", "chasing_game_attacker_overload", "tactical_versus_injury_sub_allocation"],
    },
    {
        "slug": "early_substitution_information_cost",
        "title": "Early-Substitution Information Cost",
        "summary": "A substitution made before the 60th minute forfeits the option to observe how the match state evolves before committing the budget, a real option cost. Pre-60th-minute changes driven by injury or early under-performance consume a slot before the manager has seen 60-90 minutes of information about what the match actually requires.",
        "stat_signature": "Share of substitutions made before the 60th minute; correlation of pre-60 sub rate with residual tactical-sub availability in the 70-90 window; post-60-minute state-change rate (goals, red cards) as the information that would have been harvested by waiting.",
        "mechanism": "Match state is most resolved in the final third. A change made at minute 45-55 is made with incomplete information about how the opponent's fatigue, score dynamics, and tactical adjustments will develop. Each early change reduces the option set available when information is richest and marginal-sub value is highest.",
        "conditions": "Information cost is highest in tight, even matches where both score and tactical shape remain fluid; lower in one-sided matches where the outcome is already determined and the only remaining question is load management.",
        "magnitude": "Teams averaging more than one pre-60-minute substitution per match have a residual budget of fewer than two tactical subs in the 65-90 window in roughly 40-50 % of matches, versus fewer than 15 % for teams averaging fewer than 0.3 pre-60 forced changes.",
        "links": ["substitution_window_budgeting", "tactical_versus_injury_sub_allocation", "extra_time_stamina_reserve", "rotation_versus_continuity_within_match"],
    },
    {
        "slug": "chasing_game_attacker_overload",
        "title": "Chasing-Game Attacker Overload",
        "summary": "When trailing late, deploying all remaining substitutions on attacking profiles overloads the forward line to maximise goal probability at the explicit cost of defensive cover, accepting a higher probability of conceding an additional goal in exchange for a larger expected-goals output in the brief remaining window.",
        "stat_signature": "Post-substitution increase in attacking-third occupancy (players beyond midfield when team has possession); conceded counter-attack xG in the 10 minutes following the substitution block; shot-attempt rate in the final 15 minutes when all subs are attacking-oriented.",
        "mechanism": "Additional attacking bodies increase the passing network density in forward zones and generate more crosses, cutbacks, and combinations. The defensive cost is structural: fewer bodies recover behind the ball after transitions, widening counter-attack corridors. The tradeoff is rational if the goal probability gain exceeds the concession probability.",
        "conditions": "Rationally deployed when trailing by exactly one goal with 10-20 minutes remaining and when the margin is such that a single goal levels rather than requiring two. The calculus reverses when trailing by two or more, where the defensive exposure is high and the required two-goal swing is low probability regardless.",
        "magnitude": "Deploying three attacking substitutions when trailing by one after minute 70 increases shot attempt rate by 25-40 % and attacking xG by 0.10-0.18 in the remainder, while conceding counter-attack xG at 1.5-2.5x the match baseline rate.",
        "links": ["substitution_window_budgeting", "set_piece_specialist_deployment", "stoppage_time_resource_exposure", "second_half_kitchen_sink_timing"],
    },
    {
        "slug": "goalkeeper_distribution_tempo_lever",
        "title": "Goalkeeper Distribution Tempo Lever",
        "summary": "The restart speed of goal-kick and short-distribution sequences is a discretionary tempo-control instrument available to every team. A quick restart accelerates the game and reduces the opponent's defensive-shape reset time; a deliberate slow restart drains the clock and allows the team to reorganise its attacking shape.",
        "stat_signature": "Goal-kick-to-restart elapsed time split by score state (leading, level, trailing); direct long-ball rate from goalkeeper split by score state; average possession-sequence length initiated from keeper distribution when leading versus trailing.",
        "mechanism": "A slow goal-kick eliminates transition opportunities for the opponent and forces them to maintain defensive shape for longer, accelerating their collective fatigue. A quick restart exploits a disorganised defensive transition. The goalkeeper thus controls game rhythm at zero marginal energy cost to outfield players.",
        "conditions": "Slow-restart strategy is most effective when leading against a press-dependent opponent whose press requires coordinated triggering — a slow restart disrupts the trigger cue. Quick restart is most effective after a defensive goal-kick won in a high block, where the opposition is not yet set.",
        "magnitude": "Deliberately slow goal-kick restarts (average >20 seconds) when leading after minute 70 reduce effective playing time by 1.5-2.5 minutes per match, while quick-restart teams in the same game state reduce it by fewer than 0.5 minutes, a gap that compounds over multiple stoppages.",
        "links": ["tempo_energy_conservation", "time_wasting_clock_management", "var_review_stoppage_rest", "energy_pressing_intensity_budget"],
    },
    {
        "slug": "yellow_card_aggression_budget",
        "title": "Caution-Risk Aggression Budget",
        "summary": "A player carrying a yellow card represents a devalued tactical asset: subsequent aggressive challenges risk a red-card dismissal that reduces the team to ten men. The team rationally reduces high-tackle intensity from that player, redistributing aggressive defensive actions to uncautioned teammates as a form of caution-budget management.",
        "stat_signature": "Challenge intensity per 90 minutes before versus after a first caution (tackles attempted, foul rate per defensive duel); redistribution of tackle volume to uncautioned midfielders in the 30 minutes following a teammate's caution; rate of yellow-card accumulation leading to red-card dismissal.",
        "mechanism": "A second caution produces immediate numerical disadvantage and is irreversible. The rational response is to reduce the cautioned player's probability of triggering a second foul by reducing tackle frequency and replacing disciplined pressing with positional blocking, which is lower-risk but also lower-intensity defensively.",
        "conditions": "Most impactful when the cautioned player is a central defensive midfielder who anchors the team's defensive pressing system. The tactical cost is amplified when the caution occurs before the 60th minute, leaving a long period where the player must be managed; less impactful for a late first caution with few remaining minutes.",
        "magnitude": "Cautioned defensive midfielders reduce their tackle attempt rate by 25-35 % in the 30 minutes following a caution, and the team's effective pressing PPDA in that player's zone rises 10-20 % as uncautioned cover players absorb the defensive action volume at lower individual intensity.",
        "links": ["defensive_lockdown_substitution", "pressing_trigger_selectivity", "tactical_versus_injury_sub_allocation", "energy_pressing_intensity_budget"],
    },
    {
        "slug": "pressing_trigger_selectivity",
        "title": "Pressing-Trigger Selectivity",
        "summary": "A team that launches collective pressing only on high-recovery-value cues — back-pass to a goalkeeper, long ball to a weak foot, designated zone entry — spends stamina more efficiently than one pressing every build-up regardless of recovery probability, generating comparable ball-recovery counts at lower cumulative energy cost.",
        "stat_signature": "Share of opponent build-ups pressed (press rate); ball-recovery rate per press initiated (press success rate); energy expenditure per ball recovery proxied as high-intensity events per regain. Selective pressers target a 45-55 % press rate at >35 % success; indiscriminate pressers press 65-75 % at 20-28 % success.",
        "mechanism": "Selective triggering directs sprint energy toward possessions where the geometry — defensive coverage, opponent receiving position, ball speed — favours rapid recovery. Indiscriminate pressing expends the same energy on low-probability possessions, depleting type-II fibre reserves faster for equivalent ball-recovery counts.",
        "conditions": "Selectivity pays most when the opponent has one or two technically limited players who are high-value press targets, concentrating the high-intensity spend on recoverable possessions. Against technically uniform build-up units, the recovery rate differential between cued and uncued pressing shrinks.",
        "magnitude": "Selective pressing systems sustain their first-half press success rate through the 70th minute in 70-80 % of matches, versus 45-55 % for indiscriminate systems — indicating roughly 25 % better energy efficiency in translating sprint spend into ball recoveries.",
        "links": ["energy_pressing_intensity_budget", "yellow_card_aggression_budget", "tempo_energy_conservation", "fresh_legs_timing_curve"],
    },
    {
        "slug": "extra_time_stamina_reserve",
        "title": "Extra-Time Stamina Reserve",
        "summary": "In knockout formats, teams anticipating extra time preserve substitution budget and moderate energy expenditure through the final 15 minutes of regulation to maintain a functioning roster and sufficient stamina reserve for 30 additional minutes of depleted-state play.",
        "stat_signature": "Substitutions retained at 90 minutes in matches going to extra time; cramp and withdrawal rate per extra-time period (first versus second 15 minutes); high-intensity distance per minute in extra time relative to the 75-90-minute regulation segment.",
        "mechanism": "Spending all five substitutions before 90 minutes leaves no option to counter late-match injuries or fatigue in extra time. Moderating intensity in the final regulation minutes preserves glycogen and PCr for the extra-time period, maintaining sprint capacity above the functional threshold required for defensive coherence.",
        "conditions": "Reserve strategy is rational only when the 90-minute score makes extra time a plausible outcome — level scores in knockout ties from the 60th minute onward. Over-conserving when a win is achievable in regulation sacrifices win probability in exchange for a contingency that may not arise.",
        "magnitude": "Teams retaining one or more substitutions at 90 minutes complete extra time with 20-25 % fewer cramp-related substitutions and sustain sprint counts 12-18 % higher in the second extra-time period relative to teams that exhausted their budget before minute 90.",
        "links": ["substitution_window_budgeting", "tactical_versus_injury_sub_allocation", "concussion_substitution_contingency", "stoppage_time_resource_exposure"],
    },
    {
        "slug": "concussion_substitution_contingency",
        "title": "Concussion-Substitution Contingency",
        "summary": "The additional permanent-change allotment introduced for head-injury protocol activations creates a supplementary budget unit, meaning a concussion sub does not consume a standard tactical slot. Understanding this contingency avoids over-conservative budgeting that preserves a standard slot unnecessarily against the concussion scenario.",
        "stat_signature": "Rate of concussion-sub activation per 90 minutes across the match distribution; share of teams correctly reserving zero standard-sub budget for concussion contingency versus those holding one in reserve unnecessarily; net change-budget effect when concussion sub is activated.",
        "mechanism": "Concussion protocols allow an additional change above the standard five-sub limit when a player requires head-injury assessment. Treating this as a standard budget deduction leads to under-utilisation of the tactical budget in the majority of matches where no concussion sub is triggered, representing an opportunity cost.",
        "conditions": "Relevant in matches with elevated contact frequency — high-challenge, aerial-duel-intensive encounters, and matches where multiple set-piece aerial contests create head-collision exposure. The activation rate is low enough (roughly 0.05-0.10 per match) that standard-budget conservation for this contingency is rarely optimal.",
        "magnitude": "Teams that correctly treat the concussion allotment as a separate budget complete their tactical substitution plan (three or more tactical changes) in 10-15 % more matches than teams that reserve one standard slot against the concussion scenario, a directly attributable gain in tactical flexibility.",
        "links": ["tactical_versus_injury_sub_allocation", "extra_time_stamina_reserve", "substitution_window_budgeting", "early_substitution_information_cost"],
    },
]
