"""MLB RosterConstruction spec — person-free, dense, descriptive."""
from __future__ import annotations

SPORT = "MLB"
FAMILY = "RosterConstruction"

CONCEPTS = [
    {
        "slug": "bullpen_leverage_tiering",
        "title": "Bullpen Leverage-Tier Construction",
        "summary": "Relief arms stratify into high (pLI >1.5), medium, and long-inning tiers; the ERA/FIP spread between tier-1 and tier-3 arms summarizes functional bullpen depth.",
        "stat_signature": "Average pLI per arm per tier; ERA gap between top and long-relief tier (shallow if >1.5 runs); share of leverage-index-above-1.0 appearances absorbed by non-tier-1 arms.",
        "mechanism": "Managers allocate best arms to highest-stakes leverage contexts; thin top-tier forces cascade of lower-quality arms into close games, compressing leverage distribution and inflating late-inning run-expectancy.",
        "conditions": "Most consequential in one-run games and high-walk-rate opponents that extend appearances and deplete primary arms faster, forcing early tier escalation.",
        "magnitude": "Elite staffs compress ERA across tiers to under 0.8 runs; structurally shallow bullpens show gaps above 1.5 runs, correlating with two to four additional blown-lead games per season.",
        "links": ["closer_role_definition", "high_leverage_setup_depth", "bullpen_workload_recovery_buffer", "bullpen_handedness_balance"],
    },
    {
        "slug": "closer_role_definition",
        "title": "Defined-Closer Versus Committee Construction",
        "summary": "Concentration of save chances in one arm versus a rotation affects blown-save frequency and managerial sequencing complexity; the single-finisher share of save opportunities is the key ratio.",
        "stat_signature": "Single-arm share of save chances (defined closer >60 %, committee <45 %); count of arms with two or more saves; blown-save rate in ninth-inning high-leverage appearances.",
        "mechanism": "Role clarity and reps in save situations build rhythm-dependent performance for a defined closer; committee approaches demand sequencing precision and are sensitive to individual off-day accumulation.",
        "conditions": "Defined closer matters most in tight divisional races where single blown saves have outsized standings impact; committees become viable when no arm sustains command across multi-inning stints.",
        "magnitude": "Defined-closer staffs historically show blown-save rates three to five percentage points lower than deep-committee staffs in equivalent save situations.",
        "links": ["bullpen_leverage_tiering", "high_leverage_setup_depth", "bullpen_workload_recovery_buffer"],
    },
    {
        "slug": "high_leverage_setup_depth",
        "title": "High-Leverage Setup-Arm Depth",
        "summary": "The count of relievers capable of handling seventh-and-eighth inning leverage with sub-league ERA, particularly in inherited-runner situations, defines true bridge depth.",
        "stat_signature": "Arms with LI >1.2 and ERA below league-reliever median (~4.0); share of seventh-and-eighth innings covered without a below-0.9-pLI arm; WHIP in inherited-runner situations.",
        "mechanism": "Starter exits near pitch-count limits require handoff to setup arms; thin setup depth overworks the closer or exposes leads to low-quality outings when base traffic is already present.",
        "conditions": "Depth strain appears acutely in series without off-days when primary setup arms accumulate back-to-back appearances and a third arm must absorb seventh-inning work.",
        "magnitude": "Staffs with two credible setup arms hold late-inning leads at roughly five percentage points higher rates than those relying on a single bridge arm.",
        "links": ["bullpen_leverage_tiering", "closer_role_definition", "bullpen_workload_recovery_buffer", "long_relief_swingman_slot"],
    },
    {
        "slug": "long_relief_swingman_slot",
        "title": "Long-Relief and Swingman Slot",
        "summary": "A multi-inning bulk arm averaging more than 1.0 innings per appearance absorbs early-exit innings and protects the leverage tier from overuse on subsequent nights.",
        "stat_signature": "Count of relievers averaging >1.0 innings per appearance; share of post-early-exit innings absorbed by the long-relief slot; K/9 and HR/9 as bulk-inning quality proxies.",
        "mechanism": "Starter exits before the fifth inning cascade directly to long relief; without a dedicated multi-inning arm, managers burn setup arms in bulk roles, depleting leverage coverage for the next series.",
        "conditions": "Importance is elevated when the rotation contains injury-prone arms, includes opener deployment, or when off-day scarcity creates no rest buffer for the taxed bullpen.",
        "magnitude": "An effective swingman absorbs two to four innings per use, reducing setup-arm appearances by one to two per week and extending closer freshness proportionally.",
        "links": ["bullpen_leverage_tiering", "high_leverage_setup_depth", "opener_bulk_construction", "rotation_depth_six_starter"],
    },
    {
        "slug": "bullpen_handedness_balance",
        "title": "Bullpen Handedness Balance",
        "summary": "Under the three-batter minimum, left-right composition must embed platoon advantages across multi-batter segments; relievers with tight same-handed versus opposite-handed wOBA splits carry broader usage value.",
        "stat_signature": "Count of left-handed arms; each reliever's wOBA split between same-handed and opposite-handed matchups (neutral if gap <0.030, significant if >0.070); platoon-unfavorable matchup share in high-leverage appearances.",
        "mechanism": "The three-batter minimum removes single-batter LOOGY deployment; one-dimensional arms relying on same-hand dominance become contextually limited against lineups that alternate handedness deliberately.",
        "conditions": "Balance most valuable against lineups that deliberately alternate handedness to force platoon mismatches onto single-dimensional relievers mid-sequence.",
        "magnitude": "An arm with wOBA splits above 0.070 faces meaningful performance drag in roughly 40 to 50 % of high-leverage appearances where platoon alignment is unfavorable.",
        "links": ["bullpen_leverage_tiering", "bench_platoon_construction", "high_leverage_setup_depth"],
    },
    {
        "slug": "rotation_depth_six_starter",
        "title": "Starting-Rotation Depth Beyond Five",
        "summary": "Seasonal attrition guarantees a sixth starter accumulates meaningful innings; the FIP or ERA gap between the fifth and sixth options determines run-prevention degradation during injury-replacement stretches.",
        "stat_signature": "Count of starters with credible bulk projections (qualifying-pace IP); FIP/ERA differential between fifth and sixth options; share of season innings absorbed by depth starters.",
        "mechanism": "Each starter misses two to four weeks per season on average; without a credible sixth arm, organizations must overwork the bullpen, deploy an unqualified depth option, or shuttle the swingman — each path raises run-allowance.",
        "conditions": "Depth stress peaks in July through September when injury accumulation is highest and contenders are reluctant to disrupt service-time timelines for younger reserve arms.",
        "magnitude": "A sixth-starter quality gap of two-plus ERA runs above the fifth arm typically contributes three to six additional losses in years with significant rotation injury exposure.",
        "links": ["rotation_innings_workload_shape", "long_relief_swingman_slot", "opener_bulk_construction", "depth_chart_optionability"],
    },
    {
        "slug": "opener_bulk_construction",
        "title": "Opener-and-Bulk Staff Construction",
        "summary": "A one-to-two inning opener followed by a bulk arm restructures conventional starter use; the share of games scripted with this pattern and the bulk arm's innings-per-game measure adoption depth.",
        "stat_signature": "Share of starts using an opener (deliberate strategy threshold: >15 %); bulk arm innings per opener game (effective bulk: 4-5 IP); opponent top-of-order OPS in opener-scripted games versus conventional starts.",
        "mechanism": "Openers disrupt opponent lineup-card preparation for the top of the order; the bulk arm then faces the lineup a second time under reduced pressure from its most dangerous bats having already batted once.",
        "conditions": "Most effective against offenses with strong top-of-order hitters who benefit from conventional first-inning predictability; requires a bullpen with sufficient depth to cover lighter opener games without taxing setup arms.",
        "magnitude": "Opponent first-inning run scoring suppressed by roughly 0.1 to 0.2 runs per opener-scripted game; effect diminishes if the bulk arm faces the order a third time without a quality third-time-through penalty managed.",
        "links": ["long_relief_swingman_slot", "rotation_depth_six_starter", "bullpen_leverage_tiering"],
    },
    {
        "slug": "bench_platoon_construction",
        "title": "Bench Platoon-Bat Construction",
        "summary": "Reserve hitters assembled to exploit handedness splits systematically route bench plate appearances to favorable matchups, accumulating wOBA gains that compound across a full season.",
        "stat_signature": "Count of bench bats with wOBA against opposite-handed pitching above team-starter median; platoon PA share (target >55 % of bench PAs in favorable matchups); wOBA gain per bench appearance against alternatives.",
        "mechanism": "Handedness creates consistent contact-quality and launch-angle asymmetries; routing bench appearances toward favorable splits each game accumulates marginal wOBA gains that add up over 162 games of bench deployment.",
        "conditions": "Payoff highest in sixth-through-ninth innings against bullpens deploying right-left-right sequencing; constrained when pitcher-slot count leaves fewer than three bench bats available for late-game deployment.",
        "magnitude": "Deliberate platoon benches generate 0.020 to 0.035 additional wOBA per bench plate appearance, equivalent to two to four additional runs over a full season of optimized bench usage.",
        "links": ["bullpen_handedness_balance", "utility_versatility_construction", "roster_slot_pitcher_hitter_balance", "lineup_depth_top_to_bottom"],
    },
    {
        "slug": "utility_versatility_construction",
        "title": "Multi-Position Utility Construction",
        "summary": "Position players credibly covering four or more defensive spots allow a roster to carry additional pitching without sacrificing in-game flexibility; average distinct positions per bench bat summarizes this structural asset.",
        "stat_signature": "Average distinct defensive positions per bench player (super-utility target: >3.0); fielding-grade range at each covered position; lineup permutations available without roster substitution as flexibility proxy.",
        "mechanism": "Each multi-position player substitutes for a dedicated backup, freeing a roster slot for an arm or specialist; the compounding benefit survives simultaneous injuries at dissimilar positions without leaving any spot uncovered.",
        "conditions": "Value highest on small benches (three to four position players) and during injury-compressed stretches when two or more starters miss the same week across dissimilar positions.",
        "magnitude": "A super-utility bat covering five or more positions effectively replaces two dedicated backups, freeing one slot worth roughly 0.5 to 1.0 marginal wins of roster-upgrade potential.",
        "links": ["roster_slot_pitcher_hitter_balance", "bench_platoon_construction", "depth_chart_optionability", "catcher_depth_construction"],
    },
    {
        "slug": "catcher_depth_construction",
        "title": "Catcher-Depth and Tandem Construction",
        "summary": "Catcher workload degrades pitch-framing skill nonlinearly after 100 games; a primary-to-backup tandem with credible framing quality in the second slot preserves full-season run-prevention value.",
        "stat_signature": "Primary-to-backup game split (sustainable primary load: 110-120 games); pitch-framing runs-above-average for both catchers; backup pop-time and caught-stealing percentage; framing-grade drop to backup.",
        "mechanism": "Framing skill shifts run-allowance by three to six runs per 1,000 pitches; fatigue-driven degradation in the final 40 games of an overloaded primary erases a measurable fraction of the position's seasonal framing value.",
        "conditions": "Most critical for groundball-heavy rotations generating high called-strike dependence at the zone edge; diminished when the primary is an elite framer who sustains skill across full workloads.",
        "magnitude": "Deploying a competent tandem preserves two to four framing runs compared with an overloaded primary degrading late-season, equivalent to roughly 0.2 to 0.4 marginal wins.",
        "links": ["roster_slot_pitcher_hitter_balance", "utility_versatility_construction", "groundball_flyball_staff_shape"],
    },
    {
        "slug": "roster_slot_pitcher_hitter_balance",
        "title": "Pitcher-to-Position-Player Slot Balance",
        "summary": "The active-roster split between pitchers and position players directly sets bench size and constrains in-game substitution; the 12-to-13 pitcher equilibrium balances bullpen coverage against bench flexibility.",
        "stat_signature": "Pitcher slot count (12 or 13 versus 11); resulting bench size (3-4 bats versus 5); late-game substitution count per game as utilization proxy; pinch-hit opportunity rate per bench player.",
        "mechanism": "Each additional pitcher slot consumed reduces the bench by one, compressing the pool for platoon, pinch-run, and defensive replacements; a thin bullpen instead forces longer outings that accelerate fatigue accumulation.",
        "conditions": "Thirteen-pitcher rosters defensible during dense no-off-day schedules; eleven-pitcher configurations feasible only with a deep, innings-capable rotation reducing daily bullpen dependence.",
        "magnitude": "Moving from 12 to 13 pitchers reduces pinch-hit opportunities by roughly one per two games and compresses double-switch flexibility, directly limiting late-game lineup manipulation.",
        "links": ["utility_versatility_construction", "bench_platoon_construction", "bullpen_leverage_tiering", "depth_chart_optionability"],
    },
    {
        "slug": "groundball_flyball_staff_shape",
        "title": "Groundball-Flyball Staff Composition",
        "summary": "The batted-ball tendency of the pitching staff interacts with home-park dimensions and defensive range; alignment of staff groundball rate with park and defensive profile compounds run-prevention advantages.",
        "stat_signature": "Staff-wide groundball rate (league average ~44 %; groundball staff >48 %); park home-run factor as context anchor; team middle-infield Outs Above Average as groundball-conversion proxy.",
        "mechanism": "Groundball staffs suppress home runs but generate infield-range dependence; flyball staffs trade range reliance for outfield-gap and home-run sensitivity; park-and-defense alignment determines which batted-ball profile converts outs most efficiently.",
        "conditions": "Alignment matters most in pitcher-friendly parks where run-prevention gaps between well-matched and mismatched staffs are amplified; less differentiated in neutral parks.",
        "magnitude": "A groundball staff well-matched to spacious park dimensions and above-average middle-infield range gains three to five Defensive Runs Saved above what the same staff yields in a mismatched environment.",
        "links": ["rotation_innings_workload_shape", "catcher_depth_construction", "bullpen_leverage_tiering"],
    },
    {
        "slug": "depth_chart_optionability",
        "title": "Depth-Chart Optionability and Shuttle Slots",
        "summary": "Optionable players on the active roster allow frequent arm-and-bat cycling between active and reserve lists, enabling fresh relievers for consecutive high-leverage series without permanent roster displacement.",
        "stat_signature": "Count of optionable players on the 26-man roster; average roster transactions per week (shuttle frequency); quality of depth options on reserve roster measured by minor-league ERA or OPS context.",
        "mechanism": "Options allow cycling fatigued relievers to the reserve level and calling up rested arms without waiver exposure; squads with non-optionable veterans at multiple spots must absorb fatigue degradation or expose valuable players to claims.",
        "conditions": "Optionability leverage peaks during summer schedules without off-days that tax the bullpen; also critical when a starter's injury forces two-week stretches of extra relief appearances.",
        "magnitude": "Rosters with five or more optionable players maintain reliever-freshness profiles averaging 0.3 to 0.5 fewer consecutive-day appearances per arm versus rigidly non-optionable rosters over comparable schedule blocks.",
        "links": ["roster_slot_pitcher_hitter_balance", "rotation_depth_six_starter", "bullpen_workload_recovery_buffer"],
    },
    {
        "slug": "bullpen_workload_recovery_buffer",
        "title": "Bullpen Workload-Recovery Buffer",
        "summary": "A relief corps' capacity to absorb back-to-back high-leverage days without performance degradation depends on roster depth and recent-appearance accumulation; arms available on zero days rest define the recovery floor.",
        "stat_signature": "Count of relievers available on zero days rest (sustainable floor: 3-4 arms); share of appearances where a reliever worked two of the prior three days; ERA in back-to-back appearance sets versus single-outing stretches.",
        "mechanism": "Velocity and command metrics decline measurably after back-to-back outings; shallow rosters return the same arms to high-leverage spots without recovery intervals, compounding run-expectancy increases across multi-game series.",
        "conditions": "Buffer most relevant in the stretch run when roster manipulation is limited, and against high-on-base offenses that extend appearances past one inning and consume extra pitches per outing.",
        "magnitude": "Relievers making back-to-back appearances show ERA inflation of 0.5 to 1.0 runs; three-appearances-in-four-days patterns degrade performance by 0.8 to 1.5 additional ERA runs across reliever populations.",
        "links": ["bullpen_leverage_tiering", "depth_chart_optionability", "rotation_innings_workload_shape", "long_relief_swingman_slot"],
    },
    {
        "slug": "lineup_depth_top_to_bottom",
        "title": "Lineup Depth Top-to-Bottom",
        "summary": "Offensive production distribution through the batting order determines how reliably a lineup generates multi-inning run support; the OPS gap between the top and bottom thirds and the count of below-replacement bats measure structural depth.",
        "stat_signature": "Projected OPS spread between top-three and bottom-three lineup slots (shallow if gap >0.150); count of lineup spots projecting below replacement-level wOBA (~0.290); runs-created contribution by lineup third.",
        "mechanism": "Bottom-order production creates additional baserunner platforms for the top of the order's second cycle; lineups with two or more black-hole bats at the seven-through-nine slots reduce scoring opportunities for the entire rotation through the order.",
        "conditions": "Depth most critical against deep pitching rotations that induce lineup-wide whiff rates; also salient in low-scoring parks where margins between offensive-capable and black-hole lineups are amplified.",
        "magnitude": "A lineup with two sub-replacement bats in the bottom third generates roughly five to eight fewer runs per season through reduced plate-appearance productivity and sequencing quality compared with a replacement-or-better bottom third.",
        "links": ["bench_platoon_construction", "power_speed_lineup_balance", "designated_hitter_slot_usage"],
    },
    {
        "slug": "power_speed_lineup_balance",
        "title": "Power-and-Speed Lineup Balance",
        "summary": "The blend of slugging and baserunning threats distributes defensive burden across a lineup; a team with isolated power and stolen-base attempts from multiple spots forces pitchers to vary sequencing and prevents shift-stacking.",
        "stat_signature": "Team ISO (isolated power; diverse if >0.165); stolen-base attempt rate per game (active if >0.8); count of lineup spots contributing meaningfully to both dimensions (target: 3 or more).",
        "mechanism": "Lineups with both power and speed force pitchers to pitch from the stretch more often and prevent fielding alignments optimized for one batted-ball profile; the combination creates sequencing complexity that raises pitch-count-per-inning.",
        "conditions": "Balance most impactful against shifts and specialized defensive alignments that try to neutralize pull-heavy power; speed adds orthogonal value when pitchers lead from the stretch under base-threat pressure.",
        "magnitude": "Teams combining above-average ISO with an active stolen-base game score roughly 0.2 to 0.4 additional runs per game versus lineups of similar aggregate wOBA that concentrate entirely on one dimension.",
        "links": ["lineup_depth_top_to_bottom", "bench_pinch_run_speed_slot", "designated_hitter_slot_usage"],
    },
    {
        "slug": "designated_hitter_slot_usage",
        "title": "Designated-Hitter Slot Construction",
        "summary": "Whether the DH slot is a fixed-bat producer or a rest-and-matchup rotation tool shapes aggregate slot output and the lineup flexibility available to the manager through a full series.",
        "stat_signature": "Share of games with a dedicated DH occupant versus rotating cast (fixed if >70 % same player); slot aggregate wOBA and OPS; platoon-matchup rate when the slot rotates (favorable matchup share target >60 %).",
        "mechanism": "A fixed elite bat maximizes production but forgoes rest opportunities for aging position players; a rotating slot sacrifices peak output for cumulative lineup freshness and matchup exploitation across a three-to-four game series.",
        "conditions": "Rotation strategy most valuable in series against pitching staffs with pronounced platoon splits; fixed assignment most defensible when no alternative bat reaches slot-caliber production.",
        "magnitude": "A well-managed rotating DH strategy adds roughly 0.015 to 0.025 wOBA per plate appearance through matchup selection, recovering one to two runs per series versus a fixed non-platoon assignment.",
        "links": ["bench_platoon_construction", "lineup_depth_top_to_bottom", "power_speed_lineup_balance"],
    },
    {
        "slug": "bench_pinch_run_speed_slot",
        "title": "Pinch-Run and Speed Bench Slot",
        "summary": "A dedicated late-game baserunning weapon in the top sprint-speed band converts singles to extra bases and stolen-base threats at a rate that justifies a roster slot when deployed in high-leverage late innings.",
        "stat_signature": "Count of reserves in top-15th-percentile sprint speed (>29 ft/s); stolen-base success rate when deployed; share of pinch-run appearances with leverage index above 1.0; extra-base-taken rate on batted balls.",
        "mechanism": "Baserunning value concentrates in high-leverage late-inning situations where an advance or stolen base has outsized win-probability impact; a specialist justifies its roster cost only when deployed in those specific spots rather than recycled into low-leverage innings.",
        "conditions": "Most effective in tie games or within one run in the seventh inning or later against catchers with below-average pop-time; also valuable in extra-inning formats with the automatic-runner rule.",
        "magnitude": "A well-deployed speed specialist adds two to four stolen-base equivalents per season (roughly one run each), with win-probability weight concentrated into approximately 15 to 25 targeted deployments.",
        "links": ["bench_platoon_construction", "power_speed_lineup_balance", "roster_slot_pitcher_hitter_balance"],
    },
    {
        "slug": "rotation_pitch_mix_diversity",
        "title": "Rotation Pitch-Profile Diversity",
        "summary": "Whether the starting staff presents varied primary-pitch types and arm-slot profiles across a series affects how quickly opposing lineups calibrate; repeated looks in consecutive games narrow the hitter adjustment gap.",
        "stat_signature": "Count of distinct primary-pitch families among starters (fastball-heavy, spin-heavy, sinker-ground, soft-contact cutter); share of arm-slot profiles repeated across a three-game series; opponent batting average on first pitch by starter sequence.",
        "mechanism": "Hitters recalibrate timing within a series after one look at a primary offering; a diverse rotation forces recalibration across multiple pitch shapes and release angles, maintaining the early-count advantage longer into each series.",
        "conditions": "Diversity payoff is largest early in a series before advanced scouting dominates individual preparation; diminishes in playoff rounds where opponents have extensive same-opponent video.",
        "magnitude": "Rotations with three or more distinct primary-pitch profiles in a four-to-five game rotation show opponent strikeout rates roughly 0.5 to 1.0 percentage points higher in games two and three of a series compared with pitch-profile-homogeneous rotations.",
        "links": ["rotation_depth_six_starter", "groundball_flyball_staff_shape", "rotation_innings_workload_shape"],
    },
]
