"""Person-free NBA RosterConstruction concept nodes — dense, sport-accurate, no player/team names."""
from __future__ import annotations

SPORT = "NBA"
FAMILY = "RosterConstruction"

CONCEPTS: list[dict] = [
    {"slug": "rotation_depth_eight_man", "title": "Eight-Man Rotation Compression",
     "summary": "Regular-season minutes compress into eight rotation players whose top-eight share routinely exceeds 80 percent, leaving the ninth slot and below with fewer than four minutes per game on average.",
     "stat_signature": "Top-eight minutes share above 80% of team total; ninth-slot average below 4 mpg; bench Gini coefficient above 0.62 signals high compression; starters average 33-36 mpg in compressed rotations.",
     "mechanism": "Coaching preference for reliability over development concentrates possessions in a proven core whose chemistry and scheme-fit are highest; playoff conditioning rationale accelerates minute compression from January onward.",
     "conditions": "Most pronounced on contenders mid-season through playoffs; injury absences temporarily open the ninth slot but compressing back within 3-5 games is the modal recovery pattern.",
     "magnitude": "Compressed rotations show 4-6 fewer distinct players per game log; bench scoring averages 8-12 ppg below non-compressed peers; rotational fatigue accumulates noticeably by game 65-70.",
     "links": ["rotation_depth_ten_plus", "starter_bench_minute_split", "injury_replacement_depth", "garbage_time_development_slots"]},

    {"slug": "rotation_depth_ten_plus", "title": "Ten-Plus Player Depth Distribution",
     "summary": "A flattened minutes curve where players nine through eleven each log meaningful run, often driven by positional matchup needs or deliberate load management, measurable by minutes-share Gini and tenth-player game-frequency.",
     "stat_signature": "Minutes-share Gini below 0.52 across the rotation; tenth player exceeds 15 minutes in at least 30% of games; ninth-through-eleventh slots combine for 25-35 mpg; bench unit PPP within 3 pp of the starting-unit.",
     "mechanism": "Flatter distributions arise from positional versatility (multiple wings cover identical roles), genuine two-way depth, or scheduled rest programs that elevate next-man-up players into rotation-caliber minutes.",
     "conditions": "Prevalent on teams with injury histories, an aggressive load-management program, or a coaching style that values matchup-specific specialists over a fixed hierarchy.",
     "magnitude": "Tenth-player usage in playoff-eligible teams averages 9-13 mpg; teams with Gini below 0.50 show roster-depth ratings 5-8 percentile points above the league median in the final quarter of the regular season.",
     "links": ["rotation_depth_eight_man", "matchup_dependent_roster_flex", "two_way_fringe_slots", "veteran_youth_age_balance"]},

    {"slug": "starter_bench_minute_split", "title": "Starter-to-Bench Minute Allocation",
     "summary": "The share of total team minutes absorbed by the starting five versus reserves determines how much of the offensive and defensive identity is carried by bench units, with the league band for bench share running roughly 33-42 percent.",
     "stat_signature": "Bench minutes share between 33-42% of team total; starters averaging above 34 mpg signal a low-bench-trust roster; bench-unit net rating gap to starting-unit net rating narrows below 4 pp on depth-rich rosters.",
     "mechanism": "Starters establish scheme identity and handle the highest-leverage possessions; bench share determines whether reserves must match quality or merely protect leads, shaping substitution patterns and second-quarter momentum.",
     "conditions": "Bench share rises when starters have injury histories or when coaching philosophy emphasises depth; it compresses in playoff rotations where coaching trust thresholds become more conservative.",
     "magnitude": "A 5 pp shift in bench-minute share corresponds to roughly 1.5-2.5 net-rating points when bench-unit quality is below average; above-average bench units narrow the gap to under 0.5 points per 100 possessions.",
     "links": ["rotation_depth_eight_man", "rotation_depth_ten_plus", "playmaking_distribution_balance", "closing_lineup_construction"]},

    {"slug": "shooting_spacing_inventory", "title": "Floor-Spacing Shooter Inventory",
     "summary": "The count of credible catch-and-shoot threats determines how many four-spacer or five-out lineups a roster can sustain, with the league's top-tier spacing rosters carrying five or more rotation players above 36 percent on catch-and-shoot threes.",
     "stat_signature": "Rotation players above 36% catch-and-shoot three rate: elite roster carries 5+, average 3-4, spacing-poor 1-2; share of lineups with four-plus spacers above 55% marks top-quartile spacing depth; above-break three rate per 100 possessions 18-25.",
     "mechanism": "Each additional credible spacer widens driving lanes and forces the defense to defend a larger perimeter area, increasing the binary-choice pressure on help defenders and lifting teammate rim-attempt quality.",
     "conditions": "Spacing inventory is most consequential against drop-coverage schemes and zone defenses where contested mid-range shots are the defender's preferred concession; less differentiating against switch-everything schemes.",
     "magnitude": "Moving from two credible spacers to four in a lineup generates 6-10 additional open-three attempts per 100 possessions for the creation players on the floor; corner-three frequency rises 3-5 pp per additional spacer.",
     "links": ["two_big_versus_five_out_construction", "rim_protection_depth", "switchability_inventory", "lineup_combination_count"]},

    {"slug": "ball_handling_creation_count", "title": "On-Ball Creation Redundancy",
     "summary": "The number of independent shot-creators distributed across units determines whether the roster can maintain offensive quality when one creator rests, measured by usage above 24 percent and the share of minutes with at least two such creators on the floor.",
     "stat_signature": "Rotation players with usage above 24%: star-heavy roster 1-2, balanced 3-4; share of minutes with two-plus high-usage players: top-quartile above 45%; creation-depleted minutes (zero above-24% player on floor) above 20% signals a structural gap.",
     "mechanism": "A single creator's rest period or foul trouble creates a possession-quality cliff if no secondary creation alternative exists; redundant creation ensures the offense sustains half-court PPP across all lineup combinations the coach can deploy.",
     "conditions": "Creation redundancy is most valuable in playoff series where opponent scouting load-bears on the primary creator; less critical in pace-driven teams where transition scoring partially substitutes for half-court creation.",
     "magnitude": "Teams with zero secondary creation (all minutes below 20% usage when the primary rests) post bench-unit offensive ratings 8-14 pp below league average; redundant-creation rosters narrow that gap to 3-6 pp.",
     "links": ["playmaking_distribution_balance", "starter_bench_minute_split", "matchup_dependent_roster_flex", "rotation_depth_eight_man"]},

    {"slug": "rim_protection_depth", "title": "Rim-Protection Slot Depth",
     "summary": "The minutes a roster can cover with credible interior deterrence, measured by block-rate threshold and the share of possessions lacking a deterring anchor near the rim.",
     "stat_signature": "Rotation bigs above 3% block rate: elite 2-3, average 1, none marks a deterrence gap; share of minutes with no rim-protecting player on the floor above 30% in a non-five-out context signals exposure; opponent rim-FGA% rises 6-9 pp in anchorless lineups.",
     "mechanism": "A rim-protecting anchor alters opponent shot-selection before contact by raising the perceived cost of drives, suppressing rim-attempt frequency and redirecting the offense toward less-efficient mid-range attempts.",
     "conditions": "Rim protection depth is most consequential against high-drive-frequency offenses and pick-and-roll heavy attacks; less determinative when opponents rely primarily on perimeter shooting and space-and-drive from the wing.",
     "magnitude": "Absence of a rim anchor elevates opponent rim-FGA% by 6-9 pp and overall defensive rating by 3-5 pp in the affected minutes; top-block-rate bigs suppress rim-attempt frequency by 4-7 attempts per 100 possessions.",
     "links": ["switchability_inventory", "center_rotation_construction", "two_big_versus_five_out_construction", "positional_size_balance"]},

    {"slug": "switchability_inventory", "title": "Cross-Position Switch Inventory",
     "summary": "The count of defenders who can guard three or more positions without creating an exploitable mismatch, measured by matchup spread and the largest all-switch lineup the roster can field.",
     "stat_signature": "Rotation players with credible three-position matchup spread: elite 5-6, average 3-4; maximal all-switch lineup count available: elite 3-5 distinct five-man units, limited rosters 0-1; switch-eligible lineups deployed above 40% of defensive possessions on top-switch teams.",
     "mechanism": "Switching eliminates the screen-navigation delay that allows offense to generate open-catch-and-shoot looks; a roster with broad switchability can deny the pick-and-roll's primary advantage without hedging or dropping, maintaining defensive integrity on multiple ball-screen layers.",
     "conditions": "Switch inventory is most valuable against high-ball-screen-frequency offenses that probe mismatches systematically; less critical against post-entry or isolation offenses that do not seek the screen-generated mismatch.",
     "magnitude": "Teams with six switch-eligible rotation players hold opponents to 0.04-0.08 lower PPP on pick-and-roll ball-handler possessions relative to non-switch-capable rosters; mismatch-hunting sequences are resolved 2-4 possessions faster.",
     "links": ["shooting_spacing_inventory", "rim_protection_depth", "center_rotation_construction", "perimeter_defense_depth"]},

    {"slug": "center_rotation_construction", "title": "Center-Slot Construction and Backup Pairing",
     "summary": "How the five-slot is staffed across drop, switch, and small-ball looks determines defensive versatility and offensive mismatch potential, measured by distinct center profiles rostered and the non-overlap between primary and backup big minutes.",
     "stat_signature": "Distinct functional center profiles (drop-anchor, switch-capable, small-ball-eligible): elite 2-3, average 1-2; non-overlapping primary-to-backup minutes above 70% ensures coverage without overlap tax; small-ball big eligibility rate: count able to play the four in lineups with a traditional five.",
     "mechanism": "A single center profile limits tactical flexibility when opponents exploit the drop-anchor in pick-and-roll or post the non-switching big in switch schemes; a complementary backup allows the coaching staff to shift scheme mid-game without sacrificing rim protection or spacing.",
     "conditions": "Profile depth matters most in playoff series where opponents gameplan specifically for the primary big's defensive limitations; in regular-season play, a dominant primary big can absorb most lineup challenges.",
     "magnitude": "Teams with two distinct center profiles show 4-6 pp lower opponent PPP on pick-and-roll sequences in playoff contexts; the backup-big net rating gap to the primary narrows by 3-5 pp when the roles are complementary rather than identical.",
     "links": ["rim_protection_depth", "two_big_versus_five_out_construction", "switchability_inventory", "rotation_depth_eight_man"]},

    {"slug": "two_way_fringe_slots", "title": "Two-Way and Fringe-Roster Slot Allocation",
     "summary": "Two-way contracts and end-of-bench roster spots function as developmental pipelines and emergency buffers, absorbing spot minutes during injury gaps with players whose upside can materially affect outcomes in extended absences.",
     "stat_signature": "Two-way contracts used: 0-2 per roster (league maximum 2); spot-minutes absorbed by sub-rotation players in injury-replacement context: range 8-18 mpg per absence; two-way-to-standard conversion rate league-wide approximately 25-35% within two seasons.",
     "mechanism": "Fringe slots exist in a cost-floor tier that allows teams near the cap to carry developmental talent without financial exposure; the developmental pipeline value compounds over multi-year horizons even if no immediate on-court contribution materialises.",
     "conditions": "Fringe slots gain near-term importance when the rotation sustains two or more simultaneous injuries that exhaust the standard rotation; in healthy rosters their contribution is negligible to current-season outcomes.",
     "magnitude": "A high-quality two-way player filling an injury gap contributes a net rating within 6-9 pp of the injured starter in most contexts; below-average fringe slots can widen the rating gap to 14-18 pp per 100 possessions.",
     "links": ["rotation_depth_ten_plus", "injury_replacement_depth", "garbage_time_development_slots", "veteran_youth_age_balance"]},

    {"slug": "veteran_youth_age_balance", "title": "Roster Age-Curve Balance",
     "summary": "The distribution of players across rising, prime, and declining age bands shapes a roster's current ceiling and future trajectory, measured by minutes-weighted average age and the count of rotation players in the 25-to-29 prime window.",
     "stat_signature": "Minutes-weighted average age: young core below 25.5, win-now above 27.5, balanced 25.5-27.5; rotation players in the 25-to-29 prime window: peak-prime rosters carry 4-6 such players; players below 23 with above 20 mpg signal an active developmental track.",
     "mechanism": "Prime-window players deliver peak athletic output while retaining scheme-learning capacity; rising players under 24 improve non-linearly but carry performance variance; veterans above 31 contribute experience and scheme-fit but face declining athletic floors.",
     "conditions": "Age-curve imbalance shows most acutely in game-four-through-seven playoff fatigue contexts; young rosters often underperform regular-season win-rates in best-of-seven series due to narrower experience base.",
     "magnitude": "A roster clustered in the prime 25-to-29 window performs 2-4 pp better than age-equivalent peers in playoff net rating; each additional player over 32 in the rotation above two correlates with a 1-1.5 pp defensive-rating decline in late-season contexts.",
     "links": ["rotation_depth_ten_plus", "two_way_fringe_slots", "injury_replacement_depth", "garbage_time_development_slots"]},

    {"slug": "playmaking_distribution_balance", "title": "Playmaking Distribution Across Units",
     "summary": "Whether assist creation is concentrated in one player or spread across multiple playmakers determines the offense's vulnerability to defensive load-bearing and its ability to generate quality looks for bench units.",
     "stat_signature": "Assist-rate Herfindahl above 0.40 signals high concentration (one primary handler dominant); share of bench minutes with a credible secondary distributor (assist rate above 20%) on the floor above 60% marks well-distributed playmaking; team assist-to-turnover ratio range 1.6-2.4.",
     "mechanism": "Concentrated playmaking lets defenders front the primary distributor and shrink passing lanes; distributed playmaking forces the defense to guard multiple read-and-react hubs, sustaining ball movement quality when any single player is neutralised.",
     "conditions": "Distribution matters most when the primary playmaker is defended by a capable on-ball stopper; in pace-heavy transition offenses, the playmaking concentration effect is partially diluted by transition opportunities that bypass half-court sets.",
     "magnitude": "Rosters with Herfindahl above 0.45 post 6-10 pp worse bench-unit offensive rating when the primary ball-handler is off the floor; distributed rosters (below 0.30) show a gap of only 2-4 pp.",
     "links": ["ball_handling_creation_count", "starter_bench_minute_split", "closing_lineup_construction", "lineup_combination_count"]},

    {"slug": "injury_replacement_depth", "title": "Injury-Replacement Slot Depth",
     "summary": "The on-court net-rating gap between a starter and the next-man-up at the same role reveals how much quality a roster sacrifices when injuries strike, averaged across all five starting slots.",
     "stat_signature": "Starter-to-replacement net-rating drop: shallow-depth roster 12-18 pp, average 7-12 pp, deep roster 3-6 pp; positional replacement quality index (estimated on-court rating for the replacement across five slots); injury-adjusted win-total variance rises 4-7 wins for bottom-quartile depth rosters.",
     "mechanism": "Injury replacement depth is the margin between a roster's healthy ceiling and its floor under a 10-to-20 game starting injury; teams with qualified backups at every slot maintain lineup cohesion and scheme execution, limiting the performance cliff.",
     "conditions": "Replacement depth is most consequential mid-season through the playoff push when standings are contested and a 10-game absence can cost a seeding position; in early season the impact is buffered by easier schedule segments.",
     "magnitude": "Each 3 pp narrowing of the starter-to-replacement gap across the five starting slots corresponds to approximately 2-3 additional projected wins in a season with one prolonged starter absence.",
     "links": ["two_way_fringe_slots", "veteran_youth_age_balance", "rotation_depth_eight_man", "matchup_dependent_roster_flex"]},

    {"slug": "two_big_versus_five_out_construction", "title": "Two-Big Versus Five-Out Roster Construction",
     "summary": "Whether the roster is built to play two traditional bigs or to spread five shootable players determines the offensive floor-spacing architecture and the defensive rebounding tradeoffs the team accepts in its most common lineups.",
     "stat_signature": "Share of minutes in double-big alignments: traditional rosters above 45%, transitional 25-45%, five-out below 25%; count of bigs with credible perimeter range (above 33% on above-break threes): five-out rosters carry 2-3 such players; defensive-rebound rate in five-out minutes drops 4-7 pp versus two-big lineups.",
     "mechanism": "Two-big construction anchors rebounding and rim-protection at the cost of spacing; five-out construction maximises spacing gravity and forces the defense to guard all five positions at the perimeter, at the cost of interior rebounding and paint-protection depth.",
     "conditions": "Five-out construction is most effective against drop-coverage schemes that cannot cover all five perimeter threats; two-big construction is defensively superior against high-drive-frequency opponents relying on rim pressure and second-chance attempts.",
     "magnitude": "Five-out lineups generate 8-12 additional corner-three attempts per 100 half-court possessions but concede 3-5 pp in defensive-rebound rate; two-big lineups hold opponents to 4-6 fewer rim-attempt attempts per 100 possessions.",
     "links": ["shooting_spacing_inventory", "rim_protection_depth", "center_rotation_construction", "positional_size_balance"]},

    {"slug": "perimeter_defense_depth", "title": "Point-of-Attack Defender Depth",
     "summary": "The count of credible on-ball perimeter defenders in the rotation determines whether the team can contest lead ball-handlers across all lineup combinations, measured by positional coverage at the guard slot and share of minutes without a stopper.",
     "stat_signature": "Rotation players matched primarily against lead ball-handlers and holding opposing usage below 24% on-ball: elite 3-4, average 2, gap-roster 0-1; share of minutes without a credible on-ball perimeter defender above 35% signals systemic exposure; opponent creation-foul rate in stopper minutes 20-30% below non-stopper minutes.",
     "mechanism": "Credible on-ball pressure forces the primary creator into below-average looks and limits the pick-and-roll's top-of-key efficiency; limited perimeter-defense depth allows opponents to target rest periods for their highest-usage creation sequences.",
     "conditions": "Most consequential against isolation-heavy and step-back-creation offenses; less determinative when the opponent's primary creation route is off-ball or transition-based rather than on-ball pick-and-roll.",
     "magnitude": "Teams lacking a credible on-ball defender surrender 0.06-0.10 additional PPP on lead-ball-handler possessions in targeted isolation sets; stopper-present minutes hold creation-heavy opponents to 2-4 pp lower overall offensive rating.",
     "links": ["switchability_inventory", "positional_size_balance", "matchup_dependent_roster_flex", "closing_lineup_construction"]},

    {"slug": "closing_lineup_construction", "title": "Closing-Lineup Construction",
     "summary": "The composition of the crunch-time unit, often differing from the starting five, reveals the coaching staff's revealed preference for spacing, switchability, and free-throw reliability in the highest-leverage possessions of close games.",
     "stat_signature": "Closing-lineup departure from starting five: rate of at least one substitution in clutch minutes above 60% across the league; clutch-five average three-point rate above 36% marks spacing-conscious closing construction; clutch-unit net rating range minus-8 to plus-12 pp per 100 possessions.",
     "mechanism": "Coaches substitute toward players with the highest free-throw rate, perimeter shooting, and defensive versatility in late-game scenarios; the closing unit's composition signals which skills the coaching staff believes are most predictive of winning possessions in a 3-to-5 point margin.",
     "conditions": "Closing-unit construction diverges most from regular rotation in games within five points after the third-quarter mark; blowouts and early-deficit games revert to the standard rotation hierarchy.",
     "magnitude": "Clutch-unit net rating diverges by 4-8 pp from that same lineup's non-clutch net rating, driven by free-throw creation and spacing; closing-five free-throw rate above 80% collectively correlates with winning clutch game segments at a 55-62% clip.",
     "links": ["starter_bench_minute_split", "shooting_spacing_inventory", "switchability_inventory", "playmaking_distribution_balance"]},

    {"slug": "matchup_dependent_roster_flex", "title": "Matchup-Dependent Rotation Flexibility",
     "summary": "The roster's ability to reshape its rotation by opponent style, measured by the variance in which players reach meaningful minutes across opponent archetypes and the count of specialist slots toggled on or off by matchup.",
     "stat_signature": "Variance in tenth-player games-played share across opponent-style buckets (pace-heavy, switch-everything, two-big): top-flex rosters show 2-3x the variance of fixed-rotation rosters; count of specialist slots toggled above 3 per matchup shift marks high flexibility; rotation breadth score (distinct players averaging 10+ mpg over any 10-game stretch) range 9-13.",
     "mechanism": "A deep and versatile roster allows the coaching staff to front-load rim-protecting minutes against drive-heavy opponents and shift toward three-point-specialist minutes against switch-everything schemes, optimising lineup construction without sacrificing defensive floor.",
     "conditions": "Matchup flexibility is most exploitable in playoff series where opponent tendencies are stable and well-scouted; in regular-season back-to-back segments, fatigue management overrides matchup-specific substitution logic.",
     "magnitude": "High-flex rosters (four-plus specialist toggles available) show 2-4 pp better net rating against style-extreme opponents relative to fixed-rotation peers; the benefit narrows to under 1 pp in balanced-style matchups.",
     "links": ["rotation_depth_ten_plus", "switchability_inventory", "perimeter_defense_depth", "injury_replacement_depth"]},

    {"slug": "garbage_time_development_slots", "title": "Low-Leverage Development Minute Allocation",
     "summary": "Blowout and low-leverage windows used for sub-rotation player development represent a deferred-value roster asset, measured by the share of total team minutes logged in low-leverage contexts by players outside the eight-man rotation.",
     "stat_signature": "Share of total minutes in low-leverage contexts (win-probability above 90% or below 10% after the third quarter) by sub-rotation players: development-committed teams 12-18%, compressed rotations 4-7%; development-minute players logging above 10 games of 15-plus minutes advance to rotation roles within two seasons at a 30-40% clip.",
     "mechanism": "Systematic development-minute allocation converts blowout possessions into long-run roster depth; players accumulate live-game reps that accelerate scheme-fit and role-readiness at a cost of near-zero current-game expected-value.",
     "conditions": "Development minutes are available only to teams that generate enough blowouts or accept deliberate rest in low-leverage scenarios; tight-race rosters in playoff contention rarely generate sufficient low-leverage windows to sustain development programs.",
     "magnitude": "A player receiving 300 or more development minutes in a season shows on-court rating improvement averaging 3-5 pp the following season relative to equivalent players with zero such minutes; the compounding effect over two seasons spans 6-9 pp improvement.",
     "links": ["two_way_fringe_slots", "rotation_depth_ten_plus", "veteran_youth_age_balance", "rotation_depth_eight_man"]},

    {"slug": "positional_size_balance", "title": "Positional Size and Length Balance",
     "summary": "The roster's wingspan and height distribution across the five position slots determines cross-matching capacity and deterrence presence, with plus-length wings enabling coverage of multiple offensive archetypes without structural mismatches.",
     "stat_signature": "Average wingspan by slot: guard 6-5 to 6-7, wing 6-8 to 7-0, big 7-0 to 7-4; count of plus-length wings (wingspan above 6-10) available for cross-matching: elite 4-5, average 2-3; length-deficit lineups concede 4-6 pp higher opponent FG% at the rim on contested attempts.",
     "mechanism": "Greater wingspan at every slot extends the defensive radius without requiring positional rotation, allowing the scheme to contest more shots within a help-before-commitment framework; plus-length cross-matchers reduce the need for a dedicated rim anchor by deterring drives earlier in the approach.",
     "conditions": "Length advantage is most consequential against high-drive-frequency offenses and lob-threat two-man games at the elbow; less determinative against three-point-heavy offenses that bypass the paint.",
     "magnitude": "Lineups with average wingspan above 6-9 across all five slots hold opponents to 3-5 pp lower rim-FGA% and 2-3 pp better defensive rating; plus-length wings cross-matching onto bigger players concede 4-7 pp lower post-entry efficiency.",
     "links": ["switchability_inventory", "two_big_versus_five_out_construction", "rim_protection_depth", "perimeter_defense_depth"]},
]
