"""NBA Routine Consistency concept nodes — person-free pre-shot and ritual intelligence."""
from __future__ import annotations

SPORT = "NBA"
FAMILY = "RoutineConsistency"

CONCEPTS: list[dict] = [
    {
        "slug": "free_throw_routine_stability",
        "title": "Free-Throw Pre-Shot Routine Stability",
        "summary": "Captures the temporal repeatability of the dribble-set-release ritual at the line, measured as variance in pre-shot duration and dribble count across attempts. Low ritual variance is a motor-automaticity signal that predicts within-game and cross-game conversion consistency.",
        "stat_signature": "Pre-shot duration SD below 0.40 s marks high-stability routines; above 0.80 s marks disrupted or variable rituals. Mode-share of dominant dribble count above 80% separates consistent performers; below 60% indicates situational drift.",
        "mechanism": "A locked pre-shot ritual activates a motor program through consistent proprioceptive and temporal cues, suppressing conscious interference under load. Routine stability reflects the degree to which the shooter has automated the sequence into a single chunked motor unit rather than a conscious checklist.",
        "conditions": "Most diagnostic in high-leverage late-game trips and back-to-back fatigue contexts where conscious override is most likely. Road environments with crowd noise at the line amplify divergence between stable and unstable ritual carriers.",
        "magnitude": "Shooters with pre-shot duration SD below 0.35 s average 2–4 pp higher free-throw percentage than equivalent-skill peers with SD above 0.70 s. Routine drift episodes (SD spike above 0.90 s) co-occur with below-average conversion on those trips at roughly 1.5 times the base miss rate.",
        "links": ["ft_dribble_count_invariance", "ft_release_timing_consistency", "ft_clutch_routine_drift", "ft_routine_fatigue_degradation"],
    },
    {
        "slug": "ft_dribble_count_invariance",
        "title": "Free-Throw Dribble-Count Invariance",
        "summary": "Captures whether the number of dribbles before a free throw stays fixed regardless of game state, measured as the mode-share of the dominant dribble count across all trips. High mode-share is the clearest behavioral indicator of ritual lock and motor automaticity.",
        "stat_signature": "Mode-share above 85% indicates strong invariance; 65–85% moderate; below 65% situationally variable. Dribble counts cluster at 1, 2, 3, or 5 as dominant modes league-wide. Count variance coefficient above 0.30 is a disruption flag.",
        "mechanism": "Each dribble in a pre-shot routine creates a metered temporal cue that primes the shooting motor program; removing or adding a dribble under stress disrupts the internal timing offset and alters the balance phase before release. The invariant count is a pacing anchor rather than a functional mechanical prerequisite.",
        "conditions": "Dribble-count drift is most common on the second attempt of a trip (rhythm break after a make), after a defensive timeout called prior to the shooter stepping to the line, and in overtime or playoff-leverage moments when officiating pace differs from regular flow.",
        "magnitude": "Shooters whose count variance coefficient exceeds 0.30 show an average conversion drop of 1.8–3.2 pp on variable-count attempts relative to their dominant-count baseline. Mode-share is moderately stable across seasons (r ≈ 0.68 for the same shooter over 200+ trips).",
        "links": ["free_throw_routine_stability", "ft_release_timing_consistency", "ft_split_first_second_consistency", "ft_clutch_routine_drift"],
    },
    {
        "slug": "ft_release_timing_consistency",
        "title": "Free-Throw Release Timing Consistency",
        "summary": "Captures the standard deviation of the interval from final ball-set to release across all free-throw attempts, as a proxy for motor-routine repeatability under fatigue and pressure. Tight release-timing SD is the downstream confirmation of a well-automatized ritual.",
        "stat_signature": "Release-timing SD below 0.08 s marks elite mechanical repeatability; 0.08–0.15 s is functional; above 0.20 s marks measurable mechanical disruption. SD rises predictably in minutes-played windows above 34 and in the fourth-quarter period of back-to-back second nights.",
        "mechanism": "Release timing is the final motor output of the entire pre-shot sequence; timing variance propagates from two sources: disrupted set-phase cues (ritual instability) and muscular-fatigue-induced force-production inconsistency in the shooting limb. These two pathways produce distinct signatures — ritual disruption elevates duration SD, while pure fatigue narrows duration but widens release-angle scatter.",
        "conditions": "Fatigue-driven timing drift surfaces most clearly in the third and fourth trips in a single-game trip cluster and after 32+ cumulative minutes. Ritual-driven timing variance surfaces after timeouts and crowd-noise spikes independent of fatigue level.",
        "magnitude": "Each 0.05-s increase in release-timing SD is associated with a conversion probability reduction of approximately 1.0–1.5 pp after controlling for shot distance and defensive environment. Timing consistency degrades roughly 15% from game minutes 1–20 to game minutes 36–48 for high-workload shooters.",
        "links": ["free_throw_routine_stability", "ft_dribble_count_invariance", "ft_routine_fatigue_degradation", "shooting_motion_invariance"],
    },
    {
        "slug": "ft_clutch_routine_drift",
        "title": "Free-Throw Routine Drift Under Clutch Pressure",
        "summary": "Captures the shift in pre-shot ritual length and dribble count between low-leverage and high-leverage attempts, measured as delta in routine duration in the final two minutes of one-possession games. Drift magnitude distinguishes pressure-stable from pressure-sensitive ritual carriers.",
        "stat_signature": "Routine-duration delta above 0.50 s between low-leverage and clutch contexts marks meaningful drift. Clutch free-throw percentage minus overall free-throw percentage: elite pressure performers show a gap within 1 pp; high-drift performers show a 4–7 pp disadvantage in clutch contexts.",
        "mechanism": "Perceived importance triggers attentional narrowing and explicit processing of an otherwise automated motor program, a phenomenon consistent with the reinvestment model of choking. Reinvestment disrupts chunked motor execution by re-introducing conscious step-by-step monitoring, lengthening the ritual or skipping cues under time-urgency perception.",
        "conditions": "Drift is amplified in hostile road environments, in playoff games where individual trips carry higher survival stakes, and for shooters with lower pre-season free-throw volume (fewer repetitions to over-consolidate the motor program). Experience across high-leverage contexts moderates drift over multiple seasons.",
        "magnitude": "Shooters with clutch ritual drift above 0.50 s average a 4–6 pp conversion decline in situations where routine integrity matters most. Drift consistency across seasons (r ≈ 0.55) suggests it reflects a stable individual trait rather than transient noise.",
        "links": ["free_throw_routine_stability", "ft_dribble_count_invariance", "ft_split_first_second_consistency", "post_timeout_routine_reset"],
    },
    {
        "slug": "ft_split_first_second_consistency",
        "title": "Free-Throw First-Versus-Second Attempt Consistency",
        "summary": "Captures the conversion-rate and routine-length stability between the first and second shot of a two-shot trip, isolating the rhythm-break effect of a make or miss on the subsequent attempt. Make-rate gap across the pair is the primary diagnostic.",
        "stat_signature": "League-average first-attempt FT% approximately 1–2 pp lower than second-attempt (rhythm accumulation). Shooters with first-versus-second gap exceeding 4 pp show paired-trip instability. Routine-duration delta between first and second shot above 0.30 s marks a reset mechanism.",
        "mechanism": "The first shot of a trip initiates the timing sequence from a cold state; the second shot follows an outcome that provides immediate feedback and a brief rhythm window. A make on attempt one generally stabilizes the motor program for attempt two; a miss introduces an outcome-correction impulse that can disrupt the second-shot ritual via attentional reinvestment.",
        "conditions": "First-versus-second gap widens in shooters who engage in conscious outcome-monitoring between attempts rather than full ritual re-initiation. The gap is most diagnostic in and-one trips (single shot, no second-attempt comparison) versus two-shot fouls at varying leverage levels.",
        "magnitude": "Shooters with miss-then-make conversion rates more than 5 pp below their make-then-make rate show a paired-trip instability penalty worth roughly 0.05 expected points per trip at the line. Gap stability across seasons r ≈ 0.60.",
        "links": ["free_throw_routine_stability", "ft_dribble_count_invariance", "ft_clutch_routine_drift", "ft_streak_routine_lock"],
    },
    {
        "slug": "ft_routine_fatigue_degradation",
        "title": "Free-Throw Routine Fatigue Degradation",
        "summary": "Captures how ritual length and conversion rate change across cumulative minutes played within a game, isolating the fatigue pathway of routine disruption from the pressure pathway. Ritual-duration slope across minute buckets is the primary signature.",
        "stat_signature": "Routine-duration slope: above 0.02 s per cumulative minute marks progressive fatigue degradation. FT% in minutes 32–48 minus FT% in minutes 1–20: median degradation 1.5 pp; high-workload-sensitive shooters degrade 4–6 pp. Back-to-back second-night degradation averages 2.0 pp on season-level samples.",
        "mechanism": "Muscular fatigue in the shooting arm and shoulder reduces force-production consistency and increases micro-tremor, widening release-angle variance. Simultaneously, cognitive fatigue impairs ritual cue processing, increasing the probability of skipped or shortened pre-shot steps. These two pathways interact: physically fresh shooters can compensate cognitively; double-fatigued shooters show compounding degradation.",
        "conditions": "Degradation surfaces most clearly for players averaging 34+ minutes per game in high-usage roles, in the fourth quarter of close games, and across back-to-back schedules. Well-rested shooters with lower per-game minute totals show degradation curves below noise threshold.",
        "magnitude": "Each additional 4-minute block beyond minute 32 is associated with roughly 0.8 pp FT% decline and a 0.03-s increase in ritual-duration SD for high-volume shooters. Season-long degradation curve slope is moderately repeatable (r ≈ 0.58 year-over-year).",
        "links": ["free_throw_routine_stability", "ft_release_timing_consistency", "ft_clutch_routine_drift", "shooting_motion_invariance"],
    },
    {
        "slug": "ft_streak_routine_lock",
        "title": "Free-Throw Routine Lock During Make Streaks",
        "summary": "Captures whether ritual variance shrinks during consecutive-make runs, measured as pre-shot duration variance conditioned on prior-attempt outcome sequences. Streak-driven ritual tightening is a positive-feedback automaticity signal.",
        "stat_signature": "Routine-duration SD during 3+ consecutive-make sequences: elite streak-lock performers show SD below 0.25 s; league average streak SD approximately 0.40 s. SD ratio (streak context / miss-break context) below 0.70 marks a meaningful lock pattern.",
        "mechanism": "Successful repetitions under consistent ritual conditions reinforce the motor program through dopaminergic reinforcement pathways, reducing the attentional monitoring that otherwise introduces variance. The streak state creates a self-confirming loop: tight ritual produces good outcome, outcome reduces monitoring, reduced monitoring maintains tight ritual.",
        "conditions": "Streak lock appears most clearly in high-volume free-throw shooters (150+ per-season trips) where sufficient within-game and within-trip streak data accumulate. Shooters with explicit superstitious rituals show stronger streak-lock patterns than those with minimal pre-shot routines.",
        "magnitude": "Shooters with streak-lock SD ratio below 0.70 convert at 2–3 pp higher rates during streaks than their overall baseline, and show reversion toward baseline only after a miss-break, creating a lag effect. The signal has moderate season-to-season reliability (r ≈ 0.55).",
        "links": ["free_throw_routine_stability", "ft_split_first_second_consistency", "ft_clutch_routine_drift", "ft_dribble_count_invariance"],
    },
    {
        "slug": "ft_routine_road_home_split",
        "title": "Free-Throw Routine Home-Road Split",
        "summary": "Captures whether pre-shot ritual length and conversion differ between home and away environments, measured as the venue-split delta in routine duration and FT%. Road crowd noise introduces an exogenous stressor that distinguishes pressure-stable from venue-sensitive ritual carriers.",
        "stat_signature": "League-average road FT% runs 0.5–1.5 pp below home FT%. Venue-sensitive shooters show a gap exceeding 3 pp. Routine-duration delta (road minus home) above 0.20 s marks a measurable crowd-noise disruption effect.",
        "mechanism": "Road crowd noise, especially at critical moments, increases arousal and attentional distraction, which re-invests conscious monitoring into the pre-shot sequence. Elevated noise floor can mask the proprioceptive cues a shooter uses for ritual timing calibration, extending or compressing the habitual sequence.",
        "conditions": "Road-home split is largest in high-attendance arenas with loud student or supporter sections (particularly during opponent's free throws in playoff games), and is amplified for younger or lower-experience shooters who have fewer consolidation repetitions in hostile road environments.",
        "magnitude": "A 3+ pp road disadvantage in FT% at a league-average rate of 3.5 trips per game costs roughly 0.10 expected points per road game relative to home performance. Split stability across seasons is moderate (r ≈ 0.52).",
        "links": ["free_throw_routine_stability", "ft_clutch_routine_drift", "post_timeout_routine_reset", "between_play_breathing_recovery"],
    },
    {
        "slug": "shot_gather_tempo_repeatability",
        "title": "Shot Gather-to-Release Tempo Repeatability",
        "summary": "Captures consistency of the gather-load-release rhythm across jump shots, measured as coefficient of variation in gather-to-release frame count on uncontested and lightly contested attempts. Low CV is the mechanical repeatability fingerprint for off-the-dribble and catch-and-shoot proficiency.",
        "stat_signature": "Elite release-tempo CV below 0.08 on uncontested jump shots; 0.08–0.15 functional; above 0.20 marks mechanical inconsistency under fatigue or defensive disruption. CV rises roughly 20–30% when the nearest defender is within 3 ft versus open looks.",
        "mechanism": "Gather-to-release timing integrates lower-body loading, hip rotation, and upper-body sequencing into a single temporal chain. Consistent tempo ensures that force transfer from legs to fingertips peaks at the optimal release window; tempo drift causes early or late peak force, altering arc and spin rate. Stability is built through high-repetition motor-program consolidation.",
        "conditions": "Tempo CV is most diagnostic on uncontested pull-ups and spot-up threes where defender interference is minimal, isolating intrinsic mechanical variance from reactive adjustment noise. Fatigue and third-back-to-back schedule contexts reveal underlying CV trends that contest pressure can mask.",
        "magnitude": "A 0.05-point increase in gather-to-release CV is associated with a roughly 2–3 pp drop in FG% on equivalent looks, controlling for zone and contest level. CV is stable across seasons for mature shooters (r ≈ 0.66) and more volatile for developing players.",
        "links": ["shooting_motion_invariance", "catch_and_shoot_prep_consistency", "ft_release_timing_consistency", "free_throw_routine_stability"],
    },
    {
        "slug": "catch_and_shoot_prep_consistency",
        "title": "Catch-and-Shoot Footwork Prep Consistency",
        "summary": "Captures repeatability of the hop-versus-stride gather on spot-up attempts, measured as the dominant-gather-type share. Consistent footwork preparation removes a balance and timing variable before the shooting motion begins, directly reducing mechanical variance.",
        "stat_signature": "Dominant gather-type share above 80% marks high-prep consistency; 60–80% situational; below 60% unpredictable. Hop-gather shooters show marginally higher catch-to-release consistency (CV 0.06–0.09) versus stride-gather (CV 0.09–0.13) on equivalent-distance attempts.",
        "mechanism": "The gather phase sets the base from which the entire shooting kinematic chain initiates; inconsistent foot placement alters hip angle and shoulder-to-target alignment, cascading into release-angle variance. A locked gather type allows the motor program to execute the post-gather sequence identically regardless of pass angle or speed.",
        "conditions": "Gather inconsistency surface most when passes arrive in non-ideal windows — behind the target, low, or at full extension — where the catcher must improvise the base. High-frequency catch-and-shoot specialists (6+ C&S FGA per 36) show the clearest gather-type signatures due to volume.",
        "magnitude": "Shooters with dominant-gather-type share above 85% average 1.5–2.5 pp higher catch-and-shoot FG% than mixed-gather peers of equivalent raw shooting skill. Gather-type consistency is moderately stable year-over-year (r ≈ 0.62).",
        "links": ["shot_gather_tempo_repeatability", "shooting_motion_invariance", "pre_possession_alignment_routine", "warmup_to_game_carryover"],
    },
    {
        "slug": "shooting_motion_invariance",
        "title": "Shooting Motion Mechanical Invariance",
        "summary": "Captures cross-attempt repeatability of release angle and elbow-path alignment on uncontested shots, measured as standard deviation of release-arc metrics. High motion invariance is the kinematic substrate underlying conversion consistency across game states.",
        "stat_signature": "Release-arc SD below 2.5 degrees marks elite invariance; 2.5–4.0 degrees functional; above 5.0 degrees marks mechanically inconsistent shooters. Elbow-path deviation above 8 degrees from the mean trajectory is associated with short or flat release errors.",
        "mechanism": "Mechanical invariance reflects the fidelity of a motor program to reproduce the optimal kinematic chain under varying internal states. A consistent elbow path constrains the wrist-to-arc relationship; consistent release angle produces predictable ball trajectory and bank probability. Both emerge from thousands of consolidated repetitions that groove neural-muscular firing patterns.",
        "conditions": "Invariance is most interpretable on uncontested and lightly contested looks where defender-induced adjustments do not inject external variance. Fatigue conditions (minutes above 34, back-to-back schedules) reliably reveal mechanical consistency gaps that are masked in fresh-state samples.",
        "magnitude": "A 1-degree increase in release-arc SD corresponds to roughly 1.5–2.0 pp decline in FG% at equivalent distances and contest levels. Motion invariance is among the most stable individual shooting characteristics, with year-over-year correlation r ≈ 0.73 for established shooters.",
        "links": ["shot_gather_tempo_repeatability", "ft_release_timing_consistency", "catch_and_shoot_prep_consistency", "ft_routine_fatigue_degradation"],
    },
    {
        "slug": "pre_possession_alignment_routine",
        "title": "Pre-Possession Alignment Routine",
        "summary": "Captures the repeatability of a player's set-up footwork and spacing before a half-court possession begins, measured as variance in starting-position coordinates across possessions with equivalent alignment cues. Consistent pre-possession positioning reduces reaction time and cognitive load when the action initiates.",
        "stat_signature": "Starting-position coordinate SD below 1.5 ft marks high-alignment consistency; above 3.0 ft marks variable pre-possession setup. Shooters with consistent alignment reach their spot-up target position on average 0.15–0.25 s faster than variable-alignment peers on equivalent actions.",
        "mechanism": "Pre-possession alignment sets the initial state for all subsequent movement decisions; a consistent starting position reduces the degrees-of-freedom that must be solved in real-time once the action triggers. Aligned shooters can run motor programs from a known base; misaligned ones must adapt footwork on the fly, introducing tempo disruption.",
        "conditions": "Alignment consistency is most diagnostic for off-ball spacers in motion-heavy sets where starting-position variance directly correlates with catch quality and shot readiness. Transition-heavy teams show higher starting-position variance due to flow-based positioning rather than set-designed alignment.",
        "magnitude": "Off-ball shooters with starting-position SD above 3.0 ft show a 2–4 pp lower catch-and-shoot FG% on overlap actions due to improvised footwork, compared with consistent-alignment peers in equivalent sets. Alignment stability is moderately repeatable (r ≈ 0.60).",
        "links": ["catch_and_shoot_prep_consistency", "shot_gather_tempo_repeatability", "set_play_initiation_repeatability", "between_play_breathing_recovery"],
    },
    {
        "slug": "post_timeout_routine_reset",
        "title": "Post-Timeout Routine Reset",
        "summary": "Captures whether shot and free-throw rituals remain unchanged after a stoppage, measured as routine-length delta on the first attempt following a timeout relative to the baseline. Timeouts interrupt the continuous-action rhythm that sustains motor-program priming.",
        "stat_signature": "Post-timeout free-throw routine-duration delta above 0.35 s marks disrupted reset. Post-timeout first-possession FG% versus in-flow FG%: league average difference approximately 1.5 pp; reset-stable performers show gaps below 0.5 pp.",
        "mechanism": "A timeout breaks the continuous action flow, requiring the player to rebuild activation level and re-establish proprioceptive readiness before the next shot opportunity. Shooters with robust reset routines use the timeout interval for deliberate motor-program priming; those without an explicit reset process re-enter cold and show elevated ritual variance on the first post-timeout attempt.",
        "conditions": "Post-timeout disruption is largest after defensive timeouts specifically called to ice a shooter at the free-throw line, and after long reviews or medical stoppages that extend the cold interval beyond the typical 90-second timeout window.",
        "magnitude": "First post-timeout free-throw conversion drops an average 1.5–2.5 pp across the league; shooters with explicit reset awareness show gaps below 0.5 pp. The effect decays by the second attempt of the same trip, confirming it is a re-priming rather than a structural disruption.",
        "links": ["free_throw_routine_stability", "ft_clutch_routine_drift", "between_play_breathing_recovery", "ft_routine_road_home_split"],
    },
    {
        "slug": "between_play_breathing_recovery",
        "title": "Between-Play Recovery Routine",
        "summary": "Captures the use of dead-ball windows for physiological reset, measured as performance stability on possessions following short (under 6 s) versus long (over 15 s) inter-possession gaps. Structured recovery use maintains motor-program priming and reduces carry-over fatigue effects.",
        "stat_signature": "FT% and FG% on long-gap-following possessions versus short-gap: well-recovered players show under 1.5 pp variance; high-fatigue-carry players show 3–5 pp degradation on short-recovery possessions after high-exertion sequences. Recovery-routine consistency is measurable via heart-rate proxy metrics from wearable data.",
        "mechanism": "Short inter-possession windows compound muscular activation and oxygen debt without clearing lactate or resetting breathing baseline, elevating tremor and reducing force-production consistency in subsequent shot attempts. Players who deploy structured breathing or movement patterns in these windows clear physiological arousal faster and re-enter shooting actions from a more stable baseline.",
        "conditions": "Recovery-routine benefit is largest in the fourth quarter of high-pace games with frequent fouling, where short dead-ball windows alternate with high-exertion possessions. Effects are most interpretable for high-usage players running 32+ minutes in such contexts.",
        "magnitude": "Performance gap on short-recovery-window possessions is approximately 2–3 pp FG% disadvantage for recovery-passive players relative to their long-gap baseline. Gap narrows to under 1 pp for players with documented structured recovery protocols across a full season.",
        "links": ["post_timeout_routine_reset", "ft_routine_fatigue_degradation", "pre_possession_alignment_routine", "ft_routine_road_home_split"],
    },
    {
        "slug": "set_play_initiation_repeatability",
        "title": "Set-Play Initiation Repeatability",
        "summary": "Captures the consistency of the entry-cut or hand-off timing that triggers a designed action, measured as variance in initiation-cue timing across possessions running the same set. Tight initiation timing synchronizes off-ball movement with on-ball actions, improving shot-look quality.",
        "stat_signature": "Initiation-cue timing SD below 0.30 s marks high-repeatability execution; above 0.60 s marks inconsistent triggering. Possession efficiency of set plays correlates with initiation-timing consistency at r ≈ 0.45 across teams over 200+ designed actions.",
        "mechanism": "Designed actions rely on coordinated timing between the ball handler's cue and the off-ball cutter's movement; if the cutter initiates 0.5 s early or late, the screen-action spacing collapses or the defender recovers, degrading the shot quality. Repeatability reduces the coordination overhead and allows the off-ball mover to execute the same footwork pattern every repetition.",
        "conditions": "Initiation timing variance is highest early in the season when new sets are being installed and in playoff game-planning contexts where opponents have studied the team's tendencies. Well-drilled sets in mid-season show the tightest initiation-timing distributions.",
        "magnitude": "A 0.20-s reduction in initiation-timing SD is associated with a roughly 0.04-pt/possession efficiency improvement on designed-action possessions. Initiation repeatability is moderately stable within a season (r ≈ 0.57) and resets partially at each coaching-scheme change.",
        "links": ["pre_possession_alignment_routine", "catch_and_shoot_prep_consistency", "post_timeout_routine_reset", "inbound_setup_routine_consistency"],
    },
    {
        "slug": "inbound_setup_routine_consistency",
        "title": "Inbound Setup Routine Consistency",
        "summary": "Captures repeatability of the pre-inbound alignment and screen-timing on baseline and sideline restarts, measured as setup-duration variance and screen-initiation timing SD. Consistent inbound setups maximize the surprise element and shot-quality of end-of-quarter designed actions.",
        "stat_signature": "Setup-duration SD below 0.40 s on baseline inbounds marks consistent execution; above 0.80 s marks timing-variable teams. First-action eFG% on tight-clock (under 3 s) inbounds ranges from 42–56% across teams; efficient inbound units cluster at the upper end via timing repeatability.",
        "mechanism": "Baseline and sideline inbounds are among the few fully scripted actions in basketball; their effectiveness depends entirely on execution fidelity, as the defense has studied the same film. Consistent alignment and screen timing replicate the action's spacing geometry precisely, making the defender's pre-planned counter less effective and creating the designed window reliably.",
        "conditions": "Setup consistency is most valuable on clock-expiring inbounds (final possession of a quarter) where a single designed action determines the outcome. Late-game defensive switches to deny the primary entry pass benefit teams with consistent alternate-action timing.",
        "magnitude": "Teams with setup-duration SD below 0.40 s on designed inbound actions convert at roughly 4–6 pp higher eFG% on first-action looks than high-variance teams on comparable sets. Consistency is coachable and improves measurably across a season with dedicated practice volume.",
        "links": ["set_play_initiation_repeatability", "pre_possession_alignment_routine", "post_timeout_routine_reset", "catch_and_shoot_prep_consistency"],
    },
    {
        "slug": "warmup_to_game_carryover",
        "title": "Warm-Up Mechanics-to-Game Carryover",
        "summary": "Captures the consistency between pregame shooting-form metrics and in-game mechanical execution, as a proxy for how well a player's routine bridges the controlled warm-up environment to the live game context under crowd and fatigue pressure.",
        "stat_signature": "Release-arc SD ratio (in-game / pregame) below 1.20 marks strong carryover; above 1.60 marks a meaningful carryover gap. Shooters with warm-up-to-game arc SD ratio below 1.15 average 2–3 pp higher first-quarter FG% than high-ratio peers on equivalent zone attempts.",
        "mechanism": "Pregame warm-up consolidates the motor program and establishes the shooting baseline for that session; carryover reflects the degree to which that consolidation persists when arousal, crowd noise, and competitive pressure activate the game state. Strong carryover implies that the motor program is robust to state-change interference; weak carryover implies it is warm-up-context-specific and degrades under load.",
        "conditions": "Carryover gap surfaces most clearly in first-quarter performance relative to later-quarter baselines, as the early game captures the direct warm-up-to-competition transition before in-game momentum effects dominate. Road contexts and playoff environments with long tunnel-to-court delays amplify carryover gaps.",
        "magnitude": "A warm-up-to-game arc SD ratio above 1.50 corresponds to roughly 1.5–3 pp first-quarter FG% gap relative to the player's full-game shooting average. Carryover ratio is moderately stable across season contexts (r ≈ 0.55) and is most useful as a contextual scouting flag rather than a primary predictive signal.",
        "links": ["shooting_motion_invariance", "catch_and_shoot_prep_consistency", "between_play_breathing_recovery", "shot_gather_tempo_repeatability"],
    },
]
