"""MLB ShotProfiles — batted-ball shape, pitch-movement, and swing-decision concepts."""
from __future__ import annotations

SPORT = "MLB"
FAMILY = "ShotProfiles"

CONCEPTS: list[dict] = [
    {
        "slug": "launch_angle_distribution_profile",
        "title": "Launch-Angle Distribution Profile",
        "summary": "Captures the full distribution of vertical exit angle across four buckets (grounder <10°, line drive 10-25°, fly 25-50°, popup >50°) as a batted-ball-shape fingerprint. Sweet-spot rate (8-32°) is the primary summary statistic, benchmarked against the league band of 33-35%.",
        "stat_signature": "Sweet-spot rate 33-35% league band; elite profiles sustain 38-42%. Grounder rate above 52% signals severe loft deficit; popup rate above 12% signals swing-plane instability at the top of the zone.",
        "mechanism": "Vertical bat-plane angle at contact dictates the exit-angle distribution. A slight uppercut (5-10° attack angle) concentrates balls in the sweet spot, maximizing the overlap of hard contact and optimal trajectory. Extreme uppercuts raise popup and strikeout rates without lifting total production.",
        "conditions": "Loft deficits widen against high-velocity fastballs that hitters are late on, flattening the swing plane. Two-strike counts shift distribution toward flatter contact as hitters protect the zone. Cold weather suppresses carry, reducing the run value of marginal fly-ball angles.",
        "magnitude": "Moving sweet-spot rate from 30% to 37% corresponds to roughly 40 points of expected-batting-average gain; popup rate above 15% is associated with wOBA suppression of approximately 0.030-0.050 relative to contact peers.",
        "links": ["barrel_zone_contact_profile", "ground_ball_fly_ball_ratio", "pull_side_loft_power_profile", "expected_outcome_contact_gap", "two_strike_approach_shape"],
    },
    {
        "slug": "exit_velocity_distribution_profile",
        "title": "Exit-Velocity Distribution and Hard-Hit Rate",
        "summary": "Captures batted-ball speed summarized by mean, 90th-percentile, and max exit velocity, with hard-hit rate (95+ mph share) as the primary contact-quality signature benchmarked against the league band of 35-40%.",
        "stat_signature": "Hard-hit rate league band 35-40%; elite profiles reach 50-55%. Mean exit velocity above 91 mph signals above-average raw contact. 90th-percentile above 103 mph marks a true impact-bat profile.",
        "mechanism": "Exit velocity is driven by bat speed and contact efficiency (squared-up rate). High bat speed sets the ceiling; centering the barrel on the ball determines whether it is reached. Soft-contact rates above 25% suppress average exit velocity independent of peak capability.",
        "conditions": "Hard-hit rate degrades against high-spin breaking balls and elite changeup separation (10+ mph gap) that disrupts timing. Pitch-clock fatigue in late plate appearances compresses reaction windows.",
        "magnitude": "Each 1 mph gain in mean exit velocity corresponds to roughly 4-6 points of expected slugging; hard-hit rates above 50% are associated with ISO above 0.220 independent of launch angle profile.",
        "links": ["barrel_zone_contact_profile", "launch_angle_distribution_profile", "expected_outcome_contact_gap", "batted_ball_quality_against_profile", "whiff_zone_swing_miss_geometry"],
    },
    {
        "slug": "barrel_zone_contact_profile",
        "title": "Barrel-Zone Contact Profile",
        "summary": "Captures the share of batted balls landing in the optimal exit-velocity-by-launch-angle band (approximately 98+ mph at 26-30°) where hit and extra-base probability are jointly maximized. Measured as barrels per batted ball and barrels per plate appearance.",
        "stat_signature": "League-average barrel rate near 6-7% per batted ball; elite profiles sustain 10-14%. Barrels per PA above 8% marks a true power-contact fingerprint. Barrel rate is more stable than HR rate across small samples because it isolates contact quality from park and weather sequencing.",
        "mechanism": "The barrel zone is the intersection of sufficient velocity and elevation to generate hit probability above 0.500 and slugging probability above 1.500. Pitchers suppress barrel rate by keeping the ball out of the zone where the hitter's squared-contact window coincides with the optimal angle range.",
        "conditions": "Barrel rate suppresses against elite command pitchers who consistently work the shadow zone. Pitch tunneling reduces barrel rate by making the commit window ambiguous. Platoon contexts shift the exit-angle distribution, modulating which pitches are barrelable for a given swing profile.",
        "magnitude": "Barrel rate explains roughly 60% of wOBA-on-contact variance over a full season; a 4-point barrel rate advantage corresponds to approximately a 0.030-0.040 wOBA gap independent of other batted-ball metrics.",
        "links": ["launch_angle_distribution_profile", "exit_velocity_distribution_profile", "pull_side_loft_power_profile", "expected_outcome_contact_gap", "batted_ball_quality_against_profile"],
    },
    {
        "slug": "spray_chart_field_distribution",
        "title": "Spray-Chart Pull, Center, and Oppo Distribution",
        "summary": "Captures the horizontal direction of batted balls across pull, straightaway, and opposite fields. Pull rate interacts with park dimensions and defensive positioning to determine how much contact quality converts to hits.",
        "stat_signature": "Pull rate above 45% marks a pull-heavy profile; opposite-field rate below 20% signals pronounced pull tendency. Spray-balanced hitters (pull 38-42%, center 30-34%, oppo 24-28%) post higher BABIP than extreme pull profiles against shifting defenses.",
        "mechanism": "Pull tendency emerges from early extension, concentrating hard contact on the pull side but exposing the opposite-field half. Extreme pull hitters are shift-vulnerable because the defense overloads the pull side without conceding extra-base authority. Spray balance indicates better pitch-reading and the ability to use all fields.",
        "conditions": "Pull tendencies amplify against same-handed pitchers working the outer half, forcing earlier commitment. Opposite-field usage rises in hitter-behind counts. Park factors on the pull side make pull-heavy profiles more productive in specific home contexts.",
        "magnitude": "Extreme pull profiles (above 50%) show BABIP suppression of roughly 15-25 points relative to spray-balanced peers when defenses deploy the shift, though extra-base yield partially compensates.",
        "links": ["pull_side_loft_power_profile", "ground_ball_fly_ball_ratio", "platoon_split_contact_shape", "two_strike_approach_shape", "contact_point_depth_profile"],
    },
    {
        "slug": "ground_ball_fly_ball_ratio",
        "title": "Ground-Ball to Fly-Ball Ratio",
        "summary": "Captures the balance between grounders and air balls as a swing-plane and run-value fingerprint. GB/FB ratio and ground-ball rate — benchmarked against the league band near 42-45% — separate loft-oriented from worm-burner contact profiles.",
        "stat_signature": "League-average ground-ball rate near 43%; above 52% marks a pronounced ground-ball profile; below 35% marks a fly-ball orientation. GB/FB above 1.5 signals a steep swing plane; below 0.9 signals loft preference. Line-drive rate (18-22%) is the high-value complement.",
        "mechanism": "Swing-plane angle determines the GB/FB split: a downward path generates topspin grounders, an upward path generates backspin air balls. Ground-ball-heavy contact limits ISO because the vast majority of grounders are singles or outs; fly-ball profiles carry more variance (HR or out) but superior slugging when contact quality is present.",
        "conditions": "Pitchers induce ground balls by working low in the zone with sinkers that produce downward contact. Extreme fly-ball rates increase against pitchers with elite downward-breaking curveballs that hitters swing under. Altitude and humidity affect fly-ball carry without changing the underlying contact distribution.",
        "magnitude": "Shifting ground-ball rate from 43% to 35% while maintaining hard-hit rate corresponds to roughly 20-30 ISO points; ground-ball rate above 55% caps ISO near 0.120 even with above-average exit velocity.",
        "links": ["launch_angle_distribution_profile", "pull_side_loft_power_profile", "batted_ball_quality_against_profile", "spin_rate_movement_profile", "barrel_zone_contact_profile"],
    },
    {
        "slug": "pull_side_loft_power_profile",
        "title": "Pull-Side Loft and Air-Pull Power",
        "summary": "Captures the joint tendency to elevate and pull — the canonical home-run-generating combination — measured as air-pull rate (fly balls plus line drives to the pull field) and its correlation with isolated extra-base production.",
        "stat_signature": "Air-pull rate above 25% of all batted balls marks a true power-pull profile. HR-per-fly-ball above 18% confirms the combination delivers. Air-pull rate above 25% with HR/FB below 12% signals elevation without sufficient exit velocity to convert.",
        "mechanism": "Pulling a fly ball leverages the largest pull-side carry advantage and comes from the highest-leverage quadrant of the swing: early extension maximizes the lever arm for pull-side power. When combined with sufficient exit velocity, pull-side geometry minimizes the distance to the fence and maximizes home-run probability for a given trajectory.",
        "conditions": "Air-pull power suppresses when pitchers work the outer half or elevate hard fastballs to the glove side, disrupting early-extension timing. Same-handed pitchers who heavily deploy outer-half breaking balls force hitters to stay back, shifting contact to center or opposite field.",
        "magnitude": "Air-pull rate explains roughly 40-50% of variance in HR rate across batters with similar exit velocity; increasing air-pull rate from 18% to 26% is associated with approximately 6-10 additional home runs per 600 PA at constant exit velocity.",
        "links": ["spray_chart_field_distribution", "launch_angle_distribution_profile", "barrel_zone_contact_profile", "ground_ball_fly_ball_ratio", "platoon_split_contact_shape"],
    },
    {
        "slug": "pitch_mix_arsenal_profile",
        "title": "Pitcher Arsenal and Pitch-Mix Profile",
        "summary": "Captures the usage distribution of a pitcher's offerings (four-seam, sinker, slider, curve, changeup, cutter, splitter) as a repertoire fingerprint, measured as per-pitch usage share and arsenal breadth (count of pitches thrown above 10%).",
        "stat_signature": "Arsenal breadth of 4+ pitches above 10% marks a deep, unpredictable mix. Single-pitch dominance above 55% marks a narrow profile vulnerable to familiarity. Fastball-to-offspeed ratio split by count situation is the sequencing-dependency fingerprint.",
        "mechanism": "Pitch-mix breadth raises hitter uncertainty about the next offering, increasing commitment-timing load. Single-pitch dominance allows hitters to time and anticipate more accurately; deep arsenals force hitters to guard multiple movement patterns simultaneously. Count-based mix shifts (fastball-heavy behind, breaking-ball-heavy ahead) create exploitable sequencing patterns over multiple looks.",
        "conditions": "Arsenal vulnerability amplifies in third-time-through-the-order contexts where hitters have seen every offering twice. Narrow arsenals degrade faster against patient lineups that extend counts to force the fastball. Deep arsenals lose less value in pitcher-friendly counts because the broader threat maintains uncertainty.",
        "magnitude": "Third-time-through penalty for narrow-arsenal starters averages 0.30-0.50 additional ERA equivalent relative to deep-arsenal peers; this is the primary innings-limit signal independent of fatigue.",
        "links": ["pitch_location_command_profile", "velocity_band_profile", "pitch_sequencing_tunnel_profile", "first_pitch_attack_profile", "whiff_zone_swing_miss_geometry"],
    },
    {
        "slug": "velocity_band_profile",
        "title": "Velocity Band and Velo-Separation Profile",
        "summary": "Captures the speed of each pitch type and the velocity gap between fastball and off-speed, measured as fastball velocity band, changeup separation (typically 8-12 mph), and in-game velocity trend as a stuff and fatigue signature.",
        "stat_signature": "Fastball velocity above 95 mph marks above-average raw stuff; above 98 mph marks elite. Changeup separation of 8-12 mph is the effective deception band; below 6 mph loses deception. In-game velocity decline of 2+ mph from early to late outings signals fatigue-associated whiff-rate degradation.",
        "mechanism": "Fastball velocity sets the reaction-time ceiling: every 1 mph gain reduces reaction time by approximately 3 milliseconds. Velocity separation creates tunnel deception — the arm speed matches the fastball, so the hitter commits to fastball timing and is late or early when the off-speed arrives. Velo decline correlates with command deterioration and contact-quality increases against.",
        "conditions": "Separation matters most against aggressive hitters who commit early in the count. In pitcher-ahead counts, lower changeup velocity is tolerable because hitters must protect. Cold weather suppresses velocity 0.5-1.5 mph, slightly reducing the separation gap and raw reaction-time advantage.",
        "magnitude": "Each 1 mph increase in fastball velocity corresponds to roughly 0.4-0.6% whiff-rate gain; pitchers dropping from 96 to 93 mph during outings show hard-hit rate increases of 3-5 percentage points in innings 5-7 versus 1-3.",
        "links": ["spin_rate_movement_profile", "pitch_mix_arsenal_profile", "pitch_sequencing_tunnel_profile", "whiff_zone_swing_miss_geometry", "batted_ball_quality_against_profile"],
    },
    {
        "slug": "spin_rate_movement_profile",
        "title": "Spin Rate and Pitch-Movement Profile",
        "summary": "Captures the spin rate and induced horizontal and vertical break of each offering, measured as per-pitch spin (rpm), induced vertical break on the fastball (IVB), and sweep on breaking balls as the physical basis of swing-and-miss shape.",
        "stat_signature": "Four-seam IVB above 18 inches marks elite rise effect; below 12 inches yields a flat, hittable offering. Slider sweep above 15 inches creates horizontal deception; spin above 2500 rpm on a curveball drives sharp downward break. Spin efficiency (active spin share) distinguishes movement from total spin.",
        "mechanism": "Spin-induced movement creates perceptual deviation from the hitter's expected trajectory, generating timing errors even at modest velocity. High IVB fastballs appear to rise relative to a lower-spin pitch at the same speed, causing hitters to swing under. High-sweep sliders move horizontally late, pulling the bat head across the plate with the barrel tracing the opposite direction.",
        "conditions": "Movement profiles interact with pitch location: high IVB is most effective elevated in the zone where hitters struggle to suppress the bat path. High-sweep sliders are most effective when tunneled off a high fastball that anchors the eye line. Spin-movement interactions degrade in humid conditions that reduce aerodynamic grip.",
        "magnitude": "Each 2 inches of additional IVB corresponds to roughly 1.5-2.5% whiff-rate gain; high-sweep sliders (15+ inches) average 3-5 percentage points higher whiff rate than flat-breaking sliders at equivalent velocity.",
        "links": ["velocity_band_profile", "whiff_zone_swing_miss_geometry", "pitch_sequencing_tunnel_profile", "pitch_location_command_profile", "batted_ball_quality_against_profile"],
    },
    {
        "slug": "whiff_zone_swing_miss_geometry",
        "title": "Whiff-Zone and Swing-Miss Geometry",
        "summary": "Captures the locations and pitch types that generate swinging strikes, measured as whiff rate by zone region and by pitch type, with chase-region whiff rate marking the out-of-zone put-away signature.",
        "stat_signature": "Overall whiff rate above 27% marks above-average miss-generation; above 33% marks elite. Chase-region whiff rate above 40% signals a put-away offering. Heart-zone whiff rate above 15% indicates genuine deception even at the most hittable location.",
        "mechanism": "Whiffs arise from three mechanisms: velocity that shortens reaction time below the barrel-contact minimum; movement that deviates the bat from its expected intercept path; and tunneling that commits the hitter to the wrong pitch type before divergence. Chase whiffs exploit the committed swing when pitches replicate fastball early flight but land outside the zone.",
        "conditions": "Whiff rates amplify in two-strike counts where hitters cannot take borderline pitches. Pitchers deploy their highest-whiff offerings in these leverage counts. Whiff geometry is hitter-dependent: low-ball hitters whiff high, high-ball hitters whiff on breaking balls in the dirt.",
        "magnitude": "Pitchers with whiff rates above 30% sustain strikeout rates above 25%; the strikeout-to-walk gap explains the majority of ERA variation attributable to pitcher control. Chase-region whiff rates above 45% mark a true out pitch that survives even when hitters know it is coming.",
        "links": ["spin_rate_movement_profile", "velocity_band_profile", "chase_and_zone_swing_profile", "pitch_sequencing_tunnel_profile", "two_strike_approach_shape"],
    },
    {
        "slug": "chase_and_zone_swing_profile",
        "title": "Chase and In-Zone Swing-Decision Profile",
        "summary": "Captures swing aggression partitioned into out-of-zone chase and in-zone swing rates as a plate-discipline fingerprint, measured as O-swing rate, Z-swing rate, and the swing-decision differential between them.",
        "stat_signature": "League-average O-swing rate near 30%; above 38% marks pronounced chase vulnerability. Z-swing rate above 68% with O-swing below 25% marks elite zone discrimination. Swing-decision differential (Z-swing minus O-swing) above 40 points indicates strong discipline; below 30 signals undifferentiated aggressiveness.",
        "mechanism": "Plate discipline determines what pitches reach productive contact. High O-swing rates give pitchers a free out mechanism — they can expand to the chase zone without conceding count leverage. Low Z-swing rates leave hittable pitches untouched and force unfavorable counts. The optimal profile swings aggressively within the zone and refuses pitches outside it, generating the maximum mix of walks and quality contact.",
        "conditions": "Chase rates inflate in hitter-behind counts where swinging on near-zone pitches becomes rational. Pitchers with sharp lateral movement exploit high-chase hitters by starting pitches at the zone edge and carrying them outside. Hitters adjusting from lower levels show elevated O-swing rates against MLB-quality secondary pitches.",
        "magnitude": "O-swing rate above 35% is associated with strikeout rates 5-8 points above position average; combined with below-average Z-swing, it can suppress OBP by 0.030-0.050 relative to contact peers.",
        "links": ["whiff_zone_swing_miss_geometry", "two_strike_approach_shape", "first_pitch_attack_profile", "contact_point_depth_profile", "pitch_location_command_profile"],
    },
    {
        "slug": "two_strike_approach_shape",
        "title": "Two-Strike Approach and Contact-Shift Profile",
        "summary": "Captures how batted-ball and swing shape change with two strikes: flatter swing, opposite-field shift, contact-protect mode. Measured as the two-strike change in launch angle, opposite-field rate, and whiff rate relative to non-two-strike counts.",
        "stat_signature": "Two-strike launch-angle reduction of 3-6° is typical for adaptive hitters. Opposite-field rate increase of 4-8 percentage points in two-strike counts marks a good contact adjustment. Hitters whose whiff rate increases by more than 8 percentage points in two-strike counts show a strikeout-sequencing vulnerability.",
        "mechanism": "Two-strike context forces a defensive expansion of the swing zone and a flatter, contact-first approach. Adaptive hitters reduce launch angle to improve contact rate, accepting lower average exit angles to avoid strikeouts. This shifts the batted-ball distribution toward grounders and opposite-field line drives, reducing power output but improving ball-in-play rate.",
        "conditions": "Two-strike whiff vulnerability amplifies when pitchers pair a high-chase-rate breaking ball with earlier-count tunneling. Hitters with high overall strikeout rates show larger two-strike behavioral shifts. Low-swing-miss hitters maintain their approach shape more consistently across counts.",
        "magnitude": "Two-strike wOBA drops 0.060-0.090 relative to non-two-strike wOBA league-wide; hitters who successfully compress launch angle in two-strike counts recover 0.020-0.035 of that gap relative to rigid-approach peers.",
        "links": ["launch_angle_distribution_profile", "chase_and_zone_swing_profile", "whiff_zone_swing_miss_geometry", "contact_point_depth_profile", "spray_chart_field_distribution"],
    },
    {
        "slug": "expected_outcome_contact_gap",
        "title": "Expected-Outcome Gap From Contact Quality",
        "summary": "Captures the gap between expected results implied purely by exit velocity and launch angle and actual results, measured as xBA and xSLG differential from realized values, isolating contact-quality shape from sequencing, defense, and park.",
        "stat_signature": "xBA minus BA gap above 0.025 signals positive outcome luck (overperforming contact quality); below -0.025 signals negative. xSLG minus SLG gap above 0.040 marks a power-luck signal. Persistent gaps of 3+ standard deviations over 300+ PA indicate structural contact-pattern differences not captured by the batted-ball model.",
        "mechanism": "The expected-outcome model assigns run value based only on exit velocity and launch angle. Gaps arise from fielder positioning effects, park geometry differences, sequencing luck, and genuine hitter skills (bunt singles, beating shifts, sprint speed). Persistent negative xBA gaps can signal a hitter is systematically placing the ball at fielders via spray-chart or defensive-positioning exploitation.",
        "conditions": "Expected-outcome gaps are most informative over 350+ PA; small-sample gaps are dominated by sequencing noise. Shift-heavy environments inflate BABIP gaps for extreme pull hitters who beat the shift with poor contact quality. Speed-based hitters generate systematic positive BABIP gaps by beating out grounders the model treats as outs.",
        "magnitude": "The mean-reversion half-life of xBA gaps is roughly 300 PA; gaps of 0.030+ compress toward zero by roughly 60% over the subsequent 400 PA, suggesting persistent structural differences of approximately 0.010-0.015 after reversion.",
        "links": ["barrel_zone_contact_profile", "exit_velocity_distribution_profile", "launch_angle_distribution_profile", "spray_chart_field_distribution", "popup_and_infield_fly_tendency"],
    },
    {
        "slug": "pitch_sequencing_tunnel_profile",
        "title": "Pitch-Sequencing and Tunneling Profile",
        "summary": "Captures how consecutive pitches share a release point and early flight path before diverging late, measured by tunnel-point separation and the rate of fastball-then-breaking-ball pairs that mirror until the commit point, as a deception-shape signature.",
        "stat_signature": "Tunnel-point separation below 3 inches between fastball and breaking ball marks an effective tunnel pair. Pitch-pair whiff rate on sequenced breaking balls 5-10 percentage points above the pitch's solo baseline marks the tunneling lift. Fastball-slider pairs with less than 2 inches separation at 20 feet from the plate are elite.",
        "mechanism": "Tunneling exploits the hitter's commit point approximately 175 milliseconds before plate arrival, after which swing adjustment is not physiologically possible. If two pitches share trajectory until after the commit point and then diverge, the hitter must decide based on the shared early phase alone. Effective tunnels maximize late separation from a shared early path, creating genuine ambiguity that no amount of pitch recognition resolves.",
        "conditions": "Tunneling effectiveness amplifies against hitters who commit early to pitch recognition; patient, short-swing hitters who delay commitment reduce the impact. Release-point consistency is necessary for the tunnel to hold — varied release angles expose the pitch type before the commit point.",
        "magnitude": "Pitchers who consistently tunnel their top pair achieve 4-7 percentage point whiff-rate premiums on their secondary pitches compared to pitchers with identifiable early trajectories, independent of spin and velocity.",
        "links": ["spin_rate_movement_profile", "velocity_band_profile", "pitch_mix_arsenal_profile", "whiff_zone_swing_miss_geometry", "called_strike_zone_shaping"],
    },
    {
        "slug": "batted_ball_quality_against_profile",
        "title": "Contact-Quality-Allowed Suppression Profile",
        "summary": "Captures a pitcher's ability to limit hard, optimally-angled contact, measured as barrel rate allowed, average exit velocity allowed, and ground-ball rate induced as the run-suppression-by-weak-contact fingerprint independent of fielding.",
        "stat_signature": "Barrel rate allowed below 5% marks elite contact suppression; above 9% marks vulnerability. Average exit velocity allowed below 87 mph is above-average; above 90 mph is a hard-contact-allowed flag. Hard-hit rate allowed below 30% combined with barrel rate below 5% defines the top-tier contact-suppression profile.",
        "mechanism": "Contact suppression arises from inducing weak contact through three paths: pitch movement that generates mis-hits off the end or top of the barrel; pitch location at zone edges that constrain the hitter's power arc; and sequencing that prevents optimal bat-path alignment. Ground-ball induction specifically limits barrel-rate allowed by pulling hitters downward through the ball rather than through the optimal launch-angle band.",
        "conditions": "Contact suppression profiles are more durable than strand-rate and BABIP profiles because they are independent of fielder positioning and defensive range. They degrade when the pitch-mix deprives the pitcher of their primary weak-contact inducer (e.g., sinker grip injury reducing movement). Extreme hot-hitting stretches shift average exit velocity allowed by 1-2 mph.",
        "magnitude": "Each 1 mph reduction in average exit velocity allowed corresponds to roughly 0.10-0.15 ERA; barrel rate suppression from 8% to 5% is associated with approximately 0.25-0.35 ERA improvement independent of strand rate.",
        "links": ["barrel_zone_contact_profile", "exit_velocity_distribution_profile", "spin_rate_movement_profile", "ground_ball_fly_ball_ratio", "platoon_split_contact_shape"],
    },
    {
        "slug": "platoon_split_contact_shape",
        "title": "Platoon-Split Contact and Arsenal Shape",
        "summary": "Captures how batted-ball shape and pitch usage differ against same-handed versus opposite-handed opponents, measured as the same-hand versus opposite-hand gap in whiff rate, hard-hit rate, and breaking-ball usage as a platoon-vulnerability fingerprint.",
        "stat_signature": "Handedness whiff-rate gap above 8 percentage points marks a strong platoon split; below 3 points marks a platoon-neutral profile. Hard-hit-rate allowed gap above 6 points against same-handed batters signals exploitable vulnerability. Breaking-ball usage shifts of 15+ percentage points by batter handedness signal an arsenal-dependent platoon adjustment.",
        "mechanism": "Same-handed breaking balls carry away from opposite-handed hitters, creating chase situations; against same-handed batters the break runs toward them, reducing deception and making it easier to identify and let the pitch travel. Pitchers dominated by horizontal-break pitches to the glove side show amplified splits because the pitch loses its primary deception dimension against same-handed opponents.",
        "conditions": "Platoon splits amplify in two-strike counts where pitchers go to their put-away pitch, which is typically handedness-dependent. Deep arsenals with opposite-direction movement options allow mitigation of large splits by substituting the opposing-directional offering against the disadvantaged handedness.",
        "magnitude": "Pitchers with platoon whiff gaps above 12 points see ERA splits of 0.50-0.80 by batter handedness; lineup construction that stacks same-handed batters against split-vulnerable pitchers can shift expected run output by 0.3-0.5 runs per game.",
        "links": ["pitch_mix_arsenal_profile", "spray_chart_field_distribution", "pull_side_loft_power_profile", "batted_ball_quality_against_profile", "contact_point_depth_profile"],
    },
    {
        "slug": "popup_and_infield_fly_tendency",
        "title": "Pop-Up and Infield-Fly Tendency",
        "summary": "Captures the rate of near-automatic-out infield flies as both a hitter weakness and a pitcher skill, measured as infield-fly-ball rate (popups per fly ball) against the league band near 9-11% and its link to under-the-ball mishits.",
        "stat_signature": "League-average infield-fly rate near 9-11% of fly balls; rates above 15% mark a severe popup vulnerability in the hitter or elite popup-induction skill in the pitcher. Popup rate correlates with high O-swing rate and extreme uppercut swing planes targeting elevated pitches above the optimal contact window.",
        "mechanism": "Popups arise when the batter swings under the ball with an extreme uppercut path, generating launch angles above 50° with backspin that creates the classic infield-fly trajectory. Pitchers induce popups by elevating hard fastballs (especially high-IVB four-seamers) above the top of the zone, where the hitter's upward swing catches only the bottom quarter of the ball — essentially a barrel miss in the vertical dimension.",
        "conditions": "Popup induction amplifies in two-strike counts where hitters expand zone coverage upward to protect against elevated strikeouts. Pitchers with elite IVB (15+ inches) can reliably generate popups attacking above the hands; flat fastballs at the same location get hit harder because the hitter's upward swing makes solid contact.",
        "magnitude": "Infield-fly rate above 14% suppresses BABIP by approximately 20-30 points relative to fly-ball peers with lower popup rates; each 3-point increase in infield-fly rate yields approximately 0.015-0.020 reduction in wOBA on fly-ball contact.",
        "links": ["launch_angle_distribution_profile", "ground_ball_fly_ball_ratio", "expected_outcome_contact_gap", "whiff_zone_swing_miss_geometry", "velocity_band_profile"],
    },
    {
        "slug": "contact_point_depth_profile",
        "title": "Contact-Point Depth and Bat-Lag Profile",
        "summary": "Captures how deep or out front the ball is met relative to the plate as a timing fingerprint, measured by intercept depth and its split by pitch velocity, separating early-extension pull contact from deep opposite-field contact.",
        "stat_signature": "Pull-contact intercept point is typically ahead of the plate; opposite-field contact depth is 2-4 inches behind home plate. Against elite velocity (97+ mph), average contact depth shifts 1-2 inches deeper, indicating timing compression even for skilled hitters.",
        "mechanism": "Timing determines contact depth: early commitment produces out-front contact with pull-side trajectory; late commitment drives the ball deeper for opposite-field contact. Contact-point depth encodes the hitter's timing signature relative to each pitch type and velocity band, explaining the spray-chart distribution without reference to intent.",
        "conditions": "Contact-point depth compresses against high-velocity pitchers because the available decision-to-swing window shrinks, forcing earlier commitment and pull-bias. Changeup separation exploits this by preserving arm speed while arriving later, catching hitters with out-front bats and generating roll-overs or popups. Late-count fatigue can alter depth distribution within a game.",
        "magnitude": "A 1-inch shift toward deeper contact corresponds to a 4-6 percentage point increase in opposite-field batted-ball rate; pitchers who reliably shift contact depth 2+ inches deeper suppress pull-side HR rates by 20-30% compared with shallow-contact peers.",
        "links": ["spray_chart_field_distribution", "chase_and_zone_swing_profile", "velocity_band_profile", "two_strike_approach_shape", "platoon_split_contact_shape"],
    },
    {
        "slug": "called_strike_zone_shaping",
        "title": "Called-Strike and Edge-Stealing Shape",
        "summary": "Captures a pitcher's ability to generate called strikes on the zone edges and just off it, measured as called-strike rate in the shadow zone and the carry of vertical movement that beats the eye at the top of the zone.",
        "stat_signature": "Shadow-zone called-strike rate above 30% marks elite edge-stealing command. Called-strike-plus-whiff rate (CSW) above 30% is the combined stuff-and-command signature. Top-of-zone called-strike rate above 20% indicates the fastball's vertical carry is deceiving the hitter's frame-of-reference.",
        "mechanism": "The shadow zone (the 2-3 inch band around the strike zone boundary) is where umpire-perception variance and hitter uncertainty overlap. Pitches with high IVB or sharp lateral break carry into and through the shadow from a trajectory that appears to be clearly a ball until the final inches of flight. The underlying pitch trajectory is the pitcher's contribution; pitch-framing skill from the receiver amplifies called-strike conversion on borderline offerings.",
        "conditions": "Edge-stealing is most effective against patient hitters who look for pitches to take; aggressive hitters who expand the zone reduce the value of shadow-zone placement by swinging at the same pitches before they can be called. Late-game command erosion reduces edge-strike rate; pitchers who maintain it into high-leverage situations show superior pitch-quality durability.",
        "magnitude": "CSW rate explains roughly 65-70% of variance in strikeout rate at the pitcher level; a 4-point CSW advantage corresponds to approximately 1.5-2.0 strikeouts per nine innings and a 0.20-0.30 ERA equivalent.",
        "links": ["pitch_location_command_profile", "whiff_zone_swing_miss_geometry", "spin_rate_movement_profile", "first_pitch_attack_profile", "pitch_sequencing_tunnel_profile"],
    },
    {
        "slug": "first_pitch_attack_profile",
        "title": "First-Pitch and Ahead-in-Count Attack Profile",
        "summary": "Captures the location and pitch-type tendency on 0-0 and in pitcher-ahead counts versus hitter-ahead counts, measured as first-pitch strike rate, heart-of-zone rate when ahead, and the count-leverage shift in arsenal usage.",
        "stat_signature": "First-pitch strike rate above 64% marks an aggressive, count-ahead profile; below 56% marks a get-behind tendency with cascading count-leverage disadvantage. Heart-of-zone usage increases when ahead (pitcher-ahead counts have 15-20% more heart-zone pitches than hitter-ahead counts) as pitchers expand the strike zone with confidence.",
        "mechanism": "Count leverage determines which pitches can be thrown safely. Ahead in the count, pitchers can deploy their sharpest breaking balls in the chase zone with low penalty for missing; behind in the count, they must throw more fastballs in the zone to avoid walking the batter. First-pitch strike rate compounds through the at-bat: getting ahead on 0-0 shifts the average wOBA outcome by 0.030-0.050 before any pitch is thrown to the second offering.",
        "conditions": "First-pitch attack tendencies interact with the hitter's 0-0 swing rate; aggressive hitters who attack first pitches nullify the advantage of challenging hitters at 0-0 by making contact before the pitcher earns a called strike. Pitchers with elite control abandon the first-pitch fastball more readily than pitchers who need the zone to establish rhythm.",
        "magnitude": "0-0 strikes correlate with strikeout rate at roughly 0.55 across pitchers; a 6-point first-pitch strike rate advantage is associated with approximately 1.0-1.5 fewer walks per nine innings and 0.15-0.20 lower ERA.",
        "links": ["pitch_mix_arsenal_profile", "called_strike_zone_shaping", "chase_and_zone_swing_profile", "pitch_location_command_profile", "whiff_zone_swing_miss_geometry"],
    },
    {
        "slug": "pitch_location_command_profile",
        "title": "Pitch-Location and Zone-Command Profile",
        "summary": "Captures where in and around the strike zone pitches are located via a nine-box-plus-shadow grid, measured as edge rate, heart-of-zone rate, and shadow-zone rate as a command-and-attack-pattern fingerprint.",
        "stat_signature": "Edge rate (pitches in the outer two columns of the nine-box grid) above 40% marks above-average command; heart-of-zone rate below 20% marks a disciplined approach that avoids the barrel sweet spot. Shadow-zone rate above 15% marks an elite command pitcher exploiting the edges of umpire uncertainty.",
        "mechanism": "Zone location determines which pitches can generate weak contact even without premium movement: edge pitches constrain the hitter's power arc by limiting the angle of attack and contact point. Heart-of-zone pitches face the full power of the hitter's swing and generate the highest average exit velocities allowed. Command-driven suppression of heart-zone rate is the primary mechanism for pitchers with average stuff to outperform velocity-based expectations.",
        "conditions": "Location command degrades under fatigue, stress, and cold conditions that compress mechanical consistency. Hitters who widen their effective zone by protecting the shadow (taking shadow-zone pitches rarely) can exploit command-dependent pitchers. Command is most impactful in pitcher-ahead counts where the shadow zone can be fully exploited with minimal penalty.",
        "magnitude": "Heart-of-zone rate reduction from 25% to 18% is associated with approximately 0.30-0.40 ERA improvement independent of velocity; edge rate above 42% correlates with below-average hard-hit rate allowed even when fastball velocity is 91-93 mph.",
        "links": ["called_strike_zone_shaping", "pitch_sequencing_tunnel_profile", "first_pitch_attack_profile", "batted_ball_quality_against_profile", "spin_rate_movement_profile"],
    },
]
