"""scripts.platformkit.specs.shotprofiles_soccer — ShotProfiles for Soccer.

Dense, person-free shot-profile intelligence concepts for soccer.
Covers per-shot chance quality, zone origination, body-part and technique
distribution, shot-source routing, finishing residuals, and defensive
chance-concession geometry. No edge or market claims. Markets are efficient.
"""
from __future__ import annotations

SPORT = "Soccer"
FAMILY = "ShotProfiles"

CONCEPTS: list[dict] = [
    {
        "slug": "expected_goals_per_shot_profile",
        "title": "Expected-Goals-Per-Shot Quality Profile",
        "summary": "Mean xG per attempt separates selective high-quality-chance attacks from speculative high-volume ones; league average sits near 0.10-0.12 per shot, and sustained deviation above 0.13 marks a structurally disciplined chance-creation process.",
        "stat_signature": "Elite xG/shot >0.13; league average 0.10-0.12; long-range-heavy attack <0.08; year-to-year team correlation ~0.55; stabilizes by match 10 after controlling for set-piece share; separation between top and bottom decile approximately 0.06 xG/shot.",
        "mechanism": "Per-shot xG is driven by decision-making upstream of the attempt: a structure that generates central penalty-area shots off two-touch open-play sequences produces higher per-shot quality than one that accepts peripheral or outside-the-box attempts. Patient chance-selection compounds across a season into a structural xG-per-shot gap.",
        "conditions": "Most informative against organized defensive blocks where speculative attempts rise; quality profile degrades when goal-difference context forces long-range speculation in late game states; set-piece xG/shot is separable and averages ~0.07-0.09 for corners and ~0.25 for direct free kicks.",
        "magnitude": "A 0.03 xG/shot gap at 14 shots/90 adds approximately 0.42 xG/90 of structural quality — equivalent to roughly 15 extra expected goals across a 34-match season without increasing shot volume.",
        "links": ["shot_volume_versus_quality_balance", "big_chance_conversion_profile", "shot_location_zone_map", "post_shot_xg_finishing_profile"],
    },
    {
        "slug": "shot_location_zone_map",
        "title": "Shot-Location Zone Map",
        "summary": "The share of attempts originating from the six-yard box, central penalty area, wide penalty area, edge of box, and outside the box forms a structural chance-quality fingerprint; central-box share is the single strongest zone predictor of attack xG/shot.",
        "stat_signature": "Elite attack: >30% of shots from central penalty area; six-yard box share typically 8-12% (mostly set-piece); outside-the-box share >30% marks a speculative profile; central-box share year-to-year correlation ~0.60; edge-of-box share inflates under high-press game states.",
        "mechanism": "Shot probability is non-linear with distance and angle from goal; the central penalty area at 8-12 yards combines high angle subtended with close range to yield xG near 0.30-0.50 per attempt. An attack that routes a high share of attempts through this zone does so because its build-up and combination sequences consistently penetrate the central defensive block.",
        "conditions": "Zone maps shift against low-block opponents who concede the wide penalty area while sealing the centre; the central-box share is most stable in open-phase matches against pressure-oriented defenses; set-piece attempts inflate the six-yard box share independent of open-play structure.",
        "magnitude": "A 10-point increase in central-penalty-area shot share at fixed shot volume corresponds to an estimated 0.08-0.12 xG/shot improvement and roughly 0.35-0.50 xG/90 of structural gain, mediated entirely through chance-quality rather than volume.",
        "links": ["expected_goals_per_shot_profile", "shot_distance_angle_distribution", "defensive_shot_concession_zone_map", "cutback_and_low_cross_chance_profile"],
    },
    {
        "slug": "shot_distance_angle_distribution",
        "title": "Shot Distance-and-Angle Distribution",
        "summary": "The joint geometry of shot distance to goal and goalmouth-subtended angle — the two primary xG model inputs — characterises structural chance difficulty; the share of attempts inside 12 yards with a wide open angle is the sharpest summary statistic of geometric chance quality.",
        "stat_signature": "League average shot distance ~17-18 meters; elite attack mean ~14-15 meters; average goalmouth angle ~22-26 degrees; inside-12-yards wide-angle share >18% marks a high-quality attack; year-to-year distance correlation ~0.55; angle distribution stabilizes by match 8.",
        "mechanism": "Closer range reduces reaction time for the goalkeeper and increases the proportion of the goal frame exposed; a wider angle simultaneously exposes more of the goal and reduces deflection angles that help the goalkeeper. Attacks that consistently generate the geometric combination do so via central penetration — carries, passes, or set-piece movement into the central box.",
        "conditions": "Distance distribution shifts under late-goal-difference pressure, when attempts from outside the box rise regardless of structural identity; angle distribution is more stable across game states because it reflects positional build-up discipline that is harder to abandon mid-match.",
        "magnitude": "Moving from a mean shot distance of 18 to 14 meters at fixed angle distribution increases xG/shot by approximately 0.04-0.06; combining a 4-meter distance reduction with a 5-degree angle widening raises the per-shot probability by an estimated 0.08-0.12.",
        "links": ["shot_location_zone_map", "expected_goals_per_shot_profile", "long_range_attempt_profile", "shot_on_target_placement_profile"],
    },
    {
        "slug": "shot_type_body_part_profile",
        "title": "Shot-Type and Body-Part Profile",
        "summary": "The share of attempts struck with the right foot, left foot, head, or other (chest, knee) combined with technique class (placed, driven, volley, half-volley) reveals the finishing-route dependency of an attack and its set-piece-and-aerial reliance.",
        "stat_signature": "League average: ~65% right foot, ~22% left foot, ~12% header; header share >18% signals aerial or set-piece dependence; weak-foot share >28% marks a genuinely two-footed attack; header conversion rate approximately 8-10% versus 11-13% for non-headed attempts; technique splits stabilize after 80+ attempts.",
        "mechanism": "Headers are structurally lower-probability attempts because they require aerial timing accuracy, add uncertainty to direction, and are more readable for the goalkeeper; an attack that routes a disproportionate share of chances through headers is partially dependent on aerial physical dominance or set-piece delivery quality. Two-footedness widens the approach-angle envelope, preventing defenders from forcing the attempt onto the weaker side.",
        "conditions": "Body-part profile shifts most strongly against aerial-dominant opposing defenses that force away from central on-the-ground entries; header share rises mechanically when set-piece volume is high; technique class (placed versus driven) is most informative in one-on-one finishing contexts where shot-placement decisions determine outcome.",
        "magnitude": "A 6-point shift from headers to weak-foot attempts at comparable location distributions adds approximately 0.02-0.03 xG/shot on the attempt mix; the aggregate impact across 14 shots/90 is roughly 0.15-0.20 xG/90 of structural quality gain.",
        "links": ["cross_and_aerial_chance_profile", "open_play_versus_set_piece_shot_source", "shot_on_target_placement_profile", "shot_location_zone_map"],
    },
    {
        "slug": "open_play_versus_set_piece_shot_source",
        "title": "Open-Play Against Set-Piece Shot Source",
        "summary": "The share of attempts and xG originating from open play versus dead-ball situations (corners, direct free kicks, penalties) isolates set-piece-channel dependence; attacks with >35% of xG from dead balls rely on a component more sensitive to personnel and specialist quality than open-play structure.",
        "stat_signature": "League set-piece xG share ~25-30%; attacks above 35% are set-piece-reliant; penalty xG carries ~0.76 per attempt; corner-delivered shot xG ~0.07-0.10; direct free-kick attempt xG ~0.07-0.12 depending on distance and wall geometry; set-piece xG/90 year-to-year team correlation ~0.50.",
        "mechanism": "Dead-ball attempts are generated by rehearsed spatial routines independent of flowing build-up quality; a side with structurally weak open-play creation can offset xG totals via set-piece volume, but the two channels face different opponent-adaptation speeds — opponents can disrupt open-play patterns more gradually, while set-piece zonal marking changes can neutralise routines rapidly.",
        "conditions": "Set-piece share rises mechanically when foul frequency is high (pressing-intensive match types) and when the attacking side wins more corners through sustained territorial pressure; direct free-kick frequency is partly a product of opponent pressing intensity near the ball rather than a stable structural trait.",
        "magnitude": "A side generating 0.35 xG/90 from set pieces compared to a league-average 0.18 holds an estimated 6-7 expected-goal dead-ball advantage per season, equivalent to roughly 8-10% of a typical top-division xG total.",
        "links": ["shot_type_body_part_profile", "penalty_and_direct_freekick_profile", "big_chance_conversion_profile", "expected_goals_per_shot_profile"],
    },
    {
        "slug": "big_chance_conversion_profile",
        "title": "Big-Chance Creation and Conversion Profile",
        "summary": "The rate of high-probability scoring opportunities (clear chances, roughly xG above 0.30) generated per 90 and the fraction converted captures both chance-creation quality and finishing composure under low-difficulty conditions; the conversion component is noisier but structurally informative at large samples.",
        "stat_signature": "Elite attack: >2.5 big chances created/90; league average ~1.8-2.0; big-chance conversion rate league average ~28-33%; teams one standard deviation above average convert ~38-42%; big-chance share of total xG >55% marks a structured central-penetration identity; year-to-year big-chance rate correlation ~0.55.",
        "mechanism": "Big chances reflect the upstream success of combination play, runs in behind, and set-piece execution that create central close-range attempts; conversion rates at this chance tier show more persistence than at lower-xG attempts because the primary variance (goalkeeper positioning, defensive last-touch) is smaller relative to attempt quality.",
        "conditions": "Big-chance generation collapses against organised low-block defenses that seal the central box; conversion rate is most stable against opponents conceding big chances regularly (high-block or high-press teams), and more variable against sides whose big-chance concession rate is low and sample sizes are small.",
        "magnitude": "Each additional big chance per 90 over a season contributes approximately 0.09-0.10 additional expected goals per match assuming league-average conversion; a conversion rate gain of 5 points at 2.0 big chances/90 adds roughly 0.10 expected goals per 90 from finishing improvement alone.",
        "links": ["expected_goals_per_shot_profile", "shot_location_zone_map", "cutback_and_low_cross_chance_profile", "through_ball_breakaway_profile"],
    },
    {
        "slug": "shot_on_target_placement_profile",
        "title": "On-Target and Goalmouth-Placement Profile",
        "summary": "Shots-on-target percentage and the post-shot xG uplift from placement into goal corners — away from the goalkeeper's natural position — together capture the accuracy and placement dimension of finishing quality, separable from the underlying chance location.",
        "stat_signature": "League average on-target rate ~34-38%; elite finisher ~42-46%; corner-placed on-target shots add approximately 0.06-0.10 xG above baseline versus central placements at equivalent distance; post-shot xG uplifts from corner placement stabilize at ~100 on-target attempts; on-target rate year-to-year individual correlation ~0.45.",
        "mechanism": "Placement into the lower corners forces a diving save requiring full lateral extension; the goalkeeper's set position creates a larger unsaveable area in the opposite corner when the shot arrives with sufficient speed and placement accuracy. Consistent corner placement is a trainable technical skill with moderate individual persistence.",
        "conditions": "On-target rate fluctuates most at outside-the-box attempts where shot-power and goalkeeper reading interact; placement premiums are largest for driven low shots at 10-18 meters where the goalkeeper's dive is insufficient to cover the full corner; the premium collapses for high lobbed shots where trajectory rather than placement determines outcome.",
        "magnitude": "A 6-point on-target rate gain at fixed shot volume and location adds roughly 0.06-0.08 xG/90 through increased shot-stopping demand; the corner-placement premium of 0.07 xG per on-target shot compounds to approximately 0.20 xG/90 for a high-volume finisher generating 6+ on-target attempts per 90.",
        "links": ["expected_goals_per_shot_profile", "shot_distance_angle_distribution", "post_shot_xg_finishing_profile", "shot_type_body_part_profile"],
    },
    {
        "slug": "first_time_versus_settled_shot_profile",
        "title": "First-Time Against Settled-Touch Shot Profile",
        "summary": "Whether attempts are struck first-time or after a settling touch characterises finishing tempo and difficulty; first-time finishes from cutbacks or crosses demand higher technical precision but arrive before defenders recover position, and from optimal angles they mark the highest-quality open-play central chances.",
        "stat_signature": "League first-time shot share ~35-42%; central cutback first-time shots carry xG ~0.25-0.40 per attempt; settled-touch shots from equivalent positions carry ~0.15-0.22 as defense partially recovers; first-time shot rate year-to-year individual correlation ~0.50; first-time conversion gap versus settled approximately 2-4 percentage points at comparable locations.",
        "mechanism": "A first-time finish denies the goalkeeper time to set position and prevents covering defenders from making a recovery challenge; the xG premium arises because the shot arrives when the defense is mid-transition rather than re-organised. The technical cost is higher timing demand on the striker, which produces more off-target outcomes — making the net effect location-dependent.",
        "conditions": "First-time finish opportunity rate rises against high-pressing opponents who create space centrally through aggressive defensive lines; from wide cutback positions, first-time conversion requires the receiving attacker to face goal or arrive at a narrow angle, making the technical demand highest at extreme wide angles.",
        "magnitude": "Transitioning from a settled-touch profile to a first-time profile at equivalent central locations raises estimated xG/shot by 0.06-0.12 per attempt; compounding across 4 central chances per 90, the aggregate gain is approximately 0.25-0.40 xG/90 of structural quality improvement.",
        "links": ["cutback_and_low_cross_chance_profile", "shot_location_zone_map", "big_chance_conversion_profile", "shot_zone_entry_method_profile"],
    },
    {
        "slug": "cutback_and_low_cross_chance_profile",
        "title": "Cutback and Low-Cross Chance Profile",
        "summary": "Attempts generated from pulled-back balls to the penalty spot or six-yard line are among the highest-xG open-play sources, consistently yielding central first-time shots against an unset goalkeeper; the cutback-originated shot share is a fingerprint of wide-penetration and byline-reaching capability.",
        "stat_signature": "Cutback-generated shots carry mean xG ~0.30-0.45 per attempt; league average cutback share of open-play shots ~8-12%; elite wide-penetration attacks 14-18%; first-time conversion from cutbacks ~22-28%; cutback shot share year-to-year team correlation ~0.55.",
        "mechanism": "A ball played back from the byline or deep wide position arrives at the penalty spot as the goalkeeper is displaced toward the near post, creating a large open-goal area; arriving attackers shoot first-time into this gap before defenders tracking back can intervene. The structural prerequisite is byline-reaching capability — a wide forward or overlapping fullback who defeats the last defender to generate the delivery.",
        "conditions": "Cutback volume rises when opposing defensive lines drop too deep and expose the byline channel; it decreases against high-line and compact-block defenses that maintain a wide-area cover shadow and prevent the run to the byline. The profile is also sensitive to wide-forward technical quality in one-on-one isolation.",
        "magnitude": "Each additional cutback-generated shot per 90 adds an estimated 0.30-0.40 xG/90 of structural quality, making the channel roughly 3-4 times more valuable per attempt than an average open-play shot; a 4-cutback/90 attack holds approximately 1.2-1.5 xG/90 from this channel alone.",
        "links": ["first_time_versus_settled_shot_profile", "shot_zone_entry_method_profile", "big_chance_conversion_profile", "shot_location_zone_map"],
    },
    {
        "slug": "through_ball_breakaway_profile",
        "title": "Through-Ball and Breakaway Chance Profile",
        "summary": "Attempts created by balls played in behind the defensive line, leading to one-on-one or open-angle chances with only the goalkeeper to beat, represent the highest-xG open-play scenario; their share signals transition-speed and depth-run creation capability.",
        "stat_signature": "Through-ball-created chances carry xG ~0.35-0.55 per attempt (one-on-one with goalkeeper); league average through-ball shot share ~5-9%; elite transition attacks 10-14%; one-on-one conversion rate ~40-48%; through-ball-originated shot share year-to-year team correlation ~0.50.",
        "mechanism": "With the defensive line broken and only the goalkeeper to beat, the primary variance determinant shifts from shot location to individual goalkeeper-attacker duel quality; the xG is structurally high because the spatial advantage is maximal. The upstream requirement is a timed diagonal or vertical pass that beats the offside line, combining delivery timing with forward run-depth quality.",
        "conditions": "Through-ball frequency rises against high-defensive-line opponents that leave significant space in behind the backline; it decreases against compact mid-block defenses with shorter defensive lines. The chance is also created by high-press regains that directly isolate a forward in transition before the defense has recovered.",
        "magnitude": "A team generating 1.5 through-ball chances per 90 at average xG 0.40 adds an estimated 0.60 xG/90 from this channel; the through-ball xG premium over an equivalent-location settled attempt from the same position is approximately 0.15-0.25 per chance due to the absence of a set defensive structure.",
        "links": ["big_chance_conversion_profile", "shot_timing_phase_profile", "shot_location_zone_map", "cutback_and_low_cross_chance_profile"],
    },
    {
        "slug": "long_range_attempt_profile",
        "title": "Long-Range Attempt Profile",
        "summary": "Attempts from outside the penalty area represent the lowest-xG open-play source, averaging 3-4% conversion; their share reveals tactical discipline and game-state behavior, with high outside-box share flagging either speculative identity or systematic use of long-range shooting to pull defenses into position.",
        "stat_signature": "Outside-box shot share league average ~35-42%; speculative profile >50%; disciplined attack <28%; outside-box xG/shot ~0.03-0.05; conversion rate ~3-4%; distance distribution peak at 20-25 meters; outside-box shot share year-to-year correlation ~0.60, one of the most stable tactical signatures.",
        "mechanism": "Long-range attempts carry low expected value per attempt because goalkeepers have sufficient reaction time and positioning to cover the majority of the goal frame; the structural contribution is partly tactical — sustained outside-box threats pull defensive blocks wider or deeper, potentially opening central lanes for higher-value attempts.",
        "conditions": "Outside-box attempt frequency rises significantly when a side is behind on the scoreboard in late game states and when deep defensive blocks prevent central box entry; it also rises against compact mid-block opponents who concede space at the edge of the box while sealing the penalty area.",
        "magnitude": "A 10-point reduction in outside-box shot share redirected to central penalty-area attempts at equivalent xG/shot adds approximately 0.05-0.07 xG/90 of structural quality; the reallocation effect is larger than the raw shot-count effect because the destination zone carries 3-6 times the per-shot xG.",
        "links": ["shot_location_zone_map", "shot_volume_versus_quality_balance", "expected_goals_per_shot_profile", "shot_distance_angle_distribution"],
    },
    {
        "slug": "penalty_and_direct_freekick_profile",
        "title": "Penalty and Direct Free-Kick Shot Profile",
        "summary": "Penalties and direct free-kick attempts are discrete high-or-specialized-value shot sources with structurally separated xG distributions; penalties carry fixed ~0.76 xG per attempt, while direct free kicks vary widely with distance, angle, and wall placement.",
        "stat_signature": "Penalty conversion rate league average 75-78%; penalties earned per 90 elite attack ~0.35-0.45; direct free-kick attempt rate top-10 teams ~1.2-1.6/90; direct free-kick xG varies from 0.04 (35+ meters, wide angle) to 0.18 (20 meters, central); penalty rate year-to-year team correlation ~0.55.",
        "mechanism": "Penalties are drawn through forward movement into the penalty area that provokes defensive contact; the earned penalty rate is a structural indicator of central-zone penetration and contact-drawing ability. Direct free kicks from dangerous positions are a specialist output: delivery technique, wall-beating trajectory, and goalkeeper familiarity with the kicker all affect conversion probability systematically.",
        "conditions": "Penalty rate rises against physically aggressive defenses with high-press styles that make contact inside the box; direct free-kick attempts near goal are partly a product of defensive line aggression and foul positioning. Goalkeeper scouting adjustments within a season can reduce direct free-kick conversion rates for identifiable specialist kickers.",
        "magnitude": "A team earning 0.40 penalties per 90 generates approximately 0.30 xG/90 from this channel alone; at 0.20 per 90, the contribution drops to 0.15 xG/90 — a structurally significant gap equivalent to roughly 5-6 expected goals per season.",
        "links": ["open_play_versus_set_piece_shot_source", "big_chance_conversion_profile", "expected_goals_per_shot_profile", "shot_on_target_placement_profile"],
    },
    {
        "slug": "shot_volume_versus_quality_balance",
        "title": "Shot Volume Against Chance-Quality Balance",
        "summary": "Shots per 90 plotted against mean xG per shot separates high-volume speculative attacks from low-volume high-quality ones, revealing whether total xG accumulation is driven by quantity or structural quality of chances — two paths with different opponent-adaptation implications.",
        "stat_signature": "High-volume attack >16 shots/90; low-volume high-quality <11 shots/90 with xG/shot >0.13; both can reach 1.5-1.8 xG/90; the volume-quality product correlation with xG/90 is ~0.85; xG/shot at fixed volume stabilizes by match 10; shot volume stabilizes by match 6.",
        "mechanism": "A volume-first identity typically stems from a pressing structure that generates frequent turnovers in advanced zones, creating many lower-quality attempts; a quality-first identity reflects patient positional build-up that creates fewer but more central attempts. The two styles impose different defensive stresses — high shot volume tests goalkeeper endurance and concentration; high per-shot quality tests blocking accuracy on fewer events.",
        "conditions": "Volume drops sharply against compact low-block defenses that cede space outside the box but seal the central zone; quality per shot rises because only high-quality attempts penetrate the seal. Quality-first attacks see volume inflate against high-press opponents who allow central entry through aggressive line disruption.",
        "magnitude": "For a fixed xG/90 target of 1.6, an attack can achieve this via 16 shots at 0.10 xG/shot or 12 shots at 0.133 xG/shot; the quality route generates 4 fewer goalkeeper events per 90, reducing save-dependency and providing more structural repeatability against varied defensive setups.",
        "links": ["expected_goals_per_shot_profile", "shot_location_zone_map", "long_range_attempt_profile", "expected_goals_against_quality_profile"],
    },
    {
        "slug": "post_shot_xg_finishing_profile",
        "title": "Post-Shot Expected-Goals Finishing Profile",
        "summary": "Post-shot xG accounts for ball placement within the goal frame, yielding a residual versus pre-shot xG that isolates finishing skill from chance location; goals minus xG at the team level regresses sharply, but individual placement-based residuals carry modest persistence across large samples.",
        "stat_signature": "Post-shot xG exceeds pre-shot xG by ~0.02-0.06 for elite placed finishers at comparable locations; individual G-minus-xG persistent skill component requires 80-100 shots to isolate (year-to-year correlation ~0.20-0.25); team-level G-xG year-to-year near zero; psxG uplift from corner placement approximately 0.05-0.08 per on-frame shot.",
        "mechanism": "Pre-shot xG models shot location and assist type but not shot direction within the frame; the post-shot model adds ball trajectory and frame position, capturing the goalkeeper's reach difficulty. Residual skill above psxG reflects consistent above-average placement decisions that beat goalkeeper positioning more often than chance alone.",
        "conditions": "The finishing residual is most meaningful for high-volume finishers who accumulate 60+ shots per season; low-volume finishers have wide confidence intervals that swamp any real signal; the residual conflates placement skill with shot-trajectory deflections on driven shots that are partly random.",
        "magnitude": "A genuine placement-skill premium of +0.04 psxG per shot over 100 shots per season translates to approximately 4 additional goals above expectation from finishing quality alone — a rare but structurally real contribution that compounds over multiple seasons in a stable role.",
        "links": ["shot_on_target_placement_profile", "expected_goals_per_shot_profile", "big_chance_conversion_profile", "expected_goals_against_quality_profile"],
    },
    {
        "slug": "cross_and_aerial_chance_profile",
        "title": "Cross and Aerial-Chance Profile",
        "summary": "Attempts generated from high crosses and lofted deliveries into the box depend on aerial duel success that precedes the attempt; cross-originated shot share and header-from-cross conversion reveal set-piece-adjacent aerial-channel reliance independent of corner and dead-ball routines.",
        "stat_signature": "Cross-originated shot share league average ~18-24%; aerial-dominant attacks 28-34%; header conversion from open-play crosses ~9-12%; crossing accuracy (on-target cross share) elite deliverer >30%, average ~22-25%; contested aerial win rate of the target forward is the leading predictor of header attempt quality.",
        "mechanism": "Open-play aerial chances require a forward who wins contested headers to redirect the ball into the goal frame; conversion is lower than central ground shots because head-to-ball timing, aerial crowding, and deflection randomness all add variance. The upstream requirement is a wide area player capable of accurate crossing from a non-set-piece context.",
        "conditions": "Cross-dependent identity is most effective against wide-back defenses who do not track aerial runs into the box; it decreases against zonal-mark defenses with tall central defenders who consistently win contested aerial balls. Crossing volume also depends on wide-penetration success rate against the opposing fullback.",
        "magnitude": "A team generating 6 cross-originated headers per 90 at 10% conversion and 0.12 xG/header accumulates approximately 0.72 xG/90 from this channel; an aerial-dominant team at 9 such attempts per 90 accumulates roughly 1.00-1.10 xG/90, making it a viable primary chance-creation route.",
        "links": ["shot_type_body_part_profile", "open_play_versus_set_piece_shot_source", "shot_zone_entry_method_profile", "shot_location_zone_map"],
    },
    {
        "slug": "defensive_shot_concession_zone_map",
        "title": "Shot-Concession Zone Map of a Defense",
        "summary": "Where a defensive structure allows opponents to shoot from — the inverse shot-zone map — characterises defensive shape quality; high central-box concession rate marks structural vulnerability, while a high outside-box concession share signals a compact block that surrenders peripheral attempts while sealing the danger zone.",
        "stat_signature": "Central-penalty-area shot concession <25% of opponent shots marks a compact elite defense; >35% signals central structural exposure; outside-box concession share >45% is a compact-block fingerprint; defensive zone map year-to-year team correlation ~0.62; correlation between opponent xG/shot allowed and central-box concession rate ~0.70.",
        "mechanism": "A defensive shape that maintains narrow compactness through the central axis forces opponent attacks wide, restricting central-box shot access; the resulting shot concession map concentrates in peripheral zones with lower per-shot xG. The structural discipline required is collective — all ten outfield players maintaining the central block is more important than any individual defender.",
        "conditions": "Central-box concession rates rise against patient possession attacks that probe slowly for gaps and against teams with elite dribblers who can carry through the central block; the zone map is most stable in mid-table versus mid-table matches; elite attacking opponents force more central concessions regardless of defensive quality.",
        "magnitude": "A defense conceding 20% of shots from the central penalty area versus 30% allows opponents approximately 0.04-0.06 fewer xG per shot, compounding at 12 shots faced per 90 to approximately 0.48-0.72 xGA/90 of structural defensive advantage.",
        "links": ["expected_goals_against_quality_profile", "shot_location_zone_map", "shot_volume_versus_quality_balance", "expected_goals_per_shot_profile"],
    },
    {
        "slug": "expected_goals_against_quality_profile",
        "title": "Expected-Goals-Against Chance-Quality Profile",
        "summary": "Mean xG per shot conceded and big chances allowed per 90 distinguish defenses that suppress chance quality from those that concede shot volume but push attempts to low-probability zones; the per-shot concession quality is the purest structural defensive indicator.",
        "stat_signature": "Elite defense concedes <0.09 xG/shot; average defense 0.10-0.12; permissive defense >0.13; big chances allowed elite <0.8/90, average 1.2-1.5; year-to-year team xG/shot-conceded correlation ~0.58; correlates with defensive-zone map central-concession share at ~0.70.",
        "mechanism": "A compact structure that pushes attempts to outside-the-box and wide-angle positions reduces xG per shot independently of goalkeeper quality; the per-shot xG allowed is therefore a measure of defensive positioning rather than shot-stopping. Separating it from total xGA isolates whether a defense is structurally sound or merely relying on low shot volume.",
        "conditions": "The metric is most interpretable after 10+ matches; it conflates opponent-quality effects when a team plays a severely top-heavy schedule; the measure is more stable against mid-table opponents whose attacking profiles are closer to the league mean.",
        "magnitude": "A 0.03 xG/shot-conceded gap at 12 shots faced per 90 translates to approximately 0.36 xGA/90 of structural defensive quality — roughly 12 expected goals per season of advantage, separating a title-contender defense from a solid mid-table one.",
        "links": ["defensive_shot_concession_zone_map", "shot_volume_versus_quality_balance", "post_shot_xg_finishing_profile", "big_chance_conversion_profile"],
    },
    {
        "slug": "shot_timing_phase_profile",
        "title": "Phase-of-Play and Game-State Shot Timing",
        "summary": "The share of attempts arising from counter-attack, settled possession, and high-press regain phases — and how xG per shot varies across them — reveals whether an attack's quality is concentrated in transition or sustainable through slow build-up, a structural fingerprint with opponent-matchup implications.",
        "stat_signature": "Counter-attack shots carry xG/shot premium of ~0.04-0.08 over settled-possession shots at comparable distances; elite transition teams generate >25% of attempts from counter-attack phases; settled-possession shot share >65% marks a possession-dominant identity; phase distribution year-to-year team correlation ~0.60.",
        "mechanism": "Transition chances exploit disorganized defensive shape in the seconds after a turnover; the xG premium is spatial — fewer defenders between ball and goal and a goalkeeper potentially displaced. A side that generates a high share of attempts from transition phases has an intrinsic xG/shot advantage that does not apply when matched against compact low-block defenses that rarely lose the ball high.",
        "conditions": "Transition shot frequency is highest against aggressive pressing opponents whose shape is temporarily disorganized; against compact low-block defenses, transition chances are rare, forcing a shift to settled-build-up attempts at lower per-shot xG. Game-state dependency: teams trailing by one in the final quarter generate more settled-possession speculative shots, inflating volume at the cost of quality.",
        "magnitude": "An attack generating 30% of shots from transition phases versus 15% gains an estimated 0.06-0.10 xG/90 of structural quality premium solely from phase composition, without any change in shot volume or location distribution.",
        "links": ["through_ball_breakaway_profile", "expected_goals_per_shot_profile", "cutback_and_low_cross_chance_profile", "long_range_attempt_profile"],
    },
]
