"""ShotProfiles — Tennis: person-free, dense shot-pattern and ball-placement concept nodes."""
from __future__ import annotations

SPORT = "Tennis"
FAMILY = "ShotProfiles"

CONCEPTS: list[dict] = [
    {
        "slug": "serve_placement_distribution",
        "title": "Serve-Placement Distribution Profile",
        "summary": "Where serves are directed within each box (wide, body, T) split by deuce and ad court, expressed as placement-zone share and wide-to-T ratio — a directional fingerprint independent of outcome.",
        "stat_signature": "Dominant-pattern threshold: >55% to one zone per court side. Wide-to-T ratio above 2.0 or below 0.5 marks a pattern-locked server. Placement entropy below 0.9 bits flags low directional variety.",
        "mechanism": "Consistent zone targeting forces the returner to pre-read and commit early, but repeated patterns are learned and exploited. Varied placement demands wider return stance coverage, increasing error rates on the return.",
        "conditions": "Deuce-court body serves are most effective against two-handed backhand returners. Ad-court wide serves exploit shorter reach on the forehand side. Pattern value degrades after three consecutive serves to the same zone in a set.",
        "magnitude": "A zone share above 60% for wide serves on the ad court correlates with ~4-6pp lower return points won by the opponent versus a balanced-placement server.",
        "links": ["first_serve_location_tendency", "second_serve_placement_spin_profile", "serve_target_against_return_wing", "serve_plus_one_shot_placement"],
    },
    {
        "slug": "first_serve_location_tendency",
        "title": "First-Serve Location-and-Spread Tendency",
        "summary": "Directional spread and predictability of the first serve, captured as placement entropy across three target zones and the share hit to the dominant corner — distinguishing varied servers from pattern-locked ones.",
        "stat_signature": "Placement entropy: 1.4-1.58 bits = maximally varied (equal thirds); below 1.0 = pattern-locked. Dominant-zone share above 60% is structurally readable. Match-to-match entropy stability r ~0.60.",
        "mechanism": "A varied first serve denies the returner pre-read advantage; a pattern-locked server gives away initiative even when pace is high. Information value of placement is highest against aggressive returners who commit early.",
        "conditions": "Entropy advantage is largest against returners who shade early on a well-telegraphed pattern. Wind disrupts placement control and raises effective entropy involuntarily.",
        "magnitude": "Shifting from a dominant-zone share of 65% to 45% is estimated to reduce first-serve return points won by ~2-4pp by eliminating early returnner pre-positioning.",
        "links": ["serve_placement_distribution", "serve_speed_distribution_profile", "serve_target_against_return_wing", "second_serve_placement_spin_profile"],
    },
    {
        "slug": "second_serve_placement_spin_profile",
        "title": "Second-Serve Placement-and-Spin Profile",
        "summary": "Location and spin shape of the second serve under risk constraint — measured as kick-to-flat ratio, share placed to the backhand corner, and body-jam rate as an attack-suppression signature.",
        "stat_signature": "Elite kickers: >65% of second serves with heavy topspin; body-jam rate >20% on ad-court second serves. Backhand-corner placement share >55% typical against two-handed returners. Double-fault rate below 2.0% per service game.",
        "mechanism": "A high-bouncing kick serve to the backhand corner pushes the returner back and narrows the attack angle; a body jam jams the swing path. Spin variation prevents loading a comfortable returner groove on repeated second serves.",
        "conditions": "Kick effectiveness is highest on clay (amplified bounce) and against short-swing backhand returners. On grass the skid reduces kick benefit; body jams remain effective on all surfaces.",
        "magnitude": "A body-jam rate above 25% on the ad-court second serve suppresses second-serve return aggression by ~3-5pp versus a purely wide or T second serve.",
        "links": ["serve_placement_distribution", "first_serve_location_tendency", "return_depth_and_placement_profile", "serve_target_against_return_wing"],
    },
    {
        "slug": "serve_speed_distribution_profile",
        "title": "Serve-Speed Distribution Profile",
        "summary": "Speed bands of first and second serves and the gap between them — measured as mean first-serve speed, first-to-second-serve speed differential, and share of first serves above a high-velocity threshold.",
        "stat_signature": "Elite first-serve speed: >195 km/h on hard courts. First-to-second-serve gap above 40 km/h signals heavy second-serve risk aversion. Share of first serves above 210 km/h: top-tier >30%. Speed SD within a match: ~8-12 km/h typical.",
        "mechanism": "High-velocity first serves compress reaction time below 0.45 s, limiting return to a block. A large speed gap exposes the second serve to attack; a deliberately throttled but placed first serve can outperform a raw-pace approach at lower in-rates.",
        "conditions": "Speed advantage largest on hard courts and grass; clay bounce absorption reduces raw-pace return on impact. Altitude increases ball speed by ~1-3%, marginally shifting the threshold.",
        "magnitude": "Each 10 km/h of average first-serve speed correlates with ~1.5-2pp of additional first-serve points won, up to ~210 km/h where placement limits further gains.",
        "links": ["first_serve_location_tendency", "serve_placement_distribution", "serve_plus_one_shot_placement", "court_surface_shot_profile_shift"],
    },
    {
        "slug": "serve_plus_one_shot_placement",
        "title": "Serve-Plus-One Shot-Placement Profile",
        "summary": "Where the third ball is directed after the serve — into the opened court, behind the returner, or to the weaker wing — measured as plus-one direction share and forehand-after-serve rate as a first-strike-construction fingerprint.",
        "stat_signature": "First-strike specialists hit into the opened court >60% on third-ball opportunities. Forehand-after-serve rate above 55% marks a deliberate pattern. Inside-out-forehand rate on the plus-one: elite >35%.",
        "mechanism": "A wide serve opens the deuce court; a third-ball forehand into the vacated space is a geometric free point. Behind-returner placement exploits lateral momentum. The pattern is most potent when serve placement and plus-one direction are co-designed.",
        "conditions": "Pattern is most usable when the first serve lands in (no second-serve re-positioning). Against deep returners who redirect cross-court, the opened space closes before the third ball arrives.",
        "magnitude": "A coherent serve-plus-one scheme raises third-ball winner or forced-error rate by ~8-12pp versus an unstructured approach on the same first-serve percentage.",
        "links": ["serve_placement_distribution", "rally_shot_direction_pattern", "forehand_backhand_shot_balance", "net_approach_and_volley_profile"],
    },
    {
        "slug": "return_depth_and_placement_profile",
        "title": "Return Depth-and-Placement Profile",
        "summary": "Where returns land in the service box and how deep they penetrate — measured as return-depth distribution and deep-return rate — as a serve-neutralisation fingerprint.",
        "stat_signature": "Elite neutralising return: >55% of returns landing in the back third of the court (within 1m of baseline). Short-ball rate (landing in middle third or shallower) below 20% marks an elite returner. Deep-return rate r ~0.58 season-to-season.",
        "mechanism": "A deep return pushes the server to strike from behind the baseline, reducing available angles and compressing the attack window. Short returns gift an attackable mid-court ball and shift rally initiative to the server.",
        "conditions": "Deep-return rate most critical on second serves where the returner can load up. Against wide or jam serves, return depth naturally drops; the quality signal is the depth rate conditional on clean contact.",
        "magnitude": "Improving deep-return rate from 45% to 58% on second serves corresponds to roughly 3-4pp additional second-serve return points won across a match.",
        "links": ["return_contact_position_profile", "second_serve_placement_spin_profile", "rally_shot_direction_pattern", "defensive_shot_recovery_profile"],
    },
    {
        "slug": "return_contact_position_profile",
        "title": "Return Contact-Position and Aggression Profile",
        "summary": "Where the returner makes contact relative to the baseline — inside, on, or behind — as a return-stance fingerprint, measured as mean return-contact depth and the share of returns taken on the rise.",
        "stat_signature": "Aggressive stance: >35% of second-serve returns contacted inside the baseline. On-the-rise share above 25% on first serves marks exceptional reaction speed. Contact-depth stability r ~0.62 across matches.",
        "mechanism": "Contacting the ball on the rise inside the baseline cuts the server's recovery time, compressing the point. It requires early racket preparation and exceptional split-step timing; errors rise when execution is rushed.",
        "conditions": "Most effective on medium-to-slow hard courts and clay where server recovery is slower. On grass the additional bounce acceleration makes inside-baseline contact on first serves extremely high-risk.",
        "magnitude": "An inside-baseline contact share above 35% on second serves raises second-serve return points won by ~3-5pp versus standing behind the baseline.",
        "links": ["return_depth_and_placement_profile", "backhand_wing_targeting_profile", "shot_tempo_and_strike_timing", "first_strike_short_point_profile"],
    },
    {
        "slug": "rally_shot_direction_pattern",
        "title": "Rally Shot-Direction Pattern",
        "summary": "Directional tendencies within rallies — cross-court dominance, down-the-line redirect rate, inside-out angle share — measured as cross-to-down-line ratio and redirect frequency as a rally-construction fingerprint.",
        "stat_signature": "Cross-court dominance: >65% of groundstrokes going cross-court marks a safety-first constructor. Down-the-line redirect rate above 20% marks a proactive pattern-shifter. Inside-out forehand rate above 18% is a separation signal.",
        "mechanism": "Cross-court paths offer the longest court dimension and lowest net clearance risk; down-the-line redirects change the rally geometry and expose the opponent's open court. Pattern variety raises the opponent's reading load.",
        "conditions": "Down-the-line redirects carry highest error risk on clay against heavy-topspin opponents who recover cross-court fast. Inside-out forehands most effective when the rally has shifted the opponent wide to their forehand.",
        "magnitude": "A down-the-line redirect rate above 22% combined with >55% successful executions is estimated to yield ~3-5 extra winners or forced errors per set versus a purely cross-court constructor.",
        "links": ["forehand_backhand_shot_balance", "winner_and_error_shot_geometry", "serve_plus_one_shot_placement", "backhand_wing_targeting_profile"],
    },
    {
        "slug": "forehand_backhand_shot_balance",
        "title": "Forehand-to-Backhand Shot Balance",
        "summary": "Wing-usage distribution and the tendency to run around the backhand — measured as forehand share of groundstrokes, inside-out and inside-in forehand rate, and forehand-to-backhand winner ratio — as a wing-dominance signature.",
        "stat_signature": "Run-around rate above 25% marks a clear forehand-dominant pattern. Forehand share of groundstrokes above 58% combined with a forehand winner-to-backhand-winner ratio above 2.5 identifies a strong wing asymmetry.",
        "mechanism": "Running around the backhand gains forehand weaponry at a footwork cost; if the exposed court is insufficiently covered the pattern backfires. A balanced-wing player avoids the positional gamble.",
        "conditions": "Run-around pattern most viable on clay where rallies are long enough to set up the position. On fast surfaces the time cost of repositioning is too high against aggressive servers.",
        "magnitude": "A run-around rate above 30% that successfully generates inside-out forehands yields roughly 2-4 additional winner opportunities per set but exposes the ad-court diagonal to counter-attacks.",
        "links": ["rally_shot_direction_pattern", "backhand_wing_targeting_profile", "winner_and_error_shot_geometry", "serve_plus_one_shot_placement"],
    },
    {
        "slug": "shot_depth_and_court_position",
        "title": "Groundstroke Depth-and-Court-Position Profile",
        "summary": "How deep groundstrokes land and where the hitter stands relative to the baseline — measured as deep-ball rate (landing inside the back third of court) and mean court position — as a territorial-control fingerprint.",
        "stat_signature": "Territorial aggressor: >60% of rally groundstrokes landing in the back third. Baseline position: elite attackers average 0.5m inside the baseline during rally; defenders stand 1.5-2m behind. Deep-ball rate stability r ~0.57.",
        "mechanism": "Deep groundstrokes push the opponent back and shrink available return angles. Court position inside the baseline converts opponent-generated pace into forward momentum, compressing rally time.",
        "conditions": "Inside-baseline court position is most sustainable on clay and medium-hard courts with high bounce. Wind disrupts reliable depth control, shifting both distributions toward mid-court landings.",
        "magnitude": "A deep-ball rate above 60% combined with inside-baseline positioning suppresses opponent winner opportunities by ~5-8pp relative to a neutral-depth, baseline-standing pattern.",
        "links": ["rally_shot_direction_pattern", "shot_tempo_and_strike_timing", "defensive_shot_recovery_profile", "winner_and_error_shot_geometry"],
    },
    {
        "slug": "winner_and_error_shot_geometry",
        "title": "Winner and Forced-Error Shot Geometry",
        "summary": "Where and how points are ended via clean strike — winner location, down-line versus cross, drive versus angle — measured as winner-zone share and winner-to-unforced-error ratio as an offensive-shot-quality fingerprint.",
        "stat_signature": "Down-the-line winner share above 35% marks an angle-variety weapon. Winner-to-unforced-error ratio above 1.2 on a hard court is clean aggression. Cross-court angles below service-line: share above 20% flags a sharp-angle pattern.",
        "mechanism": "Winners into corners demand the highest ball-speed or angle precision; repeated clean execution reveals technique under pressure rather than lucky errors. The ratio decomposes offensive quality from inconsistency.",
        "conditions": "Down-the-line winner share rises on fast surfaces (less recovery time); angle winners are more frequent on clay (more time to set up). Ratio drops on windy days due to involuntary unforced errors.",
        "magnitude": "A winner-to-unforced-error ratio above 1.3 sustained across a match corresponds to roughly 6-8 net-offensive-point advantage versus a balanced-error opponent.",
        "links": ["forehand_backhand_shot_balance", "rally_shot_direction_pattern", "net_approach_and_volley_profile", "shot_depth_and_court_position"],
    },
    {
        "slug": "net_approach_and_volley_profile",
        "title": "Net-Approach and Volley-Placement Profile",
        "summary": "How often and from where the player approaches the net and where volleys are placed — measured as approach frequency, net-points-won rate, and share of approaches behind an attacking down-line ball as a forward-game signature.",
        "stat_signature": "Net-attack style: >20 approaches per set. Net-points-won rate above 68% is the structural threshold; below 60% signals a net liability. Down-line approach share above 55% is the positional hallmark of a sound net game.",
        "mechanism": "A well-struck down-the-line approach shot gives the volleyer inside position at the net; the opponent's passing-shot angle is geometrically compressed. Approaching behind a cross-court ball widens the passing lane.",
        "conditions": "Net approaches most productive on grass and fast hard courts where passing shots are harder to execute. Least effective on clay against heavy-topspin baseliners with elite dip passing shots.",
        "magnitude": "A net-points-won rate above 70% over 20+ approaches in a set generates ~2-3 structurally earned points beyond baseline-only expectations.",
        "links": ["serve_plus_one_shot_placement", "winner_and_error_shot_geometry", "drop_shot_and_touch_profile", "rally_shot_direction_pattern"],
    },
    {
        "slug": "drop_shot_and_touch_profile",
        "title": "Drop-Shot and Touch-Shot Profile",
        "summary": "Usage and placement of drop shots and short angles as court-geometry-altering changes of pace — measured as drop-shot frequency, conversion rate, and share deployed from inside the baseline as a disruption signature.",
        "stat_signature": "Disruptive deployers: >3 drop shots per set. Conversion rate above 58% marks effective usage; below 45% signals misreading of opponent positioning. Inside-baseline deployment share above 65% is structurally sound; from behind baseline conversion drops ~15pp.",
        "mechanism": "A drop shot forces a deep-positioned opponent to sprint forward under pressure, disrupting both rhythm and court position. Effective deployment requires reading opponent fatigue, stance, and recovery speed in real time.",
        "conditions": "Most effective on clay in long rallies against tired opponents standing deep. Least effective on grass where the low skid keeps balls away from short targets and opponent reaction time is faster.",
        "magnitude": "A drop shot deployed on a 58%+ conversion rate from an inside-baseline position creates forced-error pressure equivalent to ~1-2 additional unforced errors per set induced from the opponent.",
        "links": ["net_approach_and_volley_profile", "topspin_slice_shot_shape", "shot_depth_and_court_position", "defensive_shot_recovery_profile"],
    },
    {
        "slug": "topspin_slice_shot_shape",
        "title": "Topspin-and-Slice Shot-Shape Profile",
        "summary": "Spin composition of groundstrokes — heavy topspin loop, flat drive, backhand slice — measured as estimated rally spin distribution and backhand-slice rate as a ball-flight and bounce-height fingerprint that shapes the opponent's strike zone.",
        "stat_signature": "Heavy topspin profile: estimated >2,500 RPM average on forehand groundstrokes. Backhand-slice rate above 35% marks a slice-reliant pattern. Flat-drive share above 30% flags a pace-first approach.",
        "mechanism": "Heavy topspin lifts the bounce above shoulder height on clay, forcing opponents to absorb pace from a mechanically disadvantaged position. Slice stays low and skids on grass, disrupting opponent timing. Spin variety makes ball-strike prediction harder.",
        "conditions": "Topspin bounce advantage greatest on clay; neutralised on grass. Slice backhand effectiveness highest on fast surfaces where skid is pronounced. Mixed spin patterns most disruptive against opponents with a fixed return-strike-zone preference.",
        "magnitude": "A backhand-slice rate above 35% against a topspin-dependent opponent on grass is estimated to shift the opponent's unforced-error rate up by ~3-4pp as strike-zone comfort is disrupted.",
        "links": ["rally_shot_direction_pattern", "drop_shot_and_touch_profile", "court_surface_shot_profile_shift", "shot_tempo_and_strike_timing"],
    },
    {
        "slug": "backhand_wing_targeting_profile",
        "title": "Backhand-Wing Targeting and Exposure Profile",
        "summary": "Tendency to direct the ball at the opponent's backhand and the resulting exposure, measured as the rally-ball-to-backhand share generated and conceded — a weakness-attacking and weakness-protecting pattern fingerprint.",
        "stat_signature": "Deliberate backhand-targeting rate above 60% in rally-ball distribution marks a structurally committed attack. Conceded backhand-targeting rate above 65% signals measurable wing weakness. Backhand winner-to-error ratio below 0.6 confirms exploitable exposure.",
        "mechanism": "Directing cross-court to the opponent's backhand compounds the geometric disadvantage for two-handed players with limited reach and for one-handed players facing high-bounce topspin. Sustained targeting overloads one limb and disrupts rally-direction flexibility.",
        "conditions": "Most effective against one-handed backhand players on clay where kick serves and heavy topspin produce above-shoulder strikes. Against two-handed players the targeting advantage is smaller but the run-around cost is higher.",
        "magnitude": "A backhand-error-rate elevation of 4-6pp when targeting is above 65% corresponds to roughly 2-3 additional forced errors per set induced through deliberate pattern construction.",
        "links": ["rally_shot_direction_pattern", "forehand_backhand_shot_balance", "serve_target_against_return_wing", "topspin_slice_shot_shape"],
    },
    {
        "slug": "serve_target_against_return_wing",
        "title": "Serve-Targeting Against the Return Wing",
        "summary": "How serve placement is chosen relative to the returner's stronger and weaker wings — measured as share of serves directed to the backhand return and body-serve jam rate as a return-suppression placement signature.",
        "stat_signature": "Backhand-targeting serve share above 55% marks a deliberate wing-attack strategy. Body-jam rate above 18% signals a variety-based jam pattern. Against a known weak-wing returner, targeting share above 65% in opening games is measurable.",
        "mechanism": "A targeted serve to the weaker wing raises the likelihood of a short or defensive return, shortening the ensuing rally and enabling third-ball attack. Body jams neutralise timing by eliminating the swing path.",
        "conditions": "Wing targeting is most exploitable on second serves where the returner has time to set up but has committed stance-wise. On first serves the pace limits the returner's ability to adjust regardless of direction.",
        "magnitude": "Raising backhand-targeting serve rate from 50% to 65% against a clear weak-wing returner is estimated to lower second-serve return points won by ~3-5pp.",
        "links": ["serve_placement_distribution", "second_serve_placement_spin_profile", "backhand_wing_targeting_profile", "first_serve_location_tendency"],
    },
    {
        "slug": "court_surface_shot_profile_shift",
        "title": "Surface-Driven Shot-Profile Shift",
        "summary": "How shot location, rally length, and spin usage change across fast and slow surfaces — measured as the surface delta in ace rate, mean rally length, and net-approach frequency as a surface-adaptation fingerprint.",
        "stat_signature": "Ace rate delta (grass versus clay) above 2.5 per match flags a surface-dependent serve. Mean rally-length shift above 1.8 shots per point between surfaces marks a significant style adjustment. Net-approach frequency delta above 8 per set between surfaces is a tactical pivot signal.",
        "mechanism": "Fast surfaces reward flat first-strike and net approaches; slow surfaces reward heavy topspin and extended rallies. A player with a rigid shot profile shows large deltas; an adaptable player compresses the delta through spin-speed manipulation.",
        "conditions": "Surface adaptation signals are most readable in the first two matches on a new surface after a cross-surface transition. Early-season adaptation lags widen the measured delta beyond the structural baseline.",
        "magnitude": "A rally-length delta above 2 shots per point between clay and grass corresponds to a fundamentally different competitive environment; adapters compress this to below 1 shot through tactical shot-shape adjustments.",
        "links": ["topspin_slice_shot_shape", "serve_speed_distribution_profile", "net_approach_and_volley_profile", "shot_tempo_and_strike_timing"],
    },
    {
        "slug": "shot_tempo_and_strike_timing",
        "title": "Shot-Tempo and Ball-Strike Timing Profile",
        "summary": "How early the ball is taken and the tempo imposed on rallies — measured as mean contact timing relative to the bounce apex and the on-the-rise strike rate as a time-pressure-imposing fingerprint distinct from raw shot speed.",
        "stat_signature": "On-the-rise groundstroke rate above 30% marks a genuine tempo aggressor. Average contact timing above the bounce apex (early zone): elite tempo players achieve this on >40% of mid-rally strikes. Match-to-match stability r ~0.58.",
        "mechanism": "Contacting the ball before it drops from its apex cuts the opponent's recovery window by 0.15-0.25 s, effectively converting a neutral rally ball into a time-pressure shot without requiring additional pace. Requires exceptional anticipation and early backswing.",
        "conditions": "Tempo pressing is most effective against slow-paced players on hard courts where bounce is predictable. On clay the higher bounce and slower pace make apex timing easier but also give opponents more recovery time.",
        "magnitude": "Sustaining an on-the-rise contact rate above 35% across a full match compresses average opponent recovery time by ~0.2 s per rally shot — equivalent structurally to a ~15 km/h pace increase.",
        "links": ["return_contact_position_profile", "shot_depth_and_court_position", "topspin_slice_shot_shape", "court_surface_shot_profile_shift"],
    },
]
