"""MLB Situational context concepts — person-free, descriptive intelligence nodes."""
from __future__ import annotations

SPORT = "MLB"
FAMILY = "Situational"

CONCEPTS: list[dict] = [
    {
        "slug": "starter_days_rest",
        "title": "Starting-Pitcher Days-of-Rest Effect",
        "summary": "The gap between starts reshapes command and endurance. Three days compresses recovery; six-plus days disrupts mechanical routine built through regular bullpen work.",
        "stat_signature": "Three days rest: ERA rises ~0.40–0.65 runs, BB/9 up 0.4–0.7. Six-plus days: K/9 dips ~0.5, first-inning ERA inflates ~0.30 runs versus four-day baseline.",
        "mechanism": "Arm recovery follows a fatigue-then-adaptation curve; short rest leaves residual neuromuscular fatigue suppressing velocity and spin rate; excess layoff disrupts release-point consistency developed through routine.",
        "conditions": "Strongest for high-pitch-count prior outings (100-plus), cold-weather early-season starts, and power pitchers whose velocity-dependent secondaries degrade acutely under fatigue.",
        "magnitude": "Short-rest effect: roughly 0.4–0.65 ERA increase, 0.5–1.0 WHIP deterioration. Extended-rest rust: first-inning scoring rate 15–20 percent above same-pitcher average.",
        "links": ["bullpen_usage_fatigue", "times_through_order_penalty", "doubleheader_load"],
    },
    {
        "slug": "bullpen_usage_fatigue",
        "title": "Bullpen Cumulative-Usage Fatigue",
        "summary": "Relievers appearing on back-to-back or three consecutive days show measurable velocity loss and command degradation; rolling three-day pitch totals compound single-appearance counts.",
        "stat_signature": "Day-2 appearance: velocity down 0.4–0.8 mph, BB/9 up ~1.0–1.5. Day-3: ERA rises ~0.8–1.2 runs above season average; whiff rate drops ~2.5 percentage points.",
        "mechanism": "High-effort contractions accumulate micro-damage in rotator cuff and forearm flexors; incomplete glycogen resynthesis between same-day-turnaround outings disrupts proprioceptive release-point consistency that drives command.",
        "conditions": "Amplified in extra-inning games, doubleheaders, and post-high-leverage outings. Thin bullpen rosters see greater per-pitcher exposure; late-season back-to-back series most exposed.",
        "magnitude": "Three-consecutive-day usage: run prevention deteriorates roughly 1.0–1.4 ERA units above baseline; walk rate rises one-third above individual norm.",
        "links": ["starter_days_rest", "late_and_close_state", "extra_innings_ghost_runner", "doubleheader_load"],
    },
    {
        "slug": "times_through_order_penalty",
        "title": "Times-Through-the-Order Penalty",
        "summary": "Hitters accumulate within-game information on a starter with each successive look, systematically improving outcomes from the first time through the lineup to the third.",
        "stat_signature": "First time through order: OPS against ~0.680–0.710. Second time: ~0.720–0.750. Third time: ~0.760–0.810. wOBA rises ~0.025–0.040 per sequential pass.",
        "mechanism": "Hitters pattern-match pitch sequencing and arm-slot across repeated exposures; pitchers simultaneously exhaust tunneling variation and fatigue, narrowing effective arsenal and reducing early-game deception advantage.",
        "conditions": "Effect largest for pitchers with fewer than three distinct offerings and in high-run environments. Dominant strikeout pitches partially reset the information advantage regardless of lineup pass.",
        "magnitude": "Third-time-through OPS disadvantage of roughly 0.080–0.130 above first-time-through; ~0.3–0.5 additional expected runs per nine innings in the third pass.",
        "links": ["starter_days_rest", "high_leverage_index_state", "count_leverage_states", "platoon_handedness_context"],
    },
    {
        "slug": "high_leverage_index_state",
        "title": "High-Leverage-Index Situations",
        "summary": "Leverage index quantifies win-probability swing per plate appearance. High-LI contexts (LI above 1.5) draw optimal bullpen deployment, producing reliably different run-prevention rates than low-LI situations.",
        "stat_signature": "LI above 2.0: closer-class ERA ~2.80–3.20 deployed; scoring rate ~15–20 percent below league average. LI below 0.5: mop-up ERA exceeds 5.00; scoring rate 20–25 percent above average.",
        "mechanism": "Managers allocate top relievers to the highest-LI states; the selection effect suppresses scoring beyond individual reliever quality. Hitter swing conservatism also rises on borderline pitches under high-LI.",
        "conditions": "Strongest in one-run games in the seventh inning or later with the tying run on base. Weakens in parks with thin bullpen depth due to roster constraints.",
        "magnitude": "Roughly 15–22 percent run-prevention improvement relative to league average in LI-above-2.0 contexts; wOBA against top-closer tier in these states ~0.260–0.285.",
        "links": ["late_and_close_state", "bullpen_usage_fatigue", "runners_in_scoring_position", "platoon_handedness_context"],
    },
    {
        "slug": "late_and_close_state",
        "title": "Late-and-Close Game State",
        "summary": "Plate appearances in the seventh inning or later within a defined run margin (typically two runs) represent bullpen optimization and heightened situational decision-making from both dugouts.",
        "stat_signature": "Innings 7-plus, within two runs: league OPS ~0.680–0.710 versus ~0.740–0.760 in blowout states. Strikeout rate rises ~1.5–2.5 K/9; walk rate rises ~0.5–1.0 BB/9.",
        "mechanism": "Managers deploy high-spin velocity specialists when a single hit substantially alters win probability. Hitters shift toward contact-first swings, paradoxically raising strikeout rates when facing elite velocity.",
        "conditions": "Run-scored rate lowest due to selective deployment; sample biases accumulate when the trailing team's offense faces superior roster-depth relievers in neutral park environments.",
        "magnitude": "Scoring rate suppressed roughly 8–15 percent below full-game average; closer-class ERA differential in this state roughly 1.0–1.8 runs below season ERA.",
        "links": ["high_leverage_index_state", "bullpen_usage_fatigue", "intentional_walk_setup", "sacrifice_small_ball_context"],
    },
    {
        "slug": "runners_in_scoring_position",
        "title": "Runners-in-Scoring-Position Context",
        "summary": "A runner on second or third restructures both sides: pitchers work zone edges to avoid RBI contact while hitters shift toward contact approaches to avoid leaving runners stranded.",
        "stat_signature": "BA with runners in scoring position versus bases-empty: league-wide delta ~-0.010 to +0.010 (high variance). Contact rate rises ~1.5–2.0 points; K/9 falls ~0.8–1.2 in this state.",
        "mechanism": "Pitchers elevate strikeout-pitch frequency at zone edges exploiting heightened aggression; hitters protect the plate with two strikes, compressing swing-and-miss and collapsing the BA gap into a near-equilibrium.",
        "conditions": "Sharpest in late-and-close states where a single run is decisive. Handedness matchup and foul-territory size modulate how much contact-first adjustment translates into base hits.",
        "magnitude": "Runner-in-scoring-position scoring probability roughly 55–62 percent versus 27–32 percent from first base; contact rate improvement roughly 1.5–2.0 percentage points.",
        "links": ["high_leverage_index_state", "bases_loaded_leverage", "count_leverage_states", "platoon_handedness_context"],
    },
    {
        "slug": "bases_loaded_leverage",
        "title": "Bases-Loaded Pressure Context",
        "summary": "The bases-loaded state maximizes run-expectancy and forces extreme strategic corners: any ball becomes a run and any strikeout ends the inning at no cost to the pitcher.",
        "stat_signature": "Walk rate in bases-loaded at-bats: ~9–11 percent versus ~8–9 percent overall. Run-expectancy ~2.3–2.5 runs for remainder of inning. Strikeout rate dips ~1.0–1.5 K/9 as pitchers emphasize strikes.",
        "mechanism": "Pitchers must throw strikes to avoid automatic runs via walk, compressing their arsenal toward higher-contact types; hitters have discipline incentive to take borderline pitches, raising walk rates even as pitchers challenge the zone.",
        "conditions": "Effect largest in late-close states with a closer-class pitcher willing to challenge with velocity-only approaches. Small-park environments amplify the cost of contact and heighten the strategic tension.",
        "magnitude": "Grand-slam probability per at-bat roughly 1.5–2.5 percent; bases-loaded walk rate exceeds bases-empty by roughly 1.0–2.5 percentage points league-wide.",
        "links": ["runners_in_scoring_position", "intentional_walk_setup", "high_leverage_index_state", "count_leverage_states"],
    },
    {
        "slug": "extra_innings_ghost_runner",
        "title": "Extra-Innings Automatic-Runner Regime",
        "summary": "The automatic runner on second base beginning each extra half-inning inflates scoring probability and reshapes small-ball deployment and walk-off distribution relative to standard innings.",
        "stat_signature": "Runs per extra half-inning: ~0.50–0.60 versus ~0.46 in standard innings. Walk-off probability per half-inning roughly 25–35 percent. Sacrifice-attempt rate rises ~3–5 times above standard-inning frequency.",
        "mechanism": "Starting each half-inning with a runner on second shifts run-expectancy from ~0.48 to ~1.10, compressing strategy toward manufactured-run small-ball and raising intentional-walk usage to set force-outs.",
        "conditions": "Amplified when both bullpens are fatigued from prior extra innings, limiting pitcher-quality depth. Trailing teams face asymmetric pressure to play for the tie rather than a multi-run inning.",
        "magnitude": "Runs per extra inning roughly 10–15 percent above standard-inning rate; game-ending in the tenth inning probability roughly 35–40 percent.",
        "links": ["bullpen_usage_fatigue", "sacrifice_small_ball_context", "intentional_walk_setup", "late_and_close_state"],
    },
    {
        "slug": "count_leverage_states",
        "title": "Ball-Strike Count Leverage States",
        "summary": "Each ball-strike count carries a distinct run value and reshapes both pitcher and hitter decision trees; two-strike and three-ball counts represent the highest-leverage within-at-bat states.",
        "stat_signature": "3-0 count: hitter run value ~+0.20. 0-2 count: pitcher run value ~+0.17. BA on 3-2 versus 0-2: roughly 0.280 versus 0.160. Swing rate on 3-0: roughly 12–18 percent.",
        "mechanism": "Favorable counts allow hitters to sit on predictable pitch types in preferred zones; unfavorable counts force zone-expansion that inflates chase rate and whiff rate on secondary pitches deliberately placed at zone periphery.",
        "conditions": "Effect largest against high-walk-rate pitchers who frequently reach three-ball counts; diminished against strike-throwers who maintain zone efficiency and avoid deep counts entirely.",
        "magnitude": "Two-strike strikeout rate roughly 2.5–3.5 times at-bat average; three-ball walk probability roughly 25–38 percent depending on pitcher-walk-rate tier.",
        "links": ["platoon_handedness_context", "runners_in_scoring_position", "bases_loaded_leverage", "times_through_order_penalty"],
    },
    {
        "slug": "platoon_handedness_context",
        "title": "Platoon Handedness Matchup State",
        "summary": "Same-handed pitcher-hitter confrontations favor the pitcher while opposite-handed matchups favor the hitter; the split magnitude drives late-game substitution patterns and roster construction.",
        "stat_signature": "Platoon split OPS gap (opposite-hand advantage): roughly 0.040–0.070. Left-hand hitter against left-hand pitcher OPS roughly 0.680–0.700; against right-hand pitcher roughly 0.730–0.760.",
        "mechanism": "Opposite-hand pitchers deliver breaking balls that move into the hitter's eye-line from a more visible angle; same-hand breaking balls move away from the barrel, reducing squared-contact probability and elevating soft-contact rates.",
        "conditions": "Strongest in late-inning contexts where managers substitute to exploit the split; diminished for hitters with neutral platoon splits (below 0.020 OPS gap) deployed without same-hand restrictions.",
        "magnitude": "Platoon-advantaged confrontations show wOBA improvement roughly 0.025–0.045; matchup-seeking behavior raises bullpen usage by ~0.5–1.0 appearances per game in the seventh inning or later.",
        "links": ["high_leverage_index_state", "times_through_order_penalty", "count_leverage_states", "intentional_walk_setup"],
    },
    {
        "slug": "intentional_walk_setup",
        "title": "Intentional-Walk and Open-Base Strategy",
        "summary": "The deliberate free pass creates a force-out opportunity, bypasses a dangerous hitter, or sets up a platoon advantage; its run-expectancy cost varies sharply by base-out state.",
        "stat_signature": "Run-expectancy cost from bases-empty zero-outs: roughly +0.33 runs. Runners on second and third two-outs: roughly +0.10 runs. Frequency: roughly 0.3–0.6 per game in close contests.",
        "mechanism": "The strategy trades a conceded base-runner for a probabilistic improvement in subsequent matchup quality; net run-expectancy change depends on the hitter-quality differential between the walked and upcoming hitters plus the base-out state created.",
        "conditions": "Most frequently used in late-close states with a left-right platoon advantage available in the subsequent matchup. Extra-inning ghost-runner regimes suppress usage because loading bases increases walk-off risk.",
        "magnitude": "Positive run-expectancy cost in most states (roughly +0.10 to +0.35 runs); justified when the hitter-quality differential exceeds this threshold, occurring in roughly 35–45 percent of historical deployments.",
        "links": ["bases_loaded_leverage", "platoon_handedness_context", "late_and_close_state", "extra_innings_ghost_runner"],
    },
    {
        "slug": "sacrifice_small_ball_context",
        "title": "Sacrifice and Small-Ball Run-Manufacturing",
        "summary": "Bunt attempts and productive-out strategies advance runners at the cost of an out; run-expectancy analysis shows most sacrifice trades are costly yet persist for their variance-reduction value in one-run situations.",
        "stat_signature": "Sacrifice bunt from runner-on-first zero-outs: run-expectancy falls from ~0.86 to ~0.66 (cost ~0.20 runs). Runner-on-second zero-outs to one-out: ~1.10 to ~0.98 (cost ~0.12 runs).",
        "mechanism": "Outs are the primary inning resource; trading an out for base advancement reduces run-scoring variance rather than expected value, making the strategy rational only when a single run has outsized win-probability impact.",
        "conditions": "Deployed most in late-and-close or extra-inning contexts with a weak-contact hitter at the plate facing a pitcher whose strikeout tendency makes productive-out more reliable than swinging away.",
        "magnitude": "Run-expectancy cost of 0.10–0.25 runs per sacrifice attempt in most states; justified when a single run exceeds roughly 8–12 percentage points of win probability impact.",
        "links": ["extra_innings_ghost_runner", "late_and_close_state", "runners_in_scoring_position", "intentional_walk_setup"],
    },
    {
        "slug": "ballpark_dimensions_environment",
        "title": "Ballpark Dimensions and Run Environment",
        "summary": "Fence distances, wall heights, foul territory, and altitude collectively determine a park's run-scoring environment; park factors quantify each dimension's contribution to home-run, doubles, and total-run rates.",
        "stat_signature": "Park factor range: roughly 85 (suppressor) to 118 (enhancer) on a 100-neutral scale. High-altitude venues: HR park factor roughly 110–120. Foul-territory-rich parks reduce BA ~0.005–0.012.",
        "mechanism": "Thinner air at altitude reduces drag on batted balls, extending carry by roughly 5–8 percent; short fences convert deep fly balls to home runs; wide foul territory increases foul-out probability, suppressing BA on contact.",
        "conditions": "Park effect is stable across seasons but modulated by roster construction — power-heavy lineups benefit asymmetrically from enhancer parks. Wind direction interacts with park dimensions daily.",
        "magnitude": "HR rate differential between extreme enhancer and suppressor parks: roughly 25–35 percent; run-scoring differential roughly 15–22 percent across the full range.",
        "links": ["weather_wind_temperature", "day_night_split", "doubleheader_load"],
    },
    {
        "slug": "weather_wind_temperature",
        "title": "Weather, Wind, and Temperature Conditions",
        "summary": "Air temperature, humidity, and wind direction measurably alter batted-ball carry and pitcher grip; cold temperatures and wind blowing in show systematic run-scoring suppression.",
        "stat_signature": "Wind-out at 15-plus mph: HR rate rises ~12–18 percent above calm baseline. Wind-in at 15-plus mph: HR rate falls ~10–15 percent. Temperature below 50 F: run scoring ~5–8 percent below neutral-temperature baseline.",
        "mechanism": "Wind-aided carry extends fly-ball distances by 5–15 feet at 15 mph; cold air increases ball compression and reduces elasticity, suppressing exit velocity; cold conditions reduce pitcher grip quality and breaking-ball sharpness.",
        "conditions": "Wind-direction effect is park-specific based on stadium orientation. Temperature effects dominate early-April and late-October games in northern-latitude stadiums; retractable-roof venues neutralize weather when closed.",
        "magnitude": "HR-rate swing of roughly 25–33 percent between strong-wind-out and strong-wind-in at the same park; a 30-degree Fahrenheit temperature drop corresponds to roughly 0.20–0.35 run-per-game suppression.",
        "links": ["ballpark_dimensions_environment", "day_night_split", "starter_days_rest"],
    },
    {
        "slug": "doubleheader_load",
        "title": "Doubleheader Workload Effect",
        "summary": "Playing two full games in one day compresses pitching depth, depletes position-player stamina in the nightcap, and forces roster-management decisions that reduce optimal lineup and bullpen configurations by game two.",
        "stat_signature": "Second game of doubleheader: starter ERA roughly 0.35–0.60 above same-pitcher single-game average. Bullpen ERA rises ~0.50–0.80 runs. Offensive scoring rate in game two roughly 3–7 percent below game one.",
        "mechanism": "Pitching staffs designed for one game per day exhaust high-leverage relievers in game one; the nightcap draws on the lowest-tier depth. Hitter fatigue accumulates through nine innings, suppressing bat speed and contact quality in game two.",
        "conditions": "Effect strongest when game one extends into extras, further depleting bullpen availability. An off-day immediately before the doubleheader partially offsets fatigue but cannot replenish pitching depth.",
        "magnitude": "Second-game scoring rate suppression roughly 3–7 percent; starting-pitcher quality drop roughly 0.35–0.60 ERA units above single-game baseline.",
        "links": ["bullpen_usage_fatigue", "starter_days_rest", "extra_innings_ghost_runner", "roster_expansion_late_season"],
    },
    {
        "slug": "day_night_split",
        "title": "Day and Night Game Split",
        "summary": "Ambient lighting conditions affect ball-tracking for hitters; day games under direct sunlight produce measurable offensive output differences relative to night games in open-air stadiums.",
        "stat_signature": "Day-minus-night BA gap: roughly -0.005 to -0.010 (day slightly lower). Day-game HR rate roughly 2–4 percent below night-game rate. Strikeout rate in day games roughly 0.3–0.6 K/9 above night-game rate.",
        "mechanism": "Sunlight in hitters' eyes during afternoon first pitches and shadow lines across the plate create contrast disruption that impairs ball-tracking at release point and raises whiff rates on fastballs.",
        "conditions": "Effect concentrated in open-air stadiums during afternoon games (first-pitch before 4 PM local). Retractable-roof or domed stadiums show no meaningful day-night split.",
        "magnitude": "Day-game strikeout rate premium roughly 0.3–0.6 K/9; BA suppression roughly 5 points; effect size is small but systematic across multi-season samples.",
        "links": ["weather_wind_temperature", "ballpark_dimensions_environment", "starter_days_rest"],
    },
    {
        "slug": "roster_expansion_late_season",
        "title": "Late-Season Roster-Expansion Context",
        "summary": "The expanded active roster in the season's final weeks increases available pitching depth and pinch-deployment frequency, enabling more granular matchup management and higher bullpen-arm turnover per game.",
        "stat_signature": "Pitching changes per nine innings rises roughly 0.3–0.5 above pre-expansion average. Pinch-hit appearances per game rise ~0.4–0.8. Late-inning platoon-matching precision improves measurably.",
        "mechanism": "Larger rosters allow managers to deploy specialists for single-batter stints without exhausting available depth; increased depth reduces the penalty for using the closer in non-save situations, shifting high-LI deployment earlier.",
        "conditions": "Signal concentrated in September games for contending teams managing playoff positioning. Less pronounced for eliminated teams using expansion for development rather than win-maximization.",
        "magnitude": "Bullpen-arm deployment frequency rises ~15–20 percent; matchup-precision improvement measurable as ~0.5–1.0 percentage-point wOBA reduction against the opposing lineup's platoon-disadvantaged hitters.",
        "links": ["bullpen_usage_fatigue", "platoon_handedness_context", "high_leverage_index_state", "doubleheader_load"],
    },
]
