"""Situational intelligence concept nodes for NBA — person-free spec."""
from __future__ import annotations

SPORT: str = "NBA"
FAMILY: str = "Situational"

CONCEPTS: list[dict] = [
    {
        "slug": "back_to_back_second_night",
        "title": "Back-to-Back Second-Night Fatigue",
        "summary": "Teams on the second leg of consecutive-night contests show measurable declines in defensive intensity and late-game execution relative to rested opponents.",
        "stat_signature": "Second-night sides average ~2–3 pts/100 lower net-rating; eFG% drops ~1.5 pp; Q4 defensive rating degrades 3–4 pts/100 versus rested-opponent baseline.",
        "mechanism": "Glycogen depletion and accumulated micro-trauma reduce sprint frequency and contest-rate; slower rotations inflate opponent corner-three and paint opportunities.",
        "conditions": "Concentrates in fourth quarters; elevated against high-pace opponents stressing transition defense; attenuated when the prior game ended decisively early.",
        "magnitude": "Moderate: ~2–3 net-rating points, largest when the second game is also a road game.",
        "links": ["three_in_four_density", "rest_days_advantage_gradient", "rest_disparity_mismatch", "road_trip_length_drag"],
    },
    {
        "slug": "three_in_four_density",
        "title": "Three-Games-in-Four-Nights Density",
        "summary": "A three-game window inside four nights compounds fatigue beyond a single back-to-back, driving turnover-rate creep and fourth-quarter scoring decay across the full window.",
        "stat_signature": "Third game: ~4 pts/100 net-rating drop; turnover rate up ~1.5 pp; Q4 offensive rating trails non-compressed baseline by ~5 pts/100.",
        "mechanism": "Cumulative minutes without full recovery cycles impair decision speed and on-ball defensive aggression; bench depth advantage amplifies for the rested side.",
        "conditions": "Sharpest in the third game of the window; partially offset by roster depth; exacerbated by cross-timezone travel within the block.",
        "magnitude": "Substantial for thin rosters: up to 4–5 net-rating points in the final game of the compressed block.",
        "links": ["back_to_back_second_night", "rest_days_advantage_gradient", "road_trip_length_drag", "travel_distance_timezone_load"],
    },
    {
        "slug": "rest_days_advantage_gradient",
        "title": "Days-of-Rest Advantage Gradient",
        "summary": "Net-rating improves with each additional day of rest up to approximately three days, after which returns diminish and rhythm-loss can slightly offset the recovery benefit.",
        "stat_signature": "0 rest days: ~−1.5 pts/100 relative to season average; 1 day: baseline; 2 days: ~+1 pt/100; 3+ days: ~+1.2 pts/100 with elevated outcome variance.",
        "mechanism": "Musculoskeletal recovery and sleep quality restore sprint output and reaction time; beyond three days the lack of game-speed reps introduces marginal execution rust.",
        "conditions": "Gradient steeper for high-usage rotations and older rosters; diminishing returns appear when extended rest follows a long winning streak.",
        "magnitude": "Small to moderate: roughly 1–2 net-rating points per marginal rest day up to day three.",
        "links": ["back_to_back_second_night", "rest_disparity_mismatch", "three_in_four_density", "schedule_loss_letdown_spot"],
    },
    {
        "slug": "rest_disparity_mismatch",
        "title": "Rest-Disparity Mismatch",
        "summary": "When one side is fully rested and the opponent on a back-to-back, the rested side's net-rating and shooting variance both shift favorably relative to symmetric-rest contests.",
        "stat_signature": "Rested side gains ~4–5 pts/100 net-rating against back-to-back opponents; eFG% spread widens ~2 pp; Q4 defensive-rating gap grows ~3 pts/100.",
        "mechanism": "Asymmetric recovery combines fatigue drag on one side with full-alertness advantage on the other; the rested team can extend defensive pressure without conservative energy management.",
        "conditions": "Most pronounced when the fatigued team also traveled the night before; mitigated by superior roster depth on the fatigued side.",
        "magnitude": "Moderate to large: the rest-disparity signal is among the most consistent schedule-based differentials in the regular season.",
        "links": ["back_to_back_second_night", "rest_days_advantage_gradient", "road_trip_length_drag", "travel_distance_timezone_load"],
    },
    {
        "slug": "road_trip_length_drag",
        "title": "Extended Road-Trip Cumulative Drag",
        "summary": "Net-rating declines monotonically across successive road games within a single trip, with rebounding effort and defensive rotation quality as the first metrics to degrade.",
        "stat_signature": "Games 1–2 of a road trip: near-baseline road splits; games 4–5+: additional ~2 pts/100 net-rating drag; defensive rebounding rate falls ~1.5 pp by game five.",
        "mechanism": "Accumulated sleep disruption in unfamiliar environments, dietary deviation, and limited practice access suppress recovery quality; homecoming motivation absent.",
        "conditions": "Drag accelerates when the trip crosses multiple time zones; reduced for teams with depth or an off-day mid-trip.",
        "magnitude": "Small per game but compounding: a five-game trip's final contest shows roughly 3–4 net-rating points below a comparable rested-home baseline.",
        "links": ["travel_distance_timezone_load", "back_to_back_second_night", "home_road_environment_split"],
    },
    {
        "slug": "travel_distance_timezone_load",
        "title": "Travel Distance and Time-Zone Crossing Load",
        "summary": "Cross-continental travel with a time-zone shift degrades tip-off readiness, measured as first-quarter point-differential and shot-make-rate deltas versus within-zone road games.",
        "stat_signature": "Eastward early-tip travelers show ~3–4 pts first-quarter net-rating deficit; FG% in Q1 drops ~2–3 pp; effect persists into Q2 and diminishes by halftime.",
        "mechanism": "Circadian misalignment suppresses alertness and fine-motor coordination in opening minutes; eastward travel is directionally harder due to shortened sleep cycles.",
        "conditions": "Concentrated in Q1 on early-tip games after overnight cross-country travel; attenuated when a rest day precedes the game or travel occurred two days prior.",
        "magnitude": "Small to moderate in aggregate; locally large in first quarters of specific high-travel-stress games.",
        "links": ["road_trip_length_drag", "early_tip_circadian", "rest_days_advantage_gradient", "back_to_back_second_night"],
    },
    {
        "slug": "early_tip_circadian",
        "title": "Early-Tip Circadian Disadvantage",
        "summary": "Unusually early start times relative to a team's habitual tip-off window suppress first-half shooting and elevate turnover rates through sub-optimal arousal.",
        "stat_signature": "Games tipping more than 2 hours before median team start: first-half eFG% down ~1.5 pp, turnover rate up ~0.8 pp; effect dissipates in the second half.",
        "mechanism": "Core body temperature and neuromuscular output peak later in the day; teams calibrated to evening tips perform suboptimally in the morning window.",
        "conditions": "Stronger for west-coast teams in nationally televised early slots or holiday afternoon games; offset when travel direction aligns circadian clocks.",
        "magnitude": "Modest: roughly 1–2 pp shooting drag in the first half; larger for cross-timezone travelers.",
        "links": ["travel_distance_timezone_load", "back_to_back_second_night", "home_road_environment_split"],
    },
    {
        "slug": "home_road_environment_split",
        "title": "Home and Road Environment Split",
        "summary": "Crowd noise, referee familiarity, and home-court sleep quality systematically inflate free-throw rate and pace for the hosting side relative to road contests.",
        "stat_signature": "Home teams average ~3–4 pts/100 net-rating advantage; free-throw-rate gap ~3–4 pp favoring home; road defensive-rating ~2 pts/100 worse than neutral-site baselines.",
        "mechanism": "Crowd pressure biases borderline foul calls toward the home side; familiar sleep environment and no travel stress sustain higher-intensity play throughout.",
        "conditions": "Effect attenuated in playoff settings; elevated in louder arenas with strong home-attendance records.",
        "magnitude": "Well-documented moderate effect: one of the largest single situational factors in NBA game outcomes.",
        "links": ["road_trip_length_drag", "early_tip_circadian", "altitude_venue_effect", "rest_disparity_mismatch"],
    },
    {
        "slug": "altitude_venue_effect",
        "title": "High-Altitude Venue Conditioning Effect",
        "summary": "Reduced atmospheric oxygen at high-elevation arenas accelerates visitor cardiovascular fatigue, with fourth-quarter FG% and pace falloff as the primary markers.",
        "stat_signature": "Visiting teams at arenas above 5,000 ft: Q4 FG% ~2–3 pp below sea-level road-game baseline; pace drops ~1–2 possessions in Q4; visitor Q4 net-rating ~3 pts/100 worse.",
        "mechanism": "Lower partial-pressure oxygen reduces aerobic capacity; unacclimatized teams experience faster onset of muscular fatigue in the decisive late period.",
        "conditions": "Concentrated in fourth quarters and overtime; larger for same-day arrivals without altitude acclimatization; home teams show no comparable decay.",
        "magnitude": "Moderate late-game effect: visitor Q4 is the cleanest signal; full-game magnitude is diluted by normal first-half play.",
        "links": ["home_road_environment_split", "road_trip_length_drag", "travel_distance_timezone_load"],
    },
    {
        "slug": "score_state_lead_protection",
        "title": "Lead-Protection Score-State Behavior",
        "summary": "Teams holding a meaningful lead deliberately slow tempo and increase clock usage, compressing pace and shifting shot selection toward higher-probability attempts.",
        "stat_signature": "Leading by 10+ pts: pace drops ~3–4 possessions/game; clock-usage per possession rises ~2 s; three-point-attempt rate falls ~3 pp versus neutral-score baseline.",
        "mechanism": "Rational variance minimization converts statistical lead into clock control; the leading team maximizes possession time while forcing the trailing side to foul or accept low-quality shots.",
        "conditions": "Behavior onset sharpens in Q4; more pronounced against high-variance opponents; attenuated in early-game leads or when trailing team has poor FT%.",
        "magnitude": "Large within the lead-protection window: pace reduction alone suppresses opponent possessions by 4–6 in a Q4.",
        "links": ["score_state_trailing_aggression", "clutch_time_compression", "intentional_foul_endgame", "blowout_garbage_time_distortion"],
    },
    {
        "slug": "score_state_trailing_aggression",
        "title": "Trailing-Team Aggression and Variance",
        "summary": "Teams in a deficit deliberately increase possession speed and three-point volume to manufacture variance, accepting lower expected-value shots to maximize comeback probability.",
        "stat_signature": "Down 10+ in Q4: three-point-attempt rate rises ~8–10 pp; possession speed increases ~2 s faster; offensive rebounding crash rate rises ~2 pp.",
        "mechanism": "Rational variance-seeking — trailing teams maximize outcome variance over per-possession EV; the three-point shot is the highest-variance efficient tool available.",
        "conditions": "Intensifies as deficit widens or time narrows; attenuated when the trailing team lacks reliable three-point shooting infrastructure.",
        "magnitude": "Large shot-selection shift; actual net-rating impact depends on three-point efficiency under pressure, which typically declines from non-clutch baselines.",
        "links": ["score_state_lead_protection", "clutch_time_compression", "intentional_foul_endgame", "end_of_period_two_for_one"],
    },
    {
        "slug": "clutch_time_compression",
        "title": "Clutch-Time Possession Compression",
        "summary": "The last five minutes of a game within a five-point margin triggers an isolation-heavy, foul-rich regime that depresses offensive rating relative to non-clutch minutes.",
        "stat_signature": "Clutch offensive rating ~5–8 pts/100 below full-game average; isolation frequency triples; free-throw rate rises ~10 pp; turnover rate increases ~1–2 pp under pressure.",
        "mechanism": "Clock and possession scarcity incentivize individual creation over motion offense; defensive schemes shade toward star denial, compressing spacing and forcing lower-quality creation.",
        "conditions": "Effect magnitude scales with defensive quality of the opponent and bench-depth of each side; teams with multiple self-creation options suffer less compression.",
        "magnitude": "Large within the clutch window: league-wide clutch offensive-rating is substantially below full-game pace-adjusted baselines.",
        "links": ["score_state_lead_protection", "score_state_trailing_aggression", "after_timeout_execution", "team_bonus_penalty_state"],
    },
    {
        "slug": "blowout_garbage_time_distortion",
        "title": "Blowout Garbage-Time Stat Distortion",
        "summary": "Once a game is decided beyond a leverage threshold, deep-bench minutes inflate box-score totals for lower-usage players and truncate starter accrual, distorting per-game averages.",
        "stat_signature": "Leads of 20+ pts in Q4: ~15–20% of quarter points accrued by non-rotation players; starter stat accrual truncates 4–6 minutes early on average.",
        "mechanism": "Win-probability collapse removes strategic incentive; coaches protect starters from injury and log development minutes for depth players, creating a non-representative stat environment.",
        "conditions": "Triggered at margins beyond ~18–20 pts in Q4; more common for dominant teams with deep rosters.",
        "magnitude": "Large for box-score totals in blowouts; distortion is systematic and predictable once the leverage threshold is identified.",
        "links": ["score_state_lead_protection", "player_foul_trouble_constraint", "clutch_time_compression"],
    },
    {
        "slug": "player_foul_trouble_constraint",
        "title": "Individual Foul-Trouble Constraint",
        "summary": "A player carrying two fouls before halftime or four fouls in Q3 incurs forced bench time and reduced defensive aggression that depresses on-court net-rating.",
        "stat_signature": "Foul-trouble stints: defensive-contest rate drops ~30%; on/off net-rating swing ~4–6 pts/100 when a high-usage player sits; team FT-concession rate falls ~2 pp in protective stints.",
        "mechanism": "Rational risk aversion throttles defensive aggression to avoid disqualification; opponents target the foul-burdened player to draw calls or force substitution.",
        "conditions": "Impact scales with the constrained player's net-rating differential; concentrated against opponents with strong paint-attack infrastructure.",
        "magnitude": "Moderate to large: the more irreplaceable the constrained player, the steeper the net-rating degradation during protective minutes.",
        "links": ["team_bonus_penalty_state", "clutch_time_compression", "blowout_garbage_time_distortion"],
    },
    {
        "slug": "intentional_foul_endgame",
        "title": "Late-Game Intentional-Foul Trade",
        "summary": "Trailing teams deliberately foul to stop the clock and recover possession, exchanging expected points from opponent free throws for time and additional possession opportunities.",
        "stat_signature": "Opponent FT% ~75–77% yields ~1.50–1.54 pts per two-shot trip; trailing team recovers ~18–22 seconds plus a possession; strategy is EV-positive only when trailing by 3+ pts with fewer than 30 seconds.",
        "mechanism": "Clock management trades near-certain two points against the opportunity for a possession to close the gap; poor-FT-shooting opponents flip the expected-value calculus.",
        "conditions": "Rational only in specific score-time corridors; less effective against high-FT% opponents; systematically exploited against poor free-throw shooting big men.",
        "magnitude": "Situation-dependent: EV swing can be 0.5–2 expected-point differences per possession chain depending on opponent FT% and deficit size.",
        "links": ["score_state_trailing_aggression", "clutch_time_compression", "team_bonus_penalty_state", "end_of_period_two_for_one"],
    },
    {
        "slug": "end_of_period_two_for_one",
        "title": "End-of-Period Two-for-One and Heave",
        "summary": "Clock-aware possession management near a quarter buzzer enables an extra possession, while long heave attempts introduce near-zero-make-rate shots that distort period-level shooting splits.",
        "stat_signature": "Two-for-one execution yields ~0.8–0.9 additional expected points per attempt; heave FG% approximately 1–4%, depressing period-level eFG% by up to 0.5 pp per attempt.",
        "mechanism": "Initiating offense at ~35–40 seconds permits a full possession and a second trip before the buzzer; the defense must respond normally or concede an uncontested attempt.",
        "conditions": "Opportunity exists when the period clock is at 35–42 seconds and possession is recovered after a make; heaves are near-universal when fewer than 2 seconds remain.",
        "magnitude": "Small in aggregate; heave-induced split distortion is largest in short first or third quarters with multiple long-range attempts logged.",
        "links": ["after_timeout_execution", "score_state_trailing_aggression", "clutch_time_compression", "intentional_foul_endgame"],
    },
    {
        "slug": "after_timeout_execution",
        "title": "After-Timeout Set-Play Execution",
        "summary": "The first possession following a called timeout produces systematically higher points-per-possession than flow-of-game possessions, driven by drawn-up set plays against briefly unprepared defenses.",
        "stat_signature": "Post-timeout PPP ~1.10–1.18 versus ~0.98–1.02 in flow-of-game; open three-point-attempt rate rises ~6 pp; turnover rate falls ~1 pp on the first possession out of the break.",
        "mechanism": "Set plays from a dead ball create advantageous spacing and action novelty; defense requires time to load new assignments, creating a brief information asymmetry.",
        "conditions": "Largest in late-game situations where stakes encourage optimal play-calling; advantage diminishes if defense pre-scouts the opponent's out-of-bounds package.",
        "magnitude": "Small but consistent: a ~0.10–0.15 PPP premium on the first possession, compressing toward baseline over the following two trips.",
        "links": ["clutch_time_compression", "end_of_period_two_for_one", "team_bonus_penalty_state"],
    },
    {
        "slug": "team_bonus_penalty_state",
        "title": "Team Bonus and Penalty Foul State",
        "summary": "Once a team enters the penalty, every subsequent defensive foul awards opponent free throws, shifting the points-per-possession calculus and reducing defensive aggression.",
        "stat_signature": "Penalty possession opponent PPP rises ~0.10–0.15 above non-penalty average; defensive foul frequency drops ~20% once threshold is reached; pace slightly decreases as defense becomes conservative.",
        "mechanism": "Free throws are the highest-efficiency offense at ~1.50 pts per two-shot trip; penalty state creates a rational incentive to concede mid-range shots rather than risk foul-induced sequences.",
        "conditions": "Strongest in Q4 when the penalty is entered early; teams with deep fouls early in a period face the longest penalty exposure.",
        "magnitude": "Meaningful within affected periods: penalty exposure of 4+ minutes per quarter can shift per-period scoring by 2–3 points.",
        "links": ["player_foul_trouble_constraint", "clutch_time_compression", "after_timeout_execution", "intentional_foul_endgame"],
    },
    {
        "slug": "schedule_loss_letdown_spot",
        "title": "Schedule-Loss and Letdown Spot",
        "summary": "Teams following an emotionally taxing game or preceding a marquee matchup show deflated first-half effort, proxied by pace, offensive rebounding, and early net-rating.",
        "stat_signature": "Flagged letdown spots: first-half net-rating ~2–3 pts/100 below season average; offensive rebounding rate falls ~1 pp; pace drops ~1–2 possessions/game in the first half only.",
        "mechanism": "Psychological arousal cycles create asymmetric effort allocation; roster energy is implicitly conserved ahead of higher-stakes contests, reducing execution intensity.",
        "conditions": "Strongest when the bracketing game is a nationally prominent rivalry; attenuated when the intervening opponent has recent wins against the team.",
        "magnitude": "Small to moderate in first-half data; hard to isolate from schedule noise without controlling for roster rest and opponent quality.",
        "links": ["rest_days_advantage_gradient", "back_to_back_second_night", "home_road_environment_split"],
    },
]
