"""Person-free situational intelligence concepts for Tennis."""
from __future__ import annotations

SPORT = "Tennis"
FAMILY = "Situational"

CONCEPTS = [
    {
        "slug": "best_of_three_versus_five_format",
        "title": "Best-of-Three and Best-of-Five Format Effect",
        "summary": "Match format length reshapes comeback frequency and attrition profiles; a one-set deficit is recoverable at 28-34% in five-set play versus 18-22% in three-set play, compressing variance in the shorter format.",
        "stat_signature": "Recovery from one-set-down: ~30% in best-of-five, ~20% in best-of-three; first-serve speed drops 3-6 km/h by set 4-5; unforced-error rate rises 15-25% in the final set versus set 1.",
        "mechanism": "Additional sets permit physical attrition to accumulate and allow the more durable competitor to reassert advantage; shorter formats compress the margin for tactical adjustment, amplifying the impact of an early break.",
        "conditions": "Largest when physical differential between competitors is pronounced; on clay where rallies extend, the attrition gap opens faster than on fast indoor hard courts.",
        "magnitude": "Hold-rate differential between set 1 and set 5 averages 4-7 percentage points in five-set matches; recovery from two-sets-down is below 5% in any format, making early-deficit magnitude a strong state signal.",
        "links": ["set_attrition_late_fatigue", "deciding_set_dynamics", "cumulative_deep_run_load", "set_score_state_leverage"],
    },
    {
        "slug": "set_score_state_leverage",
        "title": "Set-Score-State Leverage",
        "summary": "Service hold-rate and break-conversion rate shift systematically with the current set scoreline; leading by a set stabilises serve performance while trailing induces risk-taking that raises both winner rate and error rate.",
        "stat_signature": "Hold-rate when leading by a set: +3-5 pp above personal match average; break-point conversion by the trailer rises 2-4 pp; double-fault rate for the trailer rises 0.3-0.8 per service game.",
        "mechanism": "Psychological safety when ahead permits conservative first-serve tactics; the trailer must increase risk to shift momentum, simultaneously elevating both winners and errors.",
        "conditions": "Most pronounced in best-of-three where losing another set is terminal; attenuated in best-of-five set 2 where trailing 1-0 remains highly recoverable.",
        "magnitude": "Aggregate hold-rate advantage for the set leader is 3-6 pp; break frequency roughly doubles in the set immediately after a competitor falls two sets behind.",
        "links": ["best_of_three_versus_five_format", "serving_for_set_or_match", "serving_to_stay_in", "deciding_set_dynamics"],
    },
    {
        "slug": "break_point_pressure",
        "title": "Break-Point Pressure Conversion",
        "summary": "Break points carry disproportionate leverage; conversion and save rates deviate substantially from baseline point-level performance, driven by the asymmetric cost of each outcome.",
        "stat_signature": "Tour-level break-point conversion averages 37-42%; first-serve percentage at break point rises 4-8 pp as servers shift to higher-probability placements; returner winning rate on second serves at break point runs 5-9 pp above non-break-point baseline.",
        "mechanism": "Both competitors register the asymmetric leverage; converting ends a service game while a miss resets parity; servers raise first-serve commitment, returners move forward and load return aggression.",
        "conditions": "Elevated break-point count correlates with slower surface pace and longer rallies; fast surfaces compress conversion rates toward the mean due to serve dominance.",
        "magnitude": "Competitors saving break points at 65%+ versus the tour average of 58-62% show measurably tighter hold-rate variance; a single break wins that set at 70-75% at tour level.",
        "links": ["tiebreak_situational_play", "serving_for_set_or_match", "serving_to_stay_in", "deuce_advantage_grind"],
    },
    {
        "slug": "serving_for_set_or_match",
        "title": "Serving-for-the-Set-or-Match Tightness",
        "summary": "The service game that closes a set or match carries amplified psychological weight; measurable tightening appears as lower first-serve percentage, elevated double-fault rate, and reduced hold probability relative to same-match averages.",
        "stat_signature": "First-serve percentage drops 4-9 pp when serving for the set; double-fault rate rises 0.4-1.1 per service game; hold probability is 3-6 pp below the competitor's within-match hold-rate mean.",
        "mechanism": "Asymmetric leverage intensifies self-monitoring; heightened arousal disrupts fine motor control on the ball toss, degrading serve consistency at the moment it is most demanded.",
        "conditions": "Amplified under crowd pressure and late in long matches where fatigue compounds tension; pronounced when prior failures in closing games form a recent pattern.",
        "magnitude": "Break rate in closing games is 20-30% above the baseline hold rate for that competitor in the same match; closing-game breaks materially extend total games played.",
        "links": ["serving_to_stay_in", "two_points_from_loss", "set_score_state_leverage", "tiebreak_situational_play"],
    },
    {
        "slug": "serving_to_stay_in",
        "title": "Serving-to-Stay-in-the-Set Resilience",
        "summary": "Must-hold service games under elimination pressure reveal a competitor's resilience signature; hold-rate in these games diverges widely across competitors, far more than in routine mid-set games.",
        "stat_signature": "Hold-rate in must-hold situations diverges from match average by ±6-12 pp; first-serve percentage typically falls 3-7 pp below the match average in these games, serving as the earliest indicator of pressure response.",
        "mechanism": "Elimination pressure activates threat-response physiology; competitors whose motor patterns are rehearsed under high arousal maintain serve consistency better than those who mainly practise in neutral situations.",
        "conditions": "Intensifies with match duration and accumulated fatigue; in set 3 of best-of-three the stakes are maximally compressed, making must-hold hold-rate the sharpest discriminator.",
        "magnitude": "The spread in hold-rate across competitors in must-hold games is roughly twice as wide as in routine mid-set service games, reflecting the larger role of individual pressure-handling differences.",
        "links": ["serving_for_set_or_match", "two_points_from_loss", "break_point_pressure", "deciding_set_dynamics"],
    },
    {
        "slug": "tiebreak_situational_play",
        "title": "Tiebreak Situational Play",
        "summary": "The tiebreak is a compressed scoring regime where each mini-break carries the leverage of multiple conventional points; serve dependence, first-strike aggression, and winners-to-error ratios diverge sharply from standard-game patterns.",
        "stat_signature": "First-serve percentage in tiebreaks averages 3-5 pp above the match baseline; mini-break conversion at 6-6 runs 2-4 pp above the within-tiebreak average; winners-to-unforced-error ratio spikes 15-25% relative to standard games.",
        "mechanism": "In first-to-7 format each point is roughly 14% of the set; risk tolerance shifts toward aggressive first-strike tactics because passive neutralisation permits opponents to attack at low cost.",
        "conditions": "Most volatile on fast surfaces where a single ace or return winner can swing leverage; on clay, longer rally tolerance partially offsets compressed scoring risk.",
        "magnitude": "A competitor winning tiebreaks at 55%+ wins the corresponding set at nearly twice the rate of a competitor with a sub-45% tiebreak rate; tiebreak record outpredicts service hold-rate alone for set outcomes.",
        "links": ["deciding_match_tiebreak", "break_point_pressure", "serving_for_set_or_match", "indoor_outdoor_environment"],
    },
    {
        "slug": "deciding_set_dynamics",
        "title": "Deciding-Set Dynamics",
        "summary": "The final set of a close match is played under maximum outcome leverage; service hold-rates, break frequency, and unforced-error rates all shift relative to earlier sets, reflecting accumulated fatigue and heightened stakes simultaneously.",
        "stat_signature": "Break frequency in deciding sets is 8-15% higher than in set 1; first-serve percentage falls 5-8 pp and unforced-error rate rises 10-18% relative to the set-1 baseline in the same match.",
        "mechanism": "Physical depletion reduces serve velocity and movement range while anxiety over the terminal nature of the set compounds motor-control degradation, producing more erratic shot selection.",
        "conditions": "Largest after prior sets with many deuce games; compressed deciding sets following routine earlier sets show smaller divergence from baseline patterns.",
        "magnitude": "Competitors holding serve above their match average in deciding sets win that set at over 75%; those who break serve first convert to set-win at roughly 68-72% at tour level.",
        "links": ["set_attrition_late_fatigue", "deciding_match_tiebreak", "best_of_three_versus_five_format", "deuce_advantage_grind"],
    },
    {
        "slug": "deciding_match_tiebreak",
        "title": "Final-Set Match-Tiebreak Regime",
        "summary": "The super-tiebreak format that resolves a final set compresses outcome variance by 30-40% versus an advantage deciding set; serve dependence and mini-break leverage intensify beyond any other match segment.",
        "stat_signature": "Outcome variance (standard deviation of points-won differential) is 30-40% lower in super-tiebreaks than in advantage deciding sets; first-serve winning-point rate runs 4-7 pp above the match average.",
        "mechanism": "In first-to-10 format each mini-break represents 10% of the match; both competitors commit to maximum first-serve quality and aggressive return positioning, removing the value of rally-based attrition tactics.",
        "conditions": "Used at Australian Open and US Open on hard courts; Roland Garros advantage sets produce fundamentally different dynamics through attrition rather than compressed scoring.",
        "magnitude": "Leading 6-3 or better in a super-tiebreak converts to match-win at approximately 85%; underdog conversion from such deficits is roughly half what an equivalent advantage-set situation would permit.",
        "links": ["tiebreak_situational_play", "deciding_set_dynamics", "two_points_from_loss", "indoor_outdoor_environment"],
    },
    {
        "slug": "two_points_from_loss",
        "title": "Two-Points-from-Defeat State",
        "summary": "The narrowest elimination margin in tennis creates a measurable physiological and tactical shift; save-rate and the serve-and-return performance change at match point down reveal a competitor's pressure ceiling.",
        "stat_signature": "First-serve percentage at match point down averages 3-6 pp below within-match mean; second-serve aggressiveness index rises 8-14% above baseline as passive defence is abandoned; tour-level save rate from match-point-down is approximately 38-44%.",
        "mechanism": "Terminal threat removes the cost of conservative strategy; competitors shift to maximum-aggression return posture and higher-risk serve patterns because the expected value of caution drops to near zero.",
        "conditions": "Behaviour differs in best-of-three final sets versus best-of-five due to accumulated fatigue level; on slower surfaces the save rate is modestly higher due to extended rally opportunities for the defender.",
        "magnitude": "Competitors saving match points above 45% show materially higher final-set win rates; saving one match point triggers a detectable break-rate spike in the following service game.",
        "links": ["serving_to_stay_in", "serving_for_set_or_match", "deciding_match_tiebreak", "break_point_pressure"],
    },
    {
        "slug": "deuce_advantage_grind",
        "title": "Deuce and Advantage Grind",
        "summary": "Extended games settled past deuce impose fatigue and rhythm disruption disproportionate to their point count; deuce-game frequency is a surface signature and a late-match burden accumulator.",
        "stat_signature": "On clay, 18-24% of games reach deuce versus 11-15% on fast indoor hard courts; each additional deuce exchange adds 90-140 seconds of match duration; matches with above-average deuce-game frequency show first-serve speed declines of 2-4 km/h in the final set.",
        "mechanism": "Deuce games require winning two consecutive points from parity, adding serve-return exchanges beyond what the set score demands; this extends physical and cognitive load without changing the scoreline.",
        "conditions": "Highest on clay and in humid conditions where ball bounce elevation slows rally termination; indoor conditions with faster balls reduce deuce rate significantly.",
        "magnitude": "In matches where deuce-game frequency exceeds the surface average by more than 8 pp, late-set hold-rate falls an additional 3-5 pp compared with matches of equivalent duration but lower deuce accumulation.",
        "links": ["set_attrition_late_fatigue", "deciding_set_dynamics", "heat_climate_endurance", "break_point_pressure"],
    },
    {
        "slug": "set_attrition_late_fatigue",
        "title": "Set-Attrition Late-Match Fatigue",
        "summary": "Cumulative physical decline across a long match is captured by set-by-set degradation in serve velocity, rally-length tolerance, and movement-driven unforced-error rate, exposing competitors whose game depends on peak output.",
        "stat_signature": "First-serve speed declines 1.5-3.5 km/h per set in matches exceeding three sets; unforced-error rate in set 4-5 is 18-28% above set-1 levels; rally-length tolerance contracts by 2-4 shots per rally in the final set of long matches.",
        "mechanism": "Glycogen depletion and neuromuscular fatigue degrade explosive recruitment for serve and footwork; reduced movement speed increases the fraction of shots taken out of optimal balance, elevating unforced-error rate.",
        "conditions": "Amplified by heat, humidity, and altitude; worst when prior-round match duration was long with minimal recovery; most visible in competitors whose first serve is the primary hold mechanism.",
        "magnitude": "Hold-rate gap between set 1 and the final set of a four-or-five-set match averages 4-8 pp at tour level; the competitor with superior baseline endurance holds serve 6-10 pp more reliably in the final set.",
        "links": ["best_of_three_versus_five_format", "cumulative_deep_run_load", "back_to_back_match_scheduling", "heat_climate_endurance", "deuce_advantage_grind"],
    },
    {
        "slug": "back_to_back_match_scheduling",
        "title": "Back-to-Back Match-Day Scheduling",
        "summary": "Consecutive match days impose a recovery deficit; service-speed retention and unforced-error rate after a long prior-match duration differ systematically from a rested baseline, scaling with prior-match duration.",
        "stat_signature": "After a prior match exceeding 150 minutes, first-serve speed in the next match is 2-4 km/h below the season average on comparable surfaces; unforced-error rate rises 12-20% in sets 2-3 of the following match versus fully rested performance.",
        "mechanism": "Incomplete glycogen resynthesis and residual neuromuscular soreness within a 16-22-hour window reduce explosive capacity and proprioceptive precision; the effect accumulates when the prior match also featured deuce grinding or heat stress.",
        "conditions": "Most impactful in outdoor summer tournaments where heat compounds recovery demands; indoor events with climate control show a smaller effect; short early-round prior matches minimise residual load.",
        "magnitude": "Competitors off a prior match of 2.5 or more hours show break susceptibility 5-9 pp above their tournament average in the subsequent match; the effect halves if prior-match duration was under 90 minutes.",
        "links": ["cumulative_deep_run_load", "set_attrition_late_fatigue", "layoff_rust_return", "heat_climate_endurance"],
    },
    {
        "slug": "cumulative_deep_run_load",
        "title": "Cumulative Deep-Run Load",
        "summary": "Fatigue accrued across several consecutive event rounds produces a round-by-round signature in late-set hold stability and distance-covered tolerance, distinguishing durable competitors from those with fast-fatiguing profiles.",
        "stat_signature": "By the semifinal or final of a two-week event, competitors with cumulative match time above 10 hours show first-serve speed 3-6 km/h below their event average and hold-rate decline of 5-9 pp in sets 3+ versus opening-round levels.",
        "mechanism": "Repeated match loads stress musculotendinous units without full recovery; cumulative micro-trauma to the rotator cuff and lower limb progressively reduces explosive serve and court-coverage capacity.",
        "conditions": "Most material in Grand Slam events requiring seven matches; in 250 and 500-level five-round events the load is lower; clay is the highest-load surface per match-hour due to rally length.",
        "magnitude": "A competitor carrying more than 12 hours of cumulative match time into a final shows statistically detectable hold-rate and serve-speed depression versus a competitor carrying under 9 hours in the same event.",
        "links": ["set_attrition_late_fatigue", "back_to_back_match_scheduling", "best_of_three_versus_five_format", "heat_climate_endurance"],
    },
    {
        "slug": "layoff_rust_return",
        "title": "Layoff and Match-Rust Return State",
        "summary": "An extended gap since last competitive match elevates early-round error rates, depresses first-serve percentage, and slows in-match tactical adjustment; gap length and the reason for it shape the magnitude of the rust signature.",
        "stat_signature": "After a layoff exceeding 60 days, first-serve percentage is 5-10 pp below the prior-season average in the return match; unforced-error rate in sets 1-2 is 20-30% above baseline; in-match error-rate correction (set 1 to set 3) is 8-15 pp slower than after active preparation.",
        "mechanism": "Competitive-specific arousal calibration and match rhythm — pacing of point construction and service-routine timing — degrade without match repetition; practice does not replicate the pressure cadence of real competition.",
        "conditions": "Injury-return layoffs produce larger rust signatures than planned off-season breaks; returning to a different surface from the one used in preparation compounds the adjustment penalty.",
        "magnitude": "The rust signature typically halves by the second return match and is largely resolved by match 3-4; first-serve percentage recovers fastest, unforced-error rate next, with tactical sharpness recovering last.",
        "links": ["back_to_back_match_scheduling", "set_attrition_late_fatigue", "indoor_outdoor_environment"],
    },
    {
        "slug": "heat_climate_endurance",
        "title": "Heat and Climate Endurance Condition",
        "summary": "High-temperature and humidity stress contracts rally-length tolerance, increases between-point recovery time usage, and elevates late-set physical-error rates; magnitude scales with wet-bulb temperature and body-mass loss rate.",
        "stat_signature": "At wet-bulb temperatures above 28°C, rally-length averages contract 1.5-3 shots per rally by set 3; unforced-error rate rises 22-35% versus the same surface in neutral conditions; between-point time approaches the 25-second maximum in 80%+ of games.",
        "mechanism": "Thermal stress diverts cardiac output to cutaneous vasodilation for cooling, reducing oxygen delivery to working muscles; body-mass losses above 2% impair both cognitive decision-speed and muscular power output.",
        "conditions": "Critical at summer hard-court events; effects double on clay due to slower rallies extending outdoor heat exposure per match; competitors with higher body-surface-area-to-mass ratios show systematically better heat tolerance.",
        "magnitude": "Hold-rate decline per set in court-level temperatures above 35°C is approximately 1.5-2.5 pp per set beyond what fatigue alone predicts; this is additive to the attrition slope from match duration.",
        "links": ["set_attrition_late_fatigue", "deuce_advantage_grind", "back_to_back_match_scheduling", "day_night_session_conditions"],
    },
    {
        "slug": "indoor_outdoor_environment",
        "title": "Indoor and Outdoor Environment Effect",
        "summary": "Roofed and open-air environments produce systematically different ball behaviour due to air density, wind, and humidity; service hold-rate, ace-rate, and break frequency diverge consistently across these environments even on identical surface materials.",
        "stat_signature": "Indoor hard-court hold-rate averages 82-86% versus 76-80% on outdoor hard courts at comparable tour levels; ace-rate is 15-25% higher indoors; average rally length is 0.8-1.4 shots shorter indoors due to reduced ball sit-up on the bounce.",
        "mechanism": "Still indoor air eliminates wind interference with ball trajectory and toss stability; controlled temperature keeps ball pressure and felt condition consistent, supporting higher serve-speed maintenance across sets.",
        "conditions": "The indoor serve-premium is largest on hard courts; night sessions outdoors in cool air partially replicate indoor conditions; indoor clay partially offsets the serve premium through high bounce mechanics.",
        "magnitude": "Break frequency indoors is 20-30% lower per set than on outdoor hard courts of comparable surface pace; tiebreak rates are 40-60% higher indoors, amplifying the importance of tiebreak situational skill.",
        "links": ["tiebreak_situational_play", "day_night_session_conditions", "altitude_ball_flight", "heat_climate_endurance"],
    },
    {
        "slug": "altitude_ball_flight",
        "title": "High-Altitude Ball-Flight Condition",
        "summary": "Thin-air effects on ball speed and bounce at high-elevation venues produce elevated ace rates, shorter rally lengths, and reduced break frequency; competitors with serve-dominant styles benefit disproportionately.",
        "stat_signature": "At venues above 1,500 m elevation, ace-rate rises 20-35% above sea-level baseline on the same surface type; average rally length contracts 1.2-2.2 shots; break frequency falls 12-18% relative to comparable sea-level events.",
        "mechanism": "Reduced air density decreases aerodynamic drag on the ball, increasing serve speed at impact and reducing the time available for the returner to set up; the ball also skids lower on the bounce, further compressing return preparation time.",
        "conditions": "Effect is largest on hard courts where ball skid is already pronounced; on clay the high bounce characteristic of the surface partially counteracts the speed gain; humid conditions at altitude partially offset the drag reduction.",
        "magnitude": "Service hold-rate at high-altitude hard courts averages 3-6 pp above comparable sea-level hard-court events; the gap in hold-rate between serve-dominant and return-dominant competitors is 15-25% wider at altitude.",
        "links": ["indoor_outdoor_environment", "tiebreak_situational_play", "day_night_session_conditions"],
    },
    {
        "slug": "day_night_session_conditions",
        "title": "Day and Night Session Conditions",
        "summary": "Cooler, denser night-session air on outdoor courts slows ball flight and increases bounce height relative to warmer afternoon conditions, producing session-based differences in ace-rate, rally length, and hold-rate.",
        "stat_signature": "Night-session ace-rate on outdoor hard courts is 10-18% below day-session on the same court; average rally length is 0.6-1.1 shots longer at night; service hold-rate is 2-4 pp lower at night due to slower ball flight aiding the returner.",
        "mechanism": "Cooler air is denser, increasing aerodynamic drag on the ball; combined with lower court surface temperature reducing bounce heat, the ball sits up slightly higher, giving the returner marginally more preparation time.",
        "conditions": "Most pronounced in late-summer tournaments where day-night temperature differentials exceed 10°C; at indoor events the session distinction is eliminated; on clay the already-high bounce minimises the differential.",
        "magnitude": "Break frequency in night sessions at outdoor hard-court majors is 15-20% higher than in equivalent day sessions at the same event; this is sufficient to shift expected total-games distributions by 1.5-2.5 games per match.",
        "links": ["indoor_outdoor_environment", "heat_climate_endurance", "altitude_ball_flight", "rain_delay_restart"],
    },
    {
        "slug": "rain_delay_restart",
        "title": "Rain-Delay and Restart Disruption",
        "summary": "Match interruptions break competitive rhythm and alter surface conditions; hold-rate, break frequency, and unforced-error rate in the games immediately after resumption diverge from the pre-delay baseline in consistent directional patterns.",
        "stat_signature": "In the first four games after a delay exceeding 45 minutes, unforced-error rate rises 18-28% above the pre-delay match average; hold-rate in the restart segment falls 4-7 pp; the competitor who was serving at interruption shows the largest first-serve percentage drop in the restart game.",
        "mechanism": "Warm muscles cool during the delay, degrading fine-motor calibration established through prior sets; surface moisture on clay and grass alters ball skid, invalidating the bounce-height expectations both competitors had calibrated.",
        "conditions": "Largest on grass and outdoor clay where surface conditions change materially with moisture; indoor restarts without surface change show smaller and shorter restart effects; the leading competitor typically re-calibrates faster.",
        "magnitude": "Break probability in the first two games after a restart is 30-45% above the match baseline; the disruption window is typically 3-6 games before both competitors return to pre-delay performance patterns.",
        "links": ["day_night_session_conditions", "indoor_outdoor_environment", "layoff_rust_return", "set_score_state_leverage"],
    },
]
