"""Person-free Soccer space-creation concept nodes for the brain."""
from __future__ import annotations

SPORT: str = "Soccer"
FAMILY: str = "SpaceCreation"

CONCEPTS: list[dict] = [
    {
        "slug": "third_man_run_unlocking",
        "title": "Third-Man Run Unlocking",
        "summary": "Captures space opened when a first pass draws pressure and a third runner immediately attacks the vacated zone, turning two-defender commitment into a free receiving pocket.",
        "stat_signature": "Defender-attracted count on first pass >=2; third-man reception-in-space rate >=55% of sequences where >=2 defenders engage the ball-near triangle; progressive carry or shot follows >=45% of in-space receptions.",
        "mechanism": "Pressing obligations concentrate attention on the first-pass receiver; the third-man move begins before that press resolves, leaving the vacated zone unoccupied for 1-3 seconds and enabling a clean forward reception.",
        "conditions": "Most productive against high-press structures committing full lines to engagement; less effective against disciplined zonal blocks that hold shape regardless of ball movement.",
        "magnitude": "Sequences producing a genuine third-man reception in space generate xG at roughly 1.8x the rate of two-player combinations; the pocket typically exists for under 3 seconds before recovery.",
        "links": ["give_and_go_wall_pass_burst", "rotation_to_create_passing_lane", "press_release_drop_runner", "drop_off_between_lines"],
    },
    {
        "slug": "blindside_overlap_run",
        "title": "Blindside Overlap Run Separation",
        "summary": "Quantifies attacking separation created by an overlapping run arriving behind a ball-watching defender, measured as the receiver's distance from the nearest marker at the cross or cutback moment.",
        "stat_signature": "Nearest-marker gap >=4 m at delivery moment; overlap-run arrival rate (runner present at delivery) >=60% of wide-entry sequences; cross or cutback delivery accuracy into overlap zone >=50%.",
        "mechanism": "A defender focused on the ball carrier loses peripheral awareness of the overlapper; the delayed visual cue shortens the marking reaction window below the threshold required to close the gap before the delivery.",
        "conditions": "Requires a wide ball-carrier to hold the ball momentarily while the overlapper accelerates; less effective when the opposing fullback or winger tracks the run rather than the ball.",
        "magnitude": "Overlapping runners arriving with >=4 m of separation produce open shooting or crossing positions at more than 65% of deliveries; defensive recovery takes 4-6 strides from a standing start.",
        "links": ["wide_to_half_space_drift", "diagonal_run_across_face", "switch_of_play_far_side_isolation", "near_post_far_post_split_runs"],
    },
    {
        "slug": "underlap_inside_channel_run",
        "title": "Underlap Inside-Channel Run",
        "summary": "Captures space exploited by an inside underlapping run threading between a wide defender and the nearest centre-back, measured as the half-space gap width entered and progressive-pass completion into that channel.",
        "stat_signature": "Half-space gap entered >=6 m wide at run initiation; progressive-pass completion into channel >=52%; resulting shot or dangerous carry follows >=38% of successful receptions.",
        "mechanism": "Wide-oriented defenders expect and track outward runs; an inside run exploits that anticipatory bias, squeezing through the seam before the centre-back can step across without vacating central cover.",
        "conditions": "Most productive when the wide defender is positioned high and inward-tracking is not their priority; reduces effectiveness if a defensive midfielder shadows the channel behind the press.",
        "magnitude": "Completed inside-channel entries produce shots at average xG above 0.12 per attempt; the structural dilemma for the defence — cover the channel or protect central width — is resolved in the attacker's favour roughly half the time.",
        "links": ["half_space_occupation_geometry", "drop_off_between_lines", "diagonal_run_across_face", "rotation_to_create_passing_lane"],
    },
    {
        "slug": "decoy_run_marker_drag",
        "title": "Decoy Run and Marker Drag",
        "summary": "Measures space created for a teammate when a deliberate decoy run pulls a marker out of defensive shape, quantified as the vacated-zone area and the secondary receiver's freedom score at the moment of receipt.",
        "stat_signature": "Vacated-zone area >=15 m² following the marker drag; secondary receiver nearest-marker distance >=5 m; successful decoy-then-secondary combination rate >=42% when the drag exceeds 5 m.",
        "mechanism": "Man-marking systems create one-to-one tracking obligations; a purposeful decoy exploits those obligations by moving a defender away from a more dangerous zone, transferring positional advantage to the primary target.",
        "conditions": "Operates primarily against man-oriented marking structures; less disruptive against zonal defences where the departed marker's zone is covered by a neighbouring player.",
        "magnitude": "Secondary receivers freed by a successful marker drag receive the ball with >=5 m of space in more than 55% of sequences, compared with less than 20% when no drag is made; xG contribution of resulting actions rises by roughly 60%.",
        "links": ["pinning_run_backline_fixing", "false_nine_vacating_pull", "rotational_positional_swap", "third_man_run_unlocking"],
    },
    {
        "slug": "double_movement_check_and_spin",
        "title": "Double-Movement Check-and-Spin",
        "summary": "Captures striker separation generated by checking short to invite a close mark and then spinning in behind, measured as the centre-back's weight-transfer displacement and the in-behind reception rate that follows.",
        "stat_signature": "Centre-back step-up distance >=2 m on the check before the spin; in-behind reception rate >=48% when the step-up is confirmed; shot or one-on-one attempt follows >=55% of successful receptions.",
        "mechanism": "The check triggers a conditioned defensive response (step and follow); the subsequent spin exploits the defender's committed weight-transfer, requiring a full deceleration-pivot cycle before recovery is possible.",
        "conditions": "Most effective against tight man-markers who follow the shoulder-to-shoulder; less effective against high-line zones that hold position regardless of a checking movement.",
        "magnitude": "Successful double-movement separations produce in-behind receptions averaging xG above 0.22; the window of separation is typically 1-2 strides, requiring a well-timed delivery from the passer.",
        "links": ["channel_run_into_depth", "false_nine_vacating_pull", "diagonal_run_across_face", "pinning_run_backline_fixing"],
    },
    {
        "slug": "pinning_run_backline_fixing",
        "title": "Pinning Run and Backline Fixing",
        "summary": "Quantifies how a high runner holds defenders deep by threatening the space in behind, measured as the distance the backline is pinned from advancing and the space opened ahead of midfield.",
        "stat_signature": "Backline drop-distance maintained >=8 m deeper than team's median set position when runner is active; midfield corridor depth freed >=10 m; pass-into-corridor completion rate >=50% in pinned phases.",
        "mechanism": "A runner threatening depth forces the last defender to hold position rather than step; this creates a structural void in front of the back line where pocket receivers or late-arriving midfielders can operate freely.",
        "conditions": "Requires a credible speed or timing threat from the runner that the defender cannot discount; less constraining when the opposing line communicates a zonal step-up collectively.",
        "magnitude": "Phases with an active pinning runner see midfield corridor depth increase by 8-12 m; the freed space generates progressive-pass completion rates roughly 25% above phases without a dedicated depth threat.",
        "links": ["channel_run_into_depth", "decoy_run_marker_drag", "drop_off_between_lines", "false_nine_vacating_pull"],
    },
    {
        "slug": "diagonal_run_across_face",
        "title": "Diagonal Run Across the Face",
        "summary": "Captures separation from a diagonal run crossing defenders' field of view into the far channel, measured as the marker hand-off failure rate and the far-post or far-channel arrival timing.",
        "stat_signature": "Marker hand-off failure rate >=45% on diagonal runs spanning more than one defensive zone; far-channel arrival in 3.5-5.5 s from run initiation; progressive-pass reception rate >=50% at destination.",
        "mechanism": "A diagonal trajectory forces a man-marker to cross the face of a second defender, creating a hand-off decision under time pressure; communication failures or zone-boundary hesitation leave the runner unmarked at the destination.",
        "conditions": "Most productive against zonal-boundary defences where zone transitions introduce coverage ambiguity; less effective against track-and-follow man-marking with explicit hand-off protocols.",
        "magnitude": "Diagonal runs producing a hand-off failure arrive at destination unmarked in over half of instances; resulting receptions generate xG averaging 0.14-0.18, above the league mean for comparable deliveries.",
        "links": ["blindside_overlap_run", "near_post_far_post_split_runs", "rotational_positional_swap", "switch_of_play_far_side_isolation"],
    },
    {
        "slug": "rotational_positional_swap",
        "title": "Rotational Positional Swap Separation",
        "summary": "Measures space created when two attacking players exchange zones simultaneously to confuse man-marking assignments, quantified as the marking-reassignment hesitation window and the free-reception rate it produces.",
        "stat_signature": "Hesitation window (neither defender commits to a runner) >=1.5 s; free-reception rate in the hesitation window >=50%; combination follows a positional swap within 4 passes >=35% of sequences.",
        "mechanism": "Simultaneous zone exchanges require man-markers to decide instantly whether to follow or hand off; without a pre-agreed protocol, two defenders may briefly track the same runner or leave both attackers free.",
        "conditions": "Operates against teams using strict assignment-based marking; zonal organisations are less susceptible because coverage passes to whoever enters the zone.",
        "magnitude": "Swaps generating a hesitation window of >=1.5 s produce a free-reception opportunity in over half of attempts; xG per resulting action is roughly 35% higher than equivalent possessions without positional exchange.",
        "links": ["decoy_run_marker_drag", "false_nine_vacating_pull", "third_man_run_unlocking", "drop_off_between_lines"],
    },
    {
        "slug": "drop_off_between_lines",
        "title": "Drop-Off Between Lines Reception",
        "summary": "Captures separation a player gains by dropping into the gap between midfield and defence, measured as receiving distance from the nearest defender and forward-turn completion rate.",
        "stat_signature": "Nearest-defender distance at receipt >=4 m; forward-turn completion rate >=60% when >=4 m of space is present; progressive action (carry or pass) into final third follows >=55% of successful turn completions.",
        "mechanism": "Dropping below the opposition's midfield line exits tracking responsibilities; the defensive midfielder must choose between following and leaving a gap or holding structure and conceding the reception — both options create space.",
        "conditions": "Most productive against teams pressing with a two-forward structure that leaves a pocket naturally; less exploitable when a third midfielder tracks drops aggressively.",
        "magnitude": "Successful between-lines receptions with >=4 m of space produce forward progressions at 65-70% rates; these progressions are the single most common precursor to central attacks generating xG above 0.15.",
        "links": ["third_man_run_unlocking", "press_release_drop_runner", "rotation_to_create_passing_lane", "inter_line_distance_geometry"],
    },
    {
        "slug": "wide_to_half_space_drift",
        "title": "Wide-to-Half-Space Drift",
        "summary": "Quantifies space created when a wide attacker drifts inside to occupy the half-space, simultaneously freeing the overlapping fullback's touchline corridor and opening an outside-to-inside shooting angle.",
        "stat_signature": "Winger average lateral position: >=6 m inside the touchline in attacking third; fullback touchline-corridor width freed >=8 m; half-space touch-share rising >=8 percentage points above baseline when drift is active.",
        "mechanism": "The tracking fullback faces a coverage dilemma: follow the drifting winger inside and vacate the channel, or hold width and concede a half-space pocket; either choice creates exploitable space for the attacking unit.",
        "conditions": "Requires a fullback capable and willing to advance into the freed corridor; less structurally productive against wingbacks who remain wide regardless of the drifting attacker's movement.",
        "magnitude": "Drift sequences produce a simultaneous half-space pocket and an open touchline run in roughly 55% of phases; the fullback's overlap generates crossing opportunities with >=40 m of open touchline in the most productive instances.",
        "links": ["blindside_overlap_run", "half_space_occupation_geometry", "fullback_height_width_geometry", "underlap_inside_channel_run"],
    },
    {
        "slug": "give_and_go_wall_pass_burst",
        "title": "Give-and-Go Wall-Pass Burst",
        "summary": "Captures the separation regenerated by a one-touch wall pass that bypasses a committed defender, measured as the bypassed-defender count and the post-combination progression distance.",
        "stat_signature": "Bypassed-defender count >=1 on the combination; post-combination progression distance >=10 m before next defensive engagement; completion rate of the one-touch return pass >=65%.",
        "mechanism": "A pressing defender commits body weight forward to challenge the first carrier; the wall pass is played before weight transfer completes, rendering the commitment irreversible and creating a running start for the returning runner.",
        "conditions": "Productive against aggressive one-versus-one press defenders who close short distances quickly; less effective against disciplined mid-block defences that do not commit to the carrier.",
        "magnitude": "Completed one-touch wall passes bypass >=1 defender in over 70% of executions; the resulting 10-20 m burst into space before the next defensive line engages generates progressive-pass completions at roughly 2x baseline rates.",
        "links": ["third_man_run_unlocking", "first_touch_directional_escape", "press_release_drop_runner", "rotation_to_create_passing_lane"],
    },
    {
        "slug": "first_touch_directional_escape",
        "title": "First-Touch Directional Escape",
        "summary": "Measures the separation a receiver creates with a single directional first touch away from an approaching defender, quantified as the approach-angle exploit rate and the retained-possession-into-space rate.",
        "stat_signature": "Defender approach-angle exploit rate (touch taken perpendicular to approach) >=55%; retained-possession-into-space rate >=70% when touch exceeds 1.5 m in the escape direction; resulting progressive action follows >=60% of successful escapes.",
        "mechanism": "A well-angled first touch repositions the receiver faster than the defender can alter trajectory; the defender's committed approach direction becomes a structural liability, converting a potential tackle into empty space.",
        "conditions": "Most effective in midfield receiving scenarios with a single approaching defender; requires spatial awareness of open corridors before receipt; less productive when surrounded by multiple defenders at close range.",
        "magnitude": "Receivers consistently executing directional first touches retain possession under pressure at rates 20-25% above league mean and generate progressive actions roughly 15% more frequently than those receiving with a stationary first touch.",
        "links": ["give_and_go_wall_pass_burst", "drop_off_between_lines", "press_release_drop_runner", "double_movement_check_and_spin"],
    },
    {
        "slug": "near_post_far_post_split_runs",
        "title": "Near-Post and Far-Post Split Runs",
        "summary": "Captures the box separation from coordinated attacking runs stretching across both near and far post zones simultaneously, measured as the inter-runner gap created at the delivery moment and unmarked-arrival frequency.",
        "stat_signature": "Inter-runner lateral gap >=12 m across both post zones; unmarked-arrival rate at delivery >=45% when both zones are occupied; shot-on-target rate from far-post receptions >=38%.",
        "mechanism": "Occupying both post zones forces a zonal defensive line into a spacing decision; covering both extremes stretches the line beyond its capacity to defend centrally, while collapsing centrally surrenders both post zones.",
        "conditions": "Most effective on deep and wide deliveries into the box; man-marking adapts by assigning individual runners, creating runner-pull vulnerabilities elsewhere at the cost of zone coverage.",
        "magnitude": "Coordinated split-run deliveries produce shots from the far-post zone at xG averaging 0.14-0.17; the inter-runner gap generates a second attacking opportunity on a defensive clearance roughly 30% of the time.",
        "links": ["blindside_overlap_run", "diagonal_run_across_face", "box_occupation_attacking_geometry", "near_post_far_post_split_runs"],
    },
    {
        "slug": "press_release_drop_runner",
        "title": "Press-Release Drop Runner",
        "summary": "Quantifies how a runner dropping to receive under press creates a structured bounce-pass exit, measured as the vacated forward-line space above the drop and the press-bypass completion rate.",
        "stat_signature": "Vacated forward-line space created >=12 m above the drop point; press-bypass completion rate >=58% when the drop runner receives and plays forward in one touch; resulting forward progression >=15 m follows >=40% of bypasses.",
        "mechanism": "The drop forces one or two midfielders to follow, collapsing the first press line; the bounce pass re-engages the forward-line runners into the space vacated by the following midfielder, inverting the press's structural intent.",
        "conditions": "Effective against teams pressing with forwards and midfielders in coordinated units; less disruptive when only one player follows the drop and the second press line remains intact.",
        "magnitude": "Sequences using a genuine drop runner to escape press complete a forward progression in 55-65% of cases; the vacated space above absorbs the second press line, producing a >=15 m corridor in roughly 40% of successful bypasses.",
        "links": ["drop_off_between_lines", "third_man_run_unlocking", "give_and_go_wall_pass_burst", "first_touch_directional_escape"],
    },
    {
        "slug": "channel_run_into_depth",
        "title": "Channel Run Into Depth",
        "summary": "Captures separation from a straight run into the channel between centre-back and fullback behind a high defensive line, measured by offside-line breaking timing and through-ball reception-in-behind rate.",
        "stat_signature": "Offside-line breaking timing: <=0.3 s ahead of ball release; through-ball reception-in-behind rate >=42%; resulting shot within 6 seconds of reception >=50%.",
        "mechanism": "A correctly timed diagonal or straight run into the channel exploits the spatial boundary between two defenders' coverage zones while using the offside line as a timing reference; an accurate through-ball bypasses the entire defensive structure.",
        "conditions": "Requires a high defensive line and an accurate through-ball capable of being played into a narrow channel; most dangerous against coordinated zonal lines with synchronisation gaps.",
        "magnitude": "In-behind receptions in the channel produce shots averaging xG above 0.30; the tight margin for timing means unsuccessful attempts result in offside calls roughly 35% of the time, making accuracy the binding constraint.",
        "links": ["depth_in_behind_space_geometry", "pinning_run_backline_fixing", "double_movement_check_and_spin", "diagonal_run_across_face"],
    },
    {
        "slug": "false_nine_vacating_pull",
        "title": "False-Nine Vacating Pull",
        "summary": "Measures space created centrally when a forward drops deep to pull a centre-back upfield, quantified as the opened central void size and the late-runner exploitation rate of that void.",
        "stat_signature": "Centre-back step-up distance >=5 m from starting line when following the drop; central void area created >=20 m²; late-runner exploitation rate (unmarked arrival into void) >=40%.",
        "mechanism": "A deep-dropping forward creates a binary decision for the centre-back: follow and open a central void, or hold and concede a free reception below the line; either choice creates exploitable space for runners arriving from deeper positions.",
        "conditions": "Requires a numerically free late-runner able to exploit the central void before the covering midfielder or the vacating centre-back recovers; less effective against 5-3-2 shapes with a natural deep-central cover.",
        "magnitude": "Phases generating a >=20 m² central void from a false-nine pull produce unmarked late-runner arrivals in roughly 40% of sequences; those arrivals generate shots averaging xG above 0.18.",
        "links": ["pinning_run_backline_fixing", "decoy_run_marker_drag", "drop_off_between_lines", "rotational_positional_swap"],
    },
    {
        "slug": "switch_of_play_far_side_isolation",
        "title": "Switch-of-Play Far-Side Isolation",
        "summary": "Captures separation generated by rapidly switching possession to a wide attacker before the defensive block completes its lateral shift, measured as the far-side marker recovery distance and one-on-one entry rate.",
        "stat_signature": "Far-side marker recovery distance >=6 m at the moment of receipt; one-on-one entry rate >=55% on successful switches; one-on-one outcome (dribble past or shot) >=48%.",
        "mechanism": "A ball-oriented block shifts toward the ball, shortening the far-side corridor; a quick vertical switch exploits the shift-in-progress window, finding an isolated attacker before the far-side defender returns to a tight marking position.",
        "conditions": "Requires high-speed switch delivery over >=35 m; most productive against flat ball-oriented defensive blocks; less effective against teams that hold width regardless of ball position.",
        "magnitude": "Far-side receptions with >=6 m of separation produce one-on-one duels at over 55% frequency; attackers winning those duels generate xG above 0.15 per sequence, making rapid-switch creation one of the most measurable space-creation levers.",
        "links": ["wide_to_half_space_drift", "blindside_overlap_run", "diagonal_run_across_face", "wide_overload_isolation_geometry"],
    },
    {
        "slug": "ball_carrier_drive_drawing_collapse",
        "title": "Carry-Drive Drawing Collapse",
        "summary": "Quantifies the space opened for teammates when a ball-carrier drives directly at a defensive block and collapses multiple defenders toward the ball, measured as defenders-attracted count and release-pass open-receiver rate.",
        "stat_signature": "Defenders-attracted count >=2 toward the carrier within 5 m; release-pass open-receiver rate (nearest marker >=3 m) >=50%; resulting shot or dangerous attack follows >=40% of successful releases.",
        "mechanism": "A driving carrier forces a collective defensive response; attracting two defenders creates a numerical imbalance elsewhere; the release pass finds that imbalanced zone before covering players can recover to tracking positions.",
        "conditions": "Effective in midfield-to-final-third transitions when the defensive block is not yet set; less productive inside a compact low block where covering players maintain density regardless of the drive.",
        "magnitude": "Drives attracting >=2 defenders produce a release-pass open-receiver scenario in over half of attempts; those open receivers create shots averaging xG 0.10-0.14, matching or exceeding set-piece-origin shot quality.",
        "links": ["give_and_go_wall_pass_burst", "rotational_positional_swap", "switch_of_play_far_side_isolation", "third_man_run_unlocking"],
    },
    {
        "slug": "rotation_to_create_passing_lane",
        "title": "Rotation to Open a Passing Lane",
        "summary": "Measures how a player's lateral or diagonal movement bends a covering defender off the passing lane to a teammate, quantified as the lane-angle opened in degrees and the line-breaking-pass completion rate into it.",
        "stat_signature": "Lane-angle opened >=12 degrees from the cover-shadow axis; line-breaking-pass completion rate >=55% when angle exceeds 12 degrees; the resulting receive-and-turn rate >=60%.",
        "mechanism": "A covering defender positions to screen a passing lane; a nearby attacker's movement forces the screener to shift body orientation, inadvertently opening the lane on one side; timing the pass to the instant of repositioning maximises the opportunity window.",
        "conditions": "Most effective when a wide or half-space runner draws the screener across their body line; requires coordinated timing between the moving decoy and the passer; less productive against deep-block teams without active first-line pressure.",
        "magnitude": "Lane openings exceeding 12 degrees produce line-breaking completions at nearly twice the rate of screened attempts; the subsequent turn-and-progress sequence reaches the final third in roughly 55% of cases, making lane rotation a structural multiplier for possession-based teams.",
        "links": ["drop_off_between_lines", "third_man_run_unlocking", "decoy_run_marker_drag", "first_touch_directional_escape"],
    },
]
