"""NBA / SpaceCreation — person-free concept nodes for the brain expansion engine."""
from __future__ import annotations

SPORT = "NBA"
FAMILY = "SpaceCreation"

CONCEPTS: list[dict] = [
    {
        "slug": "off_ball_screen_separation_rate",
        "title": "Off-Ball Screen Separation Generation",
        "summary": "Pin-downs, flares, and away screens force trailing defenders through contact, creating a catch-window lag measured as nearest-defender distance gained per screen event and resulting open-catch frequency.",
        "stat_signature": "Open-catch rate (defender >4 ft) on off-ball screens: league median ≈38%; elite off-ball movers >52%. Nearest-defender distance gain per screen ≈1.8–3.5 ft depending on screen angle and defensive scheme.",
        "mechanism": "A legal screen transfers the defender's momentum cost to the screener's body, creating a lag between when the cutter clears and when the defender recovers. Wider screen angles and tighter cutter timing compound the recovery deficit.",
        "conditions": "Most effective against aggressive man coverage that over-pursues on the high side; partially neutralised by switch-heavy schemes. Amplified in wide-court sets where spaced floor occupants pull help away.",
        "magnitude": "Transitioning from a guarded (0–2 ft) to an open (>4 ft) catch roughly doubles catch-and-shoot make-rate on corner and wing attempts in aggregate sample data.",
        "links": ["stagger_screen_compounding", "rescreen_re_separation", "screen_contact_disruption_separation", "v_cut_l_cut_setup_displacement"],
    },
    {
        "slug": "gravity_driven_help_displacement",
        "title": "Gravity-Driven Help Displacement",
        "summary": "A shooting threat's defender refusing to leave the shooter creates a rotational void: the nearest help defender must cover either the threat or the paint, and that commitment gap opens a weak-side window.",
        "stat_signature": "Defences shade help toward shooters rated >38% on catch-and-shoot; the weak-side gap widens by ≈3–6 ft at the catch. Corner-three open-look frequency lifts ~14 pp versus lineups with no spacing threat.",
        "mechanism": "Defender positioning is a resource-allocation problem; a credible shooting threat compels coverage that displaces the help network, creating vacancies at the rim or backside without the threat touching the ball.",
        "conditions": "Strongest when the spacing threat occupies a corner or wing with the ball on the opposite side. Less effective against true drop-back schemes that cede the three-point line outright.",
        "magnitude": "Lineups with a corner threat show at-rim attempt rates roughly 8–12% higher than lineups without one, indicating structural space gain rather than a defensive collapse.",
        "links": ["weak_side_lift_clearance", "decoy_action_attention_pull", "relocation_drift_after_drive"],
    },
    {
        "slug": "screen_navigation_lag_window",
        "title": "Screen-Navigation Lag Window",
        "summary": "When a defender fights over or under a ball screen, a timing gap opens between screen contact and defensive recovery, measured as time-to-recovery in tenths of a second and shot make-rate within that window.",
        "stat_signature": "Defender recovery after fighting over a ball screen: ≈0.6–1.2 s for mobile guards; ≈1.4–2.1 s for slower bigs. Shots released inside the lag window show eFG roughly 6–9 points above the shooter's overall catch-and-shoot baseline.",
        "mechanism": "A screener's body absorbs the defender's lateral momentum, forcing a course correction. The ball handler reads the recovery angle and releases before the defender re-establishes a contest window.",
        "conditions": "Most exploitable when the screened defender is slow over screens or switches late. Hedging eliminates the lag window but exposes the roll man; under-hedging widens the pull-up window.",
        "magnitude": "Pull-up attempts within the lag window show a ≈+5–8 point eFG premium relative to contested pull-ups taken after recovery; the window narrows sharply under hedge-and-recover schemes.",
        "links": ["off_ball_screen_separation_rate", "stagger_screen_compounding", "ghost_screen_slip_separation", "rescreen_re_separation"],
    },
    {
        "slug": "ghost_screen_slip_separation",
        "title": "Ghost Screen and Slip Separation",
        "summary": "Faking a screen and slipping early exploits the defending big's pre-committed hedge, creating a lane gap before he can recover, measured as hedge-mistime distance and slip-to-catch open-lane frequency.",
        "stat_signature": "Slip-screen possessions generate at-rim attempts at ≈1.4–1.7× the rate of standard pick-and-roll reps; catch-in-paint frequency on slips ≈35–45% versus ≈18–25% on standard rolls.",
        "mechanism": "The defender anticipates a screen and pre-hedges; the slip reverses the screener's trajectory before contact, leaving a gap between a defender already displaced laterally and a roll man not yet covered.",
        "conditions": "Most effective against hard-show and hedge-and-recover schemes. Less effective against drop coverage, which does not hedge and has nothing to exploit.",
        "magnitude": "Slip actions correlate with at-rim attempts worth ≈1.25–1.35 ppp, above the league-average pick-and-roll value of roughly 0.95–1.05 ppp.",
        "links": ["screen_navigation_lag_window", "dho_handoff_momentum_separation", "screen_angle_reject_counter"],
    },
    {
        "slug": "relocation_drift_after_drive",
        "title": "Post-Drive Relocation Drift",
        "summary": "As a ball handler drives and collapses the lane, a spaced shooter drifts laterally along the arc away from the closing help defender, reducing the defender's closeout angle and extending the open window.",
        "stat_signature": "Corner drift of ≥5 ft during a live drive reduces the help-closeout angle by ≈15–25°, cutting effective closeout distance by 1–2 ft. Drive-and-kick open-catch rate rises ≈8–12 pp when the receiver has relocated versus stayed stationary.",
        "mechanism": "Help defenders collapse along the most direct paint path; a drifting receiver forces that defender to adjust both direction and distance mid-closeout, creating a timing and angle disadvantage.",
        "conditions": "Most effective in wide-set offences with receivers in corners and wings. Partially neutralised by zone schemes where defenders guard areas rather than tracking individual receivers.",
        "magnitude": "Drive-and-kick corner-three make rates increase roughly 4–7 pp when the receiver is in motion at catch time, consistent with the elongated closeout angle reducing contest quality.",
        "links": ["gravity_driven_help_displacement", "weak_side_lift_clearance", "decoy_action_attention_pull"],
    },
    {
        "slug": "backdoor_timing_separation",
        "title": "Backdoor Cut Timing Separation",
        "summary": "A receiver attacks an over-playing denial defender with a backdoor cut, generating separation as a function of how far the defender has leaned toward the ball, measured as cut-success rate versus denial-lean angle.",
        "stat_signature": "Backdoor cuts succeed (open catch in the paint) at ≈55–68% when the denial defender's hip angles >45° toward the ball; success drops to ≈25–35% against a balanced open stance. Clean-backdoor layup conversion ≈68–74%.",
        "mechanism": "Denial defence positions the defender ahead of the pass lane, rotating hips toward the ball. A quick two-step toward the basket exploits that weight distribution and the reaction time required to reverse direction.",
        "conditions": "Emerges against aggressive man-to-man denial schemes. Requires a capable passer who reads the lean in real time; rare against zone where denial is area-based.",
        "magnitude": "Clean backdoor catches in the paint yield approximately 1.35–1.55 expected points per possession, above the league-average half-court offensive value of roughly 1.0 ppp.",
        "links": ["v_cut_l_cut_setup_displacement", "split_cut_two_man_separation", "decoy_action_attention_pull"],
    },
    {
        "slug": "rip_through_first_step_burst",
        "title": "Rip-Through First-Step Burst Separation",
        "summary": "A live-dribble attacker rips through a high defensive hand and explodes laterally, generating initial separation measured as defender lateral displacement and time-to-paint before help arrives.",
        "stat_signature": "Elite first-step attackers reach the paint in ≤1.5 s from a rip initiation; average attackers take ≥1.9 s, giving help an additional ≈0.4 s. Rim-attempt frequency is roughly 2.1× higher when time-to-paint is <1.5 s.",
        "mechanism": "The rip redirects the defender's overextended hand upward, creating a brief body-contact shield for the first crossover step. Acceleration on step one exploits hip-rotation lag — defenders need ≈0.3 s to redirect lateral momentum.",
        "conditions": "Most productive when the on-ball defender extends a high hand on the catch. Less effective against passive drop-back defenders who yield the first step to protect the paint.",
        "magnitude": "Possessions with sub-1.5 s time-to-paint yield at-rim attempts at ≈1.4 ppp versus ≈0.95 ppp on slower drives where help assembles before the attacker reaches the paint.",
        "links": ["hesitation_deceleration_recreation", "screen_angle_reject_counter", "dho_handoff_momentum_separation"],
    },
    {
        "slug": "rescreen_re_separation",
        "title": "Re-Screen Re-Separation Sequencing",
        "summary": "A second immediate screen set after a defender recovers from the first regenerates a recovery deficit before the defender has reset stance, quantified as the cumulative two-action recovery gap and second-action open-rate lift.",
        "stat_signature": "Second-screen open-catch rate is ≈8–15 pp higher than the first screen in the same possession. Stagger actions that force two sequential fights show catch-and-shoot eFG roughly 4–6 pp above single-screen actions.",
        "mechanism": "Defender recovery requires decelerating, locating the cutter, and re-establishing stance — a sequence taking ≈0.6–1.0 s. A second screen initiated during that sequence re-starts it while the defender is mid-recovery, compounding positional debt.",
        "conditions": "Effective against any man coverage that fights over screens. Diminished by switch-everything schemes that transfer coverage to a fresh defender and avoid sequential recovery.",
        "magnitude": "Two-screen sequences increase possession-level eFG by ≈4–7 points versus single-screen actions, with the largest gaps when the first screen forces a high-side fight.",
        "links": ["off_ball_screen_separation_rate", "stagger_screen_compounding", "screen_navigation_lag_window"],
    },
    {
        "slug": "dho_handoff_momentum_separation",
        "title": "Dribble-Handoff Momentum Separation",
        "summary": "A moving dribble-handoff transfers ball momentum to the receiver, who catches into a live dribble with a trailing defender, measured as trail distance at the catch and downhill rim-attack frequency.",
        "stat_signature": "DHO actions produce a ball-handler trail gap of ≈1.5–3.2 ft at the catch. Downhill drive frequency off DHO ≈42–55% versus ≈28–35% off stationary catches, reflecting the momentum advantage.",
        "mechanism": "The ball carrier builds lateral momentum before the exchange; the receiver inherits that direction and speed. The defending receiver's man must either trail the momentum or switch, both creating a gap — trail yields a downhill lane; late switch yields a mismatch.",
        "conditions": "Most effective when the dribbler attacks downhill at the point of exchange and the receiver can shoot or drive. Switch-heavy defences neutralise momentum but create mismatch consequences instead.",
        "magnitude": "DHO actions generate rim-attempt rates approximately 1.3× higher than catch-and-set actions, consistent with the momentum-derived defender trail gap enabling earlier drive initiation.",
        "links": ["ghost_screen_slip_separation", "rip_through_first_step_burst", "screen_navigation_lag_window"],
    },
    {
        "slug": "stagger_screen_compounding",
        "title": "Stagger-Screen Compounding Separation",
        "summary": "Sequential double screens compound a defender's recovery deficit by forcing two sequential hip-direction changes in a confined time window, measured as separation gained per additional screen and the open-catch curve.",
        "stat_signature": "Catch-and-shoot eFG on stagger exits: ≈55–62% versus ≈49–54% on single off-ball screens — a ≈6–8 point lift attributable to the compounded recovery deficit. Lift is larger when screens are set ≥15 ft from the basket.",
        "mechanism": "Each screen requires a distinct recovery sequence: decelerate, locate, redirect. Stacking two screens with minimal spacing forces both sequences to overlap, creating a combined deficit that exceeds the sum of individual screen costs.",
        "conditions": "Maximally effective against teams that fight through every screen; partially countered by switching every screen, which trades recovery deficit for a potential mismatch.",
        "magnitude": "Stagger actions yield open-catch frequency ≈10–16 pp above the league-average off-ball open-catch rate, with the upper range when both screeners are positioned at the wing or corner.",
        "links": ["off_ball_screen_separation_rate", "rescreen_re_separation", "screen_navigation_lag_window", "iverson_cut_cross_floor_separation"],
    },
    {
        "slug": "v_cut_l_cut_setup_displacement",
        "title": "V-Cut and L-Cut Setup Displacement",
        "summary": "A perimeter receiver sets up a catch by planting and changing direction sharply (V-cut) or changing plane from baseline to wing (L-cut), measured as defender weight-shift displacement and catch-cleanliness rate.",
        "stat_signature": "A sharp V-cut with ≥45° direction change shifts the defender's weight by ≈0.5–1.2 ft, opening a catch window of ≈0.4–0.8 s. Clean-catch rate is ≈62–72% on well-executed setups versus ≈38–48% on flat relocations.",
        "mechanism": "The setup step commits the defender's weight in one direction; the sharp cut exploits the ≈0.3 s hip-redirect lag. The L-cut adds a plane change, requiring simultaneous lateral and vertical positional adjustment.",
        "conditions": "Effective across man-coverage schemes; especially productive against defenders who anticipate a straight cut. Reduced by zone defences where there is no individual to plant-step against.",
        "magnitude": "Receivers who average ≥1 sharp cut setup per possession show catch-and-shoot open-look rates ≈10–14 pp higher than those primarily relocating on straight lines.",
        "links": ["backdoor_timing_separation", "off_ball_screen_separation_rate", "split_cut_two_man_separation"],
    },
    {
        "slug": "decoy_action_attention_pull",
        "title": "Decoy-Action Attention Pull",
        "summary": "A strong-side action draws defender eyes and rotational bodies away from the weak side, creating an attention-lapse gap for a backside cutter or shooter measured as weak-side defender displacement and backside open-rate.",
        "stat_signature": "Rotations to a strong-side action leave a weak-side receiver unguarded for ≈0.3–0.8 s; corner-three open frequency from skip passes during a drive reaches ≈68–75% compared with ≈42–50% on static ball movement.",
        "mechanism": "Defensive rotations are triggered by ball movement and drive penetration; the rotation path pulls bodies and attention toward the ball. The weak-side gap is an indirect byproduct of that rotation, not a primary defensive concession.",
        "conditions": "Emerges in drive-heavy offences with credible backside spacing threats. Zone defences mitigate the effect by guarding areas rather than tracking individual strong-side actions.",
        "magnitude": "Skip-pass corner-three shots following a strong-side drive carry an eFG premium of ≈5–9 points above the same shooter's baseline, attributable to the attention-lag catch window.",
        "links": ["gravity_driven_help_displacement", "relocation_drift_after_drive", "weak_side_lift_clearance"],
    },
    {
        "slug": "screen_angle_reject_counter",
        "title": "Screen-Reject Counter Separation",
        "summary": "Rejecting a set screen and attacking the vacated side exploits the help defender's pre-committed hedge position, measured as the mis-positioning gap and the reject-drive rim-finish rate.",
        "stat_signature": "Reject drives reach the paint against a mis-positioned big at roughly 1.8× the rate of standard pick-and-roll reps. Rim-attempt rate on clean rejects ≈38–48%.",
        "mechanism": "A hard-hedging big commits his body toward the expected ball-handler direction; the reject reverses that expectation and attacks the vacated space, requiring a 180° redirect that creates a ≈0.6–1.2 s gap.",
        "conditions": "Requires a hard-show or hedge-and-recover scheme from the defending big. Less productive against drop-back coverage where the big never hedges.",
        "magnitude": "Reject actions against hard-hedging bigs yield approximately 1.2–1.4 ppp at the rim, above the baseline pick-and-roll average of ≈0.95–1.05 ppp, reflecting the mis-positioning advantage.",
        "links": ["ghost_screen_slip_separation", "rip_through_first_step_burst", "screen_navigation_lag_window", "dho_handoff_momentum_separation"],
    },
    {
        "slug": "hesitation_deceleration_recreation",
        "title": "Hesitation and Deceleration Re-Creation",
        "summary": "A live-dribble attacker decelerates to bait a defender's overcommit then re-accelerates, exploiting the defender's forward lean, measured as defender momentum-overcommit distance and re-burst rim-attack rate.",
        "stat_signature": "Hesitation dribbles inducing ≥0.3 ft defender forward lean produce re-burst rim attempts at ≈1.7× the rate of steady-pace drives. At-rim conversion following a clean hesitation re-burst ≈62–68%, above the average layup conversion of ≈58–63%.",
        "mechanism": "Defenders in pursuit mode accelerate to close; a sudden attacker deceleration causes the defender to over-run or lean forward, transferring momentum advantage to the attacker for the subsequent direction change.",
        "conditions": "Most effective against aggressive closeout defenders. Less productive against passive drop-back defenders who do not overcommit momentum during pursuit.",
        "magnitude": "Hesitation-triggered re-bursts yield roughly 0.10–0.18 extra expected points per possession versus straight-line drives at equivalent distances, attributable to the improved basket angle from the defender's displaced position.",
        "links": ["rip_through_first_step_burst", "backdoor_timing_separation", "screen_angle_reject_counter"],
    },
    {
        "slug": "weak_side_lift_clearance",
        "title": "Weak-Side Lift and Lane Clearance",
        "summary": "A weak-side player lifting from the corner to the wing during a strong-side drive pulls the low-man help defender upward, widening the driving lane measured as cleared-lane width and at-rim conversion lift.",
        "stat_signature": "A low-man lift pulling the help defender ≥8 ft from the paint widens the driving lane by ≈4–7 ft at the charge-circle level. At-rim attempt frequency rises ≈6–10 pp versus possessions where the weak-side player stays stationary.",
        "mechanism": "Help defenders protect the paint by positioning between ball and basket; a lifting receiver with credible shooting threat compels the defender upward along the help line, widening the gap between the defender and the rim.",
        "conditions": "Requires a weak-side player who is a credible three-point threat; a non-shooter lifting is abandoned by the help defender. Amplified in five-out sets where every help defender must track a receiver.",
        "magnitude": "Five-out offences generate at-rim attempt rates roughly 12–18% higher than four-out-one-post sets, partly attributable to the absence of a low-man help anchor.",
        "links": ["gravity_driven_help_displacement", "decoy_action_attention_pull", "relocation_drift_after_drive"],
    },
    {
        "slug": "split_cut_two_man_separation",
        "title": "Split-Cut Two-Man Separation",
        "summary": "Two off-ball players screen each other off a post or top entry, creating simultaneous separation for both cutters, measured as the open-cutter gap and split-action open-catch conversion rate.",
        "stat_signature": "Split-cut actions generate at least one open-catch opportunity on ≈55–65% of possessions; open-catch conversion on split exits ≈48–56% versus ≈38–44% on standard single cuts.",
        "mechanism": "Two defenders tracking two crossing cutters must choose between following their man (risking screen contact) or switching (risking the trailing cutter). Either outcome produces a brief open window for one receiver.",
        "conditions": "Requires a post entry or top-of-key ball handler who reads which cutter becomes open. Most effective against man-to-man help structures; zone defences guard areas and are less disrupted by crossing paths.",
        "magnitude": "Split-cut sets show open-look rates ≈10–15 pp above single off-ball cut actions, consistent with the simultaneous two-defender commitment forcing one to concede position.",
        "links": ["backdoor_timing_separation", "v_cut_l_cut_setup_displacement", "off_ball_screen_separation_rate"],
    },
    {
        "slug": "iverson_cut_cross_floor_separation",
        "title": "Cross-Floor Wing-Sweep Separation",
        "summary": "Sweeping a receiver across the elbows off staggered screens generates cumulative separation as the defender trails the full floor width, measured as defender trail distance across the floor and catch-and-go frequency.",
        "stat_signature": "Cross-floor sweeps off stagger screens force the defender to travel ≈20–28 ft laterally; catch open-rate (defender >4 ft) ≈58–70%, among the highest of any off-ball action. Catch-and-go drives off the sweep ≈25–35% of exits.",
        "mechanism": "The defender must maintain proximity across the entire width of the floor while absorbing screen contact at each screen station; cumulative lateral travel and repeated screen contact compound fatigue and positional error.",
        "conditions": "Requires at least two screeners positioned at elbow or wing stations and a ball handler who times the skip pass to the catch window. Effective against both man and certain help-heavy zone coverages.",
        "magnitude": "Cross-floor sweeps generate open catch-and-shoot rates ≈12–18 pp above the league-average off-ball open rate, with the highest values when both screen contacts are made before the catch.",
        "links": ["stagger_screen_compounding", "off_ball_screen_separation_rate", "rescreen_re_separation"],
    },
    {
        "slug": "screen_contact_disruption_separation",
        "title": "Screen-Contact Disruption Separation",
        "summary": "Legal screen contact that physically delays the defender produces a measurable contact-induced recovery delay and a corresponding open-shot rate premium, distinct from positional lag created by screen angle alone.",
        "stat_signature": "Screens with body contact delay defender recovery by ≈0.2–0.5 s compared to no-contact screens, lifting open-catch rate by ≈4–7 pp on perimeter actions. Screener foul rate on legal contact screens varies by crew tendency (≈4–9%).",
        "mechanism": "Physical contact transfers momentum from the moving defender to the stationary screener's body, absorbing lateral speed and requiring the defender to re-establish stance and direction — directly extending the lag window.",
        "conditions": "Effective when the screener establishes legal position before contact and the defender is moving at high speed. Referee crew contact-tolerance tendencies modulate how much contact is permitted without a foul call.",
        "magnitude": "Possessions with confirmed screen contact show ≈4–7 pp higher open-catch frequency than screens generating separation through angle alone, implying contact adds roughly one-quarter to one-third of an additional step of separation.",
        "links": ["off_ball_screen_separation_rate", "ghost_screen_slip_separation", "stagger_screen_compounding", "rescreen_re_separation"],
    },
]
