"""Space-creation concepts for Tennis. Person-free, descriptive."""
from __future__ import annotations

SPORT = "Tennis"
FAMILY = "SpaceCreation"

CONCEPTS: list[dict] = [
    {
        "slug": "wrong_footing_recovery_exploitation",
        "title": "Wrong-Footing Recovery Exploitation",
        "summary": "Space created by hitting behind a recovering opponent against their momentum; direction-change cost produces winners or forced errors at 48-58% when the redirect arrives during mid-sprint.",
        "stat_signature": "Behind-the-runner redirects yield W/FE rates 48-58%; direction-change lag 0.3-0.5 s equates to 1.5-2.5 m of additional open court per exchange.",
        "mechanism": "A recovering opponent commits lateral momentum before contact; a shot behind that lean forces kinetic reversal that cannot begin until the stride is arrested, creating a temporal and spatial gap.",
        "conditions": "Most effective after a prior wide ball has initiated full sprint; requires disguise to prevent early momentum arrest; amplified on hard and grass surfaces where sprint momentum is harder to stop.",
        "magnitude": "Successfully wrong-footing doubles the open-court exploitation rate; the 0.35-0.50 s reversal lag leaves 2-3 m of court unprotected during the reply window.",
        "links": ["open_court_angle_creation", "disguise_delayed_shot_freeze", "rally_pattern_corner_baiting", "behind_the_player_redirection", "open_stance_recovery_advantage"],
    },
    {
        "slug": "open_court_angle_creation",
        "title": "Open-Court Angle Creation",
        "summary": "Sharp crosscourt angles drag an opponent 1.2+ m outside the sideline, exposing a 3.5+ m diagonal corridor; putaway rates into that corridor reach 55-65% when the follow-up arrives within 0.5 s.",
        "stat_signature": "Sideline overshoot >1.2 m opens corridors >3.5 m wide; follow-up putaway rates 55-65%; rally-ending within two shots estimated at 60-70% above 85 km/h.",
        "mechanism": "Lateral displacement relocates the opponent while the opposite court side stays vacant; each extra meter of overshoot nonlinearly widens the available diagonal because court width is fixed.",
        "conditions": "Most effective from a ball allowing a large racket-face angle at moderate contact height; diminished under time pressure or at contact height above the shoulder.",
        "magnitude": "A 1.5 m overshoot vacates approximately 4 m of diagonal corridor; follow-up winner rate at 60-70% when the next ball exceeds 85 km/h and arrives before opponent recovery.",
        "links": ["wrong_footing_recovery_exploitation", "two_corner_side_to_side_stretch", "short_angle_pull_off_court", "serve_wide_court_opening_deuce_ad", "inside_out_forehand_court_opening"],
    },
    {
        "slug": "first_strike_serve_plus_one_displacement",
        "title": "Serve-Plus-One Displacement",
        "summary": "Serve placement displaces the returner laterally, creating the geometry for an open-court plus-one attack; wide serves generate follow-up attack opportunities on 42-52% of non-ace rallies.",
        "stat_signature": "Wide serves pulling the returner 1.0+ m outside the sideline produce open-court plus-one chances 42-52% of rallies; plus-one forehand winner-or-forced-error rate 45-55% on hard courts.",
        "mechanism": "Serve location constrains return direction to a predictable corridor; the server pre-positions toward that corridor and attacks the reply before the returner regains neutral position.",
        "conditions": "Most effective when serve displacement prevents an aggressive neutralizing return; diminished when the returner can slice a low flat return limiting the server's attack angle.",
        "magnitude": "Serve-plus-one sequences raise first-ball winner rates from 28-35% to 45-55% when displacement exceeds 1.0 m; combined wide serve and diagonal attack forces 3-4 m coverage demand within 0.5 s.",
        "links": ["serve_wide_court_opening_deuce_ad", "body_serve_jam_then_open", "return_position_depth_steal", "approach_shot_passing_lane_squeeze", "open_court_angle_creation"],
    },
    {
        "slug": "inside_out_forehand_court_opening",
        "title": "Inside-Out Forehand Court-Opening",
        "summary": "Running around the backhand to strike inside-out opens the deuce corridor; opponents are displaced 1.0-1.8 m outside the sideline in 55-65% of exchanges, creating the inside-in finish lane.",
        "stat_signature": "Inside-out forehands within 0.6 m of the wide sideline displace opponents 1.0-1.8 m beyond it in 55-65% of exchanges; inside-in follow-up available on 38-47% of subsequent balls.",
        "mechanism": "Running around the backhand shifts position toward the ad side, enabling a forehand targeting the wide angle; the opponent recovers wide while the striker repositions center, opening a two-option inside-in threat.",
        "conditions": "Most effective when there is time to set up behind the ball; riskier when forced deep with limited time because exposing the ad-side open court invites punishment on the return.",
        "magnitude": "Consistent inside-out pressure forces opponent lateral shift of 0.5-1.0 m toward the wide side, opening the center lane 35-45% of the time; the two-option threat compresses recovery at rates near 50%.",
        "links": ["open_court_angle_creation", "rally_pattern_corner_baiting", "wrong_footing_recovery_exploitation", "two_corner_side_to_side_stretch", "open_stance_recovery_advantage"],
    },
    {
        "slug": "drop_shot_vertical_displacement",
        "title": "Drop-Shot Vertical Displacement",
        "summary": "A disguised drop shot inverts rally geometry by forcing a 6-8 m forward sprint on a deep-standing opponent; when the striker follows to net, lob-or-pass dilemma produces 55-65% W/FE rate against late arrivals.",
        "stat_signature": "Drop shots within 1.2 m of the net force sprints of 6-8 m from baseline; net-follow rate produces W/FE 55-65% against opponents arriving late; success falls to 28-35% when landing 2+ m from the net.",
        "mechanism": "A deep-court opponent must sprint forward while the striker recovers or advances; the dual space swap produces a low-contact situation for the sprinting opponent and a net-coverage position for the striker.",
        "conditions": "Requires disguise to delay opponent read; most effective when opponent is 2+ m behind baseline with backward or neutral momentum; surface matters strongly as grass produces the lowest second bounce.",
        "magnitude": "Well-disguised drop within 1.0 m of net limits successful opponent replies to 30-40% from 3+ m behind baseline; forced errors on the sprint reply alone reach 35-45%.",
        "links": ["moonball_height_recovery_steal", "depth_change_court_position_push", "net_rush_time_pressure_compression", "disguise_delayed_shot_freeze", "wrong_footing_recovery_exploitation"],
    },
    {
        "slug": "two_corner_side_to_side_stretch",
        "title": "Two-Corner Side-to-Side Stretch",
        "summary": "Alternating deep corners accumulate lateral fatigue; opponents covering 10+ m total lateral distance per rally show 15-22% accuracy degradation and concede short balls 18-28% more often from ball 6 onward.",
        "stat_signature": "Sustained 5+ ball alternating-corner patterns increase short-ball concession 18-28%; opponents covering 10+ m lateral per rally show 15-22% accuracy degradation on ball 6+.",
        "mechanism": "Each lateral sprint and recovery cycle adds kinetic cost; deceleration-reacceleration repeatedly depletes lateral power and disrupts the reply swing chain, compressing depth and pace on later balls.",
        "conditions": "Most effective on clay where rallies sustain long enough for fatigue accumulation; requires consistent depth to avoid triggering an attack-zone entry that interrupts the stretch.",
        "magnitude": "A 6-ball alternating-corner sequence raises the probability of a defensive float or short ball by 20-25 percentage points relative to the second ball of the same pattern.",
        "links": ["open_court_angle_creation", "inside_out_forehand_court_opening", "depth_change_court_position_push", "moonball_height_recovery_steal", "rally_pattern_corner_baiting"],
    },
    {
        "slug": "behind_the_player_redirection",
        "title": "Behind-the-Player Redirection",
        "summary": "Redirecting back behind an opponent committed to recovering open court exploits the 0.25-0.40 s window before they can reverse direction; W/FE rates reach 50-60% on timed redirections.",
        "stat_signature": "Timed redirections behind recovery lean produce W/FE rates 50-60%; direction-reversal lag of 0.3-0.5 s leaves the vacated side open for an estimated 0.5-0.7 s additional window.",
        "mechanism": "Any recovering opponent must lean before the ball lands; redirecting against that lean forces a momentum arrest and reversal that takes 0.3-0.5 s beyond a direct sprint, leaving the vacated side exposed.",
        "conditions": "Requires reading the opponent's lean before contact; most effective in extended rallies where opponents develop predictable recovery patterns; less effective against those who deliberately delay their recovery step.",
        "magnitude": "A timed redirection doubles the open-court exploitation rate relative to a same-direction follow-up; combined momentum arrest and spatial exposure raises point-ending probability by 30-40 percentage points.",
        "links": ["wrong_footing_recovery_exploitation", "rally_pattern_corner_baiting", "disguise_delayed_shot_freeze", "open_court_angle_creation", "open_stance_recovery_advantage"],
    },
    {
        "slug": "approach_shot_passing_lane_squeeze",
        "title": "Approach-Shot Passing-Lane Squeeze",
        "summary": "An approach within 0.8 m of one sideline compresses the crosscourt pass corridor to under 1.5 m; pass success into the remaining down-the-line lane drops to 28-38% due to a higher net margin and narrower target.",
        "stat_signature": "Crosscourt approach within 0.8 m of sideline closes crosscourt pass to under 1.5 m; DTL pass success drops to 28-38%; passing success overall falls from 42-48% to 28-36% against correctly bisected net player.",
        "mechanism": "Approaching to one side geometrically forces the passer toward the other corridor where net height is greater and the target is narrower; precision and margin demands increase simultaneously.",
        "conditions": "Most effective when the approach is deep and low, preventing an early-contact return; less effective against opponents who absorb and lob rather than pass.",
        "magnitude": "Well-placed approach reduces passing success by 12-18 percentage points; lob attempts increase 10-15 percentage points when the pass lane falls below 1.5 m wide.",
        "links": ["net_rush_time_pressure_compression", "first_strike_serve_plus_one_displacement", "open_court_angle_creation", "drop_shot_vertical_displacement", "inside_out_forehand_court_opening"],
    },
    {
        "slug": "short_angle_pull_off_court",
        "title": "Short-Angle Pull Off the Court",
        "summary": "A sharply angled short ball landing near the service-line-sideline junction pulls an opponent 0.5-1.5 m outside the singles court, exposing a 4+ m diagonal winner corridor on the follow-up.",
        "stat_signature": "Short angles within 1.5 m of net and 0.5 m of sideline pull opponents 0.5-1.5 m off court; exposed diagonal >4 m in 70-80% of cases; follow-up winner rate above 55% when struck within 0.6 s.",
        "mechanism": "The acute angle off the net post exploits the fixed width of the singles court; a landing near the sideline-service-line junction forces a reply direction that requires complete off-court movement, vacating the entire opposite diagonal.",
        "conditions": "Requires large racket-face angle at contact below shoulder height; most achievable from a wide position; most effective when the opponent is behind the baseline and not expecting a short angle.",
        "magnitude": "Off-court displacement of 1.0+ m opens a 4-5 m winner corridor; follow-up winner rate at 58-70% when struck before the opponent recovers to the sideline.",
        "links": ["open_court_angle_creation", "drop_shot_vertical_displacement", "disguise_delayed_shot_freeze", "two_corner_side_to_side_stretch", "wrong_footing_recovery_exploitation"],
    },
    {
        "slug": "depth_change_court_position_push",
        "title": "Depth-Change Court-Position Push",
        "summary": "Alternating deep and short ball lengths force contact-zone shifts of 2-3 m depth per rally; transitional replies struck mid-sprint produce errors 20-30% above those from settled positions.",
        "stat_signature": "Deep-then-short sequences create 2-3 m depth shifts per rally; transitional replies show 20-30% higher error rates and 15-20% shorter reply depth compared with settled positions.",
        "mechanism": "Contact quality peaks from settled positions; alternating depths force continuous forward-backward acceleration, disrupting the kinetic chain and reducing pace, depth, and directional precision on the transitional ball.",
        "conditions": "Requires control of both depth and shortness; most disruptive when the short ball is disguised until late contact; most effective on clay where transition distances are larger.",
        "magnitude": "Sustained 4+ ball depth-change sequences are associated with 18-26% higher error rates and 15-20% shorter reply depth on the transitional ball.",
        "links": ["drop_shot_vertical_displacement", "two_corner_side_to_side_stretch", "moonball_height_recovery_steal", "wrong_footing_recovery_exploitation", "slice_skid_low_displacement"],
    },
    {
        "slug": "serve_wide_court_opening_deuce_ad",
        "title": "Wide-Serve Court Opening by Side",
        "summary": "Wide serves pull the returner 0.8-1.5 m outside the singles sideline; the opposite diagonal is available for a W/FE follow-up at 40-50% rates, roughly 15-20 percentage points above neutral serve sequences.",
        "stat_signature": "Wide serves >150 km/h pull returner 0.8-1.5 m outside sideline in 55-65% of deliveries; open diagonal available 40-50% for a follow-up W/FE within two shots.",
        "mechanism": "Serve bounce-angle and pace drag the returner beyond the sideline; the available return corridor is constrained to a narrow crosscourt window, enabling the server to pre-load the opposite diagonal attack.",
        "conditions": "Most effective when the returner cannot redirect from wide stretch; kick serves amplify sideline carry; ad-side wide serves against a one-handed backhand compound displacement with grip reach limitation on high-kicking balls.",
        "magnitude": "A 1.2 m sideline pull opens a 3.5-4.5 m diagonal; server attacking within plus-one records W/FE rates of 42-52%, 15-20 percentage points above neutral serve sequences.",
        "links": ["first_strike_serve_plus_one_displacement", "open_court_angle_creation", "body_serve_jam_then_open", "return_position_depth_steal", "inside_out_forehand_court_opening"],
    },
    {
        "slug": "disguise_delayed_shot_freeze",
        "title": "Disguise and Delayed-Shot Freeze",
        "summary": "Disguising direction freezes the opponent's split-step commitment, delaying first-step initiation by 0.10-0.20 s — equivalent to 0.8-1.4 m extra recovery distance — and raising W/FE rates by 12-20 percentage points.",
        "stat_signature": "Disguised shots delay opponent first step by 0.10-0.20 s; equivalent to 0.8-1.4 m extra recovery distance; W/FE rates 12-20 percentage points higher than telegraphed equivalents.",
        "mechanism": "The split-step commits lateral momentum from reading swing cues; disguised shots suppress or falsify those cues until after the split-step has landed, forcing a slower neutral first step rather than a biased explosive start.",
        "conditions": "Most effective when the striker has time to maintain disguised preparation without compromising mechanics; highest value on second serves and mid-rally balls inside the baseline where opponent reaction time is short.",
        "magnitude": "A 0.15 s freeze on a per-shot basis provides 0.8-1.4 m extra distance — sufficient to convert approximately 1 in 5-6 near-winners into outright winners.",
        "links": ["wrong_footing_recovery_exploitation", "behind_the_player_redirection", "rally_pattern_corner_baiting", "short_angle_pull_off_court", "drop_shot_vertical_displacement"],
    },
    {
        "slug": "body_serve_jam_then_open",
        "title": "Body-Serve Jam-Then-Open",
        "summary": "A hip-to-shoulder body serve cramps the return swing, reducing return pace 12-20 km/h and depth 0.6-1.0 m; the resulting short or central reply creates open-court attack opportunities on 45-55% of plus-one shots.",
        "stat_signature": "Body serves at hip-shoulder height reduce return pace 12-20 km/h and depth 0.6-1.0 m; open-court attack chance on plus-one 45-55%; plus-one sequence ends point within 3 shots at estimated 55-65%.",
        "mechanism": "A body serve creates geometric conflict between the torso and the swing arc; the returner must step aside (costing time) or take the ball with a cramped swing that reduces pace, depth, and angle, producing a shallow reply in the attack zone.",
        "conditions": "Most effective when the returner stands close to the baseline; less disruptive against returners who chip-and-charge or delay their position; amplified on serve-dominant hard and grass surfaces.",
        "magnitude": "Cramped-return shallow rate of 35-45% produces open-court forehand attack chances 1.5-2.0 times higher than from a full-swing return; subsequent 3-shot sequence ends point at 55-65%.",
        "links": ["first_strike_serve_plus_one_displacement", "serve_wide_court_opening_deuce_ad", "return_position_depth_steal", "open_court_angle_creation", "approach_shot_passing_lane_squeeze"],
    },
    {
        "slug": "moonball_height_recovery_steal",
        "title": "High-Ball Recovery-Time Steal",
        "summary": "A heavy topspin ball with apex above 4 m adds 0.6-1.0 s of flight time, allowing a displaced striker to recover 2.5-4.0 m toward center and neutralize a prior displacement disadvantage in 65-75% of cases.",
        "stat_signature": "Apex >4 m adds 0.6-1.0 s flight time; displaced striker recovers 2.5-4.0 m toward center, neutralizing displacement disadvantage in 65-75% of cases; limits defensive posture from 30-40% to 15-20% of exchanges.",
        "mechanism": "A high arc extends travel time, granting a recovery window unavailable from a flat reply; the high-kick bounce also disrupts the opponent's contact quality, creating a dual benefit of self-recovery and opposing disruption.",
        "conditions": "Most used when stretched wide or pushed deep with no angle available; most effective on clay where heavy topspin is achievable and high bounce compounds opponent recovery cost; less effective on fast surfaces where flat drives are viable.",
        "magnitude": "One high-ball recovery resets the court-position deficit by approximately 60-70% in a single shot; over a 10-shot rally it limits defensive-posture exchanges from 30-40% to 15-20%.",
        "links": ["depth_change_court_position_push", "two_corner_side_to_side_stretch", "counterpunch_redirect_from_defense", "drop_shot_vertical_displacement", "open_stance_recovery_advantage"],
    },
    {
        "slug": "net_rush_time_pressure_compression",
        "title": "Net-Rush Time-Pressure Compression",
        "summary": "Advancing from 4 m to 2 m from the net removes 0.15-0.25 s of opponent reaction time; pass success drops from 42-48% at moderate proximity to 28-36% under full compression with correct bisector positioning.",
        "stat_signature": "Net advance from 4 m to 2 m removes 0.15-0.25 s; pass success drops from 42-48% to 28-36%; lob attempts rise 10-15 percentage points when the passing lane falls below 1.5 m.",
        "mechanism": "Closing the net shortens the ball's travel distance to a winner, removes an angular buffer, and compresses the remaining passing corridor geometrically, demanding higher precision under greater time pressure simultaneously.",
        "conditions": "Most effective after a short or weak reply allowing a controlled advance; the lob counter must be managed via overhead positioning; less effective against opponents who anticipate net rushes and hold the lob in reserve.",
        "magnitude": "Correct bisector compression reduces passing success by 12-18 percentage points and increases forced errors on pass attempts by 15-22 percentage points.",
        "links": ["approach_shot_passing_lane_squeeze", "drop_shot_vertical_displacement", "first_strike_serve_plus_one_displacement", "disguise_delayed_shot_freeze", "open_court_angle_creation"],
    },
    {
        "slug": "return_position_depth_steal",
        "title": "Return-Position Depth Steal",
        "summary": "Taking the return 0.5-1.0 m inside the baseline compresses the server's recovery time by 0.15-0.25 s; when the server has not yet reached recovery position at ball arrival, forced errors and short replies rise 18-28%.",
        "stat_signature": "Return 0.5-1.0 m inside baseline compresses server recovery time by 0.15-0.25 s; W/FE rates on the return rally 18-28% above baseline; returner win rate on second-serve points rises 12-18 percentage points.",
        "mechanism": "The server's post-serve movement is time-constrained; an early return arrives before the server reaches the desired position, forcing a reply from a deficit; this reverses the typical serve-advantage pattern.",
        "conditions": "Requires sufficient skill to take the ball early without sacrificing depth or direction; most effective on second serves; also effective in chip-and-charge patterns on slow surfaces.",
        "magnitude": "Early return position creates a server recovery deficit of 1.5-2.5 m; second-serve-point returner win rate rises 12-18 percentage points relative to standard deep-standing return.",
        "links": ["first_strike_serve_plus_one_displacement", "body_serve_jam_then_open", "serve_wide_court_opening_deuce_ad", "net_rush_time_pressure_compression", "disguise_delayed_shot_freeze"],
    },
    {
        "slug": "rally_pattern_corner_baiting",
        "title": "Rally-Pattern Corner Baiting",
        "summary": "After 3+ consecutive crosscourt exchanges, opponent lateral lean is detectable in 55-70% of cases; a disguised down-the-line into the vacated corner from that setup yields W/FE rates 45-58%, versus 28-35% without prior pattern.",
        "stat_signature": "After 3+ crosscourt balls, opponent lean toward that side detectable in 55-70% of cases; pattern-baited redirect W/FE rates 45-58% versus 28-35% unset; lean adds 0.3-0.5 s direction-reversal lag.",
        "mechanism": "Repeating a directional pattern builds anticipatory lean in the recovery step; a redirect to the other side catches the opponent mid-commitment, creating both a momentum-reversal cost and an open corridor where the lean has vacated court space.",
        "conditions": "Requires patience over 3-5 shots before changing direction; most effective in longer rally formats on slow surfaces; less reliable against opponents who deliberately delay their recovery lean to avoid being baited.",
        "magnitude": "Pattern-baited redirects produce 15-25 percentage points higher W/FE rates than unset directional changes; the lean adds 0.3-0.5 s reversal lag, equivalent to 1.2-2.0 m of additional open court.",
        "links": ["inside_out_forehand_court_opening", "two_corner_side_to_side_stretch", "behind_the_player_redirection", "disguise_delayed_shot_freeze", "wrong_footing_recovery_exploitation"],
    },
    {
        "slug": "open_stance_recovery_advantage",
        "title": "Open-Stance Recovery Advantage",
        "summary": "An open-stance contact on a wide ball allows recovery initiation 0.10-0.18 s earlier than a closed-stance equivalent, translating to 0.7-1.3 m of additional center recovery and 15-22% lower reply-side exposure.",
        "stat_signature": "Open-stance wide contacts initiate recovery 0.10-0.18 s earlier than closed-stance; 0.7-1.3 m additional center recovery before the next ball; 15-22% lower exposure on the reply side.",
        "mechanism": "A closed stance requires a cross-step recovery after contact; open stance allows the pushing leg to initiate return movement before full contact, converting recovery from a two-phase reset into a single continuous motion.",
        "conditions": "Most beneficial on wide forehand balls where closed stance forces full rotation; most applicable on the forehand wing where open stance is biomechanically natural; less applicable on two-handed backhand where stance width limits the chain.",
        "magnitude": "Players using open stance on 70%+ of wide forehand contacts show 15-20% lower exposure rates; the 0.12-0.18 s recovery-time gain covers 1.0-1.5 m more court before the opponent's next ball arrives.",
        "links": ["counterpunch_redirect_from_defense", "wrong_footing_recovery_exploitation", "moonball_height_recovery_steal", "inside_out_forehand_court_opening", "two_corner_side_to_side_stretch"],
    },
]
