"""Person-free NBA SpacingGeometry concept nodes — dense, sport-accurate, no player/team names."""
from __future__ import annotations

SPORT = "NBA"
FAMILY = "SpacingGeometry"

CONCEPTS: list[dict] = [
    {"slug": "floor_balance_spacing_index",
     "title": "Five-Player Floor-Balance Spacing Index",
     "summary": "Quantifies how evenly all five offensive players occupy the half-court via mean inter-player distance, pairwise-distance variance, and convex-hull area relative to a fully balanced reference footprint.",
     "stat_signature": "Mean inter-player distance 13-17 ft in balanced lineups; convex-hull area 350-520 sq ft; hull-area variance above 90 sq ft per possession signals chronic imbalance; balanced lineups (variance below 60) post half-court PPP 0.04-0.08 higher.",
     "mechanism": "Even spacing forces all five defenders to guard their assigned zones simultaneously, preventing any single help assignment from covering two threats; the result is that no rotation is free and every closeout generates an open catch.",
     "conditions": "Effect largest in half-court possessions against man-to-man coverage; zone schemes reduce the benefit by assigning areas rather than individuals, partially surviving clustering.",
     "magnitude": "Top-quintile floor-balance lineups generate open-shot opportunities 6-9 pp more frequently and corner-three rates 3-5 pp higher than bottom-quintile counterparts.",
     "links": ["three_point_gravity_field", "perimeter_arc_spread_radius", "non_shooter_spacing_tax", "driving_lane_width_geometry"]},

    {"slug": "three_point_gravity_field",
     "title": "Three-Point Shooting Gravity Field",
     "summary": "Captures the off-ball pull a perimeter shooter exerts on the nearest defender, measured as average standoff distance (feet) as a function of the shooter's catch-and-shoot make rate and arc location.",
     "stat_signature": "Shooters above 38% C&S draw defenders within 3 ft on 70-80% of off-ball frames; below 33% C&S, defender standoff exceeds 5 ft on 55-65% of frames; each 1 pp increase in C&S% shrinks average standoff by roughly 0.08 ft.",
     "mechanism": "A credible long-range threat removes the defender's option to help; the defender must stay pinned to the shooter's hip, which eliminates their ability to function as a secondary help layer and widens adjacent driving lanes by 4-7 ft.",
     "conditions": "Gravity field is strongest from above-the-break arc positions; corner gravity is directionally different — it removes the low-man tag rather than the help-side wing. Diminishes when the defense accepts surrendering below-break-even threes.",
     "magnitude": "High-gravity off-ball shooters create open driving corridors on 35-50% of their shared possessions; gravity-adjacent drives reach the rim at 8-12 pp higher rates than non-gravity drives.",
     "links": ["floor_balance_spacing_index", "corner_three_spacing_anchor", "driving_lane_width_geometry", "closeout_distance_recovery_geometry"]},

    {"slug": "corner_three_spacing_anchor",
     "title": "Corner-Three Spacing Anchor Geometry",
     "summary": "Stationing a credible corner shooter pins the low-man help defender, widening the strong-side driving lane by removing the baseline tagger.",
     "stat_signature": "Corner-three C&S rate above 40% reduces low-man tag frequency from 72% to 42% of drives; tagged-corner situations produce drive-to-rim rate of 31%, versus 48% when the corner is vacated; corner-three assisted rate 62-70%.",
     "mechanism": "The low-man defender must choose between tagging the corner shooter or stepping to intercept the drive; a shooter above 38% makes conceding the corner cost-prohibitive, so the tag disappears and the rim path opens.",
     "conditions": "Active only when a corner spot is occupied by a credible shooter; doubles its effect when both corners are occupied simultaneously, splitting the low-man's decision across two credible threats.",
     "magnitude": "Occupied credible corners expand the driving corridor by an estimated 3-5 ft at the point of the charge line; strong-side dunks and layups rise 4-7 pp in frequency.",
     "links": ["three_point_gravity_field", "driving_lane_width_geometry", "dunker_spot_short_corner_occupancy", "weak_side_help_depth_geometry"]},

    {"slug": "driving_lane_width_geometry",
     "title": "Driving-Lane Width and Help-Gap Geometry",
     "summary": "Measures the open corridor available to the ball-handler, defined as the perpendicular distance between the nearest help defender and the direct rim path at the moment of the first dribble.",
     "stat_signature": "Lanes wider than 5 ft at drive initiation produce rim-FGA% of 56-62%; lanes narrower than 2 ft produce 38-44%; each additional foot of lane width corresponds to roughly +3 pp rim-FGA and +0.04 FTA per drive.",
     "mechanism": "A wider corridor means the first help defender's intercept angle is beyond the ball-handler's reach, removing the redirect threat and allowing straight-line rim approaches that finish at higher rates and draw contact more reliably.",
     "conditions": "Lane width is spacing-dependent: five-out lineups produce the widest lanes; four-man half-court sets with a post anchor compress the lane by 2-4 ft. Against drop-coverage schemes, the screener's roll further clogs the lane even when wings are spaced.",
     "magnitude": "Top-quartile lane-width possessions convert to rim attempts at 48-55% versus 28-35% for bottom-quartile; the FTA differential is 0.12-0.20 per drive across the quartile gap.",
     "links": ["floor_balance_spacing_index", "corner_three_spacing_anchor", "ball_screen_spacing_geometry", "paint_touch_congestion_density"]},

    {"slug": "dunker_spot_short_corner_occupancy",
     "title": "Dunker-Spot and Short-Corner Occupancy",
     "summary": "Tracks a finisher's positioning in the low strong-side baseline zone, measuring occupancy rate and the low-man defender's resulting split-distance between tagging and protecting the rim.",
     "stat_signature": "Dunker-spot occupancy above 30% of half-court possessions creates low-man split-distance of 8-12 ft; uncontested catch-and-dunk rate 65-74% when the tagger commits to the rim; short-corner catch FG% 52-58% when the tag is resolved away.",
     "mechanism": "A finisher at the dunker spot creates a two-point dilemma for the low-man: commit to tagging the dunker and surrender the roll or drive; ignore the dunker and concede an uncontested put-back. Neither resolution is cost-free.",
     "conditions": "Strongest when paired with a live-dribble drive; diminishes in catch-and-shoot-only offenses where the finisher lacks roll threat. Effect amplifies when the finisher posts above 65% uncontested conversion rate, making the tag non-negotiable.",
     "magnitude": "High-occupancy dunker lineups convert strong-side rolls and dumps at 4-8 pp higher rates; they also increase free-throw generation via forced fouls from the two-way tag attempts.",
     "links": ["corner_three_spacing_anchor", "driving_lane_width_geometry", "weak_side_help_depth_geometry", "paint_touch_congestion_density"]},

    {"slug": "weak_side_help_depth_geometry",
     "title": "Weak-Side Help-Defender Depth Geometry",
     "summary": "Quantifies how far off-ball defenders sink into the lane at the moment of a strong-side drive, measured as average distance from their assignment and depth inside the paint.",
     "stat_signature": "Weak-side defenders sinking more than 4 ft into the paint concede open weak-side threes on 55-68% of kick-out possessions; sinking less than 2 ft suppresses the drive-to-rim rate by 12-18 pp but surrenders 42-48% open-three opportunities.",
     "mechanism": "A defender choosing to help on the drive must physically abandon their assignment; the depth of the sink determines both how effectively they interrupt the drive and how open the kick-out receiver becomes — creating an unavoidable efficiency trade-off.",
     "conditions": "Depth of sink is controlled by defensive scheme: help-and-recover schemes commit to sinking and depend on closeout athleticism; stay-at-home schemes accept drive completions to prevent three-point concessions.",
     "magnitude": "Each additional foot of weak-side sink depth adds 3-5 pp to open kick-out three rate; full sink-and-recover lineups give up 1.2-1.4 pts/possession on kick-out sequences versus 0.88-1.05 on successfully deterred drives.",
     "links": ["driving_lane_width_geometry", "corner_three_spacing_anchor", "closeout_distance_recovery_geometry", "spacing_gravity_overload_strong_side"]},

    {"slug": "ball_screen_spacing_geometry",
     "title": "Ball-Screen Spacing and Screen-Angle Geometry",
     "summary": "Describes the spatial setup of a ball screen — screen angle, pocket-pass window behind the screen, and the roller's vertical separation from the tagging defender.",
     "stat_signature": "Screens angled 45-70 degrees from the sideline yield the widest pocket-pass window (3-5 ft); flat sideline screens shrink the window to 1-2 ft; roller vertical separation above 4 ft from the tagger correlates with lob-catch rate 52-60%.",
     "mechanism": "The screen angle determines which side the ball-handler can attack; the resulting pocket is the gap between the hedging defender and the screener's body; a large pocket and a separated roller simultaneously force the tagging help-defender into an uncoverable two-man zone.",
     "conditions": "Angle and pocket geometry matter most in pick-and-roll-heavy offenses; against ice/blue schemes that force baseline the angle benefit is partially neutralised. Spacing of the three weak-side players amplifies the pocket's value by removing secondary help.",
     "magnitude": "Optimal-angle screens produce open roll-man catches at 40-55% of pick-and-roll possessions; well-spaced pick-and-roll lineups generate lob or short-roll scoring at 1.10-1.20 PPP versus 0.88-0.95 for cramped sets.",
     "links": ["driving_lane_width_geometry", "floor_balance_spacing_index", "elbow_nail_high_post_spacing", "paint_touch_congestion_density"]},

    {"slug": "paint_touch_congestion_density",
     "title": "Paint Congestion and Defender Density",
     "summary": "Measures how crowded the restricted area and paint are at the point of a shot attempt, defined as the number of defenders within a fixed radius of the rim and the resulting contest-density score.",
     "stat_signature": "Two or more defenders within 5 ft of the rim at shot moment drops paint FG% by 12-18 pp relative to uncontested; restricted-area make rate 62-70% with zero close defenders, 44-52% with two or more; shot-alteration rate above 15% when two defenders are present.",
     "mechanism": "Each additional body near the rim narrows the shot window and raises the probability of a contest or block; crowding also increases the trajectory compression required to clear outstretched hands, reducing high-percentage angles.",
     "conditions": "Congestion peaks in possessions involving post entries, offensive rebounding tip-ins, and roll-man catches in traffic; it is lowest in transition and early-clock possessions before the paint fills.",
     "magnitude": "The rim-contest penalty (two-plus defenders) reduces expected points on paint attempts by 0.20-0.35 per shot; top paint-protection defenses reduce opponent restricted-area PPP by 0.08-0.14 across a season.",
     "links": ["dunker_spot_short_corner_occupancy", "driving_lane_width_geometry", "rim_protector_vertical_zone", "ball_screen_spacing_geometry"]},

    {"slug": "spacing_compression_short_clock",
     "title": "Spacing Compression Under Short Clock",
     "summary": "Captures how floor spacing contracts as the shot clock expires, measured by convex-hull shrinkage and the rise in nearest-defender proximity in the final eight seconds of a possession.",
     "stat_signature": "Convex hull contracts by 20-35% from possession start to final 8 seconds; nearest-defender distance falls from 4.2 ft average to 2.8 ft; PPP in possessions ending with 0-5 seconds remaining is 0.72-0.84 versus 1.02-1.10 in 15-24 seconds.",
     "mechanism": "Defenders collapse toward the ball as the clock expires because the threat of perimeter creation disappears; the shrink removes spacing benefits and forces contested, off-balance attempts with compressed shooting windows.",
     "conditions": "Compression is most severe for offenses that rely on motion and secondary action to generate spacing; plays that create quick catches before the 8-second mark preserve spacing; teams with strong isolation creators are less affected.",
     "magnitude": "Late-clock possessions (0-5 seconds) convert at 18-26 pp below full-clock efficiency; hull-area shrinkage above 30% in the final 8 seconds correlates with PPP below 0.80 across possession types.",
     "links": ["floor_balance_spacing_index", "lift_relocation_drift_geometry", "non_shooter_spacing_tax", "driving_lane_width_geometry"]},

    {"slug": "lift_relocation_drift_geometry",
     "title": "Lift, Drift, and Relocation Geometry",
     "summary": "Describes a spaced shooter's repositioning along the arc as a drive develops — lateral relocation distance and the change in closeout angle and standoff distance before the catch.",
     "stat_signature": "Relocation moves of 4-8 ft along the arc prior to catch shift the closeout angle by 20-35 degrees; relocated shooters face straight-line closeouts on 38% of attempts versus 61% for stationary shooters; open-catch rate rises 10-16 pp after relocation.",
     "mechanism": "Moving off the catch repositions the closeout defender from a pre-set rotation angle to a recovery angle, elongating their path to the shooter; a longer closeout requires more airtime, generating a larger catch-to-contest window.",
     "conditions": "Lift and drift are most effective when paired with a live-dribble drive that commits two defenders; against switching defenses, relocation changes the matchup rather than creating an opening distance advantage.",
     "magnitude": "Shooters who average above 5 ft of pre-catch relocation convert open catch-and-shoot threes at 39-44% versus 35-38% for stationary shooters; they receive 12-18% more open catches per 100 possessions.",
     "links": ["three_point_gravity_field", "closeout_distance_recovery_geometry", "spacing_compression_short_clock", "floor_balance_spacing_index"]},

    {"slug": "rim_protector_vertical_zone",
     "title": "Rim-Protector Vertical Coverage Zone",
     "summary": "Quantifies the spatial deterrence radius of an interior defender, measured as the rim distance at which drivers alter or abort shots and the area of floor where attempts are visibly suppressed.",
     "stat_signature": "Elite interior defenders suppress rim-FGA rate within 5 ft by 15-22 pp; driver-abort rate (pull-back, kick-out instead of finishing) is 18-28% when a quality rim protector is present versus 7-12% without; FG% at rim drops 8-14 pp inside the deterrence zone.",
     "mechanism": "A high-vertical rim defender forces attackers to modify trajectory or abort the attempt at the moment of commitment; even when the block does not occur, the threat alters shooting angles and reduces the percentage of clean lay-up attempts.",
     "conditions": "Deterrence zone is largest against off-the-dribble drivers who need time to elevate; catch-and-dunk finishers are less deterred because the short decision window bypasses the trajectory-modification response.",
     "magnitude": "Top-10 rim protection units reduce opponent paint PPP by 0.07-0.12 across a season; the deterrence effect extends 4-8 ft from the rim and accounts for 25-35% of the total paint-efficiency gap between elite and average defenses.",
     "links": ["paint_touch_congestion_density", "dunker_spot_short_corner_occupancy", "weak_side_help_depth_geometry", "driving_lane_width_geometry"]},

    {"slug": "transition_floor_geometry_lane_fill",
     "title": "Transition Floor Geometry and Lane Fill",
     "summary": "Describes the spatial spread of attackers in early offense — lane-fill width across the court and the numerical-advantage geometry in the frontcourt within the first five seconds.",
     "stat_signature": "Three-lane fill (ball-lane plus two wide lanes) within 4 seconds generates open-transition three or lay-up on 48-58% of possessions; two-lane fill drops to 28-36%; transition PPP 1.10-1.25 versus 0.95-1.05 half-court; numerical edge (3-on-2 or better) present on 22-30% of runs.",
     "mechanism": "Wide lane fill forces defenders to choose between protecting the rim and contesting the wings; a spread three-lane attack provides a scoring outlet at every defensive collapse, making individual rotations insufficient to cancel the numerical or positional advantage.",
     "conditions": "Most productive off live-ball turnovers and defensive rebounds with quick outlet passes; requires at least two players with above-35% three-point shooting to keep the wings credible and prevent defenders from loading toward the lane.",
     "magnitude": "Full-width three-lane transition possessions produce lay-ups or open threes on 55-65% of runs; teams in the top quartile of transition frequency generate 8-14 additional high-value possessions per 48 minutes.",
     "links": ["floor_balance_spacing_index", "offensive_rebound_crash_geometry", "corner_three_spacing_anchor", "driving_lane_width_geometry"]},

    {"slug": "offensive_rebound_crash_geometry",
     "title": "Offensive-Rebound Crash and Floor-Balance Geometry",
     "summary": "Captures the spatial trade-off between sending bodies to the glass and retreating for transition defense, measured by crasher distance from the rim on shot and the resulting back-court spacing gap.",
     "stat_signature": "Two or more crashers within 12 ft at shot-release boosts OREB% by 8-14 pp; each additional crasher increases transition-opponent PPP by 0.06-0.10 on the defensive end; optimal single-crasher strategies maintain OREB% 24-28% while limiting transition concessions.",
     "mechanism": "Crashing bodies near the rim generate second-chance attempts but leave fewer players to prevent fast-break opportunities; the floor-balance gap is the spatial cost — each committed crasher removes one retreater, widening the open corridor for the opponent's outlet.",
     "conditions": "Trade-off is most acute against fast-transition opponents; teams with elite shot-blockers can afford to crash more because defensive rebounds are cleaner. The cost shifts when the opponent is a poor transition team.",
     "magnitude": "Full-crash lineups (three-plus crashers) gain 1.5-2.5 second-chance points per game but concede 1.0-2.0 additional transition points; the net is near-zero on average, making personnel and opponent context the differentiating factor.",
     "links": ["transition_floor_geometry_lane_fill", "floor_balance_spacing_index", "dunker_spot_short_corner_occupancy", "rim_protector_vertical_zone"]},

    {"slug": "closeout_distance_recovery_geometry",
     "title": "Closeout Distance and Recovery Geometry",
     "summary": "Measures the spatial cost of help-and-recover rotations, defined as the ground a rotating defender must cover to contest a kick-out and the residual standoff distance achieved at the catch.",
     "stat_signature": "Closeout distances above 12 ft yield an open-shot rate of 72-80% and contest-at-catch rate below 25%; distances 6-10 ft yield 38-48% open rate; every 2 ft of additional closeout distance corresponds to roughly +4 pp open-shot rate and +6 pp catch-and-shoot make rate.",
     "mechanism": "A help-and-recover defender abandons the shooter to aid on the drive; the kick-out receiver's shooting clock is shorter than the closeout window when the help distance exceeds the recovery distance, creating a systematic open-catch window.",
     "conditions": "Largest when the kick-out receiver is spaced beyond 25 ft; corner kick-outs from help-side are most extreme because recovery requires crossing the full lane width. Switching defenses avoid this by not committing the help in the first place.",
     "magnitude": "Closeout distances above 14 ft result in open-catch threes converting at 40-46% — near the top of catch-and-shoot range — while generating 1.25-1.40 PPP on those possessions.",
     "links": ["weak_side_help_depth_geometry", "lift_relocation_drift_geometry", "three_point_gravity_field", "spacing_gravity_overload_strong_side"]},

    {"slug": "spacing_gravity_overload_strong_side",
     "title": "Strong-Side Overload Spacing Geometry",
     "summary": "Describes deliberate clustering of offensive players to one side, measured by strong-to-weak-side player split and the lateral distance help defenders must travel to rotate across the floor.",
     "stat_signature": "Three-plus offensive players on the strong side create a lateral rotation distance of 18-26 ft for the weak-side help defender; skip-pass open-three rate 55-68% in overload sets; overload-to-weak-side reversal PPP 1.15-1.30 when the defense over-rotates.",
     "mechanism": "Loading one side draws defensive attention and rotations to that side; a ball reversal then exploits the slow recovery distance, converting the over-rotation into a predictable open catch on the weak side before help arrives.",
     "conditions": "Most effective against help-heavy defenses that commit multiple defenders to the strong side; against conservative stay-at-home schemes the overload simply reduces spacing on that side without creating a corresponding opening.",
     "magnitude": "Strong-side overload sets followed by reversal produce open weak-side catches on 50-65% of possessions; the skip-pass open-three is the primary scoring mechanism, converting at 38-43% from above-the-break.",
     "links": ["floor_balance_spacing_index", "closeout_distance_recovery_geometry", "weak_side_help_depth_geometry", "elbow_nail_high_post_spacing"]},

    {"slug": "elbow_nail_high_post_spacing",
     "title": "Elbow, Nail, and High-Post Spacing Geometry",
     "summary": "Quantifies the central spatial hub at the free-throw-line area, measured by occupancy of the nail and elbows and the defensive sag-distance that simultaneously compresses both wings.",
     "stat_signature": "High-post occupancy reduces defender sag-depth on both wings by 3-5 ft; elbow-to-wing drive frequency 18-26 per 100 possessions; high-post mid-range FG% 44-50%; elbow passes generate open-wing catches on 38-45% of possessions when the post occupant passes.",
     "mechanism": "An occupant at the nail or elbow forces the help defender to honor a mid-post scoring threat; that commitment lifts the defensive floor, reducing help depth on both sides simultaneously and extending wing driving lanes.",
     "conditions": "Most impactful for shooters or passers at the elbow who can score from the mid-post; a non-scoring occupant allows sag to deepen to its prior value. Against aggressive denial, the occupant vacates to the three-point line and the effect disappears.",
     "magnitude": "Elite elbow passers generate 0.06-0.10 PPP lift for wing actions versus possessions without a high-post hub; teams with consistent elbow occupancy post wing open-catch rates 8-12 pp above average.",
     "links": ["ball_screen_spacing_geometry", "spacing_gravity_overload_strong_side", "cutting_lane_vertical_spacing", "non_shooter_spacing_tax"]},

    {"slug": "non_shooter_spacing_tax",
     "title": "Non-Shooter Spacing Tax Geometry",
     "summary": "Measures the spatial cost of a non-shooting offensive player, defined as the help-distance their defender can sag toward the paint and the corresponding reduction in usable floor area for teammates.",
     "stat_signature": "Non-shooter defender sag-depth averages 6-10 ft off the assignment, adding a second body to the help layer; lineups with two non-shooters show driving-lane widths 3-5 ft narrower than five-shooter lineups; PPP penalty 0.06-0.10 per additional non-shooter in half-court.",
     "mechanism": "A credible shooting threat commands defensive attention; a non-shooter allows their defender to serve as a free helper. Two free helpers reconstruct a zone-like defensive density even within man-to-man coverages, collapsing the driving lanes and kick-out windows that spacing is designed to create.",
     "conditions": "Tax is largest in half-court possessions against competent defensive coaches who correctly identify non-shooters; transition and early-clock possessions are less affected because help rotations have not set. Functional non-shooters who roll, seal, or crash can offset the tax via secondary threat.",
     "magnitude": "Each non-shooter added reduces half-court open-three rate by 4-7 pp; two-non-shooter lineups produce half-court PPP 0.08-0.14 below single-non-shooter lineups against competent help defenses.",
     "links": ["floor_balance_spacing_index", "three_point_gravity_field", "elbow_nail_high_post_spacing", "spacing_compression_short_clock"]},

    {"slug": "perimeter_arc_spread_radius",
     "title": "Perimeter Arc Spread and Spacing Radius",
     "summary": "Captures how far offensive players station beyond the three-point line, measured by the mean radial distance of perimeter players from the rim and the depth of the resulting interior void.",
     "stat_signature": "Mean perimeter distance above 24 ft creates interior void area of 280-360 sq ft; below 22 ft, void area compresses to 140-200 sq ft; each additional foot of average perimeter radius corresponds to 1.8-2.5 additional open-interior sq ft; rim-touch frequency rises 4-6 pp per 2-ft spread increase.",
     "mechanism": "Stationing players farther from the rim physically distances defenders, enlarging the unguarded interior space the ball-handler can attack; the deeper the arc, the greater the defender's recovery distance if they choose to help, and the lower the probability of a timely contest at the rim.",
     "conditions": "Arc spread requires shooters willing and able to function 25-27 ft from the rim; five-out sets with three-plus shooters at this depth provide the maximum void; post-anchored lineups counteract this by voluntarily occupying the interior, collapsing the void from the offensive side.",
     "magnitude": "Five-out lineups with perimeter players averaging 24-plus ft from the rim generate 20-28% higher rim-touch rates than lineups averaging 22 ft; open-rim attempt rate rises 6-10 pp in the highest-spread quintile.",
     "links": ["floor_balance_spacing_index", "non_shooter_spacing_tax", "driving_lane_width_geometry", "three_point_gravity_field"]},

    {"slug": "cutting_lane_vertical_spacing",
     "title": "Cutting-Lane and Backdoor Vertical Spacing",
     "summary": "Describes the open vertical channels available for cuts to the rim, measured by the unoccupied baseline-to-elbow corridor width and the help-defender's coverage distance from the cut path.",
     "stat_signature": "Corridor widths above 6 ft on the strong side produce catch-at-rim rate on cuts of 58-68%; below 4 ft drops to 32-42%; backdoor cuts in denial situations succeed at 45-55% when the help-side defender is more than 8 ft from the cut path; assisted cut lay-up FG% 68-76%.",
     "mechanism": "A cutter exploits a gap between the ball-side defender's positioning and the help defender's orbit; if the vertical corridor is unoccupied by either a stationary teammate or a rotating defender, the cutter can reach the rim before coverage arrives.",
     "conditions": "Cutting lanes are widest in spaced-floor sets where no teammate is stationary in the lane; they collapse in four-out-one-in sets where the post occupies the low block; back-cuts are most effective when the on-ball defender is in aggressive denial position.",
     "magnitude": "High-frequency cut offenses (above 12 cuts per 100 possessions) generate lay-up attempts at 1.25-1.40 PPP; the vertically open lane accounts for 60-70% of the conversion rate advantage over set-play cuts into congested lanes.",
     "links": ["elbow_nail_high_post_spacing", "dunker_spot_short_corner_occupancy", "paint_touch_congestion_density", "floor_balance_spacing_index"]},

    {"slug": "double_team_trap_spacing_geometry",
     "title": "Double-Team Trap and Open-Player Geometry",
     "summary": "Quantifies the spatial exposure created when two defenders converge on the ball, measured by the open-man distance from the nearest recovering defender and the skip-pass corridor the trap concedes.",
     "stat_signature": "Traps committing two defenders leave an average of 1.3-1.8 open offensive players beyond 22 ft; open-man distance from nearest help 14-20 ft; skip-pass lane width 8-14 ft; trap-escape possessions produce PPP 1.18-1.35 when the offensive team completes 2-plus passes before shot.",
     "mechanism": "A two-defender convergence leaves at least one offensive player completely unguarded; if the trapped ball-handler can escape before the trap closes, the defense is forced into a help rotation that simultaneously opens a skip-pass lane and creates a secondary mismatch.",
     "conditions": "Trap geometry is most exploitable by patient, high-IQ offenses that can recognize and exploit the open space before the defense recovers; against ball-handlers who pick up their dribble or force the escape pass, the trap succeeds in forcing turnovers at rates 12-18 pp above average half-court possession turnover rates.",
     "magnitude": "Successful trap escapes produce open looks at 62-72% of possessions; when the offensive team averages 2.5-plus passes in trap-escape sequences, they achieve PPP above 1.20, one of the highest half-court efficiency profiles available.",
     "links": ["spacing_gravity_overload_strong_side", "closeout_distance_recovery_geometry", "floor_balance_spacing_index", "elbow_nail_high_post_spacing"]},
]
