"""Special-situations intelligence concept nodes for Soccer — person-free spec."""
from __future__ import annotations

SPORT: str = "Soccer"
FAMILY: str = "SpecialSituations"

CONCEPTS: list[dict] = [
    {
        "slug": "inswinging_corner_delivery",
        "title": "Inswinging Corner Delivery",
        "summary": "Corner curling toward goal raises near-post congestion and suppresses keeper-claim rate versus outswing, lifting expected goals per delivery.",
        "stat_signature": "xG per inswing delivery: ~0.035–0.055 versus ~0.020–0.030 outswing; near-post flick-on rate: ~18–24%; keeper-claim rate: ~28–35%.",
        "mechanism": "Ball moving into the six-yard box forces the keeper to commit late; a near-post runner can redirect before defenders intercept, compressing defensive reaction time to under 0.4 s.",
        "conditions": "Advantage largest against zonal defenses slow to cover the near-post channel; diminishes when keeper dominates the six-yard box; assisting wind amplifies curve.",
        "magnitude": "Moderate: ~0.015–0.025 xG above outswing baseline per delivery; near-post conversion when contact is clean: ~12–18%.",
        "links": ["outswinging_corner_delivery", "near_post_far_post_runs", "defensive_set_piece_marking", "second_ball_set_piece_recovery"],
    },
    {
        "slug": "outswinging_corner_delivery",
        "title": "Outswinging Corner Delivery",
        "summary": "Corner bending away from goal draws attacking runners to the penalty-spot arc, favouring tall far-post headers over near-post flick-ons.",
        "stat_signature": "xG per delivery: ~0.020–0.030; penalty-spot first-contact win rate: ~34–42%; headed-shot rate from the 8–12 m zone: ~22–30%; keeper-claim rate: ~42–50%.",
        "mechanism": "Outward curve gives far-post runners time to build into a moving-run header; defenders choosing between tracking the run and watching the ball create space in the central zone.",
        "conditions": "Most effective when the attacking side has height advantage at the penalty spot; heavy wind opposing the curve can flatten delivery and reduce separation.",
        "magnitude": "Moderate but lower than inswing for near-post danger; quality headed attempts from the penalty area are the primary value driver.",
        "links": ["inswinging_corner_delivery", "near_post_far_post_runs", "set_piece_blocking_screens", "second_ball_set_piece_recovery"],
    },
    {
        "slug": "short_corner_routine",
        "title": "Short-Corner Combination Routine",
        "summary": "A two-player exchange at the corner arc reangles the subsequent delivery, draws a defender out, and improves resulting cross quality and cut-back creation rate.",
        "stat_signature": "Resulting delivery xG lift: ~0.010–0.018 above direct; cut-back creation rate: ~14–20%; shot frequency per routine: ~0.38 versus ~0.28 for direct corners.",
        "mechanism": "The initial short pass forces at least one defensive marker to close, removing a body from the box; the reangle arrives from a fresh horizontal channel, reducing defensive alignment advantage.",
        "conditions": "Effective with a skilled wide dribbler who can beat a closing defender; sacrifices one-touch delivery speed; less useful against defenses that commit two players to the short zone.",
        "magnitude": "Small to moderate: the reangle gain is partially offset by extra seconds for defensive recovery; cut-back opportunities carry xG of ~0.08–0.14.",
        "links": ["inswinging_corner_delivery", "quick_free_kick_restart", "rebound_set_piece_second_phase", "penalty_box_overload_corner"],
    },
    {
        "slug": "direct_free_kick_shot_zone",
        "title": "Direct Free-Kick Shooting Zone",
        "summary": "The central arc at 18–25 m from goal is the highest-xG dead-ball zone, where curl or driven shots must clear the wall and reach a goalkeeper-exposed corner.",
        "stat_signature": "xG from 18–22 m central: ~0.08–0.13; from 22–27 m: ~0.04–0.08; on-target rate from prime arc: ~38–48%; wall-clearance rate: ~60–72%; conversion: ~8–12%.",
        "mechanism": "Keeper positioning to cover the near post is constrained by the wall's blocking angle, leaving a far- or top-corner gap; distance limits keeper reaction time to ~0.45–0.55 s after contact.",
        "conditions": "xG peaks in the central corridor within 22 m; wide angles collapse the gap behind the wall; a short or disorganised wall of four rather than five raises on-target probability.",
        "magnitude": "Moderate: xG of 0.08–0.13 is roughly 3× the corner baseline; executed conversion near 10% makes it one of the most efficient dead-ball zones.",
        "links": ["free_kick_wall_management", "free_kick_decoy_runner_routine", "indirect_free_kick_routine", "quick_free_kick_restart"],
    },
    {
        "slug": "indirect_free_kick_routine",
        "title": "Indirect and Wide Free-Kick Delivery",
        "summary": "Free kicks from wide channels or non-shooting zones convert to shots via a crossed delivery or worked combination; delivery-to-shot rate and the short-play proportion determine outcome quality.",
        "stat_signature": "Delivery-to-shot conversion: ~28–38%; xG per delivery: ~0.025–0.045; short-play proportion: ~30–40%; short routines produce ~15–22% more shots than floated deliveries.",
        "mechanism": "Wide kicks lack a direct angle but allow a well-struck cross into a stationary attacking unit; the far-post area is less populated; short-play creates cut-back channels unavailable from a direct delivery.",
        "conditions": "Benefit concentrates in the attacking third between penalty area and byline; deeper kicks degrade xG toward corner baseline; strong crossing ability widens the gap over short-play alternatives.",
        "magnitude": "Small per delivery; cumulatively a team with elite delivery quality can generate an extra 0.08–0.15 xG per game from wide free kicks alone.",
        "links": ["direct_free_kick_shot_zone", "inswinging_corner_delivery", "defensive_set_piece_marking", "second_ball_set_piece_recovery"],
    },
    {
        "slug": "penalty_kick_placement_state",
        "title": "Penalty-Kick Placement and Direction",
        "summary": "Spot-kick conversion rate varies sharply by placement zone; the goalkeeper's dive-or-stay decision and the taker's side-height combination determine the dominant outcome split.",
        "stat_signature": "Top-corner conversion: ~96–98%; mid-height corner: ~86–92%; mid-goal: ~65–75%; overall keeper save rate: ~20–24%; dive-direction match rate: ~68–74%.",
        "mechanism": "Reaction time from ball contact to required keeper position is ~0.25–0.35 s; an early-committing keeper is beaten to the opposite corner even at moderate pace; top-corner shots require exceptional athleticism to save.",
        "conditions": "Shootout pressure reduces conversion ~4–6 pp versus in-game; wet pitches impair footing precision; experienced takers show lower placement variance under pressure.",
        "magnitude": "Large per event: top-corner placement achieves near-perfect conversion; the keeper dive-direction split creates a game-theory equilibrium where both sides converge toward mixed strategies.",
        "links": ["penalty_shootout_sequence", "direct_free_kick_shot_zone", "defensive_set_piece_marking"],
    },
    {
        "slug": "penalty_shootout_sequence",
        "title": "Penalty-Shootout Sequence Dynamics",
        "summary": "The tie-breaking shootout exhibits order-position and pressure-state effects that cumulate across rounds, with leading teams converting at a measurably higher rate than trailing teams facing elimination.",
        "stat_signature": "Kick-one conversion: ~78–84%; leading-team conversion after opponent miss: ~86–92%; trailing-elimination-kick conversion drops ~5–8 pp versus baseline; overall shootout conversion: ~74–80%.",
        "mechanism": "Psychological pressure accumulates non-linearly; trailing after an opponent conversion narrows the acceptable outcome window and compresses the effective motion program for the kick; early misses cascade within the sequence.",
        "conditions": "Order effects are most measurable in elimination rounds; regular-season shootouts show attenuated effects; a goalkeeper save early amplifies the leading team's subsequent conversion rate.",
        "magnitude": "Moderate across rounds: first-kicker teams win ~60% of shootouts when both sides convert at baseline in round one.",
        "links": ["penalty_kick_placement_state"],
    },
    {
        "slug": "attacking_throw_in_long",
        "title": "Long Attacking Throw-In Delivery",
        "summary": "A specialist launched throw from the final third delivers the ball into the box as a set-piece cross, generating headed flick-on and box-entry rates comparable to corner delivery.",
        "stat_signature": "Box-entry rate: ~62–72%; aerial flick-on duel win rate: ~44–54%; xG per long throw: ~0.025–0.040; second-ball recovery at the six-yard zone: ~38–48% for the attacking team.",
        "mechanism": "Long throws are not subject to offside from the point of delivery, allowing runners to start behind the last defender and arrive at the near post unmarked; trajectory approximates inswing without reaching keeper interception height.",
        "conditions": "Requires a specialist reaching the six-yard box from the touchline; most effective against zonal defenses that do not account for throw-in offside exemption; ineffective outside the attacking third.",
        "magnitude": "Moderate: xG comparable to a corner when executed cleanly; the no-offside advantage for initial runners is a structural positional benefit absent in most set-piece scenarios.",
        "links": ["inswinging_corner_delivery", "near_post_far_post_runs", "second_ball_set_piece_recovery", "throw_in_retention_buildup"],
    },
    {
        "slug": "throw_in_retention_buildup",
        "title": "Throw-In Retention and Build-Up",
        "summary": "Short defensive- and middle-third throw routines prioritise retention and structured build-up over territory gained, with immediate-pressure turnover rate as the primary quality signal.",
        "stat_signature": "Short throw retention rate (3+ seconds held): ~72–82%; high-press turnover within 5 m: ~12–18%; progression distance after retained throw: ~8–15 m; short-throw proportion in defensive third: ~68–78%.",
        "mechanism": "Throw-in situations represent a two-second defensive reorganisation window; a short receiver controlling immediately prevents pre-organised press traps from triggering and resets build-up posture.",
        "conditions": "High-press opponents flooding the throw-in zone elevate turnover risk; teams with strong retention skills under pressure mitigate this; wide areas below own half carry the highest immediate-press turnover risk.",
        "magnitude": "Small in xG terms but structurally significant: a turnover from a defensive-third throw creates high-danger transition against an unset defence.",
        "links": ["attacking_throw_in_long", "goal_kick_buildup_versus_long", "quick_free_kick_restart"],
    },
    {
        "slug": "defensive_set_piece_marking",
        "title": "Set-Piece Defensive Marking Scheme",
        "summary": "Zonal, man-to-man, or hybrid box organisation against deliveries determines first-contact clearance rate and xG conceded per set piece, with marking scheme interacting with delivery type.",
        "stat_signature": "Zonal first-contact clearance rate: ~58–68%; man-marking: ~52–62%; hybrid: ~60–66%; xG conceded per defended corner: ~0.022–0.038; second-ball recovery share: ~54–64%.",
        "mechanism": "Zonal marking ensures every body is oriented toward the delivery point; man-marking tracks attackers but is disrupted by blocking screens; hybrid schemes combine first-contact zone responsibility with runner-tracking for late arrivals.",
        "conditions": "Man-marking is most vulnerable to rehearsed blocking routines; zonal marking concedes to near-post runs splitting zones; keeper dominance range is the main modifier across all schemes.",
        "magnitude": "Moderate: scheme selection explains ~4–8 pp of first-contact rate variance; delivery-type interaction can create exploitable mismatches.",
        "links": ["inswinging_corner_delivery", "near_post_far_post_runs", "set_piece_blocking_screens", "second_ball_set_piece_recovery"],
    },
    {
        "slug": "near_post_far_post_runs",
        "title": "Near-Post and Far-Post Run Timing",
        "summary": "Coordinated runs timing a set-piece delivery generate blind-side separation; first-contact win rate by zone quantifies the positional advantage created at the moment of contact.",
        "stat_signature": "Near-post attacking first-contact win rate: ~38–48%; far-post: ~42–52%; average marker-separation at contact: ~0.6–1.0 m for well-timed versus ~0.2–0.4 m poorly timed.",
        "mechanism": "A runner arriving at contact speed the instant the ball does forces the marker into a reactive body position; the blind side of a ball-watching defender creates a 0.3–0.6 m shoulder gap exploited before the defender can pivot.",
        "conditions": "Timing quality is highest with consistent delivery; front-foot man markers moving early with the runner collapse the blind-side angle; far-post runs are more effective against zonal defences.",
        "magnitude": "Moderate: an ~8–12 pp aerial duel win-rate lift from optimal timing translates to a material increase in first-contact attempts per delivery.",
        "links": ["inswinging_corner_delivery", "outswinging_corner_delivery", "defensive_set_piece_marking", "set_piece_blocking_screens"],
    },
    {
        "slug": "second_ball_set_piece_recovery",
        "title": "Set-Piece Second-Ball Recovery",
        "summary": "The loose-ball phase after a cleared delivery is contested at the penalty-area edge; the recovery rate determines whether the set piece continues or triggers a counter against a committed attacking shape.",
        "stat_signature": "Attacking second-ball recovery rate at 18 m: ~38–48%; re-shot rate after recovery: ~34–44%; transition-concession rate after defensive second-ball win: ~18–26%.",
        "mechanism": "A cleared delivery reaches the penalty-area edge in ~0.8–1.2 s; teams positioning a runner outside the box before delivery can contest the clearance with forward momentum; long clearances relieve pressure more reliably than short clears.",
        "conditions": "Short clearances favour attacking recovery; teams committing all bodies into the box for headers sacrifice second-ball positioning; a disciplined edge-of-box presence is required to contest.",
        "magnitude": "Moderate: winning 50% of second balls generates an additional ~0.015–0.025 xG per set-piece sequence beyond the initial delivery value.",
        "links": ["inswinging_corner_delivery", "defensive_set_piece_marking", "rebound_set_piece_second_phase", "corner_short_clearance_transition"],
    },
    {
        "slug": "set_piece_blocking_screens",
        "title": "Set-Piece Blocking and Screen Actions",
        "summary": "Legal-edge picks and obstruction actions disrupt marker tracking on deliveries, elevating the rate of unmarked first-contact attempts and reducing defensive clearance rates.",
        "stat_signature": "Marker-disruption rate from coordinated screens: ~22–32% of corner routines; unmarked first-contact rate lift: ~8–14 pp; foul-for-obstruction call rate: ~3–6% of screened corners.",
        "mechanism": "A screen body in a defender's path costs ~0.4–0.8 s of path-clearance time; against man-markers a successful screen creates a clean separation window for the primary run; passive positional blocking is legal where active running contact is not.",
        "conditions": "Most effective against strict man-marking; zonal systems are partially immune because defenders do not follow runners through screens; referee interpretation of obstruction varies materially by competition.",
        "magnitude": "Small to moderate: unmarked first-contact attempts convert at ~2–3× the rate of contested attempts, making a 10 pp increase in unmarked rate materially valuable over a full season.",
        "links": ["near_post_far_post_runs", "defensive_set_piece_marking", "penalty_box_overload_corner"],
    },
    {
        "slug": "rebound_set_piece_second_phase",
        "title": "Set-Piece Second-Phase Continuation",
        "summary": "An initial set-piece shot or half-clearance keeping the ball in the box triggers a second-phase sequence; cumulative xG across both phases typically exceeds the standalone first-delivery value.",
        "stat_signature": "Second-phase shot rate after first set-piece contact: ~28–36%; cumulative xG across two phases: ~0.060–0.090 (roughly 1.5–2.2× single phase); second-phase shots originate inside 8 m at ~56–64% frequency.",
        "mechanism": "A rebounded ball inside the box finds a keeper already off the line and committed to the first trajectory; defenders in clearing mode are poorly positioned for a second attacking contact, typically producing a closer, less-contested attempt.",
        "conditions": "Arises most from low-trajectory first contacts that rebound rather than clear; a penalty-spot stationed body is required to capitalise; a clean defensive claim or punch eliminates the phase.",
        "magnitude": "Moderate to large: close-range second-phase shots convert at materially higher rates than first-phase headers, compounding the xG value of the full set-piece sequence.",
        "links": ["second_ball_set_piece_recovery", "penalty_box_overload_corner", "inswinging_corner_delivery"],
    },
    {
        "slug": "corner_short_clearance_transition",
        "title": "Defended-Corner Counter Transition",
        "summary": "A fast break launched immediately after defending a corner exploits the maximum defensive numerical disadvantage; transition xG from this sequence is among the highest in open-play soccer.",
        "stat_signature": "Clearance-to-forward-shot transition rate after defending a corner: ~18–26%; xG per completed transition: ~0.12–0.22; time from clearance to shot in clean transitions: ~6–10 seconds.",
        "mechanism": "An attacking team loading 7–9 bodies into the box leaves 1–2 defenders near halfway; a quick clearance to a stationed runner creates a 2-versus-1 or 1-versus-0 over 40–60 m of open space before recovery is possible.",
        "conditions": "Transition value is largest when the corner-defending team stations a fast runner centrally near halfway before the corner is taken; against teams holding defenders back, the transition advantage shrinks considerably.",
        "magnitude": "Large when the transition completes cleanly: xG of 0.12–0.22 per counter is roughly 4–6× the average corner delivery xG, making a disciplined counter-setup strategically significant.",
        "links": ["penalty_box_overload_corner", "second_ball_set_piece_recovery", "defensive_set_piece_marking"],
    },
]
