"""scripts.platformkit.specs.startquality_tennis — StartQuality concepts for Tennis.
Person-free, dense intelligence on how matches begin and early patterns form.
No player/team/match names anywhere.
"""
from __future__ import annotations

SPORT = "Tennis"
FAMILY = "StartQuality"

CONCEPTS = [
    {
        "slug": "first_set_win_tendency",
        "title": "First-Set Win Tendency",
        "summary": "Captures the rate at which a player takes the opening set and quantifies the conditional link between first-set outcome and full-match result; opening-set win rate is one of the highest-correlation predictors of match outcome across surfaces.",
        "stat_signature": "First-set win rate ranges from roughly 52% to 72% across the ATP ranking distribution; among players above 60% first-set win rate, match-win rate conditional on first-set win exceeds 85%, while match-win rate after dropping the first set falls below 35%.",
        "mechanism": "Winning the first set shifts set-score leverage immediately to 1-0, requiring the opponent to win two of three remaining sets; the psychological load asymmetry — pressure shifts to the trailing player — amplifies performance divergence in set 2 beyond what the score margin alone explains.",
        "conditions": "Effect is strongest in best-of-three formats where a first-set loss leaves no recovery margin; less deterministic at Grand Slams in best-of-five formats, where the trailing player has more sets to absorb the loss.",
        "magnitude": "A one-standard-deviation increase in first-set win rate (~8 points) is associated with roughly a 10-13 percentage point increase in overall match-win rate, all else equal.",
        "links": ["fast_start_early_break_conversion", "first_set_carryover_to_match", "early_deficit_set_recovery", "first_set_break_point_conversion"],
    },
    {
        "slug": "slow_starter_early_break_concession",
        "title": "Slow-Starter Early-Break Concession",
        "summary": "Measures the rate at which a player is broken within the first three service games of a match, reflecting serve rhythm not yet dialed in, conservative first-serve intent, or vulnerable patterns readable by opponents before counter-adjustment occurs.",
        "stat_signature": "Typical early-break concession rate over the first three service games is 12-18% on hard courts; players profiled as slow starters show rates of 22-30% in games 1-3 falling to 10-14% in games 4-10, a gap of more than 10 percentage points.",
        "mechanism": "Neuromuscular warm-up lag means serve mechanics are not yet fully grooved in the first minutes of competition; spin control, leg-drive timing, and toss consistency all require a warm-up window that match conditions may not always allow.",
        "conditions": "Most pronounced after short warm-up allowances, late-afternoon scheduling when muscle temperature builds slowly, or on outdoor courts in cold conditions; also surfaces when opponents use aggressive early return positioning before the server has established patterns.",
        "magnitude": "Slow-starter players concede breaks in the first three service games at roughly 60-80% above their match-average break rate, recovering to near-baseline by game 6.",
        "links": ["first_service_game_hold_security", "first_few_games_serve_calibration", "warmup_to_match_transition", "opening_games_serve_placement_variety"],
    },
    {
        "slug": "first_few_games_serve_calibration",
        "title": "First-Few-Games Serve Calibration",
        "summary": "Captures the measurable divergence between early-match and full-match serve percentages, reflecting the mechanical calibration window before toss height, racket-face angle, and leg-drive timing fully converge.",
        "stat_signature": "First-serve percentage in games 1-3 averages 55-61% compared with a match-long mean of 62-66%; double-fault rate in the opening three service games is 30-50% above the match baseline; ace rate in games 1-3 is 15-25% below the match rate.",
        "mechanism": "Serve calibration is an iterative kinematic process: muscle spindle feedback from the first few tosses adjusts upper-body rotation and contact-point height; until the feedback loop converges, placement variance is elevated and margin errors produce double faults.",
        "conditions": "Exacerbated when warm-up is rushed, when wind or sun angle changes toss stability, or when altitude and ball bounce differ from the previous tournament; less visible among flat baseliners whose serve mechanics require less rotational precision.",
        "magnitude": "Double-fault rate is typically 1.5-2.5 standard deviations above the match average in the first two service games before decaying toward baseline by game 5.",
        "links": ["slow_starter_early_break_concession", "cold_start_first_serve_velocity_ramp", "first_service_game_hold_security", "opening_games_serve_placement_variety"],
    },
    {
        "slug": "opening_games_return_aggression",
        "title": "Opening-Games Return Aggression",
        "summary": "Captures the degree to which a player establishes early return pressure, measured as break-point creation rate and return points won in the first three return games relative to the full-match average.",
        "stat_signature": "Return-points-won in games 1-3 of a match averages 2-5 points below the match mean for the majority of players; aggressive returners who begin above match average in games 1-3 create break points at a rate roughly 20-30% above their typical frequency in those early games.",
        "mechanism": "Early return aggression forces the server to vary placement sooner, compressing the opponent's serve-calibration window and creating short-ball opportunities before the server has established reliable depth and spin; it shifts the calibration asymmetry to the returner's advantage.",
        "conditions": "Effective against slow-starting servers with poor early first-serve percentage; less effective against flat, high-velocity servers whose opener game is less margin-dependent; amplified on hard courts where aggressive early returns stay low.",
        "magnitude": "Players who rank in the top quartile for games-1-3 return-point-win rate are approximately 8-12 percentage points more likely to break in the opening service game relative to the full-match break probability.",
        "links": ["fast_start_early_break_conversion", "first_set_break_point_conversion", "slow_starter_early_break_concession", "early_rally_length_settling"],
    },
    {
        "slug": "fast_start_early_break_conversion",
        "title": "Fast-Start Early-Break Conversion",
        "summary": "Measures the rate of converting a break of serve within the first three return games and the subsequent set-win likelihood conferred by establishing an early lead before the opponent's game settles.",
        "stat_signature": "Early-break conversion rate (within the first three return games) averages 10-16% for the touring field; players above 20% in this window win roughly 70-78% of sets in which they break early, versus 55-60% when the first break comes later.",
        "mechanism": "Early breaks exploit maximum serve-calibration vulnerability while simultaneously loading psychological pressure onto the opponent before tactical patterns have been established; the trailing player must break back without yet having enough return data to optimise positioning.",
        "conditions": "Most decisive on fast surfaces where breaks are rare and early leverage is highest; reduces in value on clay where breaks are recovered more frequently and the trailing player has more time to readjust.",
        "magnitude": "Converting the first break of serve within games 1-3 raises set-win probability roughly 15-20 percentage points above the mid-set break equivalent.",
        "links": ["opening_games_return_aggression", "first_set_win_tendency", "first_set_break_point_conversion", "early_set_momentum_swing_sensitivity"],
    },
    {
        "slug": "first_set_unforced_error_rate",
        "title": "First-Set Unforced-Error Rate",
        "summary": "Captures shot-tolerance instability in the opening set, measured as the ratio of first-set unforced errors per game to subsequent-set rates, reflecting timing not yet settled and tactical caution or over-aggression before patterns calibrate.",
        "stat_signature": "First-set unforced-error rate per game is on average 8-14% above the set-2 and set-3 combined rate for hard-court matches; the decay is sharpest between games 1-3 and games 7-12 within set 1, with error rates in games 1-3 running 15-22% above the set-1 average.",
        "mechanism": "Shot-timing calibration requires feedback from actual match conditions — bounce height, ball feel, and opponent contact depth all deviate from warm-up expectations; until corrected, racket-face control at contact produces elevated groundstroke errors.",
        "conditions": "Most pronounced on surfaces with unusual bounce characteristics relative to the player's recent surface history; also elevated after quick scheduling turnarounds that limit physical recovery and movement calibration.",
        "magnitude": "First-set unforced errors average roughly one additional error per service game compared with set-2 baseline on outdoor hard courts, declining to parity by the third set.",
        "links": ["warmup_to_match_transition", "first_set_baseline_depth_calibration", "early_rally_length_settling", "first_few_games_serve_calibration"],
    },
    {
        "slug": "warmup_to_match_transition",
        "title": "Warmup-to-Match Transition",
        "summary": "Captures the speed at which competitive match rhythm arrives once points count, measured as points won in the opening two games relative to the player's set-average, reflecting how quickly the psychological gear-shift from casual warm-up to competitive execution occurs.",
        "stat_signature": "Points-won rate in games 1-2 averages 2-5 points below the set mean for the overall field; the fastest-transitioning quartile shows a gap of under 1 point, while the slowest quartile shows a gap exceeding 7 points in the opening two games.",
        "mechanism": "Warm-up is structurally cooperative while match play is adversarial; competitive arousal, tactical focus, and motor intensity must all re-calibrate within the first games; players with slow transitions often rely on proprioceptive routines that differ from match-pace execution.",
        "conditions": "Most visible in the first service game, where the server must immediately execute under match pressure; less prominent after a long first service game in which both players have already accumulated competitive point data.",
        "magnitude": "Slow-transition players lose roughly 3-5 additional points in the opening two games compared with their per-game average, a deficit equivalent to approximately 0.3-0.5 breaks of expected set advantage.",
        "links": ["first_service_game_hold_security", "slow_starter_early_break_concession", "first_set_unforced_error_rate", "first_few_games_serve_calibration"],
    },
    {
        "slug": "first_service_game_hold_security",
        "title": "First Service-Game Hold Security",
        "summary": "Measures how reliably a player holds the opening service game of a match and quantifies the downstream effect on set outcome, given that an early hold establishes serve rhythm while an early break amplifies opponent confidence.",
        "stat_signature": "First service-game hold rate averages 78-84% on hard courts, approximately 2-5 points below the match-wide hold rate; players above 88% in the opening game win the first set at roughly 62% versus 50% for those below 75%.",
        "mechanism": "A successful hold in game 1 confirms serve rhythm and grants the early service-rotation advantage, forcing the opponent to break to lead; an opening break forces an immediate deficit when serve calibration is most vulnerable and creates momentum loading before the match has settled.",
        "conditions": "High-stakes effect is amplified on fast surfaces where holding is the dominant mode and breaks are statistically rare; on clay, the cost of an opening break is lower because breaks are recovered more frequently across the set.",
        "magnitude": "Opening service-game hold rate is a 2-4 percentage point predictor of first-set win probability beyond the serve-strength baseline.",
        "links": ["slow_starter_early_break_concession", "warmup_to_match_transition", "first_few_games_serve_calibration", "early_set_momentum_swing_sensitivity"],
    },
    {
        "slug": "early_rally_length_settling",
        "title": "Early Rally-Length Settling",
        "summary": "Captures the winner-to-error ratio imbalance in the first few games when footwork and timing are still warming up, manifesting as a higher proportion of forced and unforced errors in short-to-medium rallies before movement calibration converges.",
        "stat_signature": "Winner-to-error ratio in rallies of 1-4 shots during games 1-4 averages roughly 0.4-0.6 compared with a match-long ratio of 0.7-1.0; unforced errors on rallies of 3-6 shots are 20-30% above the match mean in the first four games.",
        "mechanism": "Footwork timing, split-step rhythm, and swing-path calibration require competitive repetitions to match real-match ball pace and spin; until adjusted, lateral recovery is fractionally late, contact is rushed, and open-stance improvisation produces elevated errors.",
        "conditions": "Most observable on players with precise, timing-sensitive groundstroke mechanics who rely on consistent contact-point geometry; flat-hitting players with larger swing margins are less affected; surface traction and bounce speed modulate the calibration window.",
        "magnitude": "Winner-to-error ratio in early rallies is typically 40-50% below the match-long ratio, recovering to within 10% of match average by game 6.",
        "links": ["first_set_unforced_error_rate", "warmup_to_match_transition", "first_set_baseline_depth_calibration", "opening_games_return_aggression"],
    },
    {
        "slug": "first_set_baseline_depth_calibration",
        "title": "First-Set Baseline Depth Calibration",
        "summary": "Captures the lag in groundstroke depth accuracy in the opening set, measured as the frequency of short-ball errors and length errors relative to later-set rates, reflecting the calibration of swing trajectory against match-specific ball pace and bounce.",
        "stat_signature": "Short-ball rate (landing inside the service box on non-drop shots) averages 8-12% in set-1 games 1-4, falling to 4-7% by set 2; length errors (balls landing long from baseline exchanges) are 15-25% above the set-2 average in the opening four games.",
        "mechanism": "Groundstroke depth is determined by swing speed, contact height, and spin RPM interaction with the ball's felt condition and court surface friction; an initial calibration window of 6-10 baseline exchanges is required before depth estimates converge, producing short-ball and length outliers during adjustment.",
        "conditions": "Most pronounced when court surface speed differs from the player's most recent tournament, when ball brand changes, or after a rest day reducing muscle priming; clay specialists transitioning to hard courts show the largest depth-calibration gaps.",
        "magnitude": "Short-ball frequency in the first four games is roughly double the match-long rate, providing a quantifiable quality signal for early-set rally patterns.",
        "links": ["early_rally_length_settling", "first_set_unforced_error_rate", "first_few_games_serve_calibration", "set_one_pace_of_play_settling"],
    },
    {
        "slug": "opening_games_serve_placement_variety",
        "title": "Opening-Games Serve-Placement Variety",
        "summary": "Measures the directional spread of first serves across wide, body, and T zones in the opening three games versus the full-match distribution, capturing whether a player establishes pattern diversity early or defaults to a narrow range before reading the opponent.",
        "stat_signature": "Directional entropy of first-serve placement (measured as the Shannon diversity of zone distribution) in games 1-3 is roughly 10-20% below the match-long entropy for the median player; players in the top quartile for opening-game variety use all three zones at near full-match frequency from game 1.",
        "mechanism": "Early placement variety forces the returner to maintain a neutral split-step rather than pre-loading toward an expected zone, delaying the opponent's ability to position early and penalising early return aggression; narrow early patterns are more readable and allow the returner to establish return patterns before the server adjusts.",
        "conditions": "High-variety openers are more effective against returners who heavily weight their positioning by prior serve data; less impactful against returners with fast reaction speed who can cover late regardless of pre-loading.",
        "magnitude": "Players in the top quartile for early serve-placement variety allow roughly 1-2 fewer return-point-won percentage points in games 1-3 compared with narrow-pattern openers.",
        "links": ["first_few_games_serve_calibration", "cold_start_first_serve_velocity_ramp", "slow_starter_early_break_concession", "first_service_game_hold_security"],
    },
    {
        "slug": "early_set_momentum_swing_sensitivity",
        "title": "Early-Set Momentum Swing Sensitivity",
        "summary": "Measures the degree to which the first break of serve in a set shifts set-win probability, capturing the asymmetric structural weight of an early break when both players are least adapted to the competitive context.",
        "stat_signature": "A break in the first two games of a set raises set-win probability from roughly 50% to 65-72%; the equivalent break in games 5-7 raises probability to only 60-65%; first-break-of-set conversion rates average 28-35% for the touring field.",
        "mechanism": "Score-line pressure is maximised early in the set because the trailing player must break back under full recovery burden; when the break occurs after game 2, both players have established patterns, slightly reducing the psychological leverage of the deficit.",
        "conditions": "Effect is strongest in set 1 when neither player has calibrated patterns and the emotional gradient is steepest; partially buffered in set 2 or 3 when the trailing player has match-context information to draw on for return adjustment.",
        "magnitude": "The first break of a set delivers roughly 15-22 percentage points of set-win probability on hard courts, tapering to 10-15 points when the break occurs after game 4.",
        "links": ["fast_start_early_break_conversion", "first_set_break_point_conversion", "first_service_game_hold_security", "first_set_win_tendency"],
    },
    {
        "slug": "first_set_break_point_conversion",
        "title": "First-Set Break-Point Conversion",
        "summary": "Captures the rate of converting break points in the first set relative to the match-long conversion rate, isolating the clutch returning quality under early-set pressure when serve calibration is weakest.",
        "stat_signature": "First-set break-point conversion averages 42-48% on hard courts, typically within 2-3 points of the match-long conversion rate; players who outperform their match-long conversion in set 1 by more than 5 points win first sets at roughly 65-72%, compared with 50% for those who underperform.",
        "mechanism": "Break-point conversion integrates return aggression, serve-read accuracy, and clutch execution; in the first set, conversion is elevated when the server's first-serve percentage is at its lowest, creating a structural window that skilled returners exploit before the server recalibrates.",
        "conditions": "Most decisive against flat-serving or high-double-fault servers whose opening calibration creates multiple high-pressure points; less separating against kick-serve specialists whose spin-dependent accuracy is relatively stable from game 1.",
        "magnitude": "A 10-point above-average first-set break-point conversion rate is associated with a roughly 12-15 percentage point increase in first-set win probability over the baseline.",
        "links": ["opening_games_return_aggression", "first_set_win_tendency", "early_set_momentum_swing_sensitivity", "fast_start_early_break_conversion"],
    },
    {
        "slug": "cold_start_first_serve_velocity_ramp",
        "title": "Cold-Start First-Serve Velocity Ramp",
        "summary": "Captures the ramp in first-serve average speed across the opening games, reflecting the physical and mechanical warm-up of rotational power before peak serve velocity is consistently accessible.",
        "stat_signature": "Average first-serve velocity in games 1-3 is typically 4-8 km/h below the match peak for hard-court players; the full velocity range is reached by game 5-7 in most matches; ace frequency in games 1-3 is 20-35% below the match-long ace rate.",
        "mechanism": "Explosive serve velocity depends on rotational power from legs, trunk, and shoulder chain — a kinetic sequence requiring multiple near-maximal efforts to activate fully; muscle viscosity at match start, particularly in cooler conditions, delays access to peak neuromuscular output.",
        "conditions": "Most pronounced in early-morning or outdoor cold-weather matches; faster warm-up achieved in night sessions with higher ambient temperature; exacerbated on faster surfaces where velocity delta carries higher break-risk implications.",
        "magnitude": "Serve velocity ramp accounts for an estimated 1.5-2.5 percentage point difference in first-serve points won between games 1-3 and games 6-10.",
        "links": ["first_few_games_serve_calibration", "opening_games_serve_placement_variety", "slow_starter_early_break_concession", "set_one_pace_of_play_settling"],
    },
    {
        "slug": "early_deficit_set_recovery",
        "title": "Early-Deficit Set Recovery",
        "summary": "Captures the rate at which a player recovers from an early break deficit within the first set, measuring the ability to absorb an early reversal and re-establish parity before the deficit compounds.",
        "stat_signature": "The field average break-back rate following an early break (within games 1-3) is 28-36%, varying by surface; on clay it exceeds 38%, on grass it falls below 25%; players above 40% break-back rate from early deficits demonstrate significantly higher set-win probability after going down early.",
        "mechanism": "Early-deficit recovery is enabled by serve-side recovery in the next game, calibrated return patterns that improve after seeing the opener, and absence of accumulated fatigue pressure; breaking back immediately before the deficit becomes a double break re-balances the structural asymmetry.",
        "conditions": "Higher recovery rates on clay where service holds are less dominant; recovery is most likely when the deficit is exactly one break in games 1-3, making a single break-back sufficient to level the set.",
        "magnitude": "Players in the top quartile for early-deficit recovery win approximately 38-42% of sets in which they are broken in the first three games, compared with roughly 22-26% for the bottom quartile.",
        "links": ["first_set_win_tendency", "early_set_momentum_swing_sensitivity", "first_set_carryover_to_match", "first_set_break_point_conversion"],
    },
    {
        "slug": "first_set_tiebreak_propensity",
        "title": "First-Set Tiebreak Propensity",
        "summary": "Measures the rate at which a player's first sets reach a tiebreak, capturing whether early-set dynamics tend to produce a closely held opening set resolved at 6-6 rather than a decisive early break defining the set.",
        "stat_signature": "ATP hard-court first sets go to a tiebreak in roughly 18-22% of matches; players with first-set tiebreak rates above 30% tend to be consistent holders with low early-break concession profiles; tiebreak-heavy players show first-serve points won above 67% and opponent return-points won below 38%.",
        "mechanism": "High tiebreak propensity reflects strong mutual hold dominance in the opening set — both players are holding through the serve-calibration window, producing a set where break opportunities are rare and the 7-game score persists to 6-6; this pattern selects for serve-dominant or return-passive styles.",
        "conditions": "Amplified on fast indoor hard courts and grass where hold dominance is structural; reduced on clay where breaks are more frequent and tiebreaks are rarer; also associated with slow-starting returners who concede early rhythm.",
        "magnitude": "First-set tiebreak propensity correlates at roughly r = 0.55 with first-serve points-won rate, making it a derived serve-dominance indicator rather than an independent performance dimension.",
        "links": ["first_service_game_hold_security", "first_set_win_tendency", "slow_starter_early_break_concession", "early_set_momentum_swing_sensitivity"],
    },
    {
        "slug": "first_set_second_serve_exposure",
        "title": "First-Set Second-Serve Exposure",
        "summary": "Captures the vulnerability of the second serve in the opening set relative to later sets, when first-serve percentage is at its lowest, creating more frequent second-serve exposures against a returner who has not yet been pattern-tested.",
        "stat_signature": "Second-serve points won in set 1 averages 50-54% on hard courts, roughly 2-4 points below the set-2 and set-3 combined average; second-serve balls-in-play rate is approximately 3-5% above the match average in the first set due to elevated double-fault avoidance behavior.",
        "mechanism": "When first-serve percentage is suppressed by calibration lag, second-serve frequency rises; second serves are slower and more predictable, enabling the opponent's aggressive return positioning before reading tendencies have been established; the combination of more second serves and a fresh opponent creates maximum second-serve pressure.",
        "conditions": "Most damaging against aggressive returners who position early and attack the shorter second serve; less critical against passive returners who do not punish high-bouncing kick serves.",
        "magnitude": "Second-serve exposure in set 1 contributes an estimated 1-2 additional break points created per set for quality returners relative to later-set exposure levels.",
        "links": ["first_few_games_serve_calibration", "cold_start_first_serve_velocity_ramp", "slow_starter_early_break_concession", "opening_games_return_aggression"],
    },
    {
        "slug": "first_set_carryover_to_match",
        "title": "First-Set Carryover to Match",
        "summary": "Measures the full-match win rate conditional on first-set outcome, quantifying how completely the opening set predicts the final result across formats and surfaces.",
        "stat_signature": "On hard courts in ATP best-of-three matches, first-set winners win the match approximately 74-78% of the time; in Grand Slam best-of-five, the first-set winner proceeds to win the match roughly 68-72%; both figures are stable across ranking ranges, confirming structural rather than quality-driven carryover.",
        "mechanism": "First-set win initiates a self-reinforcing cycle: the leader serves first in the second set, carries psychological momentum into the serving rotation, and benefits from the opponent's forced aggressive play; structural leverage compounds rather than cancels as the match progresses.",
        "conditions": "Carryover is strongest when the first set was won decisively (6-3 or better) rather than by tiebreak — tiebreak set-wins show match-win rates roughly 5-8 points lower than break-dominant set-wins; surface modulation is modest.",
        "magnitude": "First-set win in ATP best-of-three is associated with a roughly 28-29 percentage point match-win lift over the 50% base expectation prior to the first point.",
        "links": ["first_set_win_tendency", "early_deficit_set_recovery", "fast_start_early_break_conversion", "early_set_momentum_swing_sensitivity"],
    },
]
