"""StartQuality Soccer concept nodes — person-free, calibration-only intelligence."""
from __future__ import annotations

SPORT = "Soccer"
FAMILY = "StartQuality"

CONCEPTS: list[dict] = [
    {
        "slug": "opening_fifteen_goal_tendency",
        "title": "Opening-Fifteen Goal Tendency",
        "summary": "Scoring concentration in the first fifteen minutes relative to the per-fifteen baseline reveals structural identity in pressing aggression and directness, with some sides systematically over-indexing on early goals.",
        "stat_signature": "Goals per minute in the 0-15 band averages 15-25% above the 16-60 plateau across top leagues; sides with the top-quartile early-goal rate produce over 20% of match goals before minute 16; the share ranges from 12% to 30% across style archetypes.",
        "mechanism": "Fresh legs sustain high-intensity pressing that triggers early transition chances; an opponent's defensive shape is least settled in the first five minutes before block organisation stabilises; directness-oriented sides exploit the tactical uncertainty of the opening phase before the opposition locks in their defensive block.",
        "conditions": "Strongest in high-press-identity and direct-attacking systems; home sides show a higher early-goal rate than away sides on average; effect is reduced in cautious away-game plans that prioritise defensive solidity for the first 20 minutes.",
        "magnitude": "Early-goal rate roughly 15-25% above the mid-match baseline; top-quartile early-scoring sides average 0.22-0.30 goals before minute 16 per match versus a league baseline of 0.16-0.20.",
        "links": ["fast_start_pressing_intensity", "opening_phase_shot_generation", "early_tempo_imposition", "early_set_piece_threat"],
    },
    {
        "slug": "early_goal_conceded_susceptibility",
        "title": "Early-Goal-Conceded Susceptibility",
        "summary": "Vulnerability to concessions in the first fifteen minutes identifies sides whose defensive shape is slow to organise from kickoff, whether through high-line exposure, aggressive initial pressing that leaves space, or poor set-piece marking at the start.",
        "stat_signature": "Goals conceded per minute in the 0-15 band averaging over 20% above the match baseline marks elevated susceptibility; bottom-quartile defensive starters concede 18-28% of their goals before minute 16; early expected-goals-against split exceeds 0.20 per match for the most exposed profiles.",
        "mechanism": "A slow-settling defensive block leaves the space behind an eager midfield press available for quick-transition attacks; set-piece sequences in early minutes exploit not-yet-locked marking assignments; opponent pressing traps catch a side before it establishes a passing rhythm that enables escape.",
        "conditions": "Susceptibility is amplified against high-press-from-kickoff opponents and in away fixtures with high early-intensity crowds; reduced for compact deep-block starters that concede possession but maintain defensive solidity from the first whistle.",
        "magnitude": "Early concession rate 20-30% above mid-match baseline; sides conceding an opening-fifteen goal lose roughly 60-68% of such matches, versus a baseline loss rate of 40-50% when goals arrive later.",
        "links": ["first_phase_defensive_compactness", "early_transition_exposure", "settling_period_error_rate", "settling_into_block_timing"],
    },
    {
        "slug": "fast_start_pressing_intensity",
        "title": "Fast-Start Pressing Intensity",
        "summary": "Opening-fifteen pressing density above a side's match-long average reflects a deliberate strategy to disrupt opponent build-up before it establishes rhythm, creating early chance clusters at the cost of higher mid-match intensity fatigue.",
        "stat_signature": "PPDA (passes allowed per defensive action) in the 0-15 band that is 20-35% tighter than match-average PPDA signals a fast-start press; pressing-action count per minute peaks 110-125% of the match average in this window for high-intensity starters; high-intensity distance per minute peaks in the 0-15 band at 115-130% of the match norm.",
        "mechanism": "Sides commit to coordinated press-triggers from kickoff to disrupt the opponent's first build-up phase before it gains confidence; the psychological impact of early disruption can suppress an opponent's positional play for the entire first half; the trade-off is that sprint reserves deplete faster, constraining pressing intensity after 60 minutes.",
        "conditions": "Most effective against possession-reliant sides that require settled build-up patterns; less effective against direct-play opponents who bypass pressing lines with long balls; fatigue cost is greatest in fixture-congested periods.",
        "magnitude": "PPDA tightening of 20-35% in the opening phase relative to match average; fast-start pressing sides force 30-40% more pressing-triggered turnovers in the first 15 minutes versus the per-15-minute match baseline.",
        "links": ["opening_fifteen_goal_tendency", "early_tempo_imposition", "slow_starter_first_phase_passivity", "opening_phase_duel_intensity"],
    },
    {
        "slug": "slow_starter_first_phase_passivity",
        "title": "Slow-Starter First-Phase Passivity",
        "summary": "A deliberately cautious opening approach, evidenced by below-baseline attacking-third involvement and shot volume in the first fifteen minutes, reflects a block-first identity that trades early initiative for defensive solidity and counter-attacking preservation.",
        "stat_signature": "Attacking-third touches in the first fifteen minutes below 70% of the per-fifteen match average marks strong passivity; shot volume before minute 16 under 0.8 shots per match versus a baseline of 1.3-1.5 indicates systematic caution; progressive carries and forward passes in the opening phase below 60% of the match per-minute rate confirm the pattern.",
        "mechanism": "The tactical plan prioritises absorbing early opposition pressure in a deep block, preserving defensive compactness until the opponent's energy expenditure creates transition opportunities; accepting positional inferiority early in exchange for structural security reduces concession risk against superior opponents.",
        "conditions": "Characteristic of away fixtures against high-press sides and lower-table survival strategies; amplified in fixture contexts where a clean sheet has higher value than an early goal; reduced when chasing a deficit forces early activation.",
        "magnitude": "Attacking-third involvement 30-40% below match baseline in the opening fifteen; shot rate under 60% of the per-minute norm; first-fifteen expected-goals-for averaging under 0.07 per match for the most passive profiles.",
        "links": ["first_phase_defensive_compactness", "settling_into_block_timing", "fast_start_pressing_intensity", "early_tempo_imposition"],
    },
    {
        "slug": "opening_phase_shot_generation",
        "title": "Opening-Phase Shot Generation",
        "summary": "First-fifteen shot and expected-goals output relative to the per-fifteen match baseline distinguishes proactive attacking starters from reactive systems, with consistent patterns that persist across fixture contexts within the same style archetype.",
        "stat_signature": "Shots in the 0-15 band averaging 1.6 or more per match versus a league per-15-minute baseline of 1.2-1.4 signals above-average opening-phase output; expected-goals in the first fifteen above 0.22 per match (versus a baseline of 0.14-0.18) marks high attacking start quality; shot-on-target share in the opening band averages 35-42%.",
        "mechanism": "Early shot generation combines pressing-triggered transitions that create before-the-block shots and structured set-piece routines from early fouls; sides with fast-start identity direct more attacking resource into the phase when defensive organisation is weakest.",
        "conditions": "Elevated in home fixtures where crowd energy supports immediate aggression; highest for direct-play systems that do not require lengthy possession build-up to generate chances; lower in away cautious plans.",
        "magnitude": "Top-quartile opening-phase shot generators average 1.7-2.2 shots and 0.23-0.32 expected goals before minute 16; bottom-quartile profiles average under 0.8 shots and 0.08 expected goals in the same window.",
        "links": ["opening_fifteen_goal_tendency", "fast_start_pressing_intensity", "early_set_piece_threat", "early_tempo_imposition"],
    },
    {
        "slug": "first_phase_defensive_compactness",
        "title": "First-Phase Defensive Compactness",
        "summary": "How tightly a side maintains its defensive block from kickoff, measured as expected-goals conceded and opponent box entries in the first fifteen minutes, captures the quality of early defensive organisation before fatigue or game-state distorts shape.",
        "stat_signature": "Opponent box entries allowed per match in the first fifteen below 1.5 versus a baseline of 2.0-2.5 indicates high compactness; expected-goals conceded before minute 16 under 0.10 per match marks elite early defensive solidity; defensive block depth measured as average defensive-action distance from own goal above 38 metres signals a high line rather than compact block.",
        "mechanism": "A compact defensive block forces opponents into peripheral, low-probability delivery zones; early compactness is easier to maintain before fatigue reduces sprint-recovery capacity, meaning first-phase defensive shape reflects the team's optimal organised defensive identity before deterioration sets in.",
        "conditions": "Compactness is highest in away fixtures against dominant possession sides and in matches with low-block tactical plans; reduced in pressing-intensive home fixtures where the side pushes its own defensive line high from kickoff.",
        "magnitude": "Elite first-phase compactness restricts expected-goals conceded in the opening fifteen to under 0.09 per match; a one-unit improvement in box entries allowed (from 2.5 to 1.5 per match) corresponds to roughly 0.04-0.07 fewer expected goals conceded in the opening phase.",
        "links": ["early_goal_conceded_susceptibility", "settling_into_block_timing", "slow_starter_first_phase_passivity", "early_transition_exposure"],
    },
    {
        "slug": "early_tempo_imposition",
        "title": "Early Tempo Imposition",
        "summary": "Dictating match rhythm from the first whistle through above-average possession share and pass volume in the opening phase signals tactical dominance that constrains the opponent's ability to execute its planned game structure.",
        "stat_signature": "Opening-fifteen possession share above 56% versus a 50% baseline, combined with a pass-per-minute count at 110-125% of the match average, marks strong early tempo imposition; territorial control above 58% of play in the opponent half before minute 16 reinforces the signal.",
        "mechanism": "Establishing early possession dominance forces the opponent into reactive defensive positions that prevent them from executing their preferred attacking transitions; sustained rhythm disrupts the opponent's timing triggers and pressing cues, compounding into a match-long positional advantage.",
        "conditions": "Strongest for technically superior possession-based systems against pressing opponents who lose energy early; suppressed when the opponent successfully applies a high press that disrupts first-phase build-up sequences.",
        "magnitude": "Sides holding over 56% possession in the opening fifteen maintain it at 54-58% for the remainder of the first half in approximately 65-70% of matches, indicating tempo imposition is a durable early outcome rather than a transient fluctuation.",
        "links": ["fast_start_pressing_intensity", "opening_phase_shot_generation", "first_phase_build_up_directness", "opening_fifteen_goal_tendency"],
    },
    {
        "slug": "settling_period_error_rate",
        "title": "Settling-Period Error Rate",
        "summary": "Elevated misplaced-pass and possession-loss rates in the first fifteen minutes, before a side settles into its rhythm, reflect technical looseness under kickoff nerves and pressing pressure that can directly gift early goals.",
        "stat_signature": "Misplaced-pass rate in the first fifteen above 20% versus a match-average of 14-17% marks a high settling-period error rate; possession losses per minute in the opening phase at 120-140% of the match norm is a threshold for consistent early vulnerability; error-leading-to-shot rate 25-40% above the match baseline identifies high-risk settling patterns.",
        "mechanism": "Technical execution is degraded in the opening minutes by elevated cortisol, incomplete muscle activation, and lack of match rhythm; sides that have not yet established passing confidence accept high-risk plays to escape early pressing pressure, compounding the turnover rate before settled patterns emerge.",
        "conditions": "Error rate premium is amplified against high-press openers that immediately disrupt build-up and force low-confidence decisions; reduced for technically dominant sides with settled passing identities that maintain composure from the first touch.",
        "magnitude": "Error rate excess of 20-40% above match baseline in the first fifteen; a one-standard-deviation increase in opening-phase possession-loss rate corresponds to approximately 0.04-0.07 additional expected goals conceded in the same window.",
        "links": ["early_goal_conceded_susceptibility", "settling_into_block_timing", "fast_start_pressing_intensity", "first_phase_defensive_compactness"],
    },
    {
        "slug": "early_set_piece_threat",
        "title": "Early Set-Piece Threat",
        "summary": "First-fifteen dead-ball danger, measured by set-piece count and expected-goals generated from early fouls and corners, identifies sides that convert their opening-phase aggression into structured scoring platforms independent of open-play quality.",
        "stat_signature": "First-fifteen set-piece expected-goals above 0.08 per match versus a baseline of 0.04-0.06 marks elevated early dead-ball threat; corners won before minute 16 averaging over 1.8 per match versus a baseline of 1.2-1.5 indicates systematic wide aggression; early-foul-drawn rate 25-35% above the match per-minute norm captures aggressive attackers winning set pieces.",
        "mechanism": "Physically and tactically aggressive opening phases produce fouls that generate free kicks and corners at a rate above the match average; sides with set-piece coaching depth exploit these early opportunities against not-yet-locked defensive marking assignments before the opponent's rehearsed set-piece shape is fully activated.",
        "conditions": "Most dangerous when combined with aerial-specialist profiles and organised delivery routines; amplified in home fixtures where crowd pressure induces early opponent fouling; reduced against deep-block openers who concede few fouls before minute 16.",
        "magnitude": "Early set-piece expected-goals contribution of 0.08-0.14 per match for the highest-threat profiles versus 0.02-0.04 for low-threat early phases; approximately 15-22% of opening-fifteen goals arise from dead-ball situations for set-piece dominant sides.",
        "links": ["opening_fifteen_goal_tendency", "opening_phase_shot_generation", "opening_phase_duel_intensity", "fast_start_pressing_intensity"],
    },
    {
        "slug": "early_transition_exposure",
        "title": "Early Transition Exposure",
        "summary": "Counterattacking chances conceded per match in the opening phase quantify the defensive vulnerability created when sides commit players forward aggressively from kickoff before their defensive shape has recovered.",
        "stat_signature": "Counterattacking chances conceded in the first fifteen above 0.8 per match versus a baseline of 0.4-0.6 indicates high early transition exposure; opponent fast-break shots before minute 16 averaging 1.2 or more per match marks a structural risk; transition expected-goals-against in this band above 0.07 per match signals systematic vulnerability.",
        "mechanism": "Aggressive attacking postures pull midfielders high, leaving space in behind for direct passes or dribble-through counters; before defensive confidence and energy management habits settle, sides pushing for early goals accept position-for-position trades that expose their backline to organised breaks.",
        "conditions": "Risk is highest against direct-play opponents with fast central attackers who can punish over-committed defensive lines; reduced when the opponent lacks counter-attacking pace or prefers possession retention to quick transitions.",
        "magnitude": "High-exposure profiles concede 0.07-0.12 transition expected goals in the first fifteen per match versus under 0.03 for compact starters; approximately 20-30% of opening-fifteen goals conceded by aggressive starters arrive via counterattacking routes.",
        "links": ["early_goal_conceded_susceptibility", "fast_start_pressing_intensity", "first_phase_defensive_compactness", "early_transition_exposure"],
    },
    {
        "slug": "opening_phase_duel_intensity",
        "title": "Opening-Phase Duel Intensity",
        "summary": "Physical engagement from kickoff, measured as first-fifteen duel and tackle count relative to the match-long rate, identifies sides that seek to impose physical dominance before the referee establishes a tolerance level and before opponents settle into their challenge timing.",
        "stat_signature": "Duels per minute in the first fifteen at 120-140% of the match norm marks high opening-phase physical intensity; tackles attempted before minute 16 at 130% or more of the per-minute match baseline indicates an aggressive early challenge strategy; foul count per minute in the opening phase at 115-130% of match average reflects physical intensity crossing into illegal contact.",
        "mechanism": "Early physical dominance in duels establishes psychological pressure that can disrupt technically-oriented opponents' confidence from the outset; referees calibrate tolerance in the first ten minutes, meaning early physical intensity can set a more permissive contest frame for the remainder of the match.",
        "conditions": "Highest in lower-league and survival-context matches where physicality over technique is the levelling mechanism; amplified in derby and high-stakes fixtures; reduced in technically dominant sides where duel avoidance through positional play is the preferred method.",
        "magnitude": "Opening-phase duel rate of 120-140% above the match norm; sides winning over 58% of first-fifteen duels maintain a 55-60% duel win-rate for the remainder of the match in approximately 60% of cases, suggesting early duel dominance is a partial predictor of full-match physical outcomes.",
        "links": ["fast_start_pressing_intensity", "early_set_piece_threat", "opening_fifteen_card_risk", "opening_fifteen_goal_tendency"],
    },
    {
        "slug": "early_lead_game_state_shift",
        "title": "Early-Lead Game-State Shift",
        "summary": "Scoring within the first fifteen minutes fundamentally reshapes both sides' match approach, with the leading side typically shifting toward defensive consolidation and the trailing side increasing attacking tempo, altering possession and shot-rate distributions for the remainder of the match.",
        "stat_signature": "Possession share for the scoring side drops 5-9 percentage points after a first-fifteen goal relative to pre-goal baselines; shot rate for the conceding side increases 25-35% in the 16-45 window following an early goal; leading sides' expected-goals-against rate rises 0.08-0.14 per match as the opponent chases.",
        "mechanism": "Rational game-state management by the scoring side reduces risk by ceding possession in exchange for structural defensive security; the trailing side activates urgency mode earlier than it would in a level match, compressing the time available for its preferred build-up and forcing more direct risk-taking.",
        "conditions": "Shift is most pronounced when the early goal arrives before minute 10, maximising the remaining game-state pressure time; reduced when the scoring side's identity is possession-dominant, as it maintains ball control even while leading.",
        "magnitude": "Possession swing of 5-9 percentage points post-early-goal; trailing-side shot rate uplift of 25-35% in the first-half remainder; combined match expected-goals rise approximately 0.15-0.25 above the baseline for all-level first-half scenarios when a first-fifteen goal is scored.",
        "links": ["opening_fifteen_goal_tendency", "early_deficit_response_pattern", "early_tempo_imposition", "first_phase_defensive_compactness"],
    },
    {
        "slug": "early_deficit_response_pattern",
        "title": "Early-Deficit Response Pattern",
        "summary": "How a side responds to conceding in the first fifteen minutes — whether it accelerates attacking-third entries and expected-goals generation, or whether it absorbs the blow and resets structure — reveals resilience characteristics and the depth of its tactical flexibility.",
        "stat_signature": "Attacking-third entries per match in the 16-45 window after an early concession rising over 20% above baseline marks an aggressive reactive response; expected-goals-for in the 16-45 window exceeding 0.25 per match after an early goal against (versus a baseline of 0.18-0.22) indicates effective counter-reaction; sides that fail to react show expected-goals-for in that band under 0.14 per match.",
        "mechanism": "The emotional and tactical response to conceding early determines whether the deficit becomes 2-0 or is quickly restored to parity; sides with tactical flexibility and bench depth can make early adjustments that redirect energy into productive attacking output before half-time; psychologically resilient sides maintain structural discipline rather than over-committing and exposing themselves to a two-goal deficit.",
        "conditions": "Resilient response is characteristic of sides with experienced leadership and tactical coaching depth; suppressed in sides with brittle confidence or limited substitution flexibility in the first half.",
        "magnitude": "Sides mounting an effective early-deficit response generate 30-45% more expected goals in the 16-45 band than passive responders; equaliser rates before half-time after a first-fifteen concession range from 18-32% across style archetypes.",
        "links": ["early_lead_game_state_shift", "settling_period_error_rate", "opening_fifteen_goal_tendency", "fast_start_pressing_intensity"],
    },
    {
        "slug": "first_phase_build_up_directness",
        "title": "First-Phase Build-Up Directness",
        "summary": "The balance between long-ball and short-pass progression in the first fifteen minutes captures a side's opening tactical identity, with direct starters bypassing midfield under early pressing pressure and possession sides committing to recycling regardless of opposition intensity.",
        "stat_signature": "Long-pass share above 22% of total passes in the opening fifteen versus a match norm of 14-18% marks high directness; average progressive-pass distance above 28 metres per pass in the opening band signals direct intent; short-pass completion in the first fifteen below 76% alongside elevated long-ball use confirms pressing-induced directness.",
        "mechanism": "Against high early press, direct build-up avoids press-traps by skipping midfield lines and targeting runners in behind; possession-oriented sides that commit to short-circuit build-up in the opening phase accept higher turnover risk in exchange for establishing their preferred structural control.",
        "conditions": "Directness is highest in away fixtures against aggressive home presses and in matches where the opponent's high line creates space behind their defensive block; reduced for technically superior possession sides that outpass pressure rather than bypass it.",
        "magnitude": "High-directness starters average 22-30% long-pass share in the opening phase versus 11-15% for possession-based starters; a 10-percentage-point shift in opening long-pass share corresponds to roughly a 4-6-metre shift in average field position gained per possession in the first fifteen.",
        "links": ["slow_starter_first_phase_passivity", "early_tempo_imposition", "fast_start_pressing_intensity", "opening_phase_shot_generation"],
    },
    {
        "slug": "settling_into_block_timing",
        "title": "Settling-Into-Block Timing",
        "summary": "The elapsed minutes before a side establishes a stable defensive shape from kickoff, measured as expected-goals-against rate before the block solidifies, captures the window of structural vulnerability that aggressive opponents can exploit.",
        "stat_signature": "Expected-goals conceded per minute in minutes 0-8 averaging 30-50% above the 9-45-minute per-minute baseline indicates a slow block-settling profile; defensive block depth stabilisation — measured as variance in average defensive line position falling below a threshold — typically occurs between minutes 5 and 12 for most sides; sides whose block settles after minute 10 concede 25-35% more expected goals before half-time than sides settled by minute 6.",
        "mechanism": "Tactical instructions take time to materialise as players shift from pre-match preparation to live execution; adrenaline-driven positioning errors in the first minutes gradually correct as verbal coordination and visual cues align the defensive unit; opponents with direct kick-off routines specifically exploit this unsettled window.",
        "conditions": "Settling delay is amplified in high-elevation or travel-fatigued contexts; reduced for deeply drilled compact systems with years of coordinated block organisation; away sides in hostile atmospheres tend to settle slower than home sides.",
        "magnitude": "Slow-settling profiles (block stabilised after minute 10) concede 0.06-0.11 additional expected goals in the 0-10 window versus fast-settling profiles; approximately 18-28% of goals scored before minute 15 occur within the first 8 minutes, confirming the highest-vulnerability clustering early.",
        "links": ["early_goal_conceded_susceptibility", "first_phase_defensive_compactness", "settling_period_error_rate", "early_transition_exposure"],
    },
    {
        "slug": "opening_fifteen_card_risk",
        "title": "Opening-Fifteen Caution Risk",
        "summary": "First-fifteen foul count and caution rate above the match-interval baseline identifies sides whose aggressive opening-phase intensity crosses into disciplinary exposure, with early yellow cards constraining physical approach for the remainder of the match.",
        "stat_signature": "Fouls per minute in the first fifteen at 130% or more of the match norm marks high early disciplinary exposure; caution rate in the opening fifteen (cards per match in this band) averaging above 0.35 versus a per-15-minute match baseline of 0.18-0.25 is elevated; aggressive starts by a two-card-per-match profile concentrate 30-40% of those cards before minute 16.",
        "mechanism": "The physical urgency of an aggressive opening, combined with a referee still calibrating tolerance, produces foul and caution concentrations; an early yellow card forces the booked player to moderate physical intensity for 75-plus minutes, diluting a pressing or combative strategy before it achieves full effect.",
        "conditions": "Risk is highest in high-press, high-duel-intensity starters and in matches with high physical stakes; elevated in two-legged ties where early card accumulation carries across legs; reduced for technically adept sides that press with positioning rather than physical contact.",
        "magnitude": "High-card-risk opening profiles receive yellow cards before minute 16 in approximately 30-40% of matches; a first-fifteen caution reduces that player's duel and pressing involvement in the remainder of the match by an estimated 15-25%.",
        "links": ["opening_phase_duel_intensity", "fast_start_pressing_intensity", "early_set_piece_threat", "opening_fifteen_goal_tendency"],
    },
    {
        "slug": "goalkeeper_early_involvement",
        "title": "Goalkeeper Early Involvement",
        "summary": "Elevated save and sweeper-keeper action count for the goalkeeper in the first fifteen minutes signals that the defensive structure is under early siege, providing a direct measure of early defensive pressure independent of outfield statistical proxies.",
        "stat_signature": "Goalkeeper saves or decisive sweeping actions before minute 16 averaging above 1.2 per match versus a per-15-minute match baseline of 0.6-0.8 marks high early involvement; high-claim count (aerial and cross-claiming actions) above 0.8 in the first fifteen indicates early delivery pressure; shot-stopping demand in the opening phase at twice the per-minute match norm is a high-pressure threshold.",
        "mechanism": "A keeper facing elevated early action volume is a downstream signal of opponent pressing success, first-phase defensive disorganisation, or aggressive opponent set-piece delivery; early saves under pressure before rhythm establishes are higher-risk technically than mid-match equivalents, slightly elevating chance-to-goal conversion.",
        "conditions": "High early involvement is correlated with high-press opponents and sides whose defensive block settles slowly; away keepers face higher early involvement in loud home environments where the opposition exploits crowd energy for aggressive opening sequences.",
        "magnitude": "Keepers recording over 1.5 actions in the first fifteen face a match save-total approximately 20-30% higher than those with below-average opening involvement; early goalkeeper involvement index above 1.5 standard deviations from team norm correlates with expected-goals-against above 0.15 in the opening phase.",
        "links": ["first_phase_defensive_compactness", "early_goal_conceded_susceptibility", "settling_into_block_timing", "early_transition_exposure"],
    },
    {
        "slug": "first_phase_momentum_carryover",
        "title": "First-Phase Momentum Carryover",
        "summary": "The match-result split between sides that win, draw, or lose the opening-fifteen expected-goals battle quantifies how predictive first-phase territorial and chance-creation dominance is of the eventual result, capturing the degree to which early momentum persists.",
        "stat_signature": "Sides winning the opening-fifteen expected-goals battle by 0.10 or more win the match approximately 52-58% of the time, compared to 38-44% for sides losing that opening exchange; result-correlation coefficient between first-fifteen expected-goals margin and final result ranges from 0.18-0.28 across top leagues — positive but not dominant.",
        "mechanism": "Psychological momentum from early dominance influences player confidence and tactical risk-taking in subsequent phases; an early goal from territorial dominance compresses opponent options in a manner that compounds through the match; however, game-state adaptations and second-half substitutions dilute the carryover significantly, explaining the moderate rather than strong correlation.",
        "conditions": "Carryover is strongest in matches without major half-time tactical adjustments; weakest when the dominant side concedes a sucker-punch counter goal that immediately resets game state; elevated in matches between evenly-matched sides where early pattern-setting has more informational value.",
        "magnitude": "Win-rate differential of 10-18 percentage points between first-phase winners and losers; expected-goals-margin carryover coefficient of 0.18-0.28 — meaningful but substantially diluted by 90-minute variance, substitution effects, and game-state management.",
        "links": ["opening_fifteen_goal_tendency", "early_lead_game_state_shift", "early_deficit_response_pattern", "early_tempo_imposition"],
    },
]
