"""Person-free NBA SubArchetypes concept nodes — dense, sport-accurate, no player/team names."""
from __future__ import annotations

SPORT = "NBA"
FAMILY = "SubArchetypes"

CONCEPTS: list[dict] = [
    {"slug": "pull_up_isolation_scorer", "title": "Pull-Up Isolation Scorer",
     "summary": "A lead-guard scoring sub-variant whose self-created offense flows through dribble pull-up jumpers out of one-on-one possessions, generating high shot volume with minimal playmaking assistance.",
     "stat_signature": "Assisted-FG share under 0.35; dribbles-per-touch above 4.5; isolation play-type frequency above 0.20 of half-court possessions; pull-up jumper share of total field goals above 0.40.",
     "mechanism": "Extended dribble sequences create separation via hesitation or step-back footwork, forcing the defender into a retreat or contest decision on each rep; the unassisted nature means scoring capacity is independent of teammate positioning.",
     "conditions": "Output concentrates in mid-clock half-court settings when pick-and-roll is unavailable; productivity declines against compact zone or two-man wall schemes that deny space for shot creation.",
     "magnitude": "Isolation PPP range 0.82-1.05 for this sub-type; pull-up jumper eFG% 0.44-0.54 indicating moderate efficiency with high self-creation cost, widening game-to-game scoring distribution by 4-7 points.",
     "links": ["pick_and_roll_ball_handler", "secondary_creation_wing", "connector_passing_wing", "transition_grab_and_go_guard"]},

    {"slug": "downhill_rim_pressure_guard", "title": "Downhill Rim-Pressure Guard",
     "summary": "A scoring-guard sub-variant who attacks the basket in straight-line drives, converting rim pressure into free-throw generation and interior attempts rather than pull-up scoring.",
     "stat_signature": "Drive frequency above 10 per 100 half-court possessions; rim-attempt share above 0.40 of total FGA; free-throw rate (FTA/FGA) above 0.35; field-goal attempts within 5 feet above 0.30 of total.",
     "mechanism": "Straight-line acceleration reduces the defender's lateral recovery window, forcing a foul or conceding a lay-up rather than allowing a contest; the two-revenue-stream nature (FTA plus rim FG%) makes efficiency resilient to night-to-night variance.",
     "conditions": "Thrives against drop-coverage schemes and mismatches against slower help defenders; attenuated by hard-hedge schemes and shot-blocking presence that raises contact cost before the finish.",
     "magnitude": "FTA-per-drive rate 0.20-0.30 for elite rim-pressers; rim FG% 0.62-0.70 before help collapses, generating 2-4 additional uncontested scoring events per game relative to perimeter-leaning guards.",
     "links": ["pull_up_isolation_scorer", "pick_and_roll_ball_handler", "vertical_spacing_lob_threat", "switchable_perimeter_stopper"]},

    {"slug": "off_screen_movement_scorer", "title": "Off-Screen Movement Scorer",
     "summary": "A shooting sub-variant who generates scoring by running off pin-downs, flares, and handoffs at speed rather than creating off the dribble, relying on catch-and-shoot rhythm.",
     "stat_signature": "Off-screen plus handoff play-type frequency above 0.25 combined; average touch time below 1.8 seconds; catch-and-shoot share of three-point attempts above 0.70; open or wide-open attempt rate above 0.55.",
     "mechanism": "Curling into a catch position forces the trailing defender to either fight through the screen or switch, with both responses creating a fraction-of-second shooting window; minimal dribbles preserve rhythm and elevate release-point consistency.",
     "conditions": "Effectiveness scales directly with screener quality and screen-setting positioning; productivity declines when the defense switches at speed and eliminates catch-and-shoot separation.",
     "magnitude": "Catch-and-shoot three eFG% 0.52-0.62 for elite movers, 8-12 pp above league average; off-screen PPP 1.05-1.18, among the highest half-court play-type efficiencies.",
     "links": ["spot_up_floor_spacer", "stretch_five_pop_big", "pick_and_roll_ball_handler", "connector_passing_wing"]},

    {"slug": "spot_up_floor_spacer", "title": "Spot-Up Floor Spacer",
     "summary": "A 3-and-D sub-variant who occupies corners and slots with minimal usage, widening driving lanes for initiators while providing a credible catch-and-shoot three threat from static positions.",
     "stat_signature": "Usage rate below 0.16; corner-three share of total three-point attempts above 0.35 (league average ~0.22); wide-open attempt share (defender 6+ feet) above 0.55; spot-up play-type above 0.50 of half-court appearances.",
     "mechanism": "Occupying the corner forces the defense to choose between helping on the drive and leaving a credible shooter unguarded; the static position concentrates scoring into maximally efficient catch-and-shoot attempts at the highest-value zone on the floor.",
     "conditions": "Gravity amplified in lineups with a credible rim-pressure initiator; diminished in five-out sets where multiple spacers reduce the per-shooter defensive attention required.",
     "magnitude": "Corner-three conversion rate 0.38-0.44 for established spacers; lineup net-rating premium with floor spacer on court versus off 2-5 pts/100 driven by driving-lane opening rather than direct scoring.",
     "links": ["off_screen_movement_scorer", "pick_and_roll_ball_handler", "two_way_play_finisher", "downhill_rim_pressure_guard"]},

    {"slug": "pick_and_roll_ball_handler", "title": "Pick-and-Roll Ball-Handler",
     "summary": "An initiator sub-variant who organises the offense through ball-screen possessions, reading the coverage to choose between downhill, pull-up, or kick-out outcomes on each repetition.",
     "stat_signature": "Pick-and-roll ball-handler play-type above 0.40 of half-court possessions; screen-assisted FGA or AST on 0.35-0.55 of total offensive contributions; points-per-direct-pick-and-roll-possession (DRPPP) above 0.90 marks above-average.",
     "mechanism": "Ball-screen action forces the coverage decision before the snap, converting the defender's commitment into a reads-based PPP advantage; the repetition frequency enables reading tendencies within a game and adjusting to the coverage offered.",
     "conditions": "Output sensitive to roll-man quality and screener gravity; attenuated by hedge-and-recover or ICE schemes that cut off the downhill option and force reset actions.",
     "magnitude": "Elite pick-and-roll ball-handlers generate DRPPP of 1.00-1.12; the play-type accounts for 35-55% of total offensive output in ball-screen-heavy schemes, making it the single highest-volume repeatable creation mechanism.",
     "links": ["pull_up_isolation_scorer", "vertical_spacing_lob_threat", "stretch_five_pop_big", "post_hub_passing_big"]},

    {"slug": "vertical_spacing_lob_threat", "title": "Vertical-Spacing Lob Threat",
     "summary": "A rim-running big sub-variant whose offensive value is gravity at the rim, finishing alley-oops and dump-offs while drawing the defense downward to open perimeter opportunities.",
     "stat_signature": "Assisted-FG share above 0.80; dunk plus alley-oop finish share above 0.40 of total made field goals; field-goal attempts within 6 feet above 0.70 of total; average catch distance from the basket below 4 feet.",
     "mechanism": "Consistent rim-run timing forces the help defender to choose between tagging the lob route and leaving the perimeter; when the tag is late the catch converts at 80-90% efficiency; when the tag is early the ball-handler gains an open driving lane.",
     "conditions": "Lob production tied to the ball-handler's ability to hold the edge and deliver above the backboard; threatened by physical switching bigs who neutralise the catch window and by drop schemes that contest the alley-oop approach.",
     "magnitude": "Rim FG% for this sub-type 0.68-0.78; lob-finish attempts generate approximately 1.5-1.7 expected points each, among the highest per-attempt values in the play-type catalog.",
     "links": ["pick_and_roll_ball_handler", "downhill_rim_pressure_guard", "stretch_five_pop_big", "post_hub_passing_big"]},

    {"slug": "stretch_five_pop_big", "title": "Stretch-Five Pop Big",
     "summary": "A stretch big sub-variant who pops beyond the arc after screen-setting rather than rolling, providing gravity that widens ball-screen PPP by threatening to convert open threes at center minutes.",
     "stat_signature": "Center-eligible minutes (positional classification) combined with three-point attempt rate above 5 per 100 possessions; pick-and-pop frequency above 0.35 of screen actions; three-point percentage above 0.33 to constitute a credible threat.",
     "mechanism": "A big who threatens the arc removes the weak-side helper from the paint, eliminating the automatic drop-tag that neutralises roll-man lob threats; the coverage dilemma shifts from rim-or-corner to rim-or-arc, compounding the ball-handler's options.",
     "conditions": "Value peaks in lineups pairing this role with a downhill ball-handler; degrades when the defense accepts the conceded corner three and loads the paint rather than following the pop.",
     "magnitude": "Lineups with a credible stretch-five show ball-handler-pick-and-roll PPP 0.05-0.12 above roll-man-only baselines; pop-attempt conversion at 35-40% from above the break is the threshold for defensive credibility.",
     "links": ["pick_and_roll_ball_handler", "off_screen_movement_scorer", "spot_up_floor_spacer", "vertical_spacing_lob_threat"]},

    {"slug": "post_hub_passing_big", "title": "Post-Hub Passing Big",
     "summary": "A playmaking big sub-variant who operates as an elbow or block offensive hub, distributing to cutters and shooters rather than finishing independently, with a passes-per-touch profile resembling a guard.",
     "stat_signature": "Frontcourt assist rate above 20%; post-up plus elbow-touch frequency above 0.30 of half-court appearances; passes-made-per-touch above 1.4; assist-to-turnover ratio above 2.5 in hub possessions.",
     "mechanism": "High-post and elbow catches elevate passing angles above the defense, enabling skip passes and lob deliveries that flat-floor point guards cannot generate; the hub position also draws double-teams that free shooters for catch-and-shoot opportunities.",
     "conditions": "Hub value highest in lineups with at least two off-ball cutters or shooters; attenuated when opponents concede the ball into the post and load help before the pass is delivered.",
     "magnitude": "Hub-big-facilitated shots convert at 1.10-1.20 PPP across catch types; frontcourt assist rate above 20% ranks in the 90th percentile for bigs and corresponds to 3-5 additional clean looks per game generated for teammates.",
     "links": ["low_post_interior_scorer", "vertical_spacing_lob_threat", "pick_and_roll_ball_handler", "connector_passing_wing"]},

    {"slug": "low_post_interior_scorer", "title": "Low-Post Interior Scorer",
     "summary": "An interior-scoring big sub-variant who generates offense with back-to-the-basket footwork and mismatch exploitation in the paint, operating almost exclusively below the free-throw line.",
     "stat_signature": "Post-up play-type above 0.30 of half-court possessions; paint-touch rate above 40% of total touches; three-point-attempt share below 0.10 of total FGA; post PPP range 0.88-1.02 depending on footwork quality.",
     "mechanism": "Back-to-basket positioning converts size and leverage mismatches into reliable mid-range or close-range finishes; repeated post catches force the defense into double-team decisions that feed shooters or proceed against a single defender.",
     "conditions": "Effective against undersized switches and opposing bigs without physical leverage; attenuated by perimeter-first defensive schemes that deny the entry pass and by long-armed rim-protection deterrents.",
     "magnitude": "Post-up shots convert at 0.46-0.54 FG% for skilled post scorers; generating 5-8 post touches per game produces 8-12 expected points and draws 2-4 free-throw attempts from defensive contact.",
     "links": ["post_hub_passing_big", "vertical_spacing_lob_threat", "offensive_rebounding_energy_big", "switchable_perimeter_stopper"]},

    {"slug": "switchable_perimeter_stopper", "title": "Switchable Perimeter Stopper",
     "summary": "A defensive sub-variant who guards across three or more positions without size or speed mismatch, enabling switch-heavy schemes that eliminate ball-screen coverage seams.",
     "stat_signature": "Matched-up position spread covering guard through forward in the same game; points-per-isolation-possession defended below 0.82; switch frequency above 25% of defensive ball-screen coverages assigned.",
     "mechanism": "Positional versatility allows the defense to switch every ball-screen without exposing a weak-side mismatch; eliminating the coverage gap removes the ball-handler's pre-snap read advantage and forces the offense into less efficient action.",
     "conditions": "Value peaks in playoff half-court battles where opponents isolate mismatches repeatedly; attenuated against size extremes where even lateral quickness cannot compensate for a 4-inch or 50-pound disadvantage.",
     "magnitude": "Switch-eligible defensive lineups concede 0.04-0.08 lower PPP on ball-screen possessions versus drop-coverage baselines; stopper-grade isolation PPP allowed of 0.78-0.85 ranks top-quartile across the league.",
     "links": ["rim_protecting_drop_anchor", "point_of_attack_pest", "two_way_play_finisher", "small_ball_five"]},

    {"slug": "rim_protecting_drop_anchor", "title": "Rim-Protecting Drop Anchor",
     "summary": "A defensive anchor sub-variant who guards ball-screens in deep drop, challenging rim attempts from paint presence rather than hedging, and suppressing opponent FG% within 6 feet.",
     "stat_signature": "Block rate above 4% of opponent field-goal attempts; contested shots at rim above 4 per 36 minutes; opponent rim FG% allowed below 0.60 (league average 0.62-0.66); drop-coverage assignment frequency above 60% of ball-screen coverages.",
     "mechanism": "Stationing the big inside the key deters drives before they reach the rim and challenges shots at the highest-value zone; the block threat displaces opponent shot selection to longer or more contested alternatives even when no block is recorded.",
     "conditions": "Drop scheme optimal against ball-handlers with limited pull-up three capacity; stressed by stretch-five pick-and-pop actions that pull the anchor out of the paint and expose the mid-range zone.",
     "magnitude": "Elite rim anchors reduce opponent paint PPP by 0.06-0.12; block rate above 4% contributes an estimated 2-4 prevented made field goals per 36 minutes through the deterrence effect alone.",
     "links": ["switchable_perimeter_stopper", "paint_protection_deterrence", "stretch_five_pop_big", "vertical_spacing_lob_threat"]},

    {"slug": "point_of_attack_pest", "title": "Point-of-Attack Pest",
     "summary": "A defensive sub-variant who pressures primary ball-handlers before the half-court set, accumulating deflections and steals through high-intensity denial and active hand positioning.",
     "stat_signature": "Deflections above 3.5 per 36 minutes; steal rate above 2.2% of opponent possessions guarded; matchup rate against opposing primary ball-handlers above 0.45 of total defensive assignments.",
     "mechanism": "Constant pressure on the initiator raises the cost of every dribble entry, forcing earlier ball-movement than the offense prefers and generating live-ball turnovers that seed transition at the highest-PPP possession type.",
     "conditions": "Most productive against initiators who hold the ball long and prefer late-clock isolation; attenuated when the offense uses quick-decision handlers who release within 2 seconds and avoid the pest's active hands.",
     "magnitude": "Top-quartile deflection-rate defenders generate 0.8-1.4 additional steal-equivalent possessions per game; opponent half-court initiation time shortens by 1.5-3.0 seconds per possession against elite pests.",
     "links": ["switchable_perimeter_stopper", "transition_grab_and_go_guard", "connector_passing_wing", "rim_protecting_drop_anchor"]},

    {"slug": "connector_passing_wing", "title": "Connector Passing Wing",
     "summary": "A low-usage role-player sub-variant who keeps ball movement fluid without dominating possessions, generating clean looks for others through quick short-touch passes and spacing discipline.",
     "stat_signature": "Assist-to-usage ratio above 1.2; turnover rate below 8% of possessions used; average touch time below 2.0 seconds; pass-ratio (passes made per touch) above 2.5.",
     "mechanism": "Sub-2-second ball movement prevents the defense from loading help on the connector's catch, maintaining the offensive flow patterns that create open looks down the sequence; very low turnover rates preserve possession for higher-usage creators.",
     "conditions": "Connector value highest in ball-movement offenses with multiple initiators; diminished in isolation-heavy sets where the connector rarely receives purposeful entry passes.",
     "magnitude": "Lineups with high-assist-ratio connectors show 3-5 pp higher team eFG% on possession sequences where the connector touches the ball; turnover suppression saves approximately 1.5-2.5 possessions per game.",
     "links": ["secondary_creation_wing", "post_hub_passing_big", "two_way_play_finisher", "spot_up_floor_spacer"]},

    {"slug": "secondary_creation_wing", "title": "Secondary Creation Wing",
     "summary": "A versatile forward sub-variant who operates as a second initiator beside a lead guard, blending playmaking, pull-up scoring, and spot-up shooting at moderate usage.",
     "stat_signature": "Usage rate 0.18-0.24; assist rate above 18% of possessions used; balanced play-type mix with pick-and-roll handler and spot-up each comprising 0.15-0.25 of actions; on/off net-rating split above +3 pts/100.",
     "mechanism": "Secondary creation relieves the primary ball-handler from possessing the ball on every action, preserving energy and creating coverage uncertainty for the defense; the blend of two-man game and off-ball threats defies single-coverage solutions.",
     "conditions": "Value amplified in lineups where the primary handler attracts heavy defensive attention; less distinctive in even-shared-ball systems where every player initiates equally.",
     "magnitude": "Second-unit initiation periods driven by this sub-type average 0.04-0.08 higher PPP than non-creation wing lineups; secondary-creator assist rate above 18% corresponds to 3-5 assisted baskets per 36 minutes for teammates.",
     "links": ["connector_passing_wing", "pull_up_isolation_scorer", "pick_and_roll_ball_handler", "two_way_play_finisher"]},

    {"slug": "transition_grab_and_go_guard", "title": "Transition Grab-and-Go Guard",
     "summary": "An initiator sub-variant who pushes pace immediately off defensive rebounds, converting stops into early-clock advantages before the defense can retreat and set assignments.",
     "stat_signature": "Transition frequency above 0.22 of offensive possessions; personal defensive-rebound-to-outlet rate above 0.55; transition points per game above 5.5 generated directly; fast-break frequency 1.5x or more above team baseline without this player.",
     "mechanism": "Initiating within 2 seconds of a rebound deny the opponent the coverage-assignment window; the numerical mismatch created before the defense retreats converts into rim attempts and open threes at transition-premium PPP of 1.10-1.22.",
     "conditions": "Output concentrated in the first 4 seconds post-rebound; productivity declines against disciplined retreating defenses that rotate goal-side and eliminate numerical advantage before the first screen.",
     "magnitude": "Transition-initiated possessions average 0.12-0.20 higher PPP than equivalent half-court actions; a grab-and-go guard generating 0.22 transition-frequency rate produces 3-5 additional premium-value possessions per 48 minutes.",
     "links": ["point_of_attack_pest", "pull_up_isolation_scorer", "pick_and_roll_ball_handler", "downhill_rim_pressure_guard"]},

    {"slug": "offensive_rebounding_energy_big", "title": "Offensive-Rebounding Energy Big",
     "summary": "A rebounding big sub-variant whose primary offensive contribution is second-chance creation from persistent glass-crashing, converting missed shots into live-ball continuations.",
     "stat_signature": "Offensive rebound rate above 12%; putback-attempt share above 0.35 of total FGA; assisted-FG share above 0.75; self-created pull-up share below 0.10 of total field goals.",
     "mechanism": "Relentless offensive crash positioning converts 30-35% of team misses into second-possession opportunities; putback proximity (average catch within 4 feet) generates attempts at 0.62-0.70 FG% without shot-clock or defensive-set requirements.",
     "conditions": "Crashing value highest against non-boxing defensive schemes and short defensive lineups; attenuated by dedicated back-to-the-basket box-out assignments that physically remove the crasher from rebound positioning.",
     "magnitude": "OREB rate above 12% produces 3-5 second-chance possessions per 36 minutes; each additional 3 pp of OREB rate corresponds to approximately 1.8 additional second-chance points per game.",
     "links": ["low_post_interior_scorer", "vertical_spacing_lob_threat", "post_hub_passing_big", "two_way_play_finisher"]},

    {"slug": "small_ball_five", "title": "Small-Ball Five",
     "summary": "A frontcourt sub-variant who occupies the center position at below-median height for that role, enabling switch-heavy defense and perimeter-leaning offense at the cost of interior size.",
     "stat_signature": "Center-eligible minutes at height below the positional median; switch frequency above 30% of defensive ball-screen coverages; three-point-attempt rate above 3 per 100 possessions; rim-FGA share below 0.30 of total.",
     "mechanism": "Undersized center placement removes the deep-drop anchor, converting the defense to a switch-everything scheme that neutralises ball-screen coverage seams; the perimeter capability simultaneously prevents the offense from being auto-tagged on three-point gravity.",
     "conditions": "Optimal in lineups with multiple shot-blockers unavailable and against ball-screen-heavy offenses; vulnerable to interior physical exploitation by traditional post scorers and offensive rebounders who overwhelm size gaps.",
     "magnitude": "Small-ball lineups generate 0.04-0.09 higher ball-screen defensive PPP allowed but reduce opponent post-up attempts by 30-45%; net rating impact ranges from -3 to +6 pts/100 depending on opponent offensive profile.",
     "links": ["switchable_perimeter_stopper", "stretch_five_pop_big", "two_way_play_finisher", "rim_protecting_drop_anchor"]},

    {"slug": "two_way_play_finisher", "title": "Two-Way Play-Finisher",
     "summary": "A role-player sub-variant who completes offensive actions without self-creation and defends multiple positions, contributing clean finishing and defensive versatility at minimal ball-possession cost.",
     "stat_signature": "Assisted-FG share above 0.78; positive on-court defensive net-rating split above +2 pts/100; dribbles-per-touch below 1.5; positional-matchup spread covering at least two adjacent positions on defense.",
     "mechanism": "High assisted-FG rates concentrate shot selection in catch-only situations near the rim or open corners, maximising eFG% without requiring creation possessions; defensive versatility reduces the coverage cost of including a non-creating finisher.",
     "conditions": "Value peaks in lineups with two or more creation-capable players who need a finisher-without-ball-stopping role; attenuated when the offense requires the finisher to self-create in half-court.",
     "magnitude": "Two-way finisher on-off impact ranges +2 to +5 net-rating pts/100 in high-creation lineups; catch-only eFG% for this sub-type 0.58-0.67, among the highest role-player finishing profiles in the league.",
     "links": ["connector_passing_wing", "switchable_perimeter_stopper", "spot_up_floor_spacer", "secondary_creation_wing"]},
]
