"""Soccer SubArchetypes concept-node spec for the brain builder."""
SPORT = "Soccer"
FAMILY = "SubArchetypes"

CONCEPTS = [
    {
        "slug": "high_press_gegenpress_unit",
        "title": "High-Press Counterpressing Unit",
        "summary": "A team sub-variant that wins the ball high and immediately after losing it, converting advanced turnovers into short-distance scoring chances through collective swarming.",
        "stat_signature": "PPDA <=7; attacking-third ball-recovery share >=35% of all recoveries; high-regain-to-shot rate >=30%; five-second recovery rate >=42% of all losses.",
        "mechanism": "Swarming around the ball immediately after losing possession catches the opponent disorganized; proximity to the opponent goal means recovery xG is structurally elevated versus mid-block turnovers.",
        "conditions": "Most destructive against short-build possession sides; degrades late in matches when collective fitness drops and direct opponents bypass the press with long balls over the defensive line.",
        "magnitude": "High-press units with PPDA <=7 generate 0.20-0.30 additional xG per 90 from press sequences; high-regain shots average xG per shot 0.15-0.22, roughly 50% above the open-play mean.",
        "links": ["deep_block_counter_attacking_unit", "set_piece_dependent_attack", "transition_vulnerable_high_line", "high_press_block"],
    },
    {
        "slug": "deep_block_counter_attacking_unit",
        "title": "Deep-Block Counter-Attacking Unit",
        "summary": "A team sub-variant that defends compactly in its own half and breaks at speed into space, concentrating xG output in low-volume, high-probability fast-break sequences.",
        "stat_signature": "Possession share <=40%; direct-attack sequence share >=40% of all offensive sequences; transition xG per fast-break >=0.14; defensive-line height <=28 m from own goal.",
        "mechanism": "Deep compactness removes high-xG central entries, forcing peripheral shots; rapid vertical breaks exploit temporary defensive imbalances in opponents committed high, producing low-count but high-value chances.",
        "conditions": "Effective against high-possession, high-line opponents with space behind the defensive line; less productive against well-organized compact defenses that match the depth and deny transition space.",
        "magnitude": "Counter-attacking units generate 45-60% of their xG from transition sequences averaging <=4 passes; transition shots reach the final third within 8 seconds of regain at 55-65% rates.",
        "links": ["high_press_gegenpress_unit", "possession_positional_play_unit", "transition_vulnerable_high_line", "counter_attack_transition_offense"],
    },
    {
        "slug": "possession_positional_play_unit",
        "title": "Possession Positional-Play Unit",
        "summary": "A team sub-variant that controls the ball through structured zone occupation and half-space combinations, building sustained positional superiority before committing to final-third actions.",
        "stat_signature": "Possession share >=58%; short-pass completion rate >=86%; central-and-half-space attack share >=55% of offensive sequences; progressive passes between lines >=13 per 90.",
        "mechanism": "Structured zone occupation forces the opponent to compress or stretch, creating pockets between the lines; third-man combinations produce local numerical overloads while global shape is maintained.",
        "conditions": "Effective against mid and low blocks with exploitable half-space gaps; less decisive against high-press sides that disrupt the circulation phase before positional superiority forms.",
        "magnitude": "Teams with possession above 58% and zone-occupation index >=0.75 average 1.4-1.7 xG from open play per 90, versus 0.9-1.1 for unstructured possession sides at equivalent share.",
        "links": ["deep_block_counter_attacking_unit", "ball_playing_deep_lying_playmaker", "advanced_creative_number_ten", "positional_play_juego_de_posicion"],
    },
    {
        "slug": "wide_overload_crossing_unit",
        "title": "Wide-Overload Crossing Unit",
        "summary": "A team sub-variant that manufactures chances from the flanks through high cross volume, byline delivery, and box targets capable of winning aerial duels or finishing cutbacks.",
        "stat_signature": "Cross volume >=20 per 90; wide-zone attacking-third touch share >=50%; headed-shot share >=25% of total shots; byline-entry rate >=4.5 per 90.",
        "mechanism": "Flank overloads stretch the defensive block horizontally, opening central gaps for late runners; byline deliveries arrive at angles that compress goalkeeper-defender positioning simultaneously.",
        "conditions": "Effective against narrow or man-oriented defenses that struggle to track overlapping runners and central targets simultaneously; less productive against wide-dedicated defensive schemes maintaining horizontal spacing.",
        "magnitude": "Byline crosses produce xG per shot 0.09-0.13 versus 0.04-0.07 for wide-area crosses; overload frequency above six per 90 correlates with 15-20% more byline entries per 90.",
        "links": ["overlapping_attacking_fullback_role", "target_forward_hold_up_role", "set_piece_dependent_attack", "wing_play_overlap_crossing"],
    },
    {
        "slug": "false_nine_central_rotation_role",
        "title": "False-Nine Central Rotation",
        "summary": "A forward role sub-variant who vacates the center-forward line to overload midfield, drawing center-backs forward and creating third-man runs for arriving midfielders into vacated central space.",
        "stat_signature": "Center-forward nominal position with average action height <=38 m from opponent goal; passes received between the lines >=4 per 90; key passes per 90 above team-forward baseline >=1.5; shots per 90 <=2.5.",
        "mechanism": "Dropping deep drags center-backs into uncomfortable decision zones; the vacated striker space is exploited by arriving midfield runners who receive in positions the center-back has abandoned.",
        "conditions": "Most effective against rigid man-marking center-backs who follow the role-holder into midfield; less disruptive against zonal defenses comfortable sitting and allowing the drop.",
        "magnitude": "Teams deploying this role generate 15-25% more central box entries per 90 from midfield runners than conventional center-forward setups at equivalent possession share.",
        "links": ["possession_positional_play_unit", "advanced_creative_number_ten", "box_to_box_progressive_carrier", "half_space_inverted_attack"],
    },
    {
        "slug": "inverted_winger_cut_inside_role",
        "title": "Inverted-Winger Cut-Inside",
        "summary": "A wide-attacker role sub-variant who starts wide to pin the full-back then drives centrally into half-space shooting lanes, contributing both high-volume shots and through-ball creation.",
        "stat_signature": "Wide starting touch cluster collapsing into central shooting locations; strong-foot bias opposite the assigned flank >=70% of shots; half-space shot share >=35%; shots per 90 >=3.0.",
        "mechanism": "Starting wide draws the full-back out, creating a central corridor; cutting onto the strong foot produces a better-angled shot than the outside-foot alternative and disorganizes the inside shoulder of the defending center-back.",
        "conditions": "Most effective when the opposing full-back tracks tightly into wide areas; less productive when a midfielder drops to cover the half-space, removing the cutting lane.",
        "magnitude": "Half-space shots from inverted-winger roles average xG per shot 0.13-0.17, roughly 30-50% above the open-play mean; volume of >=3 shots per 90 compounds into 0.35-0.50 xG per 90 for elite half-space cutters.",
        "links": ["false_nine_central_rotation_role", "overlapping_attacking_fullback_role", "inverted_fullback_midfield_role", "half_space_inverted_attack"],
    },
    {
        "slug": "ball_playing_deep_lying_playmaker",
        "title": "Ball-Playing Deep-Lying Playmaker",
        "summary": "A central-midfield role sub-variant who dictates tempo from a deep position, distributing progressive and line-breaking passes that initiate attacking sequences from a shielded base.",
        "stat_signature": "Highest pass volume on the team >=70 per 90; progressive passes per 90 >=8; line-breaking passes per 90 >=4; position-action height >=5 m lower than other central midfielders.",
        "mechanism": "Positioning deep provides clean ball reception away from press; the wide passing angle from a low-block position opens long-diagonal options to both flanks while line-breaking passes through channels are the primary chance-creation mechanism.",
        "conditions": "Most impactful against teams pressing high with two forwards, which leaves space for the deep receiver; limited by opponents deploying a high-intensity midfielder assigned to deny the receiver.",
        "magnitude": "Deep playmakers threading >=4 line-breaking passes per 90 correlate with 0.20-0.30 more xG per 90 for their teams than possession equivalents relying on lateral recycling.",
        "links": ["possession_positional_play_unit", "box_to_box_progressive_carrier", "ball_playing_progressive_center_back", "build_up_from_the_back"],
    },
    {
        "slug": "box_to_box_progressive_carrier",
        "title": "Box-to-Box Progressive Carrier",
        "summary": "A midfield role sub-variant who advances play through progressive dribbling across both halves, contributing defensive recoveries in their own half and final-third entries from carrying runs.",
        "stat_signature": "Progressive carry distance >=250 m per 90; ball recoveries in own half >=4 per 90 and final-third entries via carry >=3 per 90; balanced split with defensive actions >=4 and final-third carries >=3 per 90.",
        "mechanism": "Carrying through congested midfield bypasses press-resistant ball-circulation requirements; the dual contribution compresses the opponent block by drawing defenders out of shape on carrying runs.",
        "conditions": "Most effective in transitional moments when midfield space opens after a turnover; less efficient against deep-block opponents that remove carrying space and allow the ball to be recycled sideways.",
        "magnitude": "Progressive carries producing final-third entries generate shots at roughly twice the rate of pass-only progressions in equivalent field positions; per-90 entry rate above 3 correlates with 0.15-0.20 additional xG.",
        "links": ["ball_playing_deep_lying_playmaker", "false_nine_central_rotation_role", "high_press_gegenpress_unit", "advanced_creative_number_ten"],
    },
    {
        "slug": "advanced_creative_number_ten",
        "title": "Advanced Creative Playmaker",
        "summary": "An attacking-midfield role sub-variant who operates in the zone immediately outside the penalty area to create high-probability final passes and shoot from distance when the defense compresses.",
        "stat_signature": "Expected assists per 90 >=0.25; key passes per 90 >=2.5 above team-average forward; touch concentration in the zone 18-25 m from goal >=40% of all touches; shots per 90 >=1.5 from outside the area.",
        "mechanism": "Occupying the space between midfield and the striker forces a choice between tracking the creator or holding defensive structure; delayed runs into this zone are undetected by flat-block defenses.",
        "conditions": "Effective against defenses tracking wide threats and leaving the central zone between the lines underprotected; less productive against a two-line mid-block that assigns a midfielder to shadow the creative position.",
        "magnitude": "Creative hubs generating >=0.25 xA per 90 produce 15-25% more goal-scoring opportunities for teammates than equivalent ball-receiving forwards without the same creation profile.",
        "links": ["false_nine_central_rotation_role", "possession_positional_play_unit", "box_to_box_progressive_carrier", "third_man_combination_play"],
    },
    {
        "slug": "poacher_box_finisher_role",
        "title": "Poacher Box-Finisher",
        "summary": "A striker role sub-variant whose value is concentrated in finishing inside the penalty area with minimal build-up involvement, generating disproportionate xG per touch through high-probability positioning.",
        "stat_signature": "Box touch share >=65% of all touches; touches per shot <=6; xG per shot >=0.15 concentrated in central locations; shots per 90 >=2.8; non-area touch share <=35%.",
        "mechanism": "Remaining in or near the box continuously while teammates circulate ensures the striker is positioned for first-time finishes at the point of delivery; low non-box involvement preserves physical resources for explosive penalty-area movements.",
        "conditions": "Most effective in teams with high cross volume or wide-overload delivery patterns that create repetitive box-entry opportunities; limited by deep-block opponents who maintain central density and deny through-ball delivery.",
        "magnitude": "Box finishers with xG per shot >=0.15 convert at 18-25% versus 8-11% for peripheral shot takers; limited touch count outside the area concentrates their xG accumulation into the highest-value locations.",
        "links": ["wide_overload_crossing_unit", "target_forward_hold_up_role", "set_piece_dependent_attack", "attacking_set_piece_routines"],
    },
    {
        "slug": "target_forward_hold_up_role",
        "title": "Target-Forward Hold-Up",
        "summary": "A striker role sub-variant who anchors attacks with back-to-goal link play, winning aerial duels and layoff passes that relieve pressure and launch advancing teammates into higher-value positions.",
        "stat_signature": "Aerial duels per 90 >=5; layoff and link passes per 90 >=3.5; fouls won per 90 >=2.0; box touch share <=45% with a high proportion of deeper attacking-half receipts.",
        "mechanism": "Holding possession under pressure while teammates advance stretches the defensive block vertically; aerial contest wins from long balls in advanced areas establish possession in the final third without requiring midfield progression.",
        "conditions": "Effective against high-press defenses that push center-backs high, leaving aerial contest space; less productive against low-block defenses with compact central coverage that crowds out the link-play zone.",
        "magnitude": "Aerial-duel win rates above 55% generate second-ball recovery rates 15-20% above teams relying on ground-based hold-up; layoff pass frequency above 3.5 per 90 correlates with 12-18% more final-third entries from direct play.",
        "links": ["wide_overload_crossing_unit", "poacher_box_finisher_role", "direct_long_ball_target_unit", "direct_long_ball_progression"],
    },
    {
        "slug": "overlapping_attacking_fullback_role",
        "title": "Overlapping Attacking Full-Back",
        "summary": "A full-back role sub-variant who provides width and crossing platforms high up the flank, effectively functioning as an additional winger while the wide forward tucks inside.",
        "stat_signature": "Attacking-third touch share for a defensive role >=18 per 90; crosses per 90 >=3.5; progressive carries per 90 >=4; average defensive position >=45 m from own goal.",
        "mechanism": "High full-back positioning creates a simultaneous two-on-one on the flank while the inverted winger pulls central defenders inward, generating coordinated width overloads and central half-space pockets.",
        "conditions": "Effective when opponents track the wide attacker but undercommit resources to the overlapping defender; creates defensive vulnerability in behind when the full-back is caught high against a fast-transitioning side.",
        "magnitude": "Full-backs reaching the byline cross at 35-45% higher effective delivery rates than wide attacker crosses; attacking-third rates above 18 per 90 correlate with 12-18% more wide-overload situations per game.",
        "links": ["inverted_winger_cut_inside_role", "inverted_fullback_midfield_role", "wide_overload_crossing_unit", "overlapping_underlapping_fullbacks"],
    },
    {
        "slug": "inverted_fullback_midfield_role",
        "title": "Inverted Full-Back into Midfield",
        "summary": "A full-back role sub-variant who tucks centrally in the build-up phase to create a numerical overload at the base of midfield, enabling structured progression while an auxiliary winger provides width.",
        "stat_signature": "Central touch cluster during build-up phase; short-pass share >=78%; positional heat map narrower than 20 m from central axis during own-half possession; progressive passes per 90 >=5 for a defensive role.",
        "mechanism": "Vacating the wide build-up lane forces the opponent into an asymmetric press that either covers the central overload or the overlapping winger, rarely both; numerical superiority at the midfield base creates press-resistant circulation.",
        "conditions": "Effective in possession-based systems with a winger capable of providing width without full-back support; requires a teammate structure that reliably provides the wide outlet abandoned by the tucking full-back.",
        "magnitude": "Inverted full-back central involvement reduces press success rates against the build-up phase by 15-25% when three-versus-two overloads are established at midfield base.",
        "links": ["overlapping_attacking_fullback_role", "possession_positional_play_unit", "ball_playing_deep_lying_playmaker", "positional_play_juego_de_posicion"],
    },
    {
        "slug": "ball_playing_progressive_center_back",
        "title": "Ball-Playing Progressive Center-Back",
        "summary": "A central-defender role sub-variant who initiates attacks from the back with progressive distribution, stepping into midfield when the press is bypassed to generate an extra-man build-up overload.",
        "stat_signature": "Pass volume >=65 per 90 for a defensive role; progressive passes per 90 >=6; line-breaking passes per 90 >=2.5; build-up involvement share >=40% of own-half progressions.",
        "mechanism": "Distribution from the defensive third opens vertical channels before the opponent press engages; stepping into midfield with the ball stretches the press structure, creating space for the receiving midfielder.",
        "conditions": "Most effective in teams that invite the press and play through it with short-build structures; limits arise when the opposition commits a forward to shadow the distributing center-back during set build-up patterns.",
        "magnitude": "Center-backs threading >=2.5 line-breaking passes per 90 contribute 0.15-0.25 more progressive sequences per 90 than distribution-passive defenders at equivalent build-up possession share.",
        "links": ["ball_playing_deep_lying_playmaker", "possession_positional_play_unit", "inverted_fullback_midfield_role", "build_up_from_the_back"],
    },
    {
        "slug": "sweeper_keeper_distribution_role",
        "title": "Sweeper-Keeper Distributor",
        "summary": "A goalkeeper role sub-variant who acts as an extra outfield passer in the build-up and defends space behind a high defensive line, extending the team's structure and enabling aggressive line-stepping.",
        "stat_signature": "Outfield pass volume >=40 per 90 with long-pass completion >=55%; defensive actions outside the penalty area >=1.5 per 90; average sweeper distance >=8 m from goal line; short goal-kick rate >=65%.",
        "mechanism": "Functioning as an outfield player during build-up creates a numerical overload against the press without committing an outfield player into deep positions; covering space behind the high line requires anticipatory reading of through-ball trajectories.",
        "conditions": "Effective in possession systems where the goalkeeper is a reliable distributor; exposure increases when opponents play direct balls behind the high line to test the sweeping range and decision-making speed.",
        "magnitude": "Teams with sweeper-keepers averaging >=8 m sweeper distance suppress xG from balls played behind the defensive line by 20-30% relative to deep-staying goalkeepers in equivalent high-line systems.",
        "links": ["ball_playing_progressive_center_back", "possession_positional_play_unit", "transition_vulnerable_high_line", "offside_trap_high_line"],
    },
    {
        "slug": "set_piece_dependent_attack",
        "title": "Set-Piece-Dependent Attack",
        "summary": "A team-scoring sub-variant that derives an outsized share of goals from dead-ball situations, concentrated in aerial threat from corners and free kicks rather than open-play combination patterns.",
        "stat_signature": "Set-piece goal share >=35% of all goals; set-piece xG per 90 >=0.35; aerial-duel win rate at corners >=58%; open-play xG per 90 <=0.90 below the league median.",
        "mechanism": "Purposeful set-piece routines using blocking and screening runs generate first-contact opportunities at the point of delivery; concentrating tall aerial targets exploits zonal defenders' timing vulnerabilities at near and far posts.",
        "conditions": "Effective against zonal-marking defensive schemes with fixed positional assignments; impact is diluted by teams with man-marking switches that track aerial threats through blocking patterns.",
        "magnitude": "Elite set-piece attacking units generate 0.30-0.45 xG from dead balls per 90, representing 25-40% of total xG for sides where open-play creation is structurally below the league midpoint.",
        "links": ["poacher_box_finisher_role", "target_forward_hold_up_role", "wide_overload_crossing_unit", "attacking_set_piece_routines"],
    },
    {
        "slug": "transition_vulnerable_high_line",
        "title": "Transition-Vulnerable High Line",
        "summary": "A high-risk defensive sub-variant whose aggressively elevated back line concedes high-xG chances in behind from fast breaks and through balls when the press is bypassed.",
        "stat_signature": "Defensive line height >=52 m from own goal; shots conceded from fast-break sequences >=2.5 per 90; xG conceded from balls played behind the line >=0.35 per 90; successful through-ball rate allowed >=1.8 per 90.",
        "mechanism": "Stepping the line high compresses the midfield-to-defense gap and activates offside traps, but a single penetrating pass or press bypass opens a vast channel between the line and the goalkeeper that defenders cannot recover.",
        "conditions": "Exposure maximized against opponents with direct long-ball tendencies, timed depth runners, or a sweeper-keeper to minimize the through-ball risk; most vulnerable when collective line-stepping synchronization breaks under fatigue.",
        "magnitude": "High-line sides allowing >=1.8 successful through-balls per 90 concede 0.30-0.45 xG per 90 from transition chances behind the line; this often represents 30-50% of total xGA from open play.",
        "links": ["high_press_gegenpress_unit", "sweeper_keeper_distribution_role", "deep_block_counter_attacking_unit", "offside_trap_high_line"],
    },
]
