"""Soccer Tactics concept-node spec for the brain builder."""
SPORT = "Soccer"
FAMILY = "Tactics"

CONCEPTS = [
    {
        "slug": "high_press_block",
        "title": "High Press and Front-Foot Block",
        "summary": "The defending team engages high up the pitch to win the ball near the opposition goal, compressing the field and generating transition chances from advanced turnovers.",
        "stat_signature": "PPDA <=8 passes per defensive action; >=4 high-turnover recoveries per 90 in the final third; defensive-line height >=50 m from own goal; shot-after-high-recovery rate >=30%.",
        "mechanism": "Pressing high shortens the distance from turnover to the opponent's goal, converting defensive moments into high-value chances while denying time to organize a structured attack.",
        "conditions": "Most effective against short-build possession sides; degrades when opponents play long balls over the press into vacated space behind the defensive line.",
        "magnitude": "Teams with PPDA <=8 concede open-play shots 25-35% below median; high-recovery shots carry average xG roughly 0.15-0.18, above the open-play league mean.",
        "links": ["counter_press_gegenpress", "offside_trap_high_line", "pressing_traps_wide_zones", "build_up_from_the_back"],
    },
    {
        "slug": "mid_block_compact_defense",
        "title": "Mid-Block Compact Defending",
        "summary": "The defensive line sits around the halfway zone, sealing central lanes and forcing wide play to limit high-xG central entries.",
        "stat_signature": "Line height 35-45 m from own goal; zone-14 pass-completion allowed <=40%; PPDA 10-16; wide-corridor ball-receipt share >=55% of opponent final-third touches.",
        "mechanism": "Compacting central space denies through-ball and combination-play opportunities between the lines; opponents are funneled wide where crossing is lower-percentage than central access.",
        "conditions": "Suited to protecting narrow leads against possession-dominant sides; vulnerable when the opponent has elite crossing delivery quality that exploits volume.",
        "magnitude": "Zone-14 touch denial reduces opponent shot conversion roughly 20-30% relative to unrestricted central access; mid-block sides concede 15-20% fewer central shots per 90.",
        "links": ["low_block_deep_defense", "zonal_marking_set_structure", "wing_play_overlap_crossing", "positional_play_juego_de_posicion"],
    },
    {
        "slug": "low_block_deep_defense",
        "title": "Low-Block Deep Defending",
        "summary": "Defenders pack the penalty area to deny space in behind and force opponents into low-frequency long-range or wide-entry solutions.",
        "stat_signature": "Line height <=30 m from own goal; opponent box-entry rate conceded <=8 per 90; shots conceded outside the area >=45%; opponent xG per shot conceded <=0.10.",
        "mechanism": "Flooding the penalty area removes interior passing lanes and shooting corridors, forcing low-probability distance shots or crowded cutback combinations.",
        "conditions": "Deployed against technically superior opponents; effectiveness drops against elite set-piece delivery or wide play that stretches the compact block before crossing.",
        "magnitude": "Low-block sides concede <=0.80 xGA from open play per 90 on average; counter-attacking xG output is typically <=0.40 per 90 when the block holds shape.",
        "links": ["mid_block_compact_defense", "zonal_marking_set_structure", "counter_attack_transition_offense", "defensive_set_piece_organization"],
    },
    {
        "slug": "pressing_traps_wide_zones",
        "title": "Pressing Traps and Wide-Zone Engagement",
        "summary": "The press deliberately invites passes into pre-chosen wide zones to trigger a coordinated trap, cutting off escape routes and forcing turnovers or backward clearances.",
        "stat_signature": "Trap-trigger frequency >=5 per 90; touchline-recovery rate >=60% of traps converted to possession; turnovers in preset zones >=3 per 90; opponent long-ball rate rises >=20% against the shape.",
        "mechanism": "Shaping the press to funnel the ball to a specific zone allows the team to overload that area before the opponent can play out, cutting off forward and backward options simultaneously.",
        "conditions": "Requires coordinated team movement and clear triggers; most effective against short-build sides; breaks down against teams with a rehearsed long-ball escape route.",
        "magnitude": "Effective trapping schemes recover possession within three seconds in roughly 55-65% of traps; touchline proximity increases turnover frequency 25-40% above central pressing.",
        "links": ["high_press_block", "counter_press_gegenpress", "man_oriented_marking", "build_up_from_the_back"],
    },
    {
        "slug": "counter_press_gegenpress",
        "title": "Counter-Press on Turnover",
        "summary": "Immediately after losing possession the team swarms the ball to win it back within seconds before the opponent can organize a structured counter-attack.",
        "stat_signature": "Ball recoveries within five seconds of loss >=40% of all losses; counter-attacks conceded when press is broken <=2 per 90; recoveries in the opposition half >=6 per 90.",
        "mechanism": "The opponent is most disorganized immediately after winning the ball; immediate coordinated pressure forces rushed touches or back-passes, recovering possession higher up the pitch.",
        "conditions": "Most productive with high collective fitness; degrades in the final 15 minutes or against direct opponents who bypass the immediate press with long balls.",
        "magnitude": "Teams with >=40% five-second recovery rates create roughly 20-30% more high-value chances per 90 from counter-press sequences.",
        "links": ["high_press_block", "pressing_traps_wide_zones", "offside_trap_high_line", "counter_attack_transition_offense"],
    },
    {
        "slug": "offside_trap_high_line",
        "title": "High Defensive Line and Offside Trap",
        "summary": "A coordinated stepped-up back line exploits the offside rule to compress space, nullify runs in behind, and force aerial long-ball solutions.",
        "stat_signature": "Offsides forced >=4 per 90; line height >=52 m from own goal; through-balls successfully played behind the line <=1.5 per 90; recovery sprints from high-line breaks >=2.0 per 90.",
        "mechanism": "Stepping up as a unit removes the attacking team's primary direct threat and shortens the pitch, increasing compactness between defensive and midfield lines.",
        "conditions": "Requires elite defensive-line synchronization; most vulnerable against opponents with precise depth-run timing or when the offside assistant is poorly positioned.",
        "magnitude": "Effectively applied high lines reduce xG from balls played in behind by 30-40%; xG vulnerability from direct deliveries rises roughly 15-20% as a trade-off.",
        "links": ["high_press_block", "counter_press_gegenpress", "mid_block_compact_defense", "man_oriented_marking"],
    },
    {
        "slug": "man_oriented_marking",
        "title": "Man-Oriented Marking Scheme",
        "summary": "Defenders track individual opponents across zones to deny time on the ball rather than holding fixed positions.",
        "stat_signature": "Marking-pickup rate >=85% of identified triggers; duel volume >=18 per 90 team-wide; space conceded when marks are dragged out of shape >=15 m per displacement event.",
        "mechanism": "Persistent man-marking denies opponents comfortable touches and passing rhythms; the defending team neutralizes the opponent's key distributers at the cost of positional shape.",
        "conditions": "Most effective when opponents rely on specific individuals to initiate play; degrades against fluid rotation and third-man combinations that pull markers into disorganized positions.",
        "magnitude": "Man-oriented sides force 20-30% more turnovers per 90 in contested midfield zones but concede 15-25% more space in vacated areas when marks drag defenders wide.",
        "links": ["zonal_marking_set_structure", "pressing_traps_wide_zones", "offside_trap_high_line", "defensive_set_piece_organization"],
    },
    {
        "slug": "zonal_marking_set_structure",
        "title": "Zonal Defending Structure",
        "summary": "Defenders protect areas and pass opponents between zones, maintaining collective shape over individual tracking.",
        "stat_signature": "Zonal-line integrity score >=0.80 (shape retained after rotation); opponent progression-through-zone rate <=35%; shape-retention rate under opposition rotation >=70%.",
        "mechanism": "Area responsibility maintains compactness and prevents defensive disorganization from drag runs; defenders pre-jump deliveries with optimal body positioning rather than reacting to runners.",
        "conditions": "Effective against teams with complex blocking and screening runs at set pieces; less reliable when opponents commit multiple runners to the same zone simultaneously.",
        "magnitude": "Zonal defending at set pieces reduces first-contact xG per delivery by roughly 0.015-0.025 versus pure man-marking against blocking-heavy routines.",
        "links": ["man_oriented_marking", "defensive_set_piece_organization", "mid_block_compact_defense", "low_block_deep_defense"],
    },
    {
        "slug": "positional_play_juego_de_posicion",
        "title": "Positional-Play Build-Up",
        "summary": "The team occupies pre-defined zones and half-spaces to achieve numerical and positional superiority through structured ball circulation before committing to final-third actions.",
        "stat_signature": "Zone-occupation balance index >=0.75; third-man-combination rate >=8 per 90; progressive passes between lines >=12 per 90; possession share in the middle third >=45%.",
        "mechanism": "Occupying specific zones forces the opponent to compress or stretch, creating pockets between or behind lines; structured rotations produce local numerical overloads while maintaining global balance.",
        "conditions": "Effective against passive mid or low blocks with half-space gaps; less decisive against organized high-press sides that deny the circulation phase before positional superiority forms.",
        "magnitude": "Teams with zone-occupation index >=0.75 average 1.3-1.6 xG from open play per 90 against 0.9-1.1 for unstructured possession sides; effect is concentrated in final-third entry quality.",
        "links": ["build_up_from_the_back", "half_space_inverted_attack", "third_man_combination_play", "overload_to_isolate_switch"],
    },
    {
        "slug": "build_up_from_the_back",
        "title": "Structured Build-Up From the Back",
        "summary": "Possession is constructed deliberately from the goalkeeper and center-backs to draw and beat the opposition press, creating midfield numerical advantages before progressing.",
        "stat_signature": "Short goal-kick rate >=70%; build-up pass completion under pressure >=78%; press-resistant progressions into midfield >=8 per 90; goalkeeper outfield pass completion >=70%.",
        "mechanism": "Inviting and playing through the press disorganizes the opponent block and opens channels between the lines; successful back-line progressions produce higher-quality midfield entries than long balls.",
        "conditions": "Most productive against high-press sides with space in behind; becomes a liability when the press is executed efficiently and interceptions in the defensive third create high-xG chances.",
        "magnitude": "Teams successfully building from the back generate 15-25% more progressive carries into the final third per 90; error rate averages 1.2-1.8 own-half turnovers per 90 under pressure.",
        "links": ["positional_play_juego_de_posicion", "direct_long_ball_progression", "high_press_block", "pressing_traps_wide_zones"],
    },
    {
        "slug": "direct_long_ball_progression",
        "title": "Direct and Long-Ball Progression",
        "summary": "The team bypasses midfield with long forward passes to a hold-up target supported by a compact second-ball structure to progress quickly without constructing through midfield.",
        "stat_signature": "Long-pass share >=30% of all passes; forward-pass directness index >=0.65; aerial-duel-won rate >=52%; second-ball recovery rate >=45%; average sequence length <=4 passes.",
        "mechanism": "Long-ball play exploits space in behind high lines or compact mid-blocks by skipping contested midfield zones; second-ball battles in advanced areas allow quick possession establishment.",
        "conditions": "Effective against high-press and high-line defenses with space behind; degrades against deep-block sides with aerial-dominant center-backs and no space in behind.",
        "magnitude": "Direct-play sides generate 30-45% of open-play xG from long-ball or second-ball sequences; aerial-win-rate differences of 5% correlate with roughly 0.1 xG difference per 90.",
        "links": ["build_up_from_the_back", "wing_play_overlap_crossing", "counter_attack_transition_offense", "attacking_set_piece_routines"],
    },
    {
        "slug": "wing_play_overlap_crossing",
        "title": "Wing Overload and Crossing Attack",
        "summary": "Attacks channel wide with overlapping and underlapping runs to deliver crosses into the box, targeting aerial or cutback finishes.",
        "stat_signature": "Cross volume >=18 per 90; wide-overload frequency >=6 two-on-one situations per 90; byline-entry rate >=4 per 90; shots from crossed deliveries >=35% of total shots.",
        "mechanism": "Width forces the defensive block to stretch horizontally, opening central gaps for late runners; byline deliveries arrive at angles that defenders and goalkeepers struggle to read simultaneously.",
        "conditions": "Most effective against narrow or man-oriented defenses that struggle to track overlapping runners and central strikers simultaneously; less effective against wide-dedicated defensive schemes.",
        "magnitude": "Byline crosses produce xG per shot 0.08-0.12 versus 0.04-0.07 for wider crosses; overload frequency above six per 90 correlates with 15-20% more byline entries per game.",
        "links": ["half_space_inverted_attack", "overload_to_isolate_switch", "overlapping_underlapping_fullbacks", "attacking_set_piece_routines"],
    },
    {
        "slug": "half_space_inverted_attack",
        "title": "Half-Space and Inverted-Wide Attack",
        "summary": "Wide attackers cut into half-spaces alongside inverted full-backs to create shooting angles and central overloads in the most dangerous areas of the final third.",
        "stat_signature": "Half-space touch rate >=25% of final-third touches; inverted full-back central occupation index >=0.55; high-value central chances (xG>=0.12) created >=2.5 per 90; shots from half-space >=30%.",
        "mechanism": "Half-space occupation forces defenders to choose between tracking the inverted attacker or holding the defensive line, producing cutback opportunities and near-post shooting lanes.",
        "conditions": "Effective against defenses that mark wide and leave central half-spaces exposed when full-backs push; less productive against sides dropping a midfielder into the half-space.",
        "magnitude": "Central half-space shots average xG per shot 0.13-0.17, roughly 30-50% above the open-play mean; high half-space occupation correlates with 20-30% more shots from inside the attacking third.",
        "links": ["positional_play_juego_de_posicion", "wing_play_overlap_crossing", "overlapping_underlapping_fullbacks", "third_man_combination_play"],
    },
    {
        "slug": "third_man_combination_play",
        "title": "Third-Man and Combination Play",
        "summary": "Quick give-and-go and layoff sequences free a third runner behind a pressing line in tight central areas, bypassing pressure through pre-rehearsed movement.",
        "stat_signature": "One-two and layoff frequency >=6 per 90; line-breaking pass rate >=4 per 90; box entries created through combinations >=3 per 90; sequence completion rate >=65% through congested areas.",
        "mechanism": "The third-man principle exploits the split-second delay between the first pass and the pressing defender's reaction; the layoff receiver plays before pressure arrives, freeing the runner in behind.",
        "conditions": "Effective in tight central areas against man-oriented presses that commit individually; less productive against zonal structures that maintain depth and pre-cover the third man's run.",
        "magnitude": "Combination sequences penetrating the press generate box-entry rates 40-55% above direct-carry attempts; line-breaking passes from combinations carry average xG per resulting shot of 0.12-0.16.",
        "links": ["positional_play_juego_de_posicion", "half_space_inverted_attack", "build_up_from_the_back", "overload_to_isolate_switch"],
    },
    {
        "slug": "overlapping_underlapping_fullbacks",
        "title": "Full-Back Rotation and Overlap Patterns",
        "summary": "Full-backs push into advanced positions and rotate with wide forwards to create width, numerical overloads, and crossing platforms while the wide forward tucks inside.",
        "stat_signature": "Full-back final-third touch rate >=18 per 90; overlap/underlap frequency >=5 coordinated runs per 90; width-stretch index (widest spacing) >=60 m; full-back cross share >=25%.",
        "mechanism": "High full-back positioning creates a two-on-one on the flank while the inverted winger pulls a center-back or midfielder inside, generating simultaneous width and central overloads.",
        "conditions": "Effective when opponent wide midfielders track back selectively; creates defensive vulnerability when the full-back is caught high against a fast-transitioning opponent.",
        "magnitude": "Full-back byline-reaching crosses complete at 35-45% higher rates than wide-attacker crosses; full-back final-third rates above 18 per 90 correlate with 12-18% more wide-overload situations.",
        "links": ["wing_play_overlap_crossing", "half_space_inverted_attack", "overload_to_isolate_switch", "positional_play_juego_de_posicion"],
    },
    {
        "slug": "overload_to_isolate_switch",
        "title": "Overload-to-Isolate and Switch of Play",
        "summary": "Numbers are committed to one flank to draw the defense across, then the ball is rapidly switched to isolate a one-on-one on the far side.",
        "stat_signature": "Switch-of-play frequency >=5 per 90 from overloaded flanks; far-side isolation rate >=60% of switches producing a one-on-one; chances created within four seconds of a switch >=2.5 per 90.",
        "mechanism": "Overloading one side forces the defensive block to shift laterally; a fast switch exploits the brief moment when the far-side defender is still recovering position.",
        "conditions": "Most effective against narrow, reactive defensive blocks; less productive against wide-tracking defenses that maintain horizontal spacing regardless of ball position.",
        "magnitude": "Switches producing far-side isolation within four seconds generate shots at roughly twice the rate of non-isolated wide attacks; isolation situations convert to shots 35-45% of the time.",
        "links": ["wing_play_overlap_crossing", "overlapping_underlapping_fullbacks", "half_space_inverted_attack", "counter_attack_transition_offense"],
    },
    {
        "slug": "counter_attack_transition_offense",
        "title": "Counter-Attacking Transition Offense",
        "summary": "After winning the ball the team attacks vertically at speed before the opponent can reorganize defensively, exploiting temporary structural imbalances.",
        "stat_signature": "Direct-attack-sequence frequency >=5 per 90 from own-half recovery; time-to-shot after turnover <=8 seconds for transition chances; xG from transition sequences >=0.35 per 90; passes per sequence <=3.5.",
        "mechanism": "Transitional imbalance is maximized within seconds of a turnover; direct vertical play bypasses the opponent's recovery run, converting defensive moments into one-on-two or two-on-two finishes.",
        "conditions": "Most effective against possession-dominant high-line sides that commit many players forward; less effective against deep-block sides already compact when possession changes.",
        "magnitude": "Counter-attacking xG per shot averages 0.14-0.18, above the open-play mean; transition sequences completed in under eight seconds from the own half reach the final third 55-65% of the time.",
        "links": ["counter_press_gegenpress", "low_block_deep_defense", "direct_long_ball_progression", "restart_quick_play_throw_in"],
    },
    {
        "slug": "attacking_set_piece_routines",
        "title": "Attacking Set-Piece Routines",
        "summary": "Designed corner and free-kick deliveries use blocking runs, screens, and coordinated zonal-attack patterns to generate high-probability first-contact chances in the box.",
        "stat_signature": "Set-piece xG per corner delivery >=0.085; far-post targeting share >=40%; first-contact win rate in the box >=55%; set-piece shots per 90 >=3.0.",
        "mechanism": "Blocking and screening runs remove individual markers before delivery, creating free runs to the ball; zone-flood approaches overwhelm zonal marking by outnumbering defenders at the delivery point.",
        "conditions": "Most effective against zonal marking schemes relying on preset positions; blocking runs lose effectiveness against pure man-marking with switch coverage; short routines exploit disorganized presses.",
        "magnitude": "Teams with >=0.085 xG per corner delivery generate 0.25-0.35 xG from set pieces per 90, representing 20-30% of total xG equivalent for elite set-piece sides.",
        "links": ["defensive_set_piece_organization", "restart_quick_play_throw_in", "wing_play_overlap_crossing", "direct_long_ball_progression"],
    },
    {
        "slug": "defensive_set_piece_organization",
        "title": "Defensive Set-Piece Organization",
        "summary": "The team employs zonal, man-marking, or hybrid schemes with post protection and coordinated clearance responsibilities to deny first contact from opponent deliveries.",
        "stat_signature": "First-clearance rate >=60% of deliveries faced; shots conceded per opponent corner <=0.40; xG conceded per delivery <=0.065; second-ball recovery rate after clearance >=50%.",
        "mechanism": "Zonal organization assigns clearing responsibility by area, enabling pre-jump timing; man-marking tracks runners but is vulnerable to blocking movements; post protection is non-negotiable against near-post pace delivery.",
        "conditions": "Hybrid schemes are most stable; pure zonal is exploited by flood-zone routines; pure man-marking is disrupted by complex blocking patterns; scheme choice depends on opponent delivery tendencies.",
        "magnitude": "Difference between elite and poor set-piece organization corresponds to 0.03-0.05 xG conceded per delivery; across a full season this represents 3-5 xG difference from set pieces alone.",
        "links": ["attacking_set_piece_routines", "zonal_marking_set_structure", "man_oriented_marking", "low_block_deep_defense"],
    },
    {
        "slug": "restart_quick_play_throw_in",
        "title": "Quick-Restart and Throw-In Routines",
        "summary": "Rapid free-kicks, goal-kicks, and structured throw-in patterns catch opponents disorganized or progress play through prepared wide-zone combinations.",
        "stat_signature": "Quick-restart frequency >=4 per 90 converting stoppages within five seconds; throw-in ball-retention rate >=72%; final-third entries from restarts >=3 per 90; restart-error turnover rate <=1.5 per 90.",
        "mechanism": "Opponents expect stoppages to allow reorganization; quick restarts exploit a disorganized defensive shape before marking assignments are re-established; prepared throw-in patterns create pre-rehearsed overloads.",
        "conditions": "Most productive against sides that switch off after conceding a free-kick; requires referee permission and breaks down when the opponent aggressively prevents quick play.",
        "magnitude": "Teams with throw-in retention above 72% generate 15-20% more possession sequences from lateral restarts; quick free-kicks converted within five seconds produce final-third entries at roughly twice the rate of deliberate approaches.",
        "links": ["attacking_set_piece_routines", "counter_attack_transition_offense", "pressing_traps_wide_zones", "build_up_from_the_back"],
    },
]
