"""Soccer TempoVariation concept nodes — person-free, dense, calibrated."""
from __future__ import annotations

SPORT = "Soccer"
FAMILY = "TempoVariation"

CONCEPTS = [
    {
        "slug": "tempo_modulation_in_possession",
        "title": "Tempo Modulation in Possession",
        "summary": "Deliberately alternating between slow circulation and sudden acceleration within a single possession unsettles a settled defensive block by preventing it from anchoring to one rhythm.",
        "stat_signature": "Within-spell passes-per-minute variance > 1.8x league average; speed-up triggers (acceleration delta > 40% passes-per-minute) before final-third entries > 3 per 90 minutes.",
        "mechanism": "A block tuned to a slow ball-movement rhythm cannot instantly shift to a fast-shape when tempo abruptly increases; the gap between defensive reaction time and attack execution speed generates momentary structural vulnerabilities.",
        "conditions": "Most disruptive against mid-block defenses organized reactively to ball position; less impactful against high-press systems already operating at variable tempo.",
        "magnitude": "Possessions containing at least one documented slow-to-fast speed shift yield roughly 35–45% more shots on target per possession than same-team sequences without a shift.",
        "links": ["side_to_side_tempo_stall", "tempo_injection_through_vertical_pass", "tempo_lull_for_recovery_rest", "tempo_variance_as_unpredictability"],
    },
    {
        "slug": "game_slowing_to_kill_momentum",
        "title": "Game-Slowing to Kill Momentum",
        "summary": "Intentionally reducing tempo to neutralize an opponent's high-energy pressure spell, measurable as a sharp drop in ball-progression-per-minute and a surge in back-and-square pass share.",
        "stat_signature": "Ball-progression-per-minute falls >= 30% in windows following high-opponent-xG phases; backward-and-square pass share rises >= 12 percentage points versus the preceding 10-minute baseline.",
        "mechanism": "Slowing play denies the pressing side its preferred high-intensity continuation; each deliberate square or back pass re-anchors defensive shape while forcing the presser to reset physical effort without reward.",
        "conditions": "Applied when the opponent is in an ascendant spell characterized by high PPDA and multiple successive corners or set pieces; less relevant when the game is already fragmented by stoppages.",
        "magnitude": "Deliberate slow-down phases after a high-pressure spell correlate with a roughly 40% reduction in opponent high-tempo sequences in the following 10 minutes.",
        "links": ["game_state_tempo_management", "tempo_lull_for_recovery_rest", "controlled_tempo_dead_ball_management", "rhythm_disruption_via_tactical_foul"],
    },
    {
        "slug": "tempo_injection_through_vertical_pass",
        "title": "Tempo Injection Through Vertical Passing",
        "summary": "A sudden line-breaking forward pass after slow build-up acts as a tempo injection, measurable as a spike in forward-pass distance and progressive-pass rate against a rolling possession-speed baseline.",
        "stat_signature": "Vertical passes >= 20 m forward during a possession with prior speed <= 25th percentile for the team; progressive-pass rate spike > 50% above rolling 5-possession average.",
        "mechanism": "The receiving player receives the ball already facing forward in space opened by the prior slow phase; defenders in compact shape lose their positional advantage when the ball skips lines faster than shape can adjust.",
        "conditions": "Effective when the defensive block has fully settled behind the ball; requires a receiving player with the technical profile to control and accelerate under pressure on the first touch.",
        "magnitude": "Line-breaking vertical passes delivered after a slow-circulation phase generate attacking-third entries roughly 2x more often than equivalent vertical passes preceded by already-fast sequences.",
        "links": ["tempo_modulation_in_possession", "first_touch_pace_setting", "third_man_run_tempo_trigger", "deliberate_slow_build_to_draw_press"],
    },
    {
        "slug": "controlled_tempo_dead_ball_management",
        "title": "Controlled Tempo via Dead-Ball Management",
        "summary": "Using throw-ins, goal kicks, and set-piece routines to deliberately slow or accelerate restart cadence, measurable as time-to-restart distribution split by score state and game phase.",
        "stat_signature": "Leading teams: goal kick average > 27 s, throw-in average > 18 s; trailing teams: goal kick average < 16 s, throw-in average < 9 s; delta between states >= 8 s is the signature threshold.",
        "mechanism": "Dead-ball delays reduce effective live-play volume for the trailing side; rapid restarts exploit the disorganization window before opponents re-set, functioning as both tempo accelerators and decelerators depending on score context.",
        "conditions": "Most influential in the final 20 minutes when the added-time correction is incomplete; attenuated where referees strictly enforce restart timing with yellow-card warnings.",
        "magnitude": "Systematic dead-ball management by a leading side reduces effective ball-in-play time by roughly 4–6 minutes in the final phase relative to neutral-state restart behavior.",
        "links": ["quickened_restart_to_exploit_disorganization", "game_state_tempo_management", "game_slowing_to_kill_momentum", "ball_in_play_tempo_compression"],
    },
    {
        "slug": "first_touch_pace_setting",
        "title": "First-Touch Pace-Setting",
        "summary": "The receiving touch determines whether the next phase speeds up or settles: a one-touch lay-off continues momentum while a controlling first touch invites the carrier to read the situation before committing.",
        "stat_signature": "One-touch pass rate after receipt >= 45% indexes high-tempo continuation; controlling-touch rate correlates with sequence-speed reduction of 15–25% in the following 3 actions.",
        "mechanism": "A one-touch continuation keeps defenders in motion and prevents them from re-anchoring; a controlling touch resets body orientation and allows a tactical decision but surrenders the momentum advantage.",
        "conditions": "Pace-setting at first touch is most consequential in the middle third where neither deep defensive compactness nor clear final-third finishing chances constrain behavior.",
        "magnitude": "Sequences initiated with one-touch receipts reach the final third approximately 1.6x more often than equivalent possessions initiated with a controlling touch from the same pitch zone.",
        "links": ["tempo_injection_through_vertical_pass", "third_man_run_tempo_trigger", "tempo_modulation_in_possession", "switch_of_play_tempo_change"],
    },
    {
        "slug": "deliberate_slow_build_to_draw_press",
        "title": "Deliberate Slow Build to Draw the Press",
        "summary": "Intentionally circulating in deep areas to bait the opponent's press, then releasing with a speed burst, measurable as high build-up pass count in the defensive-to-middle-third zone and the acceleration delta when press triggers.",
        "stat_signature": "Own-third passes per possession >= 6 before the first middle-third entry; acceleration delta at press trigger > 55% passes-per-minute increase within 3 actions of the first pressing contact.",
        "mechanism": "Patient deep circulation draws pressing lines forward, compressing the opponent's defensive structure; the deliberate speed release into the gap created by the overcommitted press bypasses the entire mid-block.",
        "conditions": "Requires technical proficiency under pressure in the defensive third and at least one line-breaking pass option; fails against passive mid-blocks that refuse to commit defenders forward.",
        "magnitude": "Possessions following a confirmed press trigger after >= 5 own-third passes create final-third entries roughly 1.8x more often than possessions entering the press without the baiting phase.",
        "links": ["tempo_injection_through_vertical_pass", "tempo_modulation_in_possession", "pressing_tempo_to_quicken_opponent", "deliberate_slow_build_to_draw_press"],
    },
    {
        "slug": "transition_to_settled_tempo_drop",
        "title": "Transition-to-Settled Tempo Drop",
        "summary": "Deliberately decelerating a counter into controlled possession rather than forcing a fast finish, captured by the share of transitions converting into sustained possession and the speed reduction at conversion point.",
        "stat_signature": "Transitions converting to sustained possession (>= 4 consecutive passes after final-third entry): > 35% of all transition entries; ball-speed reduction at conversion >= 40% within 5 s.",
        "mechanism": "Converting a counter into patient possession retains the territorial gain while avoiding the low-quality shot risk of an overly rushed finish; the opponent must re-organize defensively, often producing a second numerical advantage.",
        "conditions": "Deployed when the transition lacks numerical advantage or when opposition recovery speed is sufficient to neutralize the fast-break opportunity; requires forwards capable of back-laying under pressure.",
        "magnitude": "Controlled transition conversions yield shots-on-target per possession comparable to positional attacks, roughly 0.12–0.18 shots per sequence, while avoiding the low-conversion risk of forced fast finishes.",
        "links": ["tempo_lull_for_recovery_rest", "game_state_tempo_management", "tempo_modulation_in_possession", "ball_in_play_tempo_compression"],
    },
    {
        "slug": "quickened_restart_to_exploit_disorganization",
        "title": "Quickened Restart to Exploit Disorganization",
        "summary": "Taking free kicks and throw-ins rapidly before the defense re-sets exploits a structural disorganization window, signatured by time-to-restart below 5 seconds and the elevated progressive-action rate in the subsequent 8 seconds.",
        "stat_signature": "Quick restarts executed in < 5 s: > 40% of eligible free kicks and throw-ins in attacking half; progressive actions within 8 s of restart: >= 1.5 per quick restart versus 0.4 per delayed routine.",
        "mechanism": "A rapid restart attacks the transitional window before defensive compactness is restored; the opponent settling into shape or disputing the call forfeits the organizational cover that set-piece routines depend on.",
        "conditions": "Requires pre-agreed target zones among attackers and the spatial awareness to identify the disorganization; attenuated when the opposition maintains defensive lines rather than pressing the ball.",
        "magnitude": "Quick restarts generate approximately 1.5–2x the attacking-sequence rate per action compared with deliberate set-piece routines from the same pitch area.",
        "links": ["controlled_tempo_dead_ball_management", "third_man_run_tempo_trigger", "game_slowing_to_kill_momentum", "tempo_injection_through_vertical_pass"],
    },
    {
        "slug": "tempo_lull_for_recovery_rest",
        "title": "Tempo Lull for Recovery Rest",
        "summary": "Low-intensity ball retention phases used to recover physical capacity, measurable as sustained low ball-progression-per-minute combined with reduced collective sprint-distance during the retention spell.",
        "stat_signature": "Ball-progression-per-minute <= 20th percentile for the team; collective sprint-distance in the spell <= 30% of peak-phase baseline; average duration of these spells: 3–6 minutes per half.",
        "mechanism": "Retaining possession without forward intent forces the opponent to hold defensive shape without energy return; in the meanwhile the ball-holding side accumulates aerobic recovery toward a subsequent high-intensity phase.",
        "conditions": "Emerges after sustained pressing or fast-transition phases; most deliberate in teams with high-press mandates requiring periodic rest cycles built into their shape management.",
        "magnitude": "Teams with identifiable recovery-lull phases maintain peak sprint output roughly 12–18% higher in the final 15 minutes relative to sides that never modulate tempo for rest.",
        "links": ["game_slowing_to_kill_momentum", "transition_to_settled_tempo_drop", "side_to_side_tempo_stall", "game_state_tempo_management"],
    },
    {
        "slug": "third_man_run_tempo_trigger",
        "title": "Third-Man Run Tempo Trigger",
        "summary": "A timed off-ball run that converts patient possession into sudden acceleration, captured by the co-occurrence of a high-speed run and a speed-up in sequence ball-progression within the same possession chain.",
        "stat_signature": "High-speed runs (> 5.5 m/s) occurring within 2 s of a lateral pass in the build-up: >= 1.8 per 90 minutes linked to a possession-speed spike > 35% in the following 3 actions.",
        "mechanism": "The third runner's timed movement draws a defender, creating space for the ball-carrier to play into; the run synchronization converts a static possession pattern into a dynamic one without telegraphing the attack.",
        "conditions": "Most effective when the defensive block is tracking the ball rather than maintaining zone coverage; requires precise run timing and spatial coordination between passer and runner.",
        "magnitude": "Possessions containing an identified third-man run pattern create shots on target roughly 1.7x more often per sequence than structurally similar sequences without the synchronized movement.",
        "links": ["first_touch_pace_setting", "tempo_injection_through_vertical_pass", "tempo_modulation_in_possession", "switch_of_play_tempo_change"],
    },
    {
        "slug": "side_to_side_tempo_stall",
        "title": "Side-to-Side Tempo Stall",
        "summary": "Lateral circulation used to slow the game and shift a compact defensive block, measured by the ratio of sideways-to-forward passes and the time spent in horizontal phases before a vertical release.",
        "stat_signature": "Sideways-to-forward pass ratio > 2.0 in sustained possession spells; horizontal phase duration >= 8 s before vertical release; wide zone touches > 55% of all touches in these phases.",
        "mechanism": "Sustained lateral movement forces the block to shift collectively, accumulating micro-misalignments and defensive fatigue without conceding the ball; the eventual vertical release targets the displacement gap.",
        "conditions": "Most productive against narrow compact blocks with wide areas left lightly defended; less useful against disciplined wide-zone marking or teams that concede the wide lane to funnel play centrally.",
        "magnitude": "Horizontal phases lasting >= 10 s before a vertical release precede final-third entries at roughly 1.4x the rate of direct vertical attempts against the same opposition shape.",
        "links": ["tempo_lull_for_recovery_rest", "tempo_modulation_in_possession", "tempo_setting_pivot_circulation", "deliberate_slow_build_to_draw_press"],
    },
    {
        "slug": "pressing_tempo_to_quicken_opponent",
        "title": "Pressing Tempo to Rush the Opponent",
        "summary": "Applying coordinated pressure designed to force the opponent into faster, lower-quality decisions, signatured by a reduction in opponent average possession time and a rise in forced-clearance rate under pressure.",
        "stat_signature": "Opponent average possession time falls >= 20% when press is active; forced-clearance rate rises >= 0.8 per 10 defensive actions under press versus the non-press baseline.",
        "mechanism": "Compressed decision time degrades passing accuracy and selection quality; the opponent accelerates involuntarily, producing rushed touches and clearances that can seed counter-attacks.",
        "conditions": "Most effective against ball-playing teams whose build quality depends on composure in tight spaces; less impactful against direct long-ball systems designed to bypass pressing lines entirely.",
        "magnitude": "High-press phases reducing opponent possession time by >= 20% correspond to roughly a 35–50% increase in defensive-third turnovers per 90 minutes for the pressing side.",
        "links": ["deliberate_slow_build_to_draw_press", "game_slowing_to_kill_momentum", "tempo_modulation_in_possession", "tempo_lull_for_recovery_rest"],
    },
    {
        "slug": "game_state_tempo_management",
        "title": "Game-State Tempo Management",
        "summary": "Systematic pace choice driven by scoreline — slowing possession speed when ahead and accelerating when trailing — measurable as the difference in possession speed and ball-in-play tempo between leading and trailing intervals.",
        "stat_signature": "Leading state: passes-per-minute 12–15% below match-level average; trailing state: 15–22% above; split at the moment of goal and measured in rolling 10-minute windows.",
        "mechanism": "Score state alters risk tolerance at the structural level; a lead incentivizes circulation in safe zones and avoiding transition exposure, while a deficit incentivizes acceleration and direct progression regardless of structural risk.",
        "conditions": "Most pronounced in matches decided by one goal; smaller in matches with large scoreline differentials where the trailing side faces structural infeasibility of recovery.",
        "magnitude": "Leading sides in the final third of matches show roughly a 30% reduction in attacking-third entries per minute, balanced against a similar reduction in transitions conceded.",
        "links": ["ball_in_play_tempo_compression", "controlled_tempo_dead_ball_management", "game_slowing_to_kill_momentum", "tempo_lull_for_recovery_rest"],
    },
    {
        "slug": "ball_in_play_tempo_compression",
        "title": "Ball-in-Play Tempo Compression",
        "summary": "Maximizing or minimizing effective playing time to control match rhythm, measured by the ratio of ball-in-play seconds to total elapsed time and its split by score state.",
        "stat_signature": "Range 48–67 effective minutes per 90; leading teams in the final phase: ball-in-play ratio <= 55%; trailing teams: ratio >= 62%; difference between states >= 7 pp is the signature threshold.",
        "mechanism": "Compressing ball-in-play time reduces the opponent's window for high-tempo attacking sequences; expanding it exploits the opponent's structural need for live-play moments to build chance quality.",
        "conditions": "Most controllable in the final 20 minutes when scoreline incentives are strongest; partially constrained by officiating style and the extent of added time actually awarded.",
        "magnitude": "Each 5-minute reduction in effective play correlates with roughly a 0.12-unit decrease in total xG, primarily through fewer pressing sequences and reduced transition frequency.",
        "links": ["controlled_tempo_dead_ball_management", "game_state_tempo_management", "rhythm_disruption_via_tactical_foul", "transition_to_settled_tempo_drop"],
    },
    {
        "slug": "rhythm_disruption_via_tactical_foul",
        "title": "Rhythm Disruption via Tactical Interruption",
        "summary": "Using a deliberate stoppage to break an opponent's flowing attacking sequence, signatured by interruption frequency in opponent progressive chains and the tempo reset that structurally follows.",
        "stat_signature": "Tactical interruptions per 90 minutes targeting progressive opponent sequences: >= 4; possession-speed reset following each interruption: >= 35% reduction in the next opponent possession.",
        "mechanism": "Stopping a flowing sequence forces the opponent to restart from a set position; the spatial and momentum advantages accumulated through combination play are nullified at zero cost to structural shape.",
        "conditions": "Used when the opponent's combination quality is superior in a localized zone and conceding the foul is preferable to conceding the chance; most deliberate in the middle third where yellow-card risk is lower.",
        "magnitude": "Progressive opponent sequences interrupted by a deliberate foul yield shots-on-target at roughly 35% the rate of sequences allowed to continue without interruption.",
        "links": ["game_slowing_to_kill_momentum", "ball_in_play_tempo_compression", "controlled_tempo_dead_ball_management", "pressing_tempo_to_quicken_opponent"],
    },
    {
        "slug": "switch_of_play_tempo_change",
        "title": "Switch-of-Play Tempo Change",
        "summary": "A long cross-field diagonal ball that abruptly changes attack speed and angle, measured by the rate of long diagonal switches and the acceleration in ball-progression immediately after the switch.",
        "stat_signature": "Long diagonal switches (>= 35 m cross-field): >= 6 per 90 minutes; ball-progression-per-minute acceleration after switch >= 30% relative to the 5-action pre-switch baseline.",
        "mechanism": "A long switch transfers play from a congested zone to a less-prepared defensive flank in a single action; the receiving side has a head start on the defensive re-adjustment, generating a brief positional advantage.",
        "conditions": "Most effective against narrow compact shapes that have over-shifted toward one flank; requires a passer with the physical range to deliver the switch and a receiver who can control at pace.",
        "magnitude": "Possessions containing a long switch followed by a progressive action within 3 touches reach the final third roughly 1.5x more often than same-team possessions without the switch.",
        "links": ["tempo_modulation_in_possession", "first_touch_pace_setting", "third_man_run_tempo_trigger", "side_to_side_tempo_stall"],
    },
    {
        "slug": "tempo_setting_pivot_circulation",
        "title": "Tempo-Setting Pivot Circulation",
        "summary": "A deep central player controlling whether the team speeds up or settles through touch tempo, captured by touches-per-minute variance in that zone and its correlation with team-wide sequence speed.",
        "stat_signature": "Deep central zone touches-per-minute variance > 1.6x league average; correlation between that zone's passing tempo and overall team sequence speed: r >= 0.55 within the same possession.",
        "mechanism": "The pivot's touch choices ripple outward — a one-touch lay-off signals and enables acceleration while a controlling touch signals and enables a deliberate reset; their positional centrality maximizes the downstream influence.",
        "conditions": "Most consequential in teams whose build-up routes through a dominant deep central link; less impactful in wide-origin possession systems that bypass a central pivot.",
        "magnitude": "In pivot-reliant systems, possessions originating from a fast pivot touch reach the final third roughly 1.4x more often than those from a controlling touch from the same zone.",
        "links": ["tempo_modulation_in_possession", "first_touch_pace_setting", "side_to_side_tempo_stall", "deliberate_slow_build_to_draw_press"],
    },
    {
        "slug": "tempo_variance_as_unpredictability",
        "title": "Tempo Variance as Unpredictability",
        "summary": "Maintaining a wide distribution of possession speeds so the opponent cannot anchor defensive timing, measured by the overall spread of sequence-speed values across the match.",
        "stat_signature": "Sequence-speed interquartile range >= 2.0x league average; no single speed band (slow/medium/fast) accounting for > 50% of total possessions; high-speed sequences interspersed at least once per 8 possessions.",
        "mechanism": "Predictable tempo allows a defense to optimize shape for one rhythm; high tempo variance denies that optimization, forcing the defense to maintain readiness across multiple speeds at the cost of concentrated structural depth.",
        "conditions": "Most strategically durable against analytically sophisticated defenses that exploit tempo patterns; requires versatile rotation of build-up profiles rather than a fixed tactical identity.",
        "magnitude": "Teams in the top quartile of match-level sequence-speed variance concede roughly 15–20% fewer shots-on-target per chance conceded as defenses cannot settle into a single anticipatory shape.",
        "links": ["tempo_modulation_in_possession", "side_to_side_tempo_stall", "switch_of_play_tempo_change", "game_state_tempo_management"],
    },
]
