"""Tennis / TempoVariation — dense person-free concept nodes for the brain."""
from __future__ import annotations

SPORT = "Tennis"
FAMILY = "TempoVariation"

CONCEPTS: list[dict] = [
    {
        "slug": "between_point_pace_disruption",
        "title": "Between-Point Pace Disruption",
        "summary": "Varying inter-point intervals selectively after point outcomes to break the opponent's preparation cycle and disrupt conditioned arousal timing.",
        "stat_signature": "Inter-point SD >6 s; conditional split shows +3–5 s when opponent won the prior point versus when the server won; return-in-play rate drops 4–7 pp in high-SD sets.",
        "mechanism": "Neural anticipation peaks at a learned interval; deviating from the conditioned rhythm degrades motor-program readiness and increases micro-hesitation at shot contact.",
        "conditions": "Most potent against rhythm-dependent baseliners with fixed pre-point routines; amplified on slower courts where longer points already stress concentration windows.",
        "magnitude": "Return-in-play rate falls 4–7 pp when inter-point SD exceeds 7 s; unforced error rate on the opening two shots rises ~8% for the disrupted player.",
        "links": ["serve_routine_tempo_variation", "quick_serve_to_rush_returner", "rhythm_disruption_via_time_violation_edge", "between_game_pace_management"],
    },
    {
        "slug": "rally_speed_modulation",
        "title": "Rally-Speed Modulation",
        "summary": "Deliberately alternating heavy and soft balls within a rally to disrupt swing timing, with within-rally ball-speed variance as the primary observable.",
        "stat_signature": "Within-rally ball-speed SD >25 km/h; off-pace shots placed in positions 3–5 correlate with winner or forced-error on the following shot at ~55% versus ~38% baseline.",
        "mechanism": "Swing mechanics are pre-programmed at the incoming pace level; a sudden speed drop causes over-swing or mistimed contact, shortening the reply or ballooning it.",
        "conditions": "Effective against opponents who load swing speed proportionally to incoming pace; less impactful on flat-hitters who generate self-paced swings independently.",
        "magnitude": "Forced-error rate on the shot after an off-pace insertion runs 12–15 pp above match baseline; winner conversion on the subsequent ball improves ~10 pp.",
        "links": ["change_of_pace_off_pace_ball", "moon_ball_rhythm_break", "slice_tempo_neutralization", "spin_rate_tempo_disruption", "tempo_variance_as_unpredictability_tennis"],
    },
    {
        "slug": "change_of_pace_off_pace_ball",
        "title": "Change-of-Pace Off-Pace Ball",
        "summary": "Inserting a markedly slower shot into a fast exchange to break swing timing; the speed-drop magnitude relative to rally mean is the primary measurable.",
        "stat_signature": "Shot speed >35% below rally mean; reply short-ball or error rate on the next shot rises to 40–50% versus 18–22% in pace-consistent exchanges.",
        "mechanism": "The motor system commits swing force and timing to the incoming ball trajectory; a speed reduction of this magnitude arrives before the correction window, yielding frame or net contact.",
        "conditions": "Optimal when the opponent is in an aggressive momentum phase; less effective when the opponent is already playing defensively with no over-swing tendency.",
        "magnitude": "Short-ball creation rate after off-pace insertion is 2–2.5× the match baseline, enabling an attacking follow-up shot at net or as a clean winner attempt.",
        "links": ["rally_speed_modulation", "pace_baiting_to_force_overhit", "drop_shot_tempo_interruption", "depth_variation_to_disrupt_spacing"],
    },
    {
        "slug": "serve_routine_tempo_variation",
        "title": "Serve-Routine Tempo Variation",
        "summary": "Altering the pre-serve ritual duration to disrupt a returner's anticipation cycle; the variance of time-to-serve, not a fixed change, is the operative signal.",
        "stat_signature": "Routine-duration SD >3 s; near-max-duration routines uncorrelated with first-serve errors (<5% correlation) confirms volitional variation; return winners drop ~6 pp on altered routines.",
        "mechanism": "Returners develop conditioned anticipation windows locked to routine length; an unpredictable window prevents complete pre-load of weight transfer and split-step timing.",
        "conditions": "Most effective against returners who rely heavily on ball-toss timing reads; amplified on high-leverage points where cognitive load is already elevated.",
        "magnitude": "First-return-in-play rate falls 5–8 pp when routine SD exceeds 4 s; returner reaction time to serve direction increases ~20 ms on average in disrupted sets.",
        "links": ["between_point_pace_disruption", "quick_serve_to_rush_returner", "rhythm_disruption_via_time_violation_edge"],
    },
    {
        "slug": "quick_serve_to_rush_returner",
        "title": "Quick-Serve to Rush the Returner",
        "summary": "Serving rapidly after the prior point to deny the returner sufficient physiological and cognitive reset time, measured by short inter-point intervals and return-quality metrics.",
        "stat_signature": "Inter-point interval <15 s on serve; return unforced-error rate 8–12 pp above set average; serve-and-volley success rate rises ~5 pp when the quick-serve catches the opponent out of position.",
        "mechanism": "Post-point recovery requires 18–25 s; compressing this window leaves sympathetic arousal elevated and fine motor control degraded at the return contact point.",
        "conditions": "Effective after long, physically demanding points when oxygen debt and peripheral fatigue peak; less impactful after short first-strike exchanges.",
        "magnitude": "Return fault or misfire rate averages 15–20% higher after <15 s inter-point intervals; opponent experience surveys consistently rank hurry-up serving as a primary disruptor.",
        "links": ["between_point_pace_disruption", "serve_routine_tempo_variation", "return_tempo_imposition"],
    },
    {
        "slug": "moon_ball_rhythm_break",
        "title": "High-Arc Rhythm Break",
        "summary": "Using a high-trajectory looping ball to extend flight time, force a timing reset, and push the opponent to a contact point above shoulder height where leverage is structurally weaker.",
        "stat_signature": "Net clearance >2 m; ball flight time >1.5 s versus rally mean ~0.9 s; opponent unforced error on the reply rises 10–14 pp against flat or moderate-arc shots.",
        "mechanism": "Extended flight time disrupts the internally clocked swing initiation; the high bounce forces contact above shoulder height where most technical profiles lack efficient leverage.",
        "conditions": "Most disruptive against low-contact-window players with flat groundstroke mechanics; less effective against those with a strong overhead or standing-smash option.",
        "magnitude": "Opponent retreats behind the baseline on ~60% of moon-ball replies; opponent winner rate from shoulder-height contact falls to <8% versus 22% from waist-height on fast balls.",
        "links": ["rally_speed_modulation", "slice_tempo_neutralization", "depth_variation_to_disrupt_spacing", "tempo_consistency_as_anchor"],
    },
    {
        "slug": "drop_shot_tempo_interruption",
        "title": "Drop-Shot Tempo Interruption",
        "summary": "A sudden short, slow ball that collapses rally rhythm by imposing an irrecoverable sprint under time pressure, with the reaction-time deficit as the key measurable.",
        "stat_signature": "Ball speed <30 km/h after a rally mean >70 km/h; estimated reaction deficit (time-to-contact minus sprint-to-net time) >0.3 s; point-won rate from behind baseline ~55–65%.",
        "mechanism": "The opponent's positional inertia and court depth create a physically irrecoverable sprint demand; a recovered ball still leaves them out of position for the lob or passing-shot follow-up.",
        "conditions": "Optimal when the opponent is deep behind the baseline in a grinding sequence; less effective on fast surfaces where ball skids low and the sprinting disadvantage is less pronounced.",
        "magnitude": "Drop shots from a neutral position win ~52% of points; from a deep-pulling rally the rate rises to 62–68%; a follow-up lob wins >70% when the opponent overruns the ball.",
        "links": ["change_of_pace_off_pace_ball", "depth_variation_to_disrupt_spacing", "first_strike_tempo_acceleration"],
    },
    {
        "slug": "slice_tempo_neutralization",
        "title": "Slice Tempo Neutralization",
        "summary": "Using underspin to keep the ball low and slow, denying the opponent pace to redirect and forcing them to generate their own pace from an awkward contact point.",
        "stat_signature": "Slice shots average 55–65 km/h versus topspin norms of 85–100 km/h; bounce height <0.5 m; opponent winner rate off low-slice reply is 10–15 pp below their overall winner rate.",
        "mechanism": "Underspin reduces bounce height and forward momentum, requiring the opponent to lift heavy topspin from below knee height — a high-effort, low-angle task that constrains winner probability.",
        "conditions": "Most effective on grass and low-bounce hard courts against pace-dependent opponents; less effective on high-bounce clay where opponents adjust comfortably with lifted technique.",
        "magnitude": "Forced error rate on the reply is ~18% versus 11% against pace-on groundstrokes; net approach after a slice short ball wins ~60% of net points versus 45% off a topspin approach.",
        "links": ["moon_ball_rhythm_break", "rally_speed_modulation", "deep_return_tempo_reset", "tempo_consistency_as_anchor"],
    },
    {
        "slug": "first_strike_tempo_acceleration",
        "title": "First-Strike Tempo Acceleration",
        "summary": "Shortening rallies by attacking on shot 2 or 3 to impose a fast cadence and deny the opponent time to settle into a grinding baseline exchange.",
        "stat_signature": "Points ended in 0–4 shots >45%; median rally length <4 shots; first-strike winner or forced-error rate >28% of serve-plus-one sequences.",
        "mechanism": "Attacking on the first available short ball compresses the opponent's recovery window to near zero; repeated short-rally wins also reset their concentration before a long point is established.",
        "conditions": "Most effective against opponents excelling in prolonged exchanges but struggling with pace transitions in rally shots 2–3; faster surfaces amplify the pace differential.",
        "magnitude": "Sets dominated by <4-shot rallies show ~6 pp higher win probability for the aggressor; first-strike winners account for 35–50% of total winners in first-strike-dominant profiles.",
        "links": ["serve_plus_one_tempo_pressure", "return_tempo_imposition", "change_of_pace_off_pace_ball"],
    },
    {
        "slug": "rhythm_disruption_via_time_violation_edge",
        "title": "Rhythm Disruption at the Serve-Clock Edge",
        "summary": "Stretching the inter-point routine near the shot-clock limit to maximize the opponent's wait and exploit the psychological cost of sustained near-violation tension.",
        "stat_signature": "Near-limit deliveries (>85% of shot-clock window used) >30% of service games; near-limit routine uncorrelated with first-serve errors (<3%) confirms it is volitional, not fatigue-driven.",
        "mechanism": "Extended near-limit waits induce anticipatory arousal that peaks and must sustain beyond the optimal window, increasing pre-contact muscular tension and degrading split-step smoothness.",
        "conditions": "Most potent against opponents who require tight routine consistency to time their split-step; less impactful on those who deliberately delay preparation until ball toss.",
        "magnitude": "Return-in-play rate falls ~6 pp in sets with >30% near-limit routines; first-return error spikes ~9 pp on near-limit deliveries versus routine-timed serves.",
        "links": ["serve_routine_tempo_variation", "between_point_pace_disruption", "between_game_pace_management"],
    },
    {
        "slug": "depth_variation_to_disrupt_spacing",
        "title": "Depth Variation to Disrupt Spacing",
        "summary": "Mixing deep and short balls to break an opponent's court-position rhythm, with within-rally bounce-depth variance and positioning-error rate as primary metrics.",
        "stat_signature": "Within-rally bounce-depth SD >2 m; short-ball rate (bounce inside service box) >15% of rally groundstrokes; opponent mid-court positioning error rises to 22% versus 9% in depth-consistent rallies.",
        "mechanism": "Constant depth allows opponents to anchor at a fixed court position; injecting a short ball forces a sprint forward while a subsequent deep ball punishes recovery — creating a physically draining oscillation.",
        "conditions": "Effective on clay where physical recovery sprints are more demanding; against deep-positioning opponents; requires sufficient net clearance on short balls to avoid errors.",
        "magnitude": "Deep–short–deep three-ball sequences force opponent mid-court error or short reply at ~38% versus 14% in uniform-depth exchanges; point-win probability rises ~10 pp on the fourth ball.",
        "links": ["drop_shot_tempo_interruption", "change_of_pace_off_pace_ball", "moon_ball_rhythm_break", "return_tempo_imposition"],
    },
    {
        "slug": "return_tempo_imposition",
        "title": "Return Tempo Imposition",
        "summary": "Taking the return early (inside the baseline) to rush the server's transition into the rally, compressing their recovery window before the second shot.",
        "stat_signature": "Contact inside baseline on >40% of returns; server time-to-contact on the next shot reduced ~0.4 s; server forced error on shot 2 rises 6–9 pp against early-return opponents.",
        "mechanism": "Early contact returns the ball at higher speed with reduced flight time, compressing the server's repositioning window; the server is frequently still in serve-motion recovery when the return arrives.",
        "conditions": "Most effective against servers with slow first-move or wide serves that leave them out of court; requires return precision to avoid error inflation at the aggressive contact point.",
        "magnitude": "Early-return sets show server second-shot forced-error rates ~8 pp above match average; break-point conversion is ~5 pp higher in games with >40% inside-baseline contact.",
        "links": ["quick_serve_to_rush_returner", "first_strike_tempo_acceleration", "serve_plus_one_tempo_pressure", "deep_return_tempo_reset"],
    },
    {
        "slug": "tempo_consistency_as_anchor",
        "title": "Tempo Consistency as a Timing Anchor",
        "summary": "Maintaining a steady personal cadence to neutralize an opponent's disruption attempts; low variance of own preparation and contact timing across opponent pace changes is the signal.",
        "stat_signature": "Own inter-point SD <4 s regardless of opponent routine variance; contact-point height SD <0.1 m across a range of incoming speeds; error-rate change against disruption attempts <3 pp.",
        "mechanism": "Internalizing a consistent routine and swing-trigger removes opponent-imposed timing cues from the motor-control loop, insulating the player from external tempo manipulation.",
        "conditions": "Most valuable against active disruptors who vary pace and routine widely; functions as a passive defensive trait whose importance scales with the opponent's tempo arsenal breadth.",
        "magnitude": "Players with inter-point SD <3 s maintain error rates within 2 pp when facing disruption specialists versus a 7 pp average rise for tempo-sensitive opponents.",
        "links": ["between_point_pace_disruption", "serve_routine_tempo_variation", "tempo_variance_as_unpredictability_tennis", "change_of_rhythm_after_break_point"],
    },
    {
        "slug": "pace_baiting_to_force_overhit",
        "title": "Pace-Baiting to Force the Overhit",
        "summary": "Feeding an inviting slower ball to tempt an opponent into a low-percentage power swing, measured by unforced-error conversion on aggressive replies to mid-pace deliveries.",
        "stat_signature": "Mid-pace deliveries (50–70 km/h, slightly high bounce) >20% of rally shots; opponent winner attempts off these balls >35%; unforced error on aggressive replies to mid-pace balls is 22–28% versus 12% on fast-incoming balls.",
        "mechanism": "A slower inviting ball triggers an automatic power-generation response; the resulting over-swing compresses margins and increases frame contact or net-clearance error, turning an apparent opportunity into a liability.",
        "conditions": "Most effective against aggressive baseliners conditioned to accelerate on perceived short or slow balls; less effective against disciplined players who moderate swing speed to incoming pace.",
        "magnitude": "Point-win probability on pace-bait sequences is ~58% for the baiter versus ~42% for the swinger; unforced errors account for 55–65% of all opponent mistakes on mid-pace baiting rallies.",
        "links": ["change_of_pace_off_pace_ball", "rally_speed_modulation", "tempo_variance_as_unpredictability_tennis"],
    },
    {
        "slug": "serve_plus_one_tempo_pressure",
        "title": "Serve-Plus-One Tempo Pressure",
        "summary": "Pairing a fast serve with an immediate aggressive follow-up to compress the time available to the opponent before they can recover court position.",
        "stat_signature": "Server-to-next-shot interval <0.8 s after a 180+ km/h serve; plus-one finish rate (winner or forced error on shot 3) >35%; second-shot placement within 0.5 m of open court on >55% of attempts.",
        "mechanism": "A fast serve limits return quality and court position; the immediate aggressive follow-up arrives before the opponent can recover from a scrambled return, closing the point before balance is restored.",
        "conditions": "Most potent on fast surfaces where serve speed is highest and return time shortest; requires placement accuracy to generate returner displacement, not merely raw speed.",
        "magnitude": "Service games with >30% plus-one finishes are won at ~82% versus ~72% in non-plus-one-dominant games; break-point saved rate rises ~8 pp when the plus-one is successfully executed.",
        "links": ["first_strike_tempo_acceleration", "return_tempo_imposition", "quick_serve_to_rush_returner"],
    },
    {
        "slug": "deep_return_tempo_reset",
        "title": "Deep-Return Tempo Reset",
        "summary": "Using a high, deep return to slow the server's first-strike intent and equalize the rally, measured by return depth, flight time, and suppression of server plus-one aggression.",
        "stat_signature": "Return bounce within 1 m of baseline on >50% of first-serve returns; flight time >0.9 s; server plus-one winner or forced-error rate drops to 18–22% versus 30% against short returns.",
        "mechanism": "A deep return pushes the server back and negates positional serve advantage; extra time from high bounce depth allows the returner to recover position and transition from reactive defense to neutral.",
        "conditions": "Effective against servers whose tactical plan is built on the serve-plus-one pattern; most valuable on medium and fast surfaces where the first-strike threat is greatest.",
        "magnitude": "Return-game win rate increases ~5 pp when deep-return rate exceeds 50%; server is forced into neutral rally mode on 60–70% of points versus 35% when return depth is shallow.",
        "links": ["return_tempo_imposition", "serve_plus_one_tempo_pressure", "moon_ball_rhythm_break"],
    },
    {
        "slug": "tempo_variance_as_unpredictability_tennis",
        "title": "Tempo Variance as Unpredictability",
        "summary": "Maintaining a wide distribution of shot speeds and rally cadences so the opponent cannot settle into reliable anticipation, measured by the spread of ball-speed and rally-length values across a match.",
        "stat_signature": "Match-level ball-speed interquartile range >55 km/h; rally-length CV (std/mean) >0.8; opponent error rate rises 6–10 pp in sets where the player's speed distribution is widest.",
        "mechanism": "Anticipation is largely pattern-matched; a wide speed and rhythm distribution prevents the opponent from building reliable priors, forcing longer information-wait before committing — degrading reaction speed and footwork.",
        "conditions": "Most effective against methodical pattern-players who rely on reading tendencies; requires sufficient technical range to execute the full speed spectrum without incurring personal error inflation.",
        "magnitude": "Opponents facing high-variance players commit ~9 pp more anticipation errors (wrong-footed or direction-mismatch) than against consistent-pace opponents; rally-length variance compounds physical fatigue asymmetrically across sets.",
        "links": ["rally_speed_modulation", "between_point_pace_disruption", "pace_baiting_to_force_overhit", "tempo_consistency_as_anchor"],
    },
]
