"""MLB TempoVariation concept nodes — person-free within-at-bat rhythm and timing intelligence."""
from __future__ import annotations

SPORT = "MLB"
FAMILY = "TempoVariation"

CONCEPTS: list[dict] = [
    {
        "slug": "pitch_tempo_disruption_of_timing",
        "title": "Pitch-Tempo Disruption of Hitter Timing",
        "summary": "A pitcher varying time-between-pitches within a single plate appearance degrades the hitter's internal clock, measurable as the within-at-bat standard deviation of inter-pitch seconds and the resulting swing-timing errors on subsequent pitches.",
        "stat_signature": "Within-at-bat inter-pitch standard deviation above 4 s flags high-variation pitchers; exit velocity on pitches delivered in the lowest-quartile tempo slot of a PA runs 2.5–4.5 mph below the hitter's same-outing average; swing-and-miss rate premium on tempo-varied PAs reaches 5–8 percentage points above flat-tempo baselines.",
        "mechanism": "Swing motor programs are calibrated to a narrow pitch-arrival window; delivery timing outside that window forces premature initiation or late hesitation; the imprecision compounds when tempo shifts accompany pitch-type or velocity changes, because the hitter faces simultaneous temporal and perceptual uncertainty that degrades both contact quality and decision accuracy.",
        "conditions": "Largest effect against rhythm-dependent load-trigger hitters; diminished against pure-reaction mechanical approaches that do not rely on a pre-programmed timing window; most disruptive in two-strike counts where the hitter cannot afford a take and must commit early.",
        "magnitude": "High-variation pitchers (within-PA SD above 4 s) generate whiff rates roughly 5–8 percentage points above their own flat-tempo baseline; contact on their lowest-tempo delivery of each PA shows hard-contact rate depressed by 6–9 percentage points relative to the same pitcher's league-average contact profile.",
        "links": ["quick_pitch_rhythm_break", "tempo_acceleration_when_ahead_in_count", "varied_set_hold_duration", "deliberate_slow_curveball_pace", "tempo_as_count_leverage_tool"],
    },
    {
        "slug": "quick_pitch_rhythm_break",
        "title": "Quick-Pitch Rhythm Break",
        "summary": "Delivering a pitch noticeably faster than the established cadence catches a hitter mid-reset, signatured by an inter-pitch interval well below the at-bat's rolling mean and the resulting take-or-late-swing elevation on the subsequent offering.",
        "stat_signature": "Quick pitches defined as deliveries arriving more than 3 s earlier than the prior two-pitch rolling mean; take rate on quick-pitch deliveries rises 8–12 percentage points above the pitcher's overall take rate; late-swing contact (EV below 85 mph) frequency doubles on quick pitches for hitters averaging above 3.90 P/PA.",
        "mechanism": "The hitter's load sequence — stride initiation, hip rotation, hand launch — is triggered off a learned tempo cue; an unexpectedly early delivery interrupts that sequence mid-stage, forcing an aborted swing or a rushed contact attempt that collapses the kinetic chain; the quick pitch is most effective when paired with a pitch type that differs from the hitter's expectation.",
        "conditions": "Most disruptive against deep-count hitters who establish deliberate between-pitch routines; least effective against free-swingers who stay mechanical without a rhythm reset; pitch-clock constraints cap the slow end of the tempo range but do not restrict fast deliveries, preserving the full quick-pitch tool.",
        "magnitude": "Exit velocity on late-swing contact following a quick pitch averages 3–5 mph below the hitter's overall contact average; strikeout probability within the same PA rises approximately 10–15 % when a quick pitch precedes a two-strike offering.",
        "links": ["pitch_tempo_disruption_of_timing", "rhythm_disruption_via_pitch_clock_edge", "no_windup_quick_delivery_rhythm", "batter_box_re_entry_tempo"],
    },
    {
        "slug": "deliberate_pace_slowdown_with_runners",
        "title": "Deliberate Pace Slowdown With Runners On",
        "summary": "Lengthening time-between-pitches in high-leverage base states allows the pitcher to manage the running game and reset rhythm, measured by the inter-pitch interval delta between empty-base and runners-on states.",
        "stat_signature": "Average inter-pitch interval delta (runners-on minus empty bases) for MLB pitchers: 4–7 s; pitchers with delta above 9 s invest heavily in running-game management; tempo delta correlates with stolen-base suppression at r approximately 0.38 within pitcher-season panels.",
        "mechanism": "Additional cognitive sub-routines — pickoff sequencing, sign security, lead-distance monitoring — each add processing time before a pitch can be initiated; the extended window also allows catcher and fielder communication to reset defensive positioning, converting the pace slowdown from a pure cost into a coordinated defensive preparation interval.",
        "conditions": "Slowdown most pronounced with first-and-second and man-on-second configurations where two-direction threat management is required; amplified in late-inning close games where the run-expectancy of an advancing baserunner is highest; pitchers near the disengagement-budget limit slow more because pickoff threats are constrained.",
        "magnitude": "Pitchers with widest empty-to-runners-on delta allow stolen-base attempts at rates 12–18 % above pitchers with sub-4 s delta; the slower pace in runners-on states also widens the pitch-clock compliance window for hitters who benefit from the additional reset time.",
        "links": ["step_off_and_reset_tempo", "varied_set_hold_duration", "runner_timing_disruption_holds", "pitch_tempo_disruption_of_timing"],
    },
    {
        "slug": "step_off_and_reset_tempo",
        "title": "Step-Off and Reset Tempo",
        "summary": "Rubber step-offs and disengagements interrupt both the hitter's rhythm and any baserunner's timing, quantified by disengagement frequency per plate appearance and the resulting shift in inter-pitch interval within the pitch-clock window.",
        "stat_signature": "Disengagement rate per PA with runners on: low-use pitchers below 0.35; high-use above 0.90; each step-off extends the effective inter-pitch interval perceived by the hitter by 3–6 s of additional reset burden; pitchers using two or more disengagements per PA with a runner on first suppress stolen-base success rate by 10–15 percentage points.",
        "mechanism": "A step-off forces the hitter to restart their timing sequence from a neutral state because the delivery cue has been reset; simultaneously the runner must reset their primary lead and jump-timing calibration; the dual disruption converts a single defensive action into simultaneous hitter and runner interference, compressing the effective offensive threat on both dimensions.",
        "conditions": "Most effective when alternated with normal-tempo deliveries so the hitter cannot settle into a new slow rhythm; diminished when the disengagement budget is nearly exhausted and the threat of a free advance neutralizes aggressive step-off usage; cold-weather games amplify the disruption because hitter muscle temperature drops during extended stoppages.",
        "magnitude": "High-disengagement pitchers (above 0.8 per PA with runners on) hold runners to sub-20 % stolen-base success rates in within-season samples; the associated hitter timing disruption manifests as a 3–5 percentage-point rise in first-pitch-take rate following a step-off.",
        "links": ["varied_set_hold_duration", "runner_timing_disruption_holds", "deliberate_pace_slowdown_with_runners", "mound_visit_tempo_interruption"],
    },
    {
        "slug": "varied_set_hold_duration",
        "title": "Varied Set-Hold Duration",
        "summary": "Changing how long the set position is held before delivery creates timing ambiguity for both the timing-dependent hitter and the baserunner calibrating their jump, measured by the variance of hold-time and its correlation with first-pitch outcome quality.",
        "stat_signature": "Hold-time variance above 1.5 s standard deviation per outing flags elite variators; first-pitch-swing contact rate drops 4–7 percentage points against high-variance holders compared with constant-hold pitchers; stolen-base jump-timing error rate (early or late break) rises 8–12 % against pitchers with hold SD above 1.5 s.",
        "mechanism": "Hitters build an internal probability model of delivery timing from early-PA observations; high hold-time variance prevents convergence of that model, sustaining uncertainty through late pitches; for baserunners the hold variance similarly disrupts the anticipatory muscle-activation sequence required for an optimal first-step break.",
        "conditions": "Most impactful in the first two plate appearances against a starter, before hitters have accumulated enough within-game observations to recalibrate; diminished for hitters using pre-loaded mechanical triggers that ignore hold duration entirely; amplified in high-leverage late innings where a mistimed jump on a steal attempt has maximum game impact.",
        "magnitude": "Pitchers with hold SD above 1.5 s suppress first-pitch hard contact rates by approximately 6–9 percentage points relative to same-arsenal pitchers with hold SD below 0.8 s; stolen-base attempt frequency drops 18–25 % against high-variance holders across multi-season samples.",
        "links": ["step_off_and_reset_tempo", "pitch_tempo_disruption_of_timing", "deliberate_pace_slowdown_with_runners", "runner_timing_disruption_holds"],
    },
    {
        "slug": "tempo_acceleration_when_ahead_in_count",
        "title": "Tempo Acceleration When Ahead in Count",
        "summary": "Working faster in pitcher-favorable counts denies the hitter additional reset time and raises first-pitch-after-strike urgency, captured as the inter-pitch interval difference between ahead-in-count and behind-in-count pitches within a single outing.",
        "stat_signature": "Median inter-pitch seconds in 0-2 counts for tempo-accelerating pitchers: 11–13 s versus their 2-0 count median of 14–17 s; the count-leverage tempo delta exceeds 3 s for pitchers who consciously vary pace by count; whiff rate on the pitch after an 0-2 acceleration delivery rises 4–6 percentage points for timing-dependent hitters.",
        "mechanism": "A pitcher ahead in the count has already restricted the hitter's available pitches; accelerating further compresses the hitter's cognitive budget, stacking temporal and situational pressure simultaneously; the compound effect of count deficit plus rhythm disruption produces more reactive, less selective swings on pitches at or outside the zone edge.",
        "conditions": "Most effective against disciplined hitters who use elongated between-pitch routines to reset focus; least effective against aggressive hitters who already commit early regardless of count; works best when paired with a pitch type that exploits the hitter's default two-strike swing adjustment.",
        "magnitude": "Pitchers with a documented count-tempo delta above 3 s show putaway strikeout rates 2–4 percentage points above their two-strike average at flat tempo; wOBA-against in 0-2 counts drops approximately 15–25 points for high-tempo-acceleration pitchers relative to constant-pace pitchers with equivalent arsenal quality.",
        "links": ["pitch_tempo_disruption_of_timing", "tempo_as_count_leverage_tool", "tempo_shift_after_hard_contact", "time_to_first_pitch_strike"],
    },
    {
        "slug": "rhythm_disruption_via_pitch_clock_edge",
        "title": "Rhythm Disruption at the Pitch-Clock Edge",
        "summary": "Timing the delivery near the clock limit maximizes the hitter's legal wait while remaining compliant, measured by the distribution of delivery-start time relative to clock expiration and the rate of near-limit-window pitches.",
        "stat_signature": "Pitchers averaging delivery-start with 2–4 s remaining on the clock operate in the near-limit window; rate of pitches delivered in the final 3 s of the clock above 35 % identifies systematic edge-workers; hitter swing-decision latency (time from release to swing initiation) degrades by approximately 5–8 ms on near-limit deliveries.",
        "mechanism": "The hitter's optimal strategy is to load and trigger their swing sequence on a consistent pre-delivery cue; a near-limit delivery forces the hitter to wait through the maximum legal uncertainty window before the delivery cue arrives, compressing the reaction interval between pitch-initiation and plate crossing; the legal maximum-wait strategy effectively shifts tempo management leverage to the pitcher without rule violation.",
        "conditions": "Most disruptive against hitters who use the pitcher's motion initiation as their primary load cue rather than a fixed internal timer; diminished for hitters who pre-load early and hold, accepting some mechanical inefficiency to neutralize the wait; amplified when combined with a varied pitch arsenal where the pitch type is uncertain until late in the delivery.",
        "magnitude": "Near-limit-window pitches generate take rates approximately 6–9 percentage points above league average because the compressed reaction interval favors takes over swings; contact quality on swings against near-limit deliveries shows hard-hit rate depressed by 5–7 percentage points.",
        "links": ["quick_pitch_rhythm_break", "pitch_tempo_disruption_of_timing", "tempo_acceleration_when_ahead_in_count", "batter_box_re_entry_tempo"],
    },
    {
        "slug": "batter_box_re_entry_tempo",
        "title": "Batter-Box Re-Entry Tempo",
        "summary": "A hitter's deliberate timeout-style stepping out slows a fast-working pitcher and resets their own timing, quantified by the frequency of box exits and the resulting increase in effective inter-pitch interval against tempo-driven pitchers.",
        "stat_signature": "Hitters averaging above 1.2 step-outs per PA against sub-13-second-tempo pitchers are active rhythm disruptors; the single granted timeout per PA limits formal exits; actual inter-pitch interval following a granted timeout extends by 1.5–2.5 s as the pitcher re-initiates; step-out frequency correlates with wOBA-against fast-workers at r approximately 0.30.",
        "mechanism": "A well-timed step-out interrupts the pitcher's delivery momentum and forces a full sequence restart; from the hitter's perspective it extends the effective preparation window and breaks the cadence disadvantage imposed by a fast worker; the one-timeout constraint forces strategic timing — the break is most valuable when the hitter is losing the rhythm contest.",
        "conditions": "Highest value against pitchers with inter-pitch averages below 13 s where the rhythm disruption is most meaningful; lowest against slow-tempo pitchers who already provide natural reset time; strategic deployment in two-strike counts forces an additional deliberation window before a putaway pitch at the cost of exhausting the timeout budget.",
        "magnitude": "Hitters who deploy their timeout in the fourth or later pitch of a fast-tempo PA show wOBA approximately 20–30 points above their pre-timeout rate in the same PA; the subsequent inter-pitch extension after a granted timeout widens pitch-location variance by approximately 0.8–1.2 inches for the pitcher's next delivery.",
        "links": ["quick_pitch_rhythm_break", "rhythm_disruption_via_pitch_clock_edge", "tempo_consistency_as_anti_disruption", "pitch_tempo_disruption_of_timing"],
    },
    {
        "slug": "tempo_consistency_as_anti_disruption",
        "title": "Tempo Consistency as Anti-Disruption",
        "summary": "A hitter maintaining a fixed pre-pitch routine neutralizes tempo manipulation by anchoring their load trigger to an internal clock rather than the pitcher's cadence, measured by the low variance of the hitter's actual swing-initiation timing across different pitcher tempo profiles.",
        "stat_signature": "Hitters with swing-initiation timing CV (coefficient of variation) below 8 % across varied-tempo pitchers are robust anti-disruption practitioners; their wOBA drops only 5–10 points against tempo-variable pitchers versus 20–35 points for high-CV hitters facing the same opponents; first-pitch-swing rate remains stable within 2 percentage points regardless of pitcher tempo quartile.",
        "mechanism": "An internally anchored timing mechanism decouples swing preparation from the pitcher's delivery cue; the hitter uses a fixed self-referenced countdown that begins at a consistent point in the pitcher's set, making inter-pitch interval variation irrelevant to the load sequence; this approach sacrifices some pitch-read time at the fast end but eliminates the timing degradation caused by tempo disruption.",
        "conditions": "Most effective against extreme tempo-variation pitchers who change cadence aggressively; requires sacrifice in reactivity against elite velocity where the fixed-trigger approach leaves insufficient time for late pitch-type identification; most prevalent among contact-oriented hitters who prioritize consistent mechanical timing over maximum swing-decision quality.",
        "magnitude": "High-tempo-consistency hitters (CV below 8 %) show roughly 15–20 % lower whiff-rate elevation against tempo-variable pitchers compared with rhythm-dependent hitters facing the same pitcher pool; their strikeout rate advantage in high-tempo-variation matchups reaches 2–4 percentage points.",
        "links": ["batter_box_re_entry_tempo", "pitch_tempo_disruption_of_timing", "quick_pitch_rhythm_break", "tempo_acceleration_when_ahead_in_count"],
    },
    {
        "slug": "mound_visit_tempo_interruption",
        "title": "Mound-Visit Tempo Interruption",
        "summary": "Permitted mound visits break an opposing hitting rhythm or a pitcher's own runaway pace, with the pace and outcome shift in plate appearances immediately following a visit serving as the measurable signal.",
        "stat_signature": "wOBA-against in the three PAs following a mound visit drops approximately 25–40 points below the pitcher's same-game average; first-pitch-strike rate in the post-visit PA rises 3–5 percentage points; the effect decays after three batters, reverting to the pre-visit baseline by the fourth post-visit PA.",
        "mechanism": "A mound visit halts all activity, resetting both the pitcher's mechanical focus and the hitter's accumulated rhythm data from prior PA observations; the pitcher uses the break to realign arm path, adjust grip, or refine location intent; the hitter who had calibrated timing against the prior pace must restart from an uncalibrated state.",
        "conditions": "Visit-interruption value is highest mid-rally when consecutive baserunners have activated leverage above 1.5; the limited cap (five per game) forces prioritization of high-leverage moments; visits used for pure rhythm-reset (no injury evaluation, no pitching change) show smaller but still positive command-quality dividends for the subsequent inning.",
        "magnitude": "Teams deploying a mound visit during a three-consecutive-baserunner sequence suppress scoring-inning run expectancy by an estimated 0.25–0.45 runs per visit; the command-reset benefit accounts for roughly half of this suppression, with the hitter rhythm disruption accounting for the other half.",
        "links": ["step_off_and_reset_tempo", "tempo_shift_after_hard_contact", "pitch_tempo_disruption_of_timing", "deliberate_pace_slowdown_with_runners"],
    },
    {
        "slug": "tempo_shift_after_hard_contact",
        "title": "Tempo Shift After Hard Contact",
        "summary": "Slowing pace after a loud out or a hit allows the pitcher to reset mechanically and cognitively, measured by the inter-pitch interval delta in pitches immediately following a high-exit-velocity ball in play.",
        "stat_signature": "Inter-pitch interval in the three pitches after an EV-above-100-mph contact event: average extension of 1.8–3.2 s above the pitcher's within-inning baseline; pitchers who extend pace by less than 1 s after hard contact show ERA in subsequent same-inning PAs roughly 0.25 runs higher than pitchers who absorb the full reset window.",
        "mechanism": "Hard contact is a physiological and psychological stressor that disrupts arm-path consistency and narrows attentional focus; the additional seconds permit grip re-check, breath regulation, and the sign-re-establishment sequence that restores the pitcher's mechanical reference frame before the next delivery; skipping this reset perpetuates the mechanical imprecision that often generated the hard contact in the first place.",
        "conditions": "Reset pause is most consequential for pitchers whose mechanics are sensitive to stress-induced arm-slot variation; less necessary for mechanically robust pitchers who maintain consistent release points under duress; the pitch-clock caps the maximum reset window, preventing unlimited recovery time and maintaining pace integrity.",
        "magnitude": "Pitchers absorbing the full 1.5–3 s reset after hard contact show command-metric recovery (zone rate, edge rate) returning to within-game baseline within two pitches; those who skip the reset show command degradation persisting for 3–5 pitches, corresponding to an expected-runs cost of approximately 0.08–0.14 per inning.",
        "links": ["pitch_tempo_disruption_of_timing", "mound_visit_tempo_interruption", "tempo_acceleration_when_ahead_in_count", "tempo_fatigue_drift_late_outing"],
    },
    {
        "slug": "runner_timing_disruption_holds",
        "title": "Runner Timing-Disruption Holds",
        "summary": "Slide-step and variable-hold tactics scramble a baserunner's jump timing, measured by hold-time variance with runners on and its association with stolen-base success suppression.",
        "stat_signature": "Hold-time SD above 1.2 s with runner on first suppresses stolen-base success rate to below 65 % in same-pitcher samples; slide-step delivery reduces catcher pop-time advantage by approximately 0.10–0.15 s relative to full-windup delivery; combined slide-step-and-variable-hold pitchers allow fewer than 0.9 stolen-base attempts per nine innings on average.",
        "mechanism": "A baserunner calibrates their primary lead and jump timing against the pitcher's observed hold pattern; hold variance invalidates that calibration, forcing the runner into a reactive jump off visual delivery-motion cues rather than a pre-timed anticipatory break; the reactive approach reduces first-step efficiency and increases the catcher's effective window to retire the runner.",
        "conditions": "Most effective against pure-speed runners who rely on anticipatory jump timing rather than raw post-delivery reaction; diminished against patient runners who wait for an explicit go trigger regardless of hold duration; amplified when the catcher possesses an above-average pop time that already narrows the break window independently.",
        "magnitude": "Pitchers combining slide-step and hold-time variance suppress stolen-base success rates by approximately 10–15 percentage points below league average for the same runner pool; hold-variance alone (without slide-step) achieves roughly 60 % of that suppression.",
        "links": ["varied_set_hold_duration", "step_off_and_reset_tempo", "deliberate_pace_slowdown_with_runners", "pitch_tempo_disruption_of_timing"],
    },
    {
        "slug": "deliberate_slow_curveball_pace",
        "title": "Deliberate Slow Pace Around Off-Speed",
        "summary": "Pairing a longer pre-pitch interval with off-speed offerings compounds timing disruption by adding temporal uncertainty on top of velocity contrast, captured by the joint distribution of inter-pitch interval and pitch type and the resulting swing-timing miss rate.",
        "stat_signature": "Off-speed pitches preceded by inter-pitch intervals above 16 s generate swing-and-miss rates 6–10 percentage points above the same pitcher's off-speed whiff rate at normal tempo; early-swing rate (bat contact before optimal contact zone) rises 4–7 percentage points when a slow-tempo off-speed follows a faster-tempo fastball in the same PA.",
        "mechanism": "The hitter calibrates swing timing to the established cadence; a slower pre-pitch interval relaxes the load-trigger timing while the slower off-speed pitch compounds the disruption by arriving later than the recalibrated fastball expectation; the two delays stack multiplicatively — the hitter expects both quicker delivery and faster pitch velocity, producing double-mismatch on timing.",
        "conditions": "Most impactful against hitters with high-velocity chase tendencies who over-adjust their swing timing to the pace signal; diminished against hitters who have demonstrated stable timing across tempo regimes; requires a genuine velocity differential (at least 8 mph between fastball and off-speed) for the compound effect to be statistically meaningful.",
        "magnitude": "Combined slow-tempo-plus-off-speed sequences generate early contact rates 5–8 percentage points above the same pitcher's off-speed contact rate at normal tempo; average exit velocity on this sequence drops 4–6 mph below the hitter's off-speed contact average in non-tempo-varied sequences.",
        "links": ["pitch_tempo_disruption_of_timing", "tempo_as_count_leverage_tool", "tempo_acceleration_when_ahead_in_count", "varied_set_hold_duration"],
    },
    {
        "slug": "tempo_as_count_leverage_tool",
        "title": "Tempo as Count-Leverage Tool",
        "summary": "Systematically pairing pace changes with count state keeps hitters guessing independently of pitch selection, measured by the interaction between inter-pitch interval variance and count, controlling for pitch-type effects.",
        "stat_signature": "Pitchers with documented count-tempo interactions (Pearson r between count leverage and inter-pitch interval above 0.25) show 3–5 percentage-point whiff-rate premiums above pitchers with flat count-tempo profiles; in 2-0 counts, tempo-tool pitchers average 1.5–2.5 s faster than their 0-2 baselines; the tempo contribution to swing-decision error is measurable at roughly 15–20 % of the total whiff-rate premium after controlling for pitch quality.",
        "mechanism": "Count state is a high-salience hitter cue that triggers mechanical and cognitive adjustments; layering tempo variation onto the count-state signal introduces a second independent source of uncertainty that prevents the hitter from fully solving either dimension; the tempo variation is most useful when it is genuinely independent of pitch type so the hitter cannot use pitch-type expectation to offset the timing disruption.",
        "conditions": "Works best for pitchers with a four-pitch arsenal who are not predictably count-to-pitch-type mapped; diminished for pitchers with strong count-type tendencies that hitters can exploit by solving the pitch-type before the tempo signal; most effective in the second and third time through the lineup when hitters have solved the arsenal but not yet the tempo pattern.",
        "magnitude": "Independent tempo-variation pitchers holding a count-leverage correlation above 0.25 suppress wOBA in two-strike counts by approximately 10–18 points beyond what their raw pitch quality predicts; the tempo contribution to strikeout probability in 0-2 counts is estimated at 0.03–0.06 probability units above flat-tempo equivalents.",
        "links": ["tempo_acceleration_when_ahead_in_count", "deliberate_slow_curveball_pace", "pitch_tempo_disruption_of_timing", "varied_set_hold_duration"],
    },
    {
        "slug": "reliever_entry_tempo_signature",
        "title": "Reliever-Entry Tempo Signature",
        "summary": "A relief arm's distinct working pace relative to the removed starter imposes a fresh timing problem on the lineup, quantified by the inter-pitch interval delta across the pitching change and its effect on the first batter faced.",
        "stat_signature": "Inter-pitch interval delta (reliever minus starter) exceeds 3 s in either direction for approximately 35 % of same-game pitching changes; first-batter-faced wOBA for relievers entering 3-plus seconds faster than the departed starter is 18–28 points below the reliever's season average first-batter-faced wOBA; the tempo-shift advantage decays substantially by the third PA after entry.",
        "mechanism": "A hitter who has calibrated to the starter's cadence over multiple plate appearances must rebuild the timing model from scratch for the reliever; when the reliever's tempo is substantially different from the starter's, the recalibration lag — approximately 2–4 pitches — creates a window where the hitter is mechanically committed to the wrong timing, producing contact-quality degradation independent of pitch quality.",
        "conditions": "Largest impact when the reliever's tempo is at the opposite extreme from the starter's; diminished when the reliever matches the starter's tempo closely, reducing the recalibration burden; amplified when the reliever also offers a substantially different velocity or pitch-type profile, stacking multiple adjustment demands simultaneously.",
        "magnitude": "Relievers entering with a 4-plus-second tempo acceleration above the starter's median generate first-PA K rates approximately 4–6 percentage points above their season average; the tempo-disruption effect accounts for an estimated 20–30 % of the reliever-entry strikeout premium after controlling for matchup favorability.",
        "links": ["pitch_tempo_disruption_of_timing", "tempo_shift_after_hard_contact", "mound_visit_tempo_interruption", "tempo_acceleration_when_ahead_in_count"],
    },
    {
        "slug": "tempo_fatigue_drift_late_outing",
        "title": "Tempo Fatigue Drift Late in an Outing",
        "summary": "A pitcher's working pace involuntarily lengthens as pitch count climbs, reflecting mounting physical and cognitive fatigue; the drift serves as an early warning signal for effectiveness decline before outcome statistics visibly degrade.",
        "stat_signature": "Inter-pitch seconds increase of 1.5–2.5 s from pitches 1–30 to pitches 76–100 for average starters; pitchers showing above 3 s of drift by pitch 70 are in the top fatigue-signal quartile; pace-drift slope correlates with spin-rate decay at r approximately 0.40 and command-zone-rate drop at r approximately 0.35 in pitch-tracking samples.",
        "mechanism": "Fatigue reduces fast-twitch recruitment efficiency and slows the mental processing of sign-to-set-to-deliver sequencing; pitchers compensate by abbreviating their mechanical routine, but the abbreviated routine degrades location precision and reduces the ability to execute the pitch-type distribution variation that generated swing-and-miss earlier in the outing; the pace drift thus signals not just slower working pace but a narrowing of the effective arsenal.",
        "conditions": "Drift accelerates past 85 pitches for most starter profiles; heat and humidity amplify physiological fatigue, steepening the drift curve; pitchers with two-pitch arsenals show faster effective drift because reduced repertoire predictability compounds the mechanical decline; first-pass through the lineup establishes the baseline slope that predicts late-outing drift magnitude.",
        "magnitude": "Pitchers showing pace drift above 2 s by pitch 80 allow wOBA-against approximately 28–38 points higher in the final quarter of their pitch count relative to their first-quarter performance; the drift slope explains roughly 10–14 % of variance in same-start ERA beyond pitch count alone, representing an independent fatigue signal.",
        "links": ["tempo_shift_after_hard_contact", "tempo_acceleration_when_ahead_in_count", "pitch_tempo_disruption_of_timing", "reliever_entry_tempo_signature"],
    },
]
