"""Transition Dynamics — NBA concept-node spec. Person-free, descriptive only."""
from __future__ import annotations

SPORT = "NBA"
FAMILY = "TransitionDynamics"

CONCEPTS: list[dict] = [
    {
        "slug": "push_rate_after_defensive_rebound",
        "title": "Push Rate After Defensive Rebound",
        "summary": "Share of defensive-rebound possessions where the ball crosses midcourt within 7 seconds, separating teams that habitually trigger a full-speed advance from those that reset into half-court offense.",
        "stat_signature": "Sub-7-second midcourt crossing rate on defensive-rebound possessions; league spread 18-42 percent; top-quartile teams near 38+ percent.",
        "mechanism": "Securing the rebound before the outlet is thrown keeps defenders scrambling; each tenth of a second saved translates to a thinner defensive wall at the arc, raising the probability of an open early attempt.",
        "conditions": "Amplified against slow-recovering bigs; suppressed when opponents crash aggressively, sealing rebounders near the baseline and lengthening the outlet window.",
        "magnitude": "Top-quartile push-rate teams generate roughly 6-9 additional transition possessions per 100 defensive rebounds versus the bottom quartile, each carrying a noticeably higher PPP ceiling.",
        "links": ["outlet_pass_speed_and_length", "transition_efficiency_by_trigger", "transition_numbers_advantage_distribution", "kickahead_pass_versus_dribble_advance"],
    },
    {
        "slug": "live_ball_turnover_to_transition_conversion",
        "title": "Live-Ball Turnover Transition Conversion",
        "summary": "Share of opponent live-ball turnovers — steals and errant live passes — converted into a transition attempt within 6 seconds, with points-per-possession attached to those sequences.",
        "stat_signature": "Conversion rate 55-80 percent on steals; transition PPP on converted steal sequences 1.15-1.30; dead-ball-turnover PPP sub-1.05 as the defense resets during stoppage.",
        "mechanism": "A live steal leaves the offense directionally disorganized; the defender already faces the correct direction, creating an instantaneous numbers surplus that collapses if the break is not pushed within 4-6 seconds.",
        "conditions": "Highest conversion against teams with poor sprint-back discipline; diminished when the turnover occurs deep in the paint, where geometry limits the immediate push angle.",
        "magnitude": "Live-ball turnover sequences represent the highest-PPP transition trigger class, roughly 0.15-0.25 PPP above the half-court possession baseline; six-plus live-ball turnovers forced per game yield a measurable structural scoring advantage.",
        "links": ["transition_efficiency_by_trigger", "dead_ball_versus_live_ball_break_gap", "transition_numbers_advantage_distribution", "transition_self_inflicted_turnover_rate"],
    },
    {
        "slug": "outlet_pass_speed_and_length",
        "title": "Outlet Pass Speed and Length",
        "summary": "How quickly and how far the first pass after a defensive rebound advances the ball, captured as release latency in seconds and forward distance gained — the kinetic seed of break tempo.",
        "stat_signature": "Release latency median 0.8-1.4 seconds from rebound to outlet; outlet length 30-55 feet for elite break initiators; each 0.3-second latency reduction correlates with roughly a 5-point rise in midcourt-crossing rate.",
        "mechanism": "A long early outlet collapses the distance the ball must travel by dribble, cutting break time by 1-2 seconds versus a short reset pass and allowing the receiving guard to survey the floor earlier.",
        "conditions": "Advantage amplified against defenses with heavy bigs who do not sprint back; suppressed when the rebounder is sealed near the baseline with no clean outlet angle.",
        "magnitude": "Teams in the top quintile for outlet length produce breaks roughly 1.1-1.5 seconds faster to midcourt than bottom-quintile teams, structurally widening the numbers-advantage window.",
        "links": ["push_rate_after_defensive_rebound", "kickahead_pass_versus_dribble_advance", "guard_versus_big_rebound_outlet_initiation", "transition_shot_quality_decay_curve"],
    },
    {
        "slug": "transition_numbers_advantage_distribution",
        "title": "Transition Numbers-Advantage Distribution",
        "summary": "The mix of break situations by attacker-to-defender count and the PPP conversion gradient across them, from 3-on-1 through even situations.",
        "stat_signature": "PPP benchmarks: 3-on-1 ~1.50+, 2-on-1 ~1.35-1.45, 3-on-2 ~1.20-1.30, even transition ~1.08-1.15; the 3-on-2 bucket typically accounts for 35-50 percent of transition volume.",
        "mechanism": "Each additional defender in position forces one more decision cycle, decaying shot quality and increasing turnover probability; the structural value of a break is almost entirely determined by its numbers-advantage tier at the moment of attempt.",
        "conditions": "Numbers advantage is highest off live-ball turnovers near midcourt; collapses fastest when the pushing team is slow to fill lanes or when the defense sprints back in pairs.",
        "magnitude": "Shifting average break quality from 3-on-2 to 2-on-1 represents roughly 0.10-0.15 PPP per possession — equivalent in aggregate to a meaningful scoring-rate improvement across a full season.",
        "links": ["rim_run_trailer_geometry", "seconds_to_first_shot_distribution", "transition_efficiency_by_trigger", "getback_and_transition_defense_matchup"],
    },
    {
        "slug": "rim_run_trailer_geometry",
        "title": "Rim-Run and Trailer Geometry",
        "summary": "The spatial structure of lane-filling runners ahead of the ball at the rim and the trailing big arriving a beat later, including drag-screen frequency per transition possession.",
        "stat_signature": "Elite transition offenses average 1.4-1.9 runners at the rim before the ball arrives; trailer big-to-rim frequency 0.35-0.60 per transition possession; trailer catch-and-roll PPP ~1.18-1.28.",
        "mechanism": "A rim runner occupying the paint forces a helping defender to commit, opening the trailer and the skip pass to a corner shooter; without a runner, the back-pedaling defense can concentrate on the ball-handler alone.",
        "conditions": "Effective when the team includes a high-motor big willing to sprint the floor; suppressed when the offense is guard-heavy and bigs refuse to trail in transition.",
        "magnitude": "Teams with at least one reliable rim runner in transition generate 0.08-0.12 PPP more on those possessions than equivalent personnel groups without a runner, primarily through kicks to the open trailer or corner.",
        "links": ["transition_numbers_advantage_distribution", "transition_three_point_attack_rate", "semi_transition_early_offense_window", "cross_match_scramble_exposure"],
    },
    {
        "slug": "seconds_to_first_shot_distribution",
        "title": "Seconds-to-First-Shot Distribution",
        "summary": "The clock profile of how early the first attempt arrives, separating true transition from early-clock half-court offense, measured as attempt density across the 0-to-11-second shot-clock band.",
        "stat_signature": "0-4 seconds signals true fast break; 5-8 early offense; 9-14 organized half-court; top-pace teams place 22-30 percent of possessions in the 0-8 window versus 14-18 percent for deliberate teams.",
        "mechanism": "Shot quality decays monotonically as the clock advances because defenders finish recovery; the 0-8 window captures the period of structural openness before the defense organizes communication.",
        "conditions": "Distribution shifts toward early attempts against fatigued defenses, in back-to-back contexts, and against opponents who concede offensive rebounds producing secondary breaks.",
        "magnitude": "A one-percentage-point shift from the 14-24 second window into the 0-8 window is associated with roughly 0.02-0.04 PPP improvement in overall offensive efficiency, compounding over 100 possessions.",
        "links": ["transition_shot_quality_decay_curve", "semi_transition_early_offense_window", "push_rate_after_defensive_rebound", "transition_three_point_attack_rate"],
    },
    {
        "slug": "transition_three_point_attack_rate",
        "title": "Transition Three-Point Attack Rate",
        "summary": "The propensity to pull up or spot up for a perimeter shot in transition rather than always attacking the rim, measured as transition three-attempt share and conversion rate versus transition rim attempts.",
        "stat_signature": "Transition three-attempt share 18-38 percent across teams; open transition threes convert at 38-46 percent (eFG 57-69 percent), frequently matching transition rim rates once fouling is excluded.",
        "mechanism": "When the defense prioritizes stopping rim penetration, perimeter shooters trail into open catch-and-shoot positions; pulling up converts a partially closed lane into a high-value attempt before the defense re-closes.",
        "conditions": "Most effective when the trailing shooter operates in space before a second defender rotates; degraded when the offense lacks a credible rim threat, allowing the defense to shade the arc early.",
        "magnitude": "Teams with a high-volume transition three attack generate an eFG premium of 4-8 percentage points above their half-court three rate, reflecting structural openness during defensive scramble.",
        "links": ["rim_run_trailer_geometry", "seconds_to_first_shot_distribution", "transition_shot_quality_decay_curve", "semi_transition_early_offense_window"],
    },
    {
        "slug": "transition_efficiency_by_trigger",
        "title": "Transition Efficiency by Trigger Type",
        "summary": "Points-per-possession sliced by what initiated the break — steal, defensive rebound, opponent make, or dead ball — each carrying a distinct quality ceiling and structural frequency.",
        "stat_signature": "Benchmark PPP: steal 1.18-1.28, defensive rebound 1.12-1.20, opponent make 1.06-1.14, dead ball 0.98-1.08; frequency ordering typically inverts the quality ordering — makes and misses are most frequent.",
        "mechanism": "The defensive alignment at the moment of the trigger determines the initial numbers advantage; steals leave the offense directionally disordered whereas makes leave it directionally intact.",
        "conditions": "Trigger mix shifts with opponent strategy: aggressive offensive rebounding reduces defensive-rebound triggers; turnover-prone opponents elevate steal volume and its associated quality premium.",
        "magnitude": "The steal-to-make PPP gap of 0.12-0.20 per possession means 3 extra steals converted into transition per game yields roughly 0.4-0.6 additional net points from trigger composition alone.",
        "links": ["live_ball_turnover_to_transition_conversion", "dead_ball_versus_live_ball_break_gap", "push_rate_after_defensive_rebound", "transition_numbers_advantage_distribution"],
    },
    {
        "slug": "getback_and_transition_defense_matchup",
        "title": "Get-Back and Transition-Defense Matchup",
        "summary": "How effectively a defense retreats, walls the ball, and matches up before the break resolves, measured as transition PPP allowed and rim-attempt rate conceded per opponent push.",
        "stat_signature": "Elite transition defenses concede sub-1.05 PPP on opponent break possessions and hold rim-attempt share below 35 percent; the gap between best and worst transition defenses is roughly 0.15-0.20 PPP.",
        "mechanism": "The first retreating defender's path determines whether the ball-handler can drive freely; a defender who walls the ball and forces a kick-pass adds a decision cycle and reduces expected possession value.",
        "conditions": "Most critical after high-tempo offensive sets that leave multiple bodies far from defensive position; amplified when the scoring team has slow-footed bigs who are last to retreat.",
        "magnitude": "A move from bottom to top quartile in transition defense allowed represents a reduction of roughly 2-4 points per game via improved recovery and forced half-court resolutions.",
        "links": ["cross_match_scramble_exposure", "transition_numbers_advantage_distribution", "floor_balance_and_safety_valve_positioning", "transition_foul_draw_and_and_one_rate"],
    },
    {
        "slug": "cross_match_scramble_exposure",
        "title": "Cross-Match Scramble Exposure",
        "summary": "Mismatch and miscommunication exposure when retreating defenders pick up the nearest body rather than their assignment, measured as cross-match frequency and PPP on possessions where assignments do not settle before the attempt.",
        "stat_signature": "Cross-match occurs on 12-22 percent of transition defensive possessions for average teams; PPP on cross-match possessions is 8-16 percent higher than correctly matched possessions.",
        "mechanism": "When defenders sprint back in non-assignment lanes the offense immediately reads size and speed mismatches; an attacking ball-handler identifying a guard defending a screener can call an audible to exploit the cross.",
        "conditions": "Elevated after lane-fill spread patterns that force defenders to choose between nearest body and assignment; suppressed by nearest-body matchup-zone principles that treat nearest as the correct assignment.",
        "magnitude": "Teams avoiding systematic cross-match exposure limit transition eFG allowed by an estimated 3-6 percentage points relative to scramble-heavy defenses.",
        "links": ["getback_and_transition_defense_matchup", "rim_run_trailer_geometry", "transition_numbers_advantage_distribution"],
    },
    {
        "slug": "dead_ball_versus_live_ball_break_gap",
        "title": "Dead-Ball versus Live-Ball Break Quality Gap",
        "summary": "The efficiency gap between breaks off live-ball turnovers where the defense is directionally disordered and those off makes or dead balls where the defense retreats intact, measured as PPP difference between the two trigger classes.",
        "stat_signature": "PPP gap between live-ball and dead-ball triggers averages 0.10-0.20 per possession; live-ball sequences reach the rim at 45-55 percent versus 30-38 percent on dead-ball transitions of comparable clock depth.",
        "mechanism": "A live turnover displaces the defender at the point of disruption, creating an instant direction-of-play advantage; a dead-ball stoppage gives the retreating defense three-to-five seconds to recover, eliminating the structural dislocation.",
        "conditions": "Gap widens when live-ball turnovers occur above the three-point line where geometry allows an immediate rim run; collapses when the turnover is in the paint with minimal recovery distance.",
        "magnitude": "Across an 82-game season with 15-18 live-ball turnovers per game, the structural PPP gap compounds to roughly 20-35 additional transition points for teams that convert live steals at a high rate.",
        "links": ["live_ball_turnover_to_transition_conversion", "transition_efficiency_by_trigger", "push_rate_after_defensive_rebound"],
    },
    {
        "slug": "transition_foul_draw_and_and_one_rate",
        "title": "Transition Foul-Draw and And-One Rate",
        "summary": "The elevated free-throw and three-point-play rate when attackers reach the rim against a back-pedaling or late-rotating defense, measured as transition FTA per shot attempt and and-one frequency.",
        "stat_signature": "Transition FTA-per-field-goal attempt runs 15-28 percent above half-court rates for the same player profiles; and-one frequency on transition layups is 6-11 percent versus 3-5 percent in half-court contact situations.",
        "mechanism": "A retreating defender who has not established legal guarding position is structurally more likely to commit a moving-body foul; the attacker at full speed is harder to contest cleanly, raising both foul-draw and and-one rates.",
        "conditions": "Most pronounced when the rim-running attacker arrives against a single trailing defender; suppressed when two bodies are in the paint and the defense can choose the least-foul-risk contest.",
        "magnitude": "The transition foul premium represents roughly 0.05-0.10 additional expected points per trip versus a half-court possession for high-rim-attack transition teams, compounding significantly across high-volume break offenses.",
        "links": ["transition_numbers_advantage_distribution", "rim_run_trailer_geometry", "live_ball_turnover_to_transition_conversion"],
    },
    {
        "slug": "transition_self_inflicted_turnover_rate",
        "title": "Transition Self-Inflicted Turnover Rate",
        "summary": "The cost side of speed: live-ball giveaways generated by the attacking team's own push when decisions outrun ball control, measured as turnovers per 100 transition possessions.",
        "stat_signature": "Transition turnovers per 100 possessions ranges 7-18 across teams; top-quartile transition offenses hold this below 9 while averaging the highest push rates, identifying decision quality as the separating factor.",
        "mechanism": "Speed compresses decision windows; a ball-handler racing upcourt with less than 2 seconds per read is more likely to misidentify a defender's closing angle; risk is highest on kick-ahead passes to unsettled wings.",
        "conditions": "Elevated on teams where the primary initiator is not the rebounder, adding a hand-off decision layer under duress; reduced when the rebounder is also the ball-handler and can read the floor while catching.",
        "magnitude": "A team at 14 turnovers per 100 transition possessions versus 8 loses approximately 6-8 net points per 100 possessions from self-inflicted transition damage, offsetting much of the pace premium.",
        "links": ["kickahead_pass_versus_dribble_advance", "live_ball_turnover_to_transition_conversion", "guard_versus_big_rebound_outlet_initiation"],
    },
    {
        "slug": "semi_transition_early_offense_window",
        "title": "Semi-Transition Early-Offense Window",
        "summary": "The 5-to-11-second shot-clock band where the defense is nominally back but not fully organized, attacked via drag screens and early flow sets — measured as attempt share and PPP versus late-clock half-court possessions.",
        "stat_signature": "Early-window PPP typically 1.08-1.18 versus 0.96-1.05 late-clock; teams placing 20-plus percent of possessions in the 5-to-11-second band via drag-screen flow show offensive ratings 2-4 points above their late-clock baseline.",
        "mechanism": "A drag screen set at the three-point line before the defense completes communication exploits the brief disorganization window; the rolling big is guarded by a back-tracking wing rather than a rim-protecting big, elevating roll-catch conversion.",
        "conditions": "Requires a lead ball-handler who runs the floor at pace and a big willing to sprint to the nail for the screen; suppressed when opponents sprint back in pairs and communicate the screen switch before the initiator reaches the arc.",
        "magnitude": "A 5-percentage-point shift of possessions from late-clock to the early-offense window is estimated at 0.06-0.10 PPP aggregate improvement, comparable in value to a significant half-court scheme upgrade.",
        "links": ["seconds_to_first_shot_distribution", "transition_three_point_attack_rate", "rim_run_trailer_geometry", "transition_shot_quality_decay_curve"],
    },
    {
        "slug": "guard_versus_big_rebound_outlet_initiation",
        "title": "Rebound-and-Go Initiation by Rebounder Role",
        "summary": "Whether the rebounder pushes the ball themselves or kicks to a guard, and how that choice changes break speed and turnover risk, measured as self-advance share by rebounder role and resulting PPP.",
        "stat_signature": "Guard rebounders self-advance on 35-55 percent of their defensive-rebound pushes; big-man rebounders self-advance on 8-18 percent; self-advancing guard PPP roughly 0.05-0.10 higher than kick-to-guard variants on equivalent possessions.",
        "mechanism": "A guard with the ball already in hand in the open floor eliminates the outlet-reception step, compressing break time by 0.5-1.0 seconds; the big kicking to a guard creates a handling pause that allows one more defender to recover.",
        "conditions": "Self-advance is most efficient when the rebounder has a clear path and speed advantage; problematic when a big self-advances against a retreating defense because dribble pace is insufficient to exploit the window.",
        "magnitude": "Lineup configurations that place a fast-twitch rebounder at the outlet initiation role produce outlet-to-midcourt times roughly 0.6-1.1 seconds faster on average than configurations relying on big-to-guard kicks.",
        "links": ["outlet_pass_speed_and_length", "kickahead_pass_versus_dribble_advance", "transition_self_inflicted_turnover_rate", "push_rate_after_defensive_rebound"],
    },
]
