"""Tennis / VolatilityProfiles — dense, person-free concept-node spec."""
from __future__ import annotations

SPORT = "Tennis"
FAMILY = "VolatilityProfiles"

CONCEPTS: list[dict] = [
    {
        "slug": "serve_day_variance",
        "title": "Serve-Day Variance",
        "summary": "Match-to-match swing in serving effectiveness that drives hold reliability. SD of first-serve percentage and points-won-on-serve tracks how broadly a server's output fluctuates across tournaments.",
        "stat_signature": "First-serve-in SD ≥7 pp across matches = high day-to-day volatility; serve-points-won SD ≥5 pp marks structurally wide hold-rate swings; SD 3-4 pp = moderate.",
        "mechanism": "Toss consistency, ball-toss height, and wrist-snap timing fluctuate with wind and match intensity. A percentage drop forces a lower-quality second-serve regime, compounding hold-rate damage multiplicatively.",
        "conditions": "Most pronounced on outdoor hard courts with variable wind; amplified in early-tournament rounds before match rhythm settles; strongest in best-of-five where fatigue reaches later sets.",
        "magnitude": "Top-quartile serve-day SD holders hold at 10-15 pp lower rates on bad serve days relative to their seasonal average without compensating return gains.",
        "links": ["first_serve_dependency_swing", "ace_double_fault_balance_swing", "double_fault_clustering", "service_game_hold_volatility"],
    },
    {
        "slug": "error_streak_volatility",
        "title": "Error-Streak Volatility",
        "summary": "Temporal bunching of unforced errors into damaging runs rather than uniform distribution. Clustered errors concentrate within critical games, amplifying structural damage beyond what a total error count predicts.",
        "stat_signature": "Lag-1 autocorrelation of point-level error indicators ≥0.15 signals clustering; ≥20% of errors in streaks of 3+ consecutive error-games marks a high-bunching profile.",
        "mechanism": "One error elevates doubt, shortens backswing, and raises tension on the next attempt, creating a short-run positive-feedback loop. Conversely, clean spells build rhythm that suppresses errors below baseline for multiple points.",
        "conditions": "Strongest on clay where slow-ball pressure propagates errors across rallies; amplified when facing heavy topspin; present following contested break points regardless of outcome.",
        "magnitude": "High-bunching profiles concentrate 35-45% of all unforced errors in their worst five games of a set, representing only ~30% of points played.",
        "links": ["momentum_swing_volatility", "double_fault_clustering", "rhythm_dependency_variance", "clutch_point_dispersion"],
    },
    {
        "slug": "match_to_match_consistency",
        "title": "Match-to-Match Consistency Profile",
        "summary": "Stability of overall performance level across the schedule as a floor-reliability marker. Low-SD total-points-won profiles signal a predictable range; high-SD profiles indicate wide swings between dominant and passive performances.",
        "stat_signature": "SD of total-points-won percentage across ≥12 matches: <3 pp = high consistency; 3-5 pp = moderate; >5 pp = volatile. Requires surface-stratification for fair comparison.",
        "mechanism": "Consistency reflects the stability of technical foundations, physical preparation quality, and match-state management. Volatile profiles often reflect style-sensitivity where opponents drive swings more than internal form.",
        "conditions": "Most informative mid-season after ≥10 matches on a surface; less stable in early surface-season samples; draw difficulty inflates apparent SD if not adjusted.",
        "magnitude": "A one-SD swing (~6 pp) for a high-variance profile roughly corresponds to moving from competitive to comfortable relative to a similar-ranked opponent.",
        "links": ["serve_day_variance", "return_day_variability", "early_round_form_dispersion", "opponent_style_induced_variance"],
    },
    {
        "slug": "first_serve_dependency_swing",
        "title": "First-Serve Dependency Swing",
        "summary": "Heavy reliance on first-serve quality produces feast-or-famine hold patterns. A large first-serve versus second-serve points-won gap means a bad first-serve day collapses hold rate far below average, while a great day sharply elevates it.",
        "stat_signature": "First-serve-points-won minus second-serve-points-won ≥20 pp marks high dependency; combined with first-serve-in SD ≥7 pp, hold-rate variance is substantially elevated relative to players with gap <15 pp.",
        "mechanism": "Large gaps create two serve modes — dominant (first serve landing) and vulnerable (second serve landing). Since first-serve percentage fluctuates independently of game-state, hold outcomes inherit that randomness multiplicatively.",
        "conditions": "Amplified on fast surfaces where second-serve disadvantage is highest; emerges when opponents return exceptionally well, forcing more second-serve points and narrowing the safe zone.",
        "magnitude": "A 10 pp increase in first-serve-in rate raises hold rate by 4-6 pp for high-dependency servers versus only 1-2 pp for players with a smaller first/second gap.",
        "links": ["serve_day_variance", "ace_double_fault_balance_swing", "service_game_hold_volatility", "tiebreak_outcome_variance"],
    },
    {
        "slug": "tiebreak_outcome_variance",
        "title": "Tiebreak Outcome Variance",
        "summary": "High-leverage coin-flip swing of sudden-death tiebreaks where small samples dominate set outcomes. Tiebreak win rates show weak correlation with overall set dominance, making them among the noisiest sub-markets in tennis.",
        "stat_signature": "Tiebreak win-rate 95% CI width remains ≥20 pp through 30 observations; correlation between set-dominance metrics and tiebreak win rate typically sits below 0.25.",
        "mechanism": "Tiebreaks compress a set's worth of information into 7-10 points, amplifying serve-rhythm luck, net-cord variance, and pressure responses. Alternating serve rules partially equalize inherent serve advantages.",
        "conditions": "Most volatile on fast surfaces where first-serve swings one-point outcomes most sharply; less variance on clay where rally length introduces more skill-sorting per point.",
        "magnitude": "A player's tiebreak win rate requires ≥50 observations before the 95% confidence interval shrinks to ±10 pp, illustrating the imprecision of updating beliefs from single tiebreak results.",
        "links": ["clutch_point_dispersion", "deciding_set_variance", "serve_day_variance", "break_point_conversion_variance"],
    },
    {
        "slug": "break_point_conversion_variance",
        "title": "Break-Point Conversion Variance",
        "summary": "Swing in capitalizing on rare, high-value break opportunities. Because break points are infrequent, conversion rates carry large sampling noise, yet each converted break substantially alters set outcomes.",
        "stat_signature": "Match-level break-point conversion ranges routinely from 0% to 60% for the same player; SD across matches typically 18-25 pp regardless of skill tier; stabilizes only after ≥40 opportunities.",
        "mechanism": "Break points trigger heightened server pressure, altering serve patterns (more conservative placement, shifted targets) in ways that partly offset the returner's structural advantage, making each break-point game a partially distinct mini-game.",
        "conditions": "Variance highest in best-of-three where small break-point samples per set drive large outcome swings; partially stabilizes in best-of-five; elevated against big servers who generate rare break points.",
        "magnitude": "Match-to-match conversion swings of 30+ pp are common even for skilled returners; a semifinalist might convert 25-55% of break points set-by-set across a tournament.",
        "links": ["clutch_point_dispersion", "tiebreak_outcome_variance", "service_game_hold_volatility", "return_day_variability"],
    },
    {
        "slug": "double_fault_clustering",
        "title": "Double-Fault Clustering",
        "summary": "Tendency for service misses to bunch under pressure rather than scatter randomly across a match. Clustered double faults concentrate damage in high-leverage games, raising structural impact beyond total count alone.",
        "stat_signature": "Dispersion ratio (observed cluster size divided by Poisson expectation) ≥1.4 signals pressure-bunching; ≥30% of double faults in games already at deuce or break point marks high-leverage concentration.",
        "mechanism": "A double fault triggers self-doubt about second-serve mechanics, shortening follow-through and flattening spin on the next attempt. Under pressure the serve action accelerates slightly, reducing toss consistency and creating a feedback loop.",
        "conditions": "Most pronounced in fifth sets and after losing a contested first set; strongest on fast surfaces where second-serve margin for error is smallest; amplified against chip returners who disrupt rhythm.",
        "magnitude": "High clustering-ratio servers lose breaks at 1.5-2x the rate total double-fault count alone would predict, because clustered faults fall disproportionately inside critical games.",
        "links": ["ace_double_fault_balance_swing", "serve_day_variance", "error_streak_volatility", "clutch_point_dispersion"],
    },
    {
        "slug": "return_day_variability",
        "title": "Return-Day Variability",
        "summary": "Match-to-match swing in return effectiveness that determines break-chance volume. High SD in return-points-won drives wide swings in break opportunities created, making offensive game plans inconsistent even for skilled returners.",
        "stat_signature": "SD of return-points-won percentage across matches ≥6 pp = elevated variability; SD of break-points-per-return-game ≥0.4 marks a volatile break-creation profile; tour range is 38-55% return-points-won.",
        "mechanism": "Return quality depends on read-speed, split-step timing, and positioning adjustments that take several games to calibrate to specific serve patterns. Early-match miscalibration can persist if the server establishes a tactical pattern before it is decoded.",
        "conditions": "Most volatile against power servers with high ace rates, where a single positioning miscalibration suppresses return points-won for an entire set; stabilizes against moderate-pace servers with more read time.",
        "magnitude": "A one-SD swing in return-points-won (~6 pp) translates to approximately 0.3 fewer or additional break opportunities per service game, compounding to 1-2 missed break chances per set.",
        "links": ["serve_day_variance", "match_to_match_consistency", "break_point_conversion_variance", "opponent_style_induced_variance"],
    },
    {
        "slug": "momentum_swing_volatility",
        "title": "Momentum-Swing Volatility",
        "summary": "Within-match oscillation between dominant and passive stretches, measured by frequency and magnitude of multi-game runs. High-swing profiles produce large score-deficit reversals; low-swing profiles show linear score progression.",
        "stat_signature": "Profiles with ≥3 instances of a side winning 3+ consecutive games per match indicate high oscillation; within-match variance of points-won per set above 8 pp signals structural swing tendencies.",
        "mechanism": "Holding easily produces energy and court positioning that increases first-serve aggression, while being broken produces caution that softens serve targets. This correlation creates run structures that exceed independent-point predictions.",
        "conditions": "Stronger in best-of-five formats where mid-match resets are more common; amplified when fatigue affects intensity in later sets; present in players with reactive rather than structurally dominant styles.",
        "magnitude": "Matches with ≥4 game-run streaks of 3+ produce score-line reversals at 2x the rate of low-swing matches; final set margins are poorly predicted by first-set margins in high-swing profiles.",
        "links": ["error_streak_volatility", "set_to_set_dropoff_variance", "break_point_conversion_variance", "deciding_set_variance"],
    },
    {
        "slug": "set_to_set_dropoff_variance",
        "title": "Set-to-Set Dropoff Variance",
        "summary": "Inconsistency in sustaining performance across sets, including post-set-win letdowns and post-break collapses. High within-match variance in points-won between consecutive sets signals structural unreliability regardless of average level.",
        "stat_signature": "Average match-level SD of consecutive-set points-won ≥7 pp marks high dropoff volatility; ≥10 pp swing between adjacent sets occurring in ≥40% of matches signals a structural inconsistency pattern.",
        "mechanism": "Winning a set convincingly triggers a brief emotional decompression that opens the next set competitively. A narrow loss often elevates focus in the following set, creating alternating-set patterns that inflate within-match variance.",
        "conditions": "Most pronounced in best-of-five where fatigue compounds; present after lopsided first sets in either direction; amplified for players whose motivational arousal closely tracks score-state.",
        "magnitude": "In high-variance profiles, winning a set 6-1 is followed by a competitive next set at ~1.4x the rate expected from baseline dominance, reflecting the post-dominant-set letdown pattern.",
        "links": ["momentum_swing_volatility", "deciding_set_variance", "match_to_match_consistency", "rhythm_dependency_variance"],
    },
    {
        "slug": "clutch_point_dispersion",
        "title": "Clutch-Point Dispersion",
        "summary": "Widened outcome distribution on high-leverage points where small samples and pressure dominate. Points-won rates on game-points and set-points diverge significantly from base-rate, reflecting structural pressure-response variance.",
        "stat_signature": "Points-won on deuce-game-point situations divided by overall points-won: ratios below 0.92 or above 1.08 indicate significant divergence; SD of this ratio across tournaments ≥0.06 marks a volatile clutch-point profile.",
        "mechanism": "High-leverage points trigger tactical shifts — servers move toward conservative placement, returners anticipate specific patterns, physical tension shortens swing arcs — introducing additional variance beyond the base rate.",
        "conditions": "Emerges on game-points, set-points, and match-points; more pronounced in tiebreaks and deciding sets; amplified when the score has been contested rather than comfortable throughout.",
        "magnitude": "Bottom-quartile clutch-point converters win 4-6 pp fewer points on game-points relative to their base rate, translating to 1-2 additional games lost on serve per set.",
        "links": ["tiebreak_outcome_variance", "break_point_conversion_variance", "deciding_set_variance", "double_fault_clustering"],
    },
    {
        "slug": "ace_double_fault_balance_swing",
        "title": "Ace-to-Double-Fault Balance Swing",
        "summary": "Night-to-night oscillation in the high-risk serve ledger, measuring the SD of the ace-minus-double-fault net differential per match. Volatile ledgers occur because aggressive serve days widen both the free-point and gift-point tails simultaneously.",
        "stat_signature": "SD of (aces minus double faults) per match ≥3.5 across ≥12 matches marks a volatile ledger; positive correlation between ace rate and double-fault rate across matches ≥0.25 confirms risk-coupling.",
        "mechanism": "Risk-on serve behavior increases ace potential and double-fault exposure simultaneously: a flat, hard serve aimed at the corners wins free points when it lands and produces double faults when the second serve misses. Commitment to aggression widens both distribution tails.",
        "conditions": "Most pronounced on fast surfaces where serve aggression has higher upside; amplified against returners who punish conservative second serves, incentivizing aggressive serve selection; present in players without a reliable medium-risk serve option.",
        "magnitude": "On high-ace-rate days (top quartile) double-fault counts are on average 1.5 higher than on moderate-ace days; net ledger improvement from ace days is partially offset by this coupling.",
        "links": ["serve_day_variance", "double_fault_clustering", "first_serve_dependency_swing", "service_game_hold_volatility"],
    },
    {
        "slug": "deciding_set_variance",
        "title": "Deciding-Set Variance",
        "summary": "Elevated outcome swing of final sets where fatigue, nerves, and small samples converge. Deciding-set point-win rates show higher variance relative to earlier sets and are less well-predicted by aggregate season metrics.",
        "stat_signature": "Variance ratio of deciding-set points-won versus first-set points-won ≥1.25 marks a high-variance deciding-set profile; deciding-set hold rate drops ≥5 pp below season average for high-variance profiles.",
        "mechanism": "Fatigue asymmetrically affects players based on style and conditioning: high-movement players degrade faster in final sets while power servers sustain more evenly. Heightened nerves also amplify double-fault clustering and error-streak formation simultaneously.",
        "conditions": "Applies in best-of-five formats on all surfaces; amplified in three-hour-plus matches; present in players with aerobically demanding styles dependent on high court coverage.",
        "magnitude": "In deciding-set matches, the underdog-by-sets player wins the final set at roughly 45% rate — substantially closer to coin-flip than the 40% implied by overall match-win probability — reflecting variance compression.",
        "links": ["set_to_set_dropoff_variance", "momentum_swing_volatility", "clutch_point_dispersion", "tiebreak_outcome_variance"],
    },
    {
        "slug": "rhythm_dependency_variance",
        "title": "Rhythm-Dependency Variance",
        "summary": "Reliance on settled timing produces wide error-rate swings when play is interrupted or disrupted. Players with high rhythm dependency show substantially different error profiles across uninterrupted versus stop-start match segments.",
        "stat_signature": "Error rate variance between uninterrupted and disrupted segments (weather delays, medical timeouts, extended changeovers) ≥15% relative increase marks a high rhythm-dependency profile.",
        "mechanism": "Technically intricate strokes rely on ingrained motor sequences that are disrupted by prolonged pauses. Rhythm-dependent players require several games after disruption to re-establish consistent contact timing, elevating error rate in the re-calibration window.",
        "conditions": "Strongest after weather delays mid-match; amplified by extended toilet breaks and medical timeouts at critical set junctures; present for players whose technical mechanics are timing-sensitive rather than kinetically simple.",
        "magnitude": "Error rates in the first two games after a significant interruption are on average 20-25% higher than the pre-interruption baseline for high rhythm-dependency profiles.",
        "links": ["error_streak_volatility", "set_to_set_dropoff_variance", "shot_tolerance_consistency", "surface_transition_variance"],
    },
    {
        "slug": "service_game_hold_volatility",
        "title": "Service-Game Hold Volatility",
        "summary": "Within-match swing in the reliability of holding serve, measured by the SD of per-game serve effectiveness. High hold volatility means unexpected breaks occur even within otherwise strong serving performances in the same match.",
        "stat_signature": "Within-match SD of per-service-game points-won ≥12 pp marks high hold volatility; unexpected breaks (in games where first-serve percentage exceeded player average) occurring ≥20% of all breaks identifies structurally volatile profiles.",
        "mechanism": "Service games are not independent — opponent return adjustments, crowd energy, and score-state modulate serve aggression within a match. Servers who adjust poorly to within-match tactical changes show unexplained game-to-game hold variation.",
        "conditions": "Stronger in longer matches where the returner has more time to decode serve patterns; amplified against high-IQ returners who vary positioning and chip-return tactics between games.",
        "magnitude": "Top-quartile within-match hold SD servers give up unexpected breaks at 1.6x the rate of low-SD servers despite equivalent season-level hold percentages — roughly one extra unexpected break per set.",
        "links": ["serve_day_variance", "first_serve_dependency_swing", "double_fault_clustering", "break_point_conversion_variance"],
    },
    {
        "slug": "shot_tolerance_consistency",
        "title": "Shot-Tolerance Consistency Profile",
        "summary": "Reliability of sustaining neutral rallies without errors as a low-variance floor. Low per-match SD of neutral-rally error rate indicates a player whose defensive baseline is stable regardless of form fluctuation.",
        "stat_signature": "Per-match SD of rally-ball error rate under neutral conditions (pace below threshold, no extreme angles) ≤3% marks a high-consistency floor; SD ≥6% identifies players whose neutral error rate fluctuates widely.",
        "mechanism": "Neutral rally consistency reflects depth of grooved stroke mechanics that function under varied timing. Players with well-ingrained neutral patterns sustain a consistent error floor even when offensive execution degrades, providing a predictable baseline.",
        "conditions": "Most measurable on clay where neutral rallies are common; relevant in long-match scenarios where offensive precision decays but neutral mechanics should remain intact.",
        "magnitude": "High-consistency profiles maintain rally-ball error rate within ±2% of their seasonal average across 90% of matches; low-consistency profiles show a ±6% range across the same sample.",
        "links": ["rhythm_dependency_variance", "error_streak_volatility", "match_to_match_consistency", "opponent_style_induced_variance"],
    },
    {
        "slug": "opponent_style_induced_variance",
        "title": "Opponent-Style-Induced Variance",
        "summary": "Performance swing driven by the disruptiveness of the opposing style rather than internal form fluctuation. Style-sensitive players show wider match-level variance because their point-win rates are strongly modulated by opponent tactical categories.",
        "stat_signature": "Share of match-level points-won variance explained by opponent style categories ≥30% marks a style-induced volatility profile; points-won gap across top-quartile disruptive versus bottom-quartile disruptive opponents ≥12 pp.",
        "mechanism": "Specific styles stress particular technical aspects: high-bounce topspin disrupts flat-hitting; heavy slice prevents aggressive loading; net rushers eliminate baseline rhythm. Players without neutralizing adjustments absorb the full variance from opponent style diversity.",
        "conditions": "Most visible across surface transitions where style advantages shift; amplified in draws with diverse tactical profiles; measured cleanly by comparing within-surface performances across opponent style categories.",
        "magnitude": "Style-sensitive profiles show a 15-20 pp range in points-won percentage between best and worst opponent-style matchups, accounting for a substantial share of their overall performance volatility.",
        "links": ["surface_transition_variance", "match_to_match_consistency", "return_day_variability", "rhythm_dependency_variance"],
    },
]
