"""Soccer VolatilityProfiles concept-node spec for the brain builder.

Dense, person-free profiles that characterise how scoring volatility arises from
chance quality, distribution shape, structural patterns, and game-state dynamics.
Each concept is measurable, causally grounded, and honest: markets are efficient.
"""
from __future__ import annotations

SPORT = "Soccer"
FAMILY = "VolatilityProfiles"

CONCEPTS: list[dict] = [
    {
        "slug": "high_variance_attacking",
        "title": "High-Variance Attacking Profile",
        "summary": "An attacking system that generates few but high-probability chances per match produces wider match-level goal distributions than volume-based attacks at equal total xG; the standard deviation of goals scored expands when xG is concentrated in a small number of high-value events.",
        "stat_signature": "SD of goals scored above 1.20 per match combined with fewer than 11 shots per 90 and xG per shot above 0.15; big chances (xG >=0.35) share of total xG exceeds 45%; match-level goal SD roughly 15-20% wider than a volume-based attack at equivalent total xG.",
        "mechanism": "Concentrating xG in a few high-probability attempts amplifies the binomial variance of each event; missing a single 0.40-xG chance eliminates a large fraction of the match's expected output, whereas distributed low-probability events partially cancel each other, compressing net variance.",
        "conditions": "Most pronounced for counter-attacking and direct-play systems that prioritise quality over quantity; also elevated when set-piece delivery consistently produces big chances, adding discrete lumpiness beyond open-play accumulation.",
        "magnitude": "A side averaging 4 big chances per match at xG 0.38 each (total xG ~1.52) has a goals-scored SD near 0.99; a volume attack at 15 shots and xG/shot 0.10 (total xG 1.50) reaches SD ~1.16; both exceed the control-floor benchmark of ~0.75.",
        "links": ["low_variance_control", "counter_attack_variance", "big_chance_dependency", "set_piece_variance_injection"],
    },
    {
        "slug": "low_variance_control",
        "title": "Low-Variance Control Profile",
        "summary": "Possession-dominant systems that suppress opponent chance volume compress the match-level xG distribution for both sides, narrowing the SD of goals conceded and stabilising scoring output; the dual effect of lower mean and lower variance makes outcomes more predictable than the league baseline.",
        "stat_signature": "Opponent xGA below 0.90 per 90 combined with possession above 57%; SD of opponent goals conceded approximately 0.75 versus a league-average 1.05; control sides record clean sheets at 5-8 percentage points above the Poisson-xGA implied rate.",
        "mechanism": "Sustained possession withdraws the ball during phases when the opponent could transition; the defending side's exposure time is structurally compressed, reducing the Poisson trial count and outcome variance simultaneously; a lower mean xGA cascades into a narrower distribution through the Poisson variance-equals-mean relationship.",
        "conditions": "Profile holds most strongly against direct-play and counter-attacking opponents whose chance creation depends on transition; least effective against high-press sides that can disrupt possession rhythms and generate turnover-based xG that bypasses the possession protection mechanism.",
        "magnitude": "Moving from average possession (50%) to a control profile (58%) is associated with roughly 0.30-0.40 fewer xGA per 90 and a SD reduction of approximately 0.25 goals per match, compressing tail-risk of multi-goal defeat.",
        "links": ["high_variance_attacking", "draw_proneness_profile", "clean_sheet_consistency", "game_state_dependent_variance"],
    },
    {
        "slug": "xg_overperformance_variance",
        "title": "Expected-Goals Overperformance Variance",
        "summary": "Short-window swings where finishing runs hot or cold relative to chance quality are dominated by Bernoulli noise; the SD of the goals-minus-xG gap across a squad's matches is the primary measure of this volatility component, and it regresses steeply toward zero as sample size grows.",
        "stat_signature": "Team-level G-xG per 90 SD across a 10-match window typically 0.55-0.75; year-to-year correlation for team G-xG per 90 is 0.10-0.15; gaps exceeding ±6 cumulative goals by midseason identify strong regression candidates.",
        "mechanism": "Shot outcomes are Bernoulli trials whose probabilities are set by chance quality; the team-level conversion rate aggregates across multiple finishers whose individual variance compounds rather than cancels; as the shot count grows the aggregate converges toward the xG-implied probability, erasing the surplus or deficit.",
        "conditions": "Regression is fastest for high-shot-volume sides where the law of large numbers operates quickly; slower when a single technical finisher dominates attempts, concentrating variance; set-piece conversion is a slightly more persistent sub-component than open-play finishing.",
        "magnitude": "Top-decile finishing overperformers in the first half of a season regress an average 0.15-0.25 G-xG per 90 downward in the second half; a midseason surplus of +6 goals is associated with roughly 3-4 fewer goals in subsequent matches.",
        "links": ["finishing_streak_clustering", "goal_distribution_dispersion", "shot_volume_variance_link", "goalkeeper_shot_stopping_variance"],
    },
    {
        "slug": "goal_distribution_dispersion",
        "title": "Goal-Distribution Dispersion",
        "summary": "The variance of goals scored across a team's matches around their seasonal mean — and its degree of overdispersion relative to a Poisson baseline — captures structural volatility in output; high overdispersion signals that non-Poisson factors (clustering, lumpiness, game-state effects) drive the distribution.",
        "stat_signature": "Poisson model implies variance equals mean (dispersion ratio = 1.0); empirical dispersion ratios for top-division sides cluster 1.05-1.25; sides with ratios above 1.30 have structurally lumpy output driven by set pieces, red cards, or game-state risk-taking; within-season SD of goals scored ranges 0.90-1.30 across league participants.",
        "mechanism": "Non-Poisson overdispersion arises from contagion effects — a goal changes game state and alters subsequent xG rates — and from discrete events such as dismissals, penalties, and dead-ball goals that are drawn from distributions outside the open-play Poisson process; the aggregate distribution widens beyond the Poisson prediction.",
        "conditions": "Overdispersion is highest for sides that play open, end-to-end football with frequent game-state transitions; most compressed for possession-control sides that maintain a stable, predictable chance-creation rate throughout matches regardless of the scoreline.",
        "magnitude": "A side with a dispersion ratio of 1.30 has a within-season goals-SD roughly 14% wider than a pure Poisson side at the same mean; this translates to approximately 2-3 additional extreme-score matches per season (zero goals or four-plus goals) relative to the Poisson expectation.",
        "links": ["high_variance_attacking", "xg_overperformance_variance", "set_piece_variance_injection", "penalty_dependency_variance"],
    },
    {
        "slug": "set_piece_variance_injection",
        "title": "Set-Piece Variance Injection",
        "summary": "Dead-ball situations introduce lumpy, low-frequency scoring events whose match-to-match occurrence is partially stochastic; the share of goals from set pieces and the variance it adds to match totals makes set-piece-reliant sides harder to model from open-play xG alone.",
        "stat_signature": "Set pieces account for 25-32% of all top-division goals; penalty awards average 0.25-0.35 per team per match at 75-80% conversion; year-to-year team correlation for set-piece goal share is approximately 0.35-0.45, indicating partial but imperfect persistence.",
        "mechanism": "Set-piece opportunities depend on opponent foul tendency, referee tendency, and zone of play; their conversion depends on delivery quality and aerial contest outcomes; because these inputs partially bypass the open-play xG process, set-piece goals introduce an overdispersion component that inflates the tail of the match-total distribution.",
        "conditions": "Variance injection is highest when a side specialises in corner-kick and direct free-kick delivery to aerial targets; greatest against opponents that foul frequently or allow many corner concessions; less impactful for sides whose set-piece creation rate is near the league median.",
        "magnitude": "A team earning three penalties in a 10-match window (at 75% conversion) accumulates roughly 2.25 additional expected goals beyond open-play, a 15-25% uplift that may not persist if the award rate regresses toward the league mean in subsequent fixtures.",
        "links": ["goal_distribution_dispersion", "penalty_dependency_variance", "high_variance_attacking", "xg_overperformance_variance"],
    },
    {
        "slug": "counter_attack_variance",
        "title": "Counter-Attack Variance Profile",
        "summary": "Transition-reliant attacks yield clustered high-value chances against exposed defences in brief windows, producing swingy outputs that depend on whether opponents commit players forward; the variance of fast-break xG and chance concentration captures this profile's structural volatility.",
        "stat_signature": "Counter-attack xG variance above 0.30 per match; fast-break chances (fewer than 4 seconds ball-progression to shot) accounting for over 30% of total xG with xG per shot above 0.18 in those sequences; match-to-match SD of counter-attack goals exceeds 0.60.",
        "mechanism": "Counter-attacking chance creation depends on the opponent's commitment to attack; when facing a cautious opponent who refuses to overcommit, counter-attack opportunity count drops sharply, compressing xG; against an attacking opponent the window opens and chance volume spikes, creating non-stationary within-season variance.",
        "conditions": "Variance is highest when the fixture list mixes cautious defensive opponents with attacking sides; amplified in matches where the side falls behind early and the opponent opens up further; attenuated in home matches where the counter-attack side may be expected to control possession.",
        "magnitude": "Counter-attack-dependent sides have a match-level goals-scored SD approximately 10-15% wider than possession-based sides at equivalent season xG totals; fixture-to-fixture swing in counter-attack xG generated can span 0.40-1.80 depending on opponent tactical posture.",
        "links": ["high_variance_attacking", "game_state_dependent_variance", "pressing_trigger_variance", "shot_volume_variance_link"],
    },
    {
        "slug": "clean_sheet_consistency",
        "title": "Clean-Sheet Consistency Profile",
        "summary": "Defensive reliability measured by clean-sheet rate narrows the conceded-goals distribution and functions as a floor marker; sustained shutout frequency above the Poisson-xGA implied rate contains both structural and luck components that require decomposition before drawing reliability conclusions.",
        "stat_signature": "At xGA 1.0 per match the Poisson zero-goal probability is ~37%; sides recording 50%+ clean sheets at that xGA are running 13 percentage points above structural expectation; year-to-year correlation for team clean-sheet rate is ~0.45, versus ~0.60 for xGA-implied clean-sheet rate.",
        "mechanism": "Shutouts accumulate when opponents over-miss against their own xG and when the goalkeeper saves above post-shot xG; both finishing and shot-stopping variance must simultaneously favour the defending side, making clean-sheet streaks sensitive to combined luck at the zero-goals threshold.",
        "conditions": "Structural clean-sheet consistency is most credible for sides with xGA below 0.80, where the Poisson zero probability exceeds 45%; for sides with xGA above 1.10, clean-sheet streaks above four consecutive matches almost always contain a luck component that will regress.",
        "magnitude": "A side recording 45% clean sheets against a structural expectation of 35% expects regression of 5-8 percentage points toward the xGA-implied rate in the next 20 matches, losing approximately 3-4 clean sheets of apparent defensive surplus.",
        "links": ["low_variance_control", "goalkeeper_shot_stopping_variance", "draw_proneness_profile", "defensive_error_volatility"],
    },
    {
        "slug": "finishing_streak_clustering",
        "title": "Finishing-Streak Clustering",
        "summary": "Temporal bunching of clinical and wasteful finishing stretches — measured by lag-1 autocorrelation of conversion rate — reflects whether finishing quality is genuinely serially correlated or whether the clustering is consistent with independent Bernoulli draws whose runs are misread as momentum.",
        "stat_signature": "Lag-1 autocorrelation of match-level goals-minus-xG is typically 0.05-0.15 for team-level data, consistent with near-independence; run-length statistics for above-xG months exceed Poisson-implied run lengths by roughly 10-15%, suggesting mild clustering; only clusters spanning 8+ matches exceed the 95% interval for independent draws.",
        "mechanism": "True finisher confidence effects exist at the individual level but aggregate across a squad; collective finishing runs short enough to be consistent with sampling variance; the mechanism for genuine clustering — psychological momentum in technique execution — requires a sample far larger than typical streak lengths to confirm.",
        "conditions": "Clustering is more interpretable when concentrated in one or two primary finishers who dominate attempts; squad-wide finishing streaks are more likely noise; runs that coincide with opponent quality variation (a soft fixture run) require quality-adjusted conversion tracking before attributing to genuine finishing momentum.",
        "magnitude": "A 5-match above-xG conversion run at team level should update the true conversion rate estimate by roughly 0.08-0.12 percentage points above the season baseline; the full run-length difference from the independent model translates to fewer than 0.5 additional goals above expectation on average.",
        "links": ["xg_overperformance_variance", "rolling_form_dispersion", "match_to_match_result_swing", "shot_volume_variance_link"],
    },
    {
        "slug": "match_to_match_result_swing",
        "title": "Match-to-Match Result Swing",
        "summary": "Oscillation between dominant wins and flat defeats across fixtures — measured by the SD of points per match and the alternation frequency of result categories — captures structural inconsistency that exceeds what the underlying xG difference distribution would predict from Poisson noise alone.",
        "stat_signature": "SD of points per match above 1.45 (versus a league-average near 1.20) identifies high-swing sides; alternation rate between win-and-non-win results above 55% across a 15-match window; year-to-year correlation of points-SD is approximately 0.25-0.35.",
        "mechanism": "Genuine result oscillation arises when tactical setup varies by opponent, when squad rotation produces inconsistent performance levels, or when motivation structure is linked to cup or continental competition; it is partially structural but amplified by result-based game-state effects and finishing variance in narrow-margin matches.",
        "conditions": "Most pronounced for sides competing on multiple fronts where squad rotation creates within-season quality variation; also elevated for sides with high SD of opponent quality whose fixture list alternates between elite and bottom-half opponents in successive matches.",
        "magnitude": "A side with a points-SD of 1.50 accumulates approximately the same season-total points as a side at 1.20 at the same mean PPM, but experiences roughly 20% more extreme results (3-point wins and 0-point defeats) per 20-match block.",
        "links": ["rolling_form_dispersion", "finishing_streak_clustering", "game_state_dependent_variance", "scoreline_collapse_volatility"],
    },
    {
        "slug": "shot_volume_variance_link",
        "title": "Shot-Volume Variance Link",
        "summary": "Reliance on volume versus quality shapes scoring swing differently: high shot-count attacks distribute variance across many low-probability events (partial cancellation), while quality-concentrated attacks amplify per-event variance; the dispersion of goals conditioned on shot count tracks this structural difference.",
        "stat_signature": "Conditional SD of goals given shot count 8-12: approximately 1.05-1.15 for quality-based attacks (xG/shot >0.14); approximately 0.90-1.00 for volume attacks (xG/shot <0.09) at the same shot count range; correlation between within-season shot-count variance and goals-scored variance is approximately 0.55.",
        "mechanism": "At low xG per shot (0.09), each shot trial has high variance relative to expected output (Bernoulli SD/mean ratio is large); with many trials the law of large numbers partially cancels variance; quality attacks with fewer high-xG shots avoid cancellation but have large per-shot variance, producing wider outcome distributions from fewer events.",
        "conditions": "Link is sharpest in matches where shot count deviates strongly from a side's seasonal average (unusually high or low shot volume); least informative when both sides suppress each other to fewer than 8 total shots, where the distribution becomes dominated by set-piece and individual error variance.",
        "magnitude": "A volume attack generating 18 shots at xG/shot 0.08 (xG 1.44) versus a quality attack generating 10 shots at xG/shot 0.14 (xG 1.40) show nearly identical total xG but the quality attack's goals-SD is approximately 10-15% wider per match.",
        "links": ["high_variance_attacking", "counter_attack_variance", "big_chance_dependency", "xg_overperformance_variance"],
    },
    {
        "slug": "defensive_error_volatility",
        "title": "Defensive-Error Volatility",
        "summary": "Unpredictable goals conceded from individual or structural lapses — distinct from systemic chance allowance — produce a fat-tailed conceded-goals distribution whose upper tail exceeds Poisson expectations; the variance of high-value conceded chances unexplained by opponent buildup quality measures this component.",
        "stat_signature": "Error-driven goals (defined as chances created from defensive mistakes rather than sustained buildup) account for 8-14% of all goals in top divisions; team-level error goal rate has a year-to-year correlation near 0.20, confirming low persistence; sides conceding above 0.15 error goals per 90 are in the top-volatility quartile.",
        "mechanism": "Defensive errors introduce high-xG opportunities (often near-open-goal) independently of the opponent's buildup quality; they arise from individual lapses in concentration, communication breakdowns, or structural positional errors under pressure; their low persistence means the variance they inject is predominantly non-repeatable noise.",
        "conditions": "Elevated in matches with intense pressing opponents who deliberately hunt for forced errors; amplified under fatigue conditions in congested fixture schedules; less frequent for compact low-block defences that minimise exposure by keeping defensive lines narrow and deep.",
        "magnitude": "A side conceding 3 error-driven goals over 10 matches (0.30 per 90) experiences approximately 1.5-2.0 additional conceded goals above the structural xGA baseline; the tail-risk of conceding 3-plus goals in a single match increases by roughly 5-8 percentage points relative to an error-free defence at the same structural xGA.",
        "links": ["clean_sheet_consistency", "scoreline_collapse_volatility", "game_state_dependent_variance", "goalkeeper_shot_stopping_variance"],
    },
    {
        "slug": "game_state_dependent_variance",
        "title": "Game-State-Dependent Variance",
        "summary": "Leading, drawing, or trailing alters chance dispersion as teams open up or shut down; the conditional variance of xG across game-state buckets is substantially wider than the unconditional within-match xG variance, and sides that frequently encounter extreme game states face structurally wider outcome distributions.",
        "stat_signature": "xG rate while trailing by one goal is approximately 35-50% higher than while leading, measured across top-division matches; SD of per-minute xG rate triples or more during the trailing-by-two state relative to the balanced state; game-state-adjusted xG models reduce prediction error by 8-12% relative to time-averaged xG.",
        "mechanism": "Trailing sides push more players forward, creating open-play sequences against less-defended spaces and increasing transition xG for both sides; leading sides deliberately compress space and tolerate a lower xG rate, trading chance creation for scoreline protection; the resulting within-match xG non-stationarity widens the observed goals distribution beyond a stationary Poisson model.",
        "conditions": "Variance amplification is largest in matches between teams with meaningful quality gaps where the inferior side often trails; attenuated in evenly-matched encounters that stay within one goal throughout; also attenuated for possession-control sides that maintain the same passing structure regardless of game state.",
        "magnitude": "Matches that pass through the trailing-by-one state for more than 25 minutes produce an expected 0.35-0.55 additional xG per side relative to evenly-contested matches, widening the match-total xG distribution and increasing the probability of a final scoreline with three-plus total goals by approximately 8-12 percentage points.",
        "links": ["counter_attack_variance", "low_variance_control", "match_to_match_result_swing", "scoreline_collapse_volatility"],
    },
    {
        "slug": "penalty_dependency_variance",
        "title": "Penalty-Dependency Variance",
        "summary": "Scoring output tied to the low-frequency, high-value penalty event introduces a discrete lumpiness into match totals; the share of goals from spot-kicks and the variance it injects makes penalty-reliant sides' goal distributions heavier in the tails than open-play xG models predict.",
        "stat_signature": "Penalties convert at 75-80%; award rate averages 0.25-0.35 per team per match; year-to-year team correlation for penalties awarded is approximately 0.30; sides earning above 0.40 penalties per 90 see roughly 12-18% of total goals originating from spot-kicks, a share that fluctuates by ±8 percentage points season to season.",
        "mechanism": "Penalty awards depend partly on opponent fouling tendency and referee tendency, both of which are external to the scoring team's structural quality; the high conversion rate means each awarded penalty contributes a nearly binary high-probability event that is not captured by open-play xG, inflating the upper tail of the match-total distribution.",
        "conditions": "Dependency is highest for physically aggressive forwards who draw fouls in the penalty area; elevated against high-press opponents who foul to recover the ball; dampened for sides whose primary chance creation routes avoid penalty-area contact and instead emphasise long-range or combination play.",
        "magnitude": "A team earning 8 penalties over a 20-match window (0.40 per match) and converting at 77% generates approximately 6.2 penalty goals, a 12-15% uplift over the open-play scoring baseline; in the subsequent 20 matches at league-average award rates (0.28 per match) this drops to roughly 4.3 goals, a deficit of roughly 2 goals purely from rate regression.",
        "links": ["set_piece_variance_injection", "goal_distribution_dispersion", "big_chance_dependency", "xg_overperformance_variance"],
    },
    {
        "slug": "goalkeeper_shot_stopping_variance",
        "title": "Goalkeeper Shot-Stopping Variance",
        "summary": "Match-to-match swing in goals prevented relative to post-shot xG — measured by the SD of saves-above-expected across fixtures — is the goalkeeping contribution to conceded-goals volatility; it is large relative to true skill separation for most keepers and regresses toward zero over multi-season samples.",
        "stat_signature": "SD of match-level saves-above-psxG approximately 0.55-0.70 across top-division keepers; year-to-year correlation for individual goals-prevented per 90 is approximately 0.30-0.35; true elite shot-stopping skill requires 150-plus shots faced (40-50 matches) to isolate from noise; top-decile single-season overperformers regress to near zero the following season on average.",
        "mechanism": "Post-shot xG accounts for ball trajectory and shot velocity; the residual reflects dive-distance randomness and positioning variance rather than reliably measurable skill; true skill distribution for shot-stopping is narrow relative to the wide noise band, meaning most single-season outliers are predominantly noise.",
        "conditions": "Regression is fastest for keepers behind low-shot-volume defences where small-sample variance dominates; some structural skill exists for elite-level keepers measurable only over multi-season 300-plus-shot samples; club-change environments further delay convergence by altering defensive shape and shot-type distribution.",
        "magnitude": "A keeper preventing +0.12 goals per 90 above psxG over one season (roughly 5 additional goals prevented) typically regresses to +0.04 or below in the following season, equivalent to losing approximately 3-4 goals-prevented of apparent output and widening the conceded-goals variance accordingly.",
        "links": ["clean_sheet_consistency", "defensive_error_volatility", "xg_overperformance_variance", "draw_proneness_profile"],
    },
    {
        "slug": "draw_proneness_profile",
        "title": "Draw-Proneness Profile",
        "summary": "Systems that funnel matches toward tight, low-margin outcomes compress the goal-difference distribution; draw frequency, one-goal-margin rate, and the compression of the final-score spread are collectively diagnostic of a structural tendency toward balanced chance creation that resists decisive scorelines.",
        "stat_signature": "Draw frequency above 32% over a 20-match window (league average ~25-28%); one-goal-margin rate above 58% of all matches; goal-difference SD below 1.10 versus a league baseline of 1.25-1.35; year-to-year correlation for team draw rate is approximately 0.25-0.35.",
        "mechanism": "Draw proneness arises when a side's defensive compactness suppresses opponent xG to a level that roughly matches its own modest attacking output; the resulting balanced xG distribution concentrates probability mass at the draw outcome in the Poisson win-draw-loss triplet; structural draw proneness is distinct from luck-driven draws caused by finishing variance.",
        "conditions": "Most structurally grounded for low-block or mid-block sides that actively target the draw against stronger opponents as a points-acquisition strategy; less meaningful for high-quality sides whose draw rate is inflated by short-run finishing variance rather than tactical design.",
        "magnitude": "A side with a structural draw frequency of 33% accumulates approximately 8-9 points per 10 matches from draws alone versus 5-6 for a league-average side; the compressed goal-difference distribution implies roughly 30% fewer matches with a 3-plus-goal margin and correspondingly more 0-0 and 1-1 outcomes.",
        "links": ["low_variance_control", "clean_sheet_consistency", "match_to_match_result_swing", "game_state_dependent_variance"],
    },
    {
        "slug": "scoreline_collapse_volatility",
        "title": "Scoreline-Collapse Volatility",
        "summary": "Abrupt within-match swings where a controlled lead unravels into a multi-goal turnaround are captured by the frequency and magnitude of xG momentum reversals after a lead; such collapses represent the extreme upper tail of the in-match xG non-stationarity distribution.",
        "stat_signature": "Matches featuring a lead-to-draw or lead-to-defeat reversal occur at approximately 12-16% frequency in top divisions; xG momentum reversal (opponent xG rate rising above own rate by more than 0.60 per 15-minute window after a lead) identifies structural collapse risk; year-to-year correlation for team reversal frequency is approximately 0.20-0.25.",
        "mechanism": "A lead triggers opponent risk-taking that opens space for transitions; if the leading side's defensive organisation degrades under pressure — through fatigue, positional errors, or tactical rigidity — the opponent's xG rate spikes; the resulting xG trajectory reversal can overcome a one-goal lead through chance clustering concentrated in a short window.",
        "conditions": "Most common for sides with brittle high defensive lines that become exposed when the block is disrupted; elevated in matches where a dismissal occurs while the leading side has only one goal of cushion; attenuated for possession-control sides that can maintain ball retention while protecting a lead.",
        "magnitude": "Sides conceding a lead reversal lose approximately 1.8-2.2 additional points per match relative to the structural expected-points from their leading position; across a season, 4-6 such reversals represent a 7-11-point deficit relative to a lead-protection baseline, a gap sufficient to shift league table positions materially.",
        "links": ["game_state_dependent_variance", "match_to_match_result_swing", "defensive_error_volatility", "rolling_form_dispersion"],
    },
    {
        "slug": "rolling_form_dispersion",
        "title": "Rolling Form Dispersion",
        "summary": "Multi-match oscillation between strong and weak underlying performance — measured by the SD of rolling xG-difference and its autocorrelation across fixtures — captures whether a side's quality is stable or structurally variable around a seasonal mean; high dispersion flags a side whose results are less predictable than a constant-quality model implies.",
        "stat_signature": "SD of 5-match rolling xG-difference above 0.55 per match (versus a low-dispersion side at 0.30) identifies high-dispersion sides; lag-1 autocorrelation of rolling xGD near zero confirms independence; year-to-year correlation for within-season rolling-xGD SD is approximately 0.30-0.40.",
        "mechanism": "Genuine rolling dispersion arises from squad rotation, multi-competition fatigue, tactical variation by opponent type, and key-position absence effects that alter the underlying performance level on a match-by-match basis; the result is a wider distribution of match-level outcomes that exceeds what a single-quality constant model predicts.",
        "conditions": "Highest for sides with thin squad depth competing in three competitions simultaneously where rotation-forced quality drops are regular; lowest for deep squads with tactical consistency whose first and second choices are close in quality across all positions.",
        "magnitude": "A side with rolling-xGD SD of 0.55 generates approximately 25-30% more extreme-margin matches (winning or losing by two-plus xG) per season than a stable side at 0.30 SD; this translates to roughly 5-7 additional matches per season at the tails of the outcome distribution, increasing both upset frequency and predictability variance.",
        "links": ["match_to_match_result_swing", "finishing_streak_clustering", "xg_overperformance_variance", "scoreline_collapse_volatility"],
    },
]
