"""NBA VolatilityProfiles concept nodes — person-free game-to-game output dispersion intelligence."""
from __future__ import annotations

SPORT = "NBA"
FAMILY = "VolatilityProfiles"

CONCEPTS: list[dict] = [
    {
        "slug": "boom_bust_scoring_distribution",
        "title": "Boom-Bust Scoring Distribution",
        "summary": "Captures bimodal or fat-tailed per-game scoring where output oscillates between high-ceiling explosions and floor collapses, quantified by the coefficient of variation (CV = standard deviation divided by mean) of game points exceeding roughly 0.40.",
        "stat_signature": "High-volatility scorers: CV above 0.45, with 90th-percentile games exceeding twice the median while 10th-percentile games fall below 40% of it. Stable high-usage scorers: CV 0.25–0.35. The bimodal signature emerges when game-point histograms show two distinct density modes separated by at least 8 points.",
        "mechanism": "Boom-bust patterns arise when shot-creation difficulty varies sharply across defensive schemes — a scheme that funnels possessions into contested mid-range attempts suppresses efficiency on some nights while switching to zone opens high-volume catch-and-shoot looks on others. Foul-drawing reliability and pace context amplify the spread by adding or removing possession-level opportunities in non-linear ways.",
        "conditions": "Most pronounced for high-usage isolation-heavy scorers facing a wide range of defensive identities across the schedule. Diminished for catch-and-shoot specialists whose volume is set by usage elsewhere. Amplified during opponent scheme transitions mid-game.",
        "magnitude": "Moving from CV 0.30 to CV 0.50 roughly doubles the probability mass in both the sub-10-point and above-40-point tails. The P10–P90 spread for a high-CV scorer at 22 points-per-game average spans approximately 8 to 42 points, versus 11 to 33 for a low-CV scorer at the same average.",
        "links": ["floor_ceiling_spread", "usage_dependent_variance", "shot_quality_noise_floor", "matchup_driven_output_swing"],
    },
    {
        "slug": "three_point_volume_variance",
        "title": "Three-Point Volume-Driven Variance",
        "summary": "Captures how heavy three-point dependence amplifies outcome swing because makes arrive in clustered binary chunks, measured by per-game 3PM standard deviation and the fraction of scoring variance attributable to three-point attempts versus two-point attempts.",
        "stat_signature": "Shooters attempting 8+ threes per game: 3PM standard deviation of 2.1–2.8 makes. A single three-point make/miss cycle contributes three units of point variance per event; the ratio of three-point scoring variance to total scoring variance exceeds 55% for volume shooters who attempt threes on more than 50% of field-goal attempts.",
        "mechanism": "Each three-pointer is a Bernoulli trial producing either 3 or 0 points; at 37% make rate the variance per attempt is 0.37×0.63×9 ≈ 2.1 points-squared. When volume concentrates scoring into this high-variance trial type, the central-limit-theorem smoothing of a diverse shot diet is lost, and nightly totals inherit the full binary spread multiplied across attempt count.",
        "conditions": "Strongest for off-ball shooters whose shot diet is nearly uniform across three-point attempts. Partially dampened when a high-volume three-point shooter also has a reliable two-point game that provides a floor. Amplified in offensive systems that hunt corner and above-the-break threes exclusively.",
        "magnitude": "Shifting from a 6-to-8 three-point-attempt diet to a 10-to-12 attempt diet raises expected game-scoring standard deviation by approximately 3–4 points holding make rate constant, with the effect concentrated in the upper tail (more 30+ point games and more sub-10 games simultaneously).",
        "links": ["boom_bust_scoring_distribution", "shot_quality_noise_floor", "shooting_efficiency_volatility", "floor_ceiling_spread"],
    },
    {
        "slug": "floor_ceiling_spread",
        "title": "Floor-Ceiling Spread",
        "summary": "Captures the gap between the 10th and 90th percentile of single-game output as a width band normalized by median production, providing a unified dispersion metric that does not assume symmetric distributions.",
        "stat_signature": "P90-minus-P10 spread normalized by median: values above 1.8 indicate high volatility; values below 1.1 indicate reliability. For a 20-point median scorer, a spread of 30 (P10=8, P90=38) gives a normalized width of 1.5 — moderate. Reliable scorers at the same median show P10=14, P90=28, width 0.7.",
        "mechanism": "The P90-P10 metric is robust to distributional shape because it makes no normality assumption; it directly captures the functional range a roster-construction or game-plan decision faces. The spread widens when multiple independent variance sources (volume, shot type, foul-drawing, pace) are correlated within a player's role.",
        "conditions": "Most informative for players whose game-log distributions are asymmetric (long upper tail from burst games, hard floor from role constraints). Less discriminating for true role players with narrow minute and possession ranges whose distributions are tightly constrained by lineup context.",
        "magnitude": "A normalized spread of 2.0 versus 1.0 at the same median output implies the high-spread player posts a ceiling game more than twice as often but also a floor game more than twice as often per 82-game season. Over 60 games, a normalized spread of 2.0 at 18 points median implies roughly 9 sub-10-point games and 9 above-28-point games.",
        "links": ["boom_bust_scoring_distribution", "shooting_efficiency_volatility", "clutch_output_dispersion", "usage_dependent_variance"],
    },
    {
        "slug": "team_scoring_night_dispersion",
        "title": "Team Scoring-Night Dispersion",
        "summary": "Captures game-to-game variance in total team points around the seasonal mean, measured by the standard deviation of team offensive output and the interquartile range across the full schedule.",
        "stat_signature": "League-typical team scoring standard deviation: 10–12 points per game. High-dispersion offenses: standard deviation above 14. Low-dispersion offenses: standard deviation below 9, typically associated with methodical halfcourt systems. The interquartile range (Q3 minus Q1) adds robustness: compressed offenses show IQR below 14; volatile offenses exceed IQR of 20.",
        "mechanism": "Team-level dispersion is driven by shot-type concentration, reliance on a small primary-scorer cluster, and opponent defensive variety. When a high fraction of points flows through a single shot-creation hub and that hub's efficiency oscillates with coverage, the team inherits individual variance. Systems that distribute attempts widely among multiple contributors smooth individual noise through diversification.",
        "conditions": "Amplified in small-rotation playoff basketball where bench contributions collapse. Compressed in regular-season stretches with stable opposing defenses. High-pace teams see wider absolute dispersion (more possessions mean more trials) but similar relative CV if shot-diet is diverse.",
        "magnitude": "A team with scoring standard deviation of 14 versus 10 faces approximately 3 more sub-100-point games and 3 more above-130-point games per 82-game season at the same scoring average, all else equal. Over-under total pricing is sensitive to this spread: a 4-point increase in standard deviation raises implied over probability by roughly 3–5 percentage points at typical scoring levels.",
        "links": ["pace_amplified_variance", "bench_scoring_unreliability", "shooting_efficiency_volatility", "hot_cold_streak_clustering"],
    },
    {
        "slug": "shooting_efficiency_volatility",
        "title": "Shooting Efficiency Volatility",
        "summary": "Captures night-to-night swing in true shooting percentage independent of volume, measured by the standard deviation of game-level TS% and the frequency of sub-45% versus above-65% TS nights.",
        "stat_signature": "High-efficiency-volatility shooters: TS% standard deviation above 14 percentage points. Stable shooters: TS% standard deviation below 9 pp. Sub-45% TS nights occur in 30%+ of games for high-volatility shooters at the same seasonal average as stable shooters (15% frequency). The bimodal TS distribution (two density peaks) is the clearest fingerprint.",
        "mechanism": "Game-level TS% swings because defensive contest quality, screen geometry, catch conditions, and fatigue interact with shot-creation method. Pure spot-up shooters have lower TS% volatility because openness quality is the dominant driver and varies modestly. Creation-heavy profiles introduce additional degrees of freedom (release point, defender proximity, balance) that amplify variance.",
        "conditions": "Highest for high-usage isolation creators who receive diverse defensive coverages across opponents. Lowest for off-ball specialists in motion offenses where catch-and-shoot cadence is predictable. B2B games and altitude venue changes shift conditional TS% distributions by 2–4 pp on average.",
        "magnitude": "A TS% standard deviation of 14 pp versus 8 pp at a 57% seasonal average implies the high-volatility profile posts a below-45% TS game roughly once every 3.3 games versus once every 8.7 games, and similarly for above-65% TS nights — the distribution is stretched symmetrically without moving the mean.",
        "links": ["shot_quality_noise_floor", "boom_bust_scoring_distribution", "hot_cold_streak_clustering", "usage_dependent_variance"],
    },
    {
        "slug": "usage_dependent_variance",
        "title": "Usage-Dependent Output Variance",
        "summary": "Captures how variance scales with possession share because high-usage roles compound shot-quality noise across more independent attempts per game, measured by the slope of game scoring variance regressed on usage rate.",
        "stat_signature": "Empirical slope: each additional percentage point of usage rate (e.g., 25% to 26%) associates with roughly 0.8–1.2 additional points of game-scoring standard deviation. At 30%+ usage, single-game scoring standard deviation typically exceeds 9 points; at sub-18% usage, it is typically below 5 points. R-squared of usage on scoring variance in large samples: approximately 0.45–0.60.",
        "mechanism": "Higher usage means more possessions consumed and more independent shot-creation events whose outcomes contribute to the game total. Each creation attempt carries shot-quality and defensive-coverage uncertainty; summing more such trials widens the realized distribution proportional to the square root of attempt count. Additionally, high-usage players face more varied coverage schemes within a single game (switching, blitzing, hedging), introducing scheme-level variance on top of per-shot variance.",
        "conditions": "Relationship is tightest when the player's role is stable across the season; weaker for players whose usage spikes situationally (foul trouble of others, injury coverage) because those spike games are regime shifts rather than sampling from a fixed distribution.",
        "magnitude": "The variance scaling with usage is approximately quadratic in standard-deviation units — moving a player from 20% to 28% usage is associated with roughly a 30–40% increase in per-game scoring standard deviation, not just an increase in mean output.",
        "links": ["boom_bust_scoring_distribution", "floor_ceiling_spread", "minutes_volatility_carryover", "role_stability_variance_link"],
    },
    {
        "slug": "hot_cold_streak_clustering",
        "title": "Hot-Cold Streak Clustering",
        "summary": "Captures temporal autocorrelation where good and bad shooting nights bunch into runs rather than scattering independently, measured by lag-1 autocorrelation of game-level TS% and run-length statistics of above-average and below-average games.",
        "stat_signature": "Meaningful streak clustering: lag-1 autocorrelation of game TS% above +0.18 (top quintile of shooters). Typical shooter: autocorrelation near zero (−0.05 to +0.10). Run-length test: streaky profiles show 3+ consecutive above-average games occurring 40%+ more often than expected under independence. Sample requirement for reliable autocorrelation estimate: at least 40 game observations.",
        "mechanism": "Short-term mechanical and fatigue states (release timing, shoulder fatigue, hand soreness) persist across adjacent games if the underlying cause persists. Rhythm and confidence effects can amplify an up-streak through shot-selection loosening or shorten a down-streak through conservative selection. However, most population-level analyses find autocorrelation close to zero, suggesting clustering is either weak or player-specific rather than universal.",
        "conditions": "Best-supported in players with identified mechanical tendencies (fatigue-sensitive mechanics, recurring minor injuries) and in end-of-season stretches with dense scheduling. Essentially absent for shooters whose efficiency is dominated by scheme matchup quality which changes game to game independent of prior outcomes.",
        "magnitude": "A lag-1 autocorrelation of +0.20 on a 57%-mean TS% series implies conditional expected TS% shifts by approximately 2.5 percentage points following an above-average night, a small but nonzero persistence. Over a 10-game window, expected above-average nights shifts from 5.0 to approximately 5.8 given a hot opening game.",
        "links": ["shooting_efficiency_volatility", "boom_bust_scoring_distribution", "clutch_output_dispersion", "shot_quality_noise_floor"],
    },
    {
        "slug": "garbage_time_variance_inflation",
        "title": "Garbage-Time Variance Inflation",
        "summary": "Captures artificial output swing from minutes played in decided games where defensive effort, rotation depth, and pace differ systematically from competitive segments, measured by the difference in per-minute production variance between competitive-margin and blowout-margin game segments.",
        "stat_signature": "Per-36-minute scoring variance in garbage-time (margin above 20 points, fourth quarter): 20–35% higher than in competitive segments for deep bench players. For primary rotation players, blowout minutes are often fewer and variance increases are smaller; for reserves, blowout minutes represent the majority of total minutes, making their season production statistics directly contaminated.",
        "mechanism": "In blowout segments, the leading team often reduces defensive intensity while the trailing team deploys reserves competing for roster spots rather than executing optimized schemes. The resulting offensive freedom inflates efficiency metrics while also introducing high-variance isolation attempts by non-primary creators who would not receive those possessions in competitive contexts.",
        "conditions": "Most acute for players ranked 8–12 in rotation depth who log 80%+ of minutes in non-competitive segments. Less impactful for starters who maintain consistent roles regardless of score margin. Seasons with high blowout frequency (teams over-performing or under-performing talent) amplify the effect fleet-wide.",
        "magnitude": "Removing garbage-time minutes can shift a reserve player's per-36 scoring estimate by 3–6 points and reduce individual season scoring standard deviation by 15–25%, representing a meaningful correction when projecting competitive-context performance from raw season lines.",
        "links": ["bench_scoring_unreliability", "minutes_volatility_carryover", "usage_dependent_variance", "role_stability_variance_link"],
    },
    {
        "slug": "bench_scoring_unreliability",
        "title": "Bench Scoring Unreliability",
        "summary": "Captures the elevated variance of reserve units whose minutes, matchups, and offensive rhythm fluctuate substantially relative to starters, measured by the coefficient of variation of bench points per game relative to starter CV.",
        "stat_signature": "Bench unit scoring CV typically 0.45–0.60 versus starter unit CV of 0.28–0.40 for the same team. Team bench points standard deviation averages 7–9 points per game league-wide. In 20%+ of games, bench units produce fewer than 15 points; in another 15%, they exceed 35 points — a spread rare in starter distributions.",
        "mechanism": "Bench players face more variable minute allocations (foul trouble upstream, blowout rotations, matchup substitutions) and enter the game in unpredictable offensive states (cold from rest or fatigued from earlier stints). The cohesion of the bench unit also varies because lineup combinations change more frequently than starter fives, reducing the play-familiarity that compresses variance for starters.",
        "conditions": "Variance is highest for teams with a shallow and uneven bench where one or two reserves carry most bench scoring and their personal volatility is undiversified. Compressed for deep rosters where multiple reliable contributors share bench minutes, averaging out individual fluctuations.",
        "magnitude": "A team that routes 30% of total scoring through the bench at a CV of 0.55 faces approximately 2.7 additional points of per-game total scoring standard deviation attributable purely to bench instability, compared with a team routing the same fraction through a cohesive low-CV (0.30) bench group.",
        "links": ["team_scoring_night_dispersion", "garbage_time_variance_inflation", "minutes_volatility_carryover", "role_stability_variance_link"],
    },
    {
        "slug": "matchup_driven_output_swing",
        "title": "Matchup-Driven Output Swing",
        "summary": "Captures variance attributable to opponent defensive identity rather than internal noise, measured by the share of game-to-game scoring variance explained when games are stratified by opponent defensive rating buckets.",
        "stat_signature": "Partitioning a season game log into opponent defensive-rating quintiles explains 15–30% of total game-scoring variance for high-usage scorers. The explained-variance share is highest for players whose shot diet overlaps heavily with what specific defensive styles suppress (e.g., rim-protection heavy defenses versus finishing-dependent scorers). Residual within-bucket variance reflects internal noise.",
        "mechanism": "Different defensive identities change both shot-quality opportunities and possession routing. A drop coverage frees pull-up mid-range creators; switching man-to-man pressures ball-handlers away from preferred creation zones. Because the schedule distributes defensive identities non-uniformly (division games repeat, playoff bracket concentrates opponents), opponent-driven variance partially clusters temporally, contributing to apparent streak effects.",
        "conditions": "Most pronounced for one-dimensional scorers whose efficiency concentrates in a single zone or creation method that specific defenses directly neutralize. Minimized for versatile scoring profiles that retain efficient options regardless of scheme. Also amplified late in seasons when opponent scouting is deepest.",
        "magnitude": "Scoring against a top-quintile defense versus bottom-quintile defense associates with a 4–7 point per-game scoring differential for a primary scorer, all else equal — representing a substantial fraction of the 10-point P90-P10 spread typical for volatile scorers.",
        "links": ["boom_bust_scoring_distribution", "floor_ceiling_spread", "shooting_efficiency_volatility", "usage_dependent_variance"],
    },
    {
        "slug": "assist_dependency_variance",
        "title": "Assist-Dependency Variance",
        "summary": "Captures how a playmaker's assist totals swing with teammate shotmaking outcomes they do not control, measured by the variance of assists conditioned on stable potential-assist creation volume (passes leading to a shot attempt).",
        "stat_signature": "Potential-assist creation is far more stable game to game (CV ≈ 0.18–0.25) than realized assists (CV ≈ 0.35–0.55). The gap between potential-assist CV and realized-assist CV represents the conversion-noise component attributable entirely to teammate make rates, which is a Bernoulli function of teammate shooting percentages on assisted looks.",
        "mechanism": "An assist requires two independent outcomes: the playmaker delivering a quality pass into a shot opportunity, and the recipient converting. If potential-assist creation is the stable underlying skill, realized assist totals inherit Binomial-like variance from teammate conversion rates. Teammates shooting 38% from three convert those looks with standard deviation proportional to sqrt(n×0.38×0.62) per game, injecting irreducible noise into the playmaker's box score.",
        "conditions": "The conversion-noise component is largest when the playmaker's assist profile concentrates on three-point looks (higher per-attempt variance than two-point finishes). Partially dampened in systems where the same two or three shooters receive most assisted looks, as repeat calibration within the game stabilizes teammate conversion rates somewhat.",
        "magnitude": "A playmaker generating 10 potential assists per game at a 45% teammate conversion rate faces a binomial assist standard deviation of approximately 1.6 per game from conversion noise alone — nearly half of the typical realized assist standard deviation of 3.5, meaning teammate shotmaking explains roughly 20% of assist variance on its own.",
        "links": ["usage_dependent_variance", "role_stability_variance_link", "shot_quality_noise_floor", "three_point_volume_variance"],
    },
    {
        "slug": "free_throw_rate_variability",
        "title": "Free-Throw Rate Variability",
        "summary": "Captures night-to-night fluctuation in foul-drawing frequency that injects low-noise, high-frequency points or removes them unpredictably, measured by the standard deviation of free-throw attempts per game and by whistle-environment splits across officiating crew tendencies.",
        "stat_signature": "High foul-drawers: free-throw attempt standard deviation of 2.5–4.0 per game despite consistent attack patterns. The free-throw-rate coefficient of variation (FTA CV) ranges from 0.30 for contact-seekers to 0.55 for players whose foul-drawing is attack-angle dependent. Games where FTA drops to zero for habitual foul-drawers occur in 8–15% of appearances.",
        "mechanism": "Foul-drawing depends on both the attacker's contact-seeking behavior and referee crew calling tendencies and crew-specific foul-threshold variation. Attack patterns that draw fouls reliably in one game may be called differently by another crew, introducing systematic variance. Additionally, defenders adapt mid-game after early foul trouble, reducing contact frequency in a non-stationary way.",
        "conditions": "Variance is highest for players who primarily draw fouls through driving contact at the rim, where officiating discretion is highest. Lower for players who draw shooting fouls on pull-ups, which have more standardized foul criteria. Amplified early in series or opponent-game-plan changes when defenders have not yet been conditioned to anticipate the contact pattern.",
        "magnitude": "A 3-attempt swing in FTA (from 5 to 2 or 5 to 8) at 80% free-throw percentage translates to 2.4 points of direct scoring variance in an otherwise identical game. For players where free throws represent 25% or more of total scoring, this single source contributes meaningfully to game-level scoring standard deviation.",
        "links": ["boom_bust_scoring_distribution", "matchup_driven_output_swing", "usage_dependent_variance", "floor_ceiling_spread"],
    },
    {
        "slug": "pace_amplified_variance",
        "title": "Pace-Amplified Variance",
        "summary": "Captures how higher possession counts widen the range of possible team scoring totals through more independent trial events, measured by the correlation between game possessions and absolute deviation of team points from their conditional expectation.",
        "stat_signature": "Correlation between possessions per game and absolute team-score deviation from expected: approximately +0.25 to +0.40 across the league. High-pace games (above 105 possessions) show team total standard deviation roughly 1.8–2.5 points wider than low-pace games (below 95 possessions) at the same offensive efficiency. Each additional 5 possessions per game expands expected scoring range by approximately 1.0–1.4 points of standard deviation.",
        "mechanism": "Under the central limit theorem, the variance of a sum of independent identically distributed scoring events grows linearly with the number of events (possessions). Higher pace adds more Bernoulli-like possession outcomes, so absolute deviation from expectation increases as the square root of possession count. Crucially, expected value scales linearly while standard deviation scales sub-linearly, so pace simultaneously raises means and widens distributions.",
        "conditions": "Effect is most pronounced for teams whose point-per-possession distribution is itself high-variance (three-heavy offense). For teams with a narrowly distributed point-per-possession (balanced inside-out offense), the amplification from pace is smaller in magnitude but still directionally positive.",
        "magnitude": "The over-under market pricing responds to pace: a 6-possession increase in game pace (e.g., 96 to 102 possessions) is associated with a 2.5–3.5 point increase in posted totals, reflecting both the additional expected points and market-implied variance premium. Post-hoc analysis shows game pace explains approximately 18% of variance in whether totals clear the posted line.",
        "links": ["team_scoring_night_dispersion", "rebounding_count_volatility", "turnover_variance_burden", "three_point_volume_variance"],
    },
    {
        "slug": "rebounding_count_volatility",
        "title": "Rebounding Count Volatility",
        "summary": "Captures swing in rebound totals driven by opponent miss volume, shot location distribution, and box-out competition intensity, measured by the standard deviation of total rebounds and its sensitivity to game pace and opponent field-goal-attempt volume.",
        "stat_signature": "Per-game rebound standard deviation for frontcourt starters: 2.5–4.0 boards. After controlling for opponent missed attempts (which determines the available rebound pool), residual rebound standard deviation drops to 1.8–2.6, indicating that 35–40% of raw rebound variance is attributable to opponent shooting volume fluctuation rather than box-out skill variance.",
        "mechanism": "Rebound totals depend on the size of the rebound pool (opponent misses plus own misses) multiplied by a conversion rate. Opponent shooting volume varies with pace and play-type distribution; an opponent going cold from three-point range simultaneously reduces total missed attempts (threes converted to misses rarely produce offensive rebounds for the shooter) and shifts rebound opportunity toward front-court players. These pool dynamics create mechanical rebounding variance independent of effort.",
        "conditions": "Volatile for frontcourt players on teams that concede high three-point attempt rates to opponents because three-point miss pools are deep. Stabilized for centers on low-pace halfcourt teams with predictable opponent shot distributions. Amplified in fast-break heavy games where putback and transition rebound opportunities spike.",
        "magnitude": "A 10-missed-attempt swing in opponent field-goal misses translates to roughly 2.5–3.0 additional contested rebound opportunities for the primary rebounder, implying a directional 1.5–2.0 rebound shift at a stable box-out rate. This pool-driven variance component alone can account for the difference between a 6-rebound and 10-rebound game for a frontcourt starter.",
        "links": ["pace_amplified_variance", "usage_dependent_variance", "team_scoring_night_dispersion", "matchup_driven_output_swing"],
    },
    {
        "slug": "clutch_output_dispersion",
        "title": "Clutch Output Dispersion",
        "summary": "Captures the widened distribution of late-game output in high-leverage minutes where defensive intensity spikes, sample sizes collapse, and individual possessions carry outsized score impact, measured by the variance of points in clutch windows relative to per-minute base rates.",
        "stat_signature": "Points per clutch minute: standard deviation roughly 1.8–2.5x higher than non-clutch per-minute standard deviation for the same player. Clutch-window sample median per game: 3–7 minutes for primary scorers, yielding fewer than 8 possession touches on average — too few to smooth binomial shot variance. Make-or-miss on a single three-pointer in clutch time represents 3 points in a window where total output might span 0–9.",
        "mechanism": "Clutch minutes concentrate defensive attention on primary creators, raising shot difficulty and lowering make probability from baseline. With fewer total attempts and elevated defender quality, the Bernoulli variance per attempt is higher and attempts per minute are lower, jointly widening per-minute variance. Additionally, game-state context (foul-avoidance, time management) alters shot selection toward lower-variance options (free throws) or higher-variance options (contested threes) situationally.",
        "conditions": "Most pronounced for players whose team routes 80%+ of clutch possessions through a single creator, leaving little averaging across multiple scorers. Partially dampened when a team has a reliable free-throw draw sequence that systematically adds low-variance points in clutch windows.",
        "magnitude": "A player averaging 0.5 clutch-points-per-minute in regular flow may show a clutch per-minute standard deviation of 0.9–1.2, implying that on approximately 20% of clutch appearances their effective contribution is statistically indistinguishable from zero — with a similar probability of double their base rate.",
        "links": ["floor_ceiling_spread", "hot_cold_streak_clustering", "free_throw_rate_variability", "shooting_efficiency_volatility"],
    },
    {
        "slug": "shot_quality_noise_floor",
        "title": "Shot-Quality Noise Floor",
        "summary": "Captures irreducible make-or-miss variance that persists after controlling for shot location, contest level, and off-dribble count, representing the minimum achievable game-level efficiency dispersion given the player's shot diet.",
        "stat_signature": "The noise floor is estimated as the standard deviation of game-level actual eFG% minus expected eFG% (residual efficiency). League-wide, this residual standard deviation is 9–13 percentage points per game for volume scorers. The theoretical minimum — achievable with a perfectly predictable expected-FG model and large game samples — would be near 6–8 pp; empirical residuals consistently exceed this, implying permanent unexplained make-or-miss variance.",
        "mechanism": "Identical shot types at identical locations have non-zero empirical miss probability variance because micro-variables (exact release timing, momentary balance, finger placement, contest angle within zone) are unmodeled. This granular mechanical noise is irreducible from the perspective of any zone-level or contest-level model and sets a floor below which efficiency volatility cannot fall regardless of role stability or scheme certainty.",
        "conditions": "The noise floor is highest for mid-range pull-up attempts and step-back threes, where the make probability distribution is widest within the location zone. Lowest for uncontested corner threes and free throws, where environmental control is highest and expected-FG models are most precise.",
        "magnitude": "A residual eFG% standard deviation of 10 pp means that even a perfectly calibrated shot-quality model, applied to a scorer attempting 15 shots per game, will produce game-level scoring predictions with an irreducible RMSE contribution of approximately 3 points purely from shot-quality noise floor — a hard lower bound on any scoring prediction model.",
        "links": ["shooting_efficiency_volatility", "three_point_volume_variance", "boom_bust_scoring_distribution", "assist_dependency_variance"],
    },
    {
        "slug": "role_stability_variance_link",
        "title": "Role-Stability Variance Link",
        "summary": "Captures how fluid offensive roles within a lineup raise output unpredictability by altering touches, shot-type mix, and usage share across games, measured by the variance of touches and shot-attempt type distribution and its coupling to scoring dispersion.",
        "stat_signature": "Touch-count CV across games: below 0.18 for players in stable defined roles; above 0.30 for players whose role shifts with lineup context. The slope of game-scoring standard deviation regressed on within-season touch-count standard deviation is approximately 1.1 to 1.4 points of scoring standard deviation per additional touch of touch-count standard deviation.",
        "mechanism": "When a player's offensive role varies — moving from primary ball-handler to off-ball cutter depending on which lineup is deployed — their possession allocation fluctuates. This upstream role ambiguity creates correlated variance in both volume and efficiency, since role determines shot quality. A player who sometimes operates as a spot-up shooter and sometimes as a pick-and-roll initiator inherits the variance of switching between two distinct shot-quality distributions.",
        "conditions": "Most pronounced for versatile secondary creators who slot into multiple lineup archetypes depending on who is available. Least pronounced for one-dimensional specialists (pure shooters, pure rim runners) whose function is fixed regardless of lineup context. Amplified during injury-coverage stretches when primary role assignments cascade down the rotation.",
        "magnitude": "Moving from a touch-count CV of 0.18 to 0.32 across a season (a common shift when a secondary creator covers for an injured primary) associates with an increase of approximately 2.5–3.5 points in per-game scoring standard deviation, independent of the change in mean output.",
        "links": ["usage_dependent_variance", "minutes_volatility_carryover", "bench_scoring_unreliability", "boom_bust_scoring_distribution"],
    },
    {
        "slug": "minutes_volatility_carryover",
        "title": "Minutes Volatility Carryover",
        "summary": "Captures how unstable playing time from foul trouble, blowout rotations, and lineup experimentation propagates directly into counting-stat variance, measured by per-player minutes standard deviation and its correlation with per-game output standard deviation.",
        "stat_signature": "Minutes standard deviation for rotation players: 3–6 minutes per game is typical; above 7 minutes indicates high instability. Correlation between per-player minutes standard deviation and per-game scoring standard deviation: approximately +0.65 to +0.75. A 1-minute increase in minutes standard deviation associates with roughly 0.7–1.0 additional points of scoring standard deviation.",
        "mechanism": "Most counting statistics (points, rebounds, assists) scale near-linearly with minutes in competitive contexts. When minutes fluctuate, the linear scaling propagates directly into output variance even if per-minute efficiency is stable. Foul trouble introduces nonlinearity: early foul stints reduce total minutes while creating bench intervals that reset rhythm, generating output distributions more extreme than pure minute-scaling predicts.",
        "conditions": "Dominant source of variance for 6th-to-9th rotation players whose minutes depend heavily on game script and opponent matchup decisions. Less impactful for starters who maintain 30–36 minutes in almost all competitive games. High-foul-frequency players experience the largest minutes-carryover effect.",
        "magnitude": "A player whose minutes standard deviation drops from 8 to 4 (due to a coaching role stabilization) typically sees per-game scoring standard deviation shrink by 3–5 points — one of the largest single-factor variance-reduction levers observable within a season.",
        "links": ["role_stability_variance_link", "garbage_time_variance_inflation", "usage_dependent_variance", "bench_scoring_unreliability"],
    },
]
