"""scripts.platformkit.specs.workloadfatigue_nba — WorkloadFatigue concepts for NBA."""
from __future__ import annotations

SPORT = "NBA"
FAMILY = "WorkloadFatigue"

CONCEPTS = [
    {
        "slug": "acute_chronic_minutes_ratio",
        "title": "Acute-to-Chronic Minutes Workload Ratio",
        "summary": "The ratio of rolling 7-day minutes to the 28-day chronic baseline encodes whether a recent spike has outpaced adaptation. Ratios above 1.3 mark a stress zone; above 1.5 soft-tissue breakdown hazard rises roughly 2-3x.",
        "stat_signature": "AC-ratio = 7d_min / 28d_min. Stable zone 0.8-1.2. Spike zone >1.3. Injury-report appearances at >1.5 run ~2.4x the stable-load base rate.",
        "mechanism": "Muscle-tendon units adapt over weeks; a sudden week-over-week spike exceeds adaptive capacity, compounding micro-damage rather than repairing it before each successive game.",
        "conditions": "Most predictive after an absence followed by heavy-minute return, or during compressed schedules where rest intervals cannot absorb accumulated load.",
        "magnitude": "Spike from AC-ratio 1.0 to 1.5 is associated with roughly 2-3x soft-tissue incident probability and 5-9% per-game efficiency decline within the spike window.",
        "links": ["back_to_back_recovery_deficit", "load_spike_soft_tissue_risk", "minutes_density_compression_fatigue", "cumulative_minutes_integral"],
    },
    {
        "slug": "cumulative_minutes_integral",
        "title": "Season Cumulative Minutes Integral",
        "summary": "The running season-total minutes accumulation is a dose counter: each added thousand minutes shifts the late-season efficiency and availability baseline downward via irreversible fatigue that within-week rest cannot fully reverse.",
        "stat_signature": "Efficiency drag appears near 1,800-2,000 cumulative minutes. Beyond 2,400 minutes, per-game efficiency loss versus season mean widens to 3-6% on average and missed-game probability rises 10-15%.",
        "mechanism": "Cartilage, tendon, and neuromuscular systems absorb cumulative micro-stress that only partially clears between games; beyond a biological dose ceiling the deficit accumulates monotonically.",
        "conditions": "Most consequential for high-minute starters in deep playoff runs or compressed regular-season schedules. Less predictive for role-players with per-game ceilings below 28 minutes.",
        "magnitude": "Starters crossing 2,400 regular-season minutes show 3-5% true-shooting decline and 10-15% higher missed-game probability in the final month versus their early-season baseline.",
        "links": ["acute_chronic_minutes_ratio", "age_load_tolerance_decline", "minutes_per_game_burn_rate", "load_management_rest_dosing"],
    },
    {
        "slug": "back_to_back_recovery_deficit",
        "title": "Consecutive-Night Recovery Deficit Magnitude",
        "summary": "Playing within 24 hours of the prior game leaves a measurable physiological deficit — reduced vertical, shorter sprint distance, and compressed late-game efficiency — distinct from travel or time-zone effects.",
        "stat_signature": "Second-night starters average 1.5-2.5 fewer points and 0.4-0.8 fewer rebounds. Pull-up field-goal percentage drops ~2-3 points. Foul rate rises ~15% as fatigued defenders resort to reach-in fouls.",
        "mechanism": "Lactate clearance, glycogen resynthesis, and CNS repair require 36-48h for full restoration. A 24h window allows only partial repair; residual fatigue selectively degrades explosive actions and fine motor control.",
        "conditions": "Largest for starters logging over 32 minutes in the first game. Worsened when the back-to-back includes cross-timezone travel. Attenuated when the first game ended in an early blowout exit.",
        "magnitude": "High-minute starters show 8-12% mean output reduction on zero-days rest; downside tail widens by 2-3 counting-stat units versus a rested baseline.",
        "links": ["acute_chronic_minutes_ratio", "minutes_per_game_burn_rate", "travel_recovery_kinetics", "sleep_debt_road_accumulation"],
    },
    {
        "slug": "recovery_halflife_between_games",
        "title": "Between-Game Recovery Half-Life",
        "summary": "Physiological readiness restores along an exponential curve after high-load games. The empirical half-life is near 18-22 hours, meaning full restoration to baseline requires roughly 36-44h — well beyond a 24h back-to-back window.",
        "stat_signature": "R(t) = 1 - deficit * exp(-t / tau), tau ~20h. At 24h rest, residual deficit is ~30% of initial. At 48h it falls below 10%. Shooting accuracy correlates r ~0.35 with hours-since-last-game for starters above 32 MPG.",
        "mechanism": "CNS fatigue is the slowest-recovering process, setting the effective overall half-life and governing fine motor skill recovery that underpins shooting mechanics and defensive reaction speed.",
        "conditions": "Most consequential when the next game arrives under 36h rest. Half-life lengthens with age and cumulative seasonal load; shortens for players with strong aerobic base.",
        "magnitude": "Each additional rest day up to two days restores roughly 30% of the prior-game deficit; three or more rest days yield diminishing gains and approach full physiological baseline.",
        "links": ["back_to_back_recovery_deficit", "sleep_debt_road_accumulation", "travel_recovery_kinetics", "age_load_tolerance_decline"],
    },
    {
        "slug": "sleep_debt_road_accumulation",
        "title": "Sleep-Debt Accumulation on Road Swings",
        "summary": "Multi-game road trips accumulate compounding sleep deficit from late arrivals and hotel environments. Each hour of debt degrades reaction-time-sensitive tasks — contested shooting, off-ball defense, transition decisions — at a measurable dose-linked rate.",
        "stat_signature": "Post-11pm local-arrival games: next-day three-point accuracy down ~1.5-2.5 points. Road swings of 4+ games in 6 nights show defensive-rating deterioration of 2-4 points by games 3-4 relative to the trip opener.",
        "mechanism": "Sleep deprivation impairs prefrontal function and elevates cortisol, which impairs muscle repair. The effect compounds because road schedules rarely allow extended sleep periods that would clear accumulated debt.",
        "conditions": "Largest for teams with back-to-back road games spanning multiple time zones. Attenuated for squads with charter travel and structured recovery protocols.",
        "magnitude": "A 4-game road swing in 6 nights is associated with roughly 3-5% offensive efficiency decline by the final game and 1.8-2.5 defensive-rating erosion relative to the trip opener.",
        "links": ["travel_recovery_kinetics", "back_to_back_recovery_deficit", "recovery_halflife_between_games", "minutes_density_compression_fatigue"],
    },
    {
        "slug": "load_spike_soft_tissue_risk",
        "title": "Load-Spike Soft-Tissue Injury Risk",
        "summary": "An abrupt workload spike — AC-ratio above 1.4, or a return from absence into heavy minutes — elevates hamstring, calf, and groin strain incidence by 2-3x relative to stable-load conditions, creating a predictable hazard window of 1-3 weeks.",
        "stat_signature": "Injury incidence per 1,000 player-games: ~4-6 at AC-ratio 0.9-1.1; rises to 10-15 at AC-ratio >1.4. Return-from-absence games carry a 48-72h elevated hazard window regardless of stated readiness.",
        "mechanism": "Muscle-tendon units lose tensile strength during de-load periods; re-loading before full tensile recovery creates a mismatch between demand and structural capacity, especially during explosive sprint, cut, and landing actions.",
        "conditions": "Peak hazard in the first 3-5 games after an absence, immediately following a statistical outlier in minutes, and during dense schedules that do not permit AC-ratio normalization between spikes.",
        "magnitude": "A spike above AC-ratio 1.5 carries roughly 2-3x injury hazard multiplier; the two-week post-spike window accounts for a disproportionate share of non-contact soft-tissue incidents.",
        "links": ["acute_chronic_minutes_ratio", "load_management_rest_dosing", "vacated_minutes_load_redistribution", "in_season_conditioning_base"],
    },
    {
        "slug": "load_management_rest_dosing",
        "title": "Planned Load-Management Rest Dosing",
        "summary": "Pre-emptive game or minutes omissions strategically cap chronic load for high-mileage veterans. The dose — games sat per 10-game block and minutes budget per heavy stretch — calibrates readiness for target games and extends effective season availability.",
        "stat_signature": "High-mileage veterans often sit 2-4 games per 20-game block once cumulative load crosses 1,500 minutes. Performance in managed target games following 2+ rest days shows a 4-8% efficiency lift versus fatigue-matched baseline.",
        "mechanism": "Strategic rest allows glycogen resynthesis, CNS restoration, and connective tissue repair to complete deliberately rather than reactively, preserving readiness for high-leverage games at lower injury probability.",
        "conditions": "Applied when cumulative minutes cross risk thresholds, during compressed regular-season stretches, or following high-intensity back-to-back road segments. Decision criteria weight game stakes, opponent difficulty, and current AC-ratio.",
        "magnitude": "Proper load management reduces missed-game-to-injury probability roughly 30-40% in the protected block; managed-game readiness is measurably higher than non-managed peers at equivalent season minute totals.",
        "links": ["cumulative_minutes_integral", "acute_chronic_minutes_ratio", "age_load_tolerance_decline", "load_spike_soft_tissue_risk"],
    },
    {
        "slug": "age_load_tolerance_decline",
        "title": "Age-Driven Load Tolerance Decline",
        "summary": "Recovery capacity and load tolerance decline with player age: older cohorts show steeper post-heavy-game efficiency drops, slower readiness rebounds, and lower injury-free minute ceilings, each quantifiable as an age-slope on load-outcome regressions.",
        "stat_signature": "Post back-to-back efficiency decline: ~4% at age 24-26; ~9% at 30-32; ~14% at 34+. Cumulative minute ceiling before efficiency drag appears falls roughly 100-150 minutes per year after age 30.",
        "mechanism": "Satellite cell density, mitochondrial efficiency, and hormonal anabolic signaling all decline with age, reducing muscle repair and glycogen resynthesis rates. CNS recovery half-life lengthens approximately 2-3h per year past age 28.",
        "conditions": "Most pronounced above age 30 with high historic cumulative-minute totals. Partially offset by superior conditioning, reduced per-minute intensity roles, and larger aerobic baseline.",
        "magnitude": "A 34-year-old high-minute starter loses roughly 1.5x the efficiency of a 26-year-old per unit of accumulated season load; optimal per-game minute ceiling is ~4-6 minutes lower at equivalent fitness.",
        "links": ["cumulative_minutes_integral", "load_management_rest_dosing", "recovery_halflife_between_games", "in_season_conditioning_base"],
    },
    {
        "slug": "vacated_minutes_load_redistribution",
        "title": "Vacated-Minutes Load Redistribution",
        "summary": "When a rotation member misses games, the vacated minutes redistribute onto remaining players, creating an AC-ratio spike for the absorbers with a predictable foul-rate inflation and efficiency drag across the absence window.",
        "stat_signature": "A 30-minute absence redistributed across 3 players adds ~10 minutes each. Absorbing players show a 12-18% rise in personal foul rate and a 5-8% efficiency decline by game 3 of the absence.",
        "mechanism": "Players thrust into enlarged roles exhaust physical and cognitive reserves faster; the foul-rate rise reflects defensive fatigue causing reactive reach-in fouls, while efficiency falls as usage spikes above optimal range.",
        "conditions": "Most severe when the absence is unplanned and absorbers have no prior heavy-load adaptation. Mitigated when deep rotations spread redistribution across 5+ players, keeping individual increments modest.",
        "magnitude": "A single-player 30-minute redistribution across a shallow 3-player unit raises each absorber's load ~33%; after 3 games the compound fatigue drag reduces their combined output by roughly 8-12%.",
        "links": ["acute_chronic_minutes_ratio", "load_spike_soft_tissue_risk", "usage_fatigue_efficiency_tradeoff", "minutes_per_game_burn_rate"],
    },
    {
        "slug": "usage_fatigue_efficiency_tradeoff",
        "title": "Usage-Load Efficiency Tradeoff",
        "summary": "Heavy offensive usage compounds physical load beyond raw minutes; sustaining a high-usage role across consecutive heavy games drives a measurable decline in true-shooting and finishing rate as cognitive decision fatigue stacks on top of physical fatigue.",
        "stat_signature": "True-shooting in games 1-2 of a 3-game high-usage stretch: near season average. Games 3-4: down 2-3 points. Games 5+: down 4-6 points. Effect strongest above 28% usage where shot-creation complexity is highest.",
        "mechanism": "High usage forces late-shot-clock isolation creations that are physically demanding and cognitively taxing. Accumulated decision fatigue degrades shot selection quality while physical fatigue reduces the explosiveness enabling shot separation.",
        "conditions": "Peaks when the primary creator's co-star is absent and usage spikes to compensate. Also elevated in playoff series where defensive scouting forces harder creation angles game after game.",
        "magnitude": "A 5-game stretch of 30%+ usage with 34+ minutes per game reduces true-shooting by roughly 4-6 points versus the same player at 24-minute load; the compound penalty exceeds either factor alone.",
        "links": ["minutes_per_game_burn_rate", "vacated_minutes_load_redistribution", "cumulative_minutes_integral", "fourth_quarter_fatigue_shooting"],
    },
    {
        "slug": "fourth_quarter_fatigue_shooting",
        "title": "Late-Game Fatigue Shooting Decay",
        "summary": "Jump-shot accuracy and free-throw mechanics decline in the fourth quarter as accumulated game-load compounds; isolating this effect from defensive pressure reveals a true fatigue component that is stable across opponent quality levels.",
        "stat_signature": "Catch-and-shoot three-point percentage Q4 falls ~1.8-2.5 points below Q1 for starters logging 30+ minutes. Free-throw accuracy in Q4 clutch drops ~1.5 points below full-game average after controlling for contest rate.",
        "mechanism": "Fatigue-induced perturbations in biomechanics — reduced leg drive, altered release height, impaired proprioceptive feedback — systematically lower conversion probability. Free throws, lacking a defender, isolate the pure fatigue signal.",
        "conditions": "Most pronounced for players who played 30+ near-unbroken minutes. Diminished for players who received a meaningful Q3 rest stint restoring partial neuromuscular readiness before fourth-quarter deployment.",
        "magnitude": "A starter playing 32+ minutes shows roughly a 2-point true-shooting drop in Q4 relative to Q1-Q2 baseline, translating to approximately 0.8-1.2 fewer expected points per 10 attempts.",
        "links": ["third_quarter_workload_drag", "minutes_continuity_stint_length", "back_to_back_recovery_deficit", "neuromuscular_readiness_index"],
    },
    {
        "slug": "third_quarter_workload_drag",
        "title": "Cumulative In-Game Workload Drag",
        "summary": "Within-game performance decays as accumulated possessions rise; the third quarter traditionally shows the steepest individual efficiency trough because halftime only partially restores metabolic and neuromuscular systems before load re-accumulates.",
        "stat_signature": "League-wide offensive rating: Q1 ~110, Q2 ~107, Q3 ~104, Q4 ~108. High-minute starters show a Q3 trough 4-6 points below their Q1 baseline. True-shooting drops ~1.5-2.5 points from Q1 to Q3 for 30+ minute starters.",
        "mechanism": "Halftime glycogen resynthesis is incomplete after a heavy first half; returning to full effort re-accumulates fatigue rapidly. By mid-Q3 the cumulative game-load surpasses the threshold where per-possession output measurably declines.",
        "conditions": "Deepest for starters who play heavy Q1-Q2 minutes without a mid-half rest stint. Reduced when coaches proactively sub out key players for 4-5 minute Q2 rests, preserving output through Q3.",
        "magnitude": "The Q3 efficiency trough accounts for roughly 60-70% of a starter's within-game output variance across quarters; proactive rest reduces the trough by approximately 2-3 offensive-rating points.",
        "links": ["fourth_quarter_fatigue_shooting", "minutes_continuity_stint_length", "in_season_conditioning_base", "minutes_per_game_burn_rate"],
    },
    {
        "slug": "minutes_per_game_burn_rate",
        "title": "Per-Game Minutes Burn Rate",
        "summary": "Average and peak per-game minutes quantify instantaneous load intensity: a 38-minute night taxes recovery systems differently than the same weekly total spread thinly, because deep-fatigue onset is non-linear above roughly 34 minutes.",
        "stat_signature": "Season average MPG > 34 signals high-intensity burn. Peak nights >38 min create a 12-18h recovery debt not cleared by a single rest day. MPG variance (CV > 0.15) further destabilizes recovery by preventing consistent adaptation.",
        "mechanism": "Glycogen depletion and neuromuscular fatigue accumulate non-linearly with stint length. Beyond 34 continuous or near-continuous game-minutes, marginal recovery cost per additional minute rises sharply.",
        "conditions": "Highest impact when heavy individual nights cluster with short inter-game rest. Diminished for players with low-intensity movement profiles whose per-minute metabolic cost is structurally lower.",
        "magnitude": "A 38-minute game followed by 1-day rest reduces next-game output roughly 4-7% on average; consecutive 36-plus-minute nights widen efficiency drag to 8-12% by the second back-to-back.",
        "links": ["back_to_back_recovery_deficit", "minutes_continuity_stint_length", "cumulative_minutes_integral", "acute_chronic_minutes_ratio"],
    },
    {
        "slug": "travel_recovery_kinetics",
        "title": "Post-Travel Physiological Recovery Kinetics",
        "summary": "Air travel and time-zone crossing impose a physiological cost distinct from game-load fatigue: circadian misalignment, dehydration, and postural immobility each impair neuromuscular readiness on an independent recovery curve that persists beyond game-day warm-up.",
        "stat_signature": "A 3-hour eastward zone shift produces measurable performance effects lasting roughly 3 days. Reaction-time degradation on game day after a 3-hour+ eastward shift is approximately 5-12ms, translating to slower defensive close-outs and first-step reads.",
        "mechanism": "Circadian disruption misaligns cortisol and melatonin peaks with game-time demands; dehydration from low-humidity cabin air reduces plasma volume and muscular efficiency; sedentary flight time stagnates lactic acid clearance.",
        "conditions": "Highest impact for red-eye flights landing within 12h of tip-off, for eastward travel crossing 3+ time zones, and during seasons with many cross-country trips compressed into short windows.",
        "magnitude": "A single cross-country eastward red-eye is associated with roughly 5-8% efficiency decline on game day; effects largely clear by the second game on the same trip once circadian rhythm begins adjusting.",
        "links": ["sleep_debt_road_accumulation", "back_to_back_recovery_deficit", "recovery_halflife_between_games", "minutes_density_compression_fatigue"],
    },
    {
        "slug": "minutes_density_compression_fatigue",
        "title": "Compressed-Schedule Cumulative Load Fatigue",
        "summary": "Dense game blocks — 4 games in 5 nights or 3 in 3 — accumulate fatigue at a rate outpacing between-game recovery, producing a widening readiness deficit that grows monotonically across the block and only partially clears at block's end.",
        "stat_signature": "Teams in a 4-in-5 block show net-rating decline of 2-4 points by game 4 relative to game 1. Starter efficiency metrics show monotonic decline of 1-2 points per game across the block.",
        "mechanism": "Each game's net recovery in a compressed block is negative: the rest interval restores less than the game depletes. The shortfall accumulates additively, leaving the team measurably more fatigued at each successive tip-off.",
        "conditions": "Most severe when the dense block includes an embedded back-to-back, when travel accompanies each night, and when the block arrives late in a month already heavy on total game count.",
        "magnitude": "A 4-in-5 block reduces effective team net rating by 2-4 points across the block versus a well-spaced equivalent schedule — comparable to resting a starter for one full game.",
        "links": ["acute_chronic_minutes_ratio", "sleep_debt_road_accumulation", "back_to_back_recovery_deficit", "recovery_halflife_between_games"],
    },
    {
        "slug": "minutes_continuity_stint_length",
        "title": "Continuous-Stint Length Without Rest",
        "summary": "Uninterrupted on-court stints beyond roughly 8 minutes accumulate local muscle fatigue that degrades shooting mechanics, defensive close-out speed, and decision-making quality within the final possessions of the stint.",
        "stat_signature": "Three-point percentage in stints 1-5 min: ~37%; 6-9 min: ~34%; 10+ min: ~31%. Free-throw accuracy in the closing minute of long stints drops ~2 points. Defensive contest speed on pull-up attempts falls measurably after 8 unbroken minutes.",
        "mechanism": "Local phosphocreatine reserves deplete within 8-10 seconds of maximal sprint; repeated efforts across an unbroken 10-minute stint progressively reduce peak power output while CO2 and lactate accumulation impair fine motor control for shooting mechanics.",
        "conditions": "Most severe for high-usage scorers and perimeter defenders who make repeated high-intensity movements. Attenuated for low-movement floor-spacers who stay in aerobic zones across long stints.",
        "magnitude": "A 12-minute unbroken stint degrades per-possession efficiency roughly 3-5% versus a fresh re-entry after a 2-minute rest; effect accumulates across successive long stints within the same game.",
        "links": ["third_quarter_workload_drag", "fourth_quarter_fatigue_shooting", "minutes_per_game_burn_rate", "in_season_conditioning_base"],
    },
    {
        "slug": "neuromuscular_readiness_index",
        "title": "Neuromuscular Readiness Composite",
        "summary": "A composite readiness index synthesizing jump-load proxies, reactive-strength estimates, and movement-economy signals tracks how far daily neuromuscular readiness sits below personal baseline before tip-off, quantifying the starting deficit before in-game fatigue accumulates.",
        "stat_signature": "Readiness index as percentage of 30-day rolling baseline. Below 85% signals meaningful impairment; below 75% signals severe deficit. Correlated with same-game true-shooting (r ~0.30) and sprint-distance (r ~0.35) from wearable data proxies.",
        "mechanism": "Neuromuscular fatigue is the rate-limiting constraint for explosive actions. When the index falls below baseline, peak force production, reactive strength, and movement economy all decline proportionally, reducing the quality ceiling on every high-intensity game action.",
        "conditions": "Most informative after high-load multi-day blocks, at the tail of long road swings, and for players with historically volatile readiness profiles. Less predictive for players whose conditioning maintains the index near 95%+ even during dense schedules.",
        "magnitude": "A readiness index 15 points below baseline is associated with roughly 5-8% efficiency decline in high-intensity actions; indices below 75% correspond to near-certain observable performance degradation and elevated injury risk.",
        "links": ["fourth_quarter_fatigue_shooting", "in_season_conditioning_base", "recovery_halflife_between_games", "acute_chronic_minutes_ratio"],
    },
    {
        "slug": "in_season_conditioning_base",
        "title": "Conditioning Base and Fatigue Resistance",
        "summary": "Aerobic and neuromuscular conditioning level sets how slowly a player fatigues under a given load. A higher conditioning base flattens within-game and across-week efficiency decay curves, measured by the relative flatness of per-possession output across game segments.",
        "stat_signature": "Well-conditioned players show Q3 efficiency within 2 points of Q1 baseline; poorly conditioned players show Q3 deficits of 5-8 points. Correlation between conditioning proxy (low-minute decay slope) and injury-rate: r ~-0.30 after controlling for load.",
        "mechanism": "Superior aerobic conditioning raises the lactate threshold, allowing more possessions at aerobic intensities before anaerobic fatigue accumulates. Higher mitochondrial density enables faster lactate clearance between explosive actions, compressing recovery debt per sprint.",
        "conditions": "Conditioning base declines during extended absences (measurable de-training begins within 7-10 days) and rises during training camp. Mid-season maintenance is most visible in the games immediately after a 2-week injury absence.",
        "magnitude": "A well-conditioned player sustains roughly 85-90% of their Q1 efficiency through Q3; a poorly conditioned peer at equivalent load falls to 75-80% — a gap of 5-8 efficiency points that compounds across a 7-game playoff series.",
        "links": ["neuromuscular_readiness_index", "age_load_tolerance_decline", "minutes_continuity_stint_length", "cumulative_minutes_integral"],
    },
]
