"""Spec: Soccer / WorkloadFatigue — person-free concept nodes for the brain."""
from __future__ import annotations

SPORT = "Soccer"
FAMILY = "WorkloadFatigue"

CONCEPTS = [
    {
        "slug": "total_distance_match_load",
        "title": "Total Distance Covered Match Load",
        "summary": "Per-match total distance (typically 10-13 km for outfield roles) quantifies the baseline aerobic dose. Accumulation across successive matches without adequate rest compresses aerobic capacity and depresses subsequent high-intensity output.",
        "stat_signature": "Total distance per 90 min; rolling 7-day sum >22 km flags elevated load. A >8 % drop below personal 28-day mean in a back-to-back fixture signals suppressed aerobic reserve.",
        "mechanism": "Sustained aerobic work depletes glycogen and elevates creatine kinase. Without 48-72 hours of reduced load, glycogen resynthesis is incomplete and the aerobic system enters the next fixture below functional threshold.",
        "conditions": "Most evident across mid-week plus weekend double-gameweeks and European competition windows; amplified in roles covering full channel widths such as wide midfielders and wing-backs.",
        "magnitude": "A 28-day rolling accumulation >90 km correlates with a 15-20 % reduction in high-intensity distance in the fourth match of a congested block relative to a rested baseline.",
        "links": ["high_intensity_sprint_load", "fixture_congestion_cumulative_load", "minutes_load_rolling_window", "position_specific_running_demand"],
    },
    {
        "slug": "high_intensity_sprint_load",
        "title": "High-Intensity Running and Sprint Load",
        "summary": "Distance above 19.8 km/h (high-speed running) and above 25.2 km/h (sprinting), plus sprint count, constitute the metabolically costly dose most predictive of hamstring-strain risk and residual fatigue entering the next match.",
        "stat_signature": "HSR distance per 90 min: 600-900 m for wide roles, 300-500 m for central defenders. Sprint count >25 per 90 min is a high-load threshold. HSR-to-sprint ratio >0.04 sprints/m flags disproportionate maximal-speed stress.",
        "mechanism": "Eccentric loading during deceleration from maximum velocity causes type-II muscle-fibre micro-damage. Incomplete repair within a short turnaround yields reduced peak force and elevated hamstring-injury hazard in the subsequent fixture.",
        "conditions": "Manifests most sharply after transitional, counter-attacking matches with high open-space distances; less prominent in low-block, possession-heavy games where sprints are fewer and shorter.",
        "magnitude": "Players completing >850 m HSR in match N show an average 12 % sprint-count reduction in match N+1 when turnaround is under 72 hours, versus no measurable deficit with 96+ hour recovery.",
        "links": ["total_distance_match_load", "two_day_recovery_insufficiency", "accelerations_decelerations_mechanical_load", "minutes_overload_injury_risk"],
    },
    {
        "slug": "acute_chronic_workload_ratio",
        "title": "Acute-to-Chronic Training-and-Match Load Ratio",
        "summary": "The 7-day acute load divided by the 28-day chronic baseline measures preparedness relative to conditioning. Ratios of 0.8-1.3 are associated with low injury incidence; spikes beyond 1.3-1.5 mark a load acceleration linked to non-contact injury risk.",
        "stat_signature": "ACWR = (7-day load) / (28-day load / 4). ACWR >1.3 is associated with 2-3x elevated injury odds; <0.8 indicates under-readiness. Load unit: session RPE × duration or GPS PlayerLoad.",
        "mechanism": "A rapid load spike outpaces musculoskeletal adaptation; tendons and ligaments remodel more slowly than aerobic capacity, so a training acceleration the cardio system tolerates still overstresses connective tissue.",
        "conditions": "Elevated ACWR clusters at pre-season intensification, returns from injury, and post-international-break reintegration when club training loads ramp sharply after a rest trough.",
        "magnitude": "ACWR >1.5 is associated with roughly 3-4x non-contact injury hazard relative to the 0.8-1.3 optimal band across multiple professional soccer squad studies.",
        "links": ["total_distance_match_load", "fixture_congestion_cumulative_load", "preseason_conditioning_base", "training_load_match_carryover"],
    },
    {
        "slug": "accelerations_decelerations_mechanical_load",
        "title": "Acceleration and Deceleration Mechanical Load",
        "summary": "Count of explosive accelerations (>3 m/s²) and decelerations (<-3 m/s²) constitutes a mechanical-stress dose independent of distance, driving muscular micro-damage and neuromuscular fatigue distinct from the aerobic cost captured by total distance.",
        "stat_signature": "High-intensity acceleration+deceleration count per 90 min: 80-140 for wide roles, 50-90 for centre-backs. Sum >120 events at >3 m/s² flags elevated mechanical load; deceleration-to-acceleration ratio >1.2 indicates disproportionate eccentric stress.",
        "mechanism": "Rapid deceleration generates high eccentric quadriceps and hamstring forces that damage sarcomere structure independent of speed zone. Accumulated deceleration load depresses reactive-strength index and countermovement jump height.",
        "conditions": "Highest in pressing-intensive, high-defensive-line systems requiring frequent chase-and-recover cycles; also elevated in set-piece-heavy matches with many restarts generating short explosive bursts.",
        "magnitude": "Sessions accumulating >130 high-intensity deceleration events correlate with a 10-15 % drop in countermovement jump peak force the following morning, recovering to baseline within 48-72 hours.",
        "links": ["high_intensity_sprint_load", "neuromuscular_fatigue_readiness", "second_half_fatigue_decay", "position_specific_running_demand"],
    },
    {
        "slug": "fixture_congestion_cumulative_load",
        "title": "Fixture-Congestion Cumulative Load",
        "summary": "Three or more competitive matches within a rolling 10-day window creates a load-accumulation regime where recovery deficits compound across fixtures, producing measurable decline in late-match running output by the third consecutive game.",
        "stat_signature": "Matches per 14 days >=4 defines severe congestion. Cumulative HSR across the block versus seasonal per-match mean; a >15 % drop in the final match of a 3-in-7-day run signals accumulation. Individual minutes >300 per 14 days flags critical personal load.",
        "mechanism": "Each match imposes a 48-72-hour glycogen and muscle-damage recovery debt. When inter-match rest falls below this threshold repeatedly, debts compound: each subsequent game starts with lower glycogen and elevated creatine kinase.",
        "conditions": "Characteristic of European competition months, winter cup periods, and post-postponement schedule compression; severity amplified when the block follows an international break with residual travel fatigue.",
        "magnitude": "High-intensity distance in the third match of a congested 3-in-7-day block is typically 10-18 % below the uncongested-week squad mean, with pressing actions falling 20-25 % in the final 20 minutes.",
        "links": ["total_distance_match_load", "two_day_recovery_insufficiency", "minutes_load_rolling_window", "rotation_load_sharing", "extra_time_attrition_load"],
    },
    {
        "slug": "two_day_recovery_insufficiency",
        "title": "Sub-72-Hour Recovery Insufficiency",
        "summary": "Playing a competitive fixture fewer than 72 hours after the previous match creates a physiological deficit: creatine kinase has not normalised, glycogen resynthesis is 60-80 % complete, and sprint capacity is measurably suppressed versus a 96-hour baseline.",
        "stat_signature": "Turnaround <72 hours: sprint count falls 8-14 % and HSR distance falls 6-10 % relative to same-player 96-hour-turnaround matches. Plasma CK remains 3-4x resting baseline at 48 hours post-match for high-load players.",
        "mechanism": "Muscle-damage repair and glycogen resynthesis are time-dependent. CK normalisation requires 72-96 hours; incomplete normalisation at kickoff means residual sarcomere disruption reduces peak contractile force throughout the fixture.",
        "conditions": "Mid-week cup ties followed by weekend league fixtures; knockout ties with extra time tightening the gap further; particularly acute where extra-time amplifies the preceding match-load debt.",
        "magnitude": "Sprint peak velocity reduced roughly 2-4 % at 48 hours post-match; HSR-distance deficit of 8-14 % versus a rested baseline, with wide midfielders and forwards showing the largest decrement.",
        "links": ["high_intensity_sprint_load", "recovery_kinetics_creatine_kinase", "fixture_congestion_cumulative_load", "extra_time_attrition_load"],
    },
    {
        "slug": "minutes_load_rolling_window",
        "title": "Rolling Minutes-Load Accumulation",
        "summary": "Cumulative competitive minutes over rolling 7-day and 28-day windows serve as a workload accumulator. High 28-day values suppress late-match running economy, while a spike in the 7-day window relative to the 28-day baseline predicts acute fatigue.",
        "stat_signature": "7-day minutes >180 (two full matches) flags acute overload. 28-day minutes >630 indicates sustained congestion. Late-match HSR distance (minutes 75-90) as a fraction of first-half output below 0.70 signals within-block fatigue.",
        "mechanism": "Competitive minutes aggregate all match stressors; sustained high totals prevent full tissue repair and CNS recovery. The 7-day-to-28-day ratio above 1.35 replicates the ACWR danger-zone mechanism applied specifically to competitive minutes.",
        "conditions": "Most relevant for first-choice starters playing close to full minutes in every fixture during congested periods, particularly central midfielders and key attackers whose early substitution is tactically resisted.",
        "magnitude": "Players in the top decile of 28-day minutes (>680 per 28 days) show a statistically significant 12 % depression in HSR distance in the final 15 minutes compared to players in the median band.",
        "links": ["fixture_congestion_cumulative_load", "rotation_load_sharing", "substitution_load_management", "second_half_fatigue_decay"],
    },
    {
        "slug": "recovery_kinetics_creatine_kinase",
        "title": "Post-Match Recovery Kinetics",
        "summary": "After a high-load match, muscle-damage markers follow a predictable multi-day curve: creatine kinase peaks at 24-48 hours, normalises by 72-96 hours, while neuromuscular function lags slightly behind biochemical markers.",
        "stat_signature": "CK normalisation: within 1.5x resting baseline by 72 hours after a low-load match, 96-120 hours after a high-sprint fixture. CMJ height restoration: ~90 % of baseline by 48 hours, ~99 % by 96 hours. Residual deficit at 48-hour turnaround: roughly 5-8 %.",
        "mechanism": "Eccentric muscle actions disrupt Z-discs, releasing CK into plasma; the inflammatory cascade peaks at 24-48 hours and subsides as satellite cells regenerate damaged fibres. This timeline is non-compressible through passive rest alone.",
        "conditions": "Recovery curves are steeper after high-sprint, high-deceleration matches; slower in older players, at high altitude, and in players returning from prior muscle injury. Nutrition and hydration modulate but do not shorten the 72-hour floor.",
        "magnitude": "At a 48-hour turnaround, average residual CK of 2-3x resting baseline corresponds to measurable peak-force reductions of 5-8 % and sprint-velocity reductions of 2-4 %.",
        "links": ["two_day_recovery_insufficiency", "neuromuscular_fatigue_readiness", "high_intensity_sprint_load", "travel_recovery_compounding"],
    },
    {
        "slug": "travel_recovery_compounding",
        "title": "Travel-Compounded Recovery Burden",
        "summary": "Long-haul travel and time-zone crossing add a readiness deficit on top of the match-load recovery curve. A transmeridian journey of four or more time zones degrades sleep quality, disrupts circadian rhythms, and depresses neuromuscular function for 1-3 days beyond the normal match-load window.",
        "stat_signature": "Flights >4 hours or >2 time-zone shifts before competition: sprint-count decrement of 6-10 % versus home-fixture baseline. Subjective wellness scores fall 15-20 % in the first 24 hours post-long-haul arrival.",
        "mechanism": "Circadian disruption suppresses melatonin, elevates cortisol, and fragments sleep architecture. Degraded sleep extends the match-load recovery timeline by roughly 12-24 additional hours per two-hour time-zone shift, compounding onto the existing recovery debt.",
        "conditions": "International competition windows, inter-continental tournaments, and continental cup fixtures requiring east-west travel exceeding four time zones. Eastward travel produces greater disruption than equivalent westward travel.",
        "magnitude": "Transmeridian travel of 4+ time zones followed by a match within 36 hours is associated with a 5-9 % reduction in HSR distance and a 10-15 % reduction in sprint count relative to home-rest-baseline.",
        "links": ["recovery_kinetics_creatine_kinase", "international_break_load_spike", "two_day_recovery_insufficiency", "neuromuscular_fatigue_readiness"],
    },
    {
        "slug": "rotation_load_sharing",
        "title": "Squad-Rotation Load Sharing",
        "summary": "Rotating the starting lineup across congested fixtures distributes cumulative load across the squad, reducing any individual player's rolling minutes and preserving readiness. The depth of rotation quality available constrains how effectively load can be spread.",
        "stat_signature": "Squads using 16+ distinct starters across a 4-match congested block show 15-20 % higher late-match HSR in the final fixture compared to squads using 13 or fewer. Individual rolling 14-day minutes fall below the 270-minute overload threshold with rotation of three or more positions per match.",
        "mechanism": "Each match not started reduces a player's rolling acute load, keeping individual ACWR in the low-risk band. The aggregated squad effect sustains collective high-intensity output because no player carries a fatigue-suppressed movement profile.",
        "conditions": "Requires sufficient squad depth and competitive quality across positions. Most effective when bench quality in a given position is within 10-15 % of the first-choice performer on key output metrics.",
        "magnitude": "Rotating at least three positions per match across a congested 4-game block is associated with a 12-18 % reduction in total squad HSR distance lost to fatigue versus a near-fixed lineup.",
        "links": ["fixture_congestion_cumulative_load", "minutes_load_rolling_window", "substitution_load_management", "minutes_overload_injury_risk"],
    },
    {
        "slug": "second_half_fatigue_decay",
        "title": "Within-Match Second-Half Fatigue Decay",
        "summary": "High-intensity distance and sprint count decline progressively across a match, with the steepest drop between the 60th and 90th minute. This within-match decay is a universal feature of elite soccer physiology, amplified by pre-match fatigue, heat, and fixture congestion.",
        "stat_signature": "Typical within-match decay: HSR distance drops 15-25 % from the opening 15-minute segment to the final segment. Sprint count in minutes 75-90 averages 60-70 % of the first segment. Decay rate is measurably steeper in the second match of a back-to-back.",
        "mechanism": "Progressive glycogen depletion reduces type-II fibre recruitment capacity. PCr resynthesis during brief recovery intervals becomes incomplete as intramuscular pH falls, creating the characteristic neuromuscular fade visible in running-output metrics.",
        "conditions": "Steepest in high-intensity counter-pressing systems where early-match sprint and deceleration loads are heaviest; amplified in warm ambient conditions (>22 °C) and in the third match of a congested block.",
        "magnitude": "Average HSR distance in minutes 75-90 is 18-22 % below the opening segment in a rested squad; this gap widens to 28-35 % in the third match of a congested 3-in-7-day block.",
        "links": ["late_match_pressing_dropoff", "fixture_congestion_cumulative_load", "minutes_load_rolling_window", "neuromuscular_fatigue_readiness"],
    },
    {
        "slug": "late_match_pressing_dropoff",
        "title": "Late-Match Pressing-Intensity Dropoff",
        "summary": "Collective pressing actions — pressures applied, counterpresses initiated, and recovery-run completion rate — decline materially after the 70th minute due to accumulated neuromuscular fatigue, producing tactical compactness loss and elevated defensive exposure.",
        "stat_signature": "Pressures per minute of possession fall 20-30 % from the 60-75 min bin to the 75-90 bin. Counterpress success rate (ball-recovery within 5 seconds of loss) drops 15-25 % in the final 20 minutes. PPDA rises 10-20 % after minute 70.",
        "mechanism": "Pressing requires repeated short-burst sprints and rapid directional changes. Type-II fibre fatigue from accumulated deceleration load reduces each player's initiation capacity; compactness degrades as slowest recoverers open gaps, undermining the coordinated press.",
        "conditions": "Most pronounced in teams sustaining a high-intensity, high-line press for the full match. Amplified after the second consecutive congested fixture, where pre-match fatigue advances the onset of pressing dropoff to around the 55th minute.",
        "magnitude": "PPDA in the final 20 minutes of the third match in a congested block is typically 25-35 % higher (worse) than the first-match-of-block baseline, indicating a near-complete loss of effective pressing shape.",
        "links": ["second_half_fatigue_decay", "fixture_congestion_cumulative_load", "accelerations_decelerations_mechanical_load", "extra_time_attrition_load"],
    },
    {
        "slug": "extra_time_attrition_load",
        "title": "Extra-Time Attrition Load",
        "summary": "Thirty minutes of knockout extra time adds roughly 25-35 % to the match-load dose, pushing total sprint and deceleration counts well above the standard 90-minute ceiling and imposing a disproportionate recovery cost on the subsequent fixture.",
        "stat_signature": "Extra-time matches add 2-3 km total distance and 100-200 m HSR on top of 90-minute totals. Cramp incidence rises from ~2 % in normal time to 8-12 % in extra time. Recovery to readiness baseline takes 24-36 additional hours versus a standard match.",
        "mechanism": "Extra time is played in a near-fully glycogen-depleted state; the body shifts toward fat oxidation and protein catabolism, producing greater muscle-damage markers than equivalent distance covered early in a match. Extended deceleration volume adds eccentric stress to already-compromised fibres.",
        "conditions": "Exclusive to knockout competition formats. Penalty shootout following extra time adds minor physical but measurable psychological stress, elevating cortisol and disrupting post-match sleep for 24-48 hours.",
        "magnitude": "Recovery to 95 % neuromuscular readiness requires 96-120 hours after extra time versus 72-96 hours after a standard match; players from an extra-time fixture show 15-25 % lower sprint counts in a subsequent league match within a 72-hour window.",
        "links": ["two_day_recovery_insufficiency", "recovery_kinetics_creatine_kinase", "fixture_congestion_cumulative_load", "late_match_pressing_dropoff"],
    },
    {
        "slug": "minutes_overload_injury_risk",
        "title": "Minutes-Overload Injury Hazard",
        "summary": "Players carrying sustained heavy minute loads across a congested stretch show elevated non-contact soft-tissue injury hazard, expressed as injury incidence per high-load player-match relative to a rested baseline cohort.",
        "stat_signature": "Hazard ratio for non-contact injury doubles at >270 competitive minutes per rolling 14 days. Hamstring-strain incidence rises from ~0.5 per 1,000 player-hours at rest to 1.5-2.5 per 1,000 player-hours after three consecutive full matches within 10 days.",
        "mechanism": "Repeated high-speed running without full recovery leaves residual micro-damage in hamstring and adductor musculature. Reduced peak-force capacity under fatigue alters biomechanical loading at the myotendinous junction, increasing strain probability during maximal-velocity actions.",
        "conditions": "Risk is highest in players with prior soft-tissue injury history, older players (>28 years) with slower repair kinetics, and wide-role players whose positional demand involves the highest sprint volumes and eccentric loading cycles.",
        "magnitude": "Non-contact injury incidence in the third match of a 3-in-10-day block is 2-3x the single-match baseline; the elevated hazard is concentrated in minutes 60-90 when cumulative fatigue is highest.",
        "links": ["high_intensity_sprint_load", "acute_chronic_workload_ratio", "fixture_congestion_cumulative_load", "rotation_load_sharing"],
    },
    {
        "slug": "preseason_conditioning_base",
        "title": "Preseason Conditioning Base and Load Capacity",
        "summary": "The aerobic and musculoskeletal conditioning base built in preseason sets each player's in-season load tolerance, modulating within-match decay curve steepness and the speed of recovery kinetics across congested blocks.",
        "stat_signature": "Players completing >250 km in a full 8-week preseason show 10-15 % flatter within-match decay curves in the early season versus players completing <180 km. Full-preseason squads sustain ACWR in the 0.9-1.1 sweet spot through the first six competitive weeks.",
        "mechanism": "High preseason volume increases mitochondrial density, capillary supply, and glycogen storage capacity, raising the absolute workload that triggers fatigue onset. A broader conditioning base also increases tendon stiffness and bone mineral density, raising injury-risk thresholds.",
        "conditions": "Players returning late from international duty, post-injury, or with shortened pre-season windows carry a reduced base into the season, making them vulnerable to early-season congestion and acute load spikes.",
        "magnitude": "A full versus abbreviated (<4 weeks) preseason is associated with a 20-30 % difference in the number of congested weeks before within-match HSR decay exceeds the 20 % fatigue threshold.",
        "links": ["acute_chronic_workload_ratio", "total_distance_match_load", "training_load_match_carryover", "second_half_fatigue_decay"],
    },
    {
        "slug": "neuromuscular_fatigue_readiness",
        "title": "Neuromuscular Fatigue and Readiness Index",
        "summary": "A readiness composite from countermovement jump height, reactive-strength index, and subjective wellness scores tracks how far daily neuromuscular function sits below personal baseline, integrating all stressors — match load, travel, sleep, and training — into a pre-kickoff readiness estimate.",
        "stat_signature": "CMJ height <90 % of 28-day personal mean flags impaired readiness. RSI (jump height / ground-contact time) <0.85 of baseline is the applied threshold. Composite wellness score <15/25 (fatigue + sleep + soreness + mood) flags elevated performance-decrement risk.",
        "mechanism": "Neuromuscular fatigue reflects impairment of the contractile apparatus and CNS drive. Jump metrics require maximal voluntary activation, making them sensitive proxies for residual muscle-damage and neuro-inhibition that subjective self-report can underestimate.",
        "conditions": "Most informative as a daily morning measurement taken 18-24 hours before kickoff after a congested block; rolling trends across 3-5 days reliably distinguish genuine fatigue from transient variation.",
        "magnitude": "Players entering a match with CMJ height at <90 % of personal baseline show sprint-count reductions of 8-12 % and HSR-distance reductions of 10-14 % versus matches entered at >97 % baseline readiness.",
        "links": ["recovery_kinetics_creatine_kinase", "accelerations_decelerations_mechanical_load", "travel_recovery_compounding", "second_half_fatigue_decay"],
    },
    {
        "slug": "international_break_load_spike",
        "title": "International-Window Load and Travel Spike",
        "summary": "A midweek international duty window inserts a load and travel spike into the club calendar; players return carrying a cumulative fatigue and circadian-disruption burden that elevates soft-tissue risk and depresses high-intensity output in the first post-break club fixture.",
        "stat_signature": "Players completing two international matches plus long-haul travel (>4 h each way) within a 10-day window show 10-15 % lower HSR distance in the first post-break club match. ACWR spikes above 1.4 are common for regulars who had a full rest period at club before the window.",
        "mechanism": "International fixtures compound travel fatigue, circadian disruption, and the acute match load, while the prior rest at club level has reduced the chronic baseline, creating a disproportionate ACWR spike on return to the demanding club fixture schedule.",
        "conditions": "Most acute for players selected for both qualifiers or friendlies in the window with transcontinental travel. Less pronounced for players based near the national team venue or those managing limited minutes in one fixture.",
        "magnitude": "The first post-international-break club match carries a soft-tissue injury incidence roughly 1.5-2x the non-break baseline, with the elevated risk persisting into the second fixture if turnaround is under 72 hours.",
        "links": ["travel_recovery_compounding", "acute_chronic_workload_ratio", "minutes_overload_injury_risk", "two_day_recovery_insufficiency"],
    },
    {
        "slug": "substitution_load_management",
        "title": "Substitution-Driven Load Capping",
        "summary": "Using substitutions to cap a player's match minutes manages cumulative load during congested periods, reducing each individual's rolling high-intensity totals and the readiness deficit carried into subsequent fixtures.",
        "stat_signature": "Removing a player at minute 60-70 versus playing the full 90 minutes reduces per-match HSR contribution by 20-30 % and deceleration count by 18-25 %. Across a 4-match congested block, consistent early substitution keeps individual 14-day minutes below the 270-minute overload threshold.",
        "mechanism": "Each additional minute in the 70-90-minute range delivers diminishing physical output but accumulates disproportionate fatigue cost, as the player is operating in a glycogen-depleted, high-CK state. Early removal prevents the final-phase fatigue dose while sacrificing minimal match contribution.",
        "conditions": "Most effective when applied proactively to players already in a high-load rolling window rather than reactively after visible fatigue signs. Requires tactical substitutes capable of sustaining the system's high-intensity demands.",
        "magnitude": "Consistent minute-capping (exit at 65-70 min) across a 4-game congested block reduces cumulative 28-day HSR distance by 15-20 % relative to the same player playing the full 90 minutes in all four fixtures.",
        "links": ["minutes_load_rolling_window", "rotation_load_sharing", "fixture_congestion_cumulative_load", "second_half_fatigue_decay"],
    },
    {
        "slug": "training_load_match_carryover",
        "title": "Training-Load to Match Carryover",
        "summary": "The prior training-week load carries over into match-day readiness: a high-volume training block in the days before a fixture depresses match-day high-intensity output and extends post-match recovery, while a tapered week enhances readiness.",
        "stat_signature": "Training load in the 72-hour window before match day: session RPE × minutes >500 AU flags a high-carryover risk. Players with a high-load training 48-72 hours pre-match show 8-12 % lower match-day sprint counts. A tapered (<200 AU) pre-match week is associated with 5-8 % higher HSR distance.",
        "mechanism": "Residual neuromuscular fatigue from training accumulates on the same kinetic curve as match fatigue; incomplete CK normalisation and glycogen depletion from hard training sessions enter the match-load calculation, compounding the cumulative fatigue state.",
        "conditions": "Most consequential during congested schedules where training days between matches are limited and coaches must choose between maintaining fitness and ensuring match-day readiness; the balance shifts toward tapering as congestion deepens.",
        "magnitude": "Tapering training load by 40-50 % in the 48-72 hours before a match is associated with a 5-8 % improvement in match-day HSR distance and a 10-15 % reduction in post-match recovery time to 95 % readiness.",
        "links": ["acute_chronic_workload_ratio", "preseason_conditioning_base", "neuromuscular_fatigue_readiness", "total_distance_match_load"],
    },
]
