"""Tennis / ZoneControl — person-free concept nodes (brain expansion).
Describes how players claim, hold, and exploit court-position territory.
All fields are DESCRIPTIVE; no edge / ROI / pick claims; markets efficient.
"""
from __future__ import annotations

SPORT  = "Tennis"
FAMILY = "ZoneControl"

CONCEPTS: list[dict] = [
    {
        "slug": "baseline_territory_command",
        "title": "Baseline-Territory Command",
        "summary": "Share of rally balls struck on or inside the baseline (positive contact-depth differential per rally); sustaining on-baseline position compresses opponent response time and limits their angle options.",
        "stat_signature": "Contact depth <= 0 m on >= 55 % of groundstrokes = offensive command; rally-win rate 12-18 pp higher than from > 1 m behind baseline.",
        "mechanism": "Earlier contact shortens opponent flight time and raises exit ball speed, narrowing recovery windows cumulatively across multi-ball sequences.",
        "conditions": "Most pronounced on medium-paced hard and clay; high-topspin patterns that allow taking the ball on the rise amplify the effect.",
        "magnitude": "Holding on-baseline contact throughout a rally associates with a 15-20 pp rally-win lift, largest in 5-9 shot exchanges.",
        "links": ["court_position_depth_control", "defensive_baseline_retreat_zone", "serve_plus_one_court_control", "first_strike_court_seizure"],
    },
    {
        "slug": "court_position_depth_control",
        "title": "Court-Position Depth and Contact-Point Control",
        "summary": "Average contact-point distance behind the baseline and its correlation with rally-winning probability; players under 0.8 m generate structurally superior outcomes across surfaces.",
        "stat_signature": "Contact depth < 0.8 m = offensive tier; > 2.0 m = defensive tier; rally-win probability rises ~2 pp per 0.3 m of forward gain at equal ball quality.",
        "mechanism": "Forward contact redirects opponent pace without generating it, reducing energy cost while increasing ball velocity; also opens more acute angles from shorter net distances.",
        "conditions": "Most measurable on clay and medium hard courts where rally length is sufficient; kick serves that push returners back create the deepest defensive contact depths.",
        "magnitude": "A 1 m contact-depth differential in exchange associates with a 10-15 pp rally-win advantage for the shallower-contact player, compounding across sequences.",
        "links": ["baseline_territory_command", "short_ball_attack_territory", "defensive_baseline_retreat_zone", "open_court_exploitation_geometry"],
    },
    {
        "slug": "net_approach_territory_seizure",
        "title": "Net-Approach Territory Seizure",
        "summary": "Advancing into forecourt territory to finish points; measured by approach frequency and point-won rate at net (62-74 % for proficient volleyers) against passing-shot exposure accepted.",
        "stat_signature": "Net-approach rate >= 15 % of points = net-oriented profile; point-won-at-net >= 65 % indicates effective conversion; passing-winner rate conceded >= 30 % signals cost.",
        "mechanism": "Net occupation cuts the passing corridor to ~30 % of baseline width; combined with forward momentum the first volley becomes a short-angle put-away.",
        "conditions": "Most effective after a forcing ball that pushes opponent wide or low; tactically optimal on faster surfaces where passing execution time is compressed.",
        "magnitude": "Proficient net players win 10-15 pp more points at net than baseline; approach attempts carry a 5-8 pp break-point risk premium on clay.",
        "links": ["short_ball_attack_territory", "drop_shot_forecourt_zone", "lob_backcourt_territory_reclaim", "no_mans_land_transition_zone"],
    },
    {
        "slug": "no_mans_land_transition_zone",
        "title": "No-Man's-Land Transition-Zone Exposure",
        "summary": "Disadvantage of being caught in mid-court (inside service line, behind net); the most error-prone positional state in professional rallies due to structural half-volley geometry.",
        "stat_signature": "Balls struck from 1-6 m behind the net carry ~2x the unforced-error rate of baseline averages; half-volley frequency from this zone exceeds 40 %.",
        "mechanism": "Ball descends through the hitting window at knee-to-hip height requiring a high-to-low swing that limits pace/spin, while the net height compresses the safe-landing target area.",
        "conditions": "Peaks during misfire approach sequences that stop the split-step too early, and after defensive lobs that die short; opponents target feet of advancing players with dipping topspin.",
        "magnitude": "Points containing transition-zone contact see error rates rise 15-25 pp versus purely baseline exchanges; both players in the zone simultaneously doubles error rate.",
        "links": ["net_approach_territory_seizure", "short_ball_attack_territory", "drop_shot_forecourt_zone", "defensive_baseline_retreat_zone"],
    },
    {
        "slug": "court_geometry_angle_creation",
        "title": "Court-Geometry Angle-Creation Control",
        "summary": "Use of court width to open diagonal space; measured by cross-court departure angle and the sideline displacement forced on the opponent per angled ball.",
        "stat_signature": "Departure angle > 28 degrees from net-post axis correlates with opponent recovery distance > 4 m; angle-creation frequency >= 20 % defines an angle-dominant pattern.",
        "mechanism": "Each additional degree widens required opponent coverage ~0.15 m at baseline; accumulated across a rally the displacement eventually exceeds recovery capacity.",
        "conditions": "Most effective after pulling the opponent to one sideline; clay amplifies angle-shot counts due to slower pace and higher bounces extending rally length.",
        "magnitude": "Consecutive angle balls > 28 degrees force recovery sprints averaging 0.3-0.7 m beyond optimal bisector; after two such balls the coverage deficit exceeds 1.5 m.",
        "links": ["open_court_exploitation_geometry", "center_baseline_anchor_control", "wide_serve_court_opening", "backhand_corner_territory_targeting"],
    },
    {
        "slug": "center_baseline_anchor_control",
        "title": "Center-Baseline Anchor and Recovery Control",
        "summary": "Ability to hold the geometric center behind the baseline between shots; recovery-to-bisector completion rate is the prerequisite for sustainable neutral-ball construction.",
        "stat_signature": "Bisector-recovery completion >= 80 % between shots = disciplined anchor; drop below 60 % raises opponent open-court placement rate 15-20 pp.",
        "mechanism": "The geometric bisector minimises maximum distance to any opponent target; deviation of 1 m expands the unreachable court area ~15 %, opening a structural passing lane.",
        "conditions": "Critical in baseline exchanges with enough inter-shot interval for recovery; fast-court pace shrinks the recovery window and accumulates positional debt.",
        "magnitude": "Players recovering to bisector >= 80 % concede 10-15 pp fewer open-court winners than those averaging <= 60 %, largest in rallies of 7-plus shots.",
        "links": ["court_geometry_angle_creation", "defensive_baseline_retreat_zone", "open_court_exploitation_geometry", "baseline_territory_command"],
    },
    {
        "slug": "serve_plus_one_court_control",
        "title": "Serve-Plus-One Court-Position Control",
        "summary": "Seizing central court on the first ball after the serve; the plus-one forehand from advanced position is the primary offensive pivot in contemporary baseline serving patterns.",
        "stat_signature": "Plus-one forehand from inside or on the baseline on >= 40 % of first-serve points = active profile; point-won rate 58-65 % at professional level versus 46-52 % from behind baseline.",
        "mechanism": "Wide or T serve displaces returner laterally; server recovers to center and the return arrives in the strike zone for an inside-out or inside-in forehand during returner reposition.",
        "conditions": "Most effective when serve lands in outer third of service box; deuce-court wide serves set up inside-out forehands most reliably; suppressed by chip returns that neutralise pace.",
        "magnitude": "Successful serve-plus-one sequences raise hold probability 8-12 pp relative to neutral-serve-then-neutral-rally, largest on first serves in the 115-125 mph range.",
        "links": ["wide_serve_court_opening", "deuce_court_territory_pattern", "ad_court_territory_pattern", "first_strike_court_seizure"],
    },
    {
        "slug": "return_position_depth_territory",
        "title": "Return-Position Depth-Territory Choice",
        "summary": "How far behind or inside the baseline a returner stands and the territory it claims; return-contact depth encodes a tactical philosophy that constrains every subsequent ball in the point.",
        "stat_signature": "Return contact inside baseline (< 0 m) on first serves < 15 % for most returners but delivers 12-18 pp higher point-won rate; contact > 3 m behind drops point-won rate 8-12 pp versus 0-1 m.",
        "mechanism": "Standing inside baseline halves server's reaction time to the return, denying plus-one setup; deep positioning trades that pressure for reaction time but cedes territory to recapture.",
        "conditions": "Deep positioning dominant against heavy first-serve pace on fast surfaces; aggressive inside-baseline returning favoured on clay and against second serves.",
        "magnitude": "A 1 m forward shift in return position correlates with 4-6 pp gain on second-serve returns and 2-3 pp on manageable first serves, offset by 3-5 pp higher error rate against kickers.",
        "links": ["ad_court_territory_pattern", "deuce_court_territory_pattern", "baseline_territory_command", "serve_plus_one_court_control"],
    },
    {
        "slug": "backhand_corner_territory_targeting",
        "title": "Backhand-Corner Territory Targeting",
        "summary": "Sustained attack on the opponent's backhand-corner real estate; systematic backhand loading is a foundational pattern in baseline-dominant tactical structures.",
        "stat_signature": "Rally ball to backhand third >= 55 % = loading pattern; opponent forced-error rate from backhand corner 18-24 % on clay versus 10-13 % from the forehand corner.",
        "mechanism": "Consistent loading prevents opponents from running around to the forehand, forces two-handed stretch shots, and creates angle debt — each wide backhand must redirect through a narrowing window.",
        "conditions": "Most effective against opponents with lower ball-speed output on the backhand; on high-spin clay the corner targeting compounds as the ball kicks above comfortable contact height.",
        "magnitude": "Sustained backhand loading across 6-plus shot rallies raises opponent error rate 6-10 pp; the displacement opens the forehand court for a decisive redirect on ~1 in 4 sequences.",
        "links": ["court_geometry_angle_creation", "open_court_exploitation_geometry", "ad_court_territory_pattern", "down_the_line_lane_control"],
    },
    {
        "slug": "deuce_court_territory_pattern",
        "title": "Deuce-Court Territorial Patterning",
        "summary": "Directional control of play to the deuce side; measured by deuce-court serve-and-rally placement frequency and the wide-versus-T split that stretches returner coverage.",
        "stat_signature": "Wide serve to deuce ad-side returns 40-55 % point-won when landing in outer 20 cm of box; T serve to deuce court generates 8-12 % higher body-ball follow-up rate.",
        "mechanism": "Deuce-court patterns exploit the forehand-backhand transition; a wide deuce serve pulls returner off court, exposing the entire open ad court for the plus-one.",
        "conditions": "Right-handed servers deploy the deuce-wide combination most frequently as it aligns with the forehand plus-one; kick serves to the T on the deuce side attack the backhand on second serves.",
        "magnitude": "Deuce-court wide serve combined with inside-out plus-one produces a point-won rate 10-14 pp above neutral serve-and-rally at professional level.",
        "links": ["serve_plus_one_court_control", "wide_serve_court_opening", "ad_court_territory_pattern", "return_position_depth_territory"],
    },
    {
        "slug": "ad_court_territory_pattern",
        "title": "Ad-Court Territorial Patterning",
        "summary": "Directional control of play to the advantage side; measured by ad-court placement frequency and the wide-swing serve territory exploited against the backhand-return corner.",
        "stat_signature": "Ad-court wide serve ace rate 4-7 % higher than T on that side for right-handers serving to left-handers' backhand; ad-court serving dictates the rally opening direction on 60-70 % of points.",
        "mechanism": "The ad-wide serve pulls the returner's backhand to the extreme corner; a chip or defensive return lands centrally, enabling the server to control the next-ball direction.",
        "conditions": "Most decisive against opponents with a weaker backhand-return from the ad court; second-serve placement to the ad-wide location sacrifices speed for positioning leverage.",
        "magnitude": "Consistent ad-court wide-serve patterns that generate short or central returns produce a net territorial advantage on 50-60 % of ad-court points played.",
        "links": ["deuce_court_territory_pattern", "backhand_corner_territory_targeting", "serve_plus_one_court_control", "return_position_depth_territory"],
    },
    {
        "slug": "wide_serve_court_opening",
        "title": "Wide-Serve Court-Opening Control",
        "summary": "Pulling the returner off court with a wide serve to seize the exposed open territory; the primary mechanism for instant court-geometry manipulation in professional serving patterns.",
        "stat_signature": "Wide serve landing in outer 20 cm returns 40-55 % point-won; when resulting return is weak or central, plus-one point-won jumps to 60-68 %; ace/service-winner rate 5-8 pp above T on deuce side.",
        "mechanism": "Displacement > 1.5 m from centre mark forces recovery outside the doubles alley; the diagonal recovery path takes 0.4-0.8 s longer than the server's lateral repositioning, making the open-court ball uncoverable.",
        "conditions": "Most decisive on fast hard and grass where return quality is suppressed; on clay the higher bounce allows a lifted defensive return that partially compensates for displacement.",
        "magnitude": "When wide serve forces returner beyond the singles sideline, the plus-one is finished for winner or forced error on ~45-55 % of such exchanges at professional level.",
        "links": ["serve_plus_one_court_control", "deuce_court_territory_pattern", "court_geometry_angle_creation", "open_court_exploitation_geometry"],
    },
    {
        "slug": "down_the_line_lane_control",
        "title": "Down-the-Line Lane Control",
        "summary": "Command of the higher-risk straight lane to change rally direction; winner-to-error ratio on down-the-line attempts signals whether the lane is an asset or liability in rally structure.",
        "stat_signature": "Down-the-line frequency >= 20 % = active straight-lane threat; winner-to-error ratio >= 1.4 = effective control; below 0.8 the attempt is a net liability.",
        "mechanism": "Down-the-line balls travel 1-2 m shorter court distance than cross-court equivalents, compressing opponent reaction time and forcing coverage of both lanes simultaneously.",
        "conditions": "Deployed after a wide cross-court ball pushes opponent wide; most effective from inside baseline where flat trajectory is achievable; from deep baseline the thin net-clearance margin raises errors.",
        "magnitude": "A credible down-the-line threat (ratio >= 1.0) broadens required opponent coverage ~20-30 %, measurably reducing ability to anticipate and cheat toward the higher-probability cross-court lane.",
        "links": ["backhand_corner_territory_targeting", "court_geometry_angle_creation", "open_court_exploitation_geometry", "baseline_territory_command"],
    },
    {
        "slug": "short_ball_attack_territory",
        "title": "Short-Ball Attack-Territory Conversion",
        "summary": "Seizing advanced court territory when a short ball lands; short-ball recognition and immediate commitment is the primary transition trigger in baseline patterns.",
        "stat_signature": "Short ball = opponent groundstroke landing inside service line; advance-and-attack rate >= 70 % on recognised short balls = aggressive profile; point-won 62-71 % inside baseline versus 48-54 % pushed back.",
        "mechanism": "Short ball arrives at a height and depth allowing the striker to close net while swinging through, converting defensive error into immediate forecourt position from which passing-shot angle narrows.",
        "conditions": "Most decisive after depth-pressure forces a defensive reply; clay generates more short balls per rally than hard courts due to higher topspin and fatigue-induced depth errors.",
        "magnitude": "Players attacking >= 70 % of short balls earn rally-win rates 15-20 pp higher; the attack option also deters opponents from manufacturing short balls tactically.",
        "links": ["net_approach_territory_seizure", "no_mans_land_transition_zone", "court_position_depth_control", "mid_court_sitter_zone_control"],
    },
    {
        "slug": "lob_backcourt_territory_reclaim",
        "title": "Lob and Backcourt-Territory Reclaim",
        "summary": "Using the lob to push a net-occupying opponent back and reclaim baseline territory; the primary counter-measure that limits the structural value of net approaches.",
        "stat_signature": "Defensive lob success rate >= 60 % (not retrieved for winner) = effective lobbing; topspin lob landing in 0-1 m inside opponent baseline achieves territory-reset on ~55-65 % of executions.",
        "mechanism": "A well-placed lob forces the net-player to retreat at full sprint tracking an overhead; smash from behind the service line is physically demanding, and the lobber recovers to bisector for a rally reset.",
        "conditions": "Most effective on clay and slow hard courts where overhead finishing is harder; on grass the low bounce makes the lob trajectory predictable and overhead finishing more reliable for the net player.",
        "magnitude": "Effective lobbing reduces opponent net-approach point-won rate 8-12 pp and discourages approach frequency ~20 %, a significant structural shift in the rally-territory balance.",
        "links": ["net_approach_territory_seizure", "no_mans_land_transition_zone", "drop_shot_forecourt_zone", "defensive_baseline_retreat_zone"],
    },
    {
        "slug": "first_strike_court_seizure",
        "title": "First-Strike Court-Seizure Tendency",
        "summary": "Pattern of dictating court position within the first 3-4 shots of a rally; first-strike dominance compresses the opponent's decision tree before the exchange reaches neutral territory.",
        "stat_signature": "Positive court-position differential on shots 2-3 at a rate >= 50 % = first-strike dominant; these players win 65-72 % of rallies in <= 4 shots versus 48-55 % in 8-plus shot rallies.",
        "mechanism": "Early-rally territorial control forces the opponent onto a reactive path; each defensive ball cedes contact-point advantage the aggressive player exploits with shorter swing and higher exit speed.",
        "conditions": "Particularly effective after a serve generating a weak or short return; on clay the first-strike window is harder to sustain and territorial equity often re-establishes by shot 5.",
        "magnitude": "First-strike dominant players win ~6-10 pp more points in 1-4 shot rallies than tactically neutral peers; total match uplift is diluted by the share of rallies escaping the early window.",
        "links": ["serve_plus_one_court_control", "baseline_territory_command", "wide_serve_court_opening", "short_ball_attack_territory"],
    },
    {
        "slug": "open_court_exploitation_geometry",
        "title": "Open-Court Exploitation Geometry",
        "summary": "Conversion of a displaced opponent into a finishing strike to the vacated territory; the terminal phase of most angle-creation rally patterns, where territory accumulated becomes points converted.",
        "stat_signature": "Open-court recognition rate >= 65 % when opponent is displaced >= 2 m from center = high exploitation; winner-plus-forced-error rate on true open-court balls 52-62 % at professional level.",
        "mechanism": "Displaced opponent must cover 2-4 m extra; the finish ball to the open court is decision-free — no angle creation needed, only adequate pace and depth into the gap.",
        "conditions": "Requires the preceding sequence to have generated genuine displacement; most accessible after a wide angle ball or a wide serve the returner barely reaches; clay reduces winner conversion due to higher defensive recovery speed.",
        "magnitude": "True open-court finish balls (opponent >= 3 m from center) convert to winners or forced errors at 55-65 % on hard and 40-50 % on clay; remaining 35-45 % typically produce short replies enabling a second-opportunity finish.",
        "links": ["court_geometry_angle_creation", "down_the_line_lane_control", "backhand_corner_territory_targeting", "wide_serve_court_opening"],
    },
    {
        "slug": "mid_court_sitter_zone_control",
        "title": "Mid-Court Sitter-Zone Conversion Control",
        "summary": "Command of the put-away territory when a ball sits up in the mid-court; sitter-attack rate and point-won conversion are the clearest measures of a player's ability to capitalise on opponent errors.",
        "stat_signature": "Mid-court sitter = ball landing inside service line above net height; aggression rate >= 80 % on recognised sitters = effective control; point-won 67-75 % aggressively attacked versus 52-60 % pushed conservatively.",
        "mechanism": "A mid-court ball above net height allows downward ball flight into the court near net; opponent is retreating or off-balance; the striker can choose any target quadrant — failing to accelerate is a structural inefficiency.",
        "conditions": "Sitter opportunities arise after defensive or over-hit balls; more common after drop-shot exchanges, half-volley errors, and fatigue-induced depth errors; clay generates mid-court floaters more frequently due to spin dynamics.",
        "magnitude": "Gap between aggressive (>= 80 %) and conservative (<= 50 %) sitter-attack rates corresponds to a 12-18 pp point-won difference; across a match the cumulative differential represents 2-4 service or return games.",
        "links": ["short_ball_attack_territory", "net_approach_territory_seizure", "open_court_exploitation_geometry", "no_mans_land_transition_zone"],
    },
]
